### ISSUE TITLE
Host bug

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1014]
Hi

When I put an Host Device, GNS3 says : "No server available" (Title of window : "Node creation")

**Comment by noplay** [comment]
Do you have the local server enabled?

**Comment by Raizo62** [comment]
Yes, Local Server is enabled.
and, I can use others devices.

**Comment by noplay** [comment]
Could you use Help / Export debug informations and send me the zip to julien@gns3.net?

Thanks for the help

**Comment by noplay** [comment]
Ok the problem is when you have no remote and disable the GNS3 VM.

**Comment by noplay** [comment]
Thanks a lot this regression is fixed.
