### ISSUE TITLE
bug with network cards showed by IOU

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1015]
I put several VirtualBox connected at an IOU (switch).
I start all devices

Then the IOU becomes  "crazy" and shows more network cards than really.

(edit : snapshot not necessary to show the bug)

**Comment by noplay** [comment]
Where do you see the networks cards? Why do you think IOU become crazy? The CPU is at 100%?

**Comment by Raizo62** [comment]
sorry, not crazy. 
GNS3 shows more network card to this device.

**Comment by noplay** [comment]
When you use the link tool? Can you share a screenshot?

**Comment by Raizo62** [comment]
Yes, i use the link tool.

![2016-02-09-172257_1280x1024_scrot](https://cloud.githubusercontent.com/assets/7449584/12922483/9cb70fce-cf49-11e5-9fd9-e5f0a0e9017e.png)

**Comment by grossmj** [comment]
Indeed seems to be a bug somewhere. Do you confirm you only have 16 interfaces inside IOU (on the command line)?

Thanks,

**Comment by noplay** [comment]
It seem the same issues as topology corruption seen in #992

**Comment by Raizo62** [comment]
@grossmj : "show ip interface brief" show 16 interfaces.

info : I have the same bug if i replace VBox by VPCS

**Comment by grossmj** [comment]
Nope, nothing to do with topology corruption. Just drag & drop an IOU on the scene, then start it and the tooltip shows a duplicated list of the interfaces.

**Comment by grossmj** [comment]
Starting the device also duplicate it in the topology summary. Something is definitely wrong and comes from https://github.com/GNS3/gns3-gui/blob/master/gns3/vm.py#L164

Why are we calling this in the start?

**Comment by noplay** [comment]
It's how we received the command line. But it should be update callback I
think

**Comment by noplay** [comment]
Probably the root of most issues, I forgot that we have two methods one for update and one for setup. And that you can't just call setup everytime.

**Comment by noplay** [comment]
Should be fixed thanks for the report
