### ISSUE TITLE
GNS3 VM not detected with VMware

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1019]
Still the same issues....
https://gns3.com/qa/gns3-vm-not-detected-in-v1-4

**Comment by ColdIce1** [comment]
I am able to reproduce this bug.

**Comment by grossmj** [comment]
Well I should have fixed that after 1.4.1 with https://github.com/GNS3/gns3-gui/commit/9bde5fcad6b25918f527cff2c1d73741d0a7be6b

**Comment by grossmj** [comment]
Also, forcing the host type in GNS3 preferences -> VMware before using the wizard should solve the issue.
