### ISSUE TITLE
console VPCS

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1023]
(re)Hi

I put an vpcs and ethernet switch on topology. I connect them.

I start them
I can open console of vpcs. no problem.

I close console of vpcs.
I open console of vpcs. I don't have the prompt.

I must restart vpcs to open console correctly

**Comment by noplay** [comment]
Hi,

When I reopen the console I need to press enter to see the prompt. It's doesn't work for you? 

Which version of VPCS is used? 0.6.1?

Which terminal are you using?

**Comment by Raizo62** [comment]
No, press enter doesn't work.

I use VPCS version 0.8b from VPCS/sourceforge (Build time : yesterday)

terminal is xterm

**Comment by noplay** [comment]
Yeah VPCS 0.8b is not very good.

Did you try with:
https://sourceforge.net/projects/vpcs/files/0.8/vpcs-0.8-src.tbz/download

At this time GNS3 keep the 0.6.1 version.

**Comment by Raizo62** [comment]
I will try this evening

> At this time GNS3 keep the 0.6.1 version.
I only follow your advice : "This is not the official VPCS repository and it will not be updated anymore. The latest VPCS release can be downloaded from http://sourceforge.net/projects/vpcs/files/" ;-)

**Comment by Raizo62** [comment]
> Did you try with:
> https://sourceforge.net/projects/vpcs/files/0.8/vpcs-0.8-src.tbz/download

I tried it. This doesn't work :-(
(But this code shows the number version "0.8b")

**Comment by noplay** [comment]
The only solution i see is to disallow vpcs 0.8

**Comment by Raizo62** [comment]
or to signal the bug to vpcs's team ;-)
it is the the better solution, i think

**Comment by noplay** [comment]
We reported it, it should be fixed in the svn.

**Comment by noplay** [comment]
I found in my email from the VPCS author that this should work with 0.8b

**Comment by Raizo62** [comment]
I don't understand.

It doesn't work with me. I use the code in the tab "code" of sourceforge .(https://sourceforge.net/p/vpcs/code/HEAD/tree/trunk/)
And also, I tried your link

Does it work with you ?

**Comment by noplay** [comment]
From SVN yes

```
  ./vpcs

Welcome to Virtual PC Simulator, version 0.8b
Dedicated to Daling.
Build time: Feb 17 2016 18:57:06
Copyright (c) 2007-2015, Paul Meng (mirnshi@gmail.com)
All rights reserved.

VPCS is free software, distributed under the terms of the "BSD" licence.
Source code and license can be found at vpcs.sf.net.
For more information, please visit wiki.freecode.com.cn.

Press '?' to get help.
s
VPCS[1]> ssssss
Bad command: "ssssss". Use ? for help.

VPCS[1]> ssss
Bad command: "ssss". Use ? for help.

VPCS[1]> ip 192.168.1.1
Checking for duplicate address...
PC1 : 192.168.1.1 255.255.255.0

On Wed, Feb 17, 2016 at 5:24 PM Raizo62 <notifications@github.com> wrote:

> I don't understand.
>
> It doesn't work with me. I use the code in the tab "code" of sourceforge .(
> https://sourceforge.net/p/vpcs/code/HEAD/tree/trunk/)
> And also, I tried your link
>
> Does it work with you ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/1023#issuecomment-185282009>.
>

**Comment by Raizo62** [comment]
sorry, i don't understand your example.

vpcs works, but it doesn't work if i close console and open it again.

**Comment by noplay** [comment]
Sorry I confused with another issue.

**Comment by noplay** [comment]
It's a regression of 0.8

**Comment by noplay** [comment]
Mail send to VPCS author

**Comment by noplay** [comment]
The author of VPCS just fixed it

**Comment by noplay** [comment]
It's on the SVN

**Comment by SeeMyPing** [comment]
chmod +x your executable **vpcs_0.6_Linux64** and move it to **/usr/bin/vpcs**
> pls after download vpcs_0.6_Linux64 how to install it?

**Comment by msapaola** [comment]
Hi, i've download vpcs_0.8b_Linux64 how can i install it ? With kali linux

**Comment by msapaola** [comment]
Please
