### ISSUE TITLE
zipimport.ZipImportError: can't find module 'GNS3__main__'

### ISSUE THREAD

**Issue by gipmon** [GNS3/gns3-gui#1030]
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cx_Freeze-4.3.4-py3.5-macosx-10.9-x86_64.egg/cx_Freeze/initscripts/Console.py", line 26, in <module>
zipimport.ZipImportError: can't find module 'GNS3__main__'

**Comment by noplay** [comment]
Hi,

Are you using the dmg, or are you trying to run it from sources or from pip?

Have you try to redownload the DMG and to reinstall GNS3? It seem the install has been corrupted.

**Comment by gipmon** [comment]
Hello,

I downloaded here: https://www.gns3.com/software/download and DMG..

Thank you

**Comment by noplay** [comment]
Do you have mac port or homebrew installed?

After reinstalling the app it still doesn't work?

**Comment by gipmon** [comment]
Hello, yes, I have, but I made the downgrade now.. Thank you

**Comment by noplay** [comment]
And after the downgrade it's work?

**Comment by gipmon** [comment]
Yes :)

**Comment by mediaos718** [comment]
What version did you downgrade it to?

**Comment by noplay** [comment]
@mediaos718 on which OS are you?

**Comment by mediaos718** [comment]
Running GNS3 version 1.4.6 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.
error msg:
sudo /Applications/GNS3.app/Contents/MacOS/GNS3
Password:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cx_Freeze-4.3.4-py3.5-macosx-10.9-x86_64.egg/cx_Freeze/initscripts/Console.py", line 26, in <module>
zipimport.ZipImportError: can't find module 'GNS3__main__'

**Comment by noplay** [comment]
You should not run GNS3 with sudo it's a source of issue (will broke with VMware for example).

What is the output of the env command?

**Comment by mediaos718** [comment]
I'm running GNS on MAC os and I am trying to attach my lab to an external connection to access my local LAN. I am following this documentation: http://www.fixedbyvonnie.com/2015/04/connect-your-gns3-lab-to-the-internet-mac-os-x/#.WADvj5MrKgQ

Somewhere it says to run this command:  sudo /Applications/GNS3.app/Contents/MacOS/GNS3

Do you have any documentation on how to do this? thanks!

**Comment by noplay** [comment]
Are you using the GNS3 VM?

**Comment by mediaos718** [comment]
No
