### ISSUE TITLE
Upgrade VMware banners

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1032]
We have negotiated a 20% discount instead of 10%. The banner in the setup wizard should be updated.

**Comment by noplay** [comment]
@stephenguppy do you have the new banners?

The size should be 454x150

![vmware_fusion_banner](https://cloud.githubusercontent.com/assets/345437/13074387/8347bc54-d4a4-11e5-9d30-a6cb31f697de.jpg)

![vmware_workstation_banner](https://cloud.githubusercontent.com/assets/345437/13074390/848b25ce-d4a4-11e5-91a8-4916422f642c.jpg)
