### ISSUE TITLE
High resolution screen on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1033]
GNS3 doesn't scale well on Windows 10 with a high resolution screen (tested with 3840x2160 4k display).

The toolbars and symbols are quite small. Also, the GNS3 VM menu is very small and doesn't expand.

![high_resolution_gns3](https://cloud.githubusercontent.com/assets/4752614/13023448/4c7d23ae-d1a6-11e5-9e8d-b9a8daa9c969.png)

**Comment by grossmj** [comment]
Worse, preferences window is completely unusable and cannot be expanded.

![preferences](https://cloud.githubusercontent.com/assets/4752614/13023650/17b7a674-d1a8-11e5-9304-61d804dda166.png)

**Comment by noplay** [comment]
I fear that it's a qt issues...

Le sam. 13 févr. 2016 00:46, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Maybe but we should check we have no fixed size for icons anywhere.

Also, we should find a solution for the GNS3 VM.

**Comment by grossmj** [comment]
Qt 5.6 should be release on March 3rd. https://wiki.qt.io/Qt-5.6-release

**Comment by noplay** [comment]
For the GNS3 VM it's mean you need a way to change the resolution of the VM.

But I'm surprised you can not zoom VMware? Most VM will not boot with a better resolution. On my Mac I can resize the windows.

**Comment by noplay** [comment]
I made an update for the preference dialog is it better?

**Comment by grossmj** [comment]
At least with version 1.4.2 we can expand the preferences window. Still some work to do to support 4K monitors.

**Comment by noplay** [comment]
Qt 5.6 is reported to improved HDPI on Windows 10. Not sure if it's solve our issue

**Comment by grossmj** [comment]
Qt 5.6 seems there are lot of improvements in regard to Windows 10. Let's upgrade when the final release is out.

**Comment by grossmj** [comment]
Some information regarding HDPI support in 5.6: http://doc.qt.io/qt-5/highdpi.html

**Comment by grossmj** [comment]
Now we wait for PyQt...

**Comment by cambrant** [comment]
Is [PyQt 5.6](https://www.riverbankcomputing.com/news/pyqt-56) worth a try? "Added full support for Qt v5.6.0."

**Comment by grossmj** [comment]
We are currently testing it on Windows ;)

**Comment by grossmj** [comment]
Still trying to understand how to make it work. By default the interface looks small.

![unscalled](https://cloud.githubusercontent.com/assets/4752614/14892698/4423c0c8-0d29-11e6-9cad-8e3c42ce1e66.PNG)

If I set this environment variable:

![set_env_variable](https://cloud.githubusercontent.com/assets/4752614/14892705/4d4af518-0d29-11e6-9e11-20dec34c51de.PNG)

The interface is correctly displayed, however this looks rather pixelated...

![scalled](https://cloud.githubusercontent.com/assets/4752614/14892712/5305170e-0d29-11e6-8115-5030582bd6c6.PNG)

**Comment by grossmj** [comment]
I think this is what causes the problem with the preferences dialog on high DPI monitors, we can't set fixed sizes like that: https://github.com/GNS3/gns3-gui/blob/1.5/gns3/dialogs/preferences_dialog.py#L44

**Comment by noplay** [comment]
I think we can workaround thing for preference windows. But we are in a situation where when we fix something for large screen it's break for small screen.

But perhaps we have too much level of stuff creating trouble:
* The tree
* The tab
* The setting

And the windows is exploded in multiple UI files.

VLC is doing that like this:
![capture d ecran 2016-04-28 a 22 22 14](https://cloud.githubusercontent.com/assets/345437/14900199/afe0ed52-0d8f-11e6-92b9-ff5720d42df5.png)

And with advanced settings enable:
![capture d ecran 2016-04-28 a 22 17 31](https://cloud.githubusercontent.com/assets/345437/14900039/0c23c28e-0d8f-11e6-9767-e1a1fa56c641.png)

But that seem a big work to change.

**Comment by grossmj** [comment]
We also set a fixed size (48x48) for QIcons in the QToolbars...

I don't know what the best approach for that... should we multiply 48 by the devicePixelRatio  http://doc.qt.io/qt-5/qguiapplication.html#devicePixelRatio or use scaling by setting AA_EnableHighDpiScaling in QApplication? Qt docs are not very helpful...

**Comment by noplay** [comment]
Where it's set?

I also pushed a potential fix for the preferences but can not test it

**Comment by grossmj** [comment]
Apart from the node list and the SVG items on the workspace that look a bit pixelated, things are a lot better on high DPI monitors.
