### ISSUE TITLE
no console outputting when using vmware workstation instance.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1040]
version:
GNS3 1.4.1
Lubuntu 15.10
Vmware workstation 12.1.0
and use linked base
I tested ASAv 931 and ASA842 for vmware workstation. 
Once using headless mode , running asa931 and double click to open console ,but no outputing.
disable headless mode and run asa 931, GNS3 show error message:Error: Cannot launch the UI because no display server is present in the current environment.
is this a problem or somthing I didn't enable?

non linkbase is ok……

**Comment by noplay** [comment]
Are you trying to use workstation on a server where you are not graphical logged?

**Comment by superwolfboy** [comment]
No.
I install a lubuntu on a  vmware workstation. and install gns3 in this llubuntu.

**Comment by superwolfboy** [comment]
I tested the ASA931
all condition graphic not working :"Cannot launch the UI because no display server is present in the current environment."
so I use headless mode.
At this moment:
1, use link based , not working , console(roxterm) can be open by double click on instenance.but no continually outputing.
2, no use link based, working, and the console can show the boot message and can be operated.

**Comment by noplay** [comment]
And in the lubuntu you have another vmware? Or you are running ASA in qemu?

**Comment by superwolfboy** [comment]
yes ,inside ubuntu there is another vmware workstation.

**Comment by grossmj** [comment]
I would recommend to use Qemu... Never tested ASAv with VMware.

**Comment by grossmj** [comment]
The problem seems to be with the appliance itself.
