### ISSUE TITLE
GNS3 v1.5: GUI Crashed when deleting a link

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1041]
```
2016-02-15 13:28:37 INFO packet_capture.py:62 IOU1 has successfully started capturing packets on Ethernet2/1
2016-02-15 13:31:53 INFO packet_capture.py:90 IOU1 has successfully stopped capturing packets on Ethernet2/1
2016-02-15 13:31:56 INFO link.py:141 deleting link from IOU11 Ethernet1/3 to IOU1 Ethernet2/1
2016-02-15 13:32:04 INFO link.py:141 deleting link from IOU12 Ethernet1/3 to IOU1 Ethernet2/0
2016-02-15 13:32:17 INFO link.py:141 deleting link from IOU9 Ethernet1/3 to IOU1 Ethernet3/0
2016-02-15 13:32:18 INFO link.py:141 deleting link from IOU8 Ethernet1/3 to IOU1 Ethernet2/2
2016-02-15 13:32:28 INFO link.py:141 deleting link from IOU1 Ethernet3/3 to IOU44 Ethernet1/3
Fatal Python error: Segmentation fault

Current thread 0x00007fe9cc97e740 (most recent call first):
  File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/main.py", line 269 in main
  File "/usr/local/bin/gns3", line 9 in <module>

```

**Comment by noplay** [comment]
Which OS are you using?
You don't have the issue with 1.4?
You can replicate this easily?

**Comment by AJNOURI** [comment]
- Environement

> Linux gns3-iouvm 3.13.0-75-generic #119-Ubuntu SMP Mon Jan 11 13:49:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.3 LTS
> Release:	14.04
> Codename:	trusty

- I didn't test this with 1.4

- This happens when I try to delete the TRANSIT-SW:
![selection_896](https://cloud.githubusercontent.com/assets/1716020/13106127/e0df20b0-d566-11e5-9f63-84d55a831eee.jpg)


I can replicate it 7/10 times, whether the switch started or stopped.
For the 7 times, I got this:

> 2016-02-17 10:17:34 INFO iou_device.py:166 IOU instance IOU11 has been created
> 2016-02-17 10:18:53 INFO telnet_console.py:82 Telnet console 127.0.0.1:2005 closed
> 2016-02-17 10:18:56 INFO vm.py:229 TRANSIT-SW has stopped
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU1 Ethernet0/0 to TRANSIT-SW Ethernet0/0
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from TRANSIT-SW Ethernet0/1 to SW1 Ethernet0/1
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU2 Ethernet0/0 to TRANSIT-SW Ethernet2/2
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU3 Ethernet0/0 to TRANSIT-SW Ethernet0/2
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU4 Ethernet0/0 to TRANSIT-SW Ethernet0/3
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU5 Ethernet0/0 to TRANSIT-SW Ethernet1/0
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU6 Ethernet0/0 to TRANSIT-SW Ethernet1/1
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU7 Ethernet0/0 to TRANSIT-SW Ethernet1/2
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU8 Ethernet0/0 to TRANSIT-SW Ethernet1/3
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU10 Ethernet0/0 to TRANSIT-SW Ethernet2/1
> 2016-02-17 10:19:01 INFO link.py:141 deleting link from IOU9 Ethernet0/0 to TRANSIT-SW Ethernet2/0
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007f1625c4a740 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/main.py", line 269 in main
>   File "/usr/local/bin/gns3", line 9 in <module>

But When it doesn't crash (3 time out of 10) I got this:

> 2016-02-17 10:42:18 INFO topology.py:941 Topology initialized
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from TRANSIT-SW Ethernet0/1 to SW1 Ethernet0/1
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU2 Ethernet0/0 to TRANSIT-SW Ethernet2/2
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU1 Ethernet0/0 to TRANSIT-SW Ethernet0/0
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU3 Ethernet0/0 to TRANSIT-SW Ethernet0/2
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU4 Ethernet0/0 to TRANSIT-SW Ethernet0/3
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU5 Ethernet0/0 to TRANSIT-SW Ethernet1/0
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU6 Ethernet0/0 to TRANSIT-SW Ethernet1/1
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU7 Ethernet0/0 to TRANSIT-SW Ethernet1/2
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU8 Ethernet0/0 to TRANSIT-SW Ethernet1/3
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU9 Ethernet0/0 to TRANSIT-SW Ethernet2/0
> 2016-02-17 10:42:30 INFO link.py:141 deleting link from IOU10 Ethernet0/0 to TRANSIT-SW Ethernet2/1
> 2016-02-17 10:42:30 INFO vm.py:119 TRANSIT-SW has been deleted
> 2016-02-17 10:42:30 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)

And when I delete the left 10 routers (single link) everything works OK. (5/5 times)

> 2016-02-17 11:00:44 INFO topology.py:941 Topology initialized
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU10 Ethernet0/0 to TRANSIT-SW Ethernet2/1
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU9 Ethernet0/0 to TRANSIT-SW Ethernet2/0
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU5 Ethernet0/0 to TRANSIT-SW Ethernet1/0
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU8 Ethernet0/0 to TRANSIT-SW Ethernet1/3
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU4 Ethernet0/0 to TRANSIT-SW Ethernet0/3
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU6 Ethernet0/0 to TRANSIT-SW Ethernet1/1
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU7 Ethernet0/0 to TRANSIT-SW Ethernet1/2
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU1 Ethernet0/0 to TRANSIT-SW Ethernet0/0
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU2 Ethernet0/0 to TRANSIT-SW Ethernet2/2
> 2016-02-17 11:00:54 INFO link.py:141 deleting link from IOU3 Ethernet0/0 to TRANSIT-SW Ethernet0/2
> 2016-02-17 11:00:54 INFO vm.py:119 IOU10 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU9 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU5 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU8 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU4 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU6 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU7 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU1 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU2 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:54 INFO vm.py:119 IOU3 has been deleted
> 2016-02-17 11:00:54 INFO http_client.py:752 RAM usage on http://127.0.0.1:8000 has decreased by 256 MB (total load is now -256 MB)
> 2016-02-17 11:00:57 WARNING __init__.py:121 Save changes to project "CCIEv5-topology.gns3" before closing?
> 2016-02-17 11:01:01 INFO project.py:337 Project 8629cf9c-e3bf-47bc-b2a8-bf99c2369243 closed

This is the system resources during all the test runs:

![selection_895](https://cloud.githubusercontent.com/assets/1716020/13106224/69d0c978-d567-11e5-863e-acef63fb6967.jpg)

**Comment by noplay** [comment]
You tested with the last git source? 

Could start the gui with --debug. We should get a better stackstrace.

Thanks a lot for helping us to track this complicate bug.

**Comment by AJNOURI** [comment]
I tested with the Nightly Builds of  2016-02-16 from sourceforge.

Since the last test (was using i86bi-linux-l2-adventerprise-15.1b.bin) I have changed the Switch image to i86bi_linux_l2-ipbasek9-ms-may8-2013-team_track.bin, **not a single crash!!**
I have hard time reproducing the error and isolating a pattern in my actions, even with the previous used image, crashed only 1/10 times.

Here is the log with --debug for that single crash:

> 2016-02-17 17:53:04 DEBUG vm.py:99 IOU11 is being deleted
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet0/0 to IOU1 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU1 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/5582ae8f-f493-47be-8ef4-1bad8e79b64f/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet0/1 to IOU2 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/0/ports/1/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU2 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/bb8af2bf-daae-4523-a3ed-9b787611276d/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet0/2 to IOU3 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/0/ports/2/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU3 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/db52d939-3cb3-41e1-ae24-0e845086045a/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet0/3 to IOU4 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/0/ports/3/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU4 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/fd945eb9-ff6d-4086-bbc6-df6f4974a663/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet1/0 to IOU5 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/1/ports/0/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU5 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/5b36535e-0844-4e53-9b3f-53917fd328e5/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet1/1 to IOU6 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/1/ports/1/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU6 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/c0843a9c-911e-408c-a431-5b6a08fafd76/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet1/2 to IOU7 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/1/ports/2/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU7 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/12470392-a1d0-4b16-949e-2d77e5ded59f/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet1/3 to IOU8 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/1/ports/3/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU8 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/cb5b9904-94a6-433c-af69-3f8a336707c0/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet2/0 to IOU9 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/2/ports/0/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU9 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/1d608fe5-a7e2-4412-98c9-8b5cf7784532/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from IOU11 Ethernet2/1 to IOU10 Ethernet0/0
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/2/ports/1/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU10 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/0bdbad7d-4dce-4df7-a1ac-9ae69d8d5f15/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 INFO link.py:141 deleting link from SW1 Ethernet0/0 to IOU11 Ethernet2/2
> 2016-02-17 17:53:04 DEBUG vm.py:294 SW1 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/87310ae6-e6cc-4d45-8fe7-09173dd948a5/adapters/0/ports/0/nio {}
> 2016-02-17 17:53:04 DEBUG vm.py:294 IOU11 is deleting an NIO
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0/adapters/2/ports/2/nio {}
> 2016-02-17 17:53:04 DEBUG http_client.py:566 DELETE http://127.0.0.1:8000/v1/projects/8629cf9c-e3bf-47bc-b2a8-bf99c2369243/iou/vms/e392d15c-1b83-4eea-8613-9fab238476e0 {}
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fea12270740 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/main.py", line 269 in main
>   File "/usr/local/bin/gns3", line 9 in <module>


By the way i86bi-linux-l2-adventerprise-15.1b.bin image links were generating **%AMDP2_FE-6-EXCESSCOLL** loopback messages (with full duplex), I am not sure if relates to the issue at all.

I am confused!!

**Comment by noplay** [comment]
Do you still have the problem? I fixed some potential crash recently

**Comment by noplay** [comment]
After a lot of test I don't reproduce it. I think I fixed it recently with one of my fixes in the progress dialog. 

If you still have the issue don't hesitate to comment I will reopen the issue.
