### ISSUE TITLE
1.5: vm_id of docker container changes with every open of project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1043]
GNS3 version 1.5.0dev1 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

I created a project with one docker vm, that has a VOLUME entry. This is the gns3 file after creating the VM:
[docker.gns.first.txt](https://github.com/GNS3/gns3-gui/files/132535/docker.gns.first.txt)

After re-opening the project, the docker VM got a new vm_id, everything else remains the same.
[docker.gns.second.txt](https://github.com/GNS3/gns3-gui/files/132542/docker.gns.second.txt)

The next opening will create a third vm_id for this docker VM and so on.

One minor problem is, that each time a new directory under project-files/docker is created, the old one remains as a leftover. The bigger problem is, that the data volumes are created as a subdirectory under project-files/docker/&lt;vm_id&gt;/ . With the change of the vm_id the data of the previous session is no longer available.

Here a directory listing after the second open:
```
behlers@dell:~/GNS3/projects/docker$ LANG=C ls -lR project-files/docker/
project-files/docker/:
total 8
drwxr-xr-x 3 behlers behlers 4096 Feb 16 14:15 0f106ae0-9400-461e-bf0f-38cb6c9333fc
drwxr-xr-x 3 behlers behlers 4096 Feb 16 14:16 e5c14d7f-b197-411e-abfd-3854e8bb5dc1

project-files/docker/0f106ae0-9400-461e-bf0f-38cb6c9333fc:
total 4
drwxr-xr-x 2 behlers behlers 4096 Feb 16 14:14 data

project-files/docker/0f106ae0-9400-461e-bf0f-38cb6c9333fc/data:
total 4
-rw-r--r-- 1 root root 1073 Feb 16 14:14 test.txt

project-files/docker/e5c14d7f-b197-411e-abfd-3854e8bb5dc1:
total 4
drwxr-xr-x 2 behlers behlers 4096 Feb 16 14:16 data

project-files/docker/e5c14d7f-b197-411e-abfd-3854e8bb5dc1/data:
total 0
behlers@dell:~/GNS3/projects/docker$ 
```

Maybe the reason of this issue is, that my fix for https://github.com/GNS3/gns3-gui/issues/1038 is not complete.

**Comment by noplay** [comment]
Thanks I will look on that.

**Comment by ehlers** [comment]
Thanks a lot, works fine.
