### ISSUE TITLE
Unable to select GNS3 remote server/VM for new images in Windows 1.4.2 client

### ISSUE THREAD

**Issue by DanEmord** [GNS3/gns3-gui#1049]
Just upgraded the VM and client from 1.4.1 to 1.4.2 yesterday on Windows 10 x64 and VMWare Player 12. I tried deleting folders in AppData\Roaming and directly in the userprofile folder to make sure it was a clean slate when opening the client. On first start, it prompts me to use local server vs VM and finds the VM properly, then starts the VM up without issue. However, when trying to add any image (IOS, QEMU, etc) the only option available is local server - I'm unable to select remote server or local VM. See the image below. Please let me know if you need more details.

![image](https://cloud.githubusercontent.com/assets/17316799/13145649/1b56a61e-d620-11e5-9f34-c6d4905b8a27.png)

**Comment by noplay** [comment]
If you restart GNS3 you still have the issue?

**Comment by DanEmord** [comment]
Yup, I've made sure all GNS3 processes are stopped and the VM are powered off when I delete AppData & userprofile directories to initiate a clean start.

**Comment by noplay** [comment]
The GNS3 VM is green in the list of servers?

**Comment by DanEmord** [comment]
Yes, once I add a node it turns green in the list, but the menu options for images are still grayed out.

![image](https://cloud.githubusercontent.com/assets/17316799/13147369/e6504bb2-d626-11e5-850b-f76fb9ca802a.png)

**Comment by noplay** [comment]
You are on windows (for cooking you special build)?

**Comment by DanEmord** [comment]
Yes, Windows 10 x64.

**Comment by noplay** [comment]
Same issue with the Qemu wizard?

Thanks for the help

**Comment by noplay** [comment]
The GNS3 VM use VirtualBox or VMware?

**Comment by DanEmord** [comment]
Yes, it's the same behavior for QEMU & IOU. The local GNS VM is running on VMWare Workstation Player 12.

**Comment by noplay** [comment]
Could you test this build
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-02-18/1.4/GNS3-1.4.2016-02-18-all-in-one.exe/download

**Comment by DanEmord** [comment]
Other than the warning message of mismatched versions, that did the trick - I can now add images to the GNS VM through the client. It also shuts down the VM automatically like it did on 1.4.1. Thanks for the quick turnaround!

**Comment by itsabug** [comment]
Hi,

I got the same problem as mentioned by DanEmord. Unfortunately, when I tried the build that noPlay has suggested, I''am getting below error.
![capture](https://cloud.githubusercontent.com/assets/17325224/13160895/704f9824-d6c0-11e5-8d6d-db3576c3b119.JPG)

**Comment by DanEmord** [comment]
@itsabug, you can just click ok and ignore it. It worked for me even with that error (and also brought up a warning in the console when starting some devices).

**Comment by noplay** [comment]
Yes ignore this or change the version of your gns3 vm to 1.4dev (you can do that from the VM menu). 

Since it seem to fix the issue Jeremy I suggest to release a 1.4.3 quickly.

**Comment by noplay** [comment]
Build for all OS
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-02-19/1.4/

**Comment by itsabug** [comment]
Thank you for the reply noplay and DanEmord. That fixed the issue as of now. JFYI, same issue there in build 1.4.3 as well.

**Comment by grossmj** [comment]
So is the issue present in 1.4.3?

**Comment by itsabug** [comment]
Yes, it is present in 1.4.3

**Comment by noplay** [comment]
Could you test with this build?
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-02-22/1.4/
