### ISSUE TITLE
Upgrade VM from GUI

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1053]
Users should be able to upgrade the VM/server from the GUI when they see this error message:  https://github.com/GNS3/gns3-gui/blob/1a5b5327dc0615a5a747343fa3c418df3e6f7a48/gns3/utils/wait_for_vm_worker.py#L199

**Comment by noplay** [comment]
I propose to improve the error message.

I'm not sure about trigerring the upgrade from the VM. If we have an issue the user will not seen it.

Another issue is if multiple user share the VM one can upgrade the VM for the others.
