### ISSUE TITLE
A web file browser

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1054]
This could be a first attempt in making a JS web interface connect to an API (via the controller).

With docker container we see that you can take advantage to have a direct access to the file system for large number of usage. But actually the file is hidden in the VM. You can found the path via a right click "Show in file manager" but i's obscur and you need to edit file from the VM console (by the way it's help us to convert people to vim and emacs).

The idea is to replace this right click for remote server by opening the user browser to a web file browser of the content of the VM directory. Allowing user to download, upload small files and raw text edit.

**Comment by AJNOURI** [comment]
Is it an extension of the upload function?

![iou-upload](https://cloud.githubusercontent.com/assets/1716020/13194919/f46dfe20-d7a1-11e5-8174-679b2c4174d4.png)

**Comment by noplay** [comment]
Yes and perhaps the code could also be be used as a replacement later.

But something better with really a way to navigate inside the directories.

**Comment by grossmj** [comment]
:+1: Would be very useful.

**Comment by noplay** [comment]
We probably need a kind of Virtual File System for showing a folder for dynamips with only the file of this VM.

**Comment by grossmj** [comment]
This should be part of the web UI.
