### ISSUE TITLE
Tabbed view in GNS3

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1057]
From @uktricky

Move groups of devices between tabs again allowing an off-page connector to link tabs together and perhaps have a text editor (notepad) on a different tab(s)

**Comment by noplay** [comment]
I like the idea of having a tab with a notepad. What do you think jeremy?

About the tab of group of device (#1055) I fear that this add too much complexity.

**Comment by danieldemers** [comment]
I can see the value if you want to treat tabs as Orgs or AS's. You could have a Client A tab and their two ISP Tabs....when you are simulating something. Allowing you to visually separate them instead of having to draw an ugly square/circle etc...

**Comment by noplay** [comment]
And if tab are the same view of the Topology but with different position?  Like a shortcut for going to a specific place.

**Comment by danieldemers** [comment]
Example Use Case:

Be able to tag network elements (IOU, Appliances, associated network links) and group them together. For instance if I have several overlay or underlay designs that are not interacting with each other and out of 15 devices each touches 7 of them with some overlap. It be great to tag those 7 devices for say DMVPN, VLAN, routing domain, security zone, etc. and in a tabbed/new view only shows the devices I care about at the moment. 

Keep the ability to show all but if I am only working on an MPLS lab then only show the MPLS cloud with the PE/CEs. 

This would be a manual process for the designer of the lab, however it helps with creating a scope of devices you care about depending on the work you are doing at that moment.

**Comment by noplay** [comment]
With current code it's a huge work. Everything is designed around the concept of one project open

**Comment by grossmj** [comment]
Yes, we won't do it in the current Qt GUI. However, this will be available out of the box when we have a web Ui :)
