### ISSUE TITLE
Refactor VMware VM networking implementation

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1066]
Many users have connectivity problems with VMware VMs. There is a lot done by GNS3 to try to accommodate existing adapters and adding new ones to match the requested number of adapters in GNS3. The implementation is complex and I believe this leads to various problems.

I think we should just let the users configure the adapters in the VMware GUI and then GNS3 reads it and expose the adapters in our interface.

**Comment by jcalano** [comment]
That's how I currently do it and don't experience issues.

**Comment by grossmj** [comment]
Well, I am not considering it any more. I haven't see many complaints regarding VMware adapters... Maybe it just works? ;)

I'll keep that issue around for some more time in case I change my mind.

**Comment by grossmj** [comment]
@ehlers any input/advice on this?

**Comment by ehlers** [comment]
Not really, I'm using VMware Fusion only for devices running not that good in the GNS3-VM. Currently it's only the vSRX. And I have no problems with the VMware networking (otherwise I would start creating issues :-)

**Comment by grossmj** [comment]
Re-factoring VMware networking implementation will make more sense once we have our new network back-end.

**Comment by grossmj** [comment]
Some more info about current issues: https://gns3.com/qa/re-add-network-adapter-for-vmwar

**Comment by grossmj** [comment]
Some changes that should help https://github.com/GNS3/gns3-server/commit/3fd0a6d638535000997af57a90af23cbbaaaf200

To be tested on Windows.
