### ISSUE TITLE
Allow the user to disable or reorder GNS3 Servers in the Remote Servers section

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1069]
If one of my servers is down the GUI desperatedly tries to reach that server and the user (me :-) ) gets frustrated because he can not stop the client from trying to add the device to the dead server

**Comment by 1001QAdotNET** [comment]
Alternatively we should be able to disable load balancing

**Comment by grossmj** [comment]
We are actually thinking about remove load-balancing. https://github.com/GNS3/gns3-gui/issues/1073
