### ISSUE TITLE
Import Export Menu

### ISSUE THREAD

**Issue by claytondf** [GNS3/gns3-gui#107]
Error After using the Import / Export menu

GNS3 management console. Running GNS3 Early Release (ER) version 1.0beta4.dev1 on linux (64-bit).
Copyright (c) 2006-2014 GNS3 Technologies.

=> ****** Exception detected, traceback information saved in /root/.config/GNS3/exception.log ******

PLEASE REPORT ON http://forum.gns3.net/development-f14.html OR http://github.com/GNS3/gns3-gui/issues

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.0beta4.dev1-py3.4.egg/gns3/cloud/utils.py", line 225, in run
    provider.upload_file(zipped_project_file, 'projects')
AttributeError: 'NoneType' object has no attribute 'upload_file'

**Comment by grossmj** [comment]
This was code under construction. You shouldn't have the problem anymore.
