### ISSUE TITLE
Server deleted , device created for load balancing still tries to connect to the removed server

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1070]
I created a device that had load balancing for server preferences
Because my server was down I deleted the server and restarted the client
After restarting the client when I tried to add the device to the project the client still tried to contact the server which I deleted. When I checked the Server section in Preferences the server was back there although I deleted that.

**Comment by noplay** [comment]
The load balancing does not work like this. It's only used when you create the template. I agree that it's not usefull actually and confusing. I opened an issue about removing it since we will probably not working on a real solution soon #1073
