### ISSUE TITLE
Remove load balancing

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1073]
The feature is not really usefull actually since you can not load balance when you put a node in the topology.

**Comment by grossmj** [comment]
I agree and if an user really wants to "load-balance", he/she can still create different templates with different servers.

**Comment by 1001QAdotNET** [comment]
let the user do that himself, manually, but do not remove the multiple server support. That is a very important feature for scalability

**Comment by grossmj** [comment]
Let's remove load-balancing. We won't remove the multiple server support.

**Comment by noplay** [comment]
I propose to ship it with 1.5  because it's streamline the interface.
