### ISSUE TITLE
Once use VNCviewer connect with Lubuntu and running GNS3-GUI, cannot input right characters.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1075]
This is a very interesting problem, not many person use it like this, so maybe no need to fix.
OS:Lubuntu 15.10 (zh_CN:zh)
GNS3: 1.4.3
The Lubuntu has been enabled the VNCserver by tightvnc server and Lightdm.
So open a VNCviwer on windows and connect with the Lubuntu , open the GNS3 Gui.
At this moment, about this GNS3 GUI, cannot get the currect input from keyboard. for example: I cannot change the name of node in top, cannot type the message in top, when I input "s" it will show "a"  and so on.
But do the experiment is ok cause roxterm and other linux app is OK.
The screenshot is showing when I type "book" , the GNS3 GUI show wrong and other app showing right.And by the way, XDMCP with Xmanager has the same problem.
![image](https://cloud.githubusercontent.com/assets/9411604/13227322/067d461c-d9d1-11e5-8c76-298c21825f49.png)

**Comment by noplay** [comment]
How GNS3 is started?

**Comment by superwolfboy** [comment]
double click or input "gns3" in terminal , both has this problem.

**Comment by noplay** [comment]
I think the problem is GNS3 use QT and all other app use GTK. Your keymap has been change for GTK application but not for QT.

**Comment by superwolfboy** [comment]
understood, thank you and thanks for all your amazing jobs.

**Comment by noplay** [comment]
Thanks let me know if you found how to fix it

**Comment by superwolfboy** [comment]
but  have no idea how to fix it.

**Comment by superwolfboy** [comment]
I have one way even though not perfact, use vnc4server instead tightvnc, and working , but the "up ,down , left and right "not working , but can use the mouse to point .
![Uploading image.png…]()
![Uploading QQ图片20161004172925.png…]()

tested in Lubuntu 16.04
GNS3 1.5.2

**Comment by ccollicutt** [comment]
I also have this problem.
