### ISSUE TITLE
Add a distinctive mark to the links that can not be sniffed

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1077]
some of the links that we have between various appliances can not be sniffed (traffic can not be captured)
It would be useful to mark them somehow when they are created so that the user can know  that he just created a link with some limitations. 
I found that, most of the times this is connected with the type of hypervisor that lies behind each appliance

**Comment by noplay** [comment]
I agree it's very confusing you should not have to care about this.

**Comment by grossmj** [comment]
What kind of mark? We have to be careful not to clutter the view.

**Comment by noplay** [comment]
In 2.0 we can solve that and allow sniff on all links.

**Comment by grossmj** [comment]
Indeed, let's not do unnecessary work ;)
