### ISSUE TITLE
Qemu instenance select virtio would be error

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1078]
Once use virtio network device on qemu device , it would not start and show the error message:
"virtio" is not a vaild device model name 
![image](https://cloud.githubusercontent.com/assets/9411604/13246599/af5063fe-da4f-11e5-9df0-2b4843997fdb.png)

**Comment by noplay** [comment]
I think the problem is with your qemu. How do you install qemu?

**Comment by superwolfboy** [comment]
apt-get install qemu 
do I need to install libvirt or something else?

**Comment by superwolfboy** [comment]
apt-get install qemu .
do i need to install libvirt or someting else?

**Comment by noplay** [comment]
Hmm it doesn't seem to exist in qemu. But I don't know if it's a mistake or
something that was change by qemu team. virtio-net seem to be replacement.

In order to see the list of devices:
qemu-system-x86_64 -device ?

**Comment by noplay** [comment]
Ok virtio is the legacy interface. You need to use  virtio-net-pci

**Comment by noplay** [comment]
Jeremy use e1000 for asav

**Comment by superwolfboy** [comment]
got ,thank you
