### ISSUE TITLE
Downloading a remote project when having two servers fails if the first server is down

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1081]
I have two GSN3 servers defined. One of them is down. 
I built my project on the other one and I tried to save it.
The error message is not descriptive..."you can not save this type of project"
You should add "but you can download it"
Then I tried to use that menu option and it failed with 
"Error while creating project: Cannot connect to remote server .."
where the server was the dead server....

**Comment by noplay** [comment]
It doesn't seem wrong. Since export need to have all the data. What do you expect?

We plan to rewrite project export in 1.5. We don't like the way it's work actually it's not reliable and portable.

**Comment by 1001QAdotNET** [comment]
Understood
What is the estimated date for 1.5 ?

**Comment by noplay** [comment]
No estimate. We have a big work to do to refactor the way we manage
multiple server.
