### ISSUE TITLE
IP configuration for Docker

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1082]
This is raise by suggestions from Bernhard Ehlers on how to make Docker more easy to use.

Bernhard use an init script to set the IP in the container via environnement variable. This is nice because it's work. But we can probably do better.

My suggestion is to have a right click on node and have a configuration dialog for the network:
![capture d ecran 2016-02-24 a 09 45 28](https://cloud.githubusercontent.com/assets/345437/13279953/6035438e-dadb-11e5-80c0-752ded21ac12.png)

This will push settings to the node and depending of  the emulator we will try to set the properties.
- For qemu, vmware and vbox it's not possible since they are black box.
- For IOS and IOU this require to override the startup config
- For VPCS this require to override the startup.cfg
- For Docker this require to set them via ubridge or an init script injected in the container.

We need to make clear to the users that changing a settings here will override all his config (like autonetkit for VIRL)

It's part of auto configuration challenge.

**Comment by ehlers** [comment]
Looks good, maybe you can add IPv6 addresses/gateway/DNS.

**Comment by noplay** [comment]
Good idea

**Comment by AJNOURI** [comment]
Good idea.

**Comment by noplay** [comment]
We finally have a standard /etc/network/interfaces config file.
