### ISSUE TITLE
Display CPU usage of VMs

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1085]
https://gns3.com/discussions/suggestion-find-out-which-proces

**Comment by grossmj** [comment]
This would be awesome to do it in the web interface (like VIRL).

**Comment by noplay** [comment]
We can send it via the notification feed. 

I think we should refactor the code that start a process in the different modules in order to have a common function which take a pid:
* monitor the process to see if the process crash and update the status
* monitor cpu and ram usage and send periodic notification about it

Not a big work I think.

**Comment by jean-christophe-manciot** [comment]
Displaying graphical circle widget-style CPU, RAM and maybe disk usage (such as would be awesome.
Cf. **X-CPU for Android** widgets on the bottom of the screenshot for example:
![x-cpu widgets](https://cloud.githubusercontent.com/assets/13176858/14042075/ddc015b0-f276-11e5-9013-4557eeea9acd.png)

**Comment by noplay** [comment]
https://gns3.com/discussions/new-gns-feature-network-device-b

**Comment by grossmj** [comment]
Moved to https://github.com/GNS3/gns3-web-ui/issues/2
