### ISSUE TITLE
Program GNS3GUI to check if there is a previous gns3.exe instance running and to kill it if needed

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1088]
I am running 1.4.3 on Win7 x64
Looks like GNS3 does not always exit properly and I find it running next morning when I start GNS3. the new instance is trying to connect to the local server (that is the symptom and then I know that gns3.exe must be killed)
So ..if this is not difficult program GNS3gui to look for a previous incarnation and to kill the zombie :-)

**Comment by noplay** [comment]
Problem is multiple GNS3 is allowed if you want to open two project :(

We need to find the Zombie issue. If you have idea on how to reproduce it

**Comment by 1001QAdotNET** [comment]
Actually it would be simpler to inform the user that there is a second copy of GNS3.exe running and ask him/her if it should be killed. This would be very simple to implement

**Comment by noplay** [comment]
We could add a warning. It will help.

I'm worry because for me the zombie issue was fixed :(

**Comment by noplay** [comment]
Duplicate of #1086

**Comment by grossmj** [comment]
We could check with psutil that gns3.exe if not already running... if yes we can ask to kill it or not.

**Comment by noplay** [comment]
We already check in order to not start the server twice :(

**Comment by noplay** [comment]
Seem to be a clue about the issue of ghost process:
```
I was building a topology, did a wr on all devices, saved the project and clicked close, accepted that devices were running do you want to continue dialog....
```
