### ISSUE TITLE
Docker container initialization

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1089]
Current the environment of a docker container created by GNS3 differs from a normal docker environment. So currently a docker image needs some special handling to run with GNS3.

- The interfaces (including loopback) are not enabled
- IP addresses are not configured
- No (default) routes
- /etc/hosts is empty
- /etc/resolv.conf is empty

Have a look here, how this initialization currently might look like:
https://github.com/ehlers/gns3-docker-images/tree/master/gns3-debian-base

In future it should be possible to use (almost) every docker image unmodified with GNS3. Here I like to discuss some possibilities. Currently I see the following options:

- Mount a (readonly) directory into each image and modify ENTRYPOINT/CMD to start an initialization script before the normal operation starts. That's similar to the \__gns3__ directory in my current GNS3-only docker image. Currently I use environment variables to pass the parameters, but other ways are possible, too.
- Do all the necessary changes outside of the docker container, e.g. at ubridge or gns3-server. I know, that this will work for the network interfaces, but I don't know, if /etc/hosts and /etc/resolv.conf can be modified from the outside.

Any further ideas?

**Comment by ehlers** [comment]
**Initializing /etc files from the outside:**

Found https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

Normally docker creates files for /etc/hostname, /etc/hosts and /etc/resolv.conf and mounts them into the docker container.

If the docker container is started by GNS3, only an /etc/hostname is injected. So GNS3 must only create files for the missing /etc/hosts and /etc/resolv.conf and inject them. Then the /etc directory should be fine.

Eventually it's not necessary to create /etc/resolv.conf, maybe docker can create it for us, when we use the command line options `--dns` and `--dns-search`.

**Comment by noplay** [comment]
I have put a basic script in place to test the system. Just the /hosts for the moment and up the interface. 

We need to decide how to manage the IP and the DNS. Docker can do that because he assign an IP.

**Comment by ehlers** [comment]
So you don't want to do everything from external ? I am quite (but not 100%) sure, that with this "ip netns exec $pid" stuff, you should be able to set the interface status and IPs, probably also the routes.

I'm OK with that, I was just astonished that you go that way.

**Comment by noplay** [comment]
Problem is netns require sudo and linking kernel stuff :( We can also use
nsenter but it's require sudo and not available everywhere. The other way
to do it is to add this in ubridge.

**Comment by ehlers** [comment]
Sure for the external looks more difficult, but I fear it has to be done to handle this TCP checksum offload bug from issue https://github.com/GNS3/gns3-server/issues/444 . Anyway, I'm fine with your decision.

I just looked over your injected script. The last line `/bin/sh -c "$@"` is not good. Any nontrivial docker image needs an (simple) init system and that has to get PID 1, as PID 1 is special in linux.. So you have to use `exec "$@"`

**Comment by noplay** [comment]
You can try but it's not working for me and I never get the hand back :(  Perhaps you will have an idea.

You can hack the init.sh and restart the container at each test no need to restart GNS3. It's a mount of the directory.

**Comment by AJNOURI** [comment]
What do you think about **[phusion/baseimage](https://github.com/phusion/baseimage-docker)**, a special base docker image that deals with init process issues and many others...
Or maybe we could build our own base image optimized for GSN3 use?

**Comment by noplay** [comment]
The issue with that. Is after you can only use images made for GNS3. And if you want to quickly test something (for example an elasticsearch cluster) you need to make your own image.

**Comment by ehlers** [comment]
Created a PR https://github.com/GNS3/gns3-server/pull/448, please try that.
The tests currently fail, because the arguments to docker have changed. I haven't updated the tests.

**Comment by ehlers** [comment]
Let's continue this discussion also at https://github.com/GNS3/gns3-server/pull/460
