### ISSUE TITLE
A startup config for docker?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1097]
Instead of having a an IP configuration interface (see #1082) perhaps we could have just a startup config for each VM. And provide a clean way to edit the startup config for any VM (Perhaps even for qemu push the config with #1095).

In the case of docker we can inject it and load it. And provide a default version

His content will be something like for a docker container:
```
#######
# DHCP
#######

# Uncomment this two line to enable DHCP
# udhcpc || dhcpcd || dhclient
# exit 0

######
# Static
######

ip addr add 192.168.100.1/24  eth0

# Configure the DNS
#echo '192.168.1.1' > /etc/resolv.conf

**Comment by AJNOURI** [comment]
The context menu to configure address setting is great.
By the way, concerning dhcp acquired addresses, I have noticed that dhclient command gived the following error:

> dhclient: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied

Which can be solved by moving dhclient to **/usr/sbin/**

> mv /sbin/dhclient /usr/sbin/dhclient

then

> ifconfig eth0 up
> sudo dhclient eth0

**Comment by noplay** [comment]
The dhclient in which container?

**Comment by AJNOURI** [comment]
Here is my observations for different containers.
Base containers for the below distributions need additional packages for dhcp to work:

!# Ubuntu:

> dhclient eth0
> dhclient: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
> **mv /sbin/dhclient /usr/sbin/dhclient**
> /usr/sbin/dhclient eth0 


!# debian: had to install udhcpc 

> apt-get install udhcpc

!# Opensuse: had to install iproute2, net-tools, dhcpcd

> zypper install iproute2 net-tools sysconfig wget
> wget http://download.opensuse.org/repositories/openSUSE:/13.2/standard/x86_64/dhcpcd-3.2.3-47.80.6.1.x86_64.rpm
> rpm -i dhcpcd-3.2.3-47.80.6.1.x86_64.rpm

!# centos: had to install dhclient

> yum update
> yum install dhclient

!# Alpine: had to install dhclient

> apk add dhclient

For Alpine, though the command doesn't show errors and wireshak shows normal dhcp exchange, the container doesn't get assigned ip nor gateway:
![selection_955](https://cloud.githubusercontent.com/assets/1716020/13497974/32cf1a04-e158-11e5-940e-eb8dadc42dcc.jpg)

**Comment by noplay** [comment]
Perhaps a stupid idea, but we can compile a busybox with a udhcp client and inject it in the container in the /gns3 directory. This warranty we always have access to dhclient (could work for route and ifconfig command also)

4) If you type a container name in the wizard, GNS3 will pull it from docker registry

**Comment by ehlers** [comment]
I don't think it's a stupid idea. I tried building a statically linked busybox, which includes only the features, we need for the init script.

I created it within an alpine docker image:
```
apk --update add gcc linux-headers musl-dev make ncurses-dev
download busybox
make menuconfig        (select only the minimum, statically linked)
make
```
A busybox with only udhcpc is just 75k "big".

Alternatively copy the busybox from the busybox-static alpine package, it's about 900k big. As this is a one-time download, it doesn't matter much. Put this together with the init script in a read-only mounted directory and you have all possible utilities with a well-defined behavior. The big advantage is, that you don't need resources  for building and testing busybox and you have a load full of utilities available.

**Comment by ehlers** [comment]
After thinking a little bit longer, I more and more like the idea of having a full busybox in /gns3/bin.

The init script can do something like
```
#!/gns3/bin/sh

OLD_PATH="$PATH"
PATH=/gns3/bin

.
.
.

PATH="$OLD_PATH"
exec "$@"
```

That way the GNS3 init script would use only the busybox binaries. It doesn't depend upon any binary in the docker image. So it can't fail, because some image has an unusual set of commands installed. It should create an extremely stable environment for the GNS3 init.

**Comment by AJNOURI** [comment]
A busybox in the container is a good idea, with a couple of useful tools, the footprint is small.

**Comment by noplay** [comment]
Sound like a plan :)

**Comment by noplay** [comment]
It seem with busybox we can read an /etc/network/interfaces for the network config with the ifup command

**Comment by ehlers** [comment]
Yes, /etc/network/interfaces should/will work. So we could use this configuration file format and inject it into /etc/network/ .

DHCP needs some care. It uses udhcpc, which does only the dhcp message exchange part. For the change of the interface/route/resolv.conf configuration an external script is called: /usr/share/udhcpc/default.script . So the init directory must also contain our version of that. It doesn't exist in the docker alpine image, but for example the tinycore VM has one.

This script doesn't have to be /usr/share/udhcpc/default.script, it can be changed to any command in /etc/network/interfaces.
```
iface eth0 inet dhcp
	script /hallo123
```

But as the user should be responsible for /etc/network/interfaces I would like it better to hide that from the user. It should be possible to create a script named /gns3/bin/udhcpc that adds the option "-s &lt;script file&gt;" to the command line and then calls the real udhcpc.

**Comment by noplay** [comment]
The init can write /usr/share/udhcpc/default.script at startup

**Comment by ehlers** [comment]
Sure, that's an options, too. But I personally like as few changes to the original image as possible. At least, when it's not too complicated to work around that.

Anyway, that's a minor implementation detail. At first, someone has to decide, if we want to go that way and how the user interface should be.

**Comment by noplay** [comment]
Jeremy will be back from vacation at the end of the week. He will offer another vision of the subject.

**Comment by noplay** [comment]
Discussion continue on #460
