### ISSUE TITLE
Is it possible to remove one of interface labels on same interface port

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1098]
Hi
it will be more cleaner in larger typologies  if we could remove one of the same connected interface lables
![port](https://cloud.githubusercontent.com/assets/8465075/13454521/00177e80-e06d-11e5-9e2c-751df0289659.png)

**Comment by noplay** [comment]
I see the idea and the fact it's improve stuff.

But this mean to add a system for having a label to a link.

I doubt we add this soon.

PS: I love your symbols :)
