### ISSUE TITLE
For huge topologies, can we have collapsible group of routers?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1100]
I am playing with a huge topology ( I think it is a newer version of this: https://www.gns3.com/api/v2/assets/photo/566bba016f0e7cf5f03fd12e/screenshot.png?size=large) 

When I zoom out I lose the scrolling option and it is difficult to move the view to the area where I need.
Two improvements can be done here:
-make collapsible group of routers to simplify the topology view(links can not be added to the collapsed group, you will need to expand the group and select the router that you need to connect). A special annotation object should be added for this puprose. Whatever is in that perimeter should be collapse under a symbol like AS1 or AS2 and so on (AS as in Autonomous System)
-on the same line it could be an option to temporary hide the rest of the topology and focus the view  on one group of routers (AS) only 

-make a panzoom (like in the top left corner of this image: http://blog.flabell.com/wp-content/uploads/2009/07/zoom_pan_map_viewer.png)

**Comment by noplay** [comment]
I think it's similar to #1055. The panzoom idea is interresting

**Comment by 1001QAdotNET** [comment]
Yes it is the same idea, indeed

**Comment by grossmj** [comment]
Will consider it part of https://github.com/GNS3/gns3-gui/issues/1055
