### ISSUE TITLE
REQ - Can we have some additional drawing tools

### ISSUE THREAD

**Issue by uktricky** [GNS3/gns3-gui#1101]
Would like to be able to draw:
- Lines (with or without arrow heads), 
- To have a anchor point to drag to make a curved line 

all with normal formatting solid/dashed/colours etc

**Comment by noplay** [comment]
I doubt we will work on more drawing tool soon since our priority is more on getting better networking.

**Comment by danieldemers** [comment]
I think this is highly needed but I would suggest waiting for a clean web interface for this feature to be added too.

**Comment by grossmj** [comment]
Lines could eventually be added. This shouldn't be too hard.

**Comment by grossmj** [comment]
https://github.com/GNS3/gns3-gui/issues/997

**Comment by noplay** [comment]
https://gns3.com/qa/free-hand-line-curve-drawing-opt

```
Could you please include the option for free hand different types of line/curve (dotted, straight, double ...) drawing  so that after creating a lab we can make these lines/curves more appropirate and in future when reopening same projects, these things will be really helpful along with relevant text.
 
Also for these lines/curve, providing colour selection will be a value addition.
 
Hope  this request will be considered.
 
Thanks
 ```

**Comment by noplay** [comment]
https://gns3.com/discussions/drawing-tool-features-please

```
In one of your next releases can please add a few drawing tools features like:
 
1) Add transparency fill to the ellipse and rectangle tool.
2) Add free draw pencil or Free Form Arc tool.
3) Insert Bitmap background in the ellipse and rectangle tool.
 
Thanks!
```

**Comment by candlerb** [comment]
Related to this: apart from being able to shape "drawn" lines, I would like connections between interfaces to be non-straight.

In some topologies it would be really helpful to route the lines away from crossing over intervening devices.

Just having little fixed anchors (and drawing straight lines segments between them) would be fine.

**Comment by cioby23** [comment]
@candlerb There are already some requests opened for this feature:
https://github.com/GNS3/gns3-gui/issues/2303
https://github.com/GNS3/gns3-gui/issues/1748

**Comment by candlerb** [comment]
@cioby23: thanks!  I did try a search but didn't find them.

**Comment by acaldir** [comment]
is it possible to use a pen in gns3, it would be better
