### ISSUE TITLE
Allow custom properties in the GNS3 topology file (might be already supported, have not tested extensively)

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1102]
I have already tested this with shortly and I concluded that this might already be there. 
Is GNS3-GUI going to ignore any custom property that we might add to nodes and linke?

**Purpose:** allow someone like me to incorporate in that file information needed for his scripts or plugins

**Comment by noplay** [comment]
It will ignore but raise a warning when you save.

You can see more information here and comment: #707

**Comment by 1001QAdotNET** [comment]
Yes this is more or less what I was thinking but I am not sure if the .gns3 file stucture sugested there will do it, for two reasons:
-having a plugin will complicate the processing for this file
-having that section will break the objectual structure of the file, if you are forced to store attributes for the same object (node,link,server etc) in two places within  the same file it will create confusion and complications when we process this file

IMHO the gui program should be able to read, store in memory and save the structure back when it deals with unknown data types.

**Comment by noplay** [comment]
My concern is how to avoid conflict between GNS3 properties and user defined properties. If tomorrow we add something  using the same name.

For example imagine you add a properties ethernet0.ipv4 and GNS3 add this later with a different syntax (192.168.1.1 vs 192.168.1.1/24)

**Comment by 1001QAdotNET** [comment]
That cab be avoided by adding a plugin name prefix to the new property and the author of the plugin will be responsible for managing his own name space
Whatever has no prefix it is GNS3 reserver
This way the guys who want to write code that uses the GNS3 topoology file can even easily extract and filter out their particular data structures

for me it will be  AutoIP4GNS3.IPAddress and AutoIP4GNS3.NetMask
