### ISSUE TITLE
network of VMBox ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1103]
Hi

I don't know if it is really an bug of GNS3, or VirtualBox or Debian.

Sometimes, on the lab of my students, i see that network from Linux VBox doesn't work. I must shutdown the interface (ifdown eth0) and no-shutdown (ifup eth0) to correct it. In this case, i never see error of config

For example, when i reload this lab, VM Debian-1 or Serveur doesn't start or network of this Linux doesnt work (i must ifdown/ifup) :
![image](https://cloud.githubusercontent.com/assets/7449584/13575455/55fea84e-e489-11e5-962a-cccc17ce7dee.png)

**Comment by noplay** [comment]
What type of switch are you using?

**Comment by Raizo62** [comment]
I sent you an email with more infos. Did you receiv it ?

**Comment by noplay** [comment]
I found it. My google drive notification skip my inbox.

I suspect an issue in the ethernet switch. We know that he have some issues but since the author of Dynamips is not active anymore nobody can investiguate them.

@grossmj  an idea?

**Comment by Raizo62** [comment]
I have perhaps wrong but i believe that i didn't have this bug ("ifup/ifdown") with gns3-legacy . But it is perhaps also VirtualBox or Debian

**Comment by Raizo62** [comment]
An idea for the brainstorming : With systemd and less kernel module, VM of Raizo starts more fast than before, then an UDP server/client is  not ready ?

**Comment by Raizo62** [comment]
In this lab, i tried to replace ethernet switch by switch-L3 : one VM desn't start after restart lab

**Comment by Raizo62** [comment]
I have replace all VPCS with Switch-L3 and VM doesn't crash : is it not the same bug as "GNS3/gns3-server/Two VirtualBox VMs can't start at once #190" ?

Then this doesn't explain why sometimes, i must ifdown/ifup :-(

**Comment by kothwala123** [comment]
Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by noplay** [comment]
The generic switch is not started, when you drop in the topology it's on. No need to power it.

**Comment by Raizo62** [comment]
can you reproduce these bugs ?

**Comment by noplay** [comment]
No

**Comment by Raizo62** [comment]
really ? this doesn't help to solve it :-(

even with sent files?

**Comment by noplay** [comment]
But I'm on mac

**Comment by Raizo62** [comment]
mac can boot on Live Raizo

**Comment by grossmj** [comment]
So, to summarize the problem seems to be with the simple Ethernet switch right?

**Comment by Raizo62** [comment]
I think that they are 2 bugs :
- one with vpcs (perhaps) : Cloned VM crash when i reload project.
- one with simple ethernet switch (perhaps) : sometime, I must ifup/ifdown network interface of VM

**Comment by noplay** [comment]
At worse VPCS can send bad packet but since Debian received it via the network it should handle it without crash like a real PC. Sound like an issue in Vbox clone system.


Different question not a solution to the issue: Do you have something that prevent you to run the Debian on Qemu? For qemu we don't need to have a clone system since qemu has a copy on write feature.

**Comment by Raizo62** [comment]
I thought to use qemu, but qemu misses useful functionality : 
* a method to know the name of VM into GNS3
* an access to host directory without install samba

**Comment by Raizo62** [comment]
I don't know if i was clear : When i said "one with vpcs (perhaps) : Cloned VM crash when i reload project.", i want say that VMBow won't start, with same error in log of Vbox that "GNS3/gns3-server/Two VirtualBox VMs can't start at once #190" (The VirtualBox logs tells something about failed to start the UDP tunnel server:)

**Comment by noplay** [comment]
But the VBOX is connected to a switch not directly to the VPCS

**Comment by Raizo62** [comment]
(sorry, strangly i don't see your message before)

Yes....port conflit ? different OS involve different load time ?

And there are crash only when i reload this lab.

**Comment by Raizo62** [comment]
I sent you an another partage on google.

**Comment by noplay** [comment]
I got an idea. Do you have the issue if the VM don't have the guest addition tools? Since this is playing with the network also perhaps it's conflicts.

**Comment by Raizo62** [comment]
I tried to stop vbox service into VM in the lab2. No change.

It will be difficult to test your idea : to do a lot of tests (with students in TP for example), i need guest addition for rename VM and access file.

As the bug of Lab2 occurs at each start, do you see something of strange with the connections between dynamips/Vbox/ ?

**Comment by noplay** [comment]
Nothing strange.

**Comment by Raizo62** [comment]
I did more tests on Lab2
- bug (ifup/ifdown) occurs when i start only Debian-1 and R1. Not need to start all.
- If i start Debian-1 and R1, the bug occurs.
- if i start Debian-1. I am waiting the end of boot of Debian- to start R1. The bug don't occur.
- With bug : 
    when Debian-1 ping R1, R1 know mac address of Debian-1.
    when R1 ping Debian-1, R1 don't know mac address of Debian-1.
   --> Debian-1 can send but can't receiv something.
- to correct the bug : only do : ifconfig eth0 down && ifconfig eth0 up  (as i believe, ifconfig does less thing as ifup/ifdown)

**Comment by noplay** [comment]
And with a different linux flavor like fedora or alpine you have same
issues?

**Comment by Raizo62** [comment]
I test with Live Raizo so with Debian VM. And the bug doesn't occur always then i am "happy" to have a backup to reproduce it.

**Comment by grossmj** [comment]
Do you mean it works now?

**Comment by Raizo62** [comment]
No. In lab2, network doesn't work, because receiv doesn't work when Debian et R1 start in the same time.

But i don't know if it is a bug in GNS3, VirtualBox, Debian or me....

**Comment by Raizo62** [comment]
I believe that i found a clue : 
it looks that bug occurs on lab2 where acceleration processor is disable on host, and doesn't on host where it is enable.
This should be a bug with virtualbox and debian when acceleration processor is not activated on host (or disable VTx/AMD-V in config VirtualBox of VM)

**Comment by grossmj** [comment]
Interesting finding! I will try to reproduce it on Ubuntu. Looks more like a VirtualBox bug.

**Comment by Raizo62** [comment]
I don't know if this is useful : VM are 32 bits not pae.

I had to use "not pae" because some VMs do not finish to boot when i used several VM at the same time.

**Comment by Raizo62** [comment]
This is not only VTx/AMD-V

I simplified Lab2 : only Debian-1, R1 and sw1 (ethernet switch).
I disabled VTx/AMD-V on Debian-1

I connected sw1 to Host device with tap0. (and I gave a good IP to tap0 ;-) )

If i start all at the same time, Debian-1 can't ping tap0

I disconnect R1 from sw1 and connect it on an another ethernet switch.
If i start all at the same time, Debian-1 can ping tap0

**Comment by grossmj** [comment]
So a problem with the Ethernet switch as well you think?

**Comment by Raizo62** [comment]
I don't have bug if Debian-1 is alone on a ethernet switch. Then I don't think that ethernet switch is problem.
I think more at a trame who disturb network card of Debian (or VirtualBox).

An (another) temporary solution is to reset the autonegociation of network card : mii-tool -r eth0 . But i don't know if this is the same thing that ifconfig eth0 down/up

**Comment by grossmj** [comment]
Thanks for all the debug. I think we can conclude this isn't a problem with GNS3, so unfortunately nothing  to fix I believe.

Let me know otherwise.
