### ISSUE TITLE
[1.4.4/Linux] Error when pushing to Google Analytics Connection refused

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1105]
?

**Comment by noplay** [comment]
Where do you see this error?

**Comment by grossmj** [comment]
We need more info on this. When did you see that error?

**Comment by jean-christophe-manciot** [comment]
It appeared with [this issue](https://github.com/GNS3/gns3-gui/issues/1104). Since the latter has been solved, it does not appear anymore:
GNS3 was trying to connect to Google analytics 172.217.16.72 ssl-google-analytics.l.google.com
Is it expected?

**Comment by noplay** [comment]
When stats are enabled (the default) yes , you can turn them off in the settings.
