### ISSUE TITLE
my project-files contains more device-id than i have in my topology

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1106]
Hi
recently i created a project that had only 6  IOU devices
later i have noticed that in my project-files, i have additional  folders for my devices and even for qemu and dynamips  and my qemu folder is 111 MB .
![iou](https://cloud.githubusercontent.com/assets/8465075/13594636/0b7e8284-e51b-11e5-8ec8-2f897fd18028.png)
![proect](https://cloud.githubusercontent.com/assets/8465075/13594643/1855aafa-e51b-11e5-8674-feb7e2bc23fb.png)
![iou f](https://cloud.githubusercontent.com/assets/8465075/13594650/26fdd406-e51b-11e5-8b5c-48e3aa30661c.png)
![qemu](https://cloud.githubusercontent.com/assets/8465075/13594661/3845cac0-e51b-11e5-85f6-0a501c251449.png)
![folder properties](https://cloud.githubusercontent.com/assets/8465075/13594673/4a00f0fa-e51b-11e5-98da-631267c29a72.png)

i dnot know why that happened  any idea ?

**Comment by noplay** [comment]
If you start a new project from scratch you have the same thing?

**Comment by taurus8** [comment]
Hi
NO i do NOT have the same issue
still cant understand what wrong i have done :/

**Comment by noplay** [comment]
Do you think you could have use the save as? 

I think the scenario could be you start with the untiled project. This project directory contain a lot of garbage from old projects. And after you save as a new project.

**Comment by taurus8** [comment]
yes you are right
my untitled projects contains a lot of garbage folders
![iou](https://cloud.githubusercontent.com/assets/8465075/13601965/e9c2c8fc-e548-11e5-8566-12561632eef9.png)
