### ISSUE TITLE
If server fail to start we keep the waiting dialog

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1109]
For example start the server with an additional parameter (for example --fake).

The bin will exit with an error message in the terminal but the app will not display an error.

**Comment by grossmj** [comment]
Not the correct solution because the GUI is blocked for 1 second, I can see the lag when I start the GUI.

**Comment by noplay** [comment]
I think I fixed it with the timeout fix

**Comment by grossmj** [comment]
Ok, I will remove that code then: https://github.com/GNS3/gns3-gui/commit/8894c2674815d04cbbddc748e4fe14992b8dcb7c
