### ISSUE TITLE
Is there a GNS3 node like Linux Bridge ? If not can it be added to the built in objects?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1111]
The object should work on the GNS3 VM only.

**Comment by noplay** [comment]
What is the purpose of this bridge?

**Comment by 1001QAdotNET** [comment]
It would be a network tap

**Comment by noplay** [comment]
You can create a tap on the system and use it in the bridge it's not working?

**Comment by 1001QAdotNET** [comment]
I can connect a qemu machine to any tap interface via command line but then what is the point of using GNS3?
I think that the cloud node needs some work and must be changed to an universal bridge. The user gets confused between to many options to bridge or interconnect various nodes. Cloud and hub should be unified in a bridge because these is what they both are.
The new bridge object should have all the options that the cloud object has + the option to create a linux bridge when the object is defined on a VM that supports this. The linux bridge is very versatile and it will open our access to all the network tools that can be used under Linux.
Again all the above are possible by using the command line but we need them in GNS3

**Comment by 1001QAdotNET** [comment]
Hmm there seem to be an indirect way to achieve this. Bridges must be defined on the VM and tap intefaces and then use the Host object in GNS3-GUI. I will test this

**Comment by grossmj** [comment]
We intend to provide a object which will use a Linux bridge or Openvswitch in the back-end. We will also refactor the current Cloud implementation in our next major version: 1.5.
