### ISSUE TITLE
Capture on link instead of port

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1117]
Actually when you start a capture we ask for the interface where the capture should happen. But I'm not sure if it's usefull. Because in theory if GNS3 work the capture should be the same on both side.

My proposal is to remove the choice and behind the scene the network backend can decide where to capture, this mean the api for capture will be on /links in the controller instead of the network adapter.

The current implementation doesn't create issue but I imagine stuff like packet loss configuration will be on the link instead of the port. And in this case it seem logic to have all the packet manipulation in the link API.

**Comment by noplay** [comment]
A note on a serial link the capture type should be asked it could be FRAME RELAY, PPP and HDLC

**Comment by grossmj** [comment]
I think I am fine with it excepting if someone see a specific usage I missed.

@ehlers, anyone?

**Comment by ehlers** [comment]
I see only one use case for capturing on the port: Debugging if the link is working.
But normally it's sufficient, looking at the interface counters.

So yes, I'm fine with that proposal as well.

**Comment by noplay** [comment]
In theory all link should work in GNS3 you should not have to debug GNS3 internals. I think I we need it we can edit the code to force the capture on one side of the link.

**Comment by grossmj** [comment]
Ok, let's do it then.

**Comment by noplay** [comment]
In the same time we need to process most of the capture controller side (write in the captures directory).
