### ISSUE TITLE
GNS3 doesn't handle VMware VMs nicely, that are halted within the VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1118]
GNS3 version 1.4.4 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.
VMware Fusion v8.1.0

I have some VMware Fusion VMs, that need a proper shutdown, so I'm halting them within the VM. But GNS3 doesn't recognize that, it thinks, that these VMs are still running.

Worse, I can't halt them in GNS3
`Server error from http://192.168.1.10:8000: vSRX-1: vmrun has returned an error: Error: The virtual machine is not powered on: /Users/behlers/GNS3/projects/9daa3e80-8c47-46d1-a537-b5376c7e19c0/project-files/vmware/fb445232-1210-4f87-a11d-ad78a1c9e008/vSRX-1.vmx`

As GNS3 thinks it's still active, I can't start the VM again, furthermore I can't save the topology. Deleting the VM is one of the few options, that are available, not that nice.

If getting the change of the status is difficult in VMware, it might be enough to ignore the error during halt.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/7cdf23f497a4188e61a618d867711a92b24fc3cf
