### ISSUE TITLE
Check that the RPF service is started on Windows.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1124]
This could do into the GNS3 doctor.

One example how to do it: https://mayankjohri.wordpress.com/2008/07/05/get-the-windows-service-state-using-python/

There is also ways using the pywin32 module directly.

**Comment by noplay** [comment]
What is the rpf service?

**Comment by grossmj** [comment]
This is what Winpcap installs to allow non Administrators to capture on interfaces.

**Comment by grossmj** [comment]
Well, WMI doesn't list rpf service... but I found an alternative :)

```
import win32service
	import win32serviceutil

if win32serviceutil.QueryServiceStatus("npf", None)[1] != win32service.SERVICE_RUNNING:
    print("Not running...")
```
