### ISSUE TITLE
Question: Is there any possible to add a function that allow us to edit the command line of start a qemu?

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1127]
Is there any possible or necessary to add a function allow us to edit the command line of start a qemu instance. 
The edit box should be include in configuration for qemu templete(the window of right click the templete and click "configure templete"),maybe need add one more tab?

**Comment by noplay** [comment]
The command line is generate at start.

You can already add additional parameters. What do you want to edit?

**Comment by superwolfboy** [comment]
sometime I want to delete "-nographic" though vnc can be used.
at this time I can use the virtual screen and console together to seek some problem.

**Comment by noplay** [comment]
The problem with no-graphic and no-kvm is can not customize it since the server generate them based on current context.

But your question is pertinent. When we use a VNC on qemu you could enable an aux console in order to have telnet access to the serial output.

What do you think @grossmj ?
