### ISSUE TITLE
Add an edit mode to gns3 gui

### ISSUE THREAD

**Issue by rebelinux** [GNS3/gns3-gui#1134]
It should be good to have and edit mode for the topology and a viewer mode so the item of the topology can't be edited or moved.

Some times when using gns3 the topology icons get wrongly moved and it provoke to constantly save the topology. Sorry for my bad English...

**Comment by noplay** [comment]
Thanks for the idea.

**Comment by grossmj** [comment]
Similar to https://github.com/GNS3/gns3-gui/issues/1228

Should we allow locking every object AND the entire topology?
