### ISSUE TITLE
symbol when capture

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1137]
Hi

I believe we can't do a right click on the symbol on the link  (https://github.com/GNS3/gns3-gui/issues/789)

And this symbol isn't too big ?

**Comment by grossmj** [comment]
You are correct, you cannot right click ;)  Also, the symbol may be slightly too big, however do you prefer this symbol or a Wireshark symbol?

**Comment by Raizo62** [comment]
I like your symbol : it is clear
