### ISSUE TITLE
GNS3 1.4.5 leaves instance running after closing

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1138]
Windows 10 Pro 64 bit
GNS3 1.4.5 running all images on VMware Workstation 11 VM
All seems to work great (IOU, IOS, ASA and IOSv). However, when I close GNS3 app it leaves an instance of itself running.  Best I can tell this happens consistently.  Thanks again for the great work!

**Comment by noplay** [comment]
It's happen when you are using a special kind of images or with any images?

**Comment by jtorri** [comment]
Many thanks for quick response.  Best I can tell not related to a specific image but does appear related to exactly "how" I close GNS3 app.  If I use the sensible method, i.e., File -> Quit, it does not happen. If I close the GNS3 app by clicking on the apps window's top right X it does happen.  Once again seems to be user error!  I am using Windows's Task Manager to verify GNS3 app is/is not running.

**Comment by noplay** [comment]
I try with the X and no issues :( 

And in the code I see any differences all of this is managed by Qt.

**Comment by grossmj** [comment]
Do you have any node on the workspace when closing the app?

**Comment by jtorri** [comment]
If I understand your question should I close completely all projects before closing GNS3 app? Not doing so at present. Cannot test until this evening.

**Comment by noplay** [comment]
You have multiple projects open at the same time?

**Comment by jtorri** [comment]
No. Only one.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Julien Duponchelle <notifications@github.com> </div><div>Date:03/28/2016  3:23 PM  (GMT-05:00) </div><div>To: GNS3/gns3-gui <gns3-gui@noreply.github.com> </div><div>Cc: jtorri <jtorri@windstream.net> </div><div>Subject: Re: [GNS3/gns3-gui] GNS3 1.4.5 leaves instance running after closing
  (#1138) </div><div>
</div>You have multiple projects open at the same time?

**Comment by jtorri** [comment]
And I start only one instance of GNS3 at a time.

**Comment by noplay** [comment]
With more comments I got this two informations:
* It seem to arrive with IOU on a VM
* With slow hard drive

**Comment by noplay** [comment]
Tested: Add 100 VPCS on a remote box and close the app no ghost process even if the close was slow.

I suspect something related to the GNS3 VM shutdown.

Are you using VMware or VirtualBox for running IOU.

Can you test by disabling ACPI shutdown?
![image](https://cloud.githubusercontent.com/assets/345437/14114732/7e44c22e-f5d8-11e5-98ad-0cdb475a6284.png)

Thanks a lot for the help

**Comment by jtorri** [comment]
Be happy to but work will prevent me from getting it done until later this evening.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Julien Duponchelle <notifications@github.com> </div><div>Date:03/29/2016  12:06 PM  (GMT-05:00) </div><div>To: GNS3/gns3-gui <gns3-gui@noreply.github.com> </div><div>Cc: jtorri <jtorri@windstream.net> </div><div>Subject: Re: [GNS3/gns3-gui] GNS3 1.4.5 leaves instance running after closing
  (#1138) </div><div>
</div>Tested: Add 100 VPCS on a remote box and close the app no ghost process even if the close was slow.

I suspect something related to the GNS3 VM shutdown.

Are you using VMware or VirtualBox for running IOU.

Can you test by disabling ACPI shutdown?


Thanks a lot for the help

**Comment by jtorri** [comment]
Using VMWARE Workstation 11


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Julien Duponchelle <notifications@github.com> </div><div>Date:03/29/2016  12:06 PM  (GMT-05:00) </div><div>To: GNS3/gns3-gui <gns3-gui@noreply.github.com> </div><div>Cc: jtorri <jtorri@windstream.net> </div><div>Subject: Re: [GNS3/gns3-gui] GNS3 1.4.5 leaves instance running after closing
  (#1138) </div><div>
</div>Tested: Add 100 VPCS on a remote box and close the app no ghost process even if the close was slow.

I suspect something related to the GNS3 VM shutdown.

Are you using VMware or VirtualBox for running IOU.

Can you test by disabling ACPI shutdown?


Thanks a lot for the help

**Comment by jtorri** [comment]
Unchecking ACPI did not prevent GNS3 app "ghost".

**Comment by noplay** [comment]
I have no idea about this and how to replicate on our machines.

**Comment by jtorri** [comment]
OK. Thanks for looking into it. Easy enough to end "ghost" with Windows Task Manager. Interestingly does not appear to happen with Asav.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Julien Duponchelle <notifications@github.com> </div><div>Date:04/06/2016  10:12 AM  (GMT-05:00) </div><div>To: GNS3/gns3-gui <gns3-gui@noreply.github.com> </div><div>Cc: jtorri <jtorri@windstream.net> </div><div>Subject: Re: [GNS3/gns3-gui] GNS3 1.4.5 leaves instance running after closing
  (#1138) </div><div>
</div>I have no idea about this and how to replicate on our machines.

**Comment by grossmj** [comment]
I could look into it by remote controlling to your PC using TeamViewer if you want.

**Comment by jtorri** [comment]
Wow! Thanks for the offer. There are more important and pervasive challenges you are addressing. Perhaps at a later time. The software is so useful this problem is not a big deal.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Jeremy Grossmann <notifications@github.com> </div><div>Date:04/07/2016  11:32 AM  (GMT-05:00) </div><div>To: GNS3/gns3-gui <gns3-gui@noreply.github.com> </div><div>Cc: jtorri <jtorri@windstream.net> </div><div>Subject: Re: [GNS3/gns3-gui] GNS3 1.4.5 leaves instance running after closing
  (#1138) </div><div>
</div>I could look into it by remote controlling to your PC using TeamViewer if you want.

**Comment by mysterioux** [comment]
during installation, my windows 10 system crashed and i had to restart. Now trying to run GNS3 2.0 its telling me *GNS3 is currently running. Please close it before installing a New Version* Problem is this is my first time of trying to install GNS3. I've checked on task manager but can't find its instance. Any help?

**Comment by noplay** [comment]
The install process is looking for a windows name GNS3 and prevent the installation if he found one
