### ISSUE TITLE
Group devices by server.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1139]
With a remote server, the generic switch asks where to be run:
![selection_052](https://cloud.githubusercontent.com/assets/1716020/14071358/1e1f9984-f4b4-11e5-8177-363ceb8ec9a5.png)

But for other devices (IOU) running on different servers, the only way to differentiate between them is by name, not very practical
![selection_058](https://cloud.githubusercontent.com/assets/1716020/14071360/26f7a416-f4b4-11e5-8b24-5e2256e3bee4.png)

It would be great if these devices are grouped by the server on which they are installed.

**Comment by noplay** [comment]
Are you using multiple server at the same time?

I think #957 can solve your use case. Instead of duplicating device you could switch the location of the GNS3 VM.

**Comment by grossmj** [comment]
This is related to https://github.com/GNS3/gns3-gui/issues/1076

**Comment by AJNOURI** [comment]
Though I am using one server at a time, multiple are configured. #957 could make it.  
Indeed #1076 exposes the issue.
