### ISSUE TITLE
Fix a topology if server is unknow

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1144]
Actually we save the server in the topology but the server could have change and it could be a topology imported from a different user.

What I suggest it's when you open a topology if the server doesn't exists in GNS3 settings we offer this options:
- Replace by local server
- Replace by the VM
- Replace by another server
- Add server to the list

**Comment by grossmj** [comment]
We shouldn't save the local server IP address or GNS3 VM. However, I agree we should have something at least when a user has remote servers.
