### ISSUE TITLE
A scroll bar is visible in server preferences of 1.5

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1148]
![capture d ecran 2016-03-30 a 11 27 25](https://cloud.githubusercontent.com/assets/345437/14137900/72008808-f66a-11e5-9fbb-239ade8cecc6.png)

**Comment by grossmj** [comment]
This doesn't appear on Linux and Windows.

**Comment by ehlers** [comment]
The scrollbar is correct, further down is a "Restore defaults" button. When making the preference window   larger, the scrollbar disappears, just tested on 1.5 with Mac OS X. So I see no real error.

But there is a big empty space between the Import/Export buttons and the "Restore defaults" button (at least on OS X). Maybe that space can be made smaller.

**Comment by noplay** [comment]
The scrollbar should not appear whith default windows size. The problem is with the Remote GNS3 VM in the preferences. We have too much settings that's why the the preferences windows heigh is too big.
