### ISSUE TITLE
Dissallow or warn about usage of linked clone when using VMware player

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1149]
Otherwise the user got an obscure error

**Comment by grossmj** [comment]
Do you remember the error message?

**Comment by noplay** [comment]
![image](https://cloud.githubusercontent.com/assets/345437/14248599/bab32d30-fa75-11e5-82b9-f8ade974e577.png)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-gui/commit/d0396b3da92a9b1ea48f904a3754808afc2fb194
