### ISSUE TITLE
Disallow export when a project is not portable

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1151]
A topology is not portable in multiple cases. Due to limitation of the machine or because data are not easily portable (for VMware for example you need to rexport and ova).

The export should be disallowed if:
* topology run Docker / IOU / Qemu on local server 
* topology use Vbox or VMware

For Docker / IOU / Qemu running on local server technically we could probably move stuff to the VM and to local server depending of the capacity of the host machine. But the target for 1.5 is to keep stuff simple.

**Comment by ehlers** [comment]
What if the user wants to use export/import as a backup for his projects? Or use it as a replacement for save-as. Disallowing export in these cases will limit the usefulness of export/import.

I suggest to issue a big fat warning, if it's not portable, but I won't disallow the use.
