### ISSUE TITLE
GNS3 v1.5: Deleting links between containers "bridge 'bridge0' doesn't exist"

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1159]
Delete link between 2 running containers: 

> 2016-04-06 10:09:22 INFO link.py:141 deleting link from ajnouri/dockervpc-4 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 10:09:22 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/79f01a27-c25c-4038-a4a2-5d91b45e4a15/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 10:09:22 ERROR vm.py:312 Error while deleting NIO ajnouri/alpine-haproxy-1: bridge 'bridge0' doesn't exist
> 2016-04-06 10:09:22 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/2a6f7a9a-2ec5-4574-9f54-6d7463d3e42f/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 10:09:22 ERROR vm.py:312 Error while deleting NIO ajnouri/dockervpc-4: bridge 'bridge0' doesn't exist
> 2016-04-06 10:09:49 INFO link.py:57 adding link from ajnouri/dockervpc-4 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 10:10:04 INFO link.py:141 deleting link from ajnouri/dockervpc-4 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 10:10:04 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/79f01a27-c25c-4038-a4a2-5d91b45e4a15/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 10:10:04 ERROR vm.py:312 Error while deleting NIO ajnouri/alpine-haproxy-1: bridge 'bridge0' doesn't exist
> 2016-04-06 10:10:04 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/2a6f7a9a-2ec5-4574-9f54-6d7463d3e42f/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 10:10:04 ERROR vm.py:312 Error while deleting NIO ajnouri/dockervpc-4: bridge 'bridge0' doesn't exist
> 

Delete link between 2 stopped containers, causes GNS3 GUI to shutdown.

> 2016-04-06 10:11:44 INFO vm.py:230 debian-1 has stopped
> 2016-04-06 10:11:44 INFO vm.py:230 alpine-1 has stopped
> 2016-04-06 10:11:48 INFO link.py:57 adding link from debian-1 Ethernet0 to alpine-1 Ethernet0
> 2016-04-06 10:11:55 INFO link.py:141 deleting link from debian-1 Ethernet0 to alpine-1 Ethernet0
> Fatal Python error: Segmentation fault
> 
> Thread 0x00007f27e3fff700 (most recent call first):
>   File "/usr/lib/python3.4/subprocess.py", line 491 in _eintr_retry_call
>   File "/usr/lib/python3.4/subprocess.py", line 1514 in _try_wait
>   File "/usr/lib/python3.4/subprocess.py", line 1566 in wait
>   File "/usr/lib/python3.4/subprocess.py", line 539 in call
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/telnet_console.py", line 59 in exec_command
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/telnet_console.py", line 77 in run
> 
> Current thread 0x00007f2810406740 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/main.py", line 269 in main
>   File "/usr/local/bin/gns3", line 9 in <module>
> Segmentation fault (core dumped)
> ajn:~/Downloads/gns3-1.5/gns3-gui-1.5$

**Comment by noplay** [comment]
Do you have the segfault everytime?

**Comment by AJNOURI** [comment]
Actually, I could reproduce the " bridge 'bridge0' doesn't exist" message after a couple of times, but not the segfault.

> 2016-04-06 11:47:54 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:48:07 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 
> 2016-04-06 11:48:24 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:48:32 INFO vm.py:148 ajnouri/alpine_links-1 has started
> 2016-04-06 11:48:32 INFO vm.py:148 ajnouri/alpine-haproxy-1 has started
> 2016-04-06 11:48:44 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 
> 
> 2016-04-06 11:49:13 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 
> 
> 2016-04-06 11:49:30 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:49:30 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/79f01a27-c25c-4038-a4a2-5d91b45e4a15/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 11:49:30 ERROR vm.py:312 Error while deleting NIO ajnouri/alpine-haproxy-1: bridge 'bridge0' doesn't exist
> 2016-04-06 11:49:30 INFO http_client.py:677 Response error: Error downloading http://Thswfu0Hstf0xInRfWeHvpVJ44xeNOeiDgswmQkaaHgOcF72lzmgtCeXktygxxdT@127.0.0.1:8000/v1/projects/d2a23e77-275b-4529-a0a2-027641c3602f/docker/vms/9c98e44d-a6f6-4d8b-a87f-78cb818905f9/adapters/0/ports/0/nio - server replied: Conflict (error: 299)
> 2016-04-06 11:49:30 ERROR vm.py:312 Error while deleting NIO ajnouri/alpine_links-1: bridge 'bridge0' doesn't exist
> 
> 
> 2016-04-06 11:51:07 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:51:21 INFO vm.py:230 ajnouri/alpine_links-1 has stopped
> 2016-04-06 11:51:29 INFO vm.py:230 ajnouri/alpine-haproxy-1 has stopped
> 2016-04-06 11:51:36 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:51:49 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:51:55 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:52:03 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:52:09 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:52:14 INFO link.py:57 adding link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0
> 2016-04-06 11:52:21 INFO vm.py:148 ajnouri/alpine_links-1 has started
> 2016-04-06 11:52:21 INFO vm.py:148 ajnouri/alpine-haproxy-1 has started
> 2016-04-06 11:52:27 INFO link.py:141 deleting link from ajnouri/alpine_links-1 Ethernet0 to ajnouri/alpine-haproxy-1 Ethernet0

**Comment by noplay** [comment]
It's two different problem but I was hopping to found a scenario where the the GUI segfault.

**Comment by AJNOURI** [comment]
Unfortunately, I couldn't reproduce it. 
A speculation, as it is a memory access issue, lastly, i changed the swappiness of the machine...
