### ISSUE TITLE
Remove manual console port choice

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1167]
The fact that user could choice the console port a keep it is a source of problems when you start opening multiple topologies at the same time or when you have multiple users. We will remove that.  We already do that for the tunnel between VMs.

For user who don't want to use the GUI to connect to a topology the web app will provide them the require informations.

See #1154 and https://github.com/GNS3/gns3-server/pull/479 for additional details.

**Comment by Sourg** [comment]
What if you use remote server and you access it from GUI through firewall and some specific ports are blocked?

**Comment by noplay** [comment]
On the firewall you could open the port range of GNS3. 

But we don't recommend GNS3 across firewall since you are exposing router on the whole internet. It's better to use a VPN.

**Comment by Sourg** [comment]
In my particular case I wish I could, but I have no control over the firewall. No, my server is not on the Internet.
Would it be possible at least to honor "console_end_port_range", "console_start_port_range" settings from the .conf file?

**Comment by noplay** [comment]
Oh yes their are honor, it's only the option allowing to force a port.
