### ISSUE TITLE
[Question] What file extension for exported lab

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1170]
In 1.5 we add the possibility to import and export labs to a single file.

But which file extensions should we use?

**Comment by noplay** [comment]
Keep the .gns3 is to confusing because you still have .gns3 file on your system for the project you create or after import.

For the moment the code name is gns3z (Zipped GNS3) but it's ugly.

A proposal is .lab

**Comment by grossmj** [comment]
The .lab would come with a GNS3 icon (Chameleon in a box or egg?).

**Comment by AJNOURI** [comment]
zlab, labz or maybe just z3 with a chameleon in a hatched egg.

**Comment by grossmj** [comment]
Could be a double extension: .gns3.lab (like tar.gz), I find it very explanatory.

**Comment by noplay** [comment]
But not very common on windows.

**Comment by danieldemers** [comment]
.gns3p

Simple, works on all platforms (Win/Lin) and allows for flavors of extensions later. End gns3 with a letter depending on the use case.

Dan

**Comment by grossmj** [comment]
.gns3p could work.

**Comment by noplay** [comment]
We try .gns3ALETTER with the gns3a and it seem a little confusing for user.

**Comment by danieldemers** [comment]
Is there documentation on what a meant. I am the main site everyday reading through changes, also on github everyday reading updates etc...and I do not know what a means until I googled it just now. Oddly enough I have used appliances and I still did not pick that tidbit up hehe. 

I think how this information is transferred to the user is where the disconnect is. Make it just apart of the experience. People learn best I feel if you leave them breadcrumbs constantly reinforcing a fact. 

They see those extensions as part of the file screen, it will assist in training. As EVERYONE clicks "file" at one time or another. If user A sees .gns3p everytime they go file > open project. Well they will know. 

E.g.

![image](https://cloud.githubusercontent.com/assets/17289463/14607806/dff026d8-0548-11e6-82a2-b082c858f580.png)


Also I would recommend adding if possible the extension to appear when you hover over the new/open buttons if they do not use the file > open/new method. Like so:

![image](https://cloud.githubusercontent.com/assets/17289463/14608067/d5e3a0e2-0549-11e6-8f1e-4cdd875080e9.png)

**Comment by grossmj** [comment]
Nothing prevent us to have long extensions I think, just like .torrent ;)

For instance:

- .gns3project
- .gns3lab
- .gns3appliance

The advantage is that they are very self-explanatory.

**Comment by danieldemers** [comment]
Very True @grossmj - I think I am a victim of 20 years of "this is how extensions look like...squeezed together letters with meaning".

**Comment by grossmj** [comment]
Perfect, we are going to have .gns3project and .gns3appliance then.

Thanks everyone for all your inputs :+1:
