### ISSUE TITLE
Add an options to export devices images when exporting a topology

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1173]
When a user export a topology, allow him to export the require images. It's useful for sharing a topology with a coworker.

Add a legal disclaimer to warn the user that they should not share copyrighted images

**Comment by jean-christophe-manciot** [comment]
Is there any image usable with GNS3 which is legally free and not tied to the original owner?
If not, you expose the whole company and all the contributors to the project to legal prosecution. Look at what happened to Arista. @grossmj @stephenguppy

**Comment by grossmj** [comment]
Yes there are many we could freely distribute, however you are right we
should carefully consider this. We will have more discussions with the
entire team before we go forward.

Also, why do you believe contributor would be exposed to legal prosecution?

**Comment by jean-christophe-manciot** [comment]
The easiest way is to allow export of the images which can really be openly distributed, and block the export of others. 

> Also, why do you believe contributor would be exposed to legal prosecution?
I meant all the people who could have encouraged/helped develop this feature in anyway that could violate any agreement or contract between the original users and the companies distributing these images would be exposed. 
In a broader sense, also all GNS3 users would be indirectly hurt by this feature if your company gets sued and cannot distribute/develop GNS3 anymore.
This matter is not to be taken lightly.

**Comment by noplay** [comment]
We can not know if an image is legal or not for an export. Because the problem is not the export but when you share the export with someone else.

If you export for you it's legal if you have already the right to use it in GNS3. After for sharing with someone else it will depend of the licence. If you are a teacher the image could be available via an education licence and you have the right to share it with your students. It can even depends of the country of the user.

Alcatel can made a GNS3 topology and share it on the net they have the full right on their image. I can build a topology using BSD image and share it.

An we are not alone doing that for example VirtualBox or VMware can export OVA: with IOSv or a Windows.

We will warn to make it clear for user, to remind them they need to check the licence before sharing something they don't have the legal right.

For sharing topologies on the GNS3 website we will see how to make a control of what is share (probably disallow export  including images).

**Comment by jean-christophe-manciot** [comment]
> We can not know if an image is legal or not for an export. Because the problem is not the export but when you share the export with someone else. If you export for you it's legal if you have already the right to use it in GNS3. 

I don't see the use case when exporting a lab to yourself: why not using the lab itself?

> After for sharing with someone else it will depend of the licence. If you are a teacher the image could be available via an education licence and you have the right to share it with your students. It can even depends of the country of the user.

Your point is that GNS3 cannot guess whether the user has the rights or not to share it with someone else. That may be plausible, but I'm not aware of any such specific group-wide sharing rights. Could you give real-life examples specific to networking images?
I would have guessed that only open source images could be freely distributed with an explicit mention and inclusion of the type of license, such as GNU GENERAL PUBLIC LICENSE or creative commons, but I'm not 100 % sure. 
However, you must be aware that most users won't care about the warnings and will use this feature to distribute some unsharable images, especially if it's the only way to use that feature. I read some mentions of torrent-like channels of distribution on GNS3 website. There is no room for naivety here.
Letting people do their thing is one thing, but giving them the tools to break the licenses is something else.

> Alcatel can made a GNS3 topology and share it on the net they have the full right on their image. I can build a topology using BSD image and share it.
If they distribute that package openly, it means that their image can also be distributed openly, in which case everybody can do the same, can't they? I never meant that exporting topologies could not be done, it's a great idea, but I warned about the potential legal consequences of letting all types of image export happen within GNS3.

> An we are not alone doing that for example VirtualBox or VMware can export OVA: with IOSv or a Windows.

The "other people do the same" argument won't hold in court, you can ask Arista's lawyers for confirmation. Also, I highly doubt that VMware would distribute a Cisco's image considering the current relationship between both companies, but it is true that older versions of IOSv or CSR1000v could be freely distributed by some Cisco's website; however, there was an legal agreement with the user. I suppose that Cisco needs to know who does what with its images.

**Comment by noplay** [comment]
>  I don't see the use case when exporting a lab to yourself: why not using the lab itself?

Backup and moving stuff from a computer to another. It's a very common problem.

> Your point is that GNS3 cannot guess whether the user has the rights or not to share it with someone else. That may be plausible, but I'm not aware of any such specific group-wide sharing rights. Could you give real-life examples specific to networking images?

It's really depends of the licence owner.

I will take real life examples:

- A manufacturer create demo to share with it customers
- A manufacturer can make a demo for his commercial team 
- A teacher can create a demo appliance based on a Linux and share it with students
- A teacher could make a SDN courses based on open source SDN images and share it in a course sell on internet
- Someone can demo a full open stack installation emulated in GNS3 and export the require image with it

We already have discussion about this with some people.

> I would have guessed that only open source images could be freely distributed with an explicit mention and inclusion of the type of license, such as GNU GENERAL PUBLIC LICENSE or creative commons, but I'm not 100 % sure. 

Even if it's a linux kernel you don't know if a software installed on it can legally prevent the share. 

> However, you must be aware that most users won't care about the warnings and will use this feature to distribute some unsharable images, especially if it's the only way to use that feature. I read some mentions of torrent-like channels of distribution on GNS3 website. There is no room for naivety here.
Letting people do their thing is one thing, but giving them the tools to break the licenses is something else.

The main usage we see is for teaching and manufacturers that want to demo their stuff

Also we don't provide tools to break licence, we are not extracting the image from somewhere but just zip the topology and the require image in the same files. You can already do it by hand. And the licence will not prevent to make this zip but to share a file with someone else.

> The "other people do the same" argument won't hold in court, you can ask Arista's lawyers for confirmation. Also, it is true that older versions of IOSv or CSR1000v could be freely distributed by some Cisco's website; however, there was an legal agreement with the user. I suppose that Cisco needs to know who does what with its images.

My point here is GNS3 is a general purpose emulators like VirtualBox and VMware. We are doing the exact same thing. When using IOSv from CISCO VIRL it's come as an OVA but you will have legal trouble if you share this OVA.

For the Arista problem it's different we talk about patent violation on how they design their OS.

> I'm pretty confident that it is possible for you guys to know in advance the images that can be distributed and the ones that cannot.

We are a Layer 1 emulator. GNS3 see image as raw disk we don't know what is inside.

And as I say we talk about exporting in this issue not distributing. And the legal problem is sharing.

**Comment by noplay** [comment]
I will forward the question to internal mailing list.

**Comment by stephenguppy** [comment]
We have had this approved by legal. As long as we don't distribute the images ourselves (host them on our servers and distribute them to users), then we are ok. Each users agrees to the terms and conditions when signing up with GNS3.com - which means they cannot use GNS3.com to distribute images as well.

Unfortunately, a real issue comes up IF we decide which image is ok and which isn't. At that point, we may have set a legal precedent that we will be policing image distribution instead of the end user policing it. The irony is that policing the image export might actually open us up to bigger legal issues. How we have it set is the end user is responsible for image policy instead of GNS3. Changing that may lead us to being legally responsible for what is done with the software anywhere - and that is impossible.

As Julien said, the Arista legal case is not related to this as it has to do with patent infringement (ex-cisco employees taking Cisco code to Arista).
