### ISSUE TITLE
A new appliance button

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1177]
A lot of user doesn't found how to create a new device.

I suggest to add a button at the bottom of the nodes browser
![image](https://cloud.githubusercontent.com/assets/345437/14454869/bbcb4496-009c-11e6-88a7-360e9bd9b8c7.png)

This button will open a window:
![capture d ecran 2016-04-12 a 10 59 54](https://cloud.githubusercontent.com/assets/345437/14455036/bd776878-009d-11e6-8ce4-785f07b69f22.png)

**Comment by grossmj** [comment]
I think I am ok with something like this but we should be careful not to confuse users.

**Comment by grossmj** [comment]
Added with https://github.com/GNS3/gns3-gui/pull/1199
