### ISSUE TITLE
Include link to the GNS3 courses 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1178]
From mark:
```
hey gents do you guys think we might be able to integrate a link somewhere in the software
for the GNS3 course
and training
```

It could be in the Help menu

**Comment by danieldemers** [comment]
![gns3 courses link](https://cloud.githubusercontent.com/assets/17289463/14535699/b06f67e6-0234-11e6-9309-03be66ba533f.png)

Maybe place it on that big free space. If you hide it in help...it may not be used often.

**Comment by grossmj** [comment]
I agree nobody will look in the help menu, however I want to avoid something that stands out / is ugly.

**Comment by grossmj** [comment]
Something in the (Windows) installer or Setup Wizard would make sense.

**Comment by grossmj** [comment]
We already have a link on the thank you page when you install GNS3 on Windows. We will just had one in the Help menu and that should be sufficient for now.
