### ISSUE TITLE
New 1.4.5 ESXI install Server error from http://gns3@10.10.20.32:8000: R1: No data returned from 0.0.0.0:57839, Dynamips process running: True

### ISSUE THREAD

**Issue by eniehaus** [GNS3/gns3-gui#1179]
Server error from http://gns3@10.10.20.32:8000: R1: No data returned from 0.0.0.0:57839, Dynamips process running: True
Server error from http://gns3@10.10.20.32:8000: R1: Could not send Dynamips command 'vm set_ghost_status "R1" 2' to 0.0.0.0:57839: Connection lost, process running: False

any idea what cause this ?
I watched the GNS3 Fundamentals from David Bombal and followed exactly his advise to setup GNS3VM-ESXI.
The Cisco image c3745 runs just fine in the local server but on ESXI.

GNS3 Doctor checks:
Starting checks...
Check if processor is 64 bit...
OK
Checking if AVG software is not installed...
OK
Checking for stable GNS3 version...
OK
Check if dynamips has the correct permission...
OK
Checking if experimental features are not enabled...
OK
Checking for amount of free virtual memory...
OK
Check if gns3 is not installed twice...
OK
Checking if the local server is enabled...
OK
Check if ubridge has the correct permission...
OK
Checking if vmrun is installed...
WARNING The vmrun executable could not be found, VMware VMs cannot be used

**Comment by noplay** [comment]
Did you try with a different image?

We have recommend images here:
https://gns3.com/support/docs/virtual-machines-supported-2
