### ISSUE TITLE
hdd_info.json is created at VirtualBox stop

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1181]
hi

I believe that files hdd_info.json are create only when GNS3 closes

If these files are not create and GNS3 crashs, we can't reload a project.

Has you an technical reason to not creating these files when we are saving project ?

**Comment by noplay** [comment]
It's use only in the case of linked clone.

The problem is Virtualbox should be started in order to extract the information. Not sure exactly when  the info is accurate inside vbox.

**Comment by Raizo62** [comment]
hdd_info.json contains hard disk info.
I believe that GNS3 configures hard disk of VM when it starts VM.

When we save, can you try to extract the informations ? if this is a success, you save it. If this is failure, you don't ( ;-) )

**Comment by noplay** [comment]
The problem is the linked flag. Virtual Box will need to create a linked disk and we don't know it before the disk is created by vbox.

**Comment by Raizo62** [comment]
And test to extract the information before can "crash" GNS3 ou VirtualBox ? Or it is just an error message to capture ?

**Comment by Raizo62** [comment]
Sorry, i don't understand why this is "difficult" to extract the informations to create this file when we save the project ? 
If information is inaccessible, you have an error and you can't create the file. "don't worry, it will be the next time". 
No ?

**Comment by noplay** [comment]
Actually the save doesn't communicate with emulator. It's just dumping on
the disk the content of the .gns3 changing that is not trivial (not for 1.X
series). But it's probably something we should do.

Perhaps even dropping the save notion because it's partial (you can revert
a modif on a .gns3 but non on the VBOX) #1028

**Comment by Raizo62** [comment]
[hdd_info.json.txt](https://github.com/GNS3/gns3-gui/files/236210/hdd_info.json.txt)

**Comment by grossmj** [comment]
Now that only linked cloned hard disks are saved in the hdd_info.json it doesn't matter when the file is created. However, I have added some improvements to still allow a VM to be re-opened or closed even if some disks cannot be detached/reattached. See https://github.com/GNS3/gns3-server/commit/4fc5364ab55828d41e40def1d5f4586df0b01b97
