### ISSUE TITLE
REQ: Snapback Feature - Link Names String Moves Randomly

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-gui#1182]
I have no idea where this e0/2 belongs. My topology is larger than most with 160 devices but even with smaller tops I think it would be helpful to add a "snapback" feature. Put it on the list of options when you right click on the e0/2 link name.

The snapback feature (if possible) would take the link and put it at the default location snug against whatever device this belongs to. 

This issue is probably a part of the other issue that occurs when you have two links between 2 devices...one of the links link names always moves a little bit away. 

![random link name gns3 moves](https://cloud.githubusercontent.com/assets/17289463/14613437/103294d4-0562-11e6-80ae-c9f5cd4450d1.png)

**Comment by noplay** [comment]
Seem a good idea

**Comment by grossmj** [comment]
I like it +1
