### ISSUE TITLE
GNS3 does not start anymore on the latest 1.5 branch

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#1183]
Traceback (most recent call last):
  File "/usr/bin/gns3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2900, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2886, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 942, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5==5.6.dev1604121819' distribution was not found and is required by gns3-gui

It asks for the development version of PyQt 5.6. Currently running the latest stable PyQt 5.5.1

**Comment by noplay** [comment]
Hi,

You are under linux? Which distribution?

**Comment by cioby23** [comment]
Yes. I'm using Linux specifically ArchLinux.

**Comment by cioby23** [comment]
After I cloned the latest 1.5 branch for gns3-gui I saw this line **PyQt5==5.6.dev1604121819**  into the requirements.txt file. After I removed it and tried again it gns3 started fine.
Weird is that I do not see this line here [(https://github.com/GNS3/gns3-gui/blob/master/requirements.txt)] but after I clone the 1.5 branch of gns3-gui is there.

**Comment by noplay** [comment]
Hmm I will ask the PyQt author to see if PyQt source could be added to PyPi
allowing us to keep the same requirements.txt on all platform.

Could you try with the last version of the source?

**Comment by cioby23** [comment]
I have tried now but the errors still appears now complaining about PyQt 5.5
**pkg_resources.DistributionNotFound: The 'PyQt5>=5.5' distribution was not found and is required by gns3-gui**
My version of PyQt5 5.5.1 is installed from the distribution repository so when I run pip freeze I do not see PyQt5 listed there.
I guess adding PyQt5 to PyPi will solve this issue.

**Comment by noplay** [comment]
I got feedback from PyQt author. They will not ship PyQt source on PyPi due to their custom install process.

**Comment by noplay** [comment]
I removed PyQt from the generic requirements.txt file
