### ISSUE TITLE
bug with reload of hdd_info.json with linked clone

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1184]
Hi

I create a topology with 1 cloned VirtualBox

With GUI of virtulabox, I add a new controller (example : IDE) and i add a new hdd into this controller.
Also, I add a new hdd into first controller (example : SATA)

I save and close GNS3

(I believe that hdd_info.json is correct.)

I reload my project with GNS3. New hdd have disappeared (but not new controller).

**Comment by grossmj** [comment]
Can you post the hdd_info.json content you have?

**Comment by Raizo62** [comment]
<file text hdd_info.json>
[
    {
        "controller": "IDE",
        "hdd": "NewVirtualDisk1.vdi",
        "port": "0",
        "device": "0"
    },
    {
        "controller": "SATA",
        "hdd": "{1e326d7a-b89d-482f-a542-e921de93eecb}.vdi",
        "port": "0",
        "device": "0"
    },
    {
        "controller": "SATA",
        "hdd": "NewVirtualDisk2.vdi",
        "port": "1",
        "device": "0"
    }
]
</file>

**Comment by Raizo62** [comment]
[hdd_info.json.txt](https://github.com/GNS3/gns3-gui/files/236213/hdd_info.json.txt)

**Comment by grossmj** [comment]
Hard disks created on a linked clone (after the creation GNS3/VirtualBox) are detached and not restored when re-opening a project.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/4a91d8a6a5518f3d88f0d09bdbf24cbc309dff32
