### ISSUE TITLE
disable "save project as" with linked clone

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1185]
Hi

Could you disable the "save project as" function when you detect cloned link of VM into topology ?

(because this function doesn't work with it, and i believe that project becomes unstable)

**Comment by noplay** [comment]
More generally save as and virtualbox is not a good idea because it's give you the feeling that the VM is duplicate and it's not the case.

**Comment by grossmj** [comment]
I think we can close this issue since the "save as" will be gone in 2.0.

**Comment by Raizo62** [comment]
Hi

Sorry, i reopen this issue.

I test GNS3 2.0

This is stupid, but can you add an button called "save" ? I know that GNS3 saves all the time, but I have strange feeling if i can't push the save button. 
And perhaps newbies will ask you often how to save ;-)

More seriously (but even the first is serious) : I ask again if you can disable the "save project **as**" function when you detect cloned link of VM into topology ? 
I believe that VirtualBox hates "save project **as**" with linked clone

**Comment by noplay** [comment]
No save button after few day you will forgot that :P 

For the save as it seem the correct way is to patch the UUID inside the vbox file:
```xml
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.16-macosx">
 <Machine uuid="{f8138a63-e361-49ee-a5a4-ba0559bc00e2}" name="Debian-1" OSType="Debian_64" currentSnapshot="{8bd00b14-4c14-4992-a165-cb09e80fe8e4    }" snapshotFolder="Snapshots" lastStateChange="2016-10-28T12:54:26Z">
```

**Comment by noplay** [comment]
Ok it seem to work now but will need to be test in real conditions

**Comment by Raizo62** [comment]
sorry, but this doesnt work : i have this error message when i save "untitled" as "untitled1" : 
`Could not read HDD info file: [Errno 2] No such file or directory: '/home/user/GNS3/projects/untitled1/project-files/virtualbox/13e8036a-0995-4726-84b1-b298d74301b9/Debian-1/hdd_info.json'`

**Comment by noplay** [comment]
Ok problem seem to occur if you put a Vbox and use save as before starting the VM.

**Comment by noplay** [comment]
It was not specific to save as create a project without starting Vbox and reopen it was not supported (only for linked clone).

Seem ok now but not battle tested
