### ISSUE TITLE
[2.0] Asking for qemu binary list make a direct connection to compute node

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1192]
Not sure how we need to handle this case. Actually when you go trough the qemu wizard we make a direct call to the compute node in order to ask the list of qemu binaries. 

Should we keep it like that or proxify it? Perhaps we should have a capacity endpoint returning stuff like KVM is supported, the following qemu are availables, the server has XGB or ram, Xmhz of CPU...

**Comment by grossmj** [comment]
I would vote for a capacity endpoint returning all the necessary information.

**Comment by grossmj** [comment]
Is this the same issue with https://github.com/GNS3/gns3-server/issues/537?

**Comment by noplay** [comment]
Yes it's the same kind of issue we need to expose in controller emulator specific endpoint

**Comment by noplay** [comment]
I finally implement it for the moment as a forward from controller to compute it's less invasive. We change it later.
