### ISSUE TITLE
REQ: Add Local Network Access to Internet Appliance or a Appliance/QEMU

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-gui#1194]
The idea is an effort to simplify how you can connect and pull data/files from within the topology. Right now you can deploy a VM running on a local hypervisor such as virtualbox or VMWare but that is just another VM you have to manage and backup.

I would like to have the GNS3 VM via Docker or just KVM locally to be able to spin up a VM such as a Tiny Linux and have that VM get an IP Address that your desktop can access directly (not via port forwarding). I am not an expert in KVM or Docker but the idea is basically that the VM can get access to the 192.168.x.x network that the GNS3 VM sits on or another network but the local desktop needs to know about it...so it may need to be a part of the GNS3 VM setup..vnet or w/e. Also be able to connect to internal IOU/Other Appliance/etc.. and work in that network.

There are a ton of use cases for this such as sending files to it and then the desktop having access. I may be off base and there already is a way to do this via an appliance/QEMU that runs in the GNS3 VM but I am not seeing it. I would add that simplicity above all else is important if possible. Giving the user to ability to drag and drop an appliance and without needing to have linux skills get it connected to internal networks in your topology and external networks your desktop can hit is the essential desire. 

-Dan

**Comment by noplay** [comment]
In theory the cloud should allow that. But we agree that it's not easy to use and we need to found way to make it easy.

**Comment by noplay** [comment]
It's the same issue:
https://github.com/GNS3/gns3-gui/issues/1625
