### ISSUE TITLE
Sign the DMG

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1204]
We should reconsider signing the DMG (even if this cost some $) and possibly do the same for the Windows installer.

Main issue on Mac is the DMG is reported as corrupted if it is not allowed to run in the Security settings. See https://gns3.com/qa/1-4-6-available.

**Comment by noplay** [comment]
I don't understand how people can have this settings not turned off... It's break so much stuff.

We could test but I think we will have trouble by the need to sign every binary (ubridge , dynamips, gns3, gns3server....).

**Comment by grossmj** [comment]
This is overly complicated. No time to waste on their mess (Apple and Microsoft).
