### ISSUE TITLE
REQ: Please add a "Confirm" button when resetting, shutting down, starting the lab

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-gui#1207]
It does not happen often but when it does I have a 'facepalm' moment. I have made a ton of changes and then accidentally hit the reset or stop lab buttons...

Add a "Confirm" button when you click these.

![gns3 reset](https://cloud.githubusercontent.com/assets/17289463/14937098/8ded57e2-0ec2-11e6-883d-f586e16b1a8d.png)

**Comment by noplay** [comment]
How do you hit accidentally this buttons? Perhaps we can move something.

Because I think adding a confirmation will annoy a part of users.

**Comment by danieldemers** [comment]
Maybe the solution is to STOP the process of either starting or stopping a lab. Instead of a confirmation screen, give the user an option to click cancel to a stop or star lab process. 

Right now when you stop all the devices and the dialog box appears in the middle. If you click the x, the box simply comes right back. 

I have hit that box a hundred times and still my entire lab shutdown.

**Comment by grossmj** [comment]
There is not easy way to do it currently. It will be easier when we implement https://github.com/GNS3/gns3-gui/issues/1212
