### ISSUE TITLE
GNS3 v1.5: GNS3 restart counting container names from 1 at each project reopen.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1208]
When adding instances of existing containers, GNS3 ignores existing containers and restart counting  from {container-name}-1 at each project open.

![selection_081](https://cloud.githubusercontent.com/assets/1716020/14940011/b8507a2e-0f61-11e6-8301-17ec36de8d27.png)

Resulting is strange link behavior:

When deleting a running device connected to another running device, the warning message "A link cannot be removed ..." pops up as expected, but the device is removed anyway and the connected link remains suspended.

![selection_075](https://cloud.githubusercontent.com/assets/1716020/14939741/5681434e-0f54-11e6-8996-f607d88b4c41.png)

Sometimes, the link is removed if the connected device is stopped.
Other times, cannot remove the link and shows the warning "A link cannot be removed ..." related to the another device with the same name.

![selection_077](https://cloud.githubusercontent.com/assets/1716020/14939778/5b69d3e2-0f56-11e6-881e-7938e10779b3.png)

> A link cannot be removed because dvpc-1 is running
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==1.5.0dev2', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/graphics_view.py", line 514, in mousePressEvent
>     super().mousePressEvent(event)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 266, in mousePressEvent
>     menu.exec_(QtGui.QCursor.pos())
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 289, in _deleteActionSlot
>     self.delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 116, in delete
>     QtWidgets.QMessageBox.critical(self._main_window, "Connection", "A link cannot be removed because {} is running".format(self._source_item.node().name()))
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/qt/__init__.py", line 95, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())

![selection_078](https://cloud.githubusercontent.com/assets/1716020/14939793/cc0289a0-0f56-11e6-8fb2-0cfdec44810e.png)

Even if both connected devices are deleted:

![selection_079](https://cloud.githubusercontent.com/assets/1716020/14939811/b431aefe-0f57-11e6-8139-d9cc4c6d6d9d.png)

> CRITICAL __init__.py:95 A link cannot be removed because dvpc-1 is running
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==1.5.0dev2', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/graphics_view.py", line 514, in mousePressEvent
>     super().mousePressEvent(event)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 266, in mousePressEvent
>     menu.exec_(QtGui.QCursor.pos())
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 289, in _deleteActionSlot
>     self.delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/items/link_item.py", line 116, in delete
>     QtWidgets.QMessageBox.critical(self._main_window, "Connection", "A link cannot be removed because {} is running".format(self._source_item.node().name()))
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/qt/__init__.py", line 95, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())
> 

Have to close the project.

Could sporadically reproduce link issues with other containers and with VMware and Vbox VMs unique instances.

**Comment by noplay** [comment]
I confirm the issue
