### ISSUE TITLE
GNS3 v1.5: Cannot change symbol from Docker VM Termplates

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1209]
context menu "delete" function works but not "change symbol"

![screenshot 2016-05-02 02 11 47](https://cloud.githubusercontent.com/assets/1716020/14945190/c0a5cd50-100b-11e6-9c0e-52d41f72755d.png)

**Comment by noplay** [comment]
Strange this menu doesn't exists for the other type of VM
