### ISSUE TITLE
Create stop and start all api endpoint

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1212]
I suggest that we move on the controller the code for start and stop all node. This will allow us in the future to make it more smart (for example wait for a load decrease to start more node or wait X seconds between each launch).

**Comment by danieldemers** [comment]
Is this question related to my question? 

https://www.gns3.com/qa/operation-canceled-iou-start-sto

**Comment by noplay** [comment]
Yes I think it could fix this kind of situation. In theory emulator should just be slow on startup but I suspect some like IOU to crash at startup when the load is too big.

**Comment by grossmj** [comment]
This will help solve strange issues and improve the overall stability. For instance see https://github.com/GNS3/gns3-server/issues/488
