### ISSUE TITLE
Icon for project and appliances

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1213]

**Comment by grossmj** [comment]
New great icons have been created!

**Comment by danieldemers** [comment]
Got a preview?

**Comment by grossmj** [comment]
![gns3_project](https://cloud.githubusercontent.com/assets/4752614/15036998/e87b7876-1253-11e6-88ab-6d468cc3f24d.png)

![gns3_appliance](https://cloud.githubusercontent.com/assets/4752614/15037000/ea158f78-1253-11e6-9155-2747769356ed.png)
