### ISSUE TITLE
Text  color in tab for charcoal style are dark on dark

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1214]
![capture d ecran 2016-05-02 a 11 16 37](https://cloud.githubusercontent.com/assets/345437/14951197/70fc2190-1057-11e6-9cde-ad5d2597764d.png)

**Comment by grossmj** [comment]
Clean :+1: Other styles should be moved to a file too.

**Comment by noplay** [comment]
At this time they are empty :P But I think we can make something cleaner for theme support
