### ISSUE TITLE
Hide the GNS3 VM in server summary when used as a remote server

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1218]

**Comment by danieldemers** [comment]
What is the purpose in hiding it? Is it a worry of having both a GNS3 VM and a GNS3 VM running as  remote server?

**Comment by grossmj** [comment]
I do not understand the final goal too.

**Comment by noplay** [comment]
Actually we see it twice:
* one as remote server
* one as GNS3 VM

**Comment by noplay** [comment]
Exemple here:
![capture d ecran 2016-05-06 a 11 57 15](https://cloud.githubusercontent.com/assets/345437/15069995/bbacae8a-1381-11e6-8a15-e27968c96057.png)

The 127.0.0.1:8001 and the GNS3 VM is the same server.
