### ISSUE TITLE
GNS3 v1.5: device "Configure"  doesn't work.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1219]
[http://hpnouri.free.fr/misc/device-property.gif](http://hpnouri.free.fr/misc/device-property.gif)

> 2016-05-03 19:23:42 DEBUG analytics.py:70 Ignore call Node Properties Dialog to Google Analytics because of rate limiting
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/graphics_view.py", line 947, in configureActionSlot
>     self.configureSlot(items)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/graphics_view.py", line 646, in configureSlot
>     node_properties = NodePropertiesDialog(items, self._main_window)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 54, in __init__
>     self._loadNodeItems()
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 94, in _loadNodeItems
>     self.showConfigurationPageSlot(item, 0)
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/dialogs/node_properties_dialog.py", line 127, in showConfigurationPageSlot
>     page.loadSettings(item.settings(), item.node())
>   File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.5.0dev2-py3.4.egg/gns3/modules/docker/pages/docker_vm_configuration_page.py", line 67, in loadSettings
>     self.uiConsoleHttpPortSpinBox.setValue(settings["console_http_port"])
> KeyError: 'console_http_port'

**Comment by noplay** [comment]
It's an old project?

**Comment by noplay** [comment]
(I mean before today)

**Comment by AJNOURI** [comment]
Yes, I reopened a project created a couple of days ago.

**Comment by noplay** [comment]
I just test by dropping info from my .gns3 without trouble did you update
server and client?

**Comment by AJNOURI** [comment]
Yes, now it works fine.
Thanks Julien!
