### ISSUE TITLE
[Enhancement] Allow resizing of 2nd column in Nodes Preferences

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1220]
Sometimes, the node name is too big for the fixed size of that 2nd column as here:
![2nd column width](https://cloud.githubusercontent.com/assets/13176858/15049101/fccf1ff0-12ec-11e6-9a2e-f0f0d95fa61a.png)

**Comment by grossmj** [comment]
This has been implemented in 1.5 :)
