### ISSUE TITLE
[Enhancement] Multiple Topology Tabs & Switchover to public cloud when needed

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1222]
@grossmj @noplay Imagine how awesome those major enhancements would be:
- open another topology tab
- open another lab
- select & copy some parts - nodes/links/annotations - from first tab
- paste these parts into the second tab
- offer the possibility to link the selection from tab 1 to existing nodes in tab 2 when the nodes types are compatible with first tab and the ports are unused (or ask for confirmation to link to other port numbers)
- top enhancements:
  - offer the possibility to run each tab locally or remotely within some pre-configured public cloud
  - automatic switchover to some pre-configured public cloud to be able to run some tab(s) when local resources are exhausted or when some configured thresholds are crossed, and switchover to local resources when there are enough local resources again.

Am I dreaming? ;-)

**Comment by noplay** [comment]
Two topology tab in the GUI I think it will never happen due to deep choice in the GUI. But you can run two client

What do you think of having a node for topology to topology communication? https://github.com/GNS3/gns3-server/issues/517


For the last we have some stuff in place in 1.5 that could simplify this:
* import / export of project with support of the GNS3 VM
* the GNS3 VM could be a remote server

This mean you can switch from a local GNS3 VM to a remote. 

Only a small part of the requirements.

**Comment by jean-christophe-manciot** [comment]
On top of the major technical evolutions these enhancements mean, they would probably enable GNS3 as a company to close some important deals. Think about what would be the marketing consequences of linking GNS3 to Google Cloud Platform, digital ocean, VMware vCloud Air, Amazon AWS, Microsoft Azure... What is your take on this @stephenguppy ?

**Comment by stephenguppy** [comment]
If enough interest from the GNS3 community, its easy for us to "band
together" and lower pricing for the end user - making it cheaper for the
user to just use us than to try it on their own.

On Fri, May 6, 2016 at 11:49 AM, Jean-Christophe Manciot <
notifications@github.com> wrote:

> On top of the major technical evolutions these enhancements mean, they
> would probably enable GNS3 as a company to close some important deals.
> Think about what would be the marketing consequences of linking GNS3 to
> Google Cloud Platform, digital ocean, VMware vCloud Air, Amazon AWS,
> Microsoft Azure... What is your take on this @stephenguppy
> <https://github.com/stephenguppy> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/1222#issuecomment-217481389>
>



-- 



*STEPHEN GUPPY*
Chief Executive Officer/Co-Founder

T: 1.403.869.8361
E: stephen@gns3.com
Twitter <https://twitter.com/StephenGuppy> | LinkedIn
<http://www.linkedin.com/in/stephenguppy>

<http://www.linkedin.com/in/stephenguppy>909 17th Ave SW - 4th Floor
Calgary, AB, T2T 0A4
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by grossmj** [comment]
We could probably do some of these things when we have a web Ui.
