### ISSUE TITLE
Clean the MainWindow class

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1224]
The MainWindow class is starting to get huge (close to 2000 lines) and becomes hard to maintain. It should be split in multiple files. What the best approach to have something clean? Should we use standalone or MixIn classes?

**Comment by noplay** [comment]
Standalone class I think

Good candidate for a first clean:
* refactor & extract the style support
* save & load code

**Comment by grossmj** [comment]
Not perfect but it is already cleaner. Some re-factoring is going to happen anyway when the temporary project code is removed as well as a project is saved as you go. It will be the right time to clean even further.
