### ISSUE TITLE
REQ: Allow the locking of symbols/objects for both client and future Web GUI

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-gui#1228]
Allow you to LOCK symbols/objects in the topology. The only way to create groups of devices is with squares/circles. When I want to select a bunch of devices I have to ctrl click each one (Windows). I cannot use the mouse to select them or else I pick up all the text, background symbols, port text, misc object. 

This is also an issue when you want to move a group of devices BUT not surrounding devices. 

Allow you to LOCK a symbol and not be selected when you use the mouse in the below manner. Every object should be lockable.

![gns3 lock symbols](https://cloud.githubusercontent.com/assets/17289463/15103750/d090413c-1574-11e6-8e4e-99fea8d9e87b.png)

**Comment by adosztal** [comment]
Similar request in the [forum](https://gns3.com/qa/locking-picture-in-place).

**Comment by grossmj** [comment]
Implemented :)
