### ISSUE TITLE
Qemu image is copied to local directory even if not needed

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#1230]
Qemu images are added to the local /home/_user_/GNS3/images/QEMU directory even if I import the .gns3a appliance to a remote server, like this:
![add_appliance-remote](https://cloud.githubusercontent.com/assets/16632791/15121122/4788b7fc-1619-11e6-83c0-e6cda76b9249.png)

Obviously everything works fine if I delete those files from the local directory because nothing references them.

PS: This is not a high prio issue, just wanted to let you know.
PS2: I wasn't sure if I should open the issue here or in the gns3-registry, hope I made the right choice. :)

**Comment by noplay** [comment]
For me it's work as designed.

The image is copied at this place to allow futur usage for example the first time you use the appliance. 

Changing that require to push image on the remote server in the wiazard. We could do that but this add a lot of complexity in the import appliance code.

**Comment by adosztal** [comment]
I was thinking pushing the image from its original location when the appliance is used for the first time, not changing the wizard. However what you say is a safer way, the image will be available even if the user removes it from its original directory.

I think both ways are acceptable, it shouldn't cause a problem during everyday usage. In fact I wouldn't have noticed it if I haven't tested all those appliances for gns3-registry (my SSD is only 240G, a directory with 20G of qemu images was noticeable :)).

It's your call if you'll change this behavior later or keep the current one and close this issue.

**Comment by noplay** [comment]
I don't know if we should not garbage collect images on the remote server when not used to save space in the VM. Not sure about the best strategy.

**Comment by noplay** [comment]
Will be solved by #1590
