### ISSUE TITLE
ERROR: AttributeError: type object 'Qt' has no attribute 'AA_EnableHighDpiScaling'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1232]
Need to check Qt version itself not the PyQt version.

https://app.getsentry.com/gns3/gns3-gui/issues/128134992/

**Comment by noplay** [comment]
It's a property specifc to Qt 5.6?

**Comment by grossmj** [comment]
Yes

**Comment by noplay** [comment]
This mean we will need to to disable it if we detect a version < 5.6 for old linux :(
