### ISSUE TITLE
[2.0] Compute IDLE-PC from the wizard is broken

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1234]

**Comment by noplay** [comment]
I think it's hacky with the creation of a temp project. Probably the cause of the issue

**Comment by noplay** [comment]
Fixed it was a different error

**Comment by noplay** [comment]
Reopen because we have a direct call:
Legacy compute direct call /compute/projects/19833a5e-5254-4a90-bd26-53e4fe932bcb/dynamips/vms/49a38d30-6fc8-4d95-9b9b-484bdba32b71/auto_idlepc

**Comment by noplay** [comment]
This open a question.

When an API call is specific to an emulator should we expose an endpoint in the controller?

I see multiple solutions:
* A generic proxy to the compute node: /v2/computes/COMPUTE_NODE_ID/projects/PROJECT_ID/dynamips/vms/VM_ID/auto_idlepc
* A vm endpoint working only for this use case /v2/projects/{project_id}/vms/VM_ID/auto_idlepc
* A dynamips endpoint in the controller /v2/projects/{project_id}/dynamips/vms/VM_ID/auto_idlepc

Or a different solution if we refactor image code. On server when you create a template if the IDLE PC is missing we compute it (but big refactor).

**Comment by noplay** [comment]
And this the only case where we need a specific call for a VM :(

**Comment by grossmj** [comment]
A Dynamips endpoint on the controller should be sufficient.

**Comment by noplay** [comment]
Also we need to support /idlepc_proposals
