### ISSUE TITLE
[2.0] Import/Export config use direct call to the compute node

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1236]

**Comment by noplay** [comment]
We have import/export config code for:
* Dynamips
* IOU
* VPCS

I suspect some parts are dead code for this because we have multiple way to export / import.

Perhaps instead just using #1054 could work (perhaps with a small Qt interface for a native feeling of browsing).

**Comment by grossmj** [comment]
Related to https://github.com/GNS3/gns3-gui/issues/1042

**Comment by noplay** [comment]
I think it's not related to #1042, because #1042 is about exporting the whole project and this is about exporting just one config file

**Comment by noplay** [comment]
Hmm actually the way we manage config is a collection of dirty hacks to pass sometimes the file content, sometimes a path.

**Comment by noplay** [comment]
We also have issue with the startup config :( With stuff in the ~/GNS3/config, in the project folder an in the field _content

**Comment by noplay** [comment]
I think the feature actually don't work with remote servers (at least for VPCS)
