### ISSUE TITLE
A virtual file browser in the app

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1237]
A proposal, 

Display a panel that look  like the project files but better organized than what is really on disk and with only element you can interact with (config for IOU, Docker and Dynamips, volumes for docker). Also virtually you have access from it to file located on a remote host.

And in client we have a panel with the content browsable and editable:
![capture d ecran 2016-05-11 a 14 15 07](https://cloud.githubusercontent.com/assets/345437/15180593/d31f1616-1782-11e6-8a57-6fd37487dd47.png)

Also related to #1054, #1236 

We already have the file editor for docker.

**Comment by grossmj** [comment]
I think we can have something much better with a native web interface.
