### ISSUE TITLE
[2.0] updating a node via the Node properties doesn't work

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1239]
Reported by Jeremy

**Comment by noplay** [comment]
@grossmj  I tested and it's work for me. Perhaps I didn't understood where it is

**Comment by grossmj** [comment]
I get an error 400 everytime I edit a node and apply new settings. I tried with Qemu and Dynamips.

![error400_properties](https://cloud.githubusercontent.com/assets/4752614/15220803/0954d182-1826-11e6-91b2-efe1ee287c70.png)

**Comment by noplay** [comment]
Ok tested with VPCS and it's work. Seem to be a problem with the config
fields because they are special.

**Comment by noplay** [comment]
I will take care of this
