### ISSUE TITLE
1.5.0a2 existing server is not recognised

### ISSUE THREAD

**Issue by Sourg** [GNS3/gns3-gui#1240]
project has the following server in settings:
```
        "servers": [
            {
                "host": "gns3server",
                "id": 1,
                "local": false,
                "port": 3080,
                "protocol": "http",
                "user": "",
                "vm": false
            }
        ]
```

gns3_gui.conf:

```
        "remote_servers": [
            {
                "host": "gns3server",
                "password": "",
                "port": 3080,
                "protocol": "http",
                "url": "http://gns3server:3080",
                "user": ""
            },
```

Result:
![screen shot 2016-05-13 at 03 29 12](https://cloud.githubusercontent.com/assets/1923704/15234524/523d0320-18bb-11e6-8126-7b067ec881a6.png)

**Comment by fz420** [comment]
why 3080???
`GNS3 management console.
Running GNS3 version 1.5.0a2 on Windows (64-bit) with Python 3.5.1 Qt 5.6.0.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> GNS3 VM server initialized http://unset:3080
GNS3 VM IP address set to 192.168.59.131
GNS3 VM is started and server is running on 192.168.59.131:3080
Could not connect to GNS3 server 192.168.59.131:3080 (please check your firewall settings)
WaitForVMWorker thread stopping with an error: Could not connect to GNS3 server 192.168.59.131:3080 (please check your firewall settings)
Could not connect to GNS3 server 192.168.59.131:3080 (please check your firewall settings)
Starting local server process with "D:\Program Files\GNS3\gns3server.exe" --host=192.168.59.1 --port=8000 --local --controller --log="C:\Users\lite7\AppData\Roaming\GNS3\gns3_server.log" --pid="C:\Users\lite7\AppData\Roaming\GNS3\gns3_server.pid"
Local server process has started (PID=8580)`

**Comment by noplay** [comment]
Issue confirmed

**Comment by noplay** [comment]
Fixed in git

Thanks for the report  @Sourg
