### ISSUE TITLE
REQ : interface to capture

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1256]
Hi

We can't put packet capture with wireshark on interface of VirtualBox after VM was started
We can't put packet capture on interface of dynamips device (Cisco router,...) before device was started
I don't know for qemu and other

Can you order the list of network interface to capture : first the "good" interfaces ( ethernet switch, stopped VBox, vpcs,...) and after "bad" interfaces (started VBox....) ?
So the default choose of box for packet capture will be the good one to work

**Comment by noplay** [comment]
Capture will be improved in 2.0.

**Comment by grossmj** [comment]
I think we can add 2 small improvements:

- Favour a capture on the cloud side because it can be started dynamically.
- Have an option to overwrite an existing pcap file. If you start a capture a second time on the same link you will get previously capture traffic in Wireshark.

**Comment by Raizo62** [comment]
> If you start a capture a second time on the same link you will get previously capture traffic in Wireshark.

Just for info : often, we will like to clear the interface of capture of wireshark. We don't want see the last captures
But, i believe you can't do something

**Comment by noplay** [comment]
I think the 2.0 behavior is to reset the capture if you stop and start it again.

**Comment by grossmj** [comment]
Let's delete the previous capture file by default.

**Comment by noplay** [comment]
Checked and in 2.0 it's this behavior.
