### ISSUE TITLE
Unsaved projects -make the json file available to the user via some public variable 

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1257]
Let's say I have created a project which I have not saved yet, and I do not intend to save. Would it be possible to provide the user a way to access the json file corresponding to this topology so that it can be used in a script ?

**Comment by noplay** [comment]
Hi,

What is your use case?

We plan to change the save to a system in 2.0 saving each time you make a modification. Because current system create too much trouble. For example when you change the data in a QEMU VM this change is immediate, but your topology change will you only be save on disk when you save. The result disk and topology are unsync.

**Comment by 1001QAdotNET** [comment]
I want to use my script -AutoIP4GNS3- to configure an unsaved topology

**Comment by noplay** [comment]
This mean if you have the warranty that .gns3 is always the sync with what
is on screen it's work for you right?

**Comment by 1001QAdotNET** [comment]
I have not run into the problem that you are mentioning above.
My problem appears when I create a fresh new configuration that I have no intention to save, it is just a quick test. My script takes a .gns3 file as input but since I don't plan to save it I will not have one so I need to access the topology file that GNS3 has in memory for the unsaved configuration

The other problem that this will solve for me is this: it will be a alot easier for my script to get the topology that GNS3 has in memory for two reasons:
-I will have to allways point my script to a single point (the variable that you might make available)
-when I change the topology on the fly, I would like to be able to run the script against it, and not to have to save, and then run the script using the new config.

**Comment by noplay** [comment]
2) Since the manual save will disappear for auto save at each action the problem will be solved
