### ISSUE TITLE
[1.5.0a2] Unable to select remote server when importing appliance

### ISSUE THREAD

**Issue by Sourg** [GNS3/gns3-gui#1258]
Hello!
I am using 1.5.0a2, I am trying to import appliance to GNS3, particularly ASAv and I am unable to select remote server, my first remote server is chosen automatically and the option is greyed out, so I can't select another one.
Sorry, I can't attach a screenshot, because it contains some sensitive information.

**Comment by noplay** [comment]
I confirm the issue the select box is not enabled when you select remote server

**Comment by noplay** [comment]
Thanks it's fixed in next release
