### ISSUE TITLE
REQ: Two Views in GUI - Logical vs Physical (Enhancement)

### ISSUE THREAD

**Issue by danieldemers** [GNS3/gns3-gui#1259]
Hello, 

For 2.0 or later I think it would be good to add a second view that at first I imagine would be built manually by the user but later may be able to be automatically built if the logic is created. The purpose is your physical network now a days is misleading quite often. With VRFs, SDN, and the various virtualization technologies you can be seriously mislead by the physical topology. 

A switch with several VRFs on a logical diagram could be many places in the diagram but physically just one with many connections attached to it. The main purpose is to show what is really happening but also clean up the topology...the physical topology often gets really messy with the lack of curved links and other topology tools. This would be one more tool in the toolbelt. You should be able to work solely in the logical top once it was built (right click, start/stop, etc...all the same features). Just not modify links etc..maybe also modify links...lots to think about.

The second view (logical) would use the same constructs as before but allow duplication in device names and I imagine other parameters that would be discovered once you started down this path. However, changing the logical diagram should not effect the physical one (the true one) at first...again lots to consider as you start to think about it. 

You would be able to switch between them seamlessly. 

Thoughts?

-Dan

**Comment by noplay** [comment]
I have no idea how this could be done automatically because GNS3 view only the physical stuff and the logical stuff require a deep knowledge of each system.

But I see your point and how this could be usefull

**Comment by grossmj** [comment]
Yep, this is huge. Don't really know how we could do that.

**Comment by danieldemers** [comment]
At first manual, no automatic path generate/device/link placement.

I admit the deep knowledge part makes the "auto" part of it very difficult. I think it should be manual at first and possibly the community later can assist with the deep knowledge part via plugins/logic that the community could contribute etc...

The manual creation of the logical diagram should allow you to import all the currently configured physical devices into your logical topology 1 by 1 or all at once then let you manipulate links. Also allow you to duplicate a device in case it exist in multiple places in your topology.

* Think VIRL Design. The physical topology allows you to place items down and connect them as they are but then allows you to move to a logical and do the same thing except what you do there only has visual benefits...not configuration benefits. 

These devices you import cannot be modified in this topology and they simply inherit the variables/config/etc. from the physical topology. You should be able to work out of the logical view mostly but if you want to change physical connections then you must go physical. However, in the Logical you should be able to change links but they would be a view only change....where you adding a link is an assumption you know it matches the physical...at first its your responsibility to get it right. Meaning links in the logical are for your viewing benefit only and not actual connections.

**Comment by danieldemers** [comment]
Once plugins are added I imagine people could spend some time to create  a parser plugin that could read the routing table, arp table, CAM table, bgp table, etc...this is already done in several open source projects. I do not think the GNS3 team should be responsible for this part. Just to give the community a canvas to paint on and manipulate. 

=)

**Comment by gcasella** [comment]
The only thing that I could think of that may be similar to this is what unetlab has done with adding a picture into the topology and allows you to map out each device to their physical counter part.

For example, one tab in GNS3 would be your Physical (normal GNS3 topology) another tab can be the optional Logical view of your topology which could be imported via a PNG, JPEG, etc. and each device in your picture be mapped to the physical counter-part to allow for console access to the device. 

Or, introduce some feature in the Logical screen giving the empty canvas for users to put anything they want in it, just like they do with visio. 

I may be completely off to what the original post was implying but it's a thought.

**Comment by danieldemers** [comment]
Good thought but I agree there may be a misunderstanding. A picture is not the proper solution. The idea is just like Cisco 360 or even the real CCIE lab or the numerous examples of why logical is better than physical, there is a single physical topology and multiple logical topologies. I can build out a physical topology and then configure it to function in many different ways...allowing the user to view what is actually going on versus what is physically going on. This is why a picture is useless for this because that virtual topology can change very easily...forcing the user to hop back into visio would be ugly to regenerate a picture with your changes.

The idea is to actual represent what IS happening in the network. Forget Cisco for a moment. Think of F5s or other Content Delivery Gateways (used to be called Load Balancer's)...they are not just a port on one side and another port on the backside...they can have complex routing happening within them and even switching for that matter. 

The required part for this to work is that you can work off of the logical diagram. You can right click, console, reset, power on/off...configure etc...but not change the physical connections as that is obfuscated from your view. You would indeed have two tabs or simply a physical/logical toggle where you view one or the other. 

The end result would be a topology. It DOES NOT HAVE stock routers/switches/QEMU devices. Instead it has access to only the devices you have deployed in your physical topology. You can drag and drop a device multiple times (think switches with VLANs or VRFs...it can exist multiple places). and build out links and connections. The devices themselves are duplicates of the physical topology. However, the only think in the logical diagram that DOES NOT matter is the links....you just putting them there for visual assistance. 

Its hard to explain via text but the idea is trying to bring GNS3 closer to next gen networks and getting away from physical networks...you gotta have the physical but it should not be the focus.

**Comment by noplay** [comment]
I have the feeling that the logical topology will depend of what your are using.

For example if I use openflow I want my logical topologies build with this informations. And in this case the best tools is the SDN controller interface.

GNS3 run on physical level we have no bypass access to the nodes internals (except for IOU and dynamips where we know how to inspect the NVRAM). For example for F5s we can not get this information directly we need to connect something to our virtual network and ask the F5s api for information and for that the F5 need to be properly configure to expose this informations.

That's why for me it's the job for a network visualisation tools, it's not specific to GNS3. Because the same tools can be used in GNS3 and in your real network.

**Comment by 1001QAdotNET** [comment]
I am currently trying to figure out a way to map the overlay networks for two data centers. I will also have to look into F5 configs. If I figure out how to do it I will get back here.

**Comment by grossmj** [comment]
We will not implement it in the Qt interface.
