### ISSUE TITLE
Enhancement:  zoom percentage indicator in the status bar

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1263]
A zoom percentage indicator in the status bar would be very useful when zooming in  and out a topology.

![screenshot - 240516 - 11 02 39](https://cloud.githubusercontent.com/assets/1716020/15498428/e6a2cada-219f-11e6-960e-a0e191a71ea1.png)

**Comment by noplay** [comment]
First 2.1 new feature merged :)
