### ISSUE TITLE
1.5 broken on Windows 7

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1266]
The runtime for visual studio 2015 is missing

https://gns3.com/discussions/gns3-1-5-0-beta-1-released

**Comment by grossmj** [comment]
As recommended on https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/ I have included the Visual Studio 2015 VCRedist package in the installer. It will install the necessary DLLs depending on the Windows version.

**Comment by grossmj** [comment]
Only "downside": the all-in-one installer is 14Mb larger ;)
