### ISSUE TITLE
BUG : config of Cisco Router with added slot

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1267]
Hi

I put on the topology a Cisco Router (C3725)
His config file is ok : (file: GNS3/projects/untitled/project-files/dynamips/configs/i1_startup-config.cfg)

I modify his slot-1 from empty to NM-1FE-TX
His config file is almost empty :
>------

!
!

>-------

**Comment by noplay** [comment]
With which version of GNS3 ? I think it's fix in the 1.5beta

**Comment by Raizo62** [comment]
I use the last 1.4.

I will try to test with 1.5 to confirm.

Sorry.

**Comment by noplay** [comment]
No problem, 1.5 are beta it's normal that you didn't test with it.

**Comment by grossmj** [comment]
I confirm that is a major bug fixed in the latest 1.5 beta 1: https://gns3.com/discussions/gns3-1-5-0-beta-1-released
