### ISSUE TITLE
[ 1.5.0b1] Issue when deleting a running container.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1269]
I got the message that cannot delete a running container, but it does it anyway

![screenshot - 280516 - 00 16 40](https://cloud.githubusercontent.com/assets/1716020/15623944/662fe16e-247c-11e6-952e-c5a3e1966546.png)

> 2016-05-28 00:14:18 DEBUG vm.py:101 socketplane/openvswitch-1 is being deleted
> 2016-05-28 00:14:18 CRITICAL __init__.py:94 A link cannot be removed because dvpc-1 is running
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==1.5.0b1', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 477, in mousePressEvent
>     self._showDeviceContextualMenu(QtGui.QCursor.pos())
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 717, in _showDeviceContextualMenu
>     menu.exec_(pos)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 1501, in deleteActionSlot
>     item.node().delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/vm.py", line 103, in delete
>     self.delete_links_signal.emit()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/items/node_item.py", line 209, in deleteLinksSlot
>     link.delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/items/link_item.py", line 116, in delete
>     QtWidgets.QMessageBox.critical(self._main_window, "Connection", "A link cannot be removed because {} is running".format(self._source_item.node().name()))
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 94, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())
> 2016-05-28 00:14:19 CRITICAL __init__.py:94 A link cannot be removed because socketplane/openvswitch-1 is running
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==1.5.0b1', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 262, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 477, in mousePressEvent
>     self._showDeviceContextualMenu(QtGui.QCursor.pos())
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 717, in _showDeviceContextualMenu
>     menu.exec_(pos)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 1501, in deleteActionSlot
>     item.node().delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/vm.py", line 103, in delete
>     self.delete_links_signal.emit()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/items/node_item.py", line 209, in deleteLinksSlot
>     link.delete()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/items/link_item.py", line 116, in delete
>     QtWidgets.QMessageBox.critical(self._main_window, "Connection", "A link cannot be removed because {} is running".format(self._source_item.node().name()))
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 94, in critical
>     log.critical(message, stack_info=LogQMessageBox.stack_info())
> 2016-05-28 00:14:21 DEBUG http_client.py:576 DELETE http://127.0.0.1:8000/v1/projects/88bcd7a8-270b-4aa2-9570-3d2fb92fee6a/docker/vms/1b6d7e0d-1264-4b0a-8a61-5ee23d058997 {}

And cannot delete link because it consider the container not deleted

![screenshot - 280516 - 00 17 13](https://cloud.githubusercontent.com/assets/1716020/15623946/6e394882-247c-11e6-8a8b-38dd6fdae7bf.png)

Though the container is not there:

> docker ps 
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
> 967c26c2d7fb        dvpc:latest         "/gns3/init.sh /bin/s"   5 minutes ago       Up 4 minutes                            mad_liskov
> 326904cdaf35        dvpc:latest         "/gns3/init.sh /bin/s"   5 minutes ago       Up 4 minutes                            trusting_meitner

**Comment by noplay** [comment]
Confirmed
