### ISSUE TITLE
Is GNS3 GUI compatible with the Windows COM model?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1271]
Hi guys

Excuse my ignorance, I am looking for a way to automate things like adding labels to links and other cosmetic things and I just learned that the COM objects can be used for scripting or interacting with an application via the COM model.

I am trying to avoid hours of digging by getting an answer from the programmers, I am just an network engineer with some Python skills :-)

**Comment by noplay** [comment]
No it's not compatible or we don't know how to do it.

For label, links and all cosmetic stuff you will need to wait 2.0. We will provide an API for that.
