### ISSUE TITLE
User miss the button "Console to all the devices"

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1272]
In order to start a console session with all the devices in your tiopology you either click on each one of them or you press Ctrl+A (select all) and then go through the Devices --> Console
These could be reduced to one click on a button in that tool bar

**Comment by noplay** [comment]
It's not this button?
![image](https://cloud.githubusercontent.com/assets/345437/15642350/05d7422c-2647-11e6-800d-3d5e86efbfc0.png)

**Comment by 1001QAdotNET** [comment]
Damn..., I missed that :-)
Then you do not have a consistent GUI design. A user who does not bother to read the help (like me :-( ) will look for the same icon like the one available via the Device menu ... 
And you wouldn't expect this separation bar here
 ![](https://i.imgur.com/meoF57Q.png)

**Comment by noplay** [comment]
All the icon are more minimal in the toolbar in order to have a cleaner interface. 

I move the issue to 2.0 to see if something should be done to improve that.

**Comment by 1001QAdotNET** [comment]
Sure, thanks for the help, I am OK now but the above can still be improved if you feel that it is needed

**Comment by noplay** [comment]
Thanks for the feedback

**Comment by 1001QAdotNET** [comment]
sure, my pleasure to help and to give something back for this great program

**Comment by grossmj** [comment]
We should apply the theme to the contextual menu icons too.

**Comment by grossmj** [comment]
Only thing left is to maybe create some icons for the legacy style...

**Comment by grossmj** [comment]
Icon styles should be consistent in the contextual menu now.
