### ISSUE TITLE
must select server when i have only one

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1276]
Hi

On GNS3 1.5

I don't use GNS3 VM. I use only local server.

When I put an ethernet switch, i must choose an server.

And why do i see "GNS3 VM" into Servers Summary ?

**Comment by noplay** [comment]
Could you share your gns3_gui.conf?

**Comment by Raizo62** [comment]
it is an empty starting config with only Cisco Router : 

[gns3_gui.conf.txt](https://github.com/GNS3/gns3-gui/files/291941/gns3_gui.conf.txt)
