### ISSUE TITLE
button "New appliance template"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1277]
Hi

The button "New appliance template" is it very usefull on gui ?

We use it at first time to configure GNS3 (we can also use Edit/Preferences).

After, we don't use it but it will be always on the first view....

**Comment by noplay** [comment]
For me this button will help new comers to find how to add. The fact you need to go in preferences to add new appliance is not clear.

**Comment by Raizo62** [comment]
I understand.
But the students risk to click on button just to experiment ;-)

Can we have an option to desactivate/activate this option ? option activated by default

**Comment by grossmj** [comment]
Unfortunately we don't really want to clutter the current Ui, more the opposite.

**Comment by noplay** [comment]
It's the goal push them to experiment :p 

We hope to reduce the support requests from people who don't find how to add router/VM...

For the option I agree with Jeremy we try to streamline the UI to simplify life (without blocking advanced usage) and limit issues with people clicking on every options and after don't remember what they have done.

**Comment by Raizo62** [comment]
> imit issues with people clicking on every options and after don't remember what they have done.
I understand and i am agree.

And an option into the config file without check into the gui ? :-)

**Comment by grossmj** [comment]
Here it is. You will have to add/change the option in gns3_gui.conf

```
    "MainWindow": {
        ...
        "hide_new_appliance_template_button": true,
        ...
     }

```

**Comment by Raizo62** [comment]
Thanks :-)

But, I ask me if it will not be better to remove this button and to add it into edit menu under Preference menu ?

**Comment by noplay** [comment]
If we do that the button is too much hidden. We have a first time experience problem with people who don't read the doc and put it here will help them to understand they need to create stuff before using them.

**Comment by Raizo62** [comment]
> people who don't read the doc

always ;-)

You think even if the button is into the edit menu, not into the preference menu ?
(This is just  a question)

**Comment by ehlers** [comment]
Honestly, I like that button.

But I think it looks, that it's only useful for adding appliances. Only after you hit the button, you see, that it can add all sorts of router/VMs/container.

I suggest to change the text nearby the button to "New router/VM/container".

**Comment by noplay** [comment]
Actually we use the word "appliance template" 


What do you think @grossmj ?
