### ISSUE TITLE
[2.0] Allow to connect to remote controller

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1280]
Actually we support only the local controller. 

Probably something we need to push to 2.1

Actually not supported:
- [x] Choice of the controller url
- [x] Support for GNS3 profil (local profile, remote profil...)
- [x] Remote capture
- [x] GNS3 VM control
- [x] Hide some options in file menu when controller is remote
- [x] Hide some options in preferences when controller is remote
- [x] List of devices

**Comment by grossmj** [comment]
Will see if we have time to do it in 2.0. I would say it is not a blocking issue.

**Comment by noplay** [comment]
Now we have the list of devices

**Comment by noplay** [comment]
I think without that we will have an issue. How to handle people who use remote server only?

**Comment by noplay** [comment]
You can now in the settings change the url of the controller

**Comment by noplay** [comment]
Remote capture is OK

**Comment by noplay** [comment]
Choice of profile ok
