### ISSUE TITLE
GNS3 VM 1.5.0 RC1

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1282]
Is there a need to use the "new" GNS3 VM 1.5.0 RC1 with the latest release of GNS3 application,  GNS3 1.5.0 RC1?  It seems the GNS3 app cannot start GNS3 VM after cloning and upgrading GNS3 VM.
Thanks!

**Comment by noplay** [comment]
No the vm should work after upgrade.

Could you share a screenshot of the information screen of the VM?

**Comment by noplay** [comment]
What are you using VirtualBox or VMware?

**Comment by jtorri** [comment]
Windows 10 Pro X64 and VMWare Workstation 12
When starting GNS3 1.5.0 RC1 and it tries to start GNS3 VM 1.5.0 RC1:

Could not execute vmrun: Command '['C:\\Program Files (x86)\\VMware\\VMware Player\\vmrun.exe',
 '-T', 'ws', 'start', 'C:\\VirtualMachines\\VMWareWorkstion10\\GNS3 1.5.0 RC1\\GNS3 VM 1.5.0 RC1.vmx']' 
 returned non-zero exit status 4294967295 with output 'Error: Unknown error'

Make sure the correct product (Fusion, Workstation or Player) is selected in Preferences / VMware

If starting VMWare and then start GNS3 1.5.0 RC1 the above error does not occur.  
But when start project containing VMWare virtual machines the following error occurs:

Server error from http://192.168.41.1:3080: XPPro-1: vmrun has returned an error: Unable to connect to host.
Error: The operation is not supported for the specified parameters

Server error from http://192.168.41.1:3080: Windows Server 2016 T5: vmrun has returned an error: Error: Unknown error

Server error from http://192.168.41.1:3080: lubuntu14.04_32bit: vmrun has returned an error: Error: Unknown error

This error did not occur with GNS3 1.5.0 beta 1

**Comment by noplay** [comment]
Can you run in a console:
```
"C:\Program Files (x86)\VMware\VMware Player\vmrun.exe" -T ws  start '"C:\VirtualMachines\VMWareWorkstion10\GNS3 1.5.0 RC1\GNS3 VM 1.5.0 RC1.vmx"

**Comment by jtorri** [comment]
Helpful advice.  Here's the output.  It seems the path is wrong but it sure looks right to me.  Will spend some time trying to figure it out.  As always, many thanks!

C:\WINDOWS\system32>"C:\Program Files (x86)\VMware\VMware Player\vmrun.exe" -T ws  start '"C:\VirtualMachines\VMWareWorkstion10\GNS3 1.5.0 RC1\GNS3 VM 1.5.0 RC1.vmx"

Error: Cannot open VM: C:\WINDOWS\system32\'C:\VirtualMachines\VMWareWorkstion10\GNS3 1.5.0 RC1\GNS3 VM 1.5.0 RC1.vmx, The virtual machine cannot be found

**Comment by jtorri** [comment]
![vmwarepreferences](https://cloud.githubusercontent.com/assets/10285348/15752160/c60b118e-28ba-11e6-9691-2415040999e7.jpg)
![gns3vmserver](https://cloud.githubusercontent.com/assets/10285348/15752197/fb274f2c-28ba-11e6-9d26-26f4b6de2f51.jpg)

**Comment by noplay** [comment]
The path C:\VirtualMachines\VMWareWorkstion10\GNS3 1.5.0 RC1\GNS3 VM 1.5.0 RC1.vmx exists on your disk?

**Comment by jtorri** [comment]
That's REALLY embarassing!  The path was wrong.  However, once I fixed the path now I get the following error as GNS3 app tries to start the GNS3 VM.
Could not execute vmrun [WinError 193] %1 is not a valid Win32 application

**Comment by jtorri** [comment]
BTW, if I switch back to GNS3 1.5.0 BETA 1 all works.

**Comment by jtorri** [comment]
Correction, I think the problem is related to upgrading from VMware Workstation 11 to 12.  But, not thinking clearly at the moment.  Gonna let this go for a while until I've tried a few things.

**Comment by noplay** [comment]
Perhaps you have a problem with the VIX api installed on your PC. But it's strange it should be provided by VMware workstation.

**Comment by jtorri** [comment]
My latest effort.  Corrected the path issue.  Reinstalled VMWare workstation 12.  Used the provided cmd file to recreate all the additional vmnet NICs.  Cloned the 1.5.0 beta 1 VM to 1.5.0 RC1.  Edited the GNS3 ini files to reflect the new paths to GNS3 app files. Started GNS3 1.5.0 RC1 and here's whatI got.
![generalpreferenceserror](https://cloud.githubusercontent.com/assets/10285348/15761606/1e14e22a-28e7-11e6-9482-80cbe974554f.jpg)

When I start GNS3 1.5.0 RC1 VM from within VMWare Workstation 12 runs fine.  So yea, the issue appears to be the GNS3 1.5.0 RC1 app starting the GNS3 1.5.0 RC1 VM or any VMWare virtual machine for that matter.

**Comment by grossmj** [comment]
Looks like you had VMware player installed previously and now you installed workstation pro. Go to the GNS3 preferences and update the path to vmrun to the one located in your Workstation Pro directory.

![vmware_preferences](https://cloud.githubusercontent.com/assets/4752614/15761884/dc11c834-28d7-11e6-863e-86be1b660ced.png)

**Comment by jtorri** [comment]
Tried that.  No luck.  It seems gns3vmnet.exe just hangs as well.  Bottom line, gns3 with VMware workstation 12 is dead in the water for me.  Don't remember being quit this far from functional gns3.  Clearly I did something(s) wrong!

**Comment by jtorri** [comment]
At least one problem source identified.  VMWare Workstation 12 is KNOWN to have nearly predictable problems installing and initializing virtual network drivers on Windows 10. Reinstalled VMWare several time and ran repair several times before VMWare virtual network editor would not error out and gns3vmnet.exe would run successfully.  Still no luck running GNS3 but too tired to continue.  In the over 10 years I've used VMWare I have never before seen such sloppy work pushed out their door.

**Comment by grossmj** [comment]
I have seen similar issues with VMware Workstation Pro 12. Indeed, this version is problematic :(

**Comment by jtorri** [comment]
Well now time for a HUGE plate of "crow" for me.  Perhaps you've head if gns3 app is NOT run as administrator problems occur.  That was significant part of my problem.  The other was my Windows 10 OS needed to be repaired.  If anyone needs suggestions on how to do that I spent quite a while getting it done.  Believe I now have the technique down.  However, if you doubt my ability at logical thinking I understand.

**Comment by noplay** [comment]
Hmm I think the issue is if one time you start GNS3 as admin you can break some permission for ever in VMware.
