### ISSUE TITLE
GNS3 1.5.0rc1 doesn't launch VM in Worstation Pro properly

### ISSUE THREAD

**Issue by tineg** [GNS3/gns3-gui#1283]
Hi,

First, thank you for your great work !
Everytime I try to start a VMware VW with GNS 1.5.0, Worstation Pro begins to start normally, but as soon as it launches the VM, I have this message:
![2016-06-02_21h26_03](https://cloud.githubusercontent.com/assets/11416706/15758847/a745602c-290c-11e6-8c1f-71ab7fbd12dd.png)

But my OS is Windows 7.
Strangely,, if I open Worstation before lauching the VMware VM in GNS3, then everthing seems to work fine (I didn't manage to find the networks settings in GNS3 or Worstation that works at the moment).

PC: DELL E6530
OS: Windows Seven SP1
RAM: 8GB
GNS3 GUI version: 1.5.0
GNS3 Server: Local Server
VMware VIX: installed
Workstation 12 Pro
VMware VM: ubuntu 16.04 64bits

**Comment by noplay** [comment]
Things that could explain the warning.

Do you have the lastest windows updates?

VMware is not launched in compatibility mode?

But I think VMware forum is better location for that error.

**Comment by tineg** [comment]
Hi,

Thank you for replying.
Do you have the lastest windows updates? ==> my Windows 7 is up to date since yersteday
VMware is not launched in compatibility mode? ==>no

Moreover I definitively didn't manage to establish the network connection between a VMware VM and a simple router. I inserted a generic switch between them and I tried almost all the available settings in VMware Virtual Network Editor.
As you said, I'll take a look on the forum for this bigger problem.

BR

**Comment by grossmj** [comment]
Hi,

Can you start cmd.exe and type "ver", please post the screenshot.

Thanks,

**Comment by tineg** [comment]
Hi,

Indeed it is strange. 
As I said, if Workstation is launched first the error does not happen.
 
![image](https://cloud.githubusercontent.com/assets/11416706/15762186/aadc3d2c-291c-11e6-9821-331302a636f4.png)

BR

**Comment by grossmj** [comment]
Strange indeed,

Have you upgrade to Windows 7  or is it a clean install?

**Comment by tineg** [comment]
Yes, it is a clean install provided by Dell.

**Comment by tineg** [comment]
OK, I just red that it's "A long-standing oddity of Windows".
Windows 7, for example, reported itself to software as being version 6.1. Windows 8 is 6.2, and Windows 8.1 is 6.3.
Current public builds of Windows 10 repeat this trend—they purport to be version 6.4

http://arstechnica.com/information-technology/2014/11/why-windows-10-isnt-version-6-any-more-and-why-it-will-probably-work/

**Comment by grossmj** [comment]
I was away for a few days. Do you still have the issue?

**Comment by grossmj** [comment]
More a VMware issue I think. I will close this.

**Comment by tineg** [comment]
Hi,

Obviously, VMware doesn't fail when I start it manually but rather when
it'is launched by GNS3.
It's look like if GNS3 was using a check if what Windows version the host
is running the same way you sked me to perform the "show ver" command. As
Windows returns a version 6 whereas GNS3's stranging waiting a version 7 at
least, GNS3 refuses to launch the VM.

So I think it's sounds more like a GNS3 problem.

BR
Le 10 juin 2016 01:02, "Jeremy Grossmann" <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
What vmrun path do you have in GNS3 -> Preferences -> VMware?

**Comment by tineg** [comment]
C:\Program Files (x86)\VMware\VMware VIX\vmrun.EXE

For VIX the system path is:
C:\Program Files (x86)\VMware\VMware VIX

**Comment by grossmj** [comment]
What happens if you change the vmrun path to use the one provided by VMware Workstation? Should be  ```C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe``` by default.

**Comment by tineg** [comment]
Same issue

**Comment by grossmj** [comment]
Try to manually start the VM using vmrun.exe:

Start cmd.exe and execute the following:

``C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe -T ws start "C:\Users\You\Documents\Virtual Machines\ubuntu-16-04\ubuntu-16-04.vmx"``

Replace the path to the VMX file by the correct one.

Thanks :)

**Comment by grossmj** [comment]
@tineg any luck?

**Comment by tineg** [comment]
Hi,

Sorry for the delay.
The manual method works with no error message.

**Comment by noplay** [comment]
GNS3 is not running as admin?

**Comment by tineg** [comment]
Hello,

Is GNS3 running with admin rights?
Yes

**Comment by grossmj** [comment]
It is recommended that both VMware and GNS3 shound't run with admin rights.
