### ISSUE TITLE
[1.5 rc1] vnc doesn't close after container stop

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1284]
Shouldn't vncviewers close after containers stop (x11vnc servers down)?

![image](https://cloud.githubusercontent.com/assets/1716020/15767671/571d053a-294a-11e6-853f-e080656df0ae.png)

_Note: about vncviewer black screen, not sure if it is a bug. Will post here if you confirm it._

**Comment by noplay** [comment]
The VNC server is killed when the node is removed. So you can reboot a container without the need to reopen the VNC client (same for the telnet).

It's also for technical reasons because the server need to be create before the container in order to get the X11 socket.
