### ISSUE TITLE
[1.5.0b1] Delete vlan.dat for L2IOL during config import

### ISSUE THREAD

**Issue by Sourg** [GNS3/gns3-gui#1285]
Hi,
please delete **vlan.dat** for L2IOL in node folder when you import configs. 
Otherwise, vlan/vtp information can be inconsistent and you can then get logs like this:
*Jun  4 14:20:39.125: Domain name mismatch startup-config: CCIE, vlan database: INE.
*Jun  4 14:20:39.126: %SW_VLAN-4-BAD_STARTUP_VLAN_CONFIG_FILE: Failed to configure VLAN from startup-config.  Fallback to use VLAN configuration file from non-volatile memory

**Comment by grossmj** [comment]
Thanks, we will take care of this soon.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/313226786fb3ce2ddcde41396e14b93d16dc89d5
