### ISSUE TITLE
GNS3 1.5.0RC1 lubuntu NIC assignment modifed by gns3 app?

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1286]
Windows 10 Pro 64 bit. GNS3 1.5.0RC1.  Using GNS3 1.5.0RC1 VM (upgraded GNS3 1.5.0 BETA 1 VM). Have GNS3 topology that includes lubuntu 14.04 32 bit VMWare Workstation 12 virtual machines.  In VMWare Workstation I have set the lubuntu virtual workstation NIC to VMNET2. However, when I start the lubuntu client in GNS3 app the NIC assigned is changed (by the GNS3 app?) to VMNET 4.  Is this intentional or predictable or am I lost again?  This does not happen with an XPPro and a Windows Server 2016 client also included in the GNS3 topology.

**Comment by jtorri** [comment]
Batting zero today.  Seems another fluke of VMWare Workstation 12 or my ability. More likely the latter. Does not occur with Linuxmint 17 virtual machine.

**Comment by noplay** [comment]
It's depend if you allow full control of the network by GNS3 or not in the vm parameters.
