### ISSUE TITLE
Again....GNS3 1.5.0RC1 lubuntu NIC assignment modifed by gns3 app?

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1287]
i don't believe I have assigned full control to GNS3
![linuxmint2](https://cloud.githubusercontent.com/assets/10285348/15821733/ae659a88-2bbf-11e6-839f-3b0ad43f9a86.jpg)
![xppro2](https://cloud.githubusercontent.com/assets/10285348/15821738/b6554220-2bbf-11e6-97f1-eb45855ce963.jpg)

**Comment by jtorri** [comment]
This does not occur with the GNS3 1.5.0 RC1 VM.  It is the one virtual machine into which I have installed the VMware tools.  Perhaps that is significant.  Perhaps  not.  As you know there is an ongoing debate within and outside of VMWare whether to use the VMWare Tools or open-vm-tools-desktop and open-vm-tools-dkms. I have tried both with the same results.

**Comment by noplay** [comment]
Can you click on edit on the VM?

**Comment by jtorri** [comment]
Hope this is what you are asking.
![xpproedit](https://cloud.githubusercontent.com/assets/10285348/15841083/680f4130-2c1c-11e6-8d0e-fb553b35fb53.png)
![xpproedit2](https://cloud.githubusercontent.com/assets/10285348/15841087/6af806b6-2c1c-11e6-961a-dd36d80831ad.png)

**Comment by jtorri** [comment]
The topology
![topology](https://cloud.githubusercontent.com/assets/10285348/15841190/3ae3827e-2c1d-11e6-84ce-3152a6b91b7b.jpg)

**Comment by grossmj** [comment]
I am failing to see the problem. Can you tell me more? 

Thanks,

**Comment by grossmj** [comment]
@jtorri ping :)

**Comment by jtorri** [comment]
At work when you pinged.  Closed sounds good!

**Comment by grossmj** [comment]
I can re-open if you still have the issue.
