### ISSUE TITLE
Doctor failure with 1.5rc1

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1290]
https://gns3.com/qa/gns3-1-5-0rc1-error

**Comment by grossmj** [comment]
Cannot fix, post deleted :(

**Comment by noplay** [comment]
![image](https://cloud.githubusercontent.com/assets/345437/15956861/8a7282a6-2eeb-11e6-99a7-6175c58d0d53.png)

**Comment by noplay** [comment]
Found this in an email I received
