### ISSUE TITLE
GNS3 1.5.0rc1 error runtime 

### ISSUE THREAD

**Issue by luis11645** [GNS3/gns3-gui#1292]
windows 7 pro 64bits
when I open GNS3 gives me this error
api-ms-win-crt-runtime-l1-1-0.dll

**Comment by noplay** [comment]
Hi,

You need to apply all the windows update or wait for RC2 the dll will be provided.

Thanks

**Comment by grossmj** [comment]
@luis11645 can you install the following? https://www.microsoft.com/en-us/download/details.aspx?id=51682

Thanks,

**Comment by luis11645** [comment]
I'll do it and I tell you later

**Comment by grossmj** [comment]
@luis11645 how did that go?
