### ISSUE TITLE
Synchronize the status of an interface with the green/red dot displayed on the router

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1293]
if Ethernet 0/1 is down (administratively down) somehow that should be reflected in the color of the corresponding dot in the gui.

**Comment by noplay** [comment]
We can not really do that because it's inside the OS. What happen  inside is a blackbox for us we only see the hardware state.

**Comment by 1001QAdotNET** [comment]
are you referring to the network (i)OS?

**Comment by noplay** [comment]
Yeah it's inside IOS for CISCO stuff.

**Comment by 1001QAdotNET** [comment]
I agree, it is more complicated than it looks, especially if that applies to any type of appliance ... you are right. Thanks for clarifying that
