### ISSUE TITLE
Option to suspend the communication via a link from the gui

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1295]
as far as I can understand you have tunnels connecting various types of device interfaces
allow the user to disable a link (stop the communication via a tunnel) and reflect the status of the link by the color of that link (make it red let's say). The user should be able to enable the communication  after it was disabled

**Comment by noplay** [comment]
Yeah it's something we want to add. It's not easy because actually we don't have full control on the tunnel

**Comment by grossmj** [comment]
Should be easier now with all links running with uBridge.

**Comment by 1001QAdotNET** [comment]
I have not migrated to v2 yet. Are ytou talking about v2 here ? If yes can you describe the procedure,?
Is this a side effect of using uBridge or it is an on purpose build functionality ?

**Comment by grossmj** [comment]
GNS3 uses uBridge behing the scene. The option to suspend the communication will be implemented in version 2.1, not 2.0.

**Comment by 1001QAdotNET** [comment]
Does your this statement refer to the lastest 1.X version then?

> Should be easier now with all links running with uBridge.

**Comment by grossmj** [comment]
No, starting with 2.0 only.

**Comment by 1001QAdotNET** [comment]
OK thanks for the update

**Comment by noplay** [comment]
Should we implement that as a kind of filter?

**Comment by grossmj** [comment]
I am considering it however it would be like a black hole for guest OSes. Some emulators support disconnecting a link and this info is replicated in the guest OS (i.e. the state of network adapters are set to  'down'). For instance VirtualBox supports it via setlinkstate in VBoxManage. Possibility Qemu too via the monitor mode.

**Comment by noplay** [comment]
Since we support hotlink the guest os don't know if the cable is connected or not.

**Comment by noplay** [comment]
We can implement it in 2.1 as an API call shortcut in order to toggle frequency_drop with a parameter -1

And in the future we can improve it to properly cut the link at emulator level.

**Comment by grossmj** [comment]
Let's do this and see later if we can optimize at the emulator level.

**Comment by grossmj** [comment]
@noplay do you want to add the API call? I will look at optimizing it at the emulator level later.

**Comment by noplay** [comment]
I will add /suspend API call

**Comment by noplay** [comment]
Or perhaps a suspend in the update link API
