### ISSUE TITLE
Custom console does not seem to work properly

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1301]
Here https://community.gns3.com/discussions/gns3-1-4-4-stable-has-been-relea it says the custom console dialog will display an error message if the custom script is not correct

I am trying the most basic things and ...it is inconsistent with the above (no error message) and 
this command line C:\Utils\stg\stg.exe  works while C:\Python27\python.exe does not even start the interpreter or give an error message as stated in the link above

I am running 1.4.6
What is one supposed to do the execute a python script like below

C:\Python27\python.exe c:\Scripts\script.py %h %p

**Comment by noplay** [comment]
It's not ?
C:\Python27\python.exe c:\Scripts\script.py %h %p

**Comment by 1001QAdotNET** [comment]
Yeah that was a typo here in this post

**Comment by noplay** [comment]
How are you sure that python.exe is not starting?

**Comment by 1001QAdotNET** [comment]
Damn ...I expected to see a terminal window with the output of my script (I had a "print something" there. Now that you made me look again I checked the console and I could see the script working actually ...thanks a lot, I apologize for wasting your time, I did no realize that the script needs a terminal window (command prompt, or console) to print the output. Looks like I will need to get into PyQt...

**Comment by 1001QAdotNET** [comment]
Do you have any suggestion regarding a way I could see the output of my script while running the script this way?

**Comment by noplay** [comment]
Log to a file?

**Comment by noplay** [comment]
If you don't care of the look & feel a TK windows should be enough.

**Comment by 1001QAdotNET** [comment]
:-)) Thanks...I was looking for something "live" but that will do it! 
A multitab tail will probably solve the problem
I will go with PyQt because I need to go ahead with a couple of other scripts that need GUI, a good gui API
