### ISSUE TITLE
Ask to setuid ubridge only when require

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1302]
I think we could find a way to improve that on OSX. And ask to setuid ubridge only if user need it it could be much cleaner for users because most people don't use VMware.

**Comment by grossmj** [comment]
I believe we already ask for it (I tested yesterday). In 2.0 we use uBridge in the cloud to connect to real adapters, we need setuid or access to the BPF devices in /dev/bpf*

For vmnet interfaces there is no choice but to setuid I think.

**Comment by noplay** [comment]
We ask it at start not at first use. Could be scary

Le ven. 10 juin 2016 20:08, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Something to try http://www.bonusbits.com/wiki/HowTo:Setup_Wireshark_on_Mac_OS_X or more interestingly https://maymay.net/blog/2014/07/15/how-to-securely-configure-mac-os-x-for-network-packet-sniffing-with-wireshark/

**Comment by noplay** [comment]
It seem a cleaner way is to use:
http://www.performantdesign.com/2009/10/26/cocoasudo-a-graphical-cocoa-based-alternative-to-sudo/

With that the dialog use MacOS native system feeling less scary for user.

But it's not urgent

**Comment by noplay** [comment]
No we need ubridge for all of things no longer require
