### ISSUE TITLE
Add an option to see the server log in a dock as the Console dock shows at the bottom of the screen

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1305]
Right now in order to see what is going on on the server I have to ssh to it and tail the log. That forces me to keep a terminal session up all the time. It makes sense to have a tail of the log displayed as suggested in the title of this message

**Comment by 1001QAdotNET** [comment]
probably an easy way to do it is to open an ssh session in a dock and let the user do the tail or whatever he needs

**Comment by noplay** [comment]
What information do you need from the log?

**Comment by 1001QAdotNET** [comment]
I am seeing situations when the router crashes after I run a script against it. I can not post this info online but I can send you an example at a specified email address. I will explain the reasons why I can not post the info here

**Comment by 1001QAdotNET** [comment]
The above are not shown in the console deck but you can see them on the server log

**Comment by noplay** [comment]
Send the relevant log to developers@gns3.net if the router crash it's something we should show to every user.

**Comment by noplay** [comment]
You can also use GPG if you want it more confidential.

My key fingerprint:
A474 AF21 ACE5 BE35 574C  8C6A 0898 C847 4507 54FB

**Comment by noplay** [comment]
It's more an internal error than something we want to show to users I will reply to your mail.
