### ISSUE TITLE
[2.0] Blocked by "A node is still running, please stop it before closing your project"

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1308]
If server crash this block us and prevent us to change project or quit GNS3

**Comment by noplay** [comment]
But I don't see today a good reason to keep this warning in the client. The controller is smart and can close node when you close a project. What do you think @grossmj ?

**Comment by grossmj** [comment]
Let's remove it.

**Comment by noplay** [comment]
Removed
