### ISSUE TITLE
GUI crashes when disconnecting external monitors on OS X

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1310]
Hello team,
I have this problem that my GNS3 GUI crashes when I disconnect my external monitors on MBP running OS X El Capitan.
I suspect it is due to https://bugs.launchpad.net/ubuntu/+source/qtdeclarative-opensource-src/+bug/1450137
However I am not 100% sure it is indeed the root cause. 
Let me know if this can be fixed somehow as the issue is very annoying.
Thanks in advance!

**Comment by noplay** [comment]
Work fine for me :(  You have retina display?

Can you launch GNS3 with:
/Applications/GNS3.app/Contents/MacOS/gns3 --debug

And copy paste the output?

Thanks a lot.

**Comment by Sourg** [comment]
Hi Julien,
Yes, I have Retina. The crash is not 100% reproducible though.
When I get some time at work, I will test and update the thread.

**Comment by noplay** [comment]
I found a crash in PyQt not sure if it's related, they should release a new version with a fix but not ETA.

**Comment by dmfigol** [comment]
Hi Julien,
thanks for the update.
Do you still need me to reproduce the crash and collect debugs?

**Comment by noplay** [comment]
If you can launch GNS3 with:
/Applications/GNS3.app/Contents/MacOS/gns3 --debug

And give the output when it's crash it could help to be sure.

**Comment by dmfigol** [comment]
Hi Julien, I've more details.
I get crash in 80% cases but only when I disconnect two external monitors at the same time.
Requested output:
`2016-06-20 18:49:42 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=583a4f7f-f9e0-4c41-b3e0-24e9b7fb528b&aip=1&t=screenview&an=GNS3&av=1.5.0rc2&ua=Mozilla/5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_11_5%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20GNS3/1.5.0rc2&cd=New%20Project%20Dialog&ds=gns3-gui&sr=1680x1050&ul=en_us
Fatal Python error: Segmentation fault

Current thread 0x00007fff75272000 (most recent call first):
  File "gns3-gui/gns3/main.py", line 262 in main
  File "gns3-gui/gns3/main.py", line 281 in <module>
  File "/Users/gns3/Jenkins/workspace/Release MacOSX/OSX/../boot.py", line 46 in <module>
[1]    75780 segmentation fault  GNS3.app/Contents/MacOS/gns3 --debug`

+ OS X crash report in the attachment
[gns3_crash.txt](https://github.com/GNS3/gns3-gui/files/323893/gns3_crash.txt)

**Comment by noplay** [comment]
Can you try to disable the stats:
![image](https://cloud.githubusercontent.com/assets/345437/16206606/7990fe54-3729-11e6-91f3-8d6efb9cc58a.png)

**Comment by dmfigol** [comment]
Hi Julien,
sorry for late reply.
I just tried - it didn't help.

**Comment by noplay** [comment]
I push it to 1.5.2 and perhaps it will be for the 2.0. For the moment PyQT doesn't plan to release a new  version in the coming days and they will perhaps not release a fix for Qt 5.6 forcing us to a jump to Qt 5.7.

**Comment by noplay** [comment]
Upgrade will be include with 2.0 now that PyQt 5.7 is available. We will see if it's fix.
