### ISSUE TITLE
Make md5 hash checks for appliance imports case agnostic

### ISSUE THREAD

**Issue by jonhusen** [GNS3/gns3-gui#1311]
I modified some gns3a files for the images that I use. The md5 hashes I used in the files have upper case letters and won't let me upload my images. It would be nice if the ios image hash verification were case agnostic.

**Comment by noplay** [comment]
Not sure if it's a good idea to make it agnostic because it could break when used with other tools that would implement the format.

What do you think @grossmj ?

**Comment by noplay** [comment]
We could also check the file and show a warning (by embeding the JSON schema)

**Comment by grossmj** [comment]
Why don't we lower case the MD5 hashes by default?

**Comment by jonhusen** [comment]
If this isn't easy to implement, that's fine. I can go through my files and change the hashes. The tool I used to output the hashes gave me upper case letters, so I just pasted that into the gns3a file. I thought md5 was hex and case wouldn't matter.

**Comment by noplay** [comment]
@grossmj  My problem is not in the GNS3 gui, lower case is easy. But if we use the file somewhere else (the website or the webapp for example) we need to remember that the md5 need to be lower case before used.

**Comment by noplay** [comment]
Now I check the appliance schema, you will have an error if something is wrong
