### ISSUE TITLE
When I click on Console to all devices SecureCrt does not always start all the routers in a single tabbed window

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1312]
I have configured SecureCRT to start each session in a tab, within the same window
Most of the times it does that but quite often it does not do it and then I have to close all the sessions and click again on that button. When I click again most of the times it starts as expected.

**Comment by noplay** [comment]
I would say it's a race condition in SecureCRT  :( Do you have the issue even with recent version?

You can increase the delay before starting another console:
![image](https://cloud.githubusercontent.com/assets/345437/16081945/071daa88-3310-11e6-9ff9-b5845451893d.png)

But this feature seem broken

**Comment by noplay** [comment]
My bad it's a different setting:
![image](https://cloud.githubusercontent.com/assets/345437/16082211/db6e5ef4-3310-11e6-8aa7-fe7dab5ce932.png)

And it's work

**Comment by 1001QAdotNET** [comment]
yes settings are the default, I have not changed them

**Comment by noplay** [comment]
If you increase the time it's work?

**Comment by 1001QAdotNET** [comment]
I just tried 1000ms (1 sec) I still had one orphan window in one of four attempts
I will keep watching this and I will report back in a couple of days if this fixed the problem or at least improved the things

**Comment by noplay** [comment]
Thanks
