### ISSUE TITLE
Kill the sniffer when the user stops the sniffing

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1313]
Is it possible to Kill the sniffer when the user stops the sniffing on a certain link and the sniffing was started for that link?
This would be nice to have.

**Comment by noplay** [comment]
Not sure because often I start a capture / stop it and inspect it

**Comment by noplay** [comment]
After reflexion it doesn't seem a good idea. We can not know if people want to kill wireshark when they stop capture.

And even if we do that wireshark will block you asking to save the capture
