### ISSUE TITLE
REQ : bring console to front

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1315]
hi

Do you have implemented this functionality ? because I don't find where is it in code of GNS3. I find only the check.

I saw that this can be done with this tool with Linux with the linux program : wmctrl 
To show all windows : wmctrl -lp
To bring console to front : wmctrl -ia NumId

**Comment by noplay** [comment]
I agree I see no code related to that.

But I think this feature is not easy to do with all the different terminals, windows manager  and different way to use the terminal (tabbed, not tabbed) :( For me this could be a source of bugs.

A solution for you could be to replace the direct launch of the console by a shell script wrapper compatible with a specific console and windows manager that will do this.

I vote to cleanup the settings and remove this checkbox.

**Comment by Raizo62** [comment]
I believe that @grossmj said that it doesn't work with Linux into "old" legacy gns3. He didn't know why. I believe this worked on Windows. Or i didn't understood.

I suppose that wmctrl works with different terminals (but it isn't sure)
For tabbed terminal users, they can uncheck the option ;-)

But, Linux users must install "wmctrl".

The wrapper works well :-) but this is an another patch

**Comment by grossmj** [comment]
It is planned to bring it back in a future version, please see https://github.com/GNS3/gns3-gui/issues/847

In the meantime we can hide that option.
