### ISSUE TITLE
How to support lab instruction in 2.X

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1316]
In 2.X you could have a lab fully remote. In this context lab instructions are not available on your disk (even for local project this break the rules that only the controller interact with the disk). Actually this feature is not really documented.

I think we should drop this and have a reflexion on how to attach files to a project.

By the way actually it's broken

**Comment by grossmj** [comment]
I am not sure anyone but Rednectar uses this feature.

**Comment by noplay** [comment]
I just test in 1.4.6 and 1.5 and I don't see the menu even if we have code for managed it. Jeremy can you confirm it's broke?  If it's the case it's broke since many release and no one report the problem.

**Comment by grossmj** [comment]
It works with 1.5. Just put a file named instructions.txt in the project folder. However, this should have been replaced by README (from the annotation menu).

**Comment by noplay** [comment]
Even with a  instructions.txt in the folder in 1.5 I don't see the menu.

Agree we should merge that with README it's the best options.
