### ISSUE TITLE
Lost connection to remote gns3-server after several packet captures

### ISSUE THREAD

**Issue by fanofgns** [GNS3/gns3-gui#1317]
I'm facing issues with packet capture on remote gns3 server. After 6 or 8 times capturing somewhere in the topology gns3-gui could not connect to gns3-server anymore.
To recreate problem: 
1)run gns3-gui on machine A
2)run gns3-server on machine B
3) build simple topology (two dynamips router connected together with fa0/0 ports) & run this nodes
4) start packet-capture on this link
5) stop packet-capture 
6) repeat steps 4-5 several times (6 or 8)
eventualy gns3-gui will show progress bar with attempt to connect to gns3-server and display error 'Cannot connect to remote server http://A.B.C.D:8000, where A.B.C.D - gns3-server ip address'

**Comment by noplay** [comment]
Thanks for the feedback.

What are you capturing?

**Comment by fanofgns** [comment]
Thanks for your reply!
Packets on ethernet & serial links. Live traffic capture in GNS3 is very handy. I've noticed this bug when my gns3-gui was on win2k8 server. I moved gui to ubuntu 16.04 but unfortunately that did not help (

**Comment by fanofgns** [comment]
Also i've noticed that number of tcp connection to gns3server control port (8000 by default) is increasing every time i stop live capture. After this counter reaches 6 (or 8) the problem 'cannot connecto to remote server' occures.

**Comment by noplay** [comment]
It's for IOU or Dynamips?

Hmm it's possible that something is not properly closed

**Comment by fanofgns** [comment]
It is for Dynamips & IOU

**Comment by noplay** [comment]
Fixed in next release 

Thanks !

**Comment by fanofgns** [comment]
Thank you!
