### ISSUE TITLE
[REQ] Please add feature to zeroize overlay qemu hdd

### ISSUE THREAD

**Issue by fanofgns** [GNS3/gns3-gui#1318]
Please provide an interface to recreate overlay disk for qemu images (to undo all changes made during lab and start qemu vm with clean hard drive image )
I do this manualy from gns3server shell with command qemu-img create -f qcow2 -b /root/GNS3/images/csr1000v-image.qcow2 hda_disk.qcow2 
Adding this functionality to gui interface will be very handy )

**Comment by noplay** [comment]
Why not delete the node and replace?

**Comment by fanofgns** [comment]
Deleting node remove all links to this node. If it is a server with 1-2 nics it is ok, but if it is csr or vios router that is placed into the core of your topology with lots of interfaces, all this connections will be lost, and to recreate them i must stop all the neighbors also (if it is a qemu-to-qemu link, qemu-to-dynamips/iol is ok).

**Comment by noplay** [comment]
OK thanks for the feedback

**Comment by grossmj** [comment]
Would be solved by implementing https://github.com/GNS3/gns3-gui/issues/796
