### ISSUE TITLE
[1.5] Remote GNS3 VM requires local server

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1319]
Hello,
with addition of remote GNS3 VM which is just an alias for remote server, GUI still wants to see the local server, which does not really make much sense.
Symptoms of the problem:

- Go to "Preferences"
- Check "Enable the GNS3 VM" and select "Remote"
- Select your server in the dropdown.
- Click "Ok"
- Click on "Preferences" again, you will see:

<img width="428" alt="screen shot 2016-06-17 at 23 03 39" src="https://cloud.githubusercontent.com/assets/1923704/16164881/d6a1a3e6-34e0-11e6-8f01-669fa85ecf83.png">
I am not 100% sure that Remote GNS3 Server does not require local server, but I don't see any reason why it should.
I believe if we indeed don't need local server, then the screenshot above is not the only place where it should be fixed.

**Comment by noplay** [comment]
Probably the same issue:
https://gns3.com/qa/dedicated-remote-server-don-t-wo

**Comment by grossmj** [comment]
The workaround is to select remote first and then "Enable the GNS3 VM".

**Comment by grossmj** [comment]
Things are going to change in 2.0 and I think it is best we focus on it.

**Comment by dmfigol** [comment]
@grossmj sorry Jeremy, it didn't work for me - I mean, I can save this, but then if I open preferences again, I still see an error.

**Comment by noplay** [comment]
https://gns3.com/qa/could-i-use-only-remote-servers-

**Comment by noplay** [comment]
I confirmed the issue when you reopen the settings

**Comment by noplay** [comment]
Fixed in next release
