### ISSUE TITLE
Snap to grid crashes with ostinato logo

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1324]
GNS3 version 1.5.0dev6 on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0.

When I enable "Snap to grid" and then move a node with the ostinato logo (https://github.com/GNS3/gns3-registry/blob/master/symbols/ostinato-3d-icon.svg) into the main area, the GUI crashes.

Apple crash log:
[snap_to_grid_crash.txt](https://github.com/GNS3/gns3-gui/files/323499/snap_to_grid_crash.txt)

**Comment by noplay** [comment]
Weird to see this specific situation trigger the issue but it's the case

**Comment by noplay** [comment]
It's fixed
