### ISSUE TITLE
[2.0] Cleanup remove project manager / topology / project

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1326]
Actually we have these three classes. I'm not sure what are the exact purpose of each.

**Comment by grossmj** [comment]
Topology is to load/save a .gns3 file on the disk. Project represents a project, not sure we need it and I could not find any project manager class.

**Comment by noplay** [comment]
Sorry I was not clear, it's on GUI side

**Comment by noplay** [comment]
I will clean that and keep only topoly it's a source a bugs with sync issue between project manager and topology.

**Comment by noplay** [comment]
Ok now that it's merge it's easier to track bugs of projects not properly closed
