### ISSUE TITLE
item placement for snap-to-grid can be improved

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1327]
When moving an item with snap-to-grid enabled, between the pointer and the item is quite some offset.

With this patch the item follows the pointer more closely.

```
diff --git a/gns3/items/node_item.py b/gns3/items/node_item.py
index 4ed91fb..c9c9e5d 100644
--- a/gns3/items/node_item.py
+++ b/gns3/items/node_item.py
@@ -379,8 +379,10 @@ class NodeItem():

         if change == QtWidgets.QGraphicsItem.ItemPositionHasChanged and self._main_window.uiSnapToGridAction.isChecked():
             GRID_SIZE = 75
-            tmp_x = (GRID_SIZE * round(self.x() / GRID_SIZE)) - ((self.boundingRect().width() / 2) % GRID_SIZE)
-            tmp_y = (GRID_SIZE * round(self.y() / GRID_SIZE)) - ((self.boundingRect().height() / 2) % GRID_SIZE)
+            mid_x = self.boundingRect().width() / 2
+            tmp_x = (GRID_SIZE * round((self.x() + mid_x) / GRID_SIZE)) - mid_x
+            mid_y = self.boundingRect().height() / 2
+            tmp_y = (GRID_SIZE * round((self.y() + mid_y) / GRID_SIZE)) - mid_y
             if tmp_x != self.x() and tmp_y != self.y():
                 self.setPos(tmp_x, tmp_y)
```

Sad enough this doesn't solve an initial placement issue. When snap-to-grid is not enabled the center of the item is positioned, where the pointer is. With snap-to-grid enabled it's position differs from the pointer position. Before this patch the item is initially placed upper left from the pointer, now it's placed down right.
![placement_offset](https://cloud.githubusercontent.com/assets/896406/16222715/e7197a26-3799-11e6-9b7d-11a71841aa93.png)

Furthermore the grid is shown quite prominent, when grid view is enabled. Maybe using some light gray color could make it less outstanding.

**Comment by noplay** [comment]
I embed your patch and changed the grid color. Feel free to tune it

**Comment by noplay** [comment]
I have no plan for working on this topic soon

**Comment by ehlers** [comment]
The problem is, that the item is initially placed at the cursor position and then moved to a new position, that centers the item. It's best not to interfere with this initial placement. After some tests, I found that self.isActive() is false on that initial placement. So I added a check for self.isActive() into the test for using snap-to-grid.

Now it works fine in my environment. But as I'm a total noob with QT, I have no idea if this is reasonable solution.

```
diff --git a/gns3/items/node_item.py b/gns3/items/node_item.py
index c9c9e5d..e45b874 100644
--- a/gns3/items/node_item.py
+++ b/gns3/items/node_item.py
@@ -377,7 +377,7 @@ class NodeItem():
         :param value: value of the change
         """

-        if change == QtWidgets.QGraphicsItem.ItemPositionHasChanged and self._main_window.uiSnapToGridAction.isChecked():
+        if change == QtWidgets.QGraphicsItem.ItemPositionHasChanged and self.isActive() and self._main_window.uiSnapToGridAction.isChecked():
             GRID_SIZE = 75
             mid_x = self.boundingRect().width() / 2
             tmp_x = (GRID_SIZE * round((self.x() + mid_x) / GRID_SIZE)) - mid_x
```

**Comment by noplay** [comment]
Patch merged. 

Sound good and logic with what I know of this area of Qt

**Comment by noplay** [comment]
Thanks a lot
