### ISSUE TITLE
Vmware Machine interfaces

### ISSUE THREAD

**Issue by nrafia** [GNS3/gns3-gui#1328]
I have one request for VMWare machines regarding NICs assignment. I want not to reset NICs once machine is shutdown, instead of that what ever vmnet is assigned to each nic, it should keep that vment assigned to that nic, instead of starting from a prefixed vmnet number e.g in my gns3vm machine nic vmnet start from 2. Each time i have to start my labs, I have to manually re-assign vmnets to machine from default assignment of vmnet2 to onward.

**Comment by grossmj** [comment]
Hi,

One solution is change the "managed vmnet interfaces" range in GNS3 to something else. For instance vmnet2 to vmnet10.

![managed_vmnet_interfaces](https://cloud.githubusercontent.com/assets/4752614/16250865/2f8992e8-37de-11e6-92f4-621cd43969d7.png)

Then set your VM vNIC with a vmnet outside that range.

**Comment by nrafia** [comment]
Thnaks it like a work around, but i think it will work for me.

**Comment by noplay** [comment]
Cool
