### ISSUE TITLE
[2.0] Remove / Change the setup wizard?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1329]
What should we do with the setup wizard?

**Comment by noplay** [comment]
I have the feeling that the setup wizard finally create more trouble than it solved :( Because the first experience of users is WTF is the GNS3 VM.  If you are a dynamips only user, a linux user we confuse you. At the end most people just skip it.

What we could do is to allow user to select the GNS3 VM in the device wizard. And if the VM is not configured we show you a dialog explaining that you need to configure it before and that you need to read the DOCXXX (url of the documentation) for full instructions.

And  this create two way for configuring the GNS3 VM.

**Comment by grossmj** [comment]
I am not happy with the current wizard either. It was introduced to encourage users to use the GNS3 VM. Besides that I think we should not have direct reference to an online documentation (link), this is not standard and creates ugly Ui.

**Comment by noplay** [comment]
The advantage of the online doc is we can include videos.

What I was thinking is trying to promote now the GNS3 VM for all users at first usage is perhaps a mistake. If you need only old IOS you could skip that. That's why we could add the GNS3 VM later when you try to configure IOU/QEMU... 

And we can expect that when dynamips will be too old we will be able to smooth more the process or to have a web interface good enough.

Also I think it's an issue to have two way to configure the VM (the wizard and the preferences), perhaps in all cases it should be a smart wizard (with more explanation) and with a button in preferences to rerun it and just display in preferences a summary of the VM settings.

**Comment by noplay** [comment]
I have turn it off for the moment to stop receiving crash about it.

**Comment by noplay** [comment]
I will take care off it
