### ISSUE TITLE
Docker containers in the VM cannot be used in platforms other than Linux

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-gui#1332]
https://github.com/GNS3/gns3-gui/blob/1.5/gns3/modules/docker/pages/docker_preferences_page.py#L41

I don't see a reason for not allowing to create containers on the VM on platforms other than Linux. Matter of fact I imported a project with containers and seems to be working just fine.

**Comment by noplay** [comment]
The problem is we do not support Docker on the local server for Windows and Mac because we can't inject veth in containers.

**Comment by ddompe** [comment]
How come the import of a portable project with containers worked?

**Comment by ddompe** [comment]
Just to be clear, this means I want to use the GNS3 GUI on Mac, and create containers on the GNS3 VM running on VMware... I understand you can't create veth natively on Windows/Mac.

Today even the GNS3 VM is capable of running containers, I have no way to create them from the GUI in Windows/Mac

**Comment by ddompe** [comment]
Mmm, never mind again. It seems like when I'm behind a proxy network, the communication with the VM server is flaky, and that disabled the options I was looking for.
