### ISSUE TITLE
Improve log/warn display

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1334]
Actually we display error/warning in the console at the bottom. We could do something cleaner.

**Comment by noplay** [comment]
One thing you need to move somewhere else is the display of version number. It's help when user post screenshot.

**Comment by noplay** [comment]
A possibility is to have a log panel hidden somewhere by default and to display error and warning as non blocking popup like ATOM
![image](https://cloud.githubusercontent.com/assets/345437/16407366/a3c5e366-3d13-11e6-942a-efc8a17ca341.png)

**Comment by noplay** [comment]
Could be a hint on how to implement it:
http://bits.minhazulhaque.com/qt/skype-like-desktop-popup-notification.html

**Comment by grossmj** [comment]
I like that. It shouldn't be too complicated to port to PyQt.

**Comment by noplay** [comment]
The link has change:
http://bits.mdminhazulhaque.io/qt/skype-like-desktop-popup-notification.html

**Comment by noplay** [comment]
Of course it's more complicated than that. I have something but a lot of refresh issues :(

**Comment by noplay** [comment]
I made some progress:
![capture d ecran 2017-01-23 a 22 01 04](https://cloud.githubusercontent.com/assets/345437/22222521/7b9b22a4-e1b7-11e6-853d-fd15bf47766d.png)

I no longer have display  artefacts when the element changes. Thanks qt....

**Comment by AJNOURI** [comment]
Looks nice!

**Comment by Raizo62** [comment]
can the console at the bottom work as the left panel (with devices) ?

- It is closed below when no message.
- We can rise it and close it when we click on button
- It rise when GNS3 adds new message

**Comment by noplay** [comment]
The console is too big for that, it's annoying if we open the large console when a message arrive.

**Comment by Raizo62** [comment]
The console is not so big, and message must arrive rarely : only when bug/error (no ?)

**Comment by noplay** [comment]
Information also like when we download images in background for Docker will
appear in the console.

On Wed, Feb 1, 2017 at 12:13 PM Raizo62 <notifications@github.com> wrote:

The console is not so big, and message must arrive rarely : only when
bug/error (no ?)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/1334#issuecomment-276632179>, or mute
the thread

**Comment by Raizo62** [comment]
> Information also like when we download images in background for Docker will appear in the console.

then, rise the console only when bug/error....
