### ISSUE TITLE
When importing a portable project with qemu and docker, the qemu import may fail

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-gui#1336]
I'm using the 1.5 release.

I have a portable project with the Internet qemu appliance for the GNS3 VM, and several docker images. When I import the project for the first time into a GNS3 VM that doesn't have the docker images, docker starts pulling them from the internet, but in the middle of downloading the images from docker, the logs shows an error:

<docker_connected_to_the_internet_appliance>: Cannot connect to remote server http://172.16.184.129:3080

Or sometimes:
Server error from http://172.16.184.129:3080: <internet_appliance> : Operation canceled

At the end of the import, the internet appliance failed to create properly. And the hover tooltip says: 
"This node isn't initialized Operation canceled"

I have attached the failing project, you can likely reproduce the issue by just importing it.
[ops-dc.gns3project.gns3project.zip](https://github.com/GNS3/gns3-gui/files/337554/ops-dc.gns3project.gns3project.zip)

**Comment by ddompe** [comment]
Btw, if you remove the project, and re-import it now that the docker images are on the VM, it doesn't have problems. Seems it's likely the deploying of the qemu image gets starved while docker is running...

**Comment by noplay** [comment]
Thanks should be fixed in next build
