### ISSUE TITLE
[2.0] Fresh GNS3-GUI config file traceback & unable to locate gns3server

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1339]
Hi,
Usually from my experience with GNS3, the GNS3 gui would automatically create its own gns3_gui.conf file with all necessary parameters.

However, on a fresh run of version 2.0 with no gns3_gui.conf file, i get the following errors;

* I'm aware of the vmware command not being found, i don't have it installed
* gns3server is installed and is located under /usr/bin/gns3server
* I understand the setup wizard might be going away, so not too worried about that traceback message
* The main issue i see here is when starting the GNS3 gui, it's not automatically starting the gns3 server. 
* If i skip all of this and go to Edit -> Preferences -> Server -- the fields "Server Path" and "Ubridge path" are empty, appears the GNS3 gui are not detecting the settings from my gns3server

Note: everything is running locally on Fedora Core 24. 

2016-06-30 00:53:31 INFO logger.py:107 Log level: INFO
2016-06-30 00:53:31 ERROR __init__.py:144 vmware command not found
2016-06-30 00:53:31 CRITICAL __init__.py:94 Could not find local server gns3server
2016-06-30 00:53:32 CRITICAL __init__.py:94 Could not start the local server process: gns3server
2016-06-30 00:53:32 INFO http_client.py:219 Connection to http://127.0.0.1:3080
****** Exception detected, traceback information saved in /home/gcasella/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gns3_gui-2.0.0.dev1-py3.5.egg/gns3/main_window.py", line 1028, in startupLoading
    if not self._settings["hide_setup_wizard"] and not gns3_vm.isRunning():
NameError: name 'gns3_vm' is not defined

/usr/lib/python3.5/site-packages/raven-5.21.0-py3.5.egg/raven/conf/remote.py:67: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
2016-06-30 00:53:33 INFO crash_report.py:105 Crash report sent with event ID: db73489e178e4e2f92b4840b0ae9d6e6
2016-06-30 00:53:33 INFO http_client.py:465 Response error: Connection refused (error: 1)
2016-06-30 00:53:33 ERROR http_client.py:236 Cannot connect to http://127.0.0.1:3080. Please check if GNS3 is allowed in your antivirus and firewall.

**Comment by noplay** [comment]
Hi @gcasella many thanks for testing. Just to be sure you are aware that the 2.0 is in  in the middle of refactoring and not ready to be used.

Your bug report are very usefull and we will be happy to receive more. I just want to be sure that you are not someone trying to use it for his everyday usages.

**Comment by gcasella** [comment]
Hi Julien,

I'm not using it for everyday use. I'm only using it for testing purposes.

On 30 Jun 2016 3:08 a.m., Julien Duponchelle <notifications@github.com> wrote:

Hi @gcasella<https://github.com/gcasella> many thanks for testing. Just to be sure you are aware that the 2.0 is in in the middle of refactoring and not ready to be used.

Your bug report are very usefull and we will be happy to receive more. I just want to be sure that you are not someone trying to use it for his everyday usages.

**Comment by cioby23** [comment]
Just cloned the latest 2.0 branch to test some new features and I confirm this bug. If I try to enable the local server GNS3-GUI does not save **local server preferences** even if I manually add the paths to gns3server and ubridge and I receive this error
**ERROR http_client.py:236 Cannot connect to http://127.0.0.1:3080. Please check if GNS3 is allowed in your antivirus and firewall.**
Running on Linux (ArchLinux).

**Comment by noplay** [comment]
Should be fixed now

Thanks!
