### ISSUE TITLE
Replace dot by something else for colorblind people

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1340]
https://gns3.com/discussions/possibility-of-a-colorblind-mode

**Comment by noplay** [comment]
Usefull for testing: http://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by grossmj** [comment]
This can wait for 2.0 I think.

**Comment by noplay** [comment]
Did you see my PR about that?

**Comment by grossmj** [comment]
Yes but I haven't decided if I want to accept it yet.

**Comment by grossmj** [comment]
PR merged
