### ISSUE TITLE
Weird constants

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1345]
In the code we have -4 and -10 I don't get the purpose of that. I have the feeling but I'm not sure that this create a small differences between the coordinate written in the .gns3 and what is really display.

https://github.com/GNS3/gns3-gui/blob/5664b32cc54e75c874fd9c645630c89114b410ab/gns3/items/note_item.py#L174

What do you think Jeremy?

**Comment by grossmj** [comment]
Do you see a difference when removing those constants?

**Comment by noplay** [comment]
I will test

**Comment by noplay** [comment]
Doesn't seem to change something
