### ISSUE TITLE
error in the default config of "Ether Switch Routeur"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1348]
Hi

On Linux with GNS3 1.5.1.dev1

With the default config of "Ether Switch Routeur", the default name format doesn't have {0}
and "Automaticaly delete NVRAM and disk files" are unchecked (so it is do with dynamips router)

The default name format without {0} works with GNS3, but config interface of "Ether Switch show error when we apply on the edit dialog

**Comment by noplay** [comment]
"Automaticaly delete NVRAM and disk files" unckecked is normal because the etherswitch store vlan in the NVRAM and not in the startup config you will lost them otherwise

**Comment by Raizo62** [comment]
ok. Thanks :-)

(and sorry)

**Comment by noplay** [comment]
I don't have the issue with the {0} is it with a specific image?

**Comment by Raizo62** [comment]
I think that doesn't depend of image (but i can have wrong : c3725-adventerprisek9-mz.124-25d.image)

When you create a new config of GNS3, you indicate that your IOS is an etherswitch. What is your Default name format ? ESW or ESW-{0}. I have ESW
When you edit config of Etherswitch, you click on "OK" without modify it. I have the error message "The default name format must contain at least {0} or {Id}"

**Comment by noplay** [comment]
Sorry now I see the error

**Comment by noplay** [comment]
Now it's fixed. 

Sorry for all the question

**Comment by Raizo62** [comment]
> Sorry for all the question

no problem ;-)
