### ISSUE TITLE
Ghost link when deleting qemu instance with active peer qemu VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1349]
GNS3 version 1.5.1dev1 on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0.

Initial state: 2 running qemu instances interconnected:
![qemu_up](https://cloud.githubusercontent.com/assets/896406/16545317/cc92c580-4127-11e6-8840-82ef82a879e2.png)

Now delete MicroCore-2, the qemu instance is successfully deleted. Then GNS3 tries to delete the link, but it fails, because MicroCore-1 is still running:
![warning_delete_link](https://cloud.githubusercontent.com/assets/896406/16545319/de2c32b8-4127-11e6-9db2-b60420296ae0.png)

This results in a ghost link:
![qemu_deleted_peer](https://cloud.githubusercontent.com/assets/896406/16545321/e23f2446-4127-11e6-87a7-95cf3764f6b7.png)

This ghost link can't be deleted, because GNS3 still thinks that it is connected to a running MicroCore-2. Even deleting MicroCore-1 keeps this ghost link.

**Comment by ehlers** [comment]
Looks like https://github.com/GNS3/gns3-server/issues/600 is the same issue, just with docker.

**Comment by noplay** [comment]
It's not present in 2.0 because we cleaned the system, but need a temporary fix in 1.5

**Comment by ehlers** [comment]
Maybe a simple workaround is to set the link status of the deleted VM (MicroCore-2) to down. Then after deletion of the VM (MicroCore-2) you still get a ghost link. After stopping the peer VM (MicroCore-1) you can manually delete this ghost link. But you get a warning in the log `Server error : VM ID b874d12c-3b11-489a-8331-b3212857958a doesn't exist`.

**Comment by noplay** [comment]
Issue confirmed
