### ISSUE TITLE
1.5 Unable to open HTTP  (tcp 8000) GNS3 VM page OSX 

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#1350]
Ver 1.5 (the test in via brand new download from the site, but also have issues with one upgrade from 1.4.6)

I am not sure if this is a bug or not but I can't connect to port 8000 http to upload/download images
access via SSH ok:

iMac$ telnet 172.16.166.136 22
Trying 172.16.166.136...
Connected to 172.16.166.136.
Escape character is '^]'.
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7

<img width="647" alt="screen shot 2016-07-04 at 1 37 52 pm" src="https://cloud.githubusercontent.com/assets/3232190/16550318/888fb648-41ec-11e6-80fb-4e93060dd1bc.png">

Any reason? HTTP server not listening?

Cheers,

Gordon

**Comment by cioby23** [comment]
HTTP server port has changed. It's listening on port 3080 not on 8000 anymore.

**Comment by vader75** [comment]
should of tried it, thanks, got confused as main page does not point to 3080 just the IP.

All good.

**Comment by noplay** [comment]
More informations:
https://gns3.com/discussions/migration-to-1-5-for-esxi-users-
