### ISSUE TITLE
open GNS3 via VNC and launch a qemu equipment, then close VNC client directlly , the qemu still run.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1367]
Maybe this is not a issue.
I did as follow:
1,use vnc viewer connect with Lubuntu 16.04(installed vnc server)
2,open GNS3 inside
3,open one qemu device just like vSRX
4,close vnc viewer without close GNS3
5,the vSRX still run in backround and consume CPU.
so Is there anyway to avoid it ?

**Comment by noplay** [comment]
It's no an issue. Your VNC client run in a session on your OS and closing VNC will not close this session. You can change your VNC server configuration if you want to change that.
