### ISSUE TITLE
[1.5.1/Linux] Removing a node makes GNS3 crash

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1381]
The one thing which is special about that node - CSR_1000v_2 - is that I changed its network interface type from virtio-net-pci to e1000. Then ran it, stopped it and tried to remove it.
topology.gns3: [Ansible-linux.gns3.txt](https://github.com/GNS3/gns3-gui/files/359847/Ansible-linux.gns3.txt)

**Comment by noplay** [comment]
Hi,

What is your distribution?

**Comment by jean-christophe-manciot** [comment]
Ubuntu 16.04 4.4.0-28

**Comment by noplay** [comment]
@ajnouri are you also on Xenial? You reported also multiple weird crash recently.

**Comment by AJNOURI** [comment]
I am on Debian Jessie. Happen to test on fresh Xenial VM, and until now things gone OK.

**Comment by noplay** [comment]
Should be fixed in 1.5.2 by changes in progress dialog. 

Thanks for the help

**Comment by superwolfboy** [comment]
not very happy to say , if delete device from a topo with many devices, it still would scrash the gui
Lubuntu 16.04 and 1.5.2

**Comment by noplay** [comment]
Do you have a stack trace?

**Comment by superwolfboy** [comment]
how to get the stack , and I will do it next.
by the way , when delete this node , this node did not connect with other yet , other nodes were running.
just delet a single node in a topo with other running.

**Comment by noplay** [comment]
Start gns3 from a terminal and see if something is display in the console

**Comment by superwolfboy** [comment]
ok , i will try , and not always happen . so need wait ...
