### ISSUE TITLE
[2.0] VPCS issues or not?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1382]
* [x] The first problem is we no longer have by default a VPCS node. It's confusing when you migrate from old GNS3.
* [x] the default icon for VPCS is not the VPCS icon but the standard computer icon
* [x] the new appliance button doesn't support VPCS
* [x] right click on VPCS doesn't work

![image](https://cloud.githubusercontent.com/assets/345437/16805938/c01082e6-4912-11e6-9af5-1effdd4a3a90.png)

**Comment by noplay** [comment]
It's related to #1306

**Comment by noplay** [comment]
Another issue: https://github.com/GNS3/gns3-server/issues/628

**Comment by noplay** [comment]
The new appliance button now support VPCS

**Comment by noplay** [comment]
It's now use the VPCS icon

**Comment by noplay** [comment]
Right click on a template work now

**Comment by noplay** [comment]
@grossmj what do you think about the fact a user after migration will no longer have a VPCS icon and need to create one? It could be confusing for user after the migration.

Perhaps by default a template for GNS3 VM running on local node should be in the list.

**Comment by grossmj** [comment]
Let's have a default VPCS template just like we do for cloud and other builtin nodes.

**Comment by noplay** [comment]
Default template added
