### ISSUE TITLE
Error: Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-gui#1385]
when save configuration,gns3 report it !why?
Error: Dynamips hypervisor process has stopped, return code: -11
platform：windows 10
gns3 version:1.5.1
![dfdsfds](https://cloud.githubusercontent.com/assets/15842207/16842816/6484f9ac-4a11-11e6-852f-38d965e9a69e.png)

**Comment by qianxideyu** [comment]
vIOS run qemu, router run dynamips!

**Comment by qianxideyu** [comment]
save project occur it after I have saved device configuration！

**Comment by noplay** [comment]
Hi,

Dynamips often crash due to an issue with the image.

We recommend to use one of this images:
https://gns3.com/support/docs/virtual-machines-supported-2

Best regards 

Julien
