### ISSUE TITLE
v1.5.1: Warn the user that the project file has the server on the old port and give the option to change it to 3080

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1386]
I knew that the server port changed to 3080 but I forgot that the .gns3 file contains port settings (I changed the server settings just in GUI preferences)

Warn the user that the file still uses the old port and offer the option to change it on the fly and ask the user to change the project

The message in the console deck area was not relevant to the issus (saying something about cloud int eth1 which could not be found when in fact the server could not be found)

**Comment by noplay** [comment]
Normally I think it should ask you to choose a different server if the server doesn't exists in your settings.

**Comment by noplay** [comment]
When you open the project if you don't have the remote in your settings you will have this dialog:
![capture d ecran 2016-07-28 a 12 51 31](https://cloud.githubusercontent.com/assets/345437/17210305/141ea376-54c2-11e6-9137-b521deac1c55.png)
