### ISSUE TITLE
Windows 7 64 bits Gns3 1.5.1 error

### ISSUE THREAD

**Issue by luis11645** [GNS3/gns3-gui#1387]
Universal C Runtime is not installed

**Comment by noplay** [comment]
Did you install all update from windows update?

**Comment by luis11645** [comment]
When i download the update gives me error "not applicable upgrade"

**Comment by noplay** [comment]
You can manually get it from:
https://support.microsoft.com/en-us/kb/2999226

**Comment by luis11645** [comment]
solved! all I needed was to install SP1 update and kb2999226

**Comment by rafelck** [comment]
go to this link,that's artictle maybe help you http://www.kuyhaa-android19.com/mengatasi-error-api-ms-crt-runtime-l1-1-0-dll.html
