### ISSUE TITLE
let uBridge emulate bad quality connections

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1388]
This is just a suggestion, not a issues or bug report.
In GNS3 all the connections were unified by uBridge , so is there any possible to make enhancement for  uBridge, add a feature just like emulate bad quality network connection, just like delay and lost package rate?

**Comment by cioby23** [comment]
There is an already open issue for this https://github.com/GNS3/ubridge/issues/16

**Comment by superwolfboy** [comment]
thank you

**Comment by noplay** [comment]
Thanks @cioby23
