### ISSUE TITLE
Add an option to edit the underlying .gns3 file from GUI (lauch a text editor)

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1389]
I am thinking that sometimes it is just easier to go over the project file and make bulk changes (or change the server settings). This would be much easier if you can open the current project file via GNS3 GUI.
Currently I need to go via Windows Explorer and from there navigate to the project file and open it. 
This enhancement will save some work/time for the user. Maybe somewhere under "Edit"

**Comment by noplay** [comment]
Hi,

Their is too much risk of breaking stuff. We already have support issue with people editing file by hand. 

For your migration problem to 1.5 do not try to change the port in your existing topologies change the server config it's easier:
https://gns3.com/discussions/migration-to-1-5-for-esxi-users-
