### ISSUE TITLE
AttributeError: module 'os' has no attribute 'listxattr'

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1392]
https://app.getsentry.com/gns3/gns3-gui/issues/143565624/

```
AttributeError: module 'os' has no attribute 'listxattr'
  File "gns3/main_window.py", line 1239, in startupLoading
    if not servers.localServerAutoStart():
  File "gns3/servers.py", line 426, in localServerAutoStart
    if not self.initLocalServer():
  File "gns3/servers.py", line 440, in initLocalServer
    self._checkUbridgePermissions()
  File "gns3/servers.py", line 159, in _checkUbridgePermissions
    if "security.capability" in os.listxattr(path):

AttributeError: module 'os' has no attribute 'listxattr'
```

**Comment by fcolista** [comment]
I've the same issue. How did you solved?

**Comment by noplay** [comment]
Are you using the last GNS3 version? On which OS ?

**Comment by fcolista** [comment]
Yes, the latest stable.
OS: Alpine Linux 
Thanks.

.: Francesco
.: on mobile

**Comment by noplay** [comment]
What is the version of Python 3 of your system? 

python3 -v

**Comment by fcolista** [comment]
Python 3.5.2

**Comment by noplay** [comment]
Could you test this in a shell, launch:
```
# python3
Python 3.5.2 (default, Aug 16 2016, 05:35:40)
>>> import os
>>> os.listxattr
```

We could detect if the function is here, but it's strange because it's suppose to be something builtin in Python since Python 3.3

**Comment by fcolista** [comment]
python3
Python 3.5.2 (default, Nov 25 2016, 11:35:28) 
[GCC 6.2.1 20160822] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listxattr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'listxattr'
>>>

**Comment by noplay** [comment]
I suspect that the LibC of Alpine Linux (Musl) doesn't implement the call listxattr. The easier fix for you is to comment the test. I will add a check in next big release.

**Comment by fcolista** [comment]
Sounds good. 
Thanks a lot.

**Comment by noplay** [comment]
Thanks for the report, it's very interesting to know that.

**Comment by fcolista** [comment]
Ok, so.
@clandmeter figured the issue.

Short story: seems that due to MacOSX xattr has been disabled: https://bugs.python.org/issue12720

posixmodule.c has defined:
```
#if defined(HAVE_SYS_XATTR_H) && defined(__GLIBC__) && !defined(__FreeBSD_kernel__) && !defined(__GNU__)
#define USE_XATTRS
#endif
```
It does not include MUSL.

We have applied this patch:
```
--- ./Modules/posixmodule.c.org
+++ ./Modules/posixmodule.c
@@ -97,8 +97,9 @@
 #undef HAVE_SCHED_SETAFFINITY
 #endif
 
-#if defined(HAVE_SYS_XATTR_H) && defined(__GLIBC__) && !defined(__FreeBSD_kernel__) && !defined(__GNU__)
+#if defined(HAVE_SYS_XATTR_H) && defined(__linux__) && !defined(__FreeBSD_kernel__) && !defined(__GNU__)
 #define USE_XATTRS
+#include <linux/limits.h>
 #endif
 
 #ifdef USE_XATTRS
```
And the issue gone with GNS3.

This is not a bug related to GNS3, but is related to Python.
Thanks @clandmeter for figuring out this issue and finding the solution.



.: Francesco

**Comment by noplay** [comment]
Thanks a lot for the info
