### ISSUE TITLE
[1.5.1/Linux] "Show in File Manager" launches the package installer gdebi instead of the file manager

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1393]
Any qemu Node -> "Show in File Manager":
![show in file manager launches the package installer gdebi](https://cloud.githubusercontent.com/assets/13176858/16954130/f5b3704a-4dcf-11e6-8a4f-82504db3067f.jpg)
Also, GNS3 has been launched as root.

**Comment by noplay** [comment]
Weird we pass the path to Qt: 
``` 
QtGui.QDesktopServices.openUrl(QtCore.QUrl.fromLocalFile(node_dir))
```
Qt will forward it to the OS.

It seem the OS detect this kind of path has a debian package that should be open in compatible application. 

I didn't test on a Linux but I inspected the mime package of debian and don't see why this behavior.

What is the result of:
```
xdg-open /home
```

Does is open your file browser or also gdebi?

**Comment by jean-christophe-manciot** [comment]
It also opens gdebi.

**Comment by noplay** [comment]
Sound like a configuration issue on your issue, if system open the wrong application for directory outside GNS3.

You can change the association with:
``` 
xdg-mime default Thunar.desktop inode/directory
```

Arch as a good documentation about this topic:
https://wiki.archlinux.org/index.php/default_applications

I don't see what GNS3 could do. What do you think?

**Comment by jean-christophe-manciot** [comment]
Your solution is OK for me  :)

**Comment by noplay** [comment]
Thanks
