### ISSUE TITLE
GNS3 1.5.1 GNS3 inbuilt switching instances not passing traffic but hub does

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#1408]
This is very similar to "GNS3 1.4.4 switching instances not passing traffic (Ethernet switch or IOU) but hub does" case I logged before.

Instances run on Local GNS3 server not VM.
Topology (working with GNS3 hubs, but replace with GNS3 switches and traffic passing is the problem)

![topology_failure_switch_passing_traffic](https://cloud.githubusercontent.com/assets/3232190/17131458/ea1cf18e-5360-11e6-97e2-b1724d510d19.PNG)

System:

Windows 10 Pro ver 1511
VMware Workstation 12 Pro 
GNS3 1.5.1

**Comment by noplay** [comment]
What kind of traffic?

**Comment by vader75** [comment]
Just tested a simple ping, just to get a reference connectivity.

**Comment by noplay** [comment]
You have the issue only with vmware node connected or any node?

Thanks fore the infos

**Comment by vader75** [comment]
Current topology is using VMware hosts/node, but I will try to test non vm hosts, need some time, will get back to you as soon as I can.

**Comment by vader75** [comment]
My general also observation is that deleting GNS3 nodes, ie switch/hub is taking long, "Please wait dialogue" is taking long time (0 to 100 and back).

**Comment by vader75** [comment]
Ok, topology:

![top2](https://cloud.githubusercontent.com/assets/3232190/17132925/41c7c2e6-5367-11e6-907e-1eff66f19edb.PNG)

VPCS is connected to SW1 but fails to start, says Goodbye
IOU1 running via GNS3 VM can not ping vioa switch.

Seems more generic issue, but unless you want me to debug via GNS3 commands you could give me, I cant say.

**Comment by noplay** [comment]
Can you go to help => Export debug information and send them to
developers@gns3.net

**Comment by noplay** [comment]
When the project is opened

**Comment by vader75** [comment]
Attached thanks.

[issue_125_debug.zip](https://github.com/GNS3/gns3-gui/files/383517/issue_125_debug.zip)

**Comment by noplay** [comment]
Thanks I delete the attachement because sensitive info could be inside (process list)

**Comment by noplay** [comment]
Do you have the same issue if you stop Avast? Or whitelist in avast the dynamips.exe process

We have report of issue with AVG but no problem know with Avast.

**Comment by vader75** [comment]
I stopped avast, rebooted, avast was still off, but same issues. Maybe similar to https://github.com/GNS3/gns3-gui/issues/1092 I had posted before, winpcap and ubridge issue with looping ?

**Comment by noplay** [comment]
Can you try by replacing Winpcap by npcap ?
https://github.com/nmap/npcap/releases/tag/v0.08

**Comment by vader75** [comment]
Is there an option in GNS3 GUI to say to use npcap? I uninstalled winpcap, installed npcap, but project is a bit broken now.

**Comment by vader75** [comment]
Updated topology, moved GNS3 switch and Cloud (bound to now bridged net 2 (was NAT)) to be instance on GNS3 VM not local server.

Also restored winpcap 4.1.3 (removed npcap).

![top3](https://cloud.githubusercontent.com/assets/3232190/17137803/7edf767e-5380-11e6-9914-cf0a5e3a0345.PNG)

All works now, so it seems that instances of a cloud and switch running on the local GNS3 server have an issue forwarding traffic. Not sure if this relates to winpcap (as bound interface is now of GNS3 VM).

Maybe this could be useful for you internal troubleshooting.

**Comment by noplay** [comment]
Did you reboot after npcap install?

**Comment by vader75** [comment]
Yes I did.

**Comment by vader75** [comment]
Just an update, even with instances running in GNS3 VM, it appears that L2 on the HUB, Switch IOU switch etc. is not working, ping works but sending other higher layer traffic such as TCP (example web traffic) times out.

**Comment by grossmj** [comment]
@vader75 have you installed GNS3 version 1.5.2? Also, make sure the "block network traffic originating from host OS" option is ticked in the preferences.

![managed_vmnet_interfaces](https://cloud.githubusercontent.com/assets/4752614/18692887/b67e4c94-7f5a-11e6-9e44-e97bb87e5238.png)

**Comment by vader75** [comment]
@grossmj Sorry for the delayed answer. I have installed 1.5.2 (including the option tick) and simple topologies do work i.e. pass traffic. In regards to #1521, my topologies were rather simple with 2-4 switches using IOU on GNS3 VM. Therefore it is still possible there are other or ongoing issues with packet capture plugin or similar.

If we could create a topology that has X nodes starting to cause switching issue, I could try to replicate and report.

**Comment by noplay** [comment]
So the problem seem solve?

**Comment by ThePeePs** [comment]
I am having the same problem, only running under linux.
my setup is as follows:
running 1.5.2, with a remote server on the same LAN.

running Arista vEOS in QEMU, connecting them to a generic eithernet switch to tap0 on on a host/cloud.

packet capture on the arista shows traffic coming in from the generic switch (from tap0 on the host) but no traffic from the arista makes it to the switch (checked by running a capture on the link between the QEMU Arista, and the generic switch.

all devices are run on the remote server. running Debian Jessie.  GNS3 gui on LinuxMint 17, both running the ppa version. Please let me know if you would like any other info.

**Comment by bunbohue** [comment]
I have this problem too
Windows 10 Pro ver 1607
VMware Workstation 12 Pro
GNS3 2.0.0b2

**Comment by noplay** [comment]
Do you have an antivirus running?

**Comment by grossmj** [comment]
The problem is in uBridge.

Download the latest version from https://github.com/GNS3/ubridge/releases/tag/v0.9.11, replace ubridge.exe and cygwin1.dll in the GNS3 install directory.

Please let us know if this doesn't fix the problem.

**Comment by zakzsh** [comment]
@grossmj Thanks a Lot, had been scratching my head from many days trying to resolve this weird issue. replacing ubridge.exe and cygwin1.dll in the GNS3 install directory worked like a charm.
