### ISSUE TITLE
Exporting portable projects with QEMU includes base images even when selecting no.

### ISSUE THREAD

**Issue by stewilliams-extr** [GNS3/gns3-gui#1409]
When exporting a portable project with QEMU images, and you select "NO" to including the base images they are still included.

Version 1.5.1

**Comment by noplay** [comment]
Thanks for the report!

**Comment by noplay** [comment]
Issue confirmed the client seem to send the correct info

**Comment by noplay** [comment]
Will be fixed in 1.5.2
