### ISSUE TITLE
A project menu

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1410]
For the moment I have move some option to a project menu because now that stuff are on the controller it's not really  option to manipulate file especially with remote controller.

What do you think about that?

![capture d ecran 2016-07-27 a 21 44 47](https://cloud.githubusercontent.com/assets/345437/17189951/2bc3c304-5444-11e6-8890-a727c90b4177.png)

**Comment by grossmj** [comment]
Looks good. Maybe we should also add "recent projects" to replace the recent files view.

**Comment by noplay** [comment]
And add an edit project  options related to #1331

**Comment by noplay** [comment]
The edit project dialog is here with edit name, now we can add more options inside the architecture is ready.

**Comment by noplay** [comment]
The recent projects menu is added for the moment I didn't removed the open files menu I let you decide.
