### ISSUE TITLE
Import/Export devices configuration options in 2.0?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1411]
Hi,

Should we keep the Import/Export devices configuration options? Actually it's broke and need a full rewrite for 2.0.

This feature require that the user reimport configuration in the same project, if he made a change to the topology (changing name of a node) he will have trouble. Now that we have portable project you can move stuff without this and it's less error prone. 

@grossmj do you think it's still usefull?

**Comment by grossmj** [comment]
I think it can still be useful. Especially users who want to back-up their configs, use them elsewhere etc.

**Comment by superwolfboy** [comment]
Hi:
How about the pre-configuration management as UNL? will it be add in the future?

**Comment by noplay** [comment]
What is pre configuration management?

**Comment by superwolfboy** [comment]
can management every startup-config for device in topo and also can export or import configuration in my mind.

**Comment by noplay** [comment]
Do you have some screen shoots ? I have the feeling we already do that but
perhaps it's not clear for you.

**Comment by superwolfboy** [comment]
somthing like this (it is unetlab , maybe not suitable put the screenshot here)
![image](https://cloud.githubusercontent.com/assets/9411604/17667966/c607cf06-6339-11e6-814f-34a88f5dac74.png)

**Comment by superwolfboy** [comment]
And if this feature come true , it would be allowed us migrate the topo from one computer to another, at this moment the configuration is stored by delta qcow2, different computer with gns3 maybe the base disk image is different.

**Comment by grossmj** [comment]
These are default startup-configs, right?

**Comment by superwolfboy** [comment]
yes. but every devive in every top should have its own startup-config,

**Comment by cioby23** [comment]
@superwolfboy - there is opened ticket for this https://github.com/GNS3/gns3-gui/issues/1095 but I see it's postponed to version 2.1

**Comment by superwolfboy** [comment]
thank you very much , and really yes I mean this .




在2016年09月10 22时27分, "cioby23"<notifications@github.com>写道:



@superwolfboy - there is opened ticket for this #1095 but I see it's postponed to version 2.1

**Comment by noplay** [comment]
Import/Device is backported from 1.5
