### ISSUE TITLE
once delete a connection line between two device need waiting a long time, all device closed.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1413]
![image](https://cloud.githubusercontent.com/assets/9411604/17437793/5882a9b8-5b52-11e6-9640-197d864aaf91.png)

**Comment by superwolfboy** [comment]
most likely when a topo with many builtin switch , will be problems
and builtin switch with cloud with tap interface , will be problems
and builtin switch with many kinds of devices(qemu,dy,vbox,iou),will be problems.

**Comment by noplay** [comment]
On which OS?

**Comment by superwolfboy** [comment]
the host is lubuntu 16.04

**Comment by superwolfboy** [comment]
today I remove a line between two vios_l2 in a big topo (40nodes, include dynamips and qemu), then the gns3 gui crash,left the qemu process in backround, two times, so do you have any method that can dump the crash file or get the log, so I can commit to you for find the problem?
OS:lubuntu 16.04

**Comment by noplay** [comment]
Did you test with 1.5.2 pushed a few hours ago?  The crash when delete
should no longer exist

**Comment by superwolfboy** [comment]
OK cool, I will test and will reply.
by the way , is there any way or add some features in the further that allowed us when the gui crashed left the topo running backround, reopen the gui can pick up the topo privious ?

**Comment by noplay** [comment]
The topo will continue to run in background if in Project / Edit you choose
to leave it open in background

An improvement of 2.0 is thanks to autosave no data is lost in the process.

**Comment by superwolfboy** [comment]
test several hours now , not crash now, hope this would continue....
thank you .

**Comment by noplay** [comment]
Thanks for the feedback!
