### ISSUE TITLE
Font  & icon size issues (Fedora 24)

### ISSUE THREAD

**Issue by phocean** [GNS3/gns3-gui#1415]
Latest gns3-gui (1.5.1 release or dev) is totally broken, at least on Fedora 24 (Gnome 3.20).

I have a dual screen setup, 1920x1080. In short, nothing special.
It totally messes with icon and font sizes.

On my external screen, the icons are OK but the fonts (menus and all windows) are so small that it can't be read.

If I move the same window to my main screen, the issue switches : icons become insanely huge, while fonts are normal.

When launched from a terminal, gns3  does not show any related or significant warning.

I guess it is an issue with QT. I migrated back to 1.4.0 where it is OK.

**Comment by noplay** [comment]
Which version of Qt 5 is provided with Fedora?

**Comment by phocean** [comment]
It seems to be version 5.6:

```
% dnf info qt5-qtbase.x86_64 
Vérification de l'expiration des métadonnées effectuée il y a 1 day, 7:08:19 sur Sun Aug 14 04:52:03 2016.
Paquets installés
Nom         : qt5-qtbase
Architectur : x86_64
Époque      : 0
Version     : 5.6.1
Révision    : 3.fc24
Taille      : 8.3 M
Dépôt       : @System
Depuis le d : updates
Résumé      : Qt5 - QtBase components
URL         : http://qt-project.org/
Licence     : LGPLv2 with exceptions or GPLv3 with exceptions
Description : Qt is a software toolkit for developing applications.
            : 
            : This package contains base tools, like string, xml, and network
            : handling.
```

**Comment by noplay** [comment]
What is the DPI of both screen? How do you make dual screen (nvidia tools, two xserver )? 

I suspect Qt is lost with your configuration because one screen is high dpi and not the second.

**Comment by phocean** [comment]
It is a Skylake Intel graphic card, on Thinkpad T460 (14" screen) with external screen (24").
Both have a resolution of 1920x1080 so I am not sure it qualifies for HDPI.

Anyway, here is the output for the laptop screen:

```
% xdpyinfo | grep -B2 resolution
screen #0:
  dimensions:    1920x1080 pixels (508x285 millimeters)
  resolution:    96x96 dots per inch
```

I don't know how to get the same for the external monitor, which anyway is certainly not hdpi.

**Comment by noplay** [comment]
Hmm this should be seen as low dpi.

If you don't connect a second monitor it's work?

**Comment by phocean** [comment]
If I don't connect the second monitor, there is still an issue with huge icons.

[Here is a link to a screencast](https://www.dropbox.com/s/4gx8dwoxwz7bvun/Screencast_15-08-2016_17%3A19%3A04.webm?dl=0)  with both screens, so that you can clearly see what I am talking about.

**Comment by noplay** [comment]
Can you start from a terminal with:
QT_AUTO_SCREEN_SCALE_FACTOR=0 gns3

**Comment by phocean** [comment]
Well spotted! It does the trick :-)

**Comment by noplay** [comment]
Annoying this mean Qt detect your screen as HDPI :(

**Comment by grossmj** [comment]
Maybe this is going to be fixed in a future release of Qt...

**Comment by noplay** [comment]
I'm closing the issue. It's not a GNS3 bug but a bug in Qt and your hardware / distribution... 

I will try to add a settings for turning off HDPI support in case of issue #1451.

Question are you using X11 or Wayland? I know that fedora want to switch to Wayland in fedora 25 it could probably impact this point.

**Comment by phocean** [comment]
Ok, got it.
I am on X11. I will test it with Wayland when it is out.
