### ISSUE TITLE
In VMware wizard add a warning about ESXi

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1420]
A common misunderstanding. People think that the GNS3 VMware support mean they can control an ESXi and use ESXi VM in the topology. Due to that they think the remote server in the wizard is an ESXi server.

We need to make it clear in the wizard.

**Comment by grossmj** [comment]
We can't possibly warn users about everything + warnings create ugly interfaces. Maybe something as simple as "Remote GNS3 server" or another description would be sufficient.
