### ISSUE TITLE
[1.5.2/Linux] contextlib2 may not be installed by GUI build process

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1428]
I have not checked previous releases about the following, but I find this message a little bit strange:
```
Using /usr/lib/python3/dist-packages
Searching for contextlib2==0.5.4
Best match: contextlib2 0.5.4
Adding contextlib2 0.5.4 to easy-install.pth file
```
At the end of the build process, contextlib2 is not installed in "/usr/lib/**python3**/dist-packages" and only "**contextlib2-0.5.4.dist-info**" is present inside "/usr/**local**/lib/**python3.5**/dist-packages"..

Is this behavior expected? Shouldn't we see a "/usr/**local**/lib/**python3.5**/dist-packages/**contextlib2**" folder?

**Comment by noplay** [comment]
contextlib2 is not used by GNS3.

It seem it's asked by raven (the crash report lib):
https://github.com/getsentry/raven-python/blob/master/setup.py#L38

But not use for Python >= 3.2:
https://github.com/getsentry/raven-python/blob/5c9461ccb6356f7e064dacbda31c6bf0d1b6fdb1/raven/base.py#L23

Should not create issue for for you or us.
