### ISSUE TITLE
Problem to overwrite a project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1435]
There is something that needs to be improved in the project dialog. For instance I want to create a project named "untitled", I get this:

![project_1](https://cloud.githubusercontent.com/assets/4752614/17832644/1b38d4e6-66c5-11e6-9cc2-60673d638b5b.png)

All good then, just overwrite it and then I get this:

![project_2](https://cloud.githubusercontent.com/assets/4752614/17832645/1b4b0378-66c5-11e6-98b2-b13d1e0ab37a.png)

The project should have been deleted the first time.

**Comment by noplay** [comment]
Actually the client ask for overwrite by looking on the file system but it's wrong. We should check in the project name on server and if the name already exists delete it when we overwrite.
