### ISSUE TITLE
Once close some instance based vbox, show error and close failed.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1444]
As screenshot, when I close these extermeXos based on vbox , they can not be clolse and show errors:
![image](https://cloud.githubusercontent.com/assets/9411604/17959114/df2bbb5c-6ad0-11e6-8e9b-ba01941f81fe.png)

OS: lubuntu 16.04
Vbox:5.1.2
GNS3 and server:1.5.2

**Comment by noplay** [comment]
I doubt it will the issue but did you try with VirtualBox 5.1.4?

**Comment by superwolfboy** [comment]
tried and the same :(
![image](https://cloud.githubusercontent.com/assets/9411604/17969398/74e05cd8-6b04-11e6-982f-ef6a5e054ff9.png)

**Comment by noplay** [comment]
It's the only vm that create issue? 

This VM have special hardware? It's slow to stop?

**Comment by superwolfboy** [comment]
I have alread tested some condition:
1, all the extermexos running on vbox,
2,when extermexos enable acpi shutdown, AND connect with other extermxeos, the problem will happen.
3,when extermexos not enable acpi shutdown , AND connect with others , the problem will NOT happen
4,when extermexos enable acpi shutdown, AND NOT connect any others, the problem will NOT happen.
So at this moment disable the acpi shutdown would solve this proble templary,

and I tested a tinycore running vbox ,it has simlar problem.

**Comment by noplay** [comment]
It should be fixed in last server source code

**Comment by Raizo62** [comment]
Hi

I have believe that i have still the bug (with last release 1.5)

On Linux (slow PC : with no accelerated processor, and access to vdi with nfs), i have the same error when i stop a WinXP connected to "ethernet switch" : 

```
Server error from http://user@127.0.0.1:3080: WinXP-1: VirtualBox has returned an error: VBoxManage: error: The machine 'WinXP-1' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 507 of file VBoxManageModifyVM.cpp

```

If I have only WinXP (without ethernet switch), i have no error

**Comment by noplay** [comment]
With the 1.5.2 or with the source code of 1.5.3?

**Comment by Raizo62** [comment]
the source code of 1.5.3

**Comment by noplay** [comment]
You are using last Vbox also?

**Comment by Raizo62** [comment]
yes

**Comment by Raizo62** [comment]
Did you can reproduce the bug ? if not, do you want logs or others files ?

**Comment by noplay** [comment]
I think this the problem d68bf1c263bdc27a0c5a32b1e1dec676aee63072. Could you test with last source code?

**Comment by noplay** [comment]
You just need to test with last server

**Comment by Raizo62** [comment]
I have tested, and it works
Thanks :-)

**Comment by noplay** [comment]
Thanks for the feedback
