### ISSUE TITLE
Remote server uses port 3080, but GUI want to talk to 8000

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1449]
Installed gns3 server on baremetal (Packet.net) and encountered 2 issues:
1- During installation, the script canot change the hostname with "hostnamectl"

> Failed to get D-Bus connection ...

Looks like relateed to clound-init not allowing to change the hostname...
Worked arround it by setting the server hostname to gns3vm from the beginning and commented the corresponding command in the script.

2- Started gns3 as well as Openvpn servers with server listening on 3080

```
ajn@gns3vm:~$ netstat -tulpn
(No info could be read for "-p": geteuid()=1001 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:8003            0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:3080            0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
udp        0      0 0.0.0.0:1194            0.0.0.0:*                           - 
```

Even though, I added the server:3080
![selection_253](https://cloud.githubusercontent.com/assets/1716020/18023290/c653e4ec-6bf7-11e6-9a2e-2b8f75815121.png)

The GUI client ignores it and tries to connect to server:8000

```
2016-08-27 11:47:34 INFO http_client.py:421 Connection to http://172.16.54.1:8000
2016-08-27 11:47:34 DEBUG http_client.py:576 GET http://172.16.54.1:8000/v1/version {}
2016-08-27 11:47:34 INFO http_client.py:680 Response error: Connection refused (error: 1)
2016-08-27 11:47:34 INFO http_client.py:271 Connection to http://172.16.54.1:8000 closed
2016-08-27 11:47:34 ERROR http_client.py:444 Cannot connect to local server http://172.16.54.1:8000. Please check if GNS3 is allowed in your antivirus and firewall.
Error while creating project: Cannot connect to local server http://172.16.54.1:8000. Please check if GNS3 is allowed in your antivirus and firewall.
```

![selection_251](https://cloud.githubusercontent.com/assets/1716020/18023337/77f54b0a-6bf8-11e6-938c-2a051b8e825b.png)

**Comment by noplay** [comment]
Strange I don't see any reference to the port 8000 in the code.

On which port is bind your local server?

**Comment by AJNOURI** [comment]
port 8000

![selection_256](https://cloud.githubusercontent.com/assets/1716020/18029512/14817452-6c9a-11e6-9fdb-6d3fe39a93a9.png)


ps -aux
> ajn       6240  4.2  0.2 175920 34952 pts/4    Sl+  21:03   0:00 /usr/bin/python3 /usr/local/bin/gns3server --host=172.16.54.1 --port=8000 --local --controller --debug --log=/home/ajn/.config/GNS3/gns3_server.log --pid=/home/ajn/.config/GNS3/gns3_server.pid

**Comment by noplay** [comment]
Interresting this could mean that the remote use the port of the local server instead of the remote port.

**Comment by noplay** [comment]
I don't reproduce the issue. I suspect that the docker container you have put on the topology was created with the port 8000. And when you put in the topology it's recreate the missing server (as designed a node or a template is linked forever to the server you can't change it) 

Do you think it's that?

**Comment by AJNOURI** [comment]
Looks like not erlated to docker as It happens even if I want to add a cloud component, and disabled local server.
![selection_261](https://cloud.githubusercontent.com/assets/1716020/18061395/dcd90c38-6e22-11e6-8096-0567dd5438fe.png)


Something interestingn happened, if I add the remote server from GNS3 server tab, actually it tries to connect to the right server, though still doesn't succeed:

![image](https://cloud.githubusercontent.com/assets/1716020/18061576/876f7dd0-6e23-11e6-9194-98c8ce9de065.png)

**Comment by noplay** [comment]
Could you export debug information (Help / Export debug informations ) and send me the zip to julien@gns3.net ?

You can use my PGP key if you want to secure it:
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0898C847450754FB

**Comment by AJNOURI** [comment]
Tried this morning, it went OK...Don't get it, maybe server side :-|
![selection_283](https://cloud.githubusercontent.com/assets/1716020/18161042/7edd7b2c-7030-11e6-93b7-297218c5b321.png)

By the way, had some issues with container naming:
It refused "gns3/ovs-remote" and "gns3/openvswitch-temote" as container names but accepted "ovs". No such issues with other containers "ubuntu-remote". Looks like doesn't like the forward slash.

![selection_281](https://cloud.githubusercontent.com/assets/1716020/18160909/d86cd2e2-702f-11e6-8ecd-1ad9cf9e8b0f.png)

Sent the debug inf. just in case.

**Comment by noplay** [comment]
I think docker disallow / in the container name.

Is it a problem?

**Comment by AJNOURI** [comment]
Absolutely not, just locally I used to leave image names containing "/".
![image](https://cloud.githubusercontent.com/assets/1716020/18172601/612c1634-7066-11e6-8fa3-7871a2e961bf.png)
Anyway, thanks Julien. I'll close this, until an eventual appearance of the issue.

**Comment by noplay** [comment]
Thanks for the informations
