### ISSUE TITLE
Qemu VM Configuration Settings only allow for two hard drives

### ISSUE THREAD

**Issue by githubspam** [GNS3/gns3-gui#145]
GNS 1.1: The Qemu VM Configuration Settings only allow for two hard drives. This prevents the use of the NetAPP vSim (4 Drives) under Qemu.

**Comment by grossmj** [comment]
Noted, we will have something allowing you to have more in a future release.

Thanks,

**Comment by grossmj** [comment]
Hi,

You can now add hdc and hdd hard drives in GNS3 1.3 beta 1.

Cheers,
