### ISSUE TITLE
Support VNC display in VNC application setting

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1453]
Some VNC clients, e.g. gvncviewer, don't support the port for the connection. They want the VNC display number (port - 5900). Currently I'm solving that with a wrapper script, that subtracts 5900 from the port and then calls gvncviewer.

But it would be much nicer, when GNS3 can insert the display number directly into the command. Therefore I propose an additional variable (e.g. `%d` or `%P`), which is the port number - 5900. For gvncviewer the VNC command would the be `gvncviewer %h:%d`.

**Comment by ehlers** [comment]
After testing the Linux VNC viewer gvncviewer, xtightvncviewer and vinagre, I was quite disappointed. gvncviewer is working relatively well (besides needing display numbers), the other ones have issues.

But just tested RealVNC viewer and that's the best (IMHO) and it supports ports. So I no longer need the display number. Nevertheless such a feature might be valuable for others.

**Comment by noplay** [comment]
I pushed a fix if you are interrested

**Comment by ehlers** [comment]
Just tested, working fine. Thanks.
