### ISSUE TITLE
BUG 1.5 : rename ethernet switch

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1460]
Hi

On the 1.5.3dev1 of 2016/08/24. (Sorry, i have Internet problem then i can't verify on the last release)

On the lab : 
i put an ethernet switch (default name : SW1)
i put an ethernet switch (default name : SW2)
i put an ethernet switch (default name : SW3)
i put an ethernet switch (default name : SW4)
i delete the ethernet switch SW2
i rename SW4 to SW2
i put an ethernet switch (default name : SW5)
I rename SW5 to SW4 -> Error : Name SW4 is already used by another node

**Comment by noplay** [comment]
Not tested. Did you save before rename SW5 to SW4?

Some operations cleanup are made only when we save to prevent issue if you
quit and reopen from the project on disk.

**Comment by Raizo62** [comment]
Yes, i have tested to save the project before to rename SW5 to SW4. It doesn't work.
If i close GNS3 and reopen it, it works but it is not very clean : i can have running VM....

**Comment by noplay** [comment]
Thanks it's fixed
