### ISSUE TITLE
Update iTerm3 console settings

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1466]
This proposal updates the console settings for iTerm3
- name changed from "2.9" to "3". 2.9 was only used during the beta and iTerm 3 is non-beta quite some time now.
- added `command "sh`' to `create tab with default profile` allows using this settings even when the user changes the command to something non-standard. This makes it a little bit more robust.
- `set name to "%d"` sets the tab title to the hostname. Dynamips VMs do that automatically, but e.g. docker VMs don't.
- `exec telnet` instead of `telnet` closes tab, when the telnet session ends. That's the same behavior as the tabbed Terminal.

```
diff --git a/gns3/settings.py b/gns3/settings.py
index 628fba4..8454a05 100644
--- a/gns3/settings.py
+++ b/gns3/settings.py
@@ -100,7 +100,7 @@ elif sys.platform.startswith("darwin"):
                  " -e '  end tell'"
                  " -e 'end tell'"
                  " -e 'end tell'",
-        'iTerm 2.9': "osascript -e 'tell application \"iTerm\"'"
+        'iTerm 3': "osascript -e 'tell application \"iTerm\"'"
                     " -e 'activate'"
                     " -e 'if (count of windows) = 0 then'"
                     " -e '   set t to (create window with default profile)'"
@@ -108,10 +108,11 @@ elif sys.platform.startswith("darwin"):
                     " -e '   set t to current window'"
                     " -e 'end if'"
                     " -e 'tell t'"
-                    " -e '    create tab with default profile'"
+                    " -e '    create tab with default profile command \"sh\"'"
                     " -e '    set s to current session'"
                     " -e '    tell s'"
-                    " -e '        write text \"telnet %h %p\"'"
+                    " -e '        set name to \"%d\"'"
+                    " -e '        write text \"exec telnet %h %p\"'"
                     " -e '    end tell'"
                     " -e 'end tell'"
                     " -e 'end tell'",
```

**Comment by noplay** [comment]
I will test before the 1.5.3 release. But sound good

**Comment by ehlers** [comment]
And maybe we should cleanup the names. "iTerm" (http://iterm.sourceforge.net) is dead since 2011, the GNS3 settings for iTerm are really for iTerm2 v2.x (maybe also for v1.0, but I don't know). And my term "ITerm 3" is not correct as well, it's "iTerm2 v3.x" (and iTerm2 v2.9").

**Comment by ehlers** [comment]
Just looked into the original iTerm documentation. It's Applescript supports looks quite similar to iTerm2 v2.x, so the "iTerm" settings might actually work for the original iTerm. But maybe we shouldn't care about 5 years old software.

Program naming can be complicated...

**Comment by noplay** [comment]
I have integrated this
![capture d ecran 2016-09-03 a 22 00 42](https://cloud.githubusercontent.com/assets/345437/18227353/04b77b24-7222-11e6-96cb-5b5dac0038b4.png)

**Comment by noplay** [comment]
And merged the commit
