### ISSUE TITLE
When i set IOU serial interfaces to 0 those are still shown in GUI

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1467]

**Comment by taurus8** [comment]
![error](https://cloud.githubusercontent.com/assets/8465075/18209429/f8fca8ec-7148-11e6-9a83-40133b3baf2f.png)

**Comment by noplay** [comment]
With which image?

Thanks for the report

**Comment by noplay** [comment]
Note: the report is for GNS3 2.0

**Comment by noplay** [comment]
Fixed the problem is bigger. It's how we detect a change in the list of ports for refreshing the interface.

**Comment by noplay** [comment]
Thanks for the help
