### ISSUE TITLE
when i select multiple routers and change their interfaces all routers suddenly  move to center and hide  themselves behind each other   

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1472]
![1](https://cloud.githubusercontent.com/assets/8465075/18272438/0c249ea0-744d-11e6-8d0d-5b26486350cb.png)
![2](https://cloud.githubusercontent.com/assets/8465075/18272451/19de1eae-744d-11e6-8a8f-99081fd0916f.png)

**Comment by noplay** [comment]
Confirmed

**Comment by noplay** [comment]
Hmm it's a side effect on how the edit configuration is done.

Actually we display the settings of the first item and recopy them on the page of the other item before saving. Problem in the settings you have also the positions.

**Comment by noplay** [comment]
In 1.5 we avoid this kind of issue by a blacklist of settings properties:
https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/iou/pages/iou_device_configuration_page.py#L253

It's easy to miss something :(

**Comment by noplay** [comment]
It's fix I hope to not have introduced bug because the fix impact all configuration pages. Hopefully we have enough time to retest all settings.
