### ISSUE TITLE
"Lower one layer" is not being saved when i close project

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1473]
Hi
when i close project then reopen it, i must do lower one layer 
![x1](https://cloud.githubusercontent.com/assets/8465075/18273720/02e59a86-7454-11e6-9cae-a550ba6c9a00.png)

repopen
![x2](https://cloud.githubusercontent.com/assets/8465075/18273740/1a0a1f2a-7454-11e6-848b-e364abdd3948.png)

**Comment by noplay** [comment]
It seem it's not a layer save issue, but that when we recreate a link we don't set a layer

**Comment by noplay** [comment]
It's fixed
