### ISSUE TITLE
gns3a import is not detected as GNSA file if the extension is not gns3a

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1490]
If the file is not named .gns3a when using import appliance GNS3 will think this a topology.

![image](https://cloud.githubusercontent.com/assets/345437/18349526/304e6870-75d2-11e6-9f3c-cf250eadf228.png)

A user got this error when opening 
cisco-asav.gns3a**.txt**

**Comment by grossmj** [comment]
Can't we detect this by reading the file? For projects we should have "type" field set to "topology". Apparently we are missing something like that in .gns3a

**Comment by noplay** [comment]
Don't know what to do about that. Discussion continue on #1491
