### ISSUE TITLE
Start/Stop all resets node position

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1494]
Drop a node (tested with IOS router), move it to another position and then use start/stop all in the toolbar. The node position will resets to where the node was the first time.

**Comment by noplay** [comment]
I don't replicate the issue

**Comment by noplay** [comment]
Got an explanation.

We send position change only when you unselect. But you can keep stuff
selected and start all.

**Comment by noplay** [comment]
Fixed, when you release the mouse button we send position back to the server
