### ISSUE TITLE
checkToolsState Command Missing in VMware VIX 1.15.3 (Workstation 12.1.1)

### ISSUE THREAD

**Issue by schuecl** [GNS3/gns3-gui#1499]
GNS3 uses the command 'vmrun ... checkToolsState', which was available in previous versions of VIX and vmrun, but now appears to be missing. As a result, GNS3 errors out while controlling VMware VMs. My setup is GNS3 1.5.2, VMware Workstation 12.1.1 and VMware VIX 1.15.3. Couldn't find any additional info on this issue via the web. I should note that other vmrun commands work via GNS3, such as start.

![gns3](https://cloud.githubusercontent.com/assets/22088237/18371880/ef8a2c38-7672-11e6-9830-ef635194bb4f.jpg)

**Comment by noplay** [comment]
We will check.

But something seem wrong on your system. You should not have vix installed when workstation is installed. vmrun is provided with Workstation. VIX is need only for Player user.

**Comment by schuecl** [comment]
I'll map directly to Workstation's vmrun instead. I previously had Player before Workstation, so that may be why.

**Comment by noplay** [comment]
Uninstall vix should solve the problem.

I know that VMware do some black magic when you switch from player to workstation. Could be the source of the problem.

But I will try on a clean machine to see why the command has disapear.

**Comment by schuecl** [comment]
So, here was what the issue was. I had previously been using Player, which in the GNS3 preferences points to the VIX vmrun.exe, and switched over to Workstation. I re-installed GNS3 afterwards, but it was still pointing to the VIX vmrun. I changed it to the WS vmrun and it appears to work fine now. Closing this out.
