### ISSUE TITLE
Sometimes "Duplicate" put text too far in topology

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1501]
![1](https://cloud.githubusercontent.com/assets/8465075/18387115/e398bf60-76af-11e6-9313-877f159719b4.png)
![2](https://cloud.githubusercontent.com/assets/8465075/18387116/e40534d8-76af-11e6-94fa-f0b4a8cbb555.png)

**Comment by noplay** [comment]
Lol I was putting x in y :P
