### ISSUE TITLE
Gui shows double interfaces when i close the project and reopen it

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1502]
So strange
i put two IOU routers in topology , change their eth interfaces to 1 and ser to 0
connect them with eth 0/0
close the project 
re open it
Gui show 8 Ethernet interfaces for each router

**Comment by noplay** [comment]
Fixed but big code impact on the management of ports for all devices during the fix I hope to not have introduce bugs.

**Comment by taurus8** [comment]
Hi
when i drag an IOU router i see following

![1](https://cloud.githubusercontent.com/assets/8465075/18524172/987b968a-7acc-11e6-8dc5-bdc9df09ef31.png)
![2](https://cloud.githubusercontent.com/assets/8465075/18524200/aa9e7620-7acc-11e6-9710-bc919df0edcb.png)

**Comment by taurus8** [comment]
![3](https://cloud.githubusercontent.com/assets/8465075/18524451/abe21c66-7acd-11e6-9629-ba0af8f36178.png)

**Comment by taurus8** [comment]
And when i press "Add a link" on Router it only shows Ethernet interfaces NOT serial

**Comment by taurus8** [comment]
when i connect two IOU Switch by first Ethernet 0/0 interfaces 
 ![s](https://cloud.githubusercontent.com/assets/8465075/18526637/96266fa4-7ad6-11e6-8484-2ebb25b29c98.png)

"add a link" shows correct 16 interfaces here

**Comment by noplay** [comment]
Fixed
