### ISSUE TITLE
"Save as Projects" Creates folder with .gns3 extention  for me

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1503]
![eeeee](https://cloud.githubusercontent.com/assets/8465075/18388786/364360f0-76b8-11e6-8b2b-5a72a16daf50.png)

**Comment by noplay** [comment]
Seem to be a bug in the import function

**Comment by noplay** [comment]
Thanks a lot for this report

**Comment by taurus8** [comment]
You are welcome
