### ISSUE TITLE
Add 0.0.0.0 to the list of possible host binding

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1506]
Actually we list only the IP but from interface you can't say listen on all hosts

**Comment by grossmj** [comment]
We have to be careful of side effects, I kinda remember not putting that '0.0.0.0' in the list for a good reason... unfortunately I cannot remember why ;)

**Comment by noplay** [comment]
Hmm perhaps if we add 0.0.0.0 the gui will not know on which ip to connect. And this mean if the host 0.0.0.0 you need  to connect on 127.0.0.1

**Comment by noplay** [comment]
Same for the compute
