### ISSUE TITLE
Dockerize IOU

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-gui#1508]
Cisco IOU is quite complicate to integrate, it needs 32-bit shared libraries, a special NETMAP configuration and iouyap. Using docker images for IOU would encapsulate all this special stuff. Julien made an early test with IOU within docker, see https://github.com/GNS3/gns3-registry/tree/master/docker/iou.

I've created a more advanced version, see https://github.com/ehlers/gns3-docker-images/tree/master/iou-base. It consists of a base image, that contains everything except the IOU binary, the license and the initial config. With the help of the `create-iou-image` script the user creates a new docker IOU image for each IOU binary, adding the missing stuff (binary license, config) to the base. As the base image is quite small (based on alpine, about 15 MB), this is a quite efficient way using IOU.

Of course the use of `create-iou-image` is just a temporary solution, a much better way would be a dialog integrated into GNS3.

During the development I encountered the following issues:
- Only support for ethernet interfaces  
  Especially for training this is a mayor drawback.
- The base MAC address of an IOU device is based on the device ID, see https://github.com/GNS3/gns3-server/issues/557. That means, that every IOU device in a project needs a unique ID. Currently the docker image has no way choosing one. Currently I'm using the device name to create an ID between 1..997, but that's not safe.  
  The GNS3 GUI already creates device IDs. If those IDs can be sent to the docker VMs, this issue should be solved. Maybe even https://github.com/GNS3/gns3-server/issues/557 can be solved that way.
- The interface names differ between IOU and the GNS3 GUI. That may create some confusion. The other VM types have a flexible way naming the interfaces in the GUI. Maybe that can be also added to the docker container.
- There is no GUI field in docker to modify the NVRAM and MEM size. I'm using environment variables for the (few) situations, where the defaults needs to be changed.

While IOU in docker basically works, a nice support needs some (small) changes. For me the main issue is the loss of the serial interfaces.

@noplay @grossmj What do you think about IOU within docker?

**Comment by noplay** [comment]
I think it's how we will support IOU in the future. We know that one day the 32 bit support on most linux will be dropped and we will need to have an alternative. The deadline is ubuntu 18.10.

Your alpine image is very interesting due to the small size.

I see two path:
* IOU is a container like other in the interface. You create them using gns3a, no more dedicated IOU settings / wizard. And we improve a lot docker support to allow container to have custom settings
* IOU is a different interface

We don't know how IOL in VIRL will work it can change the strategy.

> * Only support for ethernet interfaces
> Especially for training this is a mayor drawback.

Jeremy need to confirm that. But I think serial is just display. Under the hood the network communication is the same. 

We can probably modify the docker support to inject ethernet adapter with a different name in the container to symbolize that this adapter are serial link.

Question is it specific to IOU or could we use that in other container.

Also it seem IOL doesn't support serial. 

> * The base MAC address of an IOU device is based on the device ID, see GNS3/gns3-server#557. That means, that every IOU device in a project needs a unique ID. Currently the docker image has no way choosing one. Currently I'm using the device name to create an ID between 1..997, but that's not safe.
The GNS3 GUI already creates device IDs. If those IDs can be sent to the docker VMs, this issue should be solved. Maybe even GNS3/gns3-server#557 can be solved that way.

No idea on this topic :( 

> * The interface names differ between IOU and the GNS3 GUI. That may create some confusion. The other VM types have a flexible way naming the interfaces in the GUI. Maybe that can be also added to the docker container.

I will start some work on port naming architecture https://github.com/GNS3/gns3-server/issues/676 We can probably  add a support for docker in a futur release.  

> * There is no GUI field in docker to modify the NVRAM and MEM size. I'm using environment variables for the (few) situations, where the defaults needs to be changed.

Perhaps we need a settings system for containers. When you import the GNS3A the appliance file say this variable can be configured and this will be reflect to the container env. 


Also I'm not a big fan of embedding the IOU image in the container because it's break the project portability. I think we could find a way for mounting the IOU images directory and with a env variable choose the correct image.

But your technique work with today GNS3 and that's cool. On a linux box you can use IOU without the VM or ugly 32 bits dependencies just docker.

**Comment by ehlers** [comment]
Thanks for your kind review.

> I think it's how we will support IOU in the future. We know that one day the 32 bit support on most linux will be dropped and we will need to have an alternative. The deadline is ubuntu 18.10.

The docker solution depends on the kernel's capability to execute 32 bit binaries even on a 64 bit system. As long as this functionality is kept, we are safe. But when this is dropped, only a VM solution will help.

**Comment by noplay** [comment]
I doubt kernel will stop support 32 bit. But the package system could
stop.  If the container still use an old distribution no issue. And I think
docker work on stuff for multi architecture support. Even if CPU stop
supporting 32 bit or everybody start to use an ARM processor we could
imagine using that.

**Comment by ehlers** [comment]
Serial links work, sort-of !!!

I've connected an IOU serial link via iouyap to an docker ethernet interface, connected this ethernet interface to another docker IOU, where the IOU serial link is connected to an docker ethernet interface. They can communicate via this link.

Then I started wireshark. It tries to decode the serial data as an ethernet frame, what (of course) fails. When I compare this trace with a trace of a real serial link, the raw data is OK. Even packet with data length < 64 byte (minimum ethernet frame length) are fine. Then I saved the capture, changed the encapsulation with "editcap -T chdlc infile outfile" and loaded it again. This results in a perfectly fine trace file.

So technically it's possible to use the serial interface. The main task is, to let the GUI handle this ethernet link as a serial one.

**Comment by noplay** [comment]
Great news.

**Comment by ehlers** [comment]
For testing the serial connection I modified my iou-base docker image https://github.com/ehlers/gns3-docker-images/tree/master/iou-base to use the last controller as a serial one if at least 9 interfaces are configured. For example, if the docker VM is configured with 12 interfaces, then eth0-eth7 are the IOU ethernet0/0-1/3, eth8-eth11 are the IOU serial2/0-2/3.

**Comment by ehlers** [comment]
Updated my iou-base docker image, now you can control the number of serial interfaces with the environment variable SERIAL.

On the server side, the only issue left is that of the unique device ID.

On the GUI the setting of environment variables could be handled more user-friendly for all docker images. That's not IOU specific. But the interface handling within the GUI, especially the serial interfaces, is special for IOU.

**Comment by b-ehlers** [comment]
IOU-base has moved to https://git.bernhard-ehlers.de/ehlers/gns3-docker-images/src/branch/master/iou-base

**Comment by grossmj** [comment]
I think we going to have to have something like this ssooner or later.

@b-ehlers  do you have your repository https://github.com/ehlers/gns3-docker-images/tree/master/iou-base available somewhere?

**Comment by b-ehlers** [comment]
Here the files from the iou-base directory: [iou-base.tar.gz](https://github.com/GNS3/gns3-gui/files/7283682/iou-base.tar.gz)

Please note, that I haven't updated them for quite a while, currently it doesn't work and needs fixing (not me).
* It depends on iouyap, that is no longer available in alpine. I wasn't able to use ubridge instead, as I found no way to create an IOU bridge from the command line.
* The Dockerfile loads the IOU utils from <https://git.b-ehlers.de/ehlers/IOUtools/raw/branch/master/>, which is no longer available. The utils are an official part of GNS3, the latest version is available` in <https://github.com/GNS3/gns3-server/tree/3.0/gns3server/compute/iou/utils/>

**Comment by grossmj** [comment]
@b-ehlers strange, thanks for the heads up 👍

**Comment by grossmj** [comment]
Looks great, I also prefer the 2nd solution. Please send your patched iou_vm.py, thanks 👍

**Comment by b-ehlers** [comment]
The patch was made against GNS3 v2.2.33, but I suggest to port it to v3.x to keep 2.2 stable.

As a nice feature it falls back to the system loader/libraries, when it doesn't find the user defined loader.

Here my patch for the second solution:

```
diff --git a/gns3server/compute/iou/iou_vm.py b/gns3server/compute/iou/iou_vm.py
index 617b247e..cfa364fb 100644
--- a/gns3server/compute/iou/iou_vm.py
+++ b/gns3server/compute/iou/iou_vm.py
@@ -80,6 +80,8 @@ class IOUVM(BaseNode):
         self._started = False
         self._nvram_watcher = None
         self._path = self.manager.get_abs_image_path(path, project.path)
+        self._lib_base = self.manager.get_images_directory()
+        self._loader = None
         self._license_check = True
 
         # IOU settings
@@ -142,6 +144,7 @@ class IOUVM(BaseNode):
         """
 
         self._path = self.manager.get_abs_image_path(path, self.project.path)
+        self._loader = None
         log.info('IOU "{name}" [{id}]: IOU image updated to "{path}"'.format(name=self._name, id=self._id, path=self._path))
 
     @property
@@ -173,8 +176,9 @@ class IOUVM(BaseNode):
         Finds the default RAM and NVRAM values for the IOU image.
         """
 
+        self._check_requirements()
         try:
-            output = await gns3server.utils.asyncio.subprocess_check_output(self._path, "-h", cwd=self.working_dir, stderr=True)
+            output = await gns3server.utils.asyncio.subprocess_check_output(*self._loader, self._path, "-h", cwd=self.working_dir, stderr=True)
             match = re.search(r"-n <n>\s+Size of nvram in Kb \(default ([0-9]+)KB\)", output)
             if match:
                 self.nvram = int(match.group(1))
@@ -216,6 +220,20 @@ class IOUVM(BaseNode):
         if not os.access(self._path, os.X_OK):
             raise IOUError("IOU image '{}' is not executable".format(self._path))
 
+        # set loader command
+        if elf_header_start[4] == 1:
+            loader = os.path.join(self._lib_base, "lib", "ld-linux.so.2")
+            lib_path = ":".join((os.path.join(self._lib_base, "lib"),
+                                 os.path.join(self._lib_base, "lib", "i386-linux-gnu")))
+        else:
+            loader = os.path.join(self._lib_base, "lib64", "ld-linux-x86-64.so.2")
+            lib_path = ":".join((os.path.join(self._lib_base, "lib64"),
+                                 os.path.join(self._lib_base, "lib", "x86_64-linux-gnu")))
+        if os.path.isfile(loader):
+            self._loader = [loader, "--library-path", lib_path]
+        else:
+            self._loader = []
+
     def __json__(self):
 
         iou_vm_info = {"name": self.name,
@@ -378,8 +396,10 @@ class IOUVM(BaseNode):
         Checks for missing shared library dependencies in the IOU image.
         """
 
+        env = os.environ.copy()
+        env["LD_TRACE_LOADED_OBJECTS"] = "1"
         try:
-            output = await gns3server.utils.asyncio.subprocess_check_output("ldd", self._path)
+            output = await gns3server.utils.asyncio.subprocess_check_output(*self._loader, self._path, env=env)
         except (OSError, subprocess.SubprocessError) as e:
             log.warning("Could not determine the shared library dependencies for {}: {}".format(self._path, e))
             return
@@ -551,7 +571,7 @@ class IOUVM(BaseNode):
                 log.info("Starting IOU: {}".format(command))
                 self.command_line = ' '.join(command)
                 self._iou_process = await asyncio.create_subprocess_exec(
-                    *command,
+                    *self._loader, *command,
                     stdout=asyncio.subprocess.PIPE,
                     stdin=asyncio.subprocess.PIPE,
                     stderr=subprocess.STDOUT,
@@ -1070,7 +1090,7 @@ class IOUVM(BaseNode):
         if "IOURC" not in os.environ:
             env["IOURC"] = self.iourc_path
         try:
-            output = await gns3server.utils.asyncio.subprocess_check_output(self._path, "-h", cwd=self.working_dir, env=env, stderr=True)
+            output = await gns3server.utils.asyncio.subprocess_check_output(*self._loader, self._path, "-h", cwd=self.working_dir, env=env, stderr=True)
             if re.search(r"-l\s+Enable Layer 1 keepalive messages", output):
                 command.extend(["-l"])
             else:
```

There are several decision to make before using this solution:

* Where should the loader and library be stored? My patch uses the `lib` and `lib64` subdirectories of the IOU image directory.
* Will GNS3 provide a package with these libraries? If yes, from what distribution. In my tests Debian 9 (Stretch) and CentOS 7 are working fine. But newer distribution fail, when using them within Fedora 36. But Debian 9 is already EOL and CentOS 7 will be in 1 3/4 years. For Debian 9 there is a commercial offering for another 5 years of support, the [Debian LTS/Extended](https://wiki.debian.org/LTS/Extended) page says that "updates and security fixes will be available for all Debian users without cost". I haven't checked the Ubuntu distributions.

Here the libraries for Debian 9 Stretch, including the build scripts (using Docker): [libc_iou_stretch.tar.gz](https://github.com/GNS3/gns3-gui/files/9042107/libc_iou_stretch.tar.gz). Within this archive it contains `libc-iou.tar.gz`. Unpack it into the IOU image directory to use it with this patch.

**Comment by b-ehlers** [comment]
Extended solution: An additional check in `_check_requirements()` tests, if the user defined loader is really suitable for the IOU binary. This is not really required, it's just an extra safeguard.

Here the complete patch (against GNS3 2.2.33): [iou_loader.patch](https://github.com/GNS3/gns3-gui/files/9121213/iou_loader.patch.txt)

**Comment by grossmj** [comment]
I have created a PR with your patch: https://github.com/GNS3/gns3-server/pull/2086 and tested on Ubuntu 22.04 using your provided Debian 9 Stretch libraries, it worked fine :)

> Where should the loader and library be stored? My patch uses the lib and lib64 subdirectories of the IOU image directory.

This location could work. It could also be in the `~/.config/GNS3/3.0` directory but I think I prefer the IOU image directory.

> Will GNS3 provide a package with these libraries?

Eventually yes I think. For now we are safe as long as 32-bit support isn't dropped, right?

**Comment by b-ehlers** [comment]
> > Will GNS3 provide a package with these libraries?
> 
> Eventually yes I think. For now we are safe as long as 32-bit support isn't dropped, right?

Correct, this patch will fallback to the system loader/libraries, when it doesn't find the user defined loader. So as long a distribution supports 32 bit glibc libraries, that are not too recent, it's safe to use them. Notably exceptions are Alpine Linux (that doesn't provide glibc libraries) and recent Fedora distibutions (their 32-bit libraries are too new for IOU, see https://github.com/GNS3/gns3-server/issues/1979#issuecomment-938111829).

But in any case the linux kernel has to support 32-bit programs, otherwise IOUs won't run. Even Docker won't help then. But I assume it will take very long until Linux drops 32-bit support.

**Comment by mmaeso** [comment]
CML 2.7 has added support for x86_64 based IOU running IOS XE 17. The images run without (apparent) issues on an Ubuntu 22.04 docker container, since they don't even require an iourc file to run. Considering other vendors are adding support for containerized network devices (cRPD, XRd, cSRX, etc), would this be of any interest to the development team?

**Comment by grossmj** [comment]
@mmaeso 

Thanks for the input. That's great news about the iourc file!

> Here the libraries for Debian 9 Stretch

Looks like we going to need more recent libs since `x86_64_crb_linux-adventerprisek9-ms.bin` seems to require GLIC 2.27.

```
./lib64/ld-linux-x86-64.so.2 --library-path /home/gns3/GNS3/images/IOU/lib/x86_64-linux-gnu ./x86_64_crb_linux-adventerprisek9-ms.bin -e 4 -s 0 1
./x86_64_crb_linux-adventerprisek9-ms.bin: /home/gns3/GNS3/images/IOU/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by ./x86_64_crb_linux-adventerprisek9-ms.bin)
```
