### ISSUE TITLE
Filter special network interface server side

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1509]
In order to have the list in only one location move this to server:
```python
    @staticmethod
    def isSpecialInterface(interface):

        for special_interface in ("lo", "vmnet", "vboxnet", "docker", "lxcbr", "virbr", "ovs-system", "veth", "fw", "p2p"):
            if interface.lower().startswith(special_interface):
                return True
        return False

**Comment by grossmj** [comment]
What will happen if an user really want to use one of these interface? Right now we just hide these interface by default in the Cloud properties but they can be shown when using a checkbox.

**Comment by noplay** [comment]
True, even if I think most people will not correctly use that. I have seen multiple user on forum trying to do black magic with vmnet because they don't understand what they are.

Perhaps server could return an info on the interface telling it's special allowing any GUI interface to filter it.

**Comment by noplay** [comment]
Now server return a flag for filtering the interface.
