### ISSUE TITLE
Sometimes i receive following error when i press "stop all devices" 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1518]
![errr](https://cloud.githubusercontent.com/assets/8465075/18607142/5141eb66-7cd9-11e6-9270-ad24b22ded6f.png)

**Comment by noplay** [comment]
Could be Linux specific when I see the error message (dbus)

**Comment by noplay** [comment]
I don't replicate on my mac

**Comment by taurus8** [comment]
i dnot receive this error anymore better close it

**Comment by noplay** [comment]
Perhaps a bug due to another part of the system

**Comment by taurus8** [comment]
yes , maybe when i disconnected my network

**Comment by noplay** [comment]
Some black magic between QT, systemd and network manager :P
