### ISSUE TITLE
When  i do "save project as" and open new saved project without closing gns3 i receive following error 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1519]
![eeerrrrr](https://cloud.githubusercontent.com/assets/8465075/18609780/c3e54aaa-7d1f-11e6-8f77-f30a96a84d52.png)

but when i close gns3 and open new saved project it works

**Comment by noplay** [comment]
I don't exactly get the issue. But I suspect it's because at import we keep the same node ID.

**Comment by noplay** [comment]
Ok I rewrote the import to change node id and it seem ok now.

Thanks for the report

**Comment by taurus8** [comment]
Thanks its working great now
