### ISSUE TITLE
GNS3 1.52 simple and IOU switches not passing traffic 

### ISSUE THREAD

**Issue by bluwing** [GNS3/gns3-gui#1521]
This seems like it might be related to  Issue #1408 & others...

Context:   GNS 1.5.2 on Windows 10 

The simple and IOU switches don't work reliably in the topologies shown below. 

![simpleswitch](https://cloud.githubusercontent.com/assets/22296228/18633672/6ce79668-7e4b-11e6-8463-bd36ba057066.png)

---

![iouswitch](https://cloud.githubusercontent.com/assets/22296228/18633683/7e383012-7e4b-11e6-8883-7cc43cfff031.png)

Wireshark shows that neither type of switch is passing frames between any port.  
a 'sho mac address' on the IOU switch shows an empty mac table. 

But this very simple topology works reliably. 

![simpletopo](https://cloud.githubusercontent.com/assets/22296228/18633692/89fb19aa-7e4b-11e6-988c-17f085815bbd.png)

The IOU switch in the simple topo shows the mac addresses of the connected devices. 
Might this be related to the WinPcap issues mentioned in #1408 and other items? 
If so, is there a reliable workaround/fix?

Thanks....

**Comment by noplay** [comment]
Why you have cloud in the middle? It's also IOU nodes ?

**Comment by bluwing** [comment]
Sorry, should have made that clear.   The cloud icons actually are single IOU routers. I just used the cloud icon to represent external routing domains.  BTW, have tried Win10Pcap and npcap 0.98 (?) with same results.                                                                                                                                                                                                                 From: Julien DuponchelleSent: Monday, September 19, 2016 10:12To: GNS3/gns3-guiReply To: GNS3/gns3-guiCc: bluwing; AuthorSubject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Why you have cloud in the middle? It's also IOU nodes ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GNS3/gns3-gui","title":"GNS3/gns3-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GNS3/gns3-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noplay in #1521: Why you have cloud in the middle? It's also IOU nodes ?"}],"action":{"name":"View Issue","url":"https://github.com/GNS3/gns3-gui/issues/1521#issuecomment-248004622"}}}

**Comment by grossmj** [comment]
```
Might this be related to the WinPcap issues mentioned in #1408 and other items? 
```

The WinPcap issue was happening with VMware VMs, shound't be a problem for other node types.

Do you run everything in the GNS3 VM?

**Comment by bluwing** [comment]
Yes, it's all running in the GNS3 VM. The routers are all IOU 15.5.2. The IOU switch is 15.1.b.                                                                                                                                                                                                                                                                                                                                        Todd RossNetwork Design SpecialistSeraband Corporation 6527 Marina Drive, Manotick, Ontario K4M 1B3Tel:  613-863-8014                                                                                                                                                                                                                 From: Jeremy GrossmannSent: Monday, September 19, 2016 13:27To: GNS3/gns3-guiReply To: GNS3/gns3-guiCc: bluwing; AuthorSubject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Might this be related to the WinPcap issues mentioned in #1408 and other items? 


The WinPcap issue was happening with VMware VMs, shound't be a problem for other node types.

Do you run everything in the GNS3 VM?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GNS3/gns3-gui","title":"GNS3/gns3-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GNS3/gns3-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grossmj in #1521: ```\r\nMight this be related to the WinPcap issues mentioned in #1408 and other items? \r\n```\r\n\r\nThe WinPcap issue was happening with VMware VMs, shound't be a problem for other node types.\r\n\r\nDo you run everything in the GNS3 VM?"}],"action":{"name":"View Issue","url":"https://github.com/GNS3/gns3-gui/issues/1521#issuecomment-248060822"}}}

**Comment by noplay** [comment]
Can you try to replace the simple switch by an openvswitch?

You can use this template to setup it:
https://gns3.com/marketplace/appliance/openvswitch

**Comment by bluwing** [comment]
Sure... will try after work tonight & advise.                                                                                                                                                                                                                                                                                                                                         Todd RossNetwork Design SpecialistSeraband Corporation 6527 Marina Drive, Manotick, Ontario K4M 1B3Tel:  613-863-8014                                                                                                                                                                                                                 From: Julien DuponchelleSent: Tuesday, September 20, 2016 02:55To: GNS3/gns3-guiReply To: GNS3/gns3-guiCc: bluwing; AuthorSubject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Can you try to replace the simple switch by an openvswitch?

You can use this template to setup it:
https://gns3.com/marketplace/appliance/openvswitch

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GNS3/gns3-gui","title":"GNS3/gns3-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GNS3/gns3-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noplay in #1521: Can you try to replace the simple switch by an openvswitch?\r\n\r\nYou can use this template to setup it:\r\nhttps://gns3.com/marketplace/appliance/openvswitch\r\n"}],"action":{"name":"View Issue","url":"https://github.com/GNS3/gns3-gui/issues/1521#issuecomment-248218697"}}}

**Comment by bluwing** [comment]
Hi, Julien, Got the template installed OK,  but am not familiar with configuring the switch.   If you have a minute and are familiar with it, could you whip up a configuration like this:2 ports: 802.1q trunks,   vlans 10, 20, 301 port each access port, vlan 10 access port, vlan 20 access port, vlan 30That will exactly duplicate the problem scenario. Instructions on loading the config into the switch would be good, too. If you can't, no worries: I'll figure it out. Cheers, Todd Date: Tue Sep 20 2016 08:04:26 GMT-0400 (Eastern Summer Time)To: Julien Duponchelle <reply@reply.github.com>Subject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Sure... will try after work tonight & advise. Todd RossNetwork Design SpecialistSeraband Corporation 6527 Marina Drive, Manotick, Ontario K4M 1B3Tel:  613-863-8014 From: Julien DuponchelleSent: Tuesday, September 20, 2016 02:55To: GNS3/gns3-guiReply To: GNS3/gns3-guiCc: bluwing; AuthorSubject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Can you try to replace the simple switch by an openvswitch?You can use this template to setup it:https://gns3.com/marketplace/appliance/openvswitch—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by grossmj** [comment]
Have you tried to replace all switches by IOU only? Don't mix simple and IOU switches.

Also, it would be easier for us if you have a simpler topology that have the issue so we can reproduce the it on our side.

Thanks,

**Comment by noplay** [comment]
Oh I didn't except that you are using vlan.  I have no idea how to configure them in Openvswitch

**Comment by bluwing** [comment]
No sweat. Will experiment & let u know.                                                                                                                                                                                                                                                                                                                                         Todd RossNetwork Design SpecialistSeraband Corporation 6527 Marina Drive, Manotick, Ontario K4M 1B3Tel:  613-863-8014                                                                                                                                                                                                                 From: Julien DuponchelleSent: Wednesday, September 21, 2016 03:31To: GNS3/gns3-guiReply To: GNS3/gns3-guiCc: bluwing; AuthorSubject: Re: [GNS3/gns3-gui] GNS3 1.52 simple and IOU switches not passing traffic (#1521)Oh I didn't except that you are using vlan.  I have no idea how to configure them in Openvswitch

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GNS3/gns3-gui","title":"GNS3/gns3-gui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GNS3/gns3-gui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@noplay in #1521: Oh I didn't except that you are using vlan.  I have no idea how to configure them in Openvswitch"}],"action":{"name":"View Issue","url":"https://github.com/GNS3/gns3-gui/issues/1521#issuecomment-248533548"}}}

**Comment by EB-athila** [comment]
I'm having the same issue. Tested 1.4.6 (macOS-Fusion), 1.5.2 (Ubuntu-gnome14.04) and 1.5.2 (W10-vmWS12).
 Topology: INE R&Sv5 (10 IOL-l3 nodes connected to a dynamips simple switch and/or IOL-L2)

If I start all nodes at the same time, no problem. But if for some reason, I stop part of the topology then the traffic stops between IOL-l3 and dynamips switch. Re-starting the shutdown nodes will fix it.

**Comment by noplay** [comment]
Can you test if the alpha 2 solve the issue?

**Comment by EB-athila** [comment]
Alpha 2.0 shows same behavior with 10IOL-l3 + 4IOL-L2.

If the setup is 20IOL-L3 + 4IOL-L2 and all startup at once, the traffic never starts flowing.

**Comment by grossmj** [comment]
So if this only a project with IOL nodes then that's more concerning because we don't control what going on inside the IOL nodes.

We really need to implement something to help us investigate that all UDP tunnels are correctly set up by GNS3.
