### ISSUE TITLE
GUI interfaces  name and order are NOT same as vIOS L2 interfaces name and order

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1523]
![1](https://cloud.githubusercontent.com/assets/8465075/18662417/9074fbc2-7f2f-11e6-8d0c-7c4fc5b47904.png)
![2](https://cloud.githubusercontent.com/assets/8465075/18662430/9cadded6-7f2f-11e6-8000-eda65cea0dd9.png)

**Comment by noplay** [comment]
Are you using the template for IOSv? 

https://gns3.com/marketplace/appliance/cisco-iosvl2

In the template the interface seem to named Gi0/0  Gi0/1...

**Comment by taurus8** [comment]
Yes Sir
![3](https://cloud.githubusercontent.com/assets/8465075/18671420/4198c36a-7f59-11e6-9f6f-e8c4533ae9eb.png)
Look at my IOSv L2 its shows Ge but gui shows eth

**Comment by noplay** [comment]
Fixed but only for new nodes

**Comment by Bau250** [comment]
How do I fix this?  I am having the same issue.
