### ISSUE TITLE
Slow projects dialog

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1525]
The project dialog is very slow when having many projects and going to the "Projects library" tab.

**Comment by noplay** [comment]
What do you mean by slow? Slow to display or unresponsive? How many projects?

**Comment by grossmj** [comment]
I mean cannot quickly navigate between the tabs, the "Projects library" tab was unresponsive for a few seconds with around 30 close projects in the list.

**Comment by noplay** [comment]
:(

**Comment by noplay** [comment]
I will see how to optimize

It's fast on my computer even with 100 projects. Around 1000 it's start to slow the first tab switch.

Script for creating mass dumb projects
```python
import json
import urllib.request

for i in range(0, 10000):
    print(i)
    params = json.dumps({"name": "test{}".format(i)}).encode('utf8')
    req = urllib.request.Request("http://localhost:3080/v2/projects", data=params, headers={'content-type': 'application/json'})
    response = urllib.request.urlopen(req)

**Comment by noplay** [comment]
I guess recent Qt version optimize that even with 10000 element it's fast. I have push an optimize version. Let me know if it's better for you.
