### ISSUE TITLE
Auto Idle-PC broken in Wizard

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1526]
Auto Idle-PC feature is broken when used from the IOS router wizard.

**Comment by noplay** [comment]
I just test with multiple images and work for me when I follow the wizard to create a new dynamips device.

I see a node appear in my project and disapear after the idlepc is computed.

**Comment by grossmj** [comment]
Correct, it works. It was taking too long for me because the image was still compressed however I got this traceback right after the auto idle-pc was done:

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/topology_summary_view.py", line 135, in _deletedNodeSlot
    tree = self.treeWidget()
AttributeError: 'NoneType' object has no attribute 'treeWidget'
```

**Comment by noplay** [comment]
I have secured the topolgy summary slots
