### ISSUE TITLE
Change last screen of setup wizard?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1528]
Actually in 2.0 we display a summary at the end of the wizard
![image](https://cloud.githubusercontent.com/assets/345437/18706781/a416c132-7ff3-11e6-89e6-d331cbcc013b.png)

But I think the user don't care about that.  And the last screen should be "what to do next"

First we need to explain that out of the box GNS3 can do nothing. You need to add appliance and the appliance should be downloaded from GNS3 marketplace.

What do you think?

**Comment by grossmj** [comment]
Well, it mostly confirms the settings were applied. I think that we should be careful, it is not the role of the interface to replace a tutorial/documentation. I don't want to end up with an ugly cluttered Ui ;)

**Comment by grossmj** [comment]
Here is an alternative when a user need more information, simply have a help button like in the idle-pc dialog:

![inline_help](https://cloud.githubusercontent.com/assets/4752614/18734482/133c386a-8032-11e6-87a9-4d9ba17fcee6.png)

**Comment by noplay** [comment]
Yeah but in this case you can explain something in a tiny dialog.

Our problem is people at the end of the wizard can't use GNS3 because they need to to finish to setup it.  And at this step they have no choice they need to read the documentation.


In all cases I think the summary is useless because if something was wrong you can't go to this screen.

**Comment by grossmj** [comment]
I wouldn't say it is useless, gives you a chance to review/confirm what settings you will use and go back if needed.

We can't possibly have the interface to replace a proper documentation. Maybe we should bring back that page where you could choose to add nodes?

**Comment by noplay** [comment]
We can open the new appliance dialog at the end.

**Comment by grossmj** [comment]
Ok, let's do this.
