### ISSUE TITLE
Make first screen of the setup wizard more welcome

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1529]
Actually as a user your first contact with GNS3 is horrible. You are lost in an ugly screen asking you for two options:
![image](https://cloud.githubusercontent.com/assets/345437/18707368/005eb1fa-7ff6-11e6-81d0-08042b3daef1.png)

**Comment by noplay** [comment]
Suggestion replace it by the following (default options is bold)

Welcome to GNS3

What do you want to do:

On mac and windows
* **Run modern IOS (IOSv or IOU), ASA and appliance from non Cisco manufacturers. This will require an additional VM.**
* Run legacy IOS on my computer (for images <= C7200)

On linux:
* **Run the topologies on my computer**
* Run the topologies in an isolated and standard VM


Also add a GNS3 logo at the left of screen to fill the blank space

**Comment by ehlers** [comment]
Like that, just one comment:

Would add an "only" to the legacy IOS option, otherwise the user might choose that option also, when he wants to run other VMs but also the legacy ones.

> - Run legacy IOS on my computer (for images <= C7200)

- Run **only** legacy IOS on my computer (for images <= C7200)

**Comment by grossmj** [comment]
Looks good :+1:
