### ISSUE TITLE
builtin switch , cannot change port type for existed port.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1536]
the builtin switch has 8 access ports by default , when select one of them then change the type to dot1q and apply , nothing changed.
so when I want a trunk port, I must add a new port with dot1q.

**Comment by noplay** [comment]
With which GNS3 version?

**Comment by superwolfboy** [comment]
Lubuntu 16.04
GNS3 1.5.2

**Comment by ehlers** [comment]
Step 4 is wrong. "Apply" applies the port configuration shown in the right part. After step 3 you have to use "Add" to set the port configuration. Then in step 5 you have to "Apply" or use "OK" to apply and close.

The "Add" button is misleading, it's more an "Update".

**Comment by superwolfboy** [comment]
got, it is working ... thank you very much!
