### ISSUE TITLE
Why someone will need local server screen in setup wizard?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1537]
I don't find situation where someone need to change this settings at first launch:
![capture d ecran 2016-09-22 a 17 58 38](https://cloud.githubusercontent.com/assets/345437/18755975/653368ca-80ee-11e6-9091-b6561dbaaf1b.png)

If you really want to change it, you can do it from preferences.

**Comment by grossmj** [comment]
This allow users to confirm the path to the server is correctly set and give them a chance to adjust the most important settings for the local server. Also, for consistency since you can configure the GNS3 VM in the setup wizard, then why not the local server?
