### ISSUE TITLE
Retry before display  Cannot connect to http://127.0.0.1:3080. Please check if GNS3 is allowed in your antivirus and firewall.

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1542]
Sometimes the error is display but the client will connect one or two second later

**Comment by racheliscoding** [comment]
How did you fix this?

**Comment by eantowne** [comment]
@racheliscoding,

More information is needed to even begin to address this.

I would recommend opening a "Question" on the [GNS3 Community](https://www.gns3.com/community/support). This will get you fairly immediate support, and if the community cannot help, then opening a new issue with all of the relevant information would be better than responding to a 6 year old issue on GitHub.

Ideally, please provide:
GNS3 server and client version
Host Operating System and Version
Are you using the GNS3 VM?
  If so, please provide hypervisor and version being used
