### ISSUE TITLE
Cannot open created project by using Recents projects... button in GNS3 2.0 alpha1

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#1544]
Steps to reproduce:
1. Open GNS3 GUI.
2. Create new project ( no need to add devices to the topology)
3. Close the project
4. Re-open the GNS3 GUI
5. In the New Project dialog try to open the project by clicking on Recent Projects... button.
6. An popup error appears similar to the one below:

![error](https://cloud.githubusercontent.com/assets/7124193/18961007/410b964e-8674-11e6-9726-80ea1dc0f0df.png)

Tried this several times.
The project can be opened by using the Open project option from the File menu

**Comment by noplay** [comment]
I don't reproduce the issue :(  I suspect something else prevent the project list to be populate. Can you go to Help => Export debug informations and send me the file to julien@gns3.net

If you want extra security (the file will contain your ip and the process list) you can use GPG with my key https://keybase.io/jduponchelle

Thanks for the help

**Comment by cioby23** [comment]
I have started the GUI using new configuration files and now it works fine. I think the configuration files I had where from previous version 1.5.x and when I upgraded to 2.0 it used those configs which caused this.
Thanks.

**Comment by cioby23** [comment]
I have experience this error again and I found the cause. I have some projects in subfolders inside the /home/<username>/GNS3/projects folder. If I move the project one level up inside the project folder I can open it from the recent projects list. This affects also the Projects library page.
If a project is in a subfolder inside projects folder it does not get listed in the Projects library page. As soon as I move the project inside the projects folder it appears in the list.
It seems GNS3 does not scan recursive folders inside the Projects folders.

**Comment by noplay** [comment]
I will check why recent not working.

The library doesn't scan recursive. We take just the top level folder otherwise scan could and heavy risk to fail because some people choose C:\ as the root or their Project folder or put project on a network share.

The library is mainly designed for remote server where you have zero access to the file system. And in this scenario you have no way for organizing differently the projects.

It's not easy because we need to accommodate both scenario.

**Comment by cioby23** [comment]
I mainly used subfolders inside project folder to group projects in categories like labs for CCNA CCNP CCIE etc.
