### ISSUE TITLE
delete a link between some device and builtin switch fault

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#1546]
OS: lubuntu 16.04
GNS3:1.5.2
when delete the connection between the builtin switch and a stopped qemu device(others working)
 , the "waiting for ....."will keep going and going , until the console said  "operation cancled.....", at this moment, close all the topo ,and delete some link also need wait, and cannot successful.
at this moment we need close all the topo and gns3, and restart the gns3server with "systemctl restart gns3server". and open gns3 and topo again.
the file of my uploading is the topo file.
![image](https://cloud.githubusercontent.com/assets/9411604/19014189/c6ef1394-8818-11e6-85a9-fcd26e99669c.png)
![image](https://cloud.githubusercontent.com/assets/9411604/19014199/f7aa35e0-8818-11e6-8b1a-e695c734a205.png)
[crashtest.zip](https://github.com/GNS3/gns3-gui/files/504356/crashtest.zip

**Comment by noplay** [comment]
I'm not able to reproduce the issue

**Comment by superwolfboy** [comment]
please: 1,try connect the builtin switch with different kinds of device (for example qemu , and iou), and the one topo also with many kinds of device,
2,try only stop the devices around the connection you want delete ,keep others running,

**Comment by noplay** [comment]
Nothing. You replicate it each time?

**Comment by superwolfboy** [comment]
not every time , but not rare, once happed, must restart gns3server at lease,
btw, the gns3server is always running backaroud by systemctl.
just now I try it again ,but not happen , yesterday , I tryed twice, but all happen .

**Comment by noplay** [comment]
I'm interrested to know if the bug can be reproduce when the server is not
launched via systemd

**Comment by noplay** [comment]
It seem @superwolfboy reproduce that only when gns3 is launched via systemd

**Comment by supertylerc** [comment]
I actually have this issue very regularly on a (somewhat) large topology in GNS3 2.0.0b1.  I can't confirm in 2.0.0b2 because it's having trouble opening the topology (still looking into that).

My issue is not related to `systemd`.  I only install GNS3 via `pip` and start it with the `gns3server` executable.

**Comment by supertylerc** [comment]
I think that this is a problem in `gns3-server`, not `gns3-gui`.  Even sometimes while attempting to load a project, I get slapped with a timeout related to the built-in Ethernet switch:

```
{
    "message": "Timeout error when connecting to http://127.0.0.1:3080/v2/compute/projects/cb75d223-650b-4f82-933b-ac5c96a54177/ethernet_switch/nodes/f18c747d-f100-4bd0-8e20-0ed3f537f7a9/adapters/0/ports/1/nio",
    "status": 409
}
```

That's running a `curl` to start the project from the same machine as the `gns3-server`, so there's no reason/opportunity for `gns3-gui` to come into play.
