### ISSUE TITLE
Error when deleting link between cloud and switch

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1547]
When try to delete link between builtin switch and builtin cloud errors out.  Link is not deleted.
![deletelink](https://cloud.githubusercontent.com/assets/10285348/19018269/d8b9b952-8828-11e6-8490-97007c979186.png)

**Comment by jtorri** [comment]
Once I create a project cannot figure out how to save.  In previous versions there was a Save option.  Now all I see is Save Project As which tries to do an overwrite fails with an error.  Clearly I'm not the sharpest tack.  Appreciate help.  Thanks!

**Comment by AJNOURI** [comment]
> Save as you go
> 
> Your projects are automatically saved as you make changes to them, there is no need to press any save button anymore. An additional benefit is this will avoid synchronisation issues between the emulators’ virtual disks and projects.
> 

https://github.com/GNS3/gns3-server/issues/702

**Comment by jtorri** [comment]
When GNS3 2.0.0 alpha 1 starts it appears it does not check INI files and thereby recognize initial configuration has been done.  It displays the initial dialogs that seem more appropriate before initial configuration.  Am I wrong?

**Comment by AJNOURI** [comment]
At the bottom of the initial dialog window, you can check "Don't show next time..." something like that.

**Comment by jtorri** [comment]
GNS3 1.5.1 gns3_server.ini
[Server]
host = 192.168.41.1
port = 3080

GNS3 2.0.0 alpha 1  gns3_server.ini
[Server]
host = 127.0.0.1
port = 3080

Using the GNS3 VM to run all IOUs.  Should not it's host value be the IP of the GNS3 VM?
If so, do not see way to make it happen.

**Comment by noplay** [comment]
No it 's the ip of the local server. Will check for your delete link issue.

What is the interface in the cloud where you connect the switch?

Thanks for the help

**Comment by noplay** [comment]
```
Error while deleting link: Cannot send command 'bridge delete 80d0290a-bf86-443a-af86-b78c4934739f-0': uBridge is not running

**Comment by noplay** [comment]
It's due to a ubridge segfault:
https://github.com/GNS3/ubridge/issues/20

**Comment by noplay** [comment]
After test it's not ubridge (problem on the test machine) and I can't reproduce the issue.

Can you easily reproduce the issue?

**Comment by jtorri** [comment]
The delete link error no longer occurs.   No idea what changed.  Other than the following.
Now:
GNS3 2.0.0 alpha 1 gns3_server.ini
[Server]
host = 192.168.41.1
port = 3080
GNS3 VM IP 192.168.41.129

**Comment by noplay** [comment]
Ok thanks let me know if you reproduce the issue.

**Comment by kefins** [comment]
@julien-duponchelle
