### ISSUE TITLE
GNS3 1.5.2, VM Ware Workstation OVA - Bad Download?

### ISSUE THREAD

**Issue by flyinRyan424** [GNS3/gns3-gui#1548]
Every download of the Zip file containing the OVA for GN3 1.5.2 seems like there is an error. I've tried to download it multiple times. From my VPN, direct through home connection, but everytime I have this error when unzipping with 7zip:

"1    Data Error : GNS3 VM.ova"
![image](https://cloud.githubusercontent.com/assets/22579144/19023026/4ffcc8ea-8899-11e6-903b-9d1537297460.png)

And when i try to import it in Workstation I get this error:

"The import failed because C:\Users\<XXXXX>\Downloads\GNS3 VM.ova did not pass OVF specification conformance or virtual hardware compliance checks."

![image](https://cloud.githubusercontent.com/assets/22579144/19023054/c3b94fec-8899-11e6-9226-6a2978c65b0f.png)

Hope I am attaching these screen captures correctly. Any advice. Do I need to run something as an administrator.

Thanks - flyinRyan424

**Comment by noplay** [comment]
Can you compute a md5 checksum of the downloaded file ?

Thanks

**Comment by flyinRyan424** [comment]
eb 0a 1e 70 73 f5 51 4a 42 88 0e 30 04 b8 92 42 40 41 79 4a

**Comment by noplay** [comment]
Hmm I don't get the same sums. Where are you located? 

GNS3.VM.VMware.Workstation.1.5.2.zip
md5: 024e1584cd48a844f7d4ae54e9ffc9de
sha1: 1f1641616b5b076b50efd4248980e9003f24411b

GNS3 VM.ova
md5: 4d71ccc113290ab523b5d7b0759fce58
sha1: 69eca7aecab4b0b94602829fe1fef09deee7d891

**Comment by noplay** [comment]
I pushed in the release a checksum file:
https://github.com/GNS3/gns3-gui/releases/download/v1.5.2/checksums.txt

**Comment by flyinRyan424** [comment]
I am Northern CA, in the Bay Area. Turns out there was an issue downloading the file from GitHub via my work PC. Downloaded the zip on my personal machine and migrated it to my work PC. I was able to unzip and import to Workstation with no errors. Thanks. Issue closed

flyinRyan

**Comment by noplay** [comment]
Thanks for the report. 

It's strange we got many report of download issues in the past days.
