### ISSUE TITLE
[IOU] - when reloading an iou device, the telnet connection is killed

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-gui#155]
As per title, when reloading an iou device (from CLI using "reload" ) the telnet session is killed.

This shouldn't happen (and doesn't happen with "regular" iou)

**Comment by grossmj** [comment]
You meant regular IOS I suppose?

**Comment by grossmj** [comment]
Ok, I confirm if you do a reload in IOU then the telnet session is killed. IOU do a unix_reload() which is basically restarting the same process I guess. I don't know if we can prevent that though.

@noplay It seems that after a do a reload in IOU and then try to stop the same IOU VM from the GUI I get the following error:

```
2015-02-24 16:26:22 ERROR base_events.py:698 Exception in callback <bound method SubprocessStreamProtocol.process_exited of <asyncio.subprocess.SubprocessStreamProtocol object at 0x7f0dcc659470>>()
handle: Handle(<bound method SubprocessStreamProtocol.process_exited of <asyncio.subprocess.SubprocessStreamProtocol object at 0x7f0dcc659470>>, ())
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/subprocess.py", line 80, in process_exited
    waiter.set_result(returncode)
  File "/usr/lib/python3.4/asyncio/futures.py", line 298, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
asyncio.futures.InvalidStateError: CANCELLED: Future<CANCELLED>
```

**Comment by noplay** [comment]
We need to check if the pid change

**Comment by noplay** [comment]
Ok after almost two hours of debug i have found the bug, it's on server side in ioucon i have a working patch on my computer but i need to clean it before pushing it.

**Comment by noplay** [comment]
Ok this commit fix partially the issue:
https://github.com/GNS3/gns3-server/commit/5e591459481d1c0f3a42ab9f5902289f3bc220c5

Because you can reload, you see the boot messages but you can't type in the console

**Comment by noplay** [comment]
I found the issue:
https://github.com/GNS3/gns3-server/commit/62afef06af914fe0c0584a0cc5ae8c9633549ea0

Now everything is ok
