### ISSUE TITLE
 When released 1.5.3?

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-gui#1555]
Has been a long time, when released gns3 1.5.3 version

**Comment by noplay** [comment]
Do you need something particular from this version?  1.5.2 seem stable.

Actually we are focused on the alpha cycle of the 2.0 and we have no date for releasing a 1.5.3 but could change if require.

A 1.5.3 will be release before 2.0.0 release it's sure.

**Comment by qianxideyu** [comment]
Thank you very much for your reply, 1.5.2 version of the existence of some bug problems, such as capturing Packet, delete equipment caused by the collapse of cable and so on .2.0 version of the gns3 too many problems! Hope to release a more stable version!

**Comment by noplay** [comment]
Hi,

I don't see any bug reports for the problem you mention.

**Comment by noplay** [comment]
You can see all 1.5.3 issue here:
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.5.3+user%3AGNS3+

**Comment by qianxideyu** [comment]
https://github.com/GNS3/gns3-gui/issues/1546-------delete a link between some device and builtin switch fault
https://github.com/GNS3/gns3-gui/issues/1520-------capture problem

**Comment by noplay** [comment]
Hi,

Thanks for the links.

#1546 seem not easy to reproduce for unknown reason on this user PC with large topologies when run inside a VMware VM sometimes the dynamips switch could hang

#1520 it's only a display issue in very specific conditions and we don't reproduce it. It's doesn't prevent usage of GNS3 or capture. And this part has been rewrite from scratch in 2.0. 

If you have more informations and can reproduce both issue we are interested. But from what we know it's affect only one user in rare case and doesn't block them in their usage.
