### ISSUE TITLE
UDP tunnel debugging

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1562]
The idea is to have all UDP tunnel information included in the Help -> Export debug information

The controller would check all the UDP connections against what is returned by psutil to check that each UDP tunnel indeed exist on each server.

http://pythonhosted.org/psutil/#psutil.net_connections

**Comment by noplay** [comment]
This mean we need to call the controller for the export debug.  Because actually all the debug is exported by the client

**Comment by grossmj** [comment]
Yep, I think having a comprehensive debug information is going to be very useful to get to a final release.

**Comment by noplay** [comment]
I have implemented a /debug in server handler and it's include in the exported zip. Now we will need to implement this method.

**Comment by noplay** [comment]
Oh it's more complex than expected because we need also to retrieve the data from each compute node :(

**Comment by grossmj** [comment]
Yes, the controller has to take care of this ;)

**Comment by noplay** [comment]
Also we need to dump for current project on which host each part of the link is bind

**Comment by noplay** [comment]
@grossmj  do we still need that? It sound complex to implement

**Comment by grossmj** [comment]
It would definitely be a nice to have. This can wait 2.1 if you want.

**Comment by noplay** [comment]
My main concern is I'm not confortable with the idea to have more code and more complex code for checking that UDP tunnel work only for debug, than the actual code for creating UDP tunnel :(

But perhaps I miss an easy way to solve the issue.

**Comment by grossmj** [comment]
The way I see it is to have the extra code but quite separated from the code that creates UDP tunnels. Looping all tunnels and checking that each exists on the system.
