### ISSUE TITLE
[2.0.0dev2] Qemu Image does not upload

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1563]
@noplay 
So I downloaded and installed the newest nightly build for GNS3 2.0.

I was to successfully finally import a QEMU appliance, in this example it was Firefox 31.1.1~2, usually with the previous version of GNS3 when adding the device to the project it will automatically upload the image to the remote server, however, this error show's instead;

http://imgur.com/a/Aj4YJ

**Comment by noplay** [comment]
Where the image is located on your host system? Is it in the qemu images directory?

**Comment by gcasella** [comment]
It's on the host where the gns3-gui is running.

I left the qemu image inside of the Downloads directory since importing an appliance looks in that directory by default.

I didn't upload it to the remote server or move it anywhere. I didn't check if the gns3-gui moved it to the QEMU directory on the client system after importing.

On 6 Oct 2016 3:24 a.m., Julien Duponchelle <notifications@github.com> wrote:

Where the image is located on your host system? Is it in the qemu images directory?

**Comment by noplay** [comment]
At the end of the import of appliance it should ask you if you want to move the file. It's not the case?

**Comment by gcasella** [comment]
That's correct.
It didn't ask me that after import was completed.
[Import Appliance](http://imgur.com/a/vIGEm)
[Select main remote server](http://imgur.com/a/CiNFm)
[vRIN qcow2 file](http://imgur.com/a/RfSOv)
[Ready to Import](http://imgur.com/a/1U2Nm)
[Import vRIN](http://imgur.com/a/Fdeh3)

It tells me it's installed successfully - I go and add it to my topology and this comes up;
http://imgur.com/a/5yUuk

It looks like it moves it to the QEMU directory in the background, but never asks to upload it to the remove server;
http://imgur.com/a/Gmxke

It does ask that question when importing an IOU image via the "New Appliance Template" button;
[IOU](http://imgur.com/a/RvEPD)

**Comment by noplay** [comment]
Ok thanks for usefull details we will check that.

PS: You can directly include the screenshots in Github messages just drag image in the text area

**Comment by noplay** [comment]
You are using a pure remote server right? Nothing on your local machine.

**Comment by gcasella** [comment]
Hey Julien,

That's correct. Pure remote server. Selected the option on the wizard that everything runs on a remote server.

On 19 Oct 2016 3:54 a.m., Julien Duponchelle <notifications@github.com> wrote:

You are using a pure remote server right? Nothing on your local machine.

**Comment by noplay** [comment]
Ok I got the problem. The code was not designed to support a pure remote server. This require a big refactor of this part. We will try to ship it with alpha 2.

**Comment by noplay** [comment]
Will be solved by #1590
