### ISSUE TITLE
[2.0.0dev2] Docker appliance not persistent on restart of GNS3 client.

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1564]
@noplay 
I imported the Docker appliance "webterm" it installs and runs correctly.

however upon restarting the GNS3 client, it does not exist in the device listing anymore;

[Before](http://imgur.com/a/pRv0B)
[After](http://imgur.com/a/Zaiqo)

**Comment by noplay** [comment]
Thanks it's fixed
