### ISSUE TITLE
[2.0.0dev2] : Error with container console type set to http

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#1568]
When inserting an image into the canvas with console type=http, gns3 gui shows this errors, then crashes:

![screenshot from 2016-10-07 07-17-16](https://cloud.githubusercontent.com/assets/1716020/19193286/62909e32-8c5e-11e6-8000-a99f0a21b45f.png)

> 2016-10-07 07:16:32 INFO __init__.py:140 instantiating node <class 'gns3.modules.docker.docker_vm.DockerVM'>
> 2016-10-07 07:16:32 INFO docker_vm.py:41 Docker VM is being created
> 2016-10-07 07:16:32 INFO __init__.py:151 creating node Docker container with id 4
> 2016-10-07 07:16:32 CRITICAL __init__.py:97 Error while setting up node: Invalid JSON: 'http' is not one of ['serial', 'vnc', 'telnet', None] in schema: {"enum": ["serial", "vnc", "telnet", null], "description": "Console type"}
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/home/ajn/gns3-gui/gns3/qt/__init__.py", line 208, in partial
>     return func(*args, **kwargs)
>   File "/home/ajn/gns3-gui/gns3/http_client.py", line 591, in _processResponse
>     raise e
> gns3.http_client.HttpBadRequest: {
>     "message": "Invalid JSON: 'http' is not one of ['serial', 'vnc', 'telnet', None] in schema: {\"enum\": [\"serial\", \"vnc\", \"telnet\", null], \"description\": \"Console type\"}",
>     "method": "POST",
>     "path": "/v2/projects/{project_id}/nodes",
>     "request": {
>         "compute_id": "local",
>         "console_type": "http",
>         "name": "ecc12-zimbra-{0}",
>         "node_id": "5acd433d-2c46-4748-90d8-d34a0e4b9d38",
>         "node_type": "docker",
>         "properties": {
>             "adapters": 1,
>             "console_http_path": "/",
>             "console_http_port": 80,
>             "console_resolution": "1024x768",
>             "image": "ecc12/zimbra"
>         },
>         "symbol": ":/symbols/docker_guest.svg",
>         "x": -9,
>         "y": -147
>     },
>     "status": 400
> }
> 
> 2016-10-07 07:17:23 WARNING crash_report.py:79 A .git directory exist crash report is turn off for developers. Instant exit
> Segmentation fault (core dumped)
>

**Comment by noplay** [comment]
Thanks it's fixed
