### ISSUE TITLE
Duplicated node in node summary when restoring a snapshot

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1571]
![duplicate_topology_summary](https://cloud.githubusercontent.com/assets/4752614/19215847/616b3784-8d66-11e6-8bc7-07ea13752656.png)

**Comment by noplay** [comment]
Do you still reproduce it?

**Comment by grossmj** [comment]
Yes, open a project, create a snapshot then restore from it... try multiple time because this doesn't happen every time.

**Comment by noplay** [comment]
I didn't manage to reproduce it but I just add a protection in the code.

**Comment by grossmj** [comment]
Still get the issue with just one VPCS node and restoring a snapshot.

**Comment by noplay** [comment]
Still don't replicate it :( I change the way we avoid duplicate but not sure if it's ok

**Comment by noplay** [comment]
Still don't reproduce even on my ubuntu box :(

When you doubleclick on both item it's center you on the same node?

**Comment by noplay** [comment]
I pushed a different implementation
