### ISSUE TITLE
[2.0.0dev2] Remote Server wrong Console IP.

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1574]
Hey Again,

Don't know how else I should've titled this but what I noticed was when running the TightVNC packaged with GNS3 I start a QEMU node located on a remote server when I try to console in I get the following error;

[QEMU VNC](http://imgur.com/a/34u3G)
[Telnet vRIN](http://imgur.com/a/LxXt2)

**Comment by gcasella** [comment]
Dug a bit deeper, it looks like the code in compute_manager.py only has the option for two types of computes, VM or LOCAL. 

When it uses local it seems to carry over to the GNS3-GUI with the 127.0.0.1 address instead of the actual IP address of the main remote server address. 

![image](https://cloud.githubusercontent.com/assets/7719536/19405821/0819164a-924a-11e6-9c01-9f774938202e.png)

**Comment by gcasella** [comment]
Correction...
I fixed this myself.

This is how i did it;

1) Modify the gns3_server.conf file on your remote server and **make sure** the _host=_ variable is set properly. (added _host = dns_hostname/ip_)

2) Restart your remote gns3 service.

![image](https://cloud.githubusercontent.com/assets/7719536/19405906/3c544d84-924b-11e6-9ed7-3d04b5798adb.png)

![image](https://cloud.githubusercontent.com/assets/7719536/19405918/5f8b1f94-924b-11e6-9e4d-e55a95b2219c.png)

**Comment by noplay** [comment]
Thanks for the informations it will help to fix the issue.

**Comment by noplay** [comment]
Ok I got the issue. By default the server start on 0.0.0.0 and the code will replace it by 0.0.0.0 as console host.

**Comment by noplay** [comment]
Fixed will be include in alpha2

**Comment by gcasella** [comment]
Cool!

Sounds good @noplay , I just saw the update to the code. I'll test it out after the nightly build!

**Comment by gcasella** [comment]
Fyi @noplay latest nightly build of dev3 (i'd assume is Alpha 2) did not have the fix.

When the server starts it will start as 0.0.0.0:3080 but the controller will listen to 127.0.0.1

**Comment by noplay** [comment]
This it should be good
