### ISSUE TITLE
[2.0.0dev2] : BUG : Configure VirtualBox VM

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1575]
Hi

With an empty config of GNS3 2.0

When i want configure the VirtualBox : I have this error message : "VBoxManage vboxmanage is not accessible"

**Comment by noplay** [comment]
Where is located your vboxmanage and what is the content of your $PATH variable?

Thanks

**Comment by Raizo62** [comment]
Now, i don't use GNS3 2.0, then i must recompile to answer you.

Are helped you if i say : 

- i don't have this error with GNS3 1.5
- i am on Linux ?
- i can start vboxmanage in console

If not, i recompile tonight

**Comment by Raizo62** [comment]
user@raizo:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

user@raizo:~$ whereis vboxmanage 
vboxmanage: /usr/bin/vboxmanage

**Comment by noplay** [comment]
What is the result of:
* ls -l /usr/bin/vboxmanage?
* python3 -v

I try to figure how it could fail.

The error is raised here:
https://github.com/GNS3/gns3-server/blob/2.0/gns3server/compute/virtualbox/__init__.py#L77


Especially this part of the code:
```python
if not os.path.abspath(vboxmanage_path):
    vboxmanage_path = shutil.which(vboxmanage_path)

if not vboxmanage_path:
    raise VirtualBoxError("Could not find VBoxManage")
if not os.path.isfile(vboxmanage_path):
    raise VirtualBoxError("VBoxManage {} is not accessible".format(vboxmanage_path))
```

I don't see how shutil.which can return a non absolute path.
https://docs.python.org/3.5/library/shutil.html#shutil.which

**Comment by Raizo62** [comment]
> ls -l /usr/bin/vboxmanage
lrwxrwxrwx 1 root root 4 sept. 12 17:57 /usr/bin/vboxmanage -> VBox
It is a symbolic link to the binaire VBox

> python3 --version
Python 3.4.2

This bug is also in GNS3 1.5dev.
If I use GNS3 with last config, i can add VM and start them.
But, if i start with an empty config, i have also this error message

**Comment by noplay** [comment]
I think the issue is because it's a symlink we wrongly detect it as invalid

**Comment by Raizo62** [comment]
> I think the issue is because it's a symlink we wrongly detect it as invalid
I thought too but when i changed in the code "vboxmanage" by "VBox", it doesn't work also

**Comment by noplay** [comment]
Not related to this error. But it seem strange for me that vboxmanage is named vbox on your system. How VirtualBox is installed on your system?

**Comment by Raizo62** [comment]
I use amd64 package for Jessie from VirtualBox site : https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by noplay** [comment]
It seem this package install /usr/bin/VBoxManage  you don't have it on your
system?

**Comment by Raizo62** [comment]
Sorry, i don't understand why you say that.
I use this package to have the last version of VirtualBox. But, my install script doesn't modify the install (if you want, i can verify tonight)

**Comment by noplay** [comment]
The package mention a /usr/bin/VBoxManage it should be available on your system. Because VBox is not the same binary.

**Comment by Raizo62** [comment]
All files beginning with /usr/bin/vbox are symlink to VBox, except vbox-img

**Comment by Raizo62** [comment]
All files beginning with /usr/bin/VBox are symlink to VBox, except VBox, VBoxDTrace, VBoxTunctl

**Comment by noplay** [comment]
I just tested on a fresh ubuntu and virtualbox and fixed an issue could you test with last server code?

**Comment by Raizo62** [comment]
I have tested. This works. Thanks :-)

**Comment by noplay** [comment]
Thanks a lot for your time
