### ISSUE TITLE
GNS3 conversion issue from 0.8.X format

### ISSUE THREAD

**Issue by imyelmo** [GNS3/gns3-gui#1578]
I'm having problems converting a topology from 0.8.X version. The related topology is this one:

[topology.net.zip](https://github.com/GNS3/gns3-gui/files/529413/topology.net.zip)

I have the following console output:

GNS3 management console.
Running GNS3 version 1.5.2 on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Topology corrupted port FastEthernet0/0 already exists for GALP01
Topology corrupted port FastEthernet0/1 already exists for GALP01
Topology corrupted port FastEthernet0/0 already exists for IPv4ISP
Topology corrupted port FastEthernet0/1 already exists for IPv4ISP
Topology corrupted port FastEthernet0/0 already exists for ANDP01
Topology corrupted port FastEthernet0/1 already exists for ANDP01
Topology corrupted port FastEthernet0/0 already exists for IPv6ISP
Topology corrupted port FastEthernet0/1 already exists for IPv6ISP
Topology corrupted port FastEthernet0/0 already exists for MADRR01
Topology corrupted port FastEthernet0/1 already exists for MADRR01
Corrupted topology Link from ANDP01 port FastEthernet1/0 to MADRR01 port FastEthernet1/1 destination port 76 doesn't exist
Topology corrupted port FastEthernet0/0 already exists for MADRR02
Topology corrupted port FastEthernet0/1 already exists for MADRR02
Corrupted topology Link from ANDP01 port FastEthernet1/1 to MADRR02 port FastEthernet1/1 source port doesn't exist
Corrupted topology Link from ANDP01 port FastEthernet1/1 to MADRR02 port FastEthernet1/1 destination port 94 doesn't exist
Corrupted topology Link from GALP01 port FastEthernet1/1 to MADRR02 port FastEthernet1/0 source port doesn't exist
Corrupted topology Link from IPv6ISP port FastEthernet1/1 to MADRR02 port FastEthernet1/15 source port doesn't exist
Topology corrupted port FastEthernet0/0 already exists for SEVPE01
Topology corrupted port FastEthernet0/1 already exists for SEVPE01
Topology corrupted port FastEthernet0/0 already exists for VIGPE01
Topology corrupted port FastEthernet0/1 already exists for VIGPE01
Topology corrupted port FastEthernet0/0 already exists for SEVILLA
Topology corrupted port FastEthernet0/1 already exists for SEVILLA
Topology corrupted port FastEthernet0/0 already exists for VIGO
Topology corrupted port FastEthernet0/1 already exists for VIGO
Duplicate port name FastEthernet0/1 in GALP01.
Duplicate port name FastEthernet0/1 in ANDP01.
Duplicate port name FastEthernet0/1 in IPv4ISP.
Duplicate port name FastEthernet0/1 in IPv6ISP.
Duplicate port name FastEthernet0/1 in MADRR01.
Duplicate port name FastEthernet0/1 in MADRR02.
Duplicate port name FastEthernet0/1 in SEVPE01.
Duplicate port name FastEthernet0/1 in VIGPE01.
Duplicate port name FastEthernet0/1 in SEVILLA.
Duplicate port name FastEthernet0/1 in VIGO.

The original topology is as follows:
![0 8 x topology](https://cloud.githubusercontent.com/assets/11572612/19386786/7e7c9d0e-9216-11e6-9f2c-e1b6b42ba3d1.png)

The resulting topology after conversión with GNS3 1.5.2 is as follows:
![1 5 2 topology](https://cloud.githubusercontent.com/assets/11572612/19386802/8f40ce3a-9216-11e6-92a3-264a4b79aab3.png)

**Comment by noplay** [comment]
This OSX build should work:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-21/2.0/GNS3%20nightly-2.0.0dev3.dmg/download

**Comment by noplay** [comment]
Thanks for the report

**Comment by imyelmo** [comment]
I will check it in a free time slot.

**Comment by imyelmo** [comment]
It has been faster than I expected. Currently is working properly in last nightly 1.5.3dev but it is not working on last nightly 2.0.0. Furthermore, last one is currently a bit buggy as expected. Let me know if you need any further check. I will try to check it on stable releases.

**Comment by noplay** [comment]
Starting with version 2.0, the conversion from .net (project files made before version 1.0) will no longer been included in GNS3 builds. Conversion will still be possible using a separate program. This converter was a community effort but the author of this code stopped any development of it. Port this to 2.0 without regression is an effort too big for the team and we don't have enough tester to warranty this working.

We recommend to open all 0.8 projects with 1.X version in order to convert them before switching to 2.0.

We will make a clear error message:
https://github.com/GNS3/gns3-gui/issues/1639
