### ISSUE TITLE
GNS3 VM start with GNS3 2.0.0 alpha 1 is erratic

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1589]
Windows 10 prof 64 bit.  VMWARE workstation 12.5.
GNS3 2.0.0 alpha 1 and its associated GNS3 VM.ova.  
Running all objects (IOU, IOS, ASAv, etc.) from GNS3 VM.  GNS3 2.0.0 alpha 1 starts consistently but the associated GNS3 VM does not start consistently.  Cannot determine what is different between the times the GNS3 VM starts and does not start.  When the GNS3 VM does start all network objects (IOU, IOS, etc.) run just fine.
Anyone else experiencing this issue?

**Comment by noplay** [comment]
When you say the VM doesn't start  you don't see VMware open the VM?

**Comment by noplay** [comment]
Hi for all user with this error,

Can you test if you have still the error with:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-19/2.0/GNS3-2.0.2016-10-19-all-in-one.exe/download

If you have the error can you go to Help / Export Debug informations and send me the zip to julien@gns3.net (you can gpg it because it contains private info like process list and opened ports https://keybase.io/jduponchelle)

**Comment by jtorri** [comment]
"When you say the VM doesn't start you don't see VMware open the VM?"
Yes, that is correct.  Will test with new build as you suggest as soon as possible.  
Thanks!

**Comment by codeassassin** [comment]
Downloaded new build. VMware still doesn't open the VM. However, export logs does work. I emailed them to you. Thanks!

**Comment by jtorri** [comment]
Just installed GNS3 2.0.0 alpha 2 and the GNS3.ova that comes with the full install.  Still unstable.  
I running all network devices (IOU, IOS, ASAv, etc) from GNS3 VM (GNS3  VM 2.0.0 alpha 2).  The IP of GNS3 VM eth0 is 192.168.41.128/24 (vmnet1, host only.
Would you please answer this question? What value should be in Server Preferences, Main Server, Host binding in the attached image?
![untitled](https://cloud.githubusercontent.com/assets/10285348/19616127/70669102-97d9-11e6-9ffe-ee3fff9dd549.png)
And, here is the info for my GNS3 VM.
![untitled2](https://cloud.githubusercontent.com/assets/10285348/19616132/87be8ecc-97d9-11e6-90f8-81896f537ffa.png)

Thanks!

**Comment by jtorri** [comment]
One more, please.  What value should be here for remote servers, if anything
![untitled3](https://cloud.githubusercontent.com/assets/10285348/19616259/340e403a-97dc-11e6-897f-e150553df7b3.png)
?

**Comment by jtorri** [comment]
Windows 10 Prof 64 bit with latest updates.  Now running GNS3 2.0.0 alpha 2 with GNS3 VM.ova from GNS3 2.0.0 alpha 2 version.  
The GNS3 VM now starts just after the GNS3 application starts.  Based on 10 consecutive starts.  Thanks!

**Comment by codeassassin** [comment]
@noplay I've reinstalled from scratch with clear .ini . One thing I found was, for me, the default network interface configuration settings are:

Adapter0: Host-only
Adapter1: NAT

![image](https://cloud.githubusercontent.com/assets/6335629/19678757/15e214b8-9a6d-11e6-8f11-30bd76e93206.png)

However, until I manually reversed these settings, GNS3 GUI was unable to communicate with GNS3 VM. I'm using the latest VMWare Workstation, 12.5 and firewall disabled. 

![image](https://cloud.githubusercontent.com/assets/6335629/19678802/4b334ee8-9a6d-11e6-8b27-e6230c2e5d0b.png)

**Comment by noplay** [comment]
What is your VMnet 2 ? It should be host only as adapter 0 and NAT as adapter 1

**Comment by codeassassin** [comment]
My VMnet 2 is directly connected to outside Cisco L3 switch, should function the same as NAT. With host only as adapter 0 and NAT as adapter 1, GNS3 gui was unable to communicate with GNS3 VM. When I reversed the host-only to adapter 1, and set the outside interface to adapter 0, all functionality resumed.

**Comment by codeassassin** [comment]
This probably isn't the correct place for this, however, the connectivity isn't as functional as I originally thought. While attempting to upload an image to the VM, I get the following error:

![image](https://cloud.githubusercontent.com/assets/6335629/19680301/2678b6f0-9a73-11e6-9a8b-e707806eb1f2.png)

```GNS3 management console.
Running GNS3 version 2.0.0a2 on Windows (64-bit) with Python 3.5.1 Qt 5.7.0 and PyQt 5.7.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Project untitled already exists, overwrite it?
****** Exception detected, traceback information saved in C:\Users\Ariel\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 81, in <lambda>
  File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 101, in _imageBrowserSlot
  File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_configuration_page.py", line 154, in getDiskImage
  File "./gns3-gui\gns3\image_manager.py", line 50, in askCopyUploadImage
  File "./gns3-gui\gns3\image_manager.py", line 100, in _uploadImageToRemoteServer
AttributeError: 'str' object has no attribute 'id'```

**Comment by codeassassin** [comment]
@noplay I downgraded to 1.5.2, and the error I was receiving while attempting to upload the image did not reoccur, so this issue might not be a connectivity issue but a separate bug. I'll start a separate but thread. 

![image](https://cloud.githubusercontent.com/assets/6335629/19686202/2a499734-9a8e-11e6-80cb-c18d890be7d8.png)

**Comment by noplay** [comment]
@codeassassin  Ok I have a new build (same as the other post).
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-25/2.0/GNS3-2.0.2016-10-25-all-in-one.exe/download

If you can  import a fresh GNS3 VM (you don't need to erase the current, just reimport and select it), go to help export debug information and send me the zip to julien@gns3.net

It will not work better but now I extract some VMware informations. I want to check if importation work correctly in VMware. Because It seem it's broke the order of interface exposed to the VM (the VM see eth0 as eth1).

Thanks a lot for the help

**Comment by codeassassin** [comment]
No problem. Email sent. Let me know if there's anything else you need.

**Comment by noplay** [comment]
Seem related:
https://github.com/vmware/open-vm-tools/issues/93

**Comment by noplay** [comment]
OK from the vmware github it seem that vmrun getGuestIPAddress will return a random IP of the machine not necessary the first one.

This mean we need to found a different way.  This patch https://github.com/GNS3/gns3-server/commit/9e861a734095b5ba1aafa468890ab335e24d5e77 implement a different method. We use a VMware system for exchanging variable between VM and host PC and in this variable we put the VM ip.

**Comment by noplay** [comment]
I will prepare a build with that fix

**Comment by noplay** [comment]
Ok you can try this build:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-25/2.0/GNS3-2.0.2016-10-25-all-in-one.exe/download

After go to your GNS3 VM and upgrade you should get the dev version
![image](https://cloud.githubusercontent.com/assets/345437/19696089/1218ed56-9ae6-11e6-93b5-864c9921ae16.png)

**Comment by codeassassin** [comment]
I haven't tried alpha 2, I'll try it and post my result

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Oct 21, 2016 at 10:59 PM -0400, "jtorri" <notifications@github.com<mailto:notifications@github.com>> wrote:


Windows 10 Prof 64 bit with latest updates. Now running GNS3 2.0.0 alpha 2 with GNS3 VM.ova from GNS3 2.0.0 alpha 2 version.

The GNS3 VM now starts just after the GNS3 application starts. Based on 10 consecutive starts. Thanks!

-

**Comment by noplay** [comment]
Hi,

The error about the upload is already fixed:
https://github.com/GNS3/gns3-gui/issues/1594

I will post a build in few minutes here.

**Comment by jtorri** [comment]
Tried https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-25/2.0/GNS3-2.0.2016-10-25-all-in-one.exe/download.  Tried adding IOU and got the following.

![untitled](https://cloud.githubusercontent.com/assets/10285348/19711752/f75d82a4-9b05-11e6-911a-55b8a6b90e46.png)

**Comment by jtorri** [comment]
Strongly suspect I am not being helpful but the fact is that if I ignore the above error message and keeping going things seem to work!

**Comment by noplay** [comment]
So we can consider the VM start is done.

I have open a new issue for the timeout error:
https://github.com/GNS3/gns3-gui/issues/1617

**Comment by noplay** [comment]
Thanks to everyone for the help
