### ISSUE TITLE
Drop ova support in appliance import?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1591]
The .ova support in .gns3a is complex because it's require extra operation like untar the ova to extract the .vmdk. And after it's introduce corner case because image name will be:
_pc.ova/pc-disk1.vmdk_ this mean we need to manage an image in a specific directory.

After checking only one appliance use it for old releases:
https://github.com/GNS3/gns3-registry/blob/master/appliances/juniper-vsrx.gns3a#L84

If we really need to support an appliance provided as an ova a documentation about the appliance could explain to the user that we just 7-zip he can extract the vmdk from the .ova

**Comment by noplay** [comment]
We could even ship one day a simple application that convert an .ova to qcow2 (by embedding qemu-img).

**Comment by ehlers** [comment]
In juniper-vsrx.gns3a the ova images are only used for the no longer downloadable version 12.x, so maybe they can be removed from that appliance.

Furthermore ova work only as linked base VM, see https://github.com/GNS3/gns3-gui/issues/1112

So, yes, I'm for removing support of ova. An ova convert tool, maybe combined with a tool that also gets the meta informations (see https://github.com/GNS3/gns3-gui/issues/1113), may be more helpful.

**Comment by grossmj** [comment]
Well, yes we can drop it if this is barely used and complex.
