### ISSUE TITLE
[2.0a1] Re-arranged topology goes back on node startup

### ISSUE THREAD

**Issue by EB-athila** [GNS3/gns3-gui#1598]
Nodes re-located on the topology view get to their original positions as they start up.

**Comment by noplay** [comment]
Did you try with 2.0.0a2 ? 


Thanks

**Comment by cioby23** [comment]
I can confirm this happens with the latest development code also. The issue appears only when using snap to grid feature. If snap to grid is not enabled you can change the positions of the nodes it will be saved if you reopen the topology.

**Comment by noplay** [comment]
Thanks @cioby23 it's really help me I think it's now fixed.
