### ISSUE TITLE
GNS3 Large Icons and buttons (ubuntu 16.10) 

### ISSUE THREAD

**Issue by 56kb** [GNS3/gns3-gui#1600]
Installed GNS3 using `sudo add-apt-repository ppa:gns3/ppa`

after launching GNS3 it seems like its getting the wrong DPI settings and has large buttons and icons.

![screenshot from 2016-10-23 21-18-57](https://cloud.githubusercontent.com/assets/20359970/19631247/e9974712-9967-11e6-99a6-a95af3b346d7.png)

I have a photo attached with firefox for reference.

**Comment by noplay** [comment]
It seem to be a Qt bug on some computers but we expected that it will be fixed in the 16.10 :(

If a in terminal you run
```
export QT_AUTO_SCREEN_SCALE_FACTOR=0
gns3
```

It should work

Arch has more info about this:
https://wiki.archlinux.org/index.php/HiDPI

**Comment by TomsonZ** [comment]
Hi I have the same issue with my GNS3 on my Ubuntu 16.04 LTS 64xbit on my DELL XPS LX322 with I7 and 1920x1080 resolution.
I also tried the command you recommonded but without any improve.
Can you tell how work on this stuff continuing?
Prntscrn
![snimek obrazovky porizeny 2017-12-04 16-43-38](https://user-images.githubusercontent.com/34244194/33561390-d3ef96ee-d912-11e7-89e2-44a12e540959.png)

**Comment by grossmj** [comment]
Have you tried to enable HDPI mode in the preferences?

![hdpi_option](https://user-images.githubusercontent.com/4752614/33564930-5a1c73c8-d94e-11e7-922f-7440c523323c.png)

**Comment by TomsonZ** [comment]
Ji Jeremy, 

Thanks for your quick answer.
Yeah I’v tried this one but it doesn’t work for me. I will try again tomorrow, but I think it will be the same.
It have no impact for my working with program, I working with it already for 2 months but I was just curious.
I already added every stuffs like IOU so I don’t want to reload it or something like it. But my GNS version is 2.1.0 and it is the latest I think..

With regards,

Tomáš Zíma

4. 12. 2017 v 17:53, Jeremy Grossmann <notifications@github.com>:

**Comment by TomsonZ** [comment]
I tried again, but as I said, it is still too large :/ 
![snimek obrazovky porizeny 2017-12-06 09-52-31](https://user-images.githubusercontent.com/34244194/33652876-4c5adb58-da6b-11e7-93df-3cb851117b90.png)
