### ISSUE TITLE
uBridge executable version must be >= 0.9.5

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1613]
After building topology using Qemu nodes and connecting appropriate interfaces, I receive the following error when attempting to start nodes: 

`uBridge executable version must be >= 0.9.5`

![image](https://cloud.githubusercontent.com/assets/6335629/19688669/a6a8bdfa-9a98-11e6-9e64-33e48cef86fc.png)

**Comment by codeassassin** [comment]
I also tried replacing uBridge with the version updated 7 hours ago in nightly builds, but got the same error.

**Comment by noplay** [comment]
Upgrading the GNS3 VM to dev3 should fixe the issue, I will check why the package is not correct

Thanks!

**Comment by noplay** [comment]
Ubridge 0.9.5 seem stable I push it to the stable repository

**Comment by codeassassin** [comment]
Yes, I can verify that once GNS3 VM is upgraded to dev3, error no longer produces. Thanks
