### ISSUE TITLE
Save as is not switching to the saved project

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1620]
I appear to be running into difficulties saving my project.

![image](https://cloud.githubusercontent.com/assets/6335629/19726513/4dbea120-9b59-11e6-90ac-407f9920fc1c.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19726559/7f04ac7a-9b59-11e6-97f6-7dcd268207f1.png)

As you can see in the upper left, the project did not save.
![image](https://cloud.githubusercontent.com/assets/6335629/19726578/967d8ee4-9b59-11e6-87bb-a184689306f6.png)

**Comment by noplay** [comment]
How do you save ? It's a save as?

**Comment by codeassassin** [comment]
Yes sir, save as.

**Comment by noplay** [comment]
Fixed! 

Thanks

**Comment by codeassassin** [comment]
Not sure if your fix was added to the nightly I just downloaded from your other thread, however, I got hammered by a fresh round of errors when I tried to save. BTW, there is no "save", only "save as" as I can see, and after agreeing to overwrite the existing project, here is what I get. In the background, the entire topology has disappeared and is grayed out, and is replaced by the warning message. 

![image](https://cloud.githubusercontent.com/assets/6335629/19738488/a9df6472-9b85-11e6-886a-4a3e6eca963f.png)

```
GNS3 management console.
Running GNS3 version 2.0.0dev3 on Windows (64-bit) with Python 3.5.1 Qt 5.7.0 and PyQt 5.7.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Project test already exists, overwrite it?
Project test already exists, overwrite it?
Error while overwrite project: DELETE /projects/e9b0748f-ad10-4ff8-8c35-907f4c0ed746 not found
Error while duplicate: POST /projects/e9b0748f-ad10-4ff8-8c35-907f4c0ed746/qemu/nodes/c3e35bba-0cea-4cd8-ae2d-06bdc764f103/adapters/1/ports/0/nio not found
```
Thanks!

**Comment by noplay** [comment]
Save no longer exist because now:

# Save as you go


Your projects are automatically saved as you make changes to them, there is no need to press any save button anymore. An additional benefit is this will avoid synchronisation issues between the emulators’ virtual disks and projects.

**Comment by noplay** [comment]
I opened a new issue for your save issue: https://github.com/GNS3/gns3-server/issues/745

The problem I think is you try to overwrite the project when save as is for duplicate it under new name / location. We need to prevent that.
