### ISSUE TITLE
Nightly Build 10-26 errors out attempting to connect to GNS3 VM

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1621]
I get a nice long error message after GNS3 gui takes an exceptionally long time trying to communicate with the GNS3 VM. 
```
GNS3 management console.
Running GNS3 version 2.0.0dev3 on Windows (64-bit) with Python 3.5.1 Qt 5.7.0 and PyQt 5.7.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Error while save settings: Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 197, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\gns3_vm_handler.py", line 78, in update
  File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 191, in update_settings
  File "./gns3-server\gns3server\utils\asyncio\__init__.py", line 148, in new_function
  File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 274, in start
  File "./gns3-server\gns3server\controller\__init__.py", line 257, in add_compute
  File "./gns3-server\gns3server\controller\compute.py", line 353, in connect
  File "./gns3-server\gns3server\controller\compute.py", line 457, in _run_http_query
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 555, in __iter__
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 198, in _request
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\async_timeout\__init__.py", line 44, in __exit__
concurrent.futures._base.TimeoutError
```

**Comment by codeassassin** [comment]
I notice in the error output that something is looking for directory C:\Jenkins. That directory doesn't exist on my machine.

**Comment by codeassassin** [comment]
GNS3 VM doesn't seem to be reachable. I doubt this has anything to do with the network adapter issue we were seeing before as I've changed them each way and restarted to no avail. As you can see, GNS3 VM is not reachable, even though there is some connection hook to VMWare Workstation.

![image](https://cloud.githubusercontent.com/assets/6335629/19727349/0a4aa16a-9b5d-11e6-87d7-447859db816b.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19727370/1e1ac49a-9b5d-11e6-80ca-9b5502b05aec.png)

**Comment by noplay** [comment]
No worry about the Jenkins path it's normal. It's just something save during the conversion to .exe

**Comment by noplay** [comment]
Can you check in the logs of the VM (logs entry in the menu) if you don't have an error

**Comment by codeassassin** [comment]
I was trying to get to the menu, and when I typed exit, it stated if the menu was not showing up, type gns3restore. I would advise against typing gns3 restore, unless you want to revert your VM to 1.5.2

**Comment by codeassassin** [comment]
I selected logs in the VM menu, and this is all it shows. Perhaps this is all there is, but when I hit the down arrow, I just get giberish on the screen. I tried to start bash, thinking perhaps some other shell was running that didn't handle terminal navigation well, but it was already running. If there is more to this log, if you know the log filename, I'll pull it up directly. 

![image](https://cloud.githubusercontent.com/assets/6335629/19728252/b2366ea6-9b60-11e6-9ca3-73fc80386310.png)

**Comment by noplay** [comment]
And your client timeout when connecting to the VM?

**Comment by noplay** [comment]
Even if your restart it (client and VM).

**Comment by codeassassin** [comment]
Very interesting. If you wait long enough, it will finely show up...I timed it (very unscientific like) and it took almost 4 minutes for the GNS3 VM to integrate into GNS3 GUI. 

![image](https://cloud.githubusercontent.com/assets/6335629/19728930/42b204d4-9b63-11e6-9711-abe3a3e2a463.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19728952/577644ac-9b63-11e6-875e-88a513dec5fd.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19728995/72837314-9b63-11e6-8166-fb9b1a28c854.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19729060/aae38640-9b63-11e6-8aef-9b1aed4d0fcd.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19729156/fee14ca0-9b63-11e6-81af-b6fd97b5c520.png)

![image](https://cloud.githubusercontent.com/assets/6335629/19729193/2c383fb0-9b64-11e6-825e-bfb86ec3e5a6.png)

**Comment by noplay** [comment]
Ok it seem sometimes gns3server boot faster than the DCHP query in order to get server ip

**Comment by noplay** [comment]
I have a new build improving the detection method:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-26/2.0/GNS3-2.0.2016-10-26-all-in-one.exe/download

And you need to upgrade the VM.

Thanks a lot for   your feedbacks it's really help us a lot
