### ISSUE TITLE
Error: IOU process has stopped, return code: -11

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#1626]
Getting this:

Error: IOU process has stopped, return code: -11 after some time

Running GNS 3 v1.5.2 on MAC 10.12.1 and vmware fusion 8.5 pro and GNS3 VM

Once IOU crashes, I trie to start it but console is not responsive to open the IOU switch (its L2).

Not sure of its IOU or GNS3 VM L2 IOU runs on.

Hmmmm.

**Comment by noplay** [comment]
It's a problem with the image we need to better explain that to user. You need to use a different image

https://github.com/GNS3/gns3-server/issues/739
