### ISSUE TITLE
[2.0] can't start console of VM Box

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1629]
Hi

With 2.0, I can't start console on VirtualBox with headless mode and remote console.

If i start VM without headless mode, GNS3 "shows" the VM.

I have also tested with an empty config.

**Comment by Raizo62** [comment]
I can connect to VM if i use directly telnet and port.
I believe that GNS3 doesn't try to start console.

**Comment by noplay** [comment]
We won't debug current code because it will be replace:
https://github.com/GNS3/gns3-server/issues/747

**Comment by Raizo62** [comment]
No problemo but how many time before change ? Because i want also to test my VMs ? ;-)

**Comment by noplay** [comment]
I will fix all small issues and make this changes. Depending of what issue are reported in the mean time could be arrive next week.

I will start by VirtualBox because we have a tester :)

Which VirtualBox image do you recommend for testing this?

**Comment by Raizo62** [comment]
> Which VirtualBox image do you recommend for testing this?

I don't know : i have this bug with console access on linked clone VM debian of Live Raizo

**Comment by Raizo62** [comment]
I believe that the bug is just that GNS3 don't start the console command (with xterm and telnet)

**Comment by Raizo62** [comment]
But, i don't understand : it is a major bug to not start the xterm console of VM with headless mode, isn' t it ?
Or you can not reproduce it ? (Or my explains are not clear)

I have see you have add "Bring console to front". Do you use an linux command for that ? if yes, which, please ?

**Comment by noplay** [comment]
From the reports it seem almost nobody use the serial console of VirtualBox or VMware.

If they use a VirtualBox or VMware it's because they want to access to the GUI (Windows for example).

**Comment by Raizo62** [comment]
I am not agree.
serial console is necessary because Linux Server must not have GUI. In this case, you are in the TTY.
If i start this server (without GUI) with the window of VirtualBox, the copy-past doesn't work, i can not change the size of window. And the vbox addition is useless for that.

Serial console is a necessary to configure easily a Virtual Linux Server.

It is an error to remove it.

**Comment by noplay** [comment]
Most users use Qemu for linux box in GNS3. Our opinion is VMware or VirtualBox should be keep for special cases where you can't use qemu.

Also to be clear:
We will not remove serial console access, we just drop the old code that allow a direct access to it, without using a telnet connection. Their is no reason to maintain two version of the code in order to access to the same console.

**Comment by Raizo62** [comment]
> Most users use Qemu for linux box in GNS3. Our opinion is VMware or VirtualBox should be keep for special cases where you can't use qemu.

I thought several times to use  qemu instead of VirtualBox, but i don't know how to do for VM knows his GNS3 name, or to use a shared directory without network. :-(

>Also to be clear:
We will not remove serial console access, we just drop the old code that allow a direct access to it, without using a telnet connection. Their is no reason to maintain two version of the code in order to access to the same console.

Perfect :-) i want just to use "serial console access" with telnet connection. But as GNS3 doesn't start the xterm who does the telnet, i can't use it.

**Comment by Raizo62** [comment]
> Which VirtualBox image do you recommend for testing this?

Any VirtualBox image in "headless mode" works to testing. 
I think that GNS3-server does his job : it opens telnet server, that we can use directly with "telnet 127.0.0.1 500". But the GNS3-gui doesn't want to do the same.
Then yes, you can't not use the telnet connection if this VM didn't configured for console , but it is not the bug.

**Comment by noplay** [comment]
Not all images output stuff on serial console. I will setup a debian for that

**Comment by Raizo62** [comment]
Are you sure that you can't reproduce the bug with any VM with headless mode ?
Because i think that "output stuff on serial console" of GNS3-server works (because i can do "telnet 127.0.0.1 5000").

**Comment by Raizo62** [comment]
If you have already downloading Live Raizo, you can download of it the VM (/opt/raizo/user/OS/VBOX/VDI)
