### ISSUE TITLE
[2.0] location of IOS images

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1630]
Hi

Before i put my images in /opt/raizo/user/OS/IOS/ (and the config wizard of GNS3 2.0 doesn't stop me)

But now, when i want use it, GNS3 says that my IOS image on my remote server must be in /home/user/GNS3/image/IOS.
I don't understand why.
can gns3-server not read files outside of /home/user on his own system ?

**Comment by noplay** [comment]
You can change the location of the images with the var image_paths (best option for you):
https://gns3.com/support/docs/gns3-configuration-file-for-adva

Otherwise you need to start the server with --local

By security on a remote without that we don't allow to read/write file outside GNS3 standard folders.

**Comment by Raizo62** [comment]
>You can change the location of the images with the var image_paths (best option for you):
https://gns3.com/support/docs/gns3-configuration-file-for-adva

Thanks...I will look.... :-)

> Otherwise you need to start the server with --local

does gns3-gui not start gns-server with "--local" if we enable "Enable local server" in configuration interface ?

> By security on a remote without that we don't allow to read/write file outside GNS3 standard folders.

I understand

**Comment by noplay** [comment]
The gui do that for the local server started by the GUI but not when you add a remote server.

**Comment by Raizo62** [comment]
Then i don't undestand something : my problem of location of IOS is in the case of the local server is started by the gui (I don't use remote server)

**Comment by Raizo62** [comment]
If 2.0 must run as 1.5, then i believe there is a bug :

With an empty config, i start GNS3
I choose local server (topologies on my computer)
I had IOS router on /opt/raizo/user/OS/IOS/ **without** copy in default images directory
When i put the IOS on the topology : error of access

**Comment by Raizo62** [comment]
But, if i use the config of GNS3 1.5 with GNS3 2.0, i don't have the error message and it works.

**Comment by noplay** [comment]
In which screen do you add the path?

**Comment by Raizo62** [comment]
> In which screen do you add the path?

When i use an empty config, i use the default interface proposed by wizard to add IOS Routers
(I am not sure to understand your question)

**Comment by Raizo62** [comment]
I don't have the bug when i put the directory of IOS in "Additional search locations for binary images"

**Comment by noplay** [comment]
Fixed 

Thanks
