### ISSUE TITLE
[2.0] Is it possible to run the Alpha version and the official release on the same workstation?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1631]
I am now getting back to this and I will deploy the VM for 2.0 in ESXi so that will separate the 1.x and 2.x instances but I would like to use the same workstation for GUI.  Is is this possible to install the 1.x client and the 2.x client on the same workstation?

**Comment by noplay** [comment]
It's not possible. Perhaps in the future we could support that thanks to the profile support on 2.0 but for the moment it's not possible both version use same config files.
