### ISSUE TITLE
Devices sorted out of order

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1634]
Hi friends,

Low-priority request/fix:  Is it possible to have the device numbers sorted in correct order?  For example, create 10 routers, R1 - R10.  They will be sorted in the topology summary as R1, R10, R2, R3, R4, R5, R6, R7, R8, R9.  The consoles also come up in this order.  

Thanks for all you do!

**Comment by noplay** [comment]
Doesn't seem very complicated in pure Python:
http://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside

But will need to check if it's easy when we display the list with Qt.

**Comment by grossmj** [comment]
How we sort the interfaces: https://github.com/GNS3/gns3-gui/blob/master/gns3/items/node_item.py#L330

**Comment by CapnCheapo** [comment]
I think this might provide the functionality?

http://doc.qt.io/qt-5/qcollator.html

In particular setting numericMode

**Comment by noplay** [comment]
Sadly I found no way to use collator but we can override the compare fuction:
http://stackoverflow.com/questions/363200/is-it-possible-to-sort-numbers-in-a-qtreewidget-column

**Comment by noplay** [comment]
And implemented :)

**Comment by CapnCheapo** [comment]
Wow, that's awesome!  Thanks so much!
