### ISSUE TITLE
GNS3  IOU VM PASSWORD

### ISSUE THREAD

**Issue by snorttvaz** [GNS3/gns3-gui#1641]
Good night Hello, I'm new in using appliances and am having problems initializing the GNS3 IOU VM asks for a username and password to complete the boot image, but do not know what could help me please.

**Comment by noplay** [comment]
Hi,

The password are:
root / cisco

If you need GNS3 support please ask on:
https://gns3.com/community

Here we just manage bugs and only developers will be able to answer. On community you will get faster support.

Best 

Julien
