### ISSUE TITLE
[2.0] Bug when start wireshark 

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1644]
I believe that the command in "packet capture reader command" is started 2 times in the same time.

To prove it, i create this file /tmp/prog.sh

```
#!/bin/bash

echo "Father pid : $PPID" > /tmp/prog.$$.log
echo "my pid : $$" >> /tmp/prog.$$.log
```

This program puts into a file named with pid (/tmp/prog.$$.log) his own pid ($$) and his father's pid ($PPID) 
I make this program executable : chmod a+x /tmp/prog.sh

I change configuration of GNS3 with this program in the "packet capture reader command"

When i do a capture (between VPCS and ethernet switch), i have 2 files instead of 1

**Comment by Raizo62** [comment]
Now, i can't reproduce it.

Perhaps you, me or Debian have changed something.

I think that this issue can be closed.

**Comment by noplay** [comment]
Ok thanks
