### ISSUE TITLE
Something is broken when dropping a new node

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1645]
![error_drop_node](https://cloud.githubusercontent.com/assets/4752614/20029438/2646a8bc-a311-11e6-87b4-72abd1829359.png)

**Comment by grossmj** [comment]
@noplay Removing timeout in the call fixes the problem but you may want to investigate that.

**Comment by noplay** [comment]
Your aiohtttp doesn't match the requirements

Le sam. 5 nov. 2016 11:38, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Indeed, I had version 0.19.0!
