### ISSUE TITLE
GNS3 2.0.0 11-07 windows changing vmnet selected for vmware virtual machines

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1649]
Windows 10 Prof x64  VMware Workstation 12.5.1  GNS3 2.0.0 11-07
As I try to recall I believe we have been through this before.  So, I apologize if that is true.
When I add to a vmware workstation virtual machine to a GNS3 topology it seems GNS3 changes the virtual NIC selection I have made.  It seems to prefer vmnet2.  Once GNS3 has started the virtual machine, e.g., window 7, I have to change it back to the vmnet3 which is the one I want to use.

Help!  What am I missing?

Thanks!

**Comment by noplay** [comment]
If you allow GNS3 to use any interface he will remap them

**Comment by jtorri** [comment]
Windows 10 Prof x64 VMware Workstation 12.5.1 GNS3 2.0.0 11-07
Based on my limited experience that does not seem true.  When I create the virtual machine I give it vnet3.  When I add it to GNS3 via Preferences I unselect the "use any interface" option via configure the template for the virtual machine.  Than I add the virtual machine to the GNS3 project topology.
When I start the virtual machine in the GNS3 project its NIC has been changed to vnet2.  This is consistent in my limited testing.  It "appears" GNS3 is assigning the first available free vnet nic, which for my GNS3 VM is vnet2.

**Comment by jtorri** [comment]
If in GNS3 Preferences I the "use any interface" option via configure the template for the virtual machine is unselected, how does GNS3 know whether or not to use the "selected" vnet or ubridge for that virtual machines NIC?  Or does that question make any sense?

**Comment by jtorri** [comment]
Well, slow thinker that I am I believe I finally got it.  If the "use any vnet interface" is unselected than GNS3 will use ubridge for the virtual machine's NIC connectivity.  In that case, it doesn't matter which vnet GNS3 "chooses" for the virtual machine NIC, GNS3 it's not using it.
So, it seems to be the thing to do is close this issue.  Thanks!

**Comment by noplay** [comment]
I agree that it's not easy
