### ISSUE TITLE
[2.0] bug with capture

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1656]
I use an empty config of GNS3

- I put a vpcs connected to an ethernet switch. I don't start theses devices.
- I put wireshark on the link.
- I start the device. 
- On the VPCS, i do "ip dhcp".

On wireshark, i should see the DHCPDiscover. I see nothing

**Comment by noplay** [comment]
I made a quick test and it's work my mac. We need to test on Linux.

**Comment by Raizo62** [comment]
Have you can test on Linux ? (just to know that you can reproduce it ;-) )

**Comment by noplay** [comment]
I just tested the exact scenario on ubuntu 16.10 and it's work without problem.

**Comment by noplay** [comment]
Other captures work?

**Comment by Raizo62** [comment]
I have the bug also with Debian.
But with Router Cisco, i see the DHCPDiscover.

If you want, tonight i create a live with last files of GNS3 and i send you the iso. You will can test.

**Comment by noplay** [comment]
How do you install VPCS?

**Comment by Raizo62** [comment]
(I sent you the link with the live)

>How do you install VPCS?

```
cd vpcs/src
./mk.sh
```
must i change ?

**Comment by noplay** [comment]
Ok I found the issue. 

Your version of VPCS is broken. The 0.8X series is not yet stable and we don't recommend it.

We recommend to use VPCS 0.6.1 (VPCS 0.6 + some back ported patch by us)
* Use last source from https://github.com/GNS3/vpcs
* Use debian package from here (use the xenial version): https://launchpad.net/~gns3/+archive/ubuntu/ppa

**Comment by Raizo62** [comment]
I have tested with the last source "master" from github of GNS3.
I have always the bug.

Is it correct that the version of your vpcs is 0.8c ?

**Comment by noplay** [comment]
It should be 0.6.1

**Comment by Raizo62** [comment]
In this file : [vpcs of gns3](https://github.com/GNS3/vpcs/blob/master/src/vpcs.c)
const char *ver = "0.8c";

**Comment by ehlers** [comment]
https://github.com/GNS3/vpcs/releases/tag/v0.6.1 gives you access v0.6.1 (linux binary, OS X binary and source).

**Comment by ehlers** [comment]
Don't know, if it's helpful, but on v1.5.3dev1 vpcs running in my own debian stretch based GNS3VM works with both versions (0.6.1 and 0.8c) in your scenario. I can't test with 2.0, as currently I need a stable GNS3.

**Comment by Raizo62** [comment]
Me too, this scenario works with vpcs 0.8c and GNS3 v1.5.3dev1 on Debian Jessie Backport.

**Comment by Raizo62** [comment]
And vpcs issue does not explain why i have also this bug when i replace vpcs by my Debian Vbox (but, yes, i know that we can have more of 1 bug ;-) )

**Comment by Raizo62** [comment]
I have tested with vpcs v0.6.1 : always, no DHCPDiscover

**Comment by noplay** [comment]
Did you install it with our packet? It was working for me with LiveRaizo and the GNS3 vpcs packet.

I'm mostly sure 0.8c has a memory issue because it's just crash on OSX. But we didn't manage to isolate the issue with VPCS author.

**Comment by Raizo62** [comment]
I think that your "debian package" is for ubuntu OS (ppa).
I have compiled VPCS 6.1 (but, perhaps, i have used the bad commit)

Be careful, i didn't say that vpcs crashs : if i put also an DHCP Server (with VM), vpcs has an IP. But, wireshark doesn't show the packets. For me, the bug is with "wireshark capture"

I am surprised that it was working for you with LiveRaizo v8 : i have tested on my portable PC and on VirtualBox on another PC.

Tonight, i will try to use your ppa : perhaps you have a different option of compilation

**Comment by noplay** [comment]
PPA for ubuntu work for debian.

Each version of ubuntu is base on a version of  Debian, you just need to use the correct:
https://gns3.com/support/docs/linux-installation

That 's strange because before changing VPCS it was just not working for me. No capture, No DHCP. After changing it I no longer have issue. I test again with your LiveRaizo and it's work even with the 0.8:
![capture d ecran 2016-11-21 a 14 48 17](https://cloud.githubusercontent.com/assets/345437/20484892/a6808a1c-aff9-11e6-9b53-05cce1e65e4f.png)



If you have DHCP but no packets captures. Could be an issue with ubridge. Or Wireshark is not correctly installed (your user need to be a member of the wireshark group).

**Comment by Raizo62** [comment]
> your user need to be a member of the wireshark group

only if we don't use the capability ? (I use capability with Live Raizo)
I have tested for see on an old v8, but not changing

I don't understand if it works with your Live Raizo v8
Are you configure the capture before to start the lab ? (if i do it after, i see the packets)

**Comment by noplay** [comment]
I's work with the LiveRaizo you provide me. I can start the capture before I start the lab.

**Comment by Raizo62** [comment]
I have do several tests to understand why you don't have the same issue as me with the same OS.

I use vpcs 6.1 (not yet ppa)

Perhaps i have the explain :

- If i connect the cable first on the ethernet switch, wireshark shows packet (i see also one ipv6 router solicitation)
- If i connect the cable first on the vpcs, wireshark shows nothing

How do you do ?

**Comment by noplay** [comment]
Ok I confirm in this order it's not working in LiveRaizo (need to test on other hosts)

**Comment by noplay** [comment]
Ok in this oder it's not working on any OS.

Good catch

**Comment by noplay** [comment]
Big patch:

Now:
* capture is not possible if one one the node is not running
* when we choose the best node for running capture we start by node always running
* if you stop the node where capture is running the capture stop

Should cover all the use cases.

**Comment by Raizo62** [comment]
Ouf.... I was beginning to believe that i was fool ;-)
Thanks :-)
