### ISSUE TITLE
Replace .iourc file by a text box

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1662]
I propose that we replace the .iourc file in preferences by a textbox where the user will past the licence (and a browse button to fill it). This preferences will make a basic check of the syntax of the file.

The problem actually is it weird for user to put path to something on his computer, for something that is on remote. Also we make magic to update the licences on servers when starting the IOU node, it seem more logic to have this store in the controller and all compute get the info from here.

**Comment by grossmj** [comment]
Excellent idea!

**Comment by noplay** [comment]
Much better, and work better.

**Comment by AzzyInc** [comment]
Quick question ot...
Running xenserver. Start VMware. Win 10 vm. Start it and get the VMware cannot run with hyper visor error.
Ran the bcdedit command and made sure hypervisor wasn't checked. Rebooted. Same error, thoughts?

-----Original Message-----

**Comment by noplay** [comment]
Hi,

For support please ask your question on https://gns3.com/. Github is only for tracking bugs and new features. 

Also in order to help we will need more information like screenshots.

**Comment by AzzyInc** [comment]
😃 

-----Original Message-----
