### ISSUE TITLE
[2.0] bug with console of linked clone of VBox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1663]
Hi

- I put on the lab a linked clone of VBox
- I start the VM
- I open the console of the VM
- I stop the VM : the console is not closed

**Comment by noplay** [comment]
If you restart the VM the console is not connected again?

**Comment by Raizo62** [comment]
if i start the VM again, i can not put anything in the VM

**Comment by Raizo62** [comment]
Perhaps, i am not clear : I use headless mode of VM

**Comment by Raizo62** [comment]
Perhaps, i am not clear : I use headless mode of VM

**Comment by noplay** [comment]
It's fixe
