### ISSUE TITLE
Allow to disable the serial console in VirtualBox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1666]
Hi

I have a VBox without headless mode (as Microsoft)

I start the VBox.
When i start console, GNS3 start console of VBox

**Comment by noplay** [comment]
It's not an issue but normal behavior.

Headless and console are two different thing non related. You can have a appliance running non headless and you want to access to the serial console (common when you setup the serial output).

**Comment by Raizo62** [comment]
It is logical but not pratical.

I agree with you on your argument.
But you see that it is not clean to close an xterm because your VM do not work with serial (for example default Windows).

I think you "must" add an option for each VM to start the console (as GNS3 1.5)

**Comment by noplay** [comment]
I just test and it's the same behavior in 1.5. The console open.

If you think this option in 1.5 control that:
![image](https://cloud.githubusercontent.com/assets/345437/20602053/ee41f764-b25b-11e6-9972-0abb320465be.png)

It's not true. This options choose if we try to call connect to the serial via telnet or a direct connection. Perhaps in your case the serial connection was failing due to missing socat and xterm was exiting immediately. And because now all is via telnet your xterm is not closing.

**Comment by Raizo62** [comment]
My problem is for VM with OS not configured with serial

If i put on my lab an Windows XP with default installation, and i click on the "open all consoles" button of GNS3, GNS3 opens an useless xterm because i can't configure this windows with console. I need close the xterm.
(Or the bug is mine)

If my lab contains several hosts : Ciscos, "Console" Linux, vpcs and Windows : i must find consoles to close.

> If you think this option in 1.5 control

Yes, I was thinking the "Enable remote console" button, but don't worry, i don't ask to add "socat" ;-)

Perhaps, a check named "Enable serial access" : if it is checked on VM, GNS3 starts the xterm command, else not.

**Comment by AzzyInc** [comment]
Or like in xenserver, they have a "dock" console button. You also have the choice to find console.


-----Original Message-----

**Comment by Raizo62** [comment]
> Or like in xenserver, they have a "dock" console button. You also have the choice to find console.

My idea is that is "stupid/useless" to open xterm on VM which can't accept serial access.
(Or i bug and GNS3 doesn't do that)

It is better, i think, that if i double-click on the device, GNS3 shows the VirtualBox Windows of the VM than the xterm console (that i do with Live Raizo v7)

**Comment by AzzyInc** [comment]
I like the idea of double click and it opens VMware vs xterm. It should be powershell if it detects windows. Hehe

-----Original Message-----

**Comment by noplay** [comment]
Problem we can't do that because we don't know which windows is the VM. 

We just send commands to VMware and Vbox and after that they display stuff how they want. We have no link to the window.

**Comment by Raizo62** [comment]
>> It is better, i think, that if i double-click on the device, GNS3 shows the VirtualBox Windows of the VM than the xterm console. (What i do with Live Raizo v7)
>
> Problem we can't do that because we don't know which windows is the VM.

I think that you can because i does it in Live Raizo v7 ;-) You can try

**Comment by Raizo62** [comment]
But, my method works on Linux and with local GNS3 server.  I don't know on Windows and with remote GNS3 server.

And my first question ? :-)

**Comment by noplay** [comment]
Bring windows to front if we didn't have spawn it it's not something easy working cross platform & cross windows manager.

**Comment by noplay** [comment]
For the other question @grossmj  what do you think?

**Comment by noplay** [comment]
For me we should keep current behavior because it's the way it's work today and nobody complaints until now.  

Ideally we should have a console type with three choice:
* Telnet (serial output)
* VNC
* No console

And qemu & docker should also have this options. But it's too late to make changes like this in 2.0, because it's the kind of change that could have unexpected side effects.

**Comment by Raizo62** [comment]
> nobody complaints until now.

I am surprised of that.  I suppose that i am not only one who uses default Windows and who clicks on "Console connect to all device" and who is annoyed with useless console.

> VNC 

For curiosity : how do i start the command for VNC client (with GNS3) ?

In config of GNS3, i see "bring console window to front", again. The code is writing ?

But, i can perhaps use your bug to do same as "bring console windows to front" of Live Raizo v7

**Comment by noplay** [comment]
For the moment VNC is not supported for VMware and Vbox. You can use it with docker or Qemu.

**Comment by Raizo62** [comment]
> In config of GNS3, i see "bring console window to front", again. The code is writing ?

You don't want answer to this question ? ;-) 
I want to know if i must install a linux program and which

**Comment by noplay** [comment]
For bring console I found a ticket speaking about this:
https://github.com/GNS3/gns3-gui/issues/847
https://github.com/GNS3/gns3-gui/issues/1315

And for the settings it seem to not have been cleaned:
https://github.com/GNS3/gns3-gui/issues/1681

We will see this topic when we will work on (no warranty if it will be something in 2.1):
https://github.com/GNS3/gns3-gui/issues/469

But for the moment our priority is on Qemu we focus our effort on it without breaking support for VMware and Vbox.

**Comment by Raizo62** [comment]
Ok.
We have already discut from the button "bring console window to front" here #1315
As this option was come back, i had supposed that you had writing code for it.
Just answer "not writing yet" was sufissant ;-)
But thanks for all links

**Comment by noplay** [comment]
Thanks for spotting the issue.
