### ISSUE TITLE
[2.0] Save show/hide interface labels setting

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1667]
Hi

Do you know if, a day, we will have an option to enable by default the "show/hide interface labels" ? ;-)

I ask this since GNS3 legacy :'(

**Comment by noplay** [comment]
I think we should save this in the project  same for:
* show the grid
* snap to grid

And a global settings for new project creation.

**Comment by mad-bison** [comment]
I would also very much like to add defaults for Snap to grid and show the grid.
Having a checkbox in preferences to set each of these would be great!

**Comment by cioby23** [comment]
I think this has been implemented in this pull request https://github.com/GNS3/gns3-gui/pull/2138. It will be available in version 2.1

**Comment by noplay** [comment]
@cioby23 you are right

**Comment by Raizo62** [comment]
Hip Hip Hourra !!! :-D

**Comment by Raizo62** [comment]
Hi

I test the 2.1.

Sorry. i don't find where (or how) we can configure the option to enable or not the "show/hide interface labels" for new project.
