### ISSUE TITLE
I cannot connect via console to custom VM

### ISSUE THREAD

**Issue by MoD01** [GNS3/gns3-gui#1668]
I want to connect via telnet to, e.g. Kali Linux or Windows. I get the following, when the console opens:
```
Last login: Tue Nov 22 20:51:57 on ttys009
mycomputer$ telnet localhost 5007
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
KaliHost-1 console is now available... Press RETURN to get started.
```
Do I have to start a telnet service on the Kali VM or is this not required ?

I need a way to do it via GNS3 -> right click on VM -> Console

BTW: this works fine for gns3 images from the marketplace.

**Comment by noplay** [comment]
You need to enable the serial console in the OS  of the VM

**Comment by MoD01** [comment]
Ok, thanks for the quick reply 😃 
I will try to enable a serial console for Windows + Kali Linux and post my experiences here.

**Comment by MoD01** [comment]
For all who have the same problem: 
A good guide for Kali Linux can be found here : https://www.cyberciti.biz/faq/howto-setup-serial-console-on-debian-linux/

this worked for me
