### ISSUE TITLE
GNS3 2.0.2016-11-22 install on new computer won't start

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1670]
Put a rather lengthy comment here than realized problem likely related to vmware workstation player vs vmware workstation.  Sorry, do not know how to fully deleted an issue once created.  Thanks!

**Comment by noplay** [comment]
You don't have other GNS3 process running that could have not been kill
during the update?

**Comment by jtorri** [comment]
I thought I had deleted this issue.  Clearly not yet as knowledgeable of github as I need to be.  Please close it for now.  I ran the same version of GNS3 on another machine running the same OS but with VMware Workstation 12.5.2 rather than the latest version of VMware Workstation Player and all worked fine.  I suspect that is the issue and/or my less than ideal skill set.
