### ISSUE TITLE
2.0 alpha 4 : not able to load project from GNS3 VM

### ISSUE THREAD

**Issue by nrafia** [GNS3/gns3-gui#1671]
I have just upgraded from alpha 3 to alpha 4 and now GNS3 is not able to detect my GNS3 VM, which was working fine in 3. I am getting error message Operation Cancelled.
I have upgraded, restarted vm and my machine. When ever i will launch Gns3 it will start GNS3 vm successfully but when i load a project, it will keep trying to connect and it will take long time then eventually it will fail. Same project i will able to load in alpha 3. I can create new blank projects and those work fine. But old projects i cannot open.

**Comment by noplay** [comment]
Do you have upgrade the GNS3 VM also?

**Comment by nrafia** [comment]
Yes upgraded using upgrade script.

**Comment by noplay** [comment]
After GNS3 has started could you wait 5 minutes and go to help => Export debug informations and send the mail to developers@gns3.net 

No hurry we will not read the email before monday.

**Comment by noplay** [comment]
Thanks for the help

**Comment by nrafia** [comment]
I have sent multiple debug files...
