### ISSUE TITLE
Issues disabling local server

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1674]
Hey guys, running 2.0.0a4 on OSX.  

It would be nice if disabling the local server under the Server preferences would also uncheck the "Use the local server" box under Built-In, VPCS, Dynamips, IOS on UNIX, QEMU, VirtualBox, VMware, and Docker.  Then we can avoid a string of "Cannot connect to http://127.0.0.1:3080" messages.

**Comment by CapnCheapo** [comment]
...Looking around further there seems to be several bugs in the GUI related to disabling the local server and running on remote server only.  Are you aware of these problems or should I submit an issue for each?

**Comment by noplay** [comment]
When do you get the message "can not connect"? And the settings "use local server" should do nothing. 

Submit issues, in theory we have fix all issues related to this, but it seem not. And we are very interrested to have feedback on this area.

Thanks

**Comment by CapnCheapo** [comment]
So it looks like when the remote server is setup through the Setup Wizard things work fine (I am old fashioned and always close the wizard to setup things manually :)  

From the Server Preferences dialog, I uncheck Enable local server.   For the Remote Main Server box, I add my remote server info to Remote Main Server box.  I click apply.  

I noticed that adding a remote main server does not add that server to the Remote servers list on the 2nd tab.  I think the differences between remote servers and remote main server may end up being confusing to users.

With just the remote main server added and no remote servers added (2nd tab), I can't use the remote server.  Maybe the info from the remote main server box can be copied to the remote servers list?

Trying this functionality a different way:  Start with an empty config, cancel the wizard, uncheck Enable local server.  Ignore the remote main server still pointing to 127.0.0.1.  Move to the remote servers tab and add the remote server.  Click apply.  GNS3 waits for the remote server to stop.  Dialog for Cannot connect to http://127.0.0.1:3080 is displayed.  Maybe the first remote server entered can also be copied over to the remote main server box?  Now, I go back to the main server tab and manually change the remote main server to match my remote server.  Click apply.  From here devices can be added as normal, except there's now a dialog that asks if you want to use the remote computer or the main server.  See how this might be confusing?

The multiple cannot connect to 127.0.0.1 errors only occurs if I don't go back and change the remote main remote server after adding the remote server.

This might be confusing, let me know if I need to expand further :)

**Comment by noplay** [comment]
I'm still looking on that. The GUI was not really designed to run without a server and I found corner cases.

**Comment by noplay** [comment]
Should be ok now.
