### ISSUE TITLE
i cant import Dans CCIE v5 lab v4 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#1675]
Hi when i want to open Dans (Daniel Demers) CCIE v5 lab v4
i receiving following error

![err](https://cloud.githubusercontent.com/assets/8465075/20648478/977e5c10-b4bd-11e6-86e2-a83f09189db9.png)

the strange thing is that i have that image in my IOU device list 

![err2](https://cloud.githubusercontent.com/assets/8465075/20648482/b47dc080-b4bd-11e6-9a1f-e996b09a5eb1.png)

as you know i86bi-linux-l2-adventerprisek9-15.2c.bin and i86bi_linux_l2-adventerprisek9-ms.high_iron are the same images 
i have both of them

this  is that LAB

https://www.dropbox.com/s/duxbcpyczv4a3t9/Version%204.zip?dl=0#

**Comment by taurus8** [comment]
I have tested with 1.5.2 with only  i86bi-linux-l2-adventerprisek9-15.2c.bin and did NOT receive any error

**Comment by noplay** [comment]
Do you have try to create a router with the missing image?

**Comment by taurus8** [comment]
its not loading the project to create that missing router
but i can create that router in new brand project

**Comment by taurus8** [comment]
this is my i86bi-linux-l2-adventerprisek9-15.2c.bin image (high iron)
but i dnot know why its saying this image is missing 
![errrr](https://cloud.githubusercontent.com/assets/8465075/20661905/55f5d6d4-b566-11e6-8503-30651cb9e5e7.png)

**Comment by noplay** [comment]
The filename is very important you need to have the exact filename

**Comment by taurus8** [comment]
will it work if i change file name ?

**Comment by noplay** [comment]
We search image by filename, due to compatibility issue we don't retry to replace an image by another.

**Comment by taurus8** [comment]
i have this following image too , but the image name is not the same as that missing image
![image](https://cloud.githubusercontent.com/assets/8465075/20663047/5a282982-b56b-11e6-8a7c-6be23457d1a3.png)


will it work if i change this name to i86bi_linux_l2-adventerprisek9-ms.high_iron ?

**Comment by noplay** [comment]
You can try. I can't warranty that the image use by the other user has not
different commands.

**Comment by taurus8** [comment]
Still no Success :( 
i close this
