### ISSUE TITLE
[2.0] bug when HDD of qemu is not in the default directory

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1680]
Hi

I think that you can reproduce it with your Live Raizo v8

Just for test, i wanted to create a Qemu device and to use the VDI of VMRaizo.
When GNS3 asks me to choose disk image, i indicate VM-Raizo.vdi (or  /opt/raizo/user/OS/VBOX/VDI/VM-Raizo.vdi).
I don't accept to copy the file in the default images directory 

When i put my device on the lab, GNS3 says "The image VBOX/VDI/VM-Raizo.vdi is missing"

**Comment by noplay** [comment]
I will need to test on LiveRaizo I don't reproduce it on my mac when I use a random VDI available on my PC.

**Comment by noplay** [comment]
It's look like we consider that the VBOX directory in LIVE RAIZO is a standard folder for images
![capture d ecran 2016-11-28 a 15 19 21](https://cloud.githubusercontent.com/assets/345437/20672465/b3f3b81c-b581-11e6-9687-7a971ceb9866.png)

![capture d ecran 2016-11-28 a 15 43 31](https://cloud.githubusercontent.com/assets/345437/20672424/8e678290-b581-11e6-854a-e3b2002592db.png)

**Comment by noplay** [comment]
I think we recurse on the folder content at the wrong place

**Comment by noplay** [comment]
For legacy reason we support images in the top directory of the default images directories. Problem we recurse search in all folders that could contains images. But later we will detect that the folder is in the default location and strip the beginning.

This problem could also arrive if you setup an additional search image path in the standard location. 

We should not recurse if images are in the standard location. Only if they are outside.

**Comment by noplay** [comment]
Fixed. I didn't expect so much work :(
