### ISSUE TITLE
ubridge root permission dialog box issues

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1687]
Hi friends!  This is for 2.0.0a4 running on OSX.

Start with an empty config.  Two dialog boxes for ubridge permissions are displayed, one on top of each other (not to be confused with the two dialogs asking for the password twice, once for chmod, once for chown. )  

So I enter the sudo password twice and the Setup Wizard opens.  Meanwhile, there's still a ubridge permission dialog open in the background, but you are unable to click the buttons since the Wizard has focus lock.  

I complete the wizard, in my case specifying a remote server.  Dialog about waiting for local server to stop is displayed.  I click finish in the wizard.

New appliance template is displayed.  Add appliances as desired, then the project window comes up.  We create a new project.  

At this point all windows close and we are left with the second ubridge permissions dialog.  Passwords are entered again because that's the only way to get the GUI to open.  

GNS tries to connect to the local server, but it can't because we disabled it during the setup wizard.

After the connection attempt fails we can cancel and return to the GUI, where the remote server is still setup correctly.

Also, maybe you can consider something like "chmod 4750 /Applications/GNS3.app/Contents/Resources/ubridge && chown root:admin /Applications/GNS3.app/Contents/Resources/ubridge" so that the password is only asked for once?

**Comment by noplay** [comment]
First improvement both command are executed at without asking twice for the password.

**Comment by noplay** [comment]
Should be good now
