### ISSUE TITLE
Feature request:  Automatic device template import

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1694]
It would be cool for a future version to query the appliance registry and load all the templates so that the users don't have to go find appliance files themselves.  Devices could then be selected from a some kind of wizard.  There would be a button to sync the repository.  Custom templates would be maintained separately and not removed during sync.

**Comment by noplay** [comment]
Another discussion on this topic: https://github.com/GNS3/gns3-gui/issues/1045
