### ISSUE TITLE
Feature request:  Device type choice when creating device

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1695]
I have seen new GNS3 users create a QEMU device (for example IOSv), accept the defaults, and then wonder where the device went.  Since it defaults to category End Devices, with a symbol of qemu_guest, it is not always clear to a new user that, for example, a router image does not by default show up under the routers category.

My suggestion is to add radio buttons to one of the template pages as such:

This device is a:
[*] Router
[ ] Switch
[ ] Security Device
[ ] End host/Other

Then we can decide the category and choose a generic icon for each category.  The user is free to customize it further the normal way.

**Comment by CapnCheapo** [comment]
The logical extension of this would also be to have the device type a field in the appliance template for the registry.

**Comment by noplay** [comment]
The appliance template support it:
https://github.com/GNS3/gns3-registry/blob/master/schemas/appliance.json#L22


I agree for a choice in the wizard it could be a simple but usefull improvement

**Comment by noplay** [comment]
To do that we need:
Modify the wizard UI gns3/modules/qemu/ui/qemu_vm_wizard.ui
Retrieve the info and change the device type in:
gns3/modules/qemu/dialogs/qemu_vm_wizard.py

A sample implementation in the IOU wizard:
https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/iou/dialogs/iou_device_wizard.py#L117

**Comment by noplay** [comment]
@CapnCheapo has started to develop something

**Comment by CapnCheapo** [comment]
I am surprised you kept this open for me :) I had some issues preventing me from being involved for a while, but I am back and hope to get this pushed out this weekend...

**Comment by noplay** [comment]
No worry if you can't do it, we just want to avoid conflict with your work

**Comment by CapnCheapo** [comment]
No problems with work, it was actually a health problem, but I am better now.

**Comment by noplay** [comment]
Take care of yourself it's the most important :)

**Comment by noplay** [comment]
Hi @CapnCheapo we plan to release a 2.1 soon. If you have something I can help you in order to embed your work in the next release.

If you don't have something no worry it's not blocking for us.
