### ISSUE TITLE
sudo doesn't work, if user is not included in /etc/sudoers

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1699]
GNS3 version 2.0.0dev5 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

On OS X if you create a user as non-admin, he is not allowed to use sudo. If such a user wants to use GNS3 the sudo calls in GNS3 to change the permissions of `ubridge` will fail. The same should be true for linux.

On OS X you might consider replacing sudo by `osascript -e 'do shell script "privileged command" with administrator privileges'`, for linux I have no simple solution.

**Comment by noplay** [comment]
I improved this on OSX. On Linux this should be less a problem because in theory if ubridge is installed correctly (package or make install) the permission are already ok.

**Comment by ehlers** [comment]
Thanks a lot, changing the permissions of `ubridge` is now working also from a non-admin account.

But I haven't thought that far enough. `ubridge` currently allows only the admin group to get access. As I like to use GNS3 on a non-admin account, this won't work. As a workaround a changed the group of `ubridge`to access_bpf. I already added my user to the access_bpf group to allow pcap/wireshark access. But maybe a special group for GNS3 network access may be better.

I'm just starting with v2.0. When I have fully tested, what's necessary for using GNS3 as an unprivileged user I will post a follow-up.

**Comment by noplay** [comment]
The deb package create a ubridge group.
