### ISSUE TITLE
Merge devices view

### ISSUE THREAD

**Issue by Ztaguassi** [GNS3/gns3-gui#1707]
Create merge view for devices.

Something like:
Select some devices > Right Click > Merge > Insert name "Site A" > It show "Site A" like one item
Select others devices > Right Click > Merge > Insert name "Site B" > It show "Site B" like one item
Select "Site A" and "Site B" > Right Click > Merge > Insert name "Client A" > It show "Cliente A" like one item

Double click on "Client A" > It show "Site A" and "Site B"
Double click on "Site A" > It show "Site A" devices.

Add button to zoom out view.

It can help to clean the workplace when have many devices

**Comment by AzzyInc** [comment]
That's pretty good idea.

-----Original Message-----

**Comment by noplay** [comment]
Thanks

It's the same kind of idea as  #1100

Not planned for the moment because it's complex to do.
