### ISSUE TITLE
Alignment reversed after start of devices

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1710]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Place two devices into a new project
![initial_placement](https://cloud.githubusercontent.com/assets/896406/21073486/13aa727a-bee0-11e6-9433-23e840583622.png)

Align them horizontally by the "Align horizontally" function
![align_horizontally](https://cloud.githubusercontent.com/assets/896406/21073489/26c3c442-bee0-11e6-9589-eba567005b32.png)

Start the devices. The devices move back to the old position, the alignment is gone.
![start_devices](https://cloud.githubusercontent.com/assets/896406/21073491/3254b7e4-bee0-11e6-9d22-3e9ad27a5676.png)

**Comment by noplay** [comment]
Good catch it's fixed
