### ISSUE TITLE
Port numbering differs between self defined built-in hub/switch and original ones

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1712]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Self defined build-in ethernet hubs and switches (preferences -> Built-In -> Ethernet hubs/switches) use ports starting from 1 while the original ones start with port 0.

**Comment by noplay** [comment]
Probably the root cause of #1711
