### ISSUE TITLE
Menu items to handle projects are split into file and project menu

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1713]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The menu items to handle projects are split into two different menus, the file and the project menu. I don't get the logic for that. Furthermore the recent files and recent projects list differ.

File menu
![bildschirmfoto 2016-12-10 um 14 47 12](https://cloud.githubusercontent.com/assets/896406/21073758/b7ff382c-bee7-11e6-83e3-f485ae613fd8.png)

Project menu
![bildschirmfoto 2016-12-10 um 14 47 27](https://cloud.githubusercontent.com/assets/896406/21073759/bb80e482-bee7-11e6-8d5e-dd23bada987e.png)

**Comment by noplay** [comment]
We can display the file history only for local controller and the project history only for remote controller.

**Comment by grossmj** [comment]
I propose the following changes:

* "Manage Snapshots" should be moved to the Edit menu.
* Move "Take a screenshot" and "Import/Export device configs" to the Tools menu.
* Move "Edit project" and "Delete project" to the File menu.
* Delete the project menu.

**Comment by noplay** [comment]
Where we should display the recent projects when you are connected to a remote server? Just in the open project box?

**Comment by grossmj** [comment]
Maybe replace the file history in the File menu?

**Comment by grossmj** [comment]
Only the recent projects remain to be moved.

**Comment by noplay** [comment]
#1730 I will take care of the final modifications
