### ISSUE TITLE
Wireshar-Capture shows only one direction

### ISSUE THREAD

**Issue by diotimo** [GNS3/gns3-gui#1717]
Wireshar-Capture shows only one direction

if I capture a link and send a ICMP-Ping, then I see only one packet, the retirning packet is not captured by Wireshark

**Comment by noplay** [comment]
On which version? What do you try to capture?

**Comment by diotimo** [comment]
Version: GNS3 2.0 beta and the dev channel

 

Wiresharkcapture (Wiresharkversion newest 2.2.2 x64) between 2 Routers (i86bi-linux-l3-adventerprisek9-15.5.2T.bin) on a ethernetlink, with rightclick on the 'cable'.

I bulid a VPN-Tunnel and could only capture half the traffic, I missed the traffic in the other direction.

The VPN-Tunnel worked just fine.

Same problem with simple ICMP-Pings.

 

IOU-Image:

(https://www.dropbox.com/s/ftrysqxwpszz66x/i86bi-linux-l3-adventerprisek9-15.5.2T.bin?dl=0 )

 

Same works fine with version 1.5.2!

 

Greetings from Switzerland

Peter

 

Gesendet: Montag, 12. Dezember 2016 um 22:15 Uhr
Von: "Julien Duponchelle" <notifications@github.com>
An: GNS3/gns3-gui <gns3-gui@noreply.github.com>
Cc: diotimo <p.n@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [GNS3/gns3-gui] Wireshar-Capture shows only one direction (#1717)


On which version? What do you try to capture?

**Comment by grossmj** [comment]
Thanks for catching this. I think this is an issue with the new uBridge.

**Comment by grossmj** [comment]
Bug confirmed.

**Comment by grossmj** [comment]
Indeed, there was a small programming issue in uBridge. Fixed by https://github.com/GNS3/ubridge/commit/7301114b84bf6cf632169001fc21e22f64ea6ad9
