### ISSUE TITLE
[2.0] BUG : detect kvm 

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1722]
Hi

When i want to start VBox, i have this error message : "Cannot start VM because hardware virtualization (VT-x/AMD-V) is already used by another software like VMWare or KVM (on Linux)"

And i think not ;-)

**Comment by noplay** [comment]
What node do you have in your project?

**Comment by Raizo62** [comment]
You have right : i have this message when i use also ethernet switch

**Comment by noplay** [comment]
Good catch it should be fix with last server source code
