### ISSUE TITLE
GNS3 2.0.0b1 ubridge option for VMs

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1723]
Windows 10 prof 64 bit, GNS3 2.0.0b1, VMware workstation 12.5.2, all network objects and VM run in GNS3 VM.
When in GNS3 preferences adding/configuring a Virtual Machine using the network tab, the ubridge checkbox is not there.  It is in GNS3 1.5.1.  Is that because the default for VMs in GNS3 2.0.0b1 is ubridge and only if the Allow GNS3 to use any configured VM adapter is checked does the VM not use ubridge?

Is there a reliable method to verify ubridge has loaded?  Sysinternal tools do not show it.

Hope this makes sense.  Thanks!

**Comment by noplay** [comment]
It's only ubridge in 2.0
