### ISSUE TITLE
Tail process for wireshark trace not killed when we change project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1725]
GNS3 version 2.0.0dev6 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The tail process for wireshark traces on remote devices is killed, when the device is stopped. But hubs/switches are always on.

After creating a trace on a remote hub/switch, then starting a new project (or closing GNS3),  the tail process remains active. The trace should be stopped, when the project closes.

**Comment by noplay** [comment]
Fixed now when we change project we kill all the running tail process
