### ISSUE TITLE
[2.0.2016-12-16] GNS3 Client not connecting to remote controller

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1726]
Hey Again!

Just grabbed the most up to date nightly build of the GNS3 GUI client and updated the gns3-server with the most recent changes from github. 

The problem i'm seeing is that when I launch the GUI it does not attempt to make a connection to the remote server;

![image](https://cloud.githubusercontent.com/assets/7719536/21274599/10d574da-c397-11e6-86bb-7a4015a38917.png)

![image](https://cloud.githubusercontent.com/assets/7719536/21274618/24cf102c-c397-11e6-91eb-53e9a659cd6b.png)

![image](https://cloud.githubusercontent.com/assets/7719536/21274622/28118544-c397-11e6-9587-c14ede532039.png)
![image](https://cloud.githubusercontent.com/assets/7719536/21274634/36424806-c397-11e6-8e8d-b3fa609c09bf.png)

![image](https://cloud.githubusercontent.com/assets/7719536/21274673/547da98c-c397-11e6-8f31-80594fdc9f01.png)

**Server Log File**

![image](https://cloud.githubusercontent.com/assets/7719536/21274684/60325872-c397-11e6-96ef-7c515c1cb1ca.png)

**Comment by gcasella** [comment]
@noplay just an update, grabbed the latest images for both the client and server from sourceforge nightly builds and seems to be OK now. 

I do get this message in the console of the client now -- not sure if it's normal or not

> => [{'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': 'ccb6d42e-073b-4b06-a6c8-ce5fe07319e7', 'filename': 'CCNP SWITCH LAB 7-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 7-1', 'name': 'CCNP SWITCH LAB 7-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '7ae898a2-843a-43c0-b3a5-da85fca38eaf', 'filename': 'CCNP SWITCH LAB 10-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 10-1', 'name': 'CCNP SWITCH LAB 10-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '74e745ed-b9e8-47f2-a0ec-b827cf676c02', 'filename': 'CCNP SWITCH LAB 5-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 5-2', 'name': 'CCNP SWITCH LAB 5-2'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '3d4f284a-d515-4b6d-8605-46cd70aa3c90', 'filename': 'CCNP SWITCH LAB 10-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 10-2', 'name': 'CCNP SWITCH LAB 10-2'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '88b78400-449d-4492-8c9f-b38d7ee61d5b', 'filename': 'CCNP SWITCH LAB 6-3.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 6-3', 'name': 'CCNP SWITCH LAB 6-3'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '82e54090-3f6d-42ac-85e3-4fded03a5e45', 'filename': 'CCNP SWITCH LAB 5-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 5-1', 'name': 'CCNP SWITCH LAB 5-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': 'e4aa8693-2f56-4d4b-acd8-5a6381630271', 'filename': 'CCNP SWITCH LAB 7-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 7-2', 'name': 'CCNP SWITCH LAB 7-2'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': 'eab61d4c-21a9-4cd5-af83-d899c8b25d63', 'filename': 'CCNP SWITCH LAB 3-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 3-2', 'name': 'CCNP SWITCH LAB 3-2'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '1b3b9148-3893-4fc4-b6e4-6799f02b65bd', 'filename': 'CCNP SWITCH LAB 8-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 8-1', 'name': 'CCNP SWITCH LAB 8-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '48c21eec-a1e4-4c58-8bdb-0f7675869fa5', 'filename': 'CCNP SWITCH LAB 4-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 4-1', 'name': 'CCNP SWITCH LAB 4-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '3388c09f-839a-4d28-abe6-e739d3f3ffa0', 'filename': 'CCNP SWITCH LAB 6-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 6-1', 'name': 'CCNP SWITCH LAB 6-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '36506c73-aa5d-4862-8bd4-7834dde48b78', 'filename': 'CCNP SWITCH LAB 4-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 4-2', 'name': 'CCNP SWITCH LAB 4-2'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': 'ec02956d-2102-44b0-9bf4-f1d21b93aaa3', 'filename': 'CCNP SWITCH LAB 3-1.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 3-1', 'name': 'CCNP SWITCH LAB 3-1'}, {'scene_height': 1000, 'scene_width': 2000, 'auto_start': False, 'status': 'closed', 'auto_close': True, 'project_id': '30da0029-a791-4f18-8487-0c57a2ae51e5', 'filename': 'CCNP SWITCH LAB 6-2.gns3', 'auto_open': False, 'path': '/opt/gns3/projects/CCNP SWITCH LAB 6-2', 'name': 'CCNP SWITCH LAB 6-2'}]

**Comment by noplay** [comment]
Thanks a lot for testing before I asked you :D I removed also the debug you see in the console.
