### ISSUE TITLE
Something wrong with packet capture on IOU

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1727]
I do a packet capture on a link and try a stop all the nodes (stop all button). One of the IOU node shows it is still running in the GUI (the one where the packet capture is active).

![blocked_stop](https://cloud.githubusercontent.com/assets/4752614/21299895/e72f15fa-c5f3-11e6-83cb-3f660a5a5631.png)

However, if I move the IOU node then a message appears and the node shows it is stopped.

![blocked_stop_2](https://cloud.githubusercontent.com/assets/4752614/21299902/f52abe48-c5f3-11e6-879f-bbab586a72b1.png)

Now if I try to stop the capture on the link, I see the "Cannot capture traffic on a non started VM" message.

PS: we should investigate if there is the same problem with other node types.

**Comment by noplay** [comment]
I think it's similar to the bug I solved with Docker container restarting when you move it: https://github.com/GNS3/gns3-server/issues/832

**Comment by noplay** [comment]
I don't see why we disallow capture on a non running IOU. It seem the code support capture on a non running node
