### ISSUE TITLE
[enhancement request] If it is possible that to add the vbox equipment as qemu equipment?

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#173]
One qemu equipment can add many times instances for one project.
but one virtualbox equipment can only add once , 
So at this moment we must copy many virtualbox equipments and add into gns3 for one project.
Can we make the vbox equipment as the qemu equipment ?
Only setup for one time ,and can be added to project many instances for one project?

**Comment by grossmj** [comment]
It's still experimental (because of a bug on the VirtualBox side).
