### ISSUE TITLE
Odd behavior after GNS3 VM menu upgrade option used

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1734]
GNS3-2.0.2016-12-17 and GNS3-2.0.0.b2
VMware Workstation Pro 12.5.2 on Windows 10 Pro 64bit

When I run the Upgrade GNS3 VM option:
![beforeupgrade](https://cloud.githubusercontent.com/assets/10285348/21395343/2167358c-c76a-11e6-95c0-fb120246cea5.png)
After the "upgrade" is complete GNS3 VM looks like this:
![afterupgrade](https://cloud.githubusercontent.com/assets/10285348/21395374/3e33e7be-c76a-11e6-870d-9316d017620a.png)

The GNS3 VM is a result of a full clone of the previous functional version of a GNS3 VM I was using successfully.
Hope this makes sense.  So, what am I doing wrong here?
Thanks!

**Comment by nrafia** [comment]
please merge with 1735, both are same issue. This is appearing upgrade is not successful.

**Comment by jtorri** [comment]
The above error does not occur if I use the GNS3 VM downloaded with GNS3 2.0.0b2.  So....I am guessing some code has changed on the server side used to for upgrade download.  
Also, it seems pretty reasonable you folks are taking time off to enjoy the holidays and rightly ignoring those of us too silly not to do so.  So, Happy Holidays!  Catch you later!

**Comment by jtorri** [comment]
Just an FYI.  Once I used the GNS3 VM downloaded with the GNS3 2.0.0 beta 2 project to build a new GNS3 VM, all worked fine.  Thanks.

**Comment by noplay** [comment]
Fixed
