### ISSUE TITLE
2.0 beta 2 upgrade issue

### ISSUE THREAD

**Issue by nrafia** [GNS3/gns3-gui#1735]
Hi,
I have just tried to upgrade my GNS3 VM to beta 2 from beta 1 and getting following error...

![image](https://cloud.githubusercontent.com/assets/20077392/21395641/ac753dc6-c7b6-11e6-958f-52e70c311db7.png)

**Comment by grossmj** [comment]
Upgrading the VM is still problematic. I broken mine:

![broken_vm](https://cloud.githubusercontent.com/assets/4752614/21669515/5bdd9a38-d347-11e6-9127-33aac81e0cee.png)

gns3restore didn't help.

**Comment by noplay** [comment]
What is the permissions of your /var/log/upstart/gns3.log ?

**Comment by grossmj** [comment]
Hum, I got it working by upgrading again... it finally worked but that was painful.

**Comment by noplay** [comment]
Fixed
