### ISSUE TITLE
[2.0] : Bug : all interfaces of VMBox are up

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1736]
Hi

I put a Linux VMBox connected to one ethernet switch.

After start the VM, i see the interfaces connected with a link (linux command : sudo mii-tool)
All interfaces are connected. Only one must be

**Comment by grossmj** [comment]
This must be because in 2.0 we connect all interfaces with UDP tunnels to uBridge. Not sure this is a bug, need to investigate if there is something we can do.

**Comment by Raizo62** [comment]
This is very problematic : the OS will not show the real situation. It is not realistic

**Comment by Raizo62** [comment]
(Happy new years :-) )

Just an idea : could you not just use the option of each card in VBox : "Cable connected" ? you enable it when a cable is connected. I suppose that you have not need to change anything on ubridge.
But, you have always the same bug with Cisco router : "show ip interface brief" shows "up" on protocol even if the cable is not connected (But, i have already the same with GNS3 1.5 on last release of Live Raizo v7)

**Comment by grossmj** [comment]
Good idea :+1: Fixed in https://github.com/GNS3/gns3-server/commit/c9fc0a0d6d6c405a8eec52b3924d9c2c34dae8ed

**Comment by Raizo62** [comment]
(I don't have tested).
Could you do something for the same problem with Cisco Router ?

**Comment by grossmj** [comment]
I think only VirtualBox supports it.
