### ISSUE TITLE
Unable to start GNS3 after installation

### ISSUE THREAD

**Issue by karthikvee** [GNS3/gns3-gui#1737]
I've installed & used GNS3 for few days later on when I'm starting gns3 from command line using the command:
`$ gns &`
gns3 is throwing me the following error:
```
Copyright (c) 2007-2016 GNS3 Technologies Inc.
your locale en_IN.ISO8859-1 encoding is not UTF-8, switching to the UTF-8 version...
/usr/share/gns3/gns3-gui/bin/python: symbol lookup error: /usr/local/lib/libQt5DBus.so.5: undefined symbol: _Z28qEnvironmentVariableIntValuePKcPb
```
Any help in resolving the issue is appreciated. Is it a bug, if so what is the work around for this issue?

For more details also look at: [Question On Stackexchange](http://unix.stackexchange.com/q/332414/189690)
@noplay @grossmj

**Comment by noplay** [comment]
Hi,

You need to install qt5 from the package. Actually you have a broken version in /usr/local/lib
