### ISSUE TITLE
[2.0.0b2] Project already exists

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1739]
Hi,
GNS3 2.0.0b2 does not allow to overwrite a project:
If you try creating a project with the same name you will get a popup and the following log message:
_Project name "project-name" already exists_

I believe it is unexpected behaviour.

**Comment by grossmj** [comment]
Looks like it is the same issue as https://github.com/GNS3/gns3-gui/issues/1743

**Comment by noplay** [comment]
Yes seem duplicate of #1743
