### ISSUE TITLE
[2.0] Bugs : overwrite project

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1743]
reHi

- I create a project "untitled" (in /home/user)
- I close GNS3
- I start GNS3 and use the same name of project.
- GNS3 asks to overwrite. I accept. But i have this error message : 
`CRITICAL __init__.py:110 Error while overwrite project: Project ID f4a69859-74bf-4db5-a219-04adb62e183f doesn't exist`

**Comment by noplay** [comment]
Fixed thanks
