### ISSUE TITLE
[2.0.0b2] [Bug] Ports on Ethernet Switch shown as available

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1744]
Hi,
I use GNS3 on remote server.
There is no indication on Ethernet Switch if the port is free or not, it is always shown as free, but when you try connecting a link on it, you will get a console message: "Error while creating link: Port 0 isn't free".
Please refer to the screenshot below:
<img width="425" alt="screen shot 2016-12-25 at 11 27 26" src="https://cloud.githubusercontent.com/assets/1923704/21470710/9815ac4e-ca95-11e6-8b25-fd6f182a85b1.png">
After I deleted link and added again, it is now working fine.

**Comment by noplay** [comment]
Hi,

Thanks for the report.

Which version of GNS3 are you using? I didn't manage to replicate it with current 2.0 dev version.

Best regards

Julien

**Comment by noplay** [comment]
Do you reproduce it everytime?

**Comment by dmfigol** [comment]
Nope, it is not reproducible every time. I will try finding a trigger for this.

**Comment by noplay** [comment]
I confirm it's bug #1759
