### ISSUE TITLE
[2.0.0b2] [Bug] Export config for IOL is broken

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1745]
Hi,
after I finished working on my current project I did "wr" on all IOL nodes. Then I stopped the project.
I did **Tools -> Import/Export Node configs -> Export** and then I checked exported configs and they are default configs containing the template "hostname %h ...". The same config is in .gns3 file. I have checked the files directly on my remote server and in the node folder I see new startup-config.cfg which is correct.
In 1.5.x I was also doing "save project" after I stop the project, however "save" was removed as it should be automatic in 2.x if I understood correctly.
Please note that I have tested this only with IOL, the bug may be applicable to non-IOL images as well.
Thanks!

**Comment by noplay** [comment]
It seem the startup config is not dumped on disk

**Comment by noplay** [comment]
Fixed it was a double issue:
* delay too long before checking if something changed
* sync issues
