### ISSUE TITLE
CSR1000v, IOSv, IOSvL2 configuration save issues in version 2.0.0 Beta 2

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#1746]
I have setup CSR1000v, IOSv, IOSvL2 in version 2.0.0 beta 2 with VIRL images but none will save the configuration.  The VMs reset to default when a saved project is opened or reload.  Any help to resolve this issue?

**Comment by grossmj** [comment]
Need to investigate this.

**Comment by grossmj** [comment]
I tested with 2 IOSvL2 running in the GNS3 VM and did not found any problem.

Can you confirm you saved the config in IOS?

**Comment by fatbell** [comment]
I tried again in my setup and was still having the same issue.  I uninstall the all the VMs and did a complete install.  Its now working perfectly as expected.  Thank you very much for your time.

**Comment by grossmj** [comment]
Thanks for the confirmation.

**Comment by fatbell** [comment]
Jeremy,


I did not want to create another ticket on IOSvL2 so I decided to send this email to draw your attention to VLAN database issue on IOSvL2.  I created 5 VLANs moved interfaces into the VLANs on IOSvL2.  I saved the configs and closed the project.  When re-opened the project the "switchport access vlan xx" command on the interface were all deleted.  I have attached some files for easy of reference.  Please let me know if you need any additional files.  Thank you very much for your time and effort.


Nana

________________________________

**Comment by noplay** [comment]
What is the exact image you are using? That sound like something not supported by the image.

**Comment by fatbell** [comment]
Below is the image. 
vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E

[IOSvL2 - boot process output.txt](https://github.com/GNS3/gns3-gui/files/693114/IOSvL2.-.boot.process.output.txt)

**Comment by grossmj** [comment]
@noplay there may be an issue installing vIOSL2 via an appliance file (with the image left in my downloads folder). I get the following message when a try to use the freshly installed appliance.

```
Server error from xps13: Error while setting up node: The image vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E is missing
Error while setting up node: The image vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E is missing
```

Can you test on your side?

**Comment by grossmj** [comment]
I've tested (added some VLANs, save, close GNS3 and reopened the project) and haven't found anything wrong on my side. I've the exact same image.

```
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Version 15.2(4.0.55)E, TEST ENGINEERING ESTG_WEEKLY BUILD, synced to  END_OF_FLO_ISP
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Tue 28-Jul-15 18:52 by sasyamal


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco IOSv () processor (revision 1.0) with 574841K/209920K bytes of memory.
Processor board ID 9UZBNTKZZVG
16 Gigabit Ethernet interfaces
DRAM configuration is 72 bits wide with parity disabled.
256K bytes of non-volatile configuration memory.
2097144K bytes of ATA System CompactFlash 0 (Read/Write)
0K bytes of ATA CompactFlash 1 (Read/Write)
0K bytes of ATA CompactFlash 2 (Read/Write)
0K bytes of ATA CompactFlash 3 (Read/Write)



Press RETURN to get started!


*Mar  1 00:00:00.315: %ATA-6-DEV_FOUND: device 0x1F0
*Mar  1 00:00:00.417: %NVRAM-5-CONFIG_NVRAM_READ_OK: NVRAM configuration 'flash:/nvram' was read from disk.
*Jan 12 09:38:31.664: %SPANTREE-5-EXTENDED_SYSID: Extended SysId enabled for type vlan
*Jan 12 09:38:33.353: %LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to reset
*Jan 12 09:38:33.353: %LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to reset
*Jan 12 09:38:33.353: %LINK-5-CHANGED: Interface GigabitEthernet0/2, changed state to reset
*Jan 12 09:38:33.353: %LINK-5-CHANGED: Interface GigabitEthernet0/3, changed state to reset
*Jan 12 09:38:33.354: %LINK-5-CHANGED: Interface GigabitEthernet1/0, changed state to reset
*Jan 12 09:38:33.354: %LINK-5-CHANGED: Interface GigabitEthernet1/1, changed state to reset
*Jan 12 09:38:33.354: %LINK-5-CHANGED: Interface GigabitEthernet1/2, changed state to reset
*Jan 12 09:38:34.489: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/0, changed state to up
*Jan 12 09:38:34.489: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up
*Jan 12 09:38:34.489: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/2, changed state to up
*Jan 12 09:38:34.489: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/3, changed state to up
*Jan 12 09:38:34.489: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/0, changed state to up
*Jan 12 09:38:34.490: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/1, changed state to up
*Jan 12 09:38:34.490: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/2, changed state to up
*Jan 12 09:38:34.490: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/3, changed state to up
*Jan 12 09:38:34.490: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/0, changed state to up
*Jan 12 09:38:34.490: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/1, changed state to up
*Jan 12 09:38:35.518: %LINK-3-UPDOWN: Interface GigabitEthernet3/3, changed state to up
*Jan 12 09:38:35.518: %LINK-3-UPDOWN: Interface GigabitEthernet3/2, changed state to up
*Jan 12 09:38:35.518: %LINK-3-UPDOWN: Interface GigabitEthernet3/1, changed state to up
*Jan 12 09:38:35.518: %LINK-3-UPDOWN: Interface GigabitEthernet3/0, changed state to up
*Jan 12 09:38:35.518: %LINK-3-UPDOWN: Interface GigabitEthernet2/3, changed state to up
*Jan 12 09:38:35.519: %LINK-3-UPDOWN: Interface GigabitEthernet2/2, changed state to up
*Jan 12 09:38:35.519: %LINK-3-UPDOWN: Interface GigabitEthernet2/1, changed state to up
*Jan 12 09:38:35.519: %LINK-3-UPDOWN: Interface GigabitEthernet2/0, changed state to up
*Jan 12 09:38:35.519: %LINK-3-UPDOWN: Interface GigabitEthernet1/3, changed state to up
*Jan 12 09:38:35.519: %LINK-3-UPDOWN: Interface GigabitEthernet1/2, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet1/1, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet1/0, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet0/3, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
*Jan 12 09:38:35.721: %LINK-3-UPDOWN: Interface GigabitEthernet0/0, changed state to up
*Jan 12 09:38:50.413: %PLATFORM-5-SIGNATURE_VERIFIED: Image 'flash0:/vios_l2-adventerprisek9-m' passed code signing verification
```

Comparing with your boot log noticed that you don't have this:

```
*Mar  1 00:00:00.315: %ATA-6-DEV_FOUND: device 0x1F0
*Mar  1 00:00:00.417: %NVRAM-5-CONFIG_NVRAM_READ_OK: NVRAM configuration 'flash:/nvram' was read from disk.
```

Maybe there is something wrong when your node loads the NVRAM.

Can you show me what you have using the following command?

```
SW1#show file systems 
File Systems:

     Size(b)     Free(b)      Type  Flags  Prefixes
*   2142715904    2030166016      disk     rw   flash0: flash:
           -           -      disk     rw   flash1:
           -           -      disk     rw   flash2:
           -           -      disk     rw   flash3:
           -           -    opaque     rw   system:
           -           -    opaque     rw   tmpsys:
        262144        257408     nvram     rw   nvram:
           -           -    opaque     rw   null:
           -           -    opaque     ro   tar:
           -           -   network     rw   tftp:
           -           -    opaque     wo   syslog:
           -           -   network     rw   rcp:
           -           -   network     rw   http:
           -           -   network     rw   ftp:
           -           -   network     rw   scp:
           -           -   network     rw   https:
           -           -    opaque     ro   cns:

SW1#
```

**Comment by fatbell** [comment]
This is the complete boot log


                             GNU GRUB  version 2.00

 +--------------------------------------------------------------------------+
 |IOSv: flash0:vios_l2-adventerprisek9-m (hd0,msdos1)                       | 
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          |
 |                                                                          | 
 +--------------------------------------------------------------------------+

      Use the ^ and v keys to select which entry is highlighted.      
      Press enter to boot the selected OS, `e' to edit the commands      
      before booting or `c' for a command-line. ESC to return      
      previous menu.      
   The highlighted entry will be executed automatically in 0s.
                                                                               
  Booting `IOSv: flash0:vios_l2-adventerprisek9-m (hd0,msdos1)'

Booted IOSv. Boot args: [/vios_l2-adventerprisek9-m]

Smart Init is enabled

              Restricted Rights Legend

Use, duplication, or disclosure by the Government is
subject to restrictions as set forth in subparagraph
(c) of the Commercial Computer Software - Restricted
Rights clause at FAR sec. 52.227-19 and subparagraph
(c) (1) (ii) of the Rights in Technical Data and Computer
Software clause at DFARS sec. 252.227-7013.

           cisco Systems, Inc.
           170 West Tasman Drive
           San Jose, California 95134-1706



Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Version 15.2(4.0.55)E, TEST ENGINEERING ESTG_WEEKLY BUILD, synced to  END_OF_FLO_ISP
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Tue 28-Jul-15 18:52 by sasyamal


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco IOSv () processor (revision 1.0) with 574721K/209920K bytes of memory.
Processor board ID 9S3G1OG9OA0
16 Gigabit Ethernet interfaces
DRAM configuration is 72 bits wide with parity disabled.
256K bytes of non-volatile configuration memory.
2097144K bytes of ATA System CompactFlash 0 (Read/Write)
0K bytes of ATA CompactFlash 1 (Read/Write)
0K bytes of ATA CompactFlash 2 (Read/Write)
0K bytes of ATA CompactFlash 3 (Read/Write)

% Access vlan 200 does not exist
% Access vlan 300 does not exist
% Access vlan 400 does not exist
% Access vlan 500 does not exist


Press RETURN to get started!


*Mar  1 00:00:06.523: %ATA-6-DEV_FOUND: device 0x1F0
*Mar  1 00:00:08.055: %NVRAM-5-CONFIG_NVRAM_READ_OK: NVRAM configuration 'flash:/nvram' was read from disk.
*Jan 12 10:12:08.224: %SPANTREE-5-EXTENDED_SYSID: Extended SysId enabled for type vlan
*Jan 12 10:12:35.883: %LINK-5-CHANGED: Interface GigabitEthernet0/0, changed state to reset
*Jan 12 10:12:35.886: %LINK-5-CHANGED: Interface GigabitEthernet0/1, changed state to reset
*Jan 12 10:12:35.888: %LINK-5-CHANGED: Interface GigabitEthernet0/2, changed state to reset
*Jan 12 10:12:35.889: %LINK-5-CHANGED: Interface GigabitEthernet0/3, changed state to reset
*Jan 12 10:12:35.891: %LINK-5-CHANGED: Interface GigabitEthernet1/0, changed state to reset
*Jan 12 10:12:35.896: %LINK-5-CHANGED: Interface GigabitEthernet1/1, changed state to reset
*Jan 12 10:12:35.897: %LINK-5-CHANGED: Interface GigabitEthernet1/2, changed state to reset
*Jan 12 10:12:37.485: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/0, changed state to up
*Jan 12 10:12:37.486: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up
*Jan 12 10:12:37.486: %LIN
-Traceback= 1DBB7C8z 8DBFE5z 90522Ez 904F50z 904D5Dz 900F45z 901B7Bz 901B0Fz 8DBE11z 8DA47Ez 8DA425z 1CB3472z 1CC90B9z 1CC8E69z 1CC8B9Cz 1CC8A00z - Process "TTY Background", CPU hog, PC 0x008DB823
EPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/2, changed state to up
*Jan 12 10:12:37.492: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/3, changed state to up
*Jan 12 10:12:37.496: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/0, changed state to up
*Jan 12 10:12:37.497: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/1, changed state to up
*Jan 12 10:12:37.500: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/2, changed state to up
*Jan 12 10:12:37.501: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/3, changed state to up
*Jan 12 10:12:37.502: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/0, changed state to up
*Jan 12 10:12:37.507: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet2/1, changed state to up
*Jan 12 10:12:39.152: %LINK-3-UPDOWN: Interface GigabitEthernet3/3, changed state to up
*Jan 12 10:12:39.160: %LINK-3-UPDOWN: Interface GigabitEthernet3/2, changed state to up
*Jan 12 10:12:39.173: %LINK-3-UPDOWN: Interface GigabitEthernet3/1, changed state to up
*Jan 12 10:12:39.179: %LINK-3-UPDOWN: Interface GigabitEthernet3/0, changed state to up
*Jan 12 10:12:39.192: %LINK-3-UPDOWN: Interface GigabitEthernet2/3, changed state to up
*Jan 12 10:12:39.199: %LINK-3-UPDOWN: Interface GigabitEthernet2/2, changed state to up
*Jan 12 10:12:39.205: %LINK-3-UPDOWN: Interface GigabitEthernet2/1, changed state to up
*Jan 12 10:12:39.218: %LINK-3-UPDOWN: Interface GigabitEthernet2/0, changed state to up
*Jan 12 10:12:39.230: %LINK-3-UPDOWN: Interface GigabitEthernet1/3, changed state to up
*Jan 12 10:12:39.240: %LINK-3-UPDOWN: Interface GigabitEthernet1/2, changed state to up
*Jan 12 10:12:39.249: %LINK-3-UPDOWN: Interface GigabitEthernet1/1, changed state to up
*Jan 12 10:12:39.256: %LINK-3-UPDOWN: Interfac
-Traceback= 1DBB7C8z 8DBFE5z 90522Ez 904F50z 904D5Dz 900F45z 901B7Bz 901B0Fz 8DBE11z 8DA47Ez 8DA425z 1CB3472z 1CC90B9z 1CC8E69z 1CC8B9Cz 1CC8A00z - Process "TTY Background", CPU hog, PC 0x008DB823
e GigabitEthernet1/0, changed state to up
*Jan 12 10:12:39.261: %LINK-3-UPDOWN: Interface GigabitEthernet0/3, changed state to up
*Jan 12 10:12:39.403: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
*Jan 12 10:12:39.413: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
*Jan 12 10:12:39.421: %LINK-3-UPDOWN: Interface GigabitEthernet0/0, changed state to up
*Jan 12 10:12:43.647: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/1, changed state to down
*Jan 12 10:12:43.655: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/2, changed state to down
*Jan 12 10:12:46.566: %SYS-5-CONFIG_I: Configured from memory by console
*Jan 12 10:12:47.130: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan200, changed state to down
*Jan 12 10:12:47.135: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan300, changed state to down
*Jan 12 10:12:47.138: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan400, changed state to down
*Jan 12 10:12:47.143: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan500, changed state to down
*Jan 12 10:13:13.954: %SYS-5-RESTART: System restarted --
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Version 15.2(4.0.55)E, TEST ENGINEERING ESTG_WEEKLY BUILD, synced to  END_OF_FLO_ISP
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Tue 28-Jul-15 18:52 by sasyamal
*Jan 12 10:13:16.230: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/1, changed state to up
*Jan 12 10:13:16.254: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet1/2, changed state to up
*Jan 12 10:13:17.219: %LINK-3-UPDOWN: Interface Vlan200, changed state to up
*Jan 12 10:13:17.224: %LINK-3-UPDOWN: Interface Vlan300, changed state to up
*Jan 12 10:13:17.234: %LINK-3-UPDOWN: Interface Vlan400, changed state to up
*Jan 12 10:13:17.243: %LINK-3-UPDOWN: Interface Vlan500, changed state to up
*Jan 12 10:13:18.742: %LINEPROTO-5-U
-Traceback= 1DBB7C8z 8DBFE5z 90522Ez 904F50z 904D5Dz 900F45z 901B7Bz 901B0Fz 8DBE11z 8DA47Ez 8DA425z 1CC8F02z 1CC8B9Cz 1CC8A00z 1CC89B3z - Process "TTY Background", CPU hog, PC 0x008DB823
PDOWN: Line protocol on Interface Vlan200, changed state to up
*Jan 12 10:13:18.751: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan300, changed state to up
*Jan 12 10:13:18.762: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan400, changed state to up
*Jan 12 10:13:18.765: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan500, changed state to up
*Jan 12 10:13:21.082: %SYS-3-CPUHOG: Task is running for (1999)msecs, more than (2000)msecs (0/0),process = TTY Background.
*Jan 12 10:13:24.530: %SYS-3-CPUHOG: Task is running for (1997)msecs, more than (2000)msecs (0/0),process = TTY Background.
*Jan 12 10:13:28.270: %SYS-3-CPUHOG: Task is running for (1999)msecs, more than (2000)msecs (0/0),process = TTY Background.
**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
**************************************************************************

And the show commands requested

USER-Switch#sh file systems 
File Systems:

     Size(b)     Free(b)      Type  Flags  Prefixes
*   2142715904    2030166016      disk     rw   flash0: flash:
           -           -      disk     rw   flash1:
           -           -      disk     rw   flash2:
           -           -      disk     rw   flash3:
           -           -    opaque     rw   system:
           -           -    opaque     rw   tmpsys:
        262144        256959     nvram     rw   nvram:
           -           -    opaque     rw   null:
           -           -    opaque     ro   tar:
           -           -   network     rw   tftp:
           -           -    opaque     wo   syslog:
           -           -   network     rw   rcp:
           -           -   network     rw   http:
           -           -   network     rw   ftp:
           -           -   network     rw   scp:
           -           -   network     rw   https:
           -           -    opaque     ro   cns:



USER-Switch#dir flash:
Directory of flash0:/

    1  drw-           0  Jan 30 2013 00:00:00 +00:00  boot
  264  drw-           0  Oct 14 2013 00:00:00 +00:00  config
  267  -rw-   107412732  Jul 28 2015 00:00:00 +00:00  vios_l2-adventerprisek9-m
  268  -rw-      524288   Jan 8 2017 04:43:42 +00:00  nvram
  269  -rw-         856   Jan 8 2017 04:56:38 +00:00  vlan.dat
  270  -rw-         325  Jan 12 2017 09:33:50 +00:00  e1000_bia.txt

2142715904 bytes total (2030166016 bytes free)

**Comment by grossmj** [comment]
Hi,

Hum, everything looks normal.

Can you send me your startup-config before you close the project and loose the "switchport access vlan xx" commands?

Thanks,

**Comment by fatbell** [comment]
I'm sending you both the startup-config and running-config.  I don't know why the "switchport access vlan xx" command get deleted.  Please see below


USER-Switch#sh startup-config 
Using 2056 out of 262144 bytes, uncompressed size = 4448 bytes
!
! Last configuration change at 09:32:26 UTC Thu Jan 12 2017
!
version 15.2
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
service compress-config
!
hostname USER-Switch
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!
!         
!
!
ip domain-name localdomain.com
ip cef
no ipv6 cef
!
!
!
spanning-tree mode rapid-pvst
spanning-tree extend system-id
!
vlan internal allocation policy ascending
!
! 
!
!
!
!
!
!
!
!
!         
!
!
!
interface GigabitEthernet0/0
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/1
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/2
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/3
 media-type rj45
 negotiation auto
!
interface GigabitEthernet1/0
 media-type rj45
 negotiation auto
!         
interface GigabitEthernet1/1
 switchport trunk allowed vlan 1,2,200,300,400,500,962,1001-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet1/2
 switchport trunk allowed vlan 1,2,200,300,400,500,962,1001-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet1/3
 media-type rj45
 negotiation auto
!
interface GigabitEthernet2/0
 switchport access vlan 200
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/1
 switchport access vlan 300
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/2
 switchport access vlan 400
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/3
 switchport access vlan 500
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet3/0
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/1
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/2
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/3
 media-type rj45
 negotiation auto
!
interface Vlan200
 no ip address
!
interface Vlan300
 no ip address
!
interface Vlan400
 no ip address
!
interface Vlan500
 no ip address
==========================================================

USER-Switch#sh running-config 
Building configuration...

Current configuration : 4336 bytes
!
! Last configuration change at 14:14:10 UTC Thu Jan 12 2017
!
version 15.2
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
service compress-config
!
hostname USER-Switch
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!         
!
!
!
ip domain-name localdomain.com
ip cef
no ipv6 cef
!
!
!
spanning-tree mode rapid-pvst
spanning-tree extend system-id
!
vlan internal allocation policy ascending
!
! 
!
!
!
!
!
!
!
!         
!
!
!
!
interface GigabitEthernet0/0
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/1
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/2
 media-type rj45
 negotiation auto
!
interface GigabitEthernet0/3
 media-type rj45
 negotiation auto
!
interface GigabitEthernet1/0
 media-type rj45
 negotiation auto
!
interface GigabitEthernet1/1
 switchport trunk allowed vlan 1,2,200,300,400,500,962,1001-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet1/2
 switchport trunk allowed vlan 1,2,200,300,400,500,962,1001-1005
 switchport trunk encapsulation dot1q
 switchport mode trunk
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet1/3
 media-type rj45
 negotiation auto
!
interface GigabitEthernet2/0
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/1
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/2
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet2/3
 switchport mode access
 media-type rj45
 duplex full
 no negotiation auto
!
interface GigabitEthernet3/0
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/1
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/2
 media-type rj45
 negotiation auto
!
interface GigabitEthernet3/3
 media-type rj45
 negotiation auto
!
interface Vlan200
 no ip address
!
interface Vlan300
 no ip address
!
interface Vlan400
 no ip address
!
interface Vlan500
 no ip address

**Comment by grossmj** [comment]
I cannot reproduce that issue :(
 
I create a new vIOS-L2 node, start it, apply your startup-config, save, close GNS3, re-open GNS3, load the project and start the node. Everything is there.

**Comment by fatbell** [comment]
Thanks for your time.  It might be one-of case so you case close the case.

**Comment by grossmj** [comment]
Hopefully this is not blocking you.

Thanks.

**Comment by roger-max** [comment]
Hi,

I am facing the same issue as well. Anyone can offer help please?

Below is my problem:
•I have a few VLANS created with switchports assigned to those vlans.
•copy run start to save my configuration.
•I save my project from within GNS3
•I stop my node.
•I restart node
•show vlan br, the assignments are no longer part of the config.

Am using IOSvL2.vmdk that I downloaded from internet

**Comment by roger-max** [comment]
I read other post below:

https://gns3.com/qa/cisco-iosvl2-switchport-assignme

I followed the instruction but not working. Appreciate if anyone can help to solve this issue permanently. Many thanks.
