### ISSUE TITLE
[REQ] Qemu and SATA drives

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1749]
Hi,
I wonder if it would be possible to add SATA controller option under Qemu emulator? The reason is that some images take too long to load via IDE. A great example is NX-OSv9000 which loads the image for several minutes via IDE, but only a few seconds with SATA controller (tested in VMware). 
![0267](https://cloud.githubusercontent.com/assets/24818591/21536978/5a11fa78-cdde-11e6-83f7-3ba2721f73c3.jpg)

According to page 31 of the below document it is possible – they even provided examples of the commands. However I failed with all my attempts as I do not have sufficient know age of Qemu. 
http://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/nx-osv/configuration/guide/b_NX-OSv_9000.pdf 

Thank you 
Sairus

**Comment by sairuscz** [comment]
Related/duplicate. https://github.com/GNS3/gns3-server/issues/850

**Comment by ehlers** [comment]
I don't get the idea, why you added "sata". On qemu 2.7 this results in this message:
`qemu-system-i386: -drive file=/opt/gns3/projects/45dabb11-4b38-4c7d-8a14-52387f6bec48/project-files/qemu/c3f0b18b-177e-470d-b913-037d4156c091/hda_disk.qcow2,if=sata,index=0,media=disk: unsupported bus type 'sata'`

In the attached cisco document they use a "none" disk interface plus some extended configuration to get a sata drive, but in my understanding a simple type SATA doesn't exist in qemu.

**Comment by grossmj** [comment]
Hum, I shouldn't have rushed it. I will remove "sata".

**Comment by ehlers** [comment]
Well, I'm not against adding a sata disk interface, it's just not adding it simply in the GUI. What's needed besides re-adding it in the GUI is to create a special handling for sata in the qemu part of gns3-server's code. An example is shown in the linked Cisco document.

Normally I'm against some special handling, but as sata is the most used disk interface in modern VMs, I think GNS3 should try to directly support that (without adding obscure additional options).

**Comment by grossmj** [comment]
Let's see if we can do as you suggested.

**Comment by grossmj** [comment]
I have added the following code under a new branch: https://github.com/GNS3/gns3-server/commit/e777230205f905789a6ba0d13db26a7cd4016ccb

Tested with a Linux Microcore VM and it worked well switching between ide and sata. Please feel free to test more.

**Comment by noplay** [comment]
Could we merge that?

**Comment by grossmj** [comment]
Yes, I think so. Even if something is wrong, it is not intrusive.

**Comment by noplay** [comment]
Merged

**Comment by cioby23** [comment]
Regarding SATA support I see only the gns3-server part was merged. The sata option is not displayed in the option list for Qemu disk interfaces and I saw there is a branch for SATA support **(sata-qemu)** into gns3-gui which currently is not merged into 2.0 branch.

**Comment by noplay** [comment]
You are right it's now merged
