### ISSUE TITLE
Deleted then recreated links are no longer centered

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1750]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Create a simple project with 2 router and interconnect them:
![conn1](https://cloud.githubusercontent.com/assets/896406/21539567/557fdbe6-cda8-11e6-8ece-bb446b7a703c.png)
Now delete the connection and recreate it. The link is no longer centered but slightly off.
![conn2](https://cloud.githubusercontent.com/assets/896406/21539566/557f7ba6-cda8-11e6-93aa-84c68e9b0238.png)
Repeat the deletion/recreation several times, the link is placed more and more outside the center.
![conn3](https://cloud.githubusercontent.com/assets/896406/21539565/557f6a3a-cda8-11e6-9d79-4bef4161ec12.png)
![conn4](https://cloud.githubusercontent.com/assets/896406/21539568/557fd3c6-cda8-11e6-99b7-01e07650f5e6.png)
![conn5](https://cloud.githubusercontent.com/assets/896406/21539564/557f73d6-cda8-11e6-9027-1e3cbad15b63.png)

**Comment by noplay** [comment]
Thanks it's fixed
