### ISSUE TITLE
If cloud interface is down the project doesn't open

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1751]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Create a simple project.
![project](https://cloud.githubusercontent.com/assets/896406/21541356/e63b7e76-cdb5-11e6-9bf1-00c83d83ea61.png)

Then close GNS3 and disconnect the ethernet cable from the cloud interface. Now start GNS3 and open the project.

It only shows an error "Interface en0 don't have a netmask", but the project is not opened. So the user has no change to have a look at the project, see what's wrong and correct the problem.

Furthermore the error message is technically correct, but a bit misleading. I recommend something like "Interface en0 has no netmask, interface down?".

**Comment by ehlers** [comment]
I see the problem. When you "auto-correct" it, that means deleting all erroneous elements, the user could lose quite a lot, without knowing exactly what. Keeping the errors would introduce a difficult to handle project state. And the current situation to lock out the user on errors is also not a good solution.

Well maybe we have to keep it the current way and then wait for the user feedback.

**Comment by noplay** [comment]
What do you think @grossmj ?

**Comment by noplay** [comment]
And if we consider the cloud as node we can start/stop? We could raise the error when the node start allowing user to fix the problem.

**Comment by noplay** [comment]
The solution we will implement.

* Cloud is node started by default.
* You can't stop it
* If we have an error the node is stopped

**Comment by noplay** [comment]
Fixed
