### ISSUE TITLE
Interface label of cloud interface incorrect

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1752]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The interface label of a cloud interface shows something like e0/0, instead the real interface name should be shown.
![project](https://cloud.githubusercontent.com/assets/896406/21541567/cde4a864-cdb7-11e6-919a-349f3cf94e99.png)

**Comment by noplay** [comment]
Fixed thanks for the report
