### ISSUE TITLE
Resume does not work correctly

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1754]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Put two dynamips router in a topology, start them, create the console connections, then suspend one:
![suspend](https://cloud.githubusercontent.com/assets/896406/21556774/ede59e5e-ce23-11e6-87be-d4f336141d58.png)
Looks fine, the console connection of the suspended router doesn't react on user input.

When resuming the router (using Start) the console connection reacts again, but the status of the links remains yellow (suspended). Another suspend request on that device doesn't work anymore.

**Comment by noplay** [comment]
Thanks it's fixed
