### ISSUE TITLE
[2.0.0b2] [Bug] Add appliance - Create a new version fails

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1755]
Hi,
if you create a new version from the template, after uploading the image Status column will still show **Missing** and it is not possible to proceed in the wizard.
Steps to reproduce:
1. Download a new CSR image from Cisco website, for example:
_csr1000v-universalk9.16.04.01-serial.qcow2_
2. Create new version, let's say with Version name 16.4.1
3. It will require the file:
_csr1000v-universalk9.016.4.1.00.S.156-1.S-ext.qcow2_
4. Upload the file that we have downloaded from Cisco: _csr1000v-universalk9.16.04.01-serial.qcow2_
5. Upload finishes, file is on VM, but Wizard still shows **Missing**

I suspect that the problem is on step 3, where it expects the specific filename. I looked into Appliance file itself and there isn't a field which specifies a filename format with {}, so it must be done internally in the code.
It seems that the problem is here:
https://github.com/GNS3/gns3-gui/blob/3aa9ed61c6d637cbf7f8b2680a8ee7920fad726e/gns3/registry/appliance.py#L122
`filename = filename.replace(ref['images'][disk_type]['version'], version_name)`
where we replace the version in the filename, for example:
_"filename": "csr1000v-universalk9.0**3.17**.00.S.156-1.S-ext.qcow2"_
The original version: _"version": "3.17"_
The new version: _"version": "16.4.1"_
This replacement will provide a new filename: _"csr1000v-universalk9.0**16.4.1**.00.S.156-1.S-ext.qcow2"_ which is simply wrong.

I believe that for "create a new version" option, it should use the filename of the uploaded file.

**Comment by noplay** [comment]
I will check.
