### ISSUE TITLE
[2.0] [Bug] : connected link on Ethernet switch

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1756]
Hi

- I connect a device to the interface Ethernet0 of "Ethernet switch"
- I want connect another device to this switch, but i choose again the Ethernet0 : 
  - my second device is not connected
  - the interface Ethernet0 of switch become free
  - the first device is always connected

**Comment by grossmj** [comment]
Probably same bug as https://github.com/GNS3/gns3-gui/issues/1759
