### ISSUE TITLE
Unable to capture on serial interface in 2.0 Beta 2

### ISSUE THREAD

**Issue by dschuemann** [GNS3/gns3-gui#1758]
****** Exception detected, traceback information saved in /.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui/gns3/qt/__init__.py", line 225, in partial
  File "./gns3-gui/gns3/http_client.py", line 599, in _processResponse
gns3.http_client.HttpBadRequest: {
    "message": "Invalid JSON: 'DLT_PPP_SERIAL' is not one of ['DLT_ATM_RFC1483', 'DLT_EN10MB', 'DLT_FRELAY', 'DLT_C_HDLC'] in schema: {\"enum\": [\"DLT_ATM_RFC1483\", \"DLT_EN10MB\", \"DLT_FRELAY\", \"DLT_C_HDLC\"], \"description\": \"PCAP data link type (http://www.tcpdump.org/linktypes.html)\"}",
    "method": "POST",
    "path": "/v2/projects/{project_id}/links/{link_id}/start_capture",
    "request": {
        "capture_file_name": "IOU1_Serial21_to_IOU2_Serial21.pcap",
        "data_link_type": "DLT_PPP_SERIAL"
    },
    "status": 400
}

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/855ab1365505041cb31a7fc21aad3cfa68b113d0

Thanks!
