### ISSUE TITLE
Error when connecting to an already connected interface

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1759]
Unlike version 1.5 we don't seem to prevent an user from connecting a link to an interface that is already connected (this was done on GUI side if I remember correctly). This leads to many small bugs depending on the emulator implementation.

For instance with 2 Qemu VMs:

* Connect the 2 VMs together while they are shutdown.
* Start the 2 VMs.
* Connect one VM with an available interface to the already used interface of the other VM.

The following error message appears: "Error while creating link: bridge 'QEMU-4b5fe15a-a5fe-4972-af70-a17b581ea784-0' already exist".

But worse, the interface that was not free is now marked available in the GUI!

![qemu_link](https://cloud.githubusercontent.com/assets/4752614/21671771/9b423718-d358-11e6-8276-83813bca4589.png)

I think the best is to handle that globally on controller/server side and not in each emulator implementation.

**Comment by noplay** [comment]
Fixed on both side to avoid trouble
