### ISSUE TITLE
GNS3 1.2.2 GUI for windows ,after add iou , it can not see on select node dock

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#176]
OS: win7
server: ubuntu 14.10
After add the iou on GNS3 1.2.2 gui for windows, 
It can not show in device list on panel for use.
not only iou, other device by remote also can not show in device list.

After test I found that not only IOU, other device which running on remote server also can not show in device list .
![bugreportjpg2](https://cloud.githubusercontent.com/assets/9411604/5775601/1137e942-9db7-11e4-8416-0c7e57876eec.jpg)

![bugreport2 2jpg](https://cloud.githubusercontent.com/assets/9411604/5775566/83c17bf0-9db6-11e4-8b8a-094e88b86f20.jpg)

**Comment by grossmj** [comment]
Yep, some code was preventing nodes with a remote server configured to show up. Fixed now.

Thanks,
