### ISSUE TITLE
save-as doesn't work for dynamips

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1761]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

* created a new project (untitled2)
* move a dynamips router for the GNS3VM into the project
* save-as untitled3

GNS3 saves, then reopens the new project. This aborts with an error message `Cannot access the startup-config /opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89/project-files/dynamips/configs/i1_startup-config.cfg: [Errno 2] No such file or directory: '/opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89/project-files/dynamips/configs/i1_startup-config.cfg'`

Directory listing of the old project (untitled2):
```
gns3@gns3vm:~$ ls -lR /opt/gns3/projects/f7626022-c92c-4cac-8eff-3ae21d916fff
/opt/gns3/projects/f7626022-c92c-4cac-8eff-3ae21d916fff:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan  5 15:56 project-files

/opt/gns3/projects/f7626022-c92c-4cac-8eff-3ae21d916fff/project-files:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan  5 15:58 dynamips

/opt/gns3/projects/f7626022-c92c-4cac-8eff-3ae21d916fff/project-files/dynamips:
total 8
drwxrwx--- 2 gns3 gns3 4096 Jan  5 15:56 configs
-rw-rw---- 1 gns3 gns3 1769 Jan  5 15:58 dynamips_i30_log.txt

/opt/gns3/projects/f7626022-c92c-4cac-8eff-3ae21d916fff/project-files/dynamips/configs:
total 4
-rw-rw---- 1 gns3 gns3 402 Jan  5 15:56 i1_startup-config.cfg
```

Directory listing of the new project (untitled3), in fact the configs directory is empty:
```
gns3@gns3vm:~$ ls -lR /opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89
/opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan  5 15:58 project-files

/opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89/project-files:
total 4
drwxrwx--- 3 gns3 gns3 4096 Jan  5 16:05 dynamips

/opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89/project-files/dynamips:
total 8
drwxrwx--- 2 gns3 gns3 4096 Jan  5 15:58 configs
-rw-rw---- 1 gns3 gns3 1589 Jan  5 15:58 dynamips_i31_log.txt

/opt/gns3/projects/a38eec1b-921e-4307-a939-c906646c0b89/project-files/dynamips/configs:
total 0
```

And here the gns3server log file starting from the creation of untitled2
[gns3server.log.txt](https://github.com/GNS3/gns3-gui/files/687545/gns3server.log.txt)

**Comment by noplay** [comment]
I see the main problem is dynamips layout on disk. We don't have a folder by node like the other emulators.

**Comment by noplay** [comment]
I currently making test of changing the dynamips layout on disk. I will push it on a branch to avoid breaking user topologies.

**Comment by ehlers** [comment]
Sounds  good.

**Comment by noplay** [comment]
I will open a PR when I will be ready

**Comment by noplay** [comment]
PR is available: https://github.com/GNS3/gns3-server/pull/856

Beware to save topologies before.

**Comment by ehlers** [comment]
Thanks, will do some tests tomorrow.

**Comment by ehlers** [comment]
Just tested the changed layout for dynamips:

The dynamips devices, that are located on the same server as the controller (normally local server) are converted to the new layout. That works pretty well, at least I haven't found an issue using the converted project and using save-as on this project.

But I'm using most devices, including the dynamips devices, in the GNS3 VM. There these dynamips devices are not converted to the new layout. Opening a project with a remote dynamips device fails with `Cannot access the startup-config /opt/gns3/projects/1ff4d18d-07b6-4d56-8af6-a3d2c0037978/project-files/dynamips/52b33563-7ec7-48ed-a618-981836459733/configs/i2_startup-config.cfg: [Errno 2] No such file or directory: '/opt/gns3/projects/1ff4d18d-07b6-4d56-8af6-a3d2c0037978/project-files/dynamips/52b33563-7ec7-48ed-a618-981836459733/configs/i2_startup-config.cfg'`

So the conversion has be done also on the remote server.

**Comment by noplay** [comment]
Merged
