### ISSUE TITLE
Wrong slot numbering on IOS router

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1762]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

I've configured a cisco 7200 with these slots:
![ios_config](https://cloud.githubusercontent.com/assets/896406/21685846/63ae33aa-d363-11e6-9065-137cfe26fa32.png)

The resulting interface assignment in GNS3:
![gns3-interfaces](https://cloud.githubusercontent.com/assets/896406/21685856/71b96adc-d363-11e6-8b20-a263f5f3b415.png)

And here the IOS interface list:
```
R1#sh ip int bri
Interface                  IP-Address      OK? Method Status                Protocol
FastEthernet0/0            unassigned      YES unset  administratively down down
Ethernet1/0                unassigned      YES unset  administratively down down
Ethernet1/1                unassigned      YES unset  administratively down down
Ethernet1/2                unassigned      YES unset  administratively down down
Ethernet1/3                unassigned      YES unset  administratively down down
Serial2/0                  unassigned      YES unset  administratively down down
Serial2/1                  unassigned      YES unset  administratively down down
Serial2/2                  unassigned      YES unset  administratively down down
Serial2/3                  unassigned      YES unset  administratively down down
```

GNS3 starts the slot numbering for each interface type (Ethernet, FastEthernet and Serial) from zero. I've noticed that on both 7200 and 3725 router.

**Comment by noplay** [comment]
Do you know what is behavior in IOU?

**Comment by ehlers** [comment]
On IOU it looks fine, here 8 ethernet + 8 serial ports. The GNS3 interface numbering and within the IOU match.
![iou_interfaces](https://cloud.githubusercontent.com/assets/896406/21688132/f63a9bac-d36b-11e6-9c11-dbe63d68794b.png)

**Comment by noplay** [comment]
Ok I think it's the reason. The code is the same for port numbering. When fixed IOU, we broke dynamips :(

**Comment by noplay** [comment]
Fixed
