### ISSUE TITLE
Interface labels for hubs, switches and VPCS incorrect

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1764]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The port names are fine, but the port labels are not. They have the `e0/<port>` format.
![port_names](https://cloud.githubusercontent.com/assets/896406/21736152/e5f320d0-d46e-11e6-9913-3788f6ac3d2d.png)

**Comment by noplay** [comment]
Not sure how to implement a fix :( The problem is in 2.0 the port is an independent entity they don't know the port of which kind of device they are. 

We are going back on the same issue as https://github.com/GNS3/gns3-gui/issues/1742 the lack of formatting for short port name require work around.

**Comment by noplay** [comment]
It's fixed. I'm not totally happy but it's the less intrusive patch possible. Beware when you test I think the change will be visible only on new node or after some reload.
