### ISSUE TITLE
Switch property of port 0 can't be changed

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1765]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The port dialog field doesn't allow 0 as port number, therefore port 0 can't be modified.

![switch_properties](https://cloud.githubusercontent.com/assets/896406/21736210/4941e6f8-d46f-11e6-9de7-8648d2e79030.png)

**Comment by noplay** [comment]
Good catch
