### ISSUE TITLE
VPCS configuration is overwritten on project load

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1766]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

* put a VPCS in an empty project (untitled2)
* start it and start console to it
* within VPCS set IP address and save it, startup.vpc is modified
```
/Users/behlers# cat GNS3/projects/untitled2/project-files/vpcs/77c9d212-24e8-47c7-9423-fe9ae9f3f2bf/startup.vpc
set pcname PC1
ip 10.1.1.1 24
/Users/behlers#
```
* stop VPCS, startup.vpc ist still fine
* start VPCS, startup.vpcs is still fine
* stop VPCS and close GNS3, startup.vpcs is still fine
* start GNS3 and open project, startup.vpcs is overwritten with the default config.
```
/Users/behlers# cat GNS3/projects/untitled2/project-files/vpcs/77c9d212-24e8-47c7-9423-fe9ae9f3f2bf/startup.vpc
set pcname PC1
/Users/behlers#
```

**Comment by noplay** [comment]
Will need to found why this behaviors but it will be only duck tape. The root cause is:
https://github.com/GNS3/gns3-server/issues/786

**Comment by noplay** [comment]
Thanks it's fixed
