### ISSUE TITLE
Can use GNS3-SERVER for 32-bit virtualized VT-x/EPT

### ISSUE THREAD

**Issue by dragonknight320** [GNS3/gns3-gui#1767]
Dear all,
 My ESXI Server with CPU (XEON-E5410) only inclue 32bit support VT-X/EPT
![cpu](https://cloud.githubusercontent.com/assets/24969416/21738922/90ef5a20-d4c0-11e6-98b3-4035e94809e7.PNG)
So this VM can't use KVM.
Can I change GNS3.VM.VMware.ESXI.2.0.0b2.zip from 64bit to 32bit for support EPT? Or build Source code. Please guide me. Thank you.

![error](https://cloud.githubusercontent.com/assets/24969416/21738867/e07ddd42-d4bf-11e6-8902-93431b011c92.PNG)

P/s: I enabled vhv.enable =TRUE on ESXI

**Comment by noplay** [comment]
Hi,

This will be terribly slow and not officially supported by us. Some appliances will probably crash
