### ISSUE TITLE
VPCS Remote Host IP Address

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#1771]
I have VPCS on there difference versions of GNS3; version 1.5.2, 1.5.3rc1, and 2.0.0 Beta 2.  The VPCS remote host IP in versions 1.5.2 and 1.5.3rc1 is in server host binding subnet range as shown in preferences.

In version 2.0.0 Beta 2 the VPCS remote host IP is 127.0.0.1 instead of an IP in server binding subnet range.

The setup in versions 1.5.2 and 1.5.3rc1 work as expected but not in version 2.0.0 Beta 2.  Please see attached files
![host binding](https://cloud.githubusercontent.com/assets/17806351/21767811/1fda1624-d644-11e6-98b7-fbf87251b631.png)
[VPCS - GNS3 1.5.2 on Windows 64 bit.txt](https://github.com/GNS3/gns3-gui/files/693510/VPCS.-.GNS3.1.5.2.on.Windows.64.bit.txt)
[VPCS - GNS3 1.5.3rc1 on Windows 64 bit.txt](https://github.com/GNS3/gns3-gui/files/693511/VPCS.-.GNS3.1.5.3rc1.on.Windows.64.bit.txt)
[VPCS - GNS3 2.0.0 Beta 2 on Windows 64 bit.txt](https://github.com/GNS3/gns3-gui/files/693512/VPCS.-.GNS3.2.0.0.Beta.2.on.Windows.64.bit.txt)

**Comment by noplay** [comment]
Does is break something for you? It seem normal for me. In 2.0 vpcs bind on 127.0.0.1 and a small program named ubridge will make the bridge with rest. Ubridge allow stuff like capture or connection to cloud interface.


```
+-------------+               +-----------------+                 +-----------------+
|             |               |                 |                 |                 |
|             | 127.0.0.1     |                 |  0.0.0.0        |                 |
|   VPCS      +--------------->  Ubridge        +----------------->  Qemu           |
|             |               |                 |                 |                 |
|             |               |                 |                 |                 |
|             |               |                 |                 |                 |
+-------------+               +-----------------+                 +-----------------+
```

**Comment by fatbell** [comment]
Yes.  Cannot ping the gateway

________________________________

**Comment by noplay** [comment]
Your VPCS is connected to what? What is the gateway?

**Comment by fatbell** [comment]
VPCS is connected to IOSvL2 VM and the gateway is IOSvL3 VM

**Comment by noplay** [comment]
I suppose IOSvL2  is located on a remote machine.

If you put a generic ethernet switch running on the same machine as VPCS between VPCS and the remote IOSvL2 does it work?

**Comment by fatbell** [comment]
It works with a generic ethernet switch.  I deleted the VPCS and set it up again and strangely its working now.  Thanks for your time.

**Comment by noplay** [comment]
Thanks for the feedback
