### ISSUE TITLE
Port labels for docker VMs incorrect

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1773]
GNS3 version 2.0.0dev7 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

The port names are fine, but the port labels of docker VMs are not. They have the `e<port>/0` format
![docker-label](https://cloud.githubusercontent.com/assets/896406/21855576/3cca28a0-d81f-11e6-8b45-ce160a369dac.png)

**Comment by noplay** [comment]
Fixed thanks. Now it's eth for long and short label
