### ISSUE TITLE
[2.0] error message with cloud

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1775]
Hi

When i connect a Ethernet switch to eth0 from Cloud, GNS3 displays this error message : 
`bridge 'bdb48505-e602-4c9c-93b8-831f8e4eab11-0' already exist:`

but, this Cloud seems to work

**Comment by noplay** [comment]
Do you have the issue everytime?

**Comment by Raizo62** [comment]
2 times : one when practice nework. An other to verify
You can't reproduce ? zut.

**Comment by noplay** [comment]
I think their is probably some scenario after you got an error. I'm
interest to know which warning or error you got just before.

**Comment by cioby23** [comment]
I can confirm this happens. I have tested several times and with different type of devices (Dynamips, Qemu and VPCS). Every time I add a node and link it to a cloud this error message is displayed in the console:
bridge '59458573-9ee4-4bee-b012-dd9b54cfe480-0' already exist: 
bridge '9263b830-a073-415a-95d8-103fbe9515e3-0' already exist: 
bridge '9263b830-a073-415a-95d8-103fbe9515e3-1' already exist: 

I'm using GNS3 on Linux local server (latest git).  Also interesting is that after I connect a node to the cloud the link on the cloud side is still red as if the cloud is down.

**Comment by noplay** [comment]
Ok I will test on Linux seem specific to this OS.

**Comment by noplay** [comment]
Thanks it seem fixed now
