### ISSUE TITLE
[2.0] Forgotten debugging message ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1778]
Hi

I don't think that is a bug or does bugs. Then it is just for info if i am wrong

When I start a VMBox, the debugging log of GNS3 (green line in console) show "0.0.0.0" without timestamp

**Comment by noplay** [comment]
I will take a look but I think you are right sound like a debug message

**Comment by noplay** [comment]
Thanks it's cleaned
