### ISSUE TITLE
[2.0] Bug with special characters in name of dynamips devices

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1779]
Hi

I rename Cisco router with the name "éss1"

Strangly, the title of the xterm is : Ã©s
In the router, the name is : )ss1

Detect and block ?

**Comment by noplay** [comment]
It will probably failed with chinese characters

**Comment by grossmj** [comment]
I've only a problem with ')ss1' in the router. IOS doesn't like non-ascii I think.

Everywhere else the name is displayed correctly.

**Comment by Raizo62** [comment]
Now, i can't test with "GNS3 2.0".
I just test with a old GNS3 1.5 (of Live Raizo v7) : i have the same title Ã©s
And if i test "xterm -T éssai1 ", the title is correct (almost, the last character is removed (?) )

**Comment by noplay** [comment]
After tests.

Doesn't seem to be an issue IOS properly handle the error like in real world and user could fix the problem.

And the title is correctly display on OSX, perhaps your xterm doesn't support UTF-8 in title it's an optionnal feature of xterm.

**Comment by Raizo62** [comment]
> perhaps your xterm doesn't support UTF-8 in title it's an optionnal feature of xterm.

You are right. To correct, i have add "xterm*utf8Title: true" into "/etc/X11/app-defaults/XTerm"
Thanks :-D

**Comment by noplay** [comment]
Great :) It should be the case on fresh install of modern distribution.
