### ISSUE TITLE
menubar-view-docks, the last item name is empty

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#178]
menubar-view-docks, the last item name is empty

should be node select dock
![bugreportjpg3](https://cloud.githubusercontent.com/assets/9411604/5787813/ccbe9cca-9e4c-11e4-8789-0429108d6bbe.jpg)

**Comment by superwolfboy** [comment]
It's working again.... sorry .
may be my problem ...

**Comment by noplay** [comment]
Thanks
