### ISSUE TITLE
[2.0] Name of VPCS

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1780]
Hi

If name of VPCS contains accents, vpcs doesn't use the chosen name. (i have tried with éss2)
Same issue if name of VPCS uses more 6 characters.

Could you detect and block ?

**Comment by noplay** [comment]
We will improve that you are right

**Comment by grossmj** [comment]
Looks like the startup config of VPCS is not updated when changing the hostname (even without accents).

**Comment by Raizo62** [comment]
> Looks like the startup config of VPCS is not updated when changing the hostname (even without accents).

oh yes, you have right (i have tested with 3 characters)

**Comment by noplay** [comment]
The update issue is fixed. Doesn't seem to have trouble with accents
