### ISSUE TITLE
GNS3 Virtual Machines Probleme

### ISSUE THREAD

**Issue by isga2017** [GNS3/gns3-gui#1781]
![gns3 prob](https://cloud.githubusercontent.com/assets/25126499/21959117/47bf8316-dab5-11e6-9183-94c64809e679.JPG)

I Cant Start A Virtual Machine in GNS3 2.0.2b2 ....can any one Help me With this Probleme..!

**Comment by noplay** [comment]
What do you have in the server section?

**Comment by cioby23** [comment]
I'm experiencing a similar issue when trying to add a QEMU VM on a remote GNS3VM hosted on ESXi.
Every time I try to run the New appliance template wizard or trying to add a QEMU VM from Edit -> Preferences -> QEMU VMs after I type the VM name and press Next the same error pops up **Compute ID local doesn't exist**, and the Qemu binary list is empty. 

I'm using the latest 2.0 code on both sides the GUI and the remote GNS3VM.
Interesting is that if I use the Import appliance wizard it works fine.

**Comment by noplay** [comment]
Can you open a new issue? It seem different. Did you test with 2.0.0b3?
