### ISSUE TITLE
v1.5.3 OVA for ESXi is broken

### ISSUE THREAD

**Issue by ryangurazov** [GNS3/gns3-gui#1785]
Downloaded OVA v1.5.3 for ESXi from here:
https://github.com/GNS3/gns3-gui/releases/download/v1.5.3/GNS3.VM.VMware.ESXI.1.5.3.zip

Tried to load on ESXi 6.0 and got error message
![image](https://cloud.githubusercontent.com/assets/23531484/22001728/b934dd38-dbfb-11e6-95cb-b007eb78cb17.png)

Downloaded v1.5.2 and it did not have this error.

**Comment by noplay** [comment]
Hi,

Could you test the last build it should solve the issue.

**Comment by noplay** [comment]
The build replace previous build.

**Comment by ryangurazov** [comment]
it worked, thanks
