### ISSUE TITLE
NX-IOS and Unicast Routing

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#1786]
I have setup two Nexus 7K VMs with two difference images; Cisco VIRL and Titanium image.  Enabling unicast routing on titanium VM works well but cannot enable unicast routing on VIRL VM.  Boot process and unicast routing config from the two VMs are attached.   

[Titanium VM - Boot process and EIGRP routing.txt](https://github.com/GNS3/gns3-gui/files/709910/Titanium.VM.-.Boot.process.and.EIGRP.routing.txt)
[Cisco VIRL Nexus VM - Boot process and Feature EIGRP.txt](https://github.com/GNS3/gns3-gui/files/709911/Cisco.VIRL.Nexus.VM.-.Boot.process.and.Feature.EIGRP.txt)

**Comment by noplay** [comment]
You need to enable the feature:

**Comment by noplay** [comment]
https://learningnetwork.cisco.com/thread/99123

**Comment by fatbell** [comment]
The feature is enabled on both VMs.  Please check the bottom part of the attached files.

**Comment by cioby23** [comment]
I just looked at output of the Virl VM and I see **Feature grace period is disabled**
Like @noplay stated first you need to enable the grace period
switch(config)# license grace-period
and the enable the eigrp feature
switch(config)# feature eigrp

**Comment by noplay** [comment]
Sorry if was not clear.

**Comment by fatbell** [comment]
Its working.  I missed the link provided above. My apologies.  Please close the case.  Thanks for your time

**Comment by noplay** [comment]
I have added a mention in the documentation:
http://docs.gns3.com/appliances/cisco-nxosv.html#header

Don't hesitate to contribute
