### ISSUE TITLE
error while deploying gns3 on esxi (vcenter 6.0)

### ISSUE THREAD

**Issue by Isma399** [GNS3/gns3-gui#1789]
Hello,

I've got some errors from the ovf file contained in the ova.zip.
I've got to extract the ova.zip and delete each string beginning with ":" then it works.

**Comment by noplay** [comment]
When did you download the ESXi VM?

**Comment by Isma399** [comment]
Hello,
in our team, we want to work on the same lab.

**Comment by noplay** [comment]
Sorry I don't understand the answer

**Comment by Isma399** [comment]
Sorry,

I was quite brief. 
We (our team at work) want to test the same emulated network (in a collaborative way).

**Comment by noplay** [comment]
You can do that with 2.0:
http://docs.gns3.com/1K_OVfincey0cUw6CP4dWVgs_pBXMdIJ6gdFGjNy8EZQ/index.html

About the ESXi when did you download it ? We pushed an updated few hours ago.

**Comment by Isma399** [comment]
Hello,
 
big thanks to you.
I've downloaded it this morning (7 hours ago).

**Comment by noplay** [comment]
Ok it was updated in the mean time. Thanks for the feedback. Please note that we want to redact a documentation for ESXi but last ESXi 6.5 bug at import we wait for VMware update.
