### ISSUE TITLE
When one qemu device working with -enable-kvm, the vbox which in same topology can not working 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#179]
in one project,
one qemu device for example vSRX for test, with the option -enable-kvm
one vbox device for example tinycore 

clice start button, then qemu start , the vbox tinycore flash quit 
and the console show:
Server error [-3200] from 127.0.0.1:8000: TinyCore_VBox-1: Could not connect to the pipe /tmp/pipe_TinyCore_VBox-1: [Errno 2] No such file or directory

if start tinycore first , the tinycore will start well, then start vSRX , not working,
 generally speaking, they are incompatible

**Comment by grossmj** [comment]
Hi,

This is not a bug but a limitation. You cannot have both VirtualBox and Qemu (with KVM) use hardware virtualization (VT-x) at the same time. If you want to use KVM with your vSRX you will have to disable VT-x/AMD-V in your TinyCore_VBox settings (System -> Acceleration). The best is to run everything with the same emulator but I understand this isn't always that easy ;)

**Comment by superwolfboy** [comment]
@grossmj 
ok I understand , thank you ~
