### ISSUE TITLE
[2.0] bug with other directory of Qemu images

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1790]
Hi

Local path : /home/user
Path of binary image : /opt/raizo/user/OS

I want to create a Qemu device with the vdi : /opt/raizo/user/OS/VBOX/AutreVDI/Linux.vdi
I refuse when GNS3 asks to copy the vdi into default path of binary image

When i put my device on the lab, i have this error message ;
```
2017-01-17 10:01:51 ERROR node.py:302 error while updating WinQ-1: The image VBOX/AutreVDI/Linux.vdi is missing
2017-01-17 10:01:51 CRITICAL __init__.py:110 The image VBOX/AutreVDI/Linux.vdi is missing
```
(I don't know if this is useful for the bug : i have created before the md5sum file)

I have not the bug if the vdi is in "/home/user/Download"

**Comment by noplay** [comment]
Seem to work now from my tests. Please check to be sure.

**Comment by Raizo62** [comment]
I have tested. That works. Thanks :-)
