### ISSUE TITLE
GNS3 OVA Version 1.5.3 problem after deployment

### ISSUE THREAD

**Issue by ryangurazov** [GNS3/gns3-gui#1793]
Loaded GNS3 OVA on ESXi server with ` Expose hardware assisted virtualization to the guest OS` option and don't see way to start GNS3 console.

![image](https://cloud.githubusercontent.com/assets/23531484/22048302/db423eda-dce0-11e6-896c-6048d3a16dd3.png)

Here is type of CPU I have:
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

**Comment by noplay** [comment]
Hi,

Your GNS3 VM is correctly installed but their is a misunderstanding. The GNS3 VM provide only the  server part, you still need a client installed on your machine to use GNS3. 

Best regards

Julien
