### ISSUE TITLE
[2.0.0b2] 1.5 projects with ethernet switch may fail to open and GUI crashes

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1797]
Hi!
I have crashed a GUI with a project which was working fine on 1.5. The project is replica of INE topology: 20 L3 IOL + 4 L2 IOL connected to one Ethernet switch. When I am trying to open this project in 2.0 the following happens:
1. Load is extremely slow
2. Later the following error is observed and the project does not open:
3. GNS3 crashes in 50% cases.
It seems that it caused by the fact that Ethernet Switch in my topology has more than 20 ports.
Please be aware that in the attached topology file I put placeholders "PUT-L3-IOU-NAME-HERE" and "PUT-L2-IOU-NAME-HERE" instead of actual image names.
Traceback: http://pastebin.com/nSrnpbZ2
Topology file: https://github.com/GNS3/gns3-gui/files/718048/ine-ccie-rs-full.gns3.zip
Error: <img width="576" alt="screen shot 2017-01-20 at 00 25 06" src="https://cloud.githubusercontent.com/assets/1923704/22129571/20bcfeba-dea7-11e6-9ba9-5ab8073cba90.png">

**Comment by noplay** [comment]
Do you have the project before conversion to 2.0?

**Comment by dmfigol** [comment]
Hi Julien,

I think an attached project is from 1.5.x, is it not? If not, how can I check if it is converted or not? Most likely I have what you need, since I store gns3 projects in dropbox.

**Comment by noplay** [comment]
Oh you are right

**Comment by noplay** [comment]
Ok should be fixed in this build https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-01-23/2.0/GNS3%20nightly-2.0.0dev8.dmg/download

Thanks for the help
