### ISSUE TITLE
Captures with IOL nodes and PPP encapsulation are not formatted correctly. 

### ISSUE THREAD

**Issue by dschuemann** [GNS3/gns3-gui#1799]
When performing a capture using ppp encapsulation and IOL devices the capture is unable to read the data correctly. Standard IOS images work fine. I've included a capture. 
[IOL-PPP-CAP.pcapng.zip](https://github.com/GNS3/gns3-gui/files/720823/IOL-PPP-CAP.pcapng.zip)

This is in version 2.0 beta 3

**Comment by noplay** [comment]
The command was not  correctly sent to ubridge
```
sending iol_bridge start_capture IOL-BRIDGE-513 4 0 "/home/vagrant/GNS3/projects/c83eb61b-5618-45d8-9b78-634b86dba190/tmp/captures/IOU1_Serial40_to_IOU2_Serial40.pcap" DLT_PPP_SERIAL
```

Lib pcap require us to strip the DLT_

**Comment by noplay** [comment]
Thanks a lot for the report it's now fixed
