### ISSUE TITLE
Mouse/touchpad problem with GNS3

### ISSUE THREAD

**Issue by ferztyle** [GNS3/gns3-gui#1801]
Hello, I'm experiencing an issue with my mouse/touchpad buttons when trying to load any device inside a gns3 project.(like hub,switch, host,etc). I saw my logs and found this message "[  9857.058] (II) UnloadModule: "libinput"". Is there anyway to avoid that or maybe a missing configuration?. I have a fedora24 installed in a asus k501ux. Can anyone help me with this please?!

Fer Rios

**Comment by noplay** [comment]
Hi,

It seem the touchpad driver of your system crash when use with Qt.  This not specific to GNS3.

I suggest you upgrade to fedora25,  libinput (the touchpad library ) is know  to evolve fast .
