### ISSUE TITLE
2.0.0b3: Incorrect remote GNS3 VM name appears in Preferences

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#1803]
I get this error when trying to drag a device into a newly created topology:
![gns3_2b3-remote_vm-1](https://cloud.githubusercontent.com/assets/16632791/22184051/156c43ec-e0cb-11e6-8c0a-fa1b259ae9bb.png)

GNS3 VM settings:
![gns3_2b3-remote_vm-2](https://cloud.githubusercontent.com/assets/16632791/22184054/1e50b862-e0cb-11e6-8976-5d7533a796d1.png)

When I press **Refresh**, the correct remote server becomes visible:
![gns3_2b3-remote_vm-4](https://cloud.githubusercontent.com/assets/16632791/22184098/b473de8c-e0cb-11e6-8425-c222436b31ff.png)

I press **OK**, everything works fine. However, if I open Preferences again, "GNS3 VM" is reapplied and I have to repeat the process.

**Comment by adosztal** [comment]
Just for the record: Changing the remote server's name to "GNS3 VM" is a possible workaround.

**Comment by noplay** [comment]
What do you have in remote servers? I don't reproduce the issue on my side.

Thanks

**Comment by noplay** [comment]
Hmm it seem dropping a node broke the settings....

**Comment by noplay** [comment]
I think the issue is when we are on a different page Qt load the VM page with default settings.

**Comment by noplay** [comment]
I have the feeling to fix again and again the same issue :(

When the list of engine is loaded when we add engine one by one this was triggering a temporary state where the list of VMware VM was loaded.

**Comment by adosztal** [comment]
I checked b4 and couldn't reproduce the issue, it works fine. Thanks!

**Comment by noplay** [comment]
Thanks
