### ISSUE TITLE
[2.0.0b3] Project dialogue is shown after double-click on .gns3 topology file

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1808]
I am using 2.0.0b3 on OS X Sierra.
I have noticed that if I double-click on .gns3 file the topology opens but Project dialogue (with tabs "New project", "Projects Library") is shown as well.

**Comment by noplay** [comment]
The magic of Apple breaking standard from  1970

**Comment by noplay** [comment]
Fixed thanks
