### ISSUE TITLE
[2.0.0b3] [Enhancement request] IOL license file

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1809]
Hi,
starting from 2.0.x the IOL license file is stored in the GUI. If I remember correctly in 2.0.0b1 when I had .iourc file on remote server but it was not specified in GNS3 GUI, IOL didn't work. I didn't have a chance to test it in b3.
Anyway, the potential problem is that we lose portability. IOL license is generated for the hostname of the server. Meaning that every time I change my server, I need to supply a new license file, which may be annoying. I think that if we move IOL license to the GUI it should be defined on per-server basis. Ideally, we should have such an option in GUI and if license is not there, still check .iourc in home directory as we did in 1.5.x not to break backwards compatibility.

**Comment by noplay** [comment]
Hi,

The licence file allow to have one server by line. 

If the licence was in the standard location the licence is converted the first time.  For standard installation it's backward compatible. The only case where you could have issue is when you use multiple servers but IOU itself doesn't support it due mac address conflicts.
