### ISSUE TITLE
[2.0] Qemu and telnet

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1811]
Hi

A friend has created a vdi with Ubuntu server 16.04

I have tried to use qemu with it. When i use "vnc", that works. But when i use "telnet", i see nothing.
To use "telnet", do i must configure the VM with serial console ? (and the help message of GNS3 is wrong : i need configure something to use telnet) Or i have do an error ?

**Comment by noplay** [comment]
By default the serial console is not enabled on most linux distribution.  For ubuntu you need to enable it in systemd.
