### ISSUE TITLE
After installing latest build on 1/23, GUI does not see GNS VM

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1812]
After installing latest build and completely restarting computer and updating VM, GUI does not appear to see VM.

![image](https://cloud.githubusercontent.com/assets/6335629/22223912/af29dd54-e18a-11e6-80b3-b903e9e578ff.png)

**Comment by noplay** [comment]
Same issue: https://github.com/GNS3/gns3-server/issues/876
