### ISSUE TITLE
"Local GNS3 server cannot be stopped" warning does not disappear

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#1813]
This message appears when closing the GNS3 GUI:
![gns-3](https://cloud.githubusercontent.com/assets/16632791/22238772/85b02d64-e213-11e6-810e-b52c61619314.png)

My guess is the local server is waiting for the GNS3 VM to stop; I tracked it in the task manager and the local stopped right after the VM. However the message does not disappear:
![gns3-2](https://cloud.githubusercontent.com/assets/16632791/22239322/3f0b09bc-e216-11e6-8f50-4efb5a4a6497.png)

**Comment by noplay** [comment]
You want us to monitor the server state when the dialog appear and if the server exit in the interval close the dialog ?

**Comment by adosztal** [comment]
Yes, I think that would be needed. This behavior might confuse the users ("Do I cause any trouble if I kill it, or should I wait a bit more?"), especially that it happens at every shutdown not just once a while.

**Comment by noplay** [comment]
How long it's take to shutdown the server? if you see it everytime we should increase the timeout.

It sound complex to implement an hide dialog with the risk of adding potential bugs.

**Comment by adosztal** [comment]
It was ~30 s. The warning appears after 15 s.

**Comment by noplay** [comment]
10 seconds :)

**Comment by noplay** [comment]
Now timeout is 60 seconds
