### ISSUE TITLE
GNS3 2.0.0b3 appliance.json - no "sata" option

### ISSUE THREAD

**Issue by bielsky** [GNS3/gns3-gui#1817]
There is no "sata" option in appliance.json in enum:
qemu -> "hdX_disk_interface" 
i.e.:
        "hdb_disk_interface": {
            "enum": ["ide", "scsi", "sd", "mtd", "floppy", "pflash", "virtio"],
            "title": "Disk interface for the installed hdb_disk_image"
        },

**Comment by noplay** [comment]
Thanks it's fixed

**Comment by bielsky** [comment]
Thanks very much.
This feature is very useful for me.
PG

2017-01-27 11:01 GMT+01:00 Julien Duponchelle <notifications@github.com>:
