### ISSUE TITLE
[2.0] Can't connect VMBox device to switch

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1818]
Hi

On this lab, i can't connect the device Win2003-1 to SW1

[nagios3.gns3.txt](https://github.com/GNS3/gns3-gui/files/732843/nagios3.gns3.txt)

**Comment by noplay** [comment]
Do you have an error ? I see nothing in the logs

**Comment by Raizo62** [comment]
I have only "Error while creating link: Operation canceled" and after blank screen with "please create a project"

Here logs :

with debug 2 : [log_debug2.txt](https://github.com/GNS3/gns3-gui/files/735729/log_debug2.txt)

with debug 0 : [log_debug0.txt](https://github.com/GNS3/gns3-gui/files/735740/log_debug0.txt)

[gns3_gui.log.txt](https://github.com/GNS3/gns3-gui/files/735745/gns3_gui.log.txt)
[gns3_server.log.txt](https://github.com/GNS3/gns3-gui/files/735746/gns3_server.log.txt)

**Comment by noplay** [comment]
I don't see the please create a project in the logs you provided. Can you post a screenshot? Thanks

**Comment by Raizo62** [comment]
I can, but you will only see GNS3 when you click on cancel on "Project" dialog box.
I have do an little error in my description : this is the "Win2012-1" device and not Win2003-1 (there is not Win2003-1 device on the lab)

**Comment by noplay** [comment]
You mean you create the link and the project close?

**Comment by Raizo62** [comment]
Yes that's it : the status bar gets times, and after, the project closes.
(each time with this save, but I did not try to reproduce a similar topology for to see)

**Comment by noplay** [comment]
Do you have a Win2003 somewhere?

**Comment by Raizo62** [comment]
euh.... now, i don't know. It is not my own lab. I verify tomorrow my backup.

**Comment by noplay** [comment]
Probably a corruption caused by #1821

**Comment by Raizo62** [comment]
I don't know if this  bug is corrected. I have a lab with a bug but i don't know how to reproduce it ( I have tried this morning to do the same schema without success. But it is perhaps a good news :-) )

You can close this issue. I will reopen it if needed.
