### ISSUE TITLE
Error Opening project file in Version 2.0.0 Beta 3

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#1819]
I'm getting the attached error when opening a project file in version 2.0.0 beta3.  Any help will be greatly appreciated.
![error opening project](https://cloud.githubusercontent.com/assets/17806351/22361340/aed86ff2-e426-11e6-9bbb-5ac5782fccd2.png)

**Comment by noplay** [comment]
You have a process running on your computer preventing us to open the project. Probably a ghost dynamips process. Did you check in the task manager?

**Comment by fatbell** [comment]
It was vpcs process running.  I'm good now.  Thanks

**Comment by noplay** [comment]
Thanks
