### ISSUE TITLE
[2.0] bug with info shown by ethernet switch

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1828]
hi

I connect 2 VMBox to ethernet switch. One on port 0 and one on port 1.

When i move my mouse on the ethernet swicth, i see in the yellow box that Port ethernet 0 is connected in access mode, and that Port 2 to 7 are empty.

But, i don't see info on port 1

**Comment by noplay** [comment]
Good catch it's fixed

**Comment by Raizo62** [comment]
To beginning, i believed that was a clue to the bug of switch #1818
