### ISSUE TITLE
GUI local/remote servers refactoring

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-gui#183]
Hi GNS3-devs,

My use case is running GNS3-GUI on a fast laptop (SSD, reasonable mem amt [4GB in my case], UNIX-y OS [Linux in my case, specifically Ubuntu 14.04].) Not enough resources locally to run the topos I want to (Dynamips + IOU, maybe + VirtualBox VMs and/or QEMU VMs.) So, want to use the GNS3-GUI as a access client only, and desire all other functions (GNS3-Server, IOU, VB, QEMU) to run on remote machines, and for flexibility/simplicity of remote machine env's, desire that the Dynamips, IOU, VB and QEMU can be separate machines (I'm supposing that all machines will also have to run the GNS3-server executable as well for integration purposes.)

Now then, I've gotten as far as running GNS3-GUI on my laptop, with the Dynamips being on server A, and IOU being on serverB. I'm finding the current GUI layout confusing for my use case, and want to throw out some suggestions on refactoring... here goes:

1) On the "GNS3 server" section in Preferences:
    a) Local server tab: make a checkbox named something like "Disable local server" (or maybe "No local server") which would grey out the local server settings, and make the fact that the user is not running (i.e. doesn't have installed) the gns3server + dynamips/IOU/whatever locally.
   b) Remote servers tab: I understand this is to list all remote servers and set the GNS3 client<-->server intercommunications ports on them (i.e. TCP/8000); I also see the servers specified here are presented in all other remote servers tabs (Dynamips, IOS on UNIX, etc. sections) If this is the best way to set up the remote servers for these subsystems, perhaps you can present checkboxes for the different backends to be run on these remote servers (i.e. [  ] Dynamips  [  ] IOU  [  ] VirtualBox  [  ] QEMU), and then only present the so-checked servers on the relevant individual backend's "Remote servers" tab.  Else, perhaps get rid of this tab, and specify the remote servers directly in the "Remote servers" tab on each of the individual backend sections (i.e. on the Dynamips > Remote servers tab, have an "Add" and "Delete" button, and the same on the other backends.)

2) In the "Dynamips" section, on the "Server settings" tab, allow to specify a different path to dynamips for each remote server (they may differ between servers depending on whether dynamips was installed via an OS repo package vs. being compliled locally and installed in /usr/local/bin for instance.)

3) In the "VirtualBox" section, allow different paths per server for the vboxmanage executable.

Thanks for your consideration of these suggestions...

**Comment by grossmj** [comment]
Hi Will,

This is good timing  :+1: we are in the middle of a major refactoring and we started to simplify a few things for the preferences in the GUI. The refactoring focuses exactly on what you are trying to do: GUI with remote server(s). We have an alpha release planned within the next weeks.

Back to the preferences, I am definitely not satisfied of the current way to configure servers.

> a) Local server tab: make a checkbox named something like "Disable local server" (or maybe "No local server") which would grey out the local server settings, and make the fact that the user is not running (i.e. doesn't have installed) the gns3server + dynamips/IOU/whatever locally.

We have this option saying "automatically start the server at startup" but I agree we could have things more explicit and grey out the local server settings.

>b) Remote servers tab: I understand this is to list all remote servers and set the GNS3 client<-->server intercommunications ports on them (i.e. TCP/8000); I also see the servers specified here are presented in all other remote servers tabs (Dynamips, IOS on UNIX, etc. sections) If this is the best way to set up the remote servers for these subsystems, perhaps you can present checkboxes for the different backends to be run on these remote servers (i.e. [ ] Dynamips [ ] IOU [ ] VirtualBox [ ] QEMU), and then only present the so-checked servers on the relevant individual backend's "Remote servers" tab. Else, perhaps get rid of this tab, and specify the remote servers directly in the "Remote servers" tab on each of the individual backend sections (i.e. on the Dynamips > Remote servers tab, have an "Add" and "Delete" button, and the same on the other backends.)

This is where I would see the most improvements need to be made.  This is something that I want to discuss with other developers / contributors.

>In the "Dynamips" section, on the "Server settings" tab, allow to specify a different path to dynamips for each remote server (they may differ between servers depending on whether dynamips was installed via an OS repo package vs. being compliled locally and installed in /usr/local/bin for instance.)

> 3) In the "VirtualBox" section, allow different paths per server for the vboxmanage executable.

In our refactoring, the Dynamips and vboxmanage paths settings are only for the local server. We have introduced a config file for remote servers where you can add these paths or let the server find them using the $PATH enviroment variable. We just need to document how to use this config file.

Thanks a lot for your suggestions!

**Comment by noplay** [comment]
Ilustration of proposition 1:
![capture d ecran 2015-02-19 a 09 42 07](https://cloud.githubusercontent.com/assets/345437/6263723/e6c0c9f2-b81b-11e4-8afc-b4681958ee1a.png)

**Comment by rednectar** [comment]
Definitely on the right path here. I'm sure this requires more thought, need some time to get my head around it. Mind you, ever since v1.x I have been looking forward to playing with this aspect of the new GNS3

**Comment by grossmj** [comment]
Hi,

I've added some improvments in beta1, hopefully we are on the right track.

**Comment by wdennis** [comment]
Hi guys,

Checked out beta1, the simplifications are great. However, I'd still like to see an explicit "Enable local server" checkbox on the Server > Local server tab. Right now, I leave the "Path" textbox blank, and also uncheck the "Automatically start the server on startup" checkbox to disable the local gns3server (actually, I don't even have one installed on my laptop at this point.) I think it would be more explicit if there was a "Enable local server" checkbox at the top, and if unchecked, all other fields / controls were greyed out. For new installs, this checkbox could be enabled by default.

Thanks for considering.

**Comment by grossmj** [comment]
Hi Will,

I've added the Enable local server checkbox. This will be included in our next release.

Cheers,
