### ISSUE TITLE
[2.0] perhaps bad error message

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1832]
Hi

You create a project with the name "untitle"
You want save as with the same name "untitle" (idea of my student)

GNS3 refuses with the error message : "Project untitled is running you can not overwrite it"

"running" make me think to stop the running device (First thing that i have do to help my student)
Perhaps replace "is running" by "is open" ?

**Comment by noplay** [comment]
You are right

**Comment by noplay** [comment]
Fixed
