### ISSUE TITLE
[2.0] error with {name} in name of own cloud

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1833]
Hi

In built-in device, with cloud nodes, i have tried to use {name}-{0} for default name format . I wish do the same as VirtualBox VM template.

When i use this cloud device, GNS3 shows error message.

**Comment by noplay** [comment]
Fixed thanks

**Comment by Raizo62** [comment]
Sorry, but, is it a bug again if GNS3 shows same red message if i use {Name} (with Uppercase) ?

**Comment by noplay** [comment]
Ok now it's raise a proper error when the key is unknown.
