### ISSUE TITLE
GUI does not start on Ubuntu 16.04

### ISSUE THREAD

**Issue by COLABORATI** [GNS3/gns3-gui#1836]
After installing GNS3 from the repository recommended in the [official docs](https://gns3.com/support/docs/linux-installation) it just does not start, also there are no icons created in the start menu (lesser problem). 

When starting GNS3 from bash I get only this: 

```
19:13:44 ubuntu@xubuntu ~ $ gns3
GNS3 GUI version 1.5.3
Copyright (c) 2007-2017 GNS3 Technologies Inc.
Fatal Python error: Segmentation fault

Current thread 0x00007f611e2c8700 (most recent call first):
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/application.py", line 41 in __init__
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main.py", line 231 in main
  File "/usr/bin/gns3", line 11 in <module>
Segmentation fault
```

**Comment by noplay** [comment]
It's a fresh or do you have a previous install of GNS3?

Can you start with gns3 --debug?

**Comment by noplay** [comment]
Thanks for the help

**Comment by COLABORATI** [comment]
with --debug I get the exact same error. I did an `apt-get install --reinstall` - no change. Looks like gns is expecting something that is not here, or maybe something should be here that is not. Maybe only my shell environment is not good enough for gns3 - however, when I run it via Alt-F2 nothing happens (I assume a crash, too). Any hints?

**Comment by COLABORATI** [comment]
OK, I have one more hint now - looks like your  project is another victim of the annoying QT5 desktop software destruction program - last week I installed this little [qt5ct](https://sourceforge.net/projects/qt5ct/) tool to handle the total desaster that QT5 does on a Xubuntu 16.04 - this involved setting a variable: 
```
export QT_QPA_PLATFORMTHEME=qt5ct
```
When this variable is set, gns segfaults! When I do not set this variable, the GNS gui starts - but then again with monstrous font scaling that makes the startup wizard unreadable: 

![gui-bad-font](https://cloud.githubusercontent.com/assets/6514273/22695063/b4b97368-ed49-11e6-9549-ce94469de4e9.png)

Also please note that the icons are much too big. This is a desktop set to 144 dpi to have optimal rendering of fonts and graphics - QT5 greatly messed up all the GUI apps - "oh, you have actually used that DPI setting to scale your desktop to something usable - well, we assumed all desktops on this planet are running on 96 DPI" - it is totally ridicolous. 

For you as developers that means that you should test your app also on non-kde desktops like e.g. a Xubuntu 16.04 (in my and in many other peoples humble opinion XFCE still is the most usable Linux desktop) and especially with HIGH DPI SETTINGS.

Sorry, I do not know what that means for the implementation, it seems that QT5 is a great f*up regarding high DPI setting - all QT5 apps have these problems, unfortunately. Please pitchfork QT5 devs to solve that problems for all, thanks!

**Comment by COLABORATI** [comment]
Maybe here are some hints: 
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by noplay** [comment]
If you start with QT_SCALE_FACTOR=0 or QT_SCALE_FACTOR=1 does it work?

Qt should detect that your screen is hdpi and render correctly the fonts. But sometimes their code fail to detect and the rendering is broken (GTK don't have this issue because it get information from GTK settings). It's not a problem visible on all computer, the problem is more common if you have multiple screen connected.

**Comment by grossmj** [comment]
@COLABORATI 

Do you still have the issue?

**Comment by noplay** [comment]
I made a PR for the 2.0 to disable HDPI by default
