### ISSUE TITLE
[2.0] : Reset interface labels

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1841]
Hi

If i move the label "eth0" fare way of his device.

If i click on "Reset interface labels", the label doesn't return beside his device. 

I think that it is a bug. If not, it is my request :-) (it is useful to debug if a student moves accidentally the labels)

**Comment by noplay** [comment]
I don't replicate the issue the button work fine on my side can you post screenshots ?

**Comment by Raizo62** [comment]
euh...you have right.... i can't replicate, me too.... However, i had verify. I don't understand...

I can close. sorry.
