### ISSUE TITLE
[2.0] command to change permission on ubridge

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1844]
Hi

When ubridge has bad permission, GNS3 asks to change it.

But, GNS3 wants to change also group owner with admin.
But :
- Makefile of ubridge doesn't do it (it changes only owner to root)
- group "admin" doesn't exist on all distribution.

**Comment by noplay** [comment]
We can't change the Makefile otherwise it will break install where it's works.

I don't remember why we changed the message for that but it was  a requirements for some distribution.

**Comment by Raizo62** [comment]
I don't ask to change the makefile of ubridge ;-)

> but it was a requirements for some distribution.

I am surprise that you must also change the group, but ok. 
But, be careful, if group "admin" doesn't exist, your command will fail.

**Comment by noplay** [comment]
I think it's related to the use of SElinux but not sure :(
