### ISSUE TITLE
[2.0] wizard for the vncviewer : gvncviewer

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1845]
Hi

Wizard for config command of vncviewer propose only : TightVNC and Vinagre

But, archilinux advice gvncviewer ( [archilinux-QEMU](https://wiki.archlinux.org/index.php/QEMU) )

> When using VNC, you might experience keyboard problems described (in gory details) here. The solution is not to use the -k option on QEMU, and to use gvncviewer from gtk-vnc. See also this message posted on libvirt's mailing list.

Can you add for gvncviewer ? 
I will never think to use : gvncviewer %h:%P

(Be careful, i am a very newbie with qemu. I am not a very good advisor)

**Comment by noplay** [comment]
Thanks support added
