### ISSUE TITLE
Import appliance hangs, when no project is open

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1846]
GNS3 version 2.0.0dev8 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Start GNS3 and cancel the initial project dialog, so no project is open. Then import an appliance, for this test I used the Micro Core appliance. Use the defaults during the import.

After the import a "Please wait" progress bar opens, that initially is quite fast, but then slows down. I was never patient enough to see, if it will ever go to 100%. Closing the process bar doesn't help, it pops up again. This make the GUI unusable.
![appliance_without_project](https://cloud.githubusercontent.com/assets/896406/22779747/483793f4-eebc-11e6-9ef5-5e5d8836454a.png)

With an open project, this project bar doesn't pop up.

**Comment by noplay** [comment]
I don't reproduce the issue with Qt 5.6. Do you have the same issue when using https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-02-13/2.0/

I don't see why the fact you cancel the project creation will change the behavior.

**Comment by ehlers** [comment]
I tried with the nightly build and an empty GNS3 config and can't reproduce that. Then I tried with my own GNS3 GUI installation and an empty config. Then I also can't reproduce it. So I manually configured all the settings of the old setup and it's still working fine.

Maybe it's some leftover of version 1.5, I don't know. I suggest to close it.

**Comment by noplay** [comment]
Thanks
