### ISSUE TITLE
[2.0] bug : compute list: Unknown error

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1848]
Hi

These last days, i plays with qemu and also API....and i have often these error messages
Perhaps i do errors, but i think not.

In topology, i mix qemu and vbox VM.
After some time, i have  this error messages and gns3 be back to the windows "Please create a project" :

> 2017-02-12 19:45:17 ERROR compute_manager.py:70 Error while getting compute list: Unknown error
> 2017-02-12 19:45:23 CRITICAL __init__.py:110 Unknown error
> 2017-02-12 19:45:23 ERROR compute_manager.py:70 Error while getting compute list: Unknown error

**Comment by jtorri** [comment]
Windows 10 Prof 64bit, nightly build GNS3-2.0.2017-02-12, GNS3 VM supplied with GNS3 2.0b3 (after install from OVA run upgrade GNS3 from GNS3 VM menu).  All objects except virtual VMs, e.g., Windows XP, run from within the GNS3 VM.

GNS3 management console.
Running GNS3 version 2.0.0dev8 on Windows (64-bit) with Python 3.5.2 Qt 5.7.1 and PyQt 5.7.1.

During initial creation of topology merely clicking on the topology screen will cause the topology to "disappear" from the screen and a dialog appears with "Unknown Error".  It seems to me GNS3 applications nightly builds are becoming less stable the more they move beyond GNS3 2.0b3.  I know that is reasonable since they are nightly builds but this kind of instability seems a bit significant.
Thanks again for all the work!  Wish could be more help.

**Comment by noplay** [comment]
Could you share the logs? It seem the server crash that's why the gui close the project avoiding you doing stuff that will not be saved.

**Comment by Raizo62** [comment]
is it sufficient ?
[unknownerror.zip.txt](https://github.com/GNS3/gns3-gui/files/770498/unknownerror.zip.txt)

**Comment by noplay** [comment]
Can you run gns3 with --debug ?

**Comment by Raizo62** [comment]
Yes, i can :-)

[unknownerror_with_debug.zip.txt](https://github.com/GNS3/gns3-gui/files/770707/unknownerror_with_debug.zip.txt)

**Comment by noplay** [comment]
Can you try with last source code it should display the correct error instead of unknown

**Comment by Raizo62** [comment]
> 2017-02-13 14:59:08 DEBUG http_client.py:431 GET http://127.0.0.1:3080/v2/settings {}
> 2017-02-13 14:59:08 DEBUG http_client.py:431 POST http://127.0.0.1:3080/v2/projects/fa073627-2aba-4d5e-9f83-6c3057cd5b5b/open {}
> 2017-02-13 14:59:08 DEBUG http_client.py:431 GET http://127.0.0.1:3080/v2/computes {}
> 2017-02-13 14:59:08 DEBUG http_client.py:431 GET http://127.0.0.1:3080/v2/projects {}
> 2017-02-13 14:59:08 DEBUG http_client.py:431 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-13 14:59:08 DEBUG http_client.py:524 Response error: Unknown error (error: 99)
> 2017-02-13 14:59:08 DEBUG http_client.py:431 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-13 14:59:08 CRITICAL __init__.py:110 Unknown error
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==2.0.0.dev8', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 288, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/http_client.py", line 531, in _processError
>     callback({"message": error_message}, error=True, server=server, context=context)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 225, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/project.py", line 362, in _projectOpenCallback
>     self.project_creation_error_signal.emit(result["message"])
>   File "/usr/local/lib/python3.4/dist-packages/gns3/topology.py", line 206, in _projectCreationErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, "New project", message)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 110, in critical
>     log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 2017-02-13 14:59:08 DEBUG http_client.py:524 Response error: Unknown error (error: 99)
> 2017-02-13 14:59:08 ERROR compute_manager.py:70 Error while getting compute list: Unknown error
> 2017-02-13 14:59:08 DEBUG http_client.py:570 Decoding response from http://user@127.0.0.1:3080/v2/projects response 200
> 

the debug log of wizard is empty, then the max of copy-paste gives that :
[debug2.txt](https://github.com/GNS3/gns3-gui/files/771429/debug2.txt)

**Comment by noplay** [comment]
The project you try to open sometimes it's work?

I pushed an update with no timeout for project open to see if it's related.

**Comment by Raizo62** [comment]
> The project you try to open sometimes it's work?

Yes, the topology that i use to test this bug works (DHCP client/server)
Even, it works more long time with "--debug" option.
In this case, often, it crash when i click on stop button.

**Comment by Raizo62** [comment]
(I have not yet tested your new version.)
As i am waiting the end of compilation,  i supposed that the bug came perhaps of my old config of GNS3.  
Then i configured a new config but i have see again the bug while the configuration..
Strangely, i have not see this bug in the version of 08 febrary 2017

**Comment by Raizo62** [comment]
Sorry. I have again the bug with your new version.
And i believe that nework doesn't work.
The bug occures when i stop the VM and restart them.
[debug3.zip.txt](https://github.com/GNS3/gns3-gui/files/771959/debug3.zip.txt)

**Comment by noplay** [comment]
Can you try my last commit I just add more info to the debug to try to isolate which api call failed. 

I don't understand why we get an unknow error from the system it's a non sense. The only explanation I found is the keep alive is not working well in some old Qt 5 https://bugreports.qt.io/browse/QTBUG-47048 and because it seem you use debian 8 which provide Qt 5.3 (but the bug mention Qt 5.4).

**Comment by Raizo62** [comment]
[debug4.zip.txt](https://github.com/GNS3/gns3-gui/files/772582/debug4.zip.txt)

**Comment by jtorri** [comment]
Running GNS3 version 2.0.0dev8 on Windows (64-bit) with Python 3.5.2 Qt 5.7.1 and PyQt 5.7.1.
Windows 10 Prof  GNS3-2.0.2017-02-13 (lastest nightly build)  GNS3-VM from GNS3 VM.ova from GNS3 2.0.0b3
Same behavior as I mention above.  Clicking on the topology screen while building or after having built a topology will cause the topology to "disappear".  However, if when that happens I pause for 10-20 seconds the topology in tact reappears.   Eventually the topology works and all objects can communicate with each other and the outside.

**Comment by noplay** [comment]
What do you mean by building a topologie. It's when you put the node on the
topology and create link? Or reloading a file?

**Comment by Raizo62** [comment]
bug with more simple topology (i tested VMBow without disk)
[debug5.zip.txt](https://github.com/GNS3/gns3-gui/files/773568/debug5.zip.txt)

**Comment by noplay** [comment]
Seem to be issues due to bug in keep alive support of old Qt...

**Comment by noplay** [comment]
Can you test last source I tried to workaround it

**Comment by Raizo62** [comment]
sorry : [debug6.zip.txt](https://github.com/GNS3/gns3-gui/files/774043/debug6.zip.txt)

**Comment by noplay** [comment]
I got a new commit. Perhaps it's solve the issue if you can try.

I think the problem appear when you change project. We close a connection but a side effect in the Qt version you have close other connections at the same time. I try to workaround it by isolating the connection for the notification in a dedicated Qt Network Manager.

The machine where you are trying it's a Live Raizo in a VirtualBox ? Or something installed bare metal?

Thanks a lot for the help

**Comment by Raizo62** [comment]
> The machine where you are trying it's a Live Raizo in a VirtualBox ? Or something installed bare metal?

Live Raizo in a VirtualBox

**Comment by Raizo62** [comment]
I have again the bug. I will send debug.

> I think the problem appear when you change project. 

I am not sure. For test, i don't change project. I boot on Live raizo, i create the project. I am waiting without interact with GNS3. After, i change something to see the bug.

**Comment by Raizo62** [comment]
[debug7.zip.txt](https://github.com/GNS3/gns3-gui/files/774968/debug7.zip.txt)

- I create a project called "untitle"
- I put a VMBox called Debian-1, that i connect to ethernet switch.
- I start all.
- I am waiting without to use GNS3
- I add a second VMBox (called Debian-2)
- I connect the VMBox to the ethernet switch. 
- The Bug shows

**Comment by noplay** [comment]
Even with commit c93713b9e7d9cc6380cdb5c5264485343829e1d3 you still have the error? Because I installed a debian in a Vbox and don't manage to replicate the issue.

**Comment by Raizo62** [comment]
Normally, i believe that i use the last commit.

But, now (with version compiled this morning), i can't start GNS3 : i have this error log : 
```
2017-02-15 12:13:38 INFO logger.py:107 Log level: DEBUG
2017-02-15 12:13:38 INFO main.py:253 GNS3 GUI version 2.0.0dev8
2017-02-15 12:13:38 INFO main.py:254 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-02-15 12:13:38 INFO main.py:256 Application started with /usr/local/bin/gns3--debug
2017-02-15 12:13:38 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2017-02-15 12:13:38 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2017-02-15 12:13:38 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'user'
2017-02-15 12:13:38 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'user'
2017-02-15 12:13:38 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'user'
2017-02-15 12:13:38 INFO local_server.py:460 Starting local server process with "/usr/local/bin/gns3server" --local --allow --debug --log="/home/user/.config/GNS3/gns3_server.log" --pid="/home/user/.config/GNS3/gns3_server.pid"
2017-02-15 12:13:38 INFO local_server.py:473 Local server process has started (PID=2232)
2017-02-15 12:13:38 DEBUG progress_dialog.py:98 WaitForConnectionWorker thread started
2017-02-15 12:14:08 CRITICAL progress_dialog.py:159 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
2017-02-15 12:14:08 CRITICAL __init__.py:110 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
Stack (most recent call last):
  File "/usr/local/bin/gns3", line 9, in <module>
    load_entry_point('gns3-gui==2.0.0.dev8', 'gui_scripts', 'gns3')()
  File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 288, in main
    exit_code = app.exec_()
  File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1032, in startupLoading
    LocalServer.instance().localServerAutoStartIfRequire()
  File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 346, in localServerAutoStartIfRequire
    if not progress_dialog.exec_():
  File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 240, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gns3/utils/progress_dialog.py", line 160, in _error
    QtWidgets.QMessageBox.critical(self.parentWidget(), "Error", "{}".format(message))
  File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 110, in critical
    log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
2017-02-15 12:14:22 DEBUG progress_dialog.py:104 WaitForConnectionWorker thread canceled
2017-02-15 12:14:22 DEBUG progress_dialog.py:128 WaitForConnectionWorker thread is being destroyed
2017-02-15 12:14:22 DEBUG progress_dialog.py:135 WaitForConnectionWorker thread destroyed
2017-02-15 12:15:35 DEBUG progress_dialog.py:104 WaitForConnectionWorker thread canceled
2017-02-15 12:15:35 DEBUG analytics.py:77 Stats is turn off ignore call Project Dialog
```

Strangely, i don't see it yesterday

**Comment by Raizo62** [comment]
> Even with commit c93713b you still have the error? Because I installed a debian in a Vbox and don't manage to replicate the issue.

You are perhaps right. I have reload backup of Live Raizo of yesterday (20H23). I don't see your change for this commit.

**Comment by Raizo62** [comment]
> But, now (with version compiled this morning), i can't start GNS3 : i have this error log :

I have do a recompile now. I have always this bug.

**Comment by noplay** [comment]
I just test with the last LiveRaizo it was not working until I update aiohttp . But after that I don't have your issue.

**Comment by Raizo62** [comment]
Yes, now, i can restart GNS3.

But i have always the bug of "Unknown error".
I waited a long time before to add the second VMs (because  i was busy)

**Comment by Raizo62** [comment]
I am waiting 2 minutes between second VM and the "starting all"
[debug8.zip.txt](https://github.com/GNS3/gns3-gui/files/777884/debug8.zip.txt)

**Comment by noplay** [comment]
I just push a commit to gns3 server that lock aiohttp to 1.2.0 can you try. It seem it could be the problem from my last tests

**Comment by Raizo62** [comment]
Super, I don't see the bug with the usual test :-)
I will do others tests to confirm....

**Comment by noplay** [comment]
Thanks

**Comment by noplay** [comment]
I reopen the issue because user complaint of similar issue when their PC is slow

**Comment by noplay** [comment]
I made a lot of tests on my computer trying to make the CPU jump, slow down the network. No real results, request are normally queued and processed.

My current theory is the timeout system is not working well and will raise wrong error when a timeout is triggered.

**Comment by noplay** [comment]
Can you try last gui and last server (the last server use aiohttp  1.3.3). I try to avoid multiple parallel server check and reduce the timeout of server to 15. This should display error faster in case of real issue.

**Comment by Raizo62** [comment]
For info, this week, i don't see this bug again with my students.

Yes, i will try this late afternoon

**Comment by noplay** [comment]
So with our last fix rollback aiohttp the bug disappear for you. We will see if you got it back with last changes.

**Comment by Raizo62** [comment]
I have followed the steps : 
- I create a project called "untitle"
- I put a VMBox called Debian-1, that i connect to ethernet switch.
- I start all.
- I am waiting without to use GNS3 (4 minutes)
- I add a second VMBox (called Debian-2)
- I connect the VMBox to the ethernet switch. 
- The Bug shows

And i have see the bug "Error while getting compute list: Unknown error"

**Comment by Raizo62** [comment]
I have the same bug if i am waiting in front of the dialog box where we choose the name and the folder of the project.

**Comment by noplay** [comment]
Can you test the branch: unknow_error_bug for the server. I disable the keep alive and it seem to work on my debian in virtualbox.

If it's work it's good, because we will have a clear exaplanation of what's wrong: The keep alive is not working in old Qt. And a clean solution: just disable it.


Thanks a lot for the help for tracking this issue

**Comment by Raizo62** [comment]
I have tested with the branch "unknow_error_bug" : No bug error :-D

**Comment by noplay** [comment]
Great thanks a lot !!!!!

**Comment by Raizo62** [comment]
> Great thanks a lot !!!!!

No. Thanks to you to solve bugs :-)
