### ISSUE TITLE
AttributeError: 'TextItem' object has no attribute 'updateNode'

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1850]
Version: 2.0.0b3

When using the GNS3 GUI and adding text and then right clicking text and selecting "Raise one layer", the following is generated in the console:

****** Exception detected, traceback information saved in C:\Users\xxxxx\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\graphics_view.py", line 1350, in raiseLayerActionSlot
AttributeError: 'TextItem' object has no attribute 'updateNode'

**Comment by noplay** [comment]
Hi,

It's fixed in current dev version, but not yet released.

Thanks a lot for the report

Julien
