### ISSUE TITLE
Text Effects (strikeout, underline) not working.

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1851]
Version: 2.0.0b3

Steps to reproduce:

1. Add text to a project.
2. Right click text and select "Text edit".
3. In Text editor dialog, select "Select front".
4. Check either or Strikeout/Underline effects and click OK.
5. Text editor dialog shows text effect.
6. Click OK (or Apply/OK).
7. Text in project is updated with effect.
8. Click something else in project and effect disappears.

No errors shown in console.

**Comment by noplay** [comment]
Fixed.

Note:
Due to limitation of the way we store the property you can't have both enabled (CSS use the same key for underline and strike). But the default font dialog of Qt will allow you enable the two options.
