### ISSUE TITLE
[2.0] : REQ : do snapshot for Qemu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1852]
Hi

For VirtualBox, GNS3 does a snapshot for VM called "reset".

Could you the same with VM of Qemu ?

The linux qemu command is 
`qemu-img -c NameOfSnapshot FileOfVM`

example : 
`qemu-img -c reset projects/untitled/project-files/qemu/e375933f-b2c4-43d2-a97a-4ae09a85eaee/hda_disk.qcow2`

**Comment by Raizo62** [comment]
zut, i forgot the key word "snapshot" :

The linux qemu command is 
`qemu-img  snapshot -c NameOfSnapshot FileOfVM`

example : 
`qemu-img snapshot -c reset projects/untitled/project-files/qemu/e375933f-b2c4-43d2-a97a-4ae09a85eaee/hda_disk.qcow2`

**Comment by noplay** [comment]
I think it's duplicate: https://github.com/GNS3/gns3-gui/issues/796

But why creating a snapshot? We just need to delete the disk and replace it by an empty overlay disk.

**Comment by Raizo62** [comment]
> But why creating a snapshot? We just need to delete the disk and replace it by an empty overlay disk.

Because it is more simple (and more clean ?) :-)
And you don't modify GNS3, then same exactly name, same ports connected, same position, and there are less risk to crash GNS3 :-)
