### ISSUE TITLE
GNS3 2.0.0b3 - Error with VMs

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#1853]
I have created two Windows 7, 64 bits VMs in VMware Workstation 12 and included them in my topology.  The VMs will not boot up in GNSS3 but are up in vmware. 

 Error message - "=> unable to create NIO Ethernet for bridge 'ethernet0.vnet': nio_ethernet_open: unable to open device '\Device\NPF_{4B8D7889-D1FC-4FAA-ABE5-1A44420259FF}': Error opening adapter: The system cannot find the device specified. (20)"  Any help in resolving this issue?

Thanks
![windows 7 vm](https://cloud.githubusercontent.com/assets/17806351/22947636/d2c1ee3c-f2c9-11e6-804e-ffdfb0f185f1.png)
![unable to create nio ethernet for bridge](https://cloud.githubusercontent.com/assets/17806351/22947635/d2c0398e-f2c9-11e6-913a-491b4e5b8363.png)
![bridged interfaces](https://cloud.githubusercontent.com/assets/17806351/22947637/d2c1eeb4-f2c9-11e6-90c3-95585061a59f.png)

**Comment by fatbell** [comment]
![adding windows vm in gns3 2 0 0b3](https://cloud.githubusercontent.com/assets/17806351/22960891/87f61536-f30f-11e6-9392-13d7b77c9341.png)

**Comment by grossmj** [comment]
Have you tried to reboot? Also, check for the presence of VMnet adapters on
Windows.

You can add adapters from GNS3 preferences -> VMware.

**Comment by fatbell** [comment]
I have all 19 vmnet adapters, rebooted twice and still having the same issue.

**Comment by noplay** [comment]
Do you have the last patch installed for VMware ?

**Comment by fatbell** [comment]
I don't think so.  Is the patch from VMware or GNS3?  The VMware version I have is 12.5.2 build-4638234.

**Comment by noplay** [comment]
VMware. 

VMware and GNS3 run under the same user?

**Comment by fatbell** [comment]
Yes

**Comment by noplay** [comment]
Can you try to add more adapters to VMware via the GNS3 preferences / VMware / Network? 

Thanks for the help

**Comment by fatbell** [comment]
No.  I have all 19 VMnet adapters configured.  Thanks for sticking with me

**Comment by fatbell** [comment]
FYI.  I accepted the default server type GNS3 VM - "Run this VMware VM on a romote GNS3 computer"  Is that the correct choice?  Thanks

**Comment by jtorri** [comment]
I am often confused but...it seems you are running GNS3 and VMWARE from Windows.  If true, when you add the Windows VMs via GNS3 Preferences I believe you want to select the option to "Run this VMWARE vm on my local computer".  I am confident someone more knowledgeable will correct me if I am wrong.

**Comment by fatbell** [comment]
I set it up to run on local computer and it worked.  Thanks very much

**Comment by vchandan7** [comment]
Hello Grossmj....Pls help...
Getting below error while connecting Router to cloud using Microsoft loopback address.

****unable to create NIO Ethernet for bridge '611781db-6fd8-43a0-a0a8-042811d2b71a-0': uBridge version 0.9.13 ru**nning with WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Hypervisor TCP control server started (IP 127.0.0.1 port 51679).
UDP tunnel connecting from local port 10001 to IPv4 addresss 127.0.0.1 on port 10000
nio_ethernet_open: unable to open device '\Device\NPF_{F655B058-8DD6-4E72-AD0A-0FA23A8B1136}': Error opening adapter: The system cannot find the device specified. (20)**
