### ISSUE TITLE
"show" GUI console commands

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1855]
Version: 2.0.0b3

I've noticed that the following "show" GNS3 GUI console commands do not work:

> => show run
> Unknown error: 'Topology' object has no attribute 'dump'
> => show gns3vm
> Unknown error: 'ConsoleView' object has no attribute '_show_gnsvm'

**Comment by syndgr** [comment]
As a note, the "show device" and "show device <device name>" commands work.

**Comment by noplay** [comment]
Thanks a lot I removed the commands not compatible with 2.0.
