### ISSUE TITLE
[2.0] Don't start GNS3

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1856]
Hi

I can't start GNS3. 

I start GNS3 without config :

> user@raizo:~$ gns3 --debug
> 2017-02-15 14:50:33 INFO logger.py:107 Log level: DEBUG
> 2017-02-15 14:50:33 INFO main.py:253 GNS3 GUI version 2.0.0dev8
> 2017-02-15 14:50:33 INFO main.py:254 Copyright (c) 2007-2017 GNS3 Technologies Inc.
> 2017-02-15 14:50:33 INFO main.py:256 Application started with /usr/local/bin/gns3--debug
> 2017-02-15 14:50:33 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=0a3c8559-0f6a-40b0-9440-26d86027f47e&aip=1&t=screenview&an=GNS3&av=2.0.0dev8&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.0dev8&cd=Main%20Window&ds=gns3-gui&sr=1920x1080&ul=fr_fr
> 2017-02-15 14:50:33 INFO local_config.py:376 Section GraphicsView has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 DEBUG local_server_config.py:84 Write configuration file /home/user/.config/GNS3/gns3_server.conf
> 2017-02-15 14:50:33 DEBUG local_server_config.py:84 Write configuration file /home/user/.config/GNS3/gns3_server.conf
> 2017-02-15 14:50:33 INFO http_client.py:284 Connection to http://127.0.0.1:3080
> 2017-02-15 14:50:33 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:33 INFO local_config.py:376 Section VPCS has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section Dynamips has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section IOU has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section Qemu has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section VirtualBox has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section VMware has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> 2017-02-15 14:50:33 INFO local_config.py:376 Section Docker has missing default values. Adding keys  Saving configuration
> 2017-02-15 14:50:33 INFO local_config.py:271 Configuration save to /home/user/.config/GNS3/gns3_gui.conf
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> QXcbConnection: XCB error: 145 (Unknown), sequence: 162, resource id: 0, major code: 139 (Unknown), minor code: 20
> 2017-02-15 14:50:33 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=0a3c8559-0f6a-40b0-9440-26d86027f47e&aip=1&t=screenview&an=GNS3&av=2.0.0dev8&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.0dev8&cd=Main%20Window&ds=gns3-gui&sr=1920x1080&ul=fr_fr
> 2017-02-15 14:50:33 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=0a3c8559-0f6a-40b0-9440-26d86027f47e&aip=1&t=screenview&an=GNS3&av=2.0.0dev8&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.0dev8&cd=Setup%20Wizard&ds=gns3-gui&sr=1920x1080&ul=fr_fr
> 2017-02-15 14:50:33 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:33 DEBUG http_client.py:306 Retry connection to http://127.0.0.1:3080
> 2017-02-15 14:50:34 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:34 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:34 DEBUG http_client.py:306 Retry connection to http://127.0.0.1:3080
> 2017-02-15 14:50:35 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:35 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:35 DEBUG http_client.py:306 Retry connection to http://127.0.0.1:3080
> 2017-02-15 14:50:36 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:36 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:36 DEBUG http_client.py:306 Retry connection to http://127.0.0.1:3080
> 2017-02-15 14:50:37 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:37 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:37 DEBUG http_client.py:306 Retry connection to http://127.0.0.1:3080
> 2017-02-15 14:50:38 DEBUG http_client.py:449 GET http://127.0.0.1:3080/v2/version {}
> 2017-02-15 14:50:38 DEBUG http_client.py:546 Response error: Connection refused for http://admin@127.0.0.1:3080/v2/version (error: 1)
> 2017-02-15 14:50:43 DEBUG local_server_config.py:84 Write configuration file /home/user/.config/GNS3/gns3_server.conf
> 2017-02-15 14:50:43 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'admin'
> 2017-02-15 14:50:43 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'admin'
> 2017-02-15 14:50:43 DEBUG http.py:34 Synchronous get http://127.0.0.1:3080/v2/version with user 'admin'
> 2017-02-15 14:50:43 INFO local_server.py:460 Starting local server process with "/usr/local/bin/gns3server" --local --debug --log="/home/user/.config/GNS3/gns3_server.log" --pid="/home/user/.config/GNS3/gns3_server.pid"
> 2017-02-15 14:50:43 INFO local_server.py:473 Local server process has started (PID=2415)
> 2017-02-15 14:50:43 DEBUG progress_dialog.py:98 WaitForConnectionWorker thread started
> /usr/local/lib/python3.4/dist-packages/raven/conf/remote.py:90: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
>   warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
> 2017-02-15 14:51:13 CRITICAL progress_dialog.py:159 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 2017-02-15 14:51:14 CRITICAL __init__.py:110 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 9, in <module>
>     load_entry_point('gns3-gui==2.0.0.dev8', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 288, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1029, in startupLoading
>     self._setupWizardActionSlot()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 777, in _setupWizardActionSlot
>     res = setup_wizard.exec_()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/dialogs/setup_wizard.py", line 323, in validateCurrentPage
>     LocalServer.instance().updateLocalServerSettings(local_server_settings)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 258, in updateLocalServerSettings
>     self.localServerAutoStartIfRequire()
>   File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 346, in localServerAutoStartIfRequire
>     if not progress_dialog.exec_():
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 240, in func_wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/gns3/utils/progress_dialog.py", line 160, in _error
>     QtWidgets.QMessageBox.critical(self.parentWidget(), "Error", "{}".format(message))
>   File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 110, in critical
>     log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 2017-02-15 14:51:16 DEBUG progress_dialog.py:104 WaitForConnectionWorker thread canceled
> 2017-02-15 14:51:16 DEBUG progress_dialog.py:128 WaitForConnectionWorker thread is being destroyed
> 2017-02-15 14:51:16 DEBUG progress_dialog.py:135 WaitForConnectionWorker thread destroyed
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007f45a9bd8700 (most recent call first):
>   File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 346 in localServerAutoStartIfRequire
>   File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 258 in updateLocalServerSettings
>   File "/usr/local/lib/python3.4/dist-packages/gns3/dialogs/setup_wizard.py", line 323 in validateCurrentPage
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 777 in _setupWizardActionSlot
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1029 in startupLoading
>   File "/usr/local/lib/python3.4/dist-packages/gns3/main.py", line 288 in main
>   File "/usr/local/bin/gns3", line 9 in <module>
> zsh: segmentation fault  gns3 --debug
>

**Comment by noplay** [comment]
I push a potential fix for the segfault.
