### ISSUE TITLE
2/15 build doesn't appear to start local server or GNS VM

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1857]
After installing latest build, I face the following error and the local and GNS VM doesn't appear to have started.

=> WaitForConnectionWorker thread stopping with an error: Could not connect to 10.1.66.50 on port 3080: [WinError 10061] No connection could be made because the target machine actively refused it
Could not connect to 10.1.66.50 on port 3080: [WinError 10061] No connection could be made because the target machine actively refused it


![image](https://cloud.githubusercontent.com/assets/6335629/22983029/d63c3cf2-f36e-11e6-9649-a861afc1ceac.png)

**Comment by codeassassin** [comment]
![image](https://cloud.githubusercontent.com/assets/6335629/22983154/3ccc89cc-f36f-11e6-8d66-94ed9fd31610.png)

**Comment by codeassassin** [comment]
[2-15builderror.zip](https://github.com/GNS3/gns3-gui/files/777580/2-15builderror.zip)

rolling back to 2-14...

**Comment by codeassassin** [comment]
Rolling back resolved...

![image](https://cloud.githubusercontent.com/assets/6335629/22983390/f9578880-f36f-11e6-886a-93fb89bb5240.png)

**Comment by noplay** [comment]
I think 2 16 will work. A dependencies pushed a broken change and it seem working now.

**Comment by codeassassin** [comment]
Yes, the latest nightly build has successfully resolved this issue. Thanks again.
