### ISSUE TITLE
Export configs to directory causes exception/traceback.

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1859]
Version: 2.0.0b3

When using "Tools > Import/Export node configs" and selecting export configs to a directory, configs from nodes are exported but the GNS3 GUI logs an exception/traceback.

Example:

> GNS3 management console.
> Running GNS3 version 2.0.0b3 on Windows (64-bit) with Python 3.5.2 Qt 5.7.1 and PyQt 5.7.1.
> Copyright (c) 2006-2017 GNS3 Technologies.
> Use Help -> GNS3 Doctor to detect common issues.
> 
> => ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()
> 
> ****** Exception detected, traceback information saved in C:\Users\xxxxxx\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\http_client.py", line 589, in _processResponse
>   File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
>   File "./gns3-gui\gns3\modules\iou\iou_device.py", line 228, in _exportConfigToDirectoryCallback
> TypeError: object of type 'NoneType' has no len()

**Comment by noplay** [comment]
Can you test with 2.0.0b4 (not yet announced)

https://github.com/GNS3/gns3-gui/releases/tag/v2.0.0b4

Thanks for the help

**Comment by syndgr** [comment]
More than happy to test and provide feedback but I'm running GNS3VM, so assume I'd need to update that from the menu in the usual way? Or is the GUI backwards compatible (GUI == 2.0.0b4, GNS3VM == 2.0.0b3)?

**Comment by noplay** [comment]
Yes update the VM the VM will upgrade to 2.0.0dev9 but don't worry it's
compatible.

**Comment by noplay** [comment]
Confirmed it's fixed in last version
