### ISSUE TITLE
gns3-gui won't start on Cinnamon

### ISSUE THREAD

**Issue by geeMc** [GNS3/gns3-gui#1860]
Hi,

Recently I tried to install GNS3 on my Arch Linux mediacenter, running Cinnamon. The GUI wouldn't start, even when trying various versions (for example 1.5.3 and 2.0.0b3). I attached the output of `gns3 --debug` and an strace output at the bottom of the report (these outputs were with the package versions below).

I wanted to reproduce this error on another machine, and successfully did. I also tried starting the gui on the same machines with KDE and that does work. 

If you want to reproduce it yourself, install a clean ArchLinux with the packages below. Xorg doesn't log anything. Both machines in a nutshell:

- Intel Core i5 4590, using onboard graphics with xf86-video-intel
- Intel Core i5 6600K, GeForce GTX960 with proprietary nvidia driver

I tried to downgrade and upgrade some packages, like qt5, gns3-gui/server, linux and the pyqt packages, but haven't found any combo that would work. The output is the same every time, please see the attachments.

gns3-server 1.5.3
gns3-gui 1.5.3
qt5-base 5.8.0-5
pyqt5-common 5.7.1-3
python-pyqt5 5.7.1-3
cinnamon 3.2.8-1
xorg-server 1.19.1-1
linux 4.9.7-1

Other QT programs (e.g. Telegram) work fine.

If you need any more information, please let me know!

Thanks in advance for your time :)

[gns3.strace.txt](https://github.com/GNS3/gns3-gui/files/781610/gns3.strace.txt)
[gns3.debug.txt](https://github.com/GNS3/gns3-gui/files/781612/gns3.debug.txt)

**Comment by noplay** [comment]
qt5-base 5.8.0-5
pyqt5-common 5.7.1-3
python-pyqt5 5.7.1-3

It seem invalid you have pyqt5.7 with a Qt 5.8

**Comment by geeMc** [comment]
Yeah I noticed that and tried to rectify the versions there. Downgrading qt5 to the same version as the pyqt packages results in the same errors.

**Comment by noplay** [comment]
Sound like it's the same issue:
https://github.com/ContinuumIO/anaconda-issues/issues/1323

A trouble with HDPI support.

Could you try edit the file gns3/application.py

And remove this line:
self.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

Thanks

**Comment by geeMc** [comment]
Hi,

I commented out the line and the GUI starts now. Thanks very much for you help!

**Comment by noplay** [comment]
We will add an option to enable or not the HDPI mode.
