### ISSUE TITLE
[2.0] Issue with symbol firefox.svg

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1866]
With v1.5 the firefox symbol https://github.com/GNS3/gns3-registry/blob/master/symbols/firefox.svg works fine.
![firefox_1 5](https://cloud.githubusercontent.com/assets/896406/23077617/97adaf6a-f545-11e6-86c0-2bf47d713d3a.png)

With v2.0beta4 the firefox symbol works in the device sidebar, but in the project area it is replaced by the computer.svg symbol.
![firefox_2 0](https://cloud.githubusercontent.com/assets/896406/23077681/e361674e-f545-11e6-86c2-4895b56f29e5.png)

What I did:
Removed all traces of current GNS3 installation, downloaded GNS3, freshly installed it, added a 3725 router and changed the symbol to firefox.

All went smooth, the symbol selector shows the firefox, the image symbol in the preferences and in the devices sidebar are showing the correct firefox. Only (on 2.0) when I move the device from the sidebar to the project area, it changes to computer.svg, also in the .gns3 file it uses this computer.svg symbol.

When I copy another custom icon, e.g. ostinato-3d-icon.svg, to the firefox.svg file, then I can use the firefox.svg normally. So it seems that the firefox.svg has some strange attribute, that irritates V2.0

**Comment by noplay** [comment]
Perhaps related: https://github.com/GNS3/gns3-server/issues/908

**Comment by noplay** [comment]
I see the same behavior it's blink and go back to computer

**Comment by noplay** [comment]
Interresting firefox.svg is not a true SVG it's png embed in a .svg this doesn't seem to be an issue when the svg from a png is generated by GNS3 but in this case something goes wrong after loading.

**Comment by ehlers** [comment]
1.5 and 2.0b4 use the same QT (5.6.0) so I would expect, that they behave the same.

**Comment by noplay** [comment]
Fixed it was the server failing to extract the size from the svg file
