### ISSUE TITLE
[2.0.0b4] Unable to open projects with IOU created in 1.5.3

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1868]
Hi, 

when I open projects from 1.5.3 on 2.0.0b4, the file is converted with no errors. However all IOU devices change icons to PC (null) and all interfaces change names incorrectly. 

I tried to manually edit the file, but I could not make it work properly. I just started the project from scratch. But I wanted to report it...

Windows 10/GNS3 2.0.0b4
Sairus

After conversion:
                },
                "name": "IOU1",
                "node_id": "99399dc5-33ba-44d7-b506-edd78fb6fbe2",
                "node_type": "iou",
                "port_name_format": **"Ethernet{0}",**
                "port_segment_size": 0,
                "properties": {
                    "ethernet_adapters": 4,
                    "l1_keepalives": false,
                    "md5sum": "3020c63259dd3fc7b8eaf66855ebf2a1",
                    "nvram": 128,
                    "path": "image.bin",
                    "ram": 256,
                    "serial_adapters": 0,
                    "startup_config": "startup-config.cfg",
                    "use_default_iou_values": true
                },
                **"symbol": null,**
                "x": -165,
                "y": -77,
                "z": 1
            },

WHen I create a new project with IOU the format is correct:
  },
                "name": "IOU1",
                "node_id": "bf9b43f0-c001-4462-b2f1-51fa4b11327b",
                "node_type": "iou",
                **"port_name_format": "Ethernet{segment0}/{port0}",**
                "port_segment_size": 4,
                "properties": {
                    "ethernet_adapters": 4,
                    "l1_keepalives": false,
                    "md5sum": "3020c63259dd3fc7b8eaf66855ebf2a1",
                    "nvram": 128,
                    "path": "image.bin",
                    "private_config": null,
                    "private_config_content": null,
                    "ram": 256,
                    "serial_adapters": 0,
                    "startup_config": "startup-config.cfg",
                    "startup_config_content": "*removed*",
                    "use_default_iou_values": true
                },
                **"symbol": ":/symbols/multilayer_switch.svg",**
                "width": 51,
                "x": 124,
                "y": 276,
                "z": 1
            },

**Comment by noplay** [comment]
Can you share your .gns3 before conversion? 

Thanks

**Comment by sairuscz** [comment]
[project.gns3.txt](https://github.com/GNS3/gns3-gui/files/787001/project.gns3.txt)
Here it is as I saved it in 153.

**Comment by noplay** [comment]
I think the syntax for the port name format is Ethernet{segment0}/{port0}. I will fix the conversion process

**Comment by sairuscz** [comment]
When I manually edited the IOU devices with **"port_name_format": "Ethernet{segment0}/{port0}"** , the interfaces were named as Ethernet0/0, Ethernet1/1, Ethernet2/2 and so on. While these IOU devices actually have modules installed, each with four interfaces. The interface names should be Ethernet0/0, Ethernet0/1, Ethernet0/2...Ethernet4/0, Ethernet4/1 and so no depending on the number of modules. 

It works great in new projects created in 2.0.0b4 but not after conversion from 153.

**Comment by noplay** [comment]
port_segment_size should be 4

**Comment by noplay** [comment]
The original file was created with which version of GNS3?

**Comment by noplay** [comment]
Thanks for the report I fixed the conversions issues.

**Comment by sairuscz** [comment]
Yes, I missed that. port_segment_size should be 4 - Thanks.
The original was created in 1.5.3.
