### ISSUE TITLE
[2.0.0b4] Project rarely crashes when adding a link to cloud

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1869]
Hi,

it happened to me twice already that when I am adding a link to cloud, I keep seeing the "please wait" loading bar for a while. However once the attempt times out, the entire project crashes as show on picture below. 

I am also not able to cancel the request. When I try to close the loading bar window, it reopens again. I basically know it's going to crash but cannot prevent it. 

![capture](https://cloud.githubusercontent.com/assets/24818591/23101552/504f19e6-f6ea-11e6-9230-6ef9b798cf88.PNG)

Windows 10/2.0.0b4
Thanks
Sairus

**Comment by noplay** [comment]
The error say error while deleting link, but your bug report is about adding a link to a cloud. Is it correct?

**Comment by sairuscz** [comment]
It happens in both cases. Had this 4 times already while adding and removing. It may be related to issue #1867 . Perhaps if the uBridge crash issue with trunks is resolved, this will stop happening as well.

**Comment by noplay** [comment]
Oh yes it's possible that it's related

**Comment by noplay** [comment]
I think it's fixe you will be able to test with the next release, that should be released soon.


Thanks for the report
