### ISSUE TITLE
Clean the old -files directory during topology upgrade

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#188]

**Comment by noplay** [comment]
i just check and it should not happend because we move the  files:
https://github.com/GNS3/gns3-server/blob/asyncio/gns3server/modules/base_manager.py#L174

Can you confirm @grossmj ?

**Comment by grossmj** [comment]
Indeed the VM dirs are moved, this is just empty <project_name>-files/<module_name> directories that are left. I would say just leave them there, just in case a user stored other things in that folder or a conversion has failed.

**Comment by noplay** [comment]
We can check if dir is empty before deleting it
Le 25 févr. 2015 17:12, "Jeremy Grossmann" <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
OK, let's do this :+1:

**Comment by dlintott** [comment]
I haven't really dug into the code, so maybe you can answer it quicker... How does this change of -files directory affect gns3-converter?

**Comment by noplay** [comment]
No impact :)

We take care of the migration in the server.

An old project will be convert by gns3-converter and after that the server
will make the migration to the new format.

On Wed, Feb 25, 2015 at 5:55 PM, Daniel Lintott <notifications@github.com>
wrote:

> I haven't really dug into the code, so maybe you can answer it quicker...
> How does this change of -files directory affect gns3-converter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/188#issuecomment-76000701>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by noplay** [comment]
We do that in the server because some information is missing for gns3
converter to do the conversion.

On Wed, Feb 25, 2015 at 6:11 PM, Julien Duponchelle <julien@gns3.net> wrote:

> No impact :)
>
> We take care of the migration in the server.
>
> An old project will be convert by gns3-converter and after that the server
> will make the migration to the new format.
>
> On Wed, Feb 25, 2015 at 5:55 PM, Daniel Lintott <notifications@github.com>
> wrote:
>
>> I haven't really dug into the code, so maybe you can answer it quicker...
>> How does this change of -files directory affect gns3-converter?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GNS3/gns3-gui/issues/188#issuecomment-76000701>.
>>
>
>
>
> --
>
> *JULIEN DUPONCHELLE*
> Software Engineer
>
> E: julien@gns3.com
> LinkedIn <http://linkedin.com/in/julienduponchelle/>
>
> <http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
> Calgary, AB, T2T 2X5
> Twitter <http://www.twitter.com/gns3_official> | Facebook
> <https://www.facebook.com/gns3official> | LinkedIn
> <http://www.linkedin.com/company/gns3-net> | Google+
> <https://plus.google.com/+Gns3Net/posts> | CrunchBase
> <http://www.crunchbase.com/organization/gns3>
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by dlintott** [comment]
Okay, thanks for that :)

**Comment by noplay** [comment]
Done :)

**Comment by noplay** [comment]
It was on server side
