### ISSUE TITLE
2.0: IOU capture on serial line uses wrong ethernet encapsulation

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1886]
GNS3 version 2.0.0dev9 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

Capturing traffic on a serial link works fine on IOS (local and remote), but on IOU it captures always with encapsulation ethernet. Therefore it's not really useful.

Here an example of a capture:
![wireshark_bad_encap](https://cloud.githubusercontent.com/assets/896406/23263662/335a5786-f9df-11e6-8a00-009bd7666ea5.png)

When I manually change the encapsulation (editcap -T chdlc input_file output_file) I get a correct display
![wireshark_chdlc](https://cloud.githubusercontent.com/assets/896406/23263716/60a660fe-f9df-11e6-8e4f-f42567a3ba2e.png)

You can see, that the data is identical, the capture is working fine. But the encapsulation is incorrectly set in the original capture file header to ethernet instead of the serial encapsulation (cisco hdlc in my example).

**Comment by noplay** [comment]
Can you provide the logs using Export Debug Informations. It's supposed to work. 
I fixed it in the past:
https://github.com/GNS3/gns3-gui/issues/1799

Your IOU run in the GNS3 VM or it's a Linux Box?

**Comment by ehlers** [comment]
I've retested with the official GNS3Beta4 image and the GNS3VM, both freshly installed and I have also this problem.

I've enabled debug both locally and in the GNS3VM.
[capture_iou.zip](https://github.com/GNS3/gns3-gui/files/797450/capture_iou.zip)
[gns3_vm.log.txt](https://github.com/GNS3/gns3-gui/files/797451/gns3_vm.log.txt)

**Comment by noplay** [comment]
Ok thanks i discover I missed a case
