### ISSUE TITLE
GNS3 client re-connect needs better management

### ISSUE THREAD

**Issue by ryangurazov** [GNS3/gns3-gui#1887]
1. Deployed GNS3 VM 
2. Configured GNS3 client to connect to GNS3 VM
3. Deleted GNS3 VM
4. Re-deployed new GNS3 VM
5. Started GNS3 client and now it is stack in retry cycles although there is connection error 

![image](https://cloud.githubusercontent.com/assets/23531484/23274547/fbf457aa-f9b7-11e6-9f18-41a85ed4d075.png)

and re-connect's popup is interfering with all other operations

![image](https://cloud.githubusercontent.com/assets/23531484/23274691/885ad8ea-f9b8-11e6-8d49-868410f6eb8f.png)

**Comment by noplay** [comment]
Which version of GNS3 are you using?

**Comment by ryangurazov** [comment]
It is 2.0.0.b4 (Beta 4).
I was able to solve this problem.
Something has to do with the way OK & Accept buttons are working in preferences of GNS3 client.

Here is what I ended up doing to get through this as I recall it:
1. Removed Remove GNS VM
2. Remove Server
3. Removed all projects

For each of this steps made sure:
a) to avoid using Apply, rather used OK.
b) did Quit from GNS3 client and then run it again.

4. After it is all was cleared, delete VM
5. Provisioned new VM

6. Added Remote Server
7. Configured VM by referring to Remote Server

For each of this steps made sure:
a) to avoid using Apply, rather used OK.
b) did Quit from GNS3 client and then run it again.

Then after going through these steps all started working normally.

There seems to be some disconnect on the Client if VM gets reconfigured (deleted/re-added).
Plus it is not clear why Apply did not keep changes.

You might want to look into making Client - Server (VM) communication less rigid so that after number of failures to connect it errors out with the clear message (and probably suggested steps to correct the problem).

**Comment by noplay** [comment]
What do you have in server preference / main server?

**Comment by ryangurazov** [comment]
I don't have a screenshot for that that VM, but as part of the changes I also updated it and was pointing to updated IP address (it looks like I forgot to mention that, sorry):

![image](https://cloud.githubusercontent.com/assets/23531484/23381969/5b492cd6-fcf5-11e6-8928-f5bff2a9e791.png)

As I said, what it is needed is some sort of enhancement that would try to reconnect only certain number of times and time out with some message that would allow to understand where and what to fix/check/address.

**Comment by noplay** [comment]
I think their is a misunderstanding. When you use a remote main server you probably don't need the GNS3 VM. I try to add more security around that in next build. 

Especially the GNS3 VM must not be the same server as the main server in the configuration otherwise GNS3 will be confused

**Comment by noplay** [comment]
The experience is improved

Thanks
