### ISSUE TITLE
[2.0] Bug : rename IOU

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1889]
Hi

I put on the lab a IOU. The default name is Switch-L3-1
I rename it to Plane
I start all

If i do all that without waiting,  the name in the switch is always Switch-L3-1 (on the switch, and in the file of the project)

If i do all that more slowly,  the name is good.

I can't reproduce each time, but very often (this day to verify). I suppose that i was more or less speed.
I do it on Live Raizo in VirtualBox. It is perhaps more slow (but no enough for to feel it)

**Comment by noplay** [comment]
It's the kind of trouble solve by https://github.com/GNS3/gns3-gui/pull/1835 in 2.1

From what I see the client when it's too fast will send multiple query creating confusion.

I will try to improve the code server side to handle that.

**Comment by noplay** [comment]
Ok it's fixe now we patch the config file even if hostname are not sync.
