### ISSUE TITLE
Please wait window after successful importing appliance

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1891]
After importing an ASA appliance, a window pops up asking me to please wait. There is some infinite loop, and now I am waiting forever................

![image](https://cloud.githubusercontent.com/assets/6335629/23335744/a0989cb2-fb89-11e6-99db-1a277f323097.png)

**Comment by noplay** [comment]
I think it's fix in last code version. We will release a version soon with it.
