### ISSUE TITLE
[2.0.0b4] Local server crashes

### ISSUE THREAD

**Issue by KeVI121** [GNS3/gns3-gui#1897]
About 5 minutes after installing GNS3 2.0b4  the local server crashes and the project closes but the console windows of the devices that were running are stay open which I can still access the devices. 

**This is the error message I am getting from the console of GNS3:** 

****** Exception detected, traceback information saved in C:\Users\kallamby.local\AppData\Roaming\GNS3\exceptions.log ****** 

PLEASE REPORT ON https://www.gns3.com 

Traceback (most recent call last): 
File "./gns3-gui\gns3\progress.py", line 116, in update 
File "./gns3-gui\gns3\progress.py", line 178, in show 
RuntimeError: wrapped C/C++ object of type QProgressDialog has been deleted

**Comment by noplay** [comment]
I think the errors is fixed in dev version you will be able to test at next release.

Thanks
