### ISSUE TITLE
Show in file manager option for clouds powered by uBridge

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1900]
It is currently not possible to see the working directory of a cloud using right click and "Show in file manager" option. This would be useful to check ubridge.log.

![node_no_working_dir](https://cloud.githubusercontent.com/assets/4752614/23582546/e8d8f8a4-00e9-11e7-9bde-fac7ad21a0e2.png)

**Comment by noplay** [comment]
Added
