### ISSUE TITLE
 Client version 1.5.3 differs with server version 2.0.0b4 in the GNS3 VM, please upgrade the VM by selecting the Upgrade options in the VM menu.

### ISSUE THREAD

**Issue by ferdibulbul** [GNS3/gns3-gui#1901]
Hello,
I use GNS3 version 1.5.3 and GNS3-VM 2.0.0b4. I upgraded GN3-VM 2 times, but still i get the error below. Are these versions not suitable each other?

" Client version 1.5.3 differs with server version 2.0.0b4 in the GNS3 VM, please upgrade the VM by selecting the Upgrade options in the VM menu."

**Comment by ferdibulbul** [comment]
I tried all version only GNS3 VM version 1.5 works properly.

![1](https://cloud.githubusercontent.com/assets/20127332/23583747/06ccb2a0-0145-11e7-85a4-ea6aaf5a1b47.JPG)

**Comment by noplay** [comment]
Hi,

You need to use the same version for GNS3 and the GNS3 VM. If you have a 1.5 client you need an 1.5 VM.
