### ISSUE TITLE
GNS3 VM preferences are lost.

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1909]
Running GNS3 version 2.0.0rc1 on Windows (64-bit) with Python 3.6.0 Qt 5.8.0 and PyQt 5.8.

Since upgrading from 2.0.0b4 to rc1, the GNS3 VM preferences are lost:

Steps for me to reproduce:

1. Open GNS3 GUI.
2. Open Preferences.
3. Tick "Enable the GNS3 VM".
4. Set RAM to 6348 MB.
5. Set vCPU to 2.
6. Click OK (see first screenshot)
7. GNS3 VM starts.
8. Wait for GNS3 VM to boot.
9. Close GNS3 GUI, wait for GNS3 VM to shutdown/exit.
10. Start GNS3 GUI.
11. GNS3 VM does not start.
12. View GNS3 VM preferences to find they have been reset (see second screenshot).

Configured preferences:
![image](https://cloud.githubusercontent.com/assets/20760738/23676037/3be9c948-0373-11e7-87a4-8aab1c471b1e.png)

Preferences afterwards:
![image](https://cloud.githubusercontent.com/assets/20760738/23676158/abdab5dc-0373-11e7-8fe8-e0824f188d75.png)

**Comment by syndgr** [comment]
I'm unsure if this is related at all but when viewing the available VMs, the GNS3 VM appears twice. I'm not sure if this is significant or not (probably not):

![image](https://cloud.githubusercontent.com/assets/20760738/23676389/78ea03c0-0374-11e7-9b6e-de0fa807b58e.png)

VMWare Workstation Player only shows 1 VM named "GNS3 VM":

![image](https://cloud.githubusercontent.com/assets/20760738/23676420/8ff7037e-0374-11e7-95f8-207c2431d3d3.png)

**Comment by jtorri** [comment]
syndgr 
Wonder if a different outcome would result if you clicked on "Apply"  before clicking on "OK".  Then, perhaps you did.

**Comment by jtorri** [comment]
GNS3 management console.
Running GNS3 version 2.0.0rc1 on Windows (64-bit) with Python 3.6.0 Qt 5.8.0 and PyQt 5.8.
GNS3 VM from GNS3 2.0.0rc1

Well now, I once again "spoke" too soon.  I am having the same problem as listed above by syndgr.  In addition, when stop a topology and then close the GNS3 application, it hangs and never shuts down the GNS3 VM.  I have to use task manager to close GNS3 application and then "manually" shut down the GNS3 VM.  
Thanks.

**Comment by adecisco** [comment]
I have this same issues. If we can get a patch for the fix it will be great.

Thanks.

**Comment by noplay** [comment]
Thanks for the report the bug was fixed yesterday:
https://github.com/GNS3/gns3-server/issues/926

You can get nightly build with the fix here:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-03-07/2.0/

**Comment by noplay** [comment]
Sound like the build machine just decide to corrupt the binary...

**Comment by adecisco** [comment]
Okay, let's know when the new fix is ready.

**Comment by noplay** [comment]
Could you test this build?
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-03-10/2.0/GNS3-2.0.2017-03-10-all-in-one.exe/download

**Comment by adecisco** [comment]
This works thanks.
