### ISSUE TITLE
REQ: option to start automatically vnc/telnet

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1910]
Hi

When you use VirtualBox VM without headless mode, GNS3 (VirtualBox) shows the GUI.

If we replace the same VMBox in QEmu, we must double-click on the device to see the GUI.
My students are suprised and they think that the VM is not started (crashed ?)

Can we have an option for each QEmu VM  to indicate to GNS3 to start the vnc/telnet immediately after the starting of the VM ?

**Comment by Raizo62** [comment]
yes, it is better....

**Comment by grossmj** [comment]
Implemented

**Comment by grossmj** [comment]
Yes, you are probably right. I will deactivate by default then.
