### ISSUE TITLE
Feature Request - Ability to load project file from gns3-server

### ISSUE THREAD

**Issue by mcaulifn** [GNS3/gns3-gui#1911]
Is it possible to load a project file from the gns3-server rather from a folder accessible to the gui client only? Use case would be a single server but multiple gui clients that all need to access the same set of topologies.

**Comment by noplay** [comment]
It's a new feature of 2.0 ;)
http://docs.gns3.com/1K_OVfincey0cUw6CP4dWVgs_pBXMdIJ6gdFGjNy8EZQ/index.html
