### ISSUE TITLE
Add a variable to the custom console tool to expose the UUID of the QEMU VM

### ISSUE THREAD

**Issue by ianc1215** [GNS3/gns3-gui#1918]
I was looking to use virt-viewer to access QEMU VMs on my Linux workstation GNS3 instance. The issue is I need to pass the UUID of the VM to virt-viewer in order for it to connect. From the options available there is not one to pass the UUID.

Could this be added in order to expand the options for connecting to QEMU VMs?

**Comment by noplay** [comment]
I'm not sure that virt-viewer use the same UUID use by GNS3, but we can expose it.
