### ISSUE TITLE
Shortcuts don't work in GNS3 console

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#192]
Cannot do CTRL+C etc. to copy some text.

**Comment by noplay** [comment]
Perhaps related to https://bugreports.qt.io/browse/QTBUG-43596

I will try to update to QT 5.4.1

**Comment by noplay** [comment]
It's not that, perhaps it's related to our console implementation

**Comment by grossmj** [comment]
Yep I think so too. Don't worry, this isn' urgent, we must have had this bug since the beginning of GNS3 ;)

**Comment by noplay** [comment]
Fixed, the only downside you can cut everything
