### ISSUE TITLE
Remote main server - Appliance import issue

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1923]
GNS3 version 2.0.0rc2 on Windows (64-bit) with Python 3.6.0 Qt 5.8.0 and PyQt 5.8.

After importing appliance, device is not shown but does exist (trying to re-import the appliance says the name is already in use).

1. File > Import appliance.
2. Run through import wizard.
3. Success message is displayed.
4. Go to Edit > Preferences and navigate to Qemu VMs. No devices are shown:
![image](https://cloud.githubusercontent.com/assets/20760738/23851722/68a58a68-07dc-11e7-80a2-c119dafc7a53.png)
5. On remote main server, check /opt/gns3/images/QEMU and confirm image and md5sum files are there (issue #1915 now happens - have to quit GNS3 GUI at this point).
6. Attempt to re-import the appliance again.
7. "The name "NETem 0.4" is already used by another appliance" is shown:
![image](https://cloud.githubusercontent.com/assets/20760738/23851820/bf02e086-07dc-11e7-95ce-558b9b2e32c6.png)
8. Provide an alternative name when prompted (e.g. Foo-3).
9. Success (issue #1915 now happens - have to quit GNS3 GUI at this point).
10. Go to Edit > Preferences and navigate to Qemu VMs. No devices are shown:
![image](https://cloud.githubusercontent.com/assets/20760738/23851722/68a58a68-07dc-11e7-80a2-c119dafc7a53.png)

On the remote main server, if I check /home/gns3/.config/GNS3/gns3_controller.conf there is no reference to the QEMU device important.

On the machine I am running the GNS3 GUI from, if I check %appdata%\GNS3\profiles\Remote\gns3_gui.ini I see "NETem 0.4" and also "Foo-3" QEMU names listed.

**Comment by syndgr** [comment]
**Issue 3: Dynamips images are not uploaded to remote main server**

Easy to reproduce. Under Preferences, add a new Dynamips device and select image. The image is not uploaded to the remote main server. The Dynamips device references the local image:

![image](https://cloud.githubusercontent.com/assets/20760738/23852350/3985d4ba-07df-11e7-8d1c-43a2b5562c18.png)
![image](https://cloud.githubusercontent.com/assets/20760738/23852356/43f99b48-07df-11e7-8559-821c9cce575b.png)

(see also: https://www.gns3.com/qa/gns3-v2-0-0-rc1-esxi-remote-main)

**Issue 4: IOU images are not uploaded to remote main server.**

Similar to the above:

![image](https://cloud.githubusercontent.com/assets/20760738/23852417/8e4b269e-07df-11e7-8e7e-52283d16a3fe.png)

![image](https://cloud.githubusercontent.com/assets/20760738/23852435/a41c1b18-07df-11e7-8775-e3dc5afd458f.png)

Now check /opt/gns3/images/IOU on the remote main server and the IOU image is not there:

![image](https://cloud.githubusercontent.com/assets/20760738/23852452/c25a8272-07df-11e7-9be3-905ebe72db90.png)

**Comment by noplay** [comment]
Hi, 

Please open one issue by bug, it's more simple to track the issues and github don't allow us to split an issue.

Thanks

**Comment by syndgr** [comment]
Sorry. Let me open individual bugs and clean this one up. Thanks.

**Comment by noplay** [comment]
Thanks a lot
