### ISSUE TITLE
Export portable project does not export all base images

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1928]
GNS3 version 2.0.0rc2 on Windows (64-bit) with Python 3.6.0 Qt 5.8.0 and PyQt 5.8.

This is using GNS3 GUI and GNS3 VM. VM version is actually 2.0.0b4 and GUI is 2.0.0rc2. But I have tried this with GNS3 GUI and GNS3 VM versions 2.0.0b4, 2.0.0rc1 and 2.0.0rc2.

I have a project which makes use of Dynamips, IOU and QEMU images. When I use the "Export portable project" function and I select Yes to export base images, a .gns3project file is produced and no errors are displayed.

If I open the .gns3project file using 7-Zip, the images directory only contains the Dynamips image:

![image](https://cloud.githubusercontent.com/assets/20760738/23854401/29d4ec22-07e9-11e7-95eb-26ca27f8032e.png)
![image](https://cloud.githubusercontent.com/assets/20760738/23854429/556f8de2-07e9-11e7-9d3c-70b20a129ab1.png)

The project-files directory does contain Dynamips, IOS and QEMU data. For example:

![image](https://cloud.githubusercontent.com/assets/20760738/23854448/79985b68-07e9-11e7-9636-d3e9f944bf88.png)
![image](https://cloud.githubusercontent.com/assets/20760738/23854478/9146a008-07e9-11e7-9b91-2ed9a16dd864.png)
![image](https://cloud.githubusercontent.com/assets/20760738/23854505/a532e7b6-07e9-11e7-9ff4-477b26e868a7.png)

When trying to import this portable project I get the following error:

ImportProjectWorker thread stopping with an error: Could not import the project: [Errno 13] Permission denied: 'None' 
Could not import the project: [Errno 13] Permission denied: 'None' 

I'm wondering if this error happens because some of the base images are missing?

**Comment by syndgr** [comment]
GNS3 GUI full debug when trying to import project: http://pastebin.com/raw/660jh0MS

**Comment by noplay** [comment]
What is the permissions of your images directory?

**Comment by syndgr** [comment]
On the GNS3 VM /opt/gns3/images is chmod 755 and chown gns3:gns3.

![image](https://cloud.githubusercontent.com/assets/20760738/23855118/67b6cfda-07ec-11e7-8120-5715f6d33f6d.png)

**Comment by noplay** [comment]
Could you export the project and go to the GUI menu Help / Export  Debug informations and send me the zip and the resulting exported project to julien@gns3.net

Thanks a lot for the help

**Comment by syndgr** [comment]
Email sent.

**Comment by noplay** [comment]
Thanks I found the issue. 

If you don't have a copy of the image use on the remote server during export, you will have missing images.

I fixed the trouble by showing an error. I know it's not perfect but it's too risky to change this now that we are close to the release.

**Comment by WarpRat** [comment]
In 2.1.3 this appears to still be an issue and doesn't give any error. 

When exporting a portable project with IOU images and selecting include base images the IOU images aren't included in the portable project. The permissions and ownership are the same (755 & gns3:gns3) as syndgr, although I also tried setting the permissions of the images directory and everything in it to 777 for testing with no success. 

I haven't been able to export the debug information from the gui as I'm using a remote server running Ubuntu 16.04. I did read through all the logs I could find on the server and nothing jumped out at me. I've attempted this from a gns3-gui running on Ubuntu 17.10, 17.04, and MacOS 10.13 all using the same remote server.

I was able to open the portable project and manually insert the IOU images in the proper files structure and successfully load the project in another GNS3 gui, but it's an inelegant solution if you need to often create portable projects. 

Please let me know if I can provide any additional information for you or if you'd like me to open a separate bug report. Thank you.

**Comment by ziajka** [comment]
Hi @WarpRat,

Thank you for reporting this. If you may, please open the new issue with reference to this one. Probably it can be similar but different solution.

Cheers,
Dominik
