### ISSUE TITLE
Support curses console for Qemu

### ISSUE THREAD

**Issue by julien-duponchelle** [GNS3/gns3-gui#1929]
Actually if an image doesn't have a serial console you need to use the VNC output but it's limited you can't copy/paste for example.

It's probably possible to pipe the qemu curses output to telnet.

**Comment by adosztal** [comment]
What about something like `qemu-system-x86_64 -curses -monitor telnet:0.0.0.0:1234,server,nowait`?

**Comment by noplay** [comment]
It's redirect the curses output to the telnet console ? I need to recompile my qemu to test it.

**Comment by adosztal** [comment]
I guess so, I saw it [here](https://stackoverflow.com/questions/14165158/how-to-switch-to-qemu-monitor-console-when-running-with-curses).

**Comment by noplay** [comment]
If I correctly undertstand we will have the Qemu internal console (where you can check for VM status for example) available via telnet. Need to be test
