### ISSUE TITLE
Cannot add Etherswitch when running against remote gns3server

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-gui#193]
Use case: Running GNS3 GUI locally, but gns3server & IOU server are running remote. NO local dynamips or gns3server running.

When I try to drag an Etherswitch out to the topology, the switch icon displays a red "E" on it, and I get the following traceback in the console:
```
GNS3 management console. Running GNS3 version 1.2.3 on Linux (64-bit).
Copyright (c) 2006-2014 GNS3 Technologies.

=> Server error [-3200] : uncaught exception <class 'TypeError'>: can't specify None for path argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/gns3server/modules/base.py", line 276, in _decode_request
    self.modules[self.name][destination](self, params)
  File "/usr/local/lib/python3.3/dist-packages/gns3server/modules/dynamips/backends/ethsw.py", line 60, in ethsw_create
    self.start_hypervisor_manager()
  File "/usr/local/lib/python3.3/dist-packages/gns3server/modules/dynamips/__init__.py", line 281, in start_hypervisor_manager
    if not os.path.isfile(self._dynamips):
  File "/usr/lib/python3.3/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: can't specify None for path argument
```

**Comment by wdennis** [comment]
Update: On a hunch, I looked at the project's .gns3 file (JSON cfg file), and saw this line up near the top:
```"resources_type": "local",```
Changed it to:
```"resources_type": "remote",```
and then restarted the topo, and now I can drag a switch out to the topo without error.

How is this controlled via the GUI? (Or can it even be?)

**Comment by grossmj** [comment]
Hi Will,

I think this problem should be fixed in beta1. Please re-open if not.

Thanks,
