### ISSUE TITLE
Bug when rename running VBox linked clone

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1930]
Hi

- I put on the lab a VMBox (default name Debian-1)
- I start it
- I rename it to "smtp.google.fr".
- I have a error message but GNS3 seems to want to change it.  Then the name in GNS3 is changed and the name in VirtualBox not. In VirtualBox, it is always Debian-1.
- If i put a second VMBox, his default name is also Debian-1.
- Then GNS3/Virtualbox seem lost with 2 Debian-1

**Comment by noplay** [comment]
Need to test but I think Vbox don't allow . in name and we need to handle that.

**Comment by Raizo62** [comment]
perhaps.
But, GNS3 doesn't must accept to rename the VBOX if the VM is starting, no ?

**Comment by Raizo62** [comment]
I have tested with dot in name. If the VM is stopped when we change the name, there are no problem.

**Comment by noplay** [comment]
It's specific to linked clone

**Comment by Raizo62** [comment]
When i test to rename the running linked clone, i must confirm the error message with 2 dialog boxes. One with old name and one with new name. Is it ok ?

**Comment by Raizo62** [comment]
Info :  If  i use "debug 2", i have only 1 message bug

![2 messages bug](https://cloud.githubusercontent.com/assets/7449584/24095856/4b26c186-0d5f-11e7-99e8-11abebae6364.png)

**Comment by noplay** [comment]
You have two errors only debug enabled?

**Comment by Raizo62** [comment]
no. it is the opposite.

When "debug" is enabled (I wanted to post also debug info to help you), i have 1 message box.
With normal situation (debug disabled), i have 2 message box.

**Comment by noplay** [comment]
weird
