### ISSUE TITLE
[2.0] Bug when delete fake-running VMBox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1933]
Hi

- I put a VMBox, connected to ethernet switch
- I start all
- In the VBox, i shutdown the VM (Then GNS3 doesn't know it)
- In GNS3, i delete the VMBox : the VM disappeared of GNS3, but not the link

**Comment by noplay** [comment]
Fixed

**Comment by Raizo62** [comment]
Sorry, but : 

- When i delete one time, GNS3 blocks and it it is ok.
- But, when i ask to delete a second time the same device  (yes, i am obstined :-) ), the bug appears again

**Comment by noplay** [comment]
Fixed
