### ISSUE TITLE
profile cmdline arguement does not work as expected.

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1934]
The --profile cmdline arg does not work as expected (or at least how I think it should work :)).

If I run `gns3.exe --profile Remote` I would expect GNS3 GUI to load the "Remote" profile without prompting for a profile to be selected.

![image](https://cloud.githubusercontent.com/assets/20760738/23916091/fa76f6c8-08e2-11e7-8c4a-13067af4bf07.png)

Running this...

![image](https://cloud.githubusercontent.com/assets/20760738/23916059/d708798c-08e2-11e7-921d-28ccecee83d8.png)

Results in this...

![image](https://cloud.githubusercontent.com/assets/20760738/23916118/12ca6fb6-08e3-11e7-820a-97b0ec021c8c.png)

**Comment by noplay** [comment]
Thanks it's fixed
