### ISSUE TITLE
GNS3 VM settings are not saved

### ISSUE THREAD

**Issue by kaage** [GNS3/gns3-gui#1936]
Every time I start GNS3 2.0.0rc1 I need to manually re-enter all GNS3 VM related settings in Edit | Preferences | GNS3 VM - menu. After that everything works well. Doesn't matter if I close GNS3 from x in upper right corner (Windows 10) or via File | Exit.

**Comment by syndgr** [comment]
@kaage this was fixed in 2.0.0rc2, which is available for download as a release (https://github.com/GNS3/gns3-gui/releases/tag/v2.0.0rc2) but hasn't been announced.

Ref issue #926
Fixed in gns3-server commit 7b642552dde0fb41ad93eab72eca1e6ca0ad2ecc
