### ISSUE TITLE
GNS3 Packet captures doesn't support more than 100 packets per second for real time

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1937]
Hi,

I noticed that when I make a packet capture from GNS3, Wireshark only receives about 50-100 packets per second even if the actual traffic is much faster. This means that there is a huge delay between the actual data and Wireshark. It sometimes takes 1 minute to get all packets that were transferred within one seconds. 

This is best seen on the packet time-stamps in Wireshark during a file transfer between two GNS3 devices. You will see you that Wireshark keeps loading only about 100packets/s even when the actual file transfer was 5000packets/s. Wireshark still keeps loading data that I transferred 10 minutes ago. 

I notice the same delay when I do a packet capture between two IOU devices hosted on GNS3 VM and even when I do it between local cloud and local GNS3 switch on Windows 10. 

When I do the packet capture of the same file transfer directly on the physical interface the cloud connects to, there is no delay.

Unfortunately, this cannot be shown on a screenshot as the timestamps in Wireshark are correct - just delayed by several minutes. 

Sairus

Client: GNS3 200rc1 on Windows 10 (16-core Xeon/64GB RAM)
GNS3 VM 200rc1 hosted in Vmware Workstation 12 (8cores/32GB RAM)

**Comment by noplay** [comment]
What is your HDD? Are you using an HDD?

**Comment by sairuscz** [comment]
I am using only SSD drives.

**Comment by noplay** [comment]
I'm not sure if we can make it faster with current architecture. We need to read the capture file on the GNS3 VM filesystem send it via the network to your local machine, reread it from the disk using tail that will pipe the file to wireshark.

**Comment by noplay** [comment]
When we do a local capture, tail can directly pipe the data to wireshark.

**Comment by grossmj** [comment]
Yes there is some kind of optimisation we can do.

**Comment by noplay** [comment]
Sorry I mean local capture is already optimized. For remote I'm not sure we can really improve things .

**Comment by ehlers** [comment]
For v1.5 I increased the remote packet capture performance by increasing the buffer size from 16 to 1024, see https://github.com/ehlers/gns3-server/commit/a6b1d7ab354a92ce2ae630d9638e6a367dad949e

Test:
Send 10 pings with a length of 60000 byte from one remote alpine VM to another one
`ping -c 10 -s 60000 10.1.1.1`
Before the change, it takes about one minute from the termination of the ping command to the display of the last ping packet in wireshark. After the change wireshark shows it in real time.

**Comment by ehlers** [comment]
Forget my comment, v2.0 already uses a buffer size of 4096 bytes.

**Comment by grossmj** [comment]
The way packet captures are handled has been re-coded. Things will be faster in version 2.2. Please comment back if you still find experience a problem.
