### ISSUE TITLE
section_to_save_on_controller list incorrect in local_config.py

### ISSUE THREAD

**Issue by syndgr** [GNS3/gns3-gui#1939]
Opening a new issue. Issue #1924 is not fixed by commit https://github.com/GNS3/gns3-gui/commit/2099a4ae9a966c94ab86605b6073070ddb543080.

I think that "Dynamips" is missing from the section_to_save_on_controller list in local_config.py line 308 (https://github.com/GNS3/gns3-gui/blob/2.0/gns3/local_config.py#L308).

Also, should "GraphicsView" be included in the section_to_save_on_controller list? GraphicsView appears to be a user specific setting and shouldn't be shared between clients using the controller.

**Comment by noplay** [comment]
GraphicsView  is more default settings for a project. Is not really the correct name but we didn't change it for the moment to avoid a migration.

**Comment by noplay** [comment]
Should be ok now 

Thanks for the help
