### ISSUE TITLE
[2.0] Qemu appliances show incorrect interface labels

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1940]
Hi,
a tiny bug when I manually change interface name format of a Qemu appliance from the default Ethernet0/{port0} to Ethernet1/{port1}, the actual interface labels in the diagram show as e0/0 , e1/0 , e2/0 . As you can see, also the increment is incorrect - it should be e1/1, e1/2, e1/3... 

Everything else works as it should, just the labels on the diagram do not show correctly. They can be manually edited, however. 

Sairus
GNS3 200RC1 Windows 10
![qemu_int_label](https://cloud.githubusercontent.com/assets/24818591/23992961/ee3b5afa-0a92-11e7-921d-f86b7d09f25a.JPG)
![qemu_int_label2](https://cloud.githubusercontent.com/assets/24818591/23992960/ee26ebf6-0a92-11e7-91b1-ee17c1967fc8.JPG)

**Comment by noplay** [comment]
This a backward compatibility. If you keep Ethernet{interface number} as name we will display e/ with default . But I improved it should create less issues.

Thanks for the report
