### ISSUE TITLE
[2.0] Remote GNS3 VM can't be selected until preferences are closed

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1952]
On **2.0.0rc2** there is a following issue:
If you add a new server to remote server list and then try to use it as GNS3 VM, it just can't be selected. Button refresh does not help.
**Workaround**: save settings and close window, open preferences again. Now Remote GNS3 VM can be selected.
<img width="969" alt="screen shot 2017-03-21 at 09 56 04" src="https://cloud.githubusercontent.com/assets/1923704/24139838/fd8bfb34-0e1d-11e7-9993-29ad9626deff.png">
<img width="966" alt="screen shot 2017-03-21 at 09 56 11" src="https://cloud.githubusercontent.com/assets/1923704/24139840/ff7f9374-0e1d-11e7-8523-ec1fa8c69d00.png">

**Comment by noplay** [comment]
The problem is you need to apply the settings until that the server can't be available. I'm not sure how to make it clear.

**Comment by dmfigol** [comment]
Makes sense, sorry for opening a bug.
Maybe there should be a message in the remote server list under the button "Add" something like: "A new server can't be used until the settings are applied."
What do you think?

**Comment by noplay** [comment]
No problem the issue is an UX problem that we need to solve. I think the message is a good idea.
