### ISSUE TITLE
[2.0] Node conf dialogue goes to background after changing startup-config

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1955]
2.0.0rc2
If you change startup-config of the node in Preferences, then after clicking okey in the file selection window, dialogue "Device configuration" will go to the background and "Preferences" will be "always on top" now.
Tested only with IOL nodes so far.
<img width="1369" alt="screen_shot_2017-03-21_at_10_56_30" src="https://cloud.githubusercontent.com/assets/1923704/24142292/69a96c9a-0e26-11e7-9ad2-b1fd5273da12.png">

**Comment by noplay** [comment]
Do you still reproduce it? I'm not able to reproduce on our mac

**Comment by dmfigol** [comment]
I am able to reproduce it on Mac.
Steps:
1. In **Preferences** select **IOU devices** and select any device template.
2. **Edit** -> **Startup-config** -> **Browse** -> Select any file
3. GNS3 **Preferences** window is now on top, but **IOU device configuration** window is on the back.

**Comment by noplay** [comment]
Strange I don't have this behavior

**Comment by noplay** [comment]
I try to push a fix to force the window order, not sure why Qt doesn't work correctly on your system.
