### ISSUE TITLE
[2.0] Image field in nodes list is stale after changing an image

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1956]
2.0.0rc
Tested with IOL
Steps to reproduce:
1. Select an existing IOL node and click Edit.
2. Click browse near "IOU image path" and select a new image.
3. The new image will be uploaded. Save.
4. In the node list the "Image:" field is an old image name. In "Device configuration" there is a new one. If you start topology a new image is used, so it is a cosmetic issue.

I have a screenshot, but I can't publish it here. If needed, let me know, I will send it via email.

**Comment by noplay** [comment]
Thanks it's fixed
