### ISSUE TITLE
Feature request to allow Visio Import and GNS3 topology based on Visio diagram

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#1962]
Feature request to allow Visio Import and GNS3 topology based on Visio diagram

**Comment by noplay** [comment]
I don't see how it could be possible because we have no idea what the images in VISIO represent

**Comment by Vic563** [comment]
GNS3 can select the generic icon that Visio has under the "Detailed Network" stencils. Same way that VIRL has implemented this feature.

**Comment by noplay** [comment]
In VIRL what happened to this nodes, they don't have any configurations?
How do you know which hardware models is associated to a node?

**Comment by Vic563** [comment]
When a Visio diagram is imported from VIRL the device are just deployed based on the connections of the Visio diagram. In VIRL they don't deal with "all" the different vendors which exist. They just recongonzie the common nodes such as IOSv and IOSv_L2. So if VIRL sees a Router icon on the Visio diagram it deploys a IOSv router. And if it sees a Switch icon it deploys a IOSv_L2.
