### ISSUE TITLE
Getting error message IOL bridge 'IOL-Birdge-513: PID 1843 already has a lock on ID when deploying Nexus 9000v

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#1964]
Getting error message IOL bridge 'IOL-Birdge-513: PID 1843 already has a lock on ID when deploying Nexus 9000v and connecting to IOL_L2 nodes.

**Comment by noplay** [comment]
Do you have this error everytime?

**Comment by Vic563** [comment]
Not everytime. First I thought it was the L2 image but then I tried another IOU L2 image and had the problem again. It's random. Also, the PID changes.

**Comment by noplay** [comment]
Do you have multiple projects opened?

**Comment by noplay** [comment]
I think I fixed the issue you will be able to test it with RC3
