### ISSUE TITLE
Nexus 9000v node interfaces which are in use not showing up properly

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#1965]
I was able to get Nexus 9000v node up and running. However, the interfaces I am selecting to connect are not showing up properly. Any interfaces I select like eth1/1, or eth1/3. On the GUI it keeps showing interface eth0/0 for any interface I select to connect.

**Comment by noplay** [comment]
How do you have imported the appliance?

**Comment by Vic563** [comment]
I imported the appliance as was stated in the instructions below.

https://docs.gns3.com/appliances/cisco-nxosv9k.html

**Comment by noplay** [comment]
Could you post a screenshot of what you see ? Because this appliance should be fine.

**Comment by Vic563** [comment]
Below is a screenshot of the issue I was discussing.

![image](https://cloud.githubusercontent.com/assets/16152626/24550199/0a499104-15eb-11e7-866f-ba3c72cd53b0.png)


![image](https://cloud.githubusercontent.com/assets/16152626/24550234/1fc6de42-15eb-11e7-9bb1-5303df20d07b.png)

**Comment by noplay** [comment]
Bug should be fixed in dev version

**Comment by noplay** [comment]
RC3 and later should have a fix for this.
