### ISSUE TITLE
Copy directory path into clipboard

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1966]
"Show in file manager" displays only a popup, when the device directory is on a remote server.
![device_directory](https://cloud.githubusercontent.com/assets/896406/24323685/bc1da9b8-1179-11e7-822a-8d26f1346a84.png)

A very nice solution would be a file manager in the GUI, see https://github.com/GNS3/gns3-gui/issues/1237, but that will take some time.

In the mean time, what about copying the directory path to the clipboard, when this popup is shown?

Normally I do the copy to the clipboard manually and then use that in a ssh window connected to the server. But this manual copy is inconvenient as the directory string is in the middle of the text.

For me QClipboard::setText() looks like an easy way to do this, see http://doc.qt.io/qt-4.8/qclipboard.html#setText

**Comment by noplay** [comment]
Interesting idea

**Comment by syndgr** [comment]
Be aware that automatically copying to the clipboard without warning is insanely annoying when you paste later on...

**Comment by grossmj** [comment]
I agree, I would add a "Copy to clipboard" button or something like this.
