### ISSUE TITLE
GNS3 not connecting to Workstation 12 Pro using windows 10

### ISSUE THREAD

**Issue by mustapha23** [GNS3/gns3-gui#1967]
Could not execute vmrun: Command '['C:\\Program Files (x86)\\VMware\\VMware VIX\\vmrun.exe', '-T', 'ws', 'start', 'C:\\Users\\Mustapha\\Documents\\Virtual Machines\\GNS3 VM\\GNS3 VM.vmx']' returned non-zero exit status 4294967295 with output 'Unable to connect to host.
Error: Service type VIX_SERVICEPROVIDER_VMWARE_WORKSTATION was specified, but not installed

I've tried must of the things mentioned on this thread but no luck. GNS3 starts the VMware but i  do not get passed the 'starting vm'.

Tried running it manually and the command just hangs

Can someone help with this please.

**Comment by mustapha23** [comment]
![image](https://cloud.githubusercontent.com/assets/26683408/24328689/8ebfb1dc-11b5-11e7-9f6d-fd2773ff1fa4.png)

**Comment by jtorri** [comment]
Not sure but you made need to install VMWare VIX.  The following link should show you what is does.
https://blogs.vmware.com/vix/2008/07/what-is-vix-and.html

And this should aim you at the place from which to download/install it.
https://my.vmware.com/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/12_0|PLAYER-1200|drivers_tools

Hope this helps!

**Comment by mustapha23** [comment]
I've already downloaded the latest VIX 1.15.0 and it made no difference

**Comment by noplay** [comment]
Please uninstall VIX, vmrun is provided by Workstation Pro. 

Make sure VMware and GNS3 run under the same user and that your antivirus doesn't block the vmrun binary.
