### ISSUE TITLE
virtio not supported?

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1969]
Observed the following error after attempting to configure a custom qemu guest:

Start QEMU with /usr/bin/qemu-system-x86_64 -name VPC-1 -m 4096M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/opt/gns3/projects/5c519313-6623-43d4-8a90-1bc8ea146865/project-files/qemu/92409ded-0295-49a7-a38b-0990f63e582f/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 92409ded-0295-49a7-a38b-0990f63e582f -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:50362,server,nowait -net none -device virtio,mac=00:68:65:58:2f:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10003,localaddr=0.0.0.0:10002 -device virtio,mac=00:68:65:58:2f:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10013,localaddr=0.0.0.0:10012 -device virtio,mac=00:68:65:58:2f:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10015,localaddr=0.0.0.0:10014 -device virtio,mac=00:68:65:58:2f:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10017,localaddr=0.0.0.0:10016 -nographic -nographic

Execution log:
qemu-system-x86_64: -device virtio,mac=00:68:65:58:2f:00,netdev=gns3-0: 'virtio' is not a valid device model name

Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)

**Comment by noplay** [comment]
On which OS?

**Comment by noplay** [comment]
It seem your qemu is not compiled with virtio
