### ISSUE TITLE
[2.0] : BUG : connected ethernet switch doesn't want to change status port

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1970]
Hi

I connect a device to a port of an ethernet switch.

With the GUI of this ethernet switch, i want to change the state of this port from VLAN 1 to VLAN 10.

GNS3 refuses with this message : can't modify a switch already connected.

I hope that is a bug, because, if not, this functionality of vlan will not be practical

**Comment by noplay** [comment]
I will check

**Comment by noplay** [comment]
Improved.

Note: You can't change the number of adapter when the switch is connected
