### ISSUE TITLE
GNS3 2.0 RC3 Docker templates using VNC not working

### ISSUE THREAD

**Issue by dkhenderson2** [GNS3/gns3-gui#1975]
GNS3 2.0 RC3 Docker templates using VNC not working

After creating the template the error below is presented after dragging the node to the work space

receives error:

GNS3 2.0 RC3 Docker templates using VNC not working

Error while setting up node: Please install Xvfb and x11vnc before using the VNC support

tested with Linux, windows, Ubuntu and MAC OS all have the same result.

**Comment by noplay** [comment]
Duplicate of https://github.com/GNS3/gns3-server/issues/965
