### ISSUE TITLE
GNS3 V2 RC3 -Recent projects list bug

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1976]
It looks like in the picture
![image](https://cloud.githubusercontent.com/assets/345437/24614986/40d66734-188d-11e7-8b9c-34e410e69b44.png)

I don't know if that is normal. This would be the second time when I launch the client (GUI running on Windows Pro 7 x64)

**Comment by noplay** [comment]
You got this issue only one time?

**Comment by 1001QAdotNET** [comment]
Nope ..it is persistent, I just tried this morning
The size of that drop down box seems to be adjusted to the largest size that was ever reached by the list of recent projects. After deleting projects from the library the size of the drop down list is still large enough to contain the former list but the items are empty see here: https://i.imgur.com/CCVeghj.png

**Comment by syndgr** [comment]
Hey @noplay. I was about to comment on this and you've literally just closed it - good (or bad?) timing :)

I notice this issue too. I think it existed even in beta 4. Still persists in RC3.

For example:

![image](https://cloud.githubusercontent.com/assets/20760738/24753313/7384246c-1ac9-11e7-8318-0f3a6d938e4c.png)

And:

![image](https://cloud.githubusercontent.com/assets/20760738/24753322/7f392460-1ac9-11e7-9a69-28ccfafecf88.png)

I'll export debug info as you requested from @1001QAdotNET and send it over shortly...

**Comment by syndgr** [comment]
I can't export debug info because I'm using a remote server.

**Comment by syndgr** [comment]
I'm assuming the list is generated from the gns3_gui.ini, from the recent_profiles list? If this is the case, mine looks like:

````
        "recent_projects": [
            "a2c7daa0-1710-4ead-831c-6c3d9f5b4bc8:Dual-WAN Lab:/opt/gns3/projects/a2c7daa0-1710-4ead-831c-6c3d9f5b4bc8\\Dual-WAN Lab.gns3",
            "9098957c-b62c-4462-a492-658770310dfe:QoS test:/opt/gns3/projects/9098957c-b62c-4462-a492-658770310dfe\\QoS test.gns3",
            "870942e3-0c9b-48c3-bfd0-bbeb88c3a347:Test:/opt/gns3/projects/870942e3-0c9b-48c3-bfd0-bbeb88c3a347\\Test.gns3",
            "ba7a339a-248f-4ffb-a13d-5d1f277b6450:bd9870ef-420b-4ea2-a9e7-ddaf9b7a01e5:/opt/gns3/projects/ba7a339a-248f-4ffb-a13d-5d1f277b6450\\bd9870ef-420b-4ea2-a9e7-ddaf9b7a01e5.gns3"
        ],
````

The last item is clearly not right. I'm not sure what that is (maybe a project I deleted using File > Delete project?). The GUIDs mentioned in that item do not exist on my remote server under /opt/gns3/projects either.

**Comment by noplay** [comment]
Ok I got the issue

**Comment by noplay** [comment]
Fixed thanks for the report
