### ISSUE TITLE
The web interface for V2 is still pointing to old APIs

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1977]
Ing GUI v2rc3 ff you use Tools-->Web Interface"   you will be sent to the web interface of the server
There is a link to APIs that points to http://api.gns3.net/en/latest/  which I think is the old set of APIs

The latest and the greatest seem to be here:  http://api.gns3.net/en/2.1/

**Comment by noplay** [comment]
Fixed thanks
