### ISSUE TITLE
GUI V3 RC3: Add an option to shutdown the server from GUI (right side panel with servers)

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1978]
GUI V3 RC3: Add an option to shutdown the server from GUI (right side panel with servers)
I hope this is not a request for a feature that is already there. I am still learning the new features in V2

**Comment by noplay** [comment]
Hi,

Why do you need that? The server is shutdown when you close the GUI.

**Comment by 1001QAdotNET** [comment]
no why would the server be shutdown? At most the project will be (if not configurd to stay up after closing the gui)
Why I want that: when I call it a day I need to go to the ESXi server and I need to shut down the VM. Some people have the VM in the cloud and if the VM stays up that is going to cost money

**Comment by noplay** [comment]
But in this case shutdown the GNS3 server will not be enough you need to shutdown the whole machine. And in theory GNS3 don't have permission to do that, you need to be root.

**Comment by 1001QAdotNET** [comment]
I think you are right if GNS3 is not installed as a VM and it is hosted on a server together with other things. If you use the VM you guys provide this should be simple ..I guess I will script that somehow.

**Comment by noplay** [comment]
In the settings you can already ask for closing the VM with GNS3.

For ESXi or cloud it's up to you to manage it with external script depending of your situation.
