### ISSUE TITLE
HDPI support on Linux

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1980]
HDPI support on Linux needs to be improved, for instance the toolbar icons are too small.

**Comment by noplay** [comment]
The HDPI mode is enabled? If I remember now it's disabled by default on Linux due to crash issues.

**Comment by grossmj** [comment]
Yes it is enabled but HDPI support is incomplete on Linux.

**Comment by grossmj** [comment]
I need to test with Qt >= 5.6 but Ubuntu 16.04 comes with Qt 5.5.1 :(

**Comment by noplay** [comment]
I think it will be a mess until distribution switch to Wayland.

**Comment by grossmj** [comment]
I tested in a Python virtual environment with Qt 5.8.0 and PyQt 5.8.2.

Everything seems to work well excepting 2 things:

* Drag and drop of a node: the node is not right on the mouse cursor but like 2 cm on the top left (minor issue).
* Nodes do not render well on the scene, zooming in or out doesn't work.

![hdpi_linux](https://cloud.githubusercontent.com/assets/4752614/25954248/3b8f4e3e-3698-11e7-8a92-9689eae6ff7b.png)

![hdpi_linux_2](https://cloud.githubusercontent.com/assets/4752614/25954295/64b1e2cc-3698-11e7-8b93-ac2be5a78aa1.png)

**Comment by noplay** [comment]
You are using the wheel?

**Comment by grossmj** [comment]
Yes

**Comment by noplay** [comment]
What should we do? We can't use a wheel for build the .deb it's not
supported

**Comment by grossmj** [comment]
Well the wheel has mainly for me to get a Qt version that supports HDPI and
test how the GUI renders with it.

For now I think we have no choice but to wait for distros to upgrade their
Qt/PyQt deb packages to a more recent version.

**Comment by noplay** [comment]
So we can close the issue? It's not depending of us. But user with 4K should use more recent distribution.

**Comment by grossmj** [comment]
Not we cannot close it yet because of the small issues I have reported.
HDPI support is not complete on Linux. We need to investigate what can be
done in the Qt code.

https://github.com/GNS3/gns3-gui/issues/1980#issuecomment-300805348

**Comment by grossmj** [comment]
@ziajka do you have a HDPI screen?

**Comment by ziajka** [comment]
@grossmj unfortunately no

**Comment by grossmj** [comment]
This seems to have been fixed in recent Qt versions.
