### ISSUE TITLE
GNS 2.0.0RC3 VirtualBox VM adapter Reconfiguration by GNS

### ISSUE THREAD

**Issue by dhcabinian** [GNS3/gns3-gui#1986]
Current Setup:

	2 GNS instances both running GNS 2.0.0 RC3
		Server:
			Running GNS RC3 local server on AWS Server
			Holds 2 VMs (With 3 adapters: 1. Not-Attached for GNS, 2. NAT, 3. Host Only)
![screen shot 2017-04-17 at 9 52 20 pm](https://cloud.githubusercontent.com/assets/10492146/25111794/1e8b9f08-23bb-11e7-8614-17ab787e4f3b.png)
![screen shot 2017-04-17 at 9 52 44 pm](https://cloud.githubusercontent.com/assets/10492146/25111795/1fbdf61e-23bb-11e7-930e-479f3e072e41.png)
![screen shot 2017-04-17 at 9 52 51 pm](https://cloud.githubusercontent.com/assets/10492146/25111796/20fec1c0-23bb-11e7-81cb-d49a124dff48.png)

			Holds 1 Cisco Router Image
		Client:
			Running RC3 (does not run a GNS server instance)
			Runs the 2 VMs remotely using "Run everythin on remote server" option
			Creates topology
			Start and stops topology

Current Problems:

	1. Adapters becoming disabled by GNS (Bug)
		The 2 VMs running on the GNS server utilize 3 adapters. 1. Not-Attached for use by GNS. 2. NAT 3. Host-Only

		When trying to configure GNS to utilize the Not-Attached adapter, the expected behavior is that GNS will configure the UDP tunnel on the Not-Attached adapter while leaving the other 2 adapters as previously configured. (Expected behavior determined by this post https://gns3.com/qa/virtualbox-ubuntu-attachment-nat). 

		The actual behavior depends on the configuration of GNS. All configurations below have been tested and result in their noted behaviors. 
			1. Specifying 3 adapters in order (Not Attached, NAT, Host Only) in GNS with the "Allow GNS3 to use any configured VirtualBox adapter" unchecked returns an "Attachment (nat) already configured on adapter 2. Please set it to 'Not attached' to allow GNS3 to use it." error. 
<img width="1018" alt="screen shot 2017-04-17 at 9 55 33 pm" src="https://cloud.githubusercontent.com/assets/10492146/25111763/f412ebaa-23ba-11e7-8a16-4f4f8837cf00.png">

			2. Specifying 1 adapters (With all three adapters in VBox still enabled) results in no error but disables the remaining 2 adapters (NAT, and Host-Only) in VBox.
![screen shot 2017-04-17 at 10 05 46 pm](https://cloud.githubusercontent.com/assets/10492146/25111783/0b61ee8c-23bb-11e7-8db3-40befaec0103.png)

			3. Specifying 3 adapters in order (Not Attached, NAT, Host Only) in GNS with the "Allow GNS3 to use any configured VirtualBox adapter" checked returns no error but configures all 3 adapaters as GNS3 UDP tunnels.
			4. Specifying 1 adapters in GNS with the "Allow GNS3 to use any configured VirtualBox adapter" checked returns no error but configures the first adapter as a UDP tunnel and disables the other 2.

		Ordering of the adapters (i.e. which slot each network configuration is in Adapter 1 = Not Attached vs Adapter 1 = NAT) does not make a difference and still results in the "Attachment (nat) already configured on adapter 2. Please set it to 'Not attached' to allow GNS3 to use it." error with the respective adapter listed. 

		The above configurations were also tested using the Preferences>VirtualBox configuration to ensure the bug #3 listed below had no effect. 

	2. Console requires configuration in order to work. (Possible easy feature)

		The console feature does not dynamically change the IP address for a remote serve using a DNS service. In my case, I have assigned my remote GNS3 server a DNS hostname using the no-ip free service. When using the console feature of GNS, an unknown IP address is used rather than resolving the DNS hostname (listed under Server in Preferences) into the correct IP address. As a current workaround, I have simply replaced the %h delimiter in Preferences>General>Console applications with my DNS hostname.
<img width="1014" alt="screen shot 2017-04-17 at 9 57 54 pm" src="https://cloud.githubusercontent.com/assets/10492146/25111769/fcfc7880-23ba-11e7-9c90-522fad952b4d.png">
<img width="1014" alt="screen shot 2017-04-17 at 10 00 05 pm" src="https://cloud.githubusercontent.com/assets/10492146/25111773/00833a66-23bb-11e7-84ac-78e31eb3672b.png">

	3. Adapter number value (for VirtualBox VMs) differs between Preferences menu and Node Properties Menu

		Changing the number of Adapters listed under the VirtualBox VM settings in Preferences is not reflected in the right click menu of the Node Properties in the topology. The reverse is also true.

<img width="723" alt="screen shot 2017-04-17 at 9 54 10 pm" src="https://cloud.githubusercontent.com/assets/10492146/25111806/2c1b2094-23bb-11e7-901e-1d99946375a2.png">
<img width="1014" alt="screen shot 2017-04-17 at 10 14 34 pm" src="https://cloud.githubusercontent.com/assets/10492146/25111817/464ae710-23bb-11e7-8043-7338ac0bcfe6.png">

**Comment by pmandon** [comment]
Hello,
is there a way to get around this? I really need to be able to communicate with vboxnet0.

**Comment by noplay** [comment]
Their is confusion around that. You can't use existing adapters in your topologies. GNS3 will be only able to connect to the adapter added by it.

Otherwise you need to allow GNS3 to control all adapter. GNS3 will overidde the adapters allowing you to connect to any ports.  It's the recommended way.

We don't recommend to manage the network outside GNS3.

**Comment by pmandon** [comment]
Thank you, but if I set "not attached" to my vm, interfaces are down for some reason.
![image](https://cloud.githubusercontent.com/assets/26303562/26542174/3cfb19dc-4459-11e7-894d-3cd680e57425.png)
See here, M-E1/0/1 is down. When I don't launch the router in gns3, this interface is up.

**Comment by pmandon** [comment]
oh nevermind, it's working, thanks a lot.
