### ISSUE TITLE
GNS3 1.5.4 VM not closed with quitting application

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1989]
Using GNS3 1.5.4 application and GNS3 VM.  Windows 10 prof 64bit.  When quit GNS3 application the GNS3 VM is not closed.  When I set local server host binding to 127.0.0.1 the application at startup resets it to 192.168.41.1, the IP network of the GNS3 VM.  Also, the application shows 2 "instances" of "Local" in Server Summary window.  Not sure what I have done wrong.
![gns31 5 4app](https://cloud.githubusercontent.com/assets/10285348/25139584/b913e20e-242b-11e7-8678-347dbfb3734d.png)
![gns3vm](https://cloud.githubusercontent.com/assets/10285348/25139590/bcc6d3ca-242b-11e7-9fae-068e329571d1.png)

**Comment by jtorri** [comment]
You know what, this does not occur in GNS3 2.0.0rc3, so why not just close this issue.  Thanks!

**Comment by noplay** [comment]
Thanks
