### ISSUE TITLE
[2.0] minor bug : missing text "all devices" in Dock

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1990]
Hi

I start GNS3, and give a name to my project.

I don't click on the left bar, but i click on View / Docks. I have an empty box under  Console.
When i click on the left bar, the empty box becomes "All devices"

**Comment by noplay** [comment]
Could your share your gns3_gui.ini?

**Comment by cioby23** [comment]
I just opened the GNS3 gui and I  can confirm this is happening both on Linux and Windows.

**Comment by noplay** [comment]
Could you post a screenshot?

**Comment by noplay** [comment]
I think I fix it. Can you confirm?

**Comment by Raizo62** [comment]
It is good :-)
