### ISSUE TITLE
[2.0] Bug/Question ? space at the end of name of project

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1997]
Hi

If the name of my project is "name " (with space at the end), the file in gns3 is "name.gns3" (without space before dot)

It is a developer's choose, system comportment or a bug ?

To help script writing, can you use a name more generic as "topology.gns3" ? Is it important to have the same name as the directory ? (it is not the case here)

**Comment by noplay** [comment]
We strip space because usually it's not volontary.

We use the name PROJECT_NAME.gns3 because on most system the convention is to display the file name in the windows title.

**Comment by Raizo62** [comment]
> We strip space because usually it's not volontary.

Then why don't you strip space also in the name of the directory ?

**Comment by noplay** [comment]
You are right I missed that
