### ISSUE TITLE
Upgrade GNS3 VM: best way to bring appliances & images into new VM?

### ISSUE THREAD

**Issue by onpaws** [GNS3/gns3-gui#1998]
_Wasn't sure where to ask this - mods, please feel free to move as needed._

I'm interested in following GNS2.0 development, and upgraded from beta4 to rc4 yesterday, including gns3-gui and gns3-VM.

The way I usually upgrade apps on my Mac is to download updated binaries and replace the old ones. But maybe this is the wrong way to upgrade the GNS3 VM?
I can open projects in the rc4 release of GNS3 GUI (:thumbsup:) but I have problems starting e.g. a 7200 router:
```
': unable to start VM instance 'R1'
Dynamips error when running command 'vm start "R1"
```

I think I need to bring the appliances & images into the new VM.
Is there a recommended way to upgrade VM?

I saw [this](https://asciinema.org/a/9wn95j392dssb7rsj7wj2lvzp) video but I'm not sure this is the best way.

Since GNS3 already has access to the images stored on my host, it would be nice if there was a way it would automatically copy them into the VM. Possible?

Thanks for your help :)

**Comment by noplay** [comment]
Replace the old binaries is the correct way.

For the GNS3 VM you should just use the upgrade menu in the VM.

Your dynamips image was working before?

**Comment by onpaws** [comment]
Thanks Julien.

Yes the dynamips image was working before. 

If I remember right, adding a new GNS3 appliance copies the images to the VM.

Maybe I could just delete my old appliances from GNS3 and re-add?

**Comment by noplay** [comment]
It's strange that dynamips stopped working, we have not change it. Dynamips is running on your mac or in the GNS3 VM?

**Comment by waqaskhan778** [comment]
Hi ,

I am facing the same kind of problem .
