### ISSUE TITLE
2.0.0rc4 - Device running, but UI doesn't reflect

### ISSUE THREAD

**Issue by ColdIce1** [GNS3/gns3-gui#2006]
Hi,

Submitting the bug I experience. Running GNS3 server on DigitalOcean, currently using SSH to access the server with port forward, works flawlessly.

The issue, device is running on my server with Dynamips, verified with `netstat -tulpn` showing that server is listening on console port, but the UI doesn't reflect the device is running.
Have to start it multiple times or even run Auto-Idle PC to get UI to update.

Please note that I did not install GNS3 GUI, I extracted the file because I don't have permission to install programs, so that might be an issue... But yet it strange that the GNS3 server shows the device as stopped.

**Comment by ColdIce1** [comment]
Update: Doing "Raise / Lower one layer" after starting the device refreshes the UI and GNS3 Client shows the device as up.
Temporary solution.

**Comment by noplay** [comment]
SSH tunnel is not supported. We support only connection via a VPN.  

If you use SSH tunnel GNS3 will fail to properly detect the network.
