### ISSUE TITLE
GNS3 2.0.0 displays error msg loading IOU

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2012]
Windows 10 Prof X64.  GNS3 2.0.0 application and GNS3 VM.  When loading IOU into GNS3 VM via Edit -> Preferences ->IOU on Unix -> IOU Devices an error msg displays each time an IOU file is loaded.  Does not seem to affect functionality.  Everything loads just fine.
![filediaglogbaseerror](https://cloud.githubusercontent.com/assets/10285348/25632965/7eb2021c-2f43-11e7-8cad-e2d246ecc04a.png)

**Comment by noplay** [comment]
Seem to be a bug with the native File Dialog on Windows

**Comment by jtorri** [comment]
GNS3 2.0.0 on Ubuntu  16.04 x64 with latest Ubuntu updates.  GNS3 upgraded from 1.5.4 via apt-upgrade.  Running GNS3 as non-root user.  Not sure if this is helpful but there are "windows" error message here as well.  Was merely accessing Preferences option.  At least I believe that is all I was doing.
![screenshot from 2017-05-03 09-15-11](https://cloud.githubusercontent.com/assets/10285348/25662234/ca9f1d2e-2fe1-11e7-9b2d-6c554a3b969d.png)

**Comment by noplay** [comment]
Could you open a new issue for that?

**Comment by jtorri** [comment]
Done!  Thanks for the help.

**Comment by noplay** [comment]
Could you test?
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-05-04/2.0/GNS3-2.0.2017-05-04-all-in-one.exe/download
