### ISSUE TITLE
GNS3 2.0.0 on Ubuntu 16.04 "Window" error/information msg 

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2020]
GNS3 2.0.0 on Ubuntu  16.04 x64 with latest Ubuntu updates.  GNS3 upgraded from 1.5.4 via apt-upgrade.  Running GNS3 as non-root user.  Not sure if this is helpful but there are "windows" error message here as well.  Was merely accessing Preferences option.  At least I believe that is all I was doing.
![screenshot from 2017-05-03 09-15-11](https://cloud.githubusercontent.com/assets/10285348/25663458/c0e83866-2fe5-11e7-9de6-518be648fd53.png)

**Comment by noplay** [comment]
It seem fixed in Qt 5.6 (they silent the warning...):
https://codereview.qt-project.org/#/c/126172/

I will see if we can filter the message

**Comment by noplay** [comment]
Fixed
