### ISSUE TITLE
Error when connecting with GNS3 server

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#2024]
Upgraded from nightly build from march, ran into multiple errors. Uninstalled GNS3, reinstalled, same errors. Attaching logs. 

![image](https://cloud.githubusercontent.com/assets/6335629/25674680/c529a6de-3009-11e7-9335-cf820c9378eb.png)

[gns32-0.zip](https://github.com/GNS3/gns3-gui/files/974271/gns32-0.zip)

**Comment by codeassassin** [comment]
BTW, disabled AV, same error. Ran gns3server.exe on its own, console seems to output errors. Ran as admin, didn't notice errors.

**Comment by noplay** [comment]
Can you start the server in a terminal in order to see the details of the errors?

**Comment by codeassassin** [comment]
I don't see any errors when I run gns3server from console.

**Comment by codeassassin** [comment]
![image](https://cloud.githubusercontent.com/assets/6335629/25816563/70f48da8-33f2-11e7-8045-c786306e211d.png)

![image](https://cloud.githubusercontent.com/assets/6335629/25817248/c31273a0-33f4-11e7-8630-f5b9db14a8e6.png)

**Comment by codeassassin** [comment]
downloaded and installed latest daily build after uninstall of previous build. Getting new errors, still 

=> QIODevice::write (QTcpSocket): device not open
QIODevice::write (QTcpSocket): device not open
Could not start local server ""C:\Program Files\GNS3\gns3server.EXE" --local --log="C:\Users\Trent\AppData\Roaming\GNS3\gns3_server.log" --pid="C:\Users\Trent\AppData\Roaming\GNS3\gns3_server.pid"": [WinError 740] The requested operation requires elevation
Could not start the local server process: C:\Program Files\GNS3\gns3server.EXE
Could not start local server ""C:\Program Files\GNS3\gns3server.EXE" --local --log="C:\Users\Trent\AppData\Roaming\GNS3\gns3_server.log" --pid="C:\Users\Trent\AppData\Roaming\GNS3\gns3_server.pid"": [WinError 740] The requested operation requires elevation
Could not start the local server process: C:\Program Files\GNS3\gns3server.EXE


[5-8-debug.zip](https://github.com/GNS3/gns3-gui/files/984511/5-8-debug.zip)

**Comment by codeassassin** [comment]
I right clicked ran as admin GNS3 and everything functioned as expected without issue. I've never had to right click run as administrator GNS3 in the past as I recall. Thanks guys.

**Comment by noplay** [comment]
Make sure GNS3 as permission on all files in C:\Users\Trent\AppData\Roaming\GNS3\

If you start one time GNS3 as admin you will break the permission and GNS3 will no longer be able to run as a normal user, until you fix permissions on files (GNS3 need to delete the .pid file to start).

**Comment by noplay** [comment]
I close the issue because it sound like  a permission issues.

**Comment by LMayaL** [comment]
I also have this problem too I ran gns3 as an admin but it didnt work. the samr error please help me.

**Comment by SJ316** [comment]
Hi, after I installed the version 1809 with latest update from Microsoft, this break my installation.

I searched, and this was the only solution, not a permission problem, more a problem of services not running. Try the solution at the end of the first post, because you need to put the NPC service to run, after it, use the other command in the response post.

https://gns3.com/community/discussion/gns3-does-not-start-local-server

Also, you can manually start the GNS3 server, just follow the location that is presented in the log of GNS3, after you click OK, to the errors. But this is annoying, since you have to do it everytime.
