### ISSUE TITLE
Sort existing image list

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2030]
Would be nice if, in configuration, when selecting from an existing image (QEMU, Docker, etc) the list was sorted alphabetically.  Currently they are either displayed in random order, or maybe it's the order they were added.

**Comment by noplay** [comment]
Can you post  a screenshot of where you see an unsorted list? It should be already the case.

**Comment by CapnCheapo** [comment]
![screen shot 2017-05-05 at 8 54 33 am](https://cloud.githubusercontent.com/assets/22641788/25748564/1f2dc242-3171-11e7-8395-b3fa2e899073.png)
