### ISSUE TITLE
[2.0] Duplicate device naming

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2031]
Upgraded to 2.0 and opened prior lab, when adding a new container device, "gns3-endhost1" is added although the name already exist.
Strangely this didn't happen with gns3-opnevswitch which continue the counting.

![selection_999 015](https://cloud.githubusercontent.com/assets/1716020/25730182/ded834ec-313a-11e7-9de1-a510acb58f3e.png)

**Comment by mad-bison** [comment]
They're not duplicate.
One is named gns3 **/** endhost-1
The other is named gns3 **-** endhost-1

**Comment by AJNOURI** [comment]
Oh.., ok, I didn't noticed that. So, now it keeps the "/" from the default image.
Thanks mad-bison.
