### ISSUE TITLE
Was this my error or it is a horrible bug ??

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2037]
I was working on a new GNS3v2 VM (cloned  from the v1.54  and upgraded to V2 RCx) and then to V2.0 final) and because the menu did not show up and the message way saying "If the menu is not working run gns3restore" I did exactly that.
That basically reversed the upgrade and sent me back to 1.54....
That was really upsetting ...this was supposed to fix a menu

**Comment by noplay** [comment]
Fixed
