### ISSUE TITLE
[2.0] Project content suddenly disappears.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2039]
Project suddenly closed and the topology disappeared and cannot add any devices (canvas hanging).
Closed and reopended GNS3, fortunately the project is there and looks OK.

![selection_999 022](https://cloud.githubusercontent.com/assets/1716020/25767183/8cdd4a02-31f7-11e7-9a1e-6a2c7bdb4422.png)

**Comment by noplay** [comment]
The project seem to have been closed and you need to reopen it. Do you have multiple clients connected to it?

**Comment by AJNOURI** [comment]
Only one client.

**Comment by noplay** [comment]
On a local network?

**Comment by AJNOURI** [comment]
yes, all locally on the same machine.

**Comment by noplay** [comment]
Did you change the network (wifi disconnect)? Because it seem the client lost connection to the server during more than 5 seconds.

**Comment by AJNOURI** [comment]
I am not on wifi. 
Now that you mention the possibility of disconnect, sometimes when I switch to other programs and then back to GNS3, it hangs for a couple of seconds before showing the project.
I'll post a screenshot if it happens again.

**Comment by noplay** [comment]
Do you have something that suspend application when they are not  the main application

What is your windows manager?

I close the issue for the moment because it seem more a bug in qt/windows manager/xserver that make GNS3 freeze and timeout than a bug in GNS itself.

**Comment by AJNOURI** [comment]
It is gdm:
`cat /etc/X11/default-display-manager`

> /usr/sbin/gdm3

**Comment by noplay** [comment]
gdm is the login screen no?
