### ISSUE TITLE
Synchronization Issue between GNS3 Client and Server

### ISSUE THREAD

**Issue by MustafaTaqi** [GNS3/gns3-gui#2040]
Hello,
 My setup involves a  GNS3VM running on a remote box and a GNS3 client running from a MacBook air. I access the remote GNS3 server through my wifi AP, and  the AP occasionally reset itself cutting the connection between the GNS3 Client (running on a MacBook Air) and the GNS3 Server (GNS3VM running on a remote esxi box). The project just disappears after the loss of the connection forcing me to reopen the project and naturally all of my configuration is lost. 
Sometimes when I try to reopen the project the project status is Opened and the client can easily resynchronize itself with the server but most of the time that is not the case as I usually detect the connection issue after a while and not immediately and the server seems to close the project after a timeout period.

This is the output that I usually get on the GNS3 client console.

GNS3 management console.
Running GNS3 version 2.0.0 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.
Copyright (c) 2006-2017 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

*=> Can't get settings from controller
Error while getting compute list: Connection refused
Can't get settings from controller
Can't get settings from controller
Timeout request http://192.168.34.15:3080/v2/computes
Error while getting compute list: Operation timeout
Synchronisation lost with the server.
Synchronisation lost with the server.
Synchronisation lost with the server.
Synchronisation lost with the server.
Timeout request http://192.168.34.15:3080/v2/version
Timeout request http://192.168.34.15:3080/v2/version
Timeout request http://192.168.34.15:3080/v2/version
Timeout request http://192.168.34.15:3080/v2/version
Timeout request http://192.168.34.15:3080/v2/version
Synchronisation lost with the server.
Synchronisation lost with the server.
Synchronisation lost with the server.
Synchronisation lost with the server.*

-Is there any way in which I can increase the timeout timer or disable the timer completely to allow the client to always try to resynchronize with the server once the connection is restored?

-Is there a way to deliberately leave the project in an Opened state when the connection between the server and the client is lost or even if I exit the client software or open another project through the client. This will also add the benefit of being able to switch between projects without the need to reboot all virtual instances of a given project?

Regards
Mustafa Taqi

**Comment by Motysupra** [comment]
> Is there a way to deliberately leave the project in an Opened state when the connection between the server and the client is lost or even if I exit the client software or open another project through the client. 

This is actyally very important feature and I'm willing to know, if there is way to do this.

**Comment by noplay** [comment]
In the project settings you can keep it open

**Comment by MustafaTaqi** [comment]
Awesome.
I hate to admit it, but this could've saved me a lot of time.
Thank you
