### ISSUE TITLE
[2.0] periodically empty startup configuration when adding router.

### ISSUE THREAD

**Issue by Motysupra** [GNS3/gns3-gui#2042]
Update: I've opened another GNS3 client. the one in which I've created project, and everything works fine from it! 

I am running into this problem for second time now. 
Sometimes a new router created with empty startup configuration (right click on router>edit configuration shows empty list). Router like this starts up with default configuration and prompt "Would you like to enter the initial configuration dialogue? [yes/no]:" Problem is, that router like this won't save it's configuration no matter what.
For the first time problem disappeared with new project, but now, every single router I create, starts with this problem. I've tried to restart vm, but this does not work.  I am using 2.0 release and 2.0 remote vm on ESXI. I've been using all release candidates since rc2 before and upgraded vm via it's interface. Maybe I need clean installation on vm? 

An important note: I've been using multiple GNS3 clients, connecting to same GNS3 vm, but not simultaneously.

**Comment by noplay** [comment]
What kind of router?

**Comment by Motysupra** [comment]
Okay, I've located problem. I've created another gns3 vm from scratch, connected my second gns3 client to it, everything was ok, then I tried to connect from my second client to second gns3 vm and encountered this router saving problem. It seems, that after connecting one client to vm, it breaks normal operation of others clients with this vm, even after restart.

**Comment by noplay** [comment]
How do you save the configuration?

**Comment by noplay** [comment]
You have two client connected to the same the server.
* Client 1 alone can create router with correct configuration?
* Client 2 alone can create router with correct configuration?

Can you post screenshot of the router configuration in GNS3?

**Comment by Motysupra** [comment]
Client 1 alone can create router with correct configuration  

Yes

Client 2 alone can create router with correct configuration?

A freshly created router (R2)  with a second client looks like this:  https://s10.postimg.org/ukhlkqunb/gns3client.jpg 

I've uninstalled the second client by C:\Program Files\GNS3\uninst.exe and reinstalled it again: it now does save configuration via copy run start command, but when I right click on router either powered on  and click "edit config" it is still empty:
https://s14.postimg.org/ivxjui4td/wtfsave.jpg
Also, router console starts in user EXEC mode instead of privileged EXEC Mode (eq "Router>" instead of "Router#")
I'm going to test it a little bit more, I'm adding a third fresh vm, and connecting second client to it, everything is fine, within five hours I will come home and test this new fresh vm with first client.

**Comment by noplay** [comment]
Can you post the content of screen when you right click / settings on the
router in the left bar (before drag & drop)

**Comment by Motysupra** [comment]
I've tested it a little bit more and found out, where issue was. 
I was using not only different clients, but different windows machines with different user names. So the problem was here
https://s29.postimg.org/iqobs8a3r/problem.png
So when I upload ios image from other client, server memorizes path to startup-config, which pointing to a path, that does not exist on other machine. After fixing it everything is ok.

**Comment by noplay** [comment]
If you recreate the template from scratch you should have a relative path
(just the filename) and not an absolute path.

**Comment by noplay** [comment]
Do you have the correct path for configurations files in your settings?
![image](https://cloud.githubusercontent.com/assets/345437/25859286/57d86e06-34de-11e7-8082-5c253367c397.png)

**Comment by Motysupra** [comment]
@noplay no, I have C:\Users\admin\GNS3\configs in here, all 3 lines with complete path with disk and user folder. Should I change it to %HOMEPATH%\GNS3\configs ?

**Comment by noplay** [comment]
In your router settings just put ios_base_startup-config.txt not the full path

**Comment by noplay** [comment]
I think this confusion is because in 2.0 we don't manage configuration in a central location on the server. But in 2.1 we fixed that:
https://github.com/GNS3/gns3-server/issues/786

Don't hesitate to comment if you have questions
