### ISSUE TITLE
[2.0] small GNS3 topologies hogs lots of memory

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2047]
An opened GNS3 project (made of only containers) takes more and more memory if leaved untouched in the background:

![selection_999 029](https://cloud.githubusercontent.com/assets/1716020/25768941/561b980e-320e-11e7-9fb8-4ef639a471f3.png)

After closing the project, ~ 4GB is freed, that's huge for a couple of containers!

![selection_999 030](https://cloud.githubusercontent.com/assets/1716020/25768961/007eab88-320f-11e7-8bba-5f1cbf5af275.png)

(https://github.com/GNS3/gns3-server/issues/1016)

**Comment by noplay** [comment]
Two VPCS no memory leak:
![capture d ecran 2017-05-12 a 09 54 46](https://cloud.githubusercontent.com/assets/345437/25988652/1c9dd426-36f9-11e7-884d-85c0c62e3ff9.png)

**Comment by noplay** [comment]
Two docker no leak:
![capture d ecran 2017-05-12 a 10 00 07](https://cloud.githubusercontent.com/assets/345437/25988823/cf190d82-36f9-11e7-9fa5-6d1d7deac982.png)

**Comment by noplay** [comment]
No leak:
![capture d ecran 2017-05-12 a 10 08 03](https://cloud.githubusercontent.com/assets/345437/25989049/ea0f1a7c-36fa-11e7-8590-886f880b20d6.png)

**Comment by noplay** [comment]
I don't reproduce the issue. The memory will grow on client, but stop around 150mb  and server is very stable.

**Comment by grossmj** [comment]
I will run some tests as well.

**Comment by grossmj** [comment]
@AJNOURI 

It would be easier to see with a tree view in htop (F5 key) to identify which component of GNS3 leaks.

![tree_view](https://cloud.githubusercontent.com/assets/4752614/25999471/cd102cc4-3757-11e7-889e-0544211bfbe1.png)

**Comment by grossmj** [comment]
@AJNOURI 

Alternatively you can also share your lab (choose File -> Export portable project).

Thanks!

**Comment by AJNOURI** [comment]
Hey guys @noplay , @grossmj ,

Here is the exported file without images: [hpnouri.free.fr/misc/ovs-mirroring.gns3project](hpnouri.free.fr/misc/ovs-mirroring.gns3project)

Looks like /usr/local/bin/gns3 that hogs the memory

![selection_999 062](https://cloud.githubusercontent.com/assets/1716020/26025815/0952404e-37f0-11e7-9215-d6821a052fa1.png)

After:
![selection_999 063](https://cloud.githubusercontent.com/assets/1716020/26025833/5f6801f8-37f0-11e7-9e9b-1e13e4af2bc6.png)

**Comment by noplay** [comment]
Try to load it multiple time and I don't have the issue.

It's take a long time to grow like this?

Which version of PyQT, Python and Qt are you using? (you can see it at the bottom)

**Comment by AJNOURI** [comment]
Running GNS3 version 2.0.0 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2 and PyQt 5.3.2.

**Comment by noplay** [comment]
@grossmj do you reproduce on xenial?

**Comment by AJNOURI** [comment]
Upgraded to 2.0.1, same Qt/PyQT versions.

> Running GNS3 version 2.0.1 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2 and PyQt 5.3.2.

Should I upgrade them to the latest?

**Comment by noplay** [comment]
The version of qt and pyqt is provided by the the OS

**Comment by grossmj** [comment]
@AJNOURI 

Maybe you can test in a virtual environment? for instance:

```
python3 -m venv gns3test
source gns3test/bin/activate
pip3 install pyqt5
pip3 install gns3-gui==2.0.1
pip3 install gns3-server==2.0.1
```

**Comment by AJNOURI** [comment]
Same lab from the virt env:
Looks great, only handred if megabytes.

![screenshot - 190517 - 16 29 31](https://cloud.githubusercontent.com/assets/1716020/26252525/b70d763a-3cb0-11e7-8709-b5280ce9fe31.png)

**Comment by noplay** [comment]
It's confirm that it's bug in Qt :(  @grossmj what do you want to do with this one?
