### ISSUE TITLE
Behaviour when running as root/admin

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#2048]
People running GNS3 with root/admin break their permissions and create trouble. It's the N°1 source of bug reports.

Example:
* https://github.com/GNS3/gns3-gui/issues/2036
* https://github.com/GNS3/gns3-gui/issues/2024

Their is not good reason to run GNS3 like this. But when user have an issue they try running it as root.

Actually we just display a small warning in the console. I propose that we display a warning dialog at startup similar to what Wireshark is doing. 

And when a user start GNS3 as admin write a file in the settings ~/.config/GNS3/run_as_root and if this file is on the system disallow starting GNS3 as normal user.

**Comment by jtorri** [comment]
As usual I am confused.
1. Is the issue on Linux to consistently run either as root or as non-root user but to disallow switching between these two users in running GNS3 on Linux?  In my limited experience running GNS3 (version 1.4x through version 2.0) on Ubuntu, running GNS3 and VMWare as non-root user works fine.
2. Does one need to run GNS3 as administrator on Windows or merely as the same user one uses to run VMWare/Virtualbox which could be administrator?
As always, thanks for the great work you folks do!!

**Comment by noplay** [comment]
We don't want user running GNS3 as root on any OS. But we can't totally disallow it without breaking thing for current user :(

When you start using GNS3 as root, if you switch back you will break thing and complaints to the support.

Note: It's an open question, no decision about it

**Comment by noplay** [comment]
Why not changing it on Windows?

**Comment by grossmj** [comment]
> Why not changing it on Windows?

Users routinely run as an admin and Wireshark doesn't warn about this either.

**Comment by noplay** [comment]
For me the main issue is on Windows, because user don't know what they are
doing.

I think we can close this idea if we think it could disturb Windows users.

**Comment by grossmj** [comment]
@ziajka any opinion on this?

**Comment by ziajka** [comment]
IMHO, we should have same behavior as Wireshark (pop up on *nix and without message for Windows) + include info for Sentry (or don't send crash reports at all) + disallow change root->user as noplay suggests. We can see how it works and later change approach when needed.

**Comment by grossmj** [comment]
Exactly what I had in mind (excepting for Sentry) ;)
