### ISSUE TITLE
APIs v2.1 not returning list of appliances ?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2049]
c:\Utils\Curl>curl http://192.168.1.16:3080/v2/appliances
404: Not Found
c:\Utils\Curl>curl http://192.168.1.16:3080/v2/version
{
"local": false,
"version": "2.0.0"
}

From the documentation for v2.1

Using an appliance
First you need to list the available appliances

# curl "http://localhost:3080/v2/appliances"

[
{
"appliance_id": "5fa8a8ca-0f80-4ac4-8104-2b32c7755443",
"category": "guest",
"compute_id": "vm",
"default_name_format": "{name}-{0}",
"name": "MicroCore",
"node_type": "qemu",
"symbol": ":/symbols/qemu_guest.svg"
},
{
"appliance_id": "9cd59d5a-c70f-4454-8313-6a9e81a8278f",
"category": "guest",
"compute_id": "vm",
"default_name_format": "{name}-{0}",
"name": "Chromium",
"node_type": "docker",
"symbol": ":/symbols/docker_guest.svg"
}
]

**Comment by 1001QAdotNET** [comment]
Also discussed here: https://gns3.com/qa/where-are-the-templates-held-in-

**Comment by noplay** [comment]
Ok answered on the forum
