### ISSUE TITLE
1.3.0beta1: qemu VMs got mixed up after ending and restarting GUI

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#205]
My OS is OS X 10.9.5. From a clean state (deleted .config/gns3.net) I added two different qemu VMs and then closed GNS3. gns3_gui.conf looks fine.

Then a started GNS3 again. Now in the qemu preference one VM is duplicated, the other is gone. In gns3_gui.conf it's the same, two qemu VMs with duplicate information.

![qemu-duplicate-vm](https://cloud.githubusercontent.com/assets/896406/6619478/bc6e2d56-c8ca-11e4-88a6-c8257b00b964.png)

**Comment by grossmj** [comment]
Thanks for the report. Do you confirm you have only this issue with Qemu VMs?

**Comment by ehlers** [comment]
With dynamips router it's fine. I don't use VirtualBox and IOU, so I don't know for these VM types.

**Comment by grossmj** [comment]
Hi,

I have found the issue. This is fixed now.

Thanks,
