### ISSUE TITLE
Opening remote projects when a local server is defined

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2050]
Hey guys,

So when we have both a local and remote server setup, the open project dialog only allows selecting projects from the local device's filesystem.  Maybe the project library tab could either list all the projects everywhere, or even better, some kind of server selection dropdown?

**Comment by noplay** [comment]
How do you have a local and remote server setup? In theory you can have only one main server where project are located and you switch your main servers using the profile settings:
http://docs.gns3.com/1nCRIQ3AfdPbiYeL8RSC28Y_skgRJOfxPlz1MCeX94U4/index.html#h.6n1rqif3qmq9

**Comment by CapnCheapo** [comment]
We have it as sort of a "mixed" profile.  There's a work profile which is all remote, a home profile which is all local, and then a mixed which has both the local and remote as compute resources.  I guess how you have it setup makes sense though, I never really understood the difference between a server listed on remote servers tab and a "remote main server".

**Comment by noplay** [comment]
The main store the ressource , like configuration, symbols, appliances and act as a proxy.
The remote compute is just additional compute ressource.

Current design require to reload the application when you switch because the list of devices could change when you change server.
