### ISSUE TITLE
Some VMware VMs are not detected in the "New VMware VM Template" window

### ISSUE THREAD

**Issue by teomcpy** [GNS3/gns3-gui#2055]
I have several VMs in VMware Workstation Player (Windows 10). I have added most of them, but for some reason I cannot add the remaining ones, when going back to the "New VMware VM Template" window and trying to add a new VM to GNS3. 

I think this issue might be related to the fact that (some) VMs that appear below the GNS3 VM in the VM list in VMware are not seen by GNS3. Or at least it seems so.

I have an Ubuntu 16.04 VM in VMware, but I cannot add it in GNS3, because it is not detected at all. The only workaround I found, in order to add my Ubuntu VM to my topology, was to use a Cloud element, but that way I am not allowed to export a portable project.

Also, if you check my screenshot, I am not able to see the ASAv VM in GNS3 neither.
![gns](https://cloud.githubusercontent.com/assets/17598803/25910312/9adc1d62-35b8-11e7-91ab-c6576d4072e3.jpg)

**Comment by noplay** [comment]
I think this VM are not stored in the VMware standard location. If it's the case we are limited by what player return. 

Do you confirm?

**Comment by teomcpy** [comment]
Yes, I confirm. Thank you!
