### ISSUE TITLE
Save state feature

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2058]
While reading https://github.com/GNS3/gns3-gui/issues/725, it made me think that our suspend feature is more like a pause feature (temporarily put a VM on hold). We could implement a "full suspend" feature which saves the state of a VM and then stop it. The benefit is that starting the VM again is much faster.

Qemu, VirtualBox and VMware support that "full suspend" mode. Now the question is how to we implement it in GNS3?

We could ask a question before stopping a VM just like VirtualBox does but this is not practical in GNS3.

![virtual_box_save_state](https://cloud.githubusercontent.com/assets/4752614/26025181/48999b20-3814-11e7-9215-2bbb24eb9487.png)

I think the best option is just to have a new setting (enabled by default) in the Qemu, VMware and VirtualBox VM settings just like what we did for ACPI shutdown option for VirtualBox VMs.

![vbox_settings](https://cloud.githubusercontent.com/assets/4752614/26025198/c43f387a-3814-11e7-871b-59115e08c5e9.png)

Any suggestions?

**Comment by grossmj** [comment]
I see one potential problem to save VM state by default, it is going to increase the size of the project folder, this could be huge and problematic if an user wants to share his/her lab.

**Comment by noplay** [comment]
I think it's not possible with docker

**Comment by grossmj** [comment]
Wouldn't be really useful for Docker anyway.

**Comment by noplay** [comment]
Yes but we need to be carefull that user doesn't image they could save and
restore a whole topology state.

**Comment by noplay** [comment]
Also this need to be clear that they have no warranty this will work and
they still need to save configuration. If you are on Linux a qemu upgrade
could break the memory save I think.

**Comment by grossmj** [comment]
Yes, we have to be really careful with that feature.

**Comment by grossmj** [comment]
Yes, we have to be really careful with that feature.

**Comment by grossmj** [comment]
The state of Qemu, VMware and VirtualBox VMs can now be saved and restored.

Ref https://github.com/GNS3/gns3-server/commit/ea0009db6ce8e2f2823e1ac004b5771054ba9d12
