### ISSUE TITLE
[2.0] Bug with api and several server

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2059]
Hi

On Live Raizo, i have a script (Add-to-GNS3) to add VMBox in GNS3.
It uses your api when GNS3 is already started.

With 1 student , one time, it didn't work (GNS3 doesn't show the VM). But i don't know what he did to generate this bug.

I seek and found little bug in my code but also in GNS3 with a situation. But, ok, this situation is not usual ;-)

- I start GNS3 and open a project.
- In the same time, i start a second GNS3 (who ask if i want a other GNS3. I don't choose yet)
- I upload the new config in GNS3 with the api (  wget  --post-file="FileWithNewConfig.json" "http://localhost:3080/v2/settings" )
- Ok, the first GNS3 shows the new VBox in the list
- In the second GNS3, i refuse to start a second server (i click on "No")
- The first GNS3 remove  the new VBox of the list

**Comment by noplay** [comment]
When you say " i refuse to start a second server (i click on "No")" which dialog do you have? Because you are not suppose to be able to start a second server. 

Is it when GNS3 told you another GNS3 is running? It's just about the GUI, but perhaps the confusion is here.

**Comment by Raizo62** [comment]
> Is it when GNS3 told you another GNS3 is running?

Yes, this is that.
I think that the second GUI saves his "old" config when it exits, but it must not do that.

**Comment by noplay** [comment]
Thanks I will test this scenario

**Comment by noplay** [comment]
What is the content of FileWithNewConfig.json ?

I know that current API is far away to be perfect for adding VM. 2.1 add a real API for that.

**Comment by Raizo62** [comment]
> What is the content of FileWithNewConfig.json ?

I download the file "http://localhost:3080/v2/settings"
In ".VirtualBox.vms" of this file, i add in json format the config of the VMBox.
I upload this file with : wget --post-file="${FileWithNewConfig}" "http://localhost:3080/v2/settings"

> I know that current API is far away to be perfect for adding VM. 2.1 add a real API for that.

can we use 2.1 ? or GNS3 2.1 is very more "beta" than 2.0 ?

**Comment by noplay** [comment]
2.1 is not stable for the moment. We are aware of big bug

**Comment by Raizo62** [comment]
> > What is the content of FileWithNewConfig.json ?
> 
> I download the file "http://localhost:3080/v2/settings"
> In ".VirtualBox.vms" of this file, i add in json format the config of the VMBox.
> I upload this file with : wget --post-file="FileWithNewConfig" "http://localhost:3080/v2/settings"
> 

Do i use badly your API to do that ?

**Comment by noplay** [comment]
I don't think. It's look correct. But i didn't reproduce it yet (not hard
tested) :(

**Comment by noplay** [comment]
I didn't replicate the problem but I made a change when you click on No we instant exit instead of a clean shutdown.

**Comment by Raizo62** [comment]
I have tested. It is ok :-) Thanks
