### ISSUE TITLE
Status Color indication between link stay green. 

### ISSUE THREAD

**Issue by jonathan-roy-8** [GNS3/gns3-gui#2061]
Using Windows 7 pro 64bit, i7-4770 16Gb ram and GNS3 2.0.0
Creating new project, the link circle around each end of a link doesn't turn to red when it's shutdown manualy. It's red when the router is turn off. 
I run GNS3 localy. 
Not sure what can i do to help you guys? how to provide log 

![image](https://cloud.githubusercontent.com/assets/16581951/26037587/4d460b62-38c4-11e7-992c-d11512cbed73.png)

**Comment by noplay** [comment]
Hi,

This normal the status of the port is not reflected on the topology. The main reason is appart some special cases we don't have access to it.
