### ISSUE TITLE
Print support

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#2062]
The ability to print a topology. The graphic topology should be scale to fit the paper.

The background need to be white. Not gray if the user use the charcoal style.

**Comment by noplay** [comment]
@grossmj do you have an idea why we didn't implement it yet? It doesn't sound complicate to implement using PyQt, but I probably miss something.

**Comment by noplay** [comment]
Tweet about that: https://twitter.com/nfvguy/status/864223740388921345

**Comment by grossmj** [comment]
We need to know what we want to print, just a screenshot of a topology or more than this?

There are classes in Qt that handle printing, like QPrinter.

**Comment by noplay** [comment]
The graphic view widget.  Ideally we should adapt the topology to one sheet
of paper

**Comment by grossmj** [comment]
I don't see what this would bring over the screenshot feature.
