### ISSUE TITLE
GNS3 2.0.1 errors on install and first run

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2071]
Windows 10 Prof x64.  GNS3 2.0.1 GNS3 VM version 2.0.1  Errors during install and during first run of GNS3 2.0.1 application.  Is a "ghost" version of GNS3 2.0.1 being started?
![gns3-2 0 1-1](https://cloud.githubusercontent.com/assets/10285348/26271480/675b6b00-3cd4-11e7-8146-7f40037e282f.png)
![gns3-2 0 1-2](https://cloud.githubusercontent.com/assets/10285348/26271481/69e7ebfa-3cd4-11e7-86d5-760d59bc93c9.png)

**Comment by jtorri** [comment]
GNS3 2.01 works fine on Ubuntu 16.04.  Upgraded from 2.0 to 2.01 via apt-get upgrade.  I'm guessing I have done something wrong on Windows version but have not yet had time to investigate.

**Comment by noplay** [comment]
It's a common error. Their is something on your system that prevent the connection. Often it's an antivirus / firewall blocking the process. You need to whitelist gns3.exe and gns3server.exe
