### ISSUE TITLE
clock is lost when router is reloaded despite saving config

### ISSUE THREAD

**Issue by swils024** [GNS3/gns3-gui#2075]
While doing the Cisco CCNA (200-125) - Pass with GNS3 course on GNS3 Academy, I noticed that a user had commented on one of the NTP videos saying that the clock setting is lost when a router is reloaded. I have replicated the issue and despite saving the config before the reload, the config was lost. All comments welcome.

**Comment by noplay** [comment]
When using dynamips?

**Comment by swils024** [comment]
Yes using dynamips I was using one of the recommended IOS images.

Regards,
Stephen

**Comment by noplay** [comment]
This issue was moved to GNS3/dynamips#80

**Comment by noplay** [comment]
Thanks I move the issue to the dynamips project. If you can follow it in order to get the notification that will be nice.
