### ISSUE TITLE
[2.0.1] Possibility to stop automatic scrolling of the console dock

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2076]
Because the console is constantly scrolling to showing received events, it is not possible to read eventual error messages.
![selection_999 088](https://cloud.githubusercontent.com/assets/1716020/26288130/415ba65a-3e8b-11e7-8faa-8e7b67db2738.png)

It would be great if the user could stop the scrolling.

**Comment by noplay** [comment]
If you don't start with debug you will have only the error. Or you can start GNS3 in a terminal in order to have a better console program.
