### ISSUE TITLE
[2.0.1] Issue with custom symbol.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2077]
1- When trying to change a node symbol with a **custom** one,
The symbol selection dialog box is no more reactive (except box upper right buttons)
Possible actions:
- "Open project" doesn't loaded the chosen project to the canvas. 
- "Create a blank project" reload the **same project** :-|
- Close and reopen GNS3.
![selection_999 087](https://cloud.githubusercontent.com/assets/1716020/26288156/0dd939b8-3e8c-11e7-99bd-24b911342dc5.png)

2- Subsequent times, when trying the same thing with the same device, it just switch to "hotst" symbol:
![selection_999 089](https://cloud.githubusercontent.com/assets/1716020/26288140/88768f46-3e8b-11e7-9b7a-b933f43b7d7a.png)

This happens only with custom symbols

**Comment by noplay** [comment]
Is it when using your old Qt? Or in the virtualenv with a recent Qt?

It's work fine for me.

**Comment by noplay** [comment]
Did you try with GNS3 2.0.2?

**Comment by AJNOURI** [comment]
Looks great with 2.0.2
If the svg file is somehow corrupted, it informs the user and use an appropriate symbol instead.

![selection_0010](https://cloud.githubusercontent.com/assets/1716020/26640119/16cd0016-4627-11e7-985d-4048602f9fbf.png)


I close the issue.
Thanks a lot @noplay

**Comment by noplay** [comment]
Thanks for the feedback!
