### ISSUE TITLE
[2.1] Stop supporting ubuntu trusty for GUI?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#2080]
I propose that we drop support for ubuntu trusty in 2.1.

Trusty is no longer the current LTS release. Xenial replaced it.

Their is mostly two changes interesting:
* Python 3.4 (Xenial: Python 3.5)
* Qt 5.2 (Xenial: Qt 5.5)

I think dropping support for Qt 5.2 could be a benefits. We see from @AJNOURI that we have multiple issues with this version:
* https://github.com/GNS3/gns3-gui/issues/2047

I propose the change only for GUI, because the GNS3 VM still use trusty.

**Comment by noplay** [comment]
Another benefits we could use websocket to connect to the notification avoiding the need to trick with an HTTP stream. It's a new feature of Qt 5.3. 

This could solve the random disconnect from project that we see with aiohttp 2.0

**Comment by noplay** [comment]
See also #2084

**Comment by grossmj** [comment]
I am ok to stop supporting Ubuntu trusty.

**Comment by grossmj** [comment]
@noplay now
