### ISSUE TITLE
[2.0.0] No VMnet interface available between vmnet2 and vmnet19

### ISSUE THREAD

**Issue by allwynmascar** [GNS3/gns3-gui#2081]
I keep getting this mostly in a project where I am trying to start 2 Fortigate VMs together in the same GNS3 project.

```
=> error while starting FGT5.2-1: No VMnet interface available between vmnet2 and vmnet19. Go to preferences VMware / Network / Configure to add more interfaces.
No VMnet interface available between vmnet2 and vmnet19. Go to preferences VMware / Network / Configure to add more interfaces.

```

This is the state of the VMnet adapters on VMware.

![2017-05-24 17_28_27-fgt5 2-2 - vmware workstation](https://cloud.githubusercontent.com/assets/23822784/26405483/7ddb3d4e-40a6-11e7-8898-899ce151dd92.jpg)

Seems this can be a permissions issue. Here's the process explorer which shows the users.

![2017-05-24 16_49_53-process explorer - sysinternals_ www sysinternals com agora_allwyn](https://cloud.githubusercontent.com/assets/23822784/26405545/af1a91c0-40a6-11e7-890b-b329a220c8b3.jpg)

Version details:
GNS3
```
GNS3 management console.
Running GNS3 version 2.0.0 on Windows (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.
Copyright (c) 2006-2017 GNS3 Technologies.

```
VMware

![2017-05-24 17_32_09-fgt5 2-2 - vmware workstation](https://cloud.githubusercontent.com/assets/23822784/26405687/1aefcbe0-40a7-11e7-8557-380c6d280899.jpg)

**Comment by noplay** [comment]
How many interface do you have on each fortigate?

**Comment by allwynmascar** [comment]
One has 5 and the other has 4.

**Comment by noplay** [comment]
You need to create more VMNet on your system. Each interface will consume a VMnet and VMnet0 doesn't count.

**Comment by allwynmascar** [comment]
The thing is that most vmnets were still free and not being used anyway.

And should I assign any vmnets in vmware at all or just assign them all to
a single vmnet? There's also an option to just leave it as host only.

**Comment by allwynmascar** [comment]
And just to add I already had upto 12 vmnets initially. I then deleted them
thinking that would help. And hence now there are just upto 5 of them.

**Comment by grossmj** [comment]
Have you tried to create the vmnet interfaces from GNS3? (Preferences -> VMware -> Advanced Local Settings -> Configure).

**Comment by allwynmascar** [comment]
yes I always increase the number of adapters here.

[image: Inline image 1]

Do i need to set any vmnets in vmware to the interfaces?

For eg. this is fgt5.2-2 vmware which has started correctly from gns3 but
the 1 is giving me the no vmnet error.

this is the setting in vmware for this working fgt machine

[image: Inline image 2]

**Comment by Wahid-Uz-Zaman** [comment]
1. first , you should check how many VMnet adapters your machine have. (like `ifconfig` from ubuntu terminal)
now, if theres limited VMnet adapters, the best way to create VMnet adapters is through GNS3. Go to Edit -> Preference. You should get like this 
![gns3_adapter](https://cloud.githubusercontent.com/assets/6999433/26527958/08cc034e-43c1-11e7-8507-c2574f3fb581.png)
Now, you can choose  adapters quantity. then select `configure`. then we will see that required adapters is created. You can also check by `ifconfig` commands.


2. Now, in your VMware worksation, you need to assign different VMnet (custom/VmnetX) adapters for each interface. and you should make only one `bridged` if theres management port in the VM(accessible through http)

3. You should connect VM using cloud in gns3.(add VMs adapters maually in the cloud and use that cloud in gns3). @allwynmascar

**Comment by allwynmascar** [comment]
> You should connect VM using cloud in gns3.(add VMs adapters maually in the cloud and use that cloud in gns3).

But then that won't use the built in integration. Kinda beats the point of the VMware option in edit - pref if the cloud is to be used anyway, right?

I will still try it and report back.

**Comment by allwynmascar** [comment]
HI, I tried out the suggestions. I added the vmnets from gns3 - pref - config and then added them using the cloud as below.

![2017-05-28 21_30_36-node properties](https://cloud.githubusercontent.com/assets/23822784/26530850/0cb5c5c6-43ee-11e7-9621-c8343a56a12e.jpg)

![2017-05-28 21_30_57-virtual machine settings](https://cloud.githubusercontent.com/assets/23822784/26530866/65adca0c-43ee-11e7-8f51-9df5489add22.jpg)

There's these errors. 

```
unable to create NIO Ethernet for bridge 'ethernet0.vnet': nio_ethernet_open: unable to open device '\Device\NPF_{E469C1F2-2A31-43DC-8B4D-DF13DD1C1FC2}': Error opening adapter: The system cannot find the device specified. (20)
unable to create NIO Ethernet for bridge '7a2caea2-67d2-4aa0-9700-e1033fb7e3fc-0': nio_ethernet_open: unable to open device '\Device\NPF_{8B148541-ABE1-4FE3-8FE5-28B5F2E14B10}': Error opening adapter: The system cannot find the device specified. (20)

unable to create NIO Ethernet for bridge '7a2caea2-67d2-4aa0-9700-e1033fb7e3fc-0': nio_ethernet_open: unable to open device '\Device\NPF_{8B148541-ABE1-4FE3-8FE5-28B5F2E14B10}': Error opening adapter: The system cannot find the device specified. (20)

```

**Comment by noplay** [comment]
I think the type of interface need to be Custom not bridge.

**Comment by allwynmascar** [comment]
Yeah it's custom vmnets in the vmware. There's only one bridged network
option  haven't chosen that.

**Comment by allwynmascar** [comment]
Just to confirm then is the built-in vmware integration broken and cloud is
the only way to use VMs?

**Comment by noplay** [comment]
The integration is not broken. But it's require that the VMware is correctly configured (I don' say you make something wrong, but could be something related to another software).

I recommend that you delete all your vmnet adapters and recreate them from the GNS3 preferences.

**Comment by allwynmascar** [comment]
But then will that be compatible with some vms which I'm already using but
not related to gns in anyway?

**Comment by noplay** [comment]
Not sure. GNS3 try to do his best to not break already existing VMware that's why you can't start the VM.

If you have special network configuration for some VMnet do not use them in GNS3. For example you can attribute the range vmnet20 to vmnet50 to GNS3.

Alternatively you can run the GNS3 VM and use Qemu Fortigate VM. It's probably a better supported solution.

**Comment by allwynmascar** [comment]
>Alternatively you can run the GNS3 VM and use Qemu Fortigate VM. It's
probably a better supported solution.

Those then require virtualization images. I don't think fortigate supplies
them.

I'll try the vmnet deleting method and report back.

On May 29, 2017 2:59 PM, "Julien Duponchelle" <notifications@github.com>
wrote:

Not sure. GNS3 try to do his best to not break already existing VMware
that's why you can't start the VM.

If you have special network configuration for some VMnet do not use them in
GNS3. For example you can attribute the range vmnet20 to vmnet50 to GNS3.

Alternatively you can run the GNS3 VM and use Qemu Fortigate VM. It's
probably a better supported solution.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/2081#issuecomment-304634096>, or mute
the thread

**Comment by cioby23** [comment]
> probably a better supported solution.
Those then require virtualization images. I don't think fortigate supplies
them.

Fortigate does provide qcow2 imagesfor their Fortigate products. Check the GNS3 marketplace for the Fortinet appliance template.
https://gns3.com/marketplace/appliance/fortigate

**Comment by allwynmascar** [comment]
Well yes but then there are license requirements I guess. Just like cisco
has for are.

On May 29, 2017 3:29 PM, "cioby23" <notifications@github.com> wrote:

probably a better supported solution.
Those then require virtualization images. I don't think fortigate supplies
them.

Fortigate does provide qcow2 imagesfor their Fortigate products. Check the
GNS3 marketplace for the Fortinet appliance template.
https://gns3.com/marketplace/appliance/fortigate

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/2081#issuecomment-304639107>, or mute
the thread

**Comment by noplay** [comment]
It should be the same licence

**Comment by allwynmascar** [comment]
HI!

For now using the cloud and adding vmnets to it has been working fine. 

But I found one issue such that when you add a cloud for fortigate vm and say another for msloopback, it seems there are issues like gns starts freezing etc.

**Comment by noplay** [comment]
By using cloud you will probably get noise from the host OS (broadcast from application like  Dropbox) and this can slow down the machine.

**Comment by allwynmascar** [comment]
Hey that's exactly what's happening. 

Right now i was doing a splunk lab, and wondering why is it catching dropbox traffic!

![2017-05-31 17_44_53-search _ splunk 6 6 0](https://cloud.githubusercontent.com/assets/23822784/26634922/2b3f9520-4629-11e7-8b62-dea38048557c.jpg)

I'm still confused. Why exactly dropbox? You say host OS but I don't even have it installed.

**Comment by noplay** [comment]
The problem is the Dropbox on your host will send packet to all adapters including the adapter you use in the cloud.

**Comment by allwynmascar** [comment]
But I dont have dropbox installed at all. And still I see this traffic.

**Comment by noplay** [comment]
Perhaps one computer on your network?

**Comment by noplay** [comment]
I don't know. It's inside the host OS, GNS3 as not control on that.

That's why we have the GNS3 VM, in order to have a host OS that we can control.

**Comment by mwadmakki** [comment]
![Uploading Screenshot 2024-07-08 202304.png…]()
