### ISSUE TITLE
server replied: Forbidden, Running GNS3 version 2.0.1 on Linux (64-bit) with Python 3.5.3 Qt 5.7.1 and PyQt 5.7.

### ISSUE THREAD

**Issue by cciecamer** [GNS3/gns3-gui#2083]
hello,
i am not able to open my old projects with new version gns3-gui-2.0.1 and gns3server-2.0.1,
and also after created a new project i can not open it after saving.

i got this error message:

Error transferring http://admin@127.0.0.1:8000/v2/projects/load - server replied: Forbidden 

please i need help,
cordially.

**Comment by noplay** [comment]
This sound like a permission issue. Your user as the ownership on all files of the project (nothing own by root)?

**Comment by cciecamer** [comment]
![screenshot from 2017-05-26 14-58-54](https://cloud.githubusercontent.com/assets/28951077/26497787/9a77afb2-4224-11e7-974f-65233856f043.png)

**Comment by noplay** [comment]
You are running GNS3 as root?

**Comment by cciecamer** [comment]
in root mode i can open my old project.










*******************************************************
*Auguste FOTSO DEFO*
*Ing. Travaux Systèmes & Réseaux*
CCIE SECURITY *#54491*, CCNA R&S, LPI 010-150
(+237)675542731/655874670

**Comment by noplay** [comment]
That the problem I think the files of your old project as owned by root that's why you can't open them as a normal user

**Comment by elshobokshy** [comment]
Hello,
I got the same problem on windows 10. I created the project using a regular user. And now I need to open the projet using "Run as administrator" for the server to work properly and I can't load my regular user projet ... I get the same error. Any ideas ?
