### ISSUE TITLE
[2.0] no communicate between "ethernet switch" and IOU

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2089]
Hi

I have always the bug with network of VMBox Linux when virtual acceleration is not activated on the real PC (I must shutdown and restart the card in the VM). I don't know if the BUG is in Linux, VirtualBox, GNS3 or config of "LiveRaizo"

I have a another bug that, i hope, comes from the same cause.

My real PC is with Windows 10
Live Raizo is started in VirtualBox (then virtual acceleration is disable : On VirtualBox : Configuration / System / tab "Acceleration" is grey)

I do this schema : 
![schema_bug_no icmp between_switch_and iou](https://cloud.githubusercontent.com/assets/7449584/26644675/d0ea46f8-4635-11e7-9aa7-35f5e7357968.png)

I have no communicate between "SW1" and SWL3-1 : more exactly : SWL3-1 seems not to "capture" the frames from "SW1", but frames seems go out of "SWL3-1" to "SW1".

I have do a video (with VirtualBox) to have order of commands (send by mail because 29Mo)

Here Bug Log : 
[bug.zip](https://github.com/GNS3/gns3-gui/files/1042376/bug.zip)

Here netstat output :
[netstat.txt](https://github.com/GNS3/gns3-gui/files/1042378/netstat.txt)

I can't reproduce all times but very often.

**Comment by noplay** [comment]
Could be a bug in the IOU image did you try with a different image?

**Comment by Raizo62** [comment]
Which images do you advise me to try ?

**Comment by noplay** [comment]
Just another image you have access to. I was talking recently with someone using recent IOU and ethernet switch and he didn't report similar troubles.

**Comment by Raizo62** [comment]
I use "often" IOU and ethernet switch and I don't see this bug when I start LiveRaizo directly on a true PC with virtual acceleration enable. (I know that "Don't see" doesnt say "Don't exist").
This is why i did not try an another IOU. But i can. 

More info : On IOU, i give an IP to the VLAN 1, then I can ping this IP from Debian-1, but not from PC1.

**Comment by noplay** [comment]
As far I know virtual acceleration should not affect IOU.

**Comment by Raizo62** [comment]
Perhaps it is more slow and there is conflict on access to port.....(i have no explain, but we see it :-) )

**Comment by noplay** [comment]
Possible. The speed is probably the problem. Raising some kind of timeout
somewhere

**Comment by Raizo62** [comment]
Could you explain me how SW1 and SWL-1 communicates their network frames ? (link between ubridge, dynamips... with fictives but realistics ports).
Yesterday, i have tried to inspect but there are too many opens ports and i am lost....

**Comment by noplay** [comment]
Their is an upd tunnel between dynamips and ubridge, after that ubridge
write on the unix socket of IOU.

**Comment by Raizo62** [comment]
> Possible. The speed is probably the problem. Raising some kind of timeout somewhere 

If you wish, i can test this. But you must say me which variables can be increase or decrease. (and where i must change this values ;-) )
so, i will can test also the "same" bug with Vbox....

**Comment by noplay** [comment]
I think it's internal to IOU you can't tune it.

**Comment by Raizo62** [comment]
if i suppose that is a timeout problem and it is also the cause of VBox bug, then i can suppose that the bad delay is not in IOU. So, what is the common program ? ubridge ? Can i change timeout variables in ubridge (if ubridge can have this problem) ?

**Comment by noplay** [comment]
ubridge as no timeout he just pass packet from one side to another.

**Comment by Raizo62** [comment]
You are not funny.

This evening, i have tested again the lab. Surpise, this is the VM Debian-1 who sends but not receiv the frames. SWL3-1 and ESW1 seem to work correctly.
The last time that VMBox had this bug with my students, i didn't use IOU. Then i think that the bug is not in IOU.

**Comment by Raizo62** [comment]
Perhaps that i found the bug with VMBox : It seem disapear when i change the type of netword card of "Intel PRO/1000 MT Desktop (82540EM)" to "PCNet-FAST III (Am79C973)". But i must do more tests to verify.

But, even with this "patch", the bug with IOU is again here :-(

**Comment by Raizo62** [comment]
I just see that i can reproduce the bug with only PC1, "SW1" and SWL3-1 (connected as on the first schema, and always in virtualbox and disable virtual acceleration)

Then SWL3-1 doesn't ping SW1 (with wireshark : i see packet go out and go in, but SWL3-1 doesn't see the answer )

After, i add 2 sames IOU connected to SW1. The ping from PC1 to this 2 IOU work.

If i do on LiveRaizo : sudo lsof | grep /tmp/netio
```
ubridge   2263      user    5wW     REG               0,39         5      23729 /tmp/netio1000/513.lck
ubridge   2263      user    6u     unix 0xffff90443f3ef000       0t0      23730 /tmp/netio1000/513
ubridge   2263 2264 user    5wW     REG               0,39         5      23729 /tmp/netio1000/513.lck
ubridge   2263 2264 user    6u     unix 0xffff90443f3ef000       0t0      23730 /tmp/netio1000/513
ubridge   2263 2266 user    5wW     REG               0,39         5      23729 /tmp/netio1000/513.lck
ubridge   2263 2266 user    6u     unix 0xffff90443f3ef000       0t0      23730 /tmp/netio1000/513
i86bi-lin 2265      user    3wW     REG               0,39         5      22690 /tmp/netio1000/1.lck
i86bi-lin 2265      user    4u     unix 0xffff9044358fe400       0t0      22691 /tmp/netio1000/1
ubridge   2404      user    5wW     REG               0,39         5      25069 /tmp/netio1000/514.lck
ubridge   2404      user    6u     unix 0xffff90443a0fb800       0t0      25070 /tmp/netio1000/514
ubridge   2404 2405 user    5wW     REG               0,39         5      25069 /tmp/netio1000/514.lck
ubridge   2404 2405 user    6u     unix 0xffff90443a0fb800       0t0      25070 /tmp/netio1000/514
ubridge   2404 2407 user    5wW     REG               0,39         5      25069 /tmp/netio1000/514.lck
ubridge   2404 2407 user    6u     unix 0xffff90443a0fb800       0t0      25070 /tmp/netio1000/514
ubridge   2404 2408 user    5wW     REG               0,39         5      25069 /tmp/netio1000/514.lck
ubridge   2404 2408 user    6u     unix 0xffff90443a0fb800       0t0      25070 /tmp/netio1000/514
i86bi-lin 2406      user    3wW     REG               0,39         5      20338 /tmp/netio1000/2.lck
i86bi-lin 2406      user    4u     unix 0xffff90443f335000       0t0      20339 /tmp/netio1000/2
ubridge   2433      user    5wW     REG               0,39         5      25901 /tmp/netio1000/515.lck
ubridge   2433      user    6u     unix 0xffff90443f335800       0t0      25902 /tmp/netio1000/515
ubridge   2433 2434 user    5wW     REG               0,39         5      25901 /tmp/netio1000/515.lck
ubridge   2433 2434 user    6u     unix 0xffff90443f335800       0t0      25902 /tmp/netio1000/515
ubridge   2433 2436 user    5wW     REG               0,39         5      25901 /tmp/netio1000/515.lck
ubridge   2433 2436 user    6u     unix 0xffff90443f335800       0t0      25902 /tmp/netio1000/515
ubridge   2433 2437 user    5wW     REG               0,39         5      25901 /tmp/netio1000/515.lck
ubridge   2433 2437 user    6u     unix 0xffff90443f335800       0t0      25902 /tmp/netio1000/515
i86bi-lin 2435      user    3wW     REG               0,39         5      25224 /tmp/netio1000/3.lck
i86bi-lin 2435      user    4u     unix 0xffff90443e553000       0t0      25225 /tmp/netio1000/3
```
Is it correct that  /tmp/netio1000/513 is 3 times and the others is 4 times each ?

I have restarted the lab with "debug 2" in GNS3
The data in the file "projects/untitled/project-files/iou/1273c7dd-3e87-45af-ab12-dcc0dccf1982/ubridge.log"
> sendto: No such file or directory

**Comment by grossmj** [comment]
Hi @Raizo62, please try with the latest dev version of uBridge:  https://github.com/GNS3/ubridge

Thanks :)

**Comment by Raizo62** [comment]
I have tested : It works :-) Thanks :-)
