### ISSUE TITLE
[2.0] Bug : lost of old file for startup-config of IOU

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2091]
Hi

I create a template for IOU :
IOU image path : file1
Startup-config : startup_perso

I restart GNS3

I open the config of my IOU template, and change only the IOU image path (to file2, for example).
Then GNS3 change also my Startup-config (startup_perso) to your default Startup-config (iou_l2_base...)

**Comment by noplay** [comment]
Thanks it's fixed
