### ISSUE TITLE
High CPU Utilization - GNS3 Version 2.0

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2094]
I'm using VIRL images on GNS3 version 2.0.2 on Windows 64-bits.  When I start a project CPU utilization on GNS3 VM hit 100% and stays there.  Its been running at 100% for the past 30 mins.  My topology has 20 cisco-iosv and 2 cisco-csr1000v..  RAM utilization is fine.  Please see attached screenshots

![Uploading High CPU.png…]()
![Uploading CSR1Kv image.png…]()

**Comment by noplay** [comment]
Are you using VMware or VirtualBox ? If it's vmware when you start the GNS3 VM KVM is working?

**Comment by fatbell** [comment]
Thanks for the prompt response.  I'm using VMware and the VM KVM is working

**Comment by noplay** [comment]
Your windows is running bare metal, not on ESXI or something like that?

**Comment by fatbell** [comment]
Its Windows on bare metal

**Comment by fatbell** [comment]
Its still running at 100% after 1 hour

**Comment by noplay** [comment]
Did you try to stop  cisco-csr1000v to see if it's the source of the problem?

**Comment by fatbell** [comment]
Just shutdown the two CSR1000v routers.  CPU utilization is flapping between 0% and 100%.  Please see attached
![cpu utilization - 0 percent](https://user-images.githubusercontent.com/17806351/26856808-16e41a54-4af4-11e7-8b81-e1200e243d48.png)
![cpu utilization - 100 percent](https://user-images.githubusercontent.com/17806351/26856807-16e3db34-4af4-11e7-9e06-f5efd9ca9ca4.png)

**Comment by noplay** [comment]
How much ram do you have allocated to each node?

**Comment by fatbell** [comment]
The two CSR1000v each has 2560MB and all other nodes are IOSv and each has 512MB.

![csr1kv ram](https://user-images.githubusercontent.com/17806351/26870773-0eedbe54-4b3f-11e7-912f-905a8b5193d6.png)
![iosv ram](https://user-images.githubusercontent.com/17806351/26870774-0eee1264-4b3f-11e7-9c3d-fd856f6ce7f8.png)

**Comment by noplay** [comment]
VIRL calculator say CSR1000v  need at least 3072 perhaps it's create trouble if you have less http://virl.cisco.com/resource/

**Comment by fatbell** [comment]
I have changed the RAM to 3072 but still CPU is 100%

**Comment by noplay** [comment]
Do you have the trouble with other qemu images?

**Comment by fatbell** [comment]
I added 8 of IOSXRv and the CPU utilization
![six iosxrv](https://user-images.githubusercontent.com/17806351/26963724-0e5da192-4cbc-11e7-9169-7daa6db70f58.png)
 was pretty good.  Please see attached

**Comment by noplay** [comment]
Sadly it will hard to help you the problem seem to be in CSR

You can test to use virtio has disk interface instead of ide could allow you to gain performance if CSR support it

**Comment by fatbell** [comment]
Will delete the CSR and re-install it.  Thank you for your time and effort

**Comment by fatbell** [comment]
After a very long period of time CPU utilization reduced to 40 percent.  Please close this and thank you for your time.

**Comment by noplay** [comment]
Thanks for the feedback
