### ISSUE TITLE
GNS3 VM cannot complete boot process

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2095]
I have set up GNS3 VM ver 2.0.2 on a bare Windows 64-bits machine.  VM used to work perfectly but since last night VM will not complete the boot process.  Please see attached screenshot
![gns3 vm not running](https://user-images.githubusercontent.com/17806351/26864078-1b070e18-4b24-11e7-97b3-5e1b36506b4a.png)

**Comment by noplay** [comment]
If you press the Escape key do you have something?

**Comment by fatbell** [comment]
This is what comes on the screen after Esc key is pressed.
![gns3 vm boot process after esc key pressed](https://user-images.githubusercontent.com/17806351/26871310-c16ca2f6-4b40-11e7-9fe1-1ef46beac90b.png)

**Comment by noplay** [comment]
Sound like the virtual disk is damage you should try to fix the error by pressing F.

**Comment by fatbell** [comment]
F key worked.  Thanks

**Comment by noplay** [comment]
Thanks for the feedback
