### ISSUE TITLE
Bug in nodes dock widget

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2100]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/nodes_dock_widget.py", line 44, in _filterIndexChangedSlot
    self.window().uiNodesView.setShowInstalledAppliances(False)
AttributeError: 'NodesDockWidget' object has no attribute 'uiNodesView'
```

**Comment by grossmj** [comment]
This bug is very random, you can get it when playing with the drop down list to filter installed/available appliances.

**Comment by noplay** [comment]
Do you still have the issue @grossmj ? I try to reproduce without luck. I don't see how I can happen because we don't create it dynamically, so window() should not return itself but the MainWindow

**Comment by grossmj** [comment]
I cannot reproduce but as I said it is very random. I managed to get that error only twice.

Let's close and see.
