### ISSUE TITLE
[2.0.2] Symbol Directory (Windows 10)

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#2101]
Hey,

Ran into a little funny issue which I believe worked fine in previous releases.

On my gns3 vm running on esxi i would have a directory dedicated for symbols that I would grab from the github gns3-registry.

With symbols in that directory it used to show up in the Symbols Directory in the gns3-client.

I moved the symbols from the gns3-registry github into the following directory;

> /usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/symbols/

This way they will show as built-in symbols, 
For example, i added the loadbalancer.svg symbol to this directory;
![image](https://user-images.githubusercontent.com/7719536/27000509-12a0c10a-4d82-11e7-9cf2-5fee4a0ad76f.png)

In my client it shows up just fine;
![image](https://user-images.githubusercontent.com/7719536/27000511-1afeacea-4d82-11e7-8687-86085894189e.png)

However, when clicking apply I will get the following error on the client;
1) Doesn't show up in the settings -- I click apply and click ok
![image](https://user-images.githubusercontent.com/7719536/27000513-37b3e328-4d82-11e7-8b19-9e8641140c60.png)

2) Error in the console
![image](https://user-images.githubusercontent.com/7719536/27000515-3f062b86-4d82-11e7-8bd5-42c2d3a43808.png)

3) Go back to settings and it's there;
![image](https://user-images.githubusercontent.com/7719536/27000517-487ce1c8-4d82-11e7-93bc-c55ceb7bb05b.png)

Is there an easy way to use just the GNS3 Server to host the symbols? Instead of keeping them local? And if there are custom ones to upload it to the server similar to how it's done with uploading the images?

For example, my root directory that GNS3 runs in is /opt/gns3, can I have the server read all of the symbols from /opt/gns3/symbols directory instead?

I'm not sure if the above is very clear, or if it should've been put in the server section but hopefully I was able to explain it clearly.

**Comment by noplay** [comment]
In 2.0 custom symbols are uploaded to the main server. You can choose the location of the symbol directory by setting up his location in gns3_server.conf

```
[Server]
symbols_path = /Users/noplay/GNS3/symbols
```

It's not working?

**Comment by gcasella** [comment]
Hey Julien,


The sample documentation on gns3.com didn't show that as an option.

I'll try it out and let you know & i'll close it after i try it out.


________________________________

**Comment by gcasella** [comment]
Hey Julien,

So using the configuration;
[Server]
symbols_path 

Works as expected, thank you for that. However, when I do select a custom logo for example F5_Networks_logo.svg I will get this on the client (though it exists in the list for the Symbol library)

![image](https://user-images.githubusercontent.com/7719536/27161294-6cbed964-5148-11e7-8ffa-72f5174e9e4a.png)

**Comment by noplay** [comment]
[Server]
symbols_path


You don't set a path?

**Comment by gcasella** [comment]
hey julien,


look at my last entry.

i set the symbols_path and everything works, however in the actual client i received that error message looking inside of C:\Program Files\GNS3

________________________________

**Comment by noplay** [comment]
Should be more something like:

```
[Server]
symbols_path = C:\fhshjgf\symbols

**Comment by gcasella** [comment]
Right, but I don't use the windows gns3 server. I run everything on a remote server.

My gns3_server.conf file has the following;

[Server]
symbols_path = /opt/gns3/symbols


On Jun 16, 2017 4:30 AM, Julien Duponchelle <notifications@github.com> wrote:

Should be more something like:

[Server]
symbols_path = C:\fhshjgf\symbols

**Comment by noplay** [comment]
You have remove the symbols manualy added to /usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/symbols/?

Your configuration should be ok...

**Comment by gcasella** [comment]
Yup, I removed everything I added to /usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/symbols/.

Everything works as expected except for that error message that I still get in the GUI.

On Jun 16, 2017 8:49 AM, Julien Duponchelle <notifications@github.com> wrote:

You have remove the symbols manualy added to /usr/share/gns3/gns3-server/lib/python3.5/site-packages/gns3server/symbols/?

Your configuration should be ok...

**Comment by noplay** [comment]
The custom symbols are display but you see the error?

After the error. Could you got to help / Export debug informations and send the info to developers@gns3.net 

Thanks a lot

**Comment by gcasella** [comment]
Hey Julien,


When I try to go to Help -> Export Debug Information after the error, i get another error that states;

"Export debug information from a remote server is not supported"


Would it be easier for me to provide the GUI log file on my windows machine?


________________________________

**Comment by noplay** [comment]
Yes please provide the gui log instead

Thanks for the help

**Comment by gcasella** [comment]
Hey @noplay 

Here is my gns3_gui.log and gns3_gui.ini


[gns3_gui - Copy.txt](https://github.com/GNS3/gns3-gui/files/1101183/gns3_gui.-.Copy.txt)
[gns3_gui.log - Copy.txt](https://github.com/GNS3/gns3-gui/files/1101184/gns3_gui.log.-.Copy.txt)

Is there any other information i can try to gather for you?

**Comment by noplay** [comment]
Do you have the same issue if you rename the file to just f5.svg?

**Comment by gcasella** [comment]
Yessir, I still get the same error when renaming it to just f5.svg
![image](https://user-images.githubusercontent.com/7719536/27573307-328fbc4a-5adf-11e7-8285-7e626a749588.png)

**Comment by noplay** [comment]
I just made extensive test on a fresh windows and didn't replicate the issue with last code. I think we fix it. 

When we will release 2.1.0alpha2 you can test again. You can need to delete the node and template with the issue  to fix the problem.

**Comment by noplay** [comment]
Thanks for the help
