### ISSUE TITLE
GNS3 window hangs after an idle period

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2102]
This happens **everytime** I leave GNS3 project opened and meanwhile working on other stuff.

After I switch to GNS3 window, it hangs, (more excactly it shows the screen of the upper applications) and no way to get it back except killing it.

Examples:
![image](https://user-images.githubusercontent.com/1716020/27012711-afc36fec-4ed5-11e7-8174-0053c7784227.png)

or this one I haven't seen since Windows :)

![image](https://user-images.githubusercontent.com/1716020/27012736-5fc0cc46-4ed6-11e7-999a-6825ae2810a4.png)

**Comment by cioby23** [comment]
I also tend so leave sometimes GNS3 projects open for a long time and I didn't experience this kind of issue. I do not use LXDE but KDE (ArchLinux) with the latest versions of Python and Qt available.

**Comment by AJNOURI** [comment]
I am running GNS3 (2.02) in a virtual environement with latest Qt and PyQt.

Looks like a single GNS3 process runs at 100%

![selection_0029](https://user-images.githubusercontent.com/1716020/27015214-12b7d092-4f09-11e7-8bfc-4783c573ad83.png)

**Comment by noplay** [comment]
Do you have issue with a different windows manager?

**Comment by AJNOURI** [comment]
I haven't tried to replicate this on another windows manager.
I'll do it later today on Gnome (Ubuntu 16.04)

**Comment by noplay** [comment]
Thanks !

**Comment by AJNOURI** [comment]
@noplay Could not reproduce it on Xenial (VM).

**Comment by noplay** [comment]
Ok sound related to the Qt / Ubuntu / Windows manager

Thanks for the feedback
