### ISSUE TITLE
Hibernation/Network modified issues

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2104]
While reopening my laptop from hibernation I can see the following errors. Not a real problem because I could keep using the current project.

```
Can't get settings from controller
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
Network session error.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
Can't get settings from controller
Can't get settings from controller
```

**Comment by obakeng1** [comment]
Good day,

 I am also getting same errors If my latop loses wifi connection or when I disconnected my LAN cable

**Comment by grossmj** [comment]
I noticed the same issues on Windows.

**Comment by noplay** [comment]
I propose to try to improve this in 2.1 because we got multiple complaints about that on Linux since people switched to systemd.

**Comment by grossmj** [comment]
I can crash GNS3 just by accidentally switching off my wireless card on my laptop ;)

**Comment by noplay** [comment]
Seem a similar issue:
https://github.com/raelgc/scudcloud/issues/546

**Comment by noplay** [comment]
It seem the Qt network manager detect the lost of connection of a device, but will not resume it.

**Comment by noplay** [comment]
Ok I confirm this is not working as expected. 

The network manager listen for changes on all interface even if you are listening on 127.0.0.1 he will detectect you shutdown the wifi interface and change his status.

**Comment by noplay** [comment]
If I correctly understand how Qt work.

QNetworkAccessManager will take the first available network at start and will use it.

Perhaps we need to manually switch the active network. From the documentation:
```
Setting a network configuration means that the QNetworkAccessManager instance will only be using the specified one. In particular, if the default network configuration changes (upon e.g. Wifi being available), this new configuration needs to be enabled manually if desired.
```

**Comment by grossmj** [comment]
**1st test**

Disabling my Wifi card produced a dozen of "Network session error" windows.

![wifi_disabled](https://user-images.githubusercontent.com/4752614/28402896-5d9e659c-6d4c-11e7-9b8e-9e7679915661.png)

```
=> Can't get settings from controller
Error while getting appliance templates list: Network session error.
Error while getting appliance list: Network session error.
Error while getting compute list: Network session error.
Network session error.
Can't get settings from controller
Error while getting compute list: Network session error.
Error while listing project: Network session error.
Error while listing links: Network session error.
Error while listing drawings: Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Can't get settings from controller
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Error while getting compute list: Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
Network session error.
```
Once I re-enabled Wifi and clicked OK for all these windows, I was able to continue working on the project.

**2nd test**

I put my laptop in sleep mode and re-opened it. I got one "Network session error" window but could get rid of one "connection to server" window (in black).

![sleep_mode](https://user-images.githubusercontent.com/4752614/28403193-d1e74242-6d4d-11e7-9f26-7d29470721bf.png)

I was still able to move nodes around after that.

**Comment by noplay** [comment]
Which version of Qt is it a 5.5 or a 5.8?

I think we can catch and avoid to display popup about network session error.

**Comment by grossmj** [comment]
I tested with Qt 5.8
