### ISSUE TITLE
[2.0] Bug with "edit readme" ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2108]
Hi

Perhaps just only i don't understood why and how it works.

- When i click on "edit readme" menu, simple text editor is open with generic text "... This project is about...".
- I modify it and i click on save button.
- I reclick on the "edit readme" menu, it is always the original text. My text is not save.

This text is it open when we load the project ?

**Comment by noplay** [comment]
Also reported here:
https://gns3.com/qa/annotate-edit-readme

**Comment by ziajka** [comment]
@noplay solution at gns3-server PR
