### ISSUE TITLE
[2.0.2] GUI out of sync if connection to a server is temporarily lost

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#2113]
There were several attempts to fix this, but I still see out of sync problem.
The topology is running and everything is fine. At some point you lose connection to the server/close laptop and after some time the connection goes back.
**End result:** 
You are still able to connect via console to the nodes or stop them. However if you stop them, all lights will remain green (in the workspace / topology summary) if though the nodes are indeed stopped.

**Comment by noplay** [comment]
On which OS?

Le mar. 20 juin 2017 à 18:07, Dmitry Figol <notifications@github.com> a
écrit :

**Comment by dmfigol** [comment]
macOS Sierra

**Comment by noplay** [comment]
Seem the same as #2104
