### ISSUE TITLE
CSR1000v Losing Configuration

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2117]
CSR1000v losing configuration after closing project and re-opening.  Below is the configuration settings
![hdd settings](https://user-images.githubusercontent.com/17806351/27413865-f93c8ea8-56cb-11e7-9260-20413273bda2.png)
![general settings](https://user-images.githubusercontent.com/17806351/27413867-f9438668-56cb-11e7-9c63-a12fc6a5bfa7.png)
![network settings](https://user-images.githubusercontent.com/17806351/27413866-f93ea4d6-56cb-11e7-8889-1ddd00362932.png)

**Comment by noplay** [comment]
Hi,

Please discuss that on the forum. Because it's not a GNS3 bug, but specific settings for CSR that could be solve by other CSR users.
