### ISSUE TITLE
[2.1] Bug with name of VPCS

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2123]
Hi

For the first, i am not sure that it is a bug , This is perhaps your choose (and why not)

1. I put a VPCS on the lab. The name is not PC1 but VPCS-1
2. When i start the VPCS, his name in console is "VPCS" and not "VPCS-1"

**Comment by noplay** [comment]
Note: The ticket about VPCS replacement has not been merged when @Raizo62 tested this

**Comment by Raizo62** [comment]
Sorry, i don't understand. It is a note for you or i must retest ?

**Comment by noplay** [comment]
It's a not for us ,we have change in the pipe that could solve that by side
effect.

**Comment by noplay** [comment]
It seem we don't correctly inject the startup config

**Comment by noplay** [comment]
The problem doesn't impact VPCS template.
