### ISSUE TITLE
Use WebSockets for notifications

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2127]
Now that we only support Qt >= version 5.5, see https://github.com/GNS3/gns3-gui/issues/2080, we can use WebSockets for notifications.

**Comment by noplay** [comment]
Yeah more reliable !!!

**Comment by noplay** [comment]
I have bad news. I will double check tomorrow but it seem we can only do auth for websocket with Qt 5.6 and later....

**Comment by noplay** [comment]
Confirmed the request object allowing us to add auth header is available since Qt 5.6:
http://doc.qt.io/qt-5/qwebsocket.html#request

Problem Ubuntu Xenial provide Qt 5.5

**Comment by noplay** [comment]
We have multiple options:

1) Implement a kind of auth on top of websocket by sending auth information in messages. But this require server modification and I think we could easily break it without any warning
2) Use the HTTP stream for Qt 5.5 and websocket for later
3) Support only Qt >= 5.6 (but this mean dropping Xenial :( )
4) Disable auth for Qt 5.5, but it's not easy in the case of remote server

**Comment by noplay** [comment]
I think 2 because it's futur proof

**Comment by grossmj** [comment]
I vote for option 2 too
