### ISSUE TITLE
Project is not opening with "Request canceled"

### ISSUE THREAD

**Issue by gilbertoandrade** [GNS3/gns3-gui#2128]
I have the same problem described at https://github.com/GNS3/gns3-gui/issues/2074
When I start Gns3 and open my project, the system shows request canceled.
I have tried to use versions 2.0.3 and now GNS3-2.0.2017-06-23-all-in-one but the problem still happens.

Below my project before I close GNS3
![1](https://user-images.githubusercontent.com/29679189/27510491-f6fdbe1e-58e7-11e7-88a5-77085f9a813e.png)

Now the error when I try open it.
![2](https://user-images.githubusercontent.com/29679189/27510500-1c689a7a-58e8-11e7-8c93-60d544923423.png)

**Comment by noplay** [comment]
It's the only project with the issue?

**Comment by noplay** [comment]
Hi,

Please comment the issue if you still have it.
