### ISSUE TITLE
GNS3 2.0.3 wireshark captures not showing on Windows 10

### ISSUE THREAD

**Issue by jcsteele** [GNS3/gns3-gui#2130]
I have posted this to the community section on gns3.com with hopes for a response.  After a few days of no responses, I wanted to file a bug report in the event this is indeed a bug.  If not, please let me know and close.

I am running Windows 10 ver 1703 with a fresh installation.  Upon installing GNS3 with legacy options (no GNS3 VM running) I am successfully able to build topologies, lab, etc.  With a basic setup of two routers connected via fastethernet, I am unable to get wireshark captures to display any information.  For example, a R1--------R2 setup, where both interfaces are alive and sending CDP packets, I am unable to see ANYTHING in wireshark.  Wireshark will start correctly with no displayed error messages, but no frames show up in the display.
 
I have attempted to run GNS3 as an administrator on the machine, but that produces the same results.

The packet capture file is being generated, but no data is being written to it. I am assuming since the file is being generated initially that a permissions issue can be ruled out.

File: R1_FastEthernet00_to_R2_FastEthernet00.pcap 
Size: 0 KB 

This is being written to c:\Users\user\GNS3\projects\untitled\project-files\captures\ but again, no data is being sent to it.

To ensure this is not a topology issue within GNS3, I created a new topology, following a full shutdown of the system.  It consists of two VPCS nodes a hub. Same results as above. VPCS1 --- HUB --- VPCS2. I have connectivity between the VPCS nodes after assigning each an IP on the same subnet. When performing a ping between one host to another, wireshark does not show the data. The capture file says the size at 0 KB.
 
Running wireshark standalone attached to an active interface on my system seems to be functioning just fine.

**Comment by noplay** [comment]
Do you have the same issue with a capture on VPCS1 --- VPCS2 ?

**Comment by jcsteele** [comment]
I did another fresh installation of Windows 10, without any other software installed.  It is now working.  My preferred anti-virus software, Bitdefender, is not installed, which does contain a firewall.  I am wondering if that was causing the issues.

I have tested between two VPCS, two VPCS and a hub, and two 7200's and all is working now.  I will install anti-virus now and see if this causes the captures to fail again.

**Comment by jcsteele** [comment]
I have verified that the Anti-virus software, Bitdefender, was causing the issues.  Thanks your your assistance.

**Comment by lazypandabear** [comment]
I encounter the same problem and I was able to make it work with the help of Bitdefender Team. Please follow the steps below. 

Open the main interface of Bitdefender 2018 then click on the hamburger menu button from the upper left corner.
Click on Settings from the left sidebar
Select the Update tab
Select “Prompt before downloading” from the drop-down menu next to “Update processing rules”
Restart computer in Safe Mode by following the steps in our article: http://www.bitdefender.com/support/how-do-i-restart-in-safe-mode-1022.html
Browse to the: C:\Program Files\Bitdefender\Bitdefender Security folder.
Locate the file "bdtl.dll" and rename it to "bdtl.dl_";
Restart the computer in Normal mode.

**Comment by diyako1996** [comment]
i have same problem as you but i realized wireshark not showing but it save it in the project directory and i am confused why ??
i checked for anti virus and firewall no problem with that and my system operation is windows 10 please help me to figure out this problem thanks.
