### ISSUE TITLE
GNS3 2.0.2 error when deleting IOU router

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2132]
GNS3 2.0.2 application Windows 10 Prof 64 bit 
Error when deleting IOU router

GNS3 management console.
Running GNS3 version 2.0.2 on Windows (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.
Copyright (c) 2006-2017 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Timeout request http://admin@127.0.0.1:3080/v2/projects/13cca61c-865b-459d-b6e5-e5eef1f2587a/nodes/829a7110-e1b1-4224-bb05-8b34c700c639
error while deleting RouterOutside: Operation timeout
Operation timeout
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

**Comment by jtorri** [comment]
Well now, once again I cannot reproduce this consistently.  However, I am now running GNS3 2.0.3 in Windows 10 and the behavior does not occur in version 2.0.3   It seems reasonable to assume I made a mistake in the process of installing/configuring version 2.0.2, so, please feel free to close this issue.  
Thanks!

**Comment by noplay** [comment]
Thanks!
