### ISSUE TITLE
[2.0] : Inappropriate ioctl for device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2147]
Hi

I think that is not a critical bug.

On Live Raizo (Debian Jessie), i use and start an IOU switch (i86bi-linux-l2-adventerprisek9-15.2d)

- I open his console
- I see this error message :

```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
UNIX ERR:tcgetattr:Inappropriate ioctl for device

              Restricted Rights Legend
```
The switch seems to work correctly.

If i stop this switch, i open an xterm, and i do : 
```
cd ~/projects/untitled/project-files/iou/0f5fde6d-5282-4c85-8fd8-08a84acef31f
/opt/raizo/user/OS/IOU/i86bi-linux-l2-adventerprisek9-15.2d.bin -e 4 -s 0 1
```
I don't see the error message

**Comment by noplay** [comment]
Do you have the issues with all IOU images?  For me it seem a problem with an image with a different behavior and we can do nothing about it.

**Comment by Raizo62** [comment]
Which IOU do you advise me to test ?

If it is a problem of the image (why not), why i don't have the error message if i start manually the image ?

**Comment by grossmj** [comment]
Have you connected your IOU to something when you tested in GNS3?

**Comment by Raizo62** [comment]
I have tested 2 IOU switch. 1 is not connected, 1 is connected to ethernet switch.
In GNS3, i have the error message.
Manually, no error message.

**Comment by Raizo62** [comment]
I have tested on old Live Raizo v8.**17.04.22** (with GNS3 2.0.0dev13). I have the message error.

I have tested on old Live Raizo v7.**16.09.11** (with GNS3 1.5.3.dev1). I don't see the error message, but i can't see the first lines of boot of cisco : perhaps the error is here, but the console does not show it to me)

**Comment by grossmj** [comment]
I do not have the issue with Ubuntu 16.04

```
IOU1#show version
Cisco IOS Software, Linux Software (I86BI_LINUXL2-ADVIPSERVICESK9-M), Version 15.2(CML_NIGHTLY_20151103)FLO_DSGS7, EARLY DEPLOYMENT DEVELOPMENT BUILD, synced to  FLO_DSGS7_POSTCOLLAPSE_TEAM_TRACK_DSGS_PI5
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2015 by Cisco Systems, Inc.
Compiled Wed 04-Nov-15 02:31 by mmen
```

**Comment by grossmj** [comment]
According the many forums and other websites (e.g. http://evilrouters.net/2011/01/18/cisco-iou-faq/), this error has no consequences.
