### ISSUE TITLE
Improve alignments.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#215]
The alignment doesn't work well with different sized shapes. The bottom (or left) part of the shape is aligned. So the links between shapes with different heights are not horizontal. I would prefer aligning the center of the shapes.

**Comment by ehlers** [comment]
I changed the alignment the way I like it, here the results directly after horizontal and vertical alignment:

The link is added to show that it is now really horizontal (resp. vertical) after the alignment, even when the shapes have different sizes.
![horizontal_alignment](https://cloud.githubusercontent.com/assets/896406/9862182/78af2ed0-5b37-11e5-8a9e-a5833bab7c74.png)
![vertical_alignment](https://cloud.githubusercontent.com/assets/896406/9862184/7bc5e316-5b37-11e5-9f27-9fa26af1f21d.png)

I like that better than the previous alignment, but that's a matter of personal preference.

Here's the output of "git diff":
```
diff --git a/gns3/graphics_view.py b/gns3/graphics_view.py
index 10cec70..61a93d9 100644
--- a/gns3/graphics_view.py
+++ b/gns3/graphics_view.py
@@ -1349,8 +1349,8 @@ class GraphicsView(QtWidgets.QGraphicsView):
         for item in self.scene().selectedItems():
             if item.parentItem() is None:
                 if horizontal_pos is None:
-                    horizontal_pos = item.y()
-                item.setPos(item.x(), horizontal_pos)
+                    horizontal_pos = item.y() + item.boundingRect().height() / 2
+                item.setPos(item.x(), horizontal_pos - item.boundingRect().height() / 2)

     def verticalAlignmentSlot(self):
         """
@@ -1362,8 +1362,8 @@ class GraphicsView(QtWidgets.QGraphicsView):
         for item in self.scene().selectedItems():
             if item.parentItem() is None:
                 if vertical_position is None:
-                    vertical_position = item.x()
-                item.setPos(vertical_position, item.y())
+                    vertical_position = item.x() + item.boundingRect().width() / 2
+                item.setPos(vertical_position - item.boundingRect().width() / 2, item.y())

     def raiseLayerActionSlot(self):
         """
```

**Comment by grossmj** [comment]
Works well. Thanks! :+1:

**Comment by noplay** [comment]
:+1:
