### ISSUE TITLE
Ability to map nodes in Projects to map to picture or image

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#2154]
Is it possible to have Topology image mappings to nodes ?
it will be helpful in large topology for example INE 
thanks

**Comment by noplay** [comment]
You mean a way to display multiple vision of the same topology? One the GNS3 topology, one an image, etc...

**Comment by taurus8** [comment]
Yes Sir
for example INE advanced technology lab .
in gns3 we have 10 routers connected to 4 switches by one ethernet (iou/iol) interface like following image
![ine gns3](https://user-images.githubusercontent.com/8465075/28084927-71e6f014-668f-11e7-8e65-3690a28fd1cc.png)

but in reality we have 3 or 2 sub interfaces  on one Ethernet interface , that makes topology like following 

 it would be so helpful if we could map routers and switches on following  image
![ine](https://user-images.githubusercontent.com/8465075/28085261-5e7fff92-6690-11e7-88de-257d2667e00d.png)

**Comment by taurus8** [comment]
i meant,when we click on routers on picture , the console will open

**Comment by noplay** [comment]
Seem related to #1259

I move it to the to be defined milestone because  it's huge work. Perhaps one day in the web interface.

Thanks for the idea

**Comment by grossmj** [comment]
We will not implement it in the Qt interface.
