### ISSUE TITLE
Template names are unique across different emulators

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2158]
2 templates with the same names but for different emulators won't appear in the device list dock.

![vmware_template](https://user-images.githubusercontent.com/4752614/28111309-4818f90e-671f-11e7-83ff-ace8f9dc571d.png)

![virtualbox_template](https://user-images.githubusercontent.com/4752614/28111306-4814bfc4-671f-11e7-9dd9-306bf9f17d29.png)

Only one template:

![template_1](https://user-images.githubusercontent.com/4752614/28111307-4815be2e-671f-11e7-917f-8deb1a7ebf1d.png)

After changing the name of one of the template:

![template_2](https://user-images.githubusercontent.com/4752614/28111506-e49fa836-671f-11e7-8f42-52442b547858.png)

**Comment by noplay** [comment]
It's a side effect of the fact we don't want to display the gns3a template in the list when we have already imported the appliance. We need to improve the gui filtering code.
