### ISSUE TITLE
GNS3 vIOS-L2 unknown media type

### ISSUE THREAD

**Issue by anxious01210** [GNS3/gns3-gui#2162]
Hello,
When I run the vIOS-L2 in GNS3 and I run a topology with 3 SW connected in a circle together and I test it any thing looks good except when I issue #show int g0/0 then I see that the media type in the output in unknown and the negotiation of speed/duplex has failed and also when I issue #show spanning-tree then in the output all the interfaces has the Type "shr" so I have to go to interfaces and issue #spanning-tree link-type point-to-point to change the "shar" to "p2p", but I need to define the media type and I don't know how.
so my question is how I can define media type so when I add a MSW to a topology and issuing #show int g0/0 then in the output it does show the media type.

**Comment by noplay** [comment]
Hi,

This question is specific to an image you should ask it on https://gns3.com/community in order to get help from others users.

Here on github you have only issues about gns3 itself. But we don't know how each image work.

Thanks

**Comment by anxious01210** [comment]
Thank you very much for replying
