### ISSUE TITLE
Permissions of svg files

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2169]
Hi

It is not a bug (only "dirty" or perhaps hole security ?)

On linux, svg files of GNS3 have execute permission (example : vbox_guest.svg). I think that is not necessary because vpcs_guest.svg have not.

I suppose that the files come from windows system.

**Comment by noplay** [comment]
This issue was moved to GNS3/gns3-server#1132

**Comment by noplay** [comment]
Fixed in 2.1

**Comment by Raizo62** [comment]
I believe that you have do the change on the gns3-server, but not on gns3-gui.

You have a reason,  you have forget, i make a mistake ?

**Comment by noplay** [comment]
Fixed
