### ISSUE TITLE
Improve suspend a link for some emulators

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2173]
Currently the "suspend a link" feature is implemented using a frequency drop filter with a -1 value (see https://github.com/GNS3/gns3-gui/issues/1295). This is like a big black hole from a node guest OS perspective since it is not informed of the link state (like it would if you unplug an Ethernet cable from your PC).

Some emulators like VirtualBox (setlinkstate in VBoxManage) and possibly Qemu (via a Qemu monitor command, http://nairobi-embedded.org/qemu_monitor_console.html#hotplugging-devices) can disconnect a network cable and let the guest OS know about it. This could be an possible improvement.

**Comment by Raizo62** [comment]
In QEmu VM, is it possible to detect if network card is plugged or not ? With my tests, all cables seems plugged when i use 'mii-tool' or 'ip link' or 'ethtool' commands.

**Comment by Raizo62** [comment]
I have tested with Qemu monitor (with qemu version 2.8.1 of Stretch debian)

```
(qemu) info network
e1000.0: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:00
 \ gns3-0: index=0,type=socket,socket: udp=127.0.0.1:10007
e1000.1: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:01
 \ gns3-1: index=0,type=socket,socket: udp=127.0.0.1:10009
e1000.2: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:02
 \ gns3-2: index=0,type=socket,socket: udp=127.0.0.1:10011
e1000.3: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:03
 \ gns3-3: index=0,type=socket,socket: udp=127.0.0.1:10013
e1000.4: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:04
 \ gns3-4: index=0,type=socket,socket: udp=127.0.0.1:10015
e1000.5: index=0,type=nic,model=e1000,macaddr=00:db:36:11:46:05
 \ gns3-5: index=0,type=socket,socket: udp=127.0.0.1:10017
```

I disable the first netwwork card : 
```
(qemu) netdev_del gns3-0
netdev_del gns3-0
```
On the VM, the link is down : 
`kernel: e1000: ens3 NIC Link is Down
`
But, the "info network" doesn't change.

But, if i trie to reconnect; the vm doesn't see it :
`
(qemu)  netdev_add  socket,id=gns3-0,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006
`

**Comment by grossmj** [comment]
Implemented in https://github.com/GNS3/gns3-server/commit/8b91894fa4a8647627242688f06978b143fe0716

Qemu and VirtualBox VMs should now detect when a link is suspended.
