### ISSUE TITLE
Connection between two ports of the same node

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2187]
GNS3 version 2.0.4dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.

Currently it's not possible to create a connection between two ports of the same node, the error message "Error while creating link: Cannot connect to itself". Shouldn't that be possible with ubridge?

**Comment by grossmj** [comment]
Yes that would be possible with uBridge but why would you want to do this?

**Comment by noplay** [comment]
I think we can't juste remove the warning, that it's still here even if know it should be possible to implement.

The code of the Link object use the node id to know on which side of the link he is doing stuff like packet filtering or capture.

Also this require to update the GUI to support it and draw a loop link.

**Comment by ehlers** [comment]
Juniper allows to create logical router within a physical router. When you want to interconnect these logical routers, real juniper routers can use LT (logical tunnel) interfaces. Emulated routers quite often don't have this LT interface, so you need physical interfaces for that. Currently I'm interconnecting them with a switch or hub.

But I agree, that's a special case, it has very low priority. As Julien just gave some important reason against it, we should probably close this. It isn't worth putting a lot of effort into this.

**Comment by noplay** [comment]
Ok. If we found better reason we will implement it.

Could be fun to allow people to link their network interface in the cloud node :P

**Comment by andrej-korshikov** [comment]
Dear developers:) It would be nice if you'll change your mind and implement this enhancement. My use case is as described by the author of this issue - Juniper logical systems without lt interfaces. Anyway, thank you for the great software)
