### ISSUE TITLE
[GNS3-API] Getting node properties of closed project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2189]
If I like to get node properties via GNS3-API the project has to be opened.

So my solution is, if a project is closed, to open the project, get the node properties, then (if it was previously closed) to close it again. That way the project has the same status as before.

As open is quite a heavy operation, is there another way doing that?

When a project has been opened before, I can get list of all nodes, even when it's current closed. 
Can I rely on this behavior, or is that just luck?

**Comment by noplay** [comment]
This behavior is just luck. 

@grossmj I think it's interesting to change that. But perhaps risky to introduce it now.

I see two possible way to implement it:
* Try to load the project as usual without creating the nodes on computes
* When a project is closed return the data stored in the .gns3 and didn't try to do smart thing

**Comment by noplay** [comment]
I'm not sure of the side effects of both options.

I think the second way is safer, because the behavior of closed project will not impact an opened project.

**Comment by grossmj** [comment]
I agree, I like the second way and I think it will be safe.

**Comment by noplay** [comment]
And it's bug that today it's return a list of nodes. I checked the code and it should reset but we erase the link triggering the reset at close by mistake

**Comment by ehlers** [comment]
I don't think, that implementing this is worth any trouble.

What about another idea: Implement a new API call, that returns the .gns3 independently of the project state. And keep the existing API calls unchanged.

**Comment by noplay** [comment]
That will force user two implement two diffent api and we should be able to avoid it.

**Comment by grossmj** [comment]
Implemented by https://github.com/GNS3/gns3-server/commit/6e2752648ab1ca03add3b95885d1856e62411b4e
