### ISSUE TITLE
vnc qemu over "ssh -X"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2190]
Hi

I am not sure that the bug is your.

I start gns3 on LiveRaizo (Debian Jessie / last GNS3 2.0. Sorry, i cannot test this bug with GNS3 2.1 on Jessie)

From an other Debian Jessie, i connect to LiveRaizo with "ssh -X" ( or  i do the same with MobaXterm from Windows).

I put on the topology a QEmu device (linux-tinycore-linux-6.4-2.img) with vnc access.
When i start this device, the xterm (where GNS3 is started) displays "log [1]   suspended (tty output)  gns3"  and GNS3 seems to freeze.

If i use telnet access to QEmu, or VBox with head/headless mode, i have no problem.

**Comment by noplay** [comment]
Hi,

I know that Qt have a lot of trouble with ssh tunnel. A more recent version of Qt can fix the issue.
