### ISSUE TITLE
[ 2.1.0dev2 ] Annoying error: QXcbConnection: XCB error: 3 (BadWindow), sequence: 18753, resource id: 10653699, major code: 40 (TranslateCoords), minor code: 0

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2191]
Before 2.1.0dev2, apparently without any visible consequences, I constantly got this error each time I change container setting from GUI:

> QXcbConnection: XCB error: 3 (BadWindow), sequence: 26684, resource id: 10656356, major code: 40 
> (TranslateCoords), minor code: 0

Showed in the console, it wasn't an issue, but with 2.1.0dev2 it appears in the main windows:
![selection_0156](https://user-images.githubusercontent.com/1716020/28757397-87eb9052-7582-11e7-991e-6753d3ff3a55.png)

Too much ostentatious!

**Comment by noplay** [comment]
We need to filter this
