### ISSUE TITLE
Information display doesn't show server for cloud and docker nodes

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2197]
When hovering the mouse over a cloud (and NAT) or docker device, the information popup doesn't show on which server it runs.
![cloud](https://user-images.githubusercontent.com/896406/28863565-bf2d91c6-7769-11e7-9f54-49b467b1d06a.png)
![docker](https://user-images.githubusercontent.com/896406/28863561-bbc1bb2a-7769-11e7-9933-3e926a4afe3f.png)

All other device types (tested with dynamips,IOU,  qemu, vmware, vpcs) are showing this information, here the qemu information:
![qemu](https://user-images.githubusercontent.com/896406/28863669-318e45a8-776a-11e7-8732-69e0547081ad.png)

Furthermore the docker information misses the console port information.

Would be nice, when this can be added.

**Comment by noplay** [comment]
Info added thanks !

**Comment by ehlers** [comment]
I haven't tested, but I think, that NAT is still missing the server information.

**Comment by noplay** [comment]
Thanks I just add info to the nat node
