### ISSUE TITLE
wrong IP address opening console to VPCS on remote server

### ISSUE THREAD

**Issue by dimbleby** [GNS3/gns3-gui#2198]
I have:
* local (windows) PC running GNS3 GUI
* VM in AWS running GNS3 server
  * both at version 2.0.3
* VPN connection between them
* trivial topology with just two VPCS instances connected directly to one another

When I try in the GUI to open console to one of the VPCSs, this fails: 
* it tries to telnet to 54.194.10.17:5000.
  * that's the public IP address of my AWS instance
* but the server is listening on the address provided by the VPN, ie on 172.16.253.1:5000
  * and if I telnet to that address, then I do get the expected console

I see that this is a bit similar to #1574.  That talked about making changes to `/etc/gns3/gns3_server.conf`, so in case it helps here's what I have:

```
$ cat /etc/gns3/gns3_server.conf
[Server]
host = 172.16.253.1
port = 3080
images_path = /opt/gns3/images
projects_path = /opt/gns3/projects
report_errors = True

[Qemu]
enable_kvm = True
```

I've no idea whether it's the server or the GUI that's at fault here, so opening the issue in this repo is just a guess.

If you can point me in the right direction, I'm probably willing to investigate further / assist with fix / etc - but right now I wouldn't know where to start!

**Comment by noplay** [comment]
How do you start the server on the remote?

**Comment by dimbleby** [comment]
I ran `gns3-remote-install.sh` and let it do its thing.

**Comment by noplay** [comment]
Can you try to stop the server started by systemd and start it with

gns3server --host=172.16.253.1

**Comment by dimbleby** [comment]
Doesn't seem to make a difference.

**Comment by noplay** [comment]
Can you go to Help / Export debug informations and send the .zip to julien@gns3.net

**Comment by dimbleby** [comment]
Hmm, I shut down the GUI, restarted it, and created a fresh project - and now everything works as expected.  Not sure what to make of that.  Maybe I did things in some sort of 'wrong' order before?

Anyway, at the moment I can't reproduce the problem.

Not sure whether or not it's useful for you to keep this issue open in this state.  I mean *something* definitely went wrong - but I expect it'll be hard to make progress now that it's not happening.

**Comment by noplay** [comment]
Ok we close it until we know how to reproduce. Thanks a lot for the help !
