### ISSUE TITLE
Cloud shows gns3tap interfaces

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2199]
NAT/Cloud with bridge creates gns3tap interfaces. When adding another cloud node, these gns3tap interfaces are also shown by default. Maybe these could be filtered.
![cloud1](https://user-images.githubusercontent.com/896406/28923764-630895fc-785f-11e7-932f-fc9fbbd1bfe6.png)

**Comment by noplay** [comment]
Thanks it's fixed
