### ISSUE TITLE
missing snapshots after upgrade from 1.2.3

### ISSUE THREAD

**Issue by mikolar0** [GNS3/gns3-gui#220]
after upgrade from 1.2.3 to 1.3 beta 2 Ubuntu 14.04 64 bit I can see my snapshots

**Comment by grossmj** [comment]
Do you mean you cannot see them?

**Comment by mikolar0** [comment]
In manu File/manage snapshots or icon manage snapshots cannot see my old snapshots 
They are still on folders structure: gns/projects/nameofproject/snapshots/

**Comment by grossmj** [comment]
Hi,

Can you describe or take a screenshot of the snapshots directory structure please?

Thanks a lot :)

**Comment by grossmj** [comment]
Nevermind, I can reproduce the problem ;)

**Comment by grossmj** [comment]
Ok, should be fixed in RC1.

Thanks again,
