### ISSUE TITLE
Closing one gns3 window will cause VM to shutdown while other simulations is still running

### ISSUE THREAD

**Issue by AngelFalse** [GNS3/gns3-gui#2204]
While I was running multiple simulations, I closed one of these, and the VM just shutdown and leave all the rest simulations unavailable.
This issue is critical. Many projects have been damaged for this issue and if this issue continue to happen on newer versions I will consider deleting this GNS3 VM and never use that again, though this VM did speed up the simulation.
Can you developers just put a daemon watching all the gns3 running and stop the VM after all instances are closed, but not shut the VM after TERM signal is sent to the gns3.exe process?

**Comment by grossmj** [comment]
No sure I fully understand the issue. Maybe all you need is to let GNS3 keep the VM running (see preferences)

![gns3_vm](https://user-images.githubusercontent.com/4752614/29017003-7134256c-7b87-11e7-85f5-77b6822ce1f7.png)

Otherwise, please create a video or post screenshots to detail the problem.

Thanks!

**Comment by AngelFalse** [comment]
@grossmj Well, that settings did help. But I still hope that this detecting function will be added to the next version of gns3.
As we all see, gns3's simulation processes(dynamips) runs in the background, controlled by the daemon controller gns3server.
![gns3_server](https://user-images.githubusercontent.com/28922095/29017319-f12af9ac-7b88-11e7-90ee-862c5df3b907.png)
When one simulation was stopped and one of the gns3 instances is closed, the VM(acting as a simulation server) received the controller's command (from the closing gns3 instance) to stop all simulation and shutdown itself. But then other running simulation will be terminated, and those configurations that have not been saved(wr) will be lost.
And I also consider running GNS3 VM while not running GNS3 a waste of cpu and memory resources, for my computer is an old one(´･ω･`)
Thanks!

**Comment by ziajka** [comment]
Hi @AngelFalse ,

Do you still experience this issue?

For the clarification, do you run multiple simulations and don't want to be stopped when you close one of them? Or when you're closing GNS3 GUI all of them are being stopped?

Thanks,
Dominik

**Comment by ziajka** [comment]
Hi @AngelFalse,
I'm closing this issue for now, please let us know if you're still experiencing issue and then we will re-open this thread.
Thanks,
Dominik
