### ISSUE TITLE
Frame Relay "LMI AINSI" type spelling mistake

### ISSUE THREAD

**Issue by kamrul-pc** [GNS3/gns3-gui#2205]
In Linux GNS3 GUI under frame-realy switch configuration >> Help >> and there is a spelling mistake.

"Note that only the Frame-Relay LMI **AINSI** is supported"

It should be "**ANSI**".

![screenshot from 2017-08-07 19-38-23](https://user-images.githubusercontent.com/7962213/29030447-d71463ea-7bac-11e7-9958-f3459b66d2af.png)

**Comment by grossmj** [comment]
Thanks, we will fix it for our next release.

**Comment by grossmj** [comment]
Thanks @CapnCheapo!
