### ISSUE TITLE
Memory leak in Windows client

### ISSUE THREAD

**Issue by nextai2003** [GNS3/gns3-gui#2213]
It seems that the x64 GNS3 client for Windows has a memory leak, since leaving it running for extended periods of time will always result in significant and constant memory increase.

Issue found on 2.0.3 stable.

Steps to reproduce:
1. Create a topology with 4 QEMU VMs (I tried with different flavors of IOS-v , maybe others will show same issue since I think the issue is independent of what you are emulating).
2. Have the client configured to use a Remote Server (not as main server, legacy config besides Local Server). The VMs need to be configured to run on the Remote Server.

3. Start those VMs from the client.

4. After booting is complete, suspend the devices via the Pause button in the client and leave it so for one day. 

At the moment of the pause, the GNS3 client was taking 200 MB of RAM. Next day, after about 14 hours, it is taking 540 MB of RAM.

Please note that this behavior is consistent.

**Comment by nextai2003** [comment]
Just a note to @grossmj : please note that I have not experienced the CPU issue referenced in 2218 , just FYI (however, I am using the stable 2.0.3, not the latest beta). Kind regards !

**Comment by lunaticitizen** [comment]
I'm also experiencing memory leak in Windows client.
I left the client for about 48 hours without any topology loaded, and this was the result.

![ws000000](https://user-images.githubusercontent.com/9331921/34235008-12b72bd6-e632-11e7-9904-b3d29eecca02.JPG)

![ws000001](https://user-images.githubusercontent.com/9331921/34235010-163b825c-e632-11e7-87f6-b28bf8f36840.JPG)

The client is GNS3 2.1.0, the server is GNS3 2.1.0 VM running on an ESXi 6.5 server.
