### ISSUE TITLE
Setting some symbols for QEMU devices shows error message

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2214]
GNS3 version 2.0.4dev1 on Darwin 10.11.6 (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.

Procedure to reproduce:
- open preferences
- edit a Qemu VM
- select edge_label_switch_router symbol
- save with "OK"

I get two errors, debug shows:
```
2017-08-10 06:47:09 ERROR __init__.py:265 Cannot open file ':/symbols/edge_label_switch_router.svg', because: No such file or directory
2017-08-10 06:47:09 ERROR __init__.py:265 Cannot open file ':/symbols/edge_label_switch_router.svg', because: No such file or directory
```

The Qemu preferences now shows no icon for the VM
![qemu_preferences](https://user-images.githubusercontent.com/896406/29155032-59cb0940-7d99-11e7-9a16-cbc3fe5aa094.png)

When I leave the preferences (with OK), there are no further issues. In the left device sidebar the new icon is shown for that VM. When I drag it into a project, the icon is shown and when I open the QEMU preferences, the icon is also fine.

This happens only on some icons, the dslam and the edge_label_switch_router symbol are two examples I found. Other icons work fine.

Also this happens only for Qemu VMs, the problematic symbols are working fine for IOU and IOS VMs.

**Comment by ziajka** [comment]
Thank you @ehlers for reporting. Bugfix for that comes with next release.
