### ISSUE TITLE
GNS3 version 2.1.0b1 on Windows increase CPU usage

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2218]
GNS3 management console.
Running GNS3 version 2.1.0b1 on Windows (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.
Copyright (c) 2006-2017 GNS3 Technologies.
Using version 2.10b1 of VMware VM as well.
Create project with 4 IOU routers and 3 IOU switches.  Allow to run for 5 - 10 minutes.  Suddenly there is an increase of CPU usage from 4 - 8% to 40 -50%.  The increase remains until all network objects in the topology are stopped.  This behavior does not occur in GNS3 version 2.0.3 using the same network objects, and, in fact, the same topology.
Just curious as to whether or not anyone else has experienced this behavior.

**Comment by grossmj** [comment]
So the GNS3.exe on your Windows consume all that CPU, right?

**Comment by grossmj** [comment]
Have you noticed memory leaks too? https://github.com/GNS3/gns3-gui/issues/2213

**Comment by jtorri** [comment]
The increase memory associated with process VMware Workstation VMX
12.5.7 build-5813279.

**Comment by grossmj** [comment]
and the CPU too?

**Comment by jtorri** [comment]
As usual I am not explaining well. I should have said the increased CPU usage not the increased memory usage.

**Comment by jtorri** [comment]
Not sure if what I am about to add helps or not.  As I mentioned I used both the GNS3 application and the GNS3 VM from version 2.1.0b1 to create the topology which showed significantly increased CPU usage by the process VMware Workstation VMX.  So, what I did was to run the "Upgrade GNS3" menu option from the GNS3 VM.  I then selected the "Open a console" menu option, ran sudo su and ran "pip3 install gns3-server==2.1.01b".  
Now when I open the same topology the increased CPU does not occur.  Hope this does not add more confusion.

**Comment by jtorri** [comment]
Please ignore my last comment.  The increased CPU usage continues.  If I am the only one reporting this issue and it seems I am, I would put this one on the shelf for later review.  Thanks!

**Comment by noplay** [comment]
I think the problem is probably: 
"Ubridge with IOU high CPU usage"

Do you see increase network traffic between the node? If you use wireshark?

**Comment by grossmj** [comment]
@jtorri can you post a screenshot of your topology?

**Comment by grossmj** [comment]
@jtorri do you still have this behavior?

**Comment by jtorri** [comment]
Sorry.  I have ignored this one.  Have not tried to reproduce for quite a while.  Please feel free to close this issue.  Thanks for the followup.
