### ISSUE TITLE
Persistence for locked items

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2221]
Locked state for each item (excepting link items) should be saved in project file.  How to test if an item is locked: `item.flags() & QtWidgets.QGraphicsItem.ItemIsMovable`.

**Comment by grossmj** [comment]
Similar to https://github.com/GNS3/gns3-gui/issues/712

**Comment by ziajka** [comment]
@grossmj is it possible to lock items via current GUI? or is it about to make a possibility about to lock particular node on canvas, like option in node's actions?

**Comment by grossmj** [comment]
Yes this is possible. An item is locked when it gets to layer 0 or lower using the node's "lower one layer" action (we could also have a "lock" option to make this more intuitive). Currently, this state is not restored when re-opening a project.

**Comment by ziajka** [comment]
Get it, thanks!

**Comment by grossmj** [comment]
This will be available in version 2.2. See https://github.com/GNS3/gns3-gui/commit/141578a1e15334ce8e4602098ca889e5b8b0f8bb
