### ISSUE TITLE
Gns3 crashing when disconnect or switch off wifi 

### ISSUE THREAD

**Issue by obakeng1** [GNS3/gns3-gui#2222]
HI Guys,
i'm still having an issue related to issue #2104, if i disconnect my wifi gns3 closes ifself without a warning. please see the below logs.

 ~ $ gns3
2017-08-12 14:00:11 INFO root:126 Log level: INFO
2017-08-12 14:00:11 INFO main:254 GNS3 GUI version 2.1.0b1
2017-08-12 14:00:11 INFO main:255 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-08-12 14:00:11 INFO main:257 Application started with /usr/bin/gns3
2017-08-12 14:00:20 ERROR qt/__init__.py:296 "No such interface 'org.freedesktop.DBus.Properties' on object at path /"
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
Fatal Python error: Segmentation fault

Current thread 0x00007fe0db958700 (most recent call first):
  File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main.py", line 289 in main
  File "/usr/bin/gns3", line 11 in <module>
Segmentation fault

I'm using linux mint 18.2 cinnamon Qt 5.5

**Comment by noplay** [comment]
We can do nothing it's qt internal bug. More recent QT should fix the issue

**Comment by obakeng1** [comment]
This is fixed in 2.1.10
