### ISSUE TITLE
Pixelated Icons and Text on a HDPI screen under Windows 10

### ISSUE THREAD

**Issue by io8titan** [GNS3/gns3-gui#2223]
I am using Windows 10 and GNS3 2.1b1 (the same issue exists with previous 2.x versions) with a 4k HDPI screen.

If I set the scaling level in the display settings to 100% to emulate a standard resolution screen,
everything is of course way too small to be usable, but the icons and the text on the network diagram are crisp. 
![image](https://user-images.githubusercontent.com/30977406/29249674-db1848b2-8066-11e7-94d2-f0266870d9e6.png)

As soon as I set the scaling level to the recommended 250% though, the icons and the text of selected icons become pixelated, can this be fixed? 
![image](https://user-images.githubusercontent.com/30977406/29249668-cd81082e-8066-11e7-96ce-e3a73f4e8f90.png)

Also all dialogues have context help buttons in the title bar but none of them does actually work, what about disabling them (Qt::WindowContextHelpButtonHint)? 
![image](https://user-images.githubusercontent.com/30977406/29249738-edabfa04-8067-11e7-91eb-ba23188af990.png)

**Comment by grossmj** [comment]
Similar to the problems we have on Linux: https://github.com/GNS3/gns3-gui/issues/1980

**Comment by io8titan** [comment]
Yes similar, also with the drag&drop issue.
But in that issue you kind of blame it on Linux, whereas it also persists in Windows (I don't know about MacOS?).

**Comment by noplay** [comment]
It's look like Qt not detecting your HDPI screen. This seem weird Windows should provide the correct info. Are you using a multiple screen setup?

**Comment by io8titan** [comment]
No, I am using a single monitor.

**Comment by noplay** [comment]
Which graphic card?

**Comment by io8titan** [comment]
I am using a Dell XP 19560 with a 4k display and the scaling in Windows is set to the recommended 250%.

I played a bit around with different scaling factors and got the following results:
100%: sharp icons
>100%: gradually pixelated icons
any scaling factor: drag&drop issue (icon is shown on the top left of the mouse cursor but dropped at the mouse cursor)

Also compared with other Qt programs, especially the icons but also the rest of GNS3's UI is too big and occupies a lot of screen estate. I took a screenshot with two Qt programs side by side, you can see that the menu of GNS3 is larger and the icons are about 4 times as large.
![image](https://user-images.githubusercontent.com/30977406/29841987-070b9930-8d3a-11e7-9d54-afc56e92fc4b.png)

**Comment by noplay** [comment]
In the preferences the HDPI mode is enabled in GNS3?

**Comment by io8titan** [comment]
![image](https://user-images.githubusercontent.com/30977406/29842101-652dd172-8d3a-11e7-825d-0bc73214b39c.png)

**Comment by io8titan** [comment]
If I turn off the HDPI mode, the menu and all dialogues (preferences, new project etc.) are normally sized, eg. not overly big as with HDPI mode enabled. Also the device icons on the topology map are sharp on any zoom level.
But the problem then is that the toolbar icons are too small, the icons on the topology map are too small at the the default zoom level and the device/interface labels are too big. In addition the icons on the topology map sometimes disappear when scrolling around...
![image](https://user-images.githubusercontent.com/30977406/29843038-478069d4-8d3d-11e7-8abd-e9fc49633331.png)

**Comment by noplay** [comment]
Thanks for the info

**Comment by grossmj** [comment]
There may be a solution described in this webpage: https://vicrucann.github.io/tutorials/osg-qt-high-dpi/
