### ISSUE TITLE
Question regarding project: leave this project running in the background when closing gns3

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#2229]
Hello,

I have a topology elements running on remote server (topology is started on an iMac running GNS3 2.0.3 with remote GNS3 server being a Linux Ubuntu non GUI)

I have edited the project and selected : "leave this project running in the background when closing gns3"

Unfortunately, when I exit the GNS3 on iMac, the project is closed, not kept in background (on remote server).

This option when enabled for a project only seems to work when switching between projects (i.e opening different and coming back to project in question).

Reason why I would like to keep the project running is automation testing  (for example sending ansible instructions) from remote PC not having GNS3 installed.

Is this a normal behaviour due to consistency in GNS3 or am I doing something wrong?

Thanks.

**Comment by grossmj** [comment]
We are going to investigate this issue. Thanks for reporting.

**Comment by noplay** [comment]
The server is still running when you close GNS3?

**Comment by vader75** [comment]
Yes, its always on VM.

**Comment by noplay** [comment]
Can you share screenshots of server preferences? Thanks a lot

**Comment by vader75** [comment]
I shall, need first to do a test on two mac machines running GNS3 GUI, one with both local GNS3 VM and remote GNS3 VM, another only remote GNS3 VM, to reach some conclusions. I will then share both machines' server preferences, have a feeling that one running both local and remote GNS3 VM is problematic.

Will get back to you as soon as I can.

**Comment by vader75** [comment]
I think I understand my confusion better, or at least I can ask the right question.

1) The mac that has local GNS3 VM and remote GNS3 server, writes its projects locally, and will shut down the topology when local GNS3 VM is shutdown when project is cloised (this is even if some elements run on remote GNS3 VM)

2) The mac that runs topologies and configured only/solely for remote GNS3 VM resources, behaves as expected, projects stay open, and are seen in project list as opened.

My questions would be, can the mac/pc with both local (main) GNS3 VM server and added remote server see both local projects as well as remote projects in the list and open them, or is it a technical requirements that working on remote server projects to stay open, requires GNS3 GUI to only point to remote server(s)?

To me if, if both local and remote GNS3 VM server can start (for example)  qemu instance and put them in same topology, would cause some issues, and I assume project gets shutdown if in hybrid resource mode, as its not exclusive to remote GNS3 VM for always on (opened) state.

What would be the right interpretation, and for me to move forward is to always use remote GNS3 sev er on all GNS3 GUI clients to achieve consistency and not cause projects to close (as signalled)?

**Comment by noplay** [comment]
Use only remote server settings if you want to share a VM with multiple clients. This will solve your issue.

Perhaps we need to document that behavior more. But when a web app will be available it will be more easier.

Thanks

**Comment by vader75** [comment]
thanks
