### ISSUE TITLE
GNS 3 : VPCS or Router communication with VM via switch

### ISSUE THREAD

**Issue by mo-elias** [GNS3/gns3-gui#2230]
Hello @grossmj ,
I am afraid i have the same issue as the previous issue : GNS3 2.0.0b3 VMware passing traffic issue #1800, I have downloaded the files and pointed the server preference in GNS 2.0.3 to the executable, but no luck
I am running on Windows 10 and using Virtual Box,
Your support would be much appreciated ,

**Comment by grossmj** [comment]
@mo-elias Can you post a screenshot of your topology please?

Thanks!

**Comment by grossmj** [comment]
Do you use a Cloud node somewhere?

**Comment by grossmj** [comment]
I assume this is a duplicated issue of https://github.com/GNS3/gns3-gui/issues/2228
