### ISSUE TITLE
X applications fails on first start on docker container

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2231]
GNS3 version 2.0.4dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.
Using official GNS3VM as server.

When starting a docker container with VNC console the first time after the boot of the GNS3VM, then the first start of an X application fails.

Here the Dockerfile of my docker test container:
```
#FROM debian:stretch
#FROM ubuntu:xenial
FROM ubuntu:zesty

RUN set -ex \
    && apt-get update \
    && apt-get -y --no-install-recommends install lxterminal jwm menu \
    && rm -rf  /var/lib/apt/lists/* \
    && sed -i 's/xterm/x-terminal-emulator/g' /etc/jwm/system.jwmrc \
    && update-menus \
#
# set lxterminal defaults
#
    && mkdir -p /root/.config/lxterminal \
    && /bin/echo -e '\
[general]\n\
scrollback=1000\n\
fgcolor=#ffffff' \
        > /root/.config/lxterminal/lxterminal.conf \
#
# startup script
#
    && /bin/echo -e '\
\x23!/bin/sh\n\
\n\
cd\n\
export SHELL=/bin/bash\n\
jwm' \
        > /etc/init.sh && chmod +x /etc/init.sh

VOLUME [ "/root" ]
CMD [ "/etc/init.sh" ]
```

When I start this image the first time after a boot of the GNS3VM, the jwm window manager starts fine, but the first start of the lxterminal program creates an error. The second try work. When I close the project (it contains only this docker container) and open it again, then everything works at the first time. This happens only, when the container uses debian:stretch or ubuntu:zesty. With ubuntu:xenial it works also on the first time.

It doesn't matter if I stop/start docker or the gns3server in the GNS3VM. It must be something different, that influences this behavior.

When I start lxterminal in the auxiliary console, I see the following error message:
The second time, it works. The RANDR message is just a warning.

```
/ # lxterminal
Xlib:  extension "RANDR" missing on display ":100".
The program 'lxterminal' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 161 error_code 2 request_code 130 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
/ # lxterminal
Xlib:  extension "RANDR" missing on display ":100".
```

This happens on other X applications as well, e.g. firefox. QT based applications like Ostinato don't seem to be influenced.

I have no idea, why a container runs differently at the first time after boot of the GNS3VM? Any ideas?

**Comment by ehlers** [comment]
Found a workaround:
In the startup script of the container add a "lxterminal -e true". If it's the first start, it will end with an error, but the next X applications will run fine. If it's not the first start, it will start, execute the true command and closes it's window. That is that fast, that it will not be noticed.

**Comment by ziajka** [comment]
This issue is reproducible on GNS3VM.

**Comment by ehlers** [comment]
I'm using the official GNS3VM and it's reproducible. After the boot of the GNS3VM the first start of a X application has issues. After that everything is fine.

**Comment by ehlers** [comment]
Created a smaller test, a slightly modified xeyes container. It additionally installs lxterminal and sets the SHELL environment variable.

```
#FROM debian:stretch
FROM ubuntu:xenial
#FROM ubuntu:zesty

RUN apt-get update
RUN apt-get install -qqy x11-apps lxterminal
ENV SHELL /bin/bash
CMD xeyes
```

Testprocedure:
* create a project with a xeyes docker container
* close this project
* reboot GNS3VM
* open xeyes project
* start xeyes container
* open console, you should see the xeyes
* open auxiliary console
* start lxterminal, it should fail
* start lxterminal, now it should run
* stop xeyes container
* close project
* re-open project
* start xeyes container and open console and auxiliary console
* start lxterminal, now it should run also on the first try

This issue have all tested OS in the container (debian:stretch, ubuntu:xenial and ubuntu:zesty). All basic X applications like xeyes, xcalc, xedit work even on the first time after boot of the GNS3VM. Currently I suspect, that only GTK applications have this issue.

**Comment by grossmj** [comment]
Should we keep this issue open? I am not sure we can do much about this...

**Comment by ehlers** [comment]
I've got a workaround, so it has no priority for me. And I assume it's more a Docker/X11 bug, where GNS3 can't do anything. So I'm closing it.
