### ISSUE TITLE
Feature request:  non-shared projects

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2234]
Another feature request.  So when you open a remote server project right now, it is shared in that other users can open the same project and everybody can control the devices in real-time.  That's an awesome feature and we love that, but sometimes you don't want this shared control.  

It would be great if you could set an option to lock a project to the first person who opens it.  Then other users will not be able to access the project or change anything until the user releases the project.

Maybe a middle ground to this feature would be that it's locked to a user, others can open the project and view everything, but they can't change anything.

**Comment by grossmj** [comment]
We have implemented RBAC. This should solve that issue.
