### ISSUE TITLE
Unrecognized libpcap format or not libpcap data

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-gui#2235]
There are issues with libpcap on Windows and it's needed to check why it happens. 

References:
https://gns3.com/qa/-unrecognized-libpcap-format-or-
https://gns3.com/qa/gns3-and-wireshark

**Comment by grossmj** [comment]
Looks like in some situations the packet capture is forbidden and somehow the error message is saved in the .pcap file, hence the unrecognized libpcap format.

![wireshark_pcap_error](https://user-images.githubusercontent.com/4752614/29878900-e03df70a-8dcd-11e7-9b27-6f08bf31d09e.png)

**Comment by grossmj** [comment]
There is a problem with error reporting in https://github.com/GNS3/gns3-server/blob/2.1/gns3server/controller/compute.py#L348

**Comment by grossmj** [comment]
https://github.com/GNS3/gns3-server/commit/c22229101f2a499cd3ff4b115d8221a309b7584c

I've improved the error reporting a bit but an user will still be unaware of the reason why we can't stream a PCAP file. @ziajka @noplay any idea how we could improve this?

**Comment by grossmj** [comment]
I can reproduce that issue only when using npcap from version 0.08-r4. I've opened an issue on their side: https://github.com/nmap/nmap/issues/997

**Comment by grossmj** [comment]
I didn't replicate the issue when using the last npcap version (0.94).

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
I have got this error by downloading the portable version 2.4.0 and 2.4.2. I unpacked the exe-file with 7zip, because I don't want to install the software (portables should be startable without installing).
When I klick on the fin, the error appears.

**Comment by grossmj** [comment]
Some users still get that issue: https://gns3.com/qa/gns3-2-1-wireshark-issue

**Comment by grossmj** [comment]
The server will send a notification when it cannot stream a PCAP file. This should help with debugging this issue.

https://github.com/GNS3/gns3-server/commit/3e3e1df051f126d90d38ca3d186a5366d7f6bc86

**Comment by grossmj** [comment]
Note that BitDefender may be a cause: https://gns3.com/qa/gns3-2-0-3-wireshark-captures-no

**Comment by Worthy7** [comment]
I don't have BitDefender, and I am getting this problem only with the portable version.

**Comment by Worthy7** [comment]
Ok, It's because WinPCap isn't installed... https://www.winpcap.org/install/default.htm

**Comment by Mahesha999** [comment]
I am getting same error for portable version. It seems that WinPCap is not installed on my machine. However we need admin privileges for installing WinPCap. I dont have admin privileges on this machine. As this is a portable version, I guess there has to be some workaround. If there is no way to install WinPCap without admin privileges, if wireshark depends on WinPCap and if portable wireshark does not come bundled with WinPCap, then how it is portable?
