### ISSUE TITLE
Error while deleting project: The image [...].iso is missing

### ISSUE THREAD

**Issue by WhiteWinterWolf** [GNS3/gns3-gui#2237]
Hi guys,

I got the following error when attempting overwriting an already existing project:

    Project untitled already exists, overwrite it?
    Error while deleting project: The image /home/user/medias/isos/install.iso is missing

The .iso file was indeed mounter in a device node virtual CD-ROM reader.

Can you explain me how the fact that an ISO file is missing keeps GNS3 from *deleting* a project?
I can understand why it couldn't start it, but *"I will not delete this because that has already been deleted, please recreate it so I can delete it too"*, isn't it a bit strange?

IMHO, GNS3 should not prevent the deletion of a project, no matter if the project is incomplete, has wrong values, incompatible settings, or no matter what: it will be trashed anyway so who cares!

**Comment by WhiteWinterWolf** [comment]
Even more funny, I naively expected that manually deleting the project directory from the *~/GNS3/projects* would be enough, but no!
This wonderful error is raised and GNS3 still refuses to create the project until it gets restarted:

    Project untitled already exists, overwrite it?
    Error while deleting project: Can not delete project directory /home/user/GNS3/projects/untitled: [Errno 2] No such file or directory: '/home/user/GNS3/projects/untitled'

GNS3 says *"I cannot create the project because I cannot delete it because it doesn't exists"*. Brilliant, that's why I love computers ;) !

**Comment by noplay** [comment]
It's security. GNS3 try to clean delete nodes to avoid leaving dirt behind especially in the case of VMware and VirtualBox.

If you manually delete the folder you need to restart the server, because the server keep cache references. GNS3 will not ignore the folder because it could have disappear for wrong reason (network mount disconnected). But this could be improved to better manage trouble.

Which kind of node are you deleting?

**Comment by WhiteWinterWolf** [comment]
Hi,
Here is how I get this message:

1. Start GNS3, and directly click *OK* to create a new project bearing the default name *"untitled"*.
2. Add a Qemu end-device node to the topology, edit the node configuration and add an ISO image file in its CD/DVD reader (do not copy the ISO inside GNS3 repository; in my case these are just temporary ISO files I generate on the fly to pass files to the guest).
3. Close GNS3.
4. Rename or delete the ISO file previously associated to the CD-ROM reader.
5. Try to repeat step 1), it won't work anymore as GNS3 will be unable to overwrite the currently existing *untitled* project because of the missing ISO file.

I understand your concern about not leaving dirt behind, but the current behavior leaves another issue: try to open the currently existing *untitled* project in GNS3, it won't work, meaning you have lost access to the topology and cannot even change the node settings to remove the reference to the ISO file!

- A missing ISO file should not prevent GNS3 from opening a project, it should only prevent it from starting the affected node.
- A failure in opening a project should not make it impossible to delete or overwrite a project. In this case a warning seem warranted to alert the user that GNS3 may leave some dirt behind, but a button should be present to allow the user to proceed anyway (*"Force delete"* for instance).

Maybe one these two bullets should be forked into its own separate issue.

**Comment by grossmj** [comment]
It should be possible to delete projects with missing images now: https://github.com/GNS3/gns3-server/commit/4a2dfb0037b2b7b2af87125b08657f582f2ce206
