### ISSUE TITLE
Deleting a project should not affect external files

### ISSUE THREAD

**Issue by WhiteWinterWolf** [GNS3/gns3-gui#2238]
This issue is related to #2237.

When doing quick tests, I used to just overwrite the *"untitled"* default project.
This always worked as a charm with GNS3 1.x.

Now, with GNS3 2.x, when attempting to overwrite the *"untitled"* project I have the following messages:

    Project untitled already exists, overwrite it?
    Error while deleting project: The image /home/user/medias/isos/install.iso is missing

This ISO was an OS installation ISO file mounted in a device node.
Am I correctly understanding that, would the file be there, GNS3 would have deleted it from my ISO files archive?

If this is indeed the case, I'm glad this failed as I do not expect GNS3 to delete files located outside of the project directory when overwriting a project. Mounted ISO files, non linked base VM, etc. should be kept as long as they are located outside of the project directory.

I really fear now that I will soon discover that some VM images or ISO files disappeared from my archives due to this behavior...

**Comment by noplay** [comment]
GNS3 will not delete external files in the case of qemu, dynamips, docker, iou and VPCS. But when we delete a folder we open it, properly delete node and delete the project. This to avoid deleting a project without deleting external stuff especially in the case of VirtualBox and VMware.

**Comment by WhiteWinterWolf** [comment]
Hi,
Thank you for your answer.
So the error message `Error while deleting project: The image /home/user/medias/isos/install.iso is missing` was actually raised during the project opening step and not during the actual deletion step, so I'm fine with this.

If possible I think that a clearer message (like replacing `Error while deleting project` by `Error while opening project` for instance) would make it clearer that GNS3 is not attempting to delete the file mentioned in the rest of the message but just failed while opening the project I tried to delete.

As it is currently stated, I really read it as GNS3 tried to remove a non-existent file and failed, compare GNS3 message to the message raised by `rm` in such condition:

    user@host:~$ rm nonexistent
    rm: cannot remove 'nonexistent': No such file or directory
    user@host:~$

I find these message quite similar.

But this is not a major issue (more an enhancement than a bug) and, depending on how you handle things internally, may not be trivial to change so I leave up to you to decide what you will do with this :).
