### ISSUE TITLE
the docker of gns3/ubuntu cannot be pulled to local

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#2241]
use git pull gns3/ubuntu would failed,but gns3/openvswitch no problem

**Comment by noplay** [comment]
The command should be docker pull:
https://hub.docker.com/r/gns3/ubuntu/

Which error do you see?

**Comment by superwolfboy** [comment]
hi,here is some screenshot
docker pull gns3/openvswitch is working:
![pullovs](https://user-images.githubusercontent.com/9411604/29825915-6931bc3e-8d08-11e7-9a93-b327938f1ee0.png)
docker pull gns3/ubuntu is not found:
![pullubt](https://user-images.githubusercontent.com/9411604/29825939-77f1c462-8d08-11e7-878d-799b3990cb72.png)

**Comment by noplay** [comment]
I checked the .gns3a and it should be if you wan to do it by hand:
docker pull gns3/ubuntu:xenial

Le mar. 29 août 2017 à 16:29, superwolfboy <notifications@github.com> a
écrit :

**Comment by superwolfboy** [comment]
OK It's working ~
