### ISSUE TITLE
Ethernet switch console window opened when choosing "console connect to all nodes"

### ISSUE THREAD

**Issue by io8titan** [GNS3/gns3-gui#2242]
I a using GNS3 2.1.0b1 and whenever I choose "console connect to all nodes" to open the
console windows for all devices, a window for the buit-in "Ethernet switch" will also be opened.
Although I am actually using the Ethernet switch, the console window is useless since it doesn't show
anything.

**Comment by ziajka** [comment]
Hi @io8titan,

Thank you for reporting this.

Are you using GNS3 on Windows?
In this version there was a bug related to Ethernet Switch console which resulted with empty console. It's already fixed and will be shipped with the next release.

Cheers,
Dominik

**Comment by io8titan** [comment]
Yes, I am using the Windows version.
Good to hear that it's fixed.
