### ISSUE TITLE
[Feature Request] Show device/link purpose with different color/transparency on topology map

### ISSUE THREAD

**Issue by io8titan** [GNS3/gns3-gui#2243]
I would like to see the different purposes of devices and links on the topology map at first glance,
so that for example management links/devices are not congesting the topology map.

This could be accomplished by one of the following:
-option for specifying color/transparency of a link/device
-assignment of a device/link to specific layers, which then can be selectively turned on/off

Is it possible to implement such a feature or are you already working on something similar?

**Comment by ziajka** [comment]
Hi @io8titan,
Thank you for nice ideas to extend GNS3. 
We will evaluate this possibility and potential to increase usability for users.
Best wishes,
Dominik

**Comment by grossmj** [comment]
We have something similar when we support https://github.com/GNS3/gns3-gui/issues/2647
