### ISSUE TITLE
Projects cannot be deleted from Projects library window if a image is missing

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2249]
Steps to reproduce.
1. Open GNS3 GUI and click on the Project Library tab of the Project dialog box
2. Select a project to be deleted and press Delete button.
3. Press Yes for confirmation and then a message pops up saying "Error while deleting project: The image filename.qcow2 is missing.

Missing images from a project should not be used as a condition to allow a project to be deleted.
Tested on GNS3 2.1 beta1

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-gui/issues/2237

**Comment by grossmj** [comment]
Fixed in #2237
