### ISSUE TITLE
Going from disabled local server to enabled local server - where are my remote projects?

### ISSUE THREAD

**Issue by lundgrenolof** [GNS3/gns3-gui#2256]
I installed GNS3 and the first option I set was to disable local server. I had already installed GNS3 VMware esxi image server and it was running well. 
 
Now I enabled local server so that I can run some virtualbox images locally. 
 
Problem is only I cannot find the images I initially uploaded to the GNS3 VM.
 
These WHERE the settings I HAD.
Server > Main server > uncheck local server.
Servers > Main server > Remote main server > added my remote server with an IP
With these settings I got one server named "Main server"
 
Now I set it to
Server > Main server > enable local server
Server > Remote servers > add remote server IP 
GNS3 VM > Enable the GNS3 VM > Virtualization engine > "Remote" > My vm name....
With these settings I got two servers named "myremoteserver" and "Local server".
 
However, if I check my router list, now it seems like I only have the ones installed locally. Where can I find my images I installed on my ESXI Vmware image remotely? 
 
All the projects I had on the remote server is also gone in the GUI.
  
I use GNS3-GUI 2.0.3 on Ubuntu Gnome.
And the same thing also happened on my Win 10 machine connected to the GNS3 VM. Same procedure.

If I SSH to the remote GNS3 VM on the esxi server, I can see that both the projects and the images are in /opt/gns3/ directory. 
I can also see that NEW projects and images are saved into the same dir on the remote server. Just somehow this new setup doesn't want to recognize the old images and old projects.

Edit: If I go back to disabling the local server and only enable remote  server (gns3 vm tab automatically get unchecked again) I can see my images I initially uploaded and also the projects I created there. 
I cannot see the projects/images I created while having local server enabled, even though they are uploaded to gns3vm in /opt/gns3/

I also posted this issue on the gns3 forums, but I got no response so I figured this might be a bug.

Edit: I typo in the settings I had.

**Comment by grossmj** [comment]
Related to https://github.com/GNS3/gns3-gui/issues/2256

We really have to review how we manage local server vs remote ones. The problem is in 2.1 we need a controller and by default it is the local server.
