### ISSUE TITLE
Remote server vs Remote GNS3 VM

### ISSUE THREAD

**Issue by lundgrenolof** [GNS3/gns3-gui#2261]
If I enable GNS3 VM remote server I can create some devices. 

If I disable GNS3 VM, and only use the remote server option, I still have the same devices in the list. But I am not able to add them to a topology, due to them belonging to the GNS3 VM. 

Can this be fixed, because they are essentially the same thing.

Is it also possible to save projects on the remote VM/server so you can work on one project from different machines, while still having local server enabled?

**Comment by grossmj** [comment]
>  I still have the same devices in the list.

What list are you referring to?

> Is it also possible to save projects on the remote VM/server so you can work on one project from different machines, while still having local server enabled?

Yes this is possible, your project will be saved on the remove VM/server.

**Comment by lundgrenolof** [comment]
@grossmj these are the projects I can see when I disable local server and set main server as vmware esxi gns3 vm.
![screenshot from 2017-09-22 13-04-30](https://user-images.githubusercontent.com/28050577/30741900-0fef73fe-9f97-11e7-8db1-2f5c30f6a1e0.png)
THese are the devices that where enabled on same settings ![only-main-server-remote](https://user-images.githubusercontent.com/28050577/30741974-71430f80-9f97-11e7-9f1c-6f7e0aae4bdb.png)


---

If I enable the local server, as well as the set remote server the same vmware esxi gns3 vm, I get these projects. 
![screenshot from 2017-09-22 13-06-26](https://user-images.githubusercontent.com/28050577/30741918-27a792d8-9f97-11e7-9632-ed6889536105.png)

here are the devices ![local remote-server](https://user-images.githubusercontent.com/28050577/30742003-8b448f62-9f97-11e7-872a-965823fc7c7c.png)

**Comment by lundgrenolof** [comment]
As you can see, neither the projects nor the devices are the same, even though I am using the same gns3 esxi vm...

**Comment by grossmj** [comment]
Disabling the local server doesn't work well in 2.1 :(

**Comment by grossmj** [comment]
This will be fixed in https://github.com/GNS3/gns3-server/issues/1460
