### ISSUE TITLE
Image uploading is slow

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2264]
https://gns3.com/qa/windows-appliance

**Comment by grossmj** [comment]
I've tested it and actually it doesn't hang, it just feels like this because of https://github.com/GNS3/gns3-gui/issues/2188 and because the ISO image is really big (6.4 GB).

Uploading that image to the GNS3 VM via the "add appliance wizard" took me around 30 to 40 minutes, I could see the ISO image being uploaded and getting bigger and bigger in the GNS3 VM (in /opt/gns3/images), I estimate the upload speed has been between 1 and 2 MB/s. While this is a okay speed I am wondering if we should use something else than HTTP to upload images to the GNS3 server (at least for big images).

Maybe an easy fix could be to display instructions for a manual upload when the image size is too big?
Another alternative could be to use pscp.exe (from Putty website).

**Comment by grossmj** [comment]
I was able to upload the image in less than 3 minutes using pscp.exe:

```
pscp.exe 14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO gns3@192.168.33.129:/opt/gns3/images/QEMU
gns3@192.168.33.129's password:
14393.0.161119-1705.RS1_R | 1787828 kB | 38038.9 kB/s | ETA: 00:02:11 |  26%
```

**Comment by rory321** [comment]
Thanks grossmj, I'll try having a crack at using pscp.exe after I read the link you've posted. 3 mins is certainly a lot better than an hour. Cheers.

**Comment by ziajka** [comment]
We've just released RC3 which may solve this issue. 
It's necessary to enable experimental feature "Edit -> Preferences -> Miscellaneous -> Upload files directly to computes" and then try to upload this appliance.
