### ISSUE TITLE
[2.1.0dev4]: Get "Node doesn't exist"  after deletion, but still on the canvas

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2266]
Following delete of a container node, got windows mesasging telling that time is our waiting for deletion (Not sure about the exact formulation of the mesage), clicked OK.

The container won't disappear form the canvas and each time I click to evoke menu to delete I get "Node doesn't exist"

![selection_004_12_09](https://user-images.githubusercontent.com/1716020/30334369-b44d5a16-97df-11e7-8548-5465056e1009.jpg)

Closed the project and reopened, but the device still there and same behavior if clicked "Node doesn't exist"

This is not consistent behavior.

> 2017-09-12 17:25:12 CRITICAL graphics_view.py:1508 Node ID e3279ee3-21c0-47f6-9992-054fd77560c9 doesn't exist
> Stack (most recent call last):
>   File "/usr/local/bin/gns3", line 11, in <module>
>     load_entry_point('gns3-gui===2.1.0dev4-6d74ce4', 'gui_scripts', 'gns3')()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/main.py", line 289, in main
>     exit_code = app.exec_()
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/http_client.py", line 648, in _processError
>     callback(json.loads(body), error=True, server=server, context=context)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/node.py", line 244, in updateNodeCallback
>     self.server_error_signal.emit(self.id(), result["message"])
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/qt/__init__.py", line 287, in func_wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/graphics_view.py", line 1508, in _displayNodeErrorSlot
>     QtWidgets.QMessageBox.critical(self._main_window, name, message.strip())
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.0dev4_6d74ce4-py3.6.egg/gns3/qt/__init__.py", line 117, in critical
>     LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
> 

---------------------------------
GNS3 version is 2.1.0dev4 
Python version is 3.6.1 (64-bit) with utf-8 encoding
Qt version is 5.8.0
PyQt version is 5.8.2
SIP version is 4.19.2

----------------------------------
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

**Comment by AJNOURI** [comment]
Correction:
At the next gns3 reopen, I could not reopen the project:

![image](https://user-images.githubusercontent.com/1716020/30335868-b95057b2-97e3-11e7-9955-587b5ba4ab83.png)

![selection_006_12_09](https://user-images.githubusercontent.com/1716020/30335917-d90a454a-97e3-11e7-87ef-43200a8d6df8.jpg)

**Comment by grossmj** [comment]
Please re-open if you still face that issue.
