### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding

### ISSUE THREAD

**Issue by jingle0927** [GNS3/gns3-gui#2267]
aungthuhan@boom:~$ gns3
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted

**Comment by jingle0927** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=145426  via

**Comment by grossmj** [comment]
There seems to be a problem with how Python has been installed. Also, we do not officially support the Deepin distribution. Please post on our community forum over at http://gns3.com/community for help.

Thanks!

**Comment by dgsbicak** [comment]
I'm dealing with this issue for two days. It is so frusturating for me to see the solution was too easy.
Setting a particular Python path did the trick for me. In terminal:
`gedit ~/.bashrc`
We need to add a python path in there. This one below did the trick for me.
`export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6`

Please note that, I previously added codes below which didn't solve my problem. Just for warning.
```
#export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/dist-packages
#export PYTHONPATH=$PYTHONPATH:/usr/bin/python3
#export PYTHONHOME=$PYTHONHOME:/usr/local/lib/python3.6/dist-packages
```

**Comment by CesMak** [comment]
Fatal Python error: Py_Initialize: can't initialize sys standard streams
is what I get.....

**Comment by bayrock** [comment]
> I'm dealing with this issue for two days. It is so frusturating for me to see the solution was too easy.
> Setting a particular Python path did the trick for me. In terminal:
> `gedit ~/.bashrc`
> We need to add a python path in there. This one below did the trick for me.
> `export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.6`
> 
> Please note that, I previously added codes below which didn't solve my problem. Just for warning.
> 
> ```
> #export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/dist-packages
> #export PYTHONPATH=$PYTHONPATH:/usr/bin/python3
> #export PYTHONHOME=$PYTHONHOME:/usr/local/lib/python3.6/dist-packages
> ```

This saved me extra days of headaches..
