### ISSUE TITLE
GNS3-2.1.0rc1  Error while getting compute list

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2269]
GNS3 management console.
Running GNS3 version 2.1.0rc1 on Windows (64-bit) with Python 3.6.1 Qt 5.8.0 and PyQt 5.8.

Windows 10 Prof 64 bit.  Just installed this version of GNS3.  Created project.  Let is run a while. It then displays error msg: 
"Timeout request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout"

**Comment by grossmj** [comment]
Can you post the content of %APPDATA%\GNS3\gns3_server.log after you get the timeout?

Thanks,

**Comment by grossmj** [comment]
Was your computer busy doing something at that time?

**Comment by grossmj** [comment]
I have increased the timeout for this operation. Please re-open if you still get problems.
