### ISSUE TITLE
VMware VM information not deleted when deleting project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2270]
GNS3 version 2.0.4dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.

When deleting a project that contains a VMware VM, the information about that VM is not removed from the project directory.

Here my test scenario:

- Create a project named untitled
- Add a VMware VM to this project
  This creates a directory structure like this:
  ```
  /Users/behlers/GNS3/projects# find untitled | xargs ls -ld
  drwxr-xr-x  4 behlers  staff   136 16 Sep 11:23 untitled
  drwxr-xr-x  3 behlers  staff   102 16 Sep 11:23 untitled/project-files
  drwxr-xr-x  3 behlers  staff   102 16 Sep 11:23 untitled/project-files/vmware
  drwxr-xr-x  2 behlers  staff    68 16 Sep 11:23 untitled/project-files/vmware/79906d37-911d-4050-8849-3e4a2ab491b3
  -rw-r--r--  1 behlers  staff  1708 16 Sep 11:23 untitled/untitled.gns3
  ```
- Delete this project
  GNS3 shows no errors or warning, but the project directory still exists, containing the VMware VM information:
  ```
  /Users/behlers/GNS3/projects# find untitled | xargs ls -ld
  drwxr-xr-x  3 behlers  staff  102 16 Sep 11:23 untitled
  drwxr-xr-x  3 behlers  staff  102 16 Sep 11:23 untitled/project-files
  drwxr-xr-x  3 behlers  staff  102 16 Sep 11:23 untitled/project-files/vmware
  drwxr-xr-x  2 behlers  staff   68 16 Sep 11:23 untitled/project-files/vmware/79906d37-911d-4050-8849-3e4a2ab491b3
  ```

**Comment by ziajka** [comment]
It's a bug indeed. Some process is not stopped before file removal. Delaying it by one second solves the problem, however it's doesn't find the exact reason.

**Comment by ziajka** [comment]
/Compute/ sends notification after closing the node/project. JSON dump method invokes directories structure creation.

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-server/pull/1185

**Comment by grossmj** [comment]
PR merged.

@ehlers can you confirm this has been fixed?

**Comment by ehlers** [comment]
Difficult, I'm still using 2.0.

**Comment by grossmj** [comment]
I can still reproduce the issue on Linux using the procedure described in https://github.com/GNS3/gns3-gui/issues/2270#issue-258221123

**Comment by ziajka** [comment]
Hi Jeremy, I tried to reproduce it on current 2.1 branch but it's OK. Could you double check it? Are you using local server? Thanks!

**Comment by grossmj** [comment]
Ok, i will double check. Have you tried to start a VM, stop it and then delete the project?

**Comment by ziajka** [comment]
Yes, still no issues.

**Comment by grossmj** [comment]
I've tested again and confirm it is fixed :+1:

**Comment by ehlers** [comment]
Just tested it, can confirm, that the bug is resolved.
