### ISSUE TITLE
[2.1.0dev6]: OpenSuse, GNS3 crashes just after being installed (when creating new project)

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2272]
GNS3 starts the first time, but when open new project:

Watch the video below
[![Watch the video](https://user-images.githubusercontent.com/1716020/30673826-28bc1ed6-9e76-11e7-96a8-b7a7d3e2e8e8.png)](https://youtu.be/7p7_5oT2So4)

> 2017-09-21 02:05:27 DEBUG http_client:509 POST http://127.0.0.1:3080/v2/projects {'name': 'test1', 'path': '/home/ajn/GNS3/projects/test1'}
> 2017-09-21 02:05:27 DEBUG http_client:668 Decoding response from http://admin@127.0.0.1:3080/v2/projects response 201
> ****** Exception detected, traceback information saved in /home/ajn/.config/GNS3/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/http_client.py", line 688, in _processResponse
>     callback(params, server=server, context=context, raw_body=raw_body)
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/qt/__init__.py", line 272, in partial
>     return func(*args, **kwargs)
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/project.py", line 414, in _projectCreatedCallback
>     self._startListenNotifications()
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/project.py", line 545, in _startListenNotifications
>     self._notification_stream = Controller.instance().connectWebSocket(path)
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/controller.py", line 201, in connectWebSocket
>     return self._http_client.connectWebSocket(path)
>   File "/usr/lib/python3.4/site-packages/gns3_gui-2.1.0dev6_a4b897d4-py3.4.egg/gns3/http_client.py", line 451, in connectWebSocket
>     request = self._websocket.request()
> AttributeError: 'QWebSocket' object has no attribute 'request'
> 
> 2017-09-21 02:05:27 WARNING crash_report:86 A .git directory exist crash report is turn off for developers. Instant exit
> 
> 

-----------------------
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by grossmj** [comment]
Do you know what's the Qt version?

Thanks!

**Comment by AJNOURI** [comment]
5.6.2
The one available through YAST2 software manager

**Comment by grossmj** [comment]
That is strange, according to Qt documentation that method should exists since version 5.6: http://doc.qt.io/qt-5/qwebsocket.html#request

**Comment by ziajka** [comment]
Hi @AJNOURI ,

It seems to that you have pyqt5 bindings for older version (5.5.x).

Please verify by command: 

zypper info python3-qt5

Cheers,
Dominik

**Comment by AJNOURI** [comment]
OK, I'll check it and get back to you.

2017-09-27 16:57 GMT+02:00 ziajka <notifications@github.com>:

**Comment by grossmj** [comment]
@AJNOURI do you confirm this has been fixed? Thanks

**Comment by AJNOURI** [comment]
Sorry for the delay.
Something went wrog with the QT prior installation. Reinstalled it through the unified Qt linux installer: 
http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
Now works fine! 

Thanks guys!

-----------------------
GNS3 version is 1.5.3 
GNS3 Converter version is 1.3.0
Python version is 3.4.6 (64-bit) with utf-8 encoding
Qt version is 5.6.2
PyQt version is 5.5.1
SIP version is 4.16.9

**Comment by ziajka** [comment]
Thank you @AJNOURI for letting us know!
