### ISSUE TITLE
OSX 10.13 removes telnet binary,  device console type issue OOB

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#2274]
Not specifically a bug, but usability issue with OSX, subject says it all. Had to install homebew and telnet binary, changing GNS3 settings for Telnet Console Application (path).

Perhaps there are more elegant solutions, such as addition of ssh console type (instead of only telnet and vnc), maybe something to consider or point to.

Thanks.

**Comment by ehlers** [comment]
Or add the telnet binary to the OS X all-in-one and use that for the telnet console.

**Comment by noplay** [comment]
Thank you apple

**Comment by grossmj** [comment]
I agree, the easiest is to add the Telnet binary to the OS X all-in-one package.

**Comment by Uraniox** [comment]
Create a custom console with this:

osascript -e 'tell application "Terminal"' -e 'activate' -e 'do script "echo -n -e \"\\033]0;%d\\007\"; clear; nc %h %p ; exit"' -e 'end tell'

It's just the Terminal profile with telnet changed to nc. Seems to work perfectly so far.

**Comment by vader75** [comment]
@Uraniox I have a remote GNS3 server, the nc connects but the shell is not interactive (stops and start printing question marks).

I would assume that remote GNS3 server does not listen for two way nc communication, perhaps needs nc implementation in listening (server) mode.

**Comment by Uraniox** [comment]
@vader75 I also have a remote server and after a few days of trying to use nc I experienced the same thing as you. I was too hasty in my reply. Nc would work just fine when connecting the first time but closing out a console and reconnecting would bring up the question marks and inactive shell.

I finally gave up and reinstalled telnet via homebrew and all is well again.

I also tried to take the telnet binary from Sierra (as many on the InterWebs recommended) but High Sierra would not let me put it in /usr/bin via drag and drop nor via Terminal with sudo.

**Comment by vader75** [comment]
@Uraniox no worries. Done the same.

**Comment by grossmj** [comment]
I have added the telnet binary to our DMG, you can test this with our latest nightly build :https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-10-01/2.1/GNS3-2.1.0dev6.dmg/download

The binary is in GNS3.app/Contents/Resources/telnet

**Comment by grossmj** [comment]
This needs to be tested since I don't have access to an OS X system.

**Comment by vader75** [comment]
I have a stable environment with 2.0.3, cant mess with it now :-(. If someone else has the dev environment to test, would appreciate it. Otherwise I will try to virtualise Mac OS for separate client server installation when I get the chance.

**Comment by vader75** [comment]
Is there a gns3 server version "dev6" I can get. pip install only lists 2.1.0a1, 2.1.0a2, 2.1.0b1, 2.1.0b2, 2.1.0rc1 ? I am getting client server incompatibility errors.

**Comment by vader75** [comment]
tested as working server rc1 with client dev6, console updated to reflect the GNS3 telnet binary path (explicit). Not sure if GNS3 client can add internally preference search path to this binary for console terminal profile?

**Comment by grossmj** [comment]
Good idea, I think adding the path is better.

**Comment by grossmj** [comment]
Actually we already do it there: https://github.com/GNS3/gns3-gui/blob/master/gns3/main.py#L138

So I just removed the explicit path to telnet. Things should work like this.

Please confirm.

Thanks,

**Comment by vader75** [comment]
Unfortunately not working with implicit path. Not sure if OS level is overriding it due to export path or not injected:

```
$ export | grep GNS3
declare -x TCL_LIBRARY="/Applications/GNS3.app/Contents/MacOS/tcl"
declare -x TK_LIBRARY="/Applications/GNS3.app/Contents/MacOS/tk"
```

**Comment by grossmj** [comment]
@vader75 have you tried we the last nightly build? https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-10-03/2.1/GNS3-2.1.0dev7.dmg/download

**Comment by vader75** [comment]
Not yet, I will tomorrow my time (AEST) and report.

**Comment by grossmj** [comment]
Thanks :+1:

**Comment by vader75** [comment]
Unfortunately it does not work, path still have to be explicit. Is there anything in the GUI I need to change, any tick to apply?

**Comment by grossmj** [comment]
I think you must go to General Preferences -> Console applications -> Edit and select the Terminal command line and click OK for the updated command line to be applied.

**Comment by vader75** [comment]
Nope, based on what you are saying terminal command line should update in settings, but I think its not. Here is the screenshot. you can see terminal saying can't find telnet command:

![screen shot 2017-10-04 at 9 01 47 pm](https://user-images.githubusercontent.com/3232190/31170376-8c29d4aa-a947-11e7-9727-db31ae2fec7d.png)

**Comment by grossmj** [comment]
Thanks for the feedback. I will check this soon :)

**Comment by grossmj** [comment]
@vader75 I think I got it this time, can you test with out last dev 2.1 DMG?

Thanks!

**Comment by vader75** [comment]
@grossmj dev8 loaded, stillnot working, still requires explicit path. 

While I don't understand the programming side, I guess you are trying to get GNS3 application include path implicitly.

Suggestion, ship another profile called GNS3 Mac Terminal and set the path to /Applications/GNS3.app/Contents/Resources/telnet. This is what I did.

My alternative was to get brew install telnet and make available on system level (usr/bin already in path).

I would love to give you access to Mac instance, but not sure if I can build a non Apple hardware instance build on my NAS running kvm/qemu.

**Comment by noplay** [comment]
Alternative we can compile busybox and use their telnet. This will provide
a static telnet

**Comment by grossmj** [comment]
There was a bug in the last dev version, now the embedded telnet should be used if none is available system wide. Please use this version to test: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-10-21/2.1/GNS3-2.1.0dev9.dmg/download

**Comment by vader75** [comment]
Works!

**Comment by grossmj** [comment]
Finally! ;) Thanks for helping.
