### ISSUE TITLE
GNS3 always waiting while changing device position

### ISSUE THREAD

**Issue by aydinmu** [GNS3/gns3-gui#2275]
Hi,

GNS3 always shows pop-up "Waiting for http://127.0.0.1:3080" when i changed anything. For example changing device position, changing device label etc.

İs it a some sort of bugs or misconfiguration on my pc.

GNS3 v2.0.3.

**Comment by grossmj** [comment]
How fast is your computer?

**Comment by aydinmu** [comment]
i7 CPU and 16 GB RAM. I think it doesn't related my computer's hardware capabilities. GNS3 try to notify every move to GNS3 local server. And i checked connection 127.0.0.1 port 3080 it is open.

**Comment by grossmj** [comment]
Have you tried with our 2.1 RC1 version?

**Comment by grossmj** [comment]
I have increase the time before we show a progress dialog. Please try again when our next release (version 2.1 RC2) is out and re-open this issue if you still have that problem. Thanks!
