### ISSUE TITLE
Docker container interfaces configuration file is not properly saved by GNS3 GUI in Windows builds

### ISSUE THREAD

**Issue by ievgen-kostiukevych** [GNS3/gns3-gui#2276]
Dear GNS3 team,

It looks like the bug, that didn't allow proper docker container config editing from GUI, is still present in version 2.1 RC1.
The bug is relevant for Windows build.
GUI opens the correct /etc/network/interfaces file, but saves it as "etc\network\interfaces".
It basically just creates new file in the root directory of the container.
As a result - the container's config cannot be saved.
I'm attaching a screenshot for your reference.
Looks like the issue is "\" instead of "/" in Windows build saving script.

Many thanks!
![capture10](https://user-images.githubusercontent.com/32355446/30955690-c8fd02b6-a434-11e7-8b2b-ff28303b2217.PNG)

**Comment by ziajka** [comment]
Hi @ievgen-kostiukevych,

Thank you for reporting this issue. We will investigate this.

Cheers,
Dominik

**Comment by grossmj** [comment]
This will be fixed after we release RC2 version.

**Comment by ziajka** [comment]
Should be fixed now.

**Comment by ievgen-kostiukevych** [comment]
Hey, Dominik!
Maybe I'm doing something wrong, but looks like the issue may be still there?
I'm testing in Windows 7, GNS3 2.1 RC2 downloaded today, and GNS3-VM 2.1.0dev8
Ubuntu container config is still saved in root...
Thanks

<img width="1440" alt="capture" src="https://user-images.githubusercontent.com/32355446/31616978-745df108-b28e-11e7-9ebd-7d1bdb6a8f20.PNG">

**Comment by ziajka** [comment]
Hi @ievgen-kostiukevych,

That's true. Fix will come with the next RC3 as both GUI and VM need to updated.

RC3 probably will be delivered in this week.

Cheers,
Dominik

**Comment by ievgen-kostiukevych** [comment]
Understood!
Many thanks, Dominik!

**Comment by ravi1290** [comment]
I am using GNS3 2.0.3 version and facing issues with editing the config file. I try to edit the config file it resets back to default.
