### ISSUE TITLE
[2.1.0rc1] - Project spontaneously closes with no specific error

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2277]
After a clean install of 2.1.0rc1 , my topology closes approximately every 24h-48h for no apparent reason. 

**Client**: Windows 10
**Server**: GNS3VM configured as a regular "VMWare virtualization engine" (not remote server)
**Images**: All appliances (IOU,QEMU,Clouds) are hosted on GNS3VM(built from latest clean OVA 2.1.0rc1).

Sometimes when I return to my topology, I see that my project is closed and the console only states:
**=> Can't get settings from controller
Can't get settings from controller**

The main project window states:
**Please create a project**

GNS3 VM shows online in the client and CPU and RAM utilization are nearly 0. No appliances remained running.

The same topology could run stably for over a month on GNS32.0.3.
**GNS3VM's Host**: 16-core Xeon, 192GB RAM, 5xSSD RAID
**Allocated to GNS3VM**: 8-cores, 40GB RAM

Where can I find more detailed logs?
I will keep debugging on to see if I can get more details the next time this happens.

**Comment by sairuscz** [comment]
Additionally, I am unable to view /var/log/upstart/gns3.log due to permission errors.
I cannot access it neither via Nano in GNS3VM terminal or WinSCP.
Also "chmod 777 gns3.log" fails due to permission error.

Any suggestions on how to access the logs using the default gns3 user account?

**Comment by AJNOURI** [comment]
Experiencing the same thing.

From time to time, while everything works fine, it happens that I got "Can't get settings from controller"

![image](https://user-images.githubusercontent.com/1716020/31047701-ddae0d5e-a60f-11e7-9041-9f97971dff83.png)

![image](https://user-images.githubusercontent.com/1716020/31047741-690ca7a2-a610-11e7-8e1e-0dbaf04f0791.png)


It happens sometimes when stopping a device or deleting a device.


I have noticed last time, (maybe starting with 2.1 devX) that the GUI waits bit longer for the controller every time you do any action.

-------------
2.1.0dev6
GNS3 host =  debian Jessie

**Comment by grossmj** [comment]
@sairuscz did your system went to sleep mode?

**Comment by sairuscz** [comment]
My topology has now been running stably for over 6 days. 
The only thing I did is to reboot GNS3 VM and the Windows client machine.

PS: I have no sleep mode enabled. Both the GNS3VM and GNS3 Win client run on a server 24/7.

-It might be a good idea to force a Windows reboot after GNS3 installer finishes. 
-It might also be helpful if you could correct the log access permission on GNS3VM
![image](https://user-images.githubusercontent.com/24818591/31251039-8d501d00-a9d1-11e7-9441-342acf699af8.png)

**Comment by sairuscz** [comment]
Yes, my topology is still stable since I rebooted after the update.

**Comment by grossmj** [comment]
Thanks for the feedback! :+1:

**Comment by grossmj** [comment]
> It might also be helpful if you could correct the log access permission on GNS3VM

This has been fixed.

> It might be a good idea to force a Windows reboot after GNS3 installer finishes.

We will consider it.

Thanks again.
