### ISSUE TITLE
Enhancement: Show where a device is installed

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2279]
Even with https://github.com/GNS3/gns3-server/issues/1181 solved, this is important to know where each device is installed.
The user make this choice the first time when drag and drop devices into the canvas, then this inf. is lost.

- We could include this inf. when hover over a device

or

- in the server summary (like this one), with each device under its location.

![image](https://user-images.githubusercontent.com/1716020/31060130-0e7a62a8-a70e-11e7-8d5e-ddcaef5e2d15.png)

--------
Another interesting feature:
Show somewhere the total  memory + cpu used by the project and by location.

ex: the project uses 2GB RAM:
- 25% RAM + 80% CPU remote server
- 50% RAM + 10% CPU local server
- 25% RAM + 10% CPU GNS3 VM

**Comment by grossmj** [comment]
> We could include this inf. when hover over a device or in the server summary (like this one), with each device under its location.

This info is now available in both location.

> Another interesting feature: Show somewhere the total memory + cpu used by the project and by location.

This will be implemented in our web interface.
