### ISSUE TITLE
gns3-gui 2.1.0rc is missing on pypi

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2283]
https://www.gns3.com/qa/can-t-install-gns3-2-1-0rc2-on-p

While gns3-server is completely available on pypi, gns3-gui is only partly available. From the 2.1 series only 2.1.0a2 and 2.1.0b2 are downloadable, see https://pypi.python.org/pypi/gns3-gui.

Can you please add v2.1.0rc2 ?

**Comment by ziajka** [comment]
It's seems to be a bug on Travis side. I will take care of it.

**Comment by ziajka** [comment]
Thank you for reporting @ehlers. It should be available now.
