### ISSUE TITLE
Import Appliance Error in 2.1.0rc2

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2284]
Unable to import appliance into 2.1.0rc2.  This is the error that comes up
![import appliance error dated 10-7-2017](https://user-images.githubusercontent.com/17806351/31312784-46e8ddea-ab9b-11e7-9a3d-44d05dd39d87.png)

**Comment by grossmj** [comment]
What appliance have you tried to install?

**Comment by fatbell** [comment]
I tried to install CSR 1000v, IOSXRv, IOSv, and IOSL2.  All with the same error

**Comment by grossmj** [comment]
Have you waited for the images to upload?

**Comment by grossmj** [comment]
Could be related to https://github.com/GNS3/gns3-gui/issues/2264

**Comment by fatbell** [comment]
I just tried again and waited for 1 hour with same result. Will not go beyond the error screen

**Comment by fatbell** [comment]
My second trial was with IOSv image and left it for over 2 hours with same result.

**Comment by ziajka** [comment]
Hi @fatbell,

We've just released RC3 which may solve this issue. 
You need to first enable experimental feature "Edit -> Preferences -> Miscellaneous -> Upload files directly to computes" and then try to upload this appliance. 

Please let me know if it helps. Thanks!

Cheers,
Dominik

**Comment by fatbell** [comment]
Its working after going through the steps outlined.  Thank you very much for your time.  Please close my ticket

**Comment by grossmj** [comment]
I was able to reproduce the problem in RC3.

**Comment by ziajka** [comment]
Have you enabled this experimental feature option in settings?

**Comment by grossmj** [comment]
Yes, same problem. I tested with the Windows server appliance (File -> Import appliance) and I get the "Please wait for image uploading" at the end of the wizard, the is no progress dialog or anything else.

**Comment by grossmj** [comment]
I don't get the "Please wait for image uploading" after the image has been fully uploaded.

**Comment by grossmj** [comment]
Fixed
