### ISSUE TITLE
gns3 remote server : console needs to detect automatically the remote server IP

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2286]
I installed the latest GNS3 unstable through PPA to a remote server, for testing purposes:

```
sudo add-apt-repository ppa:gns3/unstable
sudo apt-get update
sudo apt-get install gns3-gui
```

I didn't use the script which, by the way still using 1.5.3 (not the latest stable 2.0.3), so no openvpn is established with the gns3 client.

Everything went OK, the client is able to create topologies with devices running, but console to devices uses **by default the VPN server local IP 172.16.253.1, so it doesn't work.**

![selection_004_09_10](https://user-images.githubusercontent.com/1716020/31324653-3e0597f2-acb5-11e7-9bad-940060630590.jpg)

(Eventhough, it is possible to workaround this, for each console, by changing %h to remote server IP.)

It should detect which IP is used for the remote server settings, either we are using openvpn server or not.

A secure/local environement could be a reason why we might want not to use openvpn packed with the remote server script.

**Comment by grossmj** [comment]
> I didn't use the script which, by the way still using 1.5.3 (not the latest stable 2.0.3), so no openvpn is established with the gns3 client.

Which script are you referring to?

**Comment by AJNOURI** [comment]
@grossmj Sorry about the delay. I missed your reply.

I am talking about the script to install gns3 remote server:
curl https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh > gns3-remote-install.sh
mentioned here:
http://docs.gns3.com/1c2Iyiczy6efnv-TS_4Hc7p11gn03-ytz9ukgwFfckDk/index.html#h.fu57266ard3d

**Comment by grossmj** [comment]
I guess the problem is you were not running the openvpn client where you installed the GUI.

**Comment by grossmj** [comment]
@AJNOURI Do you confirm? Thanks!

**Comment by AJNOURI** [comment]
Hi @grossmj ,
Yes, the remote server is hosted on public cloud with public IP and by design I didn't established openvpn with the client.
I mean, the telnet session could be established to the IP that was used to connect to the server, 172.16.253.1 (through openvpn) or any other IP (public or privte).

**Comment by grossmj** [comment]
> I didn't use the script which, by the way still using 1.5.3 (not the latest stable 2.0.3), so no openvpn is established with the gns3 client.

I used the first commands listed in http://docs.gns3.com/1c2Iyiczy6efnv-TS_4Hc7p11gn03-ytz9ukgwFfckDk/index.html#h.fu57266ard3d and the script installed 2.1.2.

> Yes, the remote server is hosted on public cloud with public IP and by design I didn't established openvpn with the client.

I am kinda confused. Do you know on what address the GNS3 server is bound? Looks like it is .160.242 but GNS3 tries to use 172.16.253.1 to connect to remote console devices right?

**Comment by AJNOURI** [comment]
Yes that's right.
The remote server is hosted on a public provider X.X.160.242 and I could connect to it from the client.
If I start a console to a device installed on that remote server (X.X.160.242) it uses automatically 172.16.253.1, which doesn't work.
As a workaround, I explicitly put the server IP X.X.160.242 in the custom console option to make it work.

**Comment by grossmj** [comment]
@AJNOURI 

I think what happened is you used the gns3-remote-install.sh with the `--with-openvpn` parameter like described in the documentation. This will tell the script to configure an openvpn server and configure the GNS3 server to use the 172.16.253.1 IP address: https://github.com/GNS3/gns3-server/blob/master/scripts/remote-install.sh#L294

Try to use the script without `--with-openvpn` parameter and I think it should work:
`bash gns3-remote-install.sh -with-iou --with-i386-repository`

Also, you can manually check/change the IP address in /etc/gns3/gns3_server.conf

**Comment by AJNOURI** [comment]
Sorry @grossmj for the late reply.
I tested a remote server without openvpn and device consoles connect to the correct public server IP:

![selection_001_05_03](https://user-images.githubusercontent.com/1716020/36980057-8d1fce32-2089-11e8-8128-cd014dd3c60a.jpg)

Thanks a lot!!

**Comment by grossmj** [comment]
Thanks! :+1:

**Comment by AJNOURI** [comment]
Hi @grossmj ,

Re-experiencing the same issue on 2.1.8 with remote gns3 server with OpenVPN.
When I open a console to a device, gns3 try to console to the **server public IP** not to **172.16.253.1** configured for the remote server:

![selection_001_19_07](https://user-images.githubusercontent.com/1716020/42916426-70426068-8b05-11e8-8580-c97483ca8e8f.jpg)

![selection_003_19_07](https://user-images.githubusercontent.com/1716020/42916467-a5362bb0-8b05-11e8-8159-813bffd7390d.jpg)

So I have to manually edit console setting to change the parameter %h with the correct openvpn server IP (172.16.253.1)

![selection_004_19_07](https://user-images.githubusercontent.com/1716020/42916496-c70bbd2c-8b05-11e8-9099-06757b34189c.jpg)
