### ISSUE TITLE
Enhancement: integrated tabbed console 

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2288]
I would love to see an integrated tabbed console view, like it is done on VIRL, 
No need for the user to configure anything:

![image](https://user-images.githubusercontent.com/1716020/31417024-53127790-ae2d-11e7-832b-f57b1f0764e1.png)

**Comment by grossmj** [comment]
We have this in the web-ui. I don't think we will do it in the desktop client.
