### ISSUE TITLE
Feature request: expansion of the project readme

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2289]
I recently discovered the project readme file- I think it has been there for quite a while, but it's a little bit hidden right now.  So I thought it might be a cool feature if you could set a checkbox in the project properties that causes the readme to automatically be displayed when a project is loaded.  This would be useful for things like lab steps, guidelines, warnings, etc.  

The above probably wouldn't be too hard to implement and I may try to tackle it in the future if people think it's a good idea and I have some time.

The other idea related to this would be to add some kind of formatting so you could adjust text size, colors, add bullet lists, tables, and maybe a diagram....

**Comment by ziajka** [comment]
@grossmj after merge PR changes for docker ExtraHosts there should be "ProjectWelcomeDialog", it can be reused.

**Comment by grossmj** [comment]
Implemented.
