### ISSUE TITLE
GNS3 2.1 on unstable branch in Ubuntu 17.10

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-gui#2290]
Investigate the issue with the latest version of Ubuntu.

https://gns3.com/discussions/gns3-2-0-on-ubuntu-17-10

**Comment by ziajka** [comment]
There are missing dependencies for python3.6. We will release with RC3 proper packages. 

Need to test it after release.

**Comment by ziajka** [comment]
Thank you for your help @AJNOURI!

**Comment by grossmj** [comment]
Looks like the packages have not been uploaded to launchpad: https://launchpad.net/~gns3/+archive/ubuntu/ppa?field.series_filter=artful

**Comment by ziajka** [comment]
Pre-release versions are not published on stable branch. 

https://launchpad.net/~gns3/+archive/ubuntu/unstable

**Comment by grossmj** [comment]
Indeed, I overlooked that.

**Comment by AJNOURI** [comment]
GNS3 looks great on 17.10

![selection_004_24_10](https://user-images.githubusercontent.com/1716020/31935716-d6a01bd0-b8af-11e7-95f5-609964825c67.jpg)


```
sudo add-apt-repository ppa:gns3/unstable
sudo apt-get update
sudo apt-get install gns3-gui
sudo apt install curl
curl -O https://download.docker.com/linux/ubuntu/dists/zesty/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
sudo dpkg -i docker-ce_17.09.0~ce-0~ubuntu_amd64.deb 
sudo gpasswd -a $USER docker
newgrp docker
sudo apt-get install xtightvncviewer
```

**Comment by grossmj** [comment]
Awesome, thanks for the feedback! :+1:
