### ISSUE TITLE
IOU looses private config

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2291]
GNS3 version 2.0.4dev1 on Darwin (64-bit) with Python 3.5.2 Qt 5.6.0 and PyQt 5.6.

See https://www.gns3.com/qa/iou-issues-with-crypto-key-not-s

It's easy to reproduce: Start a new IOU router, create RSA key, save config, stop, start

First I thought that's another issue with the IOUtools, as they are reverse engineered. But after some investigation I saw, that it's not. The issue is the configuration option "Use default IOU values for memories". It you turn that off, then it's working.

The issue is, that GNS3 tells the IOUtools to generate a NVRAM with 128 KB size, when the use_default_iou_values option is set. But the IOUs have different default values. From my collection of IOUs (29 images) the L2 images and the L3 images with IOS 12.x are using 16 KB NVRAM and the L3 images with IOS 15.x using 64 KB NVRAM. The mismatch between IOU and IOUtools leads to the lost of the private config. The IOU doesn't find the private-config in the NVRAM.

I see three possibilities:
* Change the default value in GNS3 to match those in the IOU. But that's error prone, as there is no documentation, what the default values are and different IOU images have different defaults.
* Get rid of the "Use default IOU values for memories" option, always tell the IOU what it's NVRAM size is.
* When "Use default IOU values for memories" option is used, don't use the IOUtools to create the NVRAM. But then you must use the IOU -c option to pass the initial config, but that doesn't allow to pass an initial private config.

I vote for the second option.

**Comment by grossmj** [comment]
> Get rid of the "Use default IOU values for memories" option, always tell the IOU what it's NVRAM size is.

Should we use a default value of 64 KB for NVRAM? What about the RAM value? this is a bit more complicated because different images need a different amount of RAM.

**Comment by ehlers** [comment]
Some background information: [iou-defaults.txt](https://github.com/GNS3/gns3-gui/files/1379740/iou-defaults.txt). I have extracted the RAM and NVRAM default values from the help text of various IOU images.

Now to my suggestion to get rid of "Use default IOU values for memories". What I meant, was to get rid of this "if not self.use_default_iou_values:" in https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/iou/iou_vm.py#L717 . Then the RAM and NVRAM size are always set in the IOU command line. As a second step this option could be completely eliminated from the GUI and the server. But that might introduce some issues with older projects/templates.

The second possibility is to change only the default NVRAM to 64K, leaving the rest as it is (that's more in line of the first option). While that solves this issue with L3 v15.x IOU images, it does fix it for those images, where 16K is the default. Therefore I'm not a fan of that.

But of course you can use the second option with 64KB instead of 128KB. The space savings are not really relevant. I don't now if some images work better with 128KB than 64KB, maybe, maybe not.

The RAM is uncritical as there is no other program, that uses that as a parameter. Furthermore only very few images have another RAM size.

**Comment by ehlers** [comment]
Another idea: Similar to the layer-1-keepalive option you can get the default values of an image by initially starting it with option "-h" and extract the default values from the IOU help text.

**Comment by grossmj** [comment]
> Another idea: Similar to the layer-1-keepalive option you can get the default values of an image by initially starting it with option "-h" and extract the default values from the IOU help text.

I like this idea. I think this is something we can implement.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/e1fe34ca07417d81f7701525e79f3490042a456e
