### ISSUE TITLE
Can't Ping From high security level to low security level in ASA Firewall

### ISSUE THREAD

**Issue by meroloader** [GNS3/gns3-gui#2292]
Inside zone hosts can't ping outside zone hosts when connect ASA Firewall and error  "?????" Unknown Packet Type is shown even when permit an acls ,nat or change policy Of the ASA 9.x.

and ASA Can't Ping Outside hosts or Internet even when change policy.

**Comment by meroloader** [comment]
this photo when pinging to internet and gateway.
![error](https://user-images.githubusercontent.com/32749563/31517149-b681c840-afa3-11e7-8944-b68d82f36b57.jpg)

**Comment by vader75** [comment]
Just tested with 9.7.1

Seems to work fine with NAT rule. One thing that often gets overlooked is global inspect policy and icmp.

ASAvTest(config)# policy-map global_policy
ASAvTest(config-pmap)# class inspection_default
ASAvTest(config-pmap-c)# inspect icmp  

See if that is the case and if not we can compare topology and config.

**Comment by meroloader** [comment]
I will do that and if not working can you just give the asav that you use and tell me about gns3 version that you use?

Thanks by the way

**Comment by vader75** [comment]
I run GNS3 2.0.3. Server is running in ubuntu 16.04 and client is Mac GUI 2.0.3. 

The ASAv is 9.7.1 image asav971.qcow2 (you need to get it from "somewhere").

**Comment by meroloader** [comment]
Did the GNS3VM server affect My ASA? and How You Integrate That in GNS3?

**Comment by vader75** [comment]
GNS3 server I run is a remote GNS3 server on my LAN (running as VM on separate box). All images are there. So client connects to that server and runs full topology on it. 

I can't say for sure if your setup is problematic, but maybe create a new topology, perhaps simple one like mine and configure from scratch and start testing.

**Comment by meroloader** [comment]
i'll check that if works and see.
i got confused of that ,If you can give me step by step how to integrate gns3 to work with asa From First installing gns3 to create topology in last?

Thanks for your reply.

**Comment by vader75** [comment]
I just happen to run a remote server. 

It is the same as if you ran local VM. 

I can see you have setup your environment already, so no need to to take drastic changes to simulate what I have. 

My suggestion is that instead of a detailed and somewhat complex topology you are running, open a new project, drop in new ASAv and configure in same manner as I have, one side as NAT (outside) and another LAN (inside). Then test ping.

This way you can avoid other switches, routers that may cause dropped packets and only test ASAv issues.

If this works you can expand further adding additional elements.

Detail explanation installing the environment and ASAv to final product is not something I can do, as it would be somewhat detailed. It is not overly complicated if you look up GNS3 documentation or you could look at some videos on youtube such as https://www.youtube.com/watch?v=GM_VmmkCEag&t=69s by David Bombal

**Comment by meroloader** [comment]
ok i'll see that ,i'll tell if success

**Comment by meroloader** [comment]
it seems ok ... i found that ASAv that i'm used is broken can't fix that so i replace with newer one and it pings from inside to out side /inside to dmz/ dmz to outside 
and no pings from outside to dmz or inside so the problem is with ASAv i used... fixed

**Comment by vader75** [comment]
it happens, some images are broken. Good to test in isolation. Good work :-)

**Comment by meroloader** [comment]
but i have another problem , that when i used vmware pc so the link between switch and pc still in red and i can't install asdm through that pc ,Can you figure out that for me?

**Comment by vader75** [comment]
Would be guessing. Perhaps if you let GNS3 assign network adapter instead of VMware "Workstation" already having one. Very hard to fix remotely just looking at your image, unfortunately.

**Comment by meroloader** [comment]
thanks vader75 for your help , i'll see that and return back to you

**Comment by meroloader** [comment]
![error2](https://user-images.githubusercontent.com/32749563/31544979-0cd89a7a-b026-11e7-9808-2aa8a8b72f99.png)

this error becomes when i link vmware pc to switch. help please...

**Comment by meroloader** [comment]
![error 3](https://user-images.githubusercontent.com/32749563/31545064-72d4e482-b026-11e7-9e18-9e0862b6c4e7.png)

see in gns3 doctor the warning can't let me connect vmware pc. how to fix that?

**Comment by vader75** [comment]
Again guessing you may  need to have more VMware interfaces available to GNS3, added by GNS3 in the settings. After that a reboot may be required. See of that helps.

<img width="828" alt="screen shot 2017-10-13 at 10 56 58 pm" src="https://user-images.githubusercontent.com/3232190/31545180-11008b46-b06a-11e7-89bf-ed548c90d1ac.png">

**Comment by meroloader** [comment]
after doing these steps what else?

**Comment by vader75** [comment]
Don't have anything else. Also look at error, GNS3 is telling you to allow it to assign VMware ports. I think you may need to start troubleshooting in more detail and maybe google errors :-). The life of troubleshooting :-)

**Comment by meroloader** [comment]
![error 4](https://user-images.githubusercontent.com/32749563/31545780-66b87bde-b029-11e7-8469-c164fa4bcd4b.png)

this what happens when create vmnet 2

**Comment by vader75** [comment]
seems a problem, should just add interfaces and exit. Sorry beyond my understanding of NPCAP vs WINPCAP, maybe running winpcap instead of npcap would help or fix error.

**Comment by vader75** [comment]
https://www.gns3.com/qa/npf-or-npcap-serviceis-not-insta

**Comment by meroloader** [comment]
it's fixed so the solutions is to delete template from gns3 and go to vmware and network adapter is to be host only then stop npf then restart npf then go to gns3 then recall the template again so it's fixed by reset all thing and redo all steps again. thank you very very very much vadrer75 you helped me alot
