### ISSUE TITLE
GNS3 connecting to physical devices - ethernet error

### ISSUE THREAD

**Issue by Rob1NNk0** [GNS3/gns3-gui#2295]
Hello, 

My configured physical device is connected to my configured LAN-USB adapter (Ethernet 2). In GNS3 I use cloud configured with Ethernet 2 adapter. When I connect a virtual router, its port is green but clouds port is red with this error.
I've tried this: **sc config npf start= auto** 
It's not working.
I use the latest version of GNS3 with GNS3 VM (not updated).
 
Can somebody help me with this? I can't solve it for weeks.

**Edit://** By command **getmac /fo csv /v** I see device NPF_57.... is VirtualBox adapter. So I turned it off. Then I got new error NPF_D749... and its ASIX USB to LAN adapter through which I have connected Cisco router with my PC.

So, how to remove this error? I tried to connect cisco router to my primary LAN adapter but I got the same error.
 
unable to create NIO Ethernet for bridge '673e547b-7a43-4469-a7e3-985a66d3df0c-0': uBridge version 0.9.13 running with WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Hypervisor TCP control server started (IP 127.0.0.1 port 52582).
UDP tunnel connecting from local port 10001 to IPv4 addresss 127.0.0.1 on port 10000
nio_ethernet_open: unable to open device '\Device\NPF_{57307BEF-B041-45B0-A067-2A0679F83CA3}': Error opening adapter: The operation completed successfully. (0)

![image 2](https://user-images.githubusercontent.com/32804506/31580028-a52df418-b144-11e7-89e9-09d4c15ae61c.png)

**Comment by sairuscz** [comment]
Rob1NNk0: The Windows hosted clouds do not work as well as if they are hosted on Linux in general. Depending on the NIC and drivers used, I have also been experiencing various issues. 

The best and most stable solution is to create a virtual network adapter in VMwareWorkstation/VirtualBox and bridge it to your physical adapter. You can then add the virtual adapter to GNS3 VM and use it for GNS3 cloud. 

Remember to lower MTU to about 1480 if you will need to pass 1Q tags through the interface, otherwise the uBridge will crash.

**Comment by Rob1NNk0** [comment]
Hello,

I tried it via VMware and its works :) Thank you.
But, where should I lower MTU?

**Comment by grossmj** [comment]
Lower the MTU on the router connected to the cloud, for instance:

```
R1#conf t
R1(config)#int f0/0
R1(config-if)#mtu 1480
```

**Comment by sairuscz** [comment]
You should lower MTU only if you have a trunk link passing through the Gns3
cloud. You would have to set it on both sides of the link (the virtual
router and physical router interfaces).

**Comment by Rob1NNk0** [comment]
Oh, yes, got it :)

Thank you very much guys :)

**Comment by grossmj** [comment]
Regarding the original error, I don't think we can do anything. The problem comes from Winpcap or the Ethernet adapter driver. The most important is you found a workaround.

**Comment by krayut** [comment]
I got problem during connect GNS to Vmware virtual machine, could any one help me to fix it.

**Comment by grossmj** [comment]
Make sure you have installed winpcap and reboot or start the npf service.

**Comment by krayut** [comment]
For Winpcap I already installed, but i can't find npf service on my serivces management. Do you have other solution please?

**Comment by Rob1NNk0** [comment]
Hello,

I cant connect my physical devices to the GNS3 again. IT's frustrating. Happens after GNS3 reinstallation. Before this, I had bridged VMware virtual adapters with physical aadapter so GNS3+GNS3VM +physical devices were working fire. Now, after reinstallation if I bridge VMware virtual adapters with physical adapter, GNS3VM stop working with GNS3 and so physical devices are unable to connect to GNS3 vritual machines. Excellent.

**Comment by makco10** [comment]
Restart your pc..

**Comment by terr4n** [comment]
After installing microsoft loopback, be sure to restart your PC. It helped me. The error was the same as above.

**Comment by AlfredHS** [comment]
> After installing microsoft loopback, be sure to restart your PC. It helped me. The error was the same as above.


Thank you, PC reboot worked fine.
