### ISSUE TITLE
[2.1] IOL expects _private-config.cfg on config import

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#2296]
Hi,
I think I've opened a similar issue quite a while ago.
If I import configs and the folder does not contain <node-name>_private-config.cfg, an alert pop-ups for every node and the following log is written:
`no script file could be found, expected file name: R1_private-config.cfg`
**Expected behavior:** 
GNS3 should be able to handle the absence of private-config.cfg without any **alerts**/errors in console. At maximum, a warning message to the console could be written (personally, I do not think it is a useful thing to do)

**Comment by grossmj** [comment]
The code handling that is generic and we don't know if a config is required or optional. Therefore, I have replaced the alerts/errors by a simple warning message.
