### ISSUE TITLE
2.1 : BUG : no error when number of adapters of VirtualBox exceed max

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2298]
Hi

In the "preferences" menu. In "VirtualBox VMs" menu.
I choose 9 Adapters.  If i click on "OK", I have no error message (I think that is a bug).
I must wait to use this VM to have an error message.

**Comment by grossmj** [comment]
This is not a bug. The number of adapters depends on the system chipset (PIIX3 = 8 network interfaces vs ICH9 = 36 network interfaces) and we only know what chipset is configured when we start a VM.

https://github.com/GNS3/gns3-server/blob/2.1/gns3server/compute/virtualbox/virtualbox_vm.py#L667

**Comment by Raizo62** [comment]
Could you perhaps change the error message to "Your system chipset limit your VM to 8 adapters" ? Or something with the same idea

**Comment by grossmj** [comment]
I have improved the error message as well as the detection for the maximum number of adapters: https://github.com/GNS3/gns3-server/commit/b4307e603522a7f07392fabe7c7bbc758a38803c
