### ISSUE TITLE
Critical Enhancement - Add option to fix corrupt QEMU images

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2301]
Hi Team,
more and more often it happens to me that some of my QEMU VMs cannot boot up after an ungraceful shutdown. For this reason, I always used to keep daily backups so that I can restore to previous day if needed. However, I have just found out that the below simple command has restored all my PAN, BIG-IP and BIG-IQ VMs in a matter of seconds. All my frustration and fears are finally gone :-).

**qemu-img check -r all hda_disk.qcow2**

    gns3@gns3vm:/opt/gns3/projects/edb5b11f-1c4f-4b82-9370-422f1b16bd42/project-files/qemu/898ce213-81e0-4466-9b5f-c4e1db887323$ qemu-img check -r all hda_disk.qcow2

I feel so relieved now that I have found a solution to this issue. I am just curious if you could consider adding this option into GNS3 GUI? For instance, I thought it would be helpful if we could just right-click on the affected VM when it is powered off and select option to "Repair image" or something. The actual task takes only about 2 seconds, but getting to the exact location of the image and manually typing the command is rather a slow process".

The below is the end result after executing the image check. Notice it states there were no error, just wasted disk space due to bad cluster reference. However, in reality it already fixed 7 VMs for me already. 

    ...
    Repairing cluster 65050 refcount=1 reference=0
    Repairing cluster 65074 refcount=1 reference=0
    The following inconsistencies were found and repaired:
    
    1121 leaked clusters
    0 corruptions
    
    Double checking the fixed image now...
    **No errors were found on the image.**
    63891/655360 = 9.75% allocated, 20.18% fragmented, 0.00% compressed clusters
    Image end offset: 4265082880

**Comment by grossmj** [comment]
What about that command is automatically executed when a user starts a Qemu VM?

**Comment by sairuscz** [comment]
Smart! I like this idea even more.

**Comment by jean-christophe-manciot** [comment]
@grossmj 
According to the qemu-img man page:
```
If "-r" is specified, qemu-img tries to repair any inconsistencies found during the check. 
"-r leaks" repairs only cluster leaks, whereas "-r all" fixes all kinds of errors, 
with a higher risk of choosing the wrong fix or hiding corruption that has already occurred.
```
My advice is to try ```-r leaks``` when the check return code is 3 and check again to see if the error is gone,and try ```-r all```  when the check return code is 2 or if the first fix is not enough, considering that the ```-r all```  is not 100% bullet proof and might cause more damage than repair.

**Comment by grossmj** [comment]
Thanks for the input, I will be careful.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/967798a7de7040de38bfd4314537917d6d9a71d4
