### ISSUE TITLE
High ping time value

### ISSUE THREAD

**Issue by abdullahalikareem** [GNS3/gns3-gui#2302]
Dear Colleagues,

when i configured a loopback interface of mine to mikrotik router 
router ip > 192.168.100.10/24
loopback ip > 192.168.100.100/24

and i power up a ping from my pc the time of it goes very high and made a timeout's sometime and i cant control router by Winbox.

Could you advise me about it.

Best regards

![image](https://user-images.githubusercontent.com/19862046/31842606-a0aa06a4-b5f7-11e7-873a-943380e74303.png)

**Comment by grossmj** [comment]
Do you experience this with another type of node?
