### ISSUE TITLE
Enhancement - Add option to bend links

### ISSUE THREAD

**Issue by bpozdena** [GNS3/gns3-gui#2303]
Dear GNS3 Team,

I have been wondering if you could consider adding an option to put multiple "joints" on a link so that it can be bent. This would allow us all to create cleaner topologies with redundant links, switches and routers.

I have been doing it for quite some time by inserting a regular GNS3 switch with a custom symbol on the links I need to bend. It does the trick, but as you can see below it is not ideal.

Thanks for considering this and for all your great work!
Sairus

![dc_redundant](https://user-images.githubusercontent.com/24818591/31850489-62431dbe-b607-11e7-91cc-dfa25150aa6e.jpg)

**Comment by Santucci4** [comment]
I love this idea, add an additional +1 to this request
