### ISSUE TITLE
Request : option to enable "show/hide interface label"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2308]
Hi

Can we have an option to enable (or not) the option "show/hide interface label" for new project ?

**Comment by grossmj** [comment]
Do you mean that the option should be enabled by default when you create a new project?

**Comment by Raizo62** [comment]
Me, i like that "show/hide interface label" is enable for new project (i must explain it often at my students)
But perhaps other user doesn't like that.

Can we have an option in preference menu to choose the default for new project ?

**Comment by sairuscz** [comment]
I would also like to see the option to set separate default font and color for interface labels and node names. As of now, I have to manually select all interface labels in the topology an then adjust their font size an color.

**Comment by Raizo62** [comment]
I don't understand why you choose the milestone "TDB".

Am i the only one who clicks often on this button only to see easily what is the name of the connected interface that i want to configure ? Why this option can not be enable by default ?

(Honestly, I ask this option since several years, but the answer is always : for the next release)

**Comment by ziajka** [comment]
@sairuscz Separate issue for that: https://github.com/GNS3/gns3-gui/issues/2411

**Comment by ziajka** [comment]
Hi @Raizo62, this option is already implemented. Basically when you choose "show/hide interface label" on your current project and create new project it will keep interface labels.
Please check it (the best way is to use the latest version) and let me know.
Cheers,
Dominik

**Comment by Raizo62** [comment]
Hi

Sorry, i have tried and it doesn't work : 

I use GNS3 2.1.4.dev1 of yesterday on Linux

I create a project called "untitled". I put devices with cables, i enable "show/hide interface labels".
I close GNS3

I start GNS3 and create a new project "untitled2" : "show/hide interface labels" is again disable.

**Comment by ziajka** [comment]
Hi @Raizo62,
That's true, I haven't closed GNS3 GUI.
I'm reopening this. 
Thanks,
Dominik

**Comment by Raizo62** [comment]
I have tested and that's works :-D
Thank very much :-)

**Comment by ziajka** [comment]
You're welcome!
