### ISSUE TITLE
 Increase the default virtual disk of GNS3 VM.ova and add low disk space warning

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2311]
Recently, many appliances in my topology started freezing randomly. I could not find out why until I finally noticed I that /dev/sdb1 ran out of space.

It was relatively easy to expand the vDisk in VMWare and then resize the partition using GParted. It was just not easy to detect the actual problem.

Would it be possible to:
1) Warn the user in GNS3 console when /dev/sdb1 utilization gets over 90% ?
  ```
 gns3@gns3vm:~$ df -Pl | grep '^/dev/sdb1' | awk '{print "Available Disk Space: " 100 - $5 "%"}'
   Available Disk Space: 1%
```

2) Increase the default disk size of GNS3 VM-disk2.vmdk in the GNS3 VM.ova? Perhaps 300GB lazy-zeroed would be more preferable default value compare to the current 100GB. 

Thanks for considering,
Sairus

**Comment by grossmj** [comment]
I've increased the disk size to 300GB: https://github.com/GNS3/gns3-vm/commit/b6bb7d79e14ccf3bd5ef4899c40e390ce46476fb

However let's check that the VM OVA is still small after the next build.

**Comment by grossmj** [comment]
I have implemented the low disk space warning: https://github.com/GNS3/gns3-server/commit/9afe756462219f95ce4314b4f3e6ecdcdf9903fc
