### ISSUE TITLE
Generating snapshots containing large images crashes the server and screws-up the GUI

### ISSUE THREAD

**Issue by WhiteWinterWolf** [GNS3/gns3-gui#2314]
Installed a end-node operating system from within a topology breaks the snapshot functionality:

1. Install a host from within a topology.
2. Try to do a snapshot, GNS3 completely screws up and requires a hardware restart of the host to get back to normal.
3. The snapshot appear in the snapshot list, but is corrupted: trying to load it generates a *"Can't import topology the file is corrupted or not a GNS3 project (invalid zip)"* messages after having deleted the current project.

Here, the GNS3 servers as to create a ZIP archive containing the installed end-node disk image, if the operation doesn't complete in a few seconds the whole GNS3 (server + GUI) severely screw-up requiring a hard-restart of the host.

GNS3 should allow enough time to allow to build the snapshots. In all cases, it should not fail so badly in case of timeout errors.

This issue is somewhat linked to #2239 as it shares one of the same underlying problem: GNS3 assumes that only tiny files are used in its project and that any operations on them will end in a few seconds. However I open a different issue as this one doesn't involve the discussion around MD5 files generation: here there is no other choice than making GNS3 to allow longer operations.

**Comment by WhiteWinterWolf** [comment]
Workaround which seems to work (crossing my fingers):

1. Install the end-node operating system outside of GNS3 to avoid the current issue #2314.

2. Create a Qemu snapshot image from the resulting disk image to avoid issue #2239.

3. In GNS3 GUI, select the Qemu snapshot image as new HDD image for the end-node.

4. GNS3 may silently fail to update the end-node disk image. If the OS fails to boot and, in the case of Linux distros, you get a Grub rescue shell because of an *"attempt to read or write outside of disk 'hd0'"*, you must manually delete the Qemu snapshot image generated by GNS3 from within the project files and repeat step 3 to force GNS3 to recreate it correctly¹.

The process is quite cumbersome, but at last at the end you should get a working, freshly installed end-node guest working in GNS3 with working snapshots so you can proceed your labs.

---

¹:  Something fishy seems to be hiding there. In my case the image seemed to point to the new backing file path while keeping size information from the previous one, hence causing the Grub issue. But this seems a minor annoyance compared to the rest.

**Comment by grossmj** [comment]
Hi,

What version of GNS3 have you used?

**Comment by WhiteWinterWolf** [comment]
@grossmj : I'm using GNS3 2.0.3 (Debian 8.9 Jessie).

**Comment by grossmj** [comment]
This should be fixed now.
