### ISSUE TITLE
Issue with GNS3 2.1.0 RC3 on Mac

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#2316]
Hi,
 
When I try to use an IOS 3745 image with the correct IDLE-PC value as stated in the GNS3 documentation I get the error message attached. However, if I run the same image on a windows machine with the same IDLE-PC value I have no issues getting the devices to bootup.

![image](https://user-images.githubusercontent.com/16152626/32127990-79a5aff8-bb48-11e7-905d-83abd4d1893e.png)

**Comment by ziajka** [comment]
Hi @Vic563 ,
Thank you for reporting this. We will investigate the issue.
Cheers,
Dominik

**Comment by grossmj** [comment]
Error -11 means segfault, in other words Dynamips has crashed when running the IOS image. What is the image name?

**Comment by Vic563** [comment]
I am running code version "c3745-adventerprisek9-mz.124-25d.image" and I have the image running locally on my mac since I need to bridge the 3745 router to a live network for testing. If not I would have run the 3745 image on the GNS3 VM.

**Comment by grossmj** [comment]
Create a project with one c3745 router, start it and wait for the crash to happen. Then right click on the node and select "Show in File Manager", go to the upper directory and you will find 2 text files `dynamips_i1_log.txt` and `dynamips_i1_stdout.txt`. Can you post their content?

Thanks,

**Comment by Vic563** [comment]
[c3745_i1_log.txt](https://github.com/GNS3/gns3-gui/files/1431914/c3745_i1_log.txt)

Attached is the c3745_i1_log.txt file. However, in the same folder, I don't see a stdout.txt file.

**Comment by grossmj** [comment]
@Vic563 did you have the problem with version 2.0.3?

**Comment by Vic563** [comment]
Hi grossmj,

     I just tried with 2.0.3 and I had no issues bringing up the image. So I am not sure what is the issue with 2.1.0 RC3.

**Comment by ziajka** [comment]
Internal note: dynamips is bundled in build repo so CD change has no impact on that. However between 2.0.3 version to 2.1.0 RC3 dynamips version changed from 0.2.16 to 0.2.17.

**Comment by ziajka** [comment]
`BRN-MAC-Sierra-3:Resources labuser$ ./dynamips -P 3745 -n 256 [image]
Cisco Router Simulation Platform (version 0.2.17-amd64/Darwin unstable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Jul 24 2017 04:51:00

NVRAM size set to 256 KB.
IOS image file: [image]

NVRAM is empty, setting config register to 0x2142
C3745 instance 'default' (id 0):
  VM Status  : 0
  RAM size   : 128 Mb
  NVRAM size : 256 Kb
  IOS image  : [image]

Loading ELF file '[image]'...
ELF entry point: 0x80008000

C3745 'default': starting simulation (CPU0 PC=0xffffffffbfc00000), JIT enabled.
VM default: starting CPU!
RSegmentation fault: 11
`

**Comment by ehlers** [comment]
Same here with c3725-adventerprisek9-mz.124-25d. The dynamips from 2.1.0dev9 from nightly build 2017-11-04 crashes the same way.

On https://github.com/GNS3/dynamips/pull/81 I've used gcc v4.9 for compiling dynamips, which was stable. Just recompiled it with Apple LLVM version 8.0.0 (clang-800.0.42.1) from the OS X 10.11 command line developer tools. Seems to be stable as well, but haven't time for extensive tests.

**Comment by ehlers** [comment]
Just installed the nightly build 2.1.0dev10 from 2017-11-08 and this dynamips issue is still there. Then I downloaded https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2017-11-08/dynamips-unstable-osx/download, made it executable and used it to replaced the dynamips in GNS3.app. This dynamips works.

**Comment by ziajka** [comment]
Thank @ehlers for checking it and giving a solution. I will double test and then we will ship this version of dynamips in the final release.

**Comment by ziajka** [comment]
It works.
