### ISSUE TITLE
REQ : use GNS3's variables in qemu's options

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2318]
Hi

I want that my Qemu VM knows his name in GNS3.

If i add in "Additionnal settings" of configuration of qemu this line : 
`-smbios type=1,serial="NAME-OF-VM"`
The VM can know this value with :
`dmidecode -s system-serial-number`

But, i need to adapt NAME-OF-VM with the true name of the VM.

Have we variables in this zone ?

Or do you have an another method to share this name ?

(Edit : to inform, i need also the path of project)

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/e08aebf1f0c0765a55d82da40b6f9909818ecc94

Current variables are:

* %vm-name% =VM name
* %vm-id% =VM ID
* %project-id% = project ID
* %project-path% = project path

Let me know if you need more.
