### ISSUE TITLE
REQ : autodetect kvm

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2319]
Hi

When we install GNS3 on Live distribution, we can't know if kvm can be used on the Host.

Can we have an other option who is enable only if "Enable kvm acceleration" is checked : 
This new option will be : "Enable kvm only if detected".

I believe that you only need to verify if the file "/dev/kvm" exist

**Comment by grossmj** [comment]
It should be noted that you can deactivate KVM check on a VM basis by adding "-no-kvm" to options in additional settings. Would this be enough?

**Comment by Raizo62** [comment]
I would like prefer that is transparent for users (students...) of GNS3  : If the "admin" enables an option ("Enable kvm only if detected"), GNS3 uses kvm only if it can (the file /dev/kvm exists). There are no warning for users (students,...) in the log messages if it can't

**Comment by grossmj** [comment]
Ok, we will add this option.

**Comment by grossmj** [comment]
Implemented by https://github.com/GNS3/gns3-gui/commit/d8dc31965f7938a5ff479ab67ce36a8f165043c7
and https://github.com/GNS3/gns3-server/commit/3e2e8e61f734eea52604117b33017bb9c33f90f6
