### ISSUE TITLE
Bug/Question :  2.1 : not same symbols in gns3-server and gns3-gui

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2320]
Hi

In gns3-gui/resources/symbols/, i count 26 symbols.

in gns3server/symbols/, i count 42 symbols.

All symbol in gns-server are not in the symbol directory of gns3-gui. Is it OK ?

Edit : symbol of gns3-gui seems not to be installed. Is this an old forgotten directory ?

**Comment by grossmj** [comment]
The important symbols are in gns3server/symbols/ and most of the symbols in gns3-gui/resources/symbols/ are not used anymore, these should have been deleted. I will clean this after we release 2.1

> Edit : symbol of gns3-gui seems not to be installed. Is this an old forgotten directory ?

This directory is not installed, the symbols are added to a resource file (resources_rc.py).
