### ISSUE TITLE
GNS3 overwrites the disk images files stored in  ~/GNS3/images/QEMU/

### ISSUE THREAD

**Issue by WhiteWinterWolf** [GNS3/gns3-gui#2326]
# Current behavior

1. Create a new Qemu virtual machine template, select an already existing disk image file, named *hda.qcow2* for instance.

2. Accept when GNS3 asks if it should copy it inside GNS3 directory tree.

    The selected file is copied as *~/GNS3/images/QEMU/hda.qcow2*.

3. Create a second Qemu virtual machine template, select an already existing disk image bearing the same name as the previous one (*hda.qcow2*, but the file itself is different and located in a different directory).

4. Accept when GNS3 asks if it should copy it inside GNS3 directory tree.

The newly selected file overwrites *~/GNS3/images/QEMU/hda.qcow2*.

All end-devices nodes using the first template are now be broken.

# Expected behavior

When copying a file inside its own directory tree, GNS3 should check if the destination name already exists and, if so, automatically choose a new unique name (*hda_1.qcow2* for instance).

**Comment by grossmj** [comment]
Fixed for local image copying.
