### ISSUE TITLE
GNS3 2.1 on OSX - VMware executable path not found in $PATH

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#2329]
Hello,

Running MAC OSX 10.13.1
GNS3 2.1
VMware Fusions Professional Version 10.0.1 (6754183)

What: Trying to add VMware Virtual Machine

What happens: error, see:

![screen shot 2017-11-10 at 11 27 55 am](https://user-images.githubusercontent.com/3232190/32636890-f61540f4-c60a-11e7-9013-60a2d8b33860.png)

VMware Fusions executable seems to be in the standard path:

```
Gordons-iMac:/Applications/VMware Fusion.app/Contents/Library$ ls | grep vmrun
vmrun*
 
```

Hmmm.

**Comment by grossmj** [comment]
This is strange, we only check that VMware Fusion is installed on Mac: https://github.com/GNS3/gns3-server/blob/2.1/gns3server/compute/vmware/__init__.py#L210

It shouldn't be possible to get that error message on OSX. We need to investigate that but this is not easy since we now have limited access to a Mac machine.

**Comment by vader75** [comment]
Yeah, it seems the script is not picking up the system platform. Is it case sensitive?

```
>>> platform.system()
'Darwin'
```

**Comment by grossmj** [comment]
Try with `print(sys.platform)`

**Comment by vader75** [comment]
Yeah prints 'darwin'

**Comment by vader75** [comment]
I was trying to follow the code line you sent me, am I right to say that vmware_path = VMware._get_linux_vmware_binary() will still be executed returning None anyways and causing the error ?

**Comment by grossmj** [comment]
This should not be executed on Mac because of the 'return' on https://github.com/GNS3/gns3-server/blob/2.1/gns3server/compute/vmware/__init__.py#L214

**Comment by vader75** [comment]
Thanks. Let me know if you want testing done on OSX, happy to assist.

**Comment by ehlers** [comment]
No issues with OS X 10.11 and VMware Fusion 8.5 on GNS3 V2.1.

**Comment by grossmj** [comment]
I cannot find a reason why this doesn't work. @vader75 did you install GNS3 only by moving the DMG in /Applications?

**Comment by vader75** [comment]
@grossmj Yes I did, I have now installed it on another Mac, same result. 

Only thing I can think of is the fact that I am running the GNS3 server on a remote box, while the client is local per Mac. 

Does this have any impact, is lookup still done locally? 

Otherwise I am out of ideas.

**Comment by grossmj** [comment]
> Does this have any impact, is lookup still done locally?

No the lookup is done on the server which I assume is a Linux box, right?

**Comment by vader75** [comment]
Yes its Linux. 


I must admit, I have moved to remote server months ago, but did not test this scenario (moved to study other things). 

I expected the local GNS# client would look locally for VMware Workstation/Player and tunnel the traffic to GNS3 server (as one can tunnel traffic across multiple GNS3 servers).

Is there any way this could be done, local VMware and remote GNS3 server?

**Comment by grossmj** [comment]
Sorry, emulators like VMware must be installed on the same host as the GNS3 server.

**Comment by ehlers** [comment]
I agree, that I never used VMware on a remote server. But at least the basics are working.

In GNS3 on my Mac I've added a remote linux server, which has VMware installed. In the VMware VM preference, when I add a new VM I can select, which server I want to use:
![server_selection](https://user-images.githubusercontent.com/896406/32787703-808d493a-c957-11e7-8f75-b3d3889bf40d.png)

After selecting the remote linux server I get a list of installed VMware VMs on that server:
![vmlist_remote](https://user-images.githubusercontent.com/896406/32787639-5320f3c0-c957-11e7-8d76-b70d9b89e8df.png)

At that stage, I canceled, as I don't really want to run a remote VMware VM. But at least it should be possible to select the remote VM.

**Comment by vader75** [comment]
Thank you. 

I guess we can close the issue, I will try to think about the way to "amend" my setup. 

Perhaps run local VMware server/GNS3 server for VM connectivity and a remote (linux) GNS3 server to do the heavy topology lifting.

My general approach was to run remote server to accomodate for various machines (laptops and desktops) have access to the same and consistent project environment in more distributed environment. 

:-)

**Comment by grossmj** [comment]
No worries :+1:
