### ISSUE TITLE
Console to builtin Ethernet switch doesn't close, when project closes

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2330]
GNS3 version 2.1.0 on Darwin (64-bit) with Python 3.6.3 Qt 5.9.2 and PyQt 5.9.1.

Create a project with a builtin ethernet switch and open a console to it. Now open another project, that closes the first project. All console windows get closed except the console to the ethernet switch.

**Comment by ehlers** [comment]
Same happen, when a builtin ethernet switch is deleted. A previously opened console does not close, it still reacts to \<return\> and the help command. The arp command blocks the console.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/pull/1228
