### ISSUE TITLE
GNS3 segmentation fault Ubuntu 17.10

### ISSUE THREAD

**Issue by theultimatehorse** [GNS3/gns3-gui#2331]
Hey, GNS3 crashed with a segmentation fault after clean install. I'm running Ubuntu 17.10 (artful). I checked journalctl andit seems to have something to do with:

>  
nov 10 17:32:14 rodrigo-CX62-6QD kernel: traps: gns3[15674] general protection ip:4dc410 sp:7ffecc6335e8 error:0 in python3[400000+3bf000]

Here is the full output of journalctd | grep -i gns: https://pastebin.com/ftqeYWha
 
I installed GNS3 following these instructions: https://launchpad.net/~gns3/+archive/ubuntu/ppa. 
 
Edit: just to clarify, it crashes immediatly after running "gns3" on the terminal. Output is nothing but "segmentation fault".

**Comment by AJNOURI** [comment]
Thanks @theultimatehorse .

**Comment by theultimatehorse** [comment]
Apparently GNS3 was using a shared library installed with pip3 (SIP) when it should be using its own. I fixed it by uninstalling SIP using pip3.

**Comment by grossmj** [comment]
Strange, do you remember which shared library?

**Comment by theultimatehorse** [comment]
#1  0x00007ffff50c8d21 in vp_convertor () from /home/rodrigo/.local/lib/python3.6/site-packages/sip.so
That's directly from gdb bt's output.
