### ISSUE TITLE
Issues with VM 2.1.0rc3 Upgrade 

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2332]
I have tried number of times to upgrade VM 2.1.0rc3 to the latest released VM 2.1.0 but ended up with VM 2.1.1dev1.  I have used both options (Version and Upgrade) and I'm getting the same result.  Did I miss something?
![vm version 2 1 0 after upgrade](https://user-images.githubusercontent.com/17806351/32686416-8a1b7234-c672-11e7-99d2-f45250e80873.png)
![vm version 2 1 0 upgrade](https://user-images.githubusercontent.com/17806351/32686417-8a287ca4-c672-11e7-9778-0d8e2d95f8fb.png)

**Comment by hamoja** [comment]
Same issue here how can I fix the problem, my GNS3 client 2.1.0 no longer works and now complains "client version 2.1.0 differs with server version 2.1.1dev1". help!

**Comment by grossmj** [comment]
You should still be able to use it. We are going to look at this problem soon.

**Comment by hamoja** [comment]
Tried I'm unable to open my project now. SIGH!

**Comment by sliddjur** [comment]
Me too, having the same issues trying to upgrade to 2.1

**Comment by grossmj** [comment]
Please upgrade the VM (from the menu) and this time you should get 2.1 instead of 2.1.1dev1.

**Comment by fatbell** [comment]
It worked.  Please close the ticket.  Thank you for your time
