### ISSUE TITLE
Idea for Qemu VM detects plug/unplug of link

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2336]
Hi

I use monitor of qemu. I have tested with Qemu monitor of qemu version 2.8.1 of Stretch debian.

I suppose that the monitor port of the Qemu VM is 5234

If i want to unplug the first interface, i send to this port the command : set_link gns3-0 off
Example with bash : echo 'set_link gns3-0 off' > /dev/tcp/127.0.0.1/5234

if i want to plug the first interface,  i send to this port the command : set_link gns3-0 on
Example with bash : echo 'set_link gns3-0 on' > /dev/tcp/127.0.0.1/5234

**Comment by grossmj** [comment]
Thanks, using the set_link command is what I had in mind! :+1: 

Related to https://github.com/GNS3/gns3-gui/issues/2173

**Comment by Raizo62** [comment]
Do you know when you can implement this very usefull functionnality ? ;-)

**Comment by grossmj** [comment]
I've implemented it: https://github.com/GNS3/gns3-server/commit/c7875f93a3b55ac4642d85793e017dfd8b9155a7

**Comment by grossmj** [comment]
Seems to work well. Please re-open/comment here if you see an issue.

**Comment by Raizo62** [comment]
Sorry : i have a bug but i don't know if this functionality is the cause. It is the first time that i use the 2.2 (i used the 2.1)

When i want to create link (even without qemu device : example between dynamips router and ethernet switch), i have this error message : 
```
2018-03-19 18:59:44 WARNING __init__.py:224 Error while creating link: Internal server error http://127.0.0.1:3080/v2/compute/projects/ac0cc9ed-3f0d-4122-90a6-6046458118b6/ethernet_switch/nodes/2cf74c27-b556-4a9e-9703-3403fc3ee9b9/adapters/0/ports/0/nio
2018-03-19 18:59:48 WARNING __init__.py:224 Error while creating link: Internal server error http://127.0.0.1:3080/v2/compute/projects/ac0cc9ed-3f0d-4122-90a6-6046458118b6/dynamips/nodes/8fb3404d-6f69-4d62-90b8-9060362eb2db/adapters/0/ports/0/nio
```

**Comment by grossmj** [comment]
Should be fixed now. Be careful with 2.2, it is work in progress.

**Comment by Raizo62** [comment]
Now, i can create link and start the VM, 
but at first boot of the VM : the VM doesn't see the interfaces as no plugged 
after reboot, it is ok.
(speed test)

> Be careful with 2.2, it is work in progress.

I have no choose :-( But, i will wait the merge in 2.1 if it is not too long time :-(

**Comment by grossmj** [comment]
Looks like Qemu doesn't like the set_link off just right after starting the Qemu VM. I will see what I can do.

**Comment by Raizo62** [comment]
I believe that is more the first time to create the QEmu device that the set_link doesn't like, because, after reboot, the VM see the unplugged card (it is not the time to boot)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/a40fdb3641de792b36820fa91af90fad563eea90

The problem was that we were not waiting for Qemu monitor to be ready to receive commands immediately after starting the VM.

**Comment by Raizo62** [comment]
Thanks :-)
