### ISSUE TITLE
VMware virtual machines added to GNS3 topology configuration changes

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2341]
Windows 10 Prof X64, VMware Workstation Professional 12.5.8 build-7098237, GNS3 2.1.0

Most recently occurring on GNS3 2.1.0 but occurs on previous versions of GNS3.  It appears when I add a VMware virtual machine to GNS3 via preferences GNS3 application maintains configuration information of that virtual machine.  When I delete that virtual machine from GNS3 application, again via Preferences, and add a "new" instance of that same virtual machine, GNS3 still see that virtual machine with the "original" configuration.  Bottom line, it appears the GNS3 application will literally modify a VMware Workstation virtual machine configuration.   Specially it modifies the VMware Workstation virtual machine's Network Adapter and Serial Port.
Hope this makes sense!

**Comment by grossmj** [comment]
Do you have this issue if you stop GNS3 before adding a new instance?

**Comment by jtorri** [comment]
I am unable to consistently identify a sequence of deleting, modifying or adding a VMware virtual machine to the GNS3 application via Preferences where value for network adapter and serial port of the virtual machines are not modified when the topology runs.
