### ISSUE TITLE
GNS3 all-in-one silent doesn't work [for public school]

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2343]
From community forum:
https://gns3.com/qa/i-m-trying-to-do-a-silent-instal

> Hi, I work for a public school and I need to deploy the GNS3 2.1.0 all in one program. So I did a few tests and found out about the /S switch to do a silent install. At first, it seems to work. Then, I get a popup asking if I want to install WinPcap 4.1.3. It’s already installed on my computer. Then it ask me if I want to install Wireshark 4.1.2, also already installed on my computer. Then I get a popup asking me to enter an email address for the Solarwinds program. I'm sorry but I need to do a silent install on multiple computers using Novell ZENworks. There won't be anyone in front of the computers to answer these questions. Is there a way to install each programs, include in the all in one, one by one? That way I would have more control on the installation part. In other words, does an installer exist for the GNS3 program only?
>  
> Thanks in advance for the help!
> Guillaume

**Comment by grossmj** [comment]
The installer for version 2.1.1 now supports a silent install (provided winpcap has already been installed).
