### ISSUE TITLE
Auto Idle-PC doesn't work in preference

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2344]
GNS3 version 2.1.1dev1 (latest) on Darwin (64-bit) with Python 3.6.3 Qt 5.9.2 and PyQt 5.9.1.

See also https://www.gns3.com/news/article/gns3-2-1-released comment from Tom Reilly

When I create a new dynamips router and use the Idle-PC finder in the preferences it always responds with "Error: Sorry, no idle-pc value was suitable". Before the commits today it responds with the error message Tom has posted. When dragging the same router into a new topology and use the "Auto Idle-PC" function it works.

I tested that with c2691-adventerprisek9-mz.124-25d.image (to have a similar image as Tom) and with c3725-adventerprisek9-mz.124-25d.image . In both images show this error.

**Comment by grossmj** [comment]
This should work now. Please re-open if you still encounter an issue.

**Comment by ehlers** [comment]
Works fine, thanks.
