### ISSUE TITLE
[Linux/2.1.0] Communication with tap interfaces is broken

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2348]
Ubuntu server 17.10
gns3 2.1.0
ubridge 0.9.13

**No such issue with gns 2.0.3 on Ubuntu server 17.04 zesty**

Opening an existing 2.0.3 project:
1) **Existing cloud** (called Ansible below and created with 2.0.3)
![existing cloud](https://user-images.githubusercontent.com/13176858/33206483-b5d03a5c-d10a-11e7-9472-165bbd836cbd.png)
The connection point (tap5) is red instead of green.
**There is no log attached to the cloud**.
```
# ifconfig tap5
tap5: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 9e:7a:42:6b:c2:ec  txqueuelen 1000  (Ethernet)
# brctl show virbr5
bridge name	bridge id		STP enabled	interfaces
virbr5		8000.525400b9ea63	no		tap5
							virbr5-nic
```
2) **New cloud** (called cloud-1 below and created with 2.1.0)
Using another tap interface:
```
# ifconfig tap4
tap4: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether fe:14:ab:77:51:91  txqueuelen 1000  (Ethernet)
# brctl show virbr4
bridge name	bridge id		STP enabled	interfaces
virbr4		8000.52540078ef37	no		tap4
							virbr4-nic
```
Adding a link to tap4 fails:
![new cloud](https://user-images.githubusercontent.com/13176858/33206955-43616c78-d10c-11e7-9706-01fa5d8e6ea2.png)
**No log attached to that node**.
```
create_nio_tap: ... operation not permitted
```
... despite GNS3 being run as root.

- [GNS3 GUI log](https://github.com/GNS3/gns3-gui/files/1501384/gns3_gui.log)
- [GNS3 Server log](https://github.com/GNS3/gns3-gui/files/1501385/gns3_server.log)
.

**Comment by jean-christophe-manciot** [comment]
Actually, this issue does not seem to be directly caused by GNS3: it also happens with 2.0.3 on the same Ubuntu artful.
Since there was no such issue on zesty, it must be caused by the tap or bridge utilities which have changed in the meantime.
Building latest bridge-utils from debian (1.5-14) does not solve the issue.
I need to investigate more.

**Comment by jean-christophe-manciot** [comment]
- Ubuntu zesty:
  + bridge-utils: 1.5-9ubuntu2
  + uml-utilities: 20070815.1-2build1
  + ebtables: 2.0.10.4-3.5ubuntu1
  + ifupdown: 0.8.16ubuntu1
- Ubuntu artful:
  + bridge-utils: 1.5-9ubuntu2
  + uml-utilities: 20070815.1-2build1
  + ebtables: 2.0.10.4-3.5ubuntu2
  + ifupdown: 0.8.16ubuntu2

The last 2 packages have been slightly modified.

But something deeper has changed, especially for the server flavor (as mine):

> Network configuration

> ifupdown has been deprecated in favor of netplan and is no longer present on new installs. The installer will generate a configuration file for netplan in /etc/netplan, which will set up the system to configure the network via systemd-networkd or NetworkManager. Desktop users will see their system fully managed via NetworkManager as it has been the case in previous releases, but Server users now have their network devices managed via systemd-networkd on new installs. This only applies to new installations.
> 
> Given that ifupdown is no longer installed by default, its commands will not be present: ifup and ifdown are thus unavailable, replaced by ip link set $device up and ip link set $device down.
> 
> The networkctl command is also available for users to see a summary of the network devices. networkctl status will display the current global state of IP addresses on the system; and networkctl status $device can display the details specific to a network device.
> 
> For more information about netplan, please refer to the manual page using the man 5 netplan command.

Is there an impact for GNS3?

**Comment by jean-christophe-manciot** [comment]
Using the new commands set:
```
# networkctl status tap5
● 9: tap5
       Link File: n/a
    Network File: n/a
            Type: ether
           State: n/a (unmanaged)
          Driver: tun
      HW Address: 9e:7a:42:6b:c2:ec
# networkctl status virbr5
● 15: virbr5
       Link File: n/a
    Network File: n/a
            Type: ether
           State: n/a (unmanaged)
          Driver: bridge
      HW Address: 52:54:00:b9:ea:63
         Address: 172.21.0.1
                  fc21::1
                  fe80::5054:ff:feb9:ea63
```
I also discovered that both network services are active on my system, which is not good:
```
# systemctl status  systemd-networkd
● systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; enabled-runtime; vendor preset: enabled)
   Active: active (running) since Fri 2017-11-24 09:43:33 CET; 3h 22min ago
     Docs: man:systemd-networkd.service(8)
 Main PID: 1223 (systemd-network)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   Memory: 3.6M
      CPU: 91ms
   CGroup: /system.slice/systemd-networkd.service
           └─1223 /lib/systemd/systemd-networkd

Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr3-nic: Lost carrier
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr3: Lost carrier
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr14-nic: Gained carrier
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr14-nic: Lost carrier
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr0-nic: Gained carrier
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr3: Gained IPv6LL
Nov 24 09:45:41 samsung-ubuntu systemd-networkd[1223]: virbr0-nic: Lost carrier
Nov 24 11:04:02 samsung-ubuntu systemd-networkd[1223]: wlan0: Lost carrier
Nov 24 11:04:07 samsung-ubuntu systemd-networkd[1223]: wlan0: Gained carrier
Nov 24 11:04:09 samsung-ubuntu systemd-networkd[1223]: wlan0: Gained IPv6LL

# systemctl status NetworkManager
● NetworkManager.service - Network Manager
   Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-11-24 11:04:02 CET; 2h 2min ago
     Docs: man:NetworkManager(8)
 Main PID: 1441 (NetworkManager)
    Tasks: 6 (limit: 4915)
   Memory: 33.0M
      CPU: 7.919s
   CGroup: /system.slice/NetworkManager.service
           ├─1441 /usr/sbin/NetworkManager --no-daemon
           ├─1512 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/run/NetworkManager/dnsmasq.pid --listen-address=127.0.0.1 --cac
           ├─1578 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper -pf /run/dhclient-p3p1.pid -lf /var/lib/NetworkManager/dhclient-51112cc6-a7a5-45c5-ae44-79e
           └─3054 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper -pf /run/dhclient-wlan0.pid -lf /var/lib/NetworkManager/dhclient-7ec429cb-9dde-4ea4-8eda-f2

Nov 24 13:06:37 samsung-ubuntu dnsmasq[1512]: reply play.google.com is <CNAME>
Nov 24 13:06:37 samsung-ubuntu dnsmasq[1512]: reply play.l.google.com is 216.58.205.174
Nov 24 13:06:37 samsung-ubuntu dnsmasq[1512]: query[A] play.l.google.com from 127.0.0.1
Nov 24 13:06:37 samsung-ubuntu dnsmasq[1512]: cached play.l.google.com is 216.58.205.174
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: query[A] clients4.google.com from 127.0.0.1
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: forwarded clients4.google.com to 8.8.4.4
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: reply clients4.google.com is <CNAME>
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: reply clients.l.google.com is 172.217.23.110
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: query[A] clients.l.google.com from 127.0.0.1
Nov 24 13:06:48 samsung-ubuntu dnsmasq[1512]: cached clients.l.google.com is 172.217.23.110
```
Disabling systemd-networkd:
```
# systemctl stop systemd-networkd
```
Trying GNS3 2.0.3 again leads to the same issue.

**Comment by jean-christophe-manciot** [comment]
Downgrading ebtables & ifupdown to zesty releases does not solve this issue either.
I'm clueless now.

**Comment by grossmj** [comment]
Ok, thanks for the feedback. I will try to run some tests on my side.

**Comment by jean-christophe-manciot** [comment]
@grossmj 
Same issue on **Debian**:
Debian Stretch 9.2
gns3 gui/server 2.1.0
gns3-ubridge: 0.9.13
bridge-utils: 1.5-13+deb9u1
uml-utilities: 20070815.1-2+b2
ebtables: 2.0.10.4-3.5+b1
ifupdown: 0.8.19

**Comment by jean-christophe-manciot** [comment]
Cf. https://github.com/GNS3/gns3-gui/issues/2348#issue-276579783

Is your cloud connected through a tap interface and is the associated topology point green?

**Comment by grossmj** [comment]
> Is your cloud connected through a tap interface and is the associated topology point green?

Yes, uBridge creates the TAP interface and I connect a node to the cloud/TAP interface. The point is green.

**Comment by jean-christophe-manciot** [comment]
Have you rebuilt GNS3 GUI/server in the artful-specific environment which uses python 3.6 instead of 3.5?

**Comment by jean-christophe-manciot** [comment]
Same question about the other GNS3 components (including ubridge)? The build tools have also evolved (for instance, gcc).

**Comment by jean-christophe-manciot** [comment]
Or you could fetch the builds from my static [GNS3 repository](https://gitlab.com/jean-christophe-manciot/gns3).

**Comment by jean-christophe-manciot** [comment]
I've just rebuild 2.1.0 within zesty and the tap communication works within zesty.
I just need to test that zesty build into artful now.

**Comment by jean-christophe-manciot** [comment]
Actually, I can't install on artful gns3 gui/server built in zesty: there is no python3.5 on artful. I would have to rebuild the latter.

**Comment by jean-christophe-manciot** [comment]
@grossmj 
Sorry, I missed one of your comment:
> uBridge should already have the needed permissions by default. You can check with the following command:
> $ getcap /usr/local/bin/ubridge 
> /usr/local/bin/ubridge = cap_net_admin,cap_net_raw+ep

I don't have the same capabilities:
```
# getcap /usr/local/bin/ubridge 
#
```

Setting the capabilities with:
```
# setcap cap_net_admin,cap_net_raw+ep /usr/local/bin/ubridge
# getcap /usr/local/bin/ubridge 
/usr/local/bin/ubridge = cap_net_admin,cap_net_raw+ep
````
Now, the **tap point has turned green**, but the communication with the tap interface still fails on artful!

**Are there other gns3 binaries (such as dynamips...) which need special capabilities now**?

**Comment by grossmj** [comment]
> Are there other gns3 binaries (such as dynamips...) which need special capabilities now?

Only uBridge.

**Comment by grossmj** [comment]
Do you have anything in ubridge.log?

**Comment by jean-christophe-manciot** [comment]
Yes, everything seems fine now for the host cloud:
```
uBridge version 0.9.13 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 127.0.0.1 port 58239).
UDP tunnel connecting from local port 15000 to IPv4 addresss 127.0.0.1 on port 15001
Source NIO listener thread for fadc32a2-70c4-45fe-b49b-8748fd660bbf-7 has started
Destination NIO listener thread for fadc32a2-70c4-45fe-b49b-8748fd660bbf-7 has started
```
I can ping a 3725 through the tap interface.
However, I cannot ping the NX_OSv_9k_Spine_31 just behind it. It used to work without issue before.

The ubridge.log related to the dynamips node contains:
```
uBridge version 0.9.13 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 127.0.0.1 port 51005).
UDP tunnel connecting from local port 15003 to IPv4 addresss 127.0.0.1 on port 15002
UDP tunnel connecting from local port 15001 to IPv4 addresss 127.0.0.1 on port 15000
Destination NIO listener thread for DYNAMIPS-15002-15003 has started
Source NIO listener thread for DYNAMIPS-15002-15003 has started
UDP tunnel connecting from local port 15009 to IPv4 addresss 127.0.0.1 on port 15008
UDP tunnel connecting from local port 15006 to IPv4 addresss 127.0.0.1 on port 15007
Destination NIO listener thread for DYNAMIPS-15008-15009 has started
Source NIO listener thread for DYNAMIPS-15008-15009 has started
UDP tunnel connecting from local port 15013 to IPv4 addresss 127.0.0.1 on port 15012
UDP tunnel connecting from local port 15010 to IPv4 addresss 127.0.0.1 on port 15011
Source NIO listener thread for DYNAMIPS-15012-15013 has started
Destination NIO listener thread for DYNAMIPS-15012-15013 has started
```
The ubridge.log related to the NX_OSv_9k_Spine_31 node contains: 
```
uBridge version 0.9.13 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 127.0.0.1 port 45417).
UDP tunnel connecting from local port 15017 to IPv4 addresss 127.0.0.1 on port 15016
UDP tunnel connecting from local port 15007 to IPv4 addresss 127.0.0.1 on port 15006
UDP tunnel connecting from local port 15019 to IPv4 addresss 127.0.0.1 on port 15018
UDP tunnel connecting from local port 15014 to IPv4 addresss 127.0.0.1 on port 15015
Source NIO listener thread for QEMU-8d01119a-0adc-41bc-950b-c5639db7708c-0 has started
Destination NIO listener thread for QEMU-8d01119a-0adc-41bc-950b-c5639db7708c-0 has started
Source NIO listener thread for QEMU-8d01119a-0adc-41bc-950b-c5639db7708c-1 has started
Destination NIO listener thread for QEMU-8d01119a-0adc-41bc-950b-c5639db7708c-1 has started
```

**Comment by grossmj** [comment]
I understand your topology is something like this: NX_OSv_9k_Spine_31 <--> c3725 <--> Cloud (TAP)

So you can ping from your Linux terminal to the c3725 and vice-versa but not NX_OSv_9k_Spine_31. I would assume something is wrong on c3725 or your Linux doesn't where to route packets to reach the node behind c3725.

**Comment by jean-christophe-manciot** [comment]
My bad, there was a subnet mask discrepancy..
