### ISSUE TITLE
releasing add a link

### ISSUE THREAD

**Issue by mikolar0** [GNS3/gns3-gui#235]
After add a link is chosen, right mouse could release it 
Regards
Robert

**Comment by grossmj** [comment]
Hi Robert,

You can release it with a right click on the drawing area (on the blank part).

**Comment by mikolar0** [comment]
Hi Jeremy.
Sorry for that. Are you sure ? Clicking on blank part of project, nothing happens Ubuntu and Windows 1.3.0 rc1, A cursor does not change. I have a cross cursor after add a link has been chosen, right click does not change it to arrow.
Thanks 
Robert

**Comment by grossmj** [comment]
Hey Robert,

You are right, this only happen when you start linking a node. I'll implement this soon.
