### ISSUE TITLE
qemu + spice doesn't work without IPv4

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2352]
Hi

If we have not IP address, we can not start qemu VM with spice access  : 
> getaddrinfo(0.0.0.0,5900): Address family for hostname not supported

On this link : [bugs.launchpad](https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1492621), they suggest to use "::1"

Can you configure GNS3 to use "::1" instead "0.0.0.0" (if you detect IPv6 for example) ?

**Comment by grossmj** [comment]
What is your host binding and did you set "Allow console connections to any local IP address" in the preferences?

![allow_console_connections](https://user-images.githubusercontent.com/4752614/33629548-0e568894-d9ca-11e7-9fd3-ab1cf067b8d7.png)

**Comment by Raizo62** [comment]
Yes, "Allow console connections to any local IP address" is enabled.
But, if i disabled it, i have always the error message.

**Comment by grossmj** [comment]
Ok, what is your host binding setting?

**Comment by Raizo62** [comment]
Host binding : 127.0.0.1

**Comment by grossmj** [comment]
Please, can you start python3 on the command line and type the following lines?

```
import socket
socket.getaddrinfo("0.0.0.0", 0, proto=socket.IPPROTO_TCP)
```

Let me know what you see after.

Thanks.

**Comment by Raizo62** [comment]
```
user@raizo:~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo("0.0.0.0", 0, proto=socket.IPPROTO_TCP)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0))]
```

**Comment by grossmj** [comment]
Do you have the same issue when using the VNC console?

**Comment by grossmj** [comment]
I have fixed the Qemu + SPICE issue with https://github.com/GNS3/gns3-server/commit/3a1ba8f42d51469b6ae669a278afb7644b5794a9

**Comment by Raizo62** [comment]
> Do you have the same issue when using the VNC console?

No. I think that it a bug in the lib of spice, not in GNS3.

> I have fixed the Qemu + SPICE issue with GNS3/gns3-server@3a1ba8f

I will test

**Comment by Raizo62** [comment]
> I have fixed the Qemu + SPICE issue with GNS3/gns3-server@3a1ba8f

I have tested : it works. Thanks :-)

**Comment by grossmj** [comment]
No wories :+1:
