### ISSUE TITLE
REQUEST : options for spice with qemu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2355]
Hi

Why you don't add automatically to Qemu VMs the options to use spice when we choose it :

- to  use screen/mouse : 
`-device virtio-serial -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0`

- to use shared folder : 
`-chardev spiceport,name=org.spice-space.webdav.0,id=charchannel0 -device virtserialport,chardev=charchannel0,id=channel0,name=org.spice-space.webdav.0`

**Comment by grossmj** [comment]
I am not sure I understand, do you want there settings to be automatically added when selecting the SPICE option?

**Comment by Raizo62** [comment]
Yes. If we choose Spice for a VM, GNS3 adds automatically theses options  to qemu command when the VM is started.

SPICE is really usefull when we install [spice](https://www.spice-space.org/download.html) on the Guest, isn't it ? But, then, we need these options to use thes functionnality.

(Be careful, i am a beginner with qemu)

**Comment by Raizo62** [comment]
Why we use SPICE (instead vnc) if we don't have theses options ?

**Comment by grossmj** [comment]
SPICE is usually considered faster than VNC. I agree we should add these options but I am afraid they break something and I don't want that, especially we won't have time to test this well enough before we release 2.1.1

**Comment by cioby23** [comment]
These 2 options are useful for images that have GUI enabled but they require the guest to have the spice guest tools installed, so I think they can be added as options to be enabled or disabled since enabling them on images which have only shell access won't have any benefit.

**Comment by grossmj** [comment]
I've added a new console type (spice+agent) which adds the command line options stated in https://github.com/GNS3/gns3-gui/issues/2355#issue-279657016
