### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by amin-abouee** [GNS3/gns3-gui#2357]
Hi, 
I installed new GNS3 3.2.1 on my mac. When I want to run gns3 in application, I am getting unexpectedly error. When I try to open it via terminal, I am getting "LSOpenURLsWithRole() failed with error -10810 for the file /Applications/GNS3.app.". 

OS: MacOS High Sierra 10.13.2
Libs: Python 3.6.3 Qt 5.9.2 and PyQt 5.9.1.
Could you please help me and tell me how can I fix this problem?

**Comment by grossmj** [comment]
Maybe related to https://github.com/GNS3/gns3-gui/issues/2317

**Comment by grossmj** [comment]
Indeed I can reproduce it, this is due to #2317.
