### ISSUE TITLE
GNS3 overwrites persistent Docker volumes

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2358]
https://www.gns3.com/qa/gns3-overwrites-persistent-docke

Verified it, same issue in my configuration (latest GNS3 2.1)

I even got an idea, why that happens:

In https://github.com/GNS3/gns3-server/blob/master/gns3server/compute/docker/resources/init.sh line 38 it checks, if it's the first mount. If yes, it saves the original content of the directory into the volume directory within the GNS3 project. Then this volume directory is mounted into the docker directory.

The first mount check is done, by checking if the volume directory is empty. But in this case the etc directory in the GNS3 project is initially not empty, it already contains the network configuration within etc/network. So the original /etc contents is not saved, the subsequent mount uses the almost empty etc directory to replace the /etc in the docker container.

So what's needed is a better indicator, that it's the first mount. The only idea I got is to check the existence of a special file.

**Comment by ehlers** [comment]
@AJNOURI Thanks for updating the GNS3.com discussion. I won't comment there, I closed my account on GNS3.com.

My tests show a different result:

Your original Dockerfile:

```
FROM alpine
RUN echo "data" > /etc/this_file_should_be_here
VOLUME /etc/]
ENTRYPOINT ["sh"]
```

It sort of works, because you use the volume `/etc/]`, you see that `]` directory in your listing of /etc. This does NOT create a persistent `/etc`, only a persistent `etc/]`. If I modify the Dockerfile to `VOLUME /etc/` the bug hits again (at least in my installation).

**Comment by ehlers** [comment]
I've thought about it and noticed, that we already have a special file, that indicated if it's the first mount or not. The file `.gns3_perm` is absent on the first mount, but will be created during the shutdown of the first run. So I changed init.sh to check that file. To be on the save side, it will be created afterwards. A later check of the existence of `.gns3_perms` is no longer necessary and was removed.

But that doesn't handle a special case, `/etc/network` should not be copied on the first mount, the contents of the project file system should always overwrite the contents of the docker image, even on first mount. To ensure that, I've created a .gns3_perm file in /etc/network on the project file system.

Here my changes: 

```
diff --git a/gns3server/compute/docker/docker_vm.py b/gns3server/compute/docker/docker_vm.py
index a059af78..4ac9e21d 100644
--- a/gns3server/compute/docker/docker_vm.py
+++ b/gns3server/compute/docker/docker_vm.py
@@ -236,6 +236,7 @@ class DockerVM(BaseNode):
         """
         path = os.path.join(self.working_dir, "etc", "network")
         os.makedirs(path, exist_ok=True)
+        open(os.path.join(path, ".gns3_perms"), 'a').close()
         os.makedirs(os.path.join(path, "if-up.d"), exist_ok=True)
         os.makedirs(os.path.join(path, "if-down.d"), exist_ok=True)
         os.makedirs(os.path.join(path, "if-pre-up.d"), exist_ok=True)
diff --git a/gns3server/compute/docker/resources/init.sh b/gns3server/compute/docker/resources/init.sh
index 7aa862f8..ee98bebd 100755
--- a/gns3server/compute/docker/resources/init.sh
+++ b/gns3server/compute/docker/resources/init.sh
@@ -35,17 +35,17 @@ do
     mkdir -p "$i"

     # Copy original files if destination is empty (first start)
-    [ "$(ls -A "/gns3volumes$i")" ] || cp -a "$i/." "/gns3volumes$i"
+    if [ ! -f "/gns3volumes$i/.gns3_perms" ]; then
+        cp -a "$i/." "/gns3volumes$i"
+        touch "/gns3volumes$i/.gns3_perms"
+    fi

     mount --bind "/gns3volumes$i" "$i"
-    if [ -f "$i/.gns3_perms" ]
-    then
-        while IFS=: read PERMS OWNER GROUP FILE
-        do
-            [ -L "$FILE" ] || chmod "$PERMS" "$FILE"
-            chown -h "${OWNER}:${GROUP}" "$FILE"
-        done < "$i/.gns3_perms"
-    fi
+    while IFS=: read PERMS OWNER GROUP FILE
+    do
+        [ -L "$FILE" ] || chmod "$PERMS" "$FILE"
+        chown -h "${OWNER}:${GROUP}" "$FILE"
+    done < "$i/.gns3_perms"
 done


```

**Comment by grossmj** [comment]
Thanks for the patch! :+1:

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/630afc54695e6941978524a3e4358fd5b1434c0a
