### ISSUE TITLE
Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)

### ISSUE THREAD

**Issue by 404Ghost99** [GNS3/gns3-gui#2360]
hi, i'm using Ubuntu 16.04 LTS and running gns3 version 2.1.0 and running on local server
my problem is when i was starting configure internet using internet appliance > https://docs.gns3.com/appliances/internet.html the appieance is successfully installed on my gns3, but when i start it i got this error messages like this:

=> QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name Internet -m 64M -smp cpus=1 -enable-kvm -boot order=c -drive 'file=/home/xxx/GNS3/projects/Tested Connect to Internet/project-files/qemu/be7ee282-f95a-41cf-9724-7d336f6ee889/hda_disk.qcow2,if=ide,index=0,media=disk' -uuid be7ee282-f95a-41cf-9724-7d336f6ee889 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:33239,server,nowait -net none -device e1000,mac=00:74:XX:XX:XX:XX,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,netdev=internet0 -netdev vde,sock=/var/run/vde2/qemu0.ctl,id=internet0 -nographic

Execution log:
qemu-system-i386: -netdev vde,sock=/var/run/vde2/qemu0.ctl,id=internet0: Parameter 'type' expects a netdev backend type

Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)

i already restart my gns3 and qemu but nothing, help me please.

XX mean a censored :smile:

**Comment by 404Ghost99** [comment]
actually i have been successful to connect my device to the internet, i'm using cloud nat
but i'm still confuse and curious why i can't using internet appliance.. :smile:

**Comment by grossmj** [comment]
Correct, the Internet appliance has been replace by the cloud NAT :+1: I am going to delete this appliance from the marketplace.

**Comment by givememanyfood** [comment]
same mistake

**Comment by grossmj** [comment]
Please open a new issue with detailed information. Thanks.
