### ISSUE TITLE
BUG : options of Qemu and quotes

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2371]
Hi

I create a new project with a quote in the name (untitled'1), 

In "Additionnal settings" of QEmu template, i add these options : 
`-smbios type=1,manufacturer='%vm-name%' -smbios type=2,manufacturer='%project-path%'
`

I add this device on the topology

When i start it, i have this error message : 
 ```
error while starting Debian-1: Invalid additional options: -smbios type=1,manufacturer='Debian-1' -smbios type=2,manufacturer='/home/user/projects/untitled'1' error No closing quotation
Invalid additional options: -smbios type=1,manufacturer='Debian-1' -smbios type=2,manufacturer='/home/user/projects/untitled'1' error No closing quotation
```
I have the same error if only the name of VM contains quote (Debian'1)

**Comment by grossmj** [comment]
I added this https://github.com/GNS3/gns3-server/commit/79bca29b9329941cc54577c98ad386d1b1269b62

Then it should be fine if you use `-smbios type=1,manufacturer=%vm-name% -smbios type=2,manufacturer=%project-path%`

**Comment by grossmj** [comment]
Don't use ", GNS3 will do it for you.

**Comment by Raizo62** [comment]
I don't use " or ', but my students do it :-(

Does it work if you escape these symbole ?

**Comment by grossmj** [comment]
I added escaping for double quotes. This should be alright now: https://github.com/GNS3/gns3-server/commit/23c63bbd4d134d508c8ec04417125c9eaed21f00

**Comment by grossmj** [comment]
Please close if this is good on your side. Thanks! :+1:

**Comment by Raizo62** [comment]
i have a problem (perhaps because i have manually patched the code to test)

Now, i can not start telnet console on QEmu VM with " : Debian"-2

**Comment by Raizo62** [comment]
Perhaps, an other soluce to escape " is to remove " ?

**Comment by Raizo62** [comment]
No, the error of console is not on GNS3

**Comment by Raizo62** [comment]
the problem is with parameter (%d) in "console setting" / "Console application command for telnet"

For VirtualBox VM, les quotes in the name are they removed ?

**Comment by grossmj** [comment]
This should work well now.
