### ISSUE TITLE
Couldnot pass DHCP ip form layer3 switch to client.

### ISSUE THREAD

**Issue by gcngov** [GNS3/gns3-gui#2375]
i have configure my network very simple to try gns3 to use layer 3 switch to pass DHCP ip through layer 3 switch to client.
please help guys.

my running config of router 3725:
![screenshot from 2017-12-23 10-08-38](https://user-images.githubusercontent.com/18734547/34316901-ce0cd3a2-e7c9-11e7-95c8-6a5a8271866b.png)
![screenshot from 2017-12-23 10-10-33](https://user-images.githubusercontent.com/18734547/34316902-ce51aee6-e7c9-11e7-8dda-b6d491c79ee1.png)
![screenshot from 2017-12-23 10-11-28](https://user-images.githubusercontent.com/18734547/34316903-ce91852a-e7c9-11e7-8604-087bb3ffa5ff.png)
![screenshot from 2017-12-23 10-11-42](https://user-images.githubusercontent.com/18734547/34316904-ced30cfc-e7c9-11e7-8b09-88dad4d7512f.png)

**Comment by sairuscz** [comment]
Hi @gcngov , this does not appear to be a GNS3 related issue. Your R1 router is missing a DHCP pool and even the sub-interface for VLAN10.

In the future, please post similar issues in  appropriate threads on the GNS3.com forum. Many more will be able to help you find your problem there.

For now, just run the below commands on your router R1 and your VPC client should then receive IP address. It should also be able to ping the L3  switch (10.20.222.2) and R1 (10.20.222.1).

R1:

R1(config)#ip dhcp pool POOL10
R1(dhcp-config)#network 10.20.222.0 255.255.255.0
R1(dhcp-config)#default-router 10.20.222.1
R1(dhcp-config)#exit
R1(config)#int f0/0
R1(config-if)#no shut
R1(config)#int f0/0.10
R1(config-subif)#encapsulation dot1Q 10
R1(config-subif)#ip address 10.20.222.1 255.255.255.0
R1(config-subif)#end


If you are certain your configuration is correct, please post packet captures from both the links. You can use "bootp" filter in Wireshark to see only DHCP traffic.

**Comment by grossmj** [comment]
@sairuscz Thanks for helping resolve this.
@gcngov Can you check that?

**Comment by grossmj** [comment]
Please re-open if there is still a problem.
