### ISSUE TITLE
GNS3 does not allow to have the projects with the same name

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#2380]
Why can't we have the projects with the same name if uuid is different?

**Comment by sairuscz** [comment]
How will you then distinguish which project you want to open when using the "Open recent project" option on a remote server? The GNS3 GUI only shows the project names, not the UUIDs.

**Comment by dmfigol** [comment]
GNS3 GUI shows the path to the lab in the **Projects library**.
People usually know what projects are recent for them. If it is still a concern, path to the lab can be included together with the name.

**Comment by grossmj** [comment]
There is definitely some improvement we can do here.

**Comment by grossmj** [comment]
Now you should be able to create projects with the same name provided they are in different locations.
