### ISSUE TITLE
[Linux] Feature request to change the default virtual size of a qemu disk image

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2382]
It seems that each time a qemu node is created, a disk image is allocated with a default virtual size of 8.0 G.
I have found a situation where that size is not enough, considering the complex way the disk is partitioned by the vendor (Cisco).
It happens with the last NX-OSv 9k 7.0(3)I7(1) when I try to upload & install all MTX files available in https://devhub.cisco.com/artifactory/open-nxos-agents/7.0-3-I7-1/x86_64/.
The error message ```[Errno 28] No space left on device``` appears for the last 3 MTX when using ```yum localinstall -y /bootflash/{{ item }}```, where item matches the last 3 rpms.

I know that this should not happen with 8 G, but the filesystem is partitioned in such a strange way and I would not mess with the partition scheme.

My proposal is to add the option to change the default disk image virtual size of 8.0 G, just below the existing options for each HDX in the HDD tab:
```
HDA (Primary Master)
- Disk image: ...
- Disk interface: ...
- Disk Size: x.y GB
```
and the same for each remaining HD.

**Comment by grossmj** [comment]
You can already create virtual disks and select a size by clicking on the create button in the Qemu VM preferences. However, I think you must be talking about the default disk created for you based whatever image (backing file) you use to create a new Qemu VM template.

The default disk size is based on this backing file size (here it would be the NX-OSv 9k 7.0(3)I7(1).qcow2 file). 

When GNS3 creates a node based on a VM template, it uses the configured image to create a linked clone virtual disk using this command: `qemu-img create -o backing_file=<path_to_image> -f qcow2 hda_disk.qcow2`. Checking the hda_disk.qcow2 file size and you will see it is the same as the backing file size. You can see this information with `qemu-img info <file>`.

Apparently you can create a virtual disk bigger than the size of the backing file but I want to test that this doesn't create unexpected problems.

**Comment by grossmj** [comment]
I don't know if this is going to help. I ran a quick test with a 1G Linux Microcore image to create a 100G virtual disk based on it.

The disk size is good:

```
qemu-img info hda_disk.qcow2 
image: hda_disk.qcow2
file format: qcow2
virtual size: 100G (107374182400 bytes)
```

and it recognised when booting the VM:

```
sd 0:0:0:0: [sda] 209715200 512-byte logical blocks: (107 GB/100 GiB)
```

However the partition must be extended to take advantage of the free space. Did you plan to do this NX-OSv 9k?

```
tc@box:/$ df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                   51.2M     11.0M     40.1M  22% /
tmpfs                    28.4M         0     28.4M   0% /dev/shm
/dev/sda1               984.3M     14.6M    919.7M   2% /mnt/sda1
/dev/loop0              468.0K    468.0K         0 100% /tmp/tcloop/netfilter-3.16.6-tinycore
/dev/loop1              232.0K    232.0K         0 100% /tmp/tcloop/ipv6-3.16.6-tinycore
/dev/loop2              448.0K    448.0K         0 100% /tmp/tcloop/iptables
/dev/loop3                2.1M      2.1M         0 100% /tmp/tcloop/db
/dev/loop4              472.0K    472.0K         0 100% /tmp/tcloop/iproute2
```

**Comment by grossmj** [comment]
I think implementing a button to resize a virtual disk could be useful.

**Comment by jean-christophe-manciot** [comment]
You're right about the virtual size of hda_disk.qcow2  being the same as the backing file virtual size:
```
# qemu-img info NX-OSv-9k-7.0.3.I7.1.qcow2
image: NX-OSv-9k-7.0.3.I7.1.qcow2
file format: qcow2
virtual size: 8.0G (8589934592 bytes)
```
Here is the partitioning scheme when the error ```[Errno 28] No space left on device``` arises during a rpm installation:
```
bash-4.2# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       8.9G  1.2G  7.7G  14% /
none             10M  1.5M  8.6M  15% /nxos/tmp
none             10M  1.6M  8.5M  16% /nxos/xlog
none             80M   13M   68M  16% /nxos/dme_logs
none             50M  252K   50M   1% /var/volatile/log
none            2.0M  8.0K  2.0M   1% /var/home
none            120M  324K  120M   1% /var/volatile/tmp
none            900M  260K  900M   1% /var/sysmgr
none            500M   68K  500M   1% /var/sysmgr/ftp
none             20M     0   20M   0% /var/sysmgr/srv_logs
none            2.0M     0  2.0M   0% /var/sysmgr/ftp/debug_logs
none            1.0G  397M  628M  39% /dev/shm
none            600M   61M  540M  11% /volatile
none            2.0M   56K  2.0M   3% /debug
none            1.0G  816K  1.0G   1% /mnt/ifc/cfg/db
/dev/loop1       58M   58M     0 100% /isan_lib_ro
/dev/loop2       67M   67M     0 100% /isan_bin_ro
/dev/loop3       30M   30M     0 100% /isan_bin_eth_ro
/dev/loop4       14M   14M     0 100% /isan_lib_eth_ro
/dev/loop5      2.5M  2.5M     0 100% /isan_lib_n9k_ro
/dev/loop6      128K  128K     0 100% /isan_bin_n9k_ro
unionfs         8.9G  1.2G  7.7G  14% /isan/bin
unionfs         8.9G  1.2G  7.7G  14% /isan/lib
/dev/sda4       3.3G  1.3G  2.1G  39% /bootflash
/dev/sda5       643M   19M  592M   3% /mnt/cfg/0
/dev/sda6       643M   19M  592M   3% /mnt/cfg/1
/dev/sda2       317M   11M  289M   4% /mnt/plog
none            400M  5.6M  395M   2% /var/sysmgr/startup-cfg
/dev/loop7       56M   56M     0 100% /lc_ro
/dev/loop8       80M   80M     0 100% /lc_n9k_ro
unionfs         8.9G  1.2G  7.7G  14% /lc
/dev/sda3       643M   19M  592M   3% /mnt/pss
/dev/sda7       2.4G   69M  2.2G   4% /logflash
/dev/loop9       57M   57M     0 100% /bootflash/.rpmstore/patching
```
There is plenty of space available in all partitions which may be involved with the operation, except for the loop device ```/dev/loop9``` which seems to have been undersized.

However, after further investigation, it appears that in this specific situation, resizing hda_disk is hardly useful since the loopback device is attached to a file located in the fourth partition out of 7:
```
bash-4.2# losetup /dev/loop9
/dev/loop9: [2052]:105670 (/bootflash/.rpmstore/.patching.img)
```
This means that using the added space at the end of hda_disk for sda4 would require moving all subsequent partitions which would be quite tedious to do & prone to errors.
Rather, resizing the img within /dev/sda4 seems to be the preferred action here.
Unfortunately, I don't know how to perform this without crashing the OS:
```
bash-4.2# dd if=/dev/zero bs=1MiB of=/bootflash/.rpmstore/.patching.img conv=notrunc oflag=append count=512
512+0 records in
512+0 records out
536870912 bytes (537 MB) copied, 3.46424 s, 155 MB/s
bash-4.2# losetup -c /dev/loop9
bash-4.2# resize2fs /dev/loop9
resize2fs 1.42.1 (17-Feb-2012)
Filesystem at /dev/loop9 is mounted on /bootflash/.rpmstore/patching; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 5
[  228.033395] [1515785823] BUG: soft lockup - CPU#1 stuck for 22s! [resize2fs:28409]
[  228.035182] [1515785823] Kernel panic - not syncing: softlockup: hung tasks
[  228.036099] [1515785823] Pid: 28409, comm: resize2fs Tainted: P           O 3.4.91-WR5.0.1.13_standard+ #1
...

Any suggestion?

**Comment by grossmj** [comment]
> Any suggestion?

Sorry no suggestion, maybe try to ask on the community forum.

**Comment by jean-christophe-manciot** [comment]
I have posted the issue on [CLN](https://learningnetwork.cisco.com/message/662924#662924).

**Comment by grossmj** [comment]
> I think implementing a button to resize a virtual disk could be useful.

It is implemented now.
