### ISSUE TITLE
Duplicate devices when snapshotting project with multiple users

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2383]
Hey guys, this is for 2.1.1 with remote server.

We have a project with several snapshots.  I have multiple users connected in and working on the same project.  If I restore to a different snapshot, the GUI creates additional copies of the same device when one of the other users interacts with the project (see picture), when starting all nodes only one copy of the node will start, and if it's not the first on the list the GUI thinks it's still shutdown and won't let the user access. If the user seeing multiple copies of the same device quits GNS3 and comes back to the project the device count is correct.

<img width="381" alt="screen shot 2018-01-08 at 5 08 48 pm" src="https://user-images.githubusercontent.com/22641788/34697431-abdb9c10-f498-11e7-9768-66d35f9ba2da.png">

**Comment by CapnCheapo** [comment]
I don't know if this is a related issue or separate, but another case where a snapshot restore will have the GUI make double icons for each device is if the links have been changed since the snapshot.  Again, restarting the GUI fixes the issue.

**Comment by grossmj** [comment]
I have tested and everything looks fixed (we have made a lot of changes in 2.2 and most likely fixed this as a result). Please comment back if you find any issue once we release version 2.2. Thanks!
