### ISSUE TITLE
Error Upgrading to VM 2.1.2

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2384]
Just tried to upgrade to the latest released GNS3 2.1.2 and the installation is requesting to uninstall the previous version of GNS3 VM.  Any work around?  Please see attached screenshot
![error upgrading to vm 2 1 2](https://user-images.githubusercontent.com/17806351/34704219-aed0a64a-f4c5-11e7-9ef5-e853826062ab.png)

**Comment by grossmj** [comment]
This is normal behavior, the installer is not asking to uninstall the GNS3 VM, only the previous version of the software. Move the VM out of `C:\Program Files\GNS3` if you put it there.
