### ISSUE TITLE
Error while creating node : virbr0 is missing. You need to install libvirt

### ISSUE THREAD

**Issue by randifilan** [GNS3/gns3-gui#2386]
Im trying to add NAT device in GNS3 2.1.1 but getting this error, so i cant create it. Please help.

**Comment by grossmj** [comment]
What error?

**Comment by cioby23** [comment]
You need to install the libvirt package corresponding your distribution or start the service if it’s not running. I assume you are using Linux.

**Comment by grossmj** [comment]
You must have libvirt running. To install it, for instance on Debian or Ubuntu type the following in a terminal: `sudo apt-get install libvirt-bin`

**Comment by DX37** [comment]
Sorry for opening, but why if libvirt installed and **started** already?

**Comment by dhanbha** [comment]
I am using the Windows PC and installed GNS3 2.1.11. I am also getting the same error while adding the NAT in GNS3. Please help how to resolve it.

Error while creating node: virbr0 is missing. You need to install libvirt

**Comment by dhanbha** [comment]
I was also facing this error. Please check below the video. This video has resolved the same issue.

https://www.youtube.com/watch?v=Dzs8arQ7_HI

**Comment by sami-befree** [comment]
@dhanbha 
The link to the video is broken, could you please help?
'm having the same issue on Windows 10

**Comment by dhanbha** [comment]
> @dhanbha
> The link to the video is broken, could you please help?
> 'm having the same issue on Windows 10

I have updated my last comment. Please click on that link now. You can also find same link below.

https://www.youtube.com/watch?v=r8YMDGHwBLI&feature=youtu.be

**Comment by ZodiaCKiLl3r** [comment]
install firewalld service and start it, after that restart the libvirtd service or restart the pc.
