### ISSUE TITLE
Installing GNS3 2.1.2 ask to uninstall 2.1.1 or cancel

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2387]
Windows 10 Prof 64bit
This seems new. Starting install of GNS3 2.1.2 when installation process notes GNS3 2.1.1 is installed and ask "Click 'OK' to remove the previous version or 'Cancel' to cancel this upgrade."  What if I normally have multiple version of GNS3 installed?

**Comment by grossmj** [comment]
Good point, I will look if we can have the uninstall optional.

**Comment by grossmj** [comment]
I have made the uninstall optional.
