### ISSUE TITLE
ESXi OVA hangs at "GNS3 VM Loading Screen"

### ISSUE THREAD

**Issue by mzarglis** [GNS3/gns3-gui#2388]
Can't get GNS3 ova to boot in esxi 6.5.0 Update 1 (Build 7388607), tried versions 2.0.0, 2.1.0, 2.1.1, 2.1.2 followed guide (https://docs.gns3.com/1hEoK0rmtdBRnMaUaVoMHUbYwtDAltXYShiMJUp1GMxk/index.html)  to the T no matter what the VM hangs at the loading screen with the lizards tongue all the way out. 

updated to the latest esxui v1.24.0 

Works fine in VMware Workstation 14.1.1

Any ideas?

**Comment by tegamax** [comment]
What is your hardware specification, are you running ESXI on a server or a workstation?
what resources did you allocate?

**Comment by mzarglis** [comment]
It's a server 
Dell PowerEdge R610 
2 x  Xeon L5640
24 gigs of ram

i allocated 6GB of ram and 6 cores to the GNS3 VM

**Comment by grossmj** [comment]
I have tested on a brand new install of ESXi 6.5, imported the OVA and I could start the GNS3 VM without any problem

Are you sure your have imported the correct OVA for ESXi (not VMware Workstation)?

Otherwise, please post on our community forum on gns3.com to get help from other users.
