### ISSUE TITLE
GNS3 2.1.2 won't start on Linux

### ISSUE THREAD

**Issue by Desposyni** [GNS3/gns3-gui#2389]
Since upgrading to GNS3 2.1.2, I can't run the application. I'm using Linux Mint 18.3, and it's been fine for all previous versions of GNS3.

UserName@HostName ~ $ gns3
Fatal Python error: Floating point exception

Current thread 0x00007f2444021700 (most recent call first):
File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/application.py", line 47 in __init__
File "/usr/share/gns3/gns3-gui/lib/python3.5/site-packages/gns3/main.py", line 230 in main
File "/usr/bin/gns3", line 9 in
Floating point exception (core dumped)
UserName@HostName ~ $

**Comment by grossmj** [comment]
Hi,

How have you installed GNS3?

**Comment by Desposyni** [comment]
Using the Ubuntu instructions from the GNS3 documentation.
Example:
sudo add-apt-repository ppa:gns3/ppa
sudo apt update
sudo apt install gns3-gui gns3-server gns3-iou

**Comment by grossmj** [comment]
I think the problem may come from the Qt library, which version is installed on your system?

```
$ apt list --installed | grep libqt5core

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libqt5core5a/artful,now 5.9.1+dfsg-10ubuntu1 amd64 [installed]
```

**Comment by Desposyni** [comment]
I'm a couple of versions behind. Is there a repo/ppa/flatpak I can use to keep the latest version of Qt?

apt list --installed | grep libqt5core
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
libqt5core5a/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed]

**Comment by grossmj** [comment]
You can try to install the latest version manually. Download from https://www.qt.io/download and follow the instruction there: http://sourcedigit.com/19858-how-to-install-qt-5-6-1-on-ubuntu-16-04/

**Comment by grossmj** [comment]
Excellent, thanks for the feedback, I will close this issue now. Please open a new issue if you get another problem.
