### ISSUE TITLE
IOS router: Change of image in preference is ignored

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#239]
GNS3: 1.3.0rc2, OS: Mac OS X V10.9.5

First I created an IOS router with image c3725-adventerprisek9-mz.124-25d.

The relevant part in gns3_gui.conf looks like this:
```
    "Dynamips": {
        "routers": [
            {
                "image": "c3725-adventerprisek9-mz.124-25d.image",
                "name": "c3725",
                "path": "/Users/behlers/GNS3/images/IOS/c3725-adventerprisek9-mz.124-25d.image",
            }
        ],
    },
```

When I change the image in the preference to c3725-adventerprisek9-mz.124-15.T14 the preference shows the changed IOS image. But when I move this new template in a topology and start it, it runs the old image.

gns3_gui.conf  has different values in image and path:
```
    "Dynamips": {
        "routers": [
            {
                "image": "/Users/behlers/GNS3/images/IOS/c3725-adventerprisek9-mz.124-15.T14.image",
                "name": "c3725",
                "path": "/Users/behlers/GNS3/images/IOS/c3725-adventerprisek9-mz.124-25d.image",
            }
        ],
    },
```

**Comment by grossmj** [comment]
@ehlers 

This should work now. Let me know if it ok on your side.

Thanks,

**Comment by ehlers** [comment]
Looks good

**Comment by noplay** [comment]
Thanks for the feedback
