### ISSUE TITLE
Bug with "Base MAC" and cloned QEmu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2392]
Hi

I wanted  that my DHCP Server gives an IP to my QEmu VM with a little lease time. Then i wanted to give an specific "Organisationally Identifier" to the network card of QEmu.

I have use "BASE MAC" (Of Network Setting). For example : "AA:BB:CC:00:00:00"

If i use an device with 6 network interfaces, i have : 

- aa:bb:cc:00:00:00
- aa:bb:cc:00:00:01
- aa:bb:cc:00:00:02
- aa:bb:cc:00:00:03
- aa:bb:cc:00:00:04
- aa:bb:cc:00:00:05

(too bad, it is a little too lineare to be realistic)

But if i put a second device with 6 network interfaces, i have the same : 

- aa:bb:cc:00:00:00
- aa:bb:cc:00:00:01
- aa:bb:cc:00:00:02
- aa:bb:cc:00:00:03
- aa:bb:cc:00:00:04
- aa:bb:cc:00:00:05

It is very problematic.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/7ded71142fba2411f34cc68df46366630718ba9f
