### ISSUE TITLE
Error downloading file

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#2398]
I get the following errors when opening Preferences:

Error while downloading file: /symbols/%3A/symbols/router.svg/raw
Error while downloading file: /symbols/%3A/symbols/router.svg/raw
Error while downloading file: /symbols/%3A/symbols/multilayer_switch.svg/raw
Error while downloading file: /symbols/%3A/symbols/multilayer_switch.svg/raw
Error while downloading file: /symbols/%3A/symbols/qemu_guest.svg/raw
Error while downloading file: /symbols/%3A/symbols/qemu_guest.svg/raw
Error while downloading file: /symbols/%3A/symbols/router_firewall.svg/raw
Error while downloading file: /symbols/%3A/symbols/router_firewall.svg/raw

$ uname -a
Darwin Adrians-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Tue Dec 19 11:20:50 PST 2017; root:xnu-4570.41.2~2/RELEASE_X86_64 x86_64

**Comment by grossmj** [comment]
Thanks, you will not see these messages in version 2.1.4
