### ISSUE TITLE
2.1.3 VMware fusion/Mac GNS3 VM not in the list/busted

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#2399]
Installed GNS3 VM in VMware Fusion is not in the GNS3 GUI. Failure to connect to local server...See photos.

![screen shot 2018-01-21 at 9 24 37 pm](https://user-images.githubusercontent.com/3232190/35193097-fda7bae8-fef1-11e7-978e-f0376692ff41.png)
![screen shot 2018-01-21 at 9 22 01 pm](https://user-images.githubusercontent.com/3232190/35193162-030e94e2-fef3-11e7-87d8-135e92f730c9.png)

**Comment by grossmj** [comment]
This error which was due to a packaging problem has been fixed very recently. Please can you try download & install again? Thanks!

**Comment by vader75** [comment]
Yep naughty GNS3 packing :-). Works now.
