### ISSUE TITLE
GNS3 2.1.3 Server+Gui not connecting the VMWare ESXi VM after update

### ISSUE THREAD

**Issue by aredey** [GNS3/gns3-gui#2402]
I have a GNS3 VM running in VMWare ESXi and a Server+GUI running in (vanilla) Ubuntu Mate 16.04. Version 2.1.? was running flawlessly then [both updated to v2.1.2](https://gns3.com/qa/gns3-vm-2-1-1-to-2-1-2-upgrade-f) (all sorts of problems occurred) then up to the current v2.1.3 versions. The GUI/Server only configuration seems to be running as expected but (Server+GUI) + VM produces the following error (in the GNS3 doctor in the linux box):
"WARNING The vmrun executable could not be found, VMware VMs cannot be used" 

I have removed and then reinstalled the GNS3 GUI and the Server on Ubuntu as suggested in the GNS3 website announcement but the issue persist (vmrun is missing on the server). Is this a bug? Can I copy a working (earlier) version somewhere? Where shall I get a copy (and should I hack it?)? 

Searched for "vmrun" and the error essage in here and in the the general web, no luck so far. Do you have any suggestion for how to fix it?

Many thanks,

**Comment by grossmj** [comment]
On Linux, GNS3 will look into $PATH to find vmrun. What do you have if you type `whereis vmrun` in a terminal?

**Comment by grossmj** [comment]
@aredey ping

**Comment by aredey** [comment]
user@laptop:~$ whereis vmrun
vmrun:

user@laptop:~$ which vmrun

user@laptop:~$ echo $PATH
/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

#I'm even trying to brute force find it:
user@laptop:~$ find / 2>/dev/null | egrep 'vmrun'
user@laptop:~$ 

I first upgraded 2.1.1 (which worked perfectly) to 2.1.2. This broke as per my link to the GNS3 blog link. Then tried to upgrade 2.1.2 to 2.1.3, And this is where I am now.
Is this a standalone file, where can I find a copy to drop in there somewhere manually?

**Comment by grossmj** [comment]
Actually you only need vmrun to run the GNS3 VM locally inside VMware or to add VMware VMs to your projects. I think you can disregard this message.

To configure the GUI to use a remote GNS3 VM, you should have something like this in the preferences:

![remote_gns3_vm_01](https://user-images.githubusercontent.com/4752614/35673982-18951604-077e-11e8-8331-bc8b6d19ab1d.png)

![remote_gns3_vm_02](https://user-images.githubusercontent.com/4752614/35673981-1864aa5a-077e-11e8-9f8f-4be703d936c8.png)

**Comment by aredey** [comment]
Ah, the top picture solved the issue: the ESXi uses DHCP and the router changed the IP address. I originally looked at the GNS3 Doctor for guidance and this seemed to be the issue
![screenshot from 2018-02-01 14-35-52](https://user-images.githubusercontent.com/16439806/35683999-75e6b46e-075d-11e8-815d-d8707f783325.png)

Many thanks for the help, much apreciated!

**Comment by grossmj** [comment]
Perfect :+1:

**Comment by deorajd** [comment]
Hi Grossmj,
I have been struggling for the past three days after upgrading to VM Workstation Pro 14, GNS3 2.1.3 and GNS3 VM 2.1.3. I really need some help getting this contraption to work. First, it seems like the gns3 VM has some issues since it is always grey in the server summary section as shown in the snap.
![image](https://user-images.githubusercontent.com/36138488/35782087-598516d0-09c9-11e8-9c01-e084dc6979a1.png)
How can i resolve this. I cant get to add anything using the gns3 VM.
