### ISSUE TITLE
BUG/Question? QEmu : option "linked base VM"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2403]
Hi

Perhaps that i don't understand something

I create a harddisk with the command "qemu-img create" (in /media/usb0/)

In GNS3, i create a template QEmu where : 
- I use my own harddisk file
- I uncheck "Use as a linked base VM". I hope that modifications are applied on my own harddisk

But, when i use a device of the template, my own harddisk file is not modified. GNS3 has modified a qcow file in the project.

**Comment by grossmj** [comment]
Have you created the template from scratch or added your hard disk to an existing template?

**Comment by Raizo62** [comment]
I have created the template for this VM.

I don't know if the info is important : 
- the path for my binary images is "/opt/raizo/user/OS" (and the path of the harddisk is  /media/usb0/)
- I don't copy the file in the folder of my binary images

**Comment by Raizo62** [comment]
I can't reproduce this bug.
Sorry for inconvenience.
