### ISSUE TITLE
[2.1] Change of linked base VM doesn't work with templates migrated from 2.0

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2413]
GNS3 version 2.1.4dev1 on Darwin (64-bit) with Python 3.6.4 Qt 5.9.3 and PyQt 5.9.2

There are some reports about the linked clone feature, that can't be disabled in 2.1, the latest one is https://www.gns3.com/qa/-linked-base-vm-stopped-work . Also two GitHub issues are open for this (#2403 and #2339). So I did some investigation.

I modified an already existing QEMU template and disabled the "Linked base VM" setting, then moved this template into a new project, started it und saw, that the VM still uses a linked base VM. So indeed there is an issue.

After some investigation I found, that the template has two entries for this setting, "linked_base" and "linked_clone". The linked_base setting is a leftover from 2.0, 2.1 uses only linked_clone setting. But it doesn't delete the old setting, so both are stored in gns3_gui.conf and gns3_controller.conf.

```
            {
                .
                .
                "linked_base": true,
                "linked_clone": false,
                "mac_address": null,
                "name": "NETem",
                "node_type": "qemu",
                .
                .
            }
```

The issue is, that the server prefers the old linked_base entries over the new linked_clone, see  https://github.com/GNS3/gns3-server/blob/master/gns3server/controller/appliance.py#L44. So changes to linked_clone doesn't change anything, when using a template migrated from 2.0 with the linked_base setting.

Therefore I removed all lines containing "linked_base" from gns3_gui.conf and gns3_controller.conf. Now changing the "Linked base VM" setting is working fine. Also the old "linked_base" setting doesn't show up again.

**Comment by grossmj** [comment]
This should fix the problem: https://github.com/GNS3/gns3-server/commit/abbe3d3a31dba3646d678d98cf387afc9f6683f2

**Comment by ehlers** [comment]
Works fine with the config files containing both linked_base and linked_clone. In the long run it might be nice to get rid of linked_base in the migrated templates.

**Comment by ehlers** [comment]
The fix is not that simple. While https://github.com/GNS3/gns3-server/commit/abbe3d3a31dba3646d678d98cf387afc9f6683f2 fixes the issue, I've initially reported, it doesn't work in the migration phase from 2.0 to 2.1.

When 2.1 starts with the config files from 2.0, it doesn't copy the linked_base settings to linked_clone. Instead it created new linked_clone settings initialized with the default values (true for QEMU, false otherwise). As the GUI shows the setting of linked_clone in the template view, the old setting of linked_base seems lost. But as previously the (now hidden) linked_base setting was prioritized, it still worked when starting a VM. So previously the migration results in a an inconsistent state. Now with the changes the migration simply ignores the previous linked_base setting. Both is not good.

**Comment by grossmj** [comment]
@ehlers I was suspicious this would be that easy... Maybe the fix is to save the templates back to gns3_controller.conf once they have been migrated.

**Comment by ehlers** [comment]
I've tried to sort out all the different situations, when and in which version linked_base or linked_clone was used in templates and projects and how to migrate it. But after an hour I gave up. I used a text editor to clean up my templates (the projects seem clean) and I'm fine now in my installation.

**Comment by grossmj** [comment]
We will make changes in version 2.2 (which will have alpha and beta versions). This will be less risky.

**Comment by grossmj** [comment]
Will be fixed by https://github.com/GNS3/gns3-server/issues/1427

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/issues/1427
