### ISSUE TITLE
Force the cloud object to query the server for available interfaces every time the user tries to configure it

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2416]
If I add an interface to my GNS3 VM (via ESXI) and I bring that interface up it does not become available to existing clouds, already in the configuration. If I add a new cloud that one has the new interface listed

**Comment by grossmj** [comment]
I have added buttons to refresh the interfaces.

**Comment by 1001QAdotNET** [comment]
great thank you!
