### ISSUE TITLE
No GNS3 version 2 on Ubuntu 17.10

### ISSUE THREAD

**Issue by FrankAtGitHub1** [GNS3/gns3-gui#2417]
Hi there,

i'm having an issue, which was already reported as issue #2290.
This thread was closed, but i cannot install gns3 by doing the following, which was the solution to the other issue mentioned:

sudo add-apt-repository ppa:gns3/unstable   -> no problem
sudo apt-get update   -> done
sudo apt-get install gns3-gui   -> is not an option !

When doing sudo apt-get install gns -> hitting tab twice, i only see the following options:

gns3      gns3-iou  gnss-sdr 

gns3 though is the legacy version 0.86.

Did someone move the package from the unstable tree?
Any ideas on how to fix this?

I'm running:

Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

Thx!

**Comment by ziajka** [comment]
Hi @FrankAtGitHub1, please use stable branch:
sudo add-apt-repository ppa:gns3/ppa
Let us know if it helps.
Cheers,
Dominik

**Comment by FrankAtGitHub1** [comment]
Hi,

when adding ppa:gns3/ppa i may install the following:

gns3 -> this installs version 0.8.7, but i need a version < 2.x
gns3-iou -> i do not have iou images

So this does not help.

BR,

Frank

-------- Original Message --------

**Comment by ziajka** [comment]
Hi @FrankAtGitHub1,

Have you updated this repository after adding:

```
sudo add-apt-repository ppa:gns3/ppa
sudo apt-get update
```

Could you also send to us output of this command:

`grep "" /etc/apt/sources.list.d/*`

Many thanks!
Cheers,
Dominik

**Comment by FrankAtGitHub1** [comment]
Hi Dominik and all!

Yes, updated after adding the repo:
-> OK:5 http://ppa.launchpad.net/gns3/ppa/ubuntu artful InRelease

And here is the output you've requested:

##############################

grep "" /etc/apt/sources.list.d/*
/etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-artful.list:deb http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu artful main
/etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-artful.list:# deb-src http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu artful main
/etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-artful.list.save:deb http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu artful main
/etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-artful.list.save:# deb-src http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu artful main
/etc/apt/sources.list.d/gns3-ubuntu-ppa-artful.list:deb http://ppa.launchpad.net/gns3/ppa/ubuntu artful main
/etc/apt/sources.list.d/gns3-ubuntu-ppa-artful.list:# deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu artful main
/etc/apt/sources.list.d/gns3-ubuntu-ppa-xenial.list.distUpgrade:# deb http://ppa.launchpad.net/gns3/ppa/ubuntu zesty main # Bei Aktualisierung zu zesty deaktiviert -> this means, that it was deactivated, when upgraded to zesty
/etc/apt/sources.list.d/gns3-ubuntu-ppa-xenial.list.distUpgrade:# deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu zesty main # Bei Aktualisierung zu zesty deaktiviert -> this means, that it was deactivated, when upgraded to zesty
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list:deb http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list:# deb-src http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list.distUpgrade:# deb http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list.distUpgrade:# deb-src http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list.save:deb http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main
/etc/apt/sources.list.d/teejee2008-ubuntu-ppa-xenial.list.save:# deb-src http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial main

##############################

Thank you for your help, its really appreciated!

/Frank

-------- Original Message --------

**Comment by ziajka** [comment]
Hi Frank,
Thank you for the output.
May I ask you for another two commands results:

`lsb_release -a`
and 
`uname -a`

Thank you!

Cheers,
Dominik

**Comment by FrankAtGitHub1** [comment]
Hi Dominik,

shure, here you go:

#######################

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 17.10
Release: 17.10
Codename: artful

######################

uname -a
Linux Frank 4.13.0-35-generic #39-Ubuntu SMP Mon Feb 12 11:05:54 UTC 2018 i686 i686 i686 GNU/Linux

######################

Thanks again for your help!

Cheers,
Frank

-------- Original Message --------

**Comment by ziajka** [comment]
Thank you Frank.

And here we have the reason, Basically on 17.10 we don't support 32-bit architecture, only 64-bit. Version 32-bit is available on older versions of Ubuntu.

What I can say from myself that there are two options:
1) Upgrade to 64-bit (of course it can be hard and you may loose your data).
2) Build gns3 from sources:
https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html#h.gxybzkr97f48
But we cannot guarantee you that all features will be available, this is up to our dependencies. 

Kindest regards,
Dominik
