### ISSUE TITLE
Support for ARM64 packages on ppa

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-gui#2419]
Hi,

I was wondering what it would take to generate ARM64 packages for the ppa feed. I'm working on a environment where we use ARM64 KVM simulations with GNS3, and planning to deploy to ARM64 servers.

The folks from Works on ARM and packet can offer CI for testing the builds. If there is no objection for this, I can contribute the work to maintain the ARM64 packaging.

**Comment by grossmj** [comment]
We now have ARM packages for ubridge, dynamips, vpcs and the client pack.

However the GUI and the server will have to wait because https://github.com/GNS3/gns3-server/issues/970 was only fixed in version 3.0 (not yet released)
