### ISSUE TITLE
BUG : docker and Environnment variable

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2420]
Hi

I use the alpine docker image

In GNS3, i create a docker template with this alpine.
I use the default value, but for environnment variable, i write : 
```
MYSQL_HOST=localhost\n
MYSQL_USER=root\n
```
where **\n** is the keyboard enter key.

When i use the template, GNS3 says : 
`Error while creating node: Docker has returned an error: 500 invalid environment variable`

I think that the last **\n** is the problem

I ask an another question, because i don't know if it is a bug : is it good that the default port of docker template is 80 if i choose https as console type ?

**Comment by ziajka** [comment]
Question because it needs an investigation :)

**Comment by ziajka** [comment]
Solved: https://github.com/GNS3/gns3-server/commit/9e73ca66201940035512574cea5c1cc9699d505f

Console type should be fine.

**Comment by Raizo62** [comment]
And my other question ? I don't know if it is a bug and if i must open an issue ?

> I ask an another question, because i don't know if it is a bug : is it good that the default port of docker template is 80 if i choose https as console type ?

**Comment by ziajka** [comment]
Yes, this console type should be fine. Are you experiencing any issues with that?

**Comment by Raizo62** [comment]
Honestly, i didn't success to test it.... 
I believe that Firefox doesn't accept to connect to url "https://127.0.0.1:5000" who is not the name of certificat of SSL server.
But, if the docker VM have an https server, i suppose that it listen on the port 443. If GNS3 redirect to port 80, that doesn' work.
But I'm not sure I understand everything

**Comment by Raizo62** [comment]
Do you have a easy example to use https console of docker VM ?

**Comment by Raizo62** [comment]
Then, the default port for https console must be 443 and not 80 (as explain in the link)

**Comment by ziajka** [comment]
That's correct @Raizo62, being precise it can be 443 but also any other (it's possible to define it as you want, as long the docker image also is such configured). 443 port is just only by "standard". In theory you can also define 80, but of course it may confuse people. For browser it's only important that "https" is on the beginning.

**Comment by Raizo62** [comment]
That 's why i talk of **default** port ;-)
If you use "https" on the beginning, your browser uses also the port 443 (Not with GNS3 because you indicate the port).
As you say, you should use 443 as default port for https console to not confuse people, because it is the standard.

**Comment by Raizo62** [comment]
Otherwise, the default config of GNS3 doesn't work with standard config of server
