### ISSUE TITLE
GNS3 2.1.3 on ubuntu 16.04 check for a valid IOU license key

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2422]
GNS3 2.1.3 on Ubuntu 16.04 
It seems if the checkbox "Check for a valid IOU license key" is selected and the iourc file cannot be found or if a problem occurs with the generated iourc file then GNS3 will not start making it challenging/impossible to solve the problem without uninstalling/reinstalling GNS3. Have not tested this extensively so clearly could be a mistake of mine I have not identified.  Uninstalling/reinstalling does not appear to affect any configuration or project files so not the end of the world.
Using the ppa method of installing found in GNS3 docs "GNS3 Installation on Linux"

**Comment by grossmj** [comment]
@jtorri do you still have the issue in 2.2 beta 1?

**Comment by jtorri** [comment]
Seems fine now on version 2.2.0b1.  Please feel free to close this one.  Thanks!
