### ISSUE TITLE
GNS3 2.1.3 images not visible when added manually

### ISSUE THREAD

**Issue by nar4all** [GNS3/gns3-gui#2423]
Hi Team,

When i install the images locally by manual we are unable to see in the installed device list.

![gns3issue](https://user-images.githubusercontent.com/16225266/36070860-03b03fa8-0f2a-11e8-8bc9-828fcf6aa9dd.JPG)

we need to install only through wizard, but again sometimes image doesn't match with MD5

![image](https://user-images.githubusercontent.com/16225266/36070884-7a42d234-0f2a-11e8-9263-5cc3b4e6d719.png)

**Comment by ziajka** [comment]
Hi @nar4all,
Are you able to find in "installed appliances" this router by typing "c7200"?
Cheers,
Dominik

**Comment by nar4all** [comment]
No we don't see even if we manually search

**Comment by ziajka** [comment]
Hi @nar4all . It's fixed, also in the next release will be possibility to upload file with different MD5. v2.1.4 is planned in the beginning of March.

Cheers,
Dominik
