### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-gui#2424]
https://sentry.io/gns3/gns3-gui/issues/339436755/

```
RecursionError: maximum recursion depth exceeded

RecursionError: maximum recursion depth exceeded
```

**Comment by grossmj** [comment]
Let's see if the problem is still present in version 2.1.10. Upgrading Qt + fixing the lost connection issues may have solve this issue.
