### ISSUE TITLE
Error connect to VLAN interface port of Cloud 

### ISSUE THREAD

**Issue by rizalmhn** [GNS3/gns3-gui#2426]
Environtment
OS: Windows 10
GNS3: 2.1.3

Issue:
I've tried to connect vRouter on GNS3 to real network device use VLAN network interface. When the link connect to cloud on physical interface (e.g Ethernet2) with VLAN feature is disabled, the vRouter can connect to real network, but when the link connect to cloud on VLAN interface (e.g Ethernet2-VLAN36) the cloud port is down and shown error bellow

Error log:
unable to create NIO Ethernet for bridge '38aba9eb-2cf0-44ad-8d16-7eb2a918f779-3': uBridge version 0.9.13 running with WinPcap version 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Hypervisor TCP control server started (IP 192.168.114.38 port 56840).
UDP tunnel connecting from local port 10007 to IPv4 addresss 192.168.114.38 on port 10006
nio_ethernet_open: unable to open device '\Device\NPF_{48698646-7CDF-4225-9B86-AAE00092B64C}': Error opening adapter: The system cannot find the device specified. (20)

![img-1](https://user-images.githubusercontent.com/11828942/36134604-6e08769c-10b8-11e8-8217-2835093d137b.png)

![img-2](https://user-images.githubusercontent.com/11828942/36134626-8bafe55e-10b8-11e8-9432-5823a4dc230f.png)

![img-3](https://user-images.githubusercontent.com/11828942/36134640-b08eedb6-10b8-11e8-9281-d27428e9efd5.png)

![img-3 ](https://user-images.githubusercontent.com/11828942/36134911-41011ba2-10ba-11e8-9dc9-1f03bd512ff4.png)

**Comment by sairuscz** [comment]
@rizalmhn , most Windows NIC drivers do not work correctly with WinPcap. You will be lucky to find any new network card that will work without any bugs.

Additionally, WinPcap can transmit packet with a maximum size 1518bytes only. Therefore, uBridge will crash each time you send a dot1q encapsulated packet with payload larger than 1500 bytes. 

To work around it, add a virtual NIC adapter to your GNS3 VM, add it to a virtual bridge and then link your GNS3 cloud to the virtual bridge. Also do not forget to lower MTU to at least 1496bytes on all devices(both physical and virtual) that will be transmitting via the uBridge . This will allow you to transmit the extra 4 bytes consumed by dot1q tag.

Check my previous reports #1867 and #1921  for more details and workarounds.

**Comment by ziajka** [comment]
Thank you @rizalmhn for reporting and @sairuscz for clear explanation.
