### ISSUE TITLE
Cleanup of packet captures after stopped or project closed

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-gui#2427]
I'm using a GNS3 server (2.1.1) with some containers. If I start a packet capture on a link, if I stop or close the project, when I try to capture again wireshark shows me the previous captured packets and doesn't capture any further packets. Right now I have to login into the server and find all the pcap files and remove them to get it working again.

Not sure what the correct behavior should be, but since wireshark is already asking you to save the capture, I think should be safe to remove the pcap files upon stop of the capture or project closure.
Otherwise add an option to "reset" the capture?

**Comment by ziajka** [comment]
Thank you @ddompe for reporting this. We will investigate issue.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/38f458db7c0e5a193001803bfe54efde2c9efa90
