### ISSUE TITLE
GNS3 2.1.3 Remote Main Server - Unable move to select large amount of objects in topology

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2428]
I have a large topology with 80+ nodes running on a GNS3 VM configured as a remote main server. Whenever I select a large amount of objects (nodes, text, shapes) GNS3 client freezes and eventually shows a timeout error both in Windows 10 and Linux Mint 18.3.

When I then try to move the objects in the topology, I get another time out error. After closing the GNS3 client and reopening the topology again, some of the objects remain in the 'old' position while other objects reflect the 'new' position. 

Based on the debug output is seems as if GNS3 client sends and receives about 1000 events when I select only 10 nodes with some notes (screenshots below). Also notice that by selecting just 30 nodes in the topology, the GNS3 client generated 1MB event log ([GNS3_debug.txt](https://github.com/GNS3/gns3-gui/files/1725790/GNS3_debug.txt)).. I have not even moved anything around. 

Netstats also shows that GNS3 generates over 100 TCP sessions, most of which remain in WAIT state. 
[netstat.txt](https://github.com/GNS3/gns3-gui/files/1725829/netstat.txt)

Please note that I see the same problem even when the remote main server and GNS3 client run on the same physical machine. Also, I utilize only about 50% of RAM and CPU resources on my host machine. So, it does not appear to be network or recourse related issue.

Is there any way to improve the performance of larger typologies running on a remote main server?

![0946](https://user-images.githubusercontent.com/24818591/36230276-eac1c7d4-11a7-11e8-9c9c-b83195de28d0.jpg)
![0948](https://user-images.githubusercontent.com/24818591/36230277-ebd66904-11a7-11e8-8779-e2760a0d6ff4.jpg)
![0949](https://user-images.githubusercontent.com/24818591/36230281-edc92ae4-11a7-11e8-9986-ccd947f7a760.jpg)

Running GNS3 version 2.1.3 on Windows (64-bit) with Python 3.6.3 Qt 5.8.0 and PyQt 5.8.
CPU: 16-core Xeon
RAM: 192GB DDR4
HDD: 5xSSD RAID0

**Comment by grossmj** [comment]
Most likely due to the number of API calls when moving objects. We need to investigate this.

**Comment by grossmj** [comment]
I think this should have been fixed in version 2.2. Please comment back if this isn't the case.
