### ISSUE TITLE
IOU and "enable layer 1  keepalive message"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2431]
Hi

With IOU device, i tried to check "enable layer 1  keepalive message" option.

But, with this option, the L2 IOU show all interfaces as "down down" even plugged interfaces.

Must this option work ? This [issue of 2014 with iouyap ](https://github.com/GNS3/gns3-server/issues/14) says that "no"

If it doesn't work, do you must hide this functionnality ?

if it must work, then i believe there is a bug

**Comment by grossmj** [comment]
We left this option for experimental purpose, maybe we should indicate it on the GUI and documentation. 

https://github.com/GNS3/gns3-server/issues/14

**Comment by Raizo62** [comment]
In the GUI, it is indicated as "experimental", but a experimental functionality works a little ;-) is it the case ?
If not, perhaps change the message as "not yet functional" ?

**Comment by grossmj** [comment]
I agree, we should consider displaying "Not functional" or "Not working".

**Comment by grossmj** [comment]
I have changed it to "non-functional".
