### ISSUE TITLE
Release Notes of v2.1 outdated

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2432]
https://docs.gns3.com/release.html

**Comment by ziajka** [comment]
Thanks @ehlers, probably after SF migration. We will rebuild it.

**Comment by ehlers** [comment]
Rebuilding will quite likely not help. In https://github.com/GNS3/gns3-documentation-template/blob/master/theme/release.html version 2.1 is still not released. The document about v2.1 (<https://docs.gns3.com/1_xhTp3fAzIKfE6ujQ-P1_CCaKuhgbQblOT7uITr91qI/index.html>) seems to be in sync with the google docs document https://docs.google.com/document/d/1_xhTp3fAzIKfE6ujQ-P1_CCaKuhgbQblOT7uITr91qI/edit . Both are telling us, that v2.1 is in alpha stage.

**Comment by ziajka** [comment]
You're right. Let me fix it.

**Comment by ziajka** [comment]
Updated: https://github.com/GNS3/gns3-documentation-template/commit/1c21d409a505bb0d6da105073a70a5ab979b7c42?diff=unified

SF still has issue with SSH for web project so it will be updated a bit later on SF>
