### ISSUE TITLE
gns3 2.1.3 the link type is incorrect on iou --- (windows8.1 And Vmware VM)

### ISSUE THREAD

**Issue by tlsalex** [GNS3/gns3-gui#2440]
Switch(config)#interface gigabitEthernet 0/1

Switch(config-if)#no negotiation auto

Switch(config-if)#speed 1000

Switch(config-if)#duplex full 

Switch(config-if)#media-type rj45 

Switch(config-if)#do show interface g0/1
GigabitEthernet0/1 is up, line protocol is up (connected) 
  Hardware is iGbE, address is 0097.a415.1401 (bia 0097.a415.1401)
  MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec, 
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation ARPA, loopback not set
  Keepalive set (10 sec)
  Full Duplex, 1000Mbps, link type is force-up, media type is unknown media type -------- the type is unknow

Switch(config-if)#do show interface status

Port      Name               Status       Vlan       Duplex  Speed Type 
Gi0/0                        connected    1            auto   auto unknown
Gi0/1                        connected    1            auto   auto unknown             -------------- type is unknow
Gi0/2                        connected    1            auto   auto unknown
Gi0/3                        connected    1            auto   auto unknown
          
Switch(config-if)#do show spann vlan 1

VLAN0001
  Spanning tree enabled protocol rstp
  Root ID    Priority    32769
             Address     0097.a415.1400
             This bridge is the root
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

  Bridge ID  Priority    32769  (priority 32768 sys-id-ext 1)
             Address     0097.a415.1400
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec
             Aging Time  300 sec

Interface           Role Sts Cost      Prio.Nbr Type
------------------- ---- --- --------- -------- --------------------------------
Gi0/0               Desg FWD 4         128.1    Shr 
Gi0/1               Desg FWD 4         128.2    Shr                                           ------ it is share type , not p2p

**Comment by grossmj** [comment]
Unfortunately this comes from limitation with IOU itself and there is nothing we can do. Please consider using IOSv-L2.
