### ISSUE TITLE
runtime error - R6034

### ISSUE THREAD

**Issue by mimta** [GNS3/gns3-gui#2441]
Hi
I've done everythjing from remove all MVC++ (2008 - 2015) and re-install the GNS3 2.1.3 but still get that error!!!
also I installed latest MVC++ (2017) but nothing changed!!

any idea why?! or how can I fix it?!!!

I'm using windows 7 enterprise

error message attached!
![photo5812294884680379439](https://user-images.githubusercontent.com/12979893/36727035-b66de8ee-1bb3-11e8-9cef-9b08386602db.jpg)

Thanks

**Comment by grossmj** [comment]
@mimta, apparently you resolved that issue yourself, what was the problem?

**Comment by mimta** [comment]
@grossmj you have to 

1. remove all your MVC++ packages 
2. delete all folder/file on your "C:" drive from previous installation 
3. reboot your PC

- and let GNS3 install that actual library that work with it!!

Thanks
