### ISSUE TITLE
[Linux/2.1.3] Multiple Cisco nodes cannot be added to the topology or started

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2444]
Ubuntu 17.10
gns3 gui/server v2.1.3
qemu v2.11.0
python 3.6.4-1

The following Cisco nodes **cannot be added** to the topology without error:
- ASAv 9.8.2
- CSR 1000v 16.6.1
- IOSv 15.6.3
- IOSv L2 15.2-3-2017
- IOS-XRv 6.1.3

The following Cisco node **can be added to the topology but cannot be started** without error
-  NX-OSv 9k 7.0(3)I7(1) (cf. [other issue](https://github.com/GNS3/gns3-gui/issues/2443))

The following Cisco nodes **can be added to the topology and can be started** without error
- NX-OSv 7.3.0
- IOS-XRv 9k 6.2.2

[GNS3 GUI log](https://github.com/GNS3/gns3-gui/files/1768518/gns3_gui.log.Multiple.Cisco.nodes.cannot.be.added.to.the.topology.or.started.txt)
[GNS3 server log](https://github.com/GNS3/gns3-gui/files/1768521/gns3_server.log.Multiple.Cisco.nodes.cannot.be.added.to.the.topology.or.started.txt)

**Comment by jean-christophe-manciot** [comment]
The ```cannot be added``` issue seems related to ```'default_symbol' was unexpected) in schema```.
For all the mentioned nodes, the symbol was changed during creation of the corresponding templates.

**Comment by ziajka** [comment]
Hi @jean-christophe-manciot,
Thank you for reporting this.
Do you have maybe appliance file eg. for ASAv 9.8.2? If you have then please send to us.

Thanks,
Dominik

**Comment by jean-christophe-manciot** [comment]
Here is the definition of 1 Cisco node from gns3_controller.conf which doesn't use a custom-made symbol (my ASAv does):
**CSR 1000v**:
```
                {
                    "acpi_shutdown": false,
                    "adapter_type": "virtio-net-pci",
                    "adapters": 8,
                    "appliance_id": "224a5cd3-cd81-4ff8-8c63-d2f3b8cb8cf4",
                    "bios_image": "",
                    "boot_priority": "c",
                    "category": 0,
                    "cdrom_image": "",
                    "console_type": "telnet",
                    "cpu_throttling": 0,
                    "cpus": 2,
                    "default_name_format": "{name}-{0}",
                    "default_symbol": ":/symbols/iosv_virl.normal.svg",
                    "first_port_name": "Gi1",
                    "hda_disk_image": "/media/actionmystique/SAMSUNG5-Virtual/Images/GNS3/QEMU/CSR-1000v-16.6.1.qcow2",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "",
                    "hdb_disk_interface": "ide",
                    "hdc_disk_image": "",
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_interface": "ide",
                    "hover_symbol": ":/symbols/iosv_virl.selected.svg",
                    "initrd": "",
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "legacy_networking": false,
                    "linked_base": true,
                    "linked_clone": true,
                    "mac_address": "00:00:16:06:01:00",
                    "name": "CSR_1000v",
                    "node_type": "qemu",
                    "options": "-nographic -enable-kvm -cpu host",
                    "platform": "",
                    "port_name_format": "Gi{0}",
                    "port_segment_size": 0,
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 4096,
                    "server": "local",
                    "symbol": ":/symbols/gateway.svg",
                    "usage": ""
                },
```

**Comment by ziajka** [comment]
Super, thank you @jean-christophe-manciot.

**Comment by ziajka** [comment]
Re. 

>     ASAv 9.8.2
>     CSR 1000v 16.6.1
>     IOSv 15.6.3
>     IOSv L2 15.2-3-2017
>     IOS-XRv 6.1.3

It seems to that your topology was created with older version of GNS3. 

Could you try to create new project, use wizard to create one of them and make it running? Please let me know if it changes anything. Many thanks!

Cheers,
Dominik

**Comment by jean-christophe-manciot** [comment]
No, the topology is new with 2.1.3.
However, the gns3_controller.conf file itself is the result of all gns3 updates & evolutions.
So maybe there are some issues with the template itself.

**Comment by ziajka** [comment]
That's good point @jean-christophe-manciot. Definitely shouldn't have entry:

`"default_symbol": ":/symbols/iosv_virl.normal.svg",`

but 
`
"symbol": ":/symbols/router.svg",`

If you decide to edit manually please make a copy of gns3_controller.conf

**Comment by jean-christophe-manciot** [comment]
@ziajka 
Could you elaborate please about the template rules because there seems to be some confusion here:
1) I have never edited the file manually before
2) **if the symbol is changed through the GUI with one of the embedded symbols**, what is the expected result in the template:
    - the entries ```default_symbol``` and ```hover_symbol``` disappear
      in that case, there should be 
      ```"symbol": ":/symbols/iosv_virl.svg",``` instead since  it was changed as mentioned earlier
    - or all entries remain
      in that case, there should be
      ```"default_symbol": ":/symbols/iosv_virl.normal.svg",```
      ```"hover_symbol": ":/symbols/iosv_virl.selected.svg",```
      ```"symbol": ":/symbols/iosv_virl.svg",``` 
2) **if the symbol is changed through the GUI with one of a user-supplied symbols**, what is the expected result in the template:
    - the entries ```default_symbol``` and ```hover_symbol``` disappear
      in that case, it could be 
      ```"symbol": "CSR-1000v.png",```as an example, with the file located in the symbols folder 
    - or all entries remain: I doubt it is the case

**Comment by ziajka** [comment]
Hi @jean-christophe-manciot,
I understand the file wasn't edited, I'm just saying in case you decide to edit this file and make changes.

> if the symbol is changed through the GUI with one of the embedded symbols, what is the expected result in the template:
> 
>     the entries default_symbol and hover_symbol disappear
>     in that case, there should be
>     "symbol": ":/symbols/iosv_virl.svg", instead since it was changed as mentioned earlier
Exactly this case.

> if the symbol is changed through the GUI with one of a user-supplied symbols, what is the expected result in the template:
> 
>     the entries default_symbol and hover_symbol disappear
>     in that case, it could be
>     "symbol": "CSR-1000v.png",as an example, with the file located in the symbols folder
> 

Also above one is correct.

**Comment by ziajka** [comment]
Issue resolved. Next release will bring this fix.

**Comment by jean-christophe-manciot** [comment]
@ziajka 
Editing gns3_controller.conf as suggested is a success :-) (GNS3 was not running of course)
