### ISSUE TITLE
[Linux/2.1.3] Adding Cisco NX-OSv 9000 node requires outdated OVMF versions

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2447]
Ubuntu 17.10

![nxosv9k](https://user-images.githubusercontent.com/13176858/37164710-5b8d221a-22fb-11e8-879d-ae77dc583b9d.png)

All the versions of OVMF available on this OS release are fresher:
```
# apt-cache policy ovmf
...
     0~20170911.5dfba97c-1ubuntu0.1 500
        500 http://archive.ubuntu.com/ubuntu artful-updates/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu artful-updates/universe i386 Packages
     0~20170911.5dfba97c-1 500
        500 http://archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu artful/universe i386 Packages
```

Also, is the OVMF file searched on the host, or is it expected in the QEMU folder?

**Comment by grossmj** [comment]
Is there any benefit to use a more recent OVMF file?

The OVMF file is searched in the Download directory and QEMU folder.

**Comment by jean-christophe-manciot** [comment]
@grossmj 
You're missing the point: as demonstrated in the first post (```apt-cache policy``` lists **all** the versions available on the current Ubuntu release - 17.10), the ovmf version requested is not even available anymore, so artful (17.10) users have zero chance of being able to install a new NX-Osv 9000 node.
You can double-check on the [official launchpad ovmf page for artful](https://launchpad.net/ubuntu/artful/+package/ovmf) if you feel like it.

Furthermore:
- new ovmf releases offer new features and squash some bugs (like GNS3 ;-)); by blocking the ovmf version to a specific maximum one, you prevent users from benefiting fully from services offered by those new versions.
- if they introduce new blocking bug(s), the user can always downgrade the ovmf package to an earlier non-blocking release.
- it's difficult for you to keep track of all the current ovmf versions for all the Linux distributions you support

The solutions I see are to:
- let users install the ovmf version they see fit
- enforce a minimum version if you need to (instead of a maximum).
- let users clearly know where the OVMF.fd file is expected.

**Comment by adosztal** [comment]
You don't need to install ovmf on your local system, just provide the file (after downloading it) during importing the appliance.

**Comment by grossmj** [comment]
@jean-christophe-manciot 

The OVMF file we provide for download is known to work with NX-OSv 9000 however if you want to have a more recent version, you can either "Create a new version" or select "Allow custom files" (in version 2.x?) when you add the appliance.

You can also go to the appliance template settings after you installed the appliance and then to the advanced settings tab to update the bios option to point to a newer OVMF file.
