### ISSUE TITLE
Update Checkpoint GAiA appliance template

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2448]
Hopefully this is the right place to report that the Checkpoint GAiA appliance has insufficient specs pre-configured. To successfully install and run the appliance, it needs the below upgrades:

RAM = 4GB (currently 2GB)
CPU count = 2 (currently 1)
Disk size = 100GB (currently uses empty8G.qcow2 )

Updated appliance template attached : 
[checkpoint-gaia.gns3a.txt](https://github.com/GNS3/gns3-gui/files/1794794/checkpoint-gaia.gns3a.txt)

Tested with Checkpoint GAiA 80.10. 
Appliance link: https://www.gns3.com/marketplace/appliance/checkpoint-gaia

**Comment by grossmj** [comment]
@sairuscz I have updated the appliance: https://github.com/GNS3/gns3-registry/commit/7bc23db6c0bfb75707f527b316b072b3853c1a70

Please open an issue on https://github.com/GNS3/gns3-registry/ if you spot other problems regarding appliance templates.

Thanks!
