### ISSUE TITLE
[Feature Request] Create Copy in Preferences

### ISSUE THREAD

**Issue by bowersjj** [GNS3/gns3-gui#2451]
Instead of going through the process of creating a new machine in the gui, a copy function would be great.
![preferences_machine_copy](https://user-images.githubusercontent.com/14912612/37405881-d6f2e66c-2763-11e8-9e94-47f0efdf3aab.png)
.

**Comment by CapnCheapo** [comment]
Just wondering if the copy would include the device's startup config, etc, as well?

**Comment by bowersjj** [comment]
No. Just a faster way to copy VMs so I can unlink the copy, rename, config as necessary, and use as link.

Kind of a middle ground between step 2 of this thread. https://gns3.com/discussions/speedup-iosv
And this thread
https://gns3.com/discussions/inject-a-startup-config-into-ios



On Mar 16, 2018, at 11:36, Stephen C. Moore <notifications@github.com> wrote:

Just wondering if the copy would include the device's startup config, etc, as well?

**Comment by grossmj** [comment]
Implemented
