### ISSUE TITLE
Adding console type 'none'

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2452]
Although it's not common, there are a few devices (e.g. Juniper vQFX PFE) where console is not necessary. Could you add 'none' as an additional console type in a later release?

**Comment by Raizo62** [comment]
Yes. It can be usefull also in hacking classroom when we want to hide devices behide a drawing. The button "show all consoles" will not betray us

**Comment by grossmj** [comment]
I have added the console type "none" for Qemu and Docker. Do you think we should implement this for all node types?

**Comment by adosztal** [comment]
Yes, please.

**Comment by Raizo62** [comment]
Yes : I need to hide also Cisco and Switch...

**Comment by grossmj** [comment]
It was a bit more work than anticipated but now all nodes support the console node type.

**Comment by adosztal** [comment]
Awesome! Thank you. :)
