### ISSUE TITLE
GUI segmentation fault due to upgrade of Openssl from 1.0.0 to 1.1.1

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2453]
GNS3 (gui+server) version 2.1.4

Linux gns3-iouvm 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie

-----------------------------------

Issue encountered here:
https://github.com/GNS3/gns3-gui/issues/2395

-------------------------------------
This started after having GNS3 unrelated issue with openssl:
> openssl -v
> 	openssl: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.1s' not found (required by openssl)

So installed the latest openssl (compiled from official github repo) which solved my issue:

> openssl version
> OpenSSL 1.1.1-pre3-dev  xx XXX xxxx

But now, it causes issues with **QSslSocket** in GNS3 GUI resulting in **Segmentation fault**

> ajn@~/gns3-gui$ gns3 --debug
> 2018-03-21 05:07:46 INFO root:126 Log level: DEBUG
> 2018-03-21 05:07:46 INFO main:258 GNS3 GUI version 2.1.4
> 2018-03-21 05:07:46 INFO main:259 Copyright (c) 2007-2018 GNS3 Technologies Inc.
> 2018-03-21 05:07:46 INFO main:261 Application started with /usr/local/bin/gns3--debug
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve CRYPTO_num_locks
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve CRYPTO_set_id_callback
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve CRYPTO_set_locking_callback
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve ERR_free_strings
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve EVP_CIPHER_CTX_init
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_new_null
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_push
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_free
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_num
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_pop_free
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve sk_value
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSL_library_init
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSL_load_error_strings
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSL_get_ex_new_index
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv2_client_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv3_client_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv23_client_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv2_server_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv3_server_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLv23_server_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve X509_STORE_CTX_get_chain
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLeay
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot resolve SSLeay_version
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function CRYPTO_num_locks
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function SSL_library_init
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function SSLv23_client_method
> 2018-03-21 05:07:46 DEBUG qt/__init__.py:298 QSslSocket: cannot call unresolved function sk_num
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fa906a42700 (most recent call first):
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4-py3.6.egg/gns3/utils/analytics.py", line 121 in sendScreenView
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4-py3.6.egg/gns3/qt/__init__.py", line 212 in __init__
>   File "/usr/local/lib/python3.6/site-packages/gns3_gui-2.1.4-py3.6.egg/gns3/main_window.py", line 81 in __init__
>

**Comment by AJNOURI** [comment]
Downgraded to  1.0.2o from 1.1.1

```
$ openssl
OpenSSL> version
OpenSSL 1.0.2o  27 Mar 2018
```

Now GNS3 works back!!

**Comment by grossmj** [comment]
This is a dependency bug/problem. I am not sure we can do anything about this.

**Comment by AJNOURI** [comment]
ok, v1.1.1 works fine.
