### ISSUE TITLE
Error Downloading GNS3 Appliances from Marketplace

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2456]
I have downloaded appliances from marketplace before without any issues but for some reasons I cannot download any of the appliances past couple of days.  This is the error message that comes up "Downloads can only be accessed from main site".  Any work around?  Thanks
![appliance download error](https://user-images.githubusercontent.com/17806351/37857328-916f76cc-2ed0-11e8-8bb0-7b7d68097306.png)

**Comment by grossmj** [comment]
I was able to download appliances from the marketplace without any issue. I can see in your screenshot that the URL is beta.gns3.com and not just gns3.com. Please use the main site and it should work. Thanks! :+1:
