### ISSUE TITLE
Fixed zoom-in zoom-out step value

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-gui#2457]
gns3-gui-2.1.4 current zoom-in zoom-out steps scale isn't very smooth  e.g. (69,97,137,194,274....) most of the time i need the middle values between (97 and 137). I suggest using a fixed  zoom-in zoom-out step value like 10 (0, 10, 20, 30,....) and an option where we can enter the zoom value is more useful and flexible.

Here what I did to reduce the current zoom factor.
gns3-gui-2.1.4/gns3/main_window.py
`def _zoomInActionSlot(self):
         """
         Slot called to scale in the view.
         """
        factor_in = pow(2.0, 120 / 240.0) ----> factor_in = pow(2.0, 60 / 240.0)  #for smoother scale use 30 instead of 60)
        self.uiGraphicsView.scaleView(factor_in)
        self._updateZoomSettings()`

`def _zoomOutActionSlot(self):
         """
         Slot called to scale out the view.
         """
        factor_in = pow(2.0, -120 / 240.0) ----> factor_in = pow(2.0, -60 / 240.0)   #for smoother scale use 30 instead of 60)                                    
        self.uiGraphicsView.scaleView(factor_in)
        self._updateZoomSettings()`
Result:
previous zoom-in values: 69, 97, 137, 194, 274 .....
new zoom-in values: 58, 82, 98, 117, 139, 165, 196...

**Comment by grossmj** [comment]
This should be fixed.
