### ISSUE TITLE
BUG with none console type

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2458]
Hi

I have already a QEmu Template called Debian.

I modifie the console type of the Debian 's template to none.

I push on the lab a Debian device .

I push on the lab an ethernet switch. I have this error message : 
```
2018-03-27 10:12:54 ERROR appliance_manager.py:107 Error while creating node: Bad request http://127.0.0.1:3080/v2/compute/projects/61b7b65c-db25-4063-bc74-0336ad2b47f1/ethernet_switch/nodes {
    "message": "None is not one of ['telnet', 'none']\n\nFailed validating 'enum' in schema['properties']['console_type']:\n    {'description': 'Console type', 'enum': ['telnet', 'none']}\n\nOn instance['console_type']:\n    None",
    "method": "POST",
    "path": "/v2/compute/projects/{project_id}/ethernet_switch/nodes",
    "request": {
        "node_id": "0c79ea09-ff8b-4b8c-9758-53a9f8bf9314"
    },
    "status": 400
}
```

**Comment by Raizo62** [comment]
I have the bug even without change the template of the qemu template.

If i put only the ethernet switch, i have also the bug

**Comment by grossmj** [comment]
I should be able to fix this tomorrow. In the meantime you can go to the
preferences and configure a new custom switch there to then use in your
labs.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/64949f5d0457752f3d98e3a7258e75aa98f9acf6
