### ISSUE TITLE
GNS3 can't install on ubuntu 18.04 bionic beaver

### ISSUE THREAD

**Issue by briannaturinda** [GNS3/gns3-gui#2460]
E: Unable to locate package gns3-gui
and does not the ppa repos as instructed on gns3 download instructions page
Help Required Thanks

**Comment by ziajka** [comment]
Thank you @briannaturinda. We haven't published release for bionic beaver but in the following days will do that.

**Comment by briannaturinda** [comment]
Will be grateful Thanks

**Comment by ziajka** [comment]
Hi @briannaturinda. The new shinny release is on bionic beaver. Please let us know if experience any issues. Thanks!

**Comment by drprawedha** [comment]
I can installing GNS but there is some problem like :
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied

but..
after i using chown 777 /usr/bin all error has gone and.. error on ubridge

**Comment by briannaturinda** [comment]
Thanks got it working

**Comment by jmutai** [comment]
Use below guide:

https://computingforgeeks.com/how-to-install-latest-gns3-network-simulator-on-ubuntu-18-04-ubuntu-16-04/

**Comment by briannaturinda** [comment]
Thanks
