### ISSUE TITLE
Link Colors

### ISSUE THREAD

**Issue by brentstewart** [GNS3/gns3-gui#2461]
Would it be possible to allow changing the link line color? This would allow users to distinguish contexts (like inside/outside or trunk/access). I'm imagining a picker like we have for text. Thanks!

**Comment by n3oxmind** [comment]
I usually change it before compiling gns3-gui been doing that for long time. also reducing the thickness of  links will be awesome. currently i'm using 1.2 instead of 2.0.

**Comment by Fincer** [comment]
I have a custom patch set for this feature:

[gns3-gui - patch_gns3gui_linkcolors.patch](https://fjordtek.com/git/Fincer/GNS3_patches/src/branch/master/patches/gns3-gui/patch_gns3gui_linkcolors.patch)

[gns3-server - patch_gns3server_linkcolors.patch](https://fjordtek.com/git/Fincer/GNS3_patches/src/branch/master/patches/gns3-server/patch_gns3server_linkcolors.patch)

Both patches apply to old GNS3 version `2.2.0a2` of [gns3-gui](https://github.com/GNS3/gns3-gui/releases/tag/v2.2.0a2) and [gns3-server](https://github.com/GNS3/gns3-server/releases/tag/v2.2.0a2) and may not be directly compatible with newer GNS3 versions.

The patch set in action:

[![](https://fjordtek.com/images/content/thumb/medium-550/gns3_1.png)](https://fjordtek.com/images/content/gns3_1.png)

Hope this helps.

**Comment by grossmj** [comment]
@Fincer thanks a lot for this, I am going to try to add it in our next release :+1:

**Comment by grossmj** [comment]
@Fincer everything works well. I have integrated your patches. Thanks again!

**Comment by Fincer** [comment]
@grossmj You're welcome! I am glad I could help.

I have used link coloring quite some time without a single issue so far.

**Comment by dar72** [comment]
Is it possible to allow style = none to hide links? For things like mangement links that I don't need to see and reduce clutter

**Comment by grossmj** [comment]
> Is it possible to allow style = none to hide links? For things like mangement links that I don't need to see and reduce clutter.

I think we could do something like this.

**Comment by grossmj** [comment]
Re-opening to remind us to implement the style = none idea.

**Comment by grossmj** [comment]
Implemented, there is now an "invisible" link style.

**Comment by Fincer** [comment]
Just spotted an annoying issue related to the link styles.

There's no need to run `self.update()` during link style updates. If done, GNS3 may throw the following error:

```
Error while updating link: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3server/web/route.py", line 196, in control_schema
    await func(request, response)
  File "/usr/lib/python3.7/site-packages/gns3server/handlers/api/controller/link_handler.py", line 141, in update
    await link.update_link_style(request.json["link_style"])
  File "/usr/lib/python3.7/site-packages/gns3server/controller/link.py", line 217, in update_link_style
    await self.update()
  File "/usr/lib/python3.7/site-packages/gns3server/controller/udp_link.py", line 126, in update
    await node2.put("/adapters/{adapter_number}/ports/{port_number}/nio".format(adapter_number=adapter_number2, port_number=port_number2), data=self._link_data[1], timeout=221)
  File "/usr/lib/python3.7/site-packages/gns3server/controller/node.py", line 554, in put
    return (await self._compute.put(path, data=data, **kwargs))
  File "/usr/lib/python3.7/site-packages/gns3server/controller/compute.py", line 554, in put
    response = await self.http_query("PUT", path, data, **kwargs)
  File "/usr/lib/python3.7/site-packages/gns3server/controller/compute.py", line 334, in http_query
    response = await self._run_http_query(method, path, data=data, **kwargs)
  File "/usr/lib/python3.7/site-packages/gns3server/controller/compute.py", line 532, in _run_http_query
    raise NotImplementedError("{} status code is not supported".format(response.status))
NotImplementedError: 405 status code is not supported
```

Removing the following line in [gns3server/controller/link.py](https://github.com/GNS3/gns3-server/blob/master/gns3server/controller/link.py#L216):

```
    async def update_link_style(self, link_style):
        if link_style != self._link_style:
            self._link_style = link_style
-            await self.update()
```

should fix the issue. Link styles are still being kept (saved in project file) and new styles applied as they should be done. GNS3 server reports link styles in web view, as well.

My apologies.

**Comment by grossmj** [comment]
@Fincer no worries, thanks again for your contribution :+1:

**Comment by Fincer** [comment]
@grossmj You're welcome!
