### ISSUE TITLE
Using Qemu 2.11 from Ubuntu Bionic 18.04 repo console does not load

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2465]
I have installed GNS3 server 2.1.4 on Ubuntu 18.04 and when trying to access a console for any Qemu device it's frozen (black screen) using a remote GNS3 GUI 2.1.4 client on Windows.
I have tested with an older Qemu version 2.6.2 (from Ubuntu Xenial) and it works properly. Not sure if it's Qemu of GNS3 related.

**Comment by grossmj** [comment]
I would say most likely from Qemu. I will wait the final release of Ubuntu Bionic to test.

**Comment by cioby23** [comment]
Yes I also think it's a Qemu issue. I copied the Qemu cmd line from a device added in GNS3 and tried to start it manually from the shell without opening GNS3. GUI. When I tried to telnet to the console port it connects with success but no response is received,

**Comment by cioby23** [comment]
Upon doing some more testing is seems that KVM is the culprit. Although KVM is enabled and acceleration can be used Qemu VMs do not boot when it's enabled so I manually added the -no-kvm option then it booted fine.

**Comment by grossmj** [comment]
Thanks for the feedback! :+1: I will close this since this isn't a problem with GNS3.
