### ISSUE TITLE
size of console "Configure custom adapters"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2467]
Hi

I start LiveRaizo in VirtualBox. The size of the screen is 1024x768 (the default).

When i open the "Configure custom adapters" console, this console is very too large : the button "OK" and "Cancel" are not in the window.

**Comment by grossmj** [comment]
It should be better but I would like to automatically resize the window to fit the QTreeWidget inside.

**Comment by grossmj** [comment]
Should be good now.
