### ISSUE TITLE
req : variable of custom_adapters

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2468]
hi

I ask what I explain to my students not to do.

You use json format to code custom_adapters : 
```
{
   "port_name": "ethernet",
    "adapter_number": 0
   },
 {
   "port_name": "ethernet",
   "adapter_number": 1
 }

```
If we want to write program to customize it, it is not easy : we must cut it from GNS3 config, found the good value, modify it and import it.

If you add number to variable (port_name**0**), it is more easy : we can do a "search and replace" on the variable on the GNS3 config : 
```
{
   "port_name0": "ethernet",
    "adapter_number0": 0
   },
 {
   "port_name1": "ethernet",
   "adapter_number1": 1
 }

```
Is it possible ?

**Comment by grossmj** [comment]
Sorry this is not going to be possible, besides that the format may change again because 2.2 is still being developed.

> If we want to write program to customize it, it is not easy

I disagree, it should be relatively straightforward using any language that has decent JSON library. Read the file, add the info to exists JSON and then write back to the file.
