### ISSUE TITLE
Qemu binary list locks when a version is deleted

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2474]
2.1.4 with remote server.

We used to have 2 versions of qemu for testing purposes.  We eventually removed one of the versions.  When we go to configure the template of one of the device types using the removed version, we get the error "Could not find /usr/local/bin/qemu-system-x86_64 in the Qemu binaries list", but after closing the error message, the qemu binary dropbox is blank and locked, so the qemu binary can't be changed.

**Comment by grossmj** [comment]
Should be alright now. Thanks for catching this :+1:
