### ISSUE TITLE
Generated base mac breaks vEOS MLAG

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2475]
2.1.4 with remote server

I have been having problems with getting MLAG to work on versions of Arista vEOS that used to work in GNS3.  I finally realized this broke when the base mac address generation was redesigned in a previous GNS3 version.

MAC addresses seem to be generated with 52 in the first octet.  In binary 0x52 = 1010010.  The 2nd bit from the right, the U/L bit is set to 1, for local address.  With this set, vEOS will never generate the virtual mac addresses it needs for MLAG and you will receive the following types of errors:

SW1#Apr 17 19:33:56 SW1 Mlag: %FWK-3-SOCKET_CLOSE_REMOTE: Connection to  at tbt://10.0.0.2:4432/+n closed by peer (ECONNRESET when reading)
Apr 17 19:33:56 SW1 Mlag: %FWK-3-MOUNT_PEER_CLOSED: Peer closed socket connection. (tbt://10.0.0.2:4432/+n-in)()

MLAG Status:
state               :     Inactive/Reload (0:04:11 left)

By changing all my base mac addresses from 52 to 04 I have no issues getting MLAG to come up.

**Comment by grossmj** [comment]
For reference, the original issue why we changed to 0x52: https://github.com/GNS3/gns3-server/issues/1267

**Comment by grossmj** [comment]
You are right about 0x52, somehow I missed the U/L bit is set to 1. I think I will go with 0x0C = 00001100 by default which is easily recognisable and gives no matches on https://www.wireshark.org/tools/oui-lookup.html

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/fff2e128ebafaf51d49ca55bba16fe14344753ee
