### ISSUE TITLE
Separate appliance font from note font

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-gui#2477]
I usually manually assign different font color,size and attribute for every appliance (router, switch,..,etc) I add to my project. 
Every time I add new appliance I have to do this step `right-click->Text Edit`. if we have a separate default font for appliance as its form label style in `Generale preferences->Topology view` will be very helpful to set it once and use it anytime.
see the picture bellow:
![selection_002](https://user-images.githubusercontent.com/10103340/39010924-e3bb2c1a-43c4-11e8-9192-dbc9bc5f3ce2.png)
All the fonts in blue currently set as the `add note ` font or `label font` the blue fonts is the names of the devices and should be separated from the `add note` font.

**Comment by grossmj** [comment]
Implemented. Thanks for the suggestion :+1:
