### ISSUE TITLE
关于iou和模拟器的是否支持DAI防御

### ISSUE THREAD

**Issue by SayFireworks** [GNS3/gns3-gui#2484]
做实验时候碰到一个问题，首先是vm无法和主机进行直接拦截，那么这个问题可以在cloud和交换机之间接入一台傻瓜式交换机。然后在敲命令时候配置DAI防御。发现无法开启arp的检测机制。命令如下: ip arp inspection vlan vlan-range ，提示% Invalid input detected at '^' marker. 。实际上查看这个命令时候发现根本没有inspection的选项。。。这是不支持还是我iou版本低了？既然不支持为啥还要有snooping的功能呢。
![qq 20180426155619](https://user-images.githubusercontent.com/35683906/39293009-61b8997c-496a-11e8-9c56-bdf4e5571430.png)

**Comment by SayFireworks** [comment]
Tanks。
Where can I get the latest version of IOU?

**Comment by ehlers** [comment]
Test with i86bi-linux-l2-adventerprise-15.1b.bin, that one doesn't have the "ip arp inspection" command, but the i86bi-linux-l2-adventerprisek9-15.2d.bin has this command. This command is also include into the latest VIRL IOSv-L2 image vios_l2-adventerprisek9-m.03.2017.qcow2 .

GNS3 starts only the images, it can't influence it's features. So you have to complain to the company, that created the images, in your case it's Cisco. GNS3 can't help you with that.

The only official way is to get images from Cisco. The VIRL images you need a Cisco VIRL account (https://learningnetworkstore.cisco.com/virtual-internet-routing-lab-virl), for IOU images you have to contact your cisco representative.

**Comment by SayFireworks** [comment]
Thanks!
Good luck!

**Comment by SayFireworks** [comment]
Is my brother still there? I haven't found the version of 2D. Can you share it? Be deeply grateful！

**Comment by ehlers** [comment]
No, sharing copyrighted material is a crime.
