### ISSUE TITLE
Packet capture analyzer command: 'No closing quotation' ERROR!

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-gui#2485]
I'm trying to use `tshark` to read the captured packet as bellow:
`tilix -e $SHELL -c "tail -f -c +0b %c  | tshark  -i -; $SHELL"`
![preferences_002](https://user-images.githubusercontent.com/10103340/39448386-a4cbf4d6-4c79-11e8-8010-1d29aca912fa.png)
and here is what i get:
![selection_003](https://user-images.githubusercontent.com/10103340/39449285-76b2aaba-4c7c-11e8-93ba-f5bf248a51f9.png)

```
=> Invalid packet capture command tilix -e $SHELL -c "tail -f -c +0b "/home/user/GNS3/projects/RHCE-DNS-FORWARDER/project-files/captures/R1_Ethernet10_to_SW5_Ethernet10.pcap"  | tshark  -i -; $SHELL": No closing quotation
```
I think gns3 doesn't parse the command correctly.

The Packet capture analyzer command that I entered word perfectly form the terminal.
```bash
tilix -e $SHELL -c "tail -f  -c +0 R1_Ethernet10_to_SW5_Ethernet10.pcap | tshark -i -;$SHELL"
```
the double quotation is a must for this command to work.

I'm trying to modify the parsing command from the source code; I will update once i found solution.
any help about how to fix this problem or getting tshark to work with gns3 will be appreciated.

**Comment by n3oxmind** [comment]
update:
Tilix 1.7.9 added new token ${activeTerminlTitle}, this will allow a very nice multiple tabs with the correct name see bellow:
![selection_025](https://user-images.githubusercontent.com/10103340/39680686-627ad8de-5158-11e8-94d2-fcdd304d7cd7.png)

here is how to configure Tilix for multiple tabs with gns3
1- Tilix preferences-> make sure to set the highlighted variables as bellow:
![tilix preferences_028](https://user-images.githubusercontent.com/10103340/39680764-1ed58f42-5159-11e8-9654-73ebc0fac4e8.png)
2- gns3 console setting 
```gns3 
tilix -a app-new-session -t "%d" -e "telnet %h %p"
```
all set enjoy nice multiple tabs with Tilix.

**Comment by n3oxmind** [comment]
**update2:**
Here is the final working script of `Packet capture analyzer command` that work with `Tshark` and `Tilix v
1.7.9` with multi tabs:
1. create a script `gns3tshark.sh` as bellow:
```bash
# gns3tshark.sh
#! /usr/bin/env bash
tilix -a app-new-session -t $2 -e $SHELL -c "tail -f  -c +0b $1 | tshark -i -;$SHELL"
```
2. add this command to gns3 `Packet capture analyzer command`
```
gns3tshark.sh %c "%d"
```
![r1_031](https://user-images.githubusercontent.com/10103340/39946240-4b13e726-5522-11e8-9531-b1d63e65a6b9.png)

note: the title of the tab (%d) will be the device name like (R1, SW1, ... ) I wish if `%d` returns the link name like (R1->R2, R1->SW2,...,etc)

**Comment by grossmj** [comment]
The problem was that the '|' was interpreted by GNS3 which split the command in 2 parts. I fixed that in https://github.com/GNS3/gns3-gui/commit/d511d0f5f867cdca35cbe4e6ae1ec57d0c17fe17

> note: the title of the tab (%d) will be the device name like (R1, SW1, ... ) I wish if %d returns the link name like (R1->R2, R1->SW2,...,etc)

%d is replaced by something like "R1 f0/0 to R2 f0/1", maybe the reason is that tilix doesn't support spaces. Should we have something like "R1[f0/0]->R2[f0/1]" instead?

**Comment by n3oxmind** [comment]
I forget to mention that `gnome-terminal` the `-e` option is depreciated and causing problem to me, please replace it with `--`.
