### ISSUE TITLE
GNS3_SAVED_STATE of Qemu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2487]
Hi

I don't know if it is a bug or a technical choose, then I'm asking the question anyway ;-)

For each stop/start of a QEmu device, the command "qemu-img snapshot -l hda_disk.qcow2" on his hda_disk.qcow2 shows a new line GNS3_SAVED_STATE
```
Snapshot list:
ID        TAG                 VM SIZE                DATE       VM CLOCK
1         GNS3_SAVED_STATE          0 2018-05-03 06:43:48   00:00:00.000
2         GNS3_SAVED_STATE          0 2018-05-03 06:45:52   00:00:00.000
3         GNS3_SAVED_STATE          0 2018-05-03 06:45:52   00:00:00.000
4         GNS3_SAVED_STATE          0 2018-05-03 06:46:04   00:00:00.000
5         GNS3_SAVED_STATE          0 2018-05-03 06:46:18   00:00:00.000
6         GNS3_SAVED_STATE          0 2018-05-03 06:46:18   00:00:00.000
7         GNS3_SAVED_STATE          0 2018-05-03 06:46:58   00:00:00.000
```

is this correct or is this a hidden bug ?

**Comment by grossmj** [comment]
Looks like there is a bug with that. I will investigate.

**Comment by grossmj** [comment]
I fixed the problem in https://github.com/GNS3/gns3-server/commit/1905a99ce753b06e16df101dacea0c6d757fa183

By the way, now you should be able to instantly boot Qemu VMs if you select "Save the VM state" in the node properties.

![save_vm_state](https://user-images.githubusercontent.com/4752614/41190536-c43c5738-6c0a-11e8-9519-36e7422675d6.png)
