### ISSUE TITLE
Switching console from telnet to VNC throws error

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2489]
Running GNS3 version 2.1.5 on Darwin (64-bit) with Python 3.6.5 Qt 5.10.1 and PyQt 5.10.1.
Remote server.

When a device is dragged out to the project and (while powered off) has its console type changed from telnet to VNC I receive the following error: 

VNC console require a port superior or equal to 5900 currently it's 2001

**Comment by grossmj** [comment]
Thanks for catching that, I have fixed the problem in https://github.com/GNS3/gns3-server/commit/40151cd1fe1011faab69abd4570609046aec3452
