### ISSUE TITLE
Interface sequence number check was not updated

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2491]
Although [654](https://github.com/GNS3/gns3-server/issues/654) was solved and appliances can be imported with interface counters starting from any number, its check was not updated in the GUI.

I've imported an appliance that starts counting its ports from 3:
![interface_check1](https://user-images.githubusercontent.com/16632791/39830332-681dcfe2-53c1-11e8-944e-586b3d1ef726.png)

This was in the template:
`"port_name_format": "ens{port3}",`

Importing went fine, I can drag the node in, and create connections to other nodes. However if I try to change the port naming, I get an error:
![interface_check2](https://user-images.githubusercontent.com/16632791/39830380-8f431c44-53c1-11e8-9411-f00fae0639a8.png)

**Comment by grossmj** [comment]
Should be fixed now.

**Comment by adosztal** [comment]
Thanks! :+1:
