### ISSUE TITLE
Linux - cant connect physical devices to GNS3

### ISSUE THREAD

**Issue by Rob1NNk0** [GNS3/gns3-gui#2494]
Hello,

I am working in Debian and I would like to connect my physical devices to GNS3 devices. So I connected cisco switch to my PC, configured VLAN, switchport but I am not even able to ping PCs network adapter.
Does any of you have some experience with this?

Thanks.

**Comment by grossmj** [comment]
What you will need is a breakout switch. I wrote an article a few years ago which should help:

https://web.archive.org/web/20150928014451/http://www.gns3.net/articles/ccie-routing-switching-lab/qinq-with-virtual-switch-option/

I am sure you can find many other articles describing how to do it as well. Good luck and please ask your questions on our community forum, you will get faster answers: https://gns3.com/community

Thanks :)
