### ISSUE TITLE
"Error while updating link: Link ID <ID> doesn't exist", when deleting connected nodes

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2495]
Cosmetic issue: Seems like GNS3 tries to remove the link between two nodes multiple times when deleting both nodes at the same time.

**1) Starting topology:**
![screenshot from 2018-05-12 08-23-58](https://user-images.githubusercontent.com/16632791/39954343-0b3d1130-55be-11e8-9be8-eb102fab5af2.png)

Link ID when accessing GNS3 API (http://{server-ip}/v2/projects/{project-id}/links); there's this single link only:
```
[
    {
        "capture_file_name": null,
        "capture_file_path": null,
        "capturing": false,
        "filters": {},
        "link_id": "49b0cf48-7c99-435a-a785-86e411fcac07",
        "link_type": "ethernet",
        "nodes": [
            {
                "adapter_number": 0,
                "label": {
                    "rotation": 0,
                    "style": "font-family: DejaVu Sans;font-size: 10.0;fill: #000000;fill-opacity: 1.0;",
                    "text": "eth0",
                    "x": 38,
                    "y": 51
                },
                "node_id": "b275476f-1d8f-41c3-bb04-2080106d8a0c",
                "port_number": 0
            },
            {
                "adapter_number": 0,
                "label": {
                    "rotation": 0,
                    "style": "font-family: DejaVu Sans;font-size: 10.0;fill: #000000;fill-opacity: 1.0;",
                    "text": "eth0",
                    "x": 39,
                    "y": -29
                },
                "node_id": "ee152e6f-99e0-487b-9c9d-068746658e83",
                "port_number": 0
            }
        ],
        "project_id": "000e09bb-c8ef-4ed3-bde5-6546f5d88114",
        "suspend": false
    }
]
```

**2) I select and remove both nodes:**
![screenshot from 2018-05-12 08-24-06](https://user-images.githubusercontent.com/16632791/39954352-45bd77aa-55be-11e8-9a44-4c86c2acc34b.png)

**3) Which results a warning:**
`Error while updating link: Link ID 49b0cf48-7c99-435a-a785-86e411fcac07 doesn't exist`
![screenshot from 2018-05-12 08-24-13](https://user-images.githubusercontent.com/16632791/39954355-54d18c72-55be-11e8-868e-0e06b33ec6c1.png)

I get similar warnings with more than two nodes too.

**Comment by grossmj** [comment]
Looks like it is similar to https://github.com/GNS3/gns3-gui/issues/2483

**Comment by adosztal** [comment]
Oops, I missed that somehow. This one's a duplicate and can be closed.

**Comment by grossmj** [comment]
No worries :)
