### ISSUE TITLE
format of md5sum file

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2498]
Hi

I want to add a new device into GNS3.

I have a big qcow file (A.qcow2). Manually, i create the md5sum file (A.qcow2.md5sum).
But, i finish the md5sum file with endline
Example where i show endline with \n :
dcbb5318c3e18ab085088d4474d8de85\n

When i put this device on the lab, GNS3 seems not to like and calculates again the md5sum : with big file, we must wait a "long" time.

If the md5sum file doesn't contains \n, GNS3 uses it without problem.

**Comment by grossmj** [comment]
Should be fixed now. Let me know if you still have an issue.
