### ISSUE TITLE
 disallow to rename running device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2499]
Hi

On LiveRaizo, the VM Debian detect his name in GNS3 to use it as hostname.

But, on GNS3, we can change the name of devices after his startup. Then the name in GNS3 can be different of his name showed by the device. And my students do that often :-(

Can you disallow to rename started VM ? or a global option to choose ? or a parameter by VM (i don't like) ?

**Comment by Raizo62** [comment]
I ask to disallow to rename only running device, not all devices. It is already the state with VirtualBox devices.

**Comment by grossmj** [comment]
Done.

**Comment by Raizo62** [comment]
Thanks :-)
