### ISSUE TITLE
Can't change startup-config file for IOU/Dynamips

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2501]
Starting from 2.1.5 not possible to change “initial startup-config” for IOU and Dynamips.
Error appears.

<img width="324" alt="error" src="https://user-images.githubusercontent.com/16309438/40374347-b98d7d1a-5d9d-11e8-9672-79f97b9aa641.png">

**Comment by grossmj** [comment]
It should work, are you running GNS3 server on a remote server/VM?

**Comment by grossmj** [comment]
I have tested and didn't find any issue. Make sure the file you selected can be read (correct permissions etc.)

**Comment by vint66** [comment]
i'm running gns3 on remote ubuntu server. Configs also on same server (directory specified in gns3server config file). Permissions is ok (and gns3 running as root) also it was working just fine before 2.1.5.

**Comment by grossmj** [comment]
How to you select the “initial startup-config” on the remote server from the GUI? Can you describe the process or include screenshots please?

Thanks!

**Comment by vint66** [comment]
Hi Jeremy

I’m just changing initial startup-config file (as you see in screenshots 1>2>3)

Directly with config files (file exist with exact name) provided with server configuration and using (configs_path = /opt/gns3/configs). Server running as root but directly also allowed to Read for everyone.
Workaround is to change startup config file with text editor.

<img width="444" alt="1" src="https://user-images.githubusercontent.com/16309438/41326785-8fbb68a6-6e75-11e8-9c46-97c82c781622.png">

<img width="447" alt="2" src="https://user-images.githubusercontent.com/16309438/41326788-93973478-6e75-11e8-8c7c-707921033f3c.png">

<img width="470" alt="3" src="https://user-images.githubusercontent.com/16309438/41326791-96ff9b82-6e75-11e8-938b-74c422538ea5.png">

**Comment by grossmj** [comment]
@vint66 do you have the same issue with version 2.1.9?

**Comment by vint66** [comment]
Yes, same issue with 2.1.9.

<img width="403" alt="screen shot 2018-08-22 at 7 22 19 am" src="https://user-images.githubusercontent.com/16309438/44469422-4c856980-a5dc-11e8-8f38-954914088dd9.png">

**Comment by vint66** [comment]
Hi Jeremy,

Just to let you know that issue still the same in 2.2.0rc4 (as previous screenshot)
