### ISSUE TITLE
Can't add SVG image to project

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2502]
GNS3 version 2.1.6 on Darwin (64-bit) with Python 3.6.5 Qt 5.9.3 and PyQt 5.9.2.

In a project when using "Insert a picture" and selecting linux-guest.svg no image is actually shown. This works, when using a .png image.

The project file shows an empty entry for the SVG image.
```
        "drawings": [
            {
                "drawing_id": "be57bc1f-22e6-4349-b6b3-d217188ab09a",
                "rotation": 0,
                "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"{width}\" height=\"{height}\"></svg>",
                "x": -32,
                "y": -29,
                "z": 0
            }
        ],
```

**Comment by n3oxmind** [comment]
@ehlers, do this for now it works for me:
open `gns3-gui-2.1.6/gns3/qt/qimage_svg_renderer.py` in your editor and comments line 62 and 63:
```
 62             if self.isValid():
 63                 return res
```
Reinstall gns3-gui-2.1.6 to apply changes.

**Comment by ehlers** [comment]
Yes, that works, thanks a lot. But it looks a bit like a workaround. Now the SVG image is converted in a PNG before displaying.

```
        "drawings": [
            {
                "drawing_id": "d7eac219-689e-4bed-8b48-74bc534e2873",
                "rotation": 0,
                "svg": "b49c51454a04518fef206035c3d074b1.png",
                "x": -32,
                "y": -29,
                "z": 0
            }
        ],
```

**Comment by grossmj** [comment]
@ehlers can you post "linux-guest.svg" so we can test on our side? Thanks! :)

**Comment by ehlers** [comment]
It's from the GNS3 registry:
https://github.com/GNS3/gns3-registry/blob/master/symbols/linux_guest.svg

**Comment by grossmj** [comment]
Ok thanks, I thought it was a custom symbol.

**Comment by grossmj** [comment]
This is fixed now.
