### ISSUE TITLE
Upgrade issue gns3vm

### ISSUE THREAD

**Issue by Mangab** [GNS3/gns3-gui#2511]
I have upgraded from gns3 2.1.5 to 2.1.6 which is fine.
However, when I upgrade gns3vm from 2.1.5 to 2.1.6, it says error.
Currently I cannot open my topology which took about a month to configure.
I tried to get just topology device config files, but I cannot find them. (JunOS vMX)
What should I do?

error message below.

dpkg: error processing package open-vm-tools-lts-trusty (--configure):
 dependency problems - leaving unconfigured
setting up python3-pycurl (7.19.3-0Ubuntu3) ..
..
setting up software-properties-common (0.92.37.8) ...
Errors were encountered while processing:
 open-vm-tools
 open-vm-tools-lts-trusty
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Mangab** [comment]
I can remove the gns3vm and restart settings from bottom. But the most important thing is vIOS and vMX routing configs on the gns3vm. How to collect those config files in a project? Or does anyone know installing gns3 2.1.5 in ubuntu by specifically choosing the 2.1.5 version?

**Comment by grossmj** [comment]
Hi,

Have you tried the following commands in the VM?

```
sudo apt-get remove open-vm-tools-lts-trusty
rm -r /etc/vmware-tools
sudo apt-get install open-vm-tools-lts-trusty
```

**Comment by grossmj** [comment]
I will try to fix this in our next release of the GNS3 VM: https://github.com/GNS3/gns3-vm/commit/0e5f1b8aac93d21d9f00fbf2f32fbf0db5e078c0

**Comment by Mangab** [comment]
Thank you for your quick response. After doing the instruction, it says GNS3 is not installed please install it with sudo pip3 install gns3-server. Or download a preinstalled VM.
When I enter the command, it says: Requiremnt already satisfied (use --upgrade to upgrade): psutil> 
about 20 lines of this statements.

**Comment by Mangab** [comment]
And GNS3 cannot connect to gns3vm.
Also, when I turn on gns3, there is a error message "The VMware Tools power-on script did not run successfully in this virtual machine. If you ......~~"

**Comment by grossmj** [comment]
Have you tried to reboot the VM or run upgrade again?

Also, for please see this post for reference: https://gns3.com/qa/my-gns3-gui-upgraded-authomatica

**Comment by Mangab** [comment]
I have tried several times and did not work.  Although it looks like the version is 2.1.6, it keeps saying gns3vm-server is not installed. Fortunately, I have a snapshot of 2.1.5. Can you give me a way to install GNS3 2.1.5 instead of 2.1.6?

**Comment by Mangab** [comment]
I will start from nothing. I gave up. Thank you for your help anyway.
