### ISSUE TITLE
v2.1.7 corrupted for MacOS

### ISSUE THREAD

**Issue by lugeha** [GNS3/gns3-gui#2518]
Damaged warning and fails to start.

**Comment by lugeha** [comment]
If I run it from the CLI it works. Likely just an issue with how it's packaged.

**Comment by grossmj** [comment]
I just tested on macOS sierra and I could open the app without any issue. Have you downloaded directly from GitHub? https://github.com/GNS3/gns3-gui/releases/tag/v2.1.7

MD5 checksum for GNS3-2.1.7.dmg = e276ec261b90ab8affcaa15bbae97969

**Comment by grossmj** [comment]
Just a question: do you have Little Snitch installed on your macOS?

**Comment by lugeha** [comment]
Downloaded from GitHub, MD5 sum is the same. Do not have Little Snitch.

Are you using Sierra or High Sierra?

**Comment by grossmj** [comment]
Strange... I am using Sierra.

**Comment by lugeha** [comment]
I fired up a fresh install inside a VM and was unable to reproduce the issue.

**Comment by grossmj** [comment]
I have added the xattr workaround to our build process. Hopefully this will fix the problem for our next releases.
