### ISSUE TITLE
Timeout error doesn't allow to install locally router ios.

### ISSUE THREAD

**Issue by cegepgim1001** [GNS3/gns3-gui#2522]
Hello,
This morning I have upgraded GNS3 2.1.6 to .7, and lately to .8 and I am not able to add an IOS Router's image if I have only the local machine started (not connected to GNS3 VM). The error is "Timeout after... seconds - Error while getting compute list:Operation Timeout".
I am able to install the IOS if I import the GNS3 VM.
Please, advise back.
Thank you and Best Regards,
Asen

**Comment by grossmj** [comment]
Hi,

Please can you post a screenshot?

Thanks!

**Comment by cegepgim1001** [comment]
Thank you for your prompt reply grossmj,
So I have no problem to install it on Win 8.1 x 64 - see the attachment 81_.... I also was able to import the portable appliance which you see into the picture.
Neither of both succeeded on my Win 10 x 64 - see the pictures - 10_....
Best,
Asen

![10_01](https://user-images.githubusercontent.com/19863421/41438399-3018f856-6ff5-11e8-941b-fc45c1d132a0.PNG)
![10_02](https://user-images.githubusercontent.com/19863421/41438400-302859a4-6ff5-11e8-8e4d-66bcc337dbf2.PNG)
![10_03](https://user-images.githubusercontent.com/19863421/41438401-3039dcb0-6ff5-11e8-963c-942d6a9996c2.PNG)
![10_04](https://user-images.githubusercontent.com/19863421/41438402-304ad9a2-6ff5-11e8-969d-02ffb9c9fe27.PNG)
![81_01](https://user-images.githubusercontent.com/19863421/41438403-305d81c4-6ff5-11e8-8f95-d322186c4edc.PNG)

**Comment by cegepgim1001** [comment]
Hi Jeremy,

I did it already into the post.
Could you check there, please?


Best Regards,


Asen

**Comment by Kigabiro** [comment]
Hi @grossmj ,
I am experiencing the same issue as already reported by @cegepgim1001 above.
I have been trying to calculate the IDLE-PC for different IOS Router Images and I receive the same error/failure.
The IDLE-PC is computed to infinity and when left to continue calculating, it can generate over 120 errors.
The screenshot has been attached. 
I waiting for your feedback as well.
Thank you.
Nicholas
![idle-pc failure](https://user-images.githubusercontent.com/38135324/42133801-4554a60c-7d38-11e8-92ab-9ba7e9b90ea2.PNG)

**Comment by grossmj** [comment]
Ref https://github.com/GNS3/gns3-server/commit/12e71a29170756166095d2a0559e6f4253b1f905

**Comment by grossmj** [comment]
Do you have the same problem using "Idle-PC" or "Auto Idle-PC" from the contextual menu?

![contextual_menu](https://user-images.githubusercontent.com/4752614/44771684-ee392780-ab95-11e8-8a46-d9e3a03ec9a7.png)

**Comment by Salmane89** [comment]
I have the same issue as well, when i try to add a device GNS3 is stuck in "Timeout after... seconds - Error while getting compute list:Operation Timeout" even in the latest version 2.1.11

**Comment by grossmj** [comment]
Can you try with our latest 2.2 beta 1? Thanks.

**Comment by grossmj** [comment]
Have you tried with version 2.2.0?

**Comment by cegepgim1001** [comment]
I did it indeed, and it is awesome, thank you Jeremy!

I am teaching comp. science, ip- telephony, net. Security classes with several colleges, and a major school board in Montreal, as the last couple of years heavily introducing gns3 to the students, and recording lots of labs into YouTube with it.
How can I contribute to the project?

Best,

Asen



Sent from myMail for iOS


Tuesday, October 8, 2019, 4:06 AM -0400 from notifications@github.com  <notifications@github.com>:

**Comment by grossmj** [comment]
@cegepgim1001 thanks for letting us know.

> How can I contribute to the project?

There are many ways to contribute: add code to fix or improve GNS3 in the form of a pull request, create new appliances in https://github.com/GNS3/gns3-registry, test GNS3 and create issues or answer questions on our community forum https://gns3.com/community/

Thanks :+1:
