### ISSUE TITLE
Allow users to accept different md5 hashes for preconfigured appliances.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2526]
We really need to provide users with the ability to change md5 during appliance installation with warning. Lots of related questions:

We could allow the user to install appliances with different md5 hash with a warning. Something like:

>This is not the correct file. the md5 sum is <value1> and >should be <value2>.
>Do you want to accept it at your own risks.
>
>Yes              No

**Comment by sliddjur** [comment]
This would be great, and a major game changer to GNS3 LABS...

**Comment by grossmj** [comment]
Implemented.
