### ISSUE TITLE
GNS3 2.1.8 can not make it work

### ISSUE THREAD

**Issue by leninp57** [GNS3/gns3-gui#2530]
Hello 

This problem is very weird because in my old laptop my GNS3 works without any problems, Recently I received a new laptop Lenovo T480 with  the new processor i7 8650u, and since then I couldn't make the  GNS3 2.1.8 work on this laptop.

I can install the GNS3 without problems,  I can install the GNS3 VM in vmware workstation without problems, even I can add the GNS3 server to the GNS3 without problems. I can see it up and running.

When I try to run an appliance that use qemu is when everything goes wrong, I check the logs and everything looks normal , I can see the connection to the console of the router( through telnet) up  but it does not show any output. 
Suddenly I begin to receive the following messages:
NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s  ( in the GNS3 VM)

In the logs everything looks normal

2018-06-27 01:33:59 INFO qemu_vm.py:909 Starting QEMU with: /usr/bin/qemu-system-x86_64 -name CiscoCSR1000v16.7.1-1 -m 3072M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/opt/gns3/projects/565ebe59-d27e-4f84-83f4-1cbeb9e625b2/project-files/qemu/0bbf96bc-4c55-4998-a3aa-ebc1175c3b84/hda_disk.qcow2,if=ide,index=0,media=disk -uuid 0bbf96bc-4c55-4998-a3aa-ebc1175c3b84 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:43578,server,nowait -net none -device vmxnet3,mac=0c:25:b2:3b:84:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device vmxnet3,mac=0c:25:b2:3b:84:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device vmxnet3,mac=0c:25:b2:3b:84:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device vmxnet3,mac=0c:25:b2:3b:84:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -nographic
2018-06-27 01:33:59 INFO qemu_vm.py:911 logging to /opt/gns3/projects/565ebe59-d27e-4f84-83f4-1cbeb9e625b2/project-files/qemu/0bbf96bc-4c55-4998-a3aa-ebc1175c3b84/qemu.log
2018-06-27 01:33:59 INFO base_node.py:539 Starting new uBridge hypervisor 0.0.0.0:35043
2018-06-27 01:33:59 INFO hypervisor.py:170 starting ubridge: ['/usr/bin/ubridge', '-H', '0.0.0.0:35043']
2018-06-27 01:33:59 INFO hypervisor.py:172 logging to /opt/gns3/projects/565ebe59-d27e-4f84-83f4-1cbeb9e625b2/project-files/qemu/0bbf96bc-4c55-4998-a3aa-ebc1175c3b84/ubridge.log
2018-06-27 01:33:59 INFO hypervisor.py:180 ubridge started PID=1871
2018-06-27 01:33:59 INFO base_node.py:542 Hypervisor 0.0.0.0:35043 has successfully started
2018-06-27 01:33:59 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0113 seconds
2018-06-27 01:33:59 INFO qemu_vm.py:928 QEMU VM "CiscoCSR1000v16.7.1-1" started PID=1866
2018-06-27 01:33:59 INFO helpers.py:534 192.168.22.1 [27/Jun/2018:01:33:59 +0000] "POST /v2/compute/projects/565ebe59-d27e-4f84-83f4-1cbeb9e625b2/qemu/nodes/0bbf96bc-4c55-4998-a3aa-ebc1175c3b84/start HTTP/1.1" 200 2708 "-" "Python/3.6 aiohttp/2.3.10"

I would appreciate any help 

Thanks

PD: I can see that KVM is enabled in the VM

gns3@gns3vm:~$ kvm-ok 
INFO: /dev/kvm exists
KVM acceleration can be used

**Comment by grossmj** [comment]
I suspect an issue with Qemu. What version is installed in the VM?

**Comment by leninp57** [comment]
Hi
Thanks for your response, 

Here are some outputs about the KVM, QEMU version. Could it be something with this new i7 processor (8650u)? I run this version ( GNS3 VM 2.1.8) in another laptop with other I7 procesor (older) and everything runs fine.
What other type of troubleshooting can I run in order to determine the cause of the problem?
Thanks in advanced,
Lenin


gns3@gns3vm:~$ kvm --version
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu4), Copyright (c) 2003-2008 Fabrice Bellard

gns3@gns3vm:~$ apt show qemu-system-x86
Package: qemu-system-x86
Source: qemu
Priority: optional
Section: otherosfs
Installed-Size: 17.9 MB
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Version: 1:2.5+dfsg-5ubuntu4
Recommends: qemu-utils, cpu-checker
Replaces: kvm (<< 1.3.0+dfsg-5), qemu-common (<< 1.3.0+dfsg-5), qemu-kvm (<< 1.2.0.dfsg-1), qemu-system (<< 1.3.0+dfsg-5)
Suggests: samba, vde2, qemu-block-extra (= 1:2.5+dfsg-5ubuntu4), kmod, sgabios, ovmf
Provides: qemu-system-i386, qemu-system-x86-64
Depends: libaio1 (>= 0.3.93), libasound2 (>= 1.0.16), libbluetooth3 (>= 4.91), libbrlapi0.6, libc6 (>= 2.15), libcacard0 (>= 2.2), libfdt1, libgcc1 (>= 1:4.1.1), libgcrypt11 (>= 1.5.1), libglib2.0-0 (>= 2.31.8), libgnutls26 (>= 2.12.17-0), libjpeg8 (>= 8c), libncurses5 (>= 5.5-5~), libpixman-1-0 (>= 0.19.6), libpng12-0 (>= 1.2.13-4), libpulse0 (>= 1:0.99.1), libsasl2-2 (>= 2.1.24), libsdl1.2debian (>= 1.2.11), libspice-server1 (>= 0.12.4), libtinfo5, libusb-1.0-0 (>= 2:1.0.16), libusbredirparser1 (>= 0.6), libuuid1 (>= 2.16), libvdeplug2, libx11-6, libxen-4.4 (>= 4.4.2), libxenstore3.0 (>= 4.1.0~rc6), zlib1g (>= 1:1.2.0), qemu-system-common (>> 2.0.0+dfsg-7~), seabios (>= 1.7.5~), ipxe-qemu (>= 1.0.0+git-20131111.c3d1e78-1~)
Conflicts: kvm (<< 1.3.0+dfsg-5)
Breaks: kvm (<< 1.3.0+dfsg-5), libvirt0 (<< 1.2), qemu-common (<< 1.3.0+dfsg-5), qemu-kvm (<< 1.2.0.dfsg-1), qemu-system (<< 1.3.0+dfsg-5)
Download-Size: 3,931 kB
Original-Maintainer: Debian QEMU Team <pkg-qemu-devel@lists.alioth.debian.org>
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/gns3/qemu/ubuntu/ trusty/main amd64 Packages
Description: QEMU full system emulation binaries (x86)
 QEMU is a fast processor emulator: currently the package supports
 i386 and x86-64 emulation. By using dynamic translation it achieves
 reasonable speed while being easy to port on new host CPUs.
 .
 This package provides the full system emulation binaries to emulate
 the following x86 hardware: i386 x86_64.
 .
 In system emulation mode QEMU emulates a full system, including a processor
 and various peripherals.  It enables easier testing and debugging of system
 code.  It can also be used to provide virtual hosting of several virtual
 machines on a single server.
 .
 On x86 host hardware this package also enables KVM kernel virtual machine
 usage on systems which supports it.

N: There are 2 additional records. Please use the '-a' switch to see them.
gns3@gns3vm:~$

**Comment by leninp57** [comment]
Hello

I hope you are doing fine

I was wondering if you have any ideas about how to proceed here, 

Thanks

**Comment by grossmj** [comment]
No idea why you are getting this problem. Googling the error message suggest there is a kernel bug due to an hardware problem: https://ubuntuforums.org/showthread.php?t=2205211

**Comment by leninp57** [comment]
Hi
Thanks for your response

I had checked that link before I opened this case. And I have done a lot of things without any success.
As I said before the only thing different with other machines is the CPU.

I will keep searching a way to make this works because I really like GNS3, if you have any ideas please let me know.

Regards

**Comment by leninp57** [comment]
Hello
I hope you are doing fine
This case is waiting for more information , please let me know if you need something else.

Regards,

Lenin

**Comment by grossmj** [comment]
@leninp57 can you post a screenshot of what you see in the GNS3 VM please? ("NMI watchdog: BUG: soft lockup - CPU#0 stuck" messages...)

Thanks!

**Comment by grossmj** [comment]
Also, how much RAM and CPU have you allocated to the GNS3 VM?

**Comment by leninp57** [comment]
![error gns3](https://user-images.githubusercontent.com/37081123/43875832-39e2f210-9b60-11e8-97e0-fd920a26af52.JPG)
![vm gns3](https://user-images.githubusercontent.com/37081123/43875833-3a14b8fe-9b60-11e8-9d41-43acd9b2cc78.JPG)
Hello 
I hope you are doing fine
Please find attached the information

Regards

**Comment by grossmj** [comment]
@leninp57 thanks for the information. Just for testing, can you allocate only 1 CPU to the VMware VM and test again?

Thanks!

**Comment by n3oxmind** [comment]
@leninp57, A soft lock-up occurs when a CPU reports a memory starvation while it is unable to access a memory node that is being accessed by other CPUs. Try to reduce the number of CPUs.  if not working try to change the I/O scheduler while setting the #CPUs=1. if nothing working for you check the link bellow:

reference
[Mitigate soft lockup in KVM guests](https://access.redhat.com/solutions/39542)

P.S. This has nothing to do with your processor family, its related to virtualization world in your case KVM (qemu).

**Comment by grossmj** [comment]
Please comment back of you still face this issue.

**Comment by idomok** [comment]
Hello All,

Am having the same problem with my newly purchased HP Elitebook Folio 9480m. qemu based devices won't run on gns3  but rather display error show above.
