### ISSUE TITLE
2.2 : GNS3 crash

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2532]
Hi

When i start GNS3, GNS3 doesn't start with this error message :

> 2018-06-28 20:36:58 ERROR local_server.py:487 Local server process has stopped
> 2018-06-28 20:36:58 ERROR local_server.py:489 /usr/local/lib/python3.5/dist-packages/raven/conf/remote.py:91: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
>   warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
> 
> 2018-06-28 20:37:22 CRITICAL progress_dialog.py:181 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 2018-06-28 20:37:23 CRITICAL __init__.py:183 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 2018-06-28 20:47:28 ERROR local_server.py:487 Local server process has stopped
> 2018-06-28 20:47:28 ERROR local_server.py:489 /usr/local/lib/python3.5/dist-packages/raven/conf/remote.py:91: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
>   warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
> 
> 2018-06-28 20:47:53 CRITICAL progress_dialog.py:181 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 2018-06-28 20:47:53 CRITICAL __init__.py:183 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 

I have also thes error messages in gns3_server.log

> 2018-06-28 20:47:23 INFO run.py:213 GNS3 server version 2.2.0dev2
> 2018-06-28 20:47:23 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
> 2018-06-28 20:47:23 INFO run.py:218 Config file /home/user/.config/GNS3/gns3_server.conf loaded
> 2018-06-28 20:47:23 WARNING run.py:224 Local mode is enabled. Beware, clients will have full control on your filesystem
> 2018-06-28 20:47:23 INFO run.py:232 Running with Python 3.5.3 and has PID 1179
> 2018-06-28 20:47:23 INFO run.py:79 Current locale is fr_FR.UTF-8
> 2018-06-28 20:47:23 CRITICAL run.py:256 Critical error while running the server: No directory exists at '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 479, in __init__
>     directory = directory.resolve()
>   File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
>     s = self._flavour.resolve(self)
>   File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
>     return _resolve(base, str(path)) or sep
>   File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
>     target = accessor.readlink(newpath)
>   File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
>     return os.readlink(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/run.py", line 250, in run
>     server.run()
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 282, in run
>     name='static'
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 926, in add_static
>     append_version=append_version)
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 484, in __init__
>     "No directory exists at '{}'".format(directory)) from error
> ValueError: No directory exists at '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 2018-06-28 20:47:23 ERROR manager.py:78 'StaticResource' object has no attribute '_directory'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 479, in __init__
>     directory = directory.resolve()
>   File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
>     s = self._flavour.resolve(self)
>   File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
>     return _resolve(base, str(path)) or sep
>   File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
>     target = accessor.readlink(newpath)
>   File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
>     return os.readlink(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/run.py", line 250, in run
>     server.run()
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 282, in run
>     name='static'
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 926, in add_static
>     append_version=append_version)
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 484, in __init__
>     "No directory exists at '{}'".format(directory)) from error
> ValueError: No directory exists at '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/raven/utils/serializer/manager.py", line 76, in transform
>     return repr(value)
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 644, in __repr__
>     name=name, path=self._prefix, directory=self._directory)
> AttributeError: 'StaticResource' object has no attribute '_directory'
> 2018-06-28 20:47:23 ERROR manager.py:78 'StaticResource' object has no attribute '_directory'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 479, in __init__
>     directory = directory.resolve()
>   File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
>     s = self._flavour.resolve(self)
>   File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
>     return _resolve(base, str(path)) or sep
>   File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
>     target = accessor.readlink(newpath)
>   File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
>     return os.readlink(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/run.py", line 250, in run
>     server.run()
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 282, in run
>     name='static'
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 926, in add_static
>     append_version=append_version)
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 484, in __init__
>     "No directory exists at '{}'".format(directory)) from error
> ValueError: No directory exists at '/usr/local/lib/python3.5/dist-packages/gns3server/static'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/raven/utils/serializer/manager.py", line 76, in transform
>     return repr(value)
>   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 644, in __repr__
>     name=name, path=self._prefix, directory=self._directory)
> AttributeError: 'StaticResource' object has no attribute '_directory'
> 2018-06-28 20:47:23 ERROR crash_report.py:112 Can't send crash report to Sentry: <urlopen error [Errno -3] Temporary failure in name resolution>

**Comment by Raizo62** [comment]
I believe that is ok, now...thanks

**Comment by Raizo62** [comment]
(When i install GNS3, it is always from scratch.)

This week, GNS3, with new install, starts good.

Do you want that i test again ?

**Comment by ziajka** [comment]
Yes please, I reverted changes, I think originally directory wasn't created but it should be.

**Comment by Raizo62** [comment]
Sorry : "Local server process has stopped"

**Comment by Raizo62** [comment]
Perhaps I must do "python3 setup.py clean --all", even with first install ?

**Comment by ziajka** [comment]
I think some bad things happened between my two commits and packages dir is inconsistent. Can you follow this procedure:
1. `rm -rf /usr/local/lib/python3.5/dist-packages/gns3server/` ( I guess sudo is needed)
2. `cd ~/location-of-gns3server`
3. `python3 setup.py clean --all`
4. install gns3server, I think you do it via: `python3 setup.py install`, am I right?
Many thanks for your help,
Dominik

**Comment by Raizo62** [comment]
I compile always GNS3 to add it to the OS "Live Raizo", then this is beginning always by "git clone"
Then, i suppose that i can't have old directory/file.....
The only persistent data is the config of GNS3

I will test "python3 setup.py clean --all"

**Comment by Raizo62** [comment]
To compile GNS3-Server, i use this command :

> python3 setup.py install --root="${MyTmp}/Packager/gns3-server/Build"

To create a debian package of GNS3

**Comment by Raizo62** [comment]
This additional parameter "--root=" can change anything ?

**Comment by ziajka** [comment]
I cannot find `--root` description in manual. It seems to package is still installed in `/usr/local/lib/python3.5/dist-packages/`. I tried with fresh install of Bionic and works fine. 
Somehow `gns3server/static` is not present in installation.
You can always run `mkdir /usr/local/lib/python3.5/dist-packages/gns3server/static` but I think root problem is different.
`python3 setup.py clean --all` only cleans when you build once.

**Comment by Raizo62** [comment]
if i patch my script and, after "`python3 setup.py install --root="${MyTmp}/Packager/gns3-server/Build"`  i add "`mkdir -p ${MyTmp}/Packager/gns3-server/Build//usr/local/lib/python3.5/dist-packages/gns3server/static`", gns3 can start....
