### ISSUE TITLE
OS X - telnet: command not found

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2537]
A variation of https://github.com/GNS3/gns3-gui/issues/2274  and https://github.com/GNS3/gns3-gui/issues/2328
See https://gns3.com/qa/-bash-telnet-command-not-found-l

The issue is, that applescript/osascript historically works with the MacRoman character set, some parts still don't work nicely with UTF-8. In our case it's `system attribute "PATH"` that's affected.

To reproduce it:
- start Terminal
- create directory 应用程序 (should be one of the most difficult test cases)
- copy telnet into it and renamed it to telnet1
- add this directory to PATH
- start gns3 from terminal

Then I changed the "Terminal" console entry to use telnet1 and removed the clear screen stuff to see all the data. So the entry got `osascript -e 'tell application "Terminal"' -e 'activate' -e 'do script "PATH=\"" & (system attribute "PATH") & "\" telnet1 %h %p"' -e 'end tell'`

When I now start the console I get this result:
![telnet_not_found](https://user-images.githubusercontent.com/896406/42712856-81c82e1a-86ed-11e8-85cc-f33419d8518f.png)

The chinese characters from the PATH get mangled, so the telnet1 binary is not found.

After some use of google I found a workaround. The trick is to capture the output of `do shell script "/bin/sh -c \"echo $PATH\""`. So my new version gets to `osascript -e 'set posix_path to do shell script "/bin/sh -c \"echo $PATH\""' -e 'tell application "Terminal"' -e 'activate' -e 'do script "PATH=\"" & posix_path & "\" telnet1 %h %p"' -e 'end tell'`.

This works:
![telnet_found](https://user-images.githubusercontent.com/896406/42713072-5d48c148-86ee-11e8-8601-bdf9a16b2f57.png)

So my suggestion is to add a `-e 'set posix_path to do shell script "/bin/sh -c \"echo $PATH\""'` directly after the osascript command and to replace `(system attribute "PATH")` by `posix_path` in all OS X PRECONFIGURED_TELNET_CONSOLE_COMMANDS (settings.py).

If you like, I can create a PR. But I can't fully test it, as I'm not able to create a frozen GNS3 app.

**Comment by ehlers** [comment]
Oh, and for the solution we choose, we have to check for spaces in the PATH. We  don't wanz to have another https://github.com/GNS3/gns3-gui/issues/2328

**Comment by grossmj** [comment]
@ehlers looks good. Please submit a PR and we would merge it and test with the next nightly build.

Thanks!

**Comment by ehlers** [comment]
@grossmj Friendly reminder: PR #2538 has been submitted more than 2 weeks ago.

**Comment by grossmj** [comment]
@ehlers Thanks, I am going to check it. It was submitted when I was travelling.

**Comment by ehlers** [comment]
Thanks for merging. I couldn't test this PATH issue with a frozen app. So I suggest, that I wait for the next nightly build and then test it with that nightly.

**Comment by grossmj** [comment]
>  I couldn't test this PATH issue with a frozen app. So I suggest, that I wait for the next nightly build and then I will test it with that nightly.

Perfect :+1: thanks again!

**Comment by ehlers** [comment]
Well, bad news. I can't start the GNS3 of the nightly build 2018-07-31 on my OS X V10.11.6, created issue #2553.

**Comment by ehlers** [comment]
Now the nightly works again. When starting from the terminal this bug fix indeed works. But as discussed in #2553, GNS3 crashes, when installed in a directory with non-latin characters and started from the Finder. Therefore this fix won't have any positive impact.

**Comment by grossmj** [comment]
Ok, let's consider this fixed and focus on why GNS3 crashes in https://github.com/GNS3/gns3-gui/issues/2553

Thanks! :+1:
