### ISSUE TITLE
GNS3 2.1.8 Error opening adapter: The system cannot find the device specified. (20)

### ISSUE THREAD

**Issue by merwina** [GNS3/gns3-gui#2542]
Hi,

I am trying to interface a router to a cloud via bridged adapter or a loopback adapter but I am getting the error exactly like on the figure. Note: I have created bridge connection between added MSLoopback and my wireless adapter. Please help as I am stucked here forever.

<img width="317" alt="gns3 error" src="https://user-images.githubusercontent.com/41494205/43029950-97bbc22e-8cbd-11e8-8514-3961a5e38e64.png">

**Comment by grossmj** [comment]
The winpcap service (NPF service) cannot find your network adapter. Try the following by starting cmd.exe as an administrator:

![network_device_list](https://user-images.githubusercontent.com/4752614/43621922-3dfc58e4-970c-11e8-9283-2793d4deca51.png)

Please post the output of network-device-list.cmd.

**Comment by sam12123** [comment]
C:\Program Files\GNS3>network-device-list.cmd

Network adapters on this machine:

NIO_gen_eth:\Device\NPF_{4DC318A0-064C-46DC-BF18-A3EF18530762}
 Name       : VMware Network Adapter VMnet8
 IP Address : 192.168.186.1
 Description: VMware Virtual Ethernet Adapter

NIO_gen_eth:\Device\NPF_{D4F98D34-39B7-46C7-90CB-1DE27C38EF27}
 Name       : Ethernet
 IP Address :
 IP Address : 10.243.79.165
 Description: Realtek Ethernet Controller

NIO_gen_eth:\Device\NPF_{6A25B786-2D1C-410C-BBC3-FA532E7DDE15}
 Name       : VMware Network Adapter VMnet1
 IP Address : 192.168.1.3
 Description: VMware Virtual Ethernet Adapter

NIO_gen_eth:\Device\NPF_{BB92D384-F10A-404D-845F-60A5F70ED3A6}
 Name       : VMware Network Adapter VMnet2
 IP Address : 192.168.174.1
 Description: VMware Virtual Ethernet Adapter

NIO_gen_eth:\Device\NPF_{DE387AC1-DE0E-46C9-B33B-1617D10FF887}
 Name       : Bluetooth Network Connection
 Description: Microsoft


Use as follows:
 F0/0 = NIO_gen_eth:\Device\NPF_{...}

**Comment by Robert-xiaoqiang** [comment]
**I am stuck in this problem.
But, The output is as follows.**
NIO_gen_eth:{0EE5E20B-52F1-48BF-99D9-CCF9839BBBD2}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: VMware Virtual Ethernet Adapter

NIO_gen_eth:{1D894A68-C0AF-4783-B690-5CABB7CDD856}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: Microsoft

NIO_gen_eth:{7A238351-6E95-4079-945B-A3CFC81F6927}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: TAP-Windows Adapter V9

NIO_gen_eth:{9AD4789A-E356-43D1-920D-E52919999167}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: Microsoft

NIO_gen_eth:{9CC6C008-9E51-4AD5-9533-92D8D4E4DF06}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: Sangfor SSL VPN CS Support System VNIC

NIO_gen_eth:{A32AD34C-4D7A-4ED1-8247-E0EBE973EE38}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: MS NDIS 6.0 LoopBack Driver

NIO_gen_eth:{41AE1BA2-36AE-4CFC-B7AB-328C982AF1BC}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: MS NDIS 6.0 LoopBack Driver

NIO_gen_eth:{81D52A09-D52F-4F5E-A671-F835BFA381DB}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: MS NDIS 6.0 LoopBack Driver

NIO_gen_eth:{E7742A23-EA81-4D2C-86CD-445E004979D6}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: Microsoft

NIO_gen_eth:{740829D0-1F42-4C9A-9424-E8A78FB80665}
ERROR: The system was unable to find the specified registry key or value.
 IP Address : DHCP
 Description: Realtek Ethernet Controller

**Comment by grossmj** [comment]
`ERROR: The system was unable to find the specified registry key or value.`

This isn't right. What is your Windows version? Do you have any security suite software or similar running?

**Comment by Robert-xiaoqiang** [comment]
Hi!
The OS is Windows 10, and GNS3 is 2.9.1.
I have installed both Win10Pcap and NPcap.
Because the Win10Pcap isn't identified by GNS3.
I don't know other security suit software running.
Thanks!

**Comment by delnomad** [comment]
Hey Robert,

I had exactly the same  problem.
To solve it:

1. Uninstall Win10Pcap and GNS3. 
2. Install Winpcap 4.1.3 (be sure that there were no errors with C:\Windows\System32\drivers\npf.sys during installation).
3. Install GNS3 (without Win10Pcap) and configure VMware vmnets interfaces

Let me know if it helps, 
-Chris

**Comment by grossmj** [comment]
@merwina @Robert-xiaoqiang we recommend to only install Winpcap 4.1.3 only at the moment. Please let us know if this work after you install winpcap and a reboot.

**Comment by Robert-xiaoqiang** [comment]
Thanks!
@grossmj @merwina 
I solved the problem by using GNS VM.
Connecting cloud device with VMware network adapter works in my case.
I gave up connecting it with loopback.
-Chris

**Comment by jleon-27** [comment]
@grossmj  hermano saludos desde Vzla segui los pasos de la imagen que dejaste y me funciono pepa(pepa=genial(cologialmente hablando)). un abrazo y feliz año nuevo 2020

**Comment by safeblood** [comment]
thanks that's really solved my problem!

**Comment by iamshakeelashraf** [comment]
> grossmj

Thanks, its works for me.
