### ISSUE TITLE
IOS XRv9k no interfaces detected

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2544]
I've been trying to figure out why my IOS XRv-9k device (version 6.4.1, but also the case with previous verisons) boots up and doesn't detect any interfaces in GNS3, but the same image in EVE-NG has no problem seeing the interfaces.  I believe it has to do with the net options being passed to qemu, but haven't figured it out yet.

GNS3 is running the following command line:
/usr/bin/qemu-system-x86_64 -name R1 -m 16384M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/gns3/projects/70052219-2e34-460e-b0e0-9db98dd4e01a/project-files/qemu/2414c248-bd37-493b-b93d-531feb599b31/hda_disk.qcow2,if=virtio,index=0,media=disk -uuid 2414c248-bd37-493b-b93d-531feb599b31 -serial telnet:127.0.0.1:2013,server,nowait -monitor tcp:127.0.0.1:34047,server,nowait -net none -device virtio-net-pci,mac=50:00:00:01:00:01,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10255,localaddr=127.0.0.1:10254 -device virtio-net-pci,mac=50:00:00:01:00:02,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10257,localaddr=127.0.0.1:10256 -device virtio-net-pci,mac=50:00:00:01:00:03,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10259,localaddr=127.0.0.1:10258 -device virtio-net-pci,mac=50:00:00:01:00:04,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10261,localaddr=127.0.0.1:10260 -device virtio-net-pci,mac=50:00:00:01:00:05,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10263,localaddr=127.0.0.1:10262 -device virtio-net-pci,mac=50:00:00:01:00:06,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10265,localaddr=127.0.0.1:10264 -device virtio-net-pci,mac=50:00:00:01:00:07,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10267,localaddr=127.0.0.1:10266 -smp 4 -nographic

The device boots but doesn't show any interfaces besides management:
<pre>
RP/0/RP0/CPU0:ios#sh ipv4 int br
Tue Jul 24 21:38:53.792 UTC

Interface                      IP-Address      Status          Protocol Vrf-Name
MgmtEth0/RP0/CPU0/0            unassigned      Shutdown        Down     default
RP/0/RP0/CPU0:ios#
</pre>
On the EVE-NG side, booting the same image appears to result in a few instances being called, but also the net parameters seem to be different:

/opt/unetlab/wrappers/qemu_wrapper -T 0 -D 1 -t xrv9k -F /opt/qemu/bin/qemu-system-x86_64 -d 0 -- -nographic -device virtio-net-pci,addr=3.0,multifunction=on,netdev=net0,mac=50:00:00:01:00:00 -netdev tap,id=net0,ifname=vunl0_1_0,script=no -device virtio-net-pci,addr=3.1,multifunction=on,netdev=net1,mac=50:00:00:01:00:01 -netdev tap,id=net1,ifname=vunl0_1_1,script=no -device virtio-net-pci,addr=3.2,multifunction=on,netdev=net2,mac=50:00:00:01:00:02 -netdev tap,id=net2,ifname=vunl0_1_2,script=no -device virtio-net-pci,addr=3.3,multifunction=on,netdev=net3,mac=50:00:00:01:00:03 -netdev tap,id=net3,ifname=vunl0_1_3,script=no -device virtio-net-pci,addr=3.4,multifunction=on,netdev=net4,mac=50:00:00:01:00:04 -netdev tap,id=net4,ifname=vunl0_1_4,script=no -device virtio-net-pci,addr=3.5,multifunction=on,netdev=net5,mac=50:00:00:01:00:05 -netdev tap,id=net5,ifname=vunl0_1_5,script=no -device virtio-net-pci,addr=3.6,multifunction=on,netdev=net6,mac=50:00:00:01:00:06 -netdev tap,id=net6,ifname=vunl0_1_6,script=no -smp 4 -m 16384 -name xrv9k -uuid 0f4d0962-9ba3-4b5f-a642-c7a62f4845c1 -drive file=virtioa.qcow2,if=virtio,bus=0,unit=0,cache=none -enable-kvm -smbios type=1,manufacturer=cisco,product="Cisco IOS XRv 9000",uuid=97fc351b-431d-4cf2-9c01-43c283faf2a3 -machine type=pc,accel=kvm,usb=off -serial mon:stdio -nographic -nodefconfig -nodefaults -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -realtime mlock=off -no-shutdown -boot order=c -serial null -serial null -serial null -cpu host

/opt/unetlab/wrappers/qemu_wrapper -T 0 -D 1 -t xrv9k -F /opt/qemu/bin/qemu-system-x86_64 -d 0 -- -nographic -device virtio-net-pci,addr=3.0,multifunction=on,netdev=net0,mac=50:00:00:01:00:00 -netdev tap,id=net0,ifname=vunl0_1_0,script=no -device virtio-net-pci,addr=3.1,multifunction=on,netdev=net1,mac=50:00:00:01:00:01 -netdev tap,id=net1,ifname=vunl0_1_1,script=no -device virtio-net-pci,addr=3.2,multifunction=on,netdev=net2,mac=50:00:00:01:00:02 -netdev tap,id=net2,ifname=vunl0_1_2,script=no -device virtio-net-pci,addr=3.3,multifunction=on,netdev=net3,mac=50:00:00:01:00:03 -netdev tap,id=net3,ifname=vunl0_1_3,script=no -device virtio-net-pci,addr=3.4,multifunction=on,netdev=net4,mac=50:00:00:01:00:04 -netdev tap,id=net4,ifname=vunl0_1_4,script=no -device virtio-net-pci,addr=3.5,multifunction=on,netdev=net5,mac=50:00:00:01:00:05 -netdev tap,id=net5,ifname=vunl0_1_5,script=no -device virtio-net-pci,addr=3.6,multifunction=on,netdev=net6,mac=50:00:00:01:00:06 -netdev tap,id=net6,ifname=vunl0_1_6,script=no -smp 4 -m 16384 -name xrv9k -uuid 0f4d0962-9ba3-4b5f-a642-c7a62f4845c1 -drive file=virtioa.qcow2,if=virtio,bus=0,unit=0,cache=none -enable-kvm -smbios type=1,manufacturer=cisco,product="Cisco IOS XRv 9000",uuid=97fc351b-431d-4cf2-9c01-43c283faf2a3 -machine type=pc,accel=kvm,usb=off -serial mon:stdio -nographic -nodefconfig -nodefaults -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -realtime mlock=off -no-shutdown -boot order=c -serial null -serial null -serial null -cpu host

/opt/qemu/bin/qemu-system-x86_64 -nographic -device virtio-net-pci,addr=3.0,multifunction=on,netdev=net0,mac=50:00:00:01:00:00 -netdev tap,id=net0,ifname=vunl0_1_0,script=no -device virtio-net-pci,addr=3.1,multifunction=on,netdev=net1,mac=50:00:00:01:00:01 -netdev tap,id=net1,ifname=vunl0_1_1,script=no -device virtio-net-pci,addr=3.2,multifunction=on,netdev=net2,mac=50:00:00:01:00:02 -netdev tap,id=net2,ifname=vunl0_1_2,script=no -device virtio-net-pci,addr=3.3,multifunction=on,netdev=net3,mac=50:00:00:01:00:03 -netdev tap,id=net3,ifname=vunl0_1_3,script=no -device virtio-net-pci,addr=3.4,multifunction=on,netdev=net4,mac=50:00:00:01:00:04 -netdev tap,id=net4,ifname=vunl0_1_4,script=no -device virtio-net-pci,addr=3.5,multifunction=on,netdev=net5,mac=50:00:00:01:00:05 -netdev tap,id=net5,ifname=vunl0_1_5,script=no -device virtio-net-pci,addr=3.6,multifunction=on,netdev=net6,mac=50:00:00:01:00:06 -netdev tap,id=net6,ifname=vunl0_1_6,script=no -smp 4 -m 16384 -name xrv9k -uuid 0f4d0962-9ba3-4b5f-a642-c7a62f4845c1 -drive file=virtioa.qcow2,if=virtio,bus=0,unit=0,cache=none -enable-kvm -smbios type=1,manufacturer=cisco,product="Cisco IOS XRv 9000",uuid=97fc351b-431d-4cf2-9c01-43c283faf2a3 -machine type=pc,accel=kvm,usb=off -serial mon:stdio -nographic -nodefconfig -nodefaults -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -realtime mlock=off -no-shutdown -boot order=c -serial null -serial null -serial null -cpu host

/opt/qemu/bin/qemu-system-x86_64 -nographic -device virtio-net-pci,addr=3.0,multifunction=on,netdev=net0,mac=50:00:00:01:00:00 -netdev tap,id=net0,ifname=vunl0_1_0,script=no -device virtio-net-pci,addr=3.1,multifunction=on,netdev=net1,mac=50:00:00:01:00:01 -netdev tap,id=net1,ifname=vunl0_1_1,script=no -device virtio-net-pci,addr=3.2,multifunction=on,netdev=net2,mac=50:00:00:01:00:02 -netdev tap,id=net2,ifname=vunl0_1_2,script=no -device virtio-net-pci,addr=3.3,multifunction=on,netdev=net3,mac=50:00:00:01:00:03 -netdev tap,id=net3,ifname=vunl0_1_3,script=no -device virtio-net-pci,addr=3.4,multifunction=on,netdev=net4,mac=50:00:00:01:00:04 -netdev tap,id=net4,ifname=vunl0_1_4,script=no -device virtio-net-pci,addr=3.5,multifunction=on,netdev=net5,mac=50:00:00:01:00:05 -netdev tap,id=net5,ifname=vunl0_1_5,script=no -device virtio-net-pci,addr=3.6,multifunction=on,netdev=net6,mac=50:00:00:01:00:06 -netdev tap,id=net6,ifname=vunl0_1_6,script=no -smp 4 -m 16384 -name xrv9k -uuid 0f4d0962-9ba3-4b5f-a642-c7a62f4845c1 -drive file=virtioa.qcow2,if=virtio,bus=0,unit=0,cache=none -enable-kvm -smbios type=1,manufacturer=cisco,product=Cisco IOS XRv 9000,uuid=97fc351b-431d-4cf2-9c01-43c283faf2a3 -machine type=pc,accel=kvm,usb=off -serial mon:stdio -nographic -nodefconfig -nodefaults -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -realtime mlock=off -no-shutdown -boot order=c -serial null -serial null -serial null -cpu host

With the above config, the instance boots and the interfaces are shown:
<pre>
RP/0/RP0/CPU0:ios#sh ipv4 int br
Tue Jul 24 21:46:48.396 UTC

Interface                      IP-Address      Status          Protocol Vrf-Name
MgmtEth0/RP0/CPU0/0            unassigned      Shutdown        Down     default
GigabitEthernet0/0/0/0         unassigned      Shutdown        Down     default
GigabitEthernet0/0/0/1         unassigned      Shutdown        Down     default
GigabitEthernet0/0/0/2         unassigned      Shutdown        Down     default
GigabitEthernet0/0/0/3         unassigned      Shutdown        Down     default
RP/0/RP0/CPU0:ios#
</pre>
I know that the config on the net interfaces differs, but I don't yet know enough about the internal workings of qemu to make the changes compatible with gns3.  But as it is, XRv9k does not work and maybe nobody has checked it in a long time :)

Thanks for your help!

**Comment by EB-athila** [comment]
Hi,

Per asr9kv documentation: "The CPU flags must be passed into the VM and must include the sse4_2
flag in order for the embedded Dataplane to work". Add the "-cpu host" kvm option.

**Comment by CapnCheapo** [comment]
Confirmed working.  I will add the changes to https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosxrv9k.gns3a

**Comment by CapnCheapo** [comment]
Reopening to get feedback on a related problem.  Since the xrv9k reserves 2 interfaces internally that puts our mapping off by two, meaning to use g0/0/0/0 on the device you have to connect to interface g0/0/0/2 in GNS3.  

I don't know of a way around this issue by changing the port name format.  

Does a new feature request need to be added here?

**Comment by CapnCheapo** [comment]
Yes that's perfect. Thanks.
