### ISSUE TITLE
Remote server settings & gns3 restart

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2545]
Noticed lots of issues related to remote server configuration, the configuration s not taken into consideration only after restarting GNS3.

If the issue is confirmed and this how it is supposed to work, we need to inform the user that gns3 restart is required for the new settings to take effect.

**Comment by Fathurhoho** [comment]
What kind of configuration did you mean?
Yes, gns3-server required restart in some way, for example after upgraded the version.  We just need restart the service without loosing our project.
