### ISSUE TITLE
Cannot telnet to QEMU image

### ISSUE THREAD

**Issue by kavinvin** [GNS3/gns3-gui#2546]
I installed Debian 9.5 on QEMU image then imported it to GNS3. But when I run and telnet to it, it outputs nothing in the terminal. I've tried `-nographic` flag, but it didn't work either.

(VNC works fine though)

**Comment by grossmj** [comment]
Serial console must be configured in Debian itself in order for the terminal to work. See https://www.hiroom2.com/2017/06/19/debian-9-grub2-and-linux-with-serial-console/ (untested)
