### ISSUE TITLE
Boot Priority missing when installing an Appliance

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2548]
GNS3 version 2.1.8 on Darwin (64-bit) with Python 3.6.5 Qt 5.9.3 and PyQt 5.9.2.

As an example I took the brocade-vrouter.gns3a appliance (<https://github.com/GNS3/gns3-registry/blob/master/appliances/brocade-vrouter.gns3a>) by using File / Import appliance. The imports works without any errors, but the boot_priority from the appliance file is lost.

When starting GNS3 with debug the add_appliance function (in registry/config.py) displays, that the boot_priority setting is not imported, while it's clearly in the appliance file:
`2018-07-30 13:49:10 DEBUG config.py:283 Add appliance QEMU: {'server': 'vm', 'name': 'vRouter 17.1.1', 'usage': '60 days evaluation. The Brocade vRouter must be on-line and have public connectivity in order to communicate with the Brocade licensing server for automated license key generation. Please note that the evaluation software will only run for 24 hours after installation without the activation code being entered into the system. You must enter your activation code in order to retrieve your licensing key after you install the Brocade vRouter software. Default credentials: vyatta / vyatta', 'category': 0, 'symbol': ':/symbols/router.svg', 'adapter_type': 'virtio-net-pci', 'adapters': 8, 'cpu_throttling': 0, 'cpus': 1, 'ram': 4096, 'console_type': 'telnet', 'legacy_networking': False, 'process_priority': 'normal', 'options': '-smp 4 -cpu host -nographic', 'hda_disk_image': 'empty8G.qcow2', 'cdrom_image': 'vyatta-vrouter-17.1.1_B_amd64.iso', 'hdb_disk_image': '', 'hdc_disk_image': '', 'hdd_disk_image': '', 'bios_image': '', 'initrd': '', 'kernel_image': '', 'hda_disk_interface': 'virtio', 'hdb_disk_interface': 'ide', 'hdc_disk_interface': 'ide', 'hdd_disk_interface': 'ide', 'kernel_command_line': '', 'qemu_path': '/usr/bin/qemu-system-x86_64', 'port_name_format': 'eth{0}'}`

**Comment by ehlers** [comment]
Found it, add_appliance() looks for the boot_priority parameter in the main level, not in qemu sub-level.

```
diff --git a/gns3/registry/config.py b/gns3/registry/config.py
index 05852462..3f188fa1 100644
--- a/gns3/registry/config.py
+++ b/gns3/registry/config.py
@@ -265,8 +265,8 @@ class Config:
         else:
             new_config["qemu_path"] = "qemu-system-{}".format(appliance_config["qemu"]["arch"])
 
-        if "boot_priority" in appliance_config:
-            new_config["boot_priority"] = appliance_config["boot_priority"]
+        if "boot_priority" in appliance_config["qemu"]:
+            new_config["boot_priority"] = appliance_config["qemu"]["boot_priority"]
 
         if "first_port_name" in appliance_config:
             new_config["first_port_name"] = appliance_config["first_port_name"]
```

**Comment by grossmj** [comment]
Thanks for catching that. It is fixed now.
