### ISSUE TITLE
Bug with VirtualBox ethernet adapters

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#255]
```
2015-03-31 7:16 GMT-06:00 David:
Bonjour Jérémy

Un nouveau bug. Cette fois ci sur l'attribution des cartes réseaux sur les virtualbox.

Dans la config de GNS3, je crée une VM avec 6 cartes réseaux (donc de eth0 à eth5). J'ai décoché "Allow GNS3 to...."

Ensuite, sur un lab, je place ma VM. Je connecte ensuite 2 câbles réseaux. Un sur e0 et l'autre e5 (donc la dernière)

Une fois, la VM démarrée, elle voit bien 2 interfaces mais appelée eth0 et eth1. eth1 correspondant à e5 sur GNS3
```

**Comment by Raizo62** [comment]
Hi

Same idea :

You create into GNS3's config an VMbox with 6 networks cards.

On your lab, you put this VM but without connected links. After boot, your VM is seeing 0 network card. It must see 6 networks cards but unlinked.

**Comment by noplay** [comment]
I think we need an hash here:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/virtualbox/virtualbox_vm.py#L65

**Comment by Raizo62** [comment]
perhaps, i don't know....but, can you solve this bug ? :-(

**Comment by noplay** [comment]
I'm on it but it's harder than expected :(

**Comment by noplay** [comment]
PR added on server:
https://github.com/GNS3/gns3-server/pull/135
