### ISSUE TITLE
Feature Request: Supported Markdown Formatting in Readme Project

### ISSUE THREAD

**Issue by Fathurhoho** [GNS3/gns3-gui#2550]
Supported formatting text would be great in readme, especially when we put the command or the output of command with `code format`, and keep it read friendly.

**Comment by grossmj** [comment]
> QTextDocument supports reading and writing Markdown format

Looks like Markdown is supported since Qt 5.14 (https://wiki.qt.io/New_Features_in_Qt_5.14)

**Comment by grossmj** [comment]
Implemented.
