### ISSUE TITLE
OS X Nightly build 2018-07-25 crashes on startup

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2553]
GNS3 version 2.1-nightly on Darwin v10.11.6 (64-bit)

I can't start GNS3 of the nightly build v2.1 from 2018-07-25 on my OS X v10.11.6, but the official v2.1.8 image works. Tested also nightly 2018-07-31, same issue. The nightly crashes very early during the initialization.

Starting from Terminal:
```
/Users/behlers# /Applications/GNS3.app/Contents/MacOS/gns3
Fatal Python error: initfsencoding: unable to load the file system codec
ImportError: invalid flags 1530079561 in 'encodings'

Current thread 0x00007fff78ab6000 (most recent call first):
Abort trap: 6
```

This look very similar to #2325, but the cx_Freeze software hasn't changed since end of last year.

**Comment by ehlers** [comment]
Found issue https://github.com/anthony-tuininga/cx_Freeze/issues/399
Do you use Python 3.7? If yes, can you try using Python 3.6? The working official GNS3 v2.1.8 uses Python 3.6.5, that might be the difference.

**Comment by grossmj** [comment]
I have forced the nightly build process to use Python version 3.6.5. Hopefully this fixes the problem: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-01/2.1/GNS3-2.1.8.dmg/download

**Comment by ehlers** [comment]
That version aborts with the same error message(`Fatal Python error: initfsencoding: unable to load the file system codec - ImportError: invalid flags 1530079561 in 'encodings'`). So there must be something else, that causes this issue.

**Comment by grossmj** [comment]
Looks like the build process still uses Python 3.7 even if I install version 3.6.5 with homebrew before :/

**Comment by ehlers** [comment]
If the build process automatically upgrades the brew packages, you will get back version 3.7. If that's the case you can use `brew pin python` to tell brew, that the python installation should kept unchanged.

**Comment by grossmj** [comment]
I had to force the version of Sip and PyQt in homebrew as well to have the build process use Python 3.6.5.

Please give it a try and let me know if this works: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-05/2.1/GNS3-2.1.8.dmg/download

Thanks!

**Comment by ehlers** [comment]
The good news is, that it works as well as the official GNS3. So switching to python 3.6.5 helped.

But both the official version as the nightly crash on double-clicking it's icon, when installed in /Applications/应用, generating an OS X crash report. Starting that from the console works, both with `open -a gns3` as well as  `/Applications/应用/GNS3.app/Contents/MacOS/gns3`.  Installing GNS3 in a subdirectory of /Applications with a simple name like "Local" works. Also other applications (including my starter for the non-frozen GNS3) work, when moving to the subdirectory with the Chinese name. Using the german a-umlaut (ä) as a directory name also crashes the GNS3 application, when starting it from the Finder. So any non-ascii directory name seems to be a bad choice for starting GNS3. I have no idea, what causes this crash, but as it works when starting it from the terminal it's extremely difficult to debug.

**Comment by grossmj** [comment]
Damn, why do we always get issues with macOS? :(

I guess we have the same problem with previous version of GNS3, right?

**Comment by ehlers** [comment]
GNS3 v1.5.3 and v2.0.3 are working (just tested, that they are starting). GNS3 v2.1.0a1 is the last one, that starts fine, v2.1.0a2 crashes, when started by Finder (starts fine, when started from terminal). 2.1.0a1 is the last version, that uses python 3.5, GNS3 v2.1.0a2 uses python 3.6.

**Comment by grossmj** [comment]
Thanks for testing these. Unfortunately it is difficult to force Python 3.5 in the build process (if Python is indeed the reason of the crash) and I am not really sure it is worth it anyway, do we really expect users to put GNS3.app in a directory with a name containing non-ascii characters?

**Comment by ehlers** [comment]
Installing GNS3 outside the /Applications directory is a very special case, otherwise we would have a big number of complains. I won't go back to Python 3.5, I assume, that will cause bigger issues in the long run. So perhaps we should just close it and define the installation path issue as a restriction for OS X.

**Comment by grossmj** [comment]
Sounds good, let's close this. I have added a note to our documentation regarding this.
