### ISSUE TITLE
Feature Request: Directory/Subdirectory in Projects Library

### ISSUE THREAD

**Issue by Fathurhoho** [GNS3/gns3-gui#2554]
(sorry i accidentally entered the submit button)

This request is for projects library management, it's better to show projects library by directory rather than single file. We are using gns3 server with multiple user, and each users doesn't have separation for their projects (at this time we include our name in project name). 

Also sometime we have project file that contains some tasks, task1, task2, and so on, so subdirectory'd be useful for this. 

This is how our projects library looks right now: https://i.imgur.com/VuKLr3X.jpg

Thanks

**Comment by cioby23** [comment]
This request is similar to this one: https://github.com/GNS3/gns3-gui/issues/2233 so I think it can be closed as a duplicate.

**Comment by grossmj** [comment]
Agreed.
