### ISSUE TITLE
Request: Reinitialize console connection to a device

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2555]
Is there a way to reinitialize console connection to a device? (Not just open a telnet session)

The motivation behind it is that, sometimes the console connection is lost even though the device is still running normally and the user has to restart the device to regain access to console.
https://gns3.com/qa/device-suddenly-can-t-console-bu

**Comment by grossmj** [comment]
Implemented. Please see https://github.com/GNS3/gns3-server/issues/1619#issuecomment-663960925
