### ISSUE TITLE
lock gns3 project from changes

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2559]
Would be nice to have option to LOCK project from changes. 
Currently very easy to mess up topology (Sometimes even by pressing RMB node could move and it damage topology). As it is autosaving and you don't have backup it could be challenging.

**Comment by b-ehlers** [comment]
Isn't that implemented with v2.2?

**Comment by grossmj** [comment]
Yes, you can lock items now but I think @vint66  wants a "read-only mode" preventing him to delete a node or make any other changes.

@vint66 can you give us a bit more details please? Thanks

**Comment by b-ehlers** [comment]
The lock mode in 2.2 already prevents a locked node to get deleted.

**Comment by grossmj** [comment]
True, forgot about that. Let's wait for @vint66 to tell us if the current lock mode is enough for him.

**Comment by vint66** [comment]
Basically idea was to prevent topology from accidentally deleting or moving node/element. I believe it is already implemented and I use it for a while now.
Thank you for so great product, Jeremy!

**Comment by grossmj** [comment]
Perfect, thanks :+1:
