### ISSUE TITLE
gns3 doesn't work while VPN is connected

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-gui#2560]
The image /home/n30x/KVM/templates/winsrv16-base.img is missing
Timeout after 30 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
Error while getting appliance templates list: Network session error.
Error while getting appliances list: Network session error.
Error while getting compute list: Network session error.
Error while getting appliance templates list: Network session error.
Error while getting appliances list: Network session error.
Error while getting compute list: Network session error.

Timeout after 5 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 5 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 10 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 5 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 5 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 5 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 10 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version
Timeout after 10 seconds for request http://riTawhZiHk02rSJIbPrR4XG1E1N69WqPRnZEnRSGjB0gdALt69Q2ZJHgajtnUWUP@127.0.0.1:3080/v2/version

**Comment by grossmj** [comment]
I think this is due to a bug with network changes (Wifi adapter going down, new VPN etc.), similar to https://github.com/GNS3/gns3-gui/issues/2104.

Please, can you try to start the VPN first and then GNS3?

Thanks!

**Comment by grossmj** [comment]
What version of Qt is install?

Thanks!

**Comment by grossmj** [comment]
This should be fixed now. Make sure Qt >= version 5.9 is installed.
