### ISSUE TITLE
Ability to consolidate few VMs into one logical instance

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2561]
Hi GNS3 team,

It could be nice idea to have option to consolidate few VMs into one logical instance on the Project Map. For example Juniper vMX required creation of two VMs for CP and FP but it is actually only one device and communication between it could be done on background (same for ALU and may be others).

**Comment by grossmj** [comment]
I like the idea but I think this would be too complicated to implement. We would rather work on a feature that brings more to our users.
