### ISSUE TITLE
GNS3 crashes: Faulty libeay32.dll

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2564]
From the community forum:

https://gns3.com/qa/path-libeay32-dll-error

--------------

- GNS3: version 2.1.9
- OS: Windows 10

![image](https://user-images.githubusercontent.com/1716020/44315010-fa97e480-a41f-11e8-820c-43233dc46b39.png)

**Comment by grossmj** [comment]
Looks like this is similar to https://github.com/GNS3/gns3-server/issues/1311

The solution is probably to upgrade Qt in GNS3 version 2.1.10 (to match the one we use in the development version of 2.2) but I don't feel comfortable making such a change which could have unintended consequences.

**Comment by grossmj** [comment]
I have upgraded anyway because this is a serious problem. This will fix that issue just like with https://github.com/GNS3/gns3-server/issues/1311
