### ISSUE TITLE
2.2 : Bug : The "all devices" dock doesn't show new device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2565]
Hi

With GNS3, i add a new docker device (with defaults values)
Then i don't see this device in the dock "all devices". I must restart GNS3 to see it.

I have the same bug if i want to add a new device with CLI :
`wget -q --user=user --password=user --post-file="NewConfigOfGNS3.json" "http://localhost:3080/v2/settings"`

**Comment by grossmj** [comment]
Is this in version 2.2?

**Comment by Raizo62** [comment]
Yes

**Comment by grossmj** [comment]
Thanks for catching that. Please note that 2.2 is actively being developed, so this can break anytime. I am going to fix this soon.

**Comment by Raizo62** [comment]
yes, but i need functionnality only in 2.2 :-( 
( Example : QEmu VMs detect plugged/unplugged networks cards )
