### ISSUE TITLE
Could not determine the Qemu version for /usr/bin/qemu-system-x86_64

### ISSUE THREAD

**Issue by reke592** [GNS3/gns3-gui#2574]
I install GNS3 (gns3/ppa) yesterday, when adding a pfSense appliance it shows and error about JSON: 'dc' not included in [ ... ] ...

I tried to reinstall the gns3-gui and gns3-server using pip3,
when running gns3 it returns an error about sip,
I install sip,
then it returns Qt5 not installed properly, so I remove the gns3-gui and gns3-server, and then reinstall the GNS3 from ppa.

now I can't create the appliance.
Qemu binaries:
Could not determine the Qemu version for /usr/bin/qemu-system-x86_64

I encountered another error about libcacard.so.0 when trying to run kvm. I download the Qemu and rebuild the binaries, now it's working but still the GNS3 can't determine the Qemu version.

> $ ~ ls -la /usr/bin | grep qemu
-rwxr-xr-x  1 root root     1094120 Jul 18 20:35 qemu-img
-rwxr-xr-x  1 root root     1174512 Jul 18 20:35 qemu-io
-rwxr-xr-x  1 root root     1066056 Jul 18 20:35 qemu-nbd
-rwxr-xr-x  1 root root     8873104 Jul 18 20:35 qemu-system-aarch64
-rwxr-xr-x  1 root root     8705040 Jul 18 20:35 qemu-system-arm
-rwxr-xr-x  1 root root     8407392 Jul 18 20:35 qemu-system-i386
-rwxr-xr-x  1 root root     8466464 Jul 18 20:35 qemu-system-x86_64
lrwxrwxrwx  1 root root          18 Jul 18 20:34 qemu-system-x86_64-spice -> qemu-system-x86_64

here's my kvm version
>kvm --version
QEMU emulator version 3.0.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

**Comment by grossmj** [comment]
What do you see if you type `/usr/bin/qemu-system-x86_64 --version` in a terminal?

**Comment by reke592** [comment]
> $ ~ /usr/bin/qemu-system-x86_64 --version
/usr/bin/qemu-system-x86_64: error while loading shared libraries: libcacard.so.0: cannot open shared object file: No such file or directory


>$ ~ ldd /usr/bin/qemu-system-x86_64
	linux-vdso.so.1 =>  (0x00007fff109f3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3669ca8000)
	libaio.so.1 => /lib/x86_64-linux-gnu/libaio.so.1 (0x00007f3669aa6000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f36697fe000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f36695fb000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f36693f0000)
	libbluetooth.so.3 => /usr/lib/x86_64-linux-gnu/libbluetooth.so.3 (0x00007f36691ce000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f3668fac000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f3668d83000)
	libbrlapi.so.0.6 => /lib/x86_64-linux-gnu/libbrlapi.so.0.6 (0x00007f3668b77000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f3668877000)
	libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f3668627000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f3668422000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f36681fd000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f3667fa4000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f3667d89000)
	libSDL-1.2.so.0 => /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0 (0x00007f3667af0000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f36677b6000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f3667580000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f3667250000)
	libxenstore.so.3.0 => /usr/lib/x86_64-linux-gnu/libxenstore.so.3.0 (0x00007f3667046000)
	libxenctrl-4.6.so => /usr/lib/x86_64-linux-gnu/libxenctrl-4.6.so (0x00007f3666e17000)
	libxenguest-4.6.so => /usr/lib/x86_64-linux-gnu/libxenguest-4.6.so (0x00007f3666bee000)
	libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x00007f36669a9000)
	libfdt.so.1 => /usr/lib/x86_64-linux-gnu/libfdt.so.1 (0x00007f36667a2000)
	libspice-server.so.1 => /usr/lib/x86_64-linux-gnu/libspice-server.so.1 (0x00007f3666473000)
	libcacard.so.0 => not found
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f366625b000)
	libusbredirparser.so.1 => not found
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f3666057000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f3665d46000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3665b3e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3665835000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f366561f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3665402000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3665038000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f366ad67000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3664e34000)
	libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x00007f3664c29000)
	libpulsecommon-8.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so (0x00007f36649ae000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f3664762000)
	libpulse-simple.so.0 => /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007f366455d000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f366434b000)
	libcaca.so.0 => /usr/lib/x86_64-linux-gnu/libcaca.so.0 (0x00007f3664082000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f3663e60000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f3663bfc000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f36639c9000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f36637b6000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f3663583000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f3663303000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f36630e1000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f3662e97000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f3662c2e000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f36627ea000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f366af36000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f366257a000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f366aeb0000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f3662370000)
	libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007f3662107000)
	libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f3661f01000)
	libslang.so.2 => /lib/x86_64-linux-gnu/libslang.so.2 (0x00007f3661b76000)
	libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f3661947000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f3661743000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f366153d000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f3661335000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f3661113000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f3660e32000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f3660c19000)
	libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f36609a4000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f36606fb000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f36604e0000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f36602cc000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f36600c3000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f365fe98000)

**Comment by cioby23** [comment]
It seems you miss the libcacard0 package with might be a dependency to qemu. 
Try to install it using apt-get install libcacard0 if you are running Ubuntu/Debian.

**Comment by grossmj** [comment]
> message: "Invalid JSON: 'dc' is not one of ['c', 'd', 'n' 'cn', 'cd'] in schema ... description QEMU boot priority

We have fixed the boot priority issue in https://github.com/GNS3/gns3-server/issues/1385 and things will work in version 2.1.10. 

Also, I have updated the appliance template to remove the boot priority for pfSense because it seems it was not necessary. You can download the updated template from https://raw.githubusercontent.com/GNS3/gns3-registry/master/appliances/pfsense.gns3a and import it in GNS3 using File -> Import appliance.

**Comment by reke592** [comment]
Thanks, it's now working

**Comment by ryanulr** [comment]
Hey all, sorry for re-opening such an old thread. I'm having this same problem with GNS3 2.2.8 (also posted in the forum here - https://gns3.com/community/discussion/fresh-gns3-install-cannot-determ)

It also seems however that on my VM apt is borked. When I try to install a package I get a response from apt that dpkg isn't doing what it's supposed to do. Has anyone else run into anything similar since this thread was closed?
