### ISSUE TITLE
Dynamips hypervisor process has stopped, return code: -11

### ISSUE THREAD

**Issue by rcuares** [GNS3/gns3-gui#2587]
Problem description: Cannot run Cisco IOS routers in GNS3. Getting this error messages:

> => Dynamips hypervisor process has stopped, return code: -11
> Could not send Dynamips command 'vm get_status "R1"' to 127.0.0.1:38923: Connection lost, process running: False
> Could not send Dynamips command 'vm get_status "R1"' to 127.0.0.1:38923: [Errno 32] Broken pipe, process running: False

I veried that the Dynamips was not running. I started it manually but still getting same problem.

I followed the install guide in GNS3 and external websites.

https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html#h.l56h7z55hmxm

Same problem posted in the GNS3 forum but with no resolution yet.

https://www.gns3.com/qa/install-gns3-on-ubuntu-18-04

My environment:
The operating system is Ubuntu 18.04
Running GNS3 version 2.1.9 on Linux (64-bit) with Python 3.6.5 Qt 5.9.5 and PyQt 5.10.1.

GNS3 Doctor result.

Starting checks...
Check if processor is 64 bit...
OK
Checking if AVG software is not installed...
OK
Checking for stable GNS3 version...
OK
Check if dynamips has the correct permission...
OK
Checking if experimental features are not enabled...
OK
Checking for amount of free virtual memory...
OK
Check if gns3 is not installed twice...
OK
Checking if the local server is enabled...
OK
Check if the RPF service is running (required to use Ethernet NIOs)...
OK
Check if ubridge has the correct permission...
OK
Checking if vmrun is installed...
WARNING The vmrun executable could not be found, VMware VMs cannot be used

**Comment by grossmj** [comment]
This is already known issue. Please see https://github.com/GNS3/gns3-server/issues/1363#issuecomment-416530886 for the workaround.

Thanks!

**Comment by rcuares** [comment]
The workaround works. Thank you.

**Comment by maguromaru** [comment]
ありがとうございました。

**Comment by UmarSaeed11** [comment]
This work around worked for me too.

**Comment by Mohamedhabi** [comment]
I'm using ubuntu 20.10 and the last release of GNS3 but i still get this problem, any help ?

=> Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605

**Comment by coyanadel** [comment]
help

**Comment by pythonyalfa** [comment]
ok

**Comment by desmondkang** [comment]
Hey community!
So just came across the issue of the following message pops up whenever i switched on my c7200 runinng on a ubuntu remote server:

> Dynamips hypervisor process has stopped, return code: -11

However, i managed to found the issue that was causing this.
Please check my slots arrangement for my c7200 router:
![image](https://user-images.githubusercontent.com/55220667/197114493-aca80aeb-3ff2-4230-8a27-0370d24162de.png)

The above arrangement works for me, as c7200 is booting up normally.

The problem will pop up on my side is when I change the slot5 into PA-2FE-TX module, like the following:
![image](https://user-images.githubusercontent.com/55220667/197114665-80f686f6-4156-48dc-9bce-0afd967462bc.png)

In this case, the c7200 router will boot into failure and the title error message pops up, causing the router to fail.

Hope this contributes.
