### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by korjjj** [GNS3/gns3-gui#259]
I think requirements in setup.py should be changed from == to >=
Won't run with paramiko 1.15.2, for example.
Also 'sip' should be mentioned there, it seems.

**Comment by korjjj** [comment]
Oh, and 'pyqt4'

**Comment by noplay** [comment]
Problems is PyQT 4 can be installed via pip.

**Comment by noplay** [comment]
@grossmj what did you think? It can simplify the life of some users but i fear we introduce an hard to debug.
