### ISSUE TITLE
Solar-Putty missing in Windows installer?

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2595]
When I installed GNS3-2.1.10-all-in-one.exe , I was not offered the installation of Solar-Putty. Naturally it did not install, however in the GNS3 settings, it states that Solar-Putty is included with GNS3. 

Not sure it the installer is missing Solar-Putty or if the text should be removed from GNS3 GUI?

![image](https://user-images.githubusercontent.com/24818591/45927699-2c2c3000-bf37-11e8-8f64-1f3c33128446.png)

P.S.: There are no problem after manually downloading Solar-PuTTY.exe and placing it to C:\Program Files\GNS3 .

Keep up the great work GNS3 team!

**Comment by grossmj** [comment]
@sairuscz Only the installer downloaded from gns3.com includes Solar-PuTTY. This is because of U.S. export laws which Solarwinds must strictly follow. I agree you should makes this clear in the GNS3 GUI.
