### ISSUE TITLE
Allow user to access to to the VM directory

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#260]
We need an option for opening the VM directory by left clicking on a VM in the topology.

**Comment by grossmj** [comment]
Of course this would only work for local project, right?

**Comment by noplay** [comment]
Yes we need an info box for remote project with the location on remote servers

**Comment by noplay** [comment]
I will add a vm_directory in the server object with the path to directory on the server.

**Comment by noplay** [comment]
It's done on GUI side and work for Qemu.

**Comment by noplay** [comment]
The video demo
https://www.youtube.com/watch?v=yK-YMzzqtpo&feature=em-upload_owner
