### ISSUE TITLE
Hide "out of band" management interfaces from topology

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2604]
Option to hide port connection could be very useful in case you need OOB management and don’t want see those connections on diagram.

It could be achieved by cli below (it will connect VM to specific bridge)

-netdev bridge,id=tap0,br=BRIDGE -device virtio-net-pci,netdev=tap0,mac=…

Such option could be implemented as part of network config GUI (something like - choose interface and mark them as hidden)

**Comment by b-ehlers** [comment]
As an implementation in GNS3 will take quite some time, in the mean time you might use layers as a workaround, see <https://www.b-ehlers.de/blog/posts/2020-09-06-gns3-hide-management-layer/>

**Comment by grossmj** [comment]
Links can be invisible, that should be useful to hide OOB.

![Image](https://user-images.githubusercontent.com/4752614/215477389-70448760-2177-4e2f-8506-60ba6f205444.png)
