### ISSUE TITLE
Change the size of template list on the Preferences window to relative

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2605]
https://gns3.com/community/discussion/i-installed-gns3-2-0-3-on-my-new

The box that lists the templates has a fixed size, making the New & Delete buttons disappear if the Preferences window is smaller than that. This can be confusing to the users.

**Comment by grossmj** [comment]
Should be good now.

**Comment by grossmj** [comment]
Seems it does not work on Windows.

**Comment by grossmj** [comment]
Ok this time the fix apparently works consistently across all platforms.
