### ISSUE TITLE
GNS3 fatal IO with X2GO 

### ISSUE THREAD

**Issue by kovalroma** [GNS3/gns3-gui#2609]
Trying to open GNS3 remotely with X2GO client.

An error appear:
fatal IO error 0 (Success) on X server ":50.0".
![screenshot_298](https://user-images.githubusercontent.com/20167720/47160382-1e788900-d2f0-11e8-88b0-1b605ac4a375.png)

**Comment by grossmj** [comment]
I am not really familiar with X2GO. Are you using the Windows client or something? What version do you have?

**Comment by grossmj** [comment]
> I assume the recommended way is not to run the GUI over remote desktop instead of having it locally and connect to the remote server.

Correct, this is the recommended way.

@kovalroma regarding X2GO, please try an alternative. I don't think the problem comes from GNS3.

**Comment by grossmj** [comment]
@kovalroma can you try to comment the following line in the /etc/x2go/x2goagent.options file?

```
X2GO_NXAGENT_DEFAULT_OPTIONS+=" -extension BIG-REQUESTS"
```

Then reboot the session and I hope it will work.

**Comment by grossmj** [comment]
@kovalroma ping :)

**Comment by grossmj** [comment]
Great, thanks for letting us know :+1:
