### ISSUE TITLE
bug chargement Vbox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#261]
Bug difficile à reproduire avec certitude, mais avec 20 étudiants, le même chargement passe parfois, et parfois elle échoue.

Une situation qui devrait faire apparaitre l'erreur :
Sur Linux
Je place 1 etherswitch sw0
Je place 3 etherswitch sw1, sw2 et sw3 que je connecte à sw0
Je place 3 PCs VirtualBox (en mode accès console) PC1, PC2 et PC3. Je connecte PC1 à sw1, PC2 à sw2 et PC3 à sw3.
(Je pense que les etherswitchs ne servent qu'à ralentir le processus)

Pour faire apparaitre l'erreur, Je n'ai pas besoin de démarrer le matériel.

Je sauvegarde.
Je quitte GNS3
Je relance GNS3 et je recharge le projet.
Si quitte/relance plusieurs fois (2 fois dans mon test), une VBox passe en erreur, et n'est plus connectée à son etherswitch. Dans GNS3, j'ai le message d'erreur suivant :

------------------------------

> Server error from 127.0.0.1:8000: Debian-2: VirtualBox has returned an error: VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.

---------------------------------

En cours, je ne leur demande pas d'ouvrir/fermer plusieurs fois. Le bug apparait parfois à la 1ère ouverture.

David

**Comment by noplay** [comment]
C'est la dernière version de virtualbox? 

J'ai vu passé un soucis similaire:
https://community.gns3.com/thread/7459#22734

Mais c'était moins random.

**Comment by Raizo62** [comment]
Oui, j'utilise la dernière version de virtualbox.

Cet apm, j'ai essayé en refaisant la config de gns3 (qui date de quelques commits). Les problèmes de communication persistent (aléatoirement).
Parfois, j'ai des erreurs à la fermeture de GNS3. Il semble resté bloquer puis se ferme, mais dans VirtualBox, on constate qu'une des VM est toujours présente. Ce qui pose problème pour relancer le projet.

Arrives tu à reproduire le bug (de temps en temps) ?

**Comment by noplay** [comment]
J'arrive pas à le reproduire sur mon mac :( Il faudrait que je le test sur mon desktop linux quand j'y aurais accès

**Comment by Raizo62** [comment]
Bonjour

Avec la version de GNS3 de samedi, j'ai toujours le problème. 

Aujourd'hui, sur 27 élèves, je dois en avoir eu 8 qui ont eu des messages d'erreurs sur un lab de 6 VMs. Heureusement, il suffisait de refaire le start pour que les VMs problèmatiques démarrent.

Par contre, ensuite, j'ai ensuite voulu préparer un lab similiaire à la 1ère desciption. J'ai eu plusieurs fois les problèmes à la fermeture (VMs encore présentes dans VirtualBox).

SI tu crées un lab composé de 6 ou 7 cloned VirtualBox, et que tu fermes et relances GNS3 plusieurs fois, tu devrais statistiquement reproduire le bug, non ?

**Comment by noplay** [comment]
Je suis en train d'installer un Linux sur une nouvelle machine pour pouvoir
tester.

2015-04-07 18:31 GMT+02:00 Raizo62 <notifications@github.com>:

> Bonjour
>
> Avec la version de GNS3 de samedi, j'ai toujours le problème.
>
> Aujourd'hui, sur 27 élèves, je dois en avoir eu 8 qui ont eu des messages
> d'erreurs sur un lab de 6 VMs. Heureusement, il suffisait de refaire le
> start pour que les VMs problèmatiques démarrent.
>
> Par contre, ensuite, j'ai ensuite voulu préparer un lab similiaire à la
> 1ère desciption. J'ai eu plusieurs fois les problèmes à la fermeture (VMs
> encore présentes dans VirtualBox).
>
> SI tu crées un lab composé de 6 ou 7 cloned VirtualBox, et que tu fermes
> et relances GNS3 plusieurs fois, tu devrais statistiquement reproduire le
> bug, non ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/261#issuecomment-90635648>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by Raizo62** [comment]
Peut être une proposition qui arrive trop tard, mais Je peux te passer une beta de Live Raizo...

**Comment by noplay** [comment]
Effectivement ca peut m'aider c'est avec cela qu'ils ont des soucis?
Maintenant que j'ai un PC sur mon bureau(et plus juste un macbook) je peut
tester. Je peut le mettre sur une clef USB?

2015-04-07 18:51 GMT+02:00 Raizo62 <notifications@github.com>:

> Peut être une proposition qui arrive trop tard, mais Je peux te passer une
> beta de Live Raizo...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/261#issuecomment-90643197>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by Raizo62** [comment]
Demain, je t'envoie un lien pour le télécharger. Oui, tu peux le mettre sur une clé USB (<1G est suffisant).

**Comment by Raizo62** [comment]
Je t'ai envoyé un email avec un lien vers l'iso....

**Comment by Raizo62** [comment]
Bonjour

As tu réussi à reproduire le bug ?

**Comment by noplay** [comment]
Effectivement je reproduis le bug sur debian

**Comment by noplay** [comment]
C'est apparement le VBoxManage list systemproperties qui echoue parfois ....


Un truc étrange chez moi si j'ouvre un terminal et que je lance : 
```
while true;do VBoxManage list systemproperties; done
```

Je le laisse trouné et après j'ouvre et je ferme GNS3 j'ai plus de soucis.

**Comment by Raizo62** [comment]
Bonjour

Quand tu dis que tu arrives à reproduire le bug, duquel parles tu ? ;-)
Celui au démarrage des VMs et le message d'erreur : NS_BASE_STREAM_WOULD_BLOCK
ou celui lorsqu'on ferme GNS3 et GNS3 n'arrive pas à supprimer les clones ? 

Tu utilises quelle version de Debian et VirtualBox ? J'utilise Debian Jessie et VirtualBox 4.3.26 r98988. J'ai pensé tester avec une plus vielle version de VirtualBox (Je pense que je ne pourrais pas faire ce test ce week end)

**Comment by noplay** [comment]
Celui du stream avec la vm live rezo.

**Comment by Raizo62** [comment]
Bonjour

J'ai essayé avec la vieille version de VirtualBox : 4.3.22 r98236
Le problème de fermeture reste : 6 VMs connectées à un switch ethernet. Je ne les démarre pas.  Je ne sauvegarde pas. Je quitte GNS3. J'accepte sa demande de sauvegarde. Il tarde à fermer. Dans l'interface VirtualBox, on voit qu'il reste des VMs.

J'ai essayé en faisant la même chose, mais en sauvegardant avant de quitter. Je n'ai pas eu le problème. (Sur 1 ou 2 tests, je suis d'accord que cela ne prouve pas grand chose)

Mais est ce que GNS3 ne ferait pas des actions en parallèle sur VirtualBox, ce qui lui poserait des problèmes ? (ici, je demande de fermer et je demande des infos pour créer le fichier de sauvegarde ?)

**Comment by noplay** [comment]
En théorie VirtualBox autorise les actions en parallèle.

2015-04-13 8:44 GMT+02:00 Raizo62 <notifications@github.com>:

> Bonjour
>
> J'ai essayé avec la vieille version de VirtualBox : 4.3.22 r98236
> Le problème de fermeture reste : 6 VMs connectées à un switch ethernet. Je
> ne les démarre pas. Je ne sauvegarde pas. Je quitte GNS3. J'accepte sa
> demande de sauvegarde. Il tarde à fermer. Dans l'interface VirtualBox, on
> voit qu'il reste des VMs.
>
> J'ai essayé en faisant la même chose, mais en sauvegardant avant de
> quitter. Je n'ai pas eu le problème. (Sur 1 ou 2 tests, je suis d'accord
> que cela ne prouve pas grand chose)
>
> Mais est ce que GNS3 ne ferait pas des actions en parallèle sur
> VirtualBox, ce qui lui poserait des problèmes ? (ici, je demande de fermer
> et je demande des infos pour créer le fichier de sauvegarde ?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/261#issuecomment-92232168>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by Raizo62** [comment]
"En théorie" ;-)

As tu une meilleure explication ? :-)

Est il possible de désactiver le parallélisme pour les VirtualBox pour tester ? (ou me dire où regarder pour que j'essaie )

Le problème de la fermeture a peut être la même cause que lors du chargement.

**Comment by noplay** [comment]
Je n'ai pas testé mais je pense qu'il suffit de modifier ce fichier si tu veux tester:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/virtualbox/__init__.py#L83

Dans le __init__ ajouter:
_self._lock = asyncio.Lock()_

Au début de la fonction execute ajouter
_with (yield from self._lock):_
Et indenter tous le code en dessous d'une tab

Je ne perd pas de vue ce bug report au retour de vacances de jérémy. On pourra dépiler plus vite les différents bugs.

**Comment by Raizo62** [comment]
J'ai essayé, et à 1ère vu, cela semble avoir un effet bénéfique : je n'ai pas vu d'erreur sur mes quelques essaies :-)

**Comment by noplay** [comment]
Arf notre belle architecture cassé par un bug de la couche en dessous...

2015-04-13 18:20 GMT+02:00 Raizo62 <notifications@github.com>:

> J'ai essayé, et à 1ère vu, cela semble avoir un effet bénéfique : je n'ai
> pas vu d'erreur sur mes quelques essaies :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/261#issuecomment-92415235>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by noplay** [comment]
Je vais inclure le fixe dans la 1.3.2

**Comment by Raizo62** [comment]
Bonjour

Je n'ai pas revu le bug depuis que j'ai appliqué ton patch. Et cela ne semble pas avoir d'effet gênant à l'usage.

**Comment by noplay** [comment]
C'est corrigé dans le repo de la 1.3.2

**Comment by noplay** [comment]
En théorie ca doit être plus lent. Mais ca ce voit pas.

Je suis assez content la récriture du serveur nous permet de régler ses
bugs là en deux ligne de code.

2015-04-14 15:00 GMT+02:00 Raizo62 <notifications@github.com>:

> Bonjour
>
> Je n'ai pas revu le bug depuis que j'ai appliqué ton patch. Et cela ne
> semble pas avoir d'effet gênant à l'usage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/261#issuecomment-92815315>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by Raizo62** [comment]
> C'est corrigé dans le repo de la 1.3.2

Merci :-)

> Je suis assez content la récriture du serveur nous permet de régler ses 
> bugs là en deux ligne de code.

Finalement, la refonte de "votre belle architecture" n'a pas été faite pour rien :-)
