### ISSUE TITLE
gns3-gui : PreDepends: python3.4 but it is not installable 

### ISSUE THREAD

**Issue by MahamdiAmine** [GNS3/gns3-gui#2611]
i'm using Kali linux, and  i get this message after executing the command : sudo apt-get install gns3-gui 

gns3-gui : PreDepends: python3.4 but it is not installable or
                        python3.5 but it is not installable
            Depends: gns3-server but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by grossmj** [comment]
Sorry, we do not officially provide support for Kali Linux. We don't build official packages for it.

Please try to post on our community and I am sure someone will help you.

**Comment by DavidNorena** [comment]
https://www.sysnettechsolutions.com/en/gns3/install-gns3-kali-linux/ have fun !

**Comment by Tsh-kazi** [comment]
The following packages have unmet dependencies:
 gns3-gui:i386 : PreDepends: python3.4:i386 but it is not installable or
                             python3.5:i386 but it is not installable
                 Depends: python3-pyqt5:i386 but it is not going to be installed
                 Depends: python3-pyqt5.qtsvg:i386 but it is not going to be installed
                 Depends: gns3-server:i386 but it is not going to be installed
                 Depends: wireshark:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Tsh-kazi** [comment]
anyone to help me on what i can do about that am trying to install gns3 on kali linux
