### ISSUE TITLE
BUG : 2.2 : docker and displayed customized network interface

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2613]
Hi

I create a Docker Template with 1 network interface

For this template, i configure to customize the adapters. I change the port name "eth0" to "Conn Local 1"

On a topology, i add this Docker VM and an ethernet switch.

When i want to connect the Docker to the ethernet switch : GNS3 shows "Conn Local 1". Ok.

But, after, when i click on "Shide/Hide" interface labels", GNS3 shows always "eth0"

**Comment by grossmj** [comment]
It should be fixed now.
