### ISSUE TITLE
soft lockup in KVM guest running in GNS3 Server

### ISSUE THREAD

**Issue by leninp57** [GNS3/gns3-gui#2614]
Hi

I am running GNS3 version 2.1.11 with GNS3 version 2.1.11 and I am getting this error when I try to run any image using the GNS3 Server's KVM

![error2](https://user-images.githubusercontent.com/37081123/47609670-22ec2280-da11-11e8-9b81-67eef82091e8.JPG)

![error1](https://user-images.githubusercontent.com/37081123/47609672-2bdcf400-da11-11e8-8600-5788e72e1109.JPG)

I have tried a lot of workarounds  without any luck. 

- I upgrade the Ubuntu to version 16.
- I followed this workaround https://customerhelp.co.za/linux/ubuntu/fix-ubuntu-bug-soft-lockup-cpu-stuck-vmware-server.html
- and many others

Any help will be appreciate

Thanks

**Comment by grossmj** [comment]
Honestly I don't really know what could be the source of these messages. I hope the next version of our GNS3 VM based on Ubuntu 18.04 LTS will solve this issue.

**Comment by leninp57** [comment]
Hello
Yes , I really don't now either,  I have done all the workarounds that are in Internet without any success.
I have two laptops where I run GNS3 without problems , the only think I can think is in the processor of this new laptop (I7-8650U) or some kind of feature activated by the manufacturer (Lenovo T480) that is causing the issue.
Can you tell me when the next version is going to be available?
Regards

**Comment by grossmj** [comment]
> Can you tell me when the next version is going to be available?

Most likely in January but I can probably send you a test version before.

**Comment by grossmj** [comment]
Here is a GNS3 VM built on top of Ubuntu 18.04, GNS3 version 2.1.11 is pre-installed. Note that the Qemu version is 2.11 and this could be a problem (see https://github.com/GNS3/gns3-server/issues/1335). I tested with one IOSv-L2 appliance and I didn't get any issue.

https://drive.google.com/file/d/16XucfRKYXVxO11jHJWN-i35f4gHOG5qA/view?usp=sharing

Please test and let me know if you get soft lockup errors.

**Comment by grossmj** [comment]
@leninp57 have you had a chance to try this VM? thanks :)

**Comment by leninp57** [comment]
Hello 
First of all, Thanks for your effort on this issue
I tried this VM but I am having the same problem, I try tu run an IOS-XR router and I can see in the logs that everything starts fine

 
![gns3new1](https://user-images.githubusercontent.com/37081123/50127754-d1aa2380-0248-11e9-9a74-139ad9eba918.JPG)

![gns3new2](https://user-images.githubusercontent.com/37081123/50127757-d7076e00-0248-11e9-8b93-e51a3227eee7.JPG)

But the proccess hangs up and nothing happens

![gns3new3](https://user-images.githubusercontent.com/37081123/50127782-e8507a80-0248-11e9-8204-870d081095d7.JPG)

Thanks again

Lenin

**Comment by grossmj** [comment]
@leninp57 ping

**Comment by leninp57** [comment]
Hello

This weekend I am going to perform a factory recovery on the laptop and I
will let you know how it is going

The VM has  1 cpu with 4 cores and 24 GB RAM

**Comment by grossmj** [comment]
Ok, let me know. Thanks :)

**Comment by leninp57** [comment]
Hello Jeremy

I have performed a factory reset and  I have installed the GNS3 and the
GNS3 server and everything is working fine. I don't know what was the
reason of the issue ( Driver, Antivirus program, Lenovo Utility).

Thanks for your support

Lenin,

**Comment by grossmj** [comment]
Strange but let's close this anyway.
