### ISSUE TITLE
VMware is not installed (vmware or vmplayer executable could not be found in $PATH)

### ISSUE THREAD

**Issue by orangeisnon** [GNS3/gns3-gui#2617]
On Windows Server 2012 R2, I have VMWare Workstation 11 installed in the default directory. I also have GNS3 2.1.11 installed to the default directory. I am running the GNS3 VM on an ESXi server, and it is working as expected. I have one Windows VM configured inside Workstation.
When selecting "New" in Preferences>VMware VMs in GNS3, I see the below error:
"VMware is not installed (vmware or vmplayer executable could not be found in $PATH)"
So far, I have tried adding the install directory, as well as full paths to "vmware.exe" and "vmplayer.exe" to my "Path" environment variable in Windows, followed by a reboot. No change to the error.

**Comment by grossmj** [comment]
Do you have one Windows VM running inside Workstation which is running on ESXi?

If not, have you seen the following window and have you selected "Run this VMware VM on my local computer".

![vmware_template](https://user-images.githubusercontent.com/4752614/48968412-efa5af00-f021-11e8-9c55-7f2c20aac720.png)

Please if you can, post screenshots to help understand the problem.

Thanks!

**Comment by keithseator** [comment]
I found that closing VMWare workstation first fixed this issue!
