### ISSUE TITLE
Unable to Increase memory and CPU of GNS3 VM on VMware workstation

### ISSUE THREAD

**Issue by kwadjoe** [GNS3/gns3-gui#2622]
Hello Guys
I am having an issue with my GNS3 VM version 2.1.11. Anytime i increase the Memory size and the CPU Count, the change is not registering. Anyone have an idea why this is occurring ? Please advise
thanks

**Comment by grossmj** [comment]
Have you tried to change the settings from the preferences?

![gns3_vm](https://user-images.githubusercontent.com/4752614/48968283-ca17a600-f01f-11e8-8bd8-f8dc0ef33d73.png)

Is your operating system Windows 10?

What do you have in gns3_controller.conf? This file should be in %APPDATA%\GNS3 on Windows.

**Comment by kwadjoe** [comment]
Thank you Jeremy.
I was able to figure that out after I have posted the question. That was exactly what I was missing. I though I can just change it from the VM settings.
Thank you for all the good work you have been doing.

Merci.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by grossmj** [comment]
Great, thanks :)
