### ISSUE TITLE
 Error while getting "stuff": Network access is disabled.

### ISSUE THREAD

**Issue by pa5h1nh0** [GNS3/gns3-gui#2624]
I've just installed GNS3 on Linux Mint, when trying to open the GUI as a normal user I get a bunch of `Network access is disabled` errors.
![screenshot from 2018-11-13 14-06-34](https://user-images.githubusercontent.com/3721791/48415332-605ce980-e74d-11e8-843a-32e54db26ac5.png)
As can be seen from the img capture above, there's also the `Cannot connect to http://127.0.0.1:3080` error, even though the `gns3-server` is listening and reachable on that socket (see capture below):
![screenshot from 2018-11-13 14-11-17](https://user-images.githubusercontent.com/3721791/48415568-03adfe80-e74e-11e8-9f8c-8e9a0782164c.png)
Launching `gns3server` from terminal seems all good:
`> gns3server`  
`2018-11-13 14:14:29 INFO run.py:213 GNS3 server version 2.1.11`  
`2018-11-13 14:14:29 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.`  
`2018-11-13 14:14:29 INFO run.py:218 Config file /home/h3ll0fr1end/.config/GNS3/gns3_server.conf loaded`  
`2018-11-13 14:14:29 INFO run.py:232 Running with Python 3.5.2 and has PID 12464`  
`2018-11-13 14:14:29 INFO run.py:79 Current locale is en_US.UTF-8`  
`2018-11-13 14:14:29 INFO web_server.py:283 Starting server on 127.0.0.1:3080`  
`2018-11-13 14:14:29 INFO __init__.py:65 Load controller configuration file /home/h3ll0fr1end/.config/GNS3/gns3_controller.conf`  
`2018-11-13 14:14:29 INFO __init__.py:168 Start controller`  
`2018-11-13 14:14:29 INFO compute.py:79 Create compute local`  
`2018-11-13 14:14:29 INFO compute.py:420 Connecting to compute 'local'`  
`2018-11-13 14:14:31 INFO compute.py:420 Connecting to compute 'local'`  
`2018-11-13 14:14:31 INFO helpers.py:534 127.0.0.1 [13/Nov/2018:13:14:31 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.5 aiohttp/2.3.10"`  

What can I do here to fix this?

**Comment by pa5h1nh0** [comment]
That fixed the `Cannot connect to http://127.0.0.1:3080` error. However, all those `Network access is disabled` are still there.

**Comment by grossmj** [comment]
This may be a bug with Qt 5.5.1. Is it possible to upgrade Qt?

**Comment by pa5h1nh0** [comment]
Well, upgrading Qt doesn't seem to be a fairly easy task. The "cleanest" ways to do that would be to upgrade the distro (not acceptable), or to install the pre-built packages via the `*-online.run` for which I'm unable to tell GNS3 to use that specific Qt version. What I'm leaved with is to build from source, which is pretty huge. Is there any feasible way to build only the minimum necessary stuff, in order not to find myself with 5 GB worth of Qt? I understand this might not be the best place for this question, but I'm left with no other options. Oh, is there a chance to get an older GNS3 version without this "possible" Qt issue?

**Comment by pa5h1nh0** [comment]
Solved, this had something to do with the NetworkManager saying there was no internet connection. Though, I don't understand why GNS3 would have to worry about the internet connection in the first place.

**Comment by grossmj** [comment]
:+1:  Thanks for the feedback, GNS3 should not require an Internet connection. I will investigate if we can do something on our side.

**Comment by grossmj** [comment]
I concluded this is a bug with Qt 5.5.1.
