### ISSUE TITLE
Version 2 Not working in windows 10

### ISSUE THREAD

**Issue by it2020** [GNS3/gns3-gui#2628]
I have 
![img_20181116_211454](https://user-images.githubusercontent.com/45105521/48642868-58be6e80-e9f3-11e8-8849-629c5351dfd2.jpg)
problem
I installed all version 2.1.1 - 2.1.2 -2.1.3 ... - 2.1.11 but worked just 1.4.0 - 1.4.5 and 1.3.7
In windows 10

**Comment by grossmj** [comment]
We have updated Qt to version 5.12. Hopefully, this fixes the problem. Please comment back if not.
