### ISSUE TITLE
How to register on GNS3 comunity forum?

### ISSUE THREAD

**Issue by tarucan** [GNS3/gns3-gui#2633]

**Comment by tarucan** [comment]
ther eis no register button and my gns3.com logins doesnt work on forums.
i have a problem to who i can ask?

**Comment by grossmj** [comment]
Hi,

What is your country?

**Comment by tarucan** [comment]
anyone can answer plz?
where can i post my question?
I stuck cant use GNS3.

**Comment by tarucan** [comment]
i manage this alone, tnx for nothing
