### ISSUE TITLE
Upgrade to Qt 5.12

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2636]
We have received reports of crashes on Windows. Apparently due to Qt 5.9 (we were forced to downgrade to this version in GNS3 2.1.11, https://github.com/GNS3/gns3-gui/issues/2592): https://gns3.com/community/discussion/gns3-wont-run-on-my-windows-10-m

Qt 5.12 LTS is planned to be released in December: https://wiki.qt.io/Qt_5.12_Release and hopefully this would solve these issues.

**Comment by grossmj** [comment]
Qt 5.12 is out. Waiting for PyQt to be released.

**Comment by ehlers** [comment]
PyQT 5.12 has been just released, no issues during my first test.

`Running GNS3 version 2.1.12 on Darwin (64-bit) with Python 3.6.6 Qt 5.12.1 and PyQt 5.12.`

**Comment by grossmj** [comment]
Perfect, thanks for the update :+1:

**Comment by grossmj** [comment]
Done.
