### ISSUE TITLE
2.2 : empty "all device"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2644]
Hi

I use a new default config of GNS3

When i start GNS3 for the first time, the console "all devices" have not the default devices : ethernet switch, ethernet hub, ...

I'm worried : "now", GNS3 seems to use schematic symbols for Devices (for example ethernet switch). But, i don't like them : i prefer largely the legacy symbols, more realistic. Is it also a bug or a choose ?

**Comment by grossmj** [comment]
> When i start GNS3 for the first time, the console "all devices" have not the default devices : ethernet switch, ethernet hub, ...

Do you mean the "all devices" docked window on the left?

> I'm worried : "now", GNS3 seems to use schematic symbols for Devices (for example ethernet switch). But, i don't like them : i prefer largely the legacy symbols, more realistic. Is it also a bug or a choose ?

Don't worry, we are experimenting the different symbol themes. You will be able to choose once we have finished to implement this. Everything is work in progress on 2.2 ;)

**Comment by Raizo62** [comment]
> Do you mean the "all devices" docked window on the left?

yes
> Don't worry, we are experimenting the different symbol themes. You will be able to choose once we have finished to implement this. Everything is work in progress on 2.2 ;)

ouff :-)

**Comment by grossmj** [comment]
Fixed, thanks  :+1:
