### ISSUE TITLE
GNS3 Timeouts on GNS3 VM

### ISSUE THREAD

**Issue by skeyid** [GNS3/gns3-gui#2646]
[GNS3 debug.txt](https://github.com/GNS3/gns3-gui/files/2638718/GNS3.debug.txt)
Downloaded and Installed latest version of GNS3. Along with GNS3-VM w/ VM player on windows 10 tonight. I couldn't get the GNS3 to play nicely with GNS3-VM. I'm looking for assistance on this. 

My issue is similar to issue #1027 
I have everything configured but when i opened up GNS3 it launches the GNS3-VM in VM player. But the GNS3 GUI never indicates that its on.  When i try and import an appliance specifically the ASA one. GNS-GUI keeps launching VM instances and then times out. 

I have set GNS3 and VMPlayer to always run as admin as well. I edited the GNS3 VM with the below lines as it was suggested in another issue similar to this. 
hints.hideall = "TRUE"
msg.nook = "TRUE"

Thanks

**Comment by skeyid** [comment]
Interesting enough - i found a work around. 

1. turn on GNS3VM in VMplayer
  VM NIC setting: Host-only: - A Private network shared with the host
2. open CMD run gns3server.exe 
3. open CMD run gns3.exe  

in GNS3 gui 
 -> preferences 
      * Server -> enable local checked
      * Server -> remote server -> IP of GNS3VM running locally. 
      * GNS3VM -> disable  


Why does this work this way?

**Comment by grossmj** [comment]
Something most likely wasn't configured properly. It is important that the local server and the GNS3 VM are on the same IP network and the GNS3 VM first adapter is set to host-only as shown in https://github.com/GNS3/gns3-gui/issues/2649#issuecomment-447522161
