### ISSUE TITLE
Dynamips decompress doesn't work with relative images

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2648]
See <https://gns3.com/community/discussion/how-to-load-dynamips-os-images-i>

If the Dynamips decompress function is used on a IOS router template with an absolute image path, then it works. But when the template includes only the filename as an image path, the image is not found and an error message is shown. Furthermore there is an superfluous "is" in the message.

**Comment by grossmj** [comment]
Should be fixed now. Thanks :+1:
