### ISSUE TITLE
Can't ping any devices running on the GNS3 VM

### ISSUE THREAD

**Issue by CranePet** [GNS3/gns3-gui#2649]
See related discussion at:
https://gns3.com/community/discussion/can-t-ping-any-devices-running-o

Steps to reproduce:
1. Fresh install of Windows 10 1803, no firewall, no antivirus software
2. Installed VMware Workstation Pro 15.0.2
3. Download the GNS3 VM and install
4  Download GNS3 and install
5. Set up a test project consisting of....
     One generic switch running on the host
     Two VPCS running on the host
     One VPCS running on the VM

I then connected everything up, configured the IP addresses on the 3 VPCS's, and tried to ping each in turn. The 2 VPCS's on the host pinged each other fine. Neither could pin the VPCS running on the VM (host 10.1.1.30 unreachable), nor could it ping the VPPC's running on the host.

Peter

**Comment by grossmj** [comment]
What is the IP address for the GNS3 VM and the IP address for the GNS3 local server? They need to be able to communicate.

**Comment by CranePet** [comment]
Hi Jeremy. The IP address of the GNS3 VM is 192.168.1.127/24. The IP address of the local GNS3 server is 192.168.1.196/24.  I can ping the VM IP from the local host, and vice-versa.

**Comment by grossmj** [comment]
Something isn't quite right. You should be able to ping between nodes running on the local GNS3 server and the GNS3 VM. Please can you post the following screenshots?

![gns3_settings](https://user-images.githubusercontent.com/4752614/50036919-5fc8a480-ffd2-11e8-86ad-715d2df4379a.png)

![gns3vm_settings_2](https://user-images.githubusercontent.com/4752614/50036920-5fc8a480-ffd2-11e8-8c0b-2467f52e576e.png)

![gns3vm_settings](https://user-images.githubusercontent.com/4752614/50036921-60613b00-ffd2-11e8-9560-634848a9c0e0.png)

**Comment by CranePet** [comment]
Hi Jeremy,

I was able to get it to work when I changed the Network Adapter to Bridged. After that, the local Server and the GNS3 VM were both on the same subnet.

![image](https://user-images.githubusercontent.com/33738912/50093488-d4702e80-01de-11e9-9b09-7314cabd4463.png)

![image](https://user-images.githubusercontent.com/33738912/50093624-37fa5c00-01df-11e9-8fc0-12e6460488e2.png)

**Comment by CranePet** [comment]
Sorry, same image twice.

![capture12](https://user-images.githubusercontent.com/33738912/50093705-6d06ae80-01df-11e9-9834-8959404def6e.JPG)

**Comment by CranePet** [comment]
Oh wait. I see now. If I put the Network Adapter back on Host-only, the GNS3 VM has an address of 192.168.10.132. I then set the host Server to 192.168.10.1 and all is good.

Could you tell me what the second (NAT) adapter is for? Internet access?

Thanks.

-Peter

**Comment by grossmj** [comment]
> Oh wait. I see now. If I put the Network Adapter back on Host-only, the GNS3 VM has an address of 192.168.10.132. I then set the host Server to 192.168.10.1 and all is good.

Perfect :+1: 

> Could you tell me what the second (NAT) adapter is for? Internet access?

Yes, this is for Internet access.

**Comment by grossmj** [comment]
No worries. Please open a new issue if you find a bug.

Thanks :)

**Comment by Shithappens1991** [comment]
maybe you have enable the hyper-v in Turn Windows Feature on or off. Turn off the adapter v-Ethernet (Default Switch).

**Comment by rafiirzam** [comment]
Hello, Peter
i've same problem with yours,  my GNS3 VM ip address and GNS3 local server already in same subnet and they can communicate but when i create 2 VPCS running on GNS3 VM they can't connected.
Any solution?

GNS3 version : 2.2.35.1
GNS3 VM version : 2.2.35.1
VirtualBox version : 7.0

Thanks,
Rafi

**Comment by josephmhiggins** [comment]
Rafi,
You need to create a new post on the gns3 community at gns3.com. This post was closed over 3 years ago.

**Comment by rafiirzam** [comment]
okay, joseph
thank you
