### ISSUE TITLE
GNS3VM: Error while executing VMware command: vmrun has returned an error: Unable to connect to host.

### ISSUE THREAD

**Issue by mudassir80** [GNS3/gns3-gui#2650]
Hi ,

GNS3 give this error. I have been trying different things but no luck, if someone can help much appreciated. I have installed in different location to make sure no user issue. I tried to run vmrun.exe but it just blink and nothing happens. Your help will be much appreciated as i am trying to fix this for last few weeks but no luck
*******************************************
Error while saving settings: GNS3VM: Error while executing VMware command: vmrun has returned an error: Unable to connect to host.
Error: The specified version was not found

Try to run 'D:\GN\VMware\VMware VIX\vmrun.exe' -T player checkToolsState 'C:\Users\m00269404\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx' in a terminal to see more details.
And make sure GNS3 and VMware run under the same user.
******************************

**Comment by grossmj** [comment]
Hi, what is your VMware version?

**Comment by mudassir80** [comment]
Hi Grossmj,
Thanks for the prompt reply, below is the VMware version. I also tried with older VMware player and got same error
VMware-player-15.0.1

VMware-VIX-1.15.0

GNS3-2.1.11
Using Windows 7 pro 64 bit
cheers

**Comment by mudassir80** [comment]
@grossmj  thanks for your help mate,  it works after using VMware 14

**Comment by Siddharth1133** [comment]
Im still facing the same issue with vmware 14

**Comment by langcblt** [comment]
> There is an issue with using VMware player 15. There is a workaround as explained in
> https://community.gns3.com/community/discussion/gns3-doesn-t-work-on-vmware-play but the general advise is to use VMware player 14.

I googled for vmware player 14 but couldn't find anywhere to download.  Can you provide the link pls? thanks

**Comment by langcblt** [comment]
> @grossmj thanks for your help mate, it works after using VMware 14

I googled for vmware player 14 but couldn't find anywhere to download. Can you provide the link pls? thanks

**Comment by chris4542** [comment]
This solution worked for me:

[First make sure you use VIX 1.17](https://my.vmware.com/web/vmware/downloads/details?downloadGroup=PLAYER-1400-VIX1170&productId=687)
 
Then go into VMware VIX folder and open "vixwrapper-config.txt"

At the bottom, change whatever is there to:
`
# latest un-versioned
ws       19 vmdb e.x.p Workstation-14.0.0
player   19 vmdb e.x.p Workstation-14.0.0

to

# latest un-versioned
ws       19 vmdb e.x.p Workstation-14.0.0
player   19 vmdb 15.5.6 Workstation-14.0.0
`
Save changes, & close out of GNS3 and VMware Player windows.

Reopen GNS3, and it should connect and open "GNS3 VM" in VMware Player automatically.

This works for GNS3 2.2.11, VMware Workstation Player 15.5.6 and VMware VIX 1.17.0
Hope this helps you as well. Found this solution [here](https://community.spiceworks.com/topic/2171674-gns3-vm-not-starting).

**Comment by FelixBrandstetter** [comment]
@chris4542 Your solution worked perfectly - thank you 👍
