### ISSUE TITLE
2.2 : bug with filter of add template

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2651]
Hi

I start from a default config of GNS3

I click on : 
- "New template"
- Import appliances from the GNS3 server

I see 1 time : AAA (for example)

On filter, i write "switch"

Nothing is filtered (i believe)

I remove my filter

I see 2 times : AAA

**Comment by grossmj** [comment]
This is fixed however please note that adding new appliance via the "New template" button doesn't work at the moment. We need to implement https://github.com/GNS3/gns3-gui/issues/2642 first.
