### ISSUE TITLE
GNS3 2.1.11 timeout error and  while adding a node

### ISSUE THREAD

**Issue by marvaler** [GNS3/gns3-gui#2652]
Running GNS2.1.11 while adding an IOS node i am getting a timeout error while getting compute list. This will fail over and over untill  connection is refused

Timeout after 30 seconds for request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
Timeout after 30 seconds for request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
Timeout after 30 seconds for request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
Timeout after 30 seconds for request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 120 seconds for request http://admin@127.0.0.1:3080/v2/settings
Timeout after 30 seconds for request http://admin@127.0.0.1:3080/v2/computes
Error while getting compute list: Operation timeout
[GNSerrors.txt](https://github.com/GNS3/gns3-gui/files/2677060/GNSerrors.txt)

**Comment by grossmj** [comment]
Also, check this out: https://community.gns3.com/community/discussion/timeout-after-30-seconds-for-req

**Comment by marvaler** [comment]
Thank you @grossmj i will give a try on the night, i will let you know.

**Comment by marvaler** [comment]
I am not using any VM for this

**Comment by grossmj** [comment]
Do you have any anti-virus running, something like Avast or similar?

**Comment by marvaler** [comment]
Disabling anti-virus has been the fix. Thanks a lot @grossmj

**Comment by grossmj** [comment]
Perfect :+1:  I will re-open this to see if we can have a more informative message for users facing the same problem.

**Comment by Salmane89** [comment]
Disabling Avasat didn’t fix the issue for me, but reinstalling it without the “Behavior Shield” option fixed the problem.
