### ISSUE TITLE
Error when adding Dynamips nodes

### ISSUE THREAD

**Issue by Jajao555** [GNS3/gns3-gui#2653]
I did a clean install of Linux Mint 19 and when I installed GNS3 following the directions for Ubuntu I get this error when trying to add stock Ethernet switches or add Dynamips nodes. I'm able to add a VPCS nodes fine. 

`Error while creating node: Couldn't connect to hypervisor on 127.0.0.1:58481 :[Errno 111] Connect call failed ('127.0.0.1', 58481)`

I've tried reinstalling and also making sure to add the suggested and recommended dependencies and still have the same issue. 

On a side note the first install didn't point to Dynamips in /usr/bin/ and was blank and I had to browse to the file. The second install it was added already possibly because of the other dependencies I installed?

**Comment by grossmj** [comment]
Alternatively, can you try this workaround? https://github.com/GNS3/dynamips/issues/91#issuecomment-444149596

Thanks!

**Comment by Jajao555** [comment]
Sorry I ended up going back to Mint 18.3. I'll see if I can run a VM of 19 and play around with it more but I'll close this. Thanks for the help.
