### ISSUE TITLE
[Debian 9.6 Strech] GNS3 can't ping physical devices

### ISSUE THREAD

**Issue by Rob1NNk0** [GNS3/gns3-gui#2655]
Hello,

I have a problem.

I connected my physical Cisco devices to the GNS3 virtual devices. Routers see each other, can ping each other, physical host (my laptop) can ping GNS3  virtual router but virtual router can't ping my laptop.

Connection looks like this:
GNS3 router -> real Cisco router -> real Cisco switch -> real laptop

Ping looks like this:
Real laptop pings real switch, real router, GNS3 router.
GNS3 router pings real router, real switch but won't ping real laptop (host unreachable).

Both routers are configured with EIGRP.
Switch is in its default configuration + SVI configured for telnet.

Is there something I must change/allow in Debian? Or is it just native behavior of GNS3?

**Comment by Raizo62** [comment]
Hi

Is the Firewall enable on your real laptop ?

**Comment by Rob1NNk0** [comment]
Hi,

yes, firewall is enabled on my laptop. Windows firewall and Kaspersky soft too.

**Comment by Raizo62** [comment]
You must disabled the firewall if you want to ping it ;-)

**Comment by Rob1NNk0** [comment]
Well...
Uhm..

Ye, it works now. I am stupid. 

Thank you very much :)

**Comment by Rob1NNk0** [comment]
Solved by turning off Windows firewall.

TY mr. Raizo62 :)
