### ISSUE TITLE
Req : visibility of the variable "usage"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2656]
Hi

You have a variable "usage" where you show the login/passwd (in appliances)

The data of this variable is show when the mouse is on the device.

But, it is in the middle of the block of informations. We must to seek it.

Could you put it in in the second line of the block ? After the name et before "Running..."
Or any other idea to see this information more easily?

And can we have a box to edit this information ? ;-)

**Comment by grossmj** [comment]
I think "usage" could go into an "Info" context menu item like described in https://github.com/GNS3/gns3-gui/issues/2662

**Comment by grossmj** [comment]
@Raizo62 please comment on https://github.com/GNS3/gns3-gui/issues/2662#issuecomment-450558280 about the new location for usage information.

**Comment by grossmj** [comment]
Closing this to focus on https://github.com/GNS3/gns3-gui/issues/2662
