### ISSUE TITLE
Arista vEOS Appliance - /mnt/flash Read-Only

### ISSUE THREAD

**Issue by memblin** [GNS3/gns3-gui#2659]
With the existing Arista vEOS appliance I've run into some issues. We obtained the VMDK and Aboot ISO files required by the existing appliance for 4.20.1F and 4.18.5M. We also got the new files fo 4.20.11M which is not included in the template.

Creating the new version forces us to create a renamed version of the Aboot ISO because it tries to apply the same version to the Aboot ISO that is given for the VMDK. This can be worked around by symlinking or making a copy of Aboot so that it matches what GNS3 is looking for.

![aboot_badly_named](https://user-images.githubusercontent.com/1418370/50106527-510a0980-01ed-11e9-98c1-15089f878878.png)

We can deploy all three versions after going through the Create New Version dialogue for 4.20.11M.

![aboot_present](https://user-images.githubusercontent.com/1418370/50106605-8adb1000-01ed-11e9-9047-3878b9123cb9.png)

After we deploy each of the 3 versions from the default Arista vEOS template:

 4.18.5M  - Boots and works as expected
 4.20.1F  - Boots and works as expected
 4.20.11M - Boots but mounts /mnt/flash as read-only and this breaks the VM

I found I can edit the installed templates and modify them such that the VMDK is HDA and the Aboot ISO is CDROM then deploy a new node and the node boots and works as expected.

Set Boot Priority to CD/DVD-ROM
![42011m_new_gen_settings](https://user-images.githubusercontent.com/1418370/50106857-3e440480-01ee-11e9-8dee-d65594b323a4.png)

Ensure HDA is the VMDK
![42011m_new_hdd_settings](https://user-images.githubusercontent.com/1418370/50106877-49973000-01ee-11e9-9702-d9c2efe33398.png)

Ensure ISO is set in CDROM
![42011m_new_cd_settings](https://user-images.githubusercontent.com/1418370/50106921-5fa4f080-01ee-11e9-8473-fbcabb6969ed.png)

Because of this I decided to try and use the new_appliance.py to create a new appliance file that moves the Aboot to CDROM and mounts the VMDK on HDA and sets the boot priority to the CDROM but it appears that when I do this the boot_priority = "d" option seems to be being ignored. The new appliances will install and they have the images where I want them (hda and cdrom) but the boot priority is still HDD.

Shows boot priority: d
![custom_appliance_summary](https://user-images.githubusercontent.com/1418370/50106984-8cf19e80-01ee-11e9-937b-44c2a8cb8393.png)

Configuration of the installed Template still set for HDD, if changed to CD/DVD-ROM it works.
![custom_boot_priority_still_hdd](https://user-images.githubusercontent.com/1418370/50107183-1f923d80-01ef-11e9-86d2-920ad89146ad.png)

If I then change the installed templates to Boot Priority : CD/DVD-ROM they all work. I suspect that if we are able to get the Boot Priority set properly during installation of the template then the issue will be resolved.

Changing boot settings on already deployed nodes gets odd but I've seen no fallout in functional nodes when updating the templates.

-Chris

**Comment by grossmj** [comment]
Thanks for the detailed report. I will try to fix this soon.

**Comment by memblin** [comment]
My pleasure. I rummaged the code a bit and I think I've found where the appliance config variable for boot_priority gets loaded into the newconfig but I'm having trouble following how it gets written into the $HOME/.config/GNS3.conf in Install of the appliance so I may be in the wrong place. Will update if I find my way through it.

**Comment by grossmj** [comment]
Hi Chris,

This bug has been fixed in GNS3 since version 2.1.9 (see https://github.com/GNS3/gns3-gui/issues/2548).

**Comment by grossmj** [comment]
Please leave a comment if we missed anything else or open a new issue if you find a new bug.

Thanks :+1:
