### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by flappyport** [GNS3/gns3-gui#266]
Why do you no longer release the tarball with the resources, scripts, and tests directories included?  This was introduced in the alpha, beta, and rc's for 1.3.0.  Hopefully it was just an oversight.  Thanks!

**Comment by noplay** [comment]
What is missing in https://github.com/GNS3/gns3-gui/releases/download/v1.3.0/GNS3-1.3.0.source.zip ?

**Comment by flappyport** [comment]
I should have been more explicit.  The tarball (gns3-gui-1.3.0.tar.gz) from the PyPi mirror is lacking the resources, scripts, and tests directories.

After checking each mirror it seems it is *only* PyPi that is affected.  The zip file you linked to is complete but also contains additional components such as iouyap in multiple zip files.  The github tarball (v1.3.0.tar.gz) is good as well.  For now I can change the Gentoo ebuild to use Github but having consistency across mirrors is preferred.  Thank you for your assistance!

**Comment by noplay** [comment]
I will fix it in 1.3.2
