### ISSUE TITLE
gns3 vm gets stuck after i did sudo halt 

### ISSUE THREAD

**Issue by smrh1363** [GNS3/gns3-gui#2660]
<img width="932" alt="screen shot 2018-12-24 at 7 25 32 pm" src="https://user-images.githubusercontent.com/45019678/50411059-dc693900-07b1-11e9-973f-3c96ab77e1c0.png">

**Comment by grossmj** [comment]
Do you get the same problem every time?

**Comment by grossmj** [comment]
@smrh1363 is your VM still getting stuck when you stop it?
