### ISSUE TITLE
Confusion about Wireshark capture file folders?

### ISSUE THREAD

**Issue by jchand17** [GNS3/gns3-gui#2661]
I ran into an issue with symptoms very similar to that described at https://github.com/GNS3/gns3-gui/issues/2130 when using GNS3 v2.1.8 on Windows 10.

It appears that GNS3 was creating 2 pcap capture files.  One was in C:\Users\<user>\GNS3\Projects\<project name>\project-files\captures.  This file remained zero length.  The other was in C:\Users\<user>\GNS3\Projects\<project-name>\tmp\captures.  This latter capture file had the trace data in it.  It seemed that Wireshark was getting pointed to the first file when initiated from the GNS3 GUI.

**Comment by grossmj** [comment]
There is a streaming system between the 2 files however there is a bug on Windows when stopping and starting a packet capture with the same PCAP file path. This will be fixed by GNS3 2.2.
