### ISSUE TITLE
Remove the "Command line" option from the context menu 

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2662]
https://gns3.com/community/discussion/get-command-line-is-not-supporte

It's easy to misunderstand this function. You might think, that it would give a command line interface to the node. Instead it shows the command, that GNS3 issues, to start the node. It's only defined for IOU, QEMU, TraceNG and VPCS devices.

I haven't used it for ages, I think most GNS3 users don't know for what it's good.

I suggest one of the following:
- Remove it.  
  It's mainly for debugging and you can get this information out of the server log or using the `ps` command.
- Replace it by an "Info" option.  
  Create an info popup, that includes all sorts of device information. It shows the same information, as when you hover over the device, but also adds the command line information. That additionally allows to cut-and-paste these informations.
- Add it to the note, that is shown, when you hover over a device.  
  But then you can't use cut-and-paste to copy the information.

**Comment by adosztal** [comment]
Although it's not used often, I wouldn't remove it, it helped a couple of times when I was troubleshooting appliances. The 2nd option looks good to me.

**Comment by ehlers** [comment]
@adosztal is quite likely right. Perhaps the best is to have a terse info on hovering over a node and an "Info" context menu item, showing all the details.

**Comment by grossmj** [comment]
I have added a new node information dialog (launched from the node contextual menu), please let me know what you think of it.

![node_info_1](https://user-images.githubusercontent.com/4752614/50547355-e9cb6b00-0c6a-11e9-9ec1-bbfd78583616.png)

![node_info_2](https://user-images.githubusercontent.com/4752614/50547354-e9cb6b00-0c6a-11e9-810d-a651aa5f3b70.png)

![node_info_3](https://user-images.githubusercontent.com/4752614/50547353-e932d480-0c6a-11e9-8377-6b97b23928ad.png)

**Comment by Raizo62** [comment]
Hi

I think that the dialog box is too big (on my OS). The Preference dialog box is more smaller.
And I think that "use" should also be shown in the tips box.

**Comment by adosztal** [comment]
The structure is great but it looks quite big indeed.

**Comment by joevizio** [comment]
Gentlemen,
The "hovering" over a node only works only in small topologies. What happens in topologies that are bigger than small topologies is that there is a 4-15 second delay before the "node contextual menu" appears - having the interface labels enabled is extremely highly suspect in causing the delay . As a general rule, I do not expose interface labels to my GNS3 workspace and I do not get involved with GUI problems because I would think they are not a fun thing to code because no matter what you do as a coder, no one will like it.

The node contextual menu is misplaced and should not be discovered by hovering over a node, but rather, it should be discovered by right clicking on the node in the Dock->Topology Summary..

Me personally, all the power lies in the future REST API - as I explained to the good Professor several months ago. So I think you are going down the wrong path.

**Comment by Raizo62** [comment]
Happy New Years 2019 :-)

The size of the dialog box is better.

Can you add the "usage" (perhaps only the first line) in the tips box ? if we use it to show login/password, it is too long (and not intuitive) to seek in the "show node information".
In the tips, perhaps you can also remove the "Local ID" and "server ID", used only by developpers. I think also that the ports (on gns3-server and console) are also useless.

**Comment by grossmj** [comment]
@joevizio I have opened a new issue to investigate the high delay problem: https://github.com/GNS3/gns3-gui/issues/2665

@Raizo62 

> Can you add the "usage" (perhaps only the first line) in the tips box ? if we use it to show login/password, it is too long (and not intuitive) to seek in the "show node information".

Ok, I will show the usage in the tooltip, at the bottom.

> In the tips, perhaps you can also remove the "Local ID" and "server ID", used only by developpers. I think also that the ports (on gns3-server and console) are also useless.

This may be used by users who want to use the REST API for instance, I think we will keep this information there.

**Comment by Raizo62** [comment]
> > In the tips, perhaps you can also remove the "Local ID" and "server ID", used only by developpers. I think also that the ports (on gns3-server and console) are also useless.
> 
> This may be used by users who want to use the REST API for instance, I think we will keep this information there.

This information is usefull, then it is in the "show node information" ; but is it necessary that  this information is also in the tootip which is seen very often ?
