### ISSUE TITLE
2.2 : change the docker image in template ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2672]
Hi

I don't know if it is your choose (or a technical reason).

In a Docker template, we can't change the image or copy-paste his name. (I have do a "New Template" and I wanted to copy the name of the image to pull it in docker).

**Comment by grossmj** [comment]
Is this a regression or is this something you would like to see?

**Comment by Raizo62** [comment]
no...the fault is mine...I may have had a proxy problem.
sorry....
