### ISSUE TITLE
[Bug] GNS3 client show wrong router appliance list

### ISSUE THREAD

**Issue by doronbl** [GNS3/gns3-gui#2673]
I have two teams that work on GNS3 using remote server configuration:
Team A run GNS3 remote server (main) on IP-A
Team B run GNS3 remote server (main) on IP-B

Each team connects to his own main remote server.

I've configured my GNS3 client to connect to team A main server. All seems fine and I can see the appliances list and the various projects.

However, when I try to connect to Team B main server I still see Team A appliances on the list.
What I did is to configure the main server to point to Team B main server IP (IP-B). Even after exit and re-run of the GNS3 client with the configuration of main server point to Team B the GUI still show Team A appliances.

Seems that the client have some sort of cache from which it takes the appliances list rather than from the main server reply.

Since I would like to connect my client each time to a different main server, I would like to understand how can I 'clean' the client in order to have only the current main server I connect to to appear.

Doron

**Comment by grossmj** [comment]
@doronbl I am going to investigate this. What version of GNS3 have you used?

**Comment by doronbl** [comment]
I missed that part, sorry.
I use version:
2.1.11
Qt version 5.9.1

**Comment by doronbl** [comment]
@grossmj  is there any manual operation I can perform on the client in order to 'clear' it before I connect to another remote main server?

**Comment by grossmj** [comment]
On Windows, you can reset your client by deleting the `gns3_gui.ini` file in `%APPDATA%\GNS3`.

**Comment by grossmj** [comment]
Note this issue will be solved by GNS3 version 2.2

**Comment by grossmj** [comment]
It is fixed in version 2.2 (still in alpha at this time). Unfortunately it cannot easily be fixed for version 2.1.
