### ISSUE TITLE
the gns3 client is loosing connection with the server vm

### ISSUE THREAD

**Issue by asherbersh** [GNS3/gns3-gui#2678]
can please some one explain what i need to do to keep the session open .
my client is always disconnecting from the server after some time of no connection .
please your help .
this is the message i get in gns3 when it losing the connection
=> Synchronisation lost with the server.
Synchronisation lost with the server.

the gns version is 2.1.11 and the server vm version is 0.10.14

**Comment by grossmj** [comment]
Seems to be similar to https://github.com/GNS3/gns3-gui/issues/2691

**Comment by grossmj** [comment]
I understand you only use the GNS3 VM and after a period of inactivity you start to see "Synchronisation lost with the server" messages. Correct?

**Comment by asherbersh** [comment]
Exactly correct

**Comment by grossmj** [comment]
The implemented computer hibernation detection mechanism seems to cause more problems than it solves. Let's deactivate it and see if it improves the situation. Please comment back if you still have issues with GNS3 version 2.1.13.
