### ISSUE TITLE
2.2 : BUG : lock button and layers

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2679]
Hi

I have several devices (ethernet switch, Cisco router, QEmu device, Rectangle and Text) in different layers.

When i click on "lock button", i believe that order is inversed : if i want to hide devices behind a Rectangle, then if i click on "lock button", the hided devices are showed.

**Comment by Raizo62** [comment]
the "BUG" is less serious than I thought

I see this situation when GNS3 is started in MobaXterm (client ssh with X server)

**Comment by Raizo62** [comment]
No, the bug is real, even without MobaXterm.

**Comment by grossmj** [comment]
I believe we will have to keep the locked state of each node and not rely on its layer position to know what node is locked.

**Comment by Raizo62** [comment]
Yes, your choice to use the layer position to lock the device surprised me.
Now, you can't add a absolute value to fix the bug ?

**Comment by grossmj** [comment]
> Yes, your choice to use the layer position to lock the device surprised me.

Indeed, I thought I could go away with this but I hadn't anticipated all the small problems ;)

> Now, you can't add a absolute value to fix the bug ?

I will add a "locked" variable which can be True or False.

**Comment by grossmj** [comment]
I have refactored everything to use a "locked" variable. Implemented by PRs https://github.com/GNS3/gns3-gui/pull/2725 and https://github.com/GNS3/gns3-server/pull/1541

**Comment by Raizo62** [comment]
Thanks :-)

I believe that there is still a bug: i can change the layer of a locked device

**Comment by grossmj** [comment]
This is intended, locked status is completely separated from layer position.

**Comment by Raizo62** [comment]
why ?

**Comment by grossmj** [comment]
I meant you can lock a node which is in any layer position however yes I can prevent users to change the layer position of a locked node. Actually this makes sense, I will fix this.

**Comment by grossmj** [comment]
It should be fine now. Let me know if you find anything else.

Thanks!
