### ISSUE TITLE
Show/Hide Interface Labels doesn't work in 2.1.12

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2690]
After upgrade to 2.1.12 "Show/Hide Interface Labels" stopped working.

**Comment by grossmj** [comment]
Still working here, please can you give us a little more details? Thanks :)

**Comment by vint66** [comment]
I guess it might be related to another option - "draw link status points" (it is in Preferences > General > Topology View).
If I have it disabled then "Show/Hide Interface Labels" in particular project doesn't do anything. But same working fine in case "draw link status points" is enabled.

**Comment by grossmj** [comment]
Thanks, I can reproduce the problem now :+1:

**Comment by grossmj** [comment]
Fixed now. Thanks for catching that :+1:
