### ISSUE TITLE
Constant "Synchronisation lost with the server." with GNS3 2.2.0a1

### ISSUE THREAD

**Issue by micush** [GNS3/gns3-gui#2691]
I'm constantly seeing "Synchronisation lost with the server" on GNS3 2.2.0a1. I saw no such errors with GNS3 2.1.12. Please correct this.

**Comment by fernandolcx** [comment]
Same here.

It's a known issue?

**Comment by hosseinoliabak** [comment]
Same here, my GNS3 is installed on ESXi. Constantly receiving same message Synchronisation lost with the server.

I didn't have this problem with 2.1.11

**Comment by grossmj** [comment]
I see what could be the problem, we will fix this soon. Does this error prevent you to use this version of GNS3?

**Comment by fernandolcx** [comment]
Yes for me, since it closes the project and drops all telnet connections.

The workaround is to check the option "leave the project running when closing GNS3"

**Comment by grossmj** [comment]
Do you get this error message after a period of inactivity?

**Comment by hosseinoliabak** [comment]
No, I even get this message when I am issuing the command into the CLI. Suddenly the session terminates and I have to reopen the project.

**Comment by fernandolcx** [comment]
The fastest way to replicate this bug is using the packet filters IDK why.
When I check "packet loss" the client disconnects.

**Comment by grossmj** [comment]
@fernandolcx do you use the GNS3 VM or an remote server?

**Comment by fernandolcx** [comment]
> @fernandolcx do you use the GNS3 VM or an remote server?

GNS3 VM on ESXi

**Comment by jayselan** [comment]
@grossmj I'm constantly seeing "Synchronisation lost with the server" on GNS3 2.2.0a1.

**Comment by jayselan** [comment]
very frustrating

**Comment by grossmj** [comment]
We have disabled the computer hibernation detection mechanism which was causing these messages. Hopefully this won't have any side effect. Please comment back if you detect problems in alpha 2.

Thanks!
