### ISSUE TITLE
is there gns3 vm virtualbox version 2.2.0a1 for linux mint

### ISSUE THREAD

**Issue by afrihhilal** [GNS3/gns3-gui#2692]
i have upgrade gns3 on my linux mint 19, but gns3 didn't work. Because GNS3 VM for virtualbox not same version with gns3 2.2.0a1 for linux? 
can i downgrade to 2.1.11 version or gns3 vm for virtualbox will release soon?
because when i work with version 2.1.11 version it work perfectly.

**Comment by Najihel** [comment]
:+1:

**Comment by grossmj** [comment]
I recommend you to downgrade for now. We plan to release the VirtualBox VM with another alpha version in about 2 or 3 weeks.

**Comment by grossmj** [comment]
We will distribute a GNS3 VM for VirtualBox with version 2.2a2
