### ISSUE TITLE
How does one use the appliances defined on the server?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2697]
Hi guys

I installed from source on Ubuntu 18.04 LTS. I noticed that now there are gns3a files on the server. They are in the Python folder. What is the use of these if you do not have a gns3-gui client installed on the same server (headless server in my case)

**Comment by grossmj** [comment]
The main purpose is that the appliance files can be synchronized once with our online GitHub repository so users (multiple UIs) have the latest .gnsa files in one place. Also, an Internet connection is only required for the server.

**Comment by grossmj** [comment]
I hope I answered your question. Please answer back if you need more explanation.

**Comment by 1001QAdotNET** [comment]
Hi Sorry for answering late, I was interested to see if instead of having to download the templates via the market place it would be possible to get them from the serve which seems to have them anyway

**Comment by grossmj** [comment]
Correct, the server get the appliance files from GitHub and send their content to requesting clients.
