### ISSUE TITLE
Change hdd in topology for asa 842 error 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#270]
When I drag one asa842 for experiment, then I want remove the HDD for it (default there is one hdd as flash for asa 842, then we can store the active info in it ,no need active every time), when I start the asa842 then I got:

Server error from 127.0.0.1:8000: ASA842-1: hda disk image '/home/wolfboy/GNS3/images/QEMU/' is not accessible

Which means the GNS3 gui remove the hdd name but not path.

My version is GNS3 1.3.0 with Ubuntu 14.10

**Comment by grossmj** [comment]
@superwolfboy this is fixed now: https://github.com/GNS3/gns3-server/commit/fa544ef888f2e5ee59e1574ae0ea6214bb1811e9

Thanks!
