### ISSUE TITLE
launching GNS3 from the command line opens up the python interactive command line

### ISSUE THREAD

**Issue by davidv171** [GNS3/gns3-gui#2700]
The title should very much explain it.

Link to forum thread:

https://gns3.com/community/discussion/running-gns3-in-the-terminal-ope

In short, I recently updated my whole system and left it alone(Arch Linux) for a while. After I came back, I decided to run GNS3 as I have some schoolwork to do. But it threw me a bunch of errors. I followed the AUR comment section and decided at one point to run as root, see where it takes me. I cancelled as I got the same issue. This is when it started launching into the python interactive shell.

```
Example: ~ » gns3 -v      
Update installed restart the application
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

Since then I've reinstalled the package numerous time, downgraded and upgraded async-gns3.Nothing worked. And I don't think I want to reinstall my entire system just yet. As I have realized there are some problems with incompatible images? Whatever I'm using seems to not work on other machines. And I have no idea how to fix this either. Some more outputs:
```
Optional dependencies for gns3-server
    dynamips: Cisco router emulator. [installed]
    gns3-gui: graphical user interface for GNS3 server. [installed]
    iouyap: Bridge IOU to UDP, TAP and Ethernet.
    qemu: Used by GNS3 to run Cisco ASA, PIX and IDS. [installed]
    vpcs: Simple PC emulation for basic network operations.
    ubridge: Bridge for UDP tunnels, Ethernet, TAP and VMnet interfaces. [installed]
```
It should be the newest release. 

Any help is greatly appreciated

**Comment by cioby23** [comment]
I'm also using GNS3 on Arch (installed from AUR repository) for a long time and I did not experience this kind of issue. I just looked recently at the AUR PKGBUILD and it seems the maintainer updated the aur/python-async-timeout-gns3 package to version 3.0.0 which might caused the issue
Currently GNS3 team locked down async-timeout package to version 2.x
https://github.com/GNS3/gns3-server/commit/5a0e21f58dbcdc5c4ba5add72253682fb0a6d56e
Please try to downgrade async-timeout to version 2 by removing version 3
you can manually install version 2 using
pip install async-timeout==2.0.1
then run pip freeze | grep async-timeout
to check if you have the correct version

**Comment by grossmj** [comment]
I don't really know why the maintainer updated the aur/python-async-timeout-gns3 package to version 3.0.0 which may indeed be the problem. Maybe it would be great to contact this person?

Note that we set the package to version 3 on our version 2.2 branch: https://github.com/GNS3/gns3-server/blob/2.2/requirements.txt#L9

**Comment by grossmj** [comment]
@davidv171 any success?

**Comment by cioby23** [comment]
@grossmj I propose that all installation/configuration issues should be addressed on the GNS3 community and here only bugs/features related to GNS3 should be posted because I see a lot of people starting to use GNS3 get stuck and there they should receive more help from the community.
Also maybe it's better to prepare a Github template requiring everyone to specify used environment ( software version and OS etc), steps to Reproduce, expected behaviour and observer behaviour.

**Comment by grossmj** [comment]
@cioby23 I totally agree, I noticed more and more users are looking for support here. We would like to stay focused on bugs/features and other development related topics since other requests slows us down (we are a very small team already!)
