### ISSUE TITLE
2.2 : bug : sometime, the cisco router doesn't start his startup-config

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2701]
Hi

I have a problem with this lab : [tp-vlan-3_backup_190206_15_2415.tar.xz.txt](https://github.com/GNS3/gns3-gui/files/2837754/tp-vlan-3_backup_190206_15_2415.tar.xz.txt)

I open it with GNS3 in the last LiveRaizo (started on real PC or in VirtualBox) 

I start nothing

i add on the lab a cisco router "c3725-adventerprisek9-mz.124-25d".

I start only this router.
In the console, the router seems to hang, but after a long time, it ask "Would you like enter the initial configuration dialog?"

(I don't know if it is the same bug, but sometime, this is the switch L3 which can't read his startup config)

**Comment by Raizo62** [comment]
Here a lab more easy : 
[untitled_backup_190208_14_4255.tar.xz.txt](https://github.com/GNS3/gns3-gui/files/2845216/untitled_backup_190208_14_4255.tar.xz.txt)

When i start all, the router does the same "bug".

**Comment by Raizo62** [comment]
I have perhaps a clue : when i start all of the project "untitled_backup_190208_14_4255.tar.xz", i have a file called ".fuse_hidden"

> projects/untitled/project-files/dynamips/e02ae2ad-6234-4fa9-92fc-e091e212857f/.fuse_hidden0000010a00000004

This file is created when a file was deleted but there is at least one software which is still using it

**Comment by Raizo62** [comment]
Perhaps that the bug is in the script fast-restore-lab of LiveRaizo : i use rsync in it, and i believe that a option of rsync has changed and now it deletes the configs files of device.
As the device didn't found his startup config,  this device can't start.

I analyze more to confirm

**Comment by grossmj** [comment]
Ok, let me know :+1:

**Comment by grossmj** [comment]
@Raizo62 have you found anything?

**Comment by Raizo62** [comment]
Since i fixed the bug in fast-restore-lab of LiveRaizo, i have no see this BUG again.

The bug was not in GNS3. Sorry for the inconvenience.

I close this issue.
