### ISSUE TITLE
Feature Request - Display available appliances in a hierarchical folder structure - >= 2.2a

### ISSUE THREAD

**Issue by jeepacation** [GNS3/gns3-gui#2702]
From 2.2a and beyond has a more streamlined method of importing appliances, which is fantastic, during the 'add appliance' process the user is presented with an extensive list of available appliances (due to the amazing hard work of GNS3 contributors) i think it would be great to see this list presented in a folder structure in the same way the devices are presented in the main workspace, in a hierarchical fashion;
-Routers
-Switches
-Security
-End Hosts
-Others

**Comment by grossmj** [comment]
Implemented
