### ISSUE TITLE
Feature Request - Ability to toggle the link status indicators on/off

### ISSUE THREAD

**Issue by jeepacation** [GNS3/gns3-gui#2703]
Add the ability to toggle the link status indicators on/off (this used to be a function of 0.8.2 from memory)

Users have asked for this in order to use GNS3 to assist as a documentation tool

**Comment by grossmj** [comment]
Hi, this is already supported. Please see the "Draw link status points" checkbox in the preferences.

![draw_link_status_points](https://user-images.githubusercontent.com/4752614/53152650-b06b0800-35e8-11e9-8515-03d62ea1c660.png)
