### ISSUE TITLE
qemu binary thread

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-gui#2704]
Hi Guys,

Can you please help, installed GNS3 with pip and manually installed all depencies(dynamips, ubridge,iouyap,qemu) starting old topology that had qemu vm.

1. When starting topology error:
QEMU binary path qemu-system-x86_64 is not found in the path

2. Editing qemu vm settings error:
Could not find '/bin/qemu-system-x86_64' in the Qemu binaries list, please select a new binary

checked /usr/local/bin/ and there's no qemu, can you please advise how to resolve please.
Thanks in-advance.

**Comment by grossmj** [comment]
Where is Qemu installed? Try to locate using the `whereis` command.

**Comment by grossmj** [comment]
Have you checked that the directory containing qemu-system-x86_64 is in $PATH environment variable?

**Comment by leribe** [comment]
Manage to solve the problem by install from bionic, thanks for the assist.
