### ISSUE TITLE
GNS3 2.2.0a1 import appliance not working

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2706]
GNS3 2.2.0a1, Windows 10 Prof x64, VM Workstation Pro 14.1.5 build-10950780 and the GNS3 workstation VM provided with GNS3 2.2.0a1 (assigned 16gig RAM)

Using appliance templates to import ASAv, IOSv and IOSvL2 images.  It appears all goes well but when I try to use them in a project the files cannot be found.  The folder in the VM /opt/gns3 has the appropriate folders (IOS and QEMU) but both folders are empty.  This process worked fine in GNS3 2.1.12.
If I merely add the images them via Preferences, Qemu VMs it works fine.  Did the appliance templates change between GNS3 version 2.1.12 and 2.2.0a1?
Always the likelihood I am doing something wrong.  As always, suggestions much appreciated.

**Comment by grossmj** [comment]
It should basically work the same. Do you get an error message? Does it happen when you drag and drop a template on the drawing area?

**Comment by jtorri** [comment]
Could it be a problem with the GNS3 VM? When I select File, Close on the GNS3 menu the application and the GNS3 VM close but only after receiving in the upper right-hand corner the following messages in this order: "The remote host closed the connection", "unknown error", "unknown error".
All previous GNS3 VM had a 97.5g hard disk 2, this one has a 293g hard disk 2.
Also, when running the Update menu option it attempts to run a file /tmp/update.sh. That file exist but contains only "404" and errors out requiring ctrl-c and init 6 to reboot the VM. Hope this makes sense.

**Comment by jtorri** [comment]
![gns3-2 2 0a1-1](https://user-images.githubusercontent.com/10285348/52641235-5ced1180-2ea6-11e9-8c6d-5874954e1f32.png)
![gns3-2 2 0a1-2](https://user-images.githubusercontent.com/10285348/52641237-5eb6d500-2ea6-11e9-8201-995a7cf9029a.png)
![gns3-2 2 0a1-3](https://user-images.githubusercontent.com/10285348/52641241-60809880-2ea6-11e9-8da0-7c3dfbae9222.png)

**Comment by grossmj** [comment]
This will be fixed in alpha 2. Thanks :)
