### ISSUE TITLE
[2.1.12 and 2.2.0a1] SIP Qt 5.12 and python 3.6.8 error

### ISSUE THREAD

**Issue by fcolista** [GNS3/gns3-gui#2709]
Hi.
On Alpine Linux, running python 3.6.8, I had to manually patch all the ```import sip``` recurrent statements with: ```from PyQt5 import sip``` (according with http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-11) to avoid this error:

```
$ gns3
Fail update installation: No module named 'sip'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...
```

This is the patch I've applied (for 2.2.0a1): https://dpaste.de/cxOw/raw
While this is the patch for 2.1.12: https://dpaste.de/BwkD/raw

But when I run gns3, I'm stucked at this point

```
$ gns3
Fatal Python error: Aborted

Current thread 0x00007fcab90feb68 (most recent call first):
  File "/usr/lib/python3.6/site-packages/gns3/application.py", line 34 in __init__
  File "/usr/lib/python3.6/site-packages/gns3/main.py", line 231 in main
  File "/usr/bin/gns3", line 11 in <module>
Aborted
```
I don't have any issue in importing python3 PyQt5 modules:
```
$ python3
Python 3.6.8 (default, Jan 24 2019, 16:36:39) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import *
>>> 
```
Please let me know if I can assist more for troubleshooting.
Thanks!
.: Francesco

**Comment by grossmj** [comment]
Thanks for troubleshooting this, we will fix everything soon.

**Comment by ehlers** [comment]
Not everyone installs PyQt5 from PyPi. Then Qt and sip are installed as extra packages. I haven't tested this scenario, but I assume, that "from PyQt5 import sip" might fail then (untested). Furthermore this import will fail with older PyQt versions.

So I suggest to use this:
```
try:
    import sip
except ImportError:
    from PyQt5 import sip
```

But as I don't like changing all the sip imports this way (it doesn't look hat nice), I suggest to integrate sip into the qt module the same way PyQt5 modules are integrated. Then sip is imported by `from .qt import sip`.

Here the patch for 2.1.12: [sip_pyqt_patch_2.1.12.txt](https://github.com/GNS3/gns3-gui/files/2860503/sip_pyqt_patch_2.1.12.txt)

**Comment by grossmj** [comment]
This is exactly how I intend to fix this issue ;) thanks for the patch!

**Comment by fcolista** [comment]
Thanks for the quick fix!
This would for sure be the "portable" solution.
Still, this patch does not fix this issue yet:
```
$ gns3
Fatal Python error: Aborted

Current thread 0x00007fae5c8b2b68 (most recent call first):
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 219 in _migrateOldConfig
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 120 in _resetLoadConfig
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 57 in __init__
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 504 in instance
  File "/usr/lib/python3.6/site-packages/gns3/main.py", line 228 in main
  File "/usr/bin/gns3", line 11 in <module>
Aborted
``` 
There's something more I can do for troubleshooting this issue?
Thanks!
.: Francesco

**Comment by ehlers** [comment]
Are you using cx_Freeze to create a binary? If yes, I suggest to first test GNS3 without freezing it, with fully installed python and python libraries. If that works, it might be a bug with cx_Freeze. Try different versions of cx_Freeze, I still prefer v5.0.2.

**Comment by fcolista** [comment]
Good point.
cx_Freeze is a requirement of gns3-converter.
I removed the gns3-converter as a dependency of gns3-gui so that is not pulled automatically.
I don't have cx_Freeze in my system right now, but the issue is still there:
```
$ gns3
Fatal Python error: Aborted

Current thread 0x00007f34628dab68 (most recent call first):
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 219 in _migrateOldConfig
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 120 in _resetLoadConfig
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 57 in __init__
  File "/usr/lib/python3.6/site-packages/gns3/local_config.py", line 504 in instance
  File "/usr/lib/python3.6/site-packages/gns3/main.py", line 228 in main
  File "/usr/bin/gns3", line 11 in <module>
Aborted
```
Thanks!
.: Francesco

**Comment by ehlers** [comment]
In gns3/local_config.py, line 219 is one of the places, where PyQt5 gets initialized. Maybe there is some issue with the PyQt library.

My only idea is to test with various GNS3 versions and PyQt5 versions, maybe even different alpine OS versions, until you know, who is to blame.

BTW: In gns3/local_config.py, line 219 GNS3 tells you, that you have an GNS3 configuration from a GNS3, that's newer than your current GNS3 version. For further tests I would move the GNS3 configuration file (~/.config/GNS3/gns3_gui.conf) to a safe place and start with an empty configuration. But I fear, you will then get another PyQt5 related crash on a different code line.

**Comment by fcolista** [comment]
You are definetly right...
moving GNS3 directory in .config will not solve the problem, even if the line related to the local_config is no longer there:

```
$ gns3
Fatal Python error: Aborted

Current thread 0x00007f25c8606b68 (most recent call first):
  File "/usr/lib/python3.6/site-packages/gns3/application.py", line 34 in __init__
  File "/usr/lib/python3.6/site-packages/gns3/main.py", line 231 in main
  File "/usr/bin/gns3", line 11 in <module>
Aborted
```

.: Francesco

**Comment by fcolista** [comment]
Ok, I tried to install it from scratch.
Same identical issue with "Fatal Python error: Aborted" as above.
Wondering if there are issues with Python 3.6.8.

.: Francesco

**Comment by ehlers** [comment]
Just installed Alpine 3.9 in a VM and tried a very basic PyQt5 test script:
```
from PyQt5 import QtWidgets
app = QtWidgets.QApplication([])
QtWidgets.QMessageBox.critical(None, "Title", "Message")
```

This works well on OS X with PyQt 5.12 and Debian Linux with PyQt 5.7. But in alpine 3.9 it fails:
```
alpine:~$ python3 pyqt-test.py
Traceback (most recent call last):
  File "pyqt-test.py", line 1, in <module>
    from PyQt5 import QtWidgets
ModuleNotFoundError: No module named 'PyQt5.sip'
```

You might give it a try in your environment. If that doesn't work, the PyQt5 package is broken.

**Comment by fcolista** [comment]
ehlers, thanks.
Please try edge, which contains the new GNS3 version with a working Qt5.
After the upgrade from 5.10, PyQ5.sip has been shipped with py-sip.
Try to modify the repository in this way:
```
http://rsync.alpinelinux.org/alpine/edge/main
http://rsync.alpinelinux.org/alpine/edge/community
http://rsync.alpinelinux.org/alpine/edge/testiing
```
then ```apk update && apk upgrade```

Thanks.
.: Francesco

**Comment by ehlers** [comment]
@fcolista I just wanted to give you a simple test script to verify, if the PyQt works. As I normally don't use alpine I don't care, that it doesn't work in my installation.

**Comment by ehlers** [comment]
@grossmj You should check my patch for the file `gns3/qt/__init__.py`. Maybe it first should try `from PyQt5 import sip` because that module should work best with PyQt5. Then `import sip` would be the fallback. Furthermore the other imports in this module give a nice error message, when that fails. That could be added to the sip import as well.

**Comment by fcolista** [comment]
> @fcolista I just wanted to give you a simple test script to verify, if the PyQt works. As I normally don't use alpine I don't care, that it doesn't work in my installation.

Thanks ehlers.
Tested. I've an issue with Qt.
Let me fix it, adn come back to you. Thanks!
```
$ python3 test.py 
Cannot mix incompatible Qt library (version 0x50c01) with this library (version 0x50c00)
Aborted
```
.: Francesco

**Comment by fcolista** [comment]
ehlers: fixed the Qt issue.
Now gns-gui starts correctly.
Thanks a lot for providing the test script, it helped a lot!
You can mark this as closed.

.: Francesco

**Comment by grossmj** [comment]
Applied the patch and try to import PyQt5.sip first (`from PyQt5 import sip`). Should be fixed now. Thanks for your help! :+1:
