### ISSUE TITLE
Some Critical Messages don't create a Popup in the GUI

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2710]
GNS3 version 2.1.12

Some critical messages are only sent to the log, they don't create a popup. I noticed that for the version error message in [gns3/local_config.py line 220](https://github.com/GNS3/gns3-gui/blob/2.1/gns3/local_config.py#L220) and the message about copying the GNS3 application to /Applications in [gns3/main.py line 271](https://github.com/GNS3/gns3-gui/blob/2.1/gns3/main.py#L271).

The normal user sees, that the application starts, but then stops without any error message. He normally doesn't try to start the program from the CLI to see the error messages. So this is a very confusing situation for beginners.

The reason is, that the qt module ([gns3/qt/\_\_init\_\_.py](https://github.com/GNS3/gns3-gui/blob/2.1/gns3/qt/__init__.py#L112)) overwrites QtWidgets.QMessageBox by LogQMessageBox. LogQMessageBox logs the message, then calls the original QMessageBox, but  only when the parent parameter is valid (not None and not deleted). In the two instances mentioned above, the parent parameter is set to None, therefore the check fails.

**Comment by grossmj** [comment]
PR opened: https://github.com/GNS3/gns3-gui/pull/2715

**Comment by ehlers** [comment]
Did a grep through the sources and found other instances of QtWidgets.QMessageBox with parent=None. But as far as I see, the GUI is active during the other QMessageBox calls, so the messages will show up in the log window. Wouldn't it be easier to replace those calls by a log.error / log.warning call?

```
/Users/behlers/GNS3/source/gns3-gui# grep -r QtWidgets.QMessageBox gns3 | grep None
gns3/dialogs/filter_dialog.py:            QtWidgets.QMessageBox.warning(None, "Link", "Error while listing information about the link: {}".format(result["message"]))
gns3/link.py:            QtWidgets.QMessageBox.warning(None, "Update link", "Error while updating link: {}".format(result["message"]))
gns3/link.py:            QtWidgets.QMessageBox.warning(None, "Create link", "Error while creating link: {}".format(result["message"]))
gns3/local_config.py:                QtWidgets.QMessageBox.critical(None, "Version error", "Your settings are for version {} of GNS3. You cannot use a previous version of GNS3 without risking losing data. If you want to reset delete the settings in {}".format(self._settings["version"], self.configDirectory()))
gns3/main.py:            QtWidgets.QMessageBox.critical(None, "Error", "You need to copy GNS3 in your /Applications folder before using it.")
gns3/project.py:                QtWidgets.QMessageBox.critical(None, "Duplicate project", "Error while duplicating: {}".format(result["message"]))
```
