### ISSUE TITLE
Cannot connect to compute 'Vbox' with request GET /virtualbox/vms

### ISSUE THREAD

**Issue by Johnnyreyman** [GNS3/gns3-gui#2711]
I have Virtualbox on a Server and GNS3 cannot retrieve the list of VMs from it. I used the IP address of the server with ports 22, 3080, and 18083. I received the same error.
![virtualbox vms_058](https://user-images.githubusercontent.com/31798114/52769929-6cc83b00-2ff7-11e9-9af1-6f6bea083a2b.png)
I am trying to set up a VM on a remote Virtualbox.
Option:
![new virtualbox vm template_059](https://user-images.githubusercontent.com/31798114/52769886-4904f500-2ff7-11e9-926d-51b66630d534.png)
Thank you for looking into this.

**Comment by grossmj** [comment]
Do you only have the issue VirtualBox? What if you try to add a VPCS template for instance?

Thanks

**Comment by grossmj** [comment]
Ping

**Comment by Johnnyreyman** [comment]
VirtualBox on the server computer does not seem to be returning the list of virtual machines.

**Comment by grossmj** [comment]
What do you see if you go to `http://127.0.0.1:3080/v2/compute/virtualbox/vms`? (replace 127.0.0.1:3080 by your server address and port).

**Comment by Johnnyreyman** [comment]
Here is what shows:
![image](https://user-images.githubusercontent.com/31798114/53133667-8c042280-3539-11e9-8f71-680bdd189e7a.png)

**Comment by Johnnyreyman** [comment]
Here's the headers page:
![image](https://user-images.githubusercontent.com/31798114/53133779-fb7a1200-3539-11e9-830d-7909457b37cb.png)

**Comment by grossmj** [comment]
You should at a minimum see something like this: '[ ]'

```
curl 'http://127.0.0.1:3080/v2/compute/virtualbox/vms'
[
    {
        "ram": 64,
        "vmname": "Linux Tinycore 3.8.2"
    },
    {
        "ram": 1024,
        "vmname": "Fedora"
    }
]
```

**Comment by grossmj** [comment]
This doesn't appear to be a bug with GNS3. Please can you ask for help on https://gns3.com/community?

Thank you.

**Comment by Johnnyreyman** [comment]
I had VirtualBox version 6 on my server. What is the ideal update for compatibility with it?
