### ISSUE TITLE
Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5002)

### ISSUE THREAD

**Issue by shiblovich** [GNS3/gns3-gui#2712]
hi gus 
when i'm trying to add asa firewall to gns3 it give me this issue 
`QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name ciscoasa-1 -m 1024M -smp cpus=1 -boot order=c -drive file=/home/mano/GNS3/projects/untitled/project-files/qemu/c2d78e0e-be60-4457-822a-2f40702beeba/hda_disk.qcow2,if=ide,index=0,media=disk -initrd '/media/mano/apps/for gns3/ASA842/asa842-initrd.gz' -kernel '/media/mano/apps/for gns3/ASA842/asa842-vmlinuz' -append '-append ide_generic.probe_mask=0x01 ide_core.chs=0.0:980,16,32 auto nousb console=ttyS0,9600 bigphysarea=65536 no-hlt' -uuid c2d78e0e-be60-4457-822a-2f40702beeba -serial telnet:127.0.0.1:5002,server,nowait -monitor tcp:127.0.0.1:40049,server,nowait -net none -device e1000,mac=0c:5a:f8:ee:ba:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:5a:f8:ee:ba:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:5a:f8:ee:ba:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:5a:f8:ee:ba:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -no-kvm -vnc none -vga none -m 1024 -icount auto -hdachs 980,16,32

Execution log:
qemu-system-x86_64: -hdachs: invalid option

error while starting ciscoasa-1: Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5002)

.`

**Comment by cioby23** [comment]
If you are using Qemu version 2.12 or newer this option **-hdachs** has been removed. Please see the Qemu changelog.
[https://wiki.qemu.org/ChangeLog/2.12#Incompatible_changes](url)
The deprecated CLI option "-hdachs" has been removed. You can specify the disk geometry e.g. via -device ide-hd,cyls=c,heads=h,secs=s instead.

**Comment by shiblovich** [comment]
> -device ide-hd,cyls=c,heads=h,secs=s instead

i use this command so what is the command insteat 
-vnc none -vga none -m 1024 -icount auto -hdachs 980,16,32

**Comment by cioby23** [comment]
I have not tested but I guess **-hdachs 980,16,32** can be replaced with **-device ide-hd,cyls=980,heads=16,secs=32**

**Comment by shiblovich** [comment]
> -device ide-hd,cyls=980,heads=16,secs=32

it's give me this error 
QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name ciscoasa-1 -m 1024M -smp cpus=1 -boot order=c -drive file=/home/mano/GNS3/projects/untitled/project-files/qemu/50244731-f711-4fda-a365-3b2b932090b2/hda_disk.qcow2,if=ide,index=0,media=disk -initrd '/media/mano/apps/for gns3/ASA842/asa842-initrd.gz' -kernel '/media/mano/apps/for gns3/ASA842/asa842-vmlinuz' -append '-append ide_generic.probe_mask=0x01 ide_core.chs=0.0:980,16,32 auto nousb console=ttyS0,9600 bigphysarea=65536 no-hlt' -uuid 50244731-f711-4fda-a365-3b2b932090b2 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:41973,server,nowait -net none -device e1000,mac=0c:11:60:90:b2:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -device e1000,mac=0c:11:60:90:b2:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -device e1000,mac=0c:11:60:90:b2:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=127.0.0.1:10004 -device e1000,mac=0c:11:60:90:b2:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=127.0.0.1:10006 -no-kvm -vnc none -vga none -m 1024 -icount auto -device ide-hd,cyls=980,heads=16,secs=32

Execution log:
qemu-system-x86_64: -device ide-hd,cyls=980,heads=16,secs=32: No drive specified

error while starting ciscoasa-1: Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)

Could not start QEMU console [Errno 111] Connect call failed ('127.0.0.1', 5001)
-------------------------

**Comment by cioby23** [comment]
I recommend you to use ASAv with Qemu. Your version ASA 8 is not supported by GNS3 team. Please check the documentation https://docs.gns3.com/1JZLzpB2gWVtdlgjBkKAMrKckpee9YjqAyt5zliBXGkM/index.html#h.1zcxdkbdbmy1

**Comment by shiblovich** [comment]
Thank you cioby23

**Comment by grossmj** [comment]
We should not start the Qemu console if the Qemu process is not started. Need to be fixed in our 2.2 branch.

**Comment by zhouyingge1104** [comment]
Try Hardware > Video Card, select other options.
