### ISSUE TITLE
Installer restart the computer without asking -- improper MSVC argument

### ISSUE THREAD

**Issue by pigen** [GNS3/gns3-gui#2714]
Hello,

The GNS3 all-in-one installer restart the computer without asking, based in the logs the reason is missing parameter in the calling of the vcredist installer, which is just /passive, instead of /passive /norestart
via: http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html
![image](https://user-images.githubusercontent.com/22332115/52920605-ad34fb00-330e-11e9-9f4c-4af9d4d12103.png)

The Windows system log regarding the reboot:
Windows Installer requires a system restart. Product Name: Microsoft Visual C++ 2017 x64 Minimum Runtime - 14.13.26020. Product Version: 14.13.26020. Product Language: 1033. Manufacturer: Microsoft Corporation. Type of System Restart: 2. Reason for Restart: 1.

The 2.2.0a1 and 2.1.12 installer also affected.

**Comment by grossmj** [comment]
Fixed. Thanks :+1:
