### ISSUE TITLE
Wireshark packets capture not showing

### ISSUE THREAD

**Issue by ilyesbek** [GNS3/gns3-gui#2722]
When I want to capture packets on GNS3, they don't show up when I do anything like Ping, Telnet or DHCP. I've installed GNS3 latest version and got Wireshark 2.6.5. I thought maybe it's the firewall or the antivirus but still the same issue.

**Comment by ilyesbek** [comment]
![image](https://user-images.githubusercontent.com/19342395/53298553-01207200-3830-11e9-8050-5312e6cab9a7.png)

**Comment by grossmj** [comment]
Hi,

Have you tried to change the capture file name when starting a new packet capture?

**Comment by ilyesbek** [comment]
Hi,

No, but how can I do it, what file name should I put?

**Comment by ilyesbek** [comment]
![image](https://user-images.githubusercontent.com/19342395/53300015-3635c000-3842-11e9-9fd4-9a85c6bda247.png)

**Comment by grossmj** [comment]
You can select the filename when you right click on a link and choose capture:

![capture](https://user-images.githubusercontent.com/4752614/53300386-ea523d80-3878-11e9-83fb-7f22f4d608bb.png)

**Comment by ilyesbek** [comment]
Still the same issue

**Comment by ilyesbek** [comment]
![image](https://user-images.githubusercontent.com/19342395/53303244-845dba00-3868-11e9-9f1d-1a8d705adfd9.png)

**Comment by cioby23** [comment]
@ilyesbek you can try and run Wireshark independently of GNS3 and see if you can see any traffic to exclude a Wireshark issue.

**Comment by ilyesbek** [comment]
@cioby23 There is traffic on Wireshark. So the issue must be on GNS3.

**Comment by Desposyni** [comment]
Same problem between IOS router and Palo Alto VM. I see loopback and CDP messages, but nothing from the PA-VM even though the PA-VM is pinging the IOS router.

**Comment by grossmj** [comment]
Note that we have fixed some issues regarding packet captures however we only did it for our 2.2 version which is still in alpha since the amount of changes were too important to be included in version 2.1.x

Reference: https://github.com/GNS3/gns3-gui/issues/2438

**Comment by n3oxmind** [comment]
@ilyesbek, The first think I'll do is to check if there is any captured files under `YourProjectName/project-files/captures`.

**Comment by ilyesbek** [comment]
@n3oxmind Yeah there is captured files in the project file. But when I open them with Wireshark, it's really blank, there's nothing.

**Comment by grossmj** [comment]
@ilyesbek also, have a look in YourProjectNet\tmp\captures

**Comment by n3oxmind** [comment]
@ilyesbek, Can you do another capture with different name and see if it got saved to the same folder. Also, check the size of the captured file.

few questions to narrow  down your issue:
1- Are you able to ping from device1 to device2 successfully?
2- Are you capturing on serial or ethernet link ?
3- what version of gns3 are you using ?

**Comment by ilyesbek** [comment]
@n3oxmind I tried it. The capture with a different name got saved to the same folder. All the captures's sizes are 0KB except one that has 1KB.
- I'm able to ping from device1 to device2 successfully.
- I'm capturing on Ethernet link
- GNS3 Version 2.1.12

**Comment by n3oxmind** [comment]
@ilyesbek, Create new project with simple topology 2 devices (routers) and make sure that they can ping each others. start capturing and check the file size again. let me know about the result.

I only use gns3 on my Linux machine, I'm gonna try to install the same version of yours on my win10 VM and try to generate the same problem. meanwhile you can do these troubleshooting steps:

1- Restart Win10 and create new simple project and do capture.
2- Disable your Anti-Virus and Firewall on at a time and check if anything changed with the capture
3- Reinstall gns3

Disable Firewall from Powershell
```powershell
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
```
or from command-line
```cmd
netsh advfirewall set allprofiles state off.
```

**Comment by ilyesbek** [comment]
@n3oxmind  I've tried every single thing and nothing worked, I disabled the firewall and antivirus, restarted Win10, reinstalling GNS3, creating a new projects, putting on 2 routers and they've pinged each other but still blank on the Wireshark and the capture data is 0KB. The problem may be in GNS3, because I've tried to capture packets on EVE-NG and it worked perfectly.

**Comment by n3oxmind** [comment]
@ilyesbek, I feel you, Please try these solution if you have not tried yet:

1- place gns3 virtual switch between your devices and start capture
2- Start data capture before everything started

Cheers!!

**Comment by ilyesbek** [comment]
@n3oxmind  I've tried the vswitch between 2 routers and starting the capture but still the same!
But, when I checked the projectfile/tmp/captures, there's 5KB in the capture file and when I opened it there was packets that circulated when I pinged between the two devices. Now the issue is in the live capture that doesn't show anything.

Cheers!!

**Comment by n3oxmind** [comment]
@ilyesbek , it looks like the `tail.exe` is not working.

Try these steps:
1- Add "C:\Program Files\GNS3" to your `System Environment Variables Path`
2- Start GNS3 and from `Preferences` select `Wireshark Traditional Capture` and press **Set** then select `Wireshark Live Traffic Capture` and press **Set**.
3- Apply/Okay
4- Run your project and start capturing

**Comment by ilyesbek** [comment]
@n3oxmind  Still nothing.

**Comment by cioby23** [comment]
@ilyesbek what are you using for capturing packets Winpcap or NpCAP ?
Try to use Winpcap and uninstall Npcap and then start the capture again.

**Comment by n3oxmind** [comment]
@ilyesbek, thats all I can think about have you tried to do it manually from command-line
1- set wireshark to 'Traditional Capture` and start capturing
2- From the Command-line/Powershell use this command:
```powershell
tail.exe -f -c +0b "YourProject/tmp/capturefilename" | "C:\path/to/wireshark.exe" -o "gui.window_title:%s" -k -i -
```
Thats all I can help with

> what are you using for capturing packets Winpcap or NpCAP ?

I'm using the default one that comes with gns3 packet.

P.S. I hope @grossmj  will help you with this issue.

**Comment by ilyesbek** [comment]
@cioby23  You solved it!!! the issue was NpCAP, I uninstalled it and used only WinpCAP and it worked. Thank you so much!!!
And thanks a lot to @n3oxmind  and @grossmj for taking time and staying with me through this with your help! 

Cheers!

**Comment by grossmj** [comment]
@ilyesbek excellent, I will remove Npcap from our all-in-one installer. It brings more issues than it solves.
