### ISSUE TITLE
Error During Upgrade Process

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#2727]
Hi,

I have a laptop and a desktop both running Windows 10 Pro and GNS VM version 2.1.12 installed in VMWare Workstation 12.5.9 build-7535481.   Trying to upgrade to GNS VM version 2.1.14 on both PCs but have not been successful.  I'm getting the same error.  Please see attached screenshots.  I have tried using Upgrade and Version options to upgrade and the result is the same.  Any help?

![version 2 1 14 upgrade 2](https://user-images.githubusercontent.com/17806351/53725636-6381ff80-3e3a-11e9-9d2a-01217bd518a7.png)
![version 2 1 14 upgrade 1](https://user-images.githubusercontent.com/17806351/53725637-6381ff80-3e3a-11e9-802f-45433d00af5d.png)

**Comment by grossmj** [comment]
Has your VM an Internet connection? You can test from the menu:

![internet](https://user-images.githubusercontent.com/4752614/53726493-a1197380-3ea0-11e9-9eba-fb358bdb1dc8.png)

**Comment by fatbell** [comment]
Jeremy,
The VM lost internet connection.  The issue is resolved and update is successful.  Thank you for your time.  Please close the ticket.
