### ISSUE TITLE
Unable to modify /etc/network/interfaces in order for the GNS3 QEMU VM reach the internet

### ISSUE THREAD

**Issue by jacksonier** [GNS3/gns3-gui#2728]
Description:
Unable to modify `/etc/network/interfaces` in order for the GNS3 QEMU VM reach the internet
I have the ESXi, running on HP Z420, where I have created the VM with Windows 10 x64 and VM, specifically for GNS 3 VM.
The GNS3VM KVM is enabled. Unable to make the QEMU VM reach the internet, when running on GNS3 VM.

**GNS3 version and operating system (please complete the following information):**
 - OS: GNS3 GUI (Windows x64), GNS3 VM (Linux)
 - GNS3 GUI version 2.1.14, GNS3VM 2.1.14
 - GNS3 VM is running within Ubuntu VM on ESXi:
```     gns3@gns3vm:/etc/network$ cat /etc/os-release
	NAME="Ubuntu"
	VERSION="14.04.5 LTS, Trusty Tahr"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 14.04.5 LTS"
	VERSION_ID="14.04"
	HOME_URL="http://www.ubuntu.com/"
	SUPPORT_URL="http://help.ubuntu.com/"
	BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
	gns3@gns3vm:/etc/network$ 
```  
 
Steps to Reproduce:
• Upload the Ubuntu image to the GNS3 VM: `/opt/gns3/images/QEMU/Ubuntu16.04.564bit.vmdk`, 
• Here is my `/etc/network/interfaces`

	# This file describes the network interfaces available on your system
	# and how to activate them. For more information, see interfaces(5).

	# Warning this file will be erased by each
	# GNS3 VM update; if you want to customize it
	# change the following var to 1 but DO NOT
	# remove the leading #.
	#
	# MANUAL=0

	# Host only interface
	auto eth0

	# Comment this line to disable DHCP
	iface eth0 inet dhcp
	# Uncomment this lines if you want to manually configure network
	# It's not recommended if you can avoid it.
	#
	#iface eth0 inet static
	#        address 10.10.10.10
	#        netmask 255.255.0.0
	#        gateway 10.10.0.1
	#        dns-nameservers 8.8.8.8

	# The loopback network interface
	auto lo
	iface lo inet loopback

	# NAT interface
	allow-hotplug eth1
	iface eth1 inet dhcp

	# Optional bridge interace
	allow-hotplug eth2
	iface eth2 inet dhcp

	# A vde network
	auto qemu0
		iface qemu0 inet dhcp
		vde2-switch -t qemu0

• GNS3 VM `ifconfig`:

	gns3@gns3vm:/etc/network$ ifconfig
	docker0   Link encap:Ethernet  HWaddr 02:42:80:03:75:d1
			  inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
			  UP BROADCAST MULTICAST  MTU:1500  Metric:1
			  RX packets:0 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:0
			  RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

	eth0      Link encap:Ethernet  HWaddr 00:0c:29:37:d0:62
			  inet addr:192.168.2.64  Bcast:192.168.2.255  Mask:255.255.255.0
			  inet6 addr: fe80::20c:29ff:fe37:d062/64 Scope:Link
			  UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
			  RX packets:22946 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:17740 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:1000
			  RX bytes:10752124 (10.7 MB)  TX bytes:25188117 (25.1 MB)

	lo        Link encap:Local Loopback
			  inet addr:127.0.0.1  Mask:255.0.0.0
			  inet6 addr: ::1/128 Scope:Host
			  UP LOOPBACK RUNNING  MTU:65536  Metric:1
			  RX packets:57280 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:57280 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:1
			  RX bytes:45001200 (45.0 MB)  TX bytes:45001200 (45.0 MB)

	qemu0     Link encap:Ethernet  HWaddr ba:82:01:fb:b7:d6
			  inet6 addr: fe80::b882:1ff:fefb:b7d6/64 Scope:Link
			  UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
			  RX packets:0 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:1000
			  RX bytes:0 (0.0 B)  TX bytes:9972 (9.9 KB)

	virbr0    Link encap:Ethernet  HWaddr 4e:e8:1d:9c:78:f0
			  inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
			  UP BROADCAST MULTICAST  MTU:1500  Metric:1
			  RX packets:0 errors:0 dropped:0 overruns:0 frame:0
			  TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
			  collisions:0 txqueuelen:1000
			  RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

• After I have added the Ubuntu appliance and Cloud in GNS 3 GUI, when I click on "Configure" for the Cloud, in the "Ethernet interfaces" I have only "eth0", "qemu0", "docker0", "l0", "virbr0". (snap)
• If I choose "eth0" for instance, and then start Ubuntu, which has got the IP address automatically: 192.168.2.99. But, it is not able to neither the GNS 3 VM, which is 192.168.2.64, nor the next hop gateway and DHCP server, which is 192.168.2.1

Question:
1) How should I modify the `/etc/network/interfaces` in order to be able to reach out the network from the VM running in QEMU of GNS3 VM??

Snaps:
1) GNS3 VM Config:
![image](https://user-images.githubusercontent.com/30569586/53727992-dd81ab00-3e71-11e9-9715-d8c6351988d7.png)

2) GNS3 VM, images:
![image](https://user-images.githubusercontent.com/30569586/53728006-e5414f80-3e71-11e9-82e4-1f6d14786479.png)

3) GNS3 GUI Ubuntu Template:
![image](https://user-images.githubusercontent.com/30569586/53728036-f8ecb600-3e71-11e9-89c9-7de38e5bfe1c.png)

4) GNS3 GUI Topology/Cloud node:
![image](https://user-images.githubusercontent.com/30569586/53728052-03a74b00-3e72-11e9-8fa8-d99508ab9b7f.png)
![image](https://user-images.githubusercontent.com/30569586/53728098-29cceb00-3e72-11e9-8cf9-1c67f11eb76c.png)
![image](https://user-images.githubusercontent.com/30569586/53728061-0e61e000-3e72-11e9-966a-cad53253979c.png)
![image](https://user-images.githubusercontent.com/30569586/53728063-102ba380-3e72-11e9-8012-ba2c3944af7f.png)

5) GNS3 GUI Ubuntu QEMU VM, getting IP Address assigned, but, not able to ping:
![image](https://user-images.githubusercontent.com/30569586/53728083-1c176580-3e72-11e9-972b-833985653069.png)

**Comment by jacksonier** [comment]
Unable to ping the default GW: 
![image](https://user-images.githubusercontent.com/30569586/53728272-a4960600-3e72-11e9-8df5-8787390b572e.png)

**Comment by grossmj** [comment]
The recommended way is to let your GNS3 VM get an IP address from DHCP (the default) and connect your Qemu VM to a NAT node in your project.

**Comment by jacksonier** [comment]
But, my GNS3 VM has already got the IP from DHCP, as per `iface eth0 inet dhcp`. What do you mean by connecting Qemu VM to a NAT node? In other words, the cloud appliance, listed in GNS3 GUI, is actually running on the GNS3 VM. Hence, it is showing the interfaces from the GNS3 VM.

**Comment by grossmj** [comment]
Connect your Ubuntu VM to a NAT node in GNS3, not a cloud.

![nat_node](https://user-images.githubusercontent.com/4752614/53730499-b398aa80-3eaa-11e9-9859-b5ec0bdec259.png)

**Comment by jacksonier** [comment]
Perfect! Thank you.
