### ISSUE TITLE
Unable to Esterblish Connection to VM Server GNS3

### ISSUE THREAD

**Issue by dejavoo21** [GNS3/gns3-gui#2729]
Hello,

Please i need help am unable to connect to VM server from GNS3. I get this error message most times
"Make sure GNS3 and VMware run under the same user and whitelist vmrun.exe in your antivirus."
And i have disable all Antivirus and Windows Firewall Turned-off.
Am using Windows 10 PC.
Am using GNS3 2.1.14

**Comment by grossmj** [comment]
Please post on https://gns3.com/community to receive help. Thank you.
