### ISSUE TITLE
Progress Window doesn't close when adding VirtualBox VM template

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#273]
GNS3 version 1.3.1rc4 on Darwin (64-bit), Mac OS X V10.9.5, VirtualBox 4.3.26 r98988.

When adding a new VirtualBox VM template, the progress window pops up. But it doesn't close when the loading of the VM list is done. 
![adding_vbox_vm](https://cloud.githubusercontent.com/assets/896406/7083190/28081036-df5f-11e4-8e8b-73375376561b.png)
I can't close the progress window by selecting cancel, nor can I move it. I can click into the New VirtualBox VM template window to bring it to the front and then can proceed normally. When I finish or cancel this dialog the progress window disappears.

I haven't seen this behavior on other occurrences, only when adding new VirtualBox VMs.

**Comment by ehlers** [comment]
This does NOT happen on linux, debian jessie.

**Comment by noplay** [comment]
I confirm the issue on my Mac. Not blocking, but need to be fix.

**Comment by grossmj** [comment]
This should have been fixed. Please re-open if this is not the case.
