### ISSUE TITLE
Can not import IOU in gns3 vm in 2.2 a2 

### ISSUE THREAD

**Issue by taurus8** [GNS3/gns3-gui#2737]
![8](https://user-images.githubusercontent.com/8465075/54381316-b19ccb80-46a2-11e9-9e9b-992e7146e33d.jpg)

**Comment by taurus8** [comment]
How can i launch Web Interface ?

i face following error in gns3 vm

![9](https://user-images.githubusercontent.com/8465075/54381575-62a36600-46a3-11e9-98f8-f25baa8ba387.jpg)

**Comment by grossmj** [comment]
> How can i launch Web Interface ?

Please go to the Tools menu in GNS3 and select the "WebUi" entry. This is just a preview for now, you can't really do much.

You can also just start the server with `gns3server --local --host 127.0.0.1` and open a web browser to go to ` http://127.0.0.1:3080/static/web-ui/local`

**Comment by taurus8** [comment]
Hi 
i have started gns3 server as you said and i got this error

![11](https://user-images.githubusercontent.com/8465075/54423917-fbc79080-4726-11e9-945b-86a82e69a5fe.jpg)

**Comment by grossmj** [comment]
I have fixed this error on the dev version already. Make sure you GNS3 VM has the same GNS3 version as your server (2.2.0a2) and you shouldn't get this problem.

Alternatively, you may also edit `%APPDATA%\GNS3\gns3_controller.conf` and change `"enable": true` to `"enable": false`

```
    "gns3vm": {
        "vmname": "GNS3 VM",
        "when_exit": "stop",
        "headless": false,
        "enable": true,
        "engine": "vmware",
        "ram": 512,
        "vcpus": 1
    },
```

**Comment by grossmj** [comment]
Please try again with alpha 3, we are going to release it soon. Thanks :)
