### ISSUE TITLE
VBoxManage fails if VM has specific special characters in name

### ISSUE THREAD

**Issue by It4lik** [GNS3/gns3-gui#2739]
Hi,

**Describe the bug**
When retrieving the list of Virtualbox VMs (either to configure the GNS3 VM, or juste import some VirtualBox VM to act as network clients), I got an error when some of my VMs contain certain special character in their names.
* `°` character 
* three dashes like `---`
* probably some others ?

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 Family
 - GNS3 version : 2.1.14
 - VirtualBox 6.0.4 

**To Reproduce**
1. Setup a VM with a name containing `---` or `°`
2. Retrieve list of Virtualbox VMs from GNS3 (Edit > Preferences > VirtualBox VMs > New, for example)
3. See error : "Unknown option" if using `---` or another one if using `°`

I think the VM nameneeds better handling/better use quotes/escape strings.

it4.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/dd211bce528135c7d68aa2eae5a7ab286910c34f

This should work with version >= 2.2

Thanks.
