### ISSUE TITLE
Bug when changing symbol

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#2740]
**Describe the bug**
Once I select a icon for virtual device template , If select a theme title just like 'Affinity-circle-blue'(not a icon, just title ) and click OK. it will show the error message as below :
****** Exception detected, traceback information saved in /home/wolfboy/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):

File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/gns3/modules/iou/pages/iou_device_configuration_page.py", line 147, in _symbolBrowserSlot

new_symbol_path = dialog.getSymbol()

File "/usr/share/gns3/gns3-gui/lib/python3.6/site-packages/gns3/dialogs/symbol_selection_dialog.py", line 173, in getSymbol

return current.data(0, QtCore.Qt.UserRole).id()

AttributeError: 'NoneType' object has no attribute 'id'

---------------------------------------------

**GNS3 version and operating system (please complete the following information):**
 - OS: [Lubuntu 18.04 and macOS]
 - GNS3 version [2.2.0a2]

**To Reproduce**
1. Right click one device on left list and click 'configure template'
2. Click 'Browse' for 'Symbol'
3. Click one title just like 'Affinity-circle-blue', not open it, not select one icon. 
4. Click 'OK' would show error message on GNS3 GUI Console.

![image](https://user-images.githubusercontent.com/9411604/54562675-7122b200-4a02-11e9-97f9-732a27d522f1.png)

I think these titles should not be selectable, or it should pop up a message just like "You must select one icon"

**Comment by grossmj** [comment]
Fixed. Thanks! :+1:

**Comment by superwolfboy** [comment]
Thanks! 👍
