### ISSUE TITLE
passing a function on the custom console

### ISSUE THREAD

**Issue by stkac** [GNS3/gns3-gui#2741]
Hi
I have this function for use Alacritty and Tmux but gns3-gui doesn't let me use it...

```
if [[ -x "$(command -v tmux)" && "$(ps -o 'cmd=' -p $(ps -o 'ppid=' -p $$))" = "alacritty" ]]; then
    [ -z "$TMUX" ] && { tmux new-session -s gns3 -n %d "telnet %h %p" || exec tmux -f ~/.tmux.conf && exit; }
fi
```
**I get:**

`Could not start Telnet console with command 'if [[ -x "$(command -v tmux)" && "$(ps -o 'cmd=' -p $(ps -o 'ppid=' -p $$))" = "alacritty" ]]; then [ -z "$TMUX" ] && { tmux new-session -s gns3 -n Ethernetswitch-1 "telnet 192.168.8.129 5000" || exec tmux -f ~/.tmux.conf && exit; } fi': [Errno 2] No such file or directory: 'if': 'if'`

Does someone know how to make it work?

Thanks in advance,

**Comment by grossmj** [comment]
You should put this command into a script file with executable rights and use this in GNS3.
