### ISSUE TITLE
Error while refresh the Live packet capture 

### ISSUE THREAD

**Issue by sivamsiva** [GNS3/gns3-gui#2742]
Hi

I'm getting below error if I refresh the Live packet capture

"Data written to the pipe is neither pcap format nor pcapng format"

"Please report this to the developers of program"

I'm using Wireshark to capture the packet between devices in GNS3.  (not a real time interface packet capture)

I could capture in the first time,but if I refresh capture I'm getting this error. 

I downloaded GNS3 and Wireshark from official websites recently. 

Please help someone

**Comment by sivamsiva** [comment]
Is this bug?

**Comment by grossmj** [comment]
@sivamsiva what version of GNS3 do you use?

**Comment by sivamsiva** [comment]
@grossmj 
Very Thanks for your reply.

GNS3 version :  2.1.14
wireshark version : 3.0.0
OS: windows 10 (64bit)

**tail.exe -f -c +0b %c | "C:\Program Files\Wireshark\wireshark.exe" -o "gui.window_title:%d" -k -i -**

above line is the packet capture reader command in GNS3 (which is set by default by gns3)

please let me know if you need more information.

**Comment by sivamsiva** [comment]
@grossmj 

Hi grossmj any help please ?

**Comment by grossmj** [comment]
We have fixed many issues regarding packet capture but unfortunately these fixes could not be implement in version 2.1.x. You will have to wait for the final 2.2.0 version to be released.

Sorry for the inconvenience.

**Comment by sivamsiva** [comment]
Hello @grossmj
Thanks for your support, we will wait for it. 

Please refer below link, one more user also reported the same. 

https://gns3.com/community/discussion/couldn-t-capture-on-pipe-after-r
