### ISSUE TITLE
How to simply transfer a file to the GNS3 instance, since SSH isn't supported?

### ISSUE THREAD

**Issue by alexsock** [GNS3/gns3-gui#2744]
Issue:
I need to transfer a file to the Docker instance, what are the ways available? Can I use the GNS3 VM filesystem mounted to the GNS3 instance, somehow?

Problem Description:
I am struggling to transfer a file to the UbuntuDockerGuest instance within GNS3VM, I use GNS3 GUI for managing. I connected the UbuntuDockerGuest to the outside world using NAT device.

Here is my topology:
![image](https://user-images.githubusercontent.com/30569586/54864694-f2f44180-4d5a-11e9-9848-4a27a7853f05.png)

• Since, I cannot SSH at all, It's just hanging, even the ssh server is enabled on the UbuntuDockerGuest1. 

![image](https://user-images.githubusercontent.com/30569586/54864739-b9700600-4d5b-11e9-8147-415f23cc7a03.png)

Can you explain this behavior?

• I have listed the filesystem on Docker appliance:
![image](https://user-images.githubusercontent.com/30569586/54864744-cc82d600-4d5b-11e9-9e58-19de6db352bc.png)

How can I mount, for example, the filesystem of GNS3VM to the instance of docker guest?

**Comment by grossmj** [comment]
Here is what you can try. Right click on the Docker node and select "Show in File Manager" to find out path of the Docker node then if you add files into "root" (the node must be stopped) , you should see these files inside the Docker container.
