### ISSUE TITLE
increase the size of the name of VPCS

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2745]
Hi

Currently, the size of the name of VPCS is limited to 6.

It is not always easy to find a name with only 6 characters which shows the function of the device.

Are you agree to increase it to 12 (or an other) ?

It is coded in src/vpcs.h with the variable MAX_NAMES_LEN

**Comment by Raizo62** [comment]
I believe that there is nothing to do in GNS3 : currently, GNS3 accepts vpcs's name with more of 6 characteres.

If you want, i can do a pull request on your VPCS.
(I have a also a pull request on VPCS which is waiting ;-) )

**Comment by grossmj** [comment]
I have merged your changes and released VPCS version 0.6.2 on PPA unstable and it will be included in our next macOS/Windows packages for GNS3 version 2.2
