### ISSUE TITLE
Wireshark capture - Stop and start capture

### ISSUE THREAD

**Issue by Aeisen0** [GNS3/gns3-gui#2747]
**Describe the bug**
When the GNS3 capture on a link is stopped, and then a new one on the same link is created later, nothing is showing in wireshark but the old packets.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10
 - GNS3 version 2.1.15
 - GNS3 VM is used

Tested with Wireshark 2.6.5, Wireshark 3.0, Winpcap and Npcap

**Comment by grossmj** [comment]
This is a bug we have fixed in GNS3 2.2, currently in alpha stage. The workaround is to change the name of the packet capture file when you start another capture on the same link. Sorry for the inconvenience.
