### ISSUE TITLE
 GNS3 makes CPU 100% and RAM 98% all times.

### ISSUE THREAD

**Issue by ykla** [GNS3/gns3-gui#2748]
It hardly works well on any normal notebooks. What a fuck software that it makes CPU 100% and RAM 98% ! Even I am using intel core i7-8750H and 16G RAM.

**Comment by grossmj** [comment]
There must be something you do wrong. What is your topology and what kind of appliances do you use?

A common mistake is to create a layer 2 loop in your virtual network which consume 100% of CPU.

**Comment by ykla** [comment]
Like 
![-6a117b4c4735639](https://user-images.githubusercontent.com/10327999/54910141-b412e700-4f26-11e9-988b-229a38100a81.jpg)

**Comment by ykla** [comment]
I don't think it is my mistake because of any simple example  also always my notebook CPU 100% and RAM 100% usages. Do you running GNS3 in your real PC ? I can't image what's computer are you using.

**Comment by grossmj** [comment]
It does not seem you can get a layer 2 loop. Going from there I would start nodes one by one, waiting one if fully started before moving to the other one while checking if the CPU goes to 100%. This way you should  find which node or image creates the problem.
