### ISSUE TITLE
3725 router and the 2600 Router name are invalid

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#275]
It's ESW1 and SW2 instead of R1 and R2.

https://community.gns3.com/message/24855?et=watches.email.thread#24855

**Comment by noplay** [comment]
It seem it's a confusion from the user. Do you confirm?

**Comment by grossmj** [comment]
It is where we decide if the base name is ESW or not. I think he added routers with an NM-16ESW in slot1.

```
            if "slot1" in settings and settings["slot1"] == "NM-16ESW":
                # must be an EtherSwitch router
                base_name = "ESW"
```
