### ISSUE TITLE
GNS3 version 2.2.0a3 error mesages on closing GNS3 application

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2750]
Windows 10 Prof X64 VMware Workstation Pro 14.1.6 build-12368378
Running GNS3 version 2.2.0a3 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2019 GNS3 Technologies.
All seems working fine except for one oddity.  When I close GNS3 after opening and running a project several error message appear briefly in the upper right hand corner of the application stating "The remote host closed the connection", "Connection refused", "Unknown error", "Unknown error", "Unknown error", "Unknown error".  These messages do not appear if I merely open the GNS3 application, modify some preferences and then close the application.  I believe these same messages appeared in versions 2.2.0a1 and 2.2.0a2
As always, thanks for all the hard work!

**Comment by grossmj** [comment]
Fixed, these messages should not appear in version 2.2.0a4. Please comment here if you still see them. Thanks :+1:
