### ISSUE TITLE
Have GUI load project even if images are missing

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2752]
Hi friends,

This is for 2.1.15 running on a remote server.

We recently had an issue where we lost all docker data on our GNS3 server.  This included a couple of custom images that we are unable to get back.  (Not having backups is a different issue ;)

We noticed that when we attempt to load a project that uses this image, the GUI will of course generate an error that the image is not found, but then it stops loading the project.

It would be nice if there was a yes/no option to continue loading the project without the broken images so that we don't have to edit the project files by hand.

**Comment by cioby23** [comment]
@CapnCheapo I also experienced this issue several times when changing or updating images. There is an issue already opened for this https://github.com/GNS3/gns3-gui/issues/2575 which has the milestone set to version 2.2.1.

**Comment by CapnCheapo** [comment]
Whoops, sorry for the dupe guys, closing.
