### ISSUE TITLE
Migrate versioned config file

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2756]
Starting with version 2.2 the config files are stored in a specific directory corresponding to the version number (major.minor). This allows to use different versions of GNS3 on the same computer without conflicts for the settings (e.g. version 2.2 overwriting version 2.1 settings).

For the next 2.3 version, we need to implement something to migrate the config file from a previous version of GNS3 (for instance 2.2 -> 2.3).

**Comment by jtorri** [comment]
Been switching between multiple version of GNS3 on Windows for a while.  My method is too complicated. Nonetheless, it relies upon a consistently named group of folders and the constants in the .ini files to which values are assigned not changing.  For example in gns_server.ini

path = C:\Program Files\GNS3 version#\gns3server.EXE
ubridge_path = C:\Program Files\GNS3 version#\ubridge.EXE
host = 127.0.0.1
port = 3080
images_path = C:\GNS3Files\ImagesFolder
projects_path = C:\GNS3Files\GNS3 version#\Projects
appliances_path = C:\GNS3Files\GNS3 version#\appliances
additional_images_paths = 
symbols_path = C:\Users\username\GNS3\symbols
configs_path = C:\GNS3Files\GNS3 version#\configs

**Comment by jtorri** [comment]
Question.  Should the folder in which the version config is saved have more defining digits? For example, after GNS3 2.1.0 there are quite a few version before 2.1.5.  Or is the goal solely to differentiate between version 2.1x and 2.2x?
Thanks!

**Comment by grossmj** [comment]
Right now we only do with major.minor (2.2, 2.3 etc.). Maybe it would be better to support the full version? 2.2.0 2.2.1, 2.2.2, 2.3.0 etc. What do you think?

**Comment by jtorri** [comment]
I noticed the INI files are saved to folder "2" in GNS3 nightly build 04 02.  As to answering your question, I suppose it depends to a large extent on the effort required to implement and the advantages gained.  For me being able to switch between versions, whether a major (2.1.x vs 2.2.x) or minor (2.1.4 vs 2.1.5 or 2.2.0a2 vs 2.2.0a3) allows me to continue working with a more stable version while trying to help debug a less stable version and evaluate its new features.  I suppose the first question to answer is the level of difficulty to implement.

**Comment by grossmj** [comment]
This should be fairly straightforward to implement. I am thinking about asking users if they want to copy the INI files from a previous version when the ones for the current version don't exist.

**Comment by jtorri** [comment]
As you know better than I, the issue of GNS3 on Windows will also involve "migrating" to a newer version of the GNS3 VM. At the moment I use cloning followed by upgrading via the GNS3 VM menu option.  There is also the issue of the folders,e.g., projects, configs, exported configs, etc. associated with a specific GNS3 version.  In particular, the \Projects\"Projectname"\"projectname".gns3 contains entries specific to the GNS3 version as one of the last entries in the file, e.g., "version": "2.2.0a3"
Hope I am making sense.
I have noticed on the GNS3 2.2 version of the GNS3 VM you now provide multiple version upgrade options.

**Comment by ak2766** [comment]
> Starting with version 2.2 the config files are stored in a specific directory corresponding to the version number (major.minor). This allows to use different versions of GNS3 on the same computer without conflicts for the settings (e.g. version 2.2 overwriting version 2.1 settings).
> 
> For the next 2.3 version, we need to implement something to migrate the config file from a previous version of GNS3 (for instance 2.2 -> 2.3).

This indeed a good idea - just went to test 2.2.0a3 but unfortunately I wasn't informed that my config would be obliterated.  It was a good thing that I didn't have much configured after rebuilding my laptop otherwise I'd have cried oceans.  I was previously running tag v2.1.15.

**Comment by grossmj** [comment]
I decided to keep major.minor (e.g 2.2, 2.3, 2.4 etc) instead of the full version 2.2.0, 2.2.1 for the path where config files are stored. Only thing left is to handle the migration, for instance from 2.2 to 2.3
