### ISSUE TITLE
Bad error message when connecting cloud to VirtualBox device.

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#276]
See https://community.gns3.com/thread/7932.

I assume the error itself is OK, connections between cloud devices and VirtualBox VMs don't work (at least in earlier versions they didn't work). But the error message is not very helpful.

Server error from 192.168.1.10:8000: junOS-1: Invalid JSON: {'ethernet_device': 'en1', 'type': 'nio_generic_ethernet'} is not valid under any of the given schemas in schema: {"required": ["type"], "description": "Request validation to add a NIO for a VirtualBox VM instance", "additionalProperties": true, "oneOf": [{"$ref": "#/definitions/UDP"}], "type": "object", "$schema": "http://json-schema.org/draft-04/schema#", "definitions": {"UDP": {"properties": {"lport": {"maximum": 65535, "description": "Local port", "minimum": 1, "type": "integer"}, "rhost": {"minLength": 1, "description": "Remote host", "type": "string"}, "rport": {"maximum": 65535, "description": "Remote port", "minimum": 1, "type": "integer"}, "type": {"enum": ["nio_udp"]}}, "description": "UDP Network Input/Output", "required": ["type", "lport", "rhost", "rport"], "additionalProperties": false}}}

****** Exception detected, traceback information saved in /Users/behlers/.config/gns3.net/exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/support/bug

Traceback (most recent call last):
  File "gns3/http_client.pyo", line 378, in _processResponse
gns3.http_client.HttpBadRequest: {
    "message": "Invalid JSON: {'ethernet_device': 'en1', 'type': 'nio_generic_ethernet'} is not valid under any of the given schemas in schema: {\"required\": [\"type\"], \"description\": \"Request validation to add a NIO for a VirtualBox VM instance\", \"additionalProperties\": true, \"oneOf\": [{\"$ref\": \"#/definitions/UDP\"}], \"type\": \"object\", \"$schema\": \"http://json-schema.org/draft-04/schema#\", \"definitions\": {\"UDP\": {\"properties\": {\"lport\": {\"maximum\": 65535, \"description\": \"Local port\", \"minimum\": 1, \"type\": \"integer\"}, \"rhost\": {\"minLength\": 1, \"description\": \"Remote host\", \"type\": \"string\"}, \"rport\": {\"maximum\": 65535, \"description\": \"Remote port\", \"minimum\": 1, \"type\": \"integer\"}, \"type\": {\"enum\": [\"nio_udp\"]}}, \"description\": \"UDP Network Input/Output\", \"required\": [\"type\", \"lport\", \"rhost\", \"rport\"], \"additionalProperties\": false}}}",
    "path": "/v1/projects/{project_id}/virtualbox/vms/{vm_id}/adapters/{adapter_number:\\d+}/ports/{port_number:\\d+}/nio",
    "request": {
        "ethernet_device": "en1",
        "type": "nio_generic_ethernet"
    },
    "status": 400
}

**Comment by noplay** [comment]
Thanks for the bug report

**Comment by ak2766** [comment]
It seems that an attempt to connect a cloud device to a VM causes other side effects.  In my case, it caused my VM's interfaces to have the same name - namely Ethernet1:
https://community.gns3.com/ideas/1723 (see my own responses - especially the last edit!

Cheers,
ak.

**Comment by grossmj** [comment]
Fixed, thanks for the bug reports guys. :+1:
