### ISSUE TITLE
2.2 : IOS : GNS3 can't detect the platform

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2760]
Hi

I have an IOS file with this name : c3725-adventerprisek9-mz.124-25d.image
(I use this name since a long long time)

When i want to create a "New IOS router Template", and i choose this existing image (with this name), GNS3 says "Could not detect the platform, make sur this is valid IOS image!".
GNS3 chooses as default value the platform c2691

**Comment by grossmj** [comment]
Fixed.
