### ISSUE TITLE
2 Projects running in background bridged after server restart

### ISSUE THREAD

**Issue by pcapdevila** [GNS3/gns3-gui#2761]
I was running two projects in background. I had to restart the server for some reason and after that I find that the topology I was working on was not working properly. I started troubleshooting and saw strange OSPF debug log messages with IPs I had not configured. 

What I found is that in the CDP neighbours I was seeing routers from the other topology. I stopped the other topology and removed the run in background setting but I stil see unexpected routers in sh CDP neighbors. So the internal bridges and background projects are totally messed up, I assume.

 - OS: Debian Stretch
 - GNS3 2.1.14 bare metal

1. Create a topology and leave it running in background
2. Create another topology and leave it running in background
3. Restart server
4. Topologies are mixed up. For instance in Local Interface Gi2 I see neighbors from the other topology

> P#sh cdp ne
> Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge
>                   S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone, 
>                   D - Remote, C - CVTA, M - Two-port Mac Relay 
> 
> Device ID        Local Intrfce     Holdtme    Capability  Platform  Port ID
> SW1-2            Gig 2             141             R S I            Gig 0/0
> SW2              Gig 2             139             R S I            Gig 0/1
> P1               Gig 1             120               R    IOS XRv S Gig 0/0/0/0
> CSR1Kv2          Gig 2             149              R I   CSR1000V  Gig 1
> CSR1Kv1          Gig 1             145              R I   CSR1000V  Gig 1
> 
> Total cdp entries displayed : 5

**Comment by pcapdevila** [comment]
Si I found the culprit. It turned out that several appliances were left running without GNS being aware. This is why they could appear as CDP neighbours although the projects they belong were shut down.

**Comment by grossmj** [comment]
I understand there is not bug, I am going to close this then. Thanks :+1:
