### ISSUE TITLE
GNS3 2.2.0a3 VM to GNS3 2.2.0a4 VM upgrade failure

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2763]
Window 10 Prof  VMware Workstation 14.1.7 build-12989993
Did full clone of GNS3 2.2.0a3 VM then ran the VM menu option to upgrade to VM version 2.2.0a4
Errors were displayed during upgrade and the following screen appeared.  When done the VM informational screen showed version 2.2.0a3.
Screen displayed at end of unsuccessful "upgrade":
![GNS3-2 2 0a3to2 2 0a4clone](https://user-images.githubusercontent.com/10285348/55673912-37fc9580-587c-11e9-9eb2-9af11f3ab001.png)
Screen displayed when exited from command line showing still version 2.20.a3
![GNS3-2 2 0a3to2 2 0a4clone2](https://user-images.githubusercontent.com/10285348/55673924-5793be00-587c-11e9-8835-4cbee6a1dda1.png)
Did not find any useful information in gns3.log though not sure if I should have.
Thanks!

**Comment by jtorri** [comment]
Just an FYI. I downloaded and installed GNS3.VM.VMware.Workstation.2.2.0a4.  When powered on it correctly displayed as GNS3 2.2.0a4.  Just to see what would happen, I ran the menu option to upgrade to version 2.2.0a4.  The same error as noted above occurred.  Thanks!

**Comment by grossmj** [comment]
Sorry, I messed up with the upgrade script. I fixed it and you can try again. Thanks :)
