### ISSUE TITLE
Adding multiple devices - stuck progress window

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2765]
WIndows, GNS3 v2.1.15

See also <https://www.gns3.com/community/discussion/bug-adding-multiple-devices-into>

Adding multiple devices at once (shift-drag a device to a project and enter a high number of devices to add) results in a stuck progress bar. It never gets to 100%. The only way to recover is to end GNS3. The devices are successfully added and after restarting GNS3 they can be used without any issues.

This happens with local server as well as with the GNS3VM and remote servers. It seems to be independent of the device type, it happens even for VPCS devices.

**To Reproduce**

1. Create a new project
2. Drag a device (for example VPCS) from the sidebar to the project area and hold the shift key when releasing it.
3. Enter a high number of devices to add. With my computer adding 10 devices always show this behavior.

**Screenshot**

![add_multiple_devices](https://user-images.githubusercontent.com/49040325/56022872-f0a75680-5d0c-11e9-93bd-cd4db353af71.png)

**Additional context**

The last working windows version is v2.1.12, v2.1.13 is the first one, that shows this behavior.

This does **NOT** happen with the GNS3 v2.1.15 package for macOS.

I then tried with a self-made GNS3 v2.1.15 on macOS with different versions of python modules. I can always reproduce this issue, when I'm using PyQt v5.11 or v5.12, with PyQt v5.10.1 it's working fine. Also note, that the GNS3 provided package of GNS3 v2.1.15 uses the older PyQT v5.10.1. Changing the versions of other python modules doesn't have an influence.

Also using GNS3 v2.1.15 on Debian Buster with it's PyQt 5.11.3 shows this issue. On Windows v2.1.13 is also the first version using a newer PyQt. So I'm pretty confident, that PyQt v5.11 and up triggers this issue.

**Comment by EB-athila** [comment]
I've seen this behavior on GNS3 v2.2.0a4 as well. It happens when starting 5 or more devices (in my case) at the same time too.

My system information:
HOST:
Running GNS3 version 2.2.0a4 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Windows 7 Professional, 64-bit 6.1.7601, Service Pack 1
Intel Core i5-2520M
16GB RAM
VMware Workstation 14.1.3 build-9474260

VM:
GNS3 VM
8GB RAM
2 vCPUs
GNS3 server version: 2.2.0a4
Release channel: 2.2dev
VM version: 0.10.16
Ubuntu version: bionic

**Comment by grossmj** [comment]
I couldn't find the root cause because how we handle the progress bar is currently a mess however these fixes seem to solve the problem.

**Comment by b-ehlers** [comment]
Just tested on macOS with PyQt5 v5.12.1, looks good. Thanks a lot.
