### ISSUE TITLE
Host device et interface wlan0 down

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#277]
Bonjour

Quand on connecte un cable sur HostDevice, le HostDevice affiche toutes les cartes réseaux disponibles.

Mais si la carte réseau est down (wlan0), GNS3 affiche un message d'erreur peu explicite sur l'erreur (le fait qu'elle soit down).
 
Peut être que le HostDevice ne devrait afficher que les interfaces "up" ? ou mettre un message d'erreur indiquant qu'il faut activer la carte avant ?

**Comment by noplay** [comment]
Merci on va regarder

**Comment by grossmj** [comment]
We can use netifaces to know if an interface is up or down:

```
def isAnInterfaceUp(anInterface):
    addr = netifaces.ifaddresses(anInterface)
    return netifaces.AF_INET in addr
```

**Comment by grossmj** [comment]
Done in https://github.com/GNS3/gns3-server/commit/042472f02cec4e004685e5fec0d6fe46afa9c987
