### ISSUE TITLE
2.2.0a5: symbol theme does not work

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2770]
It has no effect, regardless if
* I have a project open,
* open an existing project or create a new one after changing this setting,
* or restart the GUI after setting it.

**Comment by grossmj** [comment]
We have only an early support of symbol themes. This is only used when you add a new template with the template wizard using the recommended method.

**Comment by adosztal** [comment]
Can you maybe add a tooltip describing this? I'm afraid people might get confused without that.

**Comment by grossmj** [comment]
Done, should be less confusing now.
