### ISSUE TITLE
2.2.0a5: WebUI starts at 0,0 position

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2771]
The GUI shows the center of the topology but when I open it in the Web UI, it shows the top left corner:
![VirtualBox_gns3-testing-client_15_04_2019_19_35_09](https://user-images.githubusercontent.com/16632791/56153213-e8257900-5fb5-11e9-970a-4b9337dcf00a.png)

**Comment by ziajka** [comment]
Thanks for reporting this @adosztal, we will be tracking it here: https://github.com/GNS3/gns3-web-ui/issues/375. I'm giving a status 'Duplicate' just to make sure there is now two tasks the same.
