### ISSUE TITLE
Mouse action over device changed

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2773]
Windows 10 Prof VMware® Workstation 14 Pro 14.1.7 build-12989993
GNS3-2.2.0a5-all-in-one.exe and GNS3.VM.VMware.Workstation.2.2.0a5.zip

Created topology without problems. However, right mouse functionality which clicking on device in the topology, e.g., ASAv or IOSv, produces erratic results.  In previous version it displayed the menu with config, console, start, etc options.  Now it will sometimes displays the configuration window and sometimes the menu with config, console, start, etc.
Hope this makes sense.  Thanks!

**Comment by adosztal** [comment]
If you keep the right button clicked, you can select a menu item without clicking on it (right click --> move the mouse over the menu item --> release mouse button --> action happens). Are you sure you didn't move the mouse accidentally?

**Comment by jtorri** [comment]
Well, it seems I cannot fully recreate what I described so it seems very likely the problem likes with the user....that would be me!  Please feel free to close this one!  Thanks!
