### ISSUE TITLE
BUG : 2.2 : can't start console of ethernetswitch

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2776]
Hi

When i start the texte console of the ethernet switch, this console disappears immediately

**Comment by cioby23** [comment]
I'm not sure if this commit https://github.com/GNS3/gns3-server/commit/1f1d93d078366dbc52a14b6d6e913a58e8c3c5f3 (Deactivate the embedded shell for Ethernet switch. Ref #1424 #1556)
is related for this issue.

**Comment by Raizo62** [comment]
Then the "console type" in the configuration of the ethernetswitch must be "none", and it would have to remove all other choice (like telnet)

**Comment by grossmj** [comment]
I have set "none" by default but didn't remove "telnet" option has we are likely to add it back in the future version however there is a warning if you try to use this option.

**Comment by Raizo62** [comment]
But why do you not remove now the "telnet" option ? You will can add again the option "telnet" in the same time when you add back this functionality

**Comment by grossmj** [comment]
@Raizo62 because I am afraid to break something with older projects that have console_type set to "telnet", I found a warning was a safer option.

**Comment by Raizo62** [comment]
Yes you are right
