### ISSUE TITLE
Silent uninstall

### ISSUE THREAD

**Issue by Ocean1234567** [GNS3/gns3-gui#2777]

**Comment by Ocean1234567** [comment]
Unable to uninstall silently for SCCM deployment using /S switch. 
Getting 2 popups and unable to hide and auto select the options to uninstall.

**Comment by ziajka** [comment]
Hi @Ocean1234567. Could you please send us screenshots of those popups? Thank you

**Comment by Ocean1234567** [comment]
Please refer to the 2 screenshots attached.


![screenshot one](https://user-images.githubusercontent.com/48482873/56860272-615b9d80-69b2-11e9-9a16-9473638bcbda.PNG)
![screenshot two](https://user-images.githubusercontent.com/48482873/56860273-61f43400-69b2-11e9-898f-0f0704232dfa.PNG)

**Comment by ziajka** [comment]
Thank you @Ocean1234567

**Comment by Ocean1234567** [comment]
Any update will be appreciated

**Comment by Ocean1234567** [comment]
Hi Ziajka,

Any update will be appreciable.





*Regards,*


*Preeti Samyal*

Technologist II,  Infrastructure Applications

IT Service Center

*Direct:* +91 172.432.1402 |* Mobile:* +91 828.802.4720

*Speed Dial: **91 1402

*PSamyal@oceaneering.com <PSamyal@oceaneering.com>*

infra-application_packaging-oii@oceaneering.com

[image: OII-blue-302c-01.png] <http://www.oceaneering.com/>

Oceaneering Int. Services Ltd. | Ground Floor | Tower - E | DLF IT Park |
Chandigarh, INDIA - 160101  | +91 172.432.1500 | oceaneering.com

**Comment by ziajka** [comment]
Hi @Ocean1234567,
We are investigating the issue. Will keep you updated.

**Comment by grossmj** [comment]
@Ocean1234567 we will fix this in our next release. Thanks for catching this :+1:

**Comment by grossmj** [comment]
Support for silent uninstall is ready for our next release.
