### ISSUE TITLE
Once open two GUI on Linux, one for exam and running some device , close the other GUI, the gns3server stop and the exam of the first GUI stop.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#278]
Ubuntu gnome 14.10 with GNS3 1.3.1
No upstart just default .
When I open two clients and one is running some devices, at this moment close the other client, 
the running devices of first one stop and can not be connected. 
looks like the second client stopped the gns3server when it closed.

By the way, my another question is :if  I use upstart scripts for automatically start gns3server, then open GUI on same machine ,the GUI will start other gns3server with random port, not use the instance which is already running during system boot , is it necessary ?

**Comment by noplay** [comment]
It's fixed in listen_notification branch but we need to review it with @grossmj

**Comment by noplay** [comment]
Tested it's work in 1.4
