### ISSUE TITLE
capture starts and stops after a while

### ISSUE THREAD

**Issue by lostlsend** [GNS3/gns3-gui#2782]
**Describe the bug**
Wireshark is actually fed with packets captured from the remote server without problem at the begining, but stops after a while (local file stop receiving updates), but the capture file on the remote server is still growing. If I restart wireshark, there's no change. If I stop capture and restart capture from the GUI, wireshark starts to receive data and ceases again after a while.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 x64
 - GNS3 version: 2.1.16
 - Using GNS3 VM (2.1.16) on a remote server (VMware Workstation 15); no local server

**Screenshots or videos**
![1](https://user-images.githubusercontent.com/38998401/57501625-45130700-72b6-11e9-8de0-57dba1e5f28b.PNG)
Try to open the captured file on remote server, Wireshark gives the error message shown above.

**Comment by grossmj** [comment]
Unfortunately fixing this in our 2.1.x branch is too complicated. We have re-factored packet capture support in our next major version 2.2, the first beta version should be released soon.

**Comment by Str1ker17** [comment]
2.2 is released long time ago but the bug is still present.
The difference is that no error messages are shown. Packet capture just stops after some time, i.e. no new packets are appended to Wireshark; the status of capture is active.
