### ISSUE TITLE
Cannot load new profile in GNS3 2.2.0a5

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2784]
**Describe the bug**

I have 2 GNS3 servers running each on different remote machines.  I have configured the main remote server and I can connect to it successfully when starting GNS3-GUI.
I tried to use the new profile wizard when I start the GUI and create a new profile pointing to the secondary remote GNS3 server the wizard runs fine and after I start the GUI again profile does not appear on the list

**GNS3 servers version 2.2.0a5 running on Ubuntu/Archlinux:**
 - OS:  Windows 7
 - GNS3 version 2.2.0a5
 - Both remote servers run on bare metal Linux (Ubuntu/Archlinux)

**To Reproduce**
1. Open GNS3-GUI (I have the **Request for profile settings at application startup** enabled in the Preferences)
2. The Profile section dialog appears (default profile is automatically enabled)
3. Click New  button to create a new profile and the type the profile name.
4. Run the wizard (select Run appliances on a remote server)
5. Fill in the details (host port and credentials) and press Next then Finish.
6. When I try to start the GUI again I cannot select any of the new created profiles (the folder profiles appeared created under C:\Users\<username>\AppData\Roaming\GNS3\2.2\profiles

**Additional context**
N/A

**Comment by grossmj** [comment]
Fixed. Thanks :+1:
