### ISSUE TITLE
2.2 : REQ : add a variable for vsock in "Additional settings" of qemu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2786]
Hi

With qemu, we can use vsock to communicate between VM and their host, without IP.

On the host, we need the module vhost_vsock (included in recent kernel). On the guests, we need the module vmw_vsock_virtio_transport.

But, we need to start the Qemu VM with the option : `-device vhost-vsock-pci,id=vhost-vsock-pci0,guest-cid=3`
the number "3" is an identifier greater than 2 (which identifies each guest)

In the "Additional settings" of qemu, can we have a variable with an unique identifier greater than 2 ? To beginning, i suppose that the port number is a good value

**Comment by grossmj** [comment]
I added the `%console-port%` variable in addition of those variables: `%vm-name%`, `%vm-id%`, `%project-id%` and `%project-path%`

**Comment by Raizo62** [comment]
Thanks :-)
