### ISSUE TITLE
GNS3 2.1.17 appliance template imports but image does not

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2787]
**Describe the bug**
Import Appliance from GNS3 application menu and all seems to be fine.  However, the image is not to be found in /opt/gns3/images/QEMU.  I believe I had this issue with a previous 2.1.x version.  Hopefully the issue is not user error!

**GNS3 version and operating system (please complete the following information):**
Windows 10 Prof  VMWare workstation 14 (using the GNS3 VM supplied with GNS3 2.1.17)
GNS3 management console.
Running GNS3 version 2.1.17 on Windows (64-bit) with Python 3.6.8 Qt 5.12.3 and PyQt 5.12.2.
All components run locally.

**Screenshots or videos**
The file (image) listed in this dialog does not exist in /opt/gns3/images/QEMU
![GNS3 2 1 17 appliance issue](https://user-images.githubusercontent.com/10285348/57963170-92165f00-78ee-11e9-99dc-272f93f38f13.png)

**Comment by grossmj** [comment]
I believe this has been fixed in version 2.2, have you had a change to try with our latest alpha/beta?

**Comment by jtorri** [comment]
It does seem to work in version 2.2.0a5
