### ISSUE TITLE
Similar issue regarding to #1886. Can not capture PPP on real IOS...

### ISSUE THREAD

**Issue by ralikhani110** [GNS3/gns3-gui#2788]
Cannot capture PPP traffic on serial links on real IOS images. Please look at the following figure:

https://pasteboard.co/Iff3P0X.png

As you can see, although the encapsulation of the link is PPP, but the capture mentions it as HDLC.

Thanks

**Comment by grossmj** [comment]
Just tested and couldn't find anything wrong. Make sure both interfaces for the link you are capturing on are set to PPP:

```
R1#show interfaces serial 1/0
Serial1/0 is up, line protocol is up 
  Hardware is M4T
  Internet address is 10.0.0.1/8
  MTU 1500 bytes, BW 1544 Kbit/sec, DLY 20000 usec, 
     reliability 255/255, txload 1/255, rxload 1/255
  Encapsulation PPP, LCP Open
```

Also, make sure you select "Cisco PPP" for the link type when you start the packet capture:

![start_ppp_capture](https://user-images.githubusercontent.com/4752614/57967136-66928380-7985-11e9-849e-7bb3921e1f84.png)

![ppp_encapsulation](https://user-images.githubusercontent.com/4752614/57967109-29c68c80-7985-11e9-97a7-e503b9bdbf62.png)

**Comment by ralikhani110** [comment]
Thanks. The problem was my mistake. I have not selected the correct protocol from the **Link Type** field.

Thanks again
