### ISSUE TITLE
[2.2b1] Locked Item allows its link label to be moved

### ISSUE THREAD

**Issue by EB-athila** [GNS3/gns3-gui#2794]
Locked Item Allows its link label to be moved

 - OS: Wndows 7
 - GNS3 version 2.2.0 beta 1
 - GNS3 VM

1. Place two devices into canvas and place a link to connect each other.
2. Click "show link labels" toolbar icon.
3. Select one or both devices.
4. Right click and select "Lock/Unlock"
5. Move or edit locked item's link label.

**Comment by grossmj** [comment]
It should be good now. Thanks for catching that.
