### ISSUE TITLE
GNS3 2.1.18 VMware Workstation VM error reading VMX file

### ISSUE THREAD

**Issue by fnetworksio** [GNS3/gns3-gui#2796]
GNS3 2.1.18 VMware VM on VMware Workstation Pro 15 (Linux)

Error importing the .ova file:

VMMgr: Failed to open pending VM: VMX file is corrupt

Thanks!

**Comment by grossmj** [comment]
I am going to investigate this

**Comment by fnetworksio** [comment]
Solved.

libsnl and libcrypt (v1) needed for the ovftool and missing on Fedora 30.

Sorry for opening this issue
