### ISSUE TITLE
GNS3 client automatic upgrade fails

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2797]
**Describe the bug**
I have installed GNS3 GUI version 2.2.0a5 and try to upgrade to version 2.2.0b1 using the **Check for update** feature.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 7 64 bit
 - GNS3 version: 2.2.0a5
 - Remote server (Ubuntu Linux 18.04) runinng GNS3 server on bare metal

**To Reproduce**
1. Open GNS3 client and select Help --> Check for update.
2. A popup window appear: "**Newer GNS3 version 2.2.0b1 is available, do you want to to download it in background and install it at next application launch**?"
3. Click Yes.
4. After few seconds another popup window appears: "**GNS3 upgrade downloaded do you want to quit the application?**"
5. Click Yes. (GNS3 GUI will close)
6. Open again the GNS3 GUI.
7. In the background it tries to update it but it fails and the following popup message appears: "**Unsupported file extension exe for C:\Program Files\GNS3\Files\GNS3\gns3.exe**"
8. Click OK and check Help -> About menu (version is still he old one 2.2.0a5) 

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/7124193/58227775-f1340380-7d34-11e9-84e8-ecc4500fde52.png)

**Additional context**
N/A

**Comment by grossmj** [comment]
This is something I never test, have you been successful with the automatic upgrade for other version of GNS3?

**Comment by cioby23** [comment]
This is the first time I did this test. 
In the end I have manually upgraded by downloading the 2.2.0b1 release from Github and installing it.

**Comment by grossmj** [comment]
I understand why you got that option, this is because you have activated the experimental features in the GNS3 preferences. That's also why I never test it ;)

**Comment by grossmj** [comment]
This feature only supports upgrading from Pypi, Windows and macOS are not supported. I will fix this.

**Comment by grossmj** [comment]
Done
