### ISSUE TITLE
after upgrading I can't open my previous projects

### ISSUE THREAD

**Issue by Akbar78** [GNS3/gns3-gui#2798]
![GNS3 error](https://user-images.githubusercontent.com/50184260/58238220-db164b00-7d14-11e9-9802-30ea170a25fc.JPG)

I uninstalled my previous installation of GNS3 (2.1.11), then downloaded and installed the latest version (2.1.18).
Now I can't open my projects in C:\Users\<username>\GNS3\projects

**Comment by grossmj** [comment]
Please post the content of your .gns3 file in the project. Thanks

**Comment by Akbar78** [comment]
{
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "grid_size": 75,
    "name": "Lab 2-1 - EIGRP Load Balancing - Tshoot",
    "project_id": "4c9962a1-4d36-4951-b154-edaf30e831b1",
    "revision": 9,
    "scene_height": 1000,
    "scene_width": 2000,
    "show_grid": false,
    "show_interface_labels": true,
    "show_layers": false,
    "snap_to_grid": false,
    "supplier": null,
    "topology": {
        "computes": [],
        "drawings": [
            {
                "drawing_id": "979277f3-359f-4fb4-b519-fac7e573d9a9",
                "rotation": 0,
                "svg": "<svg height=\"71\" width=\"164\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">Lo21: 10.1.2.1/30\nLo25: 10.1.2.5/30\nLo29: 10.1.2.9/30</text></svg>",
                "x": -63,
                "y": -279,
                "z": 1
            },
            {
                "drawing_id": "0d4934fd-0a26-4a97-90cb-55b3d325dfc4",
                "rotation": 0,
                "svg": "<svg height=\"71\" width=\"164\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">Lo11: 10.1.1.1/30\nLo15: 10.1.1.5/30\nLo19: 10.1.1.9/30</text></svg>",
                "x": -301,
                "y": 151,
                "z": 1
            },
            {
                "drawing_id": "f63cf4b0-3d09-40d9-b817-b41932f13209",
                "rotation": 0,
                "svg": "<svg height=\"71\" width=\"164\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">Lo31: 10.1.3.1/30\nLo35: 10.1.3.5/30\nLo39: 10.1.3.9/30</text></svg>",
                "x": 188,
                "y": 151,
                "z": 1
            },
            {
                "drawing_id": "5a6f288b-2815-4264-9f7e-2520b7761e82",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"132\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">10.1.102.0/29</text></svg>",
                "x": -223,
                "y": -62,
                "z": 1
            },
            {
                "drawing_id": "f03fa810-c8ad-4a7a-9f36-c3715c20a603",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"132\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">10.1.203.0/29</text></svg>",
                "x": 144,
                "y": -54,
                "z": 1
            },
            {
                "drawing_id": "bd5e74c5-f474-4fbe-af55-5588a70357c2",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"132\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">10.1.103.0/29</text></svg>",
                "x": -45,
                "y": 126,
                "z": 1
            },
            {
                "drawing_id": "ddd5f98c-f202-4d8b-9faa-7fda3d905490",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.1</text></svg>",
                "x": -187,
                "y": 78,
                "z": 1
            },
            {
                "drawing_id": "00ede2ea-e400-4ce1-b572-b9192e92c0e6",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.1</text></svg>",
                "x": -162,
                "y": 99,
                "z": 1
            },
            {
                "drawing_id": "6d55cfbf-652d-4fcf-95f0-2e796044153e",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.2</text></svg>",
                "x": -13,
                "y": -155,
                "z": 1
            },
            {
                "drawing_id": "b03604b9-93f9-4673-b359-4254dfe2eb08",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.2</text></svg>",
                "x": 26,
                "y": -155,
                "z": 1
            },
            {
                "drawing_id": "70050ea7-29f2-497a-9ec5-76dba526532a",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.3</text></svg>",
                "x": 200,
                "y": 97,
                "z": 1
            },
            {
                "drawing_id": "503e40de-b17b-45b1-9bda-21edd43a814c",
                "rotation": 0,
                "svg": "<svg height=\"29\" width=\"24\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"TypeWriter\" font-size=\"10.0\" font-weight=\"bold\">.3</text></svg>",
                "x": 209,
                "y": 72,
                "z": 1
            },
            {
                "drawing_id": "4a3f2ccb-3ca9-4445-82e4-1f0beb1e9c1c",
                "rotation": 0,
                "svg": "<svg height=\"32\" width=\"118\"><text fill=\"#5555ff\" fill-opacity=\"1.0\" font-family=\"MS Shell Dlg 2\" font-size=\"12.0\" font-weight=\"bold\">EIGRP 100</text></svg>",
                "x": -43,
                "y": -4,
                "z": 1
            }
        ],
        "links": [
            {
                "filters": {},
                "link_id": "6c0e145e-f7a4-49c5-8efe-5b3583966904",
                "nodes": [
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/0",
                            "x": 4,
                            "y": -44
                        },
                        "node_id": "a725e24d-2f93-4e11-82bd-7b65af236b97",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/0",
                            "x": -58,
                            "y": 38
                        },
                        "node_id": "cea1c526-0226-40be-92b6-29cdf894d02d",
                        "port_number": 0
                    }
                ],
                "suspend": false
            },
            {
                "filters": {},
                "link_id": "8c92b8cb-fe27-4cf6-80b2-163082139e6f",
                "nodes": [
                    {
                        "adapter_number": 1,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/1",
                            "x": 68,
                            "y": 43
                        },
                        "node_id": "cea1c526-0226-40be-92b6-29cdf894d02d",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/1",
                            "x": 16,
                            "y": -32
                        },
                        "node_id": "0acbfecd-3922-42e8-9292-359f99e991ce",
                        "port_number": 0
                    }
                ],
                "suspend": false
            },
            {
                "filters": {},
                "link_id": "53d6bca7-fa40-4c87-927c-2296527a3e69",
                "nodes": [
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/0",
                            "x": -60,
                            "y": 24
                        },
                        "node_id": "0acbfecd-3922-42e8-9292-359f99e991ce",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "Gi0/1",
                            "x": 72,
                            "y": 22
                        },
                        "node_id": "a725e24d-2f93-4e11-82bd-7b65af236b97",
                        "port_number": 0
                    }
                ],
                "suspend": false
            }
        ],
        "nodes": [
            {
                "compute_id": "vm",
                "console": 5006,
                "console_type": "telnet",
                "first_port_name": "",
                "height": 45,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "R1",
                    "x": 16,
                    "y": 16
                },
                "name": "R1",
                "node_id": "a725e24d-2f93-4e11-82bd-7b65af236b97",
                "node_type": "qemu",
                "port_name_format": "Gi0/{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 4,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "hda_disk_image": "vios-adventerprisek9-m.vmdk.SPA.156-1.T",
                    "hda_disk_image_md5sum": "83707e3cc93646da58ee6563a68002b5",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "IOSv_startup_config.img",
                    "hdb_disk_image_md5sum": "bc605651c4688276f81fd59dcf5cc786",
                    "hdb_disk_interface": "virtio",
                    "hdc_disk_image": "",
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "legacy_networking": false,
                    "linked_clone": true,
                    "mac_address": "00:38:a0:79:53:00",
                    "on_close": "power_off",
                    "options": "-nographic",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512,
                    "usage": "There is no default password and enable password. There is no default configuration present."
                },
                "symbol": ":/symbols/router.svg",
                "width": 66,
                "x": -253,
                "y": 106,
                "z": 1
            },
            {
                "compute_id": "vm",
                "console": 5008,
                "console_type": "telnet",
                "first_port_name": "",
                "height": 45,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "R2",
                    "x": 21,
                    "y": 16
                },
                "name": "R2",
                "node_id": "cea1c526-0226-40be-92b6-29cdf894d02d",
                "node_type": "qemu",
                "port_name_format": "Gi0/{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 4,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "hda_disk_image": "vios-adventerprisek9-m.vmdk.SPA.156-1.T",
                    "hda_disk_image_md5sum": "83707e3cc93646da58ee6563a68002b5",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "IOSv_startup_config.img",
                    "hdb_disk_image_md5sum": "bc605651c4688276f81fd59dcf5cc786",
                    "hdb_disk_interface": "virtio",
                    "hdc_disk_image": "",
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "legacy_networking": false,
                    "linked_clone": true,
                    "mac_address": "00:38:a0:68:8c:00",
                    "on_close": "power_off",
                    "options": "-nographic",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512,
                    "usage": "There is no default password and enable password. There is no default configuration present."
                },
                "symbol": ":/symbols/router.svg",
                "width": 66,
                "x": -13,
                "y": -207,
                "z": 1
            },
            {
                "compute_id": "vm",
                "console": 5010,
                "console_type": "telnet",
                "first_port_name": "",
                "height": 45,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "R3",
                    "x": 19,
                    "y": 16
                },
                "name": "R3",
                "node_id": "0acbfecd-3922-42e8-9292-359f99e991ce",
                "node_type": "qemu",
                "port_name_format": "Gi0/{0}",
                "port_segment_size": 0,
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 4,
                    "bios_image": "",
                    "bios_image_md5sum": null,
                    "boot_priority": "c",
                    "cdrom_image": "",
                    "cdrom_image_md5sum": null,
                    "cpu_throttling": 0,
                    "cpus": 1,
                    "hda_disk_image": "vios-adventerprisek9-m.vmdk.SPA.156-1.T",
                    "hda_disk_image_md5sum": "83707e3cc93646da58ee6563a68002b5",
                    "hda_disk_interface": "virtio",
                    "hdb_disk_image": "IOSv_startup_config.img",
                    "hdb_disk_image_md5sum": "bc605651c4688276f81fd59dcf5cc786",
                    "hdb_disk_interface": "virtio",
                    "hdc_disk_image": "",
                    "hdc_disk_image_md5sum": null,
                    "hdc_disk_interface": "ide",
                    "hdd_disk_image": "",
                    "hdd_disk_image_md5sum": null,
                    "hdd_disk_interface": "ide",
                    "initrd": "",
                    "initrd_md5sum": null,
                    "kernel_command_line": "",
                    "kernel_image": "",
                    "kernel_image_md5sum": null,
                    "legacy_networking": false,
                    "linked_clone": true,
                    "mac_address": "00:38:a0:2f:fb:00",
                    "on_close": "power_off",
                    "options": "-nographic",
                    "platform": "x86_64",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512,
                    "usage": "There is no default password and enable password. There is no default configuration present."
                },
                "symbol": ":/symbols/router.svg",
                "width": 66,
                "x": 235,
                "y": 104,
                "z": 1
            }
        ]
    },
    "type": "topology",
    "variables": null,
    "version": "2.1.11",
    "zoom": 100
}

**Comment by grossmj** [comment]
Have you tried to use version 2.2.x and then reverted back to version 2.1.18?

**Comment by Akbar78** [comment]
Yeah, I did.

**Comment by grossmj** [comment]
2.2 is now in beta, so yes you could use it. Anyway, something wrong happened and I am going to try to fix this issue.

Also, you should still be able to open your project in 2.1.18 by opening the file ending with backup8 or something similar.

**Comment by Akbar78** [comment]
I installed 2.2.0b1 and now I can open my projects.
Thanks for the quick reply.
