### ISSUE TITLE
[2.2.0b1] Import Appliance upload when image already exists on remote server

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#2799]
I have several QEMU appliance images loaded on my gns3 remote server. however when i try to re-install the appliance on the gns3-gui it will make me re-upload the image to the server again.

![image](https://user-images.githubusercontent.com/7719536/58335311-50664680-7e0f-11e9-943d-c02d007414fd.png)

For example, my screenshot above, i'm re-uploading vSRX 18.1R1.9.qcow2 to my gns3 server, the red box shows that my vSRX 15.1X49-D130.6.qcow is missing, but in my screenshot below you can see it exists in the gns3 server.

![image](https://user-images.githubusercontent.com/7719536/58335400-886d8980-7e0f-11e9-9174-680ca3d6bba0.png)

After the image gets uploaded, the rest of my available versions will show up in the list of available appliances to install.

![image](https://user-images.githubusercontent.com/7719536/58335434-97543c00-7e0f-11e9-8e06-543654d46487.png)

Is there any plan to have this changed where when you create a new template and use an appliance from the remote server that it will scan the /opt/gns3/images/QEMU/ directory for the images first and have the user decide if they wish to re-upload an image manually.

**Comment by grossmj** [comment]
Fixed, thanks for catching this :+1:
