### ISSUE TITLE
Wrong aligment of symbols in saved/exported projects

### ISSUE THREAD

**Issue by gschorcht** [GNS3/gns3-gui#2800]
**Describe the bug**

I have a project in which `Snap to grid` is enabled and all nodes are aligned to the grid, see the screenshot below.

![Screenshot_20190524_164129](https://user-images.githubusercontent.com/31932013/58335981-1c0c7d80-7e43-11e9-9be0-883e92824adc.png)

When I save the project into a new project with `Save as`, the alignments are lost. That is, all nodes are misaligned and I have to touch all nodes, see the screenshot below. The same problem occur when the project is exported and imported again.

![Screenshot_20190524_164215](https://user-images.githubusercontent.com/31932013/58336303-c2f11980-7e43-11e9-8562-c4d5837fcac2.png)

**GNS3 version and operating system (please complete the following information):**

 - OS: Ubuntu 18.04 LTS
 - GNS3 version: 2.1.16

**Comment by grossmj** [comment]
Fixed, thanks for catching that.
