### ISSUE TITLE
GNS3 2.2.0b1 closing General Peferences dialog displays misleading dialog

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2801]
**Describe the bug**
More a nuisance than a bug.  Edit -> Preferences to open General Preferences. Make no changes.   Click on Cancel button.  A modal dialog appears stating you have made changes without saving them, do you wish to close anyway.  Choose Yes and the modal dialog closes.  I believe this occurs with most all the recent versions of GNS3 2.1.x and 2.2.x

**GNS3 version and operating system (please complete the following information):**
GNS3 management console.
Running GNS3 version 2.2.0b1 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2019 GNS3 Technologies.
VMware® Workstation 14 Pro
14.1.7 build-12989993**To Reproduce**

1. Edit Preferences to open General Preferences
2. Make no changes.
3. Click on Cancel button to close General Preference dialog
4. See "error".  As I said not a show stopper at all just confusing.

**Screenshots or videos**
This is the model dialog that appears when you click on Cancel button.
![Unsaved preferences](https://user-images.githubusercontent.com/10285348/58372853-1883ff80-7ef2-11e9-9b95-b3db4908a5ac.png)

**Comment by grossmj** [comment]
Should be fixed now. Thanks :+1:
