### ISSUE TITLE
2.2 : the variable %console-port%

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2804]
Hi

I believe that GNS3-gui doesn't show the variable %console-port% in the tips of "Additional setting" of Qemu.

I have a problem with the value of this variable when the console type of the VM is "none". The value of the console port is "none" : it is not a number, then qemu-system-x86_64 doesn't like it and stop.
I have tried with 0 but qemu-system-x86_64 doesn't like it too because it wants that the cid is > 2.

Can you create a variable %guest-cid% which is equal to %console-port%. But if the %console-port% is "none", %guest-cid% is equal to 3 (+ an increasing number if you have that, to identify each VM)

(PS : i have do a pull request on vpcs)

**Comment by Raizo62** [comment]
Sorry, I'm annoying you. I prefer that %guest-cid% is equal to %console-port% because i can easily identify each guest with this number  (the popup of gns3 shows this value).
I have not tested yet, but i suppose that with your unique integer it is not the same.

(We try to write in C++ a virtual wifi which uses vsock to communicate. And i hope that i will can write a script which uses your API to know the coordinate of each VM)

**Comment by grossmj** [comment]
Ok should be good now, %guest-cid% is equal to %console-port% by default.

https://github.com/GNS3/gns3-server/commit/61c87e57a4e38324cca209d6cc9728e9479e0d52

**Comment by Raizo62** [comment]
Thank you :-)
