### ISSUE TITLE
GNS3 2.2.0b2 warning message in console after starting

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2805]
**Describe the bug**
When the GNS3 2.2.0b2 application starts it displays a warning message in the console frame 3 times.  Does not appear to affect basic functionality but just started using this GNS3 version.

**GNS3 version and operating system (please complete the following information):**
Windows 10 Prof VMware® Workstation 14 Pro 14.1.7 build-12989993
GNS3 2.2.0b2 application and GNS3 Workstation VM from that version of GNS3

Messages repeat in GNS3 console frame:
GNS3 management console.
Running GNS3 version 2.2.0b2 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2019 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Timeout after 2 seconds for request http://admin@127.0.0.1:3080/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 2 seconds for request http://admin@127.0.0.1:3080/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 2 seconds for request http://admin@127.0.0.1:3080/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.

**To Reproduce**
Install GNS3 application and provided GNS3 VM as usual.
Start the GNS3 application.

**Screenshots or videos**
**Additional context**
This did not occur with GNS3 2.2.0b1

Thanks!

**Comment by jtorri** [comment]
I failed to mention I am running GNS3 application with Windows administrator privileges.

**Comment by EB-athila** [comment]
I've seen this same issue in version 2.1.20 as well.

**Comment by grossmj** [comment]
> I've seen this same issue in version 2.1.20 as well.

This is the same code on both branches, does not look like to be a blocking issue

**Comment by EB-athila** [comment]
> 
> 
> > I've seen this same issue in version 2.1.20 as well.
> 
> This is the same code on both branches, does not look like to be a blocking issue

Agreed.

**Comment by KhalilSecurity** [comment]
I've seen the issue on both versions as well. Not a deal breaker to me.

**Comment by jtorri** [comment]
Does not occur in nightly build of GNS3 2.2.x from 6/5/2019 when using both the 6/5/2019 version of GNS3 (version 2.2.0dev13) and the upgraded GNS3 VM (GNS3 server version 2.2.0dev13)

GNS3 management console.
Running GNS3 version 2.2.0dev13 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2019 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=>

**Comment by grossmj** [comment]
Thanks, looks like increasing the timeout was enough to fix this problem.

**Comment by viniciobarzallo** [comment]
help, where increase the time?
