### ISSUE TITLE
Browse for alternative image

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-gui#2808]
From the forum: https://gns3.com/community/discussion/-suggestioni-qol-when-opening-gn

> Now when opening a .gns3 file, in case of a missing IOS image, GNS3 simply displays an alert window "XXX image not found", and stops importing the file.
> It is especially problematic if you have an almost the same image, but a different version (or simply the image is renamed).
>  
> IMO the better solution could be an option to select one of your images to replace the IOS used by the creator of the lab.
> Simply add the something like "Browse for alternative image..." for this error alert.

**Comment by jtorri** [comment]
Excellent idea!!

**Comment by cioby23** [comment]
This issue was already reported a while ago here https://github.com/GNS3/gns3-gui/issues/2575 so I think it refers to the same problem.

**Comment by adosztal** [comment]
Yes, same problem but different solution.

**Comment by grossmj** [comment]
Another user feedback about this: https://gns3.com/community/discussion/problem-with-importining-portabl

**Comment by grossmj** [comment]
This will be fixed in https://github.com/GNS3/gns3-gui/issues/2575
