### ISSUE TITLE
Refresh mounted media after ISO switch.

### ISSUE THREAD

**Issue by fadlytabrani** [GNS3/gns3-gui#2809]
Is there a way to refresh or re-mount the iso on a QEMU VM after you have switched ISOs. I understand that the QEMU monitor has that functionality. Can it be implemented in GNS3?

https://en.wikibooks.org/wiki/QEMU/Monitor#change

Currently the only way (I have found) to do it is powering down/up the VM.

**Comment by grossmj** [comment]
I think we can implement this.

**Comment by grossmj** [comment]
This should work starting with version 2.2 beta 3.
