### ISSUE TITLE
Hyper-V: GNS-VM crashes when IOU and Mikrotik run together

### ISSUE THREAD

**Issue by tsafx** [GNS3/gns3-gui#2815]
Hello

GNS3 GUI: 2.2.0b3 OS Windows 10 x64 (10.0.17763)
GNS3 VM for Hyper-V: 2.2.0b3 remote server (Windows 2019 Hyper-V)

Devices
IOU_L2:		i86bi-linux-l2-ipbasek9-15.1g
Mikrotik:	        CHR  6.44.3

When IOU and Mikrotik run together GNS3-VM for Hyper-VM is crushes.
If work only Mikrotiks or IOUs, that no problem.

https://www.youtube.com/watch?v=jl-5M9LD1j4

**Comment by grossmj** [comment]
Looks like this is similar to https://github.com/GNS3/gns3-server/issues/1600

**Comment by tsafx** [comment]
It seems, but not that. VM has default NIC, I only set VLAN.

I can run multiple devices of the same type. 
IOU doesn't crushe VM immediately. I will try to do something with IOU.


https://www.youtube.com/watch?v=JCsEPnjT_tI

**Comment by tsafx** [comment]
Added Dell OS10. DELL and Mikrotik work together.
If DELL is started and starts an IOU, the GNS3-VM immediately crashes.

**Comment by tsafx** [comment]
Maybe the IOU and Qemu emulators conflict with each other?

**Comment by grossmj** [comment]
>  Maybe the IOU and Qemu emulators conflict with each other?

This is what I suspect. Only it seems to happen only on Hyper-V which adds more mystery to that problem...

**Comment by ncsurfus** [comment]
I think I also hit this on Azure. Running IOU with a QEMU VM (specifically IOSv) appeared to crash the entire Azure VM. It didn't appear to matter which device was started first.

**Comment by ncsurfus** [comment]
My GNS3 runs within Docker from Ubuntu 18.04 (the host is also 18.04). Everything appears to work fine on bare-metal (Packet Cloud).

**Comment by grossmj** [comment]
I tested on my side and I confirm that running IOU and any Qemu VM at the same time crashes Hyper-V

**Comment by grossmj** [comment]
@tsafx @ncsurfus  Please, can you try to set one of the following CPU param in additional settings to see if that changes anything? Let's try ```-cpu qemu64```, ```-cpu kvm64``` and ```-cpu host```

![Screenshot from 2019-08-23 18-11-57](https://user-images.githubusercontent.com/4752614/63588798-94fdab80-c5d1-11e9-8bfa-0d697ccf81c5.png)

Thanks!

**Comment by ncsurfus** [comment]
@grossmj I'll try to find some time to test this weekend (or this upcoming week if necessary).

**Comment by tsafx** [comment]
@grossmj I don't see the Advanced tab in the IOU properties.
![изображение](https://user-images.githubusercontent.com/22910581/64943424-5d9eb980-d874-11e9-9fe8-072b35e3b4b3.png)

**Comment by grossmj** [comment]
The advanced tab is only for Qemu VMs. Make the change on your Mikrotik node.

Thanks

**Comment by tsafx** [comment]
It i tried, all three variants. Changed the option in Mikrotik, then run Mikrotik. After added OUI to the the project, GNS3 server crashes immediately.
But Mikrotik has additionan option -nographic.
 I think is not a critical.
![изображение](https://user-images.githubusercontent.com/22910581/64943977-cdfa0a80-d875-11e9-8e30-86053eaa32a6.png)

**Comment by grossmj** [comment]
Thanks for testing this. Unfortunately the problem may be more serious than I thought. I have no idea why this happens :(

**Comment by grossmj** [comment]
Another report: https://gns3.com/community/discussion/gns3-vm-hyper-v-remote-server-is

**Comment by oleg-glushko** [comment]
I've had the same issue with EVE-NG running on Hyper-V. Only one type of VMs should be working at the same time - KVM or Dynamips. It seems like a Hyper-V nested virtualization problem, not a GNS or EVE-NG specific.

**Comment by grossmj** [comment]
@oleg-glushko thanks for the info! :+1:
