### ISSUE TITLE
Fedora IOU support

### ISSUE THREAD

**Issue by BedoM** [GNS3/gns3-gui#2817]
Hello i have fedora and the link for install IOU support is broken.
"
Sorry, the page you were looking for could not be found
"
Link : https://gns3.com/discussions/use-iou-images-in-64-bit-linux

Do you have the procedure ?

THank's

Linux legiony520 5.1.12-300.fc30.x86_64 #1 SMP Wed Jun 19 15:19:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by grossmj** [comment]
Sorry I don't have this one however you could follow this procedure: https://computingforgeeks.com/how-to-install-gns3-on-fedora-29-fedora-28/
