### ISSUE TITLE
drag the ellipse and lower the layer should pop the warning window with check for "no show next time"

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#282]
or else every time need click "OK"
thank you

**Comment by grossmj** [comment]
I am not sure I understand the problem. If I drag an ellipse and lower the layer, the following message is displayed: Object moved to a background layer. You will now have to use the right-click action to select this object in the future and raise it to layer 0 to be able to move it.

What's wrong with it?

**Comment by superwolfboy** [comment]
The function is no problem , I just think it doesn't  need every time.
So my thought is add one checkbox on this diaglog window, if checked it ,means the user know how to use it and no need displayed it every time :)

**Comment by grossmj** [comment]
@superwolfboy I've fixed this in https://github.com/GNS3/gns3-gui/commit/863e1a2e20a6be5f8488f038b81ef481ec8392e5

Thanks :)

**Comment by superwolfboy** [comment]
Love you , thanks
