### ISSUE TITLE
Template cloning

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2822]
Ubuntu 19.10
gns3 gui & server 2.1.21

Right now, when we need to define a new template, we have to start from scratch, even though one (such as the image version) or only a few details (amount of RAM & number of CPUs for instance) differ from another already defined similar template.
![New template](https://user-images.githubusercontent.com/13176858/60111815-ef63c280-976e-11e9-8015-fc2eb81696bc.png)

I propose tro add:
- a clone button in the ```Edit --> Preferences --> Qemu VMs``` window between ```New``` and ```Edit``` function:
![New buttons](https://user-images.githubusercontent.com/13176858/60114117-6d29cd00-9773-11e9-99f5-321466835ee7.png)
- a ```Clone template``` between ```Configure template``` and ```Delete template``` in the ```Browse all devices``` function

**Comment by cioby23** [comment]
This is already implemented in the latest version 2.2.0 b3. There is Copy button as you depicted in the above screenshot in the Templates Preferences page.
![clone_template](https://user-images.githubusercontent.com/7124193/60115266-34432580-977e-11e9-8792-a703c12f95f3.png)

**Comment by jean-christophe-manciot** [comment]
OK, then
