### ISSUE TITLE
2.2 : infinite error message when rename locked and running router

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2824]
Hi

- I put on the topology a Cisco router called R1

- I start it.

- I lock all the devices.
 
- I want to rename the Cisco to R12. Then i have an error message :  "Dynamips error when running command 'vm rename "R1" "R12" : unable to rename VM instance R1"

- Ok. But now, as soon as i click on the device, GNS3 shows me again this error message. (You must perhaps click again on the unlock/lock button)

**Comment by grossmj** [comment]
Does it only happen when the router is locked?

**Comment by Raizo62** [comment]
Yes. If i don't use the lock button, the error message is shown only one time.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/b0f74c2a5e9b1c4c958190efdffba96f539179d7
