### ISSUE TITLE
Connectivity issues after waking computer from sleep

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2826]
See https://gns3.com/community/discussion/gns3-connectivity-issues-after-w and https://gns3.com/community/discussion/telnet-sessions-to-remote-server

**Comment by wardota** [comment]
I have similar issues for GNS3 2.1.21 on ubuntu 16.04

**Comment by arash88** [comment]
I have this exact problem with GNS3 2.1.21 on win10

**Comment by ak223wd** [comment]
I have the same issue with mine. Whenever, my pc goes into sleep mode, and then I wakes the PC back. The nodes does not want to start or stop (they are not responsive). To fix this, I have to quit GNS3 and re-open it again. I am using MacOS Catalina GNS3 2.2.5
