### ISSUE TITLE
Can't run ASA 8.4.2 on GNS3 2.2.0b3 anymore

### ISSUE THREAD

**Issue by lucatortiglione** [GNS3/gns3-gui#2827]
QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name ASA8.4.2-3 -m 2048M -smp cpus=1 -boot order=c -drive file=/opt/gns3/projects/31d26bc9-d591-4993-af6a-8cf5034f9538/project-files/qemu/b452ef6e-9f64-4ed0-9e0d-364d8d6e6c56/hda_disk.qcow2,if=ide,index=0,media=disk -initrd /opt/gns3/images/QEMU/asa842-initrd.gz -kernel /opt/gns3/images/QEMU/asa842-vmlinuz -append 'ide_generic.probe_mask=0x01 ide_core.chs=0.0:980,16,32 auto nousb console=ttyS0,9600 bigphysarea=65536 ide1=noprobe no-hlt -net nic' -uuid b452ef6e-9f64-4ed0-9e0d-364d8d6e6c56 -serial telnet:127.0.0.1:5005,server,nowait -monitor tcp:127.0.0.1:39111,server,nowait -net none -device e1000,mac=0c:95:38:6c:56:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10017,localaddr=127.0.0.1:10016 -device e1000,mac=0c:95:38:6c:56:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10019,localaddr=127.0.0.1:10018 -device e1000,mac=0c:95:38:6c:56:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10021,localaddr=127.0.0.1:10020 -device e1000,mac=0c:95:38:6c:56:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10023,localaddr=127.0.0.1:10022 -no-kvm -icount auto -device ide-hd,cyls=980,heads=16,secs=32 -nographic

Execution log:
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: -device ide-hd,cyls=980,heads=16,secs=32: No drive specified

**Comment by grossmj** [comment]
Removing ```-hdachs 980,16,32``` from the additional settings is enough to make ASA run in the GNS3 VM without apparent consequences.

**Comment by grossmj** [comment]
I have removed the parameter. I do not have time to run tests to check if the image runs properly with it.

Please note that we wanted to completely remove the legacy ASA support in version 2.2 but had to revert because some users still use it for multiple context mode which is not supported by ASAv. See https://techstat.net/setup-multiple-context-asa-gns3/

Ref https://github.com/GNS3/gns3-server/issues/1579
