### ISSUE TITLE
Add an option to tag links and to hide or show them as needed

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2833]
I work with complex topologies and I manage the devices by using their management interfaces, all  of them connected to a switch that is connected to a cloud that facilitates the connection to the network where my orchestrator is. The image on the screen looks messy with all the connections and I would like to be able to hide the management links when needed and show them again when needed like with the interface labels

Can you please add that feature ? There is no way around this currently

**Comment by b-ehlers** [comment]
See also: https://github.com/GNS3/gns3-gui/issues/2647

**Comment by b-ehlers** [comment]
See also issues https://github.com/GNS3/gns3-gui/issues/2647 and https://github.com/GNS3/gns3-gui/issues/2604

**Comment by phiea** [comment]
hi, if it's really "urgent" you can hide layers via css
for now my dirty fix is: add custom css file in the static folder and import it from index.html
underneath css code hides layer -1 (temp unhide via browser development mode and just temporarily remove the css snippet)
```
.layer[data-index="-1"]{
  display: none
}
```
if i can find the time i well hack in something more elegant with a menu and some buttons and send in a pull request.
i have not looked into the fat-client

**Comment by cristian-ciobanu** [comment]
This can be done in the GNS3 gui by changing the link style to invisible which will hide the unwanted links.
![image](https://user-images.githubusercontent.com/7124193/188644877-5b30eb50-7be6-45d5-ac64-46ccbc9add4a.png)

![image](https://user-images.githubusercontent.com/7124193/188644356-0c59e10b-53ba-4a6f-a8f7-07dd54de34b0.png)
As you can see in the image above I have 9 links connected to the switch only 3 visible the other 6 are hidden.

**Comment by grossmj** [comment]
Tags will be added in a separate issue: https://github.com/GNS3/gns3-server/issues/2175
