### ISSUE TITLE
"Please wait" dialog box prevents the user from navigating the GUI

### ISSUE THREAD

**Issue by rothman857** [GNS3/gns3-gui#2834]
**Describe the bug**
The user cannot navigate the GUI while GNS3 is connecting to a server that is not running or does not exist.  This is because the "Please wait" dialog locks out the entire GUI for the duration of the connection attempt.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows
 - GNS3 version 2.1.21
 - GNS3 VM via Workstation

**To Reproduce**
1. Open GNS3 and configure a remoter server with the wrong IP address
2. GNS3 will try connecting to the remote server, but the user cannot fix any config errors while the "Please wait" dialog is being displayed.  Pressing ESC during the dialog will cause the dialog to disappear, but it will reappear instantly until the connection process times out.
3. Until this timeout occurs, the user is essentially locked out of the GUI, and unable to make any config changes.  This "Please wait" dialog needs to be less invasive, and allow the user to click in other areas of the GUI.

![image](https://user-images.githubusercontent.com/11377430/61727132-c9ffaf80-ad40-11e9-9f07-db3690b9b1b6.png)

**Comment by grossmj** [comment]
Fixed in version 3.0 (to be released).

**Comment by sachinites** [comment]
its still very annoying, i am on 2.2.49
