### ISSUE TITLE
Merging labs together...

### ISSUE THREAD

**Issue by ralikhani110** [GNS3/gns3-gui#2835]
Hi;

Suppose I have created several distinct labs regarding to test EIGRP protocol. Now I want to merge them all in a mega lab that when I want to play with them, I do not start them separately. So, when I want to play with a lab, I just start the related devices...

Hope got the ideas...

Thanks

**Comment by grossmj** [comment]
@ralikhani110 not sure I fully understand. Do you mean you want to merge different projects into a common one?

**Comment by saviodsouza** [comment]
Can you please compare the Mac addresses of atleast similar devices between 2 labs/projects

What I have come accross in my vyos labs
2  different projects with 2 vyos routers, each with 3 or 4 interfaces.

The Mac addresses are the same on both projects.
So if I merge them there can be problems.

**Comment by grossmj** [comment]
> The Mac addresses are the same on both projects.

This should have been fixed a few versions ago
