### ISSUE TITLE
Can't change the server IP (VM IP) 

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2836]
Anymated gif here:
https://imgur.com/iXcDYVj
practically the apply button stays grey after changing the IP (last octet)
I am on the latest version 2.2.0b

**Comment by cioby23** [comment]
I think this issue was solved recently here https://github.com/GNS3/gns3-gui/issues/2823
The next beta or release candidate should have this fix.

**Comment by grossmj** [comment]
Indeed, same bug and this is fixed now.
