### ISSUE TITLE
[2.2.0b4]There should be a "Create a new version" button on add 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#2837]
Client:GNS3 2.2.0b4 on windows 7
Server: GNS3vm 2.2.0b4

1,Click "New template" botton under templates list,
2,Select a item I want to add (for example vEOS as the screenshot below), and click next.
3.There is a list of different version for this item.

The privious GNS3 just like 2.1.21, there is a "create a new version" button that we can add a new version that out of list, in case of some virtual device release new version image.
But 2.2.0b4 cancle this maybe.
I know there is "manually create a now template" function, but it is not as convenient as "Create a new version", cause that don't need set many parameters.
For example I want add vEOS 4.22,  which is not included in the list . So I want create a 4.22 version and inherit the parameters from other vEOS. No need to set them manually,
![image](https://user-images.githubusercontent.com/9411604/62533808-24892780-b87a-11e9-8651-14ed49ab4faf.png)

**Comment by grossmj** [comment]
Related? https://gns3.com/community/discussion/issue-adding-images-to-cisco-app

**Comment by superwolfboy** [comment]
> Related? https://gns3.com/community/discussion/issue-adding-images-to-cisco-app

The problem is not the same I think.
2.2.0B4 haven't "Create a new version" button and I think it shoud be back.

**Comment by grossmj** [comment]
Related to https://gns3.com/community/discussion/checksum-mismatches

**Comment by grossmj** [comment]
This will be back in version 2.2.6
