### ISSUE TITLE
(GNS3 Doesn't start) OSError: [Errno34] Result too large: 'jsonschema\\schemas\\draft6.json'

### ISSUE THREAD

**Issue by Aeisen0** [GNS3/gns3-gui#2842]
I'm getting this error since I updated from 2.2.0b4 to 2.20rc2
![Sans titre2](https://user-images.githubusercontent.com/48893826/62835480-67237900-bc59-11e9-863f-43af227f261d.png)

**Comment by grossmj** [comment]
Version 2.2 RC3 should fix this. Thanks :)
