### ISSUE TITLE
GNS3 2.2.0rc2 does not start

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2843]
**Describe the bug**
Start gns3 application, a blank dialog windows appears and then nothing happens.  List of running apps show gns3 is not running and I assume never started.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 Professional 64 bit version 1809 OS Build 17763.615
 - GNS3 version: GNS3 2.2.0rc2 and VMWare workstation VM 2.2.0rc2
 - VMware Workstation 14 latest version

**To Reproduce**
1. Install GNS3 2.2.0rc2
2. Specify run as administrator
3. Click on GNS3 icon to start the GNS3 application
4. See problem

**Screenshots or videos**
**Additional context**

**Comment by jtorri** [comment]
Interestingly, after GNS3 2.2.0rc2 is installed and an attempt to run it is made, there are no ini entries in ...\Appdata\Roaming\GNS3\

**Comment by grossmj** [comment]
Version 2.2 RC3 should fix this. Thanks :)
