### ISSUE TITLE
HPE VSR1001 won't boot on GNS3 2.2 rc3

### ISSUE THREAD

**Issue by Float-Zone** [GNS3/gns3-gui#2844]
I'm having an issue starting an HPE VSR1001 router in GNS3 2.2 rc3.
This worked on 2.1.21.

![image](https://user-images.githubusercontent.com/54148985/63117312-7117e580-bf93-11e9-800d-1f9ee30d995c.png)

I got the same results creating a a new VSR1001 template on a fresh install of 2.2 rc3 and when I imported a working project from 2.1.21.

The VSR1001 software used is VSR1000_HPE-CMW710-E0519L03-X64.qco

FZ.

**Comment by grossmj** [comment]
Can you try to add "-cpu kvm64" in the additional settings of advanced settings tab? I found this allowed to boot the appliance.

**Comment by grossmj** [comment]
@Float-Zone any results?

**Comment by Float-Zone** [comment]
Just got back off vacation. Will test it later today.

Ta,

FZ.

**Comment by grossmj** [comment]
Okay, thanks :+1:

**Comment by Float-Zone** [comment]
Added the text as requested and the router still fails to boot (as before).

The Advanced tab looks like this:
![image](https://user-images.githubusercontent.com/54148985/63893926-4aba6700-c9e3-11e9-9cb4-738e2c51a2bb.png)

I'm still on 2.2 rc3.

FZ.

**Comment by grossmj** [comment]
Can you try with only `-cpu qemu64`? Also, do you run this in the GNS3 VM?

**Comment by Float-Zone** [comment]
1. I am running this in the GNS3 VM 2.2 rc3 on VMware Workstation 15.1.0.

2. HPE VSR router still crashes at same point.

Advanced options configured like this:
![image](https://user-images.githubusercontent.com/54148985/63962850-a04a4e80-ca8b-11e9-8462-043aa26463b9.png)

Router aborts like this:
![image](https://user-images.githubusercontent.com/54148985/63962775-6d07bf80-ca8b-11e9-85c9-3c2eea58a134.png)

Regards,

FZ.

**Comment by Float-Zone** [comment]
Apologies for delay - I misread the latest request.

I have changed the "Additional Settings" to be **only** "-cpu qemu64", and the VM now boots successfully.

Regards,

FZ.

**Comment by grossmj** [comment]
@Float-Zone thanks, I will modify the appliance file on our side.
