### ISSUE TITLE
Trying connect to 127.0.0.1:3080 on MacOS

### ISSUE THREAD

**Issue by greg0r0** [GNS3/gns3-gui#2845]
After wizard install gns3 trying connect to 127.0.0.1:3080 (or [::1]:3080 and etc., i try all combinations of web server settings). At first settings of web server gns3 successfully connect to server, but after starting VM it can't. Also, if i reopen gns3 it still trying to connect after GNS3 VM start.

And i try connect to server after VM is up with telnet (like "telnet localhost 3080") - it ok, web server not in down or smth else. Also, web panel is working (i check it on safari and MF)

My suggestion is gns3-gui have some bug in connection. Any solve from other issues/gns forums dont help.

But at same time on windows all works fine.

 - OS: MacOS 10.14.6
 - GNS3 version 2.2.0 and older 
 - Trying to use standart GNS3 VM in VirtualBox 6

P.s. Sorry for bad english :)

**Comment by grossmj** [comment]
Can you post screenshots of the problem? This will help us identify what is going wrong.

Thanks!

**Comment by paskamato** [comment]
okay, first run wizard and go to server settings
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/36220096/63642320-3bc37400-c6c6-11e9-90ae-41f4c77e0734.png">

next
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/36220096/63642327-47169f80-c6c6-11e9-92cf-1ba92e871af5.png">

seems to be ok

but after VM settings i see only how gns3 try to connect to web server, infinitely
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/36220096/63642334-67def500-c6c6-11e9-9776-9ce716ba5f8e.png">

we waiting, waiting and can have standard error after 120 secs. But often it infinitely
 At this time i don't do anything (don't create project and etc.)

<img width="931" alt="image" src="https://user-images.githubusercontent.com/36220096/63642403-2ac73280-c6c7-11e9-816b-bd8c77f3ef89.png">

(http://admin@127.0.0.1:3080/v2/gns3vm error if i dont start virtual, if i start error about "cannot connect to /v2/...)
(and in win10 i dont get error /v2/gns3vm if i dont start virtual)

But i have also project that don't use VM (with few alpine linux and mikrotik chr in vbox) and this project on win10 is working fine. On Macos its trying to connect with server only


Can you explain to me in what purposes server was create? Maybe i will create some kind of plug, after few hours in wireshark :)

When i check code i see only logging devices


UPD: I set in wizard "Run appliances on my local computer" and error is gone. Now start RouterOs in another virtualbox machine.

Maybe i don't understand interaction between server and VM?

**Comment by grossmj** [comment]
Have you tried to change the gns3server port to let's say 3081?

**Comment by paskamato** [comment]
Yes of course
Also tried another IP and IPv6
And remove password :)

I wrote "Any solve from other issues/gns forums don't help."

**Comment by grossmj** [comment]
I would recommend to ignore the wizard and try to configure the GNS3 VM from the preferences. 

![Screenshot from 2019-08-28 16-52-07](https://user-images.githubusercontent.com/4752614/63845476-390d9b00-c9b4-11e9-9ca8-9e3dd3e22ca6.png)

Also, make sure the GNS3 VM is correctly imported in VMware Fusion and that VT-x is enabled.

![Screenshot from 2019-08-28 16-49-40](https://user-images.githubusercontent.com/4752614/63845275-f5b32c80-c9b3-11e9-8828-bf3d6d5c5adf.png)

**Comment by paskamato** [comment]
Hey, i use only VBox (i cant use vmware for some purposes) and vmware not installed

Configured in setting, still same - than try to add element it still lagged

**Comment by grossmj** [comment]
Try to pick another port, for instance 3081

**Comment by grossmj** [comment]
@paskamato have you managed to get around this problem?

**Comment by paskamato** [comment]
In a one way, Yes - just start use GNS3 on windows.
I tryed all hypothetical fixes from forums and issues - nothing work. Maybe issue not in GNS3, but in MacOS.

**Comment by grossmj** [comment]
Made a test on a clean MacOS 10.15 Catalina (make sure you delete any previous GNS3 configuration in `~/.config/GNS3`) with GNS3 2.2.5 and everything worked without problem. I suspect some kind of issue with MacOS.
