### ISSUE TITLE
When starting any QEMU VM on a linux host the following errors occurs

### ISSUE THREAD

**Issue by trip5ter** [GNS3/gns3-gui#2847]
**Describe the bug**
When trying to start a QEMU vm running on the local linux machine the following error occurs. 

**GNS3 2.1.21
 - OS: ubuntu 18.04
 - GNS3 VM running on localmachine with virtualbox

**Screenshots or videos**
screen shot attached

**Additional context**
![Screenshot from 2019-08-22 10-49-24](https://user-images.githubusercontent.com/826882/63479267-ee31e600-c4d0-11e9-8d76-7fcc8a8c11b0.png)

**Comment by grossmj** [comment]
It is not possible to use the GNS3 VM running with nested virtualization enabled and Qemu based appliances configured to run with KVM at the same time. Please choose between using the GNS3 VM or running everything on your Ubuntu host.

**Comment by grossmj** [comment]
Actually try this first, make sure you have the KVM permissions correctly configured:

Create/edit this file: `/lib/udev/rules.d/60-qemu-system-common.rules` and add this line ```KERNEL=="kvm", GROUP="kvm", MODE="0660"```

Then set the correct permissions on this file:

```
sudo chmod 644 /lib/udev/rules.d/60-qemu-system-common.rules
sudo chown root:root /lib/udev/rules.d/60-qemu-system-common.rules
```

Finally, make sure your user belongs to the kvm group:

```
sudo usermod -aG kvm <your_username>
```

Let us know if you have questions.

**Comment by trip5ter** [comment]
Thanks Grossmj - i'll go down the path of migrating away from the GNS3 VM.
I appreciate your help
Cheers

**Comment by grossmj** [comment]
@trip5ter Ok no worries. Follow my instructions to properly setup permissions for /dev/kvm on Ubuntu 18.04
