### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by BedoM** [GNS3/gns3-gui#2850]
Hello ! 

I have an issue on gns3 IOU utilisation

THe error is :

Bridge is not available, path doesn't exist, or you just installed GNS3 and need to restart your user session to refresh user permissions

more details:

> [mabed@desktop-k89gs9m ~]$ locate ubridge
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__init__.py
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/hypervisor.py
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/ubridge_error.py
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/ubridge_hypervisor.py
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/ubridge_hypervisor_test.py
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__/__init__.cpython-37.pyc
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__/hypervisor.cpython-37.pyc
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__/ubridge_error.cpython-37.pyc
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__/ubridge_hypervisor.cpython-37.pyc
> /usr/local/lib/python3.7/site-packages/gns3server/ubridge/__pycache__/ubridge_hypervisor_test.cpython-37.pyc
> 

My OS : 

> [mabed@desktop-k89gs9m ~]$ uname -a
> Linux desktop-k89gs9m.home 5.2.9-200.fc30.x86_64 #1 SMP Fri Aug 16 21:37:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>

**Comment by grossmj** [comment]
Hi,

You must install the ubridge tool in addition of GNS3: https://pkgs.org/download/ubridge

**Comment by grossmj** [comment]
Have you been successful installing ubridge?

**Comment by BedoM** [comment]
Oh sorry!
Yes I solv my problem!

thanks you verry much!
