### ISSUE TITLE
Issue Installing GNS3 2.2.0rc4 on ESXi via OVA

### ISSUE THREAD

**Issue by PeterEstephanV2** [GNS3/gns3-gui#2852]
After downloading the ESXi installation OVA (GNS3.VM.VMware.ESXI.2.2.0rc4.zip
) from the Github repository (https://github.com/GNS3/gns3-gui/releases), I proceeded to install the OVA on my ESXi 6.7.0 U3 server via vCenter and seemed to install successfully. However, upon first boot I received the following error:
https://imgur.com/a/jBP8EPg
I then ran: sudo gns3restore and after the command completed the same error occurred.

**Comment by PeterEstephanV2** [comment]
I am able to however, install rc3 and upgrade to rc4 successfully.

**Comment by grossmj** [comment]
We are going to fix this in rc5. The workaround is to type these commands and then reboot:

```
sudo apt update
sudo apt install dialog
```
