### ISSUE TITLE
Add gns3-vm for docker

### ISSUE THREAD

**Issue by mabed-fr** [GNS3/gns3-gui#2853]
Hello ! 

After release gns3 image for KVM (thank you very much)

Can you publish a remote server version running in a docker container and the published on docker hub

This could allow to host a remote server easily

Thank you

**Comment by BedoM** [comment]
If you need me for test the configuration ( publish port, volumes, etc...) contact me i work with docker daily :)

**Comment by grossmj** [comment]
We have a script to run the GNS3 server in Docker: https://github.com/GNS3/gns3-server/blob/master/scripts/docker_dev_server.sh
