### ISSUE TITLE
"Edit readme" is missing in GNS3 GUI.

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2854]
Starting from v2.2 "Edit readme" function is missing (see screenshots). It is extremely useful and heavily used option.
Could you restore this functionality (it make sense even improve it).

GNS3 v2.1:
![gns3v2 1](https://user-images.githubusercontent.com/16309438/65163094-3fa99400-d9ef-11e9-8de0-a40342a70612.png)

GNS3 v2.2rc5
<img width="213" alt="gns3v2 2" src="https://user-images.githubusercontent.com/16309438/65163101-43d5b180-d9ef-11e9-9cef-0839372f5184.png">

**Comment by vint66** [comment]
Hi Jeremy,
Are you changing something significant with this Readme feature (I see it is getting postponed again)? Is the any way to get it working at least as before?

**Comment by cioby23** [comment]
I see there is an open pull request https://github.com/GNS3/gns3-gui/pull/2875 to bring back this feature.

**Comment by vint66** [comment]
I see you returned readme with 2.2.9. Leave it this way please until you ready to implement it as new feature. ;)
We can close this bug.
