### ISSUE TITLE
Bring back node's console port option in GUI

### ISSUE THREAD

**Issue by arash88** [GNS3/gns3-gui#2855]
Hi Devs,
First i have to thanks for all of your efforts for developing GNS3 and helping us who can't afford real devices!
I know GNS3 chose free ports for nodes when opening a project. but i'm using SecureCRT along with PuTTy and i don't want to change default console app to SecureCRT.
GNS3 changes nodes port randomly at every project loading which makes it annoying to change SecureCRT sessions option every time.
There used to be this option that let you change the nodes console port that i'm missing a lot right now.
So if it's not problem for you guys, is it possible to bring back this useful feature?

Thanks in advance and Godspeed

**Comment by grossmj** [comment]
Thanks for the proposal, we agree it could be great to manually assign a console port in some situations. We have an issue already opened for this: https://github.com/GNS3/gns3-gui/issues/2811
