### ISSUE TITLE
Read folder structure correctly for custom symbols.

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2856]
GNS3 v2.2.0rc5

I would be nice if GNS3 server can read custom symbols from nested folder and show them grouped just like it was done for affinity symbols.

As for now workaround is to put folder with symbols to /usr/local/lib/python3.6/dist-packages/gns3server/symbols/

**Comment by grossmj** [comment]
This should be supported already. Please comment if this isn't the case. Thanks.

**Comment by vint66** [comment]
I see 2.2.11 still has same issue.

Mode detailed explanation:

This is folder where gns3 will be looking for symbols: **/opt/gns3/symbols/** (it is form gns3 config).
In this folder I have another folder - **3DN** where all my 3d symbols located. I might have another folder "sibling" of 3DN with more symbols.

The issue:
GNS3 will merge all symbols in all nested folders and show then as "Custom symbols" one category.

However it would be nicer to have folder read correctly and show it as you see with 3db folder on screenshot (this is same 3DN placed in /usr/local/lib/python3.6/dist-packages/gns3server/symbols/.

<img width="249" alt="Screen Shot 2020-07-15 at 9 53 35 AM" src="https://user-images.githubusercontent.com/16309438/87573191-6e30e380-c681-11ea-96e1-6b0ceeadbfd7.png">

Hopefully it make sense. Let me know if need more info.

**Comment by grossmj** [comment]
> Hopefully it make sense. Let me know if need more info.

Ok, got it this time. This will work in version 2.3
