### ISSUE TITLE
Reach "project readme"

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2857]
GNS3 v2.2.0rc5

"Project readme" needs to be improved to support RTF or HTML + builtin editor.

**Comment by grossmj** [comment]
Markdown would be better I think: https://github.com/GNS3/gns3-gui/issues/2550

**Comment by vint66** [comment]
Yes, markdown should be good.
Thank you for looking into this, Jeremy.

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-gui/issues/2550
