### ISSUE TITLE
Add "Resume all connections".

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2858]
GNS3 v2.2.0rc5

Could you add "Resume all connections" function to resume all suspended links via Topology Summary.

Suspended link could be resumed only one by one at the moment by clicking on each suspended link:
<img width="229" alt="Screen Shot 2019-09-21 at 6 28 27 PM" src="https://user-images.githubusercontent.com/16309438/65381076-dd29ef80-dc9d-11e9-9930-13e90b6b6d50.png">

I would be nice to have shortcut to resume all links at once just like for capture or filters:
<img width="267" alt="Screen Shot 2019-09-21 at 6 28 14 PM" src="https://user-images.githubusercontent.com/16309438/65381078-e0bd7680-dc9d-11e9-862d-a7906d085e21.png">

**Comment by grossmj** [comment]
Implemented.
