### ISSUE TITLE
Dynamips error Windows 10

### ISSUE THREAD

**Issue by BedoM** [GNS3/gns3-gui#2860]
Hello my friend running GNS3 without vm on Windows 10 latest release encounter this problem:

Problem on version :  2.1.21

Same problem on version 2.2.0

He cut the firewall, change ports

I d'ont understand this error

`Dynamips error when running command 'nio create_udp udp-2b349880-7ca2-4740-972d-6ec7df4efc47 10012 127.0.0.1 10013
': unable to create UDP NIO`

Do you have any solutions ?

The problem is occured with an import of project.

Thank'you

**Comment by grossmj** [comment]
Do you have any dynamips_i1_stdout.txt or similar inside the project directory?

**Comment by BedoM** [comment]
Hello the installation was broken. I have re-install the GNS3 GUI 2.2.0 and GNS3 VM 2.2.0 and work fine , good job!
