### ISSUE TITLE
Questions about proper way of using HAXM with v2.2.x

### ISSUE THREAD

**Issue by arash88** [GNS3/gns3-gui#2863]
Hi dear Devs,
I'm really having a hard time getting any performance improvements from latest stable GNS3 for example using IOSv/L2.
So, I have a couple of questions regarding the proper way of using Qemu with HAXM in GNS3 v2.2.0.

1- According to qemu.org blog, i should recall HAXM assistance with an additional argument at the time of utilizing the VM:  -accel hax (or -enable-hax)
Now, Does GNS3 2.2 already doing this for me or should i add the arg in "Additional settings -> Options" manually? if not, which one should i use -accel hax or -enable-hax?

2- I see HAXM v7.3.2 is shipped with GNS3 v2.2 installer, but according to HAXM Github (My presumption maybe), the latest version is what's recommended, which is v7.5.2 at this moment.
Now, Should i stick with what GNS3 offers or should i skip GNS3 recommendation and install HAXM 7.5.2 afterwards?

Thanks a lot guys.

**Comment by grossmj** [comment]
Hi,

Just a warning first, HAXM is experimental with GNS3. An appliance running well on Linux with KVM may not work on Windows/macOS with HAXM.

> 1- According to qemu.org blog, i should recall HAXM assistance with an additional argument at the time of utilizing the VM: -accel hax (or -enable-hax)
Now, Does GNS3 2.2 already doing this for me or should i add the arg in "Additional settings -> Options" manually? if not, which one should i use -accel hax or -enable-hax?

GNS3 automatically added the correct param. You can confirm that with a right click on the node -> show node information -> command line tab (the node needs to be started at least once).

> 2- I see HAXM v7.3.2 is shipped with GNS3 v2.2 installer, but according to HAXM Github (My presumption maybe), the latest version is what's recommended, which is v7.5.2 at this moment.
Now, Should i stick with what GNS3 offers or should i skip GNS3 recommendation and install HAXM 7.5.2 afterwards?

We were not aware of this newer version. We will ship version 7.5.2 with the next release. Thanks :)

**Comment by arash88** [comment]
HAXM v7.5.4 was released with bug fixes:
https://github.com/intel/haxm/releases

**Comment by grossmj** [comment]
I confirm HAXM v7.5.4 will be included with our next release.

**Comment by arash88** [comment]
HAXM v7.5.6 was released:
https://github.com/intel/haxm/releases

**Comment by grossmj** [comment]
Next release will include HAXM v7.5.6

Thanks!

**Comment by arash88** [comment]
HAXM v7.6.1 was released:
https://github.com/intel/haxm/releases

**Comment by grossmj** [comment]
Should be already included in version 2.2.8

**Comment by arash88** [comment]
HAXM v7.6.6 was released:
https://github.com/intel/haxm/releases

I see GNS3 is still utilizing HAXM v7.6.1

**Comment by grossmj** [comment]
Good point, we should upgrade this.

**Comment by grossmj** [comment]
I have upgrade to version 7.6.6

I am curious to know how and why you use HAXM on Windows? Please note that the next major version of GNS3 (3.0) will focus on running the back-end on Linux and won't official support Windows/macOS. You will have to use a remote server or the GNS3 VM.
