### ISSUE TITLE
A lot of traffic when using cloud node

### ISSUE THREAD

**Issue by kangver** [GNS3/gns3-gui#2864]
When I added cloud node and bridge gns3vm interface connected directly to host physical interface, a lot of traffic source from host sent to gns3vm

Environment
- gns3 2.2 and gns3 vm as remote server
- Windows 10 x64

![image](https://user-images.githubusercontent.com/56177476/66244041-dfc22580-e730-11e9-90dd-87bd967f2fc6.png)

**Comment by grossmj** [comment]
What is your goal, have PC1 access to Internet or your host?
