### ISSUE TITLE
[2.2.0] [Appliance] Uploading non-matching MD5 cause GNS3 not to accept it

### ISSUE THREAD

**Issue by dot-mike** [GNS3/gns3-gui#2867]
**Describe the bug**
In import appliance dialog, you are asked to provide matching files.
If you **don't** have "Allow custom files" checked, yet you try to upload the file, GNS3 asks you if you want to continue using a non-matching file. This feature does not work. I believe the file will get uploaded, but the client sees is as an invalid file.
You actually have to check "Allow custom files" to make it work. Why ask the user if the upload should be done for non-matching MD5 hash when is has no effect?

**GNS3 version and operating system:**
 - OS: Windows 10
 - GNS3 version 2.2.0
 - GNS3 VM

**To Reproduce**
1. Fire up GNS3 and let it start VM
2. Click on 'import appliance'
3. Import PFsense Appliance
4. Import the qcow2 image
5. Try to import the PFSense image (Current release: 2.4.4-p3. Appliance wants: 2.4.4) without checking "Allow custom files". It will ask you continue or not. Click yes to accept the risks
6. Let it go through and upload. Client will after upload see that image is not imported

**Comment by grossmj** [comment]
This will have to wait for version 2.2.2. The current workaround is to check "Allow custom files". I will also update the appliance file to add 2.4.4-p3.

**Comment by grossmj** [comment]
PR opened https://github.com/GNS3/gns3-registry/pull/470

**Comment by grossmj** [comment]
I have added back "create a new version" for the appliance wizard. This should help with this issue.
