### ISSUE TITLE
Permission denied when trying to open recent project

### ISSUE THREAD

**Issue by m4shie** [GNS3/gns3-gui#2871]
**Describe the bug**
I have a setup where the GNS3 server always is running in the background on my Xubuntu 18.04 Workstation. This is so I can use the same labs regardless if I run the GUI locally or from a remote laptop.

After upgrading from 2.1.21 to 2.2.0 a new issue have appeared.
When I start a project under Open Project everything is working fine.
If I try and start any project listed in the Recent Projects section at the bottom of the file menu I get a permission denied and a massive string looking like one or more UUID as the path that was denied.
If so then try to open the same project but from the Open Project option it works fine again.

This has never happened before the 2.2.0 build. It is the same behaviour regardless if I run the GUI locally or from a remote system.

**GNS3 version and operating system (please complete the following information):**
 - OS: Xubuntu 18.04 Workstation
 - GNS3 version 2.2.0
 - Always on baremetql server that either use a local GUI session or a remote server connection.

Let me know if you need a few screenshots and I can provide them on Sunday.

**Comment by grossmj** [comment]
Thanks for the report. Please post some screenshots if you can. Thanks :+1:

**Comment by m4shie** [comment]
Hi Jeremy,

Here are some screenshots seen from the remote GUI session.

This is the error when I try to start the project from the recent selection:
![GNS3_error](https://user-images.githubusercontent.com/40231381/66737535-2e27a080-ee64-11e9-92c3-9ea0d7390ea6.png)

This is how the menu itself looks like, any item with a path next to it fail to open with the error above.
![GNS3_menu1](https://user-images.githubusercontent.com/40231381/66737587-4b5c6f00-ee64-11e9-89fd-920fe6ec355a.png)

Here is another entry that appeared.
![GNS3_menu2](https://user-images.githubusercontent.com/40231381/66737681-88c0fc80-ee64-11e9-8599-c7438a6d007a.png)

This is how all of it is listed under the Open Project -> Project Library dialog:
![GNS3_library](https://user-images.githubusercontent.com/40231381/66737719-9b3b3600-ee64-11e9-9d13-94cbe056471f.png)

It is always the same projects failing and as you can see not all of them are affected, although I have no idea what is different between them. Also all projects open up fine if using the Project Library, it is just the "Recent Project" section causing problem.

**Comment by m4shie** [comment]
A bit further testing, so with the remote GUI some projects can be opened using "Recent Projects", when I use a local GUI on the baremetal server not a single project can be opened using the "Recent Projects". It all still work just fine using the Project Library route.

Here are a few screenshots from the Local GUI:

![Local_menu](https://user-images.githubusercontent.com/40231381/66739481-b314b900-ee68-11e9-84df-7b65e1313e81.png)

![Local_error1](https://user-images.githubusercontent.com/40231381/66739493-b9a33080-ee68-11e9-99ba-86c26d89e1c0.png)

![Local_error2](https://user-images.githubusercontent.com/40231381/66739511-c4f65c00-ee68-11e9-8eea-cc0ae8713c50.png)

![Local_library](https://user-images.githubusercontent.com/40231381/66739524-cd4e9700-ee68-11e9-8997-da18055e25c6.png)

**Comment by candlerb** [comment]
I don't know for sure if this is related, but I get the same error when I restore a project from a snapshot:

```
Error transferring http://nsrc@x.x.x.x:3080/v2/projects/load - server replied: Forbidden (x.x.x.x:3080)
```

However, when I then select the project again from recent projects, it's fine.

I am using a remote server (Ubuntu 18.04, gns3-server 2.2.0) and connecting from macOS front-end.

I do have authentication configured in `~/.config/GNS3/2.2/gns3_server.conf`.  I did at first wonder if the front-end was omitting to send the HTTP basic auth credentials when calling `/v2/projects/load` - but I have checked with tcpdump and can confirm it *is* doing this correctly.

gns3server is running under systemd.  Output captured by systemd also shows the 403, but notice the error on the line before: "Can't load the project the server is not started with --local"

```
Oct 22 13:58:08 brian-kit gns3server[29568]: 2019-10-22 13:58:08 INFO web_log.py:233 10.12.255.241 [22/Oct/2019:12:58:01 +0000] "POST /v2/projects/538fd8
9a-e9f8-4f1c-bb2c-4988d7e9b29d/snapshots/186b78db-25b1-4424-ba5f-2a9d1dc665f6/restore HTTP/1.1" 201 787 "-" "GNS3 QT Client v2.2.0"
Oct 22 13:58:08 brian-kit gns3server[29568]: 2019-10-22 13:58:08 ERROR project_handler.py:208 Can't load the project the server is not started with --local
Oct 22 13:58:08 brian-kit gns3server[29568]: 2019-10-22 13:58:08 INFO web_log.py:233 10.12.255.241 [22/Oct/2019:12:58:08 +0000] "POST /v2/projects/load HTTP/1.1" 403 200 "-" "GNS3 QT Client v2.2.0"
Oct 22 13:58:08 brian-kit gns3server[29568]: 2019-10-22 13:58:08 INFO project_handler.py:279 Client has disconnected from notification stream for project ID '538fd89a-e9f8-4f1c-bb2c-4988d7e9b29d' (WebSocket method)
```

This message appears to come from `/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/handlers/api/controller/project_handler.py`

```
    @Route.post(
        r"/projects/load",
        description="Open a project (only local server)",
        parameters={
            "path": ".gns3 path",
        },
        status_codes={
            201: "The project has been opened",
            403: "The server is not the local server"
        },
        input=PROJECT_LOAD_SCHEMA,
        output=PROJECT_OBJECT_SCHEMA)
    async def load(request, response):

        controller = Controller.instance()
        config = Config.instance()
        if config.get_section_config("Server").getboolean("local", False) is False:
            log.error("Can't load the project the server is not started with --local")
            response.set_status(403)
            return
        project = await controller.load_project(request.json.get("path"),)
        response.set_status(201)
        response.json(project)
```

I'm afraid I don't know what the `--local` option is for.  `gns3server --help` says only:

```
  -L, --local           local mode (allows some insecure operations)
```

And the option is not mentioned in the [sample gns3_server.conf](https://github.com/GNS3/gns3-server/blob/master/conf/gns3_server.conf) at all.

Should I be starting gns3server with this flag?  And what is the risk of doing so?

**Comment by candlerb** [comment]
@m4shie: can you run gns3server process in the foreground, and see if it outputs the same error "Can't load the project the server is not started with --local" when you get the permission denied response?

**Comment by m4shie** [comment]
@candlerb I just tested with the server running in the foreground and I got the same error as you.

I did however just test to start the server with the "--local" flag and everything worked without a problem, both from a local and from a remote GUI. I'm not too worried about the insecurity part as the only way to reach the server is either from the LAN or from a VPN. It woudl however be very interesting to know what the "--local" flag is doing. 

@grossmj Any ideas why we now need to use the "--local" flag to get the remote servers to work in 2.2.0?

**Comment by grossmj** [comment]
> @grossmj Any ideas why we now need to use the "--local" flag to get the remote servers to work in 2.2.0?

The "--local" param shouldn't be needed for remote servers. I will investigate this soon.

Our goal is the remove this param in a future major version of GNS3 anyway.

**Comment by grossmj** [comment]
I should have partly fixed the issue. I suspect there will still be a few bugs when switching between a local server and a remote one.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-gui/issues/2421
