### ISSUE TITLE
Start/stop only selected items

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-gui#2876]
**Is your feature request related to a problem? Please describe.**
I keep doing the following:

* Carefully select a subset of devices that I want to start or stop
* Press the big green Start or big red Stop button at the top of the screen
* GNS3 starts or stops *every* device instead of the ones I selected

I know that what I should do instead is right-click and select Start or Stop from the pop-up menu.  I always forget to do this :-(

**Describe the solution you'd like**
If one or more devices is selected, then the big buttons at the top would apply only to the selected devices.  Including Start, Stop, Suspend, Reload, Consoles etc.

**Describe alternatives you've considered**
Hypnosis to train myself to use right-click instead.

Removing the row of buttons entirely.

**Comment by grossmj** [comment]
> * Carefully select a subset of devices that I want to start or stop
> * Press the big green Start or big red Stop button at the top of the screen
> * GNS3 starts or stops every device instead of the ones I selected

Unfortunately this is the intended goal of the big green Start and big red Stop button at the top of the screen, their caption/tooltip are  "start all devices", "stop all devices" etc.

> Hypnosis to train myself to use right-click instead.

I think this is what you will have to do ;)
