### ISSUE TITLE
Instaling GNS3 2.2.0 in (Fedora 31)

### ISSUE THREAD

**Issue by hhlp** [GNS3/gns3-gui#2878]
**Before you start**

Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

I did, nobody answer it:

* [Question](https://gns3.com/community/discussion/problem-instaling-gns3-2-2-0-in-)

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**

**Problem Installing GNS3 2.2.0 in Fedora (31)**

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

Linux Fedora 31, GNOME Desktop, x86_64

pip3 list | grep gns3        
gns3-gui                   2.2.0       
gns3-server              2.2.0

**To Reproduce**
1. pip3 install --user gns3-gui==2.2.0 gns3-server==2.2.0

> I execute the command like you explain in your page but and I've had to add the parameters --user for a pip error

2. Install sucesfull
3. I can't execute because I can't find the ICON in GNOME-SHELL

**Screenshots or videos**

* See here -> [Screen Shot](https://gns3.com/community/discussion/problem-instaling-gns3-2-2-0-in-)

**Additional context**

``` 
which gns3-gui
/usr/bin/which: **no gns3-gui** in (/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/hhlp/bin:/home/hhlp/bin)
``` 

```
which gns3-server
/usr/bin/which: **no gns3-server** in (/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/hhlp/bin:/home/hhlp/bin)
``` 

``` 
pip3 show grep gns3-gui gns3-server  
```

```                                          
Name: gns3-gui
Version: 2.2.0
Summary: GNS3 graphical interface for the GNS3 server.
Home-page: http://github.com/GNS3/gns3-gui
Author: Jeremy Grossmann
Author-email: package-maintainer@gns3.net
License: GNU General Public License v3 (GPLv3)
Location: /home/hhlp/.local/lib/python3.7/site-packages
Requires: jsonschema, raven, psutil, distro
Required-by:  
```

```
Name: gns3-server
Version: 2.2.0
Summary: GNS3 server
Home-page: http://github.com/GNS3/gns3-server
Author: None
Author-email: None
License: GNU General Public License v3 (GPLv3)
Location: /home/hhlp/.local/lib/python3.7/site-packages
Requires: jsonschema, aiohttp, aiohttp-cors, aiofiles, async-generator, Jinja2, raven, psutil, async-timeout, distro
Required-by:  
``` 

Regards.,

**Comment by grossmj** [comment]
The executable are named gns3 and gns3server. Please check that they are installed.

**Comment by hhlp** [comment]
Launch sucessfull from /home/hhlp/.local/bin/gns3...

``` 
/home/hhlp/.local/bin/gns3
/home/hhlp/.local/lib/python3.7/site-packages/gns3
```

```
/usr/bin/which: no gns3 in (/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/hhlp/bin:/home/hhlp/bin)
``` 

There is not in my path, I also need to provide the same path to gns3-server... also I can't find an ICON to launch in GNOME-SHELL and this is very strange

Regards.,

**Comment by hhlp** [comment]
I also have to create a **gns3.desktop** to launch from GNOME-SHELL point out to this route
