### ISSUE TITLE
Mac OS X: For serial console connection use netcat instead of socat

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#288]
For serial console connections on Mac OS X there is a predefined setting 'Terminal + socat'. The problem is, that socat is neither installed by OS X nor by GNS3. The user must search for it on the internet and install it himself.

The predecessor of socat, netcat or nc, is pre-installed by OS X and can replace socat in this case. So I suggest to replace socat by nc. The command line would be like this:
```
/usr/bin/osascript -e 'tell application "terminal" to do script with command "stty raw; nc -U \"%s\"; exit"'
```

Maybe an alternative would be to get rid of those serial console connections altogether. As far as I know this serial console stuff is only used for VirtualBox VMs. We can always enable the VirtualBox option "Enable remote console". That way for the user the console connection is always a telnet connection.

**Comment by ehlers** [comment]
Just to make it clear: I suggest to use netcat only on Mac OS X. On Linux both programs can easily be installed and socat is more powerful. So stick with socat on Linux.

**Comment by noplay** [comment]
VirtualBox 5.0 include a patch for improving that. But I Will take a look
on this, it sound an easy improvement.

On Thu, Apr 23, 2015 at 10:01 PM, ehlers <notifications@github.com> wrote:

> Just to make it clear: I suggest to use netcat only on Mac OS X. On Linux
> both programs can easily be installed and socat is more powerful. So stick
> with socat on Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/288#issuecomment-95702746>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>

**Comment by noplay** [comment]
Oh Jeremy is already on that. I will touch this :palm_tree:

**Comment by noplay** [comment]
Not touch this. The beginning of day is hard.

**Comment by ehlers** [comment]
Maybe my idea to get rid of the serial connection is not that good. There's just a discussion in the forum, where a vSRX hangs, when a remote console is configured but not activated, see https://community.gns3.com/thread/8098. I can't reproduce it on Mac OS X (and I refuse to use GNS3 on Windows :-).

Anyway using nc instead of socat should be possible.

**Comment by grossmj** [comment]
I've added the command but I couldn't test it: https://github.com/GNS3/gns3-gui/commit/1ba6e361bda824924dd63bf4463e0ab103136bba

Please check. Re-open if this doesn't work.

Thanks,

**Comment by ehlers** [comment]
Small typo: In your commit, you reference issue 228, but it's issue 288.

In linux it's easy for me to test a development version, as I use the source. But in OS X I use the .dmg files. Is there an easy way to test a development version in this environment ?

**Comment by cioby23** [comment]
@ehlers you can use the brew or macports installation method fro gns3-server and gns3-gui. Check the main page on Github https://github.com/GNS3/gns3-gui#mac-os-x and https://github.com/GNS3/gns3-server#mac-os-x

**Comment by ehlers** [comment]
Well, but that's really a lot of work. I hoped for a way to update the .dmg. OK, then I will wait for the next official release.

**Comment by grossmj** [comment]
@ehlers actually you don't have to wait for a release, we have nightly builds now: http://sourceforge.net/projects/gns-3/files/Nightly%20Builds/ :)

@noplay should we only keep the latest nightly build or maybe just the last 3? Also, at what time are the build generated?

**Comment by noplay** [comment]
I don't know the excat time. I think i use the @nightly settings of jenkins.
Le 25 avr. 2015 17:59, "Jeremy Grossmann" <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Does Jenkins look out the window to see if it is nighttime? ;)

**Comment by ehlers** [comment]
Oh, I didn't know about the nightly, very cool.

I just got the nightly from 2015-04-25 and tested the change. It doesn't work, neither with netcat nor with socat. But it works with remote console.

I believe that the problem is your server change 161adb7 "Use UUIDs instead of the VM names for VirtualBox pipe paths.". There you changed the path of the serial pipe. But you didn't change it in the GUI  in serial_console.py. There the old pipe name is still active. So socat and nc try to open the old pipe name, what's doesn't work.

**Comment by grossmj** [comment]
@ehlers thanks for catching that! :+1: I've fixed the issue in the GUI now.

> Oh, I didn't know about the nightly, very cool.

This is quite new and it should help us in our debugging process. Now let's wait for the next nightly build...

Cheers,

**Comment by ehlers** [comment]
Just tested with nightly 2015-04-26: Everything runs well, both serial console commands (nc and socat) are working fine.

**Comment by grossmj** [comment]
@ehlers thanks for testing :+1:

**Comment by noplay** [comment]
We call that the cloud :P Let's decide during the tonight call an hour

On Sat, Apr 25, 2015 at 8:00 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> Does Jenkins look out the window to see if it is nighttime? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/288#issuecomment-96246536>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
