### ISSUE TITLE
Error when opening project with NAT device

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2882]
Adding a NAT device to a project works well, but opening this project later on results in an error:

```
Bad request http://127.0.0.1:3080/v2/compute/projects/08407e3a-e4a7-4c0b-a686-4ccfd32ee21d/nat/nodes {
    "message": "JSON schema error with API request '/v2/compute/projects/08407e3a-e4a7-4c0b-a686-4ccfd32ee21d/nat/nodes' and JSON data '{'ports_mapping': [{'interface': 'vmnet8', 'name': 'nat0', 'port_number': 0, 'type': 'ethernet'}], 'name': 'NAT1', 'console_type': 'none', 'node_id': 'a9fbe020-272b-4304-858e-4629c4ad1b0c'}': Additional properties are not allowed ('console_type' was unexpected)",
    "method": "POST",
    "path": "/v2/compute/projects/{project_id}/nat/nodes",
    "request": {
        "console_type": "none",
        "name": "NAT1",
        "node_id": "a9fbe020-272b-4304-858e-4629c4ad1b0c",
        "ports_mapping": [
            {
                "interface": "vmnet8",
                "name": "nat0",
                "port_number": 0,
                "type": "ethernet"
            }
        ]
    },
    "status": 400
}
```

**GNS3 version and operating system (please complete the following information):**
GNS3 version 2.2.1dev1 on Darwin (64-bit) with Python 3.7.4 Qt 5.13.0 and PyQt 5.13.1.

**To Reproduce**
1. Create a project and place a NAT device in it
2. Restart GNS3 to close the project
3. Open the project

The project file:
[untitled.gns3](https://github.com/GNS3/gns3-gui/files/3774614/untitled.gns3.txt)

It happens both with local NAT device as well as a NAT device in the GNS3VM.

**Additional context**
When I use an editor and remove the line `"console_type": null,` I can open the project. But as soon GNS3 opens it, the console_type line is added again.

**Comment by grossmj** [comment]
Fixed
