### ISSUE TITLE
GUI uses only telnet console

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2885]
**Describe the bug**

Since v2.2.1, commit https://github.com/GNS3/gns3-gui/commit/b2fe7eb643059d6717b009edb503c9c6a25caff6, the GUI no longer opens a VNC or spice console.

**GNS3 version and operating system (please complete the following information):**

GNS3 version 2.2.1 on Darwin (64-bit) with Python 3.7.4 Qt 5.13.0 and PyQt 5.13.1.

**To Reproduce**
1. Open a node with a non-telnet console type
2. See error

**Additional context**
In `gns3/node.py`the `consoleCommand` function is normally called with console_type=None. Only aux connections set the console_type parameter to telnet. So the changes in https://github.com/GNS3/gns3-gui/commit/b2fe7eb643059d6717b009edb503c9c6a25caff6 result in only using the telnet console command.

I suggest something like:
```
diff --git a/gns3/node.py b/gns3/node.py
index 9a2c0695..995334d4 100644
--- a/gns3/node.py
+++ b/gns3/node.py
@@ -628,12 +628,12 @@ class Node(BaseNode):
         from .main_window import MainWindow
         general_settings = MainWindow.instance().settings()

-        if console_type and console_type != "telnet":
+        if not console_type:
             console_type = self.consoleType()
-            if console_type == "vnc":
-                return general_settings["vnc_console_command"]
-            if console_type.startswith("spice"):
-                return general_settings["spice_console_command"]
+        if console_type == "vnc":
+            return general_settings["vnc_console_command"]
+        elif console_type.startswith("spice"):
+            return general_settings["spice_console_command"]
         return general_settings["telnet_console_command"]

     def consoleType(self):
```

But that doesn't handle self.consoleType() == None, no idea if that can happen and what result should be returned then.

**Comment by grossmj** [comment]
Thanks, looks like we going to release version 2.2.2 very soon. We were planning to do one it within a week anyway.
