### ISSUE TITLE
Updating the execution path of SecureCRT application

### ISSUE THREAD

**Issue by ralikhani110** [GNS3/gns3-gui#2896]
In the following figure, you can see the default application path of SecureCRT that is incorrect in recent versions:

![image](https://user-images.githubusercontent.com/50766200/68794211-d6977300-0663-11ea-9e2f-368fcf29eb3b.png)

The correct path is:

![image](https://user-images.githubusercontent.com/50766200/68794248-ed3dca00-0663-11ea-9214-c6be0d7eef2e.png)

Thanks

**Comment by grossmj** [comment]
Done, thanks :+1:

**Comment by kmanwar89** [comment]
I would like to ask this be re-opened, as the correct path is actually *"C:\Program Files\VanDyke Software\SecureCRT\SecureCRT.EXE" /T /N "%d" /telnet %h %p*.  This is with SecureCRT v8.7.0.  Can this be updated?

**Comment by grossmj** [comment]
That would mean reverting the changes proposed by @ralikhani110, so what is the correct default path for SecureCRT?

**Comment by grossmj** [comment]
Just installed SecureCRT v8.7.0 and the default path is %PROGRAMFILES%\VanDyke Software\SecureCRT\SecureCRT.exe

**Comment by kmanwar89** [comment]
> That would mean reverting the changes proposed by @ralikhani110, so what is the correct default path for SecureCRT?

Apologies, I didn't see this notification before. I posted the correct path in my original message, but I see you already incorporated this in #2896/commit 0c3d433, so thank you!
