### ISSUE TITLE
Support the ability to Provision ESXi VMs in GNS3

### ISSUE THREAD

**Issue by PeterEstephan** [GNS3/gns3-gui#2897]
Similar to how the VMware Workstation feature operates where you are able to add/create VMs to your GNS3 topology, could this same feature be applied to an ESXi environment? Where you are able in GNS3 to add for example a Windows 10 VM, that will be provisioned in ESXi and connected to your GNS3 project?

**Comment by grossmj** [comment]
Sorry, we will not implement this.
