### ISSUE TITLE
Add SVG Icon in GNS3 Linux

### ISSUE THREAD

**Issue by ycharbi** [GNS3/gns3-gui#2898]
**En Français**
Bonjour,

Serait-il possible d'ajouter l'icône de GNS3 en SVG dans le répertoire `/usr/share/icons/hicolor/scalable/apps/` ?

Je ne sais pas si cette icône existe quelque part mais cela permettrai un affichage propre sur des écrans en HIDPI.

Merci.

**In English**
Hello,

Would it be possible to add the GNS3 icon in SVG in the `/usr/share/icons/hicolor/scalable/apps/` directory?

I don't know if this icon exists somewhere but it will allow a clean display on HIDPI screens.

Thank you.

**Comment by grossmj** [comment]
Scalable icons will be added when installing our next release. Thanks :+1:

**Comment by ycharbi** [comment]
Thanks to you !  :thumbsup: :clap:
