### ISSUE TITLE
Edit setting of VirtualBox VM Templates works only once time per session

### ISSUE THREAD

**Issue by ninefix** [GNS3/gns3-gui#2899]
**Describe the bug**
After one modify of VirtualBox vm template setting, it doesn't work anymore until restart GNS3

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux Sidcution (based on debian unstable)
 - GNS3 version 2.2.3 (server and client)
 - VirtualBox 6.0.14 r133895 (Qt5.12.5) as VM provider

**To Reproduce**
1. Open GNS3 from terminal
2. Go to 'edit --> preferences --> VirtualBox Vms'
3. Click on 'New' and import a VM from VirtualBox list
4. Select a VM, click 'Edit', change one setting and save
5. Repeat the step above on the same VM or on another one and no setting window opens anymore
6. On the terminal there is an exception that I pasted below

**Additional context**

AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/daniele/.local/lib/python3.7/site-packages/gns3/modules/virtualbox/pages/virtualbox_vm_preferences_page.py", line 160, in _vboxVMEditSlot
    dialog = ConfigurationDialog(vbox_vm["vmname"], vbox_vm, VirtualBoxVMConfigurationPage(), parent=self)
  File "/home/daniele/.local/lib/python3.7/site-packages/gns3/dialogs/configuration_dialog.py", line 41, in __init__
    self.setupUi(self)
  File "/home/daniele/.local/lib/python3.7/site-packages/gns3/ui/configuration_dialog_ui.py", line 64, in setupUi
    QtCore.QMetaObject.connectSlotsByName(configurationDialog)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

**Comment by grossmj** [comment]
There is a bug with PyQt: https://github.com/GNS3/gns3-gui/issues/2819#issuecomment-533876471

Please upgrade to version PyQt >= 5.13.1
