### ISSUE TITLE
Restore from snapshot generating error messages

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2901]
Version 2.2.3, GUI: MacOS, Server: Linux

When restoring a snapshot, the project is closed and I receive the following message "Error transferring http://user@10.127.1.1:3080/v2/projects/load - server replied: Forbidden (10.127.1.1:3080)"

After re-opening the project I verified the snapshot DOES work successfully, but the errors displayed may make others think the operation failed.

**Comment by grossmj** [comment]
I think this is related to https://github.com/GNS3/gns3-gui/issues/2871

**Comment by grossmj** [comment]
Fixed.
