### ISSUE TITLE
"Console to all nodes" doesn't open cloud objects with console configured

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2902]
GNS3 v2.2.3 doesn't open console to cloud objects with console configured upon "Console to all nodes" pressed.

**Comment by b-ehlers** [comment]
I assume, that's the result of issue https://github.com/GNS3/gns3-gui/issues/2309, which blocks the consoles to all internal nodes, when using the "Console to all nodes" function. As the internal ethernet switch has no longer a console, the GNS3 devs might decide to revert the commit https://github.com/GNS3/gns3-gui/commit/f24c93a55f1d8481b33ccb27b5b65b0463674bb5.

**Comment by grossmj** [comment]
> As the internal ethernet switch has no longer a console, the GNS3 devs might decide to revert the commit f24c93a.

We plan to add back the console support for the Ethernet switch (disabled due to dependency nightmare).

> GNS3 v2.2.3 doesn't open console to cloud objects with console configured upon "Console to all nodes" pressed.

I think we should allow it since users have to explicitly configure clouds, so that's probably what they would expect.

**Comment by grossmj** [comment]
Should be fixed now. Thanks :+1:
