### ISSUE TITLE
GNS3 Preferences button doesn't show version 2.2.3

### ISSUE THREAD

**Issue by filippogasbarro** [GNS3/gns3-gui#2903]
If I click to Edit --> Preferences, the preferences Windows doesn't appear. Moreover isn't impossible to click in any other button in GNS3 because it seems the the windows is opened but invisible. For retake the control of GNS3 I must use ALT+ F4 for the "invisible windows".

**GNS3 version and operating system (please complete the following information):**
 - OS: [Windows]
 - GNS3 version [e.g. 2.2.3]
 - Any use of the GNS3 VM or remote server (VMware workstation 12 on Windows 2012)

**Comment by grossmj** [comment]
Do you have more than one monitor?

**Comment by filippogasbarro** [comment]
Yes,
I have two monitor. Is it a problem?

Il mer 25 dic 2019, 23:48 Jeremy Grossmann <notifications@github.com> ha
scritto:

**Comment by grossmj** [comment]
Yes, many users have had the problem. 

https://www.gns3.com/community/discussion/edit-preferences-won-t-open

We need to check what we could do the fix that issue. Is this the only dialog that causes the problem?

**Comment by filippogasbarro** [comment]
The problem you wrote about I had before with the old version. By upgrading
to 2.2.3, all the windows are not visible. If I open gns3, I see the icon
in the omnibar, but if I click nothing appens. The only way to close is to
kill in the task manager.

Il gio 26 dic 2019, 17:53 Jeremy Grossmann <notifications@github.com> ha
scritto:

**Comment by filippogasbarro** [comment]
Update:
If I open GNS3 with only one monitor I see the window where ask me the project to use; I click on it to open the project but after I don't see anymore the GNS3 screen (also if GNS3 is open in the omnibar).
I'll send you the logs if are useful for you
[GNS3 log.zip](https://github.com/GNS3/gns3-gui/files/4015692/GNS3.log.zip)

**Comment by filippogasbarro** [comment]
Update:
If I open GNS3 with only one monitor I see the window where ask me the project to use; but I don't see the settings Windows
I'll send you the logs if are useful for you
https://github.com/GNS3/gns3-gui/files/4015692/GNS3.log.zip

**Comment by grossmj** [comment]
Let's see if upgrading to Qt version 5.14.1 could have solved that problem. See https://github.com/GNS3/gns3-gui/issues/2778#issuecomment-577101377

**Comment by filippogasbarro** [comment]
Hi, where can I download the nightly build?

**Comment by cioby23** [comment]
> Hi, where can I download the nightly build?

You can get them from here https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/

**Comment by filippogasbarro** [comment]
> ding to Qt
Yes, it works with the nightly build :)

**Comment by grossmj** [comment]
> Yes, it works with the nightly build :)

That's a good news. Is this with nightly build for version 2.3?

**Comment by filippogasbarro** [comment]
yes, the last one.
Before I tryed with the last nightly 2.2 and the bug it remain. After I tryed 2.3 nightly and everythings work :)

**Comment by grossmj** [comment]
Perfect, I will update the Qt version for nightly 2.2 as well. Test everything is going well and probably release version 2.2.6 soon.

**Comment by grossmj** [comment]
Nightly build with the latest Qt version: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-01-24/2.2/GNS3-2.2.2020-01-24-all-in-one.exe/download

**Comment by filippogasbarro** [comment]
It works with the 2.2.2020-01-24. Thank you :)

**Comment by grossmj** [comment]
Upgrading Qt to version 5.14.1 seems to have fixed the problem. Ref https://github.com/GNS3/gns3-gui/issues/2778
