### ISSUE TITLE
Wait for the servers to be online before GNS3 allows to either create or open a project

### ISSUE THREAD

**Issue by dAb74** [GNS3/gns3-gui#2907]
Hi,

can we please have some kind of "waiting" popup at startup so that GNS3 waits to get contact to the servers before the user is allowed to do anything at all? I find very misleading that right at startup GNS3 informs the user to create a project, or allows to open one, implying that it's ready to work while clearly it's not. Expecially when working with VM servers, it isn't possible to properly open a project when the VM server is not online and reachable yet.

Thanks,
Danilo

**Comment by grossmj** [comment]
Fixed.
