### ISSUE TITLE
Temporary location issue with project duplicate or "save as"

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2909]
In some situation, users can run out of space because projects are stored on a different disk than the default temporary location (e.g. /tmp). GNS3 uses this temporary location when duplicating projects  (because we use this Python module: https://docs.python.org/3.8/library/tempfile.html), therefore duplicating a huge project can lead the temporary location disk to reach 100% of used space.

https://gns3.com/community/discussion/duplicate-or-save-as-issues

**Comment by dllegru** [comment]
+1 
Was running out of space in my root partition when duplicating a project. Didn't know where it was coming from until I found out about this. 
Managed to bypass it by setting a bind mountpoint for /tmp to another partition.

Would be great to parametrize the GNS3 temp directory in the GNS3 server configuration file.

**Comment by grossmj** [comment]
Solved and back-ported to 2.2 branch.
