### ISSUE TITLE
Add remote-viewer to the preconfigured VNC commands

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2913]
When using SPICE, the user has installed `remote-viewer`. This program can be also used for VNC, installing an additional VNC program is not necessary.

It would be nice, if remote-viewer is added to PRECONFIGURED_VNC_CONSOLE_COMMANDS. The command is the same as for SPICE, just replace the protocol `spice:` by `vnc:`.

For Linux this would be `'Remote Viewer': 'remote-viewer vnc://%h:%p'`

**Comment by grossmj** [comment]
Added, thanks :+1:
