### ISSUE TITLE
Adding new qemu adapter type

### ISSUE THREAD

**Issue by antfobe** [GNS3/gns3-gui#2914]
Hi all, I'm trying to add a custom qemu adapter, `open_eth` to a gns3 appliance. I looked where the `adapter_type` definitions where in the source files and added the new adapter to the list:
`gns3server/schemas/qemu_template.py:69`
`"virtio-net-pci", "vmxnet3", "open_eth"],`

But I am still getting the error 'adapter is not one of'...
Any ideas?
![image](https://user-images.githubusercontent.com/13102173/71029637-93ab3e00-20ee-11ea-9114-1192f90fcbb4.png)

My custom gns3a file:
[esp32-mqtt-client.txt](https://github.com/GNS3/gns3-gui/files/3975238/esp32-mqtt-client.txt)

**Comment by grossmj** [comment]
Have you changed qemu source code to add this "open_eth" adapter type?

**Comment by antfobe** [comment]
> Have you changed qemu source code to add this "open_eth" adapter type?
Yes, I am able to run it from the qemu's xtensa binary - `qemu-system-xtensa`, my complete command line is: `qemu-system-xtensa -machine esp32 -nographic -serial mon:stdio -drive file=mqtt_tcp.bin,if=mtd,format=raw -nic user,model=open_eth`

I am not expecting to get the machines output, just the network connections - what i have been doing so far is bridging a host network with these qemu images as a cloud to gns3.

**Comment by grossmj** [comment]
> I looked where the adapter_type definitions where in the source files and added the new adapter to the list:
gns3server/schemas/qemu_template.py:69
"virtio-net-pci", "vmxnet3", "open_eth"],

You must also add your new adapter type on the GUI side in https://github.com/GNS3/gns3-gui/blob/2.2/gns3/schemas/appliance.json#L267

**Comment by antfobe** [comment]
It seems that was indeed the problem, however now I'm having issues with the `-no-kvm` option added by gns3, as I have a custom qemu build and there is no kvm support for xtensa arch, it trows an error:
```
QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-xtensa -name ESP32MQTTClient1-1 -m 64M -smp cpus=1 -boot order=d -drive file=/home/fobe/GNS3/projects/mqtt_sensor_net/project-files/qemu/2ceebf16-baff-447f-823d-e268f41bd44a/hda_disk.qcow2,if=ide,index=0,media=disk,id=drive0 -uuid 2ceebf16-baff-447f-823d-e268f41bd44a -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:40991,server,nowait -net none -device e1000,mac=0c:4a:d8:d4:4a:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10003,localaddr=127.0.0.1:10002 -machine esp32 -nographic -drive file=/opt/esp-idf/examples/protocols/mqtt/tcp/mqtt_tcp.bin,if=mtd,format=raw -nic user,model=open_eth -no-kvm

Execution log:
qemu-system-xtensa: -no-kvm: Option not supported for this target
```

**Comment by antfobe** [comment]
I think I can close this issue, because my current problem is not related to it
