### ISSUE TITLE
CPU maxed out on GNS3 2.2.3 with QEMU and Mikrotik CHR

### ISSUE THREAD

**Issue by arash88** [GNS3/gns3-gui#2915]
Using GNS3 2.2.3 and Mikrotik CHR on locally QEMU makes CPU goes CRAZY!
GNS3 2.2.3 makes the CPU go and stay on 100% when using even two Mikrotik CHR nodes connecting to each other (Latest official img)!
Tested with either HAXM acceleration on or off.
The settings of CHR QEMU Node are exactly as what GNS3 appliance for CHR was suggested.
GNS3 2.1.21 is totally Fine without any problem!

 - OS: Win 7 SP1 - Win10 1903
 - GNS3 version 2.2.x
 - Locally and Without GNS3 VM or remote server (ESXi, bare metal etc.)

**Comment by grossmj** [comment]
Tested on GNS3 VM version 2.2.3 and I couldn't find any issue. Needs more investigation.

**Comment by arash88** [comment]
GNS3 VM is OK but, without VM and Locally it has problem!

**Comment by grossmj** [comment]
I am not sure Mikrotik can run well locally on Windows with or without HAXM. HAXM itself it still considered experimental and it may not work with many appliances.

**Comment by arash88** [comment]
Actually it's working kinda better in GNS3 2.1.21
I don't know if it's qemu3.x faults or not! maybe qemu4 can improve user experiences!

**Comment by grossmj** [comment]
> Actually it's working kinda better in GNS3 2.1.21

So does it work locally? How have you installed Qemu and what is the version?

Thanks

**Comment by arash88** [comment]
Hi dear Jeremy,
It runs locally on Win10 1903. Using Qemu 2.4 which were installed automatically by GNS 2.1.21, it's mostly usable without maxing CPU out like GNS 2.2.x does!
Though using CHR on GNS3 vm was giving me a better experience with both GNS 2.1.21 and 2.2.5.

**Comment by grossmj** [comment]
> Though using CHR on GNS3 vm was giving me a better experience with both GNS 2.1.21 and 2.2.5.

Indeed, I recommend running everything in the GNS3 VM.
