### ISSUE TITLE
GUI stability at scale

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#2917]
I've been building a huge lab in GNS3 to be able to test performance of different network automation tools at scale.
Currently I've added ~400 IOL devices, though my target is 1000.
Already at 400 I've found that GUI is quite unstable, communication with the server times out and then the whole GUI crashes.
I've been streaming the process of building the lab, here is the [moment in the video](https://youtu.be/9qeOp5HqH2Y?t=12882) where it crashed
Any tips how we can improve stability of the GUI on such a scale? E.g. may be make communication between gui and server less frequent, may be something else?
Meanwhile, I will probably try working with this lab without gui at all.
If you are interested in improving the performance, my lab can be your guinea pig :)
Thanks!

**Comment by grossmj** [comment]
Correct, the GUI needs a serious refactoring. While our current focus is on the Web-Ui, we have some plans to redo the GUI using the asyncio model instead of the current callbacks mess which leads to crashes and extremely hard to debug.

**Comment by dmfigol** [comment]
@grossmj 
So webui is already "recommended" way to use GNS3 or not yet?
I've tried it with my topology. It does not seem to crash, but moving a single node is already a challenge (laggy), moving a group of nodes is close to impossible

**Comment by grossmj** [comment]
> So webui is already "recommended" way to use GNS3 or not yet?

Not quite yet since the web-ui is still in alpha. We are going to recommend it in the first half of 2020 as we have all the major features ready.

> I've tried it with my topology. It does not seem to crash, but moving a single node is already a challenge (laggy), moving a group of nodes is close to impossible

This is definitely something to improve. We most likely sending or receiving too many requests to/from the server.

**Comment by grossmj** [comment]
The web-ui should be mostly usable on its own (there are still a few missing features). We may refactor the desktop Ui once we have something really solid. Ref. https://github.com/GNS3/gns3-gui/issues/2848
