### ISSUE TITLE
GNS3 2.2.3 GUI not complitable with 2.2.4 server - please update ppa

### ISSUE THREAD

**Issue by HappyFX** [GNS3/gns3-gui#2918]
https://launchpad.net/~gns3/+archive/ubuntu/ppa
![image](https://user-images.githubusercontent.com/8521474/72052700-b3d9b180-32d6-11ea-9d20-8b39c92d677f.png)
Can't roll back updated server from 2.2.4, can't use GNS3-gui

**Comment by grossmj** [comment]
There was a building issue. We have released version 2.2.5.

Packages will be ready soon: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+builds?build_text=&build_state=all

**Comment by grossmj** [comment]
2.2.5 is fully released now.
