### ISSUE TITLE
GNS3 Linux desktop integration

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2919]
With commit 6dda0ff7875b4e9b1e1ea433e2f1ea277b1471c5 and 626510865f6df474cb49877a940043de085208b9 the GNS3 icons are installed into `/usr/local/share/icons`. That's a very nice improvement for the Linux desktop integration. But I like to suggest some additional steps:

- The MIME icons are installed in `/usr/local/share/icons/hicolor/*/apps/mimetypes`, at least in my installation they work better in `/usr/local/share/icons/hicolor/*/mimetypes`.
- The `gns3.desktop` file is installed in `share/applications` in the gns3-gui module library path, I would prefer installing it in `/usr/local/share/applications`.
- The MIME file `/usr/local/share/mime/packages/gns3-gui.xml` is missing.

**GNS3 version and operating:**
 - OS: Debian Linux 10 (Buster)
 - GNS3 version 2.2.4

**Comment by b-ehlers** [comment]
And I would prefer, when the mimetypes icons get the execute permission revoked. It's likely caused by copying them from a Windows system.

**Comment by grossmj** [comment]
I added the MIME file and changed the paths. However, for the files to be installed in `/usr/local/share` I think you must use something like `pip3 install --user gns3-gui` or `python3 setup.py install --user`. If this doesn't work, try with  `--prefix=/usr/local`.

**Comment by b-ehlers** [comment]
Thanks for your fast response, you have fulfilled all my wishes (well, regarding this issue 😃).

I've tried several `pip3 install` and `python3 setup.py install` installation options in my Debian Buster. The first two commands install from PyPi, the last two command from source.

| install command | share folder | python modules |
| --- | --- | --- |
| pip3 install --user gns3-gui | /home/user/.local/share | /home/user/.local/lib/python3.7/site-packages/gns3 |
| sudo pip3 install gns3-gui | /usr/local/share | /usr/local/lib/python3.7/dist-packages/gns3 |
| sudo python3 setup.py install | /usr/local/lib/python3.7/dist-packages/gns3_gui-2.2.5-py3.7.egg/share | /usr/local/lib/python3.7/dist-packages/gns3_gui-2.2.5-py3.7.egg/gns3 |
| sudo pip3 install . | /usr/local/share | /usr/local/lib/python3.7/dist-packages/gns3 |

The `--user` installs in the user's home directory, that's fine when only one user wants to use GNS3. 

I was a bit suprised, that `python3 setup.py install` and `pip3 install .` behave differently. With `python3 setup.py install` the data directories (share in our example) are located as subdirectories in the python library path, while `pip3 install .` stores them in `/usr/local`.

For my needs the best way is `sudo pip3 install gns3-gui` when installing from PyPi and `sudo pip3 install .` when installing from source.

I'm totally pleased with the current state, close this issue?

**Comment by grossmj** [comment]
Thanks for the feedback!
