### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2920]
https://sentry.io/organizations/gns3/issues/1329137795/?referrer=github_plugin

```
AttributeError: 'NoneType' object has no attribute 'startswith'
  File "./gns3-gui\gns3\graphics_view.py", line 634, in mouseDoubleClickEvent
  File "./gns3-gui\gns3\node.py", line 720, in bringToFront
  File "./gns3-gui\gns3\node.py", line 635, in consoleCommand

AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by luchiago** [comment]
Hi, can I grab this issue? And if yes, where should I start looking?

**Comment by grossmj** [comment]
Sure, you can start looking around there: https://github.com/GNS3/gns3-gui/blob/2.2/gns3/node.py#L621

Thanks :+1:

**Comment by grossmj** [comment]
@luchiago has you made any progress on this? Thanks :)

**Comment by luchiago** [comment]
@grossmj Sorry for taking so long to respond. I had some problems with time to do this issue and I don't know If I'll have. Feel free to give this issue to another person.

**Comment by grossmj** [comment]
This happened on an ATM switch which don't have console. I cannot reproduce the problem and I consider this is unlikely to happen.

**Comment by SakharamS** [comment]
I had the same issue and starting the GNS3 application as administrator resolved it.
