### ISSUE TITLE
Project is closing, please try again in a few seconds...

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#2921]
GNS3 v2.2.5
Server running on remove Ubuntu 18.04
GUI is on macOS 10.15.2

Project stuck in closing state (wee error on screenshot). I could not be opened from different GUI and showing same error.
No particular trigger identified so far.

Server logs doesn't show any communication happens at this time.

Project contains: 1x dynamips L2 switch, 20x CSR1k.

<img width="417" alt="error" src="https://user-images.githubusercontent.com/16309438/72226293-8c881c00-3544-11ea-9226-4c9021f85d94.png">

**Comment by grossmj** [comment]
How long have you waited before trying to open the same project again?

**Comment by vint66** [comment]
Wait time is vary, more then 10 min for sure.
As for now issue seems to be related to dynamips itself as same topology but with Open vSwitch as L2 working well. I suggested to avoid using dynamips built-in objects.

**Comment by vint66** [comment]
Hi Jeremy,

I think we can close this issue as I don't have any complains since last time.

I recently saw similar behavior in case lab has a lot of QEMU nodes and save VM state selected as shutdown policy (so it is very possible this issue was due to such config).

If you have any other thoughts feel free to reopen it.
