### ISSUE TITLE
Zoom in/out not working on linux

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-gui#2923]
Hi Guys,

Can you please help, zoom in/out not working on Linux, it defaults to small pic/topology and can't zoom out.
![DeepinScreenshot_select-area_20200121085038](https://user-images.githubusercontent.com/10646178/72791496-179d9c00-3c40-11ea-9020-d886e3508214.png)

**GNS3 version and operating system 
 - OS: Linux
 - GNS3 version 2.2.5

**Comment by grossmj** [comment]
Have you tried to press: `CTRL+0`?

**Comment by leribe** [comment]
Works, thanks

**Comment by grossmj** [comment]
You can also use `CTRL++` and `CTRL +-` to zoom in/out.
