### ISSUE TITLE
GNS3 don't start in fedora 31 (Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...)

### ISSUE THREAD

**Issue by hhlp** [GNS3/gns3-gui#2927]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**

GNS3 don't start in fedora 31 

Fail update installation: No module named 'sip'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...

**GNS3 version and operating system (please complete the following information):**

 - OS: [e.g. Windows, Linux or macOS]

Linux hhlp 5.4.15-200.fc31.x86_64  SMP Tue Jan 28 09:08:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Fedora 31

 - GNS3 version [e.g. 2.1.14]

pip list | grep gns3\*
gns3-gui                      2.2.5     
gns3-server                   2.2.5     

 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
1. Go to '...'  sudo pip install gns3-gui gns3-server or pip install --user install gns3-gui gns3-server
2. Click on '....' type in terminal gns3
3. See error

Fail update installation: No module named 'sip'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...

**Additional context**

rpm -qa qt5\*

```
qt5-qtwebsockets-5.13.2-1.fc31.x86_64
qt5-qtserialport-5.13.2-1.fc31.x86_64
qt5-qdbusviewer-5.13.2-3.fc31.x86_64
qt5-qttools-libs-designercomponents-5.13.2-3.fc31.x86_64
qt5-designer-5.13.2-3.fc31.x86_64
qt5-assistant-5.13.2-3.fc31.x86_64
qt5-qtmultimedia-5.13.2-1.fc31.x86_64
qt5-qtconnectivity-5.13.2-1.fc31.x86_64
qt5-qttools-common-5.13.2-3.fc31.noarch
qt5-qtscript-5.13.2-1.fc31.x86_64
qt5-qtxmlpatterns-5.13.2-1.fc31.x86_64
qt5-qtenginio-1.6.2-27.fc31.x86_64
qt5-qtsensors-5.13.2-1.fc31.x86_64
qt5-qtwebengine-5.13.2-1.fc31.x86_64
qt5-qtgraphicaleffects-5.13.2-1.fc31.x86_64
qt5-qtbase-postgresql-5.13.2-2.fc31.x86_64
qt5-qtquickcontrols-5.13.2-1.fc31.x86_64
qt5-qtbase-5.13.2-2.fc31.x86_64
qt5-qtbase-common-5.13.2-2.fc31.noarch
qt5-qtquickcontrols2-5.13.2-1.fc31.x86_64
qt5-qtwebkit-5.212.0-0.41.alpha3.fc31.x86_64
qt5-qtx11extras-5.13.2-1.fc31.x86_64
qt5-qtsvg-5.13.2-1.fc31.x86_64
qt5-qttools-libs-designer-5.13.2-3.fc31.x86_64
qt5-srpm-macros-5.13.2-1.fc31.noarch
qt5-qttools-libs-help-5.13.2-3.fc31.x86_64
qt5-qtimageformats-5.13.2-1.fc31.x86_64
qt5-qttools-5.13.2-3.fc31.x86_64
qt5-qtdeclarative-5.13.2-1.fc31.x86_64
qt5-qtbase-gui-5.13.2-2.fc31.x86_64
qt5-qtwayland-5.13.2-2.fc31.x86_64
qt5-qtbase-mysql-5.13.2-2.fc31.x86_64
qt5-qtwebchannel-5.13.2-1.fc31.x86_64
qt5-qtlocation-5.13.2-1.fc31.x86_64
qt5-5.13.2-1.fc31.noarch
qt5-qtdoc-5.13.2-1.fc31.noarch
qt5-qt3d-5.13.2-1.fc31.x86_64
```

``` 
Package python3-qt5-5.13.2-3.fc31.x86_64 is already installed.
Package python3-pyqt5-sip-4.19.19-1.fc31.x86_64 is already installed.
``` 

Regards.,

**Comment by grossmj** [comment]
Try to install PyQt via pip: `sudo python3 -m pip install pyqt5`

**Comment by hhlp** [comment]
❯ sudo python3 -m pip install pyqt5
[sudo] password for hhlp: 
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3 -m pip install --user` instead.
Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.7/site-packages (5.12.3)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /usr/lib64/python3.7/site-packages (from pyqt5) (4.19.19)
❯ gns3
Fail update installation: No module named 'sip'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...

**Comment by DevDorrejo** [comment]
> Try to install PyQt via pip: `sudo python3 -m pip install pyqt5`

Hello, this fix my problem on Opensuse TW

**Comment by DevDorrejo** [comment]
> Try to install PyQt via pip: `sudo python3 -m pip install pyqt5`

i think is not the right way to make gns3 force the user to have pyqt5 and QT, when one have the QT.

**Comment by grossmj** [comment]
I installed GNS3 on a fresh Fedora 31 and followed the documentation: https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html#h.odi1imgo08q0

Unfortunately, this installs version 2.1.10 which doesn't work well with Python 3.7

The workaround is to install the testing version, the information can be found there:

https://src.fedoraproject.org/rpms/gns3-gui
https://src.fedoraproject.org/rpms/gns3-server

To install the testing version, please use this command: `dnf install gns3-server gns3-gui --enablerepo=updates-testing --best`

**Comment by hhlp** [comment]
works well in Fedora 32 Beta with two method:

-> sudo pip install gns3-gui gns3-server  (install GNS3 GUI version 2.2.6)
-> sudo dnf install gns3-server gns3-gui (install GNS3 GUI version 2.2.5)

Regards.,

**Comment by grossmj** [comment]
@hhlp thanks for the feedback :+1:

**Comment by bobv** [comment]
> Try to install PyQt via pip: `sudo python3 -m pip install pyqt5`

This worked for me. Many thanks!
