### ISSUE TITLE
Failed to install a Cisco 2691 appliance

### ISSUE THREAD

**Issue by netsgnut** [GNS3/gns3-gui#2928]
**Describe the bug**
I tried to install a Cisco 2691 appliance. After choosing an image and clicking on "Finish" button, an error prompt of the following content appeared:
`
The template cannot be created: JSON schema error adding template with JSON data '{'compute_id': 'local', 'name': 'Cisco 2691 124-15.T14', 'category': 'router', 'symbol': ':/symbols/classic/router.svg', 'template_type': 'dynamips', 'nvram': 256, 'platform': 'c3600', 'ram': 192, 'slot0': 'GT96100-FE', 'startup_config': 'ios_base_startup-config.txt', 'image': 'c2691-adventerprisek9-mz.124-15.T14.image', 'idlepc': '0x60bcf9f8', 'template_id': 'd78e7b63-d46b-45f1-adb0-3ffc7490d9b8'}': 'chassis' is a required property
`

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux (Ubuntu 18.04, kernel 5.3.0-26)
 - GNS3 version: 2.2.5 (installed via [PPA](https://launchpad.net/~gns3/+archive/ubuntu/ppa))
 - Using a remote server within the local network, provisioned with [`remote-install.sh`](https://raw.githubusercontent.com/GNS3/gns3-server/master/scripts/remote-install.sh)

**To Reproduce**
1. At the sidebar, choose `Routers` > `New Template`.
2. Choose `Install an appliance from the GNS3 server` and click `Next`.
3. Choose `Cisco 2691` and click `Install`.
4. Choose `Install the appliance on the main server` and click `Next`.
5. Confirm the existence of the supported image and click `Next`.
6. At the prompt `Would you like to install Cisco 2691 version 124-15.T14?`, choose `Yes`.
7. Click `Finish`.

After clicking `Finish`, the above error message should appear.

**Additional context**
I did not try all of the IOS devices, but it seems this problem only applies to 2691 alone.

**Comment by grossmj** [comment]
I have fixed our template file: https://github.com/GNS3/gns3-registry/commit/219b5f283b2253fdaf53b1b3b50c11db4e98816b

Click on "Update from online repository" and you should get the new template file and then be able to install the c2691 appliance without error.

Thanks!

**Comment by netsgnut** [comment]
Thanks, @grossmj. I can confirm the above patch works for me here. However, it seems the "Update from online repository" did not update the affected appliance in my case. I edited it manually at `/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/appliances/c2691.gns3a` and the appliance can be added without error.

Thanks again!
