### ISSUE TITLE
unable to connect gns3 node to real interface

### ISSUE THREAD

**Issue by jasvijay** [GNS3/gns3-gui#2929]
This is a strange problem, i have a simple connection from a vpc to cloud on loopback interface when i try to ping from windows to the vpc i get RTO's but when i run wireshark i can see the arp requests and arp reply.
![Capture2](https://user-images.githubusercontent.com/6857910/74267821-cdef2100-4cd4-11ea-82cd-0628c48f4564.PNG)

![Capture](https://user-images.githubusercontent.com/6857910/74267715-9a13fb80-4cd4-11ea-9482-a08423695187.PNG)

**Comment by grossmj** [comment]
This is strange. Please can you try the process described in https://github.com/GNS3/gns3-gui/issues/2933 ?

**Comment by jasvijay** [comment]
This was so long ago i forgot all about it, so the problem was that the node was created on GNS3-VM server but the cloud was on local server, if i put them both on same server then they can communicate. but still, the arp requests/replies threw me off when i was diagnosing this.
