### ISSUE TITLE
requirement.txt for oneshot install from pip3

### ISSUE THREAD

**Issue by BedoM** [GNS3/gns3-gui#2930]
Hello,

Can you provide an requirement.txt for oneshot install from pip3 install gns3-gui gns-server ? 

Thank you for your work

**Comment by grossmj** [comment]
We could do something like this. What is the reason you need it?

**Comment by BedoM** [comment]
Hello,
The main reason is that the version offered in "pip3" is always up to date but the primary installation is more complicated (in my opinion).
With a 'requirements' file this will make things easier.

thank you,

Have a good day

**Comment by grossmj** [comment]
The problem I see is we would have to maintain the server dependencies list in 2 locations.

**Comment by grossmj** [comment]
Maybe there is a misunderstanding here. We already have requirements.txt for both the gui and server. Why can't you use them?

https://github.com/GNS3/gns3-server/blob/master/requirements.txt
https://github.com/GNS3/gns3-gui/blob/master/requirements.txt

**Comment by grossmj** [comment]
@BedoM ping :)

**Comment by BedoM** [comment]
My request is too specific to the host distribution, I will use what you have provided me.

thank you so much
