### ISSUE TITLE
Unable to open existing project in GNS3 v2.2.5

### ISSUE THREAD

**Issue by ashenafiwb** [GNS3/gns3-gui#2933]
Unable to open existing projects (both from "Recent projects" and "Projects library") even though they exist in /opt/gns3/projects directory.

GNS3 version and OS information
 - OS: macOS Catalina version 10.15.3
 - GNS3 version 2.2.5
 - Remote server on Ubuntu 18.04 LTS in GCP VM instance. Connected with OVPN.

GNS3 Console output on macOS Client
=> version
GNS3 version is 2.2.5 (compiled)
Python version is 3.6.5 (64-bit) with utf-8 encoding
Qt version is 5.11.0
PyQt version is 5.10.1
SIP version is 4.19.8

1. Go to 'Open project'
2. Click on 'Recent projects'
3. No other project listed to open other than a project I created as "untitled" in the same session.
4. The projects exist in server directory /opt/gns3/projects
5. Click on tab "Projects library" 
6. See that no other project is listed other than the one I created as "untitled" in current session.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/7331481/75308556-c8d5ba00-581c-11ea-805c-df0fff40424e.png)

![image](https://user-images.githubusercontent.com/7331481/75308584-df7c1100-581c-11ea-9421-3a3266b1963b.png)

**Comment by grossmj** [comment]
What is the content of `~/.config/GNS3/2.2/gns3_server.conf`?
