### ISSUE TITLE
Problem with comunication between GNS3 and GNS3VM

### ISSUE THREAD

**Issue by jakubkameleon** [GNS3/gns3-gui#2938]
Hi please help, I have traying whole day ... to fix this problem.... Couple times just works after quit and start one more time it wasn't.
System: Debian 10.3
GNS3: 2.2.5
GNS3 server: 2.2.5

![Screenshot from 2020-03-07 00-16-48](https://user-images.githubusercontent.com/33316966/76129913-11555a80-6009-11ea-956b-be0e4f087ffd.png)

![Screenshot from 2020-03-07 00-16-54](https://user-images.githubusercontent.com/33316966/76129918-15817800-6009-11ea-9a79-c281053a6d37.png)

**Comment by grossmj** [comment]
Please post on https://gns3.com for support. Thanks :+1:
