### ISSUE TITLE
Any idea why the GNS3 GUI is eating 2G of memory 

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2944]
This is on Windows 10, client version is 2.3dev1
![image](https://user-images.githubusercontent.com/17384308/76567195-ab435a00-6484-11ea-982d-a7abee5621a9.png)

**Comment by grossmj** [comment]
Yep, most likely memory leaks :( Have you run the GUI for a long time?

**Comment by 1001QAdotNET** [comment]
no not really...I have had a hectic day with GNS3 see the issues raised today
I have also came across situations when I would drop the appliance template in the project, it would create the node but then the labels won't be visible. Clicking where I guessed there was a label revealed the label. Restarting the client and reopening the project showed the labels there

**Comment by grossmj** [comment]
We will attempt to fix memory leaks if we refactor the desktop Ui. Our priority for now is the web Ui.
