### ISSUE TITLE
2.2 : BUG : can't delete the values in Usage

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2947]
Hi

I have a template of Cisco route (dynamips) with values in Usage.

I use a device of this type.

In this device, in Usage, i select all text and delete it. 
I click on Ok or Apply
The text is be back.

I must replace my text by space to remove it.

**Comment by grossmj** [comment]
Seemed to only be a problem for Dynamips routers. Fixed now.
