### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by silvereyez1** [GNS3/gns3-gui#2949]
Hello,
I am getting following error while i am trying to upgrade from 2.1 to 2.2. 
Could anyone suggest
![error-gns3](https://user-images.githubusercontent.com/62209244/76703066-98789180-66df-11ea-8d2f-6fe6afa3acb0.JPG)

**Comment by grossmj** [comment]
Try to log in to the VM and delete the gns3-server inside the home directory.

**Comment by silvereyez1** [comment]
Thank you

**Comment by grossmj** [comment]
@silvereyez1 I assume it worked. Closing this now. Thanks :+1:
