### ISSUE TITLE
gns3.http_client in _processResponse UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 10: invalid start byte

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#295]
https://app.getsentry.com/gns3/gns3-gui/group/60479671/

```
Stacktrace (appel le plus récent en dernier) : 

  File "./gns3-gui\gns3\http_client.py", line 353, in _processResponse
```

In the body: Error downloading http://127.0.0.1:8000/v1/version - server replied: Request has been forbidden by antivirus

**Comment by grossmj** [comment]
Still trying to understand where the UnicodeDecodeError comes from. Maybe adding errors='replace' to the decode() method would be a solution.

**Comment by noplay** [comment]
And catching exception? Like this

**Comment by grossmj** [comment]
Yep, that's fine I think :+1:

**Comment by noplay** [comment]
Us against anti virus:
![Giphy](http://media0.giphy.com/media/11V3dAPYzVNP8s/giphy.gif)
