### ISSUE TITLE
GNS3 2.2.6 Client not starting.

### ISSUE THREAD

**Issue by s1l3ns** [GNS3/gns3-gui#2952]
**Describe the bug**
GNS3 2.2.6 Client does not start after installing/upgrading from GNS3 2.2.5.

**GNS3 version and operating system (please complete the following information):**
 - OS: **Windows 10 (build 18363.720)**
 - GNS3 version: **2.2.6**

**To Reproduce**
1. Install GNS3 2.2.6 
2. Specify run as administrator
3. Click on GNS3 icon to start the GNS3 application
4. See problem

**Screenshots or videos**
-

**Additional context**
Deleted folder **C:\Users\$Username$\AppData\Roaming\GNS3** - without success.

**Comment by grossmj** [comment]
@s1l3ns is it working now?

**Comment by s1l3ns** [comment]
@grossmj - I managed to get it working by fully uninstalling GNS3, removing the folder in AppData again and re-installing it. Not sure what caused it to not work after the initial install.

**Comment by douirio** [comment]
it looks like there is an issue with Qt5core dll according the windows event viewer. I had the same problem and had to uninstall it competely and re-install it again. it fixed the issue

**Comment by grossmj** [comment]
This may be due to the upgrade Qt version to 5.14.1 in GNS3 version 2.2.6...

**Comment by s1l3ns** [comment]
Looking at the fault log on my end it does indicate an issue with Qt5Core module @grossmj  - Here is the fault log:

`Faulting application name: gns3.exe, version: 2.2.6.0, time stamp: 0x5920c4b7
Faulting module name: Qt5Core.dll, version: 5.14.1.0, time stamp: 0x5e296b4a
Exception code: 0xc0000005
Fault offset: 0x000000000002ada6
Faulting process id: 0x32a4
Faulting application start time: 0x01d603823f24e982
Faulting application path: C:\Program Files\GNS3\gns3.exe
Faulting module path: C:\Program Files\GNS3\Qt5Core.dll
Report Id: f60c13a7-4afc-4bf3-956a-ed4269a18c0e
Faulting package full name: 
Faulting package-relative application ID: `
