### ISSUE TITLE
An issue with GNS3 2.2.6 device menu selection

### ISSUE THREAD

**Issue by dilumtharaka** [GNS3/gns3-gui#2955]
I just upgraded my GNS3 2.2.5 to 2.2.6. I having some difficulty with right clicking (selecting) a device to access the menu.
When I try to right click a device, it automatically selects the first menu item. First I thought this was an issue with my mouse, but then I tried using my laptop touchpad, and the issue is still there.

 - OS: Windows 10
 - GNS3 version: 2.2.6
 - GNS3 VM: 2.2.6

**Comment by grossmj** [comment]
This may be due to the upgrade Qt version to 5.14.1 in GNS3 version 2.2.6...

**Comment by grossmj** [comment]
Discussed in https://gns3.com/community/discussion/an-issue-with-gns3-2-2-6-device-

**Comment by grossmj** [comment]
This version should work for the most part https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-03-31/2.2/GNS3-2.2.2020-03-31-all-in-one.exe/download

However, it looks like there is still an issue with selecting a port when adding a link...

**Comment by rayep** [comment]
Had the same issue, hence rollbacked to v2.2.5. Everything is back to normal :)

**Comment by grossmj** [comment]
We have released version 2.2.7 which should have fixed that issue.

**Comment by dilumtharaka** [comment]
Issue is fixed in version 2.2.7.

**Comment by grossmj** [comment]
@dilumtharaka thanks for the confirmation!
