### ISSUE TITLE
GRE Tunnels Crashing Between VM Instances

### ISSUE THREAD

**Issue by alexstrov** [GNS3/gns3-gui#2956]
Bug Description:
Having students GRE tunnel from GNS3 VM instance on Hyper-V to another GNS3 VM instance. Some students are crashing only when the GRE tunnel connect to others students routers going through Cloud (external interface). GRE tunnels are working fine and no crashes when tunneling to other routers on same Hyper-V VM instance; only external. Of 15 student VMs all on same hardware, only 3 seem to repeatedly crash upon GRE tunneling with others. 

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10
 - GNS3 version 2.2.5
 - GNS3 Hyper-V VM
 - Using 2691 images exclusively

**Comment by grossmj** [comment]
I think this is due to this bug: https://github.com/GNS3/gns3-gui/issues/1867

One possible workaround could be to lower the MTU for the GRE tunnels... but not sure about that.

**Comment by grossmj** [comment]
@alexstrov please can you provide startup-configs for the c2691 nodes so we can reproduce on our side? A quick lab with 2-3 routers will be enough to demonstrate the issue.

Thanks!

**Comment by alexstrov** [comment]
I requested the file and unfortunately the students had not saved them. I have had them set their MTU size and max TCP segment size down to 1400 and we have had no crashing issues.
