### ISSUE TITLE
Annoying uBrigde error popups when Docker image has stopped

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2957]
**Describe the bug**
When a docker image stops by itself, uBridge v0.9.18 creates the error message "Bad address" which results in two large error popups. First of all "Bad address" doesn't give the user any hint, what's the matter. Furthermore it creates two identical popups, like all ubridge errors.

The more interesting information, that the docker image has stopped doesn't result in any message, just the link indicators get red. But I think that's fine, as other VM types behave the same.

Luckily this uBridge error message is not shown, when the docker image is stopped by GNS3.

Here the log from the gns3server, even there is no messgage that the docker VM has stopped.

```
2020-03-31 15:05:06 ERROR hypervisor.py:195 uBridge process has stopped, return
code: 1
uBridge version 0.9.18 running with libpcap version 1.8.1
Hypervisor TCP control server started (IP 0.0.0.0 port 40871).
UDP tunnel connecting from local port 10000 to IPv4 address 192.168.1.99 on port
 10001
Source NIO listener thread for bridge0 has started
Destination NIO listener thread for bridge0 has started
recv: Bad address
Source NIO listener thread for bridge0 has stopped because of an error: Invalid argument


2020-03-31 15:05:06 INFO docker_vm.py:531 Docker container 'alpine-1' fix ownership, state = exited
2020-03-31 15:05:12 INFO docker_vm.py:782 Docker container 'alpine-1' [alpine-be:latest] stopped
```

**GNS3 version and operating system:**
 - OS: macOS 10.13.6
 - GNS3 version 2.2.6
 - Docker image running in GNS3 VM

**To Reproduce**
1. Start a docker image, for example alpine
2. In its console type "exit" to stop it
3. See error

**Comment by grossmj** [comment]
We monitor the uBridge processes since version 2.2.6, I will revert that.
