### ISSUE TITLE
Using a virtual disk to transfer data to/from QEMU VMs

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2958]
**Is your feature request related to a problem? Please describe.**

Currently you can't easily transfer data to/from a QEMU VM. Especially transfering configurations would be very helpful. Issue #1095 wants to create a very comfortable way to share configurations similar to the current Dynamips/IOU solution. But it's also very complex to implement. For every device type a special solution must be found.

This idea should be ways simpler to implement, but is not as comfortable as #1095. This can serve as a transitional solution until a full import/export tool is available.

**Describe the solution you'd like**

Each QEMU device gets an empty 1MB FAT non-cloned raw image added as harddisk D. As almost every system supports FAT disks, the user gets an external storage device, where he can save configurations, but also other informations. It's a sort of virtual USB stick. GNS3 implements methods to transfer the files from this image via the GNS3 GUI to the user's host.

Transfering files from the image to the GUI:
- GUI sends request to server
- Server uses the mtools (https://www.gnu.org/software/mtools/) to extract the files from the raw image, puts them into a .zip archive and sends it to the GUI.
- The GUI stores that .zip file or optionally extracts it

Transfering files from the GUI to the image:
- GUI puts the files into a .zip archive and sends it to the server
- Server extracts the files from the zip archive, adds them with the mtools into an empty FAT image and uses this as the new harddisk D.

Advantages:
- Much simpler to implement as #1095
- Can be used for all file types, it's not limited to configuration files
- Supports a wide range of devices, no device specific code is needed
- Can store multiple files/configurations
- Uses only user mode tools to access the image, no root privileges needed

Disadvantages:
- The user must manually tranfer configurations from/to this virtual disk, the configuration doesn't get automatically activated.
- For performance reasons the virtual disk size should be limited, it's not intended for exchanging big files
- Works only when the VM is switched off

**Comment by b-ehlers** [comment]
I created a base implementation for my own use:

[gns3-gui_patch.txt](https://github.com/GNS3/gns3-gui/files/4438140/gns3-gui_patch.txt)
[gns3-server_patch.txt](https://github.com/GNS3/gns3-gui/files/4438141/gns3-server_patch.txt)
[config.img.zip](https://github.com/GNS3/gns3-gui/files/4438142/config.img.zip)

The GUI patch was quite simple, the server changes are bigger. `config.img.zip` contains a base config disk image together with a build script.

Remaining steps:
- more testing / review
- adding automated tests
- adding a VM configuration option to disable this feature
- currently the user has to add a config disk into the GNS3/images/QEMU directory, maybe that could be done automatically
- optional: pack/unpack the zip file on the GUI side
- bug: python zip extraction sets the timestamp to the current time, I was too lazy to work around that
- limitation: works only, if HD-D is not used

**Comment by b-ehlers** [comment]
I created a base implementation for my own use, see
https://git.bernhard-ehlers.de/ehlers/gns3-qemu-config

**Comment by b-ehlers** [comment]
My implementation is now complete. What remains is to test it under Windows, but I will refrain from that.

**Comment by grossmj** [comment]
Thanks @b-ehlers, I will check it out soon.

**Comment by grossmj** [comment]
PRs https://github.com/GNS3/gns3-gui/pull/3024 and https://github.com/GNS3/gns3-server/pull/1801 opened.

**Comment by grossmj** [comment]
@b-ehlers 

It seems your implementation could be adapted to support extracting configs from IOSv and IOSvL2: https://github.com/GNS3/gns3-server/issues/1315#issuecomment-542883665 I haven't looked into it in too much details but it should work in theory.

We could use libguestfs for it but mtools seems simpler and more portable.

**Comment by b-ehlers** [comment]
Quite some time ago I made some few tests with libguestfs and found it quite slow. When I remember correctly, something around a second. That doesn't sound much, but if you have a topology with 10 routers and have to wait 10 seconds on every start and stop it could be annoying. Therefore I stopped using it. But maybe that has changed, or I made something wrong.

I made some tests using the new version of the IOUtools (https://github.com/GNS3/gns3-server/issues/1627) with IOSv to ensure that config extraction and insertion works. So basically the IOUtools should be ready.

- vios-adventerprisek9-m.vmdk.SPA.156-2.T
- vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E
- vios_l2-adventerprisek9-m.03.2017.qcow2

**Comment by b-ehlers** [comment]
I saw a lot of test failures in <https://ci.appveyor.com/project/gns3-build/gns3-server/builds/34178776>. That's mainly because the qemu base manager `gns3server/compute/qemu/__init__.py` creates an empty config image `config.ing` in the image directory. That irritates quite some tests.

**Comment by grossmj** [comment]
> Quite some time ago I made some few tests with libguestfs and found it quite slow. When I remember correctly, something around a second. That doesn't sound much, but if you have a topology with 10 routers and have to wait 10 seconds on every start and stop it could be annoying. Therefore I stopped using it. But maybe that has changed, or I made something wrong.

I believe it is slow because libguestfs actually launches a VM in the background to mount images (I haven't checked that myself).

> I made some tests using the new version of the IOUtools (GNS3/gns3-server#1627) with IOSv to ensure that config extraction and insertion works. So basically the IOUtools should be ready.

That's great, thanks for the confirmation :)

> I saw a lot of test failures in https://ci.appveyor.com/project/gns3-build/gns3-server/builds/34178776. That's mainly because the qemu base manager gns3server/compute/qemu/__init__.py creates an empty config image config.ing in the image directory. That irritates quite some tests.

Yes, I noticed too. I will fix the tests later.

**Comment by grossmj** [comment]
> I believe it is slow because libguestfs actually launches a VM

This confirms it: http://libguestfs.org/guestfs-performance.1.html

I can also see a lot can go wrong or limit performances. Using mtools looks like a better solution at the moment.

**Comment by b-ehlers** [comment]
The use of mtools is portable, lightweight and supports a wide range of qemu VM types. Of course a solution using libguestfs and IOUtools would be more comfortable, but limited for IOS based VMs. For me this is a base solution, until for some VM types, a full import/export tool is available.

Interesting is, what VIRL v2 is doing, see <https://github.com/GNS3/gns3-gui/issues/1095#issuecomment-636042545>. In my view that's too simple and limited.

**Comment by grossmj** [comment]
> Interesting is, what VIRL v2 is doing, see #1095 (comment). In my view that's too simple and limited.

I agree, issuing some commands on the console port to export configs is not something I want to do.

**Comment by grossmj** [comment]
Implemented. We will work on extracting configs from IOSv, IOSvL2 etc. in the 3.x versions.

**Comment by b-ehlers** [comment]
@grossmj , thanks a lot for your integration work. In the near future I will remove my now obsolete patches at <https://git.b-ehlers.de/ehlers/gns3-qemu-config>.

Since its README file might give some useful hints, I attach it here so that the information is not lost.

Furthermore, I've adding the file [config.img.zip](https://github.com/GNS3/gns3-gui/files/5083320/config.img.zip)

---

# gns3-qemu-config - QEMU config disk

Currently you can't easily transfer data to/from a QEMU VM.
Especially transfering configurations would be very helpful.
But to share configurations similar to the current
Dynamips/IOU solution is very complex.
For every device type a special solution must be found.

This extension is much simpler to implement.
It adds a small DOS formatted disk as HD-D to every QEMU VM.
The user can use this storage device to save configurations,
but also any other data.
The GNS3 server converts this disk image to a ZIP archive,
which is accessible in the GUI by import/export configuration.
To access the files in the disk image the server needs the
`mtools` installed (<https://www.gnu.org/software/mtools/>).

The config disk uses the disk interface of HD-D, unless that
is of type "ide". If it is, the HD-A disk interface is used.
This prevents the use of "ide", unless HD-A is also using it.

Advantages:

* Much simpler to implement as a full configuration import/export.
* Can be used for all file types, it's not limited to configuration files.
* Supports a wide range of devices, no device specific code is needed.
* Can store multiple files/configurations.

Disadvantages:

* The user must manually tranfer configurations from/to this disk,
  the configuration doesn't get automatically activated.
* The user has to manually pack/unpack the ZIP files.
* For performance reasons the virtual disk size is limited,
  it's not intended for exchanging big files.
* Limitation: Works only, if HD-D is not used.


## Patching the GNS3 sources

Apply this addition to a GNS3 sources with:

```text
cd <gns3-gui source directory>
git am <path to patches>/gns3-gui*.patch
cd <gns3-server source directory>
git am <path to patches>/gns3-server*.patch
```

Afterwards do the normal installation from source of GNS3.


## Installing mtools

Linux: mtools packages are available for most distributions,
see <https://pkgs.org/download/mtools>.

macOS: mtools is available in the [Homebrew](https://brew.sh/)
package manager, install it with `brew install mtools`.

Windows: mtools binaries for Win32 are available at
<https://github.com/foone/mtools_win32/releases>.
They will also run on 64-bit Windows.
I have not tested my GNS3 extension on Windows, so
I have no idea if mtools works in this environment.


## Optional: Create an empty DOS formatted disk image

This extension needs a DOS formatted disk image `config.img`
in the QEMU image directory of the GNS3 server.
If this image is missing, a 1 MB image will be created.

If you need a different size, create it as shown below:

```
disk_size=1024		# disk size in KiByte
dd if=/dev/zero bs=1024 count=$disk_size of=config.img status=none
printf 'drive x:\n  file="config.img"\n  partition=1\n' > mtoolsrc
MTOOLSRC=mtoolsrc mpartition -I -c -s 8 -h 16 -t $(($disk_size / 64)) x:
MTOOLSRC=mtoolsrc mformat x:
rm mtoolsrc
```

Afterwards copy it into the QEMU image directory of the GNS3 server.

`config.img.zip` contains the 1 MB image together with the build script.


## Remaining steps

* Needs some tests on Windows, but I have no plans for that.
* Optional: pack/unpack the zip file on the GUI side.

**Comment by b-ehlers** [comment]
Just want to report a special use of the config disk. As junOS uses an unix OS, I was able to set the `/config` directory to the config disk (device `/dev/ad3s1`) in /etc/fstab on junOS/FreeBSD. That way I have the actual configuration directly accessible in GNS3.

I'm using only very old versions of junOS, so I don't know if that works with more recent version.

Olive 12.3R6.6:
```
root@% cat /etc/fstab
#version 3
# Device       Mountpoint  FStype  Options  Dump  Pass#
/dev/ad0s1a    /           ufs     rw        1    1
/dev/ad3s1     /config     msdosfs rw,noauto 0    0
proc           /proc       procfs  rw        0    0
/dev/ad0s1f    /var        ufs     rw,noauto 2    0
/dev/ad0s1b    none        swap    sw        0    0
/dev/ad0s1b    /tmp        mfs     rw,noauto 0    0
/dev/ad0s1b    /mfs        mfs     rw,noauto 0    0
```

vSRX 12.1X47-D20.7:
```
root@% cat /etc/fstab
# Device       Mountpoint  FStype  Options  Dump  Pass#
/dev/md0       /           cd9660  ro        0    0
proc           /proc       procfs  rw        0    0
/dev/ad3s1     /config     msdosfs rw        0    0
/dev/bo0s1b    none        swap    sw        0    0
```

**Comment by b-ehlers** [comment]
With the archive feature of IOS the changed configs can be automatically saved to the config disk. That has the additional benefit, that the user gets a backup of his configurations.

Add to IOS config:

```
archive
 path flash1:$h
 write-memory
```

**Comment by candlerb** [comment]
This feature is interesting, but it would be very useful to have some notes explaining how it is used.

I've tested with CiscoIOSv15.7(3)M3. I checked the box for HDD config disk (which changes "Disk image" to "Startup-cfg"), and left the Startup-cfg field empty:

![image](https://user-images.githubusercontent.com/44789/108070289-41e8a580-705c-11eb-8dd5-64b862beab63.png)

(Note that the [IOSv appliance](https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosv.gns3a) also attaches a qcow image to HDB.  I have left that attached.)

What I found was:

* If you leave HDD as IDE, the device can't boot at all.  The Qemu process is stuck using 100% CPU, and nothing on its console port (normally the grub boot would appear immediately).  My guess is that it tries to boot from HDD in preference.
* Changing HDD from IDE to virtio fixes this.  (Hence perhaps the appliance should set HDC and HDD to virtio? Should it remove the startup image from HDB as well??)

During bootup, I see this amongst the messages:

```
*Feb 16 14:45:45.582: %SYS-5-CONFIG_I: Configured from flash2:ios_config.txt by console
```
I believe that's from the qcow image on HDB.

Once booted, I see three "flash" drives:

```
Router#dir flash0:
Directory of flash0:/

    1  drw-           0  Jan 30 2013 00:00:00 +00:00  boot
  264  drw-           0  Oct 14 2013 00:00:00 +00:00  config
  266  -rw-         374   Aug 1 2018 00:00:00 +00:00  config.grub
  267  -rw-   148955508   Aug 1 2018 00:00:00 +00:00  vios-adventerprisek9-m
  268  -rw-      524288  Feb 16 2021 14:24:36 +00:00  nvram

2142715904 bytes total (1988628480 bytes free)
Router#dir flash1:
Directory of flash1:/

No files in directory

1021440 bytes total (1021440 bytes free)
Router#dir flash2:
Directory of flash2:/

    1  -rw-         386  Mar 27 2017 12:51:08 +00:00  ios_config.txt
    2  -rw-          33  Mar 27 2017 12:51:08 +00:00  ios_config_checksum

966656 bytes total (958464 bytes free)
Router#dir flash3:
%Error opening flash3:/ (No such device)
```

That confirms that flash2: is the HDB `IOSv_startup_config.img`, which by elimination means that flash1: is HDD.

Trying it out:

```
Router#conf t
Enter configuration commands, one per line.  End with CNTL/Z.
Router(config)#hostname foobar
foobar(config)#exit
foobar#cop
*Feb 16 14:36:49.554: %SYS-5-CONFIG_I: Configured from console by console
foobar#copy run flash1:qwerty
Destination filename [qwerty]? 
3150 bytes copied in 1.223 secs (2576 bytes/sec)

foobar#dir flash1:
Directory of flash1:/

    1  -rw-        3150  Feb 16 2021 14:37:02 +00:00  qwerty

1021440 bytes total (1017856 bytes free)
foobar#
```

I then stop the router, and use "Export config" from the menu.  And there's the file:

```
$ ls -l CiscoIOSv15.7\(3\)M3-1_config.zip
-rw-r--r--@ 1 brian  staff  920 16 Feb 14:37 CiscoIOSv15.7(3)M3-1_config.zip
$ unzip CiscoIOSv15.7\(3\)M3-1_config.zip
Archive:  CiscoIOSv15.7(3)M3-1_config.zip
  inflating: qwerty
$ grep hostname qwerty
hostname foobar
```

OK, that's pretty neat.

But then what does the setting "Startup-cfg" do, that I left empty in the GUI?  I tried entering "qwerty" here, but it says "The image qwerty is missing".  Is this for providing an initial zip file, or img file, or something else?

P.S. I've checked that if I select two routers, and then "Export config", I do get a zipfile for each - although I get prompted for multiple Save dialog boxes.

```
$ unzip -v CiscoIOSv15.7\(3\)M3-1_config.zip
Archive:  CiscoIOSv15.7(3)M3-1_config.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3150  Defl:N      810  74% 02-16-2021 14:37 d0ec76f6  qwerty
--------          -------  ---                            -------
    3150              810  74%                            1 file
$ unzip -v CiscoIOSv15.7\(3\)M3-2_config.zip
Archive:  CiscoIOSv15.7(3)M3-2_config.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3150  Defl:N      810  74% 02-16-2021 14:48 990ee333  asdf
--------          -------  ---                            -------
    3150              810  74%                            1 file
```

**Comment by b-ehlers** [comment]
I don't know if the gns3 devs are planning to create a documentation. I'm planning to write something, but currently I'm busy. Maybe in a week or so.

**Comment by grossmj** [comment]
> I don't know if the gns3 devs are planning to create a documentation.

We have no plans so far. Please feel free to write something, thanks :+1:

**Comment by b-ehlers** [comment]
@candlerb I have create a documentation, see <https://www.b-ehlers.de/blog/posts/2021-02-19-gns3-configuration-transfer-qemu/>. Please check it out and give some feedback.

**Comment by candlerb** [comment]
This is very clear indeed. Thank you!

**Comment by grossmj** [comment]
@b-ehlers 

Great documentation indeed. Do you mind if we copy it to our official documentation? I am thinking adding it there: https://github.com/mother/gns3-docs/tree/master/docs/using-gns3/advanced

**Comment by jnatschev** [comment]
Hi.

I may have missed something in all the discussions regarding this topic, so please excuse my query.

I tried to add a “disk” to a qemu node running a csr1000v and after booting the node, getting to the console, and executing ’show file systems’, the HDD Secondary Slave isn’t visible.

Should it work?


Cheers,
John Natschev

**Comment by candlerb** [comment]
The page says: *"Some VM types, like ASAv, support only the main disk image. The config disk will therefore not be visible on these VMs."*

It's quite possible CSRv is also like this, although I've not tested CSRv + additional disk myself.

**Comment by jnatschev** [comment]
OK. By rereading the documentation, I found I am missing one vital ingredient: mtools.

I just installed mtools using Homebrew.

So now my question is how does GNS3 work out where the mtools executable is?



Cheers,
John Natschev

**Comment by candlerb** [comment]
```
+            if not shutil.which("mcopy"):
+                log.warning("Config disk: 'mtools' are not installed.")
```

In other words: it works out where it is the same way as the shell does for you, by searching for it in `$PATH`

```
$ which mtools
/usr/bin/mtools
$ 
```

**Comment by candlerb** [comment]
Note also: mtools is only needed at the server side.  If you are running the GNS3 GUI on a mac, and the GNS3 server is running in a Linux VM or a remote Linux server, then you don't need mtools on the mac.

**Comment by b-ehlers** [comment]
@grossmj Feel free to use my documentation as a basis for the official documentation, modify it as needed.

**Comment by jnatschev** [comment]
Thanks for the response regarding how mtools is found. Message understood.

I also reread the documentation and found that mtools is required on the GNS3 VM.

I checked the GNS3 VM and didn’t find mtools, so I installed it with ‘sudo apt install mtools’. So now, by executing ‘which mtools’ on the GNS3 VM shell I get ‘/usr/bin/mtools’.

Now just need to check whether a csr1000v node will work.

Let’s see how i go…


Cheers,
John.

**Comment by candlerb** [comment]
> I checked the GNS3 VM and didn’t find mtools, so I installed it with ‘sudo apt install mtools’.

I wonder why that was not done automatically when you upgraded the gns3-server package?  Try this:

```
apt-cache show gns3-server | grep Depends:
```

If you have gns3-server 2.2.18 then you should see "mtools" in the list of dependencies.

**Comment by jnatschev** [comment]
here is the output:
Depends: python3, vpcs, ubridge (>= 0.9.14), qemu-system-x86, qemu-kvm, qemu-utils, mtools, cpulimit, libvirt-bin | libvirt-daemon-system, libc6 (>= 2.25), libexpat1 (>= 2.1~beta3), zlib1g (>= 1:1.2.0)

which is strange then because i upgraded from 2.2.17 to 2.2.18 and needed to install mtools manually.

**Comment by b-ehlers** [comment]
I have to confess, that I use GNS3 directly within Linux and therefore haven't tested the GNS3VM as good as I should.

Currently the mtools package is **NOT** installed in the GNS3VM, you have to do it manually. I updated my documentation and created issue https://github.com/GNS3/gns3-gui/issues/3138 to get that fixed.

The command `apt-cache show gns3-server | grep Depends:` shows, what dependencies the GNS3 server package has, but not if the gns3-server package is actually installed. To see that, run a `dpkg -s gns3-server`. You will see, that the gns3-server package is not installed, the GNS3VM installs the GNS3 server from source.

**Comment by grossmj** [comment]
This is correct, I noticed that problem a few days ago, the Debian packages aren't used in the GNS3 VM. I plan to manually install mtools package in the VM soon.

**Comment by grossmj** [comment]
Re-opening this issue to remind me to install the mtools package.

**Comment by grossmj** [comment]
> Re-opening this issue to remind me to install the mtools package.

You have been faster than me. You already opened an issue for that: https://github.com/GNS3/gns3-gui/issues/3138

**Comment by jnatschev** [comment]
I tried every which way i could think of and could not get a second virtual disk available on a Cisco CSR1000v.

Thanks to all for their messages.

Need to try and think of a different way of getting a backup of the configurations.


Cheers,
john.

**Comment by candlerb** [comment]
> Need to try and think of a different way of getting a backup of the configurations

You'll probably find it easiest to set up a local tftp server.

For IOSv/IOSvL2, in principle it's possible to read and write the NVRAM file on the main (hda) disk: see https://github.com/GNS3/gns3-server/issues/1315

For CSR1000v, the NVRAM file is encrypted by default.  You can override this by configuring

```
boot config bootflash:config.txt nvbypass
```

after which it uses `/config.txt` on the main disk (hda) as its startup config.  But you still need to retrieve that file from the hda qcow2 file, e.g. using guestfish.  

For importing the initial CSRv config on first boot, there's another option: you can attach a CD-ROM image containing `iosxe_config.txt`.  You can generate a suitable ISO file using:

```
genisoimage -output CSRv_boot_config.iso -joliet -rock iosxe_config.txt
```

**Comment by jnatschev** [comment]
thank you brian. i had been doing it by adding a vmware host with a nic connected to the topology and a nic connected to the lan then copying from the device to the vmware host or copying from the vmware host to the device’s running-config or startup-config.

just cumbersome and do a degree difficult to automate.

however, with your suggestion i may be able to get it done.

thanks again.


john.
