### ISSUE TITLE
checksum sha256 is not valid for GNS3.VM.KVM.2.2.6.zip

### ISSUE THREAD

**Issue by RaleghDirat** [GNS3/gns3-gui#2959]
cat GNS3.VM.KVM.2.2.6.zip.sha256 
347c5851d964c289846b676da3a8cdbabb21eb55fd660865a0422cf3d9d0d394  GNS3.VM.KVM.2.2.6.zip

sha256sum -b GNS3.VM.KVM.2.2.6.zip
20b66c45cf6ebeb4cfb1b04da3d8b054a12d855b8648887fde375cc9cc8b2954 *GNS3.VM.KVM.2.2.6.zip

sha256sum -c GNS3.VM.KVM.2.2.6.zip.sha256 
GNS3.VM.KVM.2.2.6.zip: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match

**Comment by grossmj** [comment]
Thanks, have you only tested the KVM zip?

**Comment by RaleghDirat** [comment]
> Thanks, have you only tested the KVM zip?

Only the kvm, yes.

**Comment by grossmj** [comment]
This should be good with version 2.2.7. Please comment back if not.
