### ISSUE TITLE
In GNS3 V1.3.2dev QEMU devices can use only 1 port

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#296]
I just tested the current dev version. With linux and OS X (Windows not tested) I can connect only one link in the GUI to a qemu VM. Only Ethernet0 is available. When starting the qemu VM all configured interfaces (4 in my example) are there. It's just the GUI that limits it to one.

All other VM types as dynamips(IOS), IOU and VirtualBox are not affected.

**Comment by cioby23** [comment]
I agree I have tested also and from the GUI there is only Ethernet0 available for connection even if I have added multiple interfaces.

**Comment by ehlers** [comment]
Additional remark:
When I change the number of interfaces after dragging the qemu template into a topology, I can use all interfaces. The problem arises only, when I don't change the number of interfaces.

**Comment by davidnvega** [comment]
Sorry for comment in here but i'm really lost. I have installed GNS3 version 2.0.0dev1 and i am having problems with HUB and Switch. It only allows to me to use only one port, and when i try to connect it an error occurs. Thanks and sorry for my english!

**Comment by noplay** [comment]
Hi,

Please open a new question on http://gns3.com/community with more details (a screenshot of topology and the error for example).

Thanks
