### ISSUE TITLE
unable to Configure Custom Adapters (Qemu VM)

### ISSUE THREAD

**Issue by sum1els** [GNS3/gns3-gui#2961]
> GNS3 GUI version 2.2.6
> Distributor ID: Ubuntu
> Description:    Ubuntu 19.10
> Release:        19.10
> Codename:       eoan
> Python 3.7.5

Whenever I click on the "Configure Custom Adapters" under a Qemu VM, I get the following error:

`Traceback (most recent call last):
  File "/usr/share/gns3/gns3-gui/lib/python3.7/site-packages/gns3/modules/qemu/pages/qemu_vm_configuration_page.py", line 404, in _customAdaptersConfigurationSlot
    if self._settings["legacy_networking"]:
TypeError: 'NoneType' object is not subscriptable
`

Could it be my python version ad it seems to be a python issue ?

**Comment by sum1els** [comment]
noticed it is only when you try and do it in the template, but once you drag the device to your project, you can then edit and configure custom adapters/names.

**Comment by cioby23** [comment]
I can confirm it also. Only happens on the template configuration part. I'm running also version 2.2.6/Python 3.8/OS: Archlinux.

**Comment by grossmj** [comment]
Fixed.

**Comment by b-ehlers** [comment]
Yes, it seems to be fixed, but only in the development branch v2.3. v2.2.7 still has this bug.
https://gns3.com/community/discussion/bug-when-changing-network-adapte

**Comment by grossmj** [comment]
Thanks, changes have been merged to branch v2.2

**Comment by b-ehlers** [comment]
No, the changes are still only done in v2.3. You merged v2.3 of **gns3-server** into v2.2 (websocket console and server statistics). The changes in the **gns3-gui** were not merged.

**Comment by grossmj** [comment]
Correct, should be good now :+1:

**Comment by b-ehlers** [comment]
That looks better, thanks.
