### ISSUE TITLE
Not able to add Frame relay or bulit in Ethernet switches in GNS3 Linux mint

### ISSUE THREAD

**Issue by sachinsebastian** [GNS3/gns3-gui#2962]
This is what i get after pulling my Frame relay switch and Ethernet switch 
I tried almost all the recommendation provided in forms but no luck
Can you guys please help me out, i am not expert in linux but learning step by step...Thanks in advance.

GNS3 management console.
Running GNS3 version 2.2.6 on Linux (64-bit) with Python 3.6.9 Qt 5.9.5 and PyQt 5.10.1.
Copyright (c) 2006-2020 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=45bae288-c019-4126-a7de-9b69e0f29be2&aip=1&t=screenview&an=GNS3&av=2.2.6&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.2.6&cd=Main%20Window&ds=gns3-gui&sr=1366x768&ul=en_in
GET http://localhost:3080/v2/version
Error while connecting to local server Connection refused
GET http://localhost:3080/v2/version
Error while connecting to local server Connection refused
GET http://localhost:3080/v2/version
Error while connecting to local server Connection refused
Starting local server process with "/usr/bin/gns3server" --local --debug --log="/home/sachin/.config/GNS3/2.2/gns3_server.log" --pid="/home/sachin/.config/GNS3/2.2/gns3_server.pid"
Local server process has started (PID=4180)
Set worker inside a thread <class 'gns3.utils.wait_for_connection_worker.WaitForConnectionWorker'>
WaitForConnectionWorker thread started
WaitForConnectionWorker thread finished
WaitForConnectionWorker thread is being destroyed
WaitForConnectionWorker thread destroyed
Connection to http://localhost:3080
GET http://localhost:3080/v2/version {}
Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=45bae288-c019-4126-a7de-9b69e0f29be2&aip=1&t=screenview&an=GNS3&av=2.2.6&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.2.6&cd=Project%20Dialog&ds=gns3-gui&sr=1366x768&ul=en_in
Decoding response from http://admin@localhost:3080/v2/version response 200
GET http://localhost:3080/v2/templates {}
GET http://localhost:3080/v2/computes {}
GET http://localhost:3080/v2/appliances?symbol_theme=Classic {}
GET http://localhost:3080/v2/projects {}
Connecting to WebSocket endpoint: ws://localhost:3080/v2/notifications/ws
GET http://localhost:3080/v2/version {}
GET http://localhost:3080/v2/projects {}
Decoding response from http://admin@localhost:3080/v2/templates response 200
GET http://localhost:3080/v2/symbols/%3A/symbols/multilayer_switch.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/router.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/classic/docker_guest.svg/raw {}
GET http://localhost:3080/v2/symbols/linux_guest.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/classic/multilayer_switch.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/cloud.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/vpcs_guest.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/ethernet_switch.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/hub.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/frame_relay_switch.svg/raw {}
GET http://localhost:3080/v2/symbols/%3A/symbols/atm_switch.svg/raw {}
Decoding response from http://admin@localhost:3080/v2/computes response 200
Decoding response from http://admin@localhost:3080/v2/appliances?symbol_theme=Classic response 200
Decoding response from http://admin@localhost:3080/v2/projects response 200
Decoding response from http://admin@localhost:3080/v2/version response 200
Decoding response from http://admin@localhost:3080/v2/projects response 200
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/router.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/18011c181013b0971a1a8f3e94202386.svg for /symbols/%3A/symbols/router.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/multilayer_switch.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/b4625a5a801e68d455bd5cf0012a088f.svg for /symbols/%3A/symbols/multilayer_switch.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/classic/multilayer_switch.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/bb687004e613d46bc8da3b859604f187.svg for /symbols/%3A/symbols/classic/multilayer_switch.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/classic/docker_guest.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/597cb910bb6c22dd1dcf2ab41afec7c3.svg for /symbols/%3A/symbols/classic/docker_guest.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/cloud.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/b7fc40772980613897e485197a957f88.svg for /symbols/%3A/symbols/cloud.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/linux_guest.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/bd5c00e80ad556a12e1689b051505b88.svg for /symbols/linux_guest.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/hub.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/8ebdb8f0fe6895a42d27ed50b06de689.svg for /symbols/%3A/symbols/hub.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/vpcs_guest.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/94045dc1e27af247496de443eeb31a8f.svg for /symbols/%3A/symbols/vpcs_guest.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/ethernet_switch.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/855e8cf4fe8848800855d1b9730328d1.svg for /symbols/%3A/symbols/ethernet_switch.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/frame_relay_switch.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/2a45f9c65479fc28388a2332e7b3c526.svg for /symbols/%3A/symbols/frame_relay_switch.svg/raw
Decoding response from http://admin@localhost:3080/v2/symbols/%3A/symbols/atm_switch.svg/raw response 200
File stored /tmp/tmpsjwez5qa-gns3/d8198a5d11a729a46b8074c9af9549c1.svg for /symbols/%3A/symbols/atm_switch.svg/raw
POST http://localhost:3080/v2/projects {'name': 'BUg report', 'path': '/home/sachin/GNS3/projects/BUg report', 'grid_size': 75, 'drawing_grid_size': 25, 'show_grid': False, 'snap_to_grid': False, 'show_interface_labels': False}
Decoding response from http://admin@localhost:3080/v2/projects response 201
Connecting to WebSocket endpoint: ws://localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/notifications/ws
Section MainWindow has changed. Saving configuration
Configuration save to /home/sachin/.config/GNS3/2.2/gns3_gui.conf
Section MainWindow has changed. Saving configuration
Configuration save to /home/sachin/.config/GNS3/2.2/gns3_gui.conf
POST http://localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/dd0f6f3a-ba58-3249-81cb-a1dd88407a47 {'x': -44, 'y': -3, 'compute_id': 'local'}
Response error: Error transferring http://admin@localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/dd0f6f3a-ba58-3249-81cb-a1dd88407a47 - server replied: Conflict (localhost:3080) for http://admin@localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/dd0f6f3a-ba58-3249-81cb-a1dd88407a47 (error: 206)
Error while creating node from template: Couldn't connect to hypervisor on localhost:56457 :[Errno 111] Connect call failed ('127.0.0.1', 56457)
POST http://localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/1966b864-93e7-32d5-965f-001384eec461 {'x': -101, 'y': 12, 'compute_id': 'local'}
Response error: Error transferring http://admin@localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/1966b864-93e7-32d5-965f-001384eec461 - server replied: Conflict (localhost:3080) for http://admin@localhost:3080/v2/projects/9aaf459e-8f21-4879-9bc8-fd7499f3a722/templates/1966b864-93e7-32d5-965f-001384eec461 (error: 206)
Error while creating node from template: Couldn't connect to hypervisor on localhost:54389 :[Errno 111] Connect call failed ('127.0.0.1', 54389)

**Comment by grossmj** [comment]
Something is blocking dynamips.exe to run on your system. This may be your antivirus.

**Comment by grossmj** [comment]
What do you see if you manually start dynamips?

```
dynamips --version
Cisco Router Simulation Platform (version 0.2.21-amd64/Linux stable)
```
