### ISSUE TITLE
gns3-gui hangs connecing waiting for connection server running on localhost

### ISSUE THREAD

**Issue by ninjasta** [GNS3/gns3-gui#2963]
I am running Fedora 31 Gns3 2.2.6 suite installed to run vm's local host.
Whilst building Topologies the Gui hangs and endlessly show "connecting the server 127.0.0.1:3080.
This happens but once it starts the topology cannot be edited nor can connections be added or deleted.

**Comment by grossmj** [comment]
Try to manually start the GNS3 server and see if you spot any error: `gns3server --local`
