### ISSUE TITLE
GNS3 2.2.5 not starting on high sierra

### ISSUE THREAD

**Issue by bmabioye** [GNS3/gns3-gui#2964]
GNS3 2.2.5 and 2.2.7 won't start on High Sierra. It closes immediately launching from the Application folder on mac.
Meanwhile, GNS3 2.2.1 works.

Mac OS X High Sierra 10.13.1 
System Integrity Disabled 
sudo spctl --master-disable

I have GNS3 VM 2.2.5 server but not working with the older version GNS3 2.2.1
I have uninstalled and re-installed times without number.
I have VMware Fusion Professional Version 10.1.3 (9472307) installed

**Comment by grossmj** [comment]
Just tested 2.2.7 on macOS 10.15 (Catalina) and everything worked well.

Can you provide more information about the crash, maybe by getting information from the console app? https://blog.macsales.com/45586-how-to-use-the-mac-console-app-to-diagnose-a-crash/

Thanks!

**Comment by bmabioye** [comment]
Here is what i found on system.log
after i tried to launch it thrice consecutively 

Apr 12 12:26:39 MacBook-Pro com.apple.xpc.launchd[1] (net.gns3.9584[46707]): Service exited with abnormal code: 1
Apr 12 12:26:43 MacBook-Pro com.apple.xpc.launchd[1] (net.gns3.9584[46708]): Service exited with abnormal code: 1
Apr 12 12:26:45 MacBook-Pro com.apple.xpc.launchd[1] (net.gns3.9584[46709]): Service exited with abnormal code: 1

**Comment by bmabioye** [comment]
> Just tested 2.2.7 on macOS 10.15 (Catalina) and everything worked well.
> 
> Can you provide more information about the crash, maybe by getting information from the console app? https://blog.macsales.com/45586-how-to-use-the-mac-console-app-to-diagnose-a-crash/
> 
> Thanks!

Thank you. hope that log says anything meaningful?
for now i have resolve to using GNS3 version 2.2.1 which works.

**Comment by grossmj** [comment]
I guess I will have to install high sierra to figure this out.

**Comment by grossmj** [comment]
I didn't get any issue on freshly installed macOS 10.13 (running in VirtualBox).

![Screenshot from 2020-05-01 15-40-07](https://user-images.githubusercontent.com/4752614/80788214-a454e000-8bc7-11ea-8c4d-9fed979f6afe.png)

Maybe you can try the same build? https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-05-01/2.2/GNS3-2.2.8dev1.dmg/download

**Comment by bmabioye** [comment]
I will try the build and revert back. Thanks

**Comment by bmabioye** [comment]
> I didn't get any issue on freshly installed macOS 10.13 (running in VirtualBox).
> 
> ![Screenshot from 2020-05-01 15-40-07](https://user-images.githubusercontent.com/4752614/80788214-a454e000-8bc7-11ea-8c4d-9fed979f6afe.png)
> 
> Maybe you can try the same build? https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-05-01/2.2/GNS3-2.2.8dev1.dmg/download

I did try running this version, it's the same(closes immediate after launch).
 I guess it might have to do the High Sierra 10.13.1 
I will assume it has to do with my OS until I can run on another Mac OS. 

many thanks.
