### ISSUE TITLE
Enhancements when duplicating multiple selected objects

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-gui#2966]
**Is your feature request related to a problem? Please describe.**
When building up a complex topology, I'll build a cluster of devices, then select them all, then "Duplicate" to create a new cluster.

GNS3 does a nice job of this, including renaming all the devices sensibly (e.g. "border1" -> "border2").  However there are a couple of annoyances:

1. The duplicated objects aren't selected. Hence if you click on one and drag it, it drags just that one, not the whole group.  You have to to command-click on every duplicated device individually before moving the cluster. (You can't drag over an area, because that would select the originals too)

2. Connections between devices in the cluster have to be recreated manually

**Describe the solution you'd like**

1. After duplicating a group, all the duplicated items to be selected automatically.  Thus you can drag to move the copies together.

2. When duplicating a group, automatically duplicate connections where both ends are between selected items.  (Links to items outside the group can be ignored).

**Describe alternatives you've considered**
Some drawing package allow you to permanently "group" items (i.e. select multiple items then right-click "Group" or "Ungroup").  That would work too.  However I'm happy just to have the items pre-selected immediately after a Duplicate operation, since the first thing I'll do is move them to the right place anyway.

**Additional context**
N/A

**Comment by grossmj** [comment]
Thanks for the great ideas. It seems this is not so trivial to implement, so this is gonna have to wait.
