### ISSUE TITLE
Confirmation dialog for "console connect to all nodes"

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-gui#2971]
**Is your feature request related to a problem? Please describe.**
I have an emulation with 50+ nodes.  I click the "Console connect to all nodes" button:

![image](https://user-images.githubusercontent.com/44789/80196746-b1952c00-8615-11ea-969f-365df197946b.png)

...either because I mistake it for the tool for adding Text to a diagram, or because I've control-clicked two or three devices and I want to open consoles on those only (I should have used the right-click menu instead - see #2876)

Result: I get spammed with telnet windows which have to be closed one by one :-(

**Describe the solution you'd like**
If it would open more than (say) 5 consoles, then pop up a confirmation dialog box along the lines of:

"You are about to open console windows to 56 devices.  Are you sure?"

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
N/A

**Comment by grossmj** [comment]
Implemented. It will ask for confirmation when trying to open more than 10 consoles.
