### ISSUE TITLE
Qt or PyQt missing on Win10 1909

### ISSUE THREAD

**Issue by MattNot** [GNS3/gns3-gui#2976]
**Describe the bug**
Just installed the latest (and also other versions) of GNS3.
**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 64bit build version 1909
 - GNS3 version latest (and older too) (used the AOI installer)

**To Reproduce**
1. Install it as guide

**Screenshots or videos**
![Cattura](https://user-images.githubusercontent.com/29925647/80531441-f238d080-899a-11ea-9908-e3274f586921.PNG)

It says "Impossible to find the specified procedure

**Additional context**
Python is installed on my machine

**Comment by grossmj** [comment]
There may be a conflict here. What happens if you uninstall Python and reboot?

Alternatively, you could try to install PyQt using your Python installation. I think executing something like this from the command line would work:

`<path_to_Python_install_dir>\Scripts\pip.exe install PyQt5`

**Comment by MattNot** [comment]
Already tried, I've installed python for this problem, thinking that it could resolve.
Installed PyQt5 too.

**Comment by cioby23** [comment]
@MattNot I just installed latest GNS3 gui version 2.2.8 on a Windows 10 1909 64-bit VM and the installation went fine without any issues.
I recommend to uninstall existing GNS3 version and remove and traces left by GNS3 installer (remove Program Files\GNS3 folder) and the perform a new clean installation.
Also if you have PyQt installed separately please remove it as GNS3 installer comes with PyQt included.
