### ISSUE TITLE
Ubuntu Focal 20.04: GNS3 PPA is actually v2.2.6 and not latest v2.2.7

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#2977]
**Describe the bug**
The gns3 version from ppa is actually 2.2.6 and not the latest 2.2.7.

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 20.04
 - GNS3 version: 2.2.7

**To Reproduce**
```
sliddjur@ubuntu ~> cat /etc/apt/sources.list.d/gns3-ubuntu-ppa-focal.list
deb http://ppa.launchpad.net/gns3/ppa/ubuntu focal main
# deb-src http://ppa.launchpad.net/gns3/ppa/ubuntu focal main

sliddjur@ubuntu ~> sudo apt update
...                                                                                                                                                   
Hit:8 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease                               
...
Reading package lists... Done
Building dependency tree       
Reading state information... Done

sliddjur@ubuntu ~> apt show gns3-gui
Package: gns3-gui
Version: 2.2.6~focal1
Priority: extra
Section: net
Maintainer: GNS3 team <developers@gns3.net>
Installed-Size: 31,1 MB
Depends: python3, python3-pyqt5, python3-pyqt5.qtsvg, python3-pyqt5.qtwebsockets, wireshark, vinagre, libc6 (>= 2.14)
Recommends: gns3-server
Replaces: gns3 (<< 1.4.0-1)
Download-Size: 7 151 kB
APT-Sources: http://ppa.launchpad.net/gns3/ppa/ubuntu focal/main amd64 Packages
Description: GNS3 GUI
```

**Additional context**
After installing this from ppa apt source, I get client version 2.2.6 and mismatch version with my gns3-server that runs 2.2.7

**Comment by sliddjur** [comment]
Looks like gns3-server and gns3-gui has failed to build on ubuntu-20.04
https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal

**Comment by cioby23** [comment]
This is a known problem and there is an existing issue opened for this https://github.com/GNS3/gns3-server/issues/1746

**Comment by grossmj** [comment]
Indeed, we already have an issue opened.
