### ISSUE TITLE
Create new version imports image with wrong filename

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#2978]
**Describe the bug**
When you create a new template, create new version of that template, and then import the disk image, the file name is incorrect. It uses the file name of an already existing version from that template.

**GNS3 version and operating system (please complete the following information):**
 - OS Client: Ubuntu 19.10, Ubuntu 20.04
 - OS Server: gns3vm, Ubuntu 18.04
 - GNS3 version: gns3 2.2.7 (via ppa and pip)
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.): only using gns3vm as main server.

**To Reproduce**
See video
If I create another version again, say version 1.2.6, it will again use the same file name, and overwrite the current one, which will eventually break my 1.2.5 image.
The workaround is to manually change file names in gns3vm for the `iso` and `md5sum` file. Then update the template to use the correct cd-drive file.

**Screenshots or videos**
![gns3](https://user-images.githubusercontent.com/10002057/80750574-9ef48880-8b28-11ea-8822-1462906ed46f.gif)

**Additional context**

**Comment by grossmj** [comment]
There was a problem with the appliance file itself. I have updated it: https://raw.githubusercontent.com/GNS3/gns3-registry/master/appliances/vyos.gns3a

Please click on "Update from online repository" and then you should be able to add a new version for the VyOS appliance.

![Screenshot from 2020-05-05 14-31-28](https://user-images.githubusercontent.com/4752614/81036151-28b3a580-8edd-11ea-99b1-cf795b34493f.png)

**Comment by sliddjur** [comment]
@grossmj first I got error `=> Error while getting appliances list: Could not write appliance file '/usr/local/lib/python3.6/dist-packages/gns3server/appliances/Simulator.gns3a': [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/gns3server/appliances/Simulator.gns3a'` when updating from online registry.

So I did `$ sudo chown gns3 /usr/local/lib/python3.6/dist-packages/gns3server/appliances/*` and now I can press `Update from online registry`. However, problem still persists, and I cannot see any of the appliance files has been updated after pressing the button.

**Comment by grossmj** [comment]
Confirmed, there is a problem writing to appliance files.

![webtermbnoxerror](https://user-images.githubusercontent.com/4752614/81366590-314ceb80-912a-11ea-8793-253231d34b25.png)

**Comment by grossmj** [comment]
Do you get the problem installing GNS3 using PyPi (pip)?

**Comment by sliddjur** [comment]
> Do you get the problem installing GNS3 using PyPi (pip)?

@grossmj I just tried now again in 2.2.8 (ubuntu 20.04, installed via pip), and it seems to be importing with the correct file name!

Since PPA is still broken for ubuntu20, I have not tested it with that version.

**Comment by grossmj** [comment]
> @grossmj I just tried now again in 2.2.8 (ubuntu 20.04, installed via pip), and it seems to be importing with the correct file name!

Great :+1: should I close this issue?

> Since PPA is still broken for ubuntu20, I have not tested it with that version.

PPA version should work after the next release.

**Comment by sliddjur** [comment]
Yes

> Great +1 should I close this issue?
