### ISSUE TITLE
Error while creating node from template: Couldn't connect to hypervisor on localhost:43405 :[Errno 111] Connect call failed ('127.0.0.1', 43405)

### ISSUE THREAD

**Issue by Rohs90** [GNS3/gns3-gui#2979]
hello, premise I had to install gns3 because I am following a pen testing course on udemy, as soon as the course had arrived in the part where he had to put a c3725 device on the gns3 map I had this problem, I paste the error that gives me when I put any switch or router in the map, another premise this error happens only when I try to add a switch or router, instead when I put a cloud or PCs in the map everything is as smooth as oil,the error is Error while creating node from template: Couldn't connect to hypervisor on localhost:60191 :[Errno 111] Connect call failed ('127.0.0.1', 60191)
i also tried to change the path of dynamips in /usr/bin/dwp and i had also install the "new" dynimaps from git hub without problem.Idk what can i do,please help me.Thank

**Comment by grossmj** [comment]
Please post on gns3.com to get support. Thanks :+1:
