### ISSUE TITLE
To run a Pinned docker cpu or memory resource on gns3

### ISSUE THREAD

**Issue by emylincon** [GNS3/gns3-gui#2980]
**Problem**
I use GNS3 as an experimental testbed for my research. I am currently running an experiment that compares CPU and memory utilization during algorithm runtime. however, I cannot do this at the moment because the docker container on gns3 has access to the whole system resources.

I can pin the docker CPU and memory resources on the gns3 VM but i cannot use the same docker in my gns3 topology
```
docker run -it --cpus=".5" ubuntu /bin/bash
```
**Feature**
Would it be possible to add a feature where you can specify the max resources each docker container can use (cpu, memory, etc)

**Comment by grossmj** [comment]
This is similar to https://github.com/GNS3/gns3-server/issues/486 and definitely something you would like to do.

In the meantime, here is a workaround. Find out your running container ID.

```
$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS               NAMES
3740ca0fb5de        gns3/ubuntu:xenial   "/gns3/init.sh sh -c…"   6 seconds ago       Up 4 seconds                            friendly_hodgkin
```

Then update the CPU value and check the NanoCpus value has been updated:

```
$ docker update --cpus=".5" 3740ca0fb5de
3740ca0fb5de

$ docker inspect 3740ca0fb5de | grep NanoCpus
            "NanoCpus": 500000000,
```

For info, here is how to do it using the Docker Engine API:

```
curl -X POST --unix-socket /var/run/docker.sock "http://docker/containers/3740ca0fb5de/update" -d '{"NanoCpus": 500000000}' -H 'Content-Type: application/json'
{"Warnings":null}
```

Hope this helps.

**Comment by emylincon** [comment]
It works. Thanks a lot for replying so quick Jeremy.

**Comment by grossmj** [comment]
Implemented.
