### ISSUE TITLE
Wrong URL in Online help menu

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-gui#2984]
Hello,

GNS3 2.2.8 GUI menu Help - Online help opens URL https://gns3.com/support/docs where only "Sorry! The page you are looking for could not be found."

**Comment by nuqleo** [comment]
Maybe GNS3 Academy menu also should be updated.
There is http://academy.gns3.com which is redirected to https://gns3.teachable.com/

**Comment by PeterEstephanV2** [comment]
There is this link to the documentation: https://docs.gns3.com/

**Comment by grossmj** [comment]
Thanks, I have fixed the link :+1: The http://academy.gns3.com redirection is fine.
