### ISSUE TITLE
Upgraded Server to 2.2.8 and the GNS3 Server Console no longer loads correctly

### ISSUE THREAD

**Issue by PeterEstephanV2** [GNS3/gns3-gui#2985]
I currently have a GNS3 Server running on my ESXi server. (The GNS3 server was originally deployed using the OVA, so it runs Ubuntu). It was previously running 2.2.7 and I just upgraded it today to 2.2.8. I upgraded it via the GNS3 Console Menu by going to Upgrade -->2.2.8. Once it was done upgrading/updating, it rebooted then I got the following error message:
![image](https://user-images.githubusercontent.com/43788259/81348910-33f10780-907c-11ea-81ea-3736a30bc603.png)

I then proceeded to do "sudo gns3restore" and after that completed and it rebooted the VM, the same issue/error messages occurred.

**Comment by grossmj** [comment]
Here is a workaround:

1. Go to configure

![Screenshot from 2020-05-08 11-52-47](https://user-images.githubusercontent.com/4752614/81363458-8684ff00-9122-11ea-9b43-d4a4df066a27.png)

2. Add `port = 3080` to the file

![Screenshot from 2020-05-08 11-53-03](https://user-images.githubusercontent.com/4752614/81363465-8a188600-9122-11ea-831a-ab190acbfd51.png)

3 Restart the VM

Or you can edit the file directly in ~/.config/GNS3/2.2/gns3_server.conf and then restart.

**Comment by grossmj** [comment]
I have fixed the problem in https://github.com/GNS3/gns3-vm/commit/87a732741a73e2e84f5a01660180e11fa8073b16

Update the VM will apply the fix.
