### ISSUE TITLE
Multi-device selection/deselection not working as expected with right click

### ISSUE THREAD

**Issue by cdwchriburg** [GNS3/gns3-gui#2986]
**Describe the bug**
There seems to be an issue with selection/de-selection behavior of objects in the desktop GUI.  If you right click a device and click the console menu item, then right click another device and click the console menu item of that device, both devices are selected and the second time you click console you get a duplicate window from the first device.

Expected standard GUI behavior is that the first device would be de-selected when you right click the second device (unless the control key was being held down).  You also see this selection not working as expected if you right click multiple devices without selecting something in the context menu - it will keep adding devices to the selection as if you are holding the control key.

But if you left-click multiple devices you see that it properly de-selects the previous selection unless you're holding the control key as expecte.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 build 1809
 - GNS3 version 2.2.8 (also present in 2.2.7)
 - GNS3 VM on ESXi

**To Reproduce**
1. Add two devices (e.g. routers) to the topology
2. Right click one device and select console
3. Right click the other device and select console
4. You now have three console windows open instead of two

**Screenshots or videos**

**Additional context**
Have seen this issue in 2.2.7 and 2.2.8.  Unsure the first version it appeared in.

**Comment by grossmj** [comment]
Thanks for catching that. This should be fixed when we release version 2.2.9 next week.

**Comment by grossmj** [comment]
I reverted back the changes and now simply force all items to be deselected after showing the contextual menu. Seems to fix the problem reported by the OP and not changing the old behavior.
