### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by larssec** [GNS3/gns3-gui#2988]
Dynamips error when running command 'nio create_udp udp-b75929d2-4e74-4d12-8d79-bb0336a2e20a 10010 127.0.0.1 10011
': unable to create UDP NIO

This is useless.  I am just trying to start a project.
GNS3 is Not Functional

**Comment by larssec** [comment]
Also it take a minute to close, common

**Comment by grossmj** [comment]
Please have a look at https://github.com/GNS3/gns3-server/issues/1271#issuecomment-578389042

Thanks
