### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by C0d3-R3d** [GNS3/gns3-gui#2990]
Gns3 won't start, I'm running Ubuntu 20.04 LTS. 
I know the repository is for windows but kindly look over the issue once. I'm not finding any solution anywhere.

![Screenshot from 2020-05-28 21-35-00](https://user-images.githubusercontent.com/33718703/83277511-cbff8e00-a1ef-11ea-862b-c042ed4af93a.png)

**Comment by grossmj** [comment]
How have you installed GNS3?

**Comment by C0d3-R3d** [comment]
> How have you installed GNS3?

via terminal 
sudo add-apt-repository ppa:gns3/ppa
sudo apt update                                
sudo apt install gns3-gui gns3-server

**Comment by C0d3-R3d** [comment]
Hey @grossmj Thanks for your support you have shown.
I found out the error why it was happening.
I'm attaching the screenshot where it was messed up or can say i messed up, since i don't check it at beginning .
 
![Screenshot from 2020-05-31 14-51-38](https://user-images.githubusercontent.com/33718703/83348945-52ca7d00-a34e-11ea-8bdb-35d704a9ad4b.png)

The ppa was somehow by default picked up on "eoan" & "beaver" instead of "focal".
I clean gns3 totally from my device and release the ppa and again put it and check it as if it is "focal" or not and reinstall everything like last time. And it worked totally fine.
Thanks man, for putting this in concern. 
I will keep doing normal tasks and see if anything new and suspicious error will get into my hand, And also it's resolution not on internet. I will put you in concern one more time.

I hope if someone somehow reach here and read the issue may be it will help them too.
Thanks.

**Comment by grossmj** [comment]
Perfect, thanks for posting the solution to your problem :+1:
