### ISSUE TITLE
Know images to work with GNS3

### ISSUE THREAD

**Issue by pythonyalfa** [GNS3/gns3-gui#2991]
I wanted to ask, if ok to ask here, if there is a list or site somewhere that lists what are the known images to work with GNS3. I use one site, but so far, I have only got a 3640 image work. The site im using has about 40 images to download but not all of them work. Thanks in advanced for your suggestions.

**Comment by grossmj** [comment]
Hi,

Here is a list of IOS images known to work with GNS3: https://docs.gns3.com/1-kBrTplBltp9P3P-AigoMzlDO-ISyL1h3bYpOl5Q8mQ/index.html

I personally like to use the c3745 and c7200 images.

**Comment by pythonyalfa** [comment]
Ok cool thanks. Why do you like those specific one? Any sites that show case why those are better? THanks again !

**Comment by grossmj** [comment]
These images, especially the c7200 support the most IOS features and also the c7200 is the only router (supported by Dynamips) that can run IOS 15.x images. There is this one c7200-adventerprisek9-mz.152-4.M8.bin but maybe you could find an even more recent one.

**Comment by AirDRoN-lab** [comment]
> There is this one c7200-adventerprisek9-mz.152-4.M8.bin but maybe you could find an even more recent one.
Hi, could you please share c7200-adventerprisek9-mz.152-4.M8.bin image (or c7200-advipservicesk9-mz.152-4.M8.bin)? It's realy difficult to find this image nowadays, unfortunately. Many thanks!

**Comment by Zorbatron** [comment]
@AirDRoN-lab Here is a site that seems to have just about every cIOS image ever: [https://cios.dhitechnical.com/](https://cios.dhitechnical.com/). I know I'm not allowed to share links like these on the GNS3 forums, but I'm not sure about GitHub. I'll delete this if you need my to, or an admin can probably delete it.
