### ISSUE TITLE
Dynamips error 

### ISSUE THREAD

**Issue by C0d3-R3d** [GNS3/gns3-gui#2992]
I don't know whether to say it bug or not. But i search on internet and many of the questions haven't answered yet, and those who have isn't working most of the answers don't make sense.

Whenever i start any router this is the error i found:-

Dynamips error when running command 'vm start "R1"
': unable to start VM instance 'R1'

**Comment by grossmj** [comment]
Make sure you use the latest IOS images supported by Dynamips. Please see https://github.com/GNS3/gns3-gui/issues/2991 for a list of images that work in GNS3.
