### ISSUE TITLE
GUI doesn't detect another GUI on macOS

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2994]
**Describe the bug**
On macOS the GUI doesn't detect another running GNS3 GUI. Therefore the second GUI kills the server of the first GUI.

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS 10.13.6
 - GNS3 version 2.2.8

**Additional context**
In macOS the process name of the GNS3 GUI is "Python" with an upercase P. In local_config.py line 495 the process name is checked for "gns3" and "python" (both lowercase), so it won't match.

Simple fix: Make the process name lower case
```
diff --git a/gns3/local_config.py b/gns3/local_config.py
index 8f63ea10..8b9da10c 100644
--- a/gns3/local_config.py
+++ b/gns3/local_config.py
@@ -488,7 +488,7 @@ class LocalConfig(QtCore.QObject):
                     if pid != my_pid:
                         try:
                             process = psutil.Process(pid=pid)
-                            ps_name = process.name()
+                            ps_name = process.name().lower()
                         except (OSError, psutil.NoSuchProcess, psutil.AccessDenied):
                             pass
                         else:
```

**Comment by grossmj** [comment]
Done. Thanks :+1:
