### ISSUE TITLE
Ubuntu 20.04 PPA pointing to 2.2.6 and not 2.2.8

### ISSUE THREAD

**Issue by m4shie** [GNS3/gns3-gui#2995]
The PPA for Ubuntu Focal (20.04) is pointing to GNS3 2.2.6 while the PPA for older Ubuntu versions are pointing to the correct version of GNS3 2.2.8.

**Comment by fre4ki** [comment]
It should be fine with 2.2.9.

**Comment by grossmj** [comment]
We will release version 2.2.9 soon.

**Comment by grossmj** [comment]
Packages for version 2.2.9 have just been released. Please give it a try and let me know if you have any problems.

https://launchpad.net/~gns3/+archive/ubuntu/ppa/+builds?build_text=&build_state=all

Thanks!

**Comment by PranavBhattarai** [comment]
A new milestone. Great.

**Comment by m4shie** [comment]
> Packages for version 2.2.9 have just been released. Please give it a try and let me know if you have any problems.
> 
> https://launchpad.net/~gns3/+archive/ubuntu/ppa/+builds?build_text=&build_state=all
> 
> Thanks!
2.2.9 installed ok but it can't be started on 20.04, it doesn't even have the knowledge of "gns3".

This is all I get:
mashie@X1Extreme:~$ gns3

Command 'gns3' not found, did you mean:

  command 'gbs3' from deb gambas3-script (3.14.3-2ubuntu3.1)

Try: sudo apt install <deb name>

mashie@X1Extreme:~$

No difference if I do it as root either.

**Comment by talha700** [comment]
installed gns3 2.2.9 on ubuntu 20.04 and gns3 is no where to be found lol

**Comment by fre4ki** [comment]
Don't know why noone is testing it. And after that - why will the build will not be dropped - my report was a few minutes after publishing. Everyone broke his installation now. 

Maybe "build from source" is a alternative..?

**Comment by brentstewart** [comment]
Good and bad news.  Mostly good.  I'm running Ubuntu Mate (Cinnamon) 20.04 and I was getting 2.2.6 yesterday.  Messed with dependencies, gave up and went to bed.

Bad - Got 2.2.9 today and there's no icon in the menu (per fre4ki)
Good - I found the installation (run /usr/share/bin/gns3) and tested and it's working fine now.  I installed and built the menu item using the icon at /usr/share/icons/hicolor/scalable/apps/gns3.svg.  Upgraded my server to 2.2.9 and I'm back in business!
![image](https://user-images.githubusercontent.com/4146647/83816109-ac54e380-a68f-11ea-9030-e592076a7de8.png)

Thanks for everything y'all are doing!

**Comment by PranavBhattarai** [comment]
@brentstewart How did u create **gns3.svg**? I really want to know. 
And thanks for your info_(although there are other problems like "Could not start local server process: /usr/bin/gns3server", "Could not find local server /user/bin/gns3server", all install IOU devices gone, etc)._

**Comment by lestercheung** [comment]
With the 2.2.9 build the symlinks in /usr/bin points to nowhere:
> $ ll  gns*
> lrwxrwxrwx 1 root root 31 Jun  4 18:20 gns3 -> ../share/gns3/gns3-gui/bin/gns3
> lrwxrwxrwx 1 root root 40 Jun  4 18:20 gns3server -> ../share/gns3/gns3-server/bin/gns3server
> lrwxrwxrwx 1 root root 39 Jun  4 18:20 gns3vmnet -> ../share/gns3/gns3-server/bin/gns3vmnet

I pointed them to the following instead:
> ../share/bin/gns3
> ../share/bin/gns3server 
> ../share/bin/gns3vmnet 

But I ended up with the following when the gui starts the local server:

> 2020-06-05 13:34:11 INFO root:126 Log level: INFO
> 2020-06-05 13:34:11 INFO main:256 GNS3 GUI version 2.2.9
> 2020-06-05 13:34:11 INFO main:257 Copyright (c) 2007-2020 GNS3 Technologies Inc.
> 2020-06-05 13:34:11 INFO main:259 Application started with /usr/bin/gns3
> 2020-06-05 13:34:17 ERROR local_server:496 Local server process has stopped
> 2020-06-05 13:34:17 ERROR local_server:498 Traceback (most recent call last):
>   File "/usr/bin/gns3server", line 11, in <module>
>     load_entry_point('gns3-server==2.2.9', 'console_scripts', 'gns3server')()
>   File "/usr/lib/python3/dist-packages/gns3server/main.py", line 82, in main
>     from gns3server.run import run
>   File "/usr/lib/python3/dist-packages/gns3server/run.py", line 32, in <module>
>     from gns3server.web.web_server import WebServer
>   File "/usr/lib/python3/dist-packages/gns3server/web/web_server.py", line 45, in <module>
>     import gns3server.handlers
>   File "/usr/lib/python3/dist-packages/gns3server/handlers/__init__.py", line 22, in <module>
>     from gns3server.handlers.api.compute import *
>   File "/usr/lib/python3/dist-packages/gns3server/handlers/api/compute/__init__.py", line 29, in <module>
>     from .server_handler import ServerHandler
>   File "/usr/lib/python3/dist-packages/gns3server/handlers/api/compute/server_handler.py", line 29, in <module>
>     from psutil._common import bytes2human
> ImportError: cannot import name 'bytes2human' from 'psutil._common' (/usr/lib/python3/dist-packages/psutil/_common.py)

**Comment by grossmj** [comment]
@lestercheung we are working on this issue. Another build is coming we should fix the symlinks issues and the ImportError.

**Comment by lestercheung** [comment]
> @lestercheung we are working on this issue. Another build is coming we should fix the symlinks issues and the ImportError.

Thanks @grossmj ! Didn't expect to have a response just minutes (seconds?) after I posted - you guys are amazing. Keep up with the good work!

**Comment by grossmj** [comment]
We have published a new packages (gns3-gui-2.2.9~focal10 & gns3-server-2.2.9~focal10). I tested in a Docker container and everything seems to work as expected this time. Please try and let me know if this work for you.

**Comment by lestercheung** [comment]
> We have published new packages (`gns3-gui-2.2.9~focal10` & `gns3-server-2.2.9~focal10`). I tested in a Docker container and everything seems to work as expected this time. Please try and let me know if this works for you.

Yup that works - appreicate the quick turnaround Jeremy!

**Comment by fre4ki** [comment]
Good morning. I changed the path to gns3server in my service-file and mine is running too.

![gns3-service](https://user-images.githubusercontent.com/62788741/83843648-c16c5980-a705-11ea-816f-8e9dfc66d650.png)

**Comment by m4shie** [comment]
Thanks @grossmj, it is all working now.

**Comment by grossmj** [comment]
Perfect, just for info we may have a chance the use dh-virtualenv again to create the packages for Ubuntu 20.04 LTS: https://github.com/GNS3/gns3-server/issues/1746

Using dh-virtualenv is a better solution.
