### ISSUE TITLE
Web UI fails to open

### ISSUE THREAD

**Issue by smart2128** [GNS3/gns3-gui#2996]
**Describe the bug**
Web UI fails to open

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux
 - GNS3 version 2.2.9
 - GNS3 on Archlinux on bare metal

**To Reproduce**
1. Go to `Tools` menu
2. Click on `Web UI - beta`
3. Error dialog appears

**Screenshots or videos**
![Screenshot_20200604_175817](https://user-images.githubusercontent.com/16859/83780073-fb4d4980-a68c-11ea-8116-f011bdad3c64.png)

**Comment by grossmj** [comment]
How have you installed GNS3?

**Comment by cioby23** [comment]
@smart2128 I'm using same setup as you GNS3 2.2.9 running on Archlinux bare metal and the WebUI starts fine. The only difference is that GNS3 server is listening on port 8080 on my PC instead of 3080.
For installation I'm using the package provided in the AUR repository https://aur.archlinux.org/packages/gns3-gui/

**Comment by smart2128** [comment]
@grossmj Yes, I installed both gns3-server and gns3-gui from AUR.
@cioby23 Thank you for your feedback. I'll do further tests. As I just wrote to Jeremy I also used AUR packages.

Thank you both.

**Comment by smart2128** [comment]
I tried starting gns3-server on a different port. The server starts as expected, but I get the same error message.

**Comment by cioby23** [comment]
If you try to open that link directly in the browser does it work ?

**Comment by smart2128** [comment]
@cioby23 Yes, it works. Looking at the screenshot I attached to the bug report. I noticed that error has been reported by KIO client.
So, I closed my previous Plasma session and restarted a new one, probably some plasma packages has been updated in the last few days.
Now, Web UI starts also invoking it from Tools menu.
Thank you very much for your support.

Vincenzo
