### ISSUE TITLE
GNS3 Virtualbox VM upgrade via menu option fails

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#2998]
**Describe the bug**
Please provide a clear and detailed description of what the bug is.
GNS3 Virtualbox VM upgrade via menu option fails.

**GNS3 version and operating system (please complete the following information):**
 - OS: Window 10 Pro
 - Virtualbox 6.1.10
 - GNS3 version 2.2.9 and GNS3 Virtualbox Image from 2.2.9 release

**To Reproduce**
1. Download GNS3 Virtualbox image and unzip
2. Start Virtualbox and open the GNS3.ova
3. Edit settings as required, e.g., Enable Nested VT-x/AMD V, increase memory, etc.
4. Start VM
5. From the onscreen menu select Upgrade the GNS3 VM
6. Select Release 2.2.9

**Screenshots or videos**
![gns3-2 2 9-virtualboxupgradefail](https://user-images.githubusercontent.com/10285348/84320901-604ae880-ab40-11ea-9107-75065b9af837.png)

**Comment by grossmj** [comment]
According the the screenshot, it seems that the Ubuntu package repository is temporally unavailable (invalid for another 2h 32min 24s etc.)... Strange, I would not expect this from Ubuntu. Please try again since I assume it should work now.

**Comment by jtorri** [comment]
Yes. That was my thought as well. However, the result is the same no matter how many times I try.  The only change is in the value of time (hours, minutes, seconds) following "...is not valid yet...".   Does the upgrade work successfully for you?

**Comment by grossmj** [comment]
> Does the upgrade work successfully for you?

Yes, the upgrade works without any problem. Very strange.

**Comment by jtorri** [comment]
In that case, I suggest closing this bug report.  I've been trying out Virtualbox VM because it has worked more consistently than the VMware VM for me using the latest versions of GNS3.  However, both require I restart my workstation ethernet adapter prior to starting GNS3 otherwise eth2 does not obtain an IP (eth0 host-only, eth1 NAT, eth2 bridged.  Best I can tell this is related to ethernet adapter issues in Windows 10 1909 described in multiple places on the internet.  Obviously, I have no idea what is causing the Virtualbox VM version upgrade failure but the GNS3 application and Virtualbox VM work fine. I was running the upgrade solely to have a value display in PORT on the Virtualbox VM information window. 
As always, thanks!
