### ISSUE TITLE
Impossible to import Pfsense appliance

### ISSUE THREAD

**Issue by stefan4577** [GNS3/gns3-gui#3001]
- OS: Windows 10 Pro
 - GNS3 version 2.2.9
 - GNS 3 VM Run to VMWARE Workstation

I community and developpers, 
Is it impossible for me to import a Pfsense appliance... 

GNS3 ask me to import a pfsense version 2.4.4 but the current version is 2.4.5. So i download the new version of psense and the install in the GNS3 is complete but when i want to drag and drop the pfsense router, i have an error: "Error while creating node from template: POST /projects/4427112e-0f03-4636-921f-80e8f06ad533/qemu/nodes not found"

Can you help me about this problem? 
You can see that on the capture attached.
Thank you for your response

![Capture](https://user-images.githubusercontent.com/67011731/84790295-7ac60b80-aff1-11ea-8701-d333b7636c7d.PNG)

**Comment by grossmj** [comment]
I have added Pfsense 2.4.5-p1. Please try with the next release to see if you still have the same issue.

**Comment by grossmj** [comment]
Version 2.2.10 has been released. Please test and let me know if the Pfsense appliance works as you expect.

**Comment by stefan4577** [comment]
Hi !
The problem is fix.
To solve it I had to restart my computer entirely
Thank you for your assist

--
Stéphane NONNET
0647070226

De : Jeremy Grossmann <notifications@github.com>
Répondre à : GNS3/gns3-gui <reply@reply.github.com>
Date : mardi 23 juin 2020 à 14:21
À : GNS3/gns3-gui <gns3-gui@noreply.github.com>
Cc : stefan4577 <stephane.nonnet@outlook.fr>, Author <author@noreply.github.com>
Objet : Re: [GNS3/gns3-gui] Impossible to import Pfsense appliance (#3001)


Version 2.2.10 has been released. Please test and let me know if the Pfsense appliance works as you expect.
