### ISSUE TITLE
Create New Version doesn't take the customer image or IOS number  

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3002]
hi 
Create new Version Does not taking the new IOS or image number its always take the latest image number as defined in the GNS3 application (windows).for example i upload ASAv 9.13 series ios but its only showing the latest image number available in gns3 .also asav 9.14 is not running .pls chcek 

![Capture-2](https://user-images.githubusercontent.com/11521667/85225894-e47b5680-b3f1-11ea-8e91-6c1fe5459cbf.PNG)
![Gns3 Issues](https://user-images.githubusercontent.com/11521667/85225897-e5ac8380-b3f1-11ea-8e26-803ab28691db.PNG)

**Comment by jnatschev** [comment]
i found a different way of achieving what you're after for a cisco csr1000v.
1. made a copy of the "appliance" file "cisco-csr1000v.gns3a" named "cisco-csr1000v-jn.gns3".
2. edited the file following the existing format. the version i added was "csr1000v-universalk9.17.02.01r-serial.qcow2".
3. start gns3 and didn't create a new project and didn't open a project
3. imported the appliance file named ""cisco-csr1000v-jn.gns3"
4. now created a new project
5. add new cisco csr1000v 17.2.1.r into topology
6. started cisco csr1000v 17.2.1r
7. telnet to cisco csr1000v 17.2.1r
8. job done
i've attached a copy of the appliance file i created as .txt
[cisco-csr1000v-jn.gns3a.txt](https://github.com/GNS3/gns3-gui/files/4824709/cisco-csr1000v-jn.gns3a.txt)

**Comment by grossmj** [comment]
This should work starting with GNS3 version 2.2.14

**Comment by aksplease** [comment]
Thank You Jeremy

Now i can add costume images perfectly fine
