### ISSUE TITLE
GNS3 VM KVM at GNS3-GUI 2.2.5

### ISSUE THREAD

**Issue by LiRa-C** [GNS3/gns3-gui#3004]
Hello

I was wondering if there is any way to integrate GNS3 VM KVM with GNS3-GUI interface. I am using GSN3 2.2.5, in the menu to choose VM for the server, only Virtualbox and VMware options are available. With the script provided here, I have been able to run GNS3 VM KVM but I don't know how to bind it to GNS3-GUI.

I have looked for information in the GNS3 forums, but there is only the procedure for VMware. My host operating system is Linux Mint 19.3 (based on ubuntu 18.04 lts).
Thank you!!

**Comment by jtorri** [comment]
There is a very real possibility I don't understand your question but, here goes. GNS3 runs locally on Linuxmint.  No need for a GNS3 VM.  The instructions for installing on Ubuntu-based distributions (64-bit only) are at:
https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html
It will install the latest version of GNS3.  
Later on when a newer version of GNS3 is published merely run apt upgrade to obtain it.

**Comment by grossmj** [comment]
> I was wondering if there is any way to integrate GNS3 VM KVM with GNS3-GUI interface

We could do this I guess. A GNS3 VM KVM was requested by some advanced users but we don't really offer support for it. The way you can use it in the GUI is just to configure a GNS3 VM as a remote server and to manually start the VM yourself.

**Comment by LiRa-C** [comment]
> > I was wondering if there is any way to integrate GNS3 VM KVM with GNS3-GUI interface
> 
> We could do this I guess. A GNS3 VM KVM was requested by some advanced users but we don't really offer support for it. The way you can use it in the GUI is just to configure a GNS3 VM as a remote server and to manually start the VM yourself.

Thank you very much!!!
That was exactly the question I had, thanks for the solution !!!. I hope that if you consider it a good idea, in the future, it can be integrated at the GNS3 interface.

Regards!
