### ISSUE TITLE
Short description of the feature request

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#3006]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
When selecting a node I would like to see its configuration in the docking area instead of having to right click, select configuration and showing it overlapping with the diagram
I hope this picture is clear

![picture](https://i.imgur.com/u5FsSW2.png)

**Comment by grossmj** [comment]
Indeed, we could have something like this however we will be focusing on the web-ui and a new back-end in the short to medium terms.
