### ISSUE TITLE
settings (preferences) option to enable/disable the display of the "project" window at gns3 startup

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-gui#3008]
**Before you start**
Please check if a similar feature request has already been submitted.

You may also post this issue directly on the GNS3 server repository if you know the feature request only applies to the server: https://github.com/GNS3/gns3-server/issues/new

**Is your feature request related to a problem? Please describe.**
sort of. #3007

**Describe the solution you'd like**
add a checkbox to "settings (preferences) -> general -> miscellaneous" to enable/disable "project" window at startup 

**Describe alternatives you've considered**
when gns3 is started and the "project" window is displayed, click cancel and navigate gns3 from native window.

**Additional context**
i, for one, am more than happy to just get the native gns3 window at startup and navigate my way around from there rather than having the "project" window displayed to select a recent project, create a new project, go to settings, etc.

**Comment by b-ehlers** [comment]
I don't see any advantage, when this gets implemented. When you prefer to use the file browser to open a project you can use the "Open a project from disk" button in the Project dialog. That's just one click.

GNS3 has already too much options (IMHO), I don't like adding more options without a strong advantage.

**Comment by grossmj** [comment]
> GNS3 has already too much options (IMHO), I don't like adding more options without a strong advantage.

I agree, we should aim to simplify things, not increase the complexity of GNS3.

**Comment by jnatschev** [comment]
thanks for considering anyway. all good.
