### ISSUE TITLE
GNS3 GUI fails to open due to missing sip module

### ISSUE THREAD

**Issue by ederollora** [GNS3/gns3-gui#3013]
Not possible to open GNS3 GUI after upgrading. Complains about "Fail update installation: No module named 'sip'" and "Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...". Tried to follow some of the similar problems I found from past users but could not fix it. 

- OS: Lubuntu 16.04
- GNS3 version: 2.2.5
- Installed in Lubuntu 16 server, not a VM.

Upgrading using pip prevents GNS3 GUI from opening. 

Steps:

sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.6 python3.6-dev python3.6-venv
sudo python3.6 -m ensurepip --upgrade
sudo python3.6 -m pip install gns3-server==2.2.5
sudo python3.6 -m pip install gns3-gui==2.2.5

user@machine:~$ gns3
Fail update installation: No module named 'sip'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...

PD: Sorry for the mistaken title

**Comment by ederollora** [comment]
Happens the same for later versions so I think the problem is still related to PyQt but I cannot figure out how to fix it.

**Comment by ederollora** [comment]
Doing this as stated for solution in a similar problem: 

virtualenv -p python3.6 /home/user/GNS3
source /home/user/GNS3/bin/activate
pip3 install -U gns3-gui gns3-server PyQt5-sip

Brings another error:
(GNS3) user@machine:~$ gns3
Fail update installation: cannot import name 'QtCore'
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly...

**Comment by ederollora** [comment]
Seems like I fixed it running these commands (I run quite many solutions so I might miss something). I fixed it both in the virtualenv and out so:

pip3 install -U gns3-gui gns3-server PyQt5-sip
pip3 install pyqt5==5.14.0

**Comment by shrutikaponde** [comment]
> Seems like I fixed it running these commands (I run quite many solutions so I might miss something). I fixed it both in the virtualenv and out so:
> 
> pip3 install -U gns3-gui gns3-server PyQt5-sip
> pip3 install pyqt5==5.14.0

Thanks !! I have tried this inside the virtual environment, solved my Issue!
