### ISSUE TITLE
Leftover dynamips processes when project name contains a space character

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3015]
**Describe the bug**
When I create a project with a name containing a space, the dynamips process doesn't stop, when the project gets closed. I didn't notice this issue with qemu processes. I assume this happens only with dynamips processes running locally, as the directory names for projects on remote server don't contain space characters.

Besides this leftover process and some oddities mentioned in the "Additional context" section, the node is working fine.

**GNS3 version and operating system:**
 - macOS 10.13.6 High Sierra
 - GNS3 version 2.2.10
 - Only local server used, no GNS3 VM

**To Reproduce**
1. Create a new project named "test abc"
2. Add a dynamips VM
3. Start it, verify that it works, stop it
4. Close process by either loading a new project or alternatively exiting GNS3
5. Check process table for leftover dynamips processes

```
/Users/behlers# ps ax | grep dynamips
 1222   ??  S      0:06.61 /Applications/Lokal/GNS3.app/Contents/MacOS/dynamips
```

**Additional context**
Besides this leftover process I noticed the following:

A warning in gns3_sever.log, this doesn't happen with projects with "regular" names:
```
2020-07-08 10:19:29 WARNING __init__.py:430 Could not create ghost instance: Dynamips error when running command 'vm set_ghost_file "Ghost" '/Users/behlers/GNS3/projects/test abc/project-files/dynamips/c3725-adventerprisek9-mz.124-25d.image-128.ghost'
': Bad number of parameters (3 with min/max=2/2)
```

Even though I created only one node, the project directory contains two node uuids. One of them contains only an empty config directory.

```
/Users/behlers/GNS3/projects# ls test\ abc/project-files/dynamips/
77288a1b-da47-4a17-9263-8c250405b3ed/	9d2c2ca3-46ce-4750-b2f5-3dfe62732ace/
```

When adding more than one dynamips node, stopping all nodes takes some time, while normally stopping all nodes is an almost instant operation.

**Comment by b-ehlers** [comment]
Workaround is to disable ghost support.

![disable_ghost_support](https://user-images.githubusercontent.com/49040325/86908574-06294d00-c117-11ea-825b-85f51bc4f5ac.png)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/1cbed45f16f6408c12c328d6cf5cde8df952badb

Thanks! :+1:
