### ISSUE TITLE
Key Error vendor_id on GNS 2.2.11 with virtual box

### ISSUE THREAD

**Issue by AdamMahiou** [GNS3/gns3-gui#3017]
**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 - version 1909
 - GNS3 version  2.2.11
 - VM on local host - virtual box 6.1.10

**To Reproduce**
Preferences -> GNS3 VM -> Virtual Box as the virtualization engine -> press refresh

![image](https://user-images.githubusercontent.com/68087284/87100098-c6b04d00-c24b-11ea-8394-b0e165ffe222.png)

**Comment by grossmj** [comment]
That's strange. What CPU do you have?

Please check by launching regedit.exe and type the following path:

`Computer\HKEY_LOCAL_MACHINE\Hardware\Description\System\CentralProcessor\0`

![Screenshot from 2020-07-10 16-08-13](https://user-images.githubusercontent.com/4752614/87124296-acb45000-c2c7-11ea-9729-7748f62a11a0.png)

Thanks.

**Comment by medharrak** [comment]
Hi,
Same issue I have with Ubuntu 18.04

**Comment by grossmj** [comment]
@medharrak can you try the following?

```
sudo python3 -m pip install py-cpuinfo==6.0.0
python3 -m cpuinfo
```

Thanks.

**Comment by medharrak** [comment]
done
$ python3 -m cpuinfo
Python Version: 3.8.2.final.0 (64 bit)
Cpuinfo Version: 6.0.0
Vendor ID Raw: GenuineIntel
Hardware Raw: 
Brand Raw: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Hz Advertised Friendly: 1.8000 GHz
Hz Actual Friendly: 2.8436 GHz
Hz Advertised: (1800000000, 0)
Hz Actual: (2843576000, 0)
Arch: X86_64
Bits: 64
Count: 8
Arch String Raw: x86_64
L1 Data Cache Size: 128 KiB
L1 Instruction Cache Size: 128 KiB
L2 Cache Size: 1 MiB
L2 Cache Line Size: 256
L2 Cache Associativity: 0x6
L3 Cache Size: 8192 KB
Stepping: 10
Model: 142
Family: 6
Processor Type: 
Extended Model: 8
Extended Family: 
Flags: 3dnowprefetch, abm, acpi, adx, aes, aperfmperf, apic, arat, arch_perfmon, art, avx, avx2, bmi1, bmi2, bts, clflush, clflushopt, cmov, constant_tsc, cpuid, cpuid_fault, cx16, cx8, de, ds_cpl, dtes64, dtherm, dts, epb, ept, ept_ad, erms, est, f16c, flexpriority, flush_l1d, fma, fpu, fsgsbase, fxsr, ht, hwp, hwp_act_window, hwp_epp, hwp_notify, ibpb, ibrs, ida, intel_pt, invpcid, invpcid_single, lahf_lm, lm, mca, mce, md_clear, mmx, monitor, movbe, mpx, msr, mtrr, nonstop_tsc, nopl, nx, osxsave, pae, pat, pbe, pcid, pclmulqdq, pdcm, pdpe1gb, pebs, pge, pln, pni, popcnt, pse, pse36, pti, pts, rdrand, rdrnd, rdseed, rdtscp, rep_good, sdbg, sep, sgx, smap, smep, ss, ssbd, sse, sse2, sse4_1, sse4_2, ssse3, stibp, syscall, tm, tm2, tpr_shadow, tsc, tsc_adjust, tsc_deadline_timer, tscdeadline, vme, vmx, vnmi, vpid, x2apic, xgetbv1, xsave, xsavec, xsaveopt, xsaves, xtopology, xtpr

**Comment by grossmj** [comment]
@medharrak thanks, I found the problem. It is the same on both Windows and Linux so I will close this issue and focus on https://github.com/GNS3/gns3-gui/issues/3018
