### ISSUE TITLE
Error while getting compute list: Connection refused (localhost:3080)

### ISSUE THREAD

**Issue by vlotho** [GNS3/gns3-gui#3019]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

unable to post a message on the community forum, whether with the brave browser or firefox.

**Describe the bug**

After updating to version 2.2.11, GNS3 no longer seems to want to connect to the server.
GNS3 displays errors:
Websocket notification stream error: Unknown error
Websocket notification stream error: Out of resources
These errors appear directly after launching GNS3.

I tried to deactivate the server, restart GNS3 and reactivate it but the error is displayed all the time.
there is also no residual deamon running.
I also updated the gns3 vm.

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux Debian Bullseye/sid
 - GNS3 2.2.11

**To Reproduce**

start gns3

**Screenshots or videos**
![Capture d’écran du 2020-07-11 10-23-16](https://user-images.githubusercontent.com/6847623/87220761-29e2d200-c367-11ea-82a2-cf0fb40ad881.png)

![Capture d’écran du 2020-07-11 14-24-10](https://user-images.githubusercontent.com/6847623/87224048-4cceaf80-c382-11ea-8f4b-bad15d4babb0.png)

**Additional context**

[gns3debug.zip](https://github.com/GNS3/gns3-gui/files/4906534/gns3debug.zip)

no firewall configured on the workstation.
version 2.2.9 worked without problems.
why am i updating gns3 with the new version, if the old one worked before?
because, normally, the more up to date a linux system is, the better it is bug free, and the better it is protected.

**Comment by TribuneX** [comment]
Same for me on macOS 10.15.5.

**Comment by grossmj** [comment]
This has been fixed in https://github.com/GNS3/gns3-gui/issues/3018
