### ISSUE TITLE
Wireshark error "End of file on pipe magic during open"

### ISSUE THREAD

**Issue by biggena** [GNS3/gns3-gui#3021]
While starting capture Wireshark throws error:
![image](https://user-images.githubusercontent.com/40003342/87253264-8edf1a80-c482-11ea-98da-27c2c9791e90.png)

My capture settings are standard:
tail.exe -f -c +0b %c | "C:\Program Files\Wireshark\wireshark.exe" -o "gui.window_title:%d" -k -i -

I tried to start tail.exe and all this command from cmd, referencing capture file name, it works. But from GNS3 tail.exe doesn't start, I see no such process in task manager after starting capture.

This error is present in 2.2.10-2.2.11, also I tried different wireshark versions, looks like the problem is in tail.exe sequence which doesn't start properly.
Windows is 10 Pro:
![image](https://user-images.githubusercontent.com/40003342/87253460-137e6880-c484-11ea-8054-d10837e034fb.png)
Tried to use Vmware Workstation or Vmware Player, it makes no difference, error is the same.
Are there any ways to troubleshoot this?

**Comment by biggena** [comment]
Solved this! 
Tried to change places of tail and wireshark in capture settings.
Placed wireshark at first place, then | and tail.exe with arguments and noticed that wireshark starts, but no tail.exe.
Deleted %c and noticed that tail.exe also stays in task manager.
%c is capture file name with full path. I supposed that cyrillic letters in my account name weren't passed properly, 
I changed account name among with home folder name to latin in Windows, also changed home folder in gns3_server.ini.
After this live capture started like a charm!

Please check what is broken with passing cyrillic %c to tail.exe, it was working in GNS3 some time ago.
Also it works with cyrillic if manually start in CMD.EXE capture string, for example:
CMD>tail.exe -f -c +0b C:\Users\тест\R1_Ethernet00_to_R2_Ethernet00.pcap  | "C:\Program Files\Wireshark\wireshark.exe" -k -i -

**Comment by grossmj** [comment]
I think this is because tail.exe uses Cygwin DLL which doesn't support UTF-8 (at least in the version we ship).

**Comment by adimu87** [comment]
Hi biggena ,
i faced the sane problem.
Did the things as you described above.
The error during opening of  wireshark is gone.
But now there is no catched traffic on interface between devices ni gns3.
Can you advices something ?

**Comment by biggena** [comment]
@adimu87 Hello.
I haven't faced such issue. Traffic was present.
If you have at least one unshut interface in GNS you have to see CDP messages on link.
Check if you have proper IOU license present and routers are able to start.

**Comment by adimu87** [comment]
> @adimu87 Hello.
> I haven't faced such issue. Traffic was present.
> If you have at least one unshut interface in GNS you have to see CDP messages on link.
> Check if you have proper IOU license present and routers are able to start.

Yes, i have the license. Without it IOU devices will not start in gns. I changed the name of folders to latin from cyril and deleted %c. After then I have not issue in opening wireshark. But there in no traffic.

**Comment by manh57** [comment]
tôi chỉ muốn nói là do lỗi tên file đó các bạn ạ :((((.I just wanted to say that the filename is wrong guys :(

**Comment by grossmj** [comment]
@manh57 what filename?

**Comment by jj458** [comment]
I think, i found a reason:
My windows username "Maximilian Müller" contains special characters.

GNS3 calls
`C:\Program Files\GNS3\tail.exe" -f -c +0b "C:/Users/Maximilian Müller/AppData/Local/Temp/GNS3.bwujTl"`

The cygwin tail cannot open this file. When i try this command in CMD i get an error.
`/GNS3/tail: cannot open "C:/Users/Maximilan Müller/AppData/Local/Temp/GNS3.bwujTl" for reading: No such file or directory`

With an 8.3 filename, tail is working, for example `"C:\Program Files\GNS3\tail.exe" -v -f -c +0b "C:/Users/MAXIMI~1/AppData/Local/Temp/GNS3.bwujTl"`

I tried a newer version of tail from cygwin. In CMD ist works with the original filename, but GNS3 cant start it.

**Comment by grossmj** [comment]
Thanks for this 👍

**Comment by jj458** [comment]
Solved the Problem for me:
From Cygwin (9.0-1) i copied tail.exe and all dlls to GNS3\bin

This newer version of tail works withe non-ascii paths.

**Comment by grossmj** [comment]
I have added the latest Cygwin tail.exe and DLLs. Hopefully, this issue is solved now. Please test once we release version 2.2.45.
