### ISSUE TITLE
need to "Start" twice to un-suspend qemu VM

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3027]
Hi

On GNS3 master

- I have a running Qemu VM connected to ethernet switch.
- I suspend it with the button. I have the yellow indicator.
- I click on the "Start" button of the QEmu VM. The indicator stays yellow.
- I click on "Console", i have the message "This node must be started before...."
- I click again on the "Start" button. The indicator becomes green.
- The "Console" can be open.

**Comment by grossmj** [comment]
Fixed.
