### ISSUE TITLE
GNS3 VM timedatectl works in Vmware VM but not virtualbox VM

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#3028]
**Describe the bug**
cli command timedatectl does not work correctly in Virtualbox GNS3 VM but does work find in Vmware Workstation GNS3 VM.
Obviously I am curious as to why.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 version 2004 OS Build 19041.388
 - GNS3 version 2.2.11
 - Virtualbox 6.1.12r13918 (Qt 5.6.2)

**To Reproduce**
1. Load GNS3 2.2.11 virtualbox VM
2. Configure appropriately 
3. Exit menu to command line
4. sudo timedatectl will show UTC timezone
5. sudo timedatectl set-timezone America/New_York fails with in valid timezone
6. Most other timedatectl commands fail

All timedatectl commands work fine in Vmware GNS3 VM 2.2.11

**Comment by jtorri** [comment]
Problem solved by existing menu to command line then sudo su then apt install ntp.  The installation and configuration of ntp allows me to set timezone to the correct value.  Now it is possible to run update.

**Comment by jtorri** [comment]
I continue to have this issue in GNS3 2.2.12 Virtualbox VM.  I am curious, am I the only one experiencing this issue? If so, would someone be kind enough to post a picture of your GNS3 2.2.12 Virtualbox VM configuration?   Thanks!

**Comment by grossmj** [comment]
@jtorri please let me know if you still have the problem with version 2.2.13

**Comment by jtorri** [comment]
Thanks for asking!  Unfortunately, the answer is the problem persist with GNS3 Virtualbox VM version 2.2.13.  Have not yet installed GNS3 2.2.13, merely loaded the Virtualbox VM 2.2.13 and tested for date/time issue.

Output after running menu option upgrade to 2.2.13 on the 2.2.13 Virtualbox VM just to see if upgrade worked.

![Upgrqade via menu GNS 2 2 13 WITH VirtualBox6 1](https://user-images.githubusercontent.com/10285348/92310233-5cc9d080-ef7a-11ea-9d20-3341b09f6b49.png)
 
Output from timedatectl on GNS3 2.2.13 Virtualbox VM
![Timedateclt GNS 2 2 13 WITH VirtualBox6 1](https://user-images.githubusercontent.com/10285348/92310246-78cd7200-ef7a-11ea-8797-17bd7507317e.png)

Output from timedatectl on GNS3 2.2.12 (earlier version of GNS3)  VMware Workstation VM
![Timedatectl GNS 2 2 12 WITH VMwareWorkstation](https://user-images.githubusercontent.com/10285348/92310266-94d11380-ef7a-11ea-9709-e4748455f184.png)

Hope this helps.

**Comment by grossmj** [comment]
> Output after running menu option upgrade to 2.2.13 on the 2.2.13 Virtualbox VM just to see if upgrade worked.

I see the upgrade failed but I think this was due to Ubuntu repository (invalid for another 2h...) Can you try again please?

**Comment by jtorri** [comment]
Apparently I am not explaining this issue very well.  As I mentioned earlier I can only fix it by installing ntp and setting the time/date based on it.  Running update again without ntp installed and configured will not change the results for me.  None of this happens with the VMware VM.
Perhaps this link will help explain it.  Thanks!

https://blog.sleeplessbeastie.eu/2019/11/15/how-to-deal-with-repository-is-not-valid-yet-error/

**Comment by grossmj** [comment]
Thanks for the link. It makes more sense now.

There is definitely something strange going on. I install VirtualBox and launched the GNS3 VM (v2.2.13)

![Screenshot from 2020-09-07 06-18-20](https://user-images.githubusercontent.com/4752614/92335016-1091a400-f0d2-11ea-8102-52813d3c6290.png)

The system clock is synchronized and I can update the packages.

**Comment by jtorri** [comment]
Good to know! I suspect there is something, or somethings, I am doing differently than you when I create the GNS3 Virtualbox VM after uncompressing the GNS3 VirtualboxVM zip file. Would it be possible for you to list the specifics of how you are doing it?  If so, as much details as possible.  Thanks again.

**Comment by grossmj** [comment]
I just did a simple import virtual appliance in VirtualBox leaving everything by default.

![Screenshot from 2020-09-07 17-45-34](https://user-images.githubusercontent.com/4752614/92364284-02737000-f132-11ea-84f4-bf9ef6d90965.png)

**Comment by jtorri** [comment]
Well, I'm stuck.  Installing and configuring ntp fixes the issue for me and is easy enough.  BTW, if I install Ubuntu 18.04.4 x64 in Virtualbox the issue does not occur.  It seems I am the only one experiencing this issue so I suggest you just as well close it.  Thanks!

**Comment by grossmj** [comment]
@jtorri no worries :+1:
