### ISSUE TITLE
GNS3 not installing on python3.8

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-gui#3031]
Hi GNS3 Team

just saw another thread that states you added support for python3.8, getting below error installing in Linux.
The following packages have unmet dependencies:
 gns3-server : PreDepends: python3.4 but it is not installable or
                           python3.5 but it is not installable or
                           python3.6 but it is not installable or
                           python3.7 but it is not installable
               Recommends: dynamips but it is not going to be installed
               Recommends: x11vnc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

OS: Linux Debian stretch
Python: ver 3.8
Have tried to force dependency installation but did not work (apt-get install -f)

Regards

**Comment by grossmj** [comment]
How have you install Python3.8?

**Comment by leribe** [comment]
yes, that's correct
Python: 3.8.5 at the moment

**Comment by grossmj** [comment]
I think best would be to install GNS3 using pip. Have you tried this?

`sudo python3.8 -m pip install gns3-server`

The only problem is you will have to install dependencies manually (Dynamips, Qemu etc.).

**Comment by leribe** [comment]
Thanks, tried and was getting below error, installed dynamips ver: 0.2.18-1~xenial1 and qemu ver: 1:5.0-6, running on Linux Debian stretch.
**Dynamips Error**
=> Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605
**Qemu Error**
Sorry, no QEMU binary has been found. Please make sure QEMU is installed before continuing

**Comment by grossmj** [comment]
> Thanks, tried and was getting below error, installed dynamips ver: 0.2.18-1~xenial1 and qemu ver: 1:5.0-6, running on Linux Debian stretch.

I have answered on your issue regarding Dynamips/Qemu.

**Comment by grossmj** [comment]
Can you launch the gns3server after you installed it using pip?

**Comment by leribe** [comment]
used pip install gns3-server,gns3-gui and everything working
