### ISSUE TITLE
VMBoxManage command cannot enable nested vt-x/amd-v without nested-paging and unrestricted guest execution

### ISSUE THREAD

**Issue by my-ix** [GNS3/gns3-gui#3032]
Not able to install GNS3 2.2.12

Microsoft Windows 10 Professional
VirtualBox 6.1
GNS3 VM

Run appliance in virtual machine wizard result the following error:
Error while saving settings: GNS3VM: Error while executing VBoxManage command: VirtualBox has returned an error: VBoxManage.exe: error: Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution!
VBoxManage.exe: error:  (VERR_CPUM_INVALID_HWVIRT_CONFIG)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by jtorri** [comment]
Could this be a Virtualbox version issue?  The following works for me as of the morning.  I believe 6.1.2 is the latest Virtualbox release.

OS: Windows 10 version 2004 OS Build 19041.388
GNS3 version 2.2.12
Virtualbox 6.1.12r13918 (Qt 5.6.2)

I believe in earlier version of Virtualbox the error you describe was found and solved with the following.

https://dannyda.com/2020/03/10/how-to-enable-nested-vt-x-amd-v-force-enable-nested-vt-x-amd-v-in-oracle-vm-virtualbox/

**Comment by grossmj** [comment]
Maybe you are trying to run another virtualization software like VMware or Hyper-V?

**Comment by my-ix** [comment]
I am running the latest Virtualbox Version 6.1.12 r139181 (Qt5.6.2)

**Comment by my-ix** [comment]
> Could this be a Virtualbox version issue? The following works for me as of the morning. I believe 6.1.2 is the latest Virtualbox release.
> 
> OS: Windows 10 version 2004 OS Build 19041.388
> GNS3 version 2.2.12
> Virtualbox 6.1.12r13918 (Qt 5.6.2)
> 
> I believe in earlier version of Virtualbox the error you describe was found and solved with the following.
> 
> https://dannyda.com/2020/03/10/how-to-enable-nested-vt-x-amd-v-force-enable-nested-vt-x-amd-v-in-oracle-vm-virtualbox/

I am using Virtualbox Version 6.1.12 r139181 (Qt5.6.2) and I tried following the shared option, which gives the same error result.

**Comment by my-ix** [comment]
> Maybe you are trying to run another virtualization software like VMware or Hyper-V?

No I am not, I am running Virtualbox Version 6.1.12 r139181 (Qt5.6.2) on my Windows 10 Professional Version 2004 OS Build 19041.388 (Microsoft Windows NT 10.0.19041.0)

**Comment by my-ix** [comment]
Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution!
(VERR_CPUM_INVALID_HWVIRT_CONFIG).

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by jtorri** [comment]
Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox.  The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off

https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/

**Comment by AbhishekBhatP** [comment]
I faced issue regarding VT-x. But after enabling nested VT-x it gives error as shown in the pic
![Screenshot (1)](https://user-images.githubusercontent.com/48376316/89943835-79edd680-dc3c-11ea-9419-50905ebce4e9.png)
![Screenshot (2)](https://user-images.githubusercontent.com/48376316/89943840-7c503080-dc3c-11ea-9bcd-a0b9ce61fdf6.png)
![Screenshot (3)](https://user-images.githubusercontent.com/48376316/89943843-7e19f400-dc3c-11ea-9723-0a92beced420.png)

**Comment by my-ix** [comment]
> Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> 
> https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/

Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:

1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
2. turn off windows feature "Virtual Machine Platform"
3. reboot

**Comment by grossmj** [comment]
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link

Thank for the feedback! :+1:

**Comment by kyxap** [comment]
I was too lazy to run and read about unknown command (bcdedit) and somehow my issue resolved by disabling `Vt/Amd-v`...

**Comment by DavidAG2000** [comment]
> > Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> > The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> > https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/
> 
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:
> 
> 1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
> 2. turn off windows feature "Virtual Machine Platform"
> 3. reboot

It didn't work for me.

Instead, for me what it worked was disabling Vt/Amd-v... option in System settings.

**Comment by DavidAG2000** [comment]
> I was too lazy to run and read about unknown command (bcdedit) and somehow my issue resolved by disabling `Vt/Amd-v`...

It worked for me too!

**Comment by FilkerZero** [comment]
I didn't have Virtual Machine Platform enabled.  I have several VMs that stopped working after MS forced an update of my Windows 10 Pro system a few weeks back.

I believe that it is Microsoft's attempt to use the new execute permissions bits in later Intel processors getting in the way of foreign hypervisors.  Like others, I've had to disable VT/AMD-V in the VM settings, but now the VM is running at about 1/4 the speed it used to.  I think that the latest builds of Windows 10 is interfering with VB.  I doubt it is deliberate, and it's certainly not unprecedented, but it's unlikely that they will provide enough information for mortals like me to solve the problem.

**Comment by AbhimanyuAryan** [comment]
> > Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> > The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> > https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/
> 
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:
> 
> 1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
> 2. turn off windows feature "Virtual Machine Platform"
> 3. reboot

this worked with Windows 10 Dev VMs https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ for Oracle Virtual Box

**Comment by nemsys54** [comment]
1: run this at command prompt: bcdedit /set hypervisorlaunchtype off
2: turn off windows feature "Virtual Machine Platform"  <====== This was the key for me. I installed Docker and it enabled this.
3: reboot

**Comment by thecriticalpoint** [comment]
Sorry to hop in here without a whole lot of log files and the saga. I'm not going to be shy. I don't know what I'm doing. Everything is an entire area of specialization that could each be a career. It's asking too much for people to know everything about everything or assume they aren't doing due diligence. 

I have WSL running on windows 10 without issue but it doesn't have USB support so it's worthless to me.
I was running a 64but ubuntu VM on 6.1 + Extension pack without issues
Then wanted to check out Docker so I installed Docker Desktop and when I installed the Docker plugin in VSCode it promted me to install a WSL Kernel Module.

I think it's worth noting that this is when I got this same error discussed here. Immediately after I installed docker and the WSL Kernel update.

I don't know where to to look or who to ask about compatibility issues, coincidence may not be causation but then it might be why mine broke.

In any case it seems like I'm circling down a recursive rabbithole of workarounds and alternate virtualization methods and I'm starting to get a little unhinged.

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by cesarvarela** [comment]
Disabling the Virtual Machine Platform is not a solution, it's necessary for WSL to work.

**Comment by chincholikarsalil** [comment]
> I was too lazy to run and read about unknown command (bcdedit) and somehow my issue resolved by disabling `Vt/Amd-v`...

This Works the best

> Disabling the Virtual Machine Platform is not a solution, it's necessary for WSL to work.

Absolutely!

**Comment by tjpr87** [comment]
> I faced issue regarding VT-x. But after enabling nested VT-x it gives error as shown in the pic. Kindly help me regarding this issue.
> ![Screenshot (1)](https://user-images.githubusercontent.com/48376316/89943835-79edd680-dc3c-11ea-9419-50905ebce4e9.png)
> ![Screenshot (2)](https://user-images.githubusercontent.com/48376316/89943840-7c503080-dc3c-11ea-9bcd-a0b9ce61fdf6.png)
> ![Screenshot (3)](https://user-images.githubusercontent.com/48376316/89943843-7e19f400-dc3c-11ea-9723-0a92beced420.png)

it worked for me, thanks :)

**Comment by fhodun** [comment]
Disabling "Enable Nested VT-x/AMD-v" option worked for me.

**Comment by gtsteffaniak** [comment]
Disabling "Enable Nested VT-x/AMD-v" is a horrible solution. Because it disables the acceleration and makes the VM 10x slower.

**Comment by fhodun** [comment]
I confirm, I noticed it after starting the machine

> Disabling "Enable Nested VT-x/AMD-v" is a horrible solution. Because it disables the acceleration and makes the VM 10x slower.

I confirm, I noticed it after starting the machine

**Comment by RobFosterNYC** [comment]
> 
> 
> > I was too lazy to run and read about unknown command (bcdedit) and somehow my issue resolved by disabling `Vt/Amd-v`...
> 
> It has worked for me too!

I just ran into this problem today 05-16-2021
And oddly disabling VTx/AMD-v  actually works, even today in 2021.
Using Windows 10 and GNS3 v2.2.21 with VBox v6.1.22 r 144080 (Qt5.6.2)

**Comment by gtsteffaniak** [comment]
Yes it works, but with massive penalty in performance.

**Comment by eantowne** [comment]
No, disabling virtualization capabilities is not an effective strategy. Conversely, stating that disabling MS Hyper-v capabilities to run GNS3 VM correctly in Virtualbox is unacceptable because "WSL" is not fair either. As a side note this is not an issue related to the GUI, it is more accurately related to [GNS3 VM](https://github.com/GNS3/gns3-vm), even if there is NOTHING the GNS3 developers can do about it. This issue is caused by MS and other hypervisor software companies.

There are a couple of opportunities for compromise.

1. If you are running Windows 10 Pro, why not use MS Hyper-V to run the GNS3 VM? [GNS3 VM Download List](https://www.gns3.com/software/download-vm)
2. If you are not running Windows 10 Pro, use Virtualbox to run a full VM of Linux instead of WSL, allowing GNS3 VM to run correctly

**Comment by antdude** [comment]
Disable Vt/AMD-V nested option in System Settings fixed my 64-bit W10 Pro VM, but dang it sure makes it a lot slower. I do use W10 Pro's Sandbox. Argh. :(

**Comment by AlejAlvarez** [comment]
> > Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> > The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> > https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/
> 
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:
> 
> 1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
> 2. turn off windows feature "Virtual Machine Platform"
> 3. reboot

This Worked for me like a charm! Thank you!

**Comment by Kosinkiewicz** [comment]
I have the same error if "core isolation" in Windows 10 is turn on  and  "Enable Nested VT-x/AMD-V" in VirtualBox  is turn on.
How to do make turn on both? Is it possible?

**Comment by Kosinkiewicz** [comment]
Just I have found the anwser for my questions - look at this link [https://www.howtogeek.com/357757/what-are-core-isolation-and-memory-integrity-in-windows-10/](www.howtogeek.com)

**Comment by sayedfarhanali** [comment]
> > Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> > The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> > https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/
> 
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:
> 
> 1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
> 2. turn off windows feature "Virtual Machine Platform"
> 3. reboot

This worked for me.

Virtual Box ver 6.1.18
Windows 10 build 19042.1110

**Comment by jayeshmann** [comment]
Any other method to make this work without disabling Hyper-V, WSL requires Hyper-V as well and then that breaks.

**Comment by caevv** [comment]
How is this close if still an issue?

**Comment by grossmj** [comment]
@caevv this isn't an issue in GNS3

**Comment by ketansiddhapura** [comment]
Indeed it did worked.

I was trying to install openshift Code ready container (CRC) and it was throwing Error Enable virtualization in BIOS, even though it is enabled.

Key: please restart after below steps

My case what I did was

I am having Windows 10 where I Installed VirtualBox and installed centos8

1.)Shutdown (Guest) OS running inside VirtualBox
2.) Run CMD with admin privileges'  
Go to Virtualbox location -->cd  C:\Program Files\Oracle\VirtualBox 
        
VBoxManage modifyvm Name_of_your_VM --nested-hw-virt on 

3.) Search for "Windows features on or off" 
make sure unchecked all the shown in image
https://imgur.com/a/lzzDqrx

4.)  Run CMD with admin privileges' and run below command
bcdedit /set hypervisorlaunchtype off

5) restart the computer or laptop

**Comment by Avamander** [comment]
If you have both Hyper-V and Windows Hypervisor Platform installed, you just have to disable nested virtualization on the specific VM's you're trying to run in Virtualbox.

**Comment by Bessonov** [comment]
For me it was a glitch in Windows and in VirtualBox. I've never enabled Hyper-V nor Windows Hypervision Platform. But VirtualBox still showed a turtle even everything looks fine. Of course, the tooltip showed that VT-x isn't enabled.

Following steps worked for me:
1. Enable Windows Hypervision Platform
2. Reboot
3. Disable Windows Hypervision Platform
4. Reboot
5. Run in cmd.exe (even VirtualBox shows that the features already enabled, it could not start without it):
```
VBoxManage modifyvm dev-vm --nested-hw-virt on
VBoxManage modifyvm dev-vm --vtxux on
```

**Comment by awensiscc** [comment]
> > Likely you have already found it but there is a post from a year or so ago referencing the same or at least a very similar error. It occurred after someone had installed hyper-v then tried to disable hyper-v and later installed virtualbox. The error they received was "Cannot enable nested VT-x/AMD-V without nested-paging and unresricted guest execution! (VERR_CPUM_INVALID_HWVIRT_CONFIG). "
> > The solution they found is in the early part of the post: bcdedit /set hypervisorlaunchtype off
> > https://www.reddit.com/r/virtualization/comments/ci7tmv/virtualbox_vm_not_starting_after_installing/
> 
> Thank you for pointing to me the link, indeed it resolved my problem, this what I did to get it working as suggested in the link:
> 
> 1. run this at command prompt: bcdedit /set hypervisorlaunchtype off
> 2. turn off windows feature "Virtual Machine Platform"
> 3. reboot

thanks a million!
it worked well for me
