### ISSUE TITLE
Installation error with version 2.2.12 -- VCRUNTIME140.dll

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [GNS3/gns3-gui#3033]
Trying to install the latest version (2.2.12) of gns3. I'm getting this error on Windows 10.

![image](https://user-images.githubusercontent.com/5278928/89712397-b381c180-d95e-11ea-90e9-c60c6c54c71b.png)

**Comment by EmiyaUBW6** [comment]
In my case i have just login out after uninstalling the previous version of gns3.

**Comment by grossmj** [comment]
@Karlheinzniebuhr make sure all GNS3 is not used (no running/leftover processes), best is to reboot to be certain.

**Comment by Karlheinzniebuhr** [comment]
fixed by rebooting
