### ISSUE TITLE
7200 ospf EXSTART to DOWN, Neighbor Down: Dead timer expired

### ISSUE THREAD

**Issue by riden1117** [GNS3/gns3-gui#3034]
![image](https://user-images.githubusercontent.com/69714835/90310008-526d6700-dee5-11ea-90d4-840f957aae53.png)

The OSPF adjacency doesn't come up. not sure what's going on, on 2.2.5 it was working fine but now doesn't want to connect at all, even commands are going in slower. The gns3 2.2.12 is run on esxi 6.7 with 128bg and 24 vcore. rest ios work ok but have an issue with this one. I have tried different versions of ios and the issue remains

**Comment by riden1117** [comment]
Forgot this is the ospf config 
conf t
int lo 0
ip add 1.1.1.1 255.255.255.255
int g0/0
no sh
ip add 10.0.0.1 255.255.255.252
exit

router ospf 1
net 10.0.0.0 0.0.0.255 area 0
net 1.1.1.1 0.0.0.0 area 0



conf t
int lo 0
ip add 2.2.2.2 255.255.255.255
int g0/0
no sh
ip add 10.0.0.2 255.255.255.252
exit

router ospf 1
net 10.0.0.0 0.0.0.255 area 0
net 2.2.2.2 0.0.0.0 area 0

**Comment by riden1117** [comment]
![image](https://user-images.githubusercontent.com/69714835/90310390-f0166580-dee8-11ea-8e46-caeb2df58f62.png)
another issue, the whole wireshark captures jumps at once then they don't change for a long time and more jumps out at once. Previously packets were jumping into Wireshark as they were transmitted through the wire without delay.

**Comment by grossmj** [comment]
Something worth trying would be to test with the GNS3 VM but not running it on VMware ESXi (with VMware workstation for instance). I have noticed some other users reported similar issues and they all share on common thing, they run their projects on ESXi. Maybe this is a wrong assumption but if it does then it would help a lot to isolate the problem. Thanks.

**Comment by riden1117** [comment]
same issue with 2.2.14 on esxi

**Comment by grossmj** [comment]
@riden1117 have you had a chance to test with something else than ESXi?
