### ISSUE TITLE
config-disk: wrong defaults

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3035]
**Describe the bug**
Testing the freshly added config disk in v2.3

In two cases GNS3 uses the wrong defaults:
1. When converting 2.2 settings to 2.3 the create_config_disk settings in gns3_controller.conf is set to true
2. When creating a new qemu VM using the wizard in the preferences the disk interface gets set to "ide"

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS 10.13.6
 - GNS3 version 2.3.0dev2
 - Using GNS3 VM

**To Reproduce**

Case 1:

1. Stop GNS3
2. Copy the preferences from .configGNS3/2.2 to config/GNS3/2.3
3. Start GNS3
4. Compare gns3_controller.conf of both versions, the `create_config_disk` settings is set to true

```
             "template_type": "qemu",
             "builtin": false,
-            "replicate_network_connection_state": true
+            "replicate_network_connection_state": true,
+            "maxcpus": 1,
+            "aux_type": "none",
+            "create_config_disk": true
         },
```

Case 2:

1. Open preferences
2. Navigate to QEMU / Qemu VMs
3. Use "New" to create a new VM
4. When done, use Edit to view the new VM
4. All disk interfaces are set to "ide", should be "none" with 2.3

**Additional context**

Case 1:

GNS3 server:

```
diff --git a/gns3server/schemas/qemu_template.py b/gns3server/schemas/qemu_template.py
index 9d12e42e..213c6e9e 100644
--- a/gns3server/schemas/qemu_template.py
+++ b/gns3server/schemas/qemu_template.py
@@ -193,7 +193,7 @@ QEMU_TEMPLATE_PROPERTIES = {
     "create_config_disk": {
         "description": "Automatically create a config disk on HDD disk interface (secondary slave)",
         "type": "boolean",
-        "default": True
+        "default": False
     },
     "on_close": {
         "description": "Action to execute on the VM is closed",
```

Case 2:

GNS3 GUI:

```
diff --git a/gns3/modules/qemu/settings.py b/gns3/modules/qemu/settings.py
index 24608a99..0d6ad3bb 100644
--- a/gns3/modules/qemu/settings.py
+++ b/gns3/modules/qemu/settings.py
@@ -41,10 +41,10 @@ QEMU_VM_SETTINGS = {
     "hdb_disk_image": "",
     "hdc_disk_image": "",
     "hdd_disk_image": "",
-    "hda_disk_interface": "ide",
-    "hdb_disk_interface": "ide",
-    "hdc_disk_interface": "ide",
-    "hdd_disk_interface": "ide",
+    "hda_disk_interface": "none",
+    "hdb_disk_interface": "none",
+    "hdc_disk_interface": "none",
+    "hdd_disk_interface": "none",
     "cdrom_image": "",
     "bios_image": "",
     "boot_priority": "c",
```

**Comment by grossmj** [comment]
This should be fixed but I cannot test for now.

**Comment by cristian-ciobanu** [comment]
As a cosmetic change since the default disk interface type was changed from IDE to none I guess the names
(Primary Master)
(Primary Slave)
(Secondary Master)
(Secondary Master)
can be removed since they apply only to IDE interface and not all other types.

**Comment by b-ehlers** [comment]
> This should be fixed but I cannot test for now.

For me it's working now. One housekeeping task (low priority) would be to add `"hd*_disk_interface": "ide",` to all appliances in GNS3-registry, that don't set the disk interface.

**Comment by grossmj** [comment]
> As a cosmetic change since the default disk interface type was changed from IDE to none I guess the names
(Primary Master)
(Primary Slave)
(Secondary Master)
(Secondary Master)
can be removed since they apply only to IDE interface and not all other types.

What about using these names instead?
HDA (Disk 0)
HDB (Disk 1)
HDC (Disk 2)
HDD (Disk 3)

**Comment by cristian-ciobanu** [comment]
Using disk numbers is good since it can apply to any disk interfaces types selected from the drop down list.

**Comment by grossmj** [comment]
Done.
