### ISSUE TITLE
Dynamips and Qemu errors

### ISSUE THREAD

**Issue by leribe** [GNS3/gns3-gui#3041]
Hi GNS3 Team

Running gns3 on debian stretch, installed perfectly but getting this error when trying to run devices: 
**Dynamips**
=> Dynamips hypervisor process has stopped, return code: -11
C7200 'Ghost': generic_nvram_extract_config: Unknown error -61605
installed dynamips 0.2.18-1

**Qemu**
Sorry, no QEMU binary has been found. Please make sure QEMU is installed before continuing
installed qemu: 1:5.0-6
any advise what to do?

OS: Debian Stretch
GNS3 Ver: 2.2.11

Thanks in-advance.

**Comment by grossmj** [comment]
How have you installed these packages?

**Comment by leribe** [comment]
both used: apt-get install dynamips/qemu,
please advise if any better way and preferred version to install.

**Comment by grossmj** [comment]
For Dynamips, you could compile it from scratch, please see https://github.com/GNS3/dynamips/#compiling-linuxmac

Regarding Qemu, you managed to install it but it is not found by GNS3 right? What do you see if you type `whereis qemu-system-x86_64`?

**Comment by leribe** [comment]
it doesn't give me the path, just below
qemu-system-x86_64:

**Comment by grossmj** [comment]
What about `whereis qemu`?

**Comment by leribe** [comment]
manage to reinstall qemu using, can connect to qemu devices: 
**apt-get install qemu-system**

**Comment by leribe** [comment]
everything working, thanks for your patience.
