### ISSUE TITLE
QEmu : bad connected networks interfaces

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3042]
Hi

I am on LiveRaizo (Debian) with the last stable GNS3. 

On the Lab, i have a QEmu Linux VM with 6 networks interfaces.
I connect enp0s0 of this VM to an ethernet switch.

On the QEmu VM, i display the connected interfaces : `mii-tool enp0s0 enp0s1 enp0s2 enp0s3 enp0s4 enp0s5`
> enp0s0: negotiated 1000baseT-FD flow-control, link ok
> enp0s1: no link
> enp0s2: no link
> enp0s3: no link
> enp0s4: negotiated 1000baseT-FD flow-control, link ok
> enp0s5: no link 

Then the command shows that enp0s0 and enp0s4 are connected

If i connected to enp0s5 instead enp0s0, mii-tool showed no connected interfaces

**Comment by Raizo62** [comment]
> grossmj modified the milestones: 2.2.14, 2.2.15 4 days ago

I am surprised : it is a big bug for QEmu users. 
If we have a VM with 6 interfaces. If we connect only the last interface, the VM believes that no interface is connected.

**Comment by grossmj** [comment]
Sorry, 2.2.14 is scheduled to be released in less than a week and we don't have time to investigate this. Our current priority is the web-ui.

**Comment by Raizo62** [comment]
Perhaps that the problem is mine (or Linux). I will investigate and perhaps i will close this ticket.
Sorry.

**Comment by grossmj** [comment]
No worries, please let us know the outcome 👍

**Comment by Raizo62** [comment]
With QEmu, the kernel names the first interface ens3 and add a altname enp0s3. Then when i rename ens6 to enp0s3, udev refuses because enp0s3 already exists. I haved enp0s0, enp0s1, enp0s2 and ens6, ens7, ens8
Strangely QEMu/Kernel was lost when GNS3 ordered to power on/off the interface enp0s5.

I have not found solution to remove altname during the boot
I have rename my interfaces to enp1s and now the orders of GNS3 work.

Sorry for inconvenience

I close the issue
