### ISSUE TITLE
GNS3vm wonr run .. 

### ISSUE THREAD

**Issue by Artem718** [GNS3/gns3-gui#3043]
When i start the VM in VM Workation 15, it give an error saying \
"Could not open?dev/vmmon: no such directory exists"  my GNS3 gui and server are the version.
Please help with this issue.

![Screenshot from 2020-08-21 11-18-25](https://user-images.githubusercontent.com/1651086/90906775-2435ce80-e3a0-11ea-851d-6bc2c42d8a5c.png)
![Screenshot from 2020-08-21 11-18-35](https://user-images.githubusercontent.com/1651086/90906795-2ac44600-e3a0-11ea-964e-95f039a60791.png)

**Comment by grossmj** [comment]
I think this is a problem with VMware workstation itself. After a quick look, I found this https://askubuntu.com/questions/1096052/vmware-15-error-on-ubuntu-18-4-could-not-open-dev-vmmon-no-such-file-or-dire I haven't tested myself but this could fix the problem.
