### ISSUE TITLE
GNS v2.2.12 ESXi loading v2.2.13dev1 causing incompatibility with 2.2.12 GUI

### ISSUE THREAD

**Issue by tomsnj** [GNS3/gns3-gui#3044]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by tomsnj** [comment]
Server OS: GNS3.VM.VMware.ESXI.2.2.12.zip 
GUI OS: GNS3-2.2.12.dmg

ESXi VM launch results in server version 2.2.13dev1, so that attempts to connect to server from the GUI with 2.2.12 fail.  Attempts to revert the gns3server using pip install gns3server==2.2.12 fail to change the server version.

**Comment by tomsnj** [comment]
![image](https://user-images.githubusercontent.com/45703458/91643818-888e0900-ea04-11ea-9db7-019646a4ab48.png)

**Comment by grossmj** [comment]
Version 2.2.13 has been released. Do you still have the issue?
