### ISSUE TITLE
Existing Images on remote-server won't show in gns3-gui

### ISSUE THREAD

**Issue by Paraidomat** [GNS3/gns3-gui#3045]
**Describe the bug**
gns3-gui doesn't show images that are located on a remote-server which is running gns3-server. When loading an existing topology/project the nodes on the server show up fine.

**GNS3 version and operating system (please complete the following information):**
 - OS:
  - gns3-gui: Ubuntu 18.04.5 LTS
  - gns3-server: Ubuntu 18.04.5 LTS (hosted on AWS)
 - GNS3 version:
  - gns3-gui: Running GNS3 version 2.2.12 on Linux (64-bit) with Python 3.6.9 Qt 5.9.5 and PyQt 5.10.1
  - gns3-server: 2.2.12
 - I'm using a remote-server hosted on AWS.

**To Reproduce**
In order to reproduce:
- Start gns3-server 
- Start gns3-gui
  - gns3-gui is already configured to use the remote-server
  - gns3-gui shows that the connection to the server is okay (green bubble in the "Servers Summary")
- When creating a new project no images show up at all
- When opening a preexisting project, the topology loads with all nodes from images that are located on the server, but the images still don't show up in the list on the left hand side, so I can't add any additional nodes.

Any troubleshooting aid would be greatly appreciated.

**Comment by Paraidomat** [comment]
Apparently, the Templates are not placed on the server for some reason:

```
$ python3 get_templates.py 
Cloud: 39e257dc-8412-3174-b6b3-0ee3ed6a43e9 -- Type: cloud -- Builtin: True -- Console: N/A -- Category: guest
NAT: df8f4ea9-33b7-3e96-86a2-c39bc9bb649c -- Type: nat -- Builtin: True -- Console: N/A -- Category: guest
VPCS: 19021f99-e36f-394d-b4a1-8aaa902ab9cc -- Type: vpcs -- Builtin: True -- Console: N/A -- Category: guest
Ethernet switch: 1966b864-93e7-32d5-965f-001384eec461 -- Type: ethernet_switch -- Builtin: True -- Console: none -- Category: switch
Ethernet hub: b4503ea9-d6b6-3695-9fe4-1db3b39290b0 -- Type: ethernet_hub -- Builtin: True -- Console: N/A -- Category: switch
Frame Relay switch: dd0f6f3a-ba58-3249-81cb-a1dd88407a47 -- Type: frame_relay_switch -- Builtin: True -- Console: N/A -- Category: switch
ATM switch: aaa764e2-b383-300f-8a0e-3493bbfdb7d2 -- Type: atm_switch -- Builtin: True -- Console: N/A -- Category: switch
```

**Comment by grossmj** [comment]
> When creating a new project no images show up at all

Do you mean images or templates? Templates are stored in `~/.config/GNS3/2.2/gns3_controller.conf` on the server.

You can retrieve the list of templates by making an API request to `http://127.0.0.1:3080/v2/templates`

**Comment by Paraidomat** [comment]
> Do you mean images or templates?

I think I'm missing out on the templates. The templates are what I would drag + drop into a new topology in the GUI, right?

Something must have happend, so that the templates got lost.

**Comment by Paraidomat** [comment]
```
ubuntu@ip-xxx-yyy-zzz-aaa:~$ cat ~/.config/GNS3/2.2/gns3_controller.conf
{
    "computes": [],
    "templates": [],     <---
    "gns3vm": {
        "vmname": null,
        "when_exit": "stop",
        "headless": false,
        "enable": false,
        "engine": "vmware",
        "ram": 2048,
        "vcpus": 1,
        "port": 3080
    },
    "iou_license": {
        "iourc_content": "",
        "license_check": true
    },
    "appliances_etag": null,
    "version": "2.2.12"
```
I guess we found the root cause. 
I may have broke my installation by alternating usage of `pip` and `apt`...

**Comment by Paraidomat** [comment]
Okay, from what I tested the templates are lost, but the GUI shows the existing images, so it's quite easy to create the templates anew.
