### ISSUE TITLE
Ability to take a screenshot photo of topology using python API

### ISSUE THREAD

**Issue by syaltamimi** [GNS3/gns3-gui#3046]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the GUI, there is a button to save a screenshot image of the topology (which I use manually to store images every T second to create an animation offline). But I don't see in the documentaioh a way to do it from the API.

**Additional context**
*Use Case:* in Reinforcement Learning, an agent can learn by interacting with an environment. The training is usually done on a synthetic data, and the testing can be performed on an environment like GNS3. During the testing, it is nice to record an animation of this interaction.

**Comment by grossmj** [comment]
We won't implement this because the view of a topology is done on clients not the server.
