### ISSUE TITLE
Add GNS3 to System Path on Windows

### ISSUE THREAD

**Issue by PeterEstephan** [GNS3/gns3-gui#3051]
I recently had to manually add GNS3's folder to the system path to fix issues with opening VNC consoles from the WebUI. Prior to me doing this, I could never automatically open a VNC appliance in my project. It would always give me the error along the lines of cannot find the path to tvnviewer.exe.  And Yes, I have the GNS3 Web Client installed.

**Comment by grossmj** [comment]
You should have been able to configure the path to VNC client by launching `gns3-webclient-config.exe` from where is installed the GNS3 web-client pack.

**Comment by grossmj** [comment]
@PeterEstephan Any success?

**Comment by PeterEstephan** [comment]
Yes, I am able to successfully configure the path to the VNC client for example in the WebClient configuration. Thank you. However, I am suggesting to add the GNS3 folder to the systems environment path or update the default GNS3 WebClient "commands" to have the "C:\Program Files\GNS3\\" so that no additional configuration by the user would be required after installation. 
By default the GNS3 WebClient comes configured as so for me:
![image](https://user-images.githubusercontent.com/5473785/95606548-b741cb00-0a17-11eb-8d95-80871002227e.png)

Then if I wanted to for instance, console into a VNC appliance I would automatically get the following error message upon attempting to right clicking and consle'ing into a device via the WebUI:
![image](https://user-images.githubusercontent.com/5473785/95606845-2ddec880-0a18-11eb-9b6d-1a2befab63b2.png)
![image](https://user-images.githubusercontent.com/5473785/95606921-40590200-0a18-11eb-96d2-c8006ef3b72f.png)

The way that I thought of to get around this would either have to be manipulating each of the putty/vnc/packet capture commands as such to append the GNS3 installation directory. Or by adding the GNS3 path to the system environment variables. 
![image](https://user-images.githubusercontent.com/5473785/95607439-f91f4100-0a18-11eb-99a8-6dbd5fbde04a.png)

**Comment by grossmj** [comment]
The WebClient can be installed independently so including the GNS3 install dir in the PATH may not be the best. I have added the tvnviewer.exe by default in the WebClient install dir instead.
