### ISSUE TITLE
GNS3 2.2.14 on Mac OS Catalina can't add network device to project

### ISSUE THREAD

**Issue by fernandaadhi** [GNS3/gns3-gui#3055]
His guys, I run GNS3 and GNS3 VM in VMWare Fusion on my Mac OS Catalina, but I don't know why I can't add any networking devices to my projects, there is no error alert or something like that, but the thing is I can't add any networking devices to my projects including my network images, switchs, cloud, vpcs, etc.

Please anyone, help me with this problem if you know how to solve it, thanks.

**Comment by grossmj** [comment]
Do you have screenshots or a short video?

**Comment by taniokaeiji** [comment]
I have same issue.
My Environment is:
- GNS3 2.2.14 with GNS3_VM on VMware Fusion
- macOS Catalina 10.15.7
- VMware Fusion 12.0

short video captured using Kap (https://getkap.co/) .
![gns3_cant_drop_devices](https://user-images.githubusercontent.com/46465738/94358432-f3059800-00db-11eb-817f-b4203178e35c.gif)

**Comment by fernandaadhi** [comment]
Btw its not only on MacOS Catalina, I try it on my MacOS Mojave, it doesn't work too

**Comment by fernandaadhi** [comment]
MacOS Mojave 10.14
MacBook Pro 2012, Core i5, 16GB RAM
VMware Fusion 11.5

**Comment by grossmj** [comment]
Do you have a firewall or any other security suite? If yes, please deactivate and try again.

**Comment by taniokaeiji** [comment]
I'm using firewall only built-in firewall on macOS.

Today, I tried to wait Green Signal at "Servers Summary" status, and Create new Project.
After that, I can drop devices into project.
Previous version GNS3, I don't have to wait green signal.
