### ISSUE TITLE
Import custom version is still bugged 

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#3056]
**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 20.04
 - GNS3 version 2.2.14
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.): only using gns3server on gns3vm.

**To Reproduce**
Add new appliance
GUI reports wrong file size in wizzard for additional confusion.
Template gets imported with wrong image file names.
File is still uploaded to server in `/opt/gns3/images/QEMU` 
Workaround is to manually set template to use my desired file.

**Screenshots or videos**
![gns3-import-bug](https://user-images.githubusercontent.com/10002057/93747790-7d8b5a80-fbf7-11ea-8516-57f5bdf1a834.gif)

**Additional context**
Should have been solved in many reported issues on github already.
https://github.com/GNS3/gns3-gui/issues/3002
https://github.com/GNS3/gns3-gui/issues/2978
https://github.com/GNS3/gns3-gui/issues/2905

**Comment by grossmj** [comment]
I tried to reproduce the error using the exact same VyOS image and I couldn't find any issue. This is weird you ended up with a vFPC image, the MD5 shouldn't have matched. I cannot really explain why, maybe because you have previously edited the template and mistakenly put the same MD5  checksum somewhere?

**Comment by sliddjur** [comment]
Ok thats weird. I have not edited the template or put that specific checksum in a template before, since it was a completely new image.

**Comment by grossmj** [comment]
@sliddjur can you still reproduce the issue?

**Comment by sliddjur** [comment]
@grossmj no I was not able to reproduce it now. :thinking: I guess you can close this issue until/if I can reproduce it again.
