### ISSUE TITLE
gns3 vm in newest version doesnt connect when using hyper-v

### ISSUE THREAD

**Issue by legendcodermartino1245** [GNS3/gns3-gui#3058]
when i use gns gui the newest version and gns3 vm for hyper-v newest version it cant connnect

**Comment by legendcodermartino1245** [comment]
https://www.gns3.com/community/featured/the-new-hyper-v-based-gns3-vm this looks the same as my issue but in my case i cant do the workaround described here

**Comment by Mario156090** [comment]
Similar problem here.
https://www.gns3.com/community/support/can-gns3-gui-connect-with-hyper-v-gns3-vm

GNS3-GUI can not connect with Hyper-V GNS3 VM.
![image](https://user-images.githubusercontent.com/47507975/95627734-4bc12300-0a42-11eb-9645-3a9353693026.png)

**Comment by grossmj** [comment]
Please try to connect to the GNS3 VM and start a shell, then type the following commands:

```
sudo apt update
sudo apt install --yes --install-recommends linux-generic-hwe-18.04
sudo apt install --yes linux-virtual-hwe-18.04 linux-cloud-tools-virtual-hwe-18.04 linux-tools-virtual-hwe-18.04
```

Finally, reboot and this should work.

**Comment by Mario156090** [comment]
> Please try to connect to the GNS3 VM and start a shell, then type the following commands:
> 
> ```
> sudo apt update
> sudo apt install --yes --install-recommends linux-generic-hwe-18.04
> sudo apt install --yes linux-virtual-hwe-18.04 linux-cloud-tools-virtual-hwe-18.04 linux-tools-virtual-hwe-18.04
> ```
> 
> Finally, reboot and this should work.

Thank's a lot, I install that commands and works perfectly now.

![image](https://user-images.githubusercontent.com/47507975/95734592-484bb880-0c49-11eb-9656-f9d3dc9692bf.png)
![image](https://user-images.githubusercontent.com/47507975/95734653-5e597900-0c49-11eb-8a1a-bf5c0186de83.png)

**Comment by grossmj** [comment]
> Thank's a lot, I installed that commands and works perfectly now.

Perfect, thanks for the confirmation, this will be fixed by default in the next release.

**Comment by mlakhaney** [comment]
One more confirmation that the commands work perfectly.  I had exact situation with newest version gns3 vm stuck at starting.

**Comment by Mario156090** [comment]
> > Thank's a lot, I installed that commands and works perfectly now.
> 
> Perfect, thanks for the confirmation, this will be fixed by default in the next release.

New GNS3 2.2.16 with same error but the suggested packets are correct now. :(

**Comment by victoreebel** [comment]
I'm also experiencing this on 2.2.16 after attempting the suggested fix.

![image](https://user-images.githubusercontent.com/74570240/99668811-1d355f80-2a66-11eb-8040-ce68b764d359.png)

**Comment by Reverendheat** [comment]
Experiencing this issue on 2.2.16, attempted the suggested fix as well, but still stuck: GNS3 VM is starting  (GNS3 VM). Can connect and interact with the VM fine.
