### ISSUE TITLE
Increase the Number of Active  Ethnet Interface In Gns3 VM 

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3059]
Hi Jeremy ,

Can you Please increase the Number of Active Ethernet Interface In Gns3 VM although the number of Ethernet can be added but it doesn't appear in Gns3 VM 

the reason being for the request of of the feature is like in my lab i have shown in the picture if i need to access FTDv and FMCv running in different network though web interface (through Internet explore)  i have to add two cloud interface and both the could interface need to be added to two different Gns3 Vm Ethernet .and the  Gns3 Vm  Ethernet are mapped to VMware Interface then only i will be able to get ping response from my windows  workstation to FTDv and FMCv interface which are running in Qemu 

![Feature enhancement 01](https://user-images.githubusercontent.com/11521667/94341514-87fa8980-0027-11eb-9c84-ec5d582a5211.PNG)

**Comment by grossmj** [comment]
Hi,

I don't understand why you cannot add more interfaces to the GNS3 VM? Start a shell and do an "ifconfig" to see what interfaces have been detected.

**Comment by aksplease** [comment]
thank you Jeremy, you tried to address the issue i raised please find the snap shot of the number of interfaces i have added
![Eth Interface Error](https://user-images.githubusercontent.com/11521667/95258485-7ee99380-0843-11eb-8bcf-b79e927139b7.JPG)
 and the numbers showing in gns3 VM

**Comment by aksplease** [comment]
hi Jeremy ,
also i had one more query like can we see  a bend connection link enhancement  feature (pictorially) for easier link identification  name detection between multiple links running between two device ? as you can see from my project multiple link running between switch and FTDv.  Its difficult to identify interface names in first look.

**Comment by grossmj** [comment]
Add the following at the end of the `/etc/netplan/80_gns3vm_default_netcfg.yaml` file to add more interfaces

```
    eth3:
     dhcp4: yes
     optional: true
     dhcp-identifier: mac
    eth4:
     dhcp4: yes
     optional: true
     dhcp-identifier: mac
```

then issue the `netplan apply` command.

> also i had one more query like can we see a bend connection link enhancement feature (pictorially) for easier link identification name detection between multiple links running between two device ? as you can see from my project multiple link running between switch and FTDv. Its difficult to identify interface names in first look.

We already have an issue opened about it ;)

**Comment by aksplease** [comment]
Thank You Jeremy for your this simple tips to increase the interface 
  well cannot  this feature be auto mated like as the user will increase the no. of interface , on next restart of Gns3 VM the visible active interface will be automatic visible without manual inter venation.
![Active Interface increased](https://user-images.githubusercontent.com/11521667/95353167-975bbb80-08e0-11eb-882d-caeb96d173a2.JPG)

**Comment by grossmj** [comment]
@aksplease you totally right, I will automate this.

**Comment by aksplease** [comment]
thank u Jeremy for your attention
