### ISSUE TITLE
Interface light on/off

### ISSUE THREAD

**Issue by cischology** [GNS3/gns3-gui#3060]
Would like to see when one shutdown an interface , that interface will turn into red indicating it is shutdown.

**Comment by b-ehlers** [comment]
While this would be a nice enhancement, it can't be implemented.

Why? GNS3 doesn't run the nodes, GNS3 starts/stops programs like dynamips and qemu, that run the nodes. So GNS3 has only very limited information about the state of the node. GNS3 can determine, if a node runs or if it stops, it can send/receive data to/from the network interfaces and the console. Only recently (with v2.2) the devs found out how to set the interface status from GNS3, but only for QEMU and Virtualbox nodes.

But that's it, currently there is no way to get the interface status. Therefore GNS3 can't change the interface color.

As Virl and EVE-NG use a similar architecture, these programs have the same limitation.
