### ISSUE TITLE
Upgraded GNS3 VM from Ubuntu 18.04 to 20.04 LTS as per the message shown in front page. Not I can't even use "sudo gns3restore"!

### ISSUE THREAD

**Issue by PranavBhattarai** [GNS3/gns3-gui#3066]
I saw "**do-release-upgrade"** command for the first time and thought its OK to update since its coming from GNS team.
![Screenshot from 2020-10-07 17-28-25](https://user-images.githubusercontent.com/32763112/95352522-0a196680-08e2-11eb-9c99-5e8b8aea8b8d.png)

Now that things have updated, I can't even use "**sudo gns3restore**". What can I do?
![Screenshot from 2020-10-07 19-14-06](https://user-images.githubusercontent.com/32763112/95352782-4baa1180-08e2-11eb-82d8-d512ec9d5996.png)

Edit:
Do I need to re-install GNS3 VM?
Can't I do something from terminal to make it work?
_When will GNS3 VM update to Ubuntu 20.04?_

**Comment by grossmj** [comment]
Sorry, the GNS3 VM doesn't support Ubuntu 20.04 LTS. You shouldn't have upgraded the VM. So yes, you need to re-install the GNS3 VM.

The GNS3 VM will be updated to work on Ubuntu 20.04 in the future. We are also considering using Alpine Linux instead.
