### ISSUE TITLE
Errno 13 when updating appliance list online

### ISSUE THREAD

**Issue by brentstewart** [GNS3/gns3-gui#3068]
**Describe the bug**
When I attempt to update the appliance list from online, I get:
Error while getting appliances list: Could not write appliance file '/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/appliances/IPCop.gns3a': [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/appliances/IPCop.gns3a'

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux Mint 20
 - GNS3 version 2.1.15
 - GNS3 server version 2.1.15

**To Reproduce**
1. Go to New template
2. choose first option, install from GNS3 server
3. Error message appears in console.

**Screenshots or videos**
n/a

**Additional context**
I found the problem - I don't have python3.6.  I have 3.8.  Is there a way to update the path?

**Comment by grossmj** [comment]
What is the output of `ls -l /usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/appliances/`?

Thanks :+1:

**Comment by grossmj** [comment]
Also, how have you installed GNS3? Using pip or setup.py?

**Comment by brentstewart** [comment]
Here's the output.  The system time is set to UTC, so the times match to 
when I was trying to pull these.  Looks like they updated even though I 
got the error.*
*

*
*

*gns3@gns3vm:~$ *ls -l 
/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/appliances
total 984
-rw-rw-r-- 1 root staff  2643 Oct  8 23:56 a10-vthunder.gns3a
-rw-rw-r-- 1 root staff   725 Oct  8 23:56 aaa.gns3a
-rw-rw-r-- 1 root staff  2715 Oct  8 23:56 alcatel-7750.gns3a
-rw-rw-r-- 1 root staff   634 Oct  8 23:56 alpine-linux.gns3a
-rw-rw-r-- 1 root staff  2256 Oct  8 23:56 arista-ceos.gns3a
-rw-rw-r-- 1 root staff 14106 Oct  8 23:56 arista-veos.gns3a
-rw-rw-r-- 1 root staff  2400 Oct  8 23:56 aruba-arubaoscx.gns3a
-rw-rw-r-- 1 root staff  1812 Oct  8 23:56 aruba-vmc.gns3a
-rw-rw-r-- 1 root staff  4909 Oct  8 23:56 asterisk.gns3a
-rw-rw-r-- 1 root staff  1919 Oct  8 23:56 bigswitch-bigcloud-fabric.gns3a
-rw-rw-r-- 1 root staff  1564 Oct  8 23:56 bird.gns3a
-rw-rw-r-- 1 root staff  1680 Oct  8 23:56 brocade-vadx.gns3a
-rw-rw-r-- 1 root staff  6368 Oct  8 23:56 brocade-vrouter.gns3a
-rw-rw-r-- 1 root staff  6008 Oct  8 23:56 brocade-vtm.gns3a
-rw-rw-r-- 1 root staff  4418 Oct  8 23:56 bsdrp.gns3a
-rw-rw-r-- 1 root staff  2646 Oct  8 23:56 centos7.gns3a
-rw-rw-r-- 1 root staff  1800 Oct  8 23:56 centos-cloud.gns3a
-rw-rw-r-- 1 root staff  4554 Oct  8 23:56 checkpoint-gaia.gns3a
-rw-rw-r-- 1 root staff   451 Oct  8 23:56 chromium.gns3a
-rw-rw-r-- 1 root staff  1066 Oct  8 23:56 cisco-1700.gns3a
-rw-rw-r-- 1 root staff  1045 Oct  8 23:56 cisco-2600.gns3a
-rw-rw-r-- 1 root staff  1049 Oct  8 23:56 cisco-2691.gns3a
-rw-rw-r-- 1 root staff  1015 Oct  8 23:56 cisco-3620.gns3a
-rw-rw-r-- 1 root staff  1011 Oct  8 23:56 cisco-3640.gns3a
-rw-rw-r-- 1 root staff  1027 Oct  8 23:56 cisco-3660.gns3a
-rw-rw-r-- 1 root staff  1049 Oct  8 23:56 cisco-3725.gns3a
-rw-rw-r-- 1 root staff  1273 Oct  8 23:56 cisco-3745.gns3a
-rw-rw-r-- 1 root staff  1129 Oct  8 23:56 cisco-7200.gns3a
-rw-rw-r-- 1 root staff  3293 Oct  8 23:56 cisco-asa.gns3a
-rw-rw-r-- 1 root staff  5537 Oct  8 23:56 cisco-asav.gns3a
-rw-rw-r-- 1 root staff 11078 Oct  8 23:56 cisco-csr1000v.gns3a
-rw-rw-r-- 1 root staff  4069 Oct  8 23:56 cisco-dcnm.gns3a
-rw-rw-r-- 1 root staff  4168 Oct  8 23:56 cisco-fcnf.gns3a
-rw-rw-r-- 1 root staff  5283 Oct  8 23:56 cisco-fmcv.gns3a
-rw-rw-r-- 1 root staff  2849 Oct  8 23:56 cisco-fsve.gns3a
-rw-rw-r-- 1 root staff  4394 Oct  8 23:56 cisco-ftdv.gns3a
-rw-rw-r-- 1 root staff  3363 Oct  8 23:56 cisco-iosv.gns3a
-rw-rw-r-- 1 root staff  2355 Oct  8 23:56 cisco-iosvl2.gns3a
-rw-rw-r-- 1 root staff  6390 Oct  8 23:56 cisco-iosxrv9k.gns3a
-rw-rw-r-- 1 root staff  1897 Oct  8 23:56 cisco-iosxrv.gns3a
-rw-rw-r-- 1 root staff  1684 Oct  8 23:56 cisco-iou-l2.gns3a
-rw-rw-r-- 1 root staff  1340 Oct  8 23:56 cisco-iou-l3.gns3a
-rw-rw-r-- 1 root staff  6204 Oct  8 23:56 cisco-ise.gns3a
-rw-rw-r-- 1 root staff  3077 Oct  8 23:56 cisco-ngipsv.gns3a
-rw-rw-r-- 1 root staff 10652 Oct  8 23:56 cisco-nxosv9k.gns3a
-rw-rw-r-- 1 root staff  1903 Oct  8 23:56 cisco-nxosv.gns3a
-rw-rw-r-- 1 root staff  3676 Oct  8 23:56 cisco-smc.gns3a
-rw-rw-r-- 1 root staff  4582 Oct  8 23:56 cisco-vWLC.gns3a
-rw-rw-r-- 1 root staff  2237 Oct  8 23:56 cisco-wsav.gns3a
-rw-rw-r-- 1 root staff  3079 Oct  8 23:56 citrix-netscaler-vpx.gns3a
-rw-rw-r-- 1 root staff  4168 Oct  8 23:56 clearos.gns3a
-rw-rw-r-- 1 root staff  3610 Oct  8 23:56 cloudrouter.gns3a
-rw-rw-r-- 1 root staff 13666 Oct  8 23:56 coreos.gns3a
-rw-rw-r-- 1 root staff 15108 Oct  8 23:56 cumulus-vx.gns3a
-rw-rw-r-- 1 root staff  2828 Oct  8 23:56 danos.gns3a
-rw-rw-r-- 1 root staff  1347 Oct  8 23:56 debian10-min.gns3a
-rw-rw-r-- 1 root staff  4274 Oct  8 23:56 deft-linux.gns3a
-rw-rw-r-- 1 root staff  2399 Oct  8 23:56 dell-ftos.gns3a
-rw-rw-r-- 1 root staff   726 Oct  8 23:56 dns.gns3a
-rw-rw-r-- 1 root staff  5446 Oct  8 23:56 exos.gns3a
-rw-rw-r-- 1 root staff  2886 Oct  8 23:56 extreme-networks-voss.gns3a
-rw-rw-r-- 1 root staff 14513 Oct  8 23:56 f5-bigip.gns3a
-rw-rw-r-- 1 root staff  7832 Oct  8 23:56 f5-bigiq.gns3a
-rw-rw-r-- 1 root staff  2096 Oct  8 23:56 firefox.gns3a
-rw-rw-r-- 1 root staff 14991 Oct  8 23:56 fortiadc.gns3a
-rw-rw-r-- 1 root staff  2125 Oct  8 23:56 fortiadc-manager.gns3a
-rw-rw-r-- 1 root staff 11813 Oct  8 23:56 fortianalyzer.gns3a
-rw-rw-r-- 1 root staff  7506 Oct  8 23:56 fortiauthenticator.gns3a
-rw-rw-r-- 1 root staff  8156 Oct  8 23:56 forticache.gns3a
-rw-rw-r-- 1 root staff 17548 Oct  8 23:56 fortigate.gns3a
-rw-rw-r-- 1 root staff 12923 Oct  8 23:56 fortimail.gns3a
-rw-rw-r-- 1 root staff 11198 Oct  8 23:56 fortimanager.gns3a
-rw-rw-r-- 1 root staff  2840 Oct  8 23:56 fortiproxy.gns3a
-rw-rw-r-- 1 root staff  3065 Oct  8 23:56 fortirecorder.gns3a
-rw-rw-r-- 1 root staff  7679 Oct  8 23:56 fortisandbox.gns3a
-rw-rw-r-- 1 root staff  9779 Oct  8 23:56 fortisiem-super_worker.gns3a
-rw-rw-r-- 1 root staff  7615 Oct  8 23:56 fortiweb.gns3a
-rw-rw-r-- 1 root staff  5999 Oct  8 23:56 freebsd.gns3a
-rw-rw-r-- 1 root staff  7378 Oct  8 23:56 freenas.gns3a
-rw-rw-r-- 1 root staff  1375 Oct  8 23:56 freeRouter.gns3a
-rw-rw-r-- 1 root staff  1750 Oct  8 23:56 frr.gns3a
-rw-rw-r-- 1 root staff  7159 Oct  8 23:56 hp-vsr1001.gns3a
-rw-rw-r-- 1 root staff  1763 Oct  8 23:56 internet.gns3a
-rw-rw-r-- 1 root staff  1851 Oct  8 23:56 IPCop.gns3a
-rw-rw-r-- 1 root staff  7666 Oct  8 23:56 ipfire.gns3a
-rw-rw-r-- 1 root staff   694 Oct  8 23:56 ipterm.gns3a
-rw-rw-r-- 1 root staff  2280 Oct  8 23:56 juniper-junos-space.gns3a
-rw-rw-r-- 1 root staff  2115 Oct  8 23:56 juniper-vmx-legacy.gns3a
-rw-rw-r-- 1 root staff 17937 Oct  8 23:56 juniper-vmx-vcp.gns3a
-rw-rw-r-- 1 root staff  9448 Oct  8 23:56 juniper-vmx-vfp.gns3a
-rw-rw-r-- 1 root staff  2791 Oct  8 23:56 juniper-vqfx-pfe.gns3a
-rw-rw-r-- 1 root staff  3274 Oct  8 23:56 juniper-vqfx-re.gns3a
-rw-rw-r-- 1 root staff  1857 Oct  8 23:56 juniper-vrr.gns3a
-rw-rw-r-- 1 root staff  9661 Oct  8 23:56 juniper-vsrx.gns3a
-rw-rw-r-- 1 root staff   832 Oct  8 23:56 jupyter27.gns3a
-rw-rw-r-- 1 root staff   791 Oct  8 23:56 jupyter.gns3a
-rw-rw-r-- 1 root staff   855 Oct  8 23:56 kali-linux-cli.gns3a
-rw-rw-r-- 1 root staff  9236 Oct  8 23:56 kali-linux.gns3a
-rw-rw-r-- 1 root staff  4404 Oct  8 23:56 kemp-vlm.gns3a
-rw-rw-r-- 1 root staff  5577 Oct  8 23:56 kerio-connect.gns3a
-rw-rw-r-- 1 root staff  6266 Oct  8 23:56 kerio-control.gns3a
-rw-rw-r-- 1 root staff  5483 Oct  8 23:56 kerio-operator.gns3a
-rw-rw-r-- 1 root staff  2026 Oct  8 23:56 loadbalancer_org-va.gns3a
-rw-rw-r-- 1 root staff  4234 Oct  8 23:56 macos-install.gns3a
-rw-rw-r-- 1 root staff  2757 Oct  8 23:56 microcore-linux.gns3a
-rw-rw-r-- 1 root staff  8972 Oct  8 23:56 mikrotik-chr.gns3a
-rw-rw-r-- 1 root staff  1606 Oct  8 23:56 mininet.gns3a
-rw-rw-r-- 1 root staff  1791 Oct  8 23:56 netem.gns3a
-rw-rw-r-- 1 root staff   733 Oct  8 23:56 net_toolbox.gns3a
-rw-rw-r-- 1 root staff   598 Oct  8 23:56 network_automation.gns3a
-rw-rw-r-- 1 root staff  1116 Oct  8 23:56 ntopng.gns3a
-rw-rw-r-- 1 root staff  1000 Oct  8 23:56 onos.gns3a
-rw-rw-r-- 1 root staff  2914 Oct  8 23:56 op5-monitor.gns3a
-rw-rw-r-- 1 root staff  1581 Oct  8 23:56 openbsd.gns3a
-rw-rw-r-- 1 root staff  2289 Oct  8 23:56 opennac.gns3a
-rw-rw-r-- 1 root staff  1677 Oct  8 23:56 opensuse.gns3a
-rw-rw-r-- 1 root staff  1082 Oct  8 23:56 openvswitch.gns3a
-rw-rw-r-- 1 root staff  1253 Oct  8 23:56 openvswitch-management.gns3a
-rw-rw-r-- 1 root staff  9711 Oct  8 23:56 openwrt.gns3a
-rw-rw-r-- 1 root staff  2520 Oct  8 23:56 openwrt-realview.gns3a
-rw-rw-r-- 1 root staff  2388 Oct  8 23:56 opnsense.gns3a
-rw-rw-r-- 1 root staff  2225 Oct  8 23:56 ostinato.gns3a
-rw-rw-r-- 1 root staff  6309 Oct  8 23:56 packetfence-zen.gns3a
-rw-rw-r-- 1 root staff  7583 Oct  8 23:56 pan-vm-fw.gns3a
-rw-rw-r-- 1 root staff  2708 Oct  8 23:56 parrot-os.gns3a
-rw-rw-r-- 1 root staff  3448 Oct  8 23:56 pfsense.gns3a
-rw-rw-r-- 1 root staff  3260 Oct  8 23:56 proxmox-mg.gns3a
-rw-rw-r-- 1 root staff   530 Oct  8 23:56 python-go-perl-php.gns3a
-rw-rw-r-- 1 root staff  1845 Oct  8 23:56 Raspian.gns3a
-rw-rw-r-- 1 root staff  2677 Oct  8 23:56 riverbed-steelhead-cx.gns3a
-rw-rw-r-- 1 root staff  3834 Oct  8 23:56 security-onion.gns3a
-rw-rw-r-- 1 root staff  2708 Oct  8 23:56 Simulator.gns3a
-rw-rw-r-- 1 root staff  2121 Oct  8 23:56 smoothwall.gns3a
-rw-rw-r-- 1 root staff  2762 Oct  8 23:56 sophos-iview.gns3a
-rw-rw-r-- 1 root staff  9547 Oct  8 23:56 sophos-utm.gns3a
-rw-rw-r-- 1 root staff  8543 Oct  8 23:56 sophos-xg.gns3a
-rw-rw-r-- 1 root staff  1578 Oct  8 23:56 tacacs-gui.gns3a
-rw-rw-r-- 1 root staff  2747 Oct  8 23:56 tinycore-linux.gns3a
-rw-rw-r-- 1 root staff  2582 Oct  8 23:56 trendmicro-imsva.gns3a
-rw-rw-r-- 1 root staff  2229 Oct  8 23:56 trendmicro-iwsva.gns3a
-rw-rw-r-- 1 root staff  1018 Oct  8 23:56 turnkey-wordpress.gns3a
-rw-rw-r-- 1 root staff  4223 Oct  8 23:56 ubuntu-cloud.gns3a
-rw-rw-r-- 1 root staff   816 Oct  8 23:56 ubuntu-docker.gns3a
-rw-rw-r-- 1 root staff  3141 Oct  8 23:56 ubuntu-gui.gns3a
-rw-rw-r-- 1 root staff  1460 Oct  8 23:56 ubuntu-server.gns3a
-rw-rw-r-- 1 root staff  7404 Oct  8 23:56 untangle.gns3a
-rw-rw-r-- 1 root staff  1731 Oct  8 23:56 viptela-edge-genericx86-64.gns3a
-rw-rw-r-- 1 root staff  1677 Oct  8 23:56 viptela-smart-genericx86-64.gns3a
-rw-rw-r-- 1 root staff  2238 Oct  8 23:56 
viptela-vmanage-genericx86-64.gns3a
-rw-rw-r-- 1 root staff  1371 Oct  8 23:56 vpp.gns3a
-rw-rw-r-- 1 root staff  4794 Oct  8 23:56 vrin.gns3a
-rw-rw-r-- 1 root staff  5063 Oct  8 23:56 vyos.gns3a
-rw-rw-r-- 1 root staff  2668 Oct  8 23:56 watchguard-fireboxv.gns3a
-rw-rw-r-- 1 root staff  2665 Oct  8 23:56 watchguard-xtmv.gns3a
-rw-rw-r-- 1 root staff   777 Oct  8 23:56 webterm.gns3a
-rw-rw-r-- 1 root staff  4565 Oct  8 23:56 windows.gns3a
-rw-rw-r-- 1 root staff  2820 Oct  8 23:56 windows_server.gns3a
-rw-rw-r-- 1 root staff  6352 Oct  8 23:56 zentyal-server.gns3a
-rw-rw-r-- 1 root staff  3734 Oct  8 23:56 zeroshell.gns3a

**Comment by brentstewart** [comment]
GNS3 is installed using apt for the front end.  The backend is the OVA 
deployed on ESXi 6.5.

**Comment by grossmj** [comment]
The easiest for now would be to add the rights manually, something like `chown -R root:your_group /usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/appliances`

**Comment by brentstewart** [comment]
I've upgraded to 2.2.16 and this is fixed.  Thanks!
