### ISSUE TITLE
Hyper-V dynamic memory support.

### ISSUE THREAD

**Issue by Mario156090** [GNS3/gns3-gui#3069]
Hi everybody,

When you use GNS3-GUI with Hyper V VM automaticly overwrite memory specification to Hyper V VM, so, if you has enable dynamic memory on Hyper V settings this change to static configuration from GNS3-GUI.

My requeriment is add an option for don't write memory specification in GNS3-GUI with relationship to Hyper-V VM.

**Comment by grossmj** [comment]
We have added an option so GNS3 won't write vCPUs and RAM specification when starting the GNS3 VM.
