### ISSUE TITLE
Integrate branch 2.3 into 3.0

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3070]
As the milestone 2.3 has be closed, I assume that the branch 2.3 will be abandoned.

On the gns3-server branch 3.0 includes all of 2.3, so nothing is lost. But that's not the case with the gns3-gui. Several commits of 2.3 are missing in 3.0, see https://github.com/GNS3/gns3-gui/compare/3.0...2.3. I suggest to merge these changes into 3.0.

**Comment by grossmj** [comment]
> As the milestone 2.3 has be closed, I assume that the branch 2.3 will be abandoned.

Indeed, branch 2.3 will be abandoned.

> On the gns3-server branch 3.0 includes all of 2.3, so nothing is lost. But that's not the case with the gns3-gui. Several commits of 2.3 are missing in 3.0, see 3.0...2.3. I suggest to merge these changes into 3.0.

Thanks for spotting this. I will merge 2.3 into 3.0 :+1:

**Comment by grossmj** [comment]
Merged.
