### ISSUE TITLE
Mac OS Catalina issues 

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3073]
1- problem bridging between gns3 and the gns3 vm
2- unable to drag appliances 
3- timeout issues 
Even after a clean install still the same problem 
Also trying to upgrade from 2.2.14 to 2.2.15 
Hangs seems to be an issue with docker ce

**Comment by grossmj** [comment]
Do you still have issues with version 2.2.16? If yes, please post screenshots if you can. Thanks.

**Comment by grossmj** [comment]
Looks like there is a still an issue in 2.2.16: https://github.com/GNS3/gns3-gui/issues/3087

**Comment by benali125** [comment]
I’m upgraded to  Mac OS Big Sur thinking will solve the issues however gns app won’t even load just hangs 
I think it’s a common issue on gns3 community with Mac users so just waiting for 2.2.17
