### ISSUE TITLE
Short description GNS3 2.2.15 v3 after a while cant detect VM

### ISSUE THREAD

**Issue by eliassal** [GNS3/gns3-gui#3074]
**Describe the bug**
I have GNS3 with VM VMwar plater 16, I was able to run GNS3 and connect to the VM without any issue, created couple of topologies using the VM. This morning, I reactivated my desktop (win 10), ALL of a sudden, it was not able to detect the VM in spite of the fact that the VM starts correctly. I went through a post here around the same issue and I triggered GNS3 through command line (disabling firewall and antivirus as well), in admin and my user mode, no way, can't detect VM.  Here is a snapshot of the 3 elements at the ame time GNS3 gui, the VMware and the command line as well as the full debug text

**GNS3 version and operating system (please complete the following information):**
 - OS: win 10 64bit
 - GNS3 2.2.15
 - local GNS3 VM VMware player 16

**To Reproduce**
1. Trigger GNS
2. cant detect VM

**Screenshots or videos**
![GNS3-VM_no detect](https://user-images.githubusercontent.com/8447864/96229304-fd0e0e80-0f96-11eb-96b0-6363f5476077.jpg)

**Debug session text**
GNS3 management console.
Running GNS3 version 2.2.15 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2020 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=b75e1657-2454-4701-93f1-a3a7ac04f8ce&aip=1&t=screenview&an=GNS3&av=2.2.15&ua=Mozilla/5.0%20%28Windows%20NT%2010%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/2.2.15&cd=Main%20Window&ds=gns3-gui&sr=2560x1440&ul=en_us
GET http://192.168.1.4:3080/v2/version
Error while connecting to local server Connection refused
GET http://192.168.1.4:3080/v2/version
Error while connecting to local server Connection refused
GET http://192.168.1.4:3080/v2/version
Error while connecting to local server Connection refused
Starting local server process with "C:\Program Files\GNS3\gns3server.EXE" --local --debug --log="C:\Users\salam.SALAM\AppData\Roaming\GNS3\2.2\gns3_server.log" --pid="C:\Users\salam.SALAM\AppData\Roaming\GNS3\2.2\gns3_server.pid"
Local server process has started (PID=2348)
Set worker inside a thread <class 'gns3.utils.wait_for_connection_worker.WaitForConnectionWorker'>
WaitForConnectionWorker thread started
WaitForConnectionWorker thread finished
WaitForConnectionWorker thread is being destroyed
WaitForConnectionWorker thread destroyed
Connection to http://192.168.1.4:3080
GET http://192.168.1.4:3080/v2/version {}
Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=b75e1657-2454-4701-93f1-a3a7ac04f8ce&aip=1&t=screenview&an=GNS3&av=2.2.15&ua=Mozilla/5.0%20%28Windows%20NT%2010%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/2.2.15&cd=Project%20Dialog&ds=gns3-gui&sr=2560x1440&ul=en_us
Decoding response from http://admin@192.168.1.4:3080/v2/version response 200
GET http://192.168.1.4:3080/v2/templates {}
GET http://192.168.1.4:3080/v2/computes {}
GET http://192.168.1.4:3080/v2/appliances?symbol_theme=Classic {}
GET http://192.168.1.4:3080/v2/projects {}
Connecting to WebSocket endpoint: ws://192.168.1.4:3080/v2/notifications/ws
GET http://192.168.1.4:3080/v2/version {}
GET http://192.168.1.4:3080/v2/projects {}
Decoding response from http://admin@192.168.1.4:3080/v2/templates response 200
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/router.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/firefox.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/microsoft.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/multilayer_switch.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/cloud.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/vpcs_guest.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/ethernet_switch.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/hub.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/frame_relay_switch.svg/raw {}
GET http://192.168.1.4:3080/v2/symbols/%3A/symbols/atm_switch.svg/raw {}
Decoding response from http://admin@192.168.1.4:3080/v2/appliances?symbol_theme=Classic response 200
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
Decoding response from http://admin@192.168.1.4:3080/v2/projects response 200
Decoding response from http://admin@192.168.1.4:3080/v2/version response 200
Decoding response from http://admin@192.168.1.4:3080/v2/projects response 200
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/microsoft.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\037943624afe4ac8476f03272f9f1513.svg for /symbols/microsoft.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/router.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\18011c181013b0971a1a8f3e94202386.svg for /symbols/%3A/symbols/router.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/firefox.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\40ebd6f3bed2a15ec7acdf11ed0ac104.svg for /symbols/firefox.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/multilayer_switch.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\b4625a5a801e68d455bd5cf0012a088f.svg for /symbols/%3A/symbols/multilayer_switch.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/vpcs_guest.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\94045dc1e27af247496de443eeb31a8f.svg for /symbols/%3A/symbols/vpcs_guest.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/cloud.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\b7fc40772980613897e485197a957f88.svg for /symbols/%3A/symbols/cloud.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/ethernet_switch.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\855e8cf4fe8848800855d1b9730328d1.svg for /symbols/%3A/symbols/ethernet_switch.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/hub.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\8ebdb8f0fe6895a42d27ed50b06de689.svg for /symbols/%3A/symbols/hub.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/frame_relay_switch.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\2a45f9c65479fc28388a2332e7b3c526.svg for /symbols/%3A/symbols/frame_relay_switch.svg/raw
Decoding response from http://admin@192.168.1.4:3080/v2/symbols/%3A/symbols/atm_switch.svg/raw response 200
File stored C:\Users\SALAM~1.SAL\AppData\Local\Temp\tmpatcnuaeg-gns3\d8198a5d11a729a46b8074c9af9549c1.svg for /symbols/%3A/symbols/atm_switch.svg/raw
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=b75e1657-2454-4701-93f1-a3a7ac04f8ce&aip=1&t=screenview&an=GNS3&av=2.2.15&ua=Mozilla/5.0%20%28Windows%20NT%2010%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/2.2.15&cd=About%20Dialog&ds=gns3-gui&sr=2560x1440&ul=en_us
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
Client config has changed, reloading it...
Load config from C:\Users\salam.SALAM\AppData\Roaming\GNS3\2.2\gns3_gui.ini
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=b75e1657-2454-4701-93f1-a3a7ac04f8ce&aip=1&t=screenview&an=GNS3&av=2.2.15&ua=Mozilla/5.0%20%28Windows%20NT%2010%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/2.2.15&cd=About%20Dialog&ds=gns3-gui&sr=2560x1440&ul=en_us
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200
GET http://192.168.1.4:3080/v2/computes {}
Decoding response from http://admin@192.168.1.4:3080/v2/computes response 200

**Comment by eliassal** [comment]
Quick info grossmj, I rebooted the machine and now GNS3 is able to comunicate with the VM, so I think it is a bug as putting the machine yesterday in "sleep' mode" then wake it up this morning made GNS loses control or something else
![GNS3-VM_no detect_002](https://user-images.githubusercontent.com/8447864/96268727-b259ba00-0fc9-11eb-907e-0516abb3403b.jpg)

**Comment by eliassal** [comment]
Now I started getting something strange when trying to access switches. when I add an Ethernet switch, right away it defaults to " none" for console. When I try to configure it for telnet I get

> SW1": Telnet access for switches is not available in this version of GNS3
> "Switch1": Telnet access for switches is not available in this version of GNS3
> "Switch2": Telnet access for switches is not available in this version of GNS3
> The project will be deleted from disk. All files will be removed including the project subdirectories. Continue?
> Error while creating link: Cannot connect to itself
> "Switch1": Telnet access for switches is not available in this version of GNS3

**Comment by eliassal** [comment]
Here is a snpashot

![image](https://user-images.githubusercontent.com/8447864/96287336-125c5a80-0fe2-11eb-9f0e-3539a201bc50.png)

**Comment by eliassal** [comment]
When I double click on the switch

**Comment by eliassal** [comment]
When I double click on the switch a terminal opens but it cant connect to the VM

![image](https://user-images.githubusercontent.com/8447864/96287547-68310280-0fe2-11eb-8539-80c4a48771df.png)

**Comment by eliassal** [comment]
It seems that GNS 3 is not stable if I am not mistaken

**Comment by eliassal** [comment]
Hi , again GNS is not able to detect the VM today

**Comment by jtorri** [comment]
I assume you have assigned vmnet1 to eth0 of the GNS3 VM.  If so, after starting GNS3 and failing to connect to associated GNS3 VM try going to Win 10 network connections and disable vmnet1, wait a moment or two, then enable vmnet1.  Give it a minute or so and see if the GNS3 VM is now connected.  I am using VMWare Workstation 16 and all works fine except I have to go through that process for the GNS3 application to connect to the associated GNS3 VM.  Several time I thought update/upgrades to Win 10 solved the issue but it always returns.  It is, however, not consistent.

**Comment by eliassal** [comment]
Thanks for the tip, I will try but I have 2 VMnets, vmnet1 & vmnet8 as you can notice in the snapshot, any idea why?
![GNS3-VM_no detect_004](https://user-images.githubusercontent.com/8447864/96361160-ab46bf00-1123-11eb-9c4f-33a92567a2eb.jpg)

**Comment by eliassal** [comment]
I fired Vmware player, (I am very new to it as I always used hyper-v on windows), 1st I can't how network adapter in VMware are linked to the NIcs in windows
![GNS3-VM_no detect_007](https://user-images.githubusercontent.com/8447864/96361270-89017100-1124-11eb-8618-8bc60ce76369.jpg)
![GNS3-VM_no detect_006](https://user-images.githubusercontent.com/8447864/96361272-8dc62500-1124-11eb-9211-86e987d83870.jpg)

**Comment by eliassal** [comment]
Yes, you are correct, I disabled both vmnet1 and 8, fired GNS3, it was able to detect the VM

**Comment by eliassal** [comment]
And now is the best one, I delted the VM and recreted it, now GNS3 is not able event to contact the VMwareplayer , I will switch to Hyper-V while GNS3 finds something to make it work and more stable.
Regards

**Comment by grossmj** [comment]
> Yes, you are correct, I disabled both vmnet1 and 8, fired GNS3, it was able to detect the VM but still cant access any switch terminal getting the same error
"Switch1": Telnet access for switches is not available in this version of GNS3

It is not possible to console to the built-in switch. You must create a switch using one vendor appliance, IOSv-L2 for instance.

**Comment by grossmj** [comment]
A simple solution to your issues would be to start the VM in VMware or any other virtulization software and then use the VM as a remote server in the GNS3 GUI.

![GNS3_remote_server](https://user-images.githubusercontent.com/4752614/100561123-d407ca00-3307-11eb-8320-6e57e57bb3fd.png)

After that, remember to always start the VM before starting GNS3.
