### ISSUE TITLE
3.0: Add startup config to QEMU config disk

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3076]
**Is your feature request related to a problem? Please describe.**
Adding an initial config disk to the QEMU config disk feature (https://github.com/GNS3/gns3-gui/issues/2958) will greatly enhance it.

For example an IOSv template could then use [IOSv_startup_image.zip](https://github.com/GNS3/gns3-gui/files/5395730/IOSv_startup_image.zip). It includes an initial configuration for the first start, that will replace the `IOSv_startup_config.img` that is currently used as HDB. But it uses a simple zip file instead of an image format, that should simplify any changes. When using the IOS archive feature the configuration changes within IOSv will be automatically stored to the config disk. With the GNS3 "Export config" function the customer gets a zip archive of this config disk.

**Describe the solution you'd like**
A very easy solution would be to use the HDD disk image to configure the startup config image. In the GUI its main task is to allow adding a HDD disk image, even when the config disk is enabled. In the server on the first run of a VM it has to copy the HDD disk image to `config.zip`.

The main drawback is, that the initial configuration is handled like a disk image. So that's no a really clean solution, but it's simple to implement. If the GNS3 devs want to go that direction I can create a PR.

**Describe alternatives you've considered**
Alternatively a startup configuration setting can be implemented, maybe with a selector for the type of startup solution. Currently there are only the types "none" (no startup solution) and "config disk". In future additional solutions as discussed in https://github.com/GNS3/gns3-gui/issues/1095, https://github.com/GNS3/gns3-server/issues/1315 and https://github.com/GNS3/gns3-server/issues/1749 could be added.

On the server side the current import/export config implementation as well as future implementations should be put into seperate modules. But that will mean a lot of work.

**Comment by grossmj** [comment]
Thanks @b-ehlers, I like the idea. Let me get back to you soon since we are in the middle of massive changes on the 3.0 branch.

**Comment by b-ehlers** [comment]
I created a patched version of GNS3 v2.2 with some custom patches. The startup config for the QEMU config disk is one of them, see https://github.com/b-ehlers/gns3-server/commit/b3e344df3dd343e125cee8a5ce4e5d0e7d76b31f for the GNS3 server and https://github.com/b-ehlers/gns3-gui/commit/2055c368e757192ed10ca6a98b1b54c5c1476944 for the GUI.

In the GUI patch only the changes in `gns3/modules/qemu/pages/qemu_vm_configuration_page.py` are needed. They allow entering a disk image even when the config disk is enabled and they change the label depending of the config disk state.

The rest includes patch https://github.com/GNS3/gns3-gui/commit/4f631669e54b9d1073596bf624fcfc88210373e2 of GNS3 v3.0. Furthermore it moves the config disk checkbos to the top of the HD-D area, I prefer it that way.

**Comment by grossmj** [comment]
Looks good, please can you create a pull request for 2.2 branch? Thanks.

**Comment by b-ehlers** [comment]
My special BE branch in my fork contains a backport of the QEMU config disk (issue https://github.com/GNS3/gns3-gui/issues/2958) and the additional changes related to this. Do you really want to add all this into stable 2.2?

I think these changes are better done in the 3.0 branch. But as this is currently too unstable for me, I'm working with my special BE branch. My patches are meant as a demonstration, that the changes are quite small. They can be used as a bases for a future PR, when 3.0 gets more stable.

**Comment by grossmj** [comment]
> They can be used as a bases for a future PR, when 3.0 gets more stable.

You are right I think, safer to do this into the 3.0 :+1:

**Comment by b-ehlers** [comment]
I've thought a bit longer over it. Branch 3.0 will include some big changes, the use of FastAPI and a user management, and maybe some additional goodies. That's great, but it will need quite some time until it's fully implemented and tested.

I still think, that it's a bit late to introduce the QEMU config disk into 2.2. But I'm using the backported version some time now and I think it's pretty stable. So if you like to introduce this feature in 2.2, I'm happy to create a PR for that.

**Comment by grossmj** [comment]
> I've thought a bit longer over it. Branch 3.0 will include some big changes, the use of FastAPI and a user management, and maybe some additional goodies. That's great, but it will need quite some time until it's fully implemented and tested.

Indeed, 3.0 will not hit beta status before a good 4 to 6 months.

> I still think, that it's a bit late to introduce the QEMU config disk into 2.2. But I'm using the backported version some time now and I think it's pretty stable. So if you like to introduce this feature in 2.2, I'm happy to create a PR for that.

I am good with this :+1: thanks.

**Comment by b-ehlers** [comment]
Created PR https://github.com/GNS3/gns3-gui/pull/3104 and https://github.com/GNS3/gns3-server/pull/1847

**Comment by b-ehlers** [comment]
Nice, that you merged the pull requests.

For the QEMU config disk to be usable, the mtools package has to be installed in the OS, that are running the gns3-server. As QEMU is not used that often in gns3-server based on Windows or macOS, I think it's not urgend to integrate mtools in the Windows and macOS packages. For Linux I suggest to add mtools as a dependency in the Ubuntu gns3-server package. That way mtools should find its way into GNS3VM and other Ubuntu installations. For other Linux variants a short note might be added to the installation instructions.

**Comment by grossmj** [comment]
> For Linux I suggest to add mtools as a dependency in the Ubuntu gns3-server package. That way mtools should find its way into GNS3VM and other Ubuntu installations.

Done.
