### ISSUE TITLE
GNS kicks the hyper-V VM but never goes through

### ISSUE THREAD

**Issue by eliassal** [GNS3/gns3-gui#3077]
**NOTE**
I have already a thread aroung GNS VMWare VM which seems not stable and not working correctly at https://github.com/GNS3/gns3-gui/issues/3074, that is the reason why I switched to Hyper-V VM

**Describe the bug**
I have most recent version of GNS3, downloaded the Hyper-V VM, created it with the script. GNS 3 succesfuly trigers the VM and can see it is in "Starting status", I switch to Hyper-V, I see indeed that VM started correctly and ready. I can ssh to it from commandline, as well as it can go to internet. However, in GNS3 it keeps saying "is starting..." and never able to finalize connection. then 5 minutes later I get an error "not able to save ...as you can notice in the snapshot
Thanks for your help

**GNS3 version and operating system (please complete the following information):**
 - OS: win 10 64bit
 - GNS3 version 2.1.15
 - Hyper-V

**To Reproduce**

**Screenshots or videos**
![GNS3-VM_no detect_009](https://user-images.githubusercontent.com/8447864/96429621-71e48100-1201-11eb-9f77-dbd41938e11b.jpg)
![GNS3-VM_no detect_010](https://user-images.githubusercontent.com/8447864/96429639-77da6200-1201-11eb-84dd-a73dcef4e1ff.jpg)

**Additional context**
I also opened a thread on GNS3 community at https://www.gns3.com/initiatives/gns-kicks-the-vm-but-never-go-through but the response is not really satisfactory

**Comment by grossmj** [comment]
Do you still have the issue with version 2.2.16?

**Comment by eliassal** [comment]
No, I reinstalled the VM, now it is working but there is a huge issue with the design. GNS3 VM is configured with NIC (Default switch) of the Hyper-V win 10. The Hyper-V Default Switch will randomly use one these IP address ranges based on the host system IP address:
- Start IP: 192.168.0.0 – End IP: 192.168.255.255
Start IP: 172.17.0.0 – End IP: 172.31.255.255

Any idea of how can we configure the VM with a fixed IP on another hyper-V switch and make GNS3 able to connect to it?

**Comment by eliassal** [comment]
Sorry, I have 2.2.15, do you mean that there is a new GNS3 version?

**Comment by Mario156090** [comment]
> Do you still have the issue with version 2.2.16?

Yes, same problem here yet with 2.2.16.

**Comment by grossmj** [comment]
@Mario156090 apparently a package is missing. Please go to the shell from the VM menu and type this command: `sudo apt update && sudo apt install linux-cloud-tools-common` then reboot.

**Comment by Mario156090** [comment]
> @Mario156090 apparently a package is missing. Please go to the shell from the VM menu and type this command: `sudo apt update && sudo apt install linux-cloud-tools-common` then reboot.

Ok, yes, that is the problem. Works perfectly now after package install.

![image](https://user-images.githubusercontent.com/47507975/98498712-76ef8b80-2215-11eb-9460-20c1fe59c8bf.png)

**Comment by grossmj** [comment]
I have added the missing package when building the GNS3 VM. Hopefully this is all what is needed.

**Comment by eliassal** [comment]
Thanks Jermey. I understand that a new version is out, 2.2.16, is there will be  a new VM for this version? If yes, should we use the new VM with the new 2.2.16 GNS3 or can we continue with the exisiting VM? If in case we need to upgrade the VM, will topologies and images that run in the image are saved somewhere or should we start from scratch and the possibility of losing all our topologies, thanks again for your help

**Comment by grossmj** [comment]
Yes, there is a new GNS3 VM after each release. However, you can just upgrade the one you have from the menu which is the preferred way since you don't have to migrate your topologies to another VM.
