### ISSUE TITLE
Switch1: Telnet access for switches is not available in this version of GNS3

### ISSUE THREAD

**Issue by eliassal** [GNS3/gns3-gui#3078]
**Describe the bug**
I have GNS3 which I setup 4 days and I was able to work and design some topologies, access routers and switches through telnet. All of a suddn when I try to add a switch on local server or on VM, I get 
"Switch1": Telnet access for switches is not available in this version of GNS3

**GNS3 version and operating system (please complete the following information):**
 - OS: win 10 64bit
 - 2.1.15]
 - Hyper-V

**To Reproduce**
1.Add switch
2. on the right hand side table topology summary I see
![GNS3-VM_no detect_011](https://user-images.githubusercontent.com/8447864/96431979-92faa100-1204-11eb-85da-a10dc28864eb.jpg)

4. then right click on the switch > configure and chose telnet
![GNS3-VM_no detect_012](https://user-images.githubusercontent.com/8447864/96432217-dead4a80-1204-11eb-9fe6-d3fa3d0ee2da.jpg)

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by grossmj** [comment]
> I have GNS3 which I setup 4 days and I was able to work and design some topologies, access routers and switches through telnet. All of a suddn when I try to add a switch on local server or on VM, I get
"Switch1": Telnet access for switches is not available in this version of GNS3

This is normal, simple switches in GNS3 don't have a console.

**Comment by alex9099** [comment]
Then i guess there should not be an option to choose telnet as the console type?
