### ISSUE TITLE
IOU duplicated MAC in multi-compute setup

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#3079]
gns3 v2.2.15 running as remote on 2 x Ubuntu Server 20.04.1

application_id for IOU is calculated based on compute node. It will cause duplicated MAC in topology with IOU nodes running on different compute.

As I understand application_id used to calculate bridge_id which is base for MAC calculation for IOU.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/5d1fdceb98e0114cb09dbd7aecef6794604e92aa
