### ISSUE TITLE
[no interfaces] IOS-XRv 9000 7.1.1 on GNS3 2.2.15

### ISSUE THREAD

**Issue by GitHub-CHKM** [GNS3/gns3-gui#3081]
I found that there are only a null0 interface and the Mgmt interface in the IOS-XRv 9k 7.1.1 when it was booted in GNS3 2.2.15. Anyone experienced the same issue? Thanks.

**Comment by GitHub-CHKM** [comment]
More information, I am using the Bare-Metal implementation with GNS3-Server installed on Ubuntu 18.04.5 LTS.

**Comment by grossmj** [comment]
I am sorry, we (developers) don't really have much time to try appliances. I recommend you post on http://gns3.com so you can have other users helping you. Thanks.
