### ISSUE TITLE
2.2 : can't use wic adapters added on running routers

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3082]
Hi

On GNS3 2.2, i put on the topology 2 dynamips Cisco router (c3725-adventerprisek9-mz.124-25d) : R1 and R2

I start them

For each router, in the configure menu, in Slots, in Adapters WICS, i set "wic 0" to "WIC-2T"

I use the mode "add a link". 
On R1, i choose Serial0/0
On R2, i choose Serial0/0

But GNS3 doesn't add the link :-(

**Comment by grossmj** [comment]
Can you do it when the routers are not already running?

**Comment by pythonyalfa** [comment]
You can try restarting the program. Also, it could be the images you are using. I asked this question way back and some images just won’t work right in GNS3. I don’t have the link to the thread, but it could be the images. GNS3 is sort of strict on what devices you can use.

**Comment by Raizo62** [comment]
@grossmj : yes, the links can be add on running router, if the adapter is plugged when the router is off

**Comment by grossmj** [comment]
> yes, the links can be add on running router, if the adapter is plugged when the router is off

That's why, you cannot add WICs on a running router just like on a real router. You should have got an error, I will check why you didn't.

**Comment by grossmj** [comment]
Fixed.
