### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by hussamfadl** [GNS3/gns3-gui#3083]
Hi .I am running Palo Alto  8.1.10 VM , 3 Webterm and 2 Networker Toolkit.
The CPU jumps to 100 %  when I boot the PA VM and after 2 minutes it goes to 30%
My Specs : Intel i7 10th gen
I have allocated to GNS VM 8 GM RAM and 2 CPU with 2 Sub-Cores 
Should I allocate more CPU ?

**Comment by grossmj** [comment]
I think you should expect more CPU to be used when an appliance is booting, I wouldn't worry too much provided it goes back to 30% after the boot process is completed. However, allocating more CPU would probably means everything boot faster.

**Comment by hussamfadl** [comment]
@grossmj
Thank you for you replay
