### ISSUE TITLE
Security issue link is broken on github.

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3085]
**Before you start**
The link to submit a security bug is broken. It currently points to 
http://docs.gns3.com/1ON9JBXSeR7Nt2-Qum2o3ZX0GU86BZwlmNSUgvmqNWGY/index.html
which seems to 404 or whatever github's version of that is.

**Describe the bug**
Its unclear how to submit security issues because of this. I don't have any to report just noticed in passing.

**GNS3 version and operating system (please complete the following information):**
 - OS: N/A
 - GNS3 version N/A
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
Go to git hub page, scroll to end click link

**Screenshots or videos**
N/A 

**Additional context**
Its currently raining.

**Comment by grossmj** [comment]
Thanks, fixed (will be merged on master soon)
