### ISSUE TITLE
Can’t drag appliances 

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3088]
The problem still persists of dragging appliances 
From version 2.2.14 till 2.2.16 Mac OS Catalina not sure what the issue is 
In order to get gns working I’ll have to reinstall gns again and then run it 
So not sure if it’s Mac OS problem or gns 
Any suggestions please

**Comment by grossmj** [comment]
See https://github.com/GNS3/gns3-gui/issues/3087
