### ISSUE TITLE
Improve interface naming convention for well know images

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-gui#309]
There are types of well know images that have a different naming convention than just Ethernet0 , Ethernet1 ecc.

For example:

Titanium image (Nexus 7K) - Ethernet 0 is always "mgmt0" and Ethernet1 --> Ethernet 48 are mapped to Ethernet 2/1 to 2/48

vIOS-Layer 2 - GigabitEthernet 0/0 - 0/3 , 1/0 - 1/3 (same as IOU, but is "GIGA" )

vIOS (Layer 3) - GigabitEthernet 0/0 , 0/1 , 0/2 , 0/3 , 0/4, ecc

CSR1000v - All interfaces are GigabitEthernet0, GigabitEthernet1, GigabitEthernet2, ecc

IOS-XRv - Ethernet 0 is always "MgmtEth0/0/CPU0/0" , Ethernet 1 to 7 for example, match to GigabitEthernet0/0/0/0, GigabitEthernet0/0/0/1, GigabitEthernet0/0/0/2, ecc

ASAv - Ethernet 0 is always "Management0/0" , Ethernet 1 to 7 for example, match GigabitEthernet 0/0 , 0/1 , 0/2 , 0/3 , 0/4, ecc

It would be good to have templates for those well known devices with interface names matching the actual names visible on the device itself, or , if possible, do the same as VIRL, where the user can decide what interface name to use:

![untitled](https://cloud.githubusercontent.com/assets/4518931/7444504/6ebea164-f186-11e4-8013-767895e62e80.png)

**Comment by grossmj** [comment]
@anubisg1 do you know what is segment sizes?

**Comment by anubisg1** [comment]
yes. it means after how many interfaces you increase the first number ... example is iou or vios-layer2.

you have 12 ethernet  interfaces, segment size is 4 . what that means is that you have:

interface ethernet {a}/{b}

you have a counter for "a" that increases by one everytime b is increased 4 times and b is reset to 0:

i.e.:

0/0  (1) b=0
0/1 (2) b=b+1
0/2 (3) b=b+1
0/3 (4)  ---> b=b+1

1/0 (1) a=a+1 , b=0
1/1 (2) b=b+1
1/2 (3) b=b+1
1/3 (4)  ---> b=b+1

2/0 (1) a=a+1 , b=0

ecc ecc

**Comment by grossmj** [comment]
@anubisg1 thanks for the details. One last question, do you know how is used the "min interface" value?

Thanks,

**Comment by anubisg1** [comment]
i am not sure, but i believe that min interfaces and max interfaces, are the minimum number of interfaces required for the device to boot and the max number of interfaces supported.

this might be tricky to implement as VIRL is using openstack to handle this part. i don't know if passing commands directly to qemu we are able to influence this as is my understanding that we can influence the number of adapters that are "connected" nor the ones "installed"


i.e. if the image has 8 adapters and i put 2 adapters, i'll see 2 up and 6 down.

**Comment by grossmj** [comment]
I've implemented custom port names for Qemu, VirtualBox and VMware however I do not support management interface names yet.

How does VIRL knows the name of the management interface for specific VMs? Is it safe to assume there can only be one management interface and it will always be the first interface?

I am thinking have an optional field to name the first interface and then use the interface name format to name the remaining ones.

**Comment by grossmj** [comment]
Management interface names supported :)

**Comment by noplay** [comment]
Yeah I think for VIRL the first port is always the management interface.

**Comment by anubisg1** [comment]
well, we can have it for the well known images as wrote in the first posts. the following ones have management interface, and is always the 1st port:

Titanium image (Nexus 7K) - Ethernet 0 is always "mgmt0" and Ethernet1 --> Ethernet 48 are mapped to Ethernet 2/1 to 2/48

IOS-XRv - Ethernet 0 is always "MgmtEth0/0/CPU0/0" , Ethernet 1 to 7 for example, match to GigabitEthernet0/0/0/0, GigabitEthernet0/0/0/1, GigabitEthernet0/0/0/2, ecc

ASAv - Ethernet 0 is always "Management0/0" , Ethernet 1 to 7 for example, match GigabitEthernet 0/0 , 0/1 , 0/2 , 0/3 , 0/4, ecc

**Comment by grossmj** [comment]
Ok, the custom port support in GNS3 will be able to handle all this cases :)

Thanks,

**Comment by anubisg1** [comment]
great, thank you!

**Comment by grossmj** [comment]
@anubisg1 do you know how VIRL handle this case? https://community.gns3.com/thread/22344

Thanks,
