### ISSUE TITLE
GNS3 2.2.16 Virtualbox 

### ISSUE THREAD

**Issue by GuidoVDV** [GNS3/gns3-gui#3090]
Hi

I downloaded the Virtualbox GNS appliance (v.2.2.16). Tried it first in Linux - Virtualbox (Versie 5.2.36 r135684 (Qt5.9.5)). There I get a CLI screen, no gui. I don't know how to go further with this.
Then I tried it in Windows - Virtualbox (v.6.1.4). There I get a black screen...

So... How to use the VirtualBox appliance?
tia
Guido

**Comment by grossmj** [comment]
Do you mean the GNS3 VM or using a VirtualBox VM inside a GNS3 project?

**Comment by grossmj** [comment]
Please, do you have screenshots?
