### ISSUE TITLE
Add a Confirmation Prompt to the Start/Suspend/Stop/Reload All Nodes Buttons

### ISSUE THREAD

**Issue by maxabaumgarten** [GNS3/gns3-gui#3091]
**Is your feature request related to a problem? Please describe.**

Myself and coworkers constantly find ourselves accidently hitting the Start/Suspend/Stop/Reload buttons and destroying entire projects due to sudden shutdowns/reboots.  This, as you can imagine, causes huge frustration when dealing with massive projects with hundreds of VMs.  Additionally, this also causes a huge load and strain on our CPUs/Disks when you are suddenly rebooting 100+ VMs at once.

**Describe the solution you'd like**

I think a simple confirmation prompt that pops up when you hit one of the Start/Suspend/Stop/Reload buttons that says "Are you sure you want to Start/Suspend/Stop/Reload?" would immediately solve this issue.  An option to disable the prompt would be useful to those who don't suffer from this issue.

Example Scenario:
User: Clicks 'Stop All Nodes' button.
GNS3 Popup Promt: Are you sure you want to Stop All Nodes? Yes/No
**Option A.**
User: Clicks No - Nodes do not stop
**Option B.**
User: Clicks Yes - All Nodes Stop

**Describe alternatives you've considered**

I tried improving my mouse control skills, but it hasn't helped.

**Additional context**

This reminds me of the John Cena Meme where he says "ARE YOU SURE ABOUT THAT?"

**Comment by spikefishjohn** [comment]
[https://github.com/GNS3/gns3-gui/pull/3097](url)
w00t! first pull request! Exicting!

**Comment by maxabaumgarten** [comment]
Great work @spikefishjohn !  Millions of VMs will be saved from certain death because of your contribution!
