### ISSUE TITLE
buggy display with tmux in telnet console of qemu

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3094]
Hi

On LiveRaizo, i have a QEmu VM with telnet console type.

In this console, when i use tmux, and play with tab and nano , le green bar goes up.

I opened an issue in the tmux github : https://github.com/tmux/tmux/issues/2459
You can see screenshot and details.

I believed that "nano" does something which solves the problem, but not.

When i open a classic xterm on LiveRaizo, and connect to the VM with telnet/ssh, the green bar doesn't go up.
Then it seems that GNS3/ubridge/dynamips does something between the xterm of GNS3 and the VM.

This issue is not new, but i was seeking elsewhere

Have you an idea ?

**Comment by Raizo62** [comment]
To proof that the bug comes from GNS3, i have start the VM directly from the cli command qemu.
Next, i removed the parameter one by one

Finaly, it seems that the bug comes from the parameter "-nographic".

If i remove this option, i can't reproduce the buggy display.

For memory, the commands to reproduce the bug are :
```
reboot # seems necessary
tmux
ip a
CTRL+B
nano
CTRL+B
LEFT TAB
LEFT TAB
```

**Comment by grossmj** [comment]
Sounds more like a Qemu issue.

**Comment by Raizo62** [comment]
is "-nographic" still useful ? I removed it and i don't see dysfunctionality

**Comment by grossmj** [comment]
`-nographic` is only used if Qemu version < 3.0 and the configured console type is telnet. Do you see a `-display none` after removing `-nographic`?

**Comment by Raizo62** [comment]
> Do you see a `-display none` after removing `-nographic`?

Yes, i see it

**Comment by grossmj** [comment]
> Yes, i see it

Ok, then it is fine to remove `-nographic` (is it from your template settings?)

**Comment by Raizo62** [comment]
> is it from your template settings?

Yes. When i create a QEmu VM with defaults values, the "-nographic" option is already set

**Comment by grossmj** [comment]
> Yes. When i create a QEmu VM with defaults values, the "-nographic" option is already set

Ok, I found out that the GUI actually adds the "-nographic" by default. I will remove this :+1:
