### ISSUE TITLE
when closing GNS3 remover all dockers created on the VM

### ISSUE THREAD

**Issue by cischology** [GNS3/gns3-gui#3095]
![image](https://user-images.githubusercontent.com/56488147/99189469-2052e780-2716-11eb-90db-e556adace535.png)
as a work around , I ssh to GNS3 VM and docker stop, docker rm all containers. 

would it be possible when shutting down GNS3 , these commands be executed on the GNS3 VM?

**Comment by grossmj** [comment]
Please tell us why you need this? Thanks.

**Comment by cischology** [comment]
Are you waiting on info from me? I thought it would be helpful when users shutdown / close GNS3/project all the dockers will be removed to avoid the errors originally attached. let me know if I can be of any help.

**Comment by grossmj** [comment]
Sorry, I cannot reproduce this issue. What are the steps that lead to that problem? Thanks.

**Comment by cischology** [comment]
one of two things, either I :
1) had the lab running over night and tried to connect after session timed out 
or
2) I connected to work vpn and then disconnect from vpn and tried to access the lab again.
