### ISSUE TITLE
GNS3 app not working in MacOS Big Sur.

### ISSUE THREAD

**Issue by Raul-Flores** [GNS3/gns3-gui#3096]
I updated my macOS to the Big Sur version but it was impossible for me to start the application in this new version of the operating system, there are any plans to patch it and make it run, I am using a Macbook pro from the year of 2017, and previously in Catalina it worked no problem, hope they can solve the problem.

**Comment by cristian-ciobanu** [comment]
This is a duplicate of the following issue #3037. You can close this one and continue to check the progress on the existing issue.

**Comment by Raul-Flores** [comment]
Ok thanks
