### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by Bugman-creator** [GNS3/gns3-gui#3098]
**Before you start**

This is for a class project. This is a list of checked output from a Static Code Analysis tool

**Describe the bug**

N/A

**GNS3 version and operating system (please complete the following information):**

N/A

**To Reproduce**

N/A

**Screenshots or videos**

N/A

**Additional context**

N/A

[gns3SCAResults.txt](https://github.com/GNS3/gns3-gui/files/5578594/gns3SCAResults.txt)

**Comment by grossmj** [comment]
I have reviewed everything and I believe there is no security issues, many of the reported issues are for test purposes. Thanks for pointing them out though 👍
