### ISSUE TITLE
Link becomes down when one host is down

### ISSUE THREAD

**Issue by Str1ker17** [GNS3/gns3-gui#3099]
**Describe the bug**
Link becomes down when one host is down after "Stop" command. This causes packet capture to stop.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 7 x64
 - GNS3 version 2.2.16
 - GNS3VM inside VMWare as a remote server

**To Reproduce**
1. Create a new project
2. Put two hosts, for example ipterm-1 and ipterm-2 (or vpcs-1 and vpcs-2) and connect ipterm-1 with a link to ipterm-2
3. Start ipterm-1 and ipterm-2
4. Start packet capture on a link
5. Stop ipterm-1
6. See that packet capture was stopped

Probably this is the way that it's meant to be, but this causes complications when restarting nodes via "Stop - Start" sequence since the "Reload" feature doesn't work with most appliances.

**Comment by grossmj** [comment]
> Probably this is the way that it's meant to be, but this causes complications when restarting nodes via "Stop - Start" sequence since the "Reload" feature doesn't work with most appliances.

It's meant to be since if you stop a node, the links connected to it are also shutdown. I am going to check the complications you reported to see if we can do something about it. Thanks :+1:
