### ISSUE TITLE
qemu 5.0.0 : warning: 'ide-drive' is deprecated

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3101]
Hi

With QEMU emulator version 5.0.0 (Debian 1:5.0-14~bpo10+1)

The logs say that 'ide-drive' is deprecated and you must use 'ide-hd' or 'ide-cd' instead : 

`qemu-system-x86_64: -device ide-drive,drive=drive0,bus=ahci0.0,id=drive0: warning: 'ide-drive' is deprecated, please use 'ide-hd' or 'ide-cd' instead`

**Comment by grossmj** [comment]
Correct, `ide-drive` is deprecated since Qemu version 4.2: https://www.qemu.org/docs/master/system/deprecated.html#ide-drive-since-4-2

Thanks for pointing this out.

**Comment by grossmj** [comment]
Should be good now.
