### ISSUE TITLE
Telnet - No console response on IOSvL2 Switch but working on IOU Router

### ISSUE THREAD

**Issue by ksinghnote** [GNS3/gns3-gui#3102]
MAC Big Sur
--------------
GNS3 management console.
Running GNS3 version 2.2.17dev1 on Darwin (64-bit) with Python 3.6.5 Qt 5.11.0 and PyQt 5.10.1.
Copyright (c) 2006-2020 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> GNS3 version 2.2.17dev1 is not the same as the GNS3 VM version 2.2.16. Please upgrade the GNS3 VM.
Using different versions may result in unexpected problems. Please use at your own risk.
The GNS3 VM (IP=172.16.155.2, NETWORK=172.16.155.0/24) is not on the same network as the local server (IP=127.0.0.1, NETWORK=127.0.0.0/8), please make sure the local server binding is in the same network as the GNS3 VM

QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name CiscoIOSvL2-1 -m 768M -smp cpus=1,sockets=1 -enable-kvm -machine smm=off -boot order=c -drive file=/opt/gns3/projects/f38454cf-7ec6-48a3-8c0b-e604e4b8c918/project-files/qemu/edb7dde5-3323-4bc4-a736-000675e8f5e2/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -uuid edb7dde5-3323-4bc4-a736-000675e8f5e2 -serial telnet:127.0.0.1:5003,server,nowait -monitor tcp:127.0.0.1:38765,server,nowait -net none -device e1000,mac=0c:c9:18:f5:e2:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:20033,localaddr=127.0.0.1:20032 -device e1000,mac=0c:c9:18:f5:e2:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:20035,localaddr=127.0.0.1:20034 -device e1000,mac=0c:c9:18:f5:e2:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:20037,localaddr=127.0.0.1:20036 -device e1000,mac=0c:c9:18:f5:e2:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:20039,localaddr=127.0.0.1:20038 -device e1000,mac=0c:c9:18:f5:e2:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:20041,localaddr=127.0.0.1:20040 -device e1000,mac=0c:c9:18:f5:e2:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:20043,localaddr=127.0.0.1:20042 -device e1000,mac=0c:c9:18:f5:e2:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:20045,localaddr=127.0.0.1:20044 -device e1000,mac=0c:c9:18:f5:e2:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:20047,localaddr=127.0.0.1:20046 -device e1000,mac=0c:c9:18:f5:e2:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:20049,localaddr=127.0.0.1:20048 -device e1000,mac=0c:c9:18:f5:e2:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:20051,localaddr=127.0.0.1:20050 -device e1000,mac=0c:c9:18:f5:e2:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:20053,localaddr=127.0.0.1:20052 -device e1000,mac=0c:c9:18:f5:e2:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:20055,localaddr=127.0.0.1:20054 -device e1000,mac=0c:c9:18:f5:e2:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:20057,localaddr=127.0.0.1:20056 -device e1000,mac=0c:c9:18:f5:e2:0d,netdev=gns3-13 -netdev socket,id=gns3-13,udp=127.0.0.1:20059,localaddr=127.0.0.1:20058 -device e1000,mac=0c:c9:18:f5:e2:0e,netdev=gns3-14 -netdev socket,id=gns3-14,udp=127.0.0.1:20061,localaddr=127.0.0.1:20060 -device e1000,mac=0c:c9:18:f5:e2:0f,netdev=gns3-15 -netdev socket,id=gns3-15,udp=127.0.0.1:20063,localaddr=127.0.0.1:20062 -display none -machine pc-q35-4.2

Execution log:
qemu-system-x86_64: -enable-kvm: unsupported machine type 'pc-q35-4.2'
Use -machine help to list supported machines

1#Tried removing this "pc-q35-4.2" also then no above Error but still no response from console for switch.

2#IOSvL2 Switch >> Issue
Trying 172.16.155.2...
Connected to 172.16.155.2.
Escape character is '^]'.

3#IOU Router >>No Issue
*Dec  3 03:44:17.592: %LINEPROTO-5-UPDOWN: Line protocol on Interface Serial2/1, changed state to down
IOU1#

**Comment by Raizo62** [comment]
Hi

Maybe I'm wrong , but i think that the problem is in the type of disk of IOSv.
The appliance of IOSv use "virtio" but with him, the IOS seems to boot but i don't have the console  If i use "SATA", the IOSv boots and i have the console. . (When i use "virtio" with other OS, the VM works)

**Comment by grossmj** [comment]
@ksinghnote have you been able to resolve your issue?

**Comment by Raizo62** [comment]
Hi @grossmj 

Can you verify that "virtio" is the good type of disk of IOSV and not "SATA" ? (I was going to open an issue on that)
I have see also on blog to use "virtio", but only IDE/SATA works on LiveRaizo (IDE seems too slow)

**Comment by grossmj** [comment]
> Can you verify that "virtio" is the good type of disk of IOSV and not "SATA" ? (I was going to open an issue on that)

Yes, the appliance has the good type of disk: https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosvl2.gns3a#L20

**Comment by Raizo62** [comment]
Yes, the appliance says to use "virtio". But, does it work really when you use virtio ? I have tried and i don't have the prompt with VIOS. I must use "SATA"

**Comment by Raizo62** [comment]
No, the problem with "virtio/sata" comes from me. To use "virtio", the option "-machine pc-q35-4.2" must be set and i didn't see it.
Sorry.

**Comment by ksinghnote** [comment]
I have no luck.
I just installed ver 2.2.18
L2 switch console no response while looking router is ok.

**Comment by Raizo62** [comment]
Have you verified that the md5sum of your L2 is good ?
