### ISSUE TITLE
macos bug sur gns3 gui 2.2.17 won't automatically start gns3 vm

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-gui#3103]
firstly, in the title of of this issue it is a deliberate typographical error. small attempt at humour. i know, i know, don't give up my day job...

secondly, this maybe a bug/maybe not a bug. however it is a change in behaviour compared to what i've been used to.

**Describe the bug**
on macos after starting the gns3 gui v2.2.17 the gns3 vm doesn't start automatically.

**GNS3 version and operating system (please complete the following information):**
 - OS: MacOS 11.0.1
 - GNS3 2.2.17
 - GNS3 VM 2.2.17

**To Reproduce**
1. don't have the gns3 vm 2.2.17 running
2. start the gns3 gui 2.2.17
3. gns3 vm 2.2.17 doesn't start

**Additional context**
However, if the gns3 vm 2.2.17 is already running, the gns3 gui 2.2.17 works fine.

gns3_controller.conf:
{
    "computes": [],
    "templates": [
        {
            "compute_id": "vm",
            "name": "Cisco CSR1000v 16.12.4a",
            "usage": "There is no default password and enable password. A default configuration is present.",
            "category": "router",
            "symbol": ":/symbols/router.svg",
            "template_type": "qemu",
            "adapter_type": "vmxnet3",
            "adapters": 4,
            "ram": 3072,
            "console_type": "telnet",
            "options": "",
            "hda_disk_image": "csr1000v-universalk9.16.12.04a-serial.qcow2",
            "qemu_path": "/usr/bin/qemu-system-x86_64",
            "port_name_format": "Gi{port1}",
            "template_id": "1b8c9855-ba84-4c63-a9db-841e837183e5",
            "builtin": false,
            "platform": "i386",
            "linked_clone": true,
            "cpus": 1,
            "mac_address": "",
            "first_port_name": "",
            "port_segment_size": 0,
            "console_auto_start": false,
            "boot_priority": "c",
            "hda_disk_interface": "ide",
            "hdb_disk_image": "",
            "hdb_disk_interface": "ide",
            "hdc_disk_image": "",
            "hdc_disk_interface": "ide",
            "hdd_disk_image": "",
            "hdd_disk_interface": "ide",
            "cdrom_image": "",
            "initrd": "",
            "kernel_image": "",
            "bios_image": "",
            "kernel_command_line": "",
            "legacy_networking": false,
            "replicate_network_connection_state": true,
            "on_close": "power_off",
            "cpu_throttling": 0,
            "process_priority": "normal",
            "custom_adapters": [],
            "default_name_format": "{name}-{0}"
        }
    ],
    "gns3vm": {
        "vmname": "GNS3 VM",
        "when_exit": "keep",
        "headless": false,
        "enable": true,
        "engine": "vmware",
        "allocate_vcpus_ram": true,
        "ram": 65535,
        "vcpus": 8,
        "port": 80
    },
    "iou_license": {
        "iourc_content": "",
        "license_check": true
    },
    "appliances_etag": null,
    "version": "2.2.17"
}

gns3_gui.conf:
{
    "Builtin": {
        "default_nat_interface": "vmnet8"
    },
    "Docker": {
        "containers": []
    },
    "Dynamips": {
        "allocate_aux_console_ports": false,
        "dynamips_path": "",
        "ghost_ios_support": true,
        "mmap_support": true,
        "sparse_memory_support": true
    },
    "GraphicsView": {
        "default_label_color": "#000000",
        "default_label_font": "Helvetica Neue,12,-1,5,75,0,0,0,0,0,Bold",
        "default_note_color": "#000000",
        "default_note_font": "Helvetica Neue,12,-1,5,50,0,0,0,0,0,Regular",
        "draw_link_status_points": true,
        "draw_rectangle_selected_item": true,
        "drawing_grid_size": 25,
        "grid_size": 75,
        "limit_size_node_symbols": true,
        "scene_height": 1000,
        "scene_width": 2000,
        "show_grid": false,
        "show_grid_on_new_project": true,
        "show_interface_labels": false,
        "show_interface_labels_on_new_project": false,
        "show_layers": false,
        "snap_to_grid": false,
        "snap_to_grid_on_new_project": true,
        "zoom": null
    },
    "IOU": {
        "iourc_content": "",
        "license_check": true
    },
    "MainWindow": {
        "check_for_update": true,
        "debug_level": 0,
        "delay_console_all": 500,
        "direct_file_upload": false,
        "experimental_features": false,
        "geometry": "AdnQywADAAAAAAAAAAAAGQAACf8AAAWfAAAAAAAAADUAAAn/AAAFnwAAAAACAAAACgAAAAAAAAAANQAACf8AAAWf",
        "hdpi": true,
        "hide_getting_started_dialog": false,
        "hide_new_template_button": false,
        "hide_setup_wizard": true,
        "last_check_for_update": 1607073582,
        "multi_profiles": false,
        "overlay_notifications": true,
        "recent_files": [
            "/Users/jnatschev/GNS3/projects/jnipv6/jnipv6.gns3"
        ],
        "recent_projects": [
            "2801b9c9-5722-4618-9e95-f4f576ecf11a:jnipv6:/Users/jnatschev/GNS3/projects/jnipv6/jnipv6.gns3"
        ],
        "send_stats": true,
        "spice_console_command": "/Applications/RemoteViewer.app/Contents/MacOS/RemoteViewer spice://%h:%p",
        "state": "AAAA/wAAAAD9AAAAAwAAAAAAAAAAAAAAAPwCAAAAAfsAAAAiAHUAaQBOAG8AZABlAHMARABvAGMAawBXAGkAZABnAGUAdAAAAAAA/////wAAAIkA////AAAAAQAAAYwAAARG/AIAAAAC+wAAADYAdQBpAFQAbwBwAG8AbABvAGcAeQBTAHUAbQBtAGEAcgB5AEQAbwBjAGsAVwBpAGQAZwBlAHQBAAAALwAAAiMAAABZAP////sAAAA0AHUAaQBDAG8AbQBwAHUAdABlAFMAdQBtAG0AYQByAHkARABvAGMAawBXAGkAZABnAGUAdAEAAAJYAAACHQAAAFkA////AAAAAwAACcAAAADT/AEAAAAB+wAAACYAdQBpAEMAbwBuAHMAbwBsAGUARABvAGMAawBXAGkAZABnAGUAdAEAAABAAAAJwAAAAEYAB///AAAILgAABEYAAAAEAAAABAAAAAgAAAAI/AAAAAIAAAAAAAAAAQAAACIAdQBpAEIAcgBvAHcAcwBlAHIAcwBUAG8AbwBsAEIAYQByAwAAAAD/////AAAAAAAAAAAAAAACAAAAAwAAACAAdQBpAEcAZQBuAGUAcgBhAGwAVABvAG8AbABCAGEAcgEAAAAA/////wAAAAAAAAAAAAAAIAB1AGkAQwBvAG4AdAByAG8AbABUAG8AbwBsAEIAYQByAQAAAGL/////AAAAAAAAAAAAAAAmAHUAaQBBAG4AbgBvAHQAYQB0AGkAbwBuAFQAbwBvAGwAQgBhAHIBAAABmP////8AAAAAAAAAAA==",
        "stats_visitor_id": "a3cbf99e-a603-4cc4-8656-b7611b31da52",
        "style": "Legacy",
        "symbol_theme": "Classic",
        "telnet_console_command": "osascript -e 'set posix_path to do shell script \"echo \\\"$PATH\\\"\"' -e 'tell application \"Terminal\"' -e 'activate' -e 'do script \"echo -n -e \\\"\\\\033]0;%d\\\\007\\\"; clear; PATH=\" & quoted form of posix_path & \" telnet %h %p ; exit\"' -e 'end tell'",
        "vnc_console_command": "osascript -e 'tell application \"Screen Sharing\"' -e '   display dialog \"WARNING OSX VNC support is limited if you have trouble connecting to a device please use an alternative client like Chicken of the VNC.\" buttons {\"OK\"} default button 1 with icon caution with title \"GNS3\"' -e '  open location \"vnc://%h:%p\"' -e 'end tell'"
    },
    "NodesView": {
        "nodes_view_filter": 0
    },
    "PacketCapture": {
        "command_auto_start": true,
        "packet_capture_analyzer_command": "",
        "packet_capture_reader_command": "tail -f -c +0 %c | /Applications/Wireshark.app/Contents/MacOS/Wireshark -o \"gui.window_title:%d\" -k -i -"
    },
    "Qemu": {
        "enable_hardware_acceleration": true,
        "require_hardware_acceleration": true
    },
    "VMware": {
        "block_host_traffic": false,
        "host_type": "ws",
        "vmnet_end_range": 100,
        "vmnet_start_range": 2,
        "vmrun_path": ""
    },
    "VPCS": {
        "vpcs_path": ""
    },
    "VirtualBox": {
        "vboxmanage_path": ""
    },
    "type": "settings",
    "version": "2.2.17"
}

gns3_server.conf:
[Server]
path = /Applications/GNS3.app/Contents/MacOS/gns3server
ubridge_path = /Applications/GNS3.app/Contents/MacOS/ubridge
host = 192.168.255.1
port = 3080
images_path = /Users/jnatschev/GNS3/images
projects_path = /Users/jnatschev/GNS3/projects
appliances_path = /Users/jnatschev/GNS3/appliances
additional_images_paths = 
symbols_path = /Users/jnatschev/GNS3/symbols
configs_path = /Users/jnatschev/GNS3/configs
report_errors = True
auto_start = True
allow_console_from_anywhere = False
auth = True
user = admin
password = fYbHWU0cDYCo0oZgcLNsPRUbK8YjN52ltBVfn3fsV5NGhlGHqIszv4elnznt2AyN
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10000
udp_end_port_range = 20000

**Comment by benali125** [comment]
I have a Mac so I’ll give it a try and let you know 
Even though worked fine for me yesterday 
Is Big Sur

**Comment by benali125** [comment]
Ok everything seems to be working fine 
Gns3  2.2.17 and gns vm 2.2.17 
I’m running gns vm on VMware fusion pro 12.1.0

**Comment by jnatschev** [comment]
yeah. right. @benali125, it seems that you and i have the same configuration. for you it works for me it doesn't. i did neglect to add the version of vmware fusion, it is 12.1.0.

**Comment by benali125** [comment]
Make sur your gns3 and gns vm are on the same network 
Also try uninstall gns3 and reinstall it 
Hopefully works 
Good luck 
I know gns3 on Mac OS hasn’t been the same since 2.2.13

**Comment by jnatschev** [comment]
ok. went through each configuration attribute/value pair. found a typographical error. in the gui for the gns3 vm configuration items, i set up the number of cpus and ram. for ram i had 65535 rather than 65536. once i change the value from 65535 to 65536 it all started working. apologies for the distraction.

closing this now.

**Comment by benali125** [comment]
I’m glad it’s working now

Sent from my iPhone

On Dec 5, 2020, at 7:11 PM, John Natschev <notifications@github.com> wrote:

﻿

ok. went through each configuration attribute/value pair. found a typographical error. in the gui for the gns3 vm configuration items, i set up the number of cpus and ram. for ram i had 65535 rather than 65536. once i change the value from 65535 to 65536 it all started working. apologies for the distraction.

closing this now.
