### ISSUE TITLE
macos bug sur and gns3 network interaction

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-gui#3106]
hi.

this is more of a report rather than a development request.

what i have found is that with macos big sur and vmware fusion 12.1.0 from a network adaptor perspective is that a bridge adaptor is created. what this means is, say one creates a vmware fusion custom network, we'll call it vmnet2, and associates the gns3 vm with it on network adaptor, the network adaptor is not visible until the gms3 vm is started. when viewing the macos big sur network adaptors with ifconfig, it is displayed as bridge101 with an ipv4 address as defined for vmnet2. from here if you start the gns3 gui and associate the server with this ipv4 address all is good.

quit the gns3 gui, shutdown the gns3 vm, and then start the gns3 gui, the gns3 app cannot find the network adaptor named bridge101 because the gms3 vm is shutdown.

doesn't seem that much can be done about it until macos/vmware sort themselves out.

so in the mean time, i need to remember to manually start the gns3 vm to ensure the bridge101 network adaptor exists prior to starting the gns3 gui.

john.

**Comment by jnatschev** [comment]
also, associating gns3 server with the macos big sur network adaptor, en0, does start the gns3 vm automatically. however because the gns3 vm is associated with vmnet2, gns3 gui reports that the gns3 server and gns3 vm are on different subnets.

conversely, associating gns3 server with "localhost" behaves the same.


john.

**Comment by grossmj** [comment]
Noted, thanks for the report. Indeed there isn't much we can do on our side I think.

**Comment by grossmj** [comment]
Please try this development version: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-06-08/2.2/GNS3-2.2.22dev1.dmg/download

This should fix this issue. It works on my side but please confirm. Thanks :+1:

**Comment by grossmj** [comment]
I will consider it fixed. Please comment back or open a new issue if something does not work as expected. Thanks.
