### ISSUE TITLE
Enable to drag appliances 

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3107]
This issu never been solved since gns3. 2.2.14 till now on Mac OS 
I have to uninstall and reinstall gns3.app 
![6683E235-9A0E-42F5-988A-F21E02464C51](https://user-images.githubusercontent.com/52331820/101294479-5abb1c00-37cc-11eb-98a3-d36d5ef0cb13.jpeg)

- that’s another issu I encountered today while trying to save a project 
- another problem is I can’t open saved project simply nothing happens 
I’m using gns3 2.2.17 
Mac OS Big Sur 

**
Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by jnatschev** [comment]
that's really strange. i've tried to reproduce what you've experienced using gns3 2.2.17 on macos big sur and i cannot. i can open an existing project and then "Save project as..." and it all works.

are you using GNS3 VM?

**Comment by benali125** [comment]
Not sure to be honest 
The problem started with version 2.2.14 and on and never been solved 
The only way is to delete the gns app and reinstall again 
And yes I’m using gns vm

**Comment by jnatschev** [comment]
weird. i wish i could offer something more. not only do i have gns3 2.2.17 (gui, server, and vm) on macos big sur as a native installation, i also have it working in a python3.7, python3.8, and python3.9 environment after doing a "pip install gns3-gui gns3-server" in each environment and starting the server manually:
python -m gns3server --local --daemon
python -m gns3

**Comment by benali125** [comment]
Thank you 
The issue is been mentioned in gns3 community since 2.2.14

**Comment by grossmj** [comment]
Does this happen only with Docker appliances?

**Comment by benali125** [comment]
No sir 
With every appliance like I said before starts happening since 2.2.14 
I haven’t updated gns3 to 2.2.18 but as far as 2.2.17 same issue max os Big Sur

**Comment by grossmj** [comment]
Thanks, this should fix this issue: https://github.com/GNS3/gns3-server/commit/055a78bade41ec0b80ec16b21181486f0aa1f6af

Please let me know if you still have the problem in the next release.
