### ISSUE TITLE
macos big sur, gns3 2.2.17, vmware fusion 12.1.0, no telnet output to a csr1000v appliance in a topology

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-gui#3108]
**Describe the bug**
telnet connects to csr1000v appliance in a topology but no output displayed

**GNS3 version and operating system (please complete the following information):**
 - macos big sur 11.0.1
 - GNS3 version 2.2.17 (gui, server, vm)
 - Any use of the GNS3 VM: yes. vmware fusion 12.1.0

**To Reproduce**
1. Start VM (to establish the bridge101 adaptor
2. Start gns3 gui
3. create a new topology
4. add a single csr1000v appliance instance in the topology
5. telnet to the ipv4 address on the port number
6. no output (even after two to three minutes

**Comment by benali125** [comment]
I had the same issu with Firefox and webterm appliance no telnet session

**Comment by jnatschev** [comment]
yes. i tried to run the same topology in the webui - a single csr1000v - and tried the web console and couldn't see any output. the difference between the two being that using the telnet <ipv4address> 5000 i could see that the telnet session was connected; just no output was displayed.

**Comment by jnatschev** [comment]
now i've tried a number of permutations to get telnet working again to no avail. remove gns3 from /Applications and delete the gns3 vm, install 2.2.17 (and 2.2.16), and no won't work. even tried new conda installs and, yet again, no go. strange. it was working, which is what i reported in the original issue #3037. i'm at a loss now.

**Comment by jnatschev** [comment]
tried 2.2.16 and 2.2.17 with gns3 vm running on virtualbox and topologies containing csr1000v 16.9.6 and csr1000v 16.12.4a. i was able to start the csr device in the topology. go to terminal and telnet to the device on its ipv4 address and port number. i got output. unfortunately the device gets to a point its boot process and from there no more output in the telnet session.

for 16.12.4a:
  Booting `CSR1000v - packages.conf'


BOOT CMD: /packages.conf rw root=/dev/ram max_loop=64 HARDWARE=virtual quiet
console= SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   c80d3e11:d9714d9:c22360c4:981ae6b3:44fe23df
        expected     c80d3e11:d9714d9:c22360c4:981ae6b3:44fe23df
package header rev 3 structure detected
IOSXE version 16.12.04a detected
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   5b586785:8c474ccf:1be2859e:c41341d6:6a76f37b
        expected     5b586785:8c474ccf:1be2859e:c41341d6:6a76f37b
Package type:0x7531, flags:0x0
linux image, size=0x64e9d0
linux isord, size=0x2548222

%IOSXEBOOT-4-PART_VERIFY: (local/local): Verifying partition table for device /dev/bootflash...
%IOSXEBOOT-4-PART_VERIFY: (local/local): Selected MBR v2 partition layout.

for 16.9.6:
  Booting 'CSR1000v - packages.conf'

root (hd0,0)
 Filesystem type is ext2fs, partition type 0x83
kernel /packages.conf rw quiet root=/dev/ram console= max_loop=64 HARDWARE=virt
ual SR_BOOT=bootflash:packages.conf
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   c6b46152:a9b9ee8c:c142c081:1edfa712:85d57549
        expected     c6b46152:a9b9ee8c:c142c081:1edfa712:85d57549
package header rev 3 structure detected
Calculating SHA-1 hash...done
SHA-1 hash:
        calculated   53edcb4f:91a45740:849a31c4:581ee791:e06d9573
        expected     53edcb4f:91a45740:849a31c4:581ee791:e06d9573
Package type:0x7531, flags:0x0
   [Linux-bzImage, setup=0x3c00, size=0x522df0]
   [isord @ 0x7deac000, 0x21431e9 bytes]

%IOSXEBOOT-4-BOOT_SRC: (rp/0): Checking grub versions 1.0 vs 1.0
%IOSXEBOOT-4-BOOT_SRC: (rp/0): No need for bootloader upgrade.

this is really weirding me out...

**Comment by jnatschev** [comment]
ok. the strangest thing happened. telnet to a csr1000v 16.12.4a (or 16.9.6) now works. 2.2.17. oh, by the way, the gns3 vm settings have the hardware version set to 18.

i kept trying a variety of permutations and nothing was working.

with gns3 vm on virtualbox, the csr1000v kept rebooting. this was visible during the telnet session.

i modified the gns3 vm setting in fusion. the settings for the gns3 vm were 8 cores and 64G of ram. i turned off "Enable hypervisor applications in the virtual machine". started the gns3 vm manually, started gns3 gui, opened a topology containing a single csr1000v 16.12.4a, and started the router. result was a kvm message. ok. so far so good.

quit gns3 gui and shutdown the gns3 vm.

reenable "Enable hypervisor applications in the virtual machine". start the gns3 vm manually, start the gns3 gui, open the topology, start the csr1000v, and telnet to the csr1000v. telnet connects but no output.

quit the gns3 gui, shutdown the gns3 vm, change the number of cores to 1 and change the memory allocation to 16GB (16384MB). start the gns3 vm manually, start the gns3 gui, load the single csr1000v topology, start the router, and telnet to the router. output now being displayed.

quit the gns3 gui, shutdown the gns3 vm, change the number of cores to 8 and change the memory allocation to 32768MB, start the gns3 vm manually, start the gns3 gui, load the single csr1000v topology, start the router, and telnet to the router. output still being displayed. YEAH!

quit the gns3 gui, shutdown the gns3 vm, changed the gns3 vm first network adaptor from "Private to my Mac" to "vmnet2". started the gns3 vm, started the gns3 gui, opened settings, changed the "Server" configuration item "Host binding" to the IPv4 address associated with the gns3 vm (oh, also, in the gns3 gui settings, the "GNS3 VM" configuration item "Action when closing GNS3" is set to "keep the GNS3 VM running"). quit the gns3 gui. start the gns3 gui, open the single csr1000v topology, start the router, and telnet to the router. and, yet again, all working.

so. in all this. i'd like to point out that the behaviour between macos "bug" sur - 11.0.1 - and vmware fusion 12.1.0 is that the host-only adaptors - private to my mac, vmnet2, vmnet3, etc. - are not visible until the virtual machine has been started. when they are visible, they display - after executing ifconfig - as bridgexxx and the enxx interface associated with the bridge. due to this, gns3 gui cannot start the gns3 vm automatically.

bit of a write up i know but in the hope it helps understand these interaction intricacies between macos 11 and vmware fusion 12.

i am now really pleased that i can have console access to my topology devices again.

cheers,
john.
