### ISSUE TITLE
HyperV appliance consistently crashes at upgrade

### ISSUE THREAD

**Issue by erwdavid** [GNS3/gns3-gui#3116]
I have a gns3 server VM (version 2.2.9) on HyperV
When trying to upgrade the server (even with apt upgrade) I get a kernel panic seemingly due to gpgv
![image](https://user-images.githubusercontent.com/10085831/105691797-f8de7f00-5efd-11eb-9a36-e7f44f2d5a25.png)

I makes upgrade impossible.

**Comment by grossmj** [comment]
Next version of the GNS3 VM will be based on Ubuntu 20.04 LTS. Let's see if this fixes this issue.

**Comment by grossmj** [comment]
@erwdavid the last GNS3 VM is on Ubuntu 20.04 LTS. Please let us know if this works on your side.
