### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#3118]
Client must be able to connect to the GNS3 server configured with SSL.

**Comment by b-ehlers** [comment]
Issue https://github.com/GNS3/gns3-server/issues/1652

SSL was removed in v2.1, from GUI in commit 56ebfc7

**Comment by grossmj** [comment]
We have added it back recently on server side. The web-ui can connect in SSL but not the GUI. Some users really want SSL and we have decided to add it back.

**Comment by ekrekeler** [comment]
When using GNS3 v2.2.25 on Windows 10 x64, I get the following error in the GUI when trying to connect to a server that uses HTTPS for the protocol:
`SSL is not supported`

This worked fine in the previous version I was using for client/server, v2.2.22. Also, I am able to connect with no issues if I run GNS3 from source off a virtual environment using python 3.9.7.

[Going off the code](https://github.com/GNS3/gns3-gui/blob/334eb5175cfa0497211c4eedf1f474055a03e925/gns3/http_client.py#L86), this looks like a check on the PyQt libraries to see if was compiled with SSL support. Is this expected?

**Comment by ekrekeler** [comment]
Also off-topic, but what are the steps to compile GNS3 for Windows targets, if I want to fix this myself?

**Comment by grossmj** [comment]
SSL support is broken in v2.2.25 because of the Qt version upgrade we have done. We recently have fixed the problem, you can try with our latest nightly build:

https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-09-26/2.2/GNS3-2.2.2021-09-26-all-in-one.exe/download
