### ISSUE TITLE
auto_open and auto_start should be exposed in project end point API

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3119]
**Before you start**
I poked around and didn't see the request.
I hope the subject is correct. I mean it sounds pretty good.

**Is your feature request related to a problem? Please describe.**
This is currently not supported. I'm not sure why. It seems like its just a bool value.
When attempting to set I get

2021-01-28 00:49:20 ERROR route.py:65 JSON schema error with API request '/v2/projects' and JSON data '{'name': 'WallStreetBetsYesFromReddit', 'auto_start': False, 'auto_close': True, 'auto_open': False, 'scene_height': 3000, 'scene_width': 6000}': Additional properties are not allowed ('auto_open', 'auto_start' were unexpected)

**Describe the solution you'd like**
Id like to be able to control this via API. I don't really know why, maybe its just really late and I'm malfunctioning [Dave](https://en.wikipedia.org/wiki/HAL_9000). Really I think auto start might be the only one interesting. I think making an API call would pretty much open the project as it is. Come to think of it I don't really know what open the project means. 

**Describe alternatives you've considered**
Be like all super lazy and just open the GNS3 gui to edit the project. Then be like, "Dave's not hear man!"

**Additional context**
I've done terrible things with security devices in GNS3 and its been super helpful in learning QEMU. Thanks for everything on this  project.

**Comment by b-ehlers** [comment]
Yes, it's true that you can't set the auto_open and auto_start parameters on project creation (POST /v2/projects). Seems to have been overlooked during a former enhancement.

As a workaround you can create a project without these parameters and update the project afterwards with [PUT /v2/projects/{project_id}](https://gns3-server.readthedocs.io/en/2.2/api/v2/controller/project/projectsprojectid.html#id11). The project update request allows to modify all parameters, including auto_open and auto_start.

**Comment by grossmj** [comment]
Thanks for catching that :+1:
