### ISSUE TITLE
Custom Console setting for node not being saved

### ISSUE THREAD

**Issue by troogyt** [GNS3/gns3-gui#3121]
**Describe the bug**
I am trying to change the console setting for a node to use a custom alternative console tool for VNC connections but the selection is not saved.

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - GNS3 version 2.2.17
 - Running GNS3 as Local Server (not using GNS3 VM or remote GNS3 server)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a topology with any host node
2. Right Click on the host node to get the context menu
3. Select 'Custom Console'
4. Choose an alternative console from the drop-down list that is not the default
5. Close the window
6. Repeat steps 2 and 3 -> the selected console is back at the default prior to changing it above.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/41710820/106351442-51fc4780-6330-11eb-8a42-601142c7e9f7.png)
then
![image](https://user-images.githubusercontent.com/41710820/106351715-d8655900-6331-11eb-8206-89b262ce0487.png)

**Comment by eantowne** [comment]
Correct me if I am wrong, but isn't the "Custom Console" option in the context menu intentionally shot-term? If you want to change the console type permanently for a node in a topology, isn't that done through the "Configure" portion of the context menu?

**Comment by grossmj** [comment]
@eantowne is correct
