### ISSUE TITLE
Error in exporting portable project with webterm appliance

### ISSUE THREAD

**Issue by mohd1024** [GNS3/gns3-gui#3123]
I am unable to Export portable projects when the Webterm appliance is used in the project. I get the following error:

```
ExportProjectWorker thread stopping with an error: project-files/docker/68f19c55-53a7-4328-8c18-422dcad43223/root/.mozilla/firefox/Crash Reports/InstallTime20200429190206 not found on compute
project-files/docker/68f19c55-53a7-4328-8c18-422dcad43223/root/.mozilla/firefox/Crash Reports/InstallTime20200429190206 not found on compute
```

GNS3 & VM version 2.2.17

**Comment by grossmj** [comment]
Looks like a similar issue with https://github.com/GNS3/gns3-gui/issues/3107

**Comment by grossmj** [comment]
This should have been fixed in https://github.com/GNS3/gns3-server/commit/6120736c911d76ffd511333d611eb1f1dfa9360c#diff-5cd8f9bc90c7bf7d575aa8efd3d4497955eee847d65463e4fca06d8461691c4b

Please try v2.2.20 once released and comment back if you still have an issue with this version. Thanks!
