### ISSUE TITLE
please add the winxp template for gns3

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#3125]
Community link: https://gns3.com/community/support/please-add-the-winxp-template-for-gns3

**Comment by b-ehlers** [comment]
The old appliance can easily be reactivated: <https://github.com/GNS3/gns3-registry/blob/bdaab166538157516818d103cf32a1f6fbe7ca5d/appliances/microsoft-windows%2Bie.gns3a>

I wanted to optimize it (<https://github.com/GNS3/gns3-registry/issues/256>), but I gave up. I wasn't satisfied with the results, that can be achieved by modifying some qemu parameters.

I'm running Windows 7 within QEMU (outside GNS3) with a good performance, mainly by adding the spice guest tools. But that can't be done with an appliance as we don't have the right to distribute a modified windows image.

**Comment by b-ehlers** [comment]
Windows XP can't be simply added to the windows appliance, as XP doesn't support the sata disk interface. But the ide disk interface is quite slow, so it's better to keep sata for Windows 7 and later. Therefore I suspect Windows XP needs a seperate appliance.

**Comment by b-ehlers** [comment]
As a side note:

I finally documented my non-appliance way of installing a Windows template into GNS3, see <https://www.b-ehlers.de/blog/posts/2021-02-15-gns3-create-windows-2008r2-template/>.

**Comment by grossmj** [comment]
I brought back the old appliance. Tested both IE8 and IE6 flavors on GNS3 2.2 and everything worked well.
