### ISSUE TITLE
Router Images not available in WEB-UI

### ISSUE THREAD

**Issue by tssalt** [GNS3/gns3-gui#3126]
When I use the WEB-UI I do not see any of the Router Images I have installed when using teh GUI.

Below are the Images from the Server
gns3@gns3vm:/opt/gns3/images$ ls IOS
c2691-adventerprisek9-mz.124-15.T14.image         c7200-jk9s-mz.124-23.image
c2691-adventerprisek9-mz.124-15.T14.image.md5sum  c7200-jk9s-mz.124-23.image.md5sum
C3725-SP-c3725-spservicesk9-mz.124-23.BIN         c7200p-adventerprisek9-mz.152-4.S7.image
C3725-SP-c3725-spservicesk9-mz.124-23.BIN.md5sum  c7200p-adventerprisek9-mz.152-4.S7.image.md5sum
c7200-adventerprisek9-mz.124-24.T5.image          c7200-spservicesk9-mz.124-24.T8.image
c7200-adventerprisek9-mz.124-24.T5.image.md5sum   c7200-spservicesk9-mz.124-24.T8.image.md5sum
gns3@gns3vm:/opt/gns3/images$
gns3@gns3vm:/opt/gns3/images$ ls qemu
IOSv_startup_config.img                  vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E
vios-adventerprisek9-m.vmdk.SPA.156-2.T
gns3@gns3vm:/opt/gns3/images$
gns3@gns3vm:/opt/gns3/images$ ls QEMU
csr1000v-universalk9.16.12.03-serial.qcow2
csr1000v-universalk9.16.12.03-serial.qcow2.md5sum
IOSv_startup_config.img
IOSv_startup_config.img.md5sum
Nokia-VSR-VM-19.10.R3.zip
Nokia-VSR-VM-19.10.R3.zip.md5sum
sros-vm.qcow2
sros-vm.qcow2.md5sum
TiMOS-SR-19_10_R3-vm.qcow2
TiMOS-SR-19_10_R3-vm.qcow2.md5sum
TiMOS-SR-VSR-VM-19.10.R3-vm.qcow2
TiMOS-SR-VSR-VM-19.10.R3-vm.qcow2.md5sum
vios-adventerprisek9-m.vmdk.SPA.156-2.T
vios-adventerprisek9-m.vmdk.SPA.156-2.T.md5sum
vios-adventerprisek9-m.vmdk.SPA.157-3.M3
vios-adventerprisek9-m.vmdk.SPA.157-3.M3.md5sum
vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E
vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E.md5sum
gns3@gns3vm:/opt/gns3/images$

But the below output shows no Routers
![image](https://user-images.githubusercontent.com/78693439/107151580-3c53d700-695b-11eb-92b7-0c63ca79669b.png)

I have just upgraded to the latest release 2.2.17. I have an existing Project that was done on my previous release and I had added an IOS image for this project. I can even start these routers. If so why can I not see the image that these are even using?

Many Thanks

**Comment by piotrpekala7** [comment]
![templates](https://user-images.githubusercontent.com/31202938/108213434-4f229480-712f-11eb-9c27-74f864f090d0.JPG)
I checked 2.2.19 version, all templates are visible on template list

**Comment by piotrpekala7** [comment]
we're taking data from v2/templates endpoint

**Comment by piotrpekala7** [comment]
images should be visible in dialog when you create template

**Comment by grossmj** [comment]
@tssalt I have found any issues on my side too.

Please try to open `http://IP_ADDRESS:PORT/v2/templates` in your browser. This should list all the available appliances instance on the GNS3 server. Let us know if the your can find the router images in the list. Thanks :+1:

**Comment by tssalt** [comment]
Hi,
I have now upgraded to 2.2.18
I have just had a look in that directory and all I see are the default templates as shown in teh text file.
[v2-templates.txt](https://github.com/GNS3/gns3-gui/files/6017684/v2-templates.txt)

But the images below are in the /opt/gns3/images directory

gns3@gns3vm:/opt/gns3/images$ ls IOS
c2691-adventerprisek9-mz.124-15.T14.image         c7200-jk9s-mz.124-23.image
c2691-adventerprisek9-mz.124-15.T14.image.md5sum  c7200-jk9s-mz.124-23.image.md5sum
C3725-SP-c3725-spservicesk9-mz.124-23.BIN         c7200p-adventerprisek9-mz.152-4.S7.image
C3725-SP-c3725-spservicesk9-mz.124-23.BIN.md5sum  c7200p-adventerprisek9-mz.152-4.S7.image.md5sum
c7200-adventerprisek9-mz.124-24.T5.image          c7200-spservicesk9-mz.124-24.T8.image
c7200-adventerprisek9-mz.124-24.T5.image.md5sum   c7200-spservicesk9-mz.124-24.T8.image.md5sum
gns3@gns3vm:/opt/gns3/images$ ls qemu
IOSv_startup_config.img                  vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E
vios-adventerprisek9-m.vmdk.SPA.156-2.T
gns3@gns3vm:/opt/gns3/images$ ls QEMU
config.img
config.img.md5sum
csr1000v-universalk9.16.12.03-serial.qcow2
csr1000v-universalk9.16.12.03-serial.qcow2.md5sum
IOSv_startup_config.img
IOSv_startup_config.img.md5sum
Nokia-VSR-VM-19.10.R3.zip
Nokia-VSR-VM-19.10.R3.zip.md5sum
sros-vm.qcow2
sros-vm.qcow2.md5sum
TiMOS-SR-19_10_R3-vm.qcow2
TiMOS-SR-19_10_R3-vm.qcow2.md5sum
TiMOS-SR-VSR-VM-19.10.R3-vm.qcow2
TiMOS-SR-VSR-VM-19.10.R3-vm.qcow2.md5sum
vios-adventerprisek9-m.vmdk.SPA.156-2.T
vios-adventerprisek9-m.vmdk.SPA.156-2.T.md5sum
vios-adventerprisek9-m.vmdk.SPA.157-3.M3
vios-adventerprisek9-m.vmdk.SPA.157-3.M3.md5sum
vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E
vios_l2-adventerprisek9-m.vmdk.SSA.152-4.0.55.E.md5sum
gns3@gns3vm:/opt/gns3/images$

**Comment by tssalt** [comment]
I have alos noticed that on the Web Page I only see 2 Projects.

But if I look in /opt/gns3/projects there are a lot more projects there?

gns3@gns3vm:/opt/gns3$ ls -al projects/
total 44
drwxr-xr-x 11 gns3 gns3 4096 Feb 13 19:42 .
drwxr-xr-x  4 gns3 gns3 4096 Aug  7  2020 ..
drwxr-xr-x  3 gns3 gns3 4096 Oct 29 20:02 228a7a8d-1388-404b-ab81-68ce353f4786
drwxr-xr-x  3 gns3 gns3 4096 Dec 29 19:16 35113371-b5dd-4734-9c23-8b7309ca78d7
drwxr-xr-x  3 gns3 gns3 4096 Feb  4 20:30 3ab715eb-d57b-4f65-8dbc-75c08d350714
drwxr-xr-x  3 gns3 gns3 4096 Feb 13 19:42 5a2817d4-4576-4d18-b1a7-8d3c27546498
drwxr-xr-x  3 gns3 gns3 4096 Feb 21 12:24 75098919-a35b-4f19-9b2b-aac704718c67
drwxr-xr-x  3 gns3 gns3 4096 Jan  9 19:55 a233da2c-b383-4889-9b6b-8582242c9250
drwxr-xr-x  3 gns3 gns3 4096 Oct 20 18:09 cd72f491-20bc-496a-8137-00bbf0aa6ac7
drwxr-xr-x  4 gns3 gns3 4096 Feb 17 21:18 d0fb1424-5b91-412c-b558-89aacf456c38
drwxr-xr-x  3 gns3 gns3 4096 Feb  7 15:51 df24bb11-7cf1-483c-815d-51e563e966fd
gns3@gns3vm:/opt/gns3$

**Comment by grossmj** [comment]
> I have just had a look in that directory and all I see are the default templates as shown in teh text file.
v2-templates.txt

I see that only the built-in templates are available. You need to register templates even if you have all your images stored in `/opt/gns3/images`. In the future, we plan to add something so templates can automatically be added if recognised images are found but it is still a manual process until we have this...

> I have alos noticed that on the Web Page I only see 2 Projects.

Somehow, the server hasn't recognised all projects. Please check the `/var/log/gns3/gns3.log` file after booting the VM. You may see errors related to this.

**Comment by tssalt** [comment]
Hi Jeremy,
Many thanks for your reply. Enclosed is the log file from today when I started the Server.
[GNS3_Log_010321.txt](https://github.com/GNS3/gns3-gui/files/6064202/GNS3_Log_010321.txt)

To register the templates is there a procedure for this please or is it the same as uploading a new image?

**Comment by grossmj** [comment]
> To register the templates is there a procedure for this please or is it the same as uploading a new image?

Yes, just click on `Add new template` :)
