### ISSUE TITLE
VNC console gives black screen

### ISSUE THREAD

**Issue by koliaskostas** [GNS3/gns3-gui#3128]
I have a docker container created as:
FROM ubuntu
RUN apt update
RUN apt install -y x11-apps x11vnc xvfb firefox
RUN mkdir ~/.vnc
EXPOSE 5900

As you can see I want to be able to run firefox from GNS3. 
I have tested the container in Ubuntu 20.4 and it works fine and I can access it if I give:
docker run -it -p 5900:5900 firefox

And then from within the container I give:
x11vnc -create -forever

In this way it is possible for me to use vnc to that container. 

I want to do the same from within GNS3
However, when the same container runs from with GNS3 environment I get a black screen on VNC.

According to the documentation:
"You can launch graphical programs if you choose VNC as the console type. Behind the scenes, GNS3 will start a fake Xserver (using Xvfb) and inject it in the container. After that this X server is exposed to the network via X11VNC. You don’t need to modify your container to get VNC support. A limitation of this, is that any container can access the X socket of other containers."

So technically it doesn't seem that I need to launch the xserver from within the container, as GNS3 will take care of it following the process above. 
 
Just being paranoid I have also tried manually starting x11vnc. Obviously, in the case of starting x11vnc I am unsure how to map the port (-p 5900:5900).

In both cases the vncviewer was giving me a black screen.
Any ideas how to resolve the issue?

 - OS: Ubuntu Linux 20.04
 - GNS3: 2.217
 - VMWare

**Comment by koliaskostas** [comment]
Any thoughts on that? Have you successfully replicated the issue?

**Comment by b-ehlers** [comment]
If you use VNC for Docker VMs, GNS3 expects the container to run clients using X11 to display their contents. The conversion to VNC is done by the GNS3 server, **NOT** by the Docker container. So you don't have to install any VNC stuff in your Dockerfile, just install the graphical clients like firefox.

Furthermore you won't have a CLI interface to the Docker VM, when using the VNC console type. So you have to start your GUI application during the container start. Either use CMD in the Dockerfile or use the "Start command" in the GNS3 docker template.

As an example here a simple firefox application, I called it ffox:

The Dockerfile:

```
FROM ubuntu
RUN apt update
RUN apt install -y firefox
```
If you want to run the image directly on the linux system (without GNS3) run:
```
xhost +local:
docker run -it --net=host --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ffox firefox
```
Within GNS3 create a template using "firefox" as a start command:
![ffox_template](https://user-images.githubusercontent.com/49040325/110216169-dd2ba880-7ead-11eb-9003-d38ad3a2d8b0.png)

Create a project:
![ffox_project](https://user-images.githubusercontent.com/49040325/110216193-ffbdc180-7ead-11eb-9f95-9dbb04e834e2.png)

In GNS3 the network interfaces are **NOT** managed by Docker, the interfaces are created by GNS3 and injected into the container. The network configuration is done with a config file in Debian network/interfaces syntax. Right-click on the node and use "Edit config" to edit the network configuration (while the node is stopped). Here I'm using DHCP on interface eth0:
![ffox_interfaces](https://user-images.githubusercontent.com/49040325/110216276-883c6200-7eae-11eb-8ff4-414c393070a4.png)

Now, when starting this container you should see firefox running in it:
![ffox_vnc](https://user-images.githubusercontent.com/49040325/110216306-b0c45c00-7eae-11eb-98a0-1b2f824a18ed.png)

But as you would notice, there is no window manager running in the Docker container. So you can't modify the size or position of the firefox application and you can't start other applications.

So my GNS3 docker images contain `jwm` as a very small window manager, here a basic Dockerfile:

```
FROM ubuntu
RUN apt update
RUN apt install -y firefox jwm lxterminal
RUN sed -i 's/xterm/x-terminal-emulator/g' /etc/jwm/system.jwmrc
CMD sh -c "firefox& jwm"
```
I prefer to use CMD, so the user doesn't need to know, how to correctly start the container.

**Don't run this image locally, as it's jwm window manager wants to overtake your local window manager. And you don't want to run into this mess. Use Docker images with an embedded window manager only within GNS3.**

With this background information you might want to have a look at <https://github.com/GNS3/gns3-registry/blob/master/docker/ipterm/web/Dockerfile> to see, how the official Firefox Docker appliance is built.

**Comment by b-ehlers** [comment]
> Furthermore you won't have a CLI interface to the Docker VM, when using the VNC console type.

While you don't have access to the main CLI console, you can start an auxiliary console (right-click on the device and select "Auxiliary console"). This creates a telnet console, which can start both cli commands, that run in the auxiliary console, and GUI commands, that are shown in the VNC window.

**Comment by grossmj** [comment]
@b-ehlers Thanks for all the details. I think this answers the question.

@koliaskostas please comment back if you have more questions.

**Comment by b-ehlers** [comment]
I created a blog post about this: <https://www.b-ehlers.de/blog/posts/2021-04-06-gns3-docker-vnc-console/>
