### ISSUE TITLE
GNS3 VM2.2.18 unable to deploy OVA on ESXi

### ISSUE THREAD

**Issue by cischology** [GNS3/gns3-gui#3134]
**Describe the bug**
Unable to deploy GNS3VM into esxi
**GNS3 version and operating system (please complete the following information):**
ESXi

**To Reproduce**
1- from vSphere deploy OVF and choose GNS3 VM 2.2.18

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/56488147/108272213-cbfd4080-7126-11eb-8ec5-5016260cd285.png)

**Comment by grossmj** [comment]
Did you have this issue with GNS3 VM 2.2.17?

**Comment by cischology** [comment]
> Did you have this issue with GNS3 VM 2.2.17?

nope. however, I have GNS3 VM 2.2.16 running. but failing to upgrade. 500 GB is woefully large for a VM :)

**Comment by grossmj** [comment]
The GNS3 VM has 2 disks, one for the system (20GB) and one for GNS3 projects & images etc. (500 GB).

I deployed the GNS3 VM 2.2.18 directly to an ESXi host (without using vSphere).

There you can select the disk provisioning type: 

![Screenshot from 2021-02-22 09-54-13](https://user-images.githubusercontent.com/4752614/108663646-f2edb500-7520-11eb-9df8-872c0efcca5e.png)

![Screenshot from 2021-02-22 09-54-25](https://user-images.githubusercontent.com/4752614/108663641-f1bc8800-7520-11eb-86ea-cd938693b000.png)

Once deployed, I can see I have the "thin" provisioning type:

![Screenshot from 2021-02-22 09-59-33](https://user-images.githubusercontent.com/4752614/108663634-eff2c480-7520-11eb-9e0f-5da863ff3cc6.png)

I am not familiar with vSphere but I guess you should be able to select the disk provisioning type.

**Comment by cischology** [comment]
Thank you, yes I understand, however I think 500GB is too much and most of us would not have that kind of free space laying around on a virtual environment. I suggest to make it smaller i.e. 10G and let users decide how big they want to set it or built it small and it will grow as they install images, files, etc. but having the 2nd disk at 500GB will prevent installing GNS3VM as a whole, at least in my case it exceed the total free space in my data store :)

**Comment by grossmj** [comment]
I thought the result of thin provisioning is that the virtual disk uses only as much storage space as it needs. Sorry, I am not too familiar with ESXi.
