### ISSUE TITLE
IOSv console issues

### ISSUE THREAD

**Issue by benali125** [GNS3/gns3-gui#3135]
In release 2.2.18 I have problem connecting to IOSv and IOSv L2 from macbook Big sur 11.1, same as 2.2.17!
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by Mario156090** [comment]
Where is the screenshot ir vídeo?

**Comment by benali125** [comment]
![FD234A19-8065-4A09-869B-DEEA45C2755D](https://user-images.githubusercontent.com/52331820/108596529-78fbd700-733a-11eb-89e4-a4797571bc9c.jpeg)

**Comment by Mario156090** [comment]
@benali125 works perfectly here:
![image](https://user-images.githubusercontent.com/47507975/108597507-70fe6000-7357-11eb-9393-d78acf65ba0d.png)

that is normal, if you press enter works...

**Comment by benali125** [comment]
No sir I tried that too many times 
Are you using Mac OS Big Sur 
There is a lot of people with same issue on gns3 community since version 2.2.17

**Comment by Mario156090** [comment]
> No sir I tried that too many times
> Are you using Mac OS Big Sur
> There is a lot of people with same issue on gns3 community since version 2.2.17

No, I'm using Linux. So, you should to add the formulary correctly ... also take a video and attach here. I believe that is level 8 error in relationship OSI model.

**Comment by benali125** [comment]
This is an issue with Mac OS user also the unable to drag appliances after restart gns3 GUI 
I’ve been using gns3 for almost 14 years now 
Thank you for your help

**Comment by grossmj** [comment]
@benali125 are you able to use the web interface?

**Comment by benali125** [comment]
No sir
So updated to gns3 2.2.19 from 2.2.18
And the problem still persist also wasn’t able to open saved projects


Sent from my iPhone

On Mar 1, 2021, at 11:04 PM, Jeremy Grossmann <notifications@github.com> wrote:

﻿

@benali125<https://github.com/benali125> are you able to use the web interface?
