### ISSUE TITLE
Add mtools package to GNS3VM

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3138]
**Is your feature request related to a problem?**
The config disk feature depends on the mtools package. In the gns3-server package mtools is listed as a dependency. So it will be automatically installed in Ubuntu based systems using the gns3-server package.

But the GNS3VM installs the GNS3 server from source. Therefore mtools in neither installed, when upgrading to 2.2.18 nor when installing a fresh 2.2.18 VM.

**Describe the solution you'd like**
Add mtools to the packages installed in the GNS3VM.

**Comment by grossmj** [comment]
Upgrading the VM will install mtools. Also, the next GNS3 VM (2.2.19) will include mtools.

**Comment by b-ehlers** [comment]
Using "Upgrade" on the focal based GNS3VM v2.2.18 works, mtools gets installed. That's fine.

But upgrading the bionic based GNS3VM v2.2.17 doesn't install mtools, quite likely because the bionic-stable branch of gns3-vm hasn't been updated. Are there any plan to modify bionic-stable as well?

**Comment by grossmj** [comment]
> But upgrading the bionic based GNS3VM v2.2.17 doesn't install mtools, quite likely because the bionic-stable branch of gns3-vm hasn't been updated. Are there any plan to modify bionic-stable as well?

Indeed, I will update bionic-stable and bionic-unstable too :+1:

**Comment by b-ehlers** [comment]
Just retested with the bionic based GNS3VM v2.2.17, works fine. Many thanks.

**Comment by b-ehlers** [comment]
The GNS3 VM v2.2.19 does **NOT** include the mtools, it still needs an "Upgrade" to install the mtools.

**Comment by grossmj** [comment]
Sorry, I have noticed that we need to rebuild the base VM :(

**Comment by grossmj** [comment]
This will be fixed when we release version 2.2.20

**Comment by grossmj** [comment]
Version 2.2.20 has been released.
