### ISSUE TITLE
unable to upgrade gns3 vm from 2.2.17 to 2.2.18

### ISSUE THREAD

**Issue by no-1imit** [GNS3/gns3-gui#3139]
Hi, I cannot upgrade my gns3 VM to 2.2.18, I get this error
![Screenshot from 2021-02-26 12-47-58](https://user-images.githubusercontent.com/62109890/109281343-706f3900-7831-11eb-96a6-5f2c8d31f688.png)
what's wrong?

**Comment by grossmj** [comment]
Please manually delete the `gns3-server` directory and try again.
