### ISSUE TITLE
WEB UI hangs at open

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#3145]
Searched for cause/solution on internet and GNS3 website but only found the issue not the cause/solution.

**Describe the bug**
GNS3  application and GNS3 Vmware VM working fine, i.e., project open and work correctly.
However, when I click on Tools -> WEB UI beta only get the screens pictures of which I have included
and then nothing changes from the second screen

**GNS3 version and operating system (please complete the following information):**
GNS3 management console.
Running GNS3 version 2.2.19 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2021 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

Windows 10 version 20H@ (OS Build 19042.844
VMware® Workstation 16 Pro 16.1.0 build-17198959

**To Reproduce**
1. Click on Tools > WEB UI beta
2. Click on "OK" button and see problem (the Network Configuration Generator dialog does disappear)

**Screenshots or videos**
![GNS WEB UI 1](https://user-images.githubusercontent.com/10285348/110140753-6c4b9a00-7da2-11eb-867b-9276f21667e3.png)
![GNS WEB UI 2](https://user-images.githubusercontent.com/10285348/110140768-6fdf2100-7da2-11eb-915a-93f5f9d806d4.png)

**Additional context**
No doubt I am missing an important point but do not know what that point is.  
As always, thanks for a great learning tool.  IMO, the best available for learning networking.

**Comment by b-ehlers** [comment]
Also using Firefox and have the same issue.

What is working for me: In your final screen click in the address bar and enter <return> to reload it, then the projects page is shown. Using the reload button does not work.

**Comment by jtorri** [comment]
Grazie mille!  Worked like a charm!
