### ISSUE TITLE
IOU image loading issue

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#315]
As described here https://community.gns3.com/ideas/1729

**Comment by grossmj** [comment]
Looks like a similar issue: https://community.gns3.com/ideas/1708

**Comment by noplay** [comment]
So the issue seem to be we need to look in images directory in order to ensure backward compatibility.

**Comment by noplay** [comment]
The original bugs is fixed.

**Comment by noplay** [comment]
The original was you can't put your image in another location than the default location.

**Comment by noplay** [comment]
Fixed on server side
