### ISSUE TITLE
2.2.19 mac m1 chip gns3-gui can not drag

### ISSUE THREAD

**Issue by raphael-red** [GNS3/gns3-gui#3152]
Hello, I can not drag nodes icon to the project topology. But I found it will be fixed when I open web-ui url and make a drag in my web browser and then back again to my gui then it can be drag with out an issue. Obviously it will not survival during reboot.

Btw, I am using gns3 remote server maybe it's not relevant but guess I'll mention it anyway.

**Comment by pokui** [comment]
Just a note that I can reproduce this on 2.2.19 running on OS X 10.14.6 on an intel MacBook Pro. I can't drag elements whether I use the local server or my remote server.

The management console claims:

`Running GNS3 version 2.2.19 on Darwin (64-bit) with Python 3.6.5 Qt 5.11.0 and PyQt 5.10.1.`

**Comment by candlerb** [comment]
I haven't seen this specific problem, but "clicking on something doesn't do anything" reminds me of #3007 - except that generates a beep, and is easy to reproduce (for me anyway).  It's possible that the underlying root cause is the same.

**Comment by turtlewax** [comment]
I'm almost positive this macOS drag problem is a Qt 5.15.1 bug.  Please see my GNS3 community post here for a quick workaround that doesn't involve reinstalling GNS3:

https://www.gns3.com/community/featured/gns3-macos-drag-and-drop-problem-can-devs-please-update-qt-to-5-15-2

**Comment by grossmj** [comment]
Upgraded to Qt 5.15.2

**Comment by grossmj** [comment]
Please try this dev build (includes Qt 5.15.2): https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-04-06/2.2/GNS3-2.2.20dev2.dmg/download

**Comment by candlerb** [comment]
FYI, it doesn't fix the "recent projects" issue (#3007) - clicking on a project just gives a beep, it does not select it, nor does it close the selection window.  (macOS 10.14.6 Intel).  So we can rule this out as a related issue.

![image](https://user-images.githubusercontent.com/44789/113697020-973f4b80-96ca-11eb-954d-3f3e2410e12b.png)

I haven't seen the drag-and-drop problem myself.

**Comment by grossmj** [comment]
@candlerb ok, I will consider this issue fixed. I don't know what is wrong regarding https://github.com/GNS3/gns3-gui/issues/3007

**Comment by pokui** [comment]
> Please try this dev build (includes Qt 5.15.2): https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-04-06/2.2/GNS3-2.2.20dev2.dmg/download

Looks fine here. But then again this is a sporadic issue that is hard to trigger on purpose. I think it's best to consider it closed and _if it reoccurs_ then someone can comment here and have the issue (re)opened.
