### ISSUE TITLE
Upgrade from 2.2.19 to 2.2.20 uses wrong remote server

### ISSUE THREAD

**Issue by mtcweb** [GNS3/gns3-gui#3167]
Before/after upgrade remote server was configured for 10.136.227.107:80.   After upgrade of client it attempted to connect with 10.136.227.100:80.  No issues after I manually updated.

GNS3 server version: 2.2.20                     |
                                                                  | Release channel: 2.2                            |
                                                                  | VM version: 0.10.27                             |
                                                                  | Ubuntu version: bionic                          |
                                                                  | Qemu version: 3.1.0                             |
                                                                  | Virtualization: vmware                          |
                                                                  | KVM support available: True                     |
                                                                  | Uptime: up 13 minutes                           |
                                                                  |                                                 |
                                                                  | IP: 10.136.227.107 PORT: 80                     |
                                                                  |                                                 |
                                                                  | To log in using SSH: ssh gns3@10.136.227.107    |
                                                                  | Password: gns3                                  |
                                                                  |                                                 |
                                                                  | To launch the Web-Ui: http://10.136.227.107     |
                                                                  |                                                 |
                                                                  | Images and projects are stored in '/opt/gns3' 

GNS3 management console.
Running GNS3 version 2.2.20 on Windows (64-bit) with Python 3.6.8 Qt 5.12.10 and PyQt 5.12.3.
Copyright (c) 2006-2021 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Timeout after 10 seconds for request http://admin@10.136.227.100:80/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 5 seconds for request http://admin@10.136.227.100:80/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 5 seconds for request http://admin@10.136.227.100:80/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 5 seconds for request http://admin@10.136.227.100:80/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Timeout after 5 seconds for request http://admin@10.136.227.100:80/v2/version. Please check the connection is not blocked by a firewall or an anti-virus.
Error while get gettings: Cannot connect to http://10.136.227.100:80. Please check if GNS3 is allowed in your antivirus and firewall. And that server version is 2.2.20.

**Comment by grossmj** [comment]
Do you still have an issue with this?
