### ISSUE TITLE
SSH version 2 BUG

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#317]
As reported there: https://community.gns3.com/ideas/1711

**Comment by noplay** [comment]
Perhaps it's related to:
https://github.com/GNS3/gns3-server/issues/171

**Comment by grossmj** [comment]
No actually this is related to the fact that we provide a base private-config that already contains a key.

**Comment by grossmj** [comment]
Recommend course of action: https://community.gns3.com/ideas/1741 :+1:

**Comment by grossmj** [comment]
I've decided to not set a default private-config when creating a new IOS router template.
