### ISSUE TITLE
Linux namespace as a GNS3 device

### ISSUE THREAD

**Issue by rcprior** [GNS3/gns3-gui#3172]
One feature that I would find very useful is possibility of configuring via the GUI a Linux network namespace as a GNS3 device, similarly to hosts in Mininet. This would give you an extremely lightweight Linux device with access to the filesystem (including all executables) of the Linux host (or the GNS3 VM). Are there any plans for this?

**Comment by grossmj** [comment]
No plans for this. What is the advantage over running Docker containers?

**Comment by rcprior** [comment]
Some advantages are:
* You can use all software installed in your linux host
* You can simply use your distro's package manager to install more
* Data persistence
* Some storage space savings

Plus, it should be pretty easy to implement in GNS3.
