### ISSUE TITLE
can't use gns3 when PC uses VPN for internet

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#3178]
Community link: https://gns3.com/community/support/cant-use-gns3-when-pc-uses-vpn-for-internet

**Comment by eantowne** [comment]
This is an issue of implementing split tunneling with a VPN, or possibly static routes on the host system. Some corporate VPN's also do not allow ANY traffic outside of their tunnel. This is not necessarily an issue to be fixed within GNS3. I was unable to send a direct message to the OP, and the support request has been closed.
