### ISSUE TITLE
Short description of the feature request

### ISSUE THREAD

**Issue by thaizoun** [GNS3/gns3-gui#3179]
I have a work project that i want to lab it in GNS3.I need to configure a new Load Balancer called Virtual Traffic Manager from PULSE SECURE (IVANTI) .I downloaded the OVA appliance and imported it within VMware Workstation and i can can login to it via its GUI. I also imported a few Linux web servers and Windows 10 inside GNS3 to use as Client/ servers.GNS3 does not a dedicated appliance for this Pulse Secure as it does for F5 .How can i have work inside GNS3 so the clients send traffic to it and it then load balance it to the servers ? .I thought about using a Microsoft loopback and use a cloud the same way we can connect physical devices .
Attached are the is my  topology so you have a visual idea about what i am describing as well the error i am getting 
![PULSE-SECURE-TOPOLOGY-INSIDE-GNS3 05-0521](https://user-images.githubusercontent.com/84204674/118323817-32e48880-b4cf-11eb-861d-0f6a8e22fd8b.png)
![GNS3-ERROR-INTEGRATION-PS-LB into GNS3](https://user-images.githubusercontent.com/84204674/118323931-5576a180-b4cf-11eb-9af8-984cdaf1257f.PNG)

Please advise 

Thank you

**Comment by grossmj** [comment]
Have you added vmnet interfaces? Go to preferences then VMware -> Network -> Configure to add more interfaces.

**Comment by thaizoun** [comment]
Hi Jeremy,

I did and fix the issue i had .
Thank you for responding to my question

V,r

Talal
