### ISSUE TITLE
VPCS Multi-host broken in v1.3.3dev1

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#318]
As reported there: https://community.gns3.com/ideas/1740

**Comment by noplay** [comment]
Hey Jeremy what the reason for supporting VPCS multi host? It sound complicated and rarely used. 

Perhaps we can make something for converting old project using that to the simple host support.

**Comment by grossmj** [comment]
This is a special request from Chris to support GNS3 Workbench, the all story can be found in https://community.gns3.com/ideas/1395

**Comment by noplay** [comment]
Ok. I understand .

On Mon, May 4, 2015 at 4:24 PM, Jeremy Grossmann <notifications@github.com>
wrote:

> This is a special request from Chris to support GNS3 Workbench, the all
> story can be found in https://community.gns3.com/ideas/1395
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/318#issuecomment-98725893>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
