### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by RobFosterNYC** [GNS3/gns3-gui#3180]
This issue still exist as of today 05-16-2021  3:00-pm EST
Please read last comments on that issue post.......  This issue needs to be re-opened as its not resolved or fixed.

https://github.com/GNS3/gns3-gui/issues/3032

**Comment by eantowne** [comment]
Can you be more specific? There are a few solutions and workarounds to this, but more information as to your environment is needed. Feel free to create a support request at: [GNS3 Support](https://www.gns3.com/community/support).
Most likely this is NOT actually a bug in GNS3, it is most likely the result of conflicting interactions between VirtualBox and the underlying operating system.

Do you have Docker installed?
Dow you have WSL installed?
