### ISSUE TITLE
GNS3 devices no longer able to connect out via Cloud. 

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#3183]
Community link: https://gns3.com/community/support/gns3-devices-no-longer-able-to-connect-via-cloud

**Comment by bigern314** [comment]
I'm still seeing this issue on 2.26.  Very frustrating. 

With a virtual Cisco 7200 setup and connected to the Cloud I will see the following. 

Gateway of last resort is 172.16.255.1 to network 0.0.0.0

     172.16.0.0/24 is subnetted, 1 subnets
C       172.16.255.0 is directly connected, GigabitEthernet1/0
S*   0.0.0.0/0 [1/0] via 172.16.255.1
CoreRouter#ping 172.16.255.1

Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 172.16.255.1, timeout is 2 seconds:
.....
Success rate is 0 percent (0/5)
CoreRouter#sh arp
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  172.16.255.1            0   8416.f95d.f7a4  ARPA   GigabitEthernet1/0 - Asus Router
Internet  172.16.255.101          0   3c7c.3f5f.9c4a  ARPA   GigabitEthernet1/0 - My laptop
Internet  172.16.255.200          -   ca01.05b3.001c  ARPA   GigabitEthernet1/0

I see the virtual Cisco in the arp table of the Asus router, but can't ping it...unless I'm running 2.17.
