### ISSUE TITLE
i have installed vm appliances and iou devices in remote server in  aws   . After  adding extra  volume for my remote server , now  when i  check my client gns3 , my  client  gns3  is  not  reading any of  thos vm appliance images or iou images ...

### ISSUE THREAD

**Issue by teja456** [GNS3/gns3-gui#3184]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by teja456** [comment]
![gns3  remote  server issue](https://user-images.githubusercontent.com/79880377/119409933-aa9f8800-bd05-11eb-9dbe-b401f4d3c0a7.PNG)

**Comment by teja456** [comment]
i can  open my project  and  work on it and  the  images  on server are responding ,  but  cannot  see  them in the  gns3  client

**Comment by grossmj** [comment]
> i can open my project and work on it and the images on server are responding , but cannot see them in the gns3 client

No sure I understand the problem. Please provide more details.
