### ISSUE TITLE
Dynamically drawn line does not draw as the topmost layer when using "Connector"

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3189]
**Bug Description**
When using the connector tool, and the line passes through a shape (Circle or Square), the dynamically drawn (while moving mouse to second node) connector line is not drawn as the top layer. This results in the portion of the line being drawn within the bounds of the shape not being visible. The connector line (both dynamically drawn, and resulting) should be drawn at the top most layer.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 20H2
 - GNS3 version: 2.2.21
 - VM's/Local/Remote bare-metal servers

**To Reproduce**

1. Draw a box on the project canvas
2. Add 2 nodes (I used VPCS) on either side of the box
3. Select "Connector" tool
4. Select first node
5. Move mouse to second node
6. Notice that portion of line within box disappears
7. Moving box to absolute bottom layer will fix

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

![connector-line-draw-layer-issue](https://user-images.githubusercontent.com/66289315/121394629-28bf7980-c917-11eb-9950-e9337273658d.png)
![connector-line-draw-layer-issue-square](https://user-images.githubusercontent.com/66289315/121394631-29581000-c917-11eb-880b-3e7f3e38b9e7.png)

**Additional context**

**Comment by b-ehlers** [comment]
Moving the connections as the topmost layer would look poor. In GNS3 the connection line goes from he center of the first device to the center of the second device. I simulared, what happens, if the connection would be the topmost layer by creating a symbol with a transparent inner part.
![layer1](https://user-images.githubusercontent.com/49040325/121485491-84017280-c9d0-11eb-8737-00fa3db6145a.png)

Therefore the connection gets a layer value of "minimum(layer first device, layer second device) - 0.5". That way the connection is below both devices and it looks as if it starts at the boundary of these devices. As the default layer value of a device is 1, the connection gets a layer value of 0.5.

If you create a box between those devices (on layer 1) it will be above the connection. In the following I am using the viewing option "Show layers" to display the layer value.
![layer2](https://user-images.githubusercontent.com/49040325/121488193-24589680-c9d3-11eb-898d-c93f72074930.png)

As you wrote, by lowering the layer of the box to 0, the connection (layer 0.5) is above the square.
![layer3](https://user-images.githubusercontent.com/49040325/121488203-26225a00-c9d3-11eb-9778-6a58a4e77f03.png)

So if you want a shape below the connection, you have to lower its layer and I see no simple way how this can be changed.

**Comment by grossmj** [comment]
> So if you want a shape below the connection, you have to lower its layer and I see no simple way how this can be changed.

This is my conclusion as well. I tried to change the layer to 100 just when adding links but quickly realized that it would look ugly like in your first image above.
