### ISSUE TITLE
Right-click → Isolate Node

### ISSUE THREAD

**Issue by eckdd** [GNS3/gns3-gui#3190]
Would like a solution that will quickly and easily suspend all links to a node without suspending the node itself. Preferably, there would be an action near the Start/Suspend/Stop functions in the right-click node menu called "Isolate." Upon selecting Isolate, all links that terminate on the node are immediately suspended. 

To resume the links, the user should be able to right-click the isolated node and select Un-isolate. Also, links can individually be resumed by right-clicking the link. 

**Additional context**
It is often useful to be able to test failure scenarios, and the existing suspend feature can simulate that. However, it is sometimes useful to be able to see what is happening on a node as it is isolated; e.g. testing an EEM script that reacts to such isolation scenario--for these cases, suspending the node is not sufficient.

**Comment by grossmj** [comment]
Implemented.

![isolate](https://user-images.githubusercontent.com/4752614/133406839-771fb5fb-419a-4650-810c-3ace5030ea44.png)
