### ISSUE TITLE
Add Windows Terminal profile as an option for "Console Applications"

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3193]
**Is your feature request related to a problem? Please describe.**
Microsoft has released Windows Terminal, and it is a viable option for use as a console application in windows. Currently it is not available as an automatically available option in Edit->Preferences->General->Console Applications. This requires it to be configured as a custom option.

**Describe the solution you'd like**
Add an additional pre-configured option for Windows Terminal using the following command:

`wt.exe -w 1 new-tab --title %d telnet %h %p`

**Comment by grossmj** [comment]
Added, thanks a lot :+1:
