### ISSUE TITLE
Theme issues in Fedora 34.

### ISSUE THREAD

**Issue by PranavBhattarai** [GNS3/gns3-gui#3194]
I use **[Yaru Dark](https://github.com/ubuntu/yaru)** theme in Fedora 34.
![A3](https://user-images.githubusercontent.com/32763112/121797300-29218280-cc3f-11eb-83f0-68eff85500a8.png)
![A1](https://user-images.githubusercontent.com/32763112/121797302-2b83dc80-cc3f-11eb-8669-cc2ca7500e19.png)
![A2](https://user-images.githubusercontent.com/32763112/121797307-2e7ecd00-cc3f-11eb-9dbc-c88630801875.png)

Ubuntu LTS and non-LTS release with this theme by default. It's a really popular and sleek theme. And works with all the apps that I use. But for some reason, I'm having this issue in Fedora! when it comes to GNS3?

I have installed this theme with the DNF command which is supposed to be a little safe as you can see.
```
pranav@fedora ~]> dnf info yaru-theme
Last metadata expiration check: 0:00:23 ago on Sun 13 Jun 2021 12:05:29 PM +0545.
Available Packages
Name         : yaru-theme
Version      : 21.04.1
Release      : 2.fc34
Architecture : noarch
Size         : 60 k
Source       : yaru-theme-21.04.1-2.fc34.src.rpm
Repository   : updates
Summary      : Ubuntu community theme "yaru"
URL          : https://community.ubuntu.com/c/desktop/theme-refresh
License      : GPLv3+ and CC-BY-SA
Description  : Yaru theme is the default theme for Ubuntu, entirely
             : backed by the community. This is the theme that is
             : shaped by the community on the Ubuntu hub, turned into
             : the default theme starting from Ubuntu 18.10 Cosmic
             : Cuttlefish.

pranav@fedora ~>
```
IF there is such info regarding this issue, do let me know.

**Comment by grossmj** [comment]
We have recently release version 2.2.22 and fixed some issues with the charcoal theme. I don't expect all the problem you reported to be solved but please can you try with this version? Thanks :)

**Comment by PranavBhattarai** [comment]
So far I have it (ver 2.2.22) hasn't released here through DNF in Fedora. I will release it here in my distro in a few days since Fedora is a semi-rolling release distro. Can't I wait till then and comment after when I receive the update?!

@grossmj

**Comment by grossmj** [comment]
I installed GNS3 v2.2.23 on Fedora 34 with yaru dark theme and everything looks fine.

![Screenshot from 2021-08-24 16-59-14](https://user-images.githubusercontent.com/4752614/130575583-45fc9f6c-ea97-4483-97ad-badd1433762b.png)

![Screenshot from 2021-08-24 16-59-50](https://user-images.githubusercontent.com/4752614/130575598-59124b78-a040-49aa-8566-0236166e8a52.png)

![Screenshot from 2021-08-24 17-00-14](https://user-images.githubusercontent.com/4752614/130575614-41ee856c-a500-42a1-a8e4-d43f289ff7e2.png)

**Comment by PranavBhattarai** [comment]
@grossmj you are right, the GNS3 v2.2.23 fixed the theming issue. 

I install the new GNS3 version using the pip command. 
DNF has to hold the GNS3 update to version 2.2.21 because the newer version having problems with some libraries.

Even though I managed to install the latest GNS3 using **pip**, I saw these warnings:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
gns3-gui 2.2.23 requires distro==1.5.0, but you have distro 1.6.0 which is incompatible.
gns3-gui 2.2.23 requires sentry-sdk==1.1.0, but you have sentry-sdk 1.3.1 which is incompatible.
```

**Comment by PranavBhattarai** [comment]
GNS3 version 2.2.24 and GNS3 server 2.2.24 all python errors we used to get. Thanks @grossmj
