### ISSUE TITLE
Add searching current working directory to "Import appliance from server"

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3198]
**Is your feature request related to a problem? Please describe.**
When importing an template from server, if image files are not found on server, the GUI does not search the current "working directory" in addition.

**Describe the solution you'd like**
In addition to searching the "Images" directory of the server, it would be ideal if it also searched the current "working directory" of the GUI, like it does with the import from .gns3a file.

**Comment by grossmj** [comment]
Done
