### ISSUE TITLE
QEMU v5.2 removed -no-kvm option

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3202]
**Describe the bug**
Using the "-no-kvm" option in QEMU v5.2+ results in an error message "qemu-system-x86_64: -no-kvm: invalid option".

**GNS3 version and operating system:**
 - OS: Debian Linux 11 (Bullseye)
 - GNS3 version 2.2.22
 - No GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
1. Create a QEMU VM
2. Add "-no-kvm" to the additional settings
3. Start VM

**Additional context**

Console log:

```
GNS3 management console.
Running GNS3 version 2.2.22 on Linux (64-bit) with Python 3.9.2 Qt 5.15.2 and PyQt 5.15.2.
Copyright (c) 2006-2021 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name alpine-cli-1 -m 256M -smp cpus=1,sockets=1 -boot order=c -drive file=/home/behlers/GNS3/projects/untitled/project-files/qemu/7eaac394-bb89-4da5-a6b3-b8aa06cafed1/hda_disk.qcow2,if=ide,index=0,media=disk,id=drive0 -uuid 7eaac394-bb89-4da5-a6b3-b8aa06cafed1 -serial telnet:127.0.0.1:5001,server,nowait -monitor tcp:127.0.0.1:40499,server,nowait -net none -device e1000,mac=0c:99:53:fe:d1:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=127.0.0.1:10000 -nographic -no-kvm

Execution log:
qemu-system-x86_64: -no-kvm: invalid option
```

Official QEMU notice: <https://github.com/qemu/qemu/blob/master/docs/about/removed-features.rst#-no-kvm-removed-in-52>, it was deprecated since QEMU v1.3.

"-no-kvm" is used in several places in the GUI and the server as a flag, that the VM should run without acceleration. The clean way would be a option for hardware acceleration in GNS3 and get rid of -no-kvm, (and -no-hax). Another way would be to filter out "-no-kvm" from the option string before QEMU is called.

**Comment by grossmj** [comment]
PR https://github.com/GNS3/gns3-gui/pull/3212 and https://github.com/GNS3/gns3-server/pull/1934 opened. I chose to use `-machine accel=tcg` instead but an hardware acceleration option would probably be cleaner. Comments welcome :)

**Comment by b-ehlers** [comment]
Looks good. I changed my option about a hardware acceleration option. It might be a bit cleaner, but it would add another option to the user interface, that is rarely used. So I think, the current solution is preferable.

**Comment by grossmj** [comment]
Indeed, this option would be rarely used :+1:

**Comment by grossmj** [comment]
PRs merged

**Comment by amanuel2** [comment]
https://medium.com/@daeseok.youn/prepare-the-environment-for-developing-linux-kernel-with-qemu-c55e37ba8ade
