### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by samylolxoxo** [GNS3/gns3-gui#3208]
**Is your feature request related to a problem? Please describe.**
This is not a problem, it's just about making the UI less brighter too ease a bit my poor eyes.

**Describe the solution you'd like**
The interface-style: Charcoal is nice, but the GraphicsView background is still too bright. More interface styles would be much appreciated.

**Comment by grossmj** [comment]
It will be supported with Dark style: https://github.com/GNS3/gns3-gui/issues/767
