### ISSUE TITLE
卡死情况

### ISSUE THREAD

**Issue by Crueshlinuxliuhui** [GNS3/gns3-gui#3211]
电脑: win10
GNS3 version: 2.2.22 
打开软件，打开设置随便点击一个地方就造成就出现卡机，然后未响应

**Comment by lidewu** [comment]
Please write down your description in English. Also you can take a screenshoot or offer more information.
請用英文寫下你的問題描述。你可以用截圖方式或者提供更多資訊來確認你的問題.
