### ISSUE TITLE
Missing download files for v2.2.23

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3215]
Missing files in the release section of GNS3 v2.2.23 <https://github.com/GNS3/gns3-gui/releases/v2.2.23>:

- GNS3-2.2.23.dmg and GNS3-2.2.23.dmg.sha256
- GNS3-2.2.23.source.zip and GNS3-2.2.23.source.zip.sha256

**Comment by grossmj** [comment]
Unfortunately our build process for macOS is broken thanks to missing Homebrew bottles. I have be trying to build a new App using recent versions of Python and PyQt but it crashes at startup. I don't know when I will be able to solve this :(

**Comment by grossmj** [comment]
I managed to build a version with updated Python/PyQt version. I tested on BigSur and everything seems to run well. Please try https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-08-09/2.2/GNS3-2.2.24dev1.dmg/download and let me know. Thanks :+1:

**Comment by b-ehlers** [comment]
I only noticed the missing files, but I can't test it. There are some posts in the community site about the missing macOS version, they should be able to test it.

**Comment by lidewu** [comment]
> I managed to build a version with updated Python/PyQt version. I tested on BigSur and everything seems to run well. Please try https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2021-08-09/2.2/GNS3-2.2.24dev1.dmg/download and let me know. Thanks 👍

It also running well on my laptop which BigSur 11.5.1

**Comment by grossmj** [comment]
Thanks, I published the package for v2.2.23. Let's see if users report issues...
