### ISSUE TITLE
Having 8 different devices started will not reach the command line

### ISSUE THREAD

**Issue by jgc1564** [GNS3/gns3-gui#3220]
I have 8 different devices started in GNS3. When I open them to the console, they take a while to get to the command line. Can this be a RAM issue. Is 16 GB not enough? It also seems like I can not go above 7 active devices.
![image](https://user-images.githubusercontent.com/80299911/131234692-88468b4e-013b-4bd6-9399-6e28c7c3d604.png)

**Comment by grossmj** [comment]
@jgc1564 Do you mean the prompt is never reached? Have you tried to start one by one?
