### ISSUE TITLE
Mouse zoom-in/out step value is two times bigger than keyboard one

### ISSUE THREAD

**Issue by andrej-korshikov** [GNS3/gns3-gui#3226]
**GNS3 version and operating system:**
 - OS: `Arch Linux` (Linux laptop 5.13.13-zen1-1-zen # 1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux)
 - GNS3 version `2.2.24`
 - no GNS3 VM or remote server

**To Reproduce**
1. Press `Ctrl + 0`.
2. Hold `Ctrl` and use the scroll wheel.
3. See the following zoom factors (%): 13, 18, 25, 35, 50, 71, 100, 141, 200...
3. Press `Ctrl + 0`.
4. Use `Ctrl + -` and `Ctrl + +` for zooming.
5. See the following zoom factors (%): 11, 12, 15, 18, 21, 25, 30, 35, 42, 50, 59, 71, 84, 100, 119, 141, 168, 200...

Especially I missed 84% and 119% when zooming with mouse.

**Comment by grossmj** [comment]
Fixed, thanks 👍
