### ISSUE TITLE
It's able to save template with empty Port name, which then leads to different intermittent issues

### ISSUE THREAD

**Issue by andrej-korshikov** [GNS3/gns3-gui#3228]
**GNS3 version and operating system:**
 - OS: `Arch Linux` (Linux laptop 5.13.13-zen1-1-zen # 1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux)
 - GNS3 version `2.2.24`
 - no GNS3 VM or remote server

**To Reproduce**
1. Go to `Configure template`, `Network`, `Configure custom adapters`.
2. Make one (or several) `Port name` empty.
3. Save the template.
4. Drag the node to the workspace. Results are different, I couldn't achieve stable behavior.

**Variant 1, the most often (the long error)**
Error while creating node from template: Bad request http://127.0.0.1:3080/v2/compute/projects/cb0c57f0-5cfe-407f-b8cf-2a3b082209a6/qemu/nodes {
    "message": "JSON schema error with API request '/v2/compute/projects/cb0c57f0-5cfe-407f-b8cf-2a3b082209a6/qemu/nodes' and JSON data '{'qemu_path': '/usr/bin/qemu-system-x86_64', 'hda_disk_image': '/home/korshikov/GNS3/images/QEMU/jinstall-vmx-14.1R4.8-domestic.img', 'hda_disk_interface': 'ide', 'hdb_disk_interface': 'none', 'hdc_disk_interface': 'none', 'hdd_disk_interface': 'none', 'boot_priority': 'c', 'ram': 3583, 'cpus': 2, 'adapters': 12, 'adapter_type': 'e1000', 'legacy_networking': False, 'replicate_network_connection_state': False, 'create_config_disk': False, 'on_close': 'power_off', 'cpu_throttling': 0, 'process_priority': 'normal', 'linked_clone': True, 'name': 'r1', 'console_type': 'telnet', 'custom_adapters': [{'adapter_number': 0, 'port_name': 'fxp0'}, {'adapter_number': 1, 'port_name': 'em1'}, {'adapter_number': 2, 'port_name': 'ge-0/0/0'}, {'adapter_number': 3, 'port_name': 'ge-0/0/1'}, {'adapter_number': 4, 'port_name': 'ge-0/0/2'}, {'adapter_number': 5, 'port_name': ''}, {'adapter_number': 6, 'port_name': 'ge-0/0/4'}, {'adapter_number': 7, 'port_name': 'ge-0/0/5'}, {'adapter_number': 8, 'port_name': 'ge-0/0/6'}, {'adapter_number': 9, 'port_name': 'ge-0/0/7'}, {'adapter_number': 10, 'port_name': 'ge-0/0/8'}, {'adapter_number': 11, 'port_name': 'ge-0/0/9'}], 'node_id': '6c64dea1-d47d-4b7d-8f5a-33e07531d9ef'}': '' is too short",
    "method": "POST",
    "path": "/v2/compute/projects/{project_id}/qemu/nodes",
    "request": {
        "adapter_type": "e1000",
        "adapters": 12,
        "boot_priority": "c",
        "console_type": "telnet",
        "cpu_throttling": 0,
        "cpus": 2,
        "create_config_disk": false,
        "custom_adapters": [
            {
                "adapter_number": 0,
                "port_name": "fxp0"
            },
            {
                "adapter_number": 1,
                "port_name": "em1"
            },
            {
                "adapter_number": 2,
                "port_name": "ge-0/0/0"
            },
            {
                "adapter_number": 3,
                "port_name": "ge-0/0/1"
            },
            {
                "adapter_number": 4,
                "port_name": "ge-0/0/2"
            },
            {
                "adapter_number": 5,
                "port_name": ""
            },
            {
                "adapter_number": 6,
                "port_name": "ge-0/0/4"
            },
            {
                "adapter_number": 7,
                "port_name": "ge-0/0/5"
            },
            {
                "adapter_number": 8,
                "port_name": "ge-0/0/6"
            },
            {
                "adapter_number": 9,
                "port_name": "ge-0/0/7"
            },
            {
                "adapter_number": 10,
                "port_name": "ge-0/0/8"
            },
            {
                "adapter_number": 11,
                "port_name": "ge-0/0/9"
            }
        ],
        "hda_disk_image": "/home/korshikov/GNS3/images/QEMU/jinstall-vmx-14.1R4.8-domestic.img",
        "hda_disk_interface": "ide",
        "hdb_disk_interface": "none",
        "hdc_disk_interface": "none",
        "hdd_disk_interface": "none",
        "legacy_networking": false,
        "linked_clone": true,
        "name": "r1",
        "node_id": "6c64dea1-d47d-4b7d-8f5a-33e07531d9ef",
        "on_close": "power_off",
        "process_priority": "normal",
        "qemu_path": "/usr/bin/qemu-system-x86_64",
        "ram": 3583,
        "replicate_network_connection_state": false
    },
    "status": 400
}

**Variant 2**
Error while creating node from template: Invalid data in topology file: '' is too short in schema: {"type": "string", "description": "Custom port name", "minLength": 1}
Invalid data in topology file: '' is too short in schema: {"type": "string", "description": "Custom port name", "minLength": 1}

**Variant 3**
The node is successfully placed on the workspace, but empty `Port name` is replaced with `EthernetX` (by `X` I mean 0, 1, etc - it depends on the port number).
Sometimes it's possible to use this node.
Sometimes attempts to use this node lead to the error from `Variant 2`.
Sometimes `Port name` is present in the `Custom adapters configuration` dialog, but doesn't present in the pop-up panel (when hover mouse over the node on the workspace).

**Variant 4 (the upsetting one)**
After dragging the node to the workspace, GNS3 GUI is crashed (unfortunately, I saw this variant only once and didn't save the log).
After restarting, GUI said that server was still running, and killed and restarted the server.
After that, the template with empty Port name was totally disappeared. I mean, there was no my experimental template at all, I had to recreate it again.

**Comment by andrej-korshikov** [comment]
Disappearing of the template with empty `Port name` after restarting GNS3 is normal. Well, at least it's a stable behavior.

**Comment by grossmj** [comment]
Fixed :)
