### ISSUE TITLE
GNS3 Server hangs after creating 6 packet captures

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3229]
Steps to reproduce:

1. Create a project with enough nodes to have more than 6 connections
2. Start all nodes in project
3. Start packet captures for 5 links (with or without starting Wireshark interface for each capture)
4. Start a 6th packet capture (Capture does start)
5. Server fails to respond to any commands from the client from this point

**Comment by thomastrung** [comment]
I have same issue. Afater capture wireshark on the 6 interface then can not connect to GNS3 VM Server any more.

**Comment by gujun4990** [comment]
I also have same issue. I have no idea how to solve the issue.

**Comment by grossmj** [comment]
Should be fixed in version 3.0 (to be released).
