### ISSUE TITLE
"Custom symbols" can't be unfolded after using "Filter" field

### ISSUE THREAD

**Issue by andrej-korshikov** [GNS3/gns3-gui#3231]
**GNS3 version and operating system:**
 - OS: `Arch Linux` (Linux laptop 5.13.13-zen1-1-zen # 1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux)
 - GNS3 version `2.2.25`
 - no GNS3 VM or remote server

**Reproduce**
1. Click on `Change symbol`, `Symbols library`.
2. Type something in the `Filter` field.
3. Delete all characters from the `Filter` field (make it empty again).
3. See that `Custom symbols` category doesn't have grey triangle now, so it's impossible to unfold it.

**Screenshots:**
![image](https://user-images.githubusercontent.com/15959858/132161768-f40b4054-160e-4231-a6bd-2953f174f06f.png)

I've written about this behavior in **Part 4** of https://github.com/GNS3/gns3-server/issues/1969, it wasn't fixed in 2.2.25.

**Comment by grossmj** [comment]
Fixed, thanks 👍
