### ISSUE TITLE
Gray and green affinity "cloud" symbols have The Black Square inside

### ISSUE THREAD

**Issue by andrej-korshikov** [GNS3/gns3-gui#3232]
**GNS3 version and operating system:**
 - OS: `Arch Linux` (Linux laptop 5.13.13-zen1-1-zen # 1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux)
 - GNS3 version `2.2.25`
 - no GNS3 VM or remote server

**Screenshots:**
![image](https://user-images.githubusercontent.com/15959858/133565412-1999adf1-95a9-4d65-8468-426aae7a3101.png)
![image](https://user-images.githubusercontent.com/15959858/133565869-161ae887-d168-411a-84a4-b71140c48d0d.png)
![image](https://user-images.githubusercontent.com/15959858/133565914-ce7b052e-c129-4c8f-bafd-9b22a5e95fa3.png)

**Additional context**
The only external viewer which shows these black squares is `gImageReader`.
![image](https://user-images.githubusercontent.com/15959858/133569278-4f8e2041-5d72-4cc6-a9d9-42ccd2839a42.png)

I've opened the files in `Geeqie`, `Ristretto`, `Firefox` and `Chromium`, and have seen ordinary white background without black square.

Anyway, `svgcheck` (`pip install svgcheck`) finds a bunch of problems, but it finds relatively similar amount of problems in others affinity files.

**Comment by grossmj** [comment]
Fixed, thanks 👍 

![Screenshot from 2021-09-20 17-45-26](https://user-images.githubusercontent.com/4752614/133973547-c027edb4-2d68-4401-9023-e05b3eae790f.png)
