### ISSUE TITLE
Upgrade GNS3 VM from 2.2.24 to 2.2.25 = 2.2.3

### ISSUE THREAD

**Issue by Ales999** [GNS3/gns3-gui#3233]
My GNS3 Server running of ESXi 6.5, current version 2.2.21.

Today start update (before update stutdown VM, create snapsot and again start VM):

My progress:

2.2.21 --> 2.2.22 = ok , after restart VM - version 2.2.22 
2.2.22 --> 2.2.23 = ok,  after restart VM - version 2.2.23
2.2.23 --> 2.2.24 = ok,  after restart VM - version 2.2.24
2.2.24 --> 2.2.25 = ok,  after restart VM - server say version 2.2.**3**

Rolback to snapshot before start update, current 2.2.21.

**Comment by mortiz-code** [comment]
Hi,
In my case, GNS3 Server running of ESXi 6.7, current version 2.2.24 --> 2.2.25 = ok, after restart VM - server say version 2.2.7
.


Regards.

**Comment by grossmj** [comment]
Something strange is definitely going on... One workaround has been found: https://github.com/GNS3/gns3-vm/issues/157#issuecomment-919806013

Please let us know if it works for you as well.

**Comment by mortiz-code** [comment]
I made the directory change but I got this issue when I made the upgrade.

![image](https://user-images.githubusercontent.com/62490642/133860161-f3954262-6726-4f36-ac2d-091e6d4cc160.png)

**Comment by marktongarcia** [comment]
I resolved mine by reupdating via cli.

Mark

**Comment by sliddjur** [comment]
I updated from 2.2.24 to 2.2.25 and I got 2.2.7.

**Comment by sliddjur** [comment]
I did the trick that @grossmj linked to, and now I have 2.2.25, but suddenly all my appliance templates are gone! My projects are still there, and I can start vm's in the projects.

**Comment by grossmj** [comment]
I have made changes to the upgrade script, please try to change version again.

**Comment by DominicHarford** [comment]
I just did the upgrade from 2.2.24 to 2.2.25 and ended on version 2.2.0.
Similar to the linked thread I had a directory "/usr/local/lib/python3.6/dist-packages/gns3server" in which version.py file 2.2.0.
Reverted to my pre-update snapshot and renamed this directory and was then able to upgrade to 2.2.25

**Comment by grossmj** [comment]
I changed the upgrade process to use PyPi instead of our GitHub repository: https://github.com/GNS3/gns3-vm/commit/08fd67d091e79a7944740cf73298914dce33ffd7

This should fix this issue and also allow for faster upgrades.
