### ISSUE TITLE
Can't use Web client Launcher/Config.exe on Win 10

### ISSUE THREAD

**Issue by bolbie** [GNS3/gns3-gui#3241]
Description:
Have downloaded an update for GUI from 2.2.25 to 2.2.26 on the website.
While installation it asked me to delete 2.25 first - done.
Then I've installed 2.26, at the end choose to start GNS3 and received an error:
"cx_Freeze: Application Terminated
Can't import Qt modules: Qt and/or PyQt is probably not installed correctly..."

 - OS: Windows 10, Version: 21H1, Build: 19043.1237
 - GNS3 version 2.26
 - GNS3 VM
 - Python version: 3.10
 
Steps to reproduce the behaviour:
1. Go to the WebClient folder (C:\ProgramFiles\GNS3\WebClient)
2. Try to start via PowerShell or just click on the web client.
3. See an error

![image](https://user-images.githubusercontent.com/48124114/136555626-ff535ba1-52f9-4bf0-aec9-f097fbb26d2c.png)

**Comment by grossmj** [comment]
This was due to a packaging issue. I have re-packaged the Windows installer, please download again and re-install. Let me know if you still have the same problem.
