### ISSUE TITLE
Symbols in "Symbol selection" dialog are not placed in alphabetical order

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3245]
**Describe the bug**
Symbols in **Symbols library** (**Symbol selection** dialog) are placed in random order. And this order is different for different "folders" (see screenshots). I don't remember this behavior in previous version (2.2.25).

**GNS3 version and operating system:**
 - OS: Arch Linux (Linux laptop 5.14.8-zen1-1-zen # 1 ZEN SMP PREEMPT Sun, 26 Sep 2021 19:36:16 +0000 x86_64 GNU/Linux)
 - GNS3 version: 2.2.26
 - No use of the GNS3 VM or remote server

**To Reproduce**
1. Open **Symbol selection** dialog
2. Unfold any "folder"

**Screenshots**
![image](https://user-images.githubusercontent.com/15959858/137024862-9912f6a9-5c34-4096-8e00-de19d5225429.png)
![image](https://user-images.githubusercontent.com/15959858/137024910-e9b89073-798d-4676-a939-fb214d0b4809.png)
![image](https://user-images.githubusercontent.com/15959858/137024935-e1b6e833-2d29-4e13-9f01-629b2b46e7a1.png)
![image](https://user-images.githubusercontent.com/15959858/137024963-8aedca10-bcbc-4408-8563-e6fc6de4f8fd.png)

**Additional context**
May be related to #3230 or #3231.

**Comment by grossmj** [comment]
Fixed
