### ISSUE TITLE
GNS3 2.26 Cloud via Bridged adapter not working. 

### ISSUE THREAD

**Issue by bigern314** [GNS3/gns3-gui#3246]
I'm running GNS3 2.2.26.  I'm using the latest VM hosted on virtual box Version 6.1.26 r145957 (Qt5.6.2).  This is all freshly installed after I removed my 2.17 setup. 

Everything works fine...except with I add a bridged adapter to the VM, then when  configuring the Cloud select that as eth2, I'm unable to connect out of the network via any device I add in the GNS topology.  This all works fine on GNS3 2.17 but every version since then it has been broken.  

Right now I have a Cisco 7200 virtual router setup and it is connected to Cloud eth2 which is a bridged adapter on the VM that is the third network adapter.  

My physical router is an Asus 172.16.255.1/24.  Gi0 on the virtual Cisco is IP 172.16.255.200/24

_interface GigabitEthernet1/0
 ip address 172.16.255.200 255.255.255.0
 negotiation auto

Gateway of last resort is 172.16.255.1 to network 0.0.0.0

172.16.0.0/24 is subnetted, 1 subnets
C       172.16.255.0 is directly connected, GigabitEthernet1/0
S*   0.0.0.0/0 [1/0] via 172.16.255.1
CoreRouter#ping 172.16.255.1

Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 172.16.255.1, timeout is 2 seconds:
.....
Success rate is 0 percent (0/5)
CoreRouter#sh arp
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
Internet  172.16.255.1            0   8416.f95d.f7a4  ARPA   GigabitEthernet1/0 _*Asus Router_
Internet  172.16.255.101          0   3c7c.3f5f.9c4a  ARPA   GigabitEthernet1/0 _*my laptop i'm running GNS3 on, wired_
Internet  172.16.255.200          -   ca01.05b3.001c  ARPA   GigabitEthernet1/0 _*Gi1/0_
CoreRouter#ping 172.16.255.1

Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 172.16.255.1, timeout is 2 seconds:
.....
Success rate is 0 percent (0/5)
CoreRouter#_

The virtual router is seeing other devices on that network and completing arp but it is unable to ping them or complete a traceroute.  If I try to ping 172.16.255.200 from the host at 172.16.255.101 or the Asus router I get "request timed out".  The Asus router has the cisco virtual router in its arp table.  

Did something change after 2.17?  Because if I reinstall that version everything works fine. 

Laptop is Windows 10 19043.1288 and I'm running off the Ethernet port rather than wireless.

**Comment by grossmj** [comment]
> Did something change after 2.17? Because if I reinstall that version everything works fine.

I don't think so. When you reinstalled v2.2.17, did you change the version from within the GNS3 VM or did download the VM for 2.2.17 again?

**Comment by bigern314** [comment]
I would revert to the 2.17 VM.  

At this point I just removed VirtualBox and went to VMware player.  I'm using 2.26 GNS now with that and the up to date VM.  Its working fine.  I'm just pressed for time and couldn't put anymore into trying to get VirtualBox to work properly with it.

**Comment by grossmj** [comment]
Thanks for the update. VirtualBox has become more problematic in the last couple of years. I always recommend VMware (player or pro).

I will keep this open so I can try on my side to see what is wrong.
