### ISSUE TITLE
Links duplicates in topology summary

### ISSUE THREAD

**Issue by dias-yelgonov** [GNS3/gns3-gui#3251]
**Description:**
I'm not really sure that it could be considered as a bug (in my opinion it seems so), but I have questions about connections showing in the "Topology summary" window.
1. When I just create a connection (link) between two nodes, the topology summary shows two records:
Some connections are duplicated some of them don't
![image](https://user-images.githubusercontent.com/48124114/138121593-0c652cc1-293c-4768-94b4-67c60085e12d.png)
2. If I click and select one of the records, it highlights the connection in red colour:
![selected link](https://user-images.githubusercontent.com/48124114/138117509-049873b5-6e89-4bbb-9f85-817931ff9353.png)
3. Then I select another record and the highlighting disappeared.
![unselected link](https://user-images.githubusercontent.com/48124114/138117801-e5b1c827-a2fe-424b-9790-21bcca7dd91b.png)
4. And now strange things are happening: 
 - "delete" option is available only for "real" connections that could be highlighted by selecting them in the topology summary window
 - After deleting the "real link", source ports are still persistent in a description (topology summary)
![phantom links](https://user-images.githubusercontent.com/48124114/138118415-a5cf339b-10d3-4405-8a4e-c9f8bae3f580.png)
5. That window helps to select links in medium/large projects, but this "bug" makes it difficult to operate with it.

**GNS3 version and operating system:**
 - OS: Win 10 21H1 Build 19043.1288
 - GNS3 version 2.2.26 / GNS 3 VM 2.2.26

**To Reproduce**:
Steps to reproduce the behaviour:
1. Add two or more nodes to the project (any type of node)
2. Create at least one connection between them
3. Expand links in "topology summary" windows
4. See the duplicates record
5. Find a "real" link between nodes by selecting them, until the link is highlighted in the topology
6. Delete it
7. Watch the ports of the deleted link in the description

**Comment by grossmj** [comment]
I think this issue only happens on Windows in a specific context. Need more investigation.

**Comment by bolbie** [comment]
Seems you are right. I've tested on Ubuntu 20.04 (local gns3 server) - can't replicate it there, but on the main & second Windows machine with GNS3 VM (both Win 10) the problem still persist.

**Comment by grossmj** [comment]
I could replicate the issue on my side. I think it is fixed now. Please comment back if you still face issue after the next release.
