### ISSUE TITLE
nano gns3

### ISSUE THREAD

**Issue by 3lnyn0** [GNS3/gns3-gui#3253]
I'm trying to write something with nano and i can't.
The cursor is down in the left corner, I can't move it.
I tried from 3 guests: networkautomation, python and kali linux, I have the same problem on all

![automation](https://user-images.githubusercontent.com/26303767/138322167-64baa405-5292-4e55-bb2c-23bc123f6c69.PNG)

**Comment by grossmj** [comment]
Looks like it comes from the terminal software you use. I do not have any issue on my side.

![Screenshot from 2021-11-03 10-51-51](https://user-images.githubusercontent.com/4752614/139969200-58ac88b7-06f3-402f-9e8b-fade977a4a13.png)

What software do you use?
