### ISSUE TITLE
"Symbol selection" dialog detects new files, but doesn't detect changes in existed files

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3256]
**Describe the bug**
"Symbols library" does not update icon when content of the file was changed but filename is the same.

**GNS3 version and operating system:**
 - OS: Arch Linux (Linux laptop 5.14.8-zen1-1-zen # 1 ZEN SMP PREEMPT Sun, 26 Sep 2021 19:36:16 +0000 x86_64 GNU/Linux)
 - GNS3 version: 2.2.26
 - No use of the GNS3 VM or remote server

**To Reproduce**
1. Copy "linux_guest.svg" to "test.svg".
2. Open "Symbol selection" dialog.
3. Confirm that "test" symbol looks like "linux_guest".
4. Close "Symbol selection" dialog.
5. Copy "firefox.svg" to "test.svg" (overwrite "test.svg" with totally new content).
6. Open "Symbol selection" dialog.
7. See that "test" symbol still looks like "linux_guest", but it is "firefox" now.

**Screenshot**
You can see "linux_guest.svg" image here (as "test"), but actually "test.svg" is a copy of "firefox.svg".
![image](https://user-images.githubusercontent.com/15959858/138781211-940a5596-e476-4c7a-be1f-f8925e0dadb4.png)

**Comment by grossmj** [comment]
This is most likely because of our cache system. I am going to have a closer look later.

**Comment by grossmj** [comment]
Fixed
