### ISSUE TITLE
GNS3 VM for MBP 2021 w/Apple Silicon

### ISSUE THREAD

**Issue by adilnas62711411** [GNS3/gns3-gui#3258]
When will GNS3 VM be available for the new 2021 Mac Book Pro running Monterey on Apple Silicon?

It currently is not able to load in VMware Fusion 12 Pro.  When I try to run the GNS3 VM, I receive the error message:

Transport (VMDB) error 014:Pipe connection has been broken.

Adil

**Comment by grossmj** [comment]
We have plans for this, please see https://github.com/GNS3/gns3-gui/issues/3257
