### ISSUE TITLE
The 'gns3-gui==2.2.26' distribution was not found

### ISSUE THREAD

**Issue by khalidalwalid** [GNS3/gns3-gui#3259]
Hello,..
I've installed gns3-gui and gns3-server well, but it doesn't run properly coz it says "The 'gns3-gui==2.2.26' distribution was not found and is required by the application".

What is that mean? and what should I do?
By the way, I'm using Ubuntu 20.04 (focal fossa)
Thanks
![gns3 not working](https://user-images.githubusercontent.com/33023197/139665723-27c4b4c8-2b4f-49f2-9a52-8ba16041f63e.jpg)
.

**Comment by grossmj** [comment]
What do you see if you execute this command `python3 -m pip freeze | grep gns3` ?

**Comment by khalidalwalid** [comment]
It shows nothing

**Comment by grossmj** [comment]
@khalidalwalid have you installed from the PPA or Pypi?
