### ISSUE TITLE
Can not draw a note Sentry SDK is not available

### ISSUE THREAD

**Issue by thuanghai** [GNS3/gns3-gui#3264]
**Describe the bug**
When I add a note for description. GNS3 report can not capture exception: Sentry SDK is not available.

**GNS3 version and operating system (please complete the following information):**
 - OS: Fedora 35
 - GNS3 version 2.2.26
 - Bare metal

**To Reproduce**
1. Click the 'Add a note' button
2. Add note failed, and report can not capture exception: Sentry SDK is not available.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/7972664/143004873-129cdfef-a76d-40a0-abb7-48a813b741e3.png)

**Comment by BenOoi** [comment]
I have the same issues. Goes away when you disable the grid.

Running Fedora 35 also. Windows does not have this problem. 2.2.24 and 2.2.26 have the same issue.

**Comment by thuanghai** [comment]
And when I install sentry-sdk using command 'pip install sentry-sdk', it report like below:
![image](https://user-images.githubusercontent.com/7972664/143151311-7d0b578a-12b7-49e0-8c8c-8d8d177208d8.png)
Also can not draw.

**Comment by tarzq306** [comment]
> I have the same issue. Goes away when you disable the grid.
> 
> Running Fedora 35 also. Windows does not have this problem. 2.2.24 and 2.2.26 have the same issue.
> 
> Running from cli gives me the following info:
> 
> ```
> ****** Exception detected, traceback information saved in /home/beno/.config/GNS3/2.2/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1664, in drawBackground
>     painter.drawLine(x, rect.top(), x, rect.bottom())
> TypeError: arguments did not match any overloaded call:
>   drawLine(self, QLineF): argument 1 has unexpected type 'int'
>   drawLine(self, QLine): argument 1 has unexpected type 'int'
>   drawLine(self, int, int, int, int): argument 2 has unexpected type 'float'
>   drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'int'
>   drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'int'
> 
> 2021-11-23 15:27:02 WARNING crash_report:136 Cannot capture exception: Sentry SDK is not available
> ```

I try to disable it an it works, thanks bro, you just saved my life

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-gui/issues/3271
