### ISSUE TITLE
Use same VM template across all computes.

### ISSUE THREAD

**Issue by vint66** [GNS3/gns3-gui#3265]
As for now in order to use remote server in addition to main server we have to create VM template per compute node. It means same VM should be duplicated per compute node.

Could you improve that part?

Basically it should be one template only but should be an option to run it on particular compute node, similar how you did for cloud object.

This will improve scale out options.

**Comment by spikefishjohn** [comment]
I just ran into this. I'm going to dust off some python skills and see if I can do this but it would be nice if there was an option to synchronize templates to remotes.

Yes, images would still need to be copied, but mirroring a directory between servers isn't a new issue and has a lot of easy fixes. Template syncing doesn't.
