### ISSUE TITLE
Unknow error, GNS3 cannot load GUI 

### ISSUE THREAD

**Issue by alifnuxer** [GNS3/gns3-gui#3268]
I have install gns3 on artix linux (OpenRC), I follow this blog https://aryapramudika.github.io/installasi-gns3-di-arch-linux/ and its work for arch linux (systemd) but this is not work for gns3 on artix linux cannot load gns3 gui

**Comment by grossmj** [comment]
Do you see any error message? Like PyQt is not installed or similar.

**Comment by Rohman4534** [comment]
I have that proble too, i have installed qt5 and pyqt. But gns-gui still not displaying
