### ISSUE TITLE
Nexus 9000v constantly crashes

### ISSUE THREAD

**Issue by sa6kad** [GNS3/gns3-gui#3269]
Nexus 9000v constantly crashes in GNS3. A node can run no more than 5-6 hours and then it gets unresponsive for a short time and finally reboots. Not clear what exactly causes the crash, it happens pretty randomly.

The setup is as follows:
OS: Ubuntu 20.04 x64 running on a VM i VMWare vSphere
GNS3: 2.2.27 (however tested even on 2.2.17 where it appear a little more stable, but just a little)
NX: 9.3.1, 9.3.8, 7.0.3.I7.9

I tried two setups: 1. running VMware server as a compute for the switches and a ubuntu VM running gns3-gui. 2. Running GNS3 only on a ubuntu VM. There was always enough RAM and CPU

For some time ago I used nxos 9.3.1 and 9.2.x on some older version of GNS3 (not sure which one though, might be 2.1.x) and it was stable, it could be up for many days without crashes.

**Comment by grossmj** [comment]
I don't think we can do much on our side. Some appliances can just be plain unstable...
