### ISSUE TITLE
Add a deprecation warning in Qemu wizard about ASA

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#327]
With ASAv support thanks to VmWare we should encourage people to use ASAv instead of ASA.

**Comment by grossmj** [comment]
Actually I think we should have a depreciation warning for using Qemu on Windows or Mac OS X ;)

**Comment by noplay** [comment]
I agree if we use Qemu on local server for Windows or Darwin we should display a warning

**Comment by noplay** [comment]
I'm on it

**Comment by noplay** [comment]
With all the warnings :)
![capture d ecran 2015-06-29 a 15 23 03](https://cloud.githubusercontent.com/assets/345437/8408766/0ddaf338-1e73-11e5-8057-e8b80cf50e68.png)
