### ISSUE TITLE
Grid system is not working on the latest GNS3 gui release

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3271]
I'm running GNS3 latest release and after I recently updated my system to Python 3.10 the grid system is broken.

 - OS: Archlinux
 - Python: 3.10
 - GNS3 version: 2.2.27
 - Bare metal installation

**To Reproduce**
1. Open an existing project which has Show the grid option enabled
2. Grid is not displayed on the desktop GUI.
3. The issue is not replicated on the Web UI
4. The following two tracebacks are shown on the CLI after starting the desktop GUI.

**Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1666, in drawBackground
    painter.drawLine(x, rect.top(), x, rect.bottom())
TypeError: arguments did not match any overloaded call:
  drawLine(self, QLineF): argument 1 has unexpected type 'int'
  drawLine(self, QLine): argument 1 has unexpected type 'int'
  drawLine(self, int, int, int, int): argument 2 has unexpected type 'float'
  drawLine(self, QPoint, QPoint): argument 1 has unexpected type 'int'
  drawLine(self, Union[QPointF, QPoint], Union[QPointF, QPoint]): argument 1 has unexpected type 'int'

****** Exception detected, traceback information saved in /home/cioby/.config/GNS3/2.2/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/items/node_item.py", line 510, in paint
    painter.drawRect((brect.width() / 2.0) - 10, (brect.height() / 2.0) - 10, 20, 20)
TypeError: arguments did not match any overloaded call:
  drawRect(self, QRectF): argument 1 has unexpected type 'float'
  drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
  drawRect(self, QRect): argument 1 has unexpected type 'float'

****** Exception detected, traceback information saved in /home/cioby/.config/GNS3/2.2/exceptions.log ********

PLEASE REPORT ON https://www.gns3.com

**Comment by b-ehlers** [comment]
Error message is the same as in https://github.com/GNS3/gns3-gui/issues/3264, the second argument to drawLine() has type float instead of int. This issue has an additional type mismatch on drawRect(). Both installations are using python 3.10.

**Comment by etiennewan** [comment]
I just pushed a pull request without realizing this issue existed https://github.com/GNS3/gns3-gui/pull/3272

**Comment by grossmj** [comment]
@etiennewan I merge your PR. Thanks :)
