### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#328]
https://app.getsentry.com/gns3/gns3-gui/group/64880745/

```
IndexError: list index out of range
  File "gns3/graphics_view.py", line 662, in dropEvent
    path = event.mimeData().urls()[0].toLocalFile()
```

**Comment by grossmj** [comment]
Exception is the code when dropping a .gns3 file to the GNS3 drawing area.

**Comment by noplay** [comment]
I take this

**Comment by noplay** [comment]
Hmm the features is broken on OSX:
https://bugreports.qt.io/browse/QTBUG-40449

I propose we wait QT5 for OSX.

**Comment by noplay** [comment]
By the way I have fixed the issue but I don't know how you can trigger it.

**Comment by grossmj** [comment]
First time we get this error... that user must have magic hands ;)
