### ISSUE TITLE
Can't tell which project a none linked node is in.

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3280]
**Is your feature request related to a problem? Please describe.**
You can only have one none linked node in any gns3 project. If you add a 2nd you get an error saying its already in use by node "whatever the node name is". The problem is it doesn't tell you which project. 

**Describe the solution you'd like**
Add the project where the node is found to the error message.

**Describe alternatives you've considered**
I made a python script that shows all running nodes that aren't switches and the project they're in as a work around.

**Additional context**

**Comment by grossmj** [comment]
> You can only have one none linked node in any gns3 project.

I am not sure I understand. Do you have an example or screenshot? Thanks :)

**Comment by spikefishjohn** [comment]
Another quality RFE! The title should be "Can**'t** tell which project a none linked node is in".

What needs to be improved is the error you get when you attempt to add a 2nd node from a template that isn't linked.

The error should include the project name that the node is located in to make it easier to find. I ran into a case where I had 30 projects and couldn't tell where it was. 

Does that make sense? Its on my todo to take a stab at patching it.

**Comment by grossmj** [comment]
Got it, thanks 👍

**Comment by grossmj** [comment]
Do you have the problem with VirtualBox or VMware templates?

**Comment by spikefishjohn** [comment]
I don't use either of those, but my assumption is the same problem would exist. Say I make 5 projects. In one project I make a new node based on a template that doesn't have "use as linked base vm". Now I got into project 5 and try to add another node using the same template. The error say which template node is having issues but doesn't say which project its located in.

Like I said, just adding the project name (not uuid) would address the issue.

**Comment by spikefishjohn** [comment]
https://github.com/GNS3/gns3-server/pull/2024

w00t!
