### ISSUE TITLE
Using some node symbols leads to exception in "node_item.py" - "argument 1 has unexpected type 'float'"

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3282]
**Describe the bug**
Using some node symbols produces the following error :
> Traceback (most recent call last):
>   File "/home/korshikov/-.software/GNS3/lib/python3.10/site-packages/gns3/items/node_item.py", line 510, in paint
>     painter.drawRect((brect.width() / 2.0) - 10, (brect.height() / 2.0) - 10, 20, 20)
> TypeError: arguments did not match any overloaded call:
>   drawRect(self, QRectF): argument 1 has unexpected type 'float'
>   drawRect(self, int, int, int, int): argument 1 has unexpected type 'float'
>   drawRect(self, QRect): argument 1 has unexpected type 'float'
> 
> 2022-01-13 15:36:59 INFO crash_report:150 Crash report sent with event ID: c38a41cc1372435a9c8f180d916e8867`

Some affected symbols:
- Affinity-cicrce-blue - atm
- Affinity-square-gray - switch

Some unaffected symbols:
- Affinity-cicrce-blue - router2
- Affinity-square-blue - laptop

If I close the project, open another one, and then reopen the project with problematic symbols (without exiting GNS3) - then this exception isn't thrown. This behavior is stable and reproducible.

**GNS3 version and operating system:**
 - OS: Arch Linux (Linux laptop 5.15.13-zen1-1-zen # 1 ZEN SMP PREEMPT Wed, 05 Jan 2022 16:21:01 +0000 x86_64 GNU/Linux)
 - GNS3 version: 2.2.29
 - Python version: 3.10.1
 - No use of the GNS3 VM or remote server

**To Reproduce**
1. Start GNS3. In the "Project" dialog select "Projects library" and open the project with affected symbols.
2. See the error.
3. Open another (for example, empty) project.
4. Reopen the project with affected symbols.
5. See there is no error.
6. Close GNS3 and start it once again. Open the problematic project.
7. See there is the same error.

**Additional context**
I've seen some issues (for example, #3281) with the same error message - "argument 1 has unexpected type 'float'".

**Comment by grossmj** [comment]
Fixed, thanks 👍
