### ISSUE TITLE
Error Expection when duplicating labels GNS3 2.2.29

### ISSUE THREAD

**Issue by marvaen7** [GNS3/gns3-gui#3283]
`GNS3 `2.2.29` 
`Python 3.10.1`

Python throwing exception when duplicating  _`Lables`_ :

> ****** Exception detected, traceback information saved in /home/mannaa/.config/GNS3/2.2/exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1414, in duplicateActionSlot
>     self.createDrawingItem(type, item.pos().x() + 20, item.pos().y() + 20, item.zValue(), rotation=item.rotation(), svg=item.toSvg())
>   File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1641, in createDrawingItem
>     item = TextItem(pos=QtCore.QPoint(x, y), z=z, rotation=rotation, locked=locked, project=self._topology.project(), drawing_id=drawing_id, svg=svg)
> TypeError: arguments did not match any overloaded call:
>   QPoint(): too many arguments
>   QPoint(int, int): argument 1 has unexpected type 'float'
>   QPoint(QPoint): argument 1 has unexpected type 'float'

**Comment by grossmj** [comment]
Fixed, thanks 👍
