### ISSUE TITLE
Renamed virtualbox machines don't work

### ISSUE THREAD

**Issue by diegomoliveira** [GNS3/gns3-gui#3286]
If I rename virtualbox machines, when I close the project and open it again, it gives an error and doesn't open anymore.
Output error:
"VirtualBox has returned an error: VBoxManage.exe: error: Could not find a registered machine named 'pc2'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2733 of file VBoxManageInfo.cpp"

**Comment by grossmj** [comment]
Have you used linked base VMs?
