### ISSUE TITLE
GNS3 returns an error when trying to edit styles on shapes.

### ISSUE THREAD

**Issue by bluescreencode** [GNS3/gns3-gui#3287]
**Describe the bug:**
When trying to edit the style of a shape, GNS3 returns an error.

**GNS3 version and operating system (please complete the following information):**
 - OS: Arch Linux x86_64 
 - GNS3 version: 2.2.29 with Python 3.10.1 Qt 5.15.2 and PyQt 5.15.6
 - Appliances are hosted locally

**To Reproduce:**
1. Create a new project
2. Create a shape (rectangle, for example.)
3. Right-click and select "Style"

**Screenshots or videos:**
Video: [https://www.youtube.com/watch?v=YI7Te3bVu98](https://www.youtube.com/watch?v=YI7Te3bVu98)

**Additional context:**
GNS3 Traceback information:
`=== GNS3 2.2.29 traceback on 22 Jan 2022 16:57:13 ===
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1429, in styleActionSlot
    style_dialog = StyleEditorDialog(self._main_window, items)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/style_editor_dialog.py", line 73, in __init__
    self.uiRotationSpinBox.setValue(first_item.rotation())
TypeError: setValue(self, int): argument 1 has unexpected type 'float'`

**Comment by grossmj** [comment]
Thanks for the report. The bug has already been fixed and the fix will be included in v2.2.30
