### ISSUE TITLE
GNS3 client also is open a permanent cmd prompt with shortcut gns3.lnk

### ISSUE THREAD

**Issue by mortiz-code** [GNS3/gns3-gui#3290]
Hi folks, 

**Describe the bug**
After upgrading to 2.2.29 when I open the GNS3 client also is open a permanent cmd prompt with shortcut gns3.lnk that only goes away with I close GNS3 Client. If I close the cmd the GNS3 client also is closed.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 11 21H2
 - GNS3 version 2.2.29
 - Remote server ESXi

**Screenshots or videos**
Version:
![image](https://user-images.githubusercontent.com/62490642/152653747-a0981128-aaba-4f86-8de3-1291a28beea6.png)
![image](https://user-images.githubusercontent.com/62490642/152653775-0f67c68e-fd94-4614-903d-8ffd886f0e14.png)

CMD:
![image](https://user-images.githubusercontent.com/62490642/152653753-ef4b5976-9a4d-47c9-9a13-b06de0c5ea6c.png)

**Additional context**
It's a cosmetic problem, GNS3 works well but I don't understand why it started behaving like this.

Thanks!

**Comment by grossmj** [comment]
This should have been fixed in v2.2.31 Please comment back if you still have the problem. Thanks 👍

**Comment by mortiz-code** [comment]
Hi @grossmj I've upgraded to 2.2.31 but it has the same behavior remains.
![image](https://user-images.githubusercontent.com/62490642/158490784-4b9aa045-1e4a-417a-8b08-70fe578fefe8.png)

Thanks,

**Comment by grossmj** [comment]
Have you uninstalled GNS3 first before re-installing?

**Comment by mortiz-code** [comment]
> Have you uninstalled GNS3 first before re-installing?

Hello, 

I've uninstalled GNS3 client from my laptop and I  did a fresh install of 2.2.31 but the behavior is the same.

![image](https://user-images.githubusercontent.com/62490642/159377589-b830b70e-731b-493d-8b55-08fd0631c253.png)

**Comment by jfcisnerosm19** [comment]
Hola @mortiz-code 

Encontraste alguna solución, en mi caso actualicé a Windows 11 22H2 y me salió este "problema".

Quedo atento a tus comentarios.

Saludos.

**Comment by mortiz-code** [comment]
Hola. No, el problema sigue ahi. Nunca se soluciono.

**Comment by JCDITServices** [comment]
Having the same issue on windows 11 with v2.2.36

**Comment by JaZzSuperman** [comment]
Still happening on 2.2.37 on windows 11

**Comment by josephmhiggins** [comment]
Be advised, this can also happen if you are using the GNS3 VM and for some reason, you have to pull the plug on your computer.
The vmware ip addresses for the vmware adapters, i.e. vmnet1 and vmnet8, get erased. Consequently, the vmnet adapters get an apipa ip address. This just happened last night to me. You must go into control panel and look the ip addresses to see what is there. If ipconfig /all shows 169.254.x.x addresses for the vmnet adapters., then you must restore defaults in vmware. Restore defaults will give a new subnet for vmnet1 and vmnet8. If you do not know not have the old ip addresses, i.e. from an archived  gns3_server.log, then you still may have more problems ahead.

**Comment by mortiz-code** [comment]
Still happening on GNS 2.2.38 and W11

![image](https://user-images.githubusercontent.com/62490642/234049076-970c48cc-8a50-4a45-9636-0ef329968822.png)

**Comment by SebaRivero** [comment]
Hey, I have the same bug on GNS3 v2.2.38 and my OS is also Windows 11

**Comment by mortiz-code** [comment]
> Hey, I have the same bug on GNS3 v2.2.38 and my OS is also Windows 11 
> 
> Edit: Running GNS3 as an Administrator makes the cmd go away as soon as it apears. Some of my classmates who also have windows 11 where having the same problem and they also "fixed" it running GNS3 as an Administrator

Interesting, I'll try it tomorrow and let you know if it works.

**Comment by grossmj** [comment]
I have looked more into it and this may be because of this issue: https://github.com/microsoft/terminal/issues/12464

**Comment by grossmj** [comment]
One workaround is to switch the default terminal app to "Windows Console host" in the settings.

![Screenshot from 2024-02-12 14-38-27](https://github.com/GNS3/gns3-gui/assets/4752614/4bcb0f38-b26f-4b7d-ac07-b58798740688)

**Comment by Domoninic** [comment]
You can edit the shortcut to use the legacy Console, on the options tab enable "Use legacy console".
NOW the hidden console will be a separate console window not attached to the Window Terminal program and no need to change your OS default terminal. 
Perhaps the installer should enable this in the shortcut by default.
