### ISSUE TITLE
May I ask when will GNS3 VM for Apple M1 platform be supported?

### ISSUE THREAD

**Issue by angelyouyou** [GNS3/gns3-gui#3292]
**Is your feature request related to a problem? Please describe.**
Currently GNS3 VM is not support on Apple M1 platform.

**Describe the solution you'd like**
GNS3 VM can run on Apple M1 platform.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cristian-ciobanu** [comment]
Please check this issue for more details: https://github.com/GNS3/gns3-server/issues/2030. This has been discussed many times before.
