### ISSUE TITLE
No Communication Possible Between Host machine and Gns3 VM Qemu/dynamip Devices 

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3296]
For a quite long time I am trying to establish communication  between My Host (Window-11,Vm Ws-16.2,gns3 2.2.29) machine and devices running inside GNS3 VM (Qemu,Dynamips).but not being succeed to do so ,regarding that I had a very good conversation with Mr. Joe. But still the problem remain the same. I am doing all things following David's video but not able to make a proper communication ,can please help me to fix the issue or find out any bug in the software …..

https://www.gns3.com/community/discussions/host-machine-not-able-to-connect-from-gns3-qemu-dynamip-device

**Comment by josephmhiggins** [comment]
I think I  just got hit by this bug with gns3 2.2.21 and vmware ws pro 16.2.1.
The bug showed up after:
1. i created a system restore point
2. installed firefox
3. installed google chrome
4. then I tried to run wireshark. 

The result was wireshark timed out and the routing table of the gns3 vm is

gns3@gns3vm:~$ ip route
default via 192.168.15.1 dev eth0 proto static ----------------this is my host only network
default via 192.168.234.2 dev eth1 proto dhcp src 192.168.234.129 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.15.0/24 dev eth0 proto kernel scope link src 192.168.15.128 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.234.0/24 dev eth1 proto kernel scope link src 192.168.234.129 
192.168.234.2 dev eth1 proto dhcp scope link src 192.168.234.129 metric 100 
gns3@gns3vm:~$

A snippet of cat /var/log/syslog shows 100s of ntp failures like this: 

Mar 16 06:07:05 gns3vm systemd-timesyncd[465]: Timed out waiting for reply from 91.189.89.199:123 (ntp.ubuntu.com).

Alternatively, my routing table looks like this:
gns3@gns3vm:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.15.1    0.0.0.0         UG    0      0        0 eth0
0.0.0.0         192.168.234.2   0.0.0.0         UG    100    0        0 eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.15.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
192.168.234.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
192.168.234.2   0.0.0.0         255.255.255.255 UH    100    0        0 eth1

gns3@gns3vm:~$ 

I never noticed if my host-only subnet has a default route; I never looked at it before

I shut gns3 and vmware ws pro down.
I disabled the vmnet 1, host-only subnet, in windows control.
I *think* I the following two things happened (I did not record it so well)
1. I restarted vmware ws pro and started the gns3 vm solo, without gns3, and
2. I received the same error messages

I then when into vmware ws pro edit virtual machine settings - network adapter for the gns3 vm and 
unchecked "Connect at power on"

I booted the gns3 vm solo and logged in via the console (ooh, good to have that console connection)
and a snippet of cat /var/log/syslog shows

"Synchronized to time server"

I have not run gns3 without a network connection in ...........at least 10 years.
Without ntp, everything could fall apart.

1. I rechecked "connect at power on"
2. I reenabled vmnet 1
3. i started the gns3 vm and I still have:

gns3@gns3vm:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.15.1    0.0.0.0         UG    0      0        0 eth0
0.0.0.0         192.168.234.2   0.0.0.0         UG    100    0        0 eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.15.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
192.168.234.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
192.168.234.2   0.0.0.0         255.255.255.255 UH    100    0        0 eth1
gns3@gns3vm:~$ 

gns3@gns3vm:~$ tail -n 5 /var/log/syslog
Mar 16 07:11:06 gns3vm systemd-timesyncd[492]: Timed out waiting for reply from 91.189.89.198:123 (ntp.ubuntu.com).
Mar 16 07:11:16 gns3vm systemd-timesyncd[492]: Timed out waiting for reply from 91.189.89.199:123 (ntp.ubuntu.com).
Mar 16 07:11:26 gns3vm systemd-timesyncd[492]: Timed out waiting for reply from 91.189.91.157:123 (ntp.ubuntu.com).
Mar 16 07:11:37 gns3vm systemd-timesyncd[492]: Timed out waiting for reply from [2001:67c:1560:8003::c7]:123 (ntp.ubuntu.com).
Mar 16 07:11:47 gns3vm systemd-timesyncd[492]: Timed out waiting for reply from [2001:67c:1560:8003::c8]:123 (ntp.ubuntu.com).
gns3@gns3vm:~$ 

So something between vm16.2.1 and gns3 2.2.21, in my case, and gns3 2.2.29, in aksplease's case.

I do not know how the gns3 and vmware ws pro 16 work together to make the static routes.

I have had gns3 2.2.21 for months but I just reloaded my pc a few weeks ago and installed
vmware workstation pro 16 on ....I do not know..bad record keeping....I installed it 2 weeks ago.

Oh well. It's a bug somewhere between gns3 and vmware ws 16

**Comment by josephmhiggins** [comment]
Oh, I do not know why github did a strike through on my post.
Nothing there should have a strike through.

**Comment by josephmhiggins** [comment]
I got it. It's here. I started an ubuntu 20 version vm that I installed 10 days ago and I added a
host only adapter with a connect at power on and I got:

osboxes@osboxes:~$ ip route
default via 192.168.234.2 dev ens33 proto dhcp metric 100 
169.254.0.0/16 dev ens33 scope link metric 1000 
192.168.15.0/24 dev ens36 proto kernel scope link src 192.168.15.129 metric 101 
192.168.234.0/24 dev ens33 proto kernel scope link src 192.168.234.128 metric 100 
osboxes@osboxes:~$
