### ISSUE TITLE
GNS3 Vmware VM is missing since 2.2.30

### ISSUE THREAD

**Issue by joseaporo** [GNS3/gns3-gui#3302]
### Discussed in https://github.com/GNS3/gns3-gui/discussions/3301

<div type='discussions-op-text'>

<sup>Originally posted by **joseaporo** March  3, 2022</sup>
I am unable to download GNS3 VM 2.2.30 or 2.2.31 for VMware ESXi. Clicking "Download" Button on below link for VMware ESXi is broken, Github "Not Found".
https://www.gns3.com/software/download-vm

On https://github.com/GNS3/gns3-gui/releases, I cannot download GNS3.VM.VMware.ESXI.2.2.31.zip, it is not there, the last release which includes it is 2.2.29. </div>

**Comment by gr3ndel-qos** [comment]
Same here.  I strictly use the ESXi images, & I always like to download direct from GitHub, but the file just doesn't exist.

I have no intention of using any other platform besides ESXi for running a virtual GNS3 server.

    Like others I'm stuck at v2.2.29 - because what has worked for me for a long time to keep things stable:
When there's a new version available, I download the new ESXi image, deploy a new VM via the OVA.
Then via the GNS3 console menu, do a transfer of the appliance images & labs from the previous GNS3 VM to the new one.  Then test the new VM.  
If the new VM is stable enough after testing a few existing labs, then I transition to using the new version of the VM & the fat client.

**Comment by muranternet** [comment]
Getting a lot of questions about this from students and in Reddit. As others pointed out 2.2.30 and 2.2.31 have no ESXi VM images at https://github.com/GNS3/gns3-gui/releases/. No responses in GNS3 fora or here. The GNS3 official page still recommends using the VM and links to a nonexistent file from the VM download page.

**Comment by spikefishjohn** [comment]
*UNTESTED*
#Download ovftool
https://developer.vmware.com/web/tool/4.4.0/ovf

#Download the VMware Workstation VM
https://github.com/GNS3/gns3-gui/releases/download/v2.2.31/GNS3.VM.VMware.Workstation.2.2.31.zip

#Download these scrips
https://github.com/GNS3/gns3-vm/blob/master/workstation_to_esxi.py

# setup the env.
#ovftool needs to be installed in the path.
unzip GNS3.VM.VMware.Workstation.2.2.31.zip
python3 workstation_to_esxi.py "GNS3 VM.ova" "GNS3VM.VMWare.ESXI.2.2.31.ova" 
zip -9 "GNS3 VM VMware ESXI 2.2.31.zip" "GNS3 VM.ova"

**Comment by grossmj** [comment]
Sorry, something was broken in the release process. I have manually built and uploaded the ESXi VM for v2.2.31 https://github.com/GNS3/gns3-gui/releases/tag/v2.2.31
