### ISSUE TITLE
GNS3 PPA for 22.04 LTS

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#3305]
I know Ubuntu 22.04 is not official yet, but many repos already are in 22.04.

**Comment by grossmj** [comment]
I pushed packages for 22.04: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy

However, the server needs testing since I had to change the aiohttp dependency version in order to build for 22.04
