### ISSUE TITLE
"Apply" button in the "Preferences" dialog stays gray when templates/nodes are opened by double-click

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3307]
**Describe the bug**
"Apply" button in the "Preferences" dialog stays gray when templates/nodes are opened by double-click instead of pressing "Edit" button. I believe there are some problems with #3239 implementation.

**GNS3 version and operating system:**
 - OS: Arch Linux (`uname -sr`: Linux 5.16.14-zen1-1-zen)
 - GNS3 version: 2.2.31
 - no use of the GNS3 VM or remote server

**To Reproduce**
1. Go to "Edit" - "Preferences".
2. Go to any nodes/templates section (for example, "Qemu VMs").
3. Double-click on any template.
4. Change something and press "OK" button in the "template configuration" dialog.
5. See that "Apply" button of the "Preferences" dialog is gray (at this moment you can press "OK" button, but your changes will not be saved).
6. Press "Edit" button. Don't change anything.
7. Close "template configuration" dialog (doesn't matter with "OK" or "Cancel").
8. See that "Apply" button is now unlocked. And only now you can save your changes with "OK" or "Apply" button of the "Preferences" dialog.

**Comment by grossmj** [comment]
Fixed, thanks 👍
