### ISSUE TITLE
création des VMs après le démarrage

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#331]
re

Ne pourrait on pas créer les VirtualBox clonés après la demande de démarrage de ces VMs, et non pas quand on les "pose" sur le lab ?

Cela permettrait de partager des labs contenant des VMs, sans que le destinataire du lab ait besoin d'avoir le vdi de cette VM. Une popup lui demanderai de choisir sa VM à utiliser à la place (comme pour les iOS, il me semble).

Par contre, cela demande plus de modifications sur GNS3, il me semble....

**Comment by noplay** [comment]
Il me semble que cette façon de faire est nécessaire pour la créations des liens réseaux.

**Comment by Raizo62** [comment]
Les liens réseaux ne pourraient pas être crées au démarrage de la VM ?
