### ISSUE TITLE
nat doublelcick exeception 

### ISSUE THREAD

**Issue by hInfern0** [GNS3/gns3-gui#3312]
****** Exception detected, traceback information saved in C:\Users\0xInferno\AppData\Roaming\GNS3\2.2\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "gns3-gui\gns3\graphics_view.py", line 666, in mouseDoubleClickEvent
  File "gns3-gui\gns3\node.py", line 740, in bringToFront
  File "gns3-gui\gns3\node.py", line 655, in consoleCommand
AttributeError: 'NoneType' object has no attribute 'startswith'

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38506/store/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38506/store/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))': /api/38506/store/
[exceptions.log](https://github.com/GNS3/gns3-gui/files/8396847/exceptions.log)

**Comment by grossmj** [comment]
Should be fixed. Thanks 👍
