### ISSUE TITLE
Wireshark in GNS3 Issue

### ISSUE THREAD

**Issue by LilSpikeFish** [GNS3/gns3-gui#3314]
_**Describe the bug**_

We're encountering an issue when running more than 6 instances of wireshark in our lab causes a recurring window to appear saying "waiting for http://IP ADDRESS OF SERVER:3080".  This window will continue to appear until the wireshark instances are closed and then GNS3 operates normally again or until the operation timesout.  Network traffic continues to flow and the existing wireshark instances continue to update, but the lab is essentially inoperable due to the window popping up constantly to the point where it can be difficult to close the existing wireshark instances without waiting for a timeout.  On timeout error message below received:

Timeout after 120 seconds for request http://IP ADDRESS OF SERVER:3080/v2/projects/2c8a4ef0-83d1-4ac4-9b42-dab709703fdd/links/c0663ad4-dd64-4c08-bf98-81ee2aa7018f/start_capture. Please check the connection is not blocked by a firewall or an anti-virus.
Error while starting capture on link c0663ad4-dd64-4c08-bf98-81ee2aa7018f: Operation timeout

**_Screenshot of lab setup below:_**
<img width="1068" alt="GNS3 Bug Report for Wireshark Issue Screenshot" src="https://user-images.githubusercontent.com/103065027/161821457-d9d3402b-c7bb-4262-b990-c9a904e8d046.png">

_**GNS3 version and operating system (please complete the following information):**_

GNS3 Host Server Version: 2.2.31
Host Server OS: Ubuntu 20.04.4 LTS
GNS3 Client Version: 2.2.31
Client Machine OS: Windows 10 Home - Version 21H1
WireShark Version: 3.6.3

_**To Reproduce
Steps to reproduce the behavior:**_

1. Create a new project
2. Put any number or type of hosts (example used is six Windows 10 Hosts and two GNS3 switches)
3. Start packet capture on a link, checking "start the capture visualization program" box.
4. Repeat on five other links in the lab
5. Start the seventh packet capture.
6. "Waiting for" window begins to occur.

**Comment by grossmj** [comment]
This look similar to https://github.com/GNS3/gns3-gui/issues/3229 

We have fixed the problem, it should work after we release version 3.0

**Comment by cristian-ciobanu** [comment]
> This look similar to #3229
> 
> We have fixed the problem, it should work after we release version 3.0

What's the timeline for the 3.0 release or the 3.0 beta/RC releases ?

**Comment by grossmj** [comment]
> What's the timeline for the 3.0 release or the 3.0 beta/RC releases ?

Unfortunately, we have accumulated lot of delay but I am hoping we can have our first alpha out by the end of the month.

**Comment by LilSpikeFish** [comment]
> > What's the timeline for the 3.0 release or the 3.0 beta/RC releases ?
> 
> Unfortunately, we have accumulated lot of delay but I am hoping we can have our first alpha out by the end of the month.

Looking forward to the release and helping to test it out!
