### ISSUE TITLE
Need Help in installation of GNS3 MAC

### ISSUE THREAD

**Issue by Shasank10** [GNS3/gns3-gui#3316]
Hi , 

I am new to GNS3 tried to install GNS3 on MAC getting below error

=> Could not use socket 127.0.0.1:80 [Errno 13] Permission denied
The server port 80 is already in use, fallback to port 53719
Local server process has stopped

GNS3 2.2.31
MAC 12.3.1

**Comment by jnatschev** [comment]
Potentially the message is reporting that the host computer already has a service (web server?) that is already using port 80.
May be worth changing the GNS3 configuration for the GNS server from 80 to 3080.

For example, the contents of your GNS3 gns3_server.conf file could look like the following:
[Server]
path = /Applications/GNS3.app/Contents/MacOS/gns3server
ubridge_path = /Applications/GNS3.app/Contents/MacOS/ubridge
host = localhost
#port = 80
port = 3080
images_path = /somepath/GNS3/images
projects_path = /somepath/GNS3/projects
appliances_path = /somepath/GNS3/appliances
additional_images_paths =
symbols_path = /somepath/GNS3/symbols
configs_path = /somepath/GNS3/configs
report_errors = True
auto_start = False
allow_console_from_anywhere = False
auth = True
user = admin
password = WlhQWs699HOR1fyIzmEhqX0QVX2TNX0pqdpT5b9cpEfg8eVzQjB0tYjAyKF0jCat
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10001
udp_end_port_range = 20000




Cheers,
John
