### ISSUE TITLE
Cannot use a remote server with https

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#3319]
**Describe the bug**
A simple remote gns3 server fails to be contacted by gns3-gui using https.
No such issue with http.
No venv is used for neither the gui nor the server.

**GNS3 version and operating system (please complete the following information):**
 - Ubuntu 21.10
 - GNS3 version 2.2.31 (from pip3)
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.): no

**To Reproduce**
0. on the remote: set https in gns3_server.conf as "protocol"
1. on the remote: /usr/local/bin/gns3server --log /var/log/gns3/gns3.log --daemon
2. launch gns3 locally
3. Edit Preferences -> Server -> Remote Servers -> Add -> https - 192.168.1.214 - 3080
4. Edit Preferences -> Server -> Remote Servers -> Add -> enable authentication - User: <remote_gns3_user>
5. Edit Preferences -> Server -> Remote Servers -> Add -> enable authentication - Password: <remote_gns3_password>
6. Edit Preferences -> Server -> Remote Servers -> Add -> enable authentication -> OK

Locally
```
nmap -p 3080 192.168.1.214
Starting Nmap 7.80 ( https://nmap.org ) at 2022-04-19 15:29 CEST
Nmap scan report for remote-server (192.168.1.214)
Host is up (0.0029s latency).

PORT     STATE SERVICE
3080/tcp open  stm_pproc
```
Remotely:
```
netstat -tunpevaW | grep 3080
tcp        0      0 192.168.1.214:3080      0.0.0.0:*               LISTEN      0          2209851    316303/python3.9    
tcp        0      0 192.168.1.214:56202     192.168.1.214:3080      ESTABLISHED 0          2209855    316303/python3.9    
tcp        0      0 192.168.1.214:3080      192.168.1.214:56202     ESTABLISHED 0          2209856    316303/python3.9    
```
Yet, the remote server icon on the right remains grey (instead of green) and it is not possible to define a new Qemu VM on that remote server.

When using http, the icon remains also grey but it is possible to define new VMs on the remote server. Their icon appear as green below the server grey icon (when started).

**Comment by jean-christophe-manciot** [comment]
After restarting gns3 gui, I can see now that the http server icon has turned green.

**Comment by grossmj** [comment]
You must have a SSL certificate and configure the server to use it.

For instance, use this command to generate a self signed cert (replace localhost by your domain name): 

```
$ openssl req -nodes -new -x509 -keyout server.key -out server.cert -subj '/CN=localhost'
```

Then you can start the server like this:

```
$ python3 -m gns3server --local --certfile server.cert --certkey server.key --ssl
```

or add the following to `gns3_server.conf ` (after changing the paths).

```
ssl = True
certfile=/home/gns3/.config/GNS3/ssl/server.cert
certkey=/home/gns3/.config/GNS3/ssl/server.key
```

Then you should be able to connect with the client in HTTPS:

![Screenshot from 2022-12-29 07-53-33](https://user-images.githubusercontent.com/4752614/209886421-85649073-1d6e-47ff-8418-85213d15016b.png)

**Comment by grossmj** [comment]
@jean-christophe-manciot please open a new issue or comment back here if you still cannot run SSL. Thanks 👍
