### ISSUE TITLE
NAT/Cloud node SSL Error: certificate has expired

### ISSUE THREAD

**Issue by Pydzik** [GNS3/gns3-gui#3321]
Hey!

I found a problem when trying to connect a topology to the Internet via a NAT node.
I am encountering an error when connecting the NAT function and clicking on the cloud: 

> Retry(Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection is broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')' /api/38506/store/.

Additionally, in the exception file: 

> Traceback (last, most recent call):
>   File "gns3-gui\graphics_view.py", line 666, in mouseDoubleClickEvent
>   File "gns3-gui\node.py", line 740, in bringToFront
>   File "gns3-guinode.py", line 655, in consoleCommand
> AttributeError: object "NoneType" does not have attribute "beginswith

Funnily enough, on the same version on a project from a few weeks ago, NAT worked fine and physically allowed internet access for devices in the topology.

I tried:
- Installing NPCAP 
- Disabling the firewall
- Running in administrator mode
- Restarting NIC

With the "Cloud" option there are no errors, no less the connected devices cannot access the internet. 

- OS: Windows 10
- GNS3 version 2.2.29
- I am using a remote server, however this should not cause the problem as the problem also occurs on fully local topologies.

I would appreciate any help!
Best regard

![nat_ssl_error](https://user-images.githubusercontent.com/74244783/165298437-ccbad358-ded0-4d8f-ab9c-bddc4ed051b3.PNG)
s

**Comment by grossmj** [comment]
Thanks, the issue has been fixed in https://github.com/GNS3/gns3-gui/issues/3312 and shouldn't happen again in the next version to be released soon.
