### ISSUE TITLE
Include virt-viewer 11 in default install

### ISSUE THREAD

**Issue by lurendrejer** [GNS3/gns3-gui#3334]
Using spice is essential when using special language characters in qemu consoles.

My students has to actively select the virt-viewer installation, under the tools section during install (they often fail to do so)

And, the included virt-viewer (old 7.0) sometimes failes with a missing windl.dll -file, the latest 11.0 works just fine, but requires manual editing of the GNS3-gui spice-settings.

**Comment by grossmj** [comment]
@lurendrejer I will update virt-viewer.

Do we need to change the spice settings as well?

**Comment by lurendrejer** [comment]
No change needed to spice-settings - everything seems dandy :)

**Comment by grossmj** [comment]
The GUI is 64-bit. I have updated the path with the correct spice-version. Thanks 👍
