### ISSUE TITLE
"Check for Update" believes that version 2.2.32 is newer than 2.2.32.1 

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3339]
**Describe the bug**
`gns3-gui` and `gns3-server` are **2.2.32.1**, but "Check for Update" is asking if I want to upgrade to **2.2.32.**
Maybe there is something wrong with #3324 implementation.

**GNS3 version and operating system:**
 - OS: Arch Linux (`uname -sr`: Linux 5.17.9-zen1-1-zen)
 - Python: 3.10.4; GNS3 is installed in Python virtual environment
 - GNS3 version: 2.2.32.1
 - no use of the GNS3 VM or remote server

**To Reproduce**
1. Go to 'Help' - 'About.
2. See **'2.2.32.1'.**
3. Go to 'Help' - 'Check for Update'
4. See the message "Newer GNS3 version **2.2.32** is available, do you want to visit our website to download it?"

**Comment by grossmj** [comment]
Thanks, unfortunately it is too late to fix this however it will be solved when we release v2.2.33
