### ISSUE TITLE
ZipImportError: bad local file header in /Applications/GNS3.app/Contents/Resources/lib/python34.zip

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#335]
https://app.getsentry.com/gns3/gns3-gui/group/64947707/

```
ZipImportError: bad local file header in /Applications/GNS3.app/Contents/Resources/lib/python34.zip
  File "gns3/main_window.pyo", line 1026, in _preferencesActionSlot
  File "gns3/dialogs/preferences_dialog.pyo", line 50, in __init__
  File "gns3/dialogs/preferences_dialog.pyo", line 82, in _loadPreferencePages
  File "gns3/modules/vpcs/__init__.pyo", line 366, in preferencePages
```

**Comment by grossmj** [comment]
That's weird, must be a corrupted App?!

**Comment by noplay** [comment]
Yeah If we need to start dealing with falling hard drive....

On Wed, May 6, 2015 at 5:02 AM, Jeremy Grossmann <notifications@github.com>
wrote:

> That's weird, must be a corrupted App?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/335#issuecomment-99302136>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
