### ISSUE TITLE
Magnifier (capturing symbol) is not shown on the link when distance between node centers is less than 150 pixels

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3356]
**Describe the bug**
There is no magnifier (capturing symbol) when distance between node centers is 125 pixels or less. So there is no visual indication of links with captures for dense node placement. Frankly, I'm not sure if it should be fixed. Anyway it would be nice to have clear explanation if it's a feature or a bug. ;)

**GNS3 version and operating system:**
 - OS: Arch Linux (`uname -sr`: Linux 5.15.55-1-lts)
 - Python: 3.10.5; GNS3 is installed in Python virtual environment
 - GNS3 version: 2.2.33.1
 - no use of the GNS3 VM or remote server

**Screenshots**
- Node and drawing grid sizes are 25 pixels (both are the same).

![image](https://user-images.githubusercontent.com/15959858/180576505-d1673335-a0c7-4cf6-9571-cda5354575a0.png)
150 pixels (6 squares) between node centers

![image](https://user-images.githubusercontent.com/15959858/180576592-8338439b-921c-40a5-b01c-35085ed662f0.png)
125 pixels (5 squares) between node centers

**Comment by grossmj** [comment]
This is on purpose to keep things pretty ;)
