### ISSUE TITLE
Wireshark Host requires authentication (localhost:3080) 

### ISSUE THREAD

**Issue by cischology** [GNS3/gns3-gui#3357]
When I try to start a capture on any link, I am greeted with this error :Host requires authentication (localhost:3080).
even when I start GNS3 as administrator, I am still receiving this error. please advise.

 - OS: [Windows (64-bit) with Python 3.7.5 Qt 5.15.2 and PyQt 5.15.6.]
 - GNS3 version [GNS3 version 2.2.33.1]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
Start capture

![image](https://user-images.githubusercontent.com/56488147/180643323-6f45b936-6b7a-4dda-8dd0-ee21aa6b2aeb.png)

**Comment by eantowne** [comment]
Most likely this is due to Wireshark permissions issues. Take a look at this [LINK](https://wiki.wireshark.org/CaptureSetup/CapturePrivileges#windows) as it provides guidance on handling permissions for Wireshark.

**Comment by cischology** [comment]
Thank you however, that is not the case for me. Wireshark stand alone works fine without any elevated permissions. yet when I try to capture within GNS3, that is when I am receiving the error. I tried to start GNS3 and Wireshark as administrator and still getting the same thing.. :(

**Comment by cischology** [comment]
update. I had to disable security from GNS3 VM and it is now working.

**Comment by spikefishjohn** [comment]
Which version is this? I seem to recall this coming up a as a bug before.

**Comment by grossmj** [comment]
![Screenshot from 2022-07-26 23-23-42](https://user-images.githubusercontent.com/4752614/181114747-190088fe-97fc-4c12-9393-752ed349e341.png)

Hum, do you have the "protect server with password" option ticked in the server preferences? If yes, can you try without it?

**Comment by grossmj** [comment]
@cischology have you tried to disable the password as shown above?

**Comment by cischology** [comment]
sorry for the late reply, no, as I mentioned above I had to disable security from GNS3 VM and it is now working.

**Comment by grossmj** [comment]
Unfortunately, I cannot reproduce the issue.

**Comment by CatharsisCoding** [comment]
the quick fix https://www.youtube.com/watch?v=i35ENphrP6k
