### ISSUE TITLE
Crash when changing colour in style or editing text colour

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3361]
Community link: https://gns3.com/community/support/crash-when-changing-colour-in-style-or-editing-text-colour

Quick research brought up references to using Gtk.init() to solve this error, but not sure of the full context.

Will see if I can recreate in Ubuntu 22.04 in a few hours.

**Comment by eantowne** [comment]
GNS3 2.2.33.1
OS: Manjaro
GNOME version: 42.3
Windowing system: Wayland

Looks to me like an issue with QT trying to get initial GTK information. May be due to GTK4 in GNOME 42.x?

ERROR LOG (So you do not have to read through community post):

2022-08-01 15:10:41 INFO root:126 Log level: INFO
2022-08-01 15:10:41 INFO main:259 GNS3 GUI version 2.2.33.1
2022-08-01 15:10:41 INFO main:260 Copyright (c) 2007-2022 GNS3 Technologies Inc.
2022-08-01 15:10:41 INFO main:261 Application started with /usr/bin/gns3



(process:37962): Gtk-CRITICAL **: 15:10:58.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:37962): Gtk-CRITICAL **: 15:10:58.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(process:37962): Gtk-CRITICAL **: 15:10:58.092: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Fatal Python error: Segmentation fault

Current thread 0x00007f42b77f7740 (most recent call first):
File "/usr/lib/python3.10/site-packages/gns3/dialogs/text_editor_dialog.py", line 90 in _setColorSlot
File "/usr/lib/python3.10/site-packages/gns3/qt/__init__.py", line 275 in func_wrapper
File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1454 in textEditActionSlot
File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 757 in _showDeviceContextualMenu
File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 538 in contextMenuEvent
File "/usr/lib/python3.10/site-packages/gns3/main.py", line 296 in main
File "/usr/bin/gns3", line 33 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtNetwork, PyQt5.QtWidgets, gns3.qt.QtCore, gns3.qt.QtGui, gns3.qt.QtNetwork, gns3.qt.QtWidgets, PyQt5.QtSvg, gns3.qt.QtSvg, PyQt5.QtWebSockets, gns3.qt.QtWebSockets, psutil._psutil_linux, psutil._psutil_posix, pvectorc (total: 15)
zsh: segmentation fault (core dumped) gns3

**Comment by grossmj** [comment]
I can't reproduce this issue. I suspect a Qt bug, have you tried with version 5.15.7?

> Will see if I can recreate in Ubuntu 22.04 in a few hours.

Have you managed to recreate it on Ubuntu 22.04?

**Comment by grossmj** [comment]
@eantowne do you have any update about this? thanks :)

**Comment by eantowne** [comment]
@grossmj I have not been able to recreate this in my current install. I need to test against a few other distros still.

Sorry for the delay.

**Comment by grossmj** [comment]
I doubt this is a GNS3 issue. I think more like a Qt bug. Anyway have you had a chance to test other distros? Thanks :)

**Comment by eantowne** [comment]
I would guess that you are most likely correct. Honestly, the fact that the community post references Manjaro as the host OS, does not give me much hope of recreating the issue as 4 months of updates in Arch land is an eternity.

I am closing this post as the original community post OP has not provided additional commentary, nor have I been able to recreate the issue. (my fault, I should have immediately spun up Manjaro.
