### ISSUE TITLE
Error while deleting link, Link ID doesn't exist.

### ISSUE THREAD

**Issue by kefins** [GNS3/gns3-gui#3363]
Hi, I found the bug still exist in GNS 2.2.31.
<img width="986" alt="2" src="https://user-images.githubusercontent.com/41069536/182757548-e83fa1df-1721-4aad-b739-27180ffd4168.png">

**Comment by kefins** [comment]
I don't how to reproduce it stably, sometimes it occurs between a cloud node and a qemu vm node, sometimes it occurs between two qemu vm nodes.

**Comment by grossmj** [comment]
I remember I have seen this issue a few times, I think it comes from the way/how fast links are created. Not sure this is worth the effort to fix this issue since we plan to completely change the network back-end in order to use Linux bridges.

**Comment by kefins** [comment]
> I remember I have seen this issue a few times, I think it comes from the way/how fast links are created. Not sure this is worth the effort to fix this issue since we plan to completely change the network back-end in order to use Linux bridges.

Yes，I also found the issue many times in the old release, but it seems that it wasn't resolvd thoroughly. If it was cause by the speed of operation, I will try to operate slowly to avoid it.

**Comment by defxsec** [comment]
Tengo el mismo problema 
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/9b1a6f32-6511-45b2-8f31-732c028b40cb)
Error while deleting link: Link ID 2f0f1ba2-c758-4b79-8d19-92baab1eafb9 doesn't exist, y no lo puedo quitar

**Comment by kefins** [comment]
You can try to close the GNS3 application and then reopen it, maybe you will find that the link has beed deleted.

**Comment by defxsec** [comment]
kefins, gracias por responder, si se puede hacer eso sin embargo creo que no es la mejor manera de solucionar, por que al cerrar y volver a abrir en algunas ocasiones lo deja normal en otras los quita y entras te indica que ese enlace sigue existiendo, lo que no ocurre cuando cargamos la maquina virtual WINDOWS11 de virtualbox solo ocurre el error con la maquina virtual WINDOWS 11 de vmware , como digo el problema esta entre GNS3 y VMWARE con la VM de windows 11.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/ff048363-48c3-4c48-8cd9-f87dd5c2932b)

**Comment by defxsec** [comment]
Buenas, eh estado haciendo pruebas ahora con la versión GNS3 y GNS3 VM 2.2.42, de igual forma me ocurría el mismo problema entre GNS3 y la maquina virtual Windows 11 de VMWare 17 pro, y como dije al parecer existía un problema entre GNS3 y VMWare, por lo que decidí instalar nuevamente la VM de Windows 11 pero esta vez con algunos parámetros modificados en.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/c0c9c342-7107-4fe2-aae8-d23355cca5a9)
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/c0a8e9bf-e604-4759-9ff2-3d6d914dfb04)
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/ddfadd90-bd0a-4c5c-932d-ad573d94594d)

Aquí cambie la versión de Windows 11 x64 por la Windows 10 x64 dejando las demás configuraciones por defecto y proceder a la instalación de Windows 11, tener en cuenta que cuando se instala Windows 11 mediante esta configuración salta un error en el proceso de instalación, del TPM que puede ser saltado con una modificación en le regedit.exe en el proceso de instalación.   
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/86e8f57f-19a0-4457-b21d-c9ca7cf7d8ba)

Luego procedemos a incluir la Máquina Virtual en GNS3. 
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/31cb366f-6f76-45a6-9428-4c81b99aa01c)
Y todo corre normal sin ningún problema por el momento.

De dicha experiencia pude deducir que cuando se instala el Windows 11 en VMware 17 pro de la forma tradicional, existe el problema entre la comunicación de GNS3 y la VM Windows 11, por lo que deduje que el problema esta en el TPM de Windows que de alguna forma no deja arrancar desde GNS3 a la maquina Windows 11. 
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/f6604d46-f9dd-4155-8aed-1bbcef1e2b93)
En esta parte no se puede quitar esta opción como parte de la instalación, pienso que este es el problema que genera el error.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/e3648beb-0566-448c-b392-9b5f40cf13bc)

Y para solucionar ese problema como una segunda soluciona y con la que me quede contento fue de la siguiente forma, una vez que se termine la instalación del Windows 11 en VMware. 

Debemos quitar algunos parámetros en VMware de la máquina Windows 11 como el Trusted Plaform Module, mediante Edit virtual machine settings y Remove el Trusted Plaform Module.
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/07681b67-9502-4323-b35b-77656cb92783)
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/3aaef530-0f27-4759-b5e1-ab916c5e31b0)

Luego en dicha ventana en Opciones> Access Control 
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/20594e31-8faf-47b6-91e7-3678ff4d098b)

Remover la encriptación, tener en cuenta que al principio no aparece la opción de remover, cuando eso ocurra cambiar la contraseña y luego aparece remover.
Con todo eso se soluciona los problemas y corre normal el GNS3.
