### ISSUE TITLE
Unable to set VNC console resolution in GNS3 3.0.0 alpha 1

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3365]
**Describe the bug**
VNC console resolution cannot be set for Docker containers (dropdown list not available).

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. Right click on a Docker container from the All devices pane and select **Configure template**
2. On the Docker container **General settings** tab go to **Console type** option and from the dropdown list select **vnc**
3. Below for VNC console resolution option there is no dropdown to allow selection of a different video resolution.
4. The container start with the default VNC console resolution of 1024 x 768.
5. The VNC console resolution option is present also if the console type is set to other values (telnet, http, none). I assume this should be visible only when vnc is used as a console type and hidden for the rest.

**Screenshots or videos**

![docker _vnc](https://user-images.githubusercontent.com/7124193/182935401-8928d118-1d14-48d8-813c-784d1ab352c6.png)

**Additional context**
None

**Comment by grossmj** [comment]
Fixed
