### ISSUE TITLE
GNS3 GUI does not detect images by default when trying to upload them in the Image Manager GNS3 3.0.0 Alpha 1

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3367]
**Describe the bug**
GNS3 GUI does not detect images by default when trying to upload them in the Image Manager

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. In GNS3 GUI go to File --> Image Management.
2. On the Images dialog box click on Upload button and navigate to a folder where images are stored.
3. By default no images are listed when the filter is set to Images even they are present in the folder.
4. Change the filter to All Files and images are being shown.
5. Checked the same steps in Web-UI and the default filter is set to Custom Files which works properly and lists correctly only the images from the directory.

**Screenshots or videos**
![image_manager_002](https://user-images.githubusercontent.com/7124193/183101298-9a92effe-6573-4cf1-89a0-f7d7d7d78bfb.png)
![image_manager_003](https://user-images.githubusercontent.com/7124193/183101302-4059d215-53b5-41ba-b1fb-9e4207b2883e.png)

**Additional context**
None

**Comment by grossmj** [comment]
Fixed
