### ISSUE TITLE
open project with .iourc not present

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#337]
Tested on Debian Jessie with gns3-1.3.3-dev2

If you try to open a project with IOU devices and .iourc file path is not configured on the system, GNS3-gui will become unresponsive.

**Comment by noplay** [comment]
Can not reproduce it on MacOS I let @grossmj test it.

**Comment by grossmj** [comment]
I can confirm the issue.

@noplay the missing .iourc file is just what triggers the problem.

Apparently when a project is loading and an exception happens (in this case this is https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/iou/__init__.py#L226) we end up in an inconsistent state. The GUI is still responsive but I cannot close it.

**Comment by grossmj** [comment]
@noplay were you able to reproduce the issue?

**Comment by noplay** [comment]
I didn't reproduce it...

**Comment by grossmj** [comment]
Fixed the original problem but there may be a deeper issue.
