### ISSUE TITLE
Editing Docker container config generates exception and empty config

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3371]
**Describe the bug**
Editing Docker container config generates exception and empty config

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. In GNS3 GUI drag a Docker container on the workspace
2. Right click on the container and from the dropdown menu select **Edit Config**
3. An empty dialog box is opened and an exception is generated as shown below

**Screenshots or videos**

![docker _config](https://user-images.githubusercontent.com/7124193/183861924-e07bc3e6-b699-4f3b-b3d4-0fcf25912417.png)

**Additional context**

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/qt/__init__.py", line 227, in partial
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gns3/http_client.py", line 751, in _processAsyncReply
    callback(content, context=context)
  File "/usr/lib/python3.10/site-packages/gns3/qt/__init__.py", line 227, in partial
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/file_editor_dialog.py", line 69, in _getCallback
    self.uiFileTextEdit.setText(result.decode("utf-8", errors="ignore"))
AttributeError: 'str' object has no attribute 'decode'

Crash report sent with event ID: 5646d8993456449faf87f8613eff1079
https://o19455.ingest.sentry.io:443 "POST /api/38506/store/ HTTP/1.1" 200 41

**Comment by grossmj** [comment]
Fixed, thanks 🙏
