### ISSUE TITLE
Npcap wants to install an old deprecated version....  Why?

### ISSUE THREAD

**Issue by SirTwsted** [GNS3/gns3-gui#3372]
On version 2.2.33.1  and even prior versions of GNS
for some odd reason Npcap continues to ask if a person wants to replace the new Npcap with an old version v0.9990
Currently the system has v1.55 installed.

Why would it even ask me that?  why not just use the newest version?

Can you guys fix this issue and also check all the little nuances in the installer to make sure this doesn't happen,
or installation of old versions of additions does not get installed. To prevent applications from break by using outdated software's.
maybe half the problems would be solved if only newest versions are installed.

just kindly curiously asking :)

.
![WHY](https://user-images.githubusercontent.com/15247713/183902468-f8562be1-db8b-4386-b082-82151ed4428b.jpg)

**Comment by josephmhiggins** [comment]
Not a Bug.

Some people like you always want to install the latest software version.
Some people like me only want to use what versions of software that the gns3 developers have staged as the default settings/versions.

It's tricky.

**Comment by arash88** [comment]
+1 It would be awesome to have the latest npcap and HAXM come with the installer
