### ISSUE TITLE
CPU maxes out on GNS3 2.2.24 with QEMU and IOSvL2 trunked nodes

### ISSUE THREAD

**Issue by arash88** [GNS3/gns3-gui#3377]
**Describe the bug**
Using GNS3 2.2.24 and IOSvL2 on locally QEMU makes the CPU goes CRAZY!
GNS3 2.2.24 makes the CPU go and stay 100% when using even two IOSvL2 nodes trunking to each other (The latest official images)!

**To Reproduce**
As soon as I connect the switch node's trunk interfaces together, the CPU maxes out and does not come down even if I remove the link.
Inside the Task Manager, I can see all the QEMU instance's CPU initializations are at 100% but uBridge's CPU initialization's normal.

Tested with either HAXM acceleration on or off.
Tested with WinPcap/npcap 0.99/npcap 1.70/win10pcap with no luck.

The settings of the IOSvL2 QEMU Nodes are exactly what GNS3 appliance for IOSvL2 suggested.
GNS3 2.1.21 is totally Fine without any problem!

I believe this problem is related to #2915
Maybe an unfixed QEMU 3.x bug? would be nice to see the latest QEMU in ver 3.x GUI along with asyncio

**GNS3 version and operating system (please complete the following information):**
- OS:  Win10 21H2
- GNS3 version 2.2.x
- Locally and Without GNS3 VM or remote server (ESXi, bare metal, etc.)

**Comment by grossmj** [comment]
> Maybe an unfixed QEMU 3.x bug? would be nice to see the latest QEMU in ver 3.x GUI along with asyncio

Do you mean update the Qemu version distributed with the GUI?

Have you tried wih the GNS3 VM which has Qemu 4.2.1? You could even upgrade to a even more recent version of Qemu: https://github.com/GNS3/gns3-server/issues/2037#issuecomment-1148907761

**Comment by arash88** [comment]
Yes I meant GUI with a newer QEMU version.
GNS3 VM is fine.
Thanks for the efforts though.

**Comment by grossmj** [comment]
No worries, I don't recommend running Qemu on Windows anyway. Also, the GNS3 server will not be supported on Windows starting with version 3.0, you will only be able to use the GUI to connect to the GNS3 VM or any remote GNS3 server.
