### ISSUE TITLE
PPA installation does not install gns3server executable binary file (2.2.34)

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3378]
**Describe the bug**
Binary file for gns3server not installed when installed via PPA. This occurs with installing gns3-gui or gns3-server packages.

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux (Ubuntu 22.04 LTS / Pop-OS 22.04)
 - GNS3 version [2.2.34]
 - Bare Metal install

**To Reproduce**

1. `sudo apt install gns3-server` (also occurs with gns3-gui)
2. `which gns3server`
3. No result returned
4. Link is created, but target does not exist

```
ls -al /usr/bin/gns3server
lrwxrwxrwx 1 root root 40 Aug 28 21:32 /usr/bin/gns3server -> ../share/gns3/gns3-server/bin/gns3server
```
`gns3` directory structure under `/usr/share` does not exist

**Comment by grossmj** [comment]
Damn, I guess v2.2.33.1 was fine right?

**Comment by eantowne** [comment]
Yes, 2.2.33.1 installed and worked as expected. If I get a little bit of time, I will pull apart the .deb and see if I can figure out what is going on.

**Comment by grossmj** [comment]
@eantowne thanks, I think I found the problem. I have published updated packages, please let me know if you see a problem.

**Comment by eantowne** [comment]
Seems to be installing and starting correctly again, thank you!

Out of curiosity, what was the issue?

**Comment by grossmj** [comment]
Not too sure what was the problem and why it happened this time, it was fine during the previous release...

I changed the libvirt dependency in the control file from `libvirt-bin | libvirt-daemon-system` to `libvirt-daemon-system`, seems that the `|` was breaking something during the build with dh-virtualenv

I also bumped the compat level from 9 to 10 in the compat file, not sure if it helped. See the "Compatibility levels before 10 are deprecated (level 9 in use)" messages in https://launchpadlibrarian.net/620799608/buildlog_ubuntu-jammy-amd64.gns3-server_2.2.34~jammy2_BUILDING.txt.gz
