### ISSUE TITLE
Could not find all required packages(python-sip) when try install from AUR

### ISSUE THREAD

**Issue by anas-elgarhy** [GNS3/gns3-gui#3385]
When I try to install it from AUR, I get this error:
```
-> Could not find all required packages:
	python-sip (Wanted by: gns3-gui-git)
```
I get the same error when try install `gns3-gui` and `gns3-gui-git`

**Comment by eantowne** [comment]
The AUR package is not a package maintained by the GNS3 developers. Please contact the package maintainer as listed in the AUR.

Examining https://aur.archlinux.org/packages/gns3-gui <https://aur.archlinux.org/packages/gns3-gui>, we see that “buzo” is the maintainer.
