### ISSUE TITLE
Problem with open VPCS on GNS3 | Fedora 36

### ISSUE THREAD

**Issue by PietrekKogucik** [GNS3/gns3-gui#3386]
When i want to start VPCS i get error: "=> error while starting PC1: Could not start VPCS /usr/local/bin/vpcs: [Errno 111] Connect call failed ('127.0.0.1', 5001)

Could not start VPCS /usr/local/bin/vpcs: [Errno 111] Connect call failed ('127.0.0.1', 5001)
Could not start VPCS /usr/local/bin/vpcs: [Errno 111] Connect call failed ('127.0.0.1', 5009)
"

or
'Error while sending command 'bridge create VPCS-6260b24d-dea0-4065-86b4-faedf58ce68c': bridge 'VPCS-6260b24d-dea0-4065-86b4-faedf58ce68c' already exist: uBridge version 0.9.18 running with libpcap version 1.10.1 (with TPACKET_V3)
Hypervisor TCP control server started (IP localhost port 43051).
UDP tunnel connecting from local port 10001 to IPv4 address 127.0.0.1 on port 10000
UDP tunnel connecting from local port 10008 to IPv4 address 127.0.0.1 on port 10009
Source NIO listener thread for VPCS-6260b24d-dea0-4065-86b4-faedf58ce68c has started
Destination NIO listener thread for VPCS-6260b24d-dea0-4065-86b4-faedf58ce68c has started'

![G](https://user-images.githubusercontent.com/98275564/193005226-2a2164cb-b5cf-49a7-8f1f-e8e18405316c.png)

**Comment by lunhas2k4** [comment]
Hi @PKusnierz , did you manage to identify and solve the issue?

**Comment by saolof** [comment]
I have the same problem

**Comment by grossmj** [comment]
Could be a similar issue to https://github.com/GNS3/gns3-server/issues/1645

Do you have Nvidia GeForce Experience installed?

**Comment by kminooie** [comment]
I am getting the same error message. I am on fedora 37, and I don't have any Nvidia software installed.
