### ISSUE TITLE
Gns3 Web UI login issue 

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3388]
hi Jeremy/team,

i am trying to login to gns3 project through Web UI-beta its asking for login credential although i am giving it as gns3/gns3 and try with admin/gns3, admin/admin
its donot let me login through port 3080

please find the snapshot 
![image](https://user-images.githubusercontent.com/11521667/193573222-99419936-eee3-446c-9778-7b2d51679940.png)

its Gns3 Version 2.2.34
Gns3 VM (VMware workstation)
OS windows -11

while i am  running the version 2.3.34 but if you mark it correctly in left (down corner) it shows as 2.2.33 version in snapshot

regards

**Comment by cristian-ciobanu** [comment]
These credentials are configured from the GNS3 GUI preferences on the Server page. So what user/pass you have set there you need to use those to connect to the web-ui also.

**Comment by aksplease** [comment]
i have not change anything its default there gns3/gns3 and if i try to connect gns3 vm by winscp/securecrt fx i use the same gns3/gns3 credential and there is no issue ..

**Comment by cristian-ciobanu** [comment]
The web-UI credentials are not the same as the one you use for SecureCRT/WinSCP. You can see in cleartext these credentials in the GNS3 server configuration file. Check the documentation for more information about the the file and it's location https://docs.gns3.com/docs/using-gns3/administration/gns3-server-configuration-file

**Comment by aksplease** [comment]
hi Cristian
do you suspect some modification to any of the file system has been  done in my case due to whats ever reason unknowingly ?
if so can you suggest me to check whats the file credential or may have corruption to the file system has been done which i can rectify  .as i have already re-installed the gns3 application without removing the running set-up .still the issue is same .

regards
ashok

**Comment by josephmhiggins** [comment]
Aks,
You are confusing me.
1. You must, in every post, list your operating system, and your hypervisor name and version if you are running a hypervisor on your localhost, and nowadays, list whether you are using a main server
2. Do not crop off your pictures. Your GNS3 VM crops off the line that says: "To Launch the Web-UI...."
3. You browser show you are trying to https: into localhost

My response is:
1. I do not know why you are trying to login to localhost, and
2. I see no way to set a password for the localserver from the GNS3 GUI, but
3. If you make your GNS3 VM a Main Server, then the username/password fields will magically appear on the Server Tab in the gui.

Suffice it to say, I punched of checkboxes and magically I was able to login to:
http://127.0.0.1:3080/static/web-ui/server/1/projects

But I am not telling you what I did. I recommend that somehow Uncheck the Enable GNS3 VM, Enable The Local Server, close gns3, restart GNS3 and then go into Help - Setup Wizard.

You can run the GNS3 VM as a Main Server, but then that breaks all the VMware VMs you may have because VMware is "on another host" - even though it is on the same host.

You may have messed up your gns3 passwords if you switched back and forth between "No Main Server and use GNS3 VM on local host" and "Main Server is the GNS3 VM running on this host".

Confusing.
I think you did something out of order.

**Comment by aksplease** [comment]
hi My Hosting Machine is Windows-11 professional.installed Gns3 VM on VMWare Workstation-16.2 which is installed in same machine only.and the reported error coming when I am using web view to see my running project.
regards 
    On Wednesday, 5 October, 2022 at 02:54:51 am IST, josephhiggins ***@***.***> wrote:  
 
 


Aks,
You are confusing me.
   
   - You must, in every post, list your operating system, and your hypervisor name and version if you are running a hypervisor on your localhost, and nowadays, list whether you are using a main server
   - Do not crop off your pictures. Your GNS3 VM crops off the line that says: "To Launch the Web-UI...."
   - You browser show you are trying to https: into localhost

My response is:
   
   - I do not know why you are trying to login to localhost, and
   - I see no way to set a password for the localserver from the GNS3 GUI, but
   - If you make your GNS3 VM a Main Server, then the username/password fields will magically appear on the Server Tab in the gui.

Suffice it to say, I punched of checkboxes and magically I was able to login to:
http://127.0.0.1:3080/static/web-ui/server/1/projects

But I am not telling you what I did. I recommend that somehow Uncheck the Enable GNS3 VM, Enable The Local Server, close gns3, restart GNS3 and then go into Help - Setup Wizard.

You can run the GNS3 VM as a Main Server, but then that breaks all the VMware VMs you may have because VMware is "on another host" - even though it is on the same host.

You may have messed up your gns3 passwords if you switched back and forth between "No Main Server and use GNS3 VM on local host" and "Main Server is the GNS3 VM running on this host".

Confusing.
I think you did something out of order.

**Comment by aksplease** [comment]
yes i did as you said now its working 
thank u but don't know what's was the error     On Wednesday, 5 October, 2022 at 03:05:46 am IST, Ashok Sahoo ***@***.***> wrote:  
 
  hi My Hosting Machine is Windows-11 professional.installed Gns3 VM on VMWare Workstation-16.2 which is installed in same machine only.and the reported error coming when I am using web view to see my running project.
regards 
    On Wednesday, 5 October, 2022 at 02:54:51 am IST, josephhiggins ***@***.***> wrote:  
 
 


Aks,
You are confusing me.
   
   - You must, in every post, list your operating system, and your hypervisor name and version if you are running a hypervisor on your localhost, and nowadays, list whether you are using a main server
   - Do not crop off your pictures. Your GNS3 VM crops off the line that says: "To Launch the Web-UI...."
   - You browser show you are trying to https: into localhost

My response is:
   
   - I do not know why you are trying to login to localhost, and
   - I see no way to set a password for the localserver from the GNS3 GUI, but
   - If you make your GNS3 VM a Main Server, then the username/password fields will magically appear on the Server Tab in the gui.

Suffice it to say, I punched of checkboxes and magically I was able to login to:
http://127.0.0.1:3080/static/web-ui/server/1/projects

But I am not telling you what I did. I recommend that somehow Uncheck the Enable GNS3 VM, Enable The Local Server, close gns3, restart GNS3 and then go into Help - Setup Wizard.

You can run the GNS3 VM as a Main Server, but then that breaks all the VMware VMs you may have because VMware is "on another host" - even though it is on the same host.

You may have messed up your gns3 passwords if you switched back and forth between "No Main Server and use GNS3 VM on local host" and "Main Server is the GNS3 VM running on this host".

Confusing.
I think you did something out of order.

**Comment by aksplease** [comment]
![image](https://user-images.githubusercontent.com/11521667/193938443-c30775b3-b0e4-4e8a-96af-de2cde549973.png)

thank u

**Comment by aksplease** [comment]
hi 
again i facing same issue ,although i did the same thing as u said but its not working ..i think may be some bug there pls look whats really happening ..
![image](https://user-images.githubusercontent.com/11521667/194052186-edf476b9-4a5f-48d1-b05a-9ae7799a0ac7.png)

**Comment by josephmhiggins** [comment]
There is no rational reason to login to 127.0.0.1 for a Windows host running the GNS3 VM.
Everything *should* be on the GNS3 VM. Login to the GNS3 VM only please.
