### ISSUE TITLE
3.0 : bad message for config file of HDPI

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3389]
Hi

When GNS3 3.0 starts, it displays a message : 
`HDPI mode is enabled. HDPI support on Linux is not fully stable and GNS3 may crash depending of your version of Linux. To disabled HDPI mode please edit ~/.config/GNS3/gns3_gui.conf and set 'hdpi' to 'false'`

But the file `gns3_gui.conf` is not in `~/.config/GNS3/gns3_gui.conf`, but in `~/.config/GNS3/3.0/gns3_gui.conf` (with the path `3.0`)

**Comment by grossmj** [comment]
Fixed
