### ISSUE TITLE
3.0 : legacy symbol theme by default

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3391]
Hi

In GNS3 3.0, is there a way to use the legacy symbol theme for default template ?

Sorry, but, i think that the legacy (or classic ?) symbols are more intuitif than other (for example : VPCS)

**Comment by grossmj** [comment]
Hi,

Yes you can change this in the server config (`gns3_server.conf` or `gns3_server.ini`) under the Server section:

```
[Server]

; Default symbol theme
; Currently available themes are "Classic", Affinity-square-blue", "Affinity-square-red"
; "Affinity-square-gray", "Affinity-circle-blue", "Affinity-circle-red" and "Affinity-circle-gray"
default_symbol_theme = Classic
```

**Comment by Raizo62** [comment]
Hi

It is a long time, and i am back to GNS32 v2.2 (so i can't test). But i believe that i speaked of change the template with the gns3-gui.
