### ISSUE TITLE
"/v2/projects/load" and "/v2/projects/{project_id}/open" API endpoints don't really open a project in GUI

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3398]
Nothing happens in GUI when using "/v2/projects/load" and "/v2/projects/.../open" endpoints. From API's point of view projects are opened ("status": "opened" in "/v2/projects" response). Yes, several projects have status "opened" at the same time.

**GNS3 version and operating system:**
 - OS: Arch Linux (`uname -sr`: Linux 5.19.13-zen1-1-zen)
 - GNS3 version: 2.2.34
 - Python version: 3.10.7
 - no use of the GNS3 VM or remote server, GNS3 is installed in Python virtual environment with `pip`

**To Reproduce**
1. Start GNS3. Don't open any project (press 'Cancel') in project selection dialog. GUI should now says "Please create a project".
2. Use "/v2/projects" API call. See, that all projects have status "closed".
3. Use "/v2/projects/load" for one project. See, there is no changes in GUI (it still says "Please create a project"), but "/v2/projects" now says "status": "opened" for this very project and "closed" for others.
4. Use "/v2/projects/{project_id}/open" API call for another (second) project. Still nothing in GUI. And "/v2/projects" now says that BOTH projects are "opened":

GET http://localhost:3080/v2/projects

HTTP/1.1 200 OK
Connection: close
X-Route: /v2/projects
Server: Python/3.10 GNS3/2.2.34
Content-Type: application/json
Content-Length: 1243
Date: Sun, 16 Oct 2022 23:52:44 GMT

[
  {
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "drawing_grid_size": 25,
    "filename": "untitled.gns3",
    "grid_size": 25,
    "name": "untitled",
    "path": "/home/korshikov/GNS3/projects/untitled",
    "project_id": "c0dc36e9-00e3-40d0-a11b-7e2042a3f1ae",
    "scene_height": 1000,
    "scene_width": 2000,
    "show_grid": false,
    "show_interface_labels": false,
    "show_layers": true,
    "snap_to_grid": true,
    **"status": "opened",**
    "supplier": null,
    "variables": null,
    "zoom": 100
  },
  {
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "drawing_grid_size": 25,
    "filename": "lab.gns3",
    "grid_size": 25,
    "name": "lab",
    "path": "/home/korshikov/GNS3/projects/lab",
    "project_id": "cb0c57f0-5cfe-407f-b8cf-2a3b082209a6",
    "scene_height": 1000,
    "scene_width": 1600,
    "show_grid": false,
    "show_interface_labels": false,
    "show_layers": false,
    "snap_to_grid": true,
    **"status": "opened",**
    "supplier": null,
    "variables": null,
    "zoom": 84
  }
]

Response code: 200 (OK); Time: 15ms; Content length: 1243 bytes

**Comment by grossmj** [comment]
> Yes, several projects have status "opened" at the same time.

There can be multiple clients and users so it is expected several projects can be opened at the same time.

Also, are you expected these API calls would open a project in the GUI?

**Comment by andrei-korshikov** [comment]
> There can be multiple clients and users so it is expected several projects can be opened at the same time.
I didn't understand that. Thank you for clarification.

> Also, are you expected these API calls would open a project in the GUI?
Yes. And now I see I was wrong. GUI is just another client, and server API shouldn't manage it.
