### ISSUE TITLE
TPM (swtpm) option in QEMU vpms

### ISSUE THREAD

**Issue by lurendrejer** [GNS3/gns3-gui#3402]
Hi.
Windows 11 can be run with workarounds - but could a tpm (using swtpm) be added to the Qemu-templates?

Having the tpm-datafile in the project-folders would be much better than me comming up with some homemade hack :)

https://www.smoothnet.org/qemu-tpm/

**Comment by josephmhiggins** [comment]
Oh, cool. I thought the Windows 11 vm would not work solely because my Windows 10 machine is so old (bios not uefi). Although, even with the TPM, Windows 11 vm might not work on my old machine.

**Comment by grossmj** [comment]
@lurendrejer do you have some more information about that `tpm-datafile`? Thanks.

**Comment by lurendrejer** [comment]
A little: https://tpm2-software.github.io/2020/10/19/TPM2-Device-Emulation-With-QEMU.html
This should be more or less plug-n-play since GNS3 just starts Qemu with 'some commandline parameters'
/tmp/ usage seems odd to me - since encryption keys, etc would be lost when the host is restarted.
using /opt/gns3/projects/<uid>/whatever should do the trick.


Start the Guest with a TPM2.0 Device
Now start the guest with a virtualized TPM2.0 device. To do this, one needs to start the SWTPM simulator in tpm2 mode using the option --tpm2, like so:

mkdir /tmp/emulated_tpm
swtpm socket --tpmstate dir=/tmp/emulated_tpm --ctrl type=unixio,path=/tmp/emulated_tpm/swtpm-sock --log level=20 --tpm2
Then start the guest:

qemu-system-x86_64 -hda ~/qemu-images/ubuntu-20.04-amd64.img -boot d -m 2048 -enable-kvm \
  -chardev socket,id=chrtpm,path=/tmp/emulated_tpm/swtpm-sock \
  -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0
Now verify that the device nodes are present in the guest VM by opening a console and running the following command:

ls /dev/tpm*
You should see /dev/tpm0 and /dev/tpmrm0 devices in the output of the ls command.

**Comment by grossmj** [comment]
TPM support has been added, it can be enabled in the template / node properties:

![Screenshot from 2023-01-04 13-13-16](https://user-images.githubusercontent.com/4752614/210488826-c01acb80-4a55-431c-851a-93d111e360ba.png)

**Comment by lurendrejer** [comment]
Fantastic, Great work!!
