### ISSUE TITLE
gns3-gui folder is non existent in last ppa build 

### ISSUE THREAD

**Issue by LespiletteMaxime** [GNS3/gns3-gui#3406]
Hello,

On Linux Mint 21 with the ppa **ppa:gns3/ppa**, after upgrading I'm unable to start gns3, **/usr/bin/gns3** link point to a non existent binary **/usr/share/gns3/gns3-gui/bin/gns3**. In fact the folder **/usr/share/gns3/** is missing.

The deb I tried was **gns3-gui_2.2.35~jammy1_amd64.deb**

![image](https://user-images.githubusercontent.com/2920479/200676037-8a656a3d-725e-4199-b4ba-480060e0e467.png)

Thanks

**Comment by elijahkash** [comment]
confirm
ubuntu 20.04
after apt update/upgrade (and even  remove/install) can't run gns3-gui: no such binary

**Comment by sliddjur** [comment]
Can confirm, GNS3 was removed from my "applications" in Gnome, Ubuntu 22.04

**Comment by elijahkash** [comment]
this may help as long as the gns3-gui in the ppa is broken
`pip3 install gns3-gui==2.2.35`

**Comment by grossmj** [comment]
Sorry about this. We have fixed the problem and uploaded new packages. Please let me know if you still have an issue.

**Comment by KlemenLacetania** [comment]
I have the same problem in Ubuntu 22.04. Have used pip3 but it does not work (it returns that gns3-gui command doesn't exist).
