### ISSUE TITLE
Current zoom factor is multiplied with loading project's "zoom" value leading to incorrect node sizes

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3408]
If your current zoom factor is not equal to 100 and you're going to open another project, what resulting zoom would you expect? I believe, two variants: a) zoom factor of opening project will be set to the current zoom (but I don't think it's a good behavior) or b) new zoom will be set to project's `"zoom"` value (that is what I would prefer).

But, instead of a) or b) you'll get option c:  your current zoom factor will be multiplied with opening project's zoom factor. So if your current zoom is 116 and opening project has `"zoom": 116` too, you'll get `"zoom": 135` as a result.

And, the most interesting part, you can see this new zoom factor with your eyes (nodes are enormously big; or small if your zoom factors were less than 100), but API (`/v2/projects` for example) doesn't show it. So, in my example, you have `135` as a real (viewable) zoom factor and `116` as API zoom factor. `Ctrl +` `Ctrl -` sequence synchronizes API with reality.

**GNS3 version and operating system:**
- OS: Arch Linux (`uname -sr`: Linux 5.19.13-zen1-1-zen)
 - GNS3 version: 2.2.35.1
 - Python version: 3.10.7
 - no use of the GNS3 VM or remote server, GNS3 is installed in Python virtual environment with `pip`

**To Reproduce**
1. Prepare two projects with `"zoom": 116`.
2. Start GNS3. Open the first project. Everything looks all right.
3. Don't close GNS3. Go to `File` menu and open the second project.
4. Now you can see that nodes in this second project are bit bigger than in the first project (so, their zoom is not `116`).
5. Look at `http://localhost:3080/v2/projects`. Both `"zoom"`s are still `116`.
6. Don't close GNS3. Go to `File` menu and open the first project again.
7. Now you can see the nodes have been grown once again.
8. Repeat any times you want.

**Screenshot**
![image](https://user-images.githubusercontent.com/15959858/202039194-497cecf5-e8a5-4eb5-ad6d-9c7c88f8a786.png)
These nodes were carefully grown from `"zoom": 116` (their zoom factor is 238 now).

**Comment by grossmj** [comment]
Fixed, thanks!
