### ISSUE TITLE
GNS3 VM stopped at gnu grub version 2.02 screen in vmware 11.0.0 build-2305329

### ISSUE THREAD

**Issue by AbNet429** [GNS3/gns3-gui#3409]
Hi 

I have newly installed GNS3 software in my windows 10 laptop.

The following versions used 
OS : Windows 10 Home Single Language
VM ware : 11.0.0 build-2305329
GNS3 : GNS3-2.2.3-all-in-one & GNS3.VM.VMware.Workstation.v2.2.3 

I have tried different versions of GNS3 and latest version GNS3.VM.VMware.Workstation.2.2.35.1 also but still GNS3 VM is not starting and I am seeing gnu grub version 2.02 screen in my GNS3 VM screen in VMware.

![image](https://user-images.githubusercontent.com/118725486/203017229-7639e9e5-7cb2-4443-8e43-58a4b8b6e5e5.png)

![image](https://user-images.githubusercontent.com/118725486/203019234-768fb7bf-83be-4706-8c54-6ff9d7f1b66c.png)

It would be very greatful if someone assists on this.

Thank you

**Comment by josephmhiggins** [comment]
I have responded over here:
https://gns3.com/community/featured/gns3-vm-stopped-at-gnu-grub-version-2-02-screen-in-vmware-11-0-0-build-2305329

**Comment by eantowne** [comment]
Recommend closure.
