### ISSUE TITLE
Docker host failed to obtain IPv4 address by DHCP

### ISSUE THREAD

**Issue by vladik1974** [GNS3/gns3-gui#3424]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Any docker node when connected to DHCP server can not obtain IPv4 address

**GNS3 version and operating system (please complete the following information):**
 - OS:Linux, Windows, Mac OS
 - GNS3 version 2.2.36
 - Using GNS3 VM on Windows and Mac OS

**To Reproduce**
1. Create a new project
2. Add to the project any docker host with DHCP config for eth0 interface
3. Add to the project NAT or Cloud Node. 
4. Add a link between the docker node and NAT/Cloud node
5. Start the docker node

Expected result:
   Docker node should receive IPv4 by DHCP
   
 Actual result:  
    Docker node fails to receive IPv4, as a result there is no networking

**Screenshots or videos**
![docker_dhcp_client_to_cloud](https://user-images.githubusercontent.com/10877936/212527388-c025a1db-7a36-463c-a912-b7b5da35d034.png)

![docker_dhcp_client_to_NAT](https://user-images.githubusercontent.com/10877936/212527460-bc395db9-cc13-4aed-906c-03362441d7bd.png)

**Additional context**
Any other types (Dynamips, QEMU) nodes successfully get the IPv4 by DHCP
It seems, the the docker host successfully performs DORA process, but actually eth0 interface hasn't the IPv4 address was selected in this process

**Comment by grossmj** [comment]
Looks like we should release a v2.2.36.1 or v2.2.37 sooner than expected...
