### ISSUE TITLE
Please put back startup delay option for nodes

### ISSUE THREAD

**Issue by micush** [GNS3/gns3-gui#3429]
Hi,

GNS3 used to have a "startup delay" feature that could be specified so that when all nodes were started at the same time there could be a delay between node starts to ease the resource utilization burden on the host.

Please bring this feature back. It is extremely useful for staggering resource utilization on a host. Starting 50 nodes at once without a staggered delay can be detrimental to host operations and can sometimes lead to corruption within the nodes if they cannot get the required resources while booting. 

Thanks and regards,

micush

**Comment by grossmj** [comment]
Thanks, we definitely should have a "smart" startup delay option. It's on the TODO list but not a priority now.
