### ISSUE TITLE
Supported versions of dynamips, ubridge and vpcs included in GNS3-gui release

### ISSUE THREAD

**Issue by bsdmp** [GNS3/gns3-gui#3433]
I'm making GNS3-{server,gui} port for OpenBSD and I came across some differences between versions of companion software shipped in _GNS3-2.2.37.source.zip_ and their latest versions.

Currently shipped in zip archive versions are
- dynamips-0.2.17
- ubridge-0.9.14
- vpcs-0.6.1

But the latest versions are the following:
- dynamips-0.2.23
- ubridge-0.9.18
- vpcs-0.8.2

Do you support latest versions of these packages in GNS3, or it's better to stick with the versions shipped in GNS3-2.2.37.source.zip?

**Comment by grossmj** [comment]
Do you support latest versions of these packages in GNS3, or it's better to stick with the versions shipped in GNS3-2.2.37.source.zip?

We support the latest versions. I will include these versions in the zip file for our next release. Thanks for catching this 👍
