### ISSUE TITLE
Is there a multilingual option for GNS3

### ISSUE THREAD

**Issue by Aronzxw** [GNS3/gns3-gui#3434]
Dear developer, I am a Chinese user, and I have a weak understanding of English. Can you provide multilingual options for GNS3, and I hope there is a Chinese version of the interface——From Google Translate

**Comment by grossmj** [comment]
Thanks for posting an issue here however this has already been discussed in https://github.com/GNS3/gns3-gui/issues/2731#issuecomment-472349426
