### ISSUE TITLE
Installer seems to have wrong url for virt-viewer on 3.0.0 alpha 3

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3435]
**Before you start**
I don't see this reported

**Describe the bug**
Installer seems to have wrong url for virt-viewer on 3.0.0 alpha 3

**GNS3 version and operating system (please complete the following information):**
Windows - all-in-one

**To Reproduce**
install and chose virt-viewer in custom install

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/31658656/218164683-bd48dbf0-edba-44b1-b8f1-cd39daebe74a.png)

**Additional context**

**Comment by spikefishjohn** [comment]
![image](https://user-images.githubusercontent.com/31658656/218164937-d3762648-d909-4cc3-90e8-f7e2d51331f6.png)

**Comment by spikefishjohn** [comment]
https://virt-manager.org/download.html 

seems to point to

https://releases.pagure.org/virt-viewer/

which would make final url

https://releases.pagure.org/virt-viewer/virt-viewer-x64-11.0-1.0.msi

**Comment by grossmj** [comment]
Fixed, thanks 👍
