### ISSUE TITLE
v3.0.0 alpha 3 - Webclient pack has wrong path for spice viewer

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3436]
**Describe the bug**
Webclient pack has wrong path for spice viewer (wrong version)

**GNS3 version and operating system (please complete the following information):**
gns3 3.0.0. alpha 3

**To Reproduce**
Install webclient and run the config.

**Screenshots or videos**

![image](https://user-images.githubusercontent.com/31658656/218167833-5c343043-2a7a-42c3-a270-e9f356fc4bc4.png)

**Additional context**
I skipped breakfast and have regrets.

**Comment by spikefishjohn** [comment]
Should be
"C:\Program Files\VirtViewer v11.0-256\bin\ etc etc"

**Comment by kezzchr34** [comment]
GNS3/gns3- WebClient pack v3.0.0 alpha works ok in Ubuntu 20.0.4
![Fortigate_lab](https://user-images.githubusercontent.com/117614880/218502338-872fc196-cf17-4f56-894f-763afa78db62.png)

 The feature to allow the user to customize spice client also works as I  also configured spice to use vinagre as well as use SecureCRT as the default console using the webclient.
![remote-Desktop-Viewer_vinagre](https://user-images.githubusercontent.com/117614880/218503943-46b2b157-f797-4fff-bf2b-ff468c975005.png)

![web-client-config](https://user-images.githubusercontent.com/117614880/218504004-f4576c03-18b0-4edb-8fce-32defb839308.png)

How long before the other enhancements

- Change the link color to each node; as this can be done in GNS3 [Version 3.0.0 alpha 3](https://github.com/GNS3/gns3-gui/releases/tag/v3.0.0a3) -web-ui
-  Adding more styling options (Curved lines, Rounded Rectangle...)
