### ISSUE TITLE
"Start the capture visualization program" checkbox works only one (first) time for a given link

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3442]
Wireshark starts automatically only one time for a given link. If you stop capturing and start it again on the same link - you have to start Wireshark manually (select "Start Wireshark" from the link menu) despite "Start the capture visualization program" checkbox.

There is no message "Stopping packet capture reader for link ..." in logs, so I think there are some problems with [if clause](https://github.com/GNS3/gns3-gui/blob/f6ab5cae16e909e905cf02ffa83db345fd902831/gns3/packet_capture.py#L121) in `stopPacketCaptureReader` function. 

**GNS3 version and operating system:**
- OS: Arch Linux (`uname -sr`: Linux 6.0.11-zen1-1-zen)
 - GNS3 version: 2.2.37
 - Python version: 3.10.8
 - no use of the GNS3 VM or remote server, GNS3 is installed in Python virtual environment with `pip`

**To Reproduce**
1. Start GNS3, open (create) a project.
2. Right-click on a link, select "Start capture", tick "Start the capture visualization program" checkbox on. Press OK.
3. Wireshark starts normally. Now close Wireshark and stop capturing.
4. Repeat the step 2 once again.
5. See error: capturing has been started (you can see magnifying glass icon), but Wireshark didn't start at all.
6. Stop capturing, repeat step 2, see the same results as in step 5.
7. Now repeat step 2, but with another link.
8. Wireshark starts normally, like in step 3 for the first link. Close Wireshark and stop capturing.
9. Repeat step 2 with the second link once again. Now you can see no Wireshark, as in step 5 for the fist link.

**Comment by josephmhiggins** [comment]
Yeah, there is some problems over there.
Another thing is that if you stop the capture and close wireshark and delete the pcap on the gns3 vm, it causes all kinds of problems.
One of the problems it can cause is you can not delete the link to try to resolve the issue.
The "you can not delete the link" shows up in various scenarios the gns3 users complain about over the last couple of years.
Wireshark is kind of  messy in gns3 < 3.0, so I am just hoping it will be better.
Other than that, I will have to enable-psremoting and figure out how wireshark is supposed to be done properly.
Wireshark is critical.

**Comment by andrei-korshikov** [comment]
@josephmhiggins
> if you stop the capture and close wireshark and delete the pcap on the gns3 vm, it causes all kinds of problems

Can't reproduce in my setup. Deleting .pcap files doesn't lead to any problems for me. But I use GNS3 in Linux (in pyenv) without VM. Also, I should say I've never had any issues with Wireshark in conjunction with GNS3 (except this one).

**Comment by josephmhiggins** [comment]
Yeah, I am using Windows 10. With the gns3server moving off of Windows it will be much, much easier.
That's why I would rather wait for 3.0
I looked at it and your "To reproduce"; it would take me at least 8 hours to break everything down.

**Comment by grossmj** [comment]
> There is no message "Stopping packet capture reader for link ..." in logs, so I think there are some problems with [if clause](https://github.com/GNS3/gns3-gui/blob/f6ab5cae16e909e905cf02ffa83db345fd902831/gns3/packet_capture.py#L121) in stopPacketCaptureReader function.

You were right, the problem was with the stopPacketCaptureReader function. Thanks, that helped to find the problem faster 👍
