### ISSUE TITLE
GNS3 Gui - double click opening wrong window.

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3444]
**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: windows
 - GNS3 version 2.2.33.1
 - bare metal because this is the way.

**To Reproduce**
I have a laptop. I'm connecting using a Fortinet VPN to access a GNS3 install. I then open a GNS3 project. In said GNS3 project there is a VM called Forticlient. If I double click on this VM the gui for the Fortinet client comes up. If I right click on the VM and chose console the console will then open. The console of this devices is spice and the VM in question is windows.

If I rename the VM forticlient1 double click will work as expected. If I change the name to "orticlient" double click will work as expected. If I then change it back to "forticlient" it will open the forticlient console again.

Note the window name of the forticlient is "forticlient". It seems not case sensitive. 

![image](https://user-images.githubusercontent.com/31658656/219979829-69e7263a-d277-43ec-b743-6d52c66fe483.png)

**Comment by eantowne** [comment]
You find the coolest bugs :) @spikefishjohn !

**Comment by grossmj** [comment]
> I'm connecting using a Fortinet VPN to access a GNS3 install.

Unfortunately I cannot reproduce this bug, the only thing I haven't done is using a Fortinet VPN...

**Comment by spikefishjohn** [comment]
My guess, and I have nothing to back this up, is gns3 is looking for the same window name when you double click it on the console and the fortinetvpn window has the same name? 

I'm assuming no one else will ever open this again to feel free to close if you can't find anything for me to look at.
