### ISSUE TITLE
Difference between Telnet / HTTP Console Command in IPv6

### ISSUE THREAD

**Issue by wangziyao318** [GNS3/gns3-gui#3448]
I use GNS3 client to connect to my remote GNS3 server with only public IPv6 address `[2000:1234:5678:abcd::1]`. I have some devices with telnet console and other devices with http console in one project.

If I input `[2000:1234:5678:abcd::1]` into Host, I can connect to the remote server, http console work, but telnet console NOT work
If I input `2000:1234:5678:abcd::1` into Host, I can connect to the remote server, telnet console work, but http console NOT work

The reason is that telnet IPv6 address should not be closed in square brackets, but http IPv6 address should be closed in square brackets.

```
telnet 2000:1234:5678:abcd::1 5000
curl http://[2000:1234:5678:abcd::1]:5050
```

So, I suggest GNS3 client to be able to distinguish them in console commands, because not everyone has a domain name to use. Thanks.

**Comment by grossmj** [comment]
Are you talking about console host in a "cloud" node?

**Comment by wangziyao318** [comment]
I'm talking about the **HTTP console of Docker nodes**. They work quite well for GNS3 server in IPv4, but for gns3 server in IPv6, extra brackets [] are missing for the HTTP console.

<img width="392" alt="Screenshot 2023-05-15 at 11 13 38" src="https://github.com/GNS3/gns3-gui/assets/69375071/911bdcb8-214f-410a-9994-6c115f2fcef8">


<img width="659" alt="Screenshot 2023-05-15 at 11 16 01" src="https://github.com/GNS3/gns3-gui/assets/69375071/0c157554-f22a-4407-922c-519f1680e2b7">

**Comment by grossmj** [comment]
This is fixed now. Please try in v2.2.40. Thanks again for catching that 👍
