### ISSUE TITLE
Short description of the bug"Transport (VMDB) error -14: Pipe connection has been broken" when running GNS3 VM on Macbook Air M1

### ISSUE THREAD

**Issue by termaulmaul** [GNS3/gns3-gui#3451]
I was just able to get the two vmdk files from the GitHub site and build a VM that launches under Fusion 13 on a Macbook Air M1
I created the VM as indicated in the article, but I chose the VM type as "Other Linux 5.x kernel 64bit ARM" instead of Ubuntu.
When asked for the hard drive during VM creation, I used the gns3vm-disk1.vmdk and opted to make a separate copy of the virtual disk.
I gave it 2 processors and 4096 MB of memory.
I added the second hard drive (making a separate copy of it as well) from gns3vm-disk2.vmdk.
I added the second network adapter as "Private to my Mac".
Booted the VM and error says "Transport (VMDB) error -14: Pipe connection has been broken"
<img width="912" alt="Screenshot 2023-03-08 at 20 34 00" src="https://user-images.githubusercontent.com/109366541/223934559-23894074-bb07-4c14-9b7e-0d1ba7b12f30.png">

gns3vm for arm from official gns3 github
https://github.com/GNS3/gns3-gui/discussions/3261

my log and screenshot
https://github.com/termaulmaul/vmwarelog

**Comment by grossmj** [comment]
Sorry, I am not able to help at the moment. Please note that M1 support for the GNS3 is experimental at this stage.

**Comment by fruitybagel** [comment]
yeah but you also killed kexts loading from 12 version on latest monterey
