### ISSUE TITLE
2.2 : docker and vnc

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3452]
Hi

On LiveRaizo (Debian bullseye), with the last GNS3 2.2

I create a new template docker (name is "testons") : i keep the defaults values, but "console type" is set to "vnc".

I put this docker on the lab. I don't start it.

I edit the configuration of this device but i change nothing
When i click on "OK",  GNS3 displays this error message : `The vnc process has stopped with return code 2 for node 'testons-1'. Please restart this node.`

gns3_gui.log contains : 
`2023-03-09 18:11:57 ERROR project.py:722 The vnc process has stopped with return code 2 for node 'testons-1'. Please restart this node.`

**Comment by grossmj** [comment]
@Raizo62 what Docker image have you used to create your Docker template?

**Comment by Raizo62** [comment]
I have verified with an "alpine"

**Comment by grossmj** [comment]
It seems there is a problem with the Xvfb + x11vnc code. I had a quick check to fix this without success however before going deeper, should we still support Xvfb + x11vnc since we recommend to install TigerVNC instead?

**Comment by grossmj** [comment]
@Raizo62 any reason you would want to use  Xvfb + x11vnc instead of TigerVNC?

**Comment by Raizo62** [comment]
That was a long time ago so I don't remember. I suppose that is the size of the package.
I will test with TigerVNC. On debian, do i need of "tigervnc-standalone-server" or "tigervnc-viewer" or the both ?

**Comment by grossmj** [comment]
`tigervnc-standalone-server` should be enough.

**Comment by Raizo62** [comment]
It's my first test, so maybe I'm forgetting something.
But, with "tigervnc-standalone-server", i can put a Docker with vnc, i can start it, i can run the vnc,.
But when a docker container is running, i can't put an other docker in GNS3 :
`Error while creating node from template: x11 socket file "/tmp/.X11-unix/X100" does not exist`
I have also installed tigervnc-xorg-extension

**Comment by grossmj** [comment]
@b-ehlers do you see any reason we should keep Xvfb + x11vnc support?

**Comment by Raizo62** [comment]
> I can not reproduce the issue Raizo62 has with multiple docker VNC nodes

@b-ehlers : De you reproduce exactlty my procedure ? If i put the devices before to run it, i have no issue.

Do you have installed an other package ou do a particular config ? I have only installed "tigervnc-standalone-server"

**Comment by Raizo62** [comment]
I believe that problem comes from the starting command of the device : "/usr/sbin/init"

**Comment by Raizo62** [comment]
>> De you reproduce exactlty my procedure ? If i put the devices before to run it, i have no issue.
> I don't know, I don't understand your procedure.

Oh...sorry for my poor english :-( 
To have the issue, a vnc container must be runnning before to add a second vnc container on the toplogy of GNS3.
If i add all the containers before to run them, i don't have the issue.

But, now, i know that the problem is the starting command ("/usr/sbin/init")

**Comment by Raizo62** [comment]
Yes, if i remove "/usr/sbin/init", the folder /tmp/.XX-unit is not empty.
I use "/usr/sbin/init" to run systemd in the container. Perhaps that is systemd of the container which clean this folder.
But I don't really need "/usr/sbin/init" here : I modified this template to use vnc only to test TigerVNC quickly
