### ISSUE TITLE
Gns3 Crashes when zooming/moving the canvas in bigger topologies

### ISSUE THREAD

**Issue by Pleonazm** [GNS3/gns3-gui#3453]
**Describe the bug**
After the topology is loaded, zooming or panning the canvas in topology crashes GNS3
Message on the console dock/alert window:
Timeout error for PUT call to http://127.0.0.1:3080/v2/compute/projects/d444ef1c-cd37-4dd9-99db-a9a2cbc51a14 after 20s

Can't say if this is a problem with the GUI or the server.

**GNS3 version and operating system (please complete the following information):**
GNS3: 2.2.38
Client: Windows 11 Pro, Standalone GUI
Server: Separate physical server, Ubuntu 20.04 directly installed, fully updated
Logs also included in the community post

**To Reproduce**
1. Load a big topology
2. Start zooming, moving the canvas with a mouse

**Additional context**
Community link: https://gns3.com/community/support/problem-with-big-topologies

**Logs**
Logs from the server (/var/log/gns3/)
The raw log file, and split into parts
Part 1 is starting gns3/loading topology
Part 2 is after I start moving the mouse/zooming etc

[gns3.log](https://github.com/GNS3/gns3-gui/files/10954907/gns3.log)
[gns3_log_part1.txt](https://github.com/GNS3/gns3-gui/files/10954908/gns3_log_part1.txt)
[gns3_log_part2.txt](https://github.com/GNS3/gns3-gui/files/10954909/gns3_log_part2.txt)

**Comment by bmcgahan** [comment]
@grossmj is there any update or hotfix that can be applied to workaround this issue? I have a number of topologies that crash when you zoom in/out, and I can't figure out any settings that affect it.

![image](https://github.com/GNS3/gns3-gui/assets/4155839/9c6be57b-25e9-4cfb-9295-4b9212597e7b)

**Comment by JKPla** [comment]
My band-aid fix for this was to increase the timeout value in /usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/controller/compute.py method _run_http_query.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/compare/d54e6babe2fd...512407939d3a
