### ISSUE TITLE
stopped docker and open vnc

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3455]
Hi

On LiveRaizo (Debian bullseye) and the last GNS3 2.2

I push on the lab a docker device which uses VNC as console.

I start the device, and open his console.

With GNS3, i stop the device, so it is stopped, but his VNC console stays open.

**Comment by Raizo62** [comment]
Thanks @b-ehlers for these explanations

**Comment by grossmj** [comment]
> To change that behavior, the stopping the VNC server needs to be done when the VM stops.

@b-ehlers are you suggesting that GNS3 server should stop the VNC server when the VM stops?
