### ISSUE TITLE
Uninstalling GNS3 Issue

### ISSUE THREAD

**Issue by SV8943** [GNS3/gns3-gui#3456]
I want to upgrade from 2.2.24, however this pops up.  

"Gns3 version 2.2.24 must first be uninstalled before installing version 2.2.38.
Would you like to proceed?
WARNING: Everything inside c:\Users\Owner will be permanently deleted"

Previously I had issues getting my vm working so I tried to do a reinstall of gns3 and it started deleting everything on my desktop. I managed to stop the uninstall and recovered some of my data. How do I prevent from this happening again? Is there a way to uninstall gns3 without it deleting everything from my desktop?

**Comment by grossmj** [comment]
We have added a protection mechanism to avoid this from happening.
