### ISSUE TITLE
Link - 'Style' says "red (#ff0000), 3 px" instead of true values

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3460]
If you go to link 'Style editor' not from canvas (by right-clicking the line itself), but from 'Topology Summary' (by right-clicking the textual representation of a given link), link selection isn't cleared (link color stays red because of selection). And 'Style editor' says that link color is red, but that's not true.

Notes:
1. I think that resetting link color (I mean clearing selection when you press right button on a line) is a bit misleading. Because when you're working somewhere in 'Packet filters' dialog or in 'Style editor', you have no glue - what link you're editing right now. So I would prefer that link selection stays permanent while I'm working with this link.
2. It would be nice to have selection with something like background color. Look at Screenshot no. 3, one "link" selected in yEd Graph Editor. So it is clearly visible, what link is selected, and what color/style it has (sometimes color or style means something, so it's nice to see them).

**GNS3 version and operating system:**
 - OS: Arch Linux (`uname -sr`: Linux 6.2.9-zen1-1-zen)
 - GNS3 version: 2.2.38
 - Qt version: 5.15.2
 - Python version: 3.10.10
 - no use of the GNS3 VM or remote server, GNS3 is installed in Python virtual environment with `pip`

**To Reproduce**
1. Go to 'Tolopogy Summary', right click on a link. Look, at this very moment the link becomes red ("selected").
4. Click on 'Style'. See 'Border color': red (#ff0000), and 'Border width': 3 px instead of true values. See screenshot no. 1.
5. Press 'Cancel'.
6. Left click on empty space (so link becomes deselected on canvas, but is still selected in 'Topology Summary').
7. Go to 'Tolopogy Summary', right click on the link once again. Now, you can see true border color/width values (in my case 'white' and '2px'; yes, 'white' is on purpose - so I create invisible links to out-of-band management switch without cluttering the overall picture). See screenshot no 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/15959858/230519959-b33787d7-a0e4-450b-b6b9-64210d31280e.png)
![image](https://user-images.githubusercontent.com/15959858/230520095-95b096fe-aa55-4253-8cfb-c02ded2b773d.png)
![image](https://user-images.githubusercontent.com/15959858/230521587-374b9701-cdb9-4cd0-8029-b7c20e210fb0.png)

**Comment by grossmj** [comment]
> I think that resetting link color (I mean clearing selection when you press right button on a line) is a bit misleading. Because when you're working somewhere in 'Packet filters' dialog or in 'Style editor', you have no glue - what link you're editing right now. So I would prefer that link selection stays permanent while I'm working with this link.

I have added same behavior that we have when you select a link on the canvas for now. I will try to find a better solution.

> It would be nice to have selection with something like background color. Look at Screenshot no. 3, one "link" selected in yEd Graph Editor. So it is clearly visible, what link is selected, and what color/style it has (sometimes color or style means something, so it's nice to see them).**

Unfortunately there is no background color option. Please see https://doc.qt.io/qt-6/qpen.html for what we can use.

**Comment by grossmj** [comment]
Now I do not reset the link color anymore. I think that should solve this issue.
