### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by icegood** [GNS3/gns3-gui#3462]
no lunar repo support under
https://ppa.launchpadcontent.net/gns3/ppa/ubuntu/dists/

i.e. for ubuntu 23.04

**Comment by grossmj** [comment]
I have built the packages for Ubuntu 23.04: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=&field.series_filter=lunar
