### ISSUE TITLE
Cannot drag and drop nodes to workspace in gui .. no issues in web client

### ISSUE THREAD

**Issue by NikolayDachev** [GNS3/gns3-gui#3464]
**Before you start**
This look like a old known issue (I found several reports without any clear resolution!)

**Describe the bug**
I can use web-gui without any issues 
I can see any added node via web-gui in gns3-gui workspace also I can modify them and delete them

The only problem is (may be related to QT on my machine?! ) I cannot drag and drop any node from device(node) panel from left side to workspace. 
No logged errors in gns3-gui or gns3-server!

When I try to add node .. the node icon is just show as not allowed/forbidden (zero with scratched line) !
In same time I can add any other element like text etc. but via menu not via drag and drop !

I have this  issue with GNS3 installed from os pkg manager, pip .. also the same issue and with 3.0beta 
For this reason I'm not sure where is the problem 

**GNS3 version and operating system (please complete the following information):**
 - OS: openSUSE Tumbleweed 20230422
 - (Running GNS3 version 2.2.38 on Linux (64-bit) with Python 3.10.10 Qt 5.15.2 and PyQt 5.15.2.)
 - GNS3 version 2.2.38 
 - PyQt5-Qt 5.15.2 (PyQt 5.15.2)
 - python version 3.10.10
 - local server with KVM (no issue in web-gui)

**To Reproduce**
1. Create new project 
2. try to add node to workspace
 
Regards,

**Comment by grossmj** [comment]
That's very strange indeed. Does it happen only on openSUSE?

**Comment by Bartosz-lab** [comment]
I have same problem on:
* OS: Fedora 38
* Python 3.11.3
* GNS3 version 2.2.38 and 2.2.39
* PyQt5-Qt 5.15.9

**Comment by micush** [comment]
I have the same problem on Ubuntu 23.04.

**Comment by Bartosz-lab** [comment]
> I have same problem on:
> * OS: Fedora 38
> * Python 3.11.3
> * GNS3 version 2.2.38 and 2.2.39
> * PyQt5-Qt 5.15.9
> 

I reinstalled my system, and now the pro lem doesn't occur.
Packages versions as same as before reinstall:
* OS: Fedora 38
* Python 3.11.3
* GNS3 version 2.2.38
* PyQt5-Qt 5.15.9

**Comment by micush** [comment]
I rolled back to Ubuntu 22.04. All works as it should now.

**Comment by ivanovuri** [comment]
Same issue on ubuntu 23.04. Running GNS3 version 2.2.39 on Linux (64-bit) with Python 3.11.2 Qt 5.15.8 and PyQt 5.15.9.
`gns3 --debug` doesn't show any info when trying to add new device.

**Comment by grossmj** [comment]
Do you confirm you see the following log when starting the GNS3 server?

```
2023-06-02 20:51:58 INFO notification_handler.py:50 New client has connected to compute WebSocket
2023-06-02 20:51:58 INFO compute.py:431 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
```

**Comment by ivanovuri** [comment]
No it does not:
    gns3 --debug > gns3_manual_start.log

    user1@vpc:~$ grep notification_handler.py gns3_manual_start.log
    user1@vpc:~$ grep compute.py gns3_manual_start.log
    user1@vpc:~$ grep WebSocket gns3_manual_start.log
    2023-06-02 14:29:24 DEBUG http_client:491 Connecting to WebSocket endpoint: ws://localhost:3080/v2/notifications/ws
    2023-06-02 14:29:29 DEBUG http_client:491 Connecting to WebSocket endpoint: ws://localhost:3080/v2/projects/dd4b912f-3983-4448-8e1e-ca061f46ddd6/notifications/ws
    user1@vpc:~$ 
This is complete output log [gns3_manual_start.log](https://github.com/GNS3/gns3-gui/files/11634863/gns3_manual_start.log)
I've simply start, open project and close gns3.

**Comment by grossmj** [comment]
I can see you are receiving events from the server in your log file: `2023-06-02 14:29:37 DEBUG project:678 Event received from project stream: {'action': 'node.updated', 'event': {'command_line': '', 'compute_id': 'local', 'console': 5005, ...` so looks like the problem is not with the websocket notification stream.

Can you try with the web-ui? (Tools -> Web UI - beta in the desktop interface). Thanks

**Comment by ivanovuri** [comment]
Sure no problem this log with the same topology and nodes R6 and R7 are created with Web UI.
Thanks in advance.
[gns3_manual_start_webui.log](https://github.com/GNS3/gns3-gui/files/11635007/gns3_manual_start_webui.log)

**Comment by NikolayDachev** [comment]
I just try gns  2.2.39 (vi a pip not opensuse zypper - pkg is not updated yet) 
No issues

**Comment by ivanovuri** [comment]
Hi @grossmj 
I've updated to new version 2.2.40 but nothing changed.
Maybe I should configure something somehow manually?

**Comment by grossmj** [comment]
I am suspecting a problem with the drop event in Qt. I have added a debug message to help with this.

https://github.com/GNS3/gns3-gui/blob/2.2/gns3/graphics_view.py#L716

**Comment by devmobux** [comment]
Hi there, i have the same problem with gns3-gui i cannot drag and drop nodes to topology but work fine with web ui beta

**Comment by grossmj** [comment]
@devmobux 

Please can you open GNS3, type `debug 1` in the GNS3 console and try to drag&drop one node on the topology?

I am looking for the debug message: `Drop event received with mime data: ['application/x-gns3-template']`

![Screenshot from 2023-07-31 18-19-01](https://github.com/GNS3/gns3-gui/assets/4752614/37fcb46a-bd2e-4e8c-a732-93a5a715a255)

Thanks

**Comment by devmobux** [comment]
@grossmj 

I try it but i don't receive debug message when i drag and drop nodes

**Comment by grossmj** [comment]
Are you using the latest version?

**Comment by devmobux** [comment]
Yes i'm using the version 2.2.41

**Comment by grossmj** [comment]
Do you still have the issue with version 2.2.42? Also, do you have a screenshot showing what you see after activating `debug 1` in the GNS3 console and trying to drop a node?

Thanks.

**Comment by grossmj** [comment]
Anyone still having this issue with the latest version? thanks 👍

**Comment by rhevo** [comment]
I have 
=> debug 1
Activating debugging
Section MainWindow has changed. Saving configuration
but when tried moving device, nothng shows

**Comment by rhevo** [comment]
i use the latest version 2.2.43

**Comment by rhevo** [comment]
@grossmj 

=> debug 1
Activating debugging
Section MainWindow has changed. Saving configuration
Configuration save to /home/mash/.config/GNS3/2.2/gns3_gui.conf
=> PUT http://localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d {'name': 'new', 'auto_open': False, 'auto_close': True, 'auto_start': False, 'scene_width': 2000, 'scene_height': 1000, 'zoom': 25, 'show_layers': False, 'snap_to_grid': False, 'show_grid': False, 'grid_size': 75, 'drawing_grid_size': 25, 'show_interface_labels': False, 'variables': None, 'supplier': None}
Decoding response from http://admin@localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d response 200
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
Event received from project stream: {'action': 'project.updated', 'event': {'auto_close': True, 'auto_open': False, 'auto_start': False, 'drawing_grid_size': 25, 'filename': 'new.gns3', 'grid_size': 75, 'name': 'new', 'path': '/home/mash/GNS3/projects/new', 'project_id': 'ef75721a-cd19-4d68-bc87-c45a9adc1b6d', 'scene_height': 1000, 'scene_width': 2000, 'show_grid': False, 'show_interface_labels': False, 'show_layers': False, 'snap_to_grid': False, 'status': 'opened', 'supplier': None, 'variables': None, 'zoom': 25}}
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
PUT http://localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d {'name': 'new', 'auto_open': False, 'auto_close': True, 'auto_start': False, 'scene_width': 2000, 'scene_height': 1000, 'zoom': 21, 'show_layers': False, 'snap_to_grid': False, 'show_grid': False, 'grid_size': 75, 'drawing_grid_size': 25, 'show_interface_labels': False, 'variables': None, 'supplier': None}
Decoding response from http://admin@localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d response 200
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
Event received from project stream: {'action': 'project.updated', 'event': {'auto_close': True, 'auto_open': False, 'auto_start': False, 'drawing_grid_size': 25, 'filename': 'new.gns3', 'grid_size': 75, 'name': 'new', 'path': '/home/mash/GNS3/projects/new', 'project_id': 'ef75721a-cd19-4d68-bc87-c45a9adc1b6d', 'scene_height': 1000, 'scene_width': 2000, 'show_grid': False, 'show_interface_labels': False, 'show_layers': False, 'snap_to_grid': False, 'status': 'opened', 'supplier': None, 'variables': None, 'zoom': 21}}
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
PUT http://localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d {'name': 'new', 'auto_open': False, 'auto_close': True, 'auto_start': False, 'scene_width': 2000, 'scene_height': 1000, 'zoom': 18, 'show_layers': False, 'snap_to_grid': False, 'show_grid': False, 'grid_size': 75, 'drawing_grid_size': 25, 'show_interface_labels': False, 'variables': None, 'supplier': None}
Decoding response from http://admin@localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d response 200
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
Event received from project stream: {'action': 'project.updated', 'event': {'auto_close': True, 'auto_open': False, 'auto_start': False, 'drawing_grid_size': 25, 'filename': 'new.gns3', 'grid_size': 75, 'name': 'new', 'path': '/home/mash/GNS3/projects/new', 'project_id': 'ef75721a-cd19-4d68-bc87-c45a9adc1b6d', 'scene_height': 1000, 'scene_width': 2000, 'show_grid': False, 'show_interface_labels': False, 'show_layers': False, 'snap_to_grid': False, 'status': 'opened', 'supplier': None, 'variables': None, 'zoom': 18}}
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
PUT http://localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d {'name': 'new', 'auto_open': False, 'auto_close': True, 'auto_start': False, 'scene_width': 2000, 'scene_height': 1000, 'zoom': 15, 'show_layers': False, 'snap_to_grid': False, 'show_grid': False, 'grid_size': 75, 'drawing_grid_size': 25, 'show_interface_labels': False, 'variables': None, 'supplier': None}
Decoding response from http://admin@localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d response 200
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
Event received from project stream: {'action': 'project.updated', 'event': {'auto_close': True, 'auto_open': False, 'auto_start': False, 'drawing_grid_size': 25, 'filename': 'new.gns3', 'grid_size': 75, 'name': 'new', 'path': '/home/mash/GNS3/projects/new', 'project_id': 'ef75721a-cd19-4d68-bc87-c45a9adc1b6d', 'scene_height': 1000, 'scene_width': 2000, 'show_grid': False, 'show_interface_labels': False, 'show_layers': False, 'snap_to_grid': False, 'status': 'opened', 'supplier': None, 'variables': None, 'zoom': 15}}
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
PUT http://localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d {'name': 'new', 'auto_open': False, 'auto_close': True, 'auto_start': False, 'scene_width': 2000, 'scene_height': 1000, 'zoom': 12, 'show_layers': False, 'snap_to_grid': False, 'show_grid': False, 'grid_size': 75, 'drawing_grid_size': 25, 'show_interface_labels': False, 'variables': None, 'supplier': None}
Decoding response from http://admin@localhost:3080/v2/projects/ef75721a-cd19-4d68-bc87-c45a9adc1b6d response 200
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration
Event received from project stream: {'action': 'project.updated', 'event': {'auto_close': True, 'auto_open': False, 'auto_start': False, 'drawing_grid_size': 25, 'filename': 'new.gns3', 'grid_size': 75, 'name': 'new', 'path': '/home/mash/GNS3/projects/new', 'project_id': 'ef75721a-cd19-4d68-bc87-c45a9adc1b6d', 'scene_height': 1000, 'scene_width': 2000, 'show_grid': False, 'show_interface_labels': False, 'show_layers': False, 'snap_to_grid': False, 'status': 'opened', 'supplier': None, 'variables': None, 'zoom': 12}}
Section MainWindow has not changed. Skip saving configuration
Section MainWindow has not changed. Skip saving configuration

**Comment by grossmj** [comment]
@rhevo about the latest log you posted, is it when you opened a project? Thanks :)

**Comment by rhevo** [comment]
@grossmj when I'm dragging devices to my workspace. Thanks

**Comment by grossmj** [comment]
Thank you, what OS and version of Qt do you have?

**Comment by grossmj** [comment]
I could reproduce the problem on Ubuntu 23.04 running X11 / Gnome 44:

![Screenshot from 2023-10-25 17-38-46](https://github.com/GNS3/gns3-gui/assets/4752614/e6f62542-858a-4657-bd3b-923da13ec979)

The problem goes away when running with Wayland. One workaround could be https://github.com/OpenShot/openshot-qt/issues/5221#issuecomment-1546539610

 or try to run `QT_QPA_PLATFORM=wayland gns3` maybe?

**Comment by grossmj** [comment]
Does anyone still have this issue?
