### ISSUE TITLE
GNS3 VM with Virtualbox 7: Host-Only Adapter not available any more

### ISSUE THREAD

**Issue by ianreesidr** [GNS3/gns3-gui#3472]
I also ran into this issue raised in GNS3 community:
https://gns3.com/gns3-vm-with-virtualbox-7-host-only-adapter-not-available-any-more

I'll submit this on behalf of GNS3bonobo, thanks for documenting it in the chat.
As requested by Joe Higgins I'm adding it here so developers can review what options are available for running GNS VM in Virtualbox 7 +

I'm running GNS3 2.2.37 on Macos Ventura 13.2.1 with VirtualBox 7.0.6.

VirtualBox 7.0.6 marks the "Host-Only"-Adapter as deprecated and creates a "Host-Only"-Network for this function. But this does not work with GNS3. After starting GNS3 complains that the GNS3 VM needs to be configured with a least one Host-Only-Adapter to work - but this is not available any more in VirtualBox 7.

**Comment by josephmhiggins** [comment]
I just read the Change log for virtualbox 7.0+
https://www.virtualbox.org/wiki/Changelog-7.0?ref=upstract.com

I see no mention of this change in the official change log. But I may have seen this change in virtualbox forums.
On Windows 10 I just installed 7.08 and it's extension pack and "everything" works.
On Windows, there is an interface name, interface alias, and interface description; I can change them all on Windows.
On Windows, the network in question still shows up as "Host-only Adapter" and there is no option to choose "Host-only Network"
I am not a mac user so I do not know what can be done to attempt a workaround.
Trying Virtualbox 7.0.8 should not hurt anything though.

**Comment by grossmj** [comment]
> VirtualBox 7.0.6 marks the "Host-Only"-Adapter as deprecated and creates a "Host-Only"-Network for this function. But this does not work with GNS3. After starting GNS3 complains that the GNS3 VM needs to be configured with a least one Host-Only-Adapter to work - but this is not available any more in VirtualBox 7.

Correct, "Host-Only" Adapter is deprecated in recent macOS versions as explained in https://www.virtualbox.org/manual/ch06.html#network_hostonly

We will have to fix for this.

**Comment by grossmj** [comment]
This should be fixed in the next version (v2.2.40)

**Comment by ianreesidr** [comment]
"This should be fixed in the next version (v2.2.40)" Many thanks indeed!
