### ISSUE TITLE
2.2 : QEmu : telnet console and "auto start console"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3474]
Hi

On LiveRaizo, i have a QEmu Device : The OS is Linux(Debian) and the "Console type" is "telnet".
I enable "Auto start console".

When i start this VM, i see a windows that opens but closes very quickly (i can't read anything).
If, after, i open the console of the VM, there is no problem.

**Comment by Raizo62** [comment]
I specify that the auto-start works with the vnc mode. The auto-start fails with telnet mode

**Comment by Raizo62** [comment]
If you can't reproduce the bug, i put here the logs : 
[gns3_server.log](https://github.com/GNS3/gns3-gui/files/12048616/gns3_server.log)
[gns3_gui.log](https://github.com/GNS3/gns3-gui/files/12048618/gns3_gui.log)

We can see :
```
DEBUG telnet_console.py:114 Starting telnet console in thread "xterm -T "%d" -e "telnet %h %p""
DEBUG telnet_console.py:88 Telnet console localhost:5000 closed
```

I don't know if it is useless : "enable kvm" is checked. "kvm is required" is unchecked

**Comment by grossmj** [comment]
I think this is because GNS3 tries to connect to the console while we node hasn't had a chance to start.
