### ISSUE TITLE
GNS3 console font color

### ISSUE THREAD

**Issue by Mario156090** [GNS3/gns3-gui#3475]
Hello dear GNS3 developer team, I using GNS3 about six years ago and ever I use the linux version, I looked for a way for set dark mode theme for the GUI. I found the option with qt5ct program and and set the classic theme to black. Here the images:

qt5c config:
![image](https://github.com/GNS3/gns3-gui/assets/47507975/5139c533-0d13-4d57-bb8e-f1d803720762)
GNS3 GUI:
![image](https://github.com/GNS3/gns3-gui/assets/47507975/a94ae509-62ce-49d7-bfa5-0b33b6a3fc61)
GNS3 classic theme seted.
![image](https://github.com/GNS3/gns3-gui/assets/47507975/8a51b185-70aa-4833-a9c1-4b622d2f14ca)

If you set this theme you can set the default label style and default note style to some color, in this case the better is white but you can't not set the console section output color to any color.

So, I think be good add an option for change the console output color to white or another color.

![image](https://github.com/GNS3/gns3-gui/assets/47507975/83d8756e-f090-4d07-b200-5d8c246ac359)

Thank's for read.

**Comment by grossmj** [comment]
I would recommend to use our `charcoal` style instead.

![Image](https://github.com/GNS3/gns3-gui/assets/4752614/703adccc-0843-4647-b12e-79ab22b37fc9)

We also plan to have a dark style: https://github.com/GNS3/gns3-gui/issues/767
