### ISSUE TITLE
Can't Ping Between VPC running on GNS3 VM

### ISSUE THREAD

**Issue by rafiirzam** [GNS3/gns3-gui#3484]
Hello everyone, 
I Got same issue like this case https://github.com/GNS3/gns3-gui/issues/2649
I already set GNS3VM IP and GNS3 Local Server IP in the same subnet but when i create vpc run on gns3vm and try to ping each other i got error ( host 192.168.10.1 not reachable)  
In same project, i've create vpc that run on local server and it's work (they can communicate)

I would thanks a lot if anyone help my problem

GNS3 version : 2.2.35.1
GNS3 VM version : 2.2.35.1
VirtualBox version : 7.0

Thanks, 
Rafi

**Comment by josephmhiggins** [comment]
what is your operating system name and version?

**Comment by grossmj** [comment]
I would recommend running everything inside the GNS3 VM

**Comment by rafiirzam** [comment]
Hi @josephmhiggins 
I'm using Windows Home 11 Version 10.022

**Comment by rafiirzam** [comment]
Hi, gross 
Thanks for your advice, yes right now im running everyting in GNS3VM
