### ISSUE TITLE
Appliance TPM InOp with swtpm version 0.8.0

### ISSUE THREAD

**Issue by Orotusso** [GNS3/gns3-gui#3488]
**Describe the bug**
When attempting to use TPM on a Windows 11 Enterprise appliance, the QEMU process exists with return code: 1. Swtpm version is 0.8.0, compiled on 20230621 from Github repo. The tmp folder supposedly containing the swtpm socket is empty. When a swtpm daemon is created manually and the appropriate flags passed to QEMU, TPM functionality is restored.

**GNS3 version and operating system (please complete the following information):**
 - OS: Client: Windows / Server: Ubuntu on Proxmox
 - GNS3 version 2.2.39

**To Reproduce**
1. Select Enable Trusted Platform Module on the appliance
2. Attempt to start appliance

**Screenshots or videos**
![image](https://github.com/GNS3/gns3-gui/assets/14371702/01447a95-9147-4ecb-8829-21cda6781c9d)

**Comment by grossmj** [comment]
> When a swtpm daemon is created manually and the appropriate flags passed to QEMU, TPM functionality is restored.

What command line do you use to run swtpm daemon?

**Comment by Orotusso** [comment]
```swtpm socket --tpm2 --tpmstate dir=/tmp/tmp.XXXXXXX/state --ctrl type=unixio,path=/tmp/tmp.XXXXXXX/swtpm.sock,terminate```

The above is what is used for the swtpm process, then disabling the TPM checkmark in appliance settings and passing the flags into QEMU through the options field

**Comment by grossmj** [comment]
Unfortunately, I cannot reproduce this issue.

**Comment by Orotusso** [comment]
Unfortunately, I no longer have access to the gns3 environment where this issue is occurring.
