### ISSUE TITLE
Cannot use a remote additional server on Azure cloud: error "Error while creating link: Cannot get an IP address on same subnet: No common subnet for compute gns3 cloud and Main server"

### ISSUE THREAD

**Issue by NeroRDC** [GNS3/gns3-gui#3494]
I have this issue with a hybrid implementation of GNS3. 

I have configured a GNS3 VM locally, a Ubuntu VM with GNS3 server installed and a Ubuntu machine on Azure. I can create links between appliances in my GNS3 VM and my Ubuntu server, and between my Ubuntu server and the Azure remote GNS3 server.

However, when creating a link between an apppliance in my Azure GNS3 server and my GNS3 VM, I am presented this error: "Error while creating link: Cannot get an IP address on same subnet: No common subnet for compute gns3 cloud and Main server".

When tshooting the connection between appliances in GNS3 VM and Ubuntu VM, it works fine. But between Ubuntu VM and Azure VM, I cannot perform a ping.

I am using a VPN, just like the documentation requires.

Can someone assist me with this issue?

**Comment by josephmhiggins** [comment]
Marc Weisel looks to have something along your lines..
He is running a gns3 vm on google and a gns3 vm on azure.
![image](https://github.com/GNS3/gns3-gui/assets/85327995/a261e6a3-04fd-4c28-abd8-fd6927deeca1)
His documentation is years old, but he is awesome.

Also microsoft has a "set up a gns3 server on azure" - but they are expecting you to use hyper-v
but it was just published 3 months ago.
https://learn.microsoft.com/en-us/azure/lab-services/class-type-networking-gns3

i may try to set something up on azure tomorrow if i can get it for free - just so I can say I did it.
the microsoft document is very new and probably will be broken a month from now - that's just the way it is with all documentation everywhere.

**Comment by WhatsTheIP** [comment]
@NeroRDC - I figured out how to resolve the issue on my end, your topology is slightly different than mine.

```
Scenerio - My goal is to access my GNS3 server located in my home network:

The server is 10.X.X.X
My client is 10.Y.Y.Y

I have a VPN setup whenever I travel I like to lab, gns3s1 is in my home network of 10.X.X.X, and my gns3s3 accesses my home network with OpenVPN:
I can ping both ways
I can ssh both ways
I can access files both ways

However, what I cannot do is launch a GNS3 template containing any resources made with gns3s1 (10.X.X.X) 

I get this error from the client machine (gns3s3):
Cannot get an IP address on same subnet: No common subnet for compute gns3s3 and gns3s1
```

Solution:
```
I created a TAP interface on gns3s3 & I changed my OpenVPN server to use TAP instead of TUN. 

TUN was causing my gns3s3 client to be on a different network, thus giving me the error:
Cannot get an IP address on same subnet: No common subnet for compute gns3s3 and gns3s1
```

On the client machine, you need to enable TAP interface:
```
sudo ip addr add 10.X.X.X/24 dev tap0
sudo ip link set tap0 up
```
