### ISSUE TITLE
Can you package a native GUI client that supports M1 chips

### ISSUE THREAD

**Issue by 2270057439** [GNS3/gns3-gui#3496]
Currently, the M1 platform client still relies on Rosetta to run. If I want to try packaging myself, what should I do?

**Comment by 2270057439** [comment]
I have tried:
`Cd gns3&&pyinstaller - D - w main.py`
But the packaged app is much smaller in size and has issues with its functionality. How should I package it correctly?

**Comment by grossmj** [comment]
> Currently, the M1 platform client still relies on Rosetta to run. If I want to try packaging myself, what should I do?

It is quite complicated to package GNS3 on macOS. Why do you need a M1 platform client vs one that relies on Rosetta?

**Comment by grossmj** [comment]
We now ship an universal app for macOS.
