### ISSUE TITLE
 name 'sys' is not defined while trying to configure vmnets in GNS3

### ISSUE THREAD

**Issue by MuhammadAbdullah54321** [GNS3/gns3-gui#3499]
- OS: Windows 11
 - GNS3 version 2.2.41

**To Reproduce**
When I go to Preferences > WMware preferences > Advanced local settings > Configure I get the error message below. 
Traceback (most recent call last):

File "gns3-gui\gns3\modules\vmware\pages\vmware_preferences_page.py", line 130, in _configureVmnetSlot

File "gns3-gui\gns3\utils\[sudo.py](https: //sudo.py/)", line 40, in sudo

NameError: name 'sys' is not defined

the same error appears when I click on reset next to configure

![image](https://github.com/GNS3/gns3-gui/assets/34376568/c976e48b-5030-4f4f-91ba-a8feb14f311f)

**Comment by josephmhiggins** [comment]
Kevin put a fix in on this 2 days ago.

**Comment by ltarrow** [comment]
I have the same issue, and I saw Kevin fix but I'm new to all this but how I set that line on the GNS3.

**Comment by josephmhiggins** [comment]
@itarrow,
we have to wait for the gns3 developers to come out with 2.2.42
or
you can install an older version.
i installed 2.2.41.
i saw kevin's fix.
i uninstalled 2.2.41
i installed 2.2.39.
it is just easier to wait for the 2.2.42

**Comment by grossmj** [comment]
You can try to download one of our nightly build: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2023-07-29/2.2/

**Comment by ltarrow** [comment]
Thank you, you guys are amazing

**Comment by defxsec** [comment]
Hola buenas buenos días, se me presento el mismo error al tratar de incluir los vmnet en GNS3
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/4f86cfb9-9ccd-4e12-9d0f-cff29add627b)
lo que hice para solucionar este problema es que en VMWare, en Edit>Virtual Network Editor>Change Settings, incluí (Add Network), tres VMnet() de Type Host-only
 
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/40fbc8c5-ee74-4027-a525-949cd7e4cecc)

y me funciono los equipos que tengo cargando en VMWare, sin embargo tengo virtualizado el Windows 11 y no levanta el sistema, 
"error while starting WINDOWS11-1: Timeout error for POST call to http://localhost:3080/v2/compute/projects/5ad4bbb2-d30e-449a-98e9-6f671e10ce21/vmware/nodes/0e787b93-db5c-4498-8b64-5ac2809aa640/start after 240s
Timeout error for POST call to http://localhost:3080/v2/compute/projects/5ad4bbb2-d30e-449a-98e9-6f671e10ce21/vmware/nodes/0e787b93-db5c-4498-8b64-5ac2809aa640/start after 240s"

**Comment by defxsec** [comment]
Según al anterior error que se me presento pude solucionar de la siguiente manera, instale Windows 11 en VirtualBox,

![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/feb192fa-9fa3-4c3f-b739-adb5ad7a7a23)
Luego añadí en GNS3 a la Maquina Virtual de Windows 11
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/9da1ebdd-2b7b-416a-ae58-8c3382851111)
Para luego incluir en la topología la maquina
![imagen](https://github.com/GNS3/gns3-gui/assets/109879632/c19628be-736c-4ab2-b3bf-ec5e11144b0b)
Como se puede ver la maquina Virtual de VirtualBox arranco sin ningún problema, al parecer el problema esta entre VMWare y GNS3 que no logra levantar la maquina Virtual de Windows 11.
