### ISSUE TITLE
GNS3 shows a generic icon in wayland (kde plasma)

### ISSUE THREAD

**Issue by txutxifel** [GNS3/gns3-gui#3501]
**Before you start**
Maybe Its not an error on GNS3, It could be an error in python-qt5 o Wayland.
Maybe the following link can help

https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

**Describe the bug**
Gns3 shows a generic icon in Wayland (no X11)

**GNS3 version and operating system (please complete the following information):**
 - OS: Opensuse (Linux) 15.4
 - GNS3 version 2.2.41
 - Local GNS3 Server

**To Reproduce**
1. Open GNS3 in Wayland (KDE)
2. Icon is showed

**Screenshots or videos**
![imagen](https://github.com/GNS3/gns3-gui/assets/4577294/694ad488-c6fb-4069-acef-570156d6c90c)

**Comment by grossmj** [comment]
Thanks, how have you installed GNS3?

**Comment by txutxifel** [comment]
hi,
I have installed GNS3 via pip->

python3 -m pip install --upgrade --force-reinstall gns3-server
python3 -m pip install --upgrade --force-reinstall gns3-gui

**Comment by grossmj** [comment]
Thanks, looks like this is a known issue: https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

Looks like we have to do use something like `QGuiApplication::setDesktopFileName("org.gns3.app")` in our GUI.

**Comment by grossmj** [comment]
This should have been fixed in the previous version (v.2.2.43): https://github.com/GNS3/gns3-gui/commit/7f6cace0d5fa3491968203529d293b29d99a1ad4

Please let me know if it sill doesn't work. Thanks 👍
