### ISSUE TITLE
Add Kitty to console programs

### ISSUE THREAD

**Issue by procobain** [GNS3/gns3-gui#3507]
kitty -title %d telnet://%h %p

**Comment by grossmj** [comment]
Looks like we already have KiTTY support: https://github.com/GNS3/gns3-gui/blob/2.2/gns3/settings.py#L163

What version of GNS3 do you use?

**Comment by grossmj** [comment]
@procobain ?

**Comment by procobain** [comment]
![gns3_tL9xg3AIwT](https://github.com/GNS3/gns3-gui/assets/31631530/e3ded2e3-7514-43af-bc05-1ccaea35c10a)
![gns3_QNvMnL8BtT](https://github.com/GNS3/gns3-gui/assets/31631530/f3e1dca1-0e3f-460f-8b8c-08ae3cfce0fa)

**Comment by grossmj** [comment]
KiTTY has been added. Thanks.

**Comment by procobain** [comment]
> KiTTY has been added. Thanks.

We appreciate it, thank you very much!
