### ISSUE TITLE
PPA Missing dependency | ModuleNotFoundError: No module named 'platformdirs'

### ISSUE THREAD

**Issue by LespiletteMaxime** [GNS3/gns3-gui#3510]
**Describe the bug**
The upgrade for GNS 2.2.43 from the PPA has a missing dependency 

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux Mint 21.2
 - GNS3 version 2.2.43

**To Reproduce**
Upgrade to 2.2.43 from the PPA

**FIX**
I fix the problem with `sudo apt install python3-platformdirs`

**Comment by grossmj** [comment]
Thanks for catching this. We have fixed the problem and pushed a new package: `2.2.43~focal2`

Please let me know if you still have an issue.
