### ISSUE TITLE
Qemu IGB network device

### ISSUE THREAD

**Issue by ventaquil** [GNS3/gns3-gui#3513]
Since version 8.0 [IGB device](https://www.qemu.org/docs/master/system/devices/igb.html) is available in Qemu (see [changelog](
https://wiki.qemu.org/ChangeLog/8.0#Network_devices)).

```shell
$ qemu-system-x86_64 --version
QEMU emulator version 8.1.1 (v8.1.1)
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
$ qemu-system-x86_64 -nic user,model=help
Available NIC models:
e1000
e1000-82544gc
e1000-82545em
e1000e
i82550
i82551
i82557a
i82557b
i82557c
i82558a
i82558b
i82559a
i82559b
i82559c
i82559er
i82562
i82801
igb
ne2k_pci
pcnet
rtl8139
tulip
virtio-net-pci
virtio-net-pci-non-transitional
virtio-net-pci-transitional
vmxnet3
```

As far as I see it shouldn't be difficult to add it, right?

https://github.com/GNS3/gns3-gui/blob/a9890265b99f26bccb6ca13ea7a945e961777e69/gns3/modules/qemu/pages/qemu_vm_configuration_page.py#L103-L130

In comparison to `e1000`/`e1000e` it supports multi queues.

**Comment by ventaquil** [comment]
Hey @b-ehlers

I prepared PR already, it works quite fine on my setup. It doesn't need any changes in server code, however I agree that changes in other repos should be next step.

First attempt to test IGB driver was quite simple - just replacement `e1000` into `igb` in my project file. Finally everything worked as expected - excluding that used network interface driver was empty (that should be fixed?).

Regarding to older Qemu version that someone may use - maybe additional information (like minimal supported Qemu version - MSQV) should be added to the list of available drivers.

IGB driver is much more powerful than any existing Intel drivers - I cannot run application by using any of existing ones because of single queue. IGB supports multi queues and for me it's must have feature. For other users maybe too.

**Comment by ventaquil** [comment]
Hey @grossmj

Is there any chance to add this change to the 3.0.0 release?

**Comment by grossmj** [comment]
Hi,

Yes I think we should add it to 3.0 :+1:

**Comment by grossmj** [comment]
I have decided to add this to 2.2 (and it will make its way to 3.0 as well). Also, I have updated the registry: https://github.com/GNS3/gns3-registry/pull/836 to support this new adapter.

> A drawback of your changes is, that a user with an older qemu, who tries to use the IGB device, gets a strange error message. That might lead to some confusion. Maybe this situation needs some extra handling.

This is definitely something to improve. The only way I know to get a list of supported devices is to execute Qemu with the `-device help` param and there is some parsing to do. I wish Qemu would make it easier to know what devices are supported... I guess we could work on this after v3.0.

> Regarding to older Qemu version that someone may use - maybe additional information (like minimal supported Qemu version - MSQV) should be added to the list of available drivers.

That could be a way to mitigate the problem in the meantime.

**Comment by ventaquil** [comment]
> This is definitely something to improve. The only way I know to get a list of supported devices is to execute Qemu with the -device help param and there is some parsing to do. I wish Qemu would make it easier to know what devices are supported... I guess we could work on this after v3.0.

In theory, we can simply review the changes in Qemu's changelog to determine when each network device was introduced.

Using `-nic model=help` is necessary solely for dynamically updating the list of available NIC devices without hardcoding them into the code.

@grossmj, please note that `-nic model=help` is significantly easier to parse (just skip the first line) compared to `-device help`.

**Comment by grossmj** [comment]
> @grossmj, please note that -nic model=help is significantly easier to parse (just skip the first line) compared to -device help.

Thanks, based on this we will improve the whole process in a future version without hard-coded adapter names.
