### ISSUE TITLE
Feature Request - New variable in Packet Capture (and console) Preferences to hold the project name.

### ISSUE THREAD

**Issue by Pcrossley69** [GNS3/gns3-gui#3517]
The preferences section for Console Applications currently  allows the use of variables:
%h (host) %p (port)  %d (Console title)  %i Project UUID)  %n ( Node UUID) and %c (Server URL)

The preferences section for Packet Capture only shows support for %c (Capture File) in point help
but  %d is used in the window title to describe the capture location.

-o "gui.window_title:%d"

I propose that another variable (%P or %T) should be available on both Console Applications and Packet Capture  to contain the project name (as set in FILE->Edit Project).

This would be a useful addition to the wireshark command line
--capture-comment "%P %d"

The capture comment is saved in the pcapng  capture file properties 
This would be very useful for record keeping.

**Comment by grossmj** [comment]
Implemented, thanks.
