### ISSUE TITLE
Add option for disable or skip Cannot start VM because hardware virtualization technology is already used by another software

### ISSUE THREAD

**Issue by Mario156090** [GNS3/gns3-gui#3521]
Hello dear GNS3 development team,

In some hardware, as ryzen amd-v technology is possible start two virtualization technology on same time.

So, I believe we need an option for disable the message in the picture and GNS3 try start the VMs.

![image](https://github.com/GNS3/gns3-gui/assets/47507975/4a02b9ca-8dec-4b24-81f9-5db5b32b8ddc)

**Comment by grossmj** [comment]
Thanks, have you tried to start both a VMware VM and a VirtualBox or KVM VM?

**Comment by Mario156090** [comment]
> Thanks, have you tried to start both a VMware VM and a VirtualBox or KVM VM?

Hello @grossmj  I tried to start Vmware Workstation and Cisco IosV at same time, so this is possible from GNS3 only if you press the play every nodes at same time. But if you use for example 4 or more nodes with differents technologys GNS3 show the message on top thread, but if you turn on QEMUKVM from GNS3 and turn on Vmware VM from vmware workstation control panel you can got on both technologys.

**Comment by grossmj** [comment]
Thanks, I think we should probably remove this check altogether.

**Comment by grossmj** [comment]
This was already removed from our 3.0 branch, I just added the option to disable it in 2.2. Edit `gns3_server.conf` and add `hardware_virtualization_check = False` to the file.

Example:

```
[Server]
; check if hardware virtualization is used by other emulators (KVM, VMware or VirtualBox)
hardware_virtualization_check = False
```
