### ISSUE TITLE
Port name inconsistency when adding new links for a device (GNS3 3.0.0dev8)

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3522]
After adding an device and trying to right click on the device to add some link the ports names defined in the template does not match as the one shown in the dropdown menu

Environment details:
OS: ArchLinux
GNS3 version: 3.0.0dev8
Python 3.11

1. Drag a new device on the topology.
2. Click on the Add a link button from the toolbar on the left hand side.
3. Click on the device to add a new link. The drop-down menu pops up and the port names are inconsistent as shown in the below screenshots (all are named Ethernet followed by the port number).

![gns3_port_numbering_01](https://github.com/GNS3/gns3-gui/assets/7124193/18c8d7a8-1f13-4f53-9c47-4b4a41e1d9a1)
![gns3_port_numbering_02](https://github.com/GNS3/gns3-gui/assets/7124193/db7220f9-dadd-4124-971e-7a73f7b817f1)

**Additional context**
Tested on multiple devices and behavior is the same. Only the First port name if defined is shown correctly.

**Comment by grossmj** [comment]
Fixed, thanks for catching this 👍
