### ISSUE TITLE
GNS3 not available in Ubuntu 23.10 PPA

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#3525]
Basically title, it would be great to have GNS3 installed natively with apt. 

As per official install docs:
https://docs.gns3.com/docs/getting-started/installation/linux/
https://launchpad.net/~gns3/+archive/ubuntu/ppa

**Comment by grossmj** [comment]
Hi @sliddjur 

I have pushed packages for Ubuntu 23.10: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=mantic

**Comment by sliddjur** [comment]
@grossmj just fyi:  gns3-webclient-pack - 1.0.0b4~mantic1 this has failed to build.

**Comment by grossmj** [comment]
> @grossmj just fyi: gns3-webclient-pack - 1.0.0b4~mantic1 this has failed to build.

Fixed, thanks :)
