### ISSUE TITLE
Cannot change default VLAN for an access port for builtin Ethernet switch (GNS3 3.0.0 alpha 4)

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3528]
Describe the bug
Cannot change default VLAN of an access port for builtin Ethernet switch (GNS3 3.0.0 alpha 4)

GNS3 version and operating system (please complete the following information):

OS: ArchLinux
GNS3 version: 3.0.0 alpha 4
GNS3 server and GUI are running on same machine (bare metal)
Python version: 3.11 (Pydantic 2.0.3)
To Reproduce

1. Drag a builtin Ethernet switch from All devices list on the topology and then right click on the device and choose Configure
2. Select one existing access port and change default VLAN 1 to a different VLAN (100 for example) in the VLAN field
3. Click Add and the Apply to update the modification.
4. A popup error is being displayed with HTTP error 422 received.

I compared it version 2.2.x and I see the Ethertype field is prefilled with value 0x8100 in version 3.0.0 and and 2.2.x there is no value for Ethertype specified for each port.

**Screenshots or videos**

![gns3_switch_vlan_01](https://github.com/GNS3/gns3-gui/assets/7124193/b69ce593-db21-4d70-9df7-cf8dfcf57008)
![gns3_switch_vlan_02](https://github.com/GNS3/gns3-gui/assets/7124193/14ad190f-5590-4729-b9f4-d435143c3214)

**Additional context**
I see the validation for the ports on the builtin switch is being done here https://github.com/GNS3/gns3-server/blob/3.0/gns3server/schemas/compute/ethernet_switch_nodes.py

**Comment by grossmj** [comment]
Thanks, this should be fixed now.
