### ISSUE TITLE
GNS3 v3.0.0a5 VMware OVA Feedback. Long Boot Time. Permission Warnings when changing from DHCP to static IP

### ISSUE THREAD

**Issue by mc1903** [GNS3/gns3-gui#3530]
Compared to the current release v2.2.43 OVA, the boot time for the v3.0.0a5 OVA on the same ESXi hardware, is considerably longer.

v2.2.43 boot time from VM power on to the blue menu screen is approx 30 seconds
v3.0.0a5 boot time from VM power on to the blue menu screen is approx 3 minutes 10 seconds.

When changing from DHCP to static IP there are several permissions warnings shown just before the VM reboots. I have captured them on a recording here https://youtu.be/Ia0SBDKlU44 at 0:51.

Also the boot time after changing to a static IP increases to approx 4 minutes 20 seconds.

**Comment by grossmj** [comment]
Hi,

Please can you try to disable cloud-init? All you have to do is type this command: `sudo touch /etc/cloud/cloud-init.disabled`

Let me know if this solves the slow boot time.

Thanks.

**Comment by mc1903** [comment]
Hello Jeremy,

Yes, disabling cloud-init has resolved the slow boot time.  VM power on to the blue menu screen is approx 35 seconds now.

Many Thanks
M
