### ISSUE TITLE
Failed Update Ubuntu Docker Guest

### ISSUE THREAD

**Issue by kezzchr34** [GNS3/gns3-gui#3532]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**

    OS: [Windows 10 Pro]
    GNS3 version [3.0.0.5a]
    Any use of the GNS3 VM or remote server (GNS3 VM - VMware Workstation Pro 17.5.0)

**To Reproduce**
1. Right Click > select Console
2. nano /etc/network/interfaces
3. Uncomment # auto eth0
4. Uncomment # iface eth0 inet dhcp
5. CTRL X and save using defaults 
6. Enter apt-get update 
![DHCP_Ubuntu_Docker_Guest](https://github.com/GNS3/gns3-gui/assets/117614880/3fda603a-8c5d-4c19-a367-1a514584cdb9)
![failed_Update_Ubuntu_Docker_Guest](https://github.com/GNS3/gns3-gui/assets/117614880/1b8cad9a-beaf-455b-9cbf-e44ff34ea7c5)
![Topology2](https://github.com/GNS3/gns3-gui/assets/117614880/fd769a7f-5e5e-4033-a754-14b64c204356)

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

**Comment by grossmj** [comment]
Do you have the same issue with GNS3 v2.2.x?

**Comment by kezzchr34** [comment]
NO. Work fine on GNS3 2.2.44.1.

Kerry Christie
Information Technology Professional, Network Engineer
CCIE (Written),CCNA,CCNP,CCNA Voice, A+, Linux+, LPIC-1
Training - CCIE R&S, VMware vSphere VCP-DCV, LPIC-2
________________________________

**Comment by grossmj** [comment]
Sorry, I couldn't reproduce the issue. Please can you try with a simple topology on your side?

![Screenshot from 2023-11-12 12-06-14](https://github.com/GNS3/gns3-gui/assets/4752614/65b715f2-40f6-40e6-b028-bbb9e81adb0b)

![Screenshot from 2023-11-12 12-06-42](https://github.com/GNS3/gns3-gui/assets/4752614/50baa8bf-93cb-4927-967c-31ea06eeeffe)

Thanks :)

**Comment by kezzchr34** [comment]
I've solve the issue with regarding , by uninstalling docker and reinstalling the application.


  *    --- sudo apt remove docker-ce runc
  *   --- sudo apt install docker-ce
  *   --- restart gns3 (ok)

Kerry Christie
Information Technology Professional, Network Engineer
CCIE (Written),CCNA,CCNP,CCNA Voice, A+, Linux+, LPIC-1
Training - CCIE R&S, VMware vSphere VCP-DCV, LPIC-2
________________________________

**Comment by grossmj** [comment]
Ok, sounds good 👍 thanks.
