### ISSUE TITLE
Feature Request: Key modifier to ignore snap to grid

### ISSUE THREAD

**Issue by micush** [GNS3/gns3-gui#3538]
It would be great to be able to hold down a key [ctrl/shift/alt/etc] in order to be able to freely drag an item around a grid without snapping to it. Putting text boxes near a node with snap to grid on doesn't allow for fine grained movement to get the box where you want it.

**Comment by grossmj** [comment]
> It would be great to be able to hold down a key [ctrl/shift/alt/etc] in order to be able to freely drag an item around a grid without snapping to it. Putting text boxes near a node with snap to grid on doesn't allow for fine grained movement to get the box where you want it.

I have added this behavior by holding ALT. Thanks 👍
