### ISSUE TITLE
bug startup-config when rename IOS Cisco

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#354]
Hi

When i put on the topology an cisco router (C3725) and i start it, there is no problem

If i put the same router but i rename it "FRSW" (for example) before to start it, it don't launch the startup-config but ask "Would you like to enter the initial configuration dialog? [yes/no]:"
I have also this messages :
Original NVCONFIG doesnt have correct MAGIC number
Backup NVCONFIG also doesnt have correct MAGIC number

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/dd9f62158fbd2a8deca149380d12b5268e39a4fa

Thanks! :+1:
