### ISSUE TITLE
Latest version of GNS3 2.2.44.1 for macOS is flagged by Virus Total security vendors.

### ISSUE THREAD

**Issue by paul-cossey** [GNS3/gns3-gui#3540]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Hi, folks 

Not sure where else to raise this, so apologies if it's not the correct channel. 

I think these are false positives, but the latest version of latest version of `GNS3 2.2.44.1` for macOS is being flagged by Virus Total security vendors.

The downloaded DMG is flagged by 2 vendors: https://www.virustotal.com/gui/file/1abd8911265d4f70c1387a74038629b47569ca583cad6b44c765adf5e78b22d9 

The App bundle is flagged by 4 vendors: https://www.virustotal.com/gui/file/6a87592c8b3e43a4cb305f052923641063f3e18733b4ca73c74fd5ba4f1f7f63

You may wish to work with the vendors in question to resolve this. 

Thanks!

**GNS3 version and operating system (please complete the following information):**
 - OS: `macOS`
 - GNS3 version: `2.2.44.1`
 - Any use of the GNS3 VM or remote server: `N/A`

**To Reproduce**
1. Go to 'Download page'
2. Click on 'Download latest version'
3. Upload to 'www.virustotal.com'
4. See error: https://www.virustotal.com/gui/file/1abd8911265d4f70c1387a74038629b47569ca583cad6b44c765adf5e78b22d9 and https://www.virustotal.com/gui/file/6a87592c8b3e43a4cb305f052923641063f3e18733b4ca73c74fd5ba4f1f7f63

**Screenshots or videos**
N/A

**Additional context**
N/A

**Comment by grossmj** [comment]
Indeed, this looks like false positives.

**Comment by paul-cossey** [comment]
Hi, folks 

This cleared up with the latest release, but now the latest version is being flagged by two vendors on VirusTotal:

- https://www.virustotal.com/gui/file/2decd3626a0151ace2a6b89ee40a1b19857e08e25755e5d99685fe069e4165f6/detection 

The App Bundle is only flagged by one vendor: 

- https://www.virustotal.com/gui/file/b261336424a392cb79cd1ff803fc94c52050ac69d1deabfc6dfc226ef78cc165?nocache=1

The download URL is coming up clean: 

- https://www.virustotal.com/gui/url/1ad2999ae06f660c06ae2367e1a56ec7ad557c1957b9b92a14721963cf1aa5bc

Looks like false positives again, but possibly worth trying to working with the vendors to stop these detections. 

Thanks!

**Comment by grossmj** [comment]
> Looks like false positives again, but possibly worth trying to working with the vendors to stop these detections.

Indeed however unfortunately we don't really have much time to work with the vendors.

**Comment by paul-cossey** [comment]
We've not had any VT alerts for a while now. Closing
