### ISSUE TITLE
gns3 v2.2.43，无法在win7 sp1上面启动

### ISSUE THREAD

**Issue by wwxlll** [GNS3/gns3-gui#3541]
GNS3 版本：GNS3 v2.2.43

操作系统： Windows 7

首次启动提示没有：api-ms-win-core-path-l1-1-0.dll

然后下载dll后移动到system32目录

然后报错，应用程序无法启动：0xc000007b错误代码

然后使用denpendency Warlker补全了缺少的dll

在cmd中启用还是报错
![image](https://github.com/GNS3/gns3-gui/assets/104618660/84ceed69-1ac9-40fa-a753-450ee3c453db)

**Comment by grossmj** [comment]
Do you have Python installed somewhere on your system? Have you tried GNS3 v2.2.45? Thanks.

**Comment by suzengyi** [comment]
我把这个dll文件放到GNS3安装目录里就能用了
(I fix this problem by putting this dll file in GNS3 install path)
https://github.com/nalexandru/api-ms-win-core-path-HACK

**Comment by wwxlll** [comment]
> 我把这个dll文件放到GNS3安装目录里就能用了 (I fix this problem by putting this dll file in GNS3 install path) https://github.com/nalexandru/api-ms-win-core-path-HACK

这个文件怎么编译，有没有现成的

**Comment by wwxlll** [comment]
> Do you have Python installed somewhere on your system? Have you tried GNS3 v2.2.45? Thanks.

有Python环境，新版本都不支持win7

**Comment by suzengyi** [comment]
> > 我把这个dll文件放到GNS3安装目录里就能用了 (I fix this problem by putting this dll file in GNS3 install path) https://github.com/nalexandru/api-ms-win-core-path-HACK
> 
> 这个文件怎么编译，有没有现成的

项目的Release里就有编译好的

**Comment by wwxlll** [comment]
> > > 我把这个dll文件放到GNS3安装目录里就能用了 (I fix this problem by putting this dll file in GNS3 install path) https://github.com/nalexandru/api-ms-win-core-path-HACK
> > 
> > 
> > 这个文件怎么编译，有没有现成的
> 
> 项目的Release里就有编译好的

没找到呀，可以给个截图吗谢谢啦

**Comment by wwxlll** [comment]
> > > 我把这个dll文件放到GNS3安装目录里就能用了 (I fix this problem by putting this dll file in GNS3 install path) https://github.com/nalexandru/api-ms-win-core-path-HACK
> > 
> > 
> > 这个文件怎么编译，有没有现成的
> 
> 项目的Release里就有编译好的

找到了，我去试一下谢谢啦

**Comment by wwxlll** [comment]
> 我把这个dll文件放到GNS3安装目录里就能用了 (I fix this problem by putting this dll file in GNS3 install path) https://github.com/nalexandru/api-ms-win-core-path-HACK

是了64和32的都不行呀，放到gns3目录了，可以提供一个可以使用的目录压缩包吗

**Comment by wwxlll** [comment]
![image](https://github.com/GNS3/gns3-gui/assets/104618660/f65f056d-3ea1-4186-bfc6-26d8a43c1673)

**Comment by suzengyi** [comment]
> ![image](https://private-user-images.githubusercontent.com/104618660/313634253-f65f056d-3ea1-4186-bfc6-26d8a43c1673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTI0MzYsIm5iZiI6MTcxMDgxMjEzNiwicGF0aCI6Ii8xMDQ2MTg2NjAvMzEzNjM0MjUzLWY2NWYwNTZkLTNlYTEtNDE4Ni1iZmM2LTI2ZDhhNDNjMTY3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzBlNjY0MDVhYmI2MGVjNjhhMzdiOGFhMWZhMGQyMzg5NTI1NjhiMDg3NTBmM2YzMWY1MjhlOGRhYTcxNzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KufnaLPdcj4PdpxmQNVGRaleVy4UrRRSE3AWwIqRMrs)

你这报错是少python3.dll，api-ms-win-core-path-l1-1-0.dll文件位置没错

**Comment by wwxlll** [comment]
> > ![image](https://private-user-images.githubusercontent.com/104618660/313634253-f65f056d-3ea1-4186-bfc6-26d8a43c1673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTI0MzYsIm5iZiI6MTcxMDgxMjEzNiwicGF0aCI6Ii8xMDQ2MTg2NjAvMzEzNjM0MjUzLWY2NWYwNTZkLTNlYTEtNDE4Ni1iZmM2LTI2ZDhhNDNjMTY3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMTM1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzBlNjY0MDVhYmI2MGVjNjhhMzdiOGFhMWZhMGQyMzg5NTI1NjhiMDg3NTBmM2YzMWY1MjhlOGRhYTcxNzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KufnaLPdcj4PdpxmQNVGRaleVy4UrRRSE3AWwIqRMrs)
> 
> 你这报错是少python3.dll，api-ms-win-core-path-l1-1-0.dll文件位置没错

有python3的dll，这个好像是提示无法加载，应该是python310的版本不支持win7

**Comment by weiqi-chen** [comment]
Windows 7 已经不支持超过Python 3.8.x或以上版本了。我目前暂时判断到gns-2.2.23-all-in-one版本还可以用。大家也可以试试看。希望官网文档里边添加说明，让大家不要找得那么辛苦。

Windows 7 no longer supports Python version 3.8.x or higher. I have noticed that the gns-2.2.23-all-in-one version is still usable for now. Others can give it a try as well. I hope the official documentation can add a note about this so people can easily find a version suitable for Windows 7.
