### ISSUE TITLE
Appliance upload stuck at 2% (13 MB)

### ISSUE THREAD

**Issue by ventaquil** [GNS3/gns3-gui#3543]
I am using the newest version (3.0.0a5) of GUI and server.

I am running GUI on Windows 10 and server on Ubuntu 20.04 - remote server was configured as main and only server.

During upload of large file I see log on server side that file is already uploading

```
2023-11-03 10:35:02 INFO gns3server.utils.images:325 Writing image file to '/tmp/gns3/images/debian-12-amd64.qcow2'
```

When I checked size of `/tmp/gns3/images/debian-12-amd64.qcow2.tmp` it shows `13M`

```shell
$ du -h /tmp/gns3/images/debian-12-amd64.qcow2.tmp
13M     /tmp/gns3/images/debian-12-amd64.qcow2.tmp
```

Tried upload smaller files (about 300 KB) as well and works as expected.

**Comment by grossmj** [comment]
This should have been solved in beta 1, please can you confirm? thanks 👍

**Comment by cristian-ciobanu** [comment]
I just tested on 3.0.0 beta 1 and it works fine without any progress information being reported.
Is this only a workaround until a proper solution will be implemented ?
Thanks,

**Comment by grossmj** [comment]
> Is this only a workaround until a proper solution will be implemented ?

Yes this is a workaround 👍

**Comment by ventaquil** [comment]
Sorry for late reply, had Christmas vacations during December.

3.0.0 Beta 1 works fine, thanks for fix @grossmj!
