### ISSUE TITLE
NO IP Address GNS3 Docker Containter Web-GUI, IOU License File Location 

### ISSUE THREAD

**Issue by kezzchr34** [GNS3/gns3-gui#3545]
**Describe the bug**
GNS3 Ubuntu Docker Guest & Toolbox does not receive an IP address via dhcp when using the GNS3 Web UI © 2022 - v3.0.0b1.

**GNS3 version and operating system (please complete the following information):**
 - OS:  Windows 10 Pro Version 22H2 OS Build: 19045.3693
 - Processor: Intel(R) Core(TM) i7-9750H
 - GNS3 3.0.0b1
 - VMware Workstation 17 Pro Version 17.5.0 build-22583795
 - Any use of the GNS3 VM 

**To Reproduce**
1. Select item in the Web UI
2. Click on 'Toolbox-1' > select Web console (cannot connect to securecrt using web gui)
3. Configure config using nano /etc/network/interfaces; then stop the appliance and start the appliance
4. Open again using web console, then use ifconfig to view dhcp address received

![IOU License](https://github.com/GNS3/gns3-gui/assets/117614880/15d338d9-0706-4710-b264-6a837ed21b90)
![Toolbox_before_dhcp](https://github.com/GNS3/gns3-gui/assets/117614880/73068a10-bb72-4917-bc55-4bb9833c3767)
![Toolbox_dhcp_config](https://github.com/GNS3/gns3-gui/assets/117614880/48f5b9ac-70c9-409b-9971-511e96b63870)
![Topology1](https://github.com/GNS3/gns3-gui/assets/117614880/c2fbcd67-84b6-4fbc-b0fc-6b0275981367)

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**
![Toolbox_before_dhcp](https://github.com/GNS3/gns3-gui/assets/117614880/765ba9f5-2f8c-4d1d-86c6-c30401fc9a1d)

**Comment by grossmj** [comment]
Did you see the Docker container sending DHCP packets?

![Image](https://github.com/GNS3/gns3-gui/assets/4752614/0a6d9369-06ac-4f72-bb8f-c152b579a2ac)
