### ISSUE TITLE
Unable to install guest image on 3.0.0b1: Image already exists

### ISSUE THREAD

**Issue by fernandolcx** [GNS3/gns3-gui#3546]
I'm using GNS3 VM, trying to upload .img files for Ubuntu 23.04.

It's stuck in a loop, keeps uploading files and throwing this error

![image](https://github.com/GNS3/gns3-gui/assets/38504809/5b1e50b6-ada6-43a3-998a-a50af7114005)

**Comment by grossmj** [comment]
I couldn't reproduce the issue:

![Screenshot from 2023-12-07 21-12-42](https://github.com/GNS3/gns3-gui/assets/4752614/a242e55d-acb4-42d8-9fce-9e49ffdc94da)

Do you have this problem with any image?

Have you tried to delete the image from the image manager first?

![Screenshot from 2023-12-07 21-13-25](https://github.com/GNS3/gns3-gui/assets/4752614/cc0db84a-be63-4dff-b6f5-5dc303a39289)

Thanks 👍

**Comment by grossmj** [comment]
Fixed.
