### ISSUE TITLE
GNS3 GUI v 2.2.44.1 not starting  packet capture on Mac OS Sonoma 14.2 update

### ISSUE THREAD

**Issue by cantek86** [GNS3/gns3-gui#3548]
Looks like there may be an issue where the gui doesn't actually start the packet capture with the new Mac OS update. I am running the 2.2.44.1 GNS3 VM and GUI on Mac OS 14.2.  I have reinstalled both wireshark and the GNS3 gui app with no resolution.
 
![Screenshot 2023-12-15 at 2 02 56 PM](https://github.com/GNS3/gns3-gui/assets/22175402/a094f74d-7bbc-4485-a702-e5c2b606c321)

When staring a capture on a link Wireshark opens but then shows its ready to load a file or capture, not that its actually capturing traffic. 

Then when you go to stop the capture in GNS3 you get an error stating "This link has no active packet captures". 

![Screenshot 2023-12-15 at 2 01 45 PM](https://github.com/GNS3/gns3-gui/assets/22175402/dfe992b3-6e96-489c-91ab-db82240d2927)

**Comment by grossmj** [comment]
Was it working before you upgraded macOS?

**Comment by cantek86** [comment]
Yes packet capturing was working prior to the upgrade.

**Comment by grossmj** [comment]
I ran some tests on macOS Sonoma 14.2 and couldn't find any issue with packet capture.

![Screenshot from 2023-12-18 20-15-41](https://github.com/GNS3/gns3-gui/assets/4752614/6bb18e84-8b0f-43bd-acd5-35f61ab1beb3)

**Comment by cantek86** [comment]
I'm migrating my data over to a new GNS3 VM and seeing if that resolves the issue then.

**Comment by cantek86** [comment]
Is this what you have in your packet capture preferences? 

tail -f -c +0 %c | /Applications/Wireshark.app/Contents/MacOS/Wireshark -o "gui.window_title:%d" -k -i -

**Comment by cantek86** [comment]
I have found that GNS3 is capturing packets I think there is something going on with my mac and WireShark. Sorry for the rabbit hole.
