### ISSUE TITLE
Toolbar missing from desktop gui

### ISSUE THREAD

**Issue by jlimbo987** [GNS3/gns3-gui#3549]
GNS3 Version: GNS3 v2.2.44.1

Operating System: Linux Mint

I've recently moved from Windows to Linux and as is my usual practice I undocked all panels to move them to a separate moniotr. The next time I opened the gui, the panel on the left of the canvas that includes the icons for routers, switched, end devices, security devices, all devices and add a link, is now missing. I still have the 'All templates' panel undocked, but I have no way of connecting devices. See attached image

![Screenshot from 2023-12-15 10-50-02](https://github.com/GNS3/gns3-gui/assets/26226541/45181312-59e5-4606-95c9-34a5afc1e8d4)

**Comment by grossmj** [comment]
Have you tried "View" -> "Reset docks"?

**Comment by jlimbo987** [comment]
Hi Jeremy,

Yes, I did, that screenshot was taken just after I did that.

**Comment by jlimbo987** [comment]
Any update on this?

I've tried to uninstall and reinstall, but that's not solved the problem. I've now got version 2.2.45. I also tried to update the server (running on dedicated box) but according to apt I have the latest version already (2.2.44). The version mismatch means I can't use the server. Can you please make 2.2.45 available via apt

**Comment by cristian-ciobanu** [comment]
@jlimbo987 which distro are you running and which version ?
I see on the GNS3 PPA the version 2.2.45 for both GUI and server are available for installation via apt. https://launchpad.net/~gns3/+archive/ubuntu/ppa

**Comment by jlimbo987** [comment]
Distro is Mint 21.2

Just tried the server update again. Output below

`root@sm0:~# apt update
Hit:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                                                
Hit:3 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                              
Hit:4 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease                                                                                                        
Hit:5 http://ppa.launchpad.net/gns3/ppa/ubuntu focal InRelease                                                                                                            
Hit:6 https://download.docker.com/linux/ubuntu focal InRelease                                                                                      
Ign:7 https://download.webmin.com/download/newkey/repository stable InRelease                                                 
Hit:8 https://download.webmin.com/download/newkey/repository stable Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@sm0:~# apt-get -y install gns3-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gns3-server is already the newest version (2.2.44.1~focal1).
The following packages were automatically installed and are no longer required:
  docker-scan-plugin libfwupdplugin1 libxmlb1
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.`

**Comment by cristian-ciobanu** [comment]
Just took a closer look at the PPA repository and it seems the build for gns3-server 2.2.45 version specific to Ubuntu focal release which is used by Linux Mint has failed

https://launchpad.net/~gns3/+archive/ubuntu/ppa/+build/27637879

If the build had been successful you should normally see some output like below on the above link but the output is empty

**Built files
Files resulting from this build:
gns3-server_2.2.45~mantic1_amd64.deb**

@grossmj needs to restart the build process and check why it failed

**Comment by grossmj** [comment]
Correct, there is a problem for building for focal: https://launchpad.net/~gns3/+archive/ubuntu/ppa/+builds?build_text=&build_state=all

I haven't found what is the reason yet.

**Comment by grossmj** [comment]
> @grossmj needs to restart the build process and check why it failed

All good now, focal packages have been successfully built.

**Comment by jlimbo987** [comment]
Thanks, upgrade is complete and working. Any fix for my missing buttons?

**Comment by grossmj** [comment]
I am not sure how you managed to have this toolbar missing. One possible workaround is to delete the geometry and state lines found in the `~/.config/GNS3/2.2/gns3_gui.conf` file then start the GUI again.

![Image](https://github.com/GNS3/gns3-gui/assets/4752614/49c8c8cd-f724-467a-8b0e-cc0557ef68fd)

![Image](https://github.com/GNS3/gns3-gui/assets/4752614/3a5e987e-ab6c-41cf-9631-542c3d6262a0)

The toolbar is indeed not in the "View -> Docks" menu, I will add it.

**Comment by grossmj** [comment]
I have added "View -> Reset GUI state" that will be available in the next release. This should fix the problem. Thanks 👍

**Comment by jlimbo987** [comment]
Thanks Jeremy, that's fixed it.

Just a heads up though, when I restarted GNS3, it emptied my project directory. Fortunately I'd backed it up elsewhere so a quick fix. When you add the reset feature, assuming it's a button that edits the config file to remove those 2 lines, just test that it doesn't do the same

Thanks again
