### ISSUE TITLE
Custom Qemu binary in Advanced tab

### ISSUE THREAD

**Issue by ventaquil** [GNS3/gns3-gui#3553]
In 2.x versions custom Qemu binary could be set to override system default (like custom build or newer version than available by package manager).

Version 3.0.0 Beta 1 makes this override impossible. I appreciate the simplicity to select desired platform but for more advanced users with less straightforward scenarios this override could be must-have feature. 

![Node properties | Advanced tab](https://github.com/GNS3/gns3-gui/assets/10523774/ca3db402-815f-44ee-b78c-32c4a95b1c32)

**Comment by cristian-ciobanu** [comment]
@ventaquil with this screenshot you mean to specify the path to another qemu binary in the options box ? 

The current screenshot is not very conclusive of what are you trying to achieve.

There is another issue opened https://github.com/GNS3/gns3-gui/issues/3048 which might be related to the problem you are experiencing.

**Comment by ventaquil** [comment]
@cristian-ciobanu 

In 2.x versions you could specify the full path of Qemu binary.

![Qemu binary full path](https://github.com/GNS3/gns3-gui/assets/10523774/200529ff-c03d-438f-85ec-2b98f8869891)

As you can see I am using `/usr/local/bin` with custom build instead of `/usr/bin` provided by OS package manager.

I totally understand the simplicity of changing the idea in 3.x so you can choose architecture instead of binary but in more advanced scenarios it's necessary to manually choose which binary I prefer.

**Comment by grossmj** [comment]
> I totally understand the simplicity of changing the idea in 3.x so you can choose architecture instead of binary but in more advanced scenarios it's necessary to manually choose which binary I prefer.

We could add a custom binary field to override what binary the GNS3 server picks. It won't be a drop down list to choose from though.

**Comment by ventaquil** [comment]
It doesn't need to be a drop down list - I can pick a binary from some file-system picker (I don't know the name of that dialog window) or I can write the path manually.

In older system (which I cannot upgrade) I have newer version of Qemu in `/usr/local/bin` directory and I cannot use this file in 3.x line.

**Comment by grossmj** [comment]
> It doesn't need to be a drop down list - I can pick a binary from some file-system picker (I don't know the name of that dialog window) or I can write the path manually.

I have added support to edit the Qemu binary path at both the template level and node level.

![Screenshot from 2024-04-03 21-29-27](https://github.com/GNS3/gns3-gui/assets/4752614/e5178663-113d-4b51-81a9-d9354ef348bd)

![Screenshot from 2024-04-03 21-27-21](https://github.com/GNS3/gns3-gui/assets/4752614/ce3f4cab-adf5-4ada-a2e9-a6992917a5bd)

Please let me know if there is anything else to change after we release beta 2. Thanks.
