### ISSUE TITLE
Export Portable Project always  exports devices as local

### ISSUE THREAD

**Issue by Pcrossley69** [GNS3/gns3-gui#3554]
**Describe the bug**
When exporting a portable project a zipped GNS3 project fie is created.
This contains a  projec.gns3 file that describes the project.

Nodes in this file contain descriptions that include  information of the form:
    "nodes": [{"compute_id": "local",

This is true even if the project is being exported from a vm.

Consequently whenever I export a portable project, I have to do a global search and replace in this file replacing
"compute_id": "local"                  with                       "compute_id": "vm"

It seems to me that the default action should be to set the compute_id to match where you export from
At the very least docker containers should default to vm as they won't run locally.

Another possibility would be to offer a choice when the export starts   "vm" or "local"

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10 22H2
 - GNS3 version 2.2.44.1
 - Any use of the GNS3 VM or remote server:   VNWARE vm

**To Reproduce**
1) Open a project
2) Dont start anything
3) Use File->Export Portable Project
4) Use File Import Portable project to import with a new name
5) Any items that were on the vm will try to load to the local server !

**Comment by grossmj** [comment]
I have added the option "Keep the original compute IDs" in Export Portable Project. That should solve your issue.
