### ISSUE TITLE
GNS3 VM' encountered an unexpected error: The user name or password is incorrect.

### ISSUE THREAD

**Issue by angelperezleon** [GNS3/gns3-gui#3556]
I get the above either when using the .bat & .ps1 script to install on my Win10 machine with Hyper-V running or when manually adding the 2 hdd the hyper-v zip file contains.

Downloaded from this page:https://gns3.com/software/download-vm
![GNS3_Hyper_VM_pass_issues](https://github.com/GNS3/gns3-gui/assets/25584631/45244647-39f8-455c-9b0d-254e02a3dc27)

**Comment by grossmj** [comment]
Sorry, I couldn't reproduce the problem. It looks like there is something wrong with your Hyper-V setup.
