### ISSUE TITLE
MacOS DMG virustotal false positive?

### ISSUE THREAD

**Issue by dhrinkino** [GNS3/gns3-gui#3557]
In a latest version of GNS3 GUI for MacOS i got 1 flag by Ikarus. Is this false positive? https://www.virustotal.com/gui/file/2decd3626a0151ace2a6b89ee40a1b19857e08e25755e5d99685fe069e4165f6/detection

Checksum
SHA512
1d50d37e608697c61db97c1de73bd88dcd99024dfcfd4758cb18fb477150c67caa74165eeb21682e0564c9d15cf796a43fb6c563d7763f5d1b768d597ce9b647  GNS3-2.2.45.dmg
SHA256
2decd3626a0151ace2a6b89ee40a1b19857e08e25755e5d99685fe069e4165f6  GNS3-2.2.45.dmg
SHA1
83b0604812497c43460dbacc60fecae514381860  GNS3-2.2.45.dmg

**Comment by grossmj** [comment]
Yes, this is a false positive. Thanks 👍
