### ISSUE TITLE
technical problem with purchase of course on GNS3 teachable website.

### ISSUE THREAD

**Issue by RobFosterNYC** [GNS3/gns3-gui#3558]
Trying to reach teach support. 
I purchased something on GNS3  and accidentally misspelled the email address improperly and now I can not get my purchase
into my proper account.  I am trying to contact GNS3 staff before I do a reverse charge.

Do you have a technical support direct email address that I can privately send information to the staff at GNS3 / Teachable.
I tried contacting on twitter.  But GNS3 for some odd reason does not allow private messaging contact.
and weirdly enough it seems my tweet was deleted by twitter for some crazy reason.
I spend money on a product, though it did not cost that much,  I feel snatched.   🤷‍♀️

**Comment by grossmj** [comment]
Hi,

Please contact mark@gns3.com

He will be able to help you.

Regards,
Jeremy

**Comment by RobFosterNYC** [comment]
Thank you so very much Jeremy.  😋
