### ISSUE TITLE
X Y coodinates in tool tip are wrong

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3560]
**Describe the bug**
It seems like the fat client tool tip in the lower left of the screen can get out of sync with reality. If submit something with a X coordinate of 134 I'll see it show up as 126 in the tool tip. If I close and re-open the gui it will be correct. 

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows
 - GNS3 version: 2.2.45 - Was seeing this back in 2.2.33 as well. 

**To Reproduce**
Add some devices in bulk and compare x y coordinates on gui.

Any tips on how to debug this?

**Comment by grossmj** [comment]
I did a quick test and couldn't see anything wrong:

![Image](https://github.com/GNS3/gns3-gui/assets/4752614/5267cb34-7551-467f-9751-d87e62b35b2f)

How did you submit your X coordinate?
