### ISSUE TITLE
X Y coordinate tool tip doesn't stay active long enough

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-gui#3561]
**Is your feature request related to a problem? Please describe.**
When you hover over something on the map the X Y coordinates will show on the lower left of the screen for about a second then disappear.

**Describe the solution you'd like**
It would be nice if the tool tip didn't disappear until no longer hovering or just waited much longer before disappearing.
<img width="158" alt="image" src="https://github.com/GNS3/gns3-gui/assets/31658656/9f02a45c-7060-4cd7-880b-b3a64b08851f">

**Comment by spikefishjohn** [comment]
Ok so stupid question. Why time it out in the first place? Do other things show up in that field (haven't poked around graphics_view yet. Still going OCD on the telnetlib issue. 

If nothing else is writing to there, would it not be better to just keep it there until something else writes to it?

Side note. It would be nice if you could copy x/y to copy/paste buffer somehow. Not sure if that is right click get coords or whatever. Moving the mouse to that window seems too prone to error (mousing over a different node as your getting there).

**Comment by grossmj** [comment]
I have increased all timeouts to 5 seconds excepting for the the coordinates message. The status message can be reset when clicking on the scene.

> Side note. It would be nice if you could copy x/y to copy/paste buffer somehow. Not sure if that is right click get coords or whatever. Moving the mouse to that window seems too prone to error (mousing over a different node as your getting there).

The easiest would be to add a shortcut (something like CTRL+ something) that would copy the current status bar message to the clipboard. Would that be enough for you?

**Comment by grossmj** [comment]
I've added the CTRL+C shortcut, this will copy the content of the status bar to the clipboard. Let me know if you want an alternative shortcut. Thanks 👍
