### ISSUE TITLE
[Windows OS] GNS3 VM server status fails to turn green on version 2.2.45

### ISSUE THREAD

**Issue by sylar73** [GNS3/gns3-gui#3564]
**Description**:
The pre-requisites for the GNS3 VM server to be running have been checked and I've re-installed multiple times but the issue still keeps happening.
After the GNS3VM settings are done and the VM is running successfully, the server status fails to turn green. The VMware adapters were checked and they are of 1) Host-only and 2) NAT types
The GNS3 versions of client and VM match as 2.2.45
The GNS3 Doctor has all check marks as **OK**

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10
 - GNS3 version - 2.2.45
 - Any use of the GNS3 VM or remote server - GNS3VM with VMware Workstation Pro 17

**To Reproduce**
1. Complete the GNS3 setup and select GNS3 VM to be used
2. Make sure that the VMware is ready with a GNS3 VM and it is not running yet
3. Select GNS3VM from the Setup Wizard and let the GNS3VM be started
4. Notice that localhost server is detected green and running
5. But the GNS3VM server is not green

Please find the screenshots of the configurations done and let me know if something is amiss.
![Bug1](https://github.com/GNS3/gns3-gui/assets/3127353/aad21701-9a95-4ee4-85e3-6d9db2ed21c8)
![Bug2](https://github.com/GNS3/gns3-gui/assets/3127353/d11dd700-b354-4ac9-84fb-85202beb9ed8)
![Bug3](https://github.com/GNS3/gns3-gui/assets/3127353/11d6d6fb-3f93-4b53-ae22-b74a266e4750)
![Bug4](https://github.com/GNS3/gns3-gui/assets/3127353/461d901f-df75-4314-8b7d-b6b2b8ee1a43)
![Bug5](https://github.com/GNS3/gns3-gui/assets/3127353/c3d88bb8-6b10-4273-88a8-21be468102ae)
 on version 2.2.45

**Comment by sylar73** [comment]
Update: I receive the following error when I try to import appliances from GNS3VM:

> => Error while getting the list of remote images: Invalid auth for server vm

**Comment by grossmj** [comment]
Please can you try to uncheck "Protect server with password" in the server preferences?

**Comment by grossmj** [comment]
@sylar73 do you still have that issue?
