### ISSUE TITLE
Cannot Start containers

### ISSUE THREAD

**Issue by pmanolak** [GNS3/gns3-gui#3569]
I recently upgraded to GNS3 2.2.46 and I am no longer able to start any containers that were working previously because of the following error 
"error while starting alpine-1: No busybox executable could be found
No busybox executable could be found"

 - OS: Ubuntu 22.04.4 LTS
 - GNS3 version 2.2.46
 - I am not using GNS3 VM server.

The same behavior faced for all Docker Container templates. 
I have tried also to delete them and add them again, without any succeed.

![Screenshot from 2024-03-06 18-08-02](https://github.com/GNS3/gns3-gui/assets/1267874/ae6cdc0a-fb1e-4ce0-b2ba-57762a91dfdc)

![Screenshot from 2024-03-06 18-07-38](https://github.com/GNS3/gns3-gui/assets/1267874/dd17f7b8-0d0a-4e16-b71c-14bbd58f70d8)

Dont know if its related, but the folder "/usr/lib/python3.10/site-packages/gns3server/compute/docker/resources" is empty.

Please note that this happens only with Docker templates when Dynamips, IOU and Quemu templates run correctly.

Also I can run these docker containers without issues from terminal. Issue happens only when trying to start them inside from GNS3.

Finally busybox is already installed on my system.

Thanks a lot for your assistance.
Panagiotis.

**Comment by pmanolak** [comment]
Example appliance I have used is ipterm
https://hub.docker.com/r/gns3/ipterm

**Comment by epacua** [comment]
This is due to missing busybox executable at 

```venv/lib/python3.11/site-packages/gns3server/compute/docker/resources/bin/```

Copying it over to the new install will resolve this.

![gns3-busybox](https://github.com/GNS3/gns3-gui/assets/15176373/e76dcb18-c295-4094-ab1e-8d8f1be3ee8c)

**Comment by pmanolak** [comment]
> This is due to missing busybox executable at
> 
> `venv/lib/python3.11/site-packages/gns3server/compute/docker/resources/bin/`
> 
> Copying it over to the new install will resolve this.
> 
> ![gns3-busybox](https://private-user-images.githubusercontent.com/15176373/310756313-e76dcb18-c295-4094-ab1e-8d8f1be3ee8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDUzOTYsIm5iZiI6MTcwOTg0NTA5NiwicGF0aCI6Ii8xNTE3NjM3My8zMTA3NTYzMTMtZTc2ZGNiMTgtYzI5NS00MDk0LWFiMWUtOGQ4ZjFiZTNlZThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwNTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYWQ2NTg3ZmIwMTY5NTM3YjIzM2U0YTMzNWFiYTZmMDgxNjdhODhlNWE3YmM3NTI3OGZhNzk1MzZhZTU1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Antnl09w1yV_oIUCnP_v4_SWBmOeFr1KxJFobbQzik4)

Hi epacua. It seems that busybox missed from the latest version, as I cannot find it elsewhere except under
/usr/bin/busybox
/usr/lib/initramfs-tools/bin/busybox
but copy it from there did not solve the issue.

**Comment by pmanolak** [comment]
It seems that finally I found a solution by copy it under /usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/docker/resources/bin and not under /usr/lib/python3.10/site-packages/gns3server/compute/docker/resources/

but again it is strange how it was lost without make any change.

**Comment by epacua** [comment]
My guess here is that:
> It seems that finally I found a solution by copy it under /usr/share/gns3/gns3-server/lib/python3.10/site-packages/gns3server/compute/docker/resources/bin

gns3 is installed via apt or any system package manager as it saves files at /usr/share.

> ... and not under /usr/lib/python3.10/site-packages/gns3server/compute/docker/resources/
> 
> but again it is strange how it was lost without make any change.

while this one appears to be installed via pip. So basically you end up with two copies/installations of gns3.

What you did, it appears to me, is you copied a system-installed busybox executable with dynamic libraries to gns3 directory. That won't work because the docker depends on statically-built busybox which does not rely on external libraries.

**Comment by pmanolak** [comment]
Hi epacua,

Currently I dont have any installed gns3 through pip, (maybe I did that before many times ago) and indeed I installed gns3 via apt package manager. In any case, its strange why the busybox disappeared, even from the correct path after the upgrade.
As everything worked ok since a couple of days and before the upgrade to the latest version, seems that something during the upgrade remove the busybox file.

**Comment by tsinghai1982** [comment]
switching those package to version 2.2.45 can be ok
pipx install gns3-gui==2.2.45
pipx install gns3-server==2.2.45

**Comment by grossmj** [comment]
The busybox binary is not included in the GNS3 source code anymore. Busybox must already be installed on your system before trying to start a Docker container. To install on Debian/Ubuntu: `apt install busybox-static`

On starting a Docker container: the GNS3 server will try to find an executable named "busybox-static", "busybox.static" or "busybox" in the paths listed in the $PATH environment variable, then copy that executable a "resources" user data directory, for instance  `~/.local/share/GNS3/docker/resources/bin`

**Comment by grossmj** [comment]
I have updated the error message to explicitly tell that busybox must be installed.
