### ISSUE TITLE
GNS3 Wireshark Error localhost:3080

### ISSUE THREAD

**Issue by wSumieSpoko** [GNS3/gns3-gui#3570]
Hello i've got a problem with capturing in gns by wireshark and can't find any solution for that. Network is working correctly. i will be appriciate for any try to help.
![obraz_2024-03-18_231340212](https://github.com/GNS3/gns3-gui/assets/50599514/e2ac655a-bbe6-42e9-a42c-8a5fe32214c7)
GNS version: 2.2.46
VirtualBox 7.0.14 for windows hosts

**Comment by grossmj** [comment]
I found the issue. It will work in the next version (v2.2.47). Thanks for reporting 👍
