### ISSUE TITLE
GNS3VM 3.0 Beta2 Broken OVA

### ISSUE THREAD

**Issue by adfrancis** [GNS3/gns3-gui#3578]
**Describe the bug**
Downloading the GNS3VM Beta 2 OVA and deploy will show show the GNS3VM CLI stating to run sudo gns3restore because the GNS3VM menu doesn't auto-run. After running the restore script, I receive an error that libssl1.1 isn't installed. I attempted to re-download the OVA several times and get the same result.

**GNS3 version and operating system (please complete the following information):**
 - GNS3VM version 3.0 beta 2 (ESXi 7.0 Update 2)

**To Reproduce**
1. Download ESXi OVA file
2. Deploy OVA files as you would any other OVA

**Screenshots or videos**
![2024-04-14 18_53_47-VH02 home net - VMware ESXi — Mozilla Firefox](https://github.com/GNS3/gns3-gui/assets/10963005/cf755b53-7479-4867-a336-7d4ea43b655e)

Attempting to run "sudo gns3restore" results in this..
![2024-04-14 18_54_13-VH02 home net - VMware ESXi — Mozilla Firefox](https://github.com/GNS3/gns3-gui/assets/10963005/069cf35f-cabd-4971-990c-0181177610de)

**Comment by DRIgnazGortngschirl** [comment]
Got the same, if more logs are needed to let me know.
