### ISSUE TITLE
How to add other QEMU versions to the new version of GNS3 and call them in the software

### ISSUE THREAD

**Issue by angel20009123** [GNS3/gns3-gui#3581]
Currently, only this version is available
![1715148325520](https://github.com/GNS3/gns3-gui/assets/68273012/8f0c90c4-c896-46ff-8745-91f315dbfc5d)

**Comment by grossmj** [comment]
You could build Qemu from source https://en.wikibooks.org/wiki/QEMU/Installing_QEMU and make sure the path to the Qemu binary is in the $PATH environment variable.
