### ISSUE TITLE
After installing gns3 in wsl, the startup error is Fatal Python error: Aborted

### ISSUE THREAD

**Issue by saber-Alter12** [GNS3/gns3-gui#3589]
GNS3 Version: GNS3 v2.2.44.1

操作系统：windows

After installing gns3 in wsl(ubuntu), the startup error is Fatal Python error: Aborted

zmy@LAPTOP-LNH622Q9:/mnt/c/Windows/system32$ gns3 Fatal Python error: Aborted Current thread 0x00007faab6c65740 (most recent call first):  File "/usr/share/gns3/gns3-gui/lib/python3.8/site-packages/gns3/application.py", line 47 in __init__  File "/usr/share/gns3/gns3-gui/lib/python3.8/site-packages/gns3/main.py", line 237 in main  File "/usr/bin/gns3", line 8 in <module> Aborted

**Comment by grossmj** [comment]
Sorry, we don't officially support WSL yet: https://github.com/GNS3/gns3-vm/issues/141

**Comment by saber-Alter12** [comment]
> 抱歉，我们尚未正式支持 WSL：[GNS3/gns3-vm#141](https://github.com/GNS3/gns3-vm/issues/141)



> 抱歉，我们尚未正式支持 WSL：[GNS3/gns3-vm#141](https://github.com/GNS3/gns3-vm/issues/141)

I am using Ubuntu 20.04 in WSL2. I have successfully started GNS3 on my previous computer, but now I only get an error when I switch to a new computer. I don't know what the reason is
