### ISSUE TITLE
Custom progress dialog

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#359]
Currently a generic progress dialog is set when we open the preferences or configuration dialogs.

https://github.com/GNS3/gns3-gui/blob/unstable/gns3/dialogs/node_configurator_dialog.py#L60
https://github.com/GNS3/gns3-gui/blob/242018d0d34a4eb598cedf074adaab991d7c4d2c/gns3/dialogs/preferences_dialog.py#L54

and we restore the default one (main window as parent) when we close these dialogs:

https://github.com/GNS3/gns3-gui/blob/unstable/gns3/dialogs/node_configurator_dialog.py#L152
https://github.com/GNS3/gns3-gui/blob/242018d0d34a4eb598cedf074adaab991d7c4d2c/gns3/dialogs/preferences_dialog.py#L143

However, it would be nicer to pass a custom progress dialog with a different title to the server http methods and better have the option to deactivate the default progress dialog, but how to handle the cancellation of a request?

**Comment by noplay** [comment]
What did you think about adding a parameter like:
```
http_client.get("/iou/vms", callback, context=context, progress_text="Downloading list of VMs")
```

**Comment by grossmj** [comment]
Sounds good but not sure this is the most flexible. The progress dialog
parent and delay need to be changed as well.

**Comment by grossmj** [comment]
We still need to discuss this. I've very strange issues regarding progress dialogs on Linux. Maybe you could pass a parent and delay in addition of the progress_text?

**Comment by noplay** [comment]
A delay for dropping the progress?

**Comment by grossmj** [comment]
Minimum delay before displaying the progress dialog. When in the config or preferences dialog I want to use a delay of 0 so the user doesn't get a chance to close the dialog before the progress appears.

**Comment by grossmj** [comment]
Alternative idea: what about using a "Network Operations Manager"? For instance in VirtualBox all network requests are listed in a separate dialog with a notification icon prevent in the bottom right corner. You can see it if you click on "Check for Updates". This is a concept present in other software as well.

**Comment by noplay** [comment]
I don't see it in the app. 

Do you mean something like:
![capture d ecran 2015-06-18 a 10 04 36](https://cloud.githubusercontent.com/assets/345437/8226714/7d06771c-15a1-11e5-8c93-648925f0ad0c.png)

And if you click on it you see a Windows with more informations.

**Comment by grossmj** [comment]
Ok, works well now. Do you think it is easily possible to have a custom text to be displayed in the progress dialog?

**Comment by noplay** [comment]
We have two options. Pass it to the HTTP query and make it global via the
context.

The context is easier to implement.

**Comment by grossmj** [comment]
If we pick the context, does this mean that the text will always be the same in the Preferences dialog for instance?

**Comment by noplay** [comment]
We can use context like russian doll.

But I add a progressText parameter allow to customize a specific query:
https://github.com/GNS3/gns3-gui/commit/c632303fd66963987d00e712d16b367c3cf818a3#diff-3a123c5b0a8d26e0899ba1a8457b1010R66

**Comment by noplay** [comment]
Is something missing for this issue?

**Comment by grossmj** [comment]
We are good :)
