### ISSUE TITLE
WebUI doesn't work without internet access

### ISSUE THREAD

**Issue by hossamkhader** [GNS3/gns3-gui#3590]
I tested it in an air-gapped network. It keeps trying to access the below URL:

https://www.googletagmanager.com/gtag/js?id=G-5D6FZL9923

**Comment by hossamkhader** [comment]
Yes.

**Comment by grossmj** [comment]
Do you still have the issue in our latest version? thanks 👍

**Comment by hossamkhader** [comment]
Issue appears to be fixed in version 3.0.0b3
