### ISSUE TITLE
Is simultaneous network monitorinng limitated to six links at the same time?

### ISSUE THREAD

**Issue by mmartinrami** [GNS3/gns3-gui#3594]
Hello i have a topology an i want to monitoring with wireshark more than  six links at the same time  but if i put seven or more at the same time  doesn't finish load  an i recive timeout. I tried in another pc with other specs but the result was the same .Is it limitated by code ?  is there a way to solve it?

![image](https://github.com/GNS3/gns3-gui/assets/170534186/342f58da-f9a5-4c1c-ae1b-497e3f2b8ebf)

**Comment by mmartinrami** [comment]
After a few minutes i have this error: Error while starting capture on link 6580d5df-95bb-4866-b30a-9e70644e4f1e: Operation timeout

**Comment by mmartinrami** [comment]
hello the taffic is not to much because  is a small  netowork topoly  (around 15 devices).
I running the server in linux Ubuntu 22.04.4 LTS
My CPU usage is :
![image](https://github.com/user-attachments/assets/dc47079f-6f78-42fa-81d9-ec8b5d3393d7)
My gns3 version is 2.2.47

**Comment by grossmj** [comment]
Good news, I can reproduce the issue on my side. It only affects the desktop client not the web-ui.

This is because of a Qt limitation as stated in https://doc.qt.io/qt-6/qnetworkaccessmanager.html

> Note: QNetworkAccessManager queues the requests it receives. The number of requests executed in parallel is dependent on the protocol. Currently, for the HTTP protocol on desktop platforms, 6 requests are executed in parallel for one host/port combination.

Since we stream PCAP files using HTTP, the GUI cannot make requests once you hit 6 packet captures.

I will try to fix this soon.
