### ISSUE TITLE
Could not find Dynamips after upgrading to 2.2.48

### ISSUE THREAD

**Issue by wcarpen01** [GNS3/gns3-gui#3595]
upgrading on macOS from 2.2.47 -> 2.2.48, get the following error:

Error while creating node from template: Could not find Dynamips

**Comment by grossmj** [comment]
Thanks, I think this is because the Dynamips executable has been compiled on Apple Silicon. I will look into it.

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-build/commit/41347378417904df3d5adf0b2c8b4f8b2e60e2e3

We are going to release v2.2.48.1 that fixes the issue soon

**Comment by arjun713** [comment]
@grossmj Thanks for the update, How many days it will take

**Comment by grossmj** [comment]
We are planning to release it today.

**Comment by thschaffr** [comment]
> We are planning to release it today.

I see that it was released a couple of hours ago here: https://github.com/GNS3/gns3-gui/releases
@grossmj, thank you.
