### ISSUE TITLE
Web console in new tab is no longer working with latest GNS3 2.2.48 (ubuntu linux)

### ISSUE THREAD

**Issue by badaniya** [GNS3/gns3-gui#3596]
**Describe the bug**
Before upgrading GNS3 to the latest 2.2.48 release, I was able to bring up "Web console in a new tab" for my emulated EXOS and VOSS switches.

After upgrading GNS3 to 2.2.48, The "Web console in new tab" no longer brings up the console in the new tab.

NOTE: I see the same behavior in both google-chrome and firefox web browsers.

Workaround:
"Web console" still works.

**GNS3 version and operating system (please complete the following information):**
 - OS: **Ubuntu 22.04 (Jammy)**
 - GNS3 version: **2.2.48**
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.): None

**To Reproduce**
1. Open a project with EXOS and VOSS switches.
2. Right click on the switch and click on "Web console in new tab".
3. A new tab is launched and seemingly proper URL is there, But web console for the switch doesn't show up.
4. Alternatively, Clicking on "Connect console for all nodes" for the project (where default setting is to bring up consoles in new tabs).  This also results in the same behavior.

**Screenshots or videos**
![image](https://github.com/user-attachments/assets/9dbedd16-c7a4-44d1-9d1f-6cd071edf892)

**Additional context**
n/a

**Comment by badaniya** [comment]
I opened this bug under the wrong component.

**Comment by grossmj** [comment]
Thanks for the report. This bug has been fixed already, it will work in v2.2.48.1 (currently being released).
