### ISSUE TITLE
QIODevice::read: device not open

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#360]
I get the following suspicious log on Linux when I close GNS3 (after I added some nodes). This may be something to do with the server notification support that we not closed properly, maybe?

2015-05-14 21:17:19 INFO http_client.py:453 Response error: Operation canceled
QIODevice::read: device not open

**Comment by noplay** [comment]
Probably.

It seem when you hit the close button Qt kill the connection for us....

**Comment by noplay** [comment]
It's fixed the error was we abort the stream and we try to read his content.
