### ISSUE TITLE
3.0.0b3   help --》Setup Wizard missing  vmware and hyper-v option

### ISSUE THREAD

**Issue by tqangxl** [GNS3/gns3-gui#3600]
missing  vmware and hyper-v option
![image](https://github.com/user-attachments/assets/b21ec501-d54a-4673-8268-eea581c3461d)

**GNS3 version and operating system (please complete the following information):**
 - OS: 
 - 版本	Windows 11 专业版
版本号	23H2
安装日期	‎2022/‎5/‎7
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0
 - 设备名称	DESKTOP-DOE0ADN
处理器	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
机带 RAM	40.0 GB (39.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

 - 
 - GNS3 version
 - V.3.0.0b3
 -Hyper-V 管理器
Microsoft Corporation
版本: 10.0.22621.1

**To Reproduce**
1. install gns3
2. chose   Hyper-V 
3. when download Hyper-V vm ，cancel download 
4.  open gns3，help --》Setup Wizard

**Screenshots or videos**
Where  running on VM?????
![image](https://github.com/user-attachments/assets/b21ec501-d54a-4673-8268-eea581c3461d)

**Additional context**

**Comment by grossmj** [comment]
Same as in https://github.com/GNS3/gns3-gui/issues/3599
