### ISSUE TITLE
Showing IPs in the Topology Summary

### ISSUE THREAD

**Issue by braza2004** [GNS3/gns3-gui#3601]
It would be very convenient to have IP information in the topology summary alongside the information that is already being displayed

**Comment by grossmj** [comment]
@braza2004 the IP information of the nodes or the IP info for the consoles?

**Comment by braza2004** [comment]
@grossmj IP information of the nodes

**Comment by grossmj** [comment]
> @grossmj IP information of the nodes

Unfortunately, we don't have that information. In GNS3, we use emulators like Qemu, Dynamips etc. to run different images (operating systems) but we don't access / or cannot easily access what is running inside these emulators.
