### ISSUE TITLE
Key Bindings/ Shortcut Keys

### ISSUE THREAD

**Issue by braza2004** [GNS3/gns3-gui#3602]
GNS3 still does not have shortcut keys like other software do.

**Comment by grossmj** [comment]
> GNS3 still does not have shortcut keys like other software do.

I would be happy to add these. Please can you propose a shortcut key for all actions that you have one? Thanks 👍

**Comment by braza2004** [comment]
@grossmj My colleague and I have added some new shortcuts in our recent pull request. We would greatly appreciate it if you could review it please.
