### ISSUE TITLE
router-switch- cloud -Internet  ：pc ping router failed

### ISSUE THREAD

**Issue by tqangxl** [GNS3/gns3-gui#3606]
cloud： DESKTOP-DOE0ADN
switch： gnsvm
router ： gnsvm

![image](https://github.com/user-attachments/assets/ad0eb09b-7e5f-44eb-b355-46e4695c1c9e)

![image](https://github.com/user-attachments/assets/046fdd65-3f93-448e-99c6-775d96295b73)
![image](https://github.com/user-attachments/assets/fafeaefe-415a-4585-977a-4b3ed4748641)

OS:

Windows 11 pro
 23H2
 ‎2022/‎5/‎7
 22631.3880
 Windows Feature Experience Pack 1000.22700.1020.0

 DESKTOP-DOE0ADN
 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz
RAM 40.0 GB (39.9 GB 可用)

GNS3 version
V.2.2.48.1

To Reproduce

install gns3
chose vmware workstation
when download vm ，cancel download
open gns3，help --》Setup Wizard
upload

**Comment by grossmj** [comment]
Have you tried with VMware Network Adapter VMnet8?

**Comment by tqangxl** [comment]
> Have you tried with VMware Network Adapter VMnet8?

![image](https://github.com/user-attachments/assets/4240cb76-7b63-44bb-bc50-a5678b0b6a82)

same

**Comment by grossmj** [comment]
@tqangxl have you tried?
