### ISSUE TITLE
最新版 Port1 isn't free

### ISSUE THREAD

**Issue by tqangxl** [GNS3/gns3-gui#3609]
![image](https://github.com/user-attachments/assets/f2fff784-2691-4a32-a639-6acad2e4c05e)

**Comment by grossmj** [comment]
Have you tried to connect 2 nodes? I would need more info to fix this. Is this something you can reproduce?

**Comment by tqangxl** [comment]
> Have you tried to connect 2 nodes? I would need more info to fix this. Is this something you can reproduce?
https://private-user-images.githubusercontent.com/9669944/350739441-ad0eb09b-7e5f-44eb-b355-46e4695c1c9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTQxMDYsIm5iZiI6MTcyMTc5MzgwNiwicGF0aCI6Ii85NjY5OTQ0LzM1MDczOTQ0MS1hZDBlYjA5Yi03ZTVmLTQ0ZWItYjM1NS00NmU0Njk1YzFjOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMDQwMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjkzOTNkMGMwMTNlYWViYThiZWJmYmFlNDBmY2EwNTJiNDgwNGQwYWVmMjhhY2MxZTJlMWZmOWQ4NGUzYzA3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1TSsEgKOO21r5t8z0nWGxePOkYTZBPD7xWHi5o0xV_4
