### ISSUE TITLE
connect to remote hypervisors

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#361]
My current config consist of:

Real_Device(Router) <-> Server with Dynamips <-> nio_udp tunnel <-> Cloud node in GNS3 on my PC

The only problem is that I need to manually start dynagen to create the configuration for the dynamips hypervisor. It would be really handy if there will be a menu in GNS3 to create the config and interact with the hypervisor.

Content of the dynagen.net file:

    autostart = True
    [10.125.144.118:7000]
      workingdir = /root
      [[ETHSW SW401]]
        1 = access 1 nio_udp:20401:10.125.21.107:10401
        2 = access 1 nio_gen_eth:eth2

I have 10 ethernet interfaces on that server from which 8 are dedicated for dynagen.

**Comment by noplay** [comment]
Hi,

In 2.0 you will be able to connect to a cloud on a different server.
