### ISSUE TITLE
Ctrl + Z

### ISSUE THREAD

**Issue by athaarnaqvi** [GNS3/gns3-gui#3611]
I would recommend the addition of a Ctrl+Z shortcut for the undo action in GNS3. Currently, there is no such thing for undoing actions, which can be inconvenient and disrupt workflow efficiency.

**Comment by grossmj** [comment]
> I would recommend the addition of a Ctrl+Z shortcut for the undo action in GNS3. Currently, there is no such thing for undoing actions, which can be inconvenient and disrupt workflow efficiency.

Unfortunately, it is too complicated to reverse some actions in GNS3, especially the ones involving the controller/server side.
