### ISSUE TITLE
Asking Quantity of a Device When Adding Them on the Scene

### ISSUE THREAD

**Issue by athaarnaqvi** [GNS3/gns3-gui#3617]
I often want to add multiple instances of a single device while making a topology and it gets really frustrating to drag and drop every single one or like even duplicate one while making large network topologies

I would like an option to specify the quantity of a certain device when adding it to the scene in GNS3. For example, when selecting a device from the templates, there should be a prompt or a field where I can enter the number of instances I want to add. This would allow me to add multiple devices simultaneously, positioned automatically or in a specified pattern.

**Comment by grossmj** [comment]
We already have it. You must press Shift while dragging & dropping on the scene.

![Screenshot from 2024-08-07 13-23-17](https://github.com/user-attachments/assets/d1623543-63b2-45e4-9afb-4cb1c4fbc306)
