### ISSUE TITLE
GNS3 Project to Project Communication

### ISSUE THREAD

**Issue by athaarnaqvi** [GNS3/gns3-gui#3618]
Managing large topologies within a single project can be difficult. Splitting the topology into multiple projects could make management easier and more organized. So is it currently possible for different GNS3 projects to communicate with each other?
If not, are there any existing workarounds or third-party tools that can enable this functionality?

**Comment by athaarnaqvi** [comment]
@grossmj can you please answer this.

**Comment by grossmj** [comment]
> So is it currently possible for different GNS3 projects to communicate with each other?

You could set up different projects to always run in the background and make them communicate with each other by using clouds that connect to bridges on your host machine.
