### ISSUE TITLE
Cannot Connect  Controller GNS3 3.0.0rc1,Cannot enable Local Controller

### ISSUE THREAD

**Issue by kezzchr34** [GNS3/gns3-gui#3623]
Cannot Connect  Controller GNS3 3.0.0rc1,Cannot enable Local Controller

GNS3 3.0.0rc1
- Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
- OS Windows 10 [ version 10.0.19045
- GNS3 3.0.0rc1
- GNS3 VM 3.0.0rc1
- VM WareWorkstation Pro version 17.5.2 build-23775571

** To Reproduce **
1. Install GNS3-3.0.0rc1-all-in-one in Windows
2. Download, extract GNS3 VM 3.0.0rc1 and import GNS3 VM 3.0.0rc1 in VM WareWorkstation Pro version 17.5.2
3. Start the VM
4. Start GNS3
5. Goto Prefereneces > Controller 
6. Cannot enable Local Controller
7. See errors in Screen Shots.

**GNS3 version and operating system (please complete the following information):**
 - OS: [e.g. Windows, Linux or macOS]
 - GNS3 version [e.g. 2.1.14]
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

![GNS3_RC1_Controller_Error](https://github.com/user-attachments/assets/71c97fd1-ad18-4f58-ba41-4e3d9a756880)
![VM_WARE_WORKSTATION_config](https://github.com/user-attachments/assets/17d3e9f2-d964-4a64-a4c6-3599ee8fde5e)
![VMware_version](https://github.com/user-attachments/assets/a07de15e-2c71-45ff-8c87-2fc3411f3b99)
![GNS3_RC1_Controller_Error](https://github.com/user-attachments/assets/87d86266-3181-49cb-8a1b-d179ed5dc954)
![VM_WARE_WORKSTATION_config](https://github.com/user-attachments/assets/d593e5fe-ddbc-4c7f-9d1d-99901d7f9c69)
![VMware_version](https://github.com/user-attachments/assets/dc4ba9d7-bb90-4d07-9184-24096eb08ee4)

**Comment by grossmj** [comment]
Looks like you are trying to use port 3080 in the GUI while the controller in the VM listens on port 80.

**Comment by grossmj** [comment]
Please try to add the controller using port 80. Let us know if this still does not work.

Thanks 👍

**Comment by kezzchr34** [comment]
Connected using port 80.

Kerry Christie
Information Technology Professional, Network Engineer
CCIE (Written),CCNA,CCNP,CCNA Voice, A+, Linux+, LPIC-1
Training - CCIE R&S, VMware vSphere VCP-DCV, LPIC-2
________________________________
