### ISSUE TITLE
Visio integration with GNS3

### ISSUE THREAD

**Issue by athaarnaqvi** [GNS3/gns3-gui#3624]
I want to integrate visio with gns3 such that i am able to import the .vsdx file in gns3 to replicate the drawing. The appliances present in the diagram can either be imported in the form of virl images or by mapping a vm of that server in gns3. I will extract the .xml files from the .vsdx file and then retrieve the devices information and linking information in the form of YAML file. The automation will be done through ansible. 

I just wanted to get some guidance from you whether this approach is right and doable or not.

**Comment by athaarnaqvi** [comment]
@grossmj can you please answer this

**Comment by cristian-ciobanu** [comment]
@athaarnaqvi this was requested many years ago https://github.com/GNS3/gns3-gui/issues/1962 and I think this is not on the feature list for developers for now.

**Comment by grossmj** [comment]
> I think this is not on the feature list for developers for now.

This is right, we are not looking at having this feature excepting maybe if someone take care of it without much input from us as we want to focus on other features.
