### ISSUE TITLE
Unable to import Cisco IOU or IOS images in GNS3 version 2.2.49

### ISSUE THREAD

**Issue by Raaanz** [GNS3/gns3-gui#3627]
**GNS3 version and operating system**
 - OS: Windows
 - GNS3 version: 2.2.49
 - Attempted with GNS3 VMWare Workstation Pro

**Steps to Reproduce**
1. Delete existing Cisco IOS templates if any.
2. Remove the IOS image and checksum files from GNS3 server folder(/opt/gns3/images/IOS).
3. Add any IOS template such as Cisco 7200 router template.
4. See error.

**Additional context**
Downgraded to GNS3 version 2.2.48 and the error was not present.

**Comment by dnszero** [comment]
This happens to me too.

- Server OS: Linux
- Server GNS3 version: 2.2.49

- Client OS: Mac OS 15 (m1 apple silicon)
- Client GNS Version: 2.2.49

If I manually create a template, then I can get the IOS image to upload to the server and work fine, but if I choose "Install and appliance from the GNS3 server", the image will upload but it will never show up ("Status Missing") even though I can ssh to the server and verify that image is in /opt/gns3/images/IOS
