### ISSUE TITLE
Unable to deploy GNS3 v3 RC1 ova on vCenter or esxi

### ISSUE THREAD

**Issue by fftkatarn** [GNS3/gns3-gui#3629]
Hello,
I'm trying to deploy the "GNS3.VM.VMware.ESXI.3.0.0rc1.zip" OVA on both vCenter server (v7.0.3) and standalone esxi 8.0 but I receive the following errors:

vCenter:
 Invalid configuration for device '8'.
 Failed to deploy OVF package. ThrowableProxy.cause A specified parameter was not correct: The operation failed due to Invalid configuration for device '8'.

esxi:
 Invalid configuration for device '2'.

Any clues?
Thanks!

**Comment by grossmj** [comment]
Have you got the same issue with any v2.2.x version?

**Comment by grossmj** [comment]
Looks like this is the same issue as described in https://github.com/GNS3/gns3-vm/issues/187

The current workaround is the edit the .ovf file to update `videoRamSizeInKB`

I fixed it for the next release (tested with ESXi 8)

**Comment by fftkatarn** [comment]
> Have you got the same issue with any v2.2.x version?

Sorry for the late reply, I tried with version 2.2.49 and I don't have this issue.


> Looks like this is the same issue as described in [GNS3/gns3-vm#187](https://github.com/GNS3/gns3-vm/issues/187)
> 
> The current workaround is the edit the .ovf file to update `videoRamSizeInKB`
> 
> I fixed it for the next release (tested with ESXi 8)

Great, thank you!
