### ISSUE TITLE
Dynamips error when starting c7200 using npe-g2

### ISSUE THREAD

**Issue by iffathanafiah** [GNS3/gns3-gui#3631]
**Describe the bug**
I tried to use NPE-G2 with 1GB RAM for my c7200 router and when I tried to start the router it said that Dynamips error when starting the router.

**GNS3 version and operating system:**
 - OS: Ubuntu 22.04
 - GNS3 version  2.2.49

**To Reproduce**
1. Have a Cisco 7200 124-24.T5 router
2. Configure the router to use NPE-G2 and 1GB RAM
3. Start the router
4. Error occurred

**Screenshots or videos**
![dynamips error](https://github.com/user-attachments/assets/3122d76e-c04f-4313-b8f2-af6f12f17b3a)

**Additional context**
I also have tried using the Cisco 7200 152-4.M7 and Cisco 7200 152-4.S6 routers resulted in the same error which cannot start the router.

**Comment by grossmj** [comment]
Hi,

NPE-G2 is marked as not working in Dynamips.

```
dynamips -h
Cisco Router Simulation Platform (version 0.2.23-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: Apr  6 2024 18:10:19

<...>

Available C7200 NPE drivers:
  * npe-100 
  * npe-150 
  * npe-175 
  * npe-200 
  * npe-225 
  * npe-300 
  * npe-400 
  * npe-g1 (NOT WORKING)
  * npe-g2 (NOT WORKING)
```

Sorry, unfortunately this is unlikely to be fixed.
