### ISSUE TITLE
Moving an interface label should display which interface it's attached to

### ISSUE THREAD

**Issue by scls19fr** [GNS3/gns3-gui#3634]
Hello,

currently interface labels (when shown) don't really show which interface they are attached to

<img width="85" alt="image" src="https://github.com/user-attachments/assets/fe8dba3d-5819-4b92-ad47-47752432a31a">

Maybe when moving an interface label a line could be drawn between this interface label and the interface (ie the green circle here).

<img width="84" alt="image" src="https://github.com/user-attachments/assets/8690d5d3-ab45-4998-9ef8-d30090fc8684">

This could help to avoid mixing several interface labels.

Kind regards

**Comment by smart2128** [comment]
There are a couple of similar enhancement requests [#2953](https://github.com/GNS3/gns3-gui/issues/2953)
