### ISSUE TITLE
Add appliance / incorrect file / Display both MD5 sum and file size

### ISSUE THREAD

**Issue by scls19fr** [GNS3/gns3-gui#3637]
Hello,

I noticed that when you want to add an appliance which is an incorrect file the following message appears

```
This is not the correct file. The MD5 sum is a30bc9143788c76ed584ffd5d25fddfe and should be af4be6b27463446905f155f14232d2b4.
Do you want to accept it at your own risks?
```

In order to more easily fix appliance with new version this message should be better formatted and display both MD5 sum and file size (in bytes).

```
This is not the correct file.

MD5 sum
actual:   a30bc9143788c76ed584ffd5d25fddfe
expected: af4be6b27463446905f155f14232d2b4
File size
actual:   267386880
expected: 265186881

Do you want to accept it at your own risks?
```

This way it will be easier to provide new version for appliances

Kind regards

PS : could help fixing https://github.com/GNS3/gns3-registry/issues/920

**Comment by grossmj** [comment]
Done, thanks 👍 

![Image](https://github.com/user-attachments/assets/cdf5c4d3-80ea-453c-9aa7-358679b6ddb3)
