### ISSUE TITLE
Connecting GNS3 and GNS3 IOU VM through GNS VM

### ISSUE THREAD

**Issue by Nangtais** [GNS3/gns3-gui#3645]
Hello, 

I've installed GNS3 GUI on my local computer. Then I installed GNS 3 VM and GNS3 IOU VM on VmWare workstation 16 Pro. 
Their network config are as folluw: 

GNS server: 
- NAT on Eth0, 
- Host Only on Eth1 and IP address 192.168.184.1/24 

GNS3 VM: 
- NAT on Eth0 
- Host Only on Eth1 and IP address 192.168.184.10/24 
GNS3 IOU VM: 
- NAT on Eth0
- Host Only on Eth1 and IP address 192.168.184.11/24

Eth0 and Eth1 are virtual interfaces created by VMware workstation.  The addresses are given by a DHCP server. The network config are default. 

GNS3 hosy and GNS3 VM are green in GNS3 GUI. But GNS3 IOU VM is grey. 
GNS3 IOU pings successfully GNS3 VM. But it cannot ping GNS3 server. 

I need that GNS3 IOU VM reaches both GNS3 server and GNS3 VM. My goal is to get l IOU appliances in GNS3 GUI through GNS3 IOU VM. 

Could you help me please ?

**Comment by grossmj** [comment]
I think the best is to run everything in the GNS3 VM.
