### ISSUE TITLE
gns3-server user rights issues - v2.2.50

### ISSUE THREAD

**Issue by Kizan** [GNS3/gns3-gui#3646]
OS: Ubuntu 24.04.1 (upgrade and fresh install)
GNS3 version: 2.2.50
Local GNS3 server

Attempt 1:
Ran upgrade from 2.2.49 to 2.2.50, discovered GNS3 server application is now running as new user "gns3-server". It has no rights in the /home/<username>/GNS3 folder and can't read/write there. Was able to add gns3-server user to local users group and that allowed gns3 to create new projects [sudo usermod -aG $(whoami) gns3-server
]. However, this still didn't allow it to open old projects. All custom templates are missing (no surprise) and am unable to use the standard templates. I tried to pull out a NAT object and get this error.

"Error while creating node from template: uBridge is not available, path doesn't exist, or you just installed GNS3 and need to restart your user session to refresh user permissions."

Restarting app does not help, nor does restarting the OS.

Attempt 2:
Fresh Ubuntu 24.04.1 (newest updates) installed and then installed GNS3 v2.2.50. New install has the gns3-server user issues mentioned above. In addition, the fresh install does not create the /home/<username>/GNS3 folder.

<img width="965" alt="2024-10-21 14_06_32-TEMPLATE - Ubuntu 24 04-GNS3-T1 - GNS3 Error 1" src="https://github.com/user-attachments/assets/3edfae99-325d-41e2-8dee-0f2a8999ad57">

![2024-10-21 14_06_32-TEMPLATE - Ubuntu 24 04-GNS3-T1 - GNS3 Error 2](https://github.com/user-attachments/assets/9216071b-0adc-43f9-b656-f88a4ec4994d)

**Comment by auspham** [comment]
I'm having the same exact problem as well for newly installed GNS3. Was looking for solution for hours.

**Comment by stutzzzz** [comment]
Same after update all images could not be seen couldn't create new project.

**Comment by Raph-lab-64** [comment]
Same after update all images could not be seen couldn't create new project.

**Comment by GanzaTM** [comment]
Та же проблема. Кто-нибудь подскажет, возможно ли GNS3 2.2.49 скачать?

**Comment by jschuhmann47** [comment]
Same here, also reported [here](https://www.gns3.com/community/featured/gns3-2-2-50-worse-than-2-2-49-issues-with-permissions-errno-13-now)

**Comment by jcalano** [comment]
I just updated to 2.2.50 and now I get an error "ubridge path not found" and all my templates are missing as are my remote servers.  All of my local paths have been reset to the defaults as well, it's as if this is a new install.  I run this with two remote servers on two workstations simultaneously.  It will take me at least two hours to reconfigure everything.  Please provide a way to revert the upgrade in cases like this where the entire system get reset.  I fixed the ubridge issue by running the setup wizard, after noticing the complete system reset and all my configurations were gone.  I'm very upset about this.  Valuable lab time has to be postponed until I can reconfigure this again.

**Comment by grossmj** [comment]
I apologize for this issue, we didn't anticipate it would create problems since this is an optional option when you install the gns3-server package.

Has anyone seen this dialog?

![Screenshot from 2024-10-09 18-33-14](https://github.com/user-attachments/assets/6c52f036-5239-46c0-9714-3222e5a992c3)

I have reverted the changes for now and will go back to the drawing board in regard of how we handle the gns3-server service. 

New packages with the old behavior have been published:

```
gns3-server-2.2.50~oracular2
gns3-server-2.2.50~noble2
gns3-server-2.2.50~jammy2
gns3-server-2.2.50~focal2
```

**Comment by Kizan** [comment]
I never saw this dialog during the upgrade or the fresh installs that I've done.

**Comment by auspham** [comment]
> I apologize for this issue, we didn't anticipate it would create problems since enabling the service is optional when you install the gns3-server package.
> 
> Has anyone seen this dialog?
> 
> ![Screenshot from 2024-10-09 18-33-14](https://private-user-images.githubusercontent.com/4752614/379065314-6c52f036-5239-46c0-9714-3222e5a992c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDg0MTksIm5iZiI6MTcyOTY0ODExOSwicGF0aCI6Ii80NzUyNjE0LzM3OTA2NTMxNC02YzUyZjAzNi01MjM5LTQ2YzAtOTcxNC0zMjIyZTVhOTkyYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDE0ODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNjNWM2MDhiZTQyOWY4ZjE4ZDEyNzIwODQ1MDYwYzliODc2MTk4MGUyMzZhZTI5MGI0NmRhMTBhNzllMTlkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Yl43W_nHqUAKLbnVtJ3hg-zsb9F4OScwKux6U85leQU)
> 
> I have reverted the changes for now and will go back to the drawing board in regard of how we handle the gns3-server service.
> 
> New packages with the old behavior have been published:
> 
> ```
> gns3-server-2.2.50~oracular2
> gns3-server-2.2.50~noble2
> gns3-server-2.2.50~jammy2
> gns3-server-2.2.50~focal2
> ```

I saw the dialog and selected NO, upons removing and reinstalling this dialog not appear anymore.

**Comment by ahmedkhlief** [comment]
i also have the same issue and after modifying the permissions i managed to make it work but now it can't list VMs in vbox or vmware and other issues also related to permissions

**Comment by Raph-lab-64** [comment]
Hello,
I cannot find these packages gns3-server-2.2.50~oracular2, gns3-server-2.2.50~noble, 2gns3-server-2.2.50~jammy, 2gns3-server-2.2.50~focal2,  in the repositories ( I use Mint). How can I install them?
thank's

**Comment by e-thibault** [comment]
Yes I must have seen it but
1) in the previous installations I remembered we always had to answer 'yes' to those screens
2) I thought in a new edition fom 2.2.49 to 2.2.50 there would not be major change anyway.

so now that we installed that version how should we proceed to get the correction ?
- do we have to uninstall GNS3 and reinstall 2.2.50 for our OS ?
- or do we have to install 2.2.50 for our OS, i.e. gns3-server-2.2.50~noble2 for me and it should correct the issue ?

**Comment by MaiMarti** [comment]
I did remove the old version  gns3-server-2.2.50~jammy1, update repository, install the new version  gns3-server-2.2.50~jammy2 and select the "NO" to avoid gns3-server as a service.
But not working for me.
The only way is doing this everytime I want to use GNS3:
close gns3
sudo ps -ef | grep gns3

And kill the process: sudo kill -9 pid

It's really annoying working this way.
I hope they will repair soon.
Is it possible to return to 2.2.49 version?

**Comment by auspham** [comment]
@grossmj 

I removed the old versions and then re-installed your updates. However facing unauthentication error.

2024-10-23 19:14:08 ERROR http_client:681 Host requires authentication (localhost:3080)
2024-10-23 19:14:08 DEBUG http_client:371 Retry connection to http://localhost:3080
2024-10-23 19:14:09 DEBUG http_client:551 GET http://localhost:3080/v2/version {}
2024-10-23 19:14:09 DEBUG http_client:662 Response error: Host requires authentication (localhost:3080) for http://admin@localhost:3080/v2/version (error: 204)

**Comment by e-thibault** [comment]
> so now that we installed that version how should we proceed to get the correction ?
> 
> * do we have to uninstall GNS3 and reinstall 2.2.50 for our OS ?
> * or do we have to install 2.2.50 for our OS, i.e. gns3-server-2.2.50~noble2 for me and it should correct the issue ?

Thinking twice about it I imagine that you produced a new version without the choice that introduces the new option
would it be just for the new people that had not upgraded yet so they can upgrade without the issue whatever their choice,
so uninstall and reinstall I think.

Now I already had an issue with GNS3 2.2.49 described there :
https://gns3.com/community/featured/gns3-2-2-49-on-ubuntu-24-04-does-not-recognize-gns3-2-2-47-projects-working-on-ubuntu-22-04
I imagine it is still there...

**Comment by e-thibault** [comment]
OK so I uninstalled GNS3 and reinstalled it, I got no screen with questions like in Jeremy's post.
the issue of users rights is solved but not the issue I found in GNS3 2.2.49 i reported there :
https://gns3.com/community/featured/gns3-2-2-49-on-ubuntu-24-04-does-not-recognize-gns3-2-2-47-projects-working-on-ubuntu-22-04

So I'm going to open an issue here...

**Comment by Raph-lab-64** [comment]
After reinstalling GNS3 with Jimmy2, I no longer have permission issues, but I get an error: 'cannot use a node on the GNS3 VM server with the GNS3 VM not configured'...  user for both the GNS3 server and the GNS3 VM??  Any idea?"
![cannot use a node](https://github.com/user-attachments/assets/3c7ed77c-4dfb-4d48-a743-5f887dcb8cf7)
thank's

**Comment by stutzzzz** [comment]
re installing the new update crashes on cosmic may be a wayland issue. x11 appears to launch and create a project but unable to see images like FTDs or FMCs that was used before.

**Comment by jcalano** [comment]
What changes during the install process that makes it so my templates are not found?  Now that my other computer was updated to the latest GNS3 version all my templates are gone.  Is there an easy way to get them back without having to reinstall them all?

**Comment by pmsobral** [comment]
All my templates are also gone! Please roll back these changes and go back to 2.2.49. Precious time lost trying to solve this!

**Comment by grossmj** [comment]
Do you know under what user the GNS3 server run? `ps aux | grep gns3server`?

Also, your templates should be stored in `~/.config/GNS3/2.2/gns3_controller.conf`

Finally, what is the output of `systemctl status gns3-server`?

Thanks.

**Comment by pmsobral** [comment]
Thank You for your message:

ps -aux | grep gns3-server

root        3952  0.4  0.4 357764 51668 ?        Ssl  12:45   0:03 /usr/share/gns3/gns3-server/bin/python /usr/bin/gns3server --local

Perhaps this is the problem as I have a user (not root) where all the templates are stored in the corresponding gns3_controller.conf file

systemctl status gns3-server

● gns3-server.service - GNS3 server
     Loaded: loaded (/lib/systemd/system/gns3-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-10-25 10:22:35 WEST; 2h 39min ago
   Main PID: 3952 (gns3server)
      Tasks: 5 (limit: 13860)
     Memory: 65.1M
     CGroup: /system.slice/gns3-server.service
             └─3952 /usr/share/gns3/gns3-server/bin/python /usr/bin/gns3server --local

Any help will be greatly appreciated! Thanks.

Regards,

Pedro

**Comment by pmsobral** [comment]
root@RedesVM:~/.config/GNS3# mv 2.2 2.2.bak
root@RedesVM:~/.config/GNS3# ln -s /home/redes/.config/GNS3/2.2 /root/.config/GNS3/2.2

solved it!

Thanks.

**Comment by e-thibault** [comment]
Sorry after a windows update I cannot start my VMs anymore on my pro laptop so for the moment I cannot provide outputs.

**Comment by stutzzzz** [comment]
recent update fixed the permission issue of opening new projects but I am unable to open old projects due to not being able to see the images. This includes new projects its also unable to locate the images.

**Comment by joohnnyf1** [comment]
please roll back these changes and go back to 2.2.49 and fix this for gods sake already!!

**Comment by e-thibault** [comment]
This issue affects already gns3 2.2.49 as the github issue #3647 states (I found it on GNS3 2.2.49).
You can yourself check that by uninstalling gns3 2.2.50 and install GNS3 2.2.49 instead :
python3 -m pip install gns3-gui==2.2.49
python3 -m pip install gns3-server==2.2.49

Personnally the version I am only sure of is GNS3 2.2.47
because I have a running install of it above ubuntu 22.04 (on my laptop)

**Comment by MaiMarti** [comment]
> I linked the 2.2 directory in the root home dir to the one with my user configs (redes) and it works now.
> 
> root@RedesVM:~/.config/GNS3# mv 2.2 2.2.bak root@RedesVM:~/.config/GNS3# ln -s /home/redes/.config/GNS3/2.2 /root/.config/GNS3/2.2
> 
> So, if the gns3server is launched at gns3-gui startup by my user and not as a service running as root in background this problem should be avoided.
> 
> Thanks.
> 
> Pedro

This solution worked for me.

I moved 2.2 to 2.2.bak
And linked my directory 2.2 to the root directory
root@host:~/.config/GNS3# mv 2.2 2.2.bak root@host:~/.config/GNS3# ln -s /home/youruser/.config/GNS3/2.2 /root/.config/GNS3/2.2

After reboot all images, projects ... work as always.

Thanks Pedro

**Comment by stutzzzz** [comment]
> > I linked the 2.2 directory in the root home dir to the one with my user configs (redes) and it works now.
> > root@RedesVM:~/.config/GNS3# mv 2.2 2.2.bak root@RedesVM:~/.config/GNS3# ln -s /home/redes/.config/GNS3/2.2 /root/.config/GNS3/2.2
> > So, if the gns3server is launched at gns3-gui startup by my user and not as a service running as root in background this problem should be avoided.
> > Thanks.
> > Pedro
> 
> This solution worked for me.
> 
> I moved 2.2 to 2.2.bak And linked my directory 2.2 to the root directory root@host: ~/.config/GNS3# mv 2.2 2.2.bak root@host: ~/.config/GNS3# ln -s /home/youruser/.config/GNS3/2.2 /root/.config/GNS3/2.2
> 
> After reboot all images, projects ... work as always.
> 
> Thanks Pedro

This worked great for me.

**Comment by pmsobral** [comment]
This was just a hack to overcome the problems caused by the initial update to the 2.2.50 version I saw in the GNS3 forum. A new update is available.  In ubuntu 22.04 I uninstalled gns3-gui and gns3-server and reinstalled them again (using apt-get) and everything works as expected now. So, you can undo the hack as it is not necessary anymore.

**Comment by grossmj** [comment]
> In ubuntu 22.04 I uninstalled gns3-gui and gns3-server and reinstalled them again (using apt-get) and everything works as expected now. So, you can undo the hack as it is not necessary anymore.

Indeed, the following packages fix the issue:

```
gns3-server-2.2.50~oracular3
gns3-server-2.2.50~noble3
gns3-server-2.2.50~jammy3
gns3-server-2.2.50~focal3
```

We are going to release v2.2.51 in a few days too.

**Comment by AlvaroLucasPerez** [comment]
i have troubles with the v2.2.51 i switch the permission and i get all the time when i try to open or create a projet.
Could not load topology /home/batoi/GNS3/projects/practica1/practica1-1.gns3: [Errno 13] Permission denied: '/home/batoi/GNS3/projects/practica1/practica1-1.gns3

**Comment by grossmj** [comment]
@AlvaroLucasPerez I need more information to help.

Do you have a systemd service running?

Use this command to find out: `systemctl status gns3-server`

**Comment by mozzy45** [comment]
@grossmj  I am also getting the error after upgrading to v2.2.51.


=> Could not load topology /home/gibson/GNS3/projects/Demo_BGP+LAB/Demo_BGP+LAB.gns3: [Errno 13] Permission denied: '/home/gibson/GNS3/projects/Demo_BGP+LAB/Demo_BGP+LAB.gns3'

Do you have a systemd service running? Yes

---
$ systemctl status gns3-server
● gns3-server.service - GNS3 server
     Loaded: loaded (/usr/lib/systemd/system/gns3-server.service; enabled; pres>
     Active: active (running) since Fri 2024-11-08 05:50:34 SAST; 9min ago
   Main PID: 1587 (gns3server)
      Tasks: 1 (limit: 14067)
     Memory: 64.6M (peak: 69.4M)
        CPU: 1.483s
     CGroup: /system.slice/gns3-server.service
             └─1587 /usr/share/gns3/gns3-server/bin/python /usr/bin/gns3server >

**Comment by grossmj** [comment]
> Do you have a systemd service running? Yes

Then stop/disable the service with `systemctl stop gns3-server && systemctl disable gns3-server` and let the GUI start the server.

**Comment by mozzy45** [comment]
Have run the above commands and when I try to create a new project I get the following error:

Could not create project directory: [Errno 13] Permission denied: '/home/gibson/GNS3/projects/mona'

--

Trying ti open an existing project and still getting the following error:


 Could not create project directory: [Errno 13] Permission denied: '/home/gibson/GNS3/projects/mona'
Could not write topology: [Errno 13] Permission denied: '/home/gibson/GNS3/projects/Demo_BGP+LAB/Demo_BGP+LAB.gns3.tmp'

**Comment by mozzy45** [comment]
Updated permissions on the projects folder to to my user and can now create new projects. But still unable to open the old projects and getting the following error:

 Could not write topology: [Errno 13] Permission denied: '/home/gibson/GNS3/projects/BGP/BGP.gns3.tmp'

**Comment by Huron** [comment]
> > Do you have a systemd service running? Yes
> 
> Then stop/disable the service with `systemctl stop gns3-server && systemctl disable gns3-server` and let the GUI start the server.

This solution works for me. Thanks a lot!

**Comment by AlvaroLucasPerez** [comment]
Hi,

Yes it is running but I am trying to do it on Windows 10 and I have all my
devices with a gns3 VM, I am doing my project but often my VM tells me that
I have a critical problem and I need to restart everything and start from
the beginning. Before I was doing it on a linux mint (ubuntu) but it has
given me a lot of problems due to permission errors.

**Comment by adioalao** [comment]
> > Do you have a systemd service running? Yes
> 
> Then stop/disable the service with `systemctl stop gns3-server && systemctl disable gns3-server` and let the GUI start the server.

     

This solution works for me too. Thanks
