### ISSUE TITLE
Short description of the bug

### ISSUE THREAD

**Issue by damirs73** [GNS3/gns3-gui#3655]
**Describe the bug**
Clean Ubuntu/Kubuntu 24.04.1LTS install, GNS3 2.2.50/51.
Docker containers can't obtain IP address via DHCP from NAT node, while static IP assignment work OK.
Other images (routers, switches, vpcs,..) and nodes work OK with DHCP.

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - GNS3 version 2.2.50/51
 - GNS3-server - local installation

**To Reproduce**
1. Create project,
2. Add docker node (toolbox, ...), add NAT node, connect them,
3. Configure docker node network settings to DHCP
4. Try ip addr, ifconfig.

**Screenshots or videos**

![gns2 2 51 docker dhcp](https://github.com/user-attachments/assets/81030beb-c898-40a9-a4d4-242dc8ee125d)

**Comment by damirs73** [comment]
Yes, prior upgrade to 2.2.49 and newer, IP DHCP for docker containers worked just fine.

**Comment by grossmj** [comment]
Please delete this folder and re-start the GNS3 server.

```
rm -rf ~/.local/share/GNS3/docker/
```

Let me know if it works.

**Comment by damirs73** [comment]
Yes, it solved issue, great!!!

Thank You very much,

Regards,

**Comment by grossmj** [comment]
This will be fixed in the next release.
