### ISSUE TITLE
Upgrading  MacOS GNS3 client to 2.2.51 not really "upgrade"

### ISSUE THREAD

**Issue by cyberdemon8** [GNS3/gns3-gui#3657]
**Describe the bug**
The client not upgrading correctly to new version

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS 15.1
 - GNS3 version: 2.2.51
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.): VM on VMware Fusion 13.6.1 installed locally on the MacBook

**To Reproduce**
Download new DMG
Open new DMG
Install over existent GNS3 2.2.50
Open new client, version not changed to 2.2.51 and error to connect to server correctly upgrade to 2.2.51

**Screenshots or videos**
![image](https://github.com/user-attachments/assets/cee5d4e8-20f3-441b-b118-82f18947acf4)
![image](https://github.com/user-attachments/assets/845a4955-cb79-481b-be32-fbdd8226ec30)

**Additional context**

**Comment by grossmj** [comment]
I just tried on my mac and couldn't find any problem. Maybe try to delete the app first in /Applications and then install v2.2.51 again?

**Comment by cyberdemon8** [comment]
By putting the app in the trash and reinstalling, the issue wasn’t resolved. I had to use a program like AppCleaner to remove all traces of the previous installation, and that worked.
Thank's for the feedback.
