### ISSUE TITLE
Ability to assign more than 64GB of RAM to a QEMU virtual machine

### ISSUE THREAD

**Issue by samy-zidelmal** [GNS3/gns3-gui#3658]
I am currently running a bare metal GNS3 installation on a server with a high amount of resources.

I need to assign 128GB of memory to one of my virtual machines but the GUI is limiting me to 64GB.
![image](https://github.com/user-attachments/assets/d519989d-3f68-4acc-9aa9-eec288a5eed8)

Would it be possible be possible to increase this limit ?

And as workaround, can I tweak the VM definition in the project files ?

**Comment by grossmj** [comment]
I didn't expect someone would want to allocated more than 64GB to a virtual machine someday. I can certainly change this for the next release.

**Comment by samy-zidelmal** [comment]
Would it be possible to get it up to 256GB or remove the limitation entirely ?
