### ISSUE TITLE
Unknown error -61605; , return code: -11

### ISSUE THREAD

**Issue by Noel265** [GNS3/gns3-gui#3661]
trying to start the Cisco router and then it shows me this error:

Dynamips hypervisor process has stopped, return code: -11
C3725 'Ghost': generic_nvram_extract_config: Unknown error -61605

**Comment by Noel265** [comment]
![Screenshot from 2024-11-19 00-47-15](https://github.com/user-attachments/assets/6020c3ac-dee1-4a54-8066-2a7349b4d89e)

**Comment by cristian-ciobanu** [comment]
@Noel265 you did not provide any information regarding
```
GNS3 version
Dynamips version
Operating system
Python version
IOS image used on this topology
```
Without this information at least is hard to troubleshoot this error.

**Comment by grossmj** [comment]
Yes, we need the image name and also how have you install Dynamips (via apt or compiled?). Thanks.
