### ISSUE TITLE
2.2.51 Unable to open Projects List or manually start any existing projects.  Images not found 

### ISSUE THREAD

**Issue by jborgas** [GNS3/gns3-gui#3665]
After upgrade from v50 to v51.  Looks very similar to the permission issues in v49.  Projects list and images all unavailable. Unable to manually open projects as the images are not reachable  

**GNS3 version and operating system (please complete the following information):**
 Unbuntu  22.04.5 LTS
 GNS3 version  2.2.51]
 Linux server only no VM in use

**To Reproduce**
Open Projects library, nothing showing
Hit Refresh nothing showing 

File, Open Project,  manually via .gns3 file  
Image file missing
Unable to open any projects

**Screenshots or videos**
![image](https://github.com/user-attachments/assets/10f67af4-7071-49ac-9440-065b4a47f124)
![image](https://github.com/user-attachments/assets/012dc75d-0f92-4ae5-b417-d4704675a333)
![image](https://github.com/user-attachments/assets/b10bf644-d0e3-489c-845c-9fd4f33b8b0c)
![image](https://github.com/user-attachments/assets/a132aee2-c5a1-4ab6-8b68-09712c1053ae)
![image](https://github.com/user-attachments/assets/c56a1fc2-e032-4801-91a5-c1a31d570d08)

**Additional context**
Path to images and projects directories are set correctly.  No change from version 2,2,50

**Comment by grossmj** [comment]
Please, can you open a browser and open [http://localhost:3080/v2/computes/local/qemu/images](http://localhost:3080/v2/computes/local/qemu/images) while GNS3 is running? Please post the content of the page here.

Thanks.

**Comment by jborgas** [comment]
No problem
![image](https://github.com/user-attachments/assets/2fcf7892-5bb7-49da-812e-1578970c6849)

Full json file here
[images.json](https://github.com/user-attachments/files/17900932/images.json)

**Comment by grossmj** [comment]
Please can you run the following commands and post their output?

```
systemctl list-units --type=service --all | grep gns3
sudo systemctl stop gns3-server
sudo systemctl disable gns3-server
```

Thanks :+1:

**Comment by jborgas** [comment]
jason@auros:~$ systemctl list-units --type=service --all | grep gns3
  gns3-server.service                                   loaded    active   running GNS3 server
jason@auros:~$ sudo systemctl stop gns3-server
jason@auros:~$ sudo systemctl disable gns3-server
Removed /etc/systemd/system/multi-user.target.wants/gns3-server.service.
![image](https://github.com/user-attachments/assets/c3405af8-2f9f-4968-b66a-4389324680cf)

Solved thanks Jeremy
