### ISSUE TITLE
[Workaround] Error during upgrade VM 2.2.51 --> 2.2.52 - "Failed to restart lvm2-lvmpolld.service: Unit lvm2-lvmpolld.socket is masked."

### ISSUE THREAD

**Issue by mlazzarotto** [GNS3/gns3-gui#3670]
**Describe the bug**
VM upgrade from 2.2.51 to 2.2.52 fails with the error in the title.

**GNS3 version and operating system:**
 - OS: Ubuntu 20.04.6 LTS
 - GNS3 version 2.2.51

**To Reproduce**
1. Launch the upgrade process to upgraded the VM from 2.2.51 to 2.2.52
![Screenshot](https://github.com/user-attachments/assets/d65a19a1-533b-44b3-adea-3e9a8b1dde5a)

**Workaround**
1. Enter Ubuntu shell on the VM
2. Type the command `sudo systemctl unmask lvm2-lvmpolld.socket`.
3. Redo the upgrade process.

**Comment by grossmj** [comment]
@mlazzarotto have you managed to find the root issue?

**Comment by mlazzarotto** [comment]
> @mlazzarotto have you managed to find the root issue?

No, I didn't search the root issue.
