### ISSUE TITLE
SSL is not supported from GUI after upgrade to v2.2.52 from v2.2.51

### ISSUE THREAD

**Issue by Zero3Dash** [GNS3/gns3-gui#3671]
GNS3 management console.
Running GNS3 version 2.2.52 on Windows (64-bit) with Python 3.10.11 Qt 5.15.2 and PyQt 5.15.11.
Copyright (c) 2006-2024 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> SSL is not supported

I can browse to the web ui fine, just cannot connect using the GUI to connect to the server using protocol https and port 443 TCP, which worked fine on v2.2.51

**Comment by grossmj** [comment]
We rely on the truststore package https://pypi.org/project/truststore/ to use the native system certificate stores. Maybe you got a problem on your system? Please can you try with v2.2.51 to see if you have the problem? Thanks!

![Screenshot from 2024-12-02 18-47-20](https://github.com/user-attachments/assets/00799a11-4a1d-4de6-a0df-6bca1acd0480)

**Comment by Zero3Dash** [comment]
On 2.2.51 its fine.
It would appear that if you use a third party certificate, that truststore v0.10.0 needs python 3.10+

**Comment by grossmj** [comment]
Ok, I am going to investigate :+1:

**Comment by grossmj** [comment]
I could reproduce the problem. It was a packaging issue with cx_Freeze, I rebuilt the Windows package: https://github.com/GNS3/gns3-gui/releases/download/v2.2.52/GNS3-2.2.52-all-in-one.exe and it worked on my side.
