### ISSUE TITLE
Swagger UI doesn't work without internet access

### ISSUE THREAD

**Issue by hossamkhader** [GNS3/gns3-gui#3674]
I tested it in an air-gapped network. It keeps trying to access the below URLs:

https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css
https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js
https://fastapi.tiangolo.com/img/favicon.png

**Comment by grossmj** [comment]
Unfortunately, Swagger UI is bundled in one of our dependencies: FastAPI

Not sure we can easily use our own Swagger UI.

**Comment by muriloglix** [comment]
> Unfortunately, Swagger UI is bundled in one of our dependencies: FastAPI
> 
> Not sure we can easily use our own Swagger UI.

It is relatively simple to keep the files statically on the server:
https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/#self-hosting-javascript-and-css-for-docs

**Comment by grossmj** [comment]
@muriloglix thanks for the link. I implemented the changes to serve static files now 👍
