### ISSUE TITLE
GNS3 server 3.0rc2 option for remote server install to bare-metal server

### ISSUE THREAD

**Issue by dhrinkino** [GNS3/gns3-gui#3676]
Hi Devs,

We really like the new version 3.0rc2. The multi-user feature is essential for us. However, we have encountered an issue.
While we appreciate that you provide the GNS3 VM, our environment relies on Proxmox. (Yes, it is possible to convert the disk image to qcow2.) However, we find the "remote server installation" approach, as described in version 2 (https://docs.gns3.com/docs/getting-started/installation/remote-server/), more suitable for our setup.

Is there any way, even unofficially, to achieve such an implementation? Or is using the GNS3 VM currently the only available option?

Thank you!

**Comment by grossmj** [comment]
@dhrinkino thanks for reaching out, we are going to add a new script or param for the existing one to install GNS3 v3 on a bare-metal server soon.

**Comment by dhrinkino** [comment]
Sounds great! Thank you so much

**Comment by grossmj** [comment]
Now you can use the `gns3-remote-install.sh` script to install version 3.0, you just have to provide an extra param to use a custom repository (ppa-v3):

```
sudo bash gns3-remote-install.sh --custom-repository ppa-v3
```

**Comment by toddgonzo74** [comment]
I'm also trying to install GNS3 v3 and am coming up against roadblocks.   

Err:8 http://ppa.launchpad.net/gns3/ppa-v3/ubuntu bionic Release
  404  Not Found [IP: 185.125.190.80 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/gns3/ppa-v3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by grossmj** [comment]
Sorry, there is no GNS3 v3 Debian package for Ubuntu Bionic. You can manually install using pypi:

```
python3 -m pip install gns3-gui==3.0.4
python3 -m pip install gns3-server==3.0.4
```

You also need Python v3.9 and install all the required dependencies (ubridge etc.)

This could be a bit complicated, the best would be to use a more recent Ubuntu release.

**Comment by toddgonzo74** [comment]
I'm currently on 20.4 LTS.. should I be on 22.4?

**Comment by grossmj** [comment]
Yes, GNS3 version 3 requires Python 3.9 or above. Also, the Debian packages are built for 22.04, 24.04 and 24.10 of Ubuntu: https://launchpad.net/~gns3/+archive/ubuntu/ppa-v3
