### ISSUE TITLE
[GNS3 3.0.0] Unable to read old data

### ISSUE THREAD

**Issue by smart2128** [GNS3/gns3-gui#3677]
**Describe the bug**
I upgraded from version 2.2.52 to the latest 3.0.0.
After launching the GNS3 GUI, I noticed that all my custom appliances were missing, and my old projects were no longer accessible.
Upon checking the preferences, I found that all the paths had reverted to their default values. To investigate further, I ran the application in debug mode and discovered that a new configuration folder had been created in ~/.config/GNS3/3.0.
I updated the preferences to point to my old paths (located on a mounted filesystem), but it seems GNS3 is still monitoring the default paths instead.

2024-12-21 19:15:14 INFO images.py:150 Discovering images in '/<HOME_DIR>/GNS3/images/IOU'
2024-12-21 19:15:14 DEBUG tasks.py:166 Monitoring for new images in '/<HOME_DIR>/GNS3/images/QEMU'
2024-12-21 19:15:14 DEBUG tasks.py:166 Monitoring for new images in '/<HOME_DIR>/GNS3/images/IOS'
2024-12-21 19:15:14 DEBUG tasks.py:166 Monitoring for new images in '/<HOME_DIR>/GNS3/images/IOU'

If I try opening an existing project it returns "The path <PROJECT_PATH> is not allowed"

**GNS3 version and operating system:**
 - OS: Linux (Arch Linux)
 - GNS3 version 3.0.0

**Comment by grossmj** [comment]
Please edit `~/.config/GNS3/3.0/gns3_server.conf` and manually configure the correct paths like this:

```
[Server]

images_path = /home/gns3/GNS3/images
projects_path = /home/gns3/GNS3/projects
appliances_path = /home/gns3/GNS3/appliances
```

Details can be found in https://github.com/GNS3/gns3-server/blob/3.0/gns3server/config_samples/gns3_server.conf

**Comment by smart2128** [comment]
Thank you @grossmj.
There was no server.conf file there, so I created it and added all custom paths.
All images have been discovered and added to the database, but they are still missing from the GUI's device list and preferences templates.
Do I have to add them manually?

**Comment by grossmj** [comment]
> Do I have to add them manually?

Unfortunately yes, we don't have anything that migrates the templates from 2.2.x to 3.0. Sorry for the inconvenience.

**Comment by smart2128** [comment]
> > Do I have to add them manually?
> 
> Unfortunately yes, we don't have anything that migrates the templates from 2.2.x to 3.0. Sorry for the inconvenience.

No worries. Thank you for your hard work.
