### ISSUE TITLE
Arch based  GNS3 3.0 and GNS3 Virtualbox VM 3.0, setup wizard

### ISSUE THREAD

**Issue by mcury1985** [GNS3/gns3-gui#3679]
Upgraded my GNS3 to version 3.0 and now setup wizard doesn't show  an option to configure a VM.
So, only local server is started.

**GNS3 version and operating system (please complete the following information):**
 - OS: EndeavourOS
 - GNS3 version: 3.0
 - Virtualbox GNS3 VM 3.0
 - virtualbox 7.1.4-2
 - virtualbox-sdk 7.1.4-2
 - virtualbox-host-modules-lts 7.1.4-11
 - libvirt 10.10.0-2

**To Reproduce**
Go to 'Setup Wizard' and no VM options will be available, only local server.

**Additional context**
Previous versions of GNS3, all I had to do was to update gns3, then download the new VM.
The VM is launching correctly through Virtualbox but I can't find an option to attach it to GNS3.

**Comment by grossmj** [comment]
> Go to 'Setup Wizard' and no VM options will be available, only local server.

The VM options were removed in version 3.0, please configure a remote controller with the IP of the VM.

![Image](https://github.com/user-attachments/assets/53c9649f-8a36-4649-bde1-71eb047269a8)

**Comment by mcury1985** [comment]
Ow, thanks, doing like this worked.
Port 80 instead of port 3080 and the VM IP.

![image](https://github.com/user-attachments/assets/b666c769-cd9a-471f-b226-941f912c4264)
