### ISSUE TITLE
[GNS3 3.0.1] Web-ui does not allow to create a project with a name containing the ":" character, but gns3-gui does

### ISSUE THREAD

**Issue by nwhisper2014** [GNS3/gns3-gui#3686]
**Describe the bug**
When creating a new project in web-ui, if you specify “:” (I didn't check the others) in the name (example: “nwhisper: test project”), the error message “Project name is incorrect” will appear. But if you do the same in gns3-gui, no error message appears and the project is successfully created.

A new project created in gns3-gui with “:” in the name then works normally in web-ui.

Probably the new project name check is different in gns3-gui and web-ui and it is better to make it the same...

**GNS3 version and operating system (please complete the following information):**
* OS: Arch Linux (the gns3-gui client is connected to the controller via HTTPS encrypted connection)
* GNS3 version: 3.0.1
* Remote GNS3 VM on VirtualBox, KVM

**Screenshots or videos**
![new-project1](https://github.com/user-attachments/assets/c4b26cb8-34a9-4d48-98c2-ccc36447302e)
![new-project2](https://github.com/user-attachments/assets/4f50cfef-32a5-4d89-bd11-688316848187)
![new-project3](https://github.com/user-attachments/assets/b5cc817f-8c04-4dae-9710-8f4c23876181)
![new-project4](https://github.com/user-attachments/assets/22baa437-d8bf-4c2d-9dad-235df5cbf8cd)

**Comment by grossmj** [comment]
Fixed. Thanks.
