### ISSUE TITLE
Uncompress IOS image doesn't work anymore

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#370]
GNS3 1.3.3, OS: Mac OS X 10.9.5 and Debian Linux 8.0 (Jessie)

I want to create a new dynamips template, the image is in my home directory:

```
behlers@dell:~$ ls -l c2691-adventerprisek9-mz.124-25d.bin 
-rw-r--r-- 1 behlers behlers 38121008 Mai 19 12:30 c2691-adventerprisek9-mz.124-25d.bin
```

This image is not in the images directory. The permissions for the image directory are OK.
```
behlers@dell:~$ ls -la GNS3/images/IOS
total 373756
drwxr-xr-x 2 behlers behlers      4096 Mai 19 13:30 .
drwxr-xr-x 5 behlers behlers      4096 Mai 19 13:26 ..
-rw-r--r-- 1 behlers behlers  97859480 Mär 30  2012 c3725-adventerprisek9-mz.124-15.T14.image
-rw-r--r-- 1 behlers behlers  81841724 Jan 19 20:12 c3725-adventerprisek9-mz.124-25d.image
-rw-r--r-- 1 behlers behlers  71528984 Feb  2 16:15 c7200-a3jk9s-mz.124-25g.image
-rw-r--r-- 1 behlers behlers 131471340 Apr 10 23:32 c7200-adventerprisek9-mz.153-3.XB12.image
```

When I start GNS3 and add this new image, GNS3 asks, if I want to copy it to the image directory, what I confirm. Afterwards the usual configuration dialogs are shown, but NOT the option to uncompress the image.

The Image is correctly installed into the image drectory:
```
behlers@dell:~$ ls -la GNS3/images/IOS
total 410984
drwxr-xr-x 2 behlers behlers      4096 Mai 19 13:35 .
drwxr-xr-x 5 behlers behlers      4096 Mai 19 13:26 ..
-rw-r--r-- 1 behlers behlers  38121008 Mai 19 13:37 c2691-adventerprisek9-mz.124-25d.bin
-rw-r--r-- 1 behlers behlers  97859480 Mär 30  2012 c3725-adventerprisek9-mz.124-15.T14.image
-rw-r--r-- 1 behlers behlers  81841724 Jan 19 20:12 c3725-adventerprisek9-mz.124-25d.image
-rw-r--r-- 1 behlers behlers  71528984 Feb  2 16:15 c7200-a3jk9s-mz.124-25g.image
-rw-r--r-- 1 behlers behlers 131471340 Apr 10 23:32 c7200-adventerprisek9-mz.153-3.XB12.image
```

When I try to uncompress the image with the GNS decompress function, I get an error: permission denied.

![ios-uncompress-err](https://cloud.githubusercontent.com/assets/896406/7702140/444b4356-fe2e-11e4-91fc-38ce60b394d3.png)

Absolutely nothing is shown in the log, even with --debug. This happens both with Mac OS X and linux (windows not tested)

**Comment by grossmj** [comment]
The permission error was the difference between:

```fd = open(ios_image, "rb")``` and ```fd = open(ios_image, "r+b")```

Fun isn't? ;)

**Comment by noplay** [comment]
Funny :)

On Wed, May 27, 2015 at 1:43 AM, Jeremy Grossmann <notifications@github.com>
wrote:

> The permission error was the difference between:
>
> fd = open(ios_image, "rb") and fd = open(ios_image, "r+b")
>
> Fun isn't? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GNS3/gns3-gui/issues/370#issuecomment-105698807>.
>



-- 

*JULIEN DUPONCHELLE*
Software Engineer

E: julien@gns3.com
LinkedIn <http://linkedin.com/in/julienduponchelle/>

<http://www.linkedin.com/in/stephenguppy>288, 200 – Rivercrest Drive SE
Calgary, AB, T2T 2X5
Twitter <http://www.twitter.com/gns3_official> | Facebook
<https://www.facebook.com/gns3official> | LinkedIn
<http://www.linkedin.com/company/gns3-net> | Google+
<https://plus.google.com/+Gns3Net/posts> | CrunchBase
<http://www.crunchbase.com/organization/gns3>
