### ISSUE TITLE
Closing gns3gui with stop /all using linux

### ISSUE THREAD

**Issue by boob4k** [GNS3/gns3-gui#374]
Hello.
I am using an gns3remote server.
I need to close gns3gui using the command line with stopping of all nodes and finishing all processes launched by project at the server side. I tried all type of signals using kill command but with no luck. Dynamips processes continues running.
Possibly i must run a specific command at gns3 server which will close all processes created by specific project with project id?

Thanks.

**Comment by noplay** [comment]
We can listen for the SIGTERM signal and close the application after closing all the communications.

**Comment by noplay** [comment]
It's done it will be in 1.4
