### ISSUE TITLE
Restrict the list of available ethernet NIO on a remote server 

### ISSUE THREAD

**Issue by boob4k** [GNS3/gns3-gui#377]
Hello.
I have remote a server. Client side i am using a cloud.
Is it possible to restrict some ports in cloud?
For example at the server side i configure that ports eth0 eth1 eth2 are not accessible and in client side they are deleted from the list.

Thanks

**Comment by noplay** [comment]
At this time it's not possible. It should not be something big to add.

**Comment by boob4k** [comment]
Can you add this feature in future releases? Thanks.

**Comment by noplay** [comment]
This issue was moved to GNS3/gns3-server#352
