### ISSUE TITLE
[feature request] sniffing for IOU

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#39]
It would be nice to have sniffing capabilities before the end of May, soon CCIEv5 will be released. I consider that this feature will make a difference.

Please take a look at:
https://github.com/Kveri/IOUsniffer

I do not think this could be hard to implement ... as long as we move the compiled binary to /usr/local/bin folder.

**Comment by grossmj** [comment]
Confirmed, this work with iouyap 0.95
