### ISSUE TITLE
GUI extension: Create File with debugging information

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#408]
How about a GUI function to create a (zip) file with the key information for debugging an issue.

This could be:
- System information (OS, OS version, GNS3 version, ...)
- GUI log
- Server log
- Topology (.GNS3 file)
- Topology as PNG file

It should be small, as otherwise people with a poor internet connectivity will have problems to upload this file.

Then we "just" have to convince the users, that issues without these informations get a lower priority.

**Comment by noplay** [comment]
I agree.

We should also add the configuration files

**Comment by ehlers** [comment]
Adding config files may raise some confidentiality concerns. I would include them only, when the user confirms.

**Comment by noplay** [comment]
Right

**Comment by noplay** [comment]
@grossmj what did you think about that?

**Comment by grossmj** [comment]
Now that we have server logs saved in a file, we can create a menu entry to export all the necessary information that should help us troubleshoot.

**Comment by ehlers** [comment]
Well, it's only the local server log, but that's a very good start. If some information is difficult to get, we can skip that. We can always ask the user to provide the missing information.

And here my next suggestion: Add the GNS3 GUI configurations and perhaps also the local server configuration.

**Comment by noplay** [comment]
I think we need to add the list of running process (for antivirus).

**Comment by noplay** [comment]
I propose to embed this in 1.4

**Comment by ehlers** [comment]
Just tried the PR https://github.com/GNS3/gns3-gui/pull/777, look very good to me, just 2 comments.
- After a fresh start of the GUI (no project opened, no temporary project directory), when you use "Export debug informations" you get an exception. Of course it's senseless to call this function at this state, but people (like me) like playing around.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.0.dev11-py3.5.egg/gns3/dialogs/export_debug_dialog.py", line 61, in _okButtonClickedSlot
    path = os.path.join(dir, filename)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```
- Can you add the .zip extension, when the debug file has got no extension ?

**Comment by noplay** [comment]
I implemented  your two feedback

**Comment by ehlers** [comment]
Perfect !!! Thanks a lot.

**Comment by noplay** [comment]
Thanks to you as always we appreciate your help
