### ISSUE TITLE
Broken load-balancing

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#419]
Review and fix.

**Comment by noplay** [comment]
About load balancing:
* What happen if a node disappear should we move the VM to another node?
* What happen if we add a node to the server pool?
* In the topology what is stored? The server pool or the chosen node.

I discover at dotscale this:
https://en.wikipedia.org/wiki/Rendezvous_hashing

It's allow a consistent distribution of keys around nodes and support a good repartition when removing and adding nodes.

**Comment by grossmj** [comment]
Well at first I was thinking doing a simple round-robin but this definitely looks interesting. Is there an implementation example?

**Comment by noplay** [comment]
I found an implementation:
https://github.com/ewdurbin/clandestined-python

But I'm worried by the fact it's use a C library.

**Comment by grossmj** [comment]
I've been able to use a pure Python implementation. However, I think in our case a load balancing based on the RAM amount would make more sense.

**Comment by noplay** [comment]
Allocate the emulator on the node with the more free ram?

Le ven. 19 juin 2015 23:05, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
Not the best load balancing support in the world but this should work. There are potential problems and inconsistencies with it in Wizard dialogs since we really allocate a specific server when a user drops a node.

I'll be implementing Rendezvous hashing load-balancing if there is a demand for it.
