### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#431]
At each start the GNS3 VM is started even if you uncheck the box.

**Comment by grossmj** [comment]
Tried and found no issue :(

**Comment by noplay** [comment]
It seem I have a more general issues. The same problem is present for the don't show it again:
![capture d ecran 2015-06-18 a 12 10 00](https://cloud.githubusercontent.com/assets/345437/8228959/2cc14cf2-15b3-11e5-8e60-065c9bdbca26.png)

**Comment by noplay** [comment]
Sometimes  you need to Apply twice for changing the settings

**Comment by noplay** [comment]
I found the issue it was tricky...
