### ISSUE TITLE
Cannot close GUI after loading a project with an inaccessible server

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#438]
I cannot close GUI after loading a project with an inaccessible server (remote or in the GNS3 VM).

**Comment by noplay** [comment]
It seem fixed. Do you have the issue with the latest version?

**Comment by noplay** [comment]
Need to test with the VM.

**Comment by noplay** [comment]
If I pause with VMware the VM I can replicate the issue

**Comment by noplay** [comment]
Not really happy but it's work. We can't use the context because closing the app is signal hell.
