### ISSUE TITLE
Allow auto upgrade of GNS3 for minor release

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#456]
We have no idea of how to do it but it could be nice

**Comment by noplay** [comment]
I'm thinking about solutions

We can add a updates folder where we create folder like:
* 1.3.8
** 1.3.8/gns3-gui
** 1.3.8/gns3-server
* 1.3.9

At startup we inject the last folder of the same version 1.3 (in our case) in path where Python look for his modules. This mean the old code is always at his original location. But I'm sure this solution as a lot of troubles.

I found also:
https://github.com/cloudmatrix/esky but it's not diff update.

Another solution could be to:
* keep the first release of the DMG (or the installed .exe) 1.3.0 for example
* when building the new release make a diff of file changed since 1.3.0 a create a zip with them
* download it an patch the application with the diff (need found a way to do this atomic)

**Comment by rednectar** [comment]
I'm not mad about the idea of "auto anything that changes stuff on the
user's machine". Auto notification - yes. And "one-click updates everything
that needs updating" - sure. But making changes because "oops - we missed
something in the last update" is NOT a good idea.

CW

**Comment by grossmj** [comment]
Hi Chris,

Thanks for the input. I agree we shouldn't do things auto-magically without users knowing about them and accepting. We are exploring ways to push minor modifications without going thru a complete release process, which is a little painful, some complains that we release too many versions ;) Web based apps have the advantage of continuous integration over desktop software, I envy that...

**Comment by noplay** [comment]
Yeah it's annoying when we solve a blocking issue for some users (for example a crash for Python 3.3 users only ) and we need to ask everyone for a complicated upgrade process.

**Comment by noplay** [comment]
The current version allow self minor upgrade but ask the user before.
