### ISSUE TITLE
Migrate symbol from old format to the new one

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#458]
Actually the symbol are like this:
:/symbols/vpcs_guest.normal.svg

But after the the drop of the hover symbol it should be:
:/symbols/vpcs_guest.svg

We need to also delete the hover_symbol key.

**Comment by grossmj** [comment]
The new VPCS symbol should be used automatically. Did you see a problem?

> We need to also delete the hover_symbol key.

I don't really want to delete anything in the setting files because if the user wants to use an older GNS3 version. We can discuss this.

**Comment by noplay** [comment]
If you open the file with the old version you have a lot of chance to break
it.

**Comment by noplay** [comment]
I found an issue in the code not related with this specific point. We use default_symbol in some part of the code.

**Comment by noplay** [comment]
Ok I missed the code for converting when reading. But I think we need an unit test on this point otherwise we will break stuff.
