### ISSUE TITLE
The  qemu_image_wizard disk size slider as a strange behavior

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#470]
When you move the slider sometimes the slider go back at the beginning.

**Comment by noplay** [comment]
I referenced in my commit the wrong issue it's the #454 fixed by 	b87244b

**Comment by noplay** [comment]
https://youtu.be/T7r0LYsL39U

**Comment by jcalano** [comment]
Don't be surprised if Cisco makes an attempt to 'acquire' you guys. Your 
work is fantastic!
