### ISSUE TITLE
IdlePC values of wellknown images not used on relative IOS images

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#471]
GNS3 V1.4.0dev1 (head = 3f132a759f3af0b186fa24e9eabd245cc1c5108c), OS: Debian Linux 8 (Jessie)

When adding a new IOS template, if I select an exting image, the idle PC values of the wellknown images (DEFAULT_IDLEPC) are not used.

When I add a new IOS image, select a new image, browse to an existing image in the IOS image directory, then it works. But when I add a new IOS image, browse to an existing image, remove the directory part to make it relative, then the wellknown idle PC value is not choosen.

It seems, that the wellknown idlepc values don't work with relative IOS images.

**Comment by noplay** [comment]
Perhaps the issue is also in 1.3.7

**Comment by ehlers** [comment]
I can't test 1.3.7 right now, but it's also in 1.3.6.

There is no selection of an existing image in 1.3.6. But when I use the browse function to select an existing image, then delete the directory part to make the image relative, the idlePC value gets not set (it's one of the well-known images). With absolute image name, the idelPC value ist correctly set.

**Comment by noplay** [comment]
It's also in 1.3.7

**Comment by noplay** [comment]
I will fix it in 1.4. The default behavior of 1.3 prevent user to make this.
