### ISSUE TITLE
1.4: Global kvm option makes it difficult to disable kvm on a single machine (e.g. ASA)

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#472]
The global option to enable kvm makes it difficult to disable KVM for a single machine (e.g. ASA), as there is no ```-disable-kvm``` qemu command line option. The best I got is the qemu option ```-machine pc,accel=tcg```, but that's difficult to remember. I haven't fully tested, if this -machine option is really the right way to switch off kvm.

The other way is to disable the kvm option globally and use the ```-enable-kvm```, the same as on v1.3. But that obsoletes the nice global kvm option.

As I know only ASA as a device, that works better without kvm, it's probably enough to add  ```-machine pc,accel=tcg``` to the default ASA command line.

**Comment by ehlers** [comment]
Update:
Through some digging in the internet I found the ```-no-kvm``` command line option to disable kvm. It works (on qemu V2.1), but that's not documented in the qemu man page (or I haven't found it).

On older qemu (tested with qemu 0.14 on Mac OS X), neither the ```-no-kvm``` nor the ```-machine``` option is supported, That makes is really difficult to disable kvm on all qemu versions.

**Comment by noplay** [comment]
When you say work better. It's crash with KVM or it's something else?

**Comment by noplay** [comment]
We plan to recommend VMware for ASA user in 1.4 it should better work for them.

**Comment by ehlers** [comment]
ASA with KVM doesn't seem to work, see https://community.gns3.com/ideas/1512

**Comment by grossmj** [comment]
> Through some digging in the internet I found the -no-kvm command line option to disable kvm. It works (on qemu V2.1), but that's not documented in the qemu man page (or I haven't found it).

It is partially documented, apparently you can see it if you type: `qemu-kvm -help | grep no-kvm` I couldn't test since I don't have qemu-kvm.

> On older qemu (tested with qemu 0.14 on Mac OS X), neither the -no-kvm nor the -machine option is supported, That makes is really difficult to disable kvm on all qemu versions.

There is not point having this option on old Qemu running on OSX or Windows since they don't support KVM anyway. The global enable KVM option is only used on Linux.

So if we want to disable KVM on a VM basis, we can either add an option to explicitly disable KVM using no-kvm or just add `no-kvm` in additional options for the ASA template. Since disabling KVM is specific to ASA, I would vote for the later.

**Comment by ehlers** [comment]
> It is partially documented, apparently you can see it if you type: qemu-kvm -help | grep no-kvm I couldn't test since I don't have qemu-kvm.
I don't have qemu-kvm either, just qemu V2.1 (on linux). The help page doesn't mention ```-no-kvm```, but it works.

> There is not point having this option on old Qemu running on OSX or Windows since they don't support KVM anyway. The global enable KVM option is only used on Linux.
Sure, what I want to say is, that you can't globally add ```-no-kvm``` to the default ASA profile, as this option is unknown to the qemu on Windows and Mac OS X and cause them to terminate. Either you add this option only on linux server, or let the user edit his ASA template and add this option (if he uses Linux with KVM).

**Comment by grossmj** [comment]
Unetlab explicitly set `-machine type=pc-1.0,accel=tcg`. This may be the way to do it.

https://github.com/dainok/unetlab/blob/7a002c1e8d9178f2635bbad9ed5c9b439d24c8e7/html/templates/asa.php#L42

**Comment by ehlers** [comment]
I haven't tried your change on Windows, but on OS X it will fail, because the "ancient" qemu v0.14 doesn't understand the ```-machine``` option.

For my own system that's no issue, I know, when and how I need to turn off KVM. But I have no idea, how to create a global template (for all systems) for qemu without KVM. That's exactly the reason for this issue.

**Comment by grossmj** [comment]
> I haven't tried your change on Windows, but on OS X it will fail, because the "ancient" qemu v0.14 doesn't understand the -machine option.

Damn Qemu! ;)

> For my own system that's no issue, I know, when and how I need to turn off KVM. But I have no idea, how to create a global template (for all systems) for qemu without KVM. That's exactly the reason for this issue.

I've added `-no-kvm` to the template and this setting is automatically stripped from the options if the server is running on another platform than Linux.

Hopefully that should do it.

Thanks,

**Comment by ehlers** [comment]
Have tested it on Linux and Mac OS X, works in both cases. Excellent !!!
