### ISSUE TITLE
vMX - one node / two qemu machines

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#474]
starting with 14.2, vMX from Juniper works with 2 qemu VMs to bring up one router.

there is one qemu VM which acts as forwarding place and another machine which acts as  management plane. these two machines need to have back to back first 3 interfaces.

It would be really nice to have this as one node under GNS3. The following will need to be incorporated under this special node:
- right click, connect to console port should connect to the console port of the qemu machine which acts as management plane.
- first 3 interfaces will need to be back to back between the two machines
- 4th interface and up should be the interfaces which connect from the node to other nodes. These interfaces should be the interfaces of the forwarding plane machine
- (optional) when using the link feature, exclude the first 3 interfaces from the node as they are always used to link back to the management plane VM.
- have an option to choose a different HDD drive for the vMP and vCP, each of these two VMs getting different RAM settings (I used 256MB for vCP and 1024MB for vMP and it works OK)

**Comment by noplay** [comment]
Interesting problem. 

Do you have a link to a documentation?

**Comment by AdrianSimionov** [comment]
Unfortunately I do not have any official documentation which I can share. I tested with a vMX version available on some shady websites. If by any chance you find it, give it a try and think maybe on a way on how to implement this as one node.

**Comment by noplay** [comment]
It's like a Blade

**Comment by grossmj** [comment]
I don't see how we could handle that special case and we didn't get many requests either.
