### ISSUE TITLE
If your enter a path for dynamips in the input field in the preferences and apply, the path is not saved

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#482]

**Comment by grossmj** [comment]
It is saved.

```cat ~/.config/GNS3/gns3_gui.conf | grep dynamips
        "dynamips_path": "/usr/local/bin/dynamips2",
```

However I have something in place to detect if the path is valid when loading the settings. If not, a new Dynamips path is searched: https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/dynamips/__init__.py#L121

This is the case for all other paths (e.g. vboxmage, vmrun etc.)
