### ISSUE TITLE
If I add an IOU node without configuring the iourc I need to configure the iourc and restart the application

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#485]
It's not a regression I think it's already the case with previous version.

We should the iourc with the start command. Not just the create.

**Comment by grossmj** [comment]
I've not found the problem. I remove the iourc path in the preferences, then add an IOU node, start it and get the message `Server error from http://127.0.0.1:8000: IOU1: Could not find an iourc file (IOU license)`. I can start the IOU node when I add back the iourc path in the preferences.

**Comment by noplay** [comment]
Strange

**Comment by grossmj** [comment]
I can confirm the bug by starting from scratch (no previous gns3_gui.conf).

**Comment by grossmj** [comment]
We send the iourc content only when a device is created. We should have a separate way to send it (not tied to an IOU device settings).

**Comment by noplay** [comment]
I will send also the iourc with the /start
