### ISSUE TITLE
Improve https security by checking self generated certificates

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#488]
Https greatly enhances the security of the connection between client and server, but for self created certificates the client doesn't verify the server certificate. This makes this connection an easy target of a man-in-the-middle attack.

In a perfect world, everyone would use official certificates, but I assume that for GNS3 client/server connections the self generated certificates will be the normal case. As the SSL library can't verify them, the  _handleSslErrors function in servers.py is called. The user has normally no other choice as to accept the warning. Further SSL errors (from this server) will then be ignored.

My idea is to behave more like browsers:

- if no server certificate has been seen before  
  Ask the user for permission and then save that certificate
- if the remote certificate matches the saved certificate  
  Accept SSL connection
- if remote certificate differs from saved certificate  
  Issue big fat warning and after entering the first 100 digits of PI, the user can accept that new certificate

That way only during the first time connection the security can be harmed. If the user confirmation shows the first bytes of the certificate, the user can be very sure, that he connects to the right server.

Another way would be to instruct the user to add the server certificate into it's system certificate store. But every system works differently and I think it's too complicated.

**Comment by noplay** [comment]
Yeah adding a new root certificate is a bad idea for most user.

**Comment by noplay** [comment]
We can store the digest of the certicate:
http://doc.qt.io/qt-4.8/qsslcertificate.html#digest

And accept only this certificate.

**Comment by ehlers** [comment]
That sounds very good, comparing the digest is perfect.

**Comment by noplay** [comment]
It's fixed thanks for the feedback!
