### ISSUE TITLE
qemu-system-x86_64: Failed to start VNC server on `127.0.0.1:-3899': can't convert to a number: -3899

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#490]

**Comment by noplay** [comment]
It seem our trick no longer work with recent qemu build :(

https://bugs.launchpad.net/qemu/+bug/1388735

**Comment by noplay** [comment]
My proposal. If it's a VNC console we search a free console port in the range 5900-6000 and we use that.

In the console range settings we add a comment about the fact 5900 -> 6000 is use by qemu VNC you should not use this range, but you need to open this range in your firewall. Or we can display an error if user try to use it.

**Comment by grossmj** [comment]
Arghh... this will complicate things. Damn you Qemu!

> My proposal. If it's a VNC console we search a free console port in the range 5900-6000 and we use that.

The advantage of the trick is that the user could switch from Telnet console to VNC without changing port. Now we must handle VNC ports explicitly :(

> In the console range settings we add a comment about the fact 5900 -> 6000 is use by qemu VNC you should not use this range, but you need to open this range in your firewall. Or we can display an error if user try to use it.

I would go for the warning message + tooptip in the preferences.

**Comment by grossmj** [comment]
Problem solved in https://github.com/GNS3/gns3-server/commit/442aa31065660c1a8bff856e35fcf139f3312c52 and https://github.com/GNS3/gns3-gui/commit/be75dc95a36c2fa3f3e2e72dbbe7bce53a0ac13e
