### ISSUE TITLE
Mac OS X: cx_Freeze app crashes on first start

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#495]
GNS3: V1.4.0dev1, OS: Mac OS X 10.9.5

Previously I'm using 1.3.7 on my iMac. Today I downloaded GNS3-unstable.2015-07-05.dmg, deleted the previous GNS3.app and copied the new version to the /Applications folder.

On the first start of the app the OS asks for permission to run, afterwards the application just stops running. On the next try everything is fine, the application runs as expected.

I tried several times, it's reproducible. Everytime I copy the app out if the dmg, the first start fails. It doesn't matter, if the old .config/gns3.net exists or not, or if the new .config/GNS3 exists or not. It doesn't happen with the 1.3.x version, no matter if I use the official 1.3.7 or the GNS3-stable.2015-07-05.dmg .

When the app stops running no log file is created and the OS doesn't show anything, the app just ends. I would expect the “unexpectedly quit” dialog box, but that isn't shown. The only info is one entry in /var/log/system.log:

```
Jul  5 11:04:31 iMac com.apple.launchd.peruser.501[251] ([0x0-0x8e08e].net.gns3[1265]): Exited with code: 2
```

If the first start of GNS3 is done via terminal, it works. If I then start it from the finder, it asks for permission, then crashes. So this first time permission question seems to irritate the app.

**Comment by noplay** [comment]
Probably something related to cx_freeze

**Comment by noplay** [comment]
Same issue if you start the application with _open /Applications/GNS3.app_

**Comment by noplay** [comment]
I found a second error in the log:
```
05/07/2015 22:19:09,788 CoreServicesUIAgent[92990]: unexpected message <OS_xpc_error: <error: 0x7fff70d08c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff70d08f70> { length = 18, contents = "Connection invalid" }
}>
```

**Comment by ehlers** [comment]
I just looked in my logs, I don't have that error message.

**Comment by noplay** [comment]
Perhaps it's an error message specific to Yosemite but not related to our issue.

This work:
open /Applications/GNS3.app --args --debug

**Comment by ehlers** [comment]
Cormfirm, that "open /Applications/GNS3.app --args --debug" works. Strange and unfortunate, that makes debugging harder.

**Comment by noplay** [comment]
Interesting:

First launch
➤  open /Applications/GNS3.app --args --dzezefez
Nothing in the console

Second launch
➤  open /Applications/GNS3.app --args --dzezefez
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/GNS3.app.

So we have the same behavior when we use the --args options with an invalid options. I suspect at first launch we received an additional parameter.

**Comment by ehlers** [comment]
It get's really strange: I started GNS3 with an initial project
open /Applications/GNS3.app --args /Users/behlers/GNS3/projects/tap/tap.gns3

This works even on the first launch

**Comment by ehlers** [comment]
With the initial project argument, we can see the arguments even on first launch, can't see any additional arguments.

```
/Users/behlers# ps x | grep gns3
  964   ??  S      0:01.50 /Applications/GNS3.app/Contents/MacOS/gns3 /Users/behlers/GNS3/projects/tap/tap.gns3
  969   ??  S      0:00.58 /Applications/GNS3.app/Contents/MacOS/gns3server --host=192.168.1.10 --port=8000 --local --log=/Users/behlers/.config/gns3.net/gns3_server.log
  986 s000  S+     0:00.00 grep gns3
```

**Comment by noplay** [comment]
I found it. At first launch we receive this:
['/Applications/GNS3.app/Contents/MacOS/gns3', '-psn_0_7173847']%

http://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder

**Comment by ehlers** [comment]
Good find !!! I don't get it, why it is passed only the first time. But I don't want to dig too deep into OS X.

**Comment by noplay** [comment]
Will be fixed in the next release. How Apple could think it's a good idea to add extra parameter

**Comment by ehlers** [comment]
Tested, works perfectly. Many thanks.

**Comment by noplay** [comment]
Thanks for the report it was tricky.
