### ISSUE TITLE
1.4, Mac OS X: qemu binaries not found

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#496]
GNS3: V1.4.0dev1, OS: Mac OS X 10.9.5

I know that qemu is no longer recommended to run on OS X, but currently it behaves quite strange.

I can use the qemu templates of 1.3 to drag a qemu VM into a topology and run it without problems. But I can't edit the VM, it says that it doesn't find the qemu binary and the binary list is empty.
![qemu_not_found](https://cloud.githubusercontent.com/assets/896406/8511174/0731238e-230c-11e5-8155-35d487d6013b.png)

The binary is there, it's just not in the binary file list:
```
/Users/behlers/.config/GNS3# ls -l /Applications/GNS3.app/Contents/Resources/qemu/bin/qemu-system-i386
-rwxr-xr-x@ 1 behlers  admin  3266348  5 Jul 09:47 /Applications/GNS3.app/Contents/Resources/qemu/bin/qemu-system-i386*
```

Here the template configuration (out of gns3_gui.conf):
```
            {
                "acpi_shutdown": false,
                "adapter_type": "e1000",
                "adapters": 1,
                "category": 2,
                "console_type": "telnet",
                "cpu_throttling": 0,
                "default_symbol": ":/symbols/qemu_guest.normal.svg",
                "first_port_name": "",
                "hda_disk_image": "/Users/behlers/GNS3/images/QEMU/TinyCore.qcow2",
                "hdb_disk_image": "",
                "hdc_disk_image": "",
                "hdd_disk_image": "",
                "hover_symbol": ":/symbols/qemu_guest.selected.svg",
                "initrd": "",
                "kernel_command_line": "",
                "kernel_image": "",
                "legacy_networking": true,
                "mac_address": "",
                "name": "TinyCore",
                "options": "-vga none -vnc none",
                "platform": "",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "process_priority": "normal",
                "qemu_path": "/Applications/GNS3.app/Contents/Resources/qemu/bin/qemu-system-i386",
                "ram": 256,
                "server": "local",
                "symbol": ":/symbols/qemu_guest.svg"
            }
```

So i symlinked the qemu binaries to /usr/local/bin. Now I can create new qemu templates and I can select the binaries from /usr/local/bin. But I still can't edit existing templates or configure nodes creating by 1.3 templates. GNS3 still can't find the qemu binary and as the qemu binary list is still empty I can't select the binaries from /usr/local/bin.

**Comment by noplay** [comment]
I confirm the issue

**Comment by noplay** [comment]
The server seem to not return the embed qemu binaries only binaries install via homebrew.

**Comment by noplay** [comment]
It should be fixed in the next build

**Comment by noplay** [comment]
Thanks for the report

**Comment by ehlers** [comment]
Yes, that did it, may thanks.

**Comment by noplay** [comment]
Thanks for testing :)
