### ISSUE TITLE
1.4, Mac OS X: initial configuration setting not migrated to new .config/GNS3

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#498]
GNS3: V1.4.0dev1, OS: Mac OS X 10.9.5

While the base_configs directory is copied from the old .config/gns3.net to .config/GNS3, the settings in the templates are not migrated. The initial configuration settings of IOS, IOU and VPCS still use the old directory .config/gns3.net .

**Comment by noplay** [comment]
It's not clean but it's actually work because we didn't delete the old ~/.config/gns3.net. But it's better to clean the configuration.

**Comment by grossmj** [comment]
Well, the new location for base configs is only used when you add new VM template in the preferences. All templates made before 1.4 will continue to use the old location.

I don't think it is worth the trouble to migrate these.
