### ISSUE TITLE
1.4, Mac OS X: Please bundle ubridge with the dmg

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#499]
GNS3: V1.4.0dev1, OS: Mac OS X 10.9.5

The GNS3-unstable.2015-07-05.dmg doesn't contain ubridge. While it's not difficult to download and install it, it would be more user friendly to add it to the dmg.

**Comment by noplay** [comment]
I think we are not packaging it also with Windows ans Linux package.

**Comment by ehlers** [comment]
Well, the linux guys are used to install extra packages, but the windows and OS X user are mostly helpless, when it's not easily available.

As VMware Fusion is not supported on OS X (at least not in V1.4), it's not necessary to include it. But it won't harm and there may be some uses besides VMware.

For Windows I think it really should be included, as VMware integration is **THE** new feature.

**Comment by grossmj** [comment]
We intend to use ubridge for Qemu to dynamically add/remove links and support packet capture. I confirm it is present in the Windows package.

**Comment by noplay** [comment]
I just test and ubridge is missing in last Windows package or not found.

**Comment by noplay** [comment]
Ubridge should be available on OSX in next nightly build and also the source is shipped with the big zip.

**Comment by ehlers** [comment]
Ubridge is included in GNS3-unstable.2015-07-07.dmg, so OS X is fine. I can't test the windows installer.

**Comment by noplay** [comment]
Thanks I will make the change  for Windows
