### ISSUE TITLE
[Feature Request] - Bouncing a link to the cloud

### ISSUE THREAD

**Issue by ak2766** [GNS3/gns3-gui#50]
When I'm using tap interfaces on my host system to connect the topology to my LAN, quite often the link to the cloud will stop working and the 2-step process of deleting the link then re-creating it solves the issue.  To save time, it would be best if there was an option in the link context menu to bounce it - disconnect and reconnect in one step.

**Comment by noplay** [comment]
You should not have the tap issue in 2.0
