### ISSUE TITLE
1.4, Mac OS X: VMware not installed: Error message when saving configuration

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#500]
GNS3: V1.4.0dev1, OS: Mac OS X 10.9.5, QT: 5.4.2

Disclaimer: I didn't really uninstall VMware Fusion, I just moved it to another location to simulate a system without VMware. If this problem doesn't show up, when VMware is really uninstalled, I beg for pardon.

When applying the configuration or exiting the configuration mode and VMware is not installed an error message is displayed:
![vmrun_does_not_exist](https://cloud.githubusercontent.com/assets/896406/8512069/fd95b380-2333-11e5-9c32-cff08e13792c.png)

On Linux (QT 5.3.2), you can fill in a blank path to vmrun (in VMware preference) and no error is shown. When there is no vmrun in $PATH, that's even the default. You can even configure any junk as the vmrun path without creating an error message (maybe that should be changed, but that is another story).

OS X instead insists to have a valid path, otherwise it shows this error message. An empty string is not OK. So what to fill in, if you haven't installed VMware ??? You can add a path to a dummy file, just to silence GNS3, but that's not really user friendly.

Can the different QT version on Mac OS X (5.4.2) and linux (5.3.2) be the reason for the different behavior? Anyway, there should be no error message, when VMware is not installed.

**Comment by grossmj** [comment]
It should have been fixed in https://github.com/GNS3/gns3-gui/commit/7007f3ea447f6e45d067ba6ce5dc306b66fdccee

**Comment by ehlers** [comment]
Almost done ...

Now GNS3 accepts an empty string and stores it into gns3_gui.conf . But on the next start GNS3 sees the empty vmrun path and fills it with the default /Applications/VMware Fusion.app/Contents/Library/vmrun and then the fun starts again.

**Comment by grossmj** [comment]
Ok, should be good now: https://github.com/GNS3/gns3-gui/commit/c4c17aa1151b733fc8eed6e127561964f49f4143
