### ISSUE TITLE
Make it clear that VMware Fusion is not supported

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#501]

**Comment by grossmj** [comment]
Let me know if we need something clearer.

**Comment by ehlers** [comment]
I just tested with GNS3-unstable.2015-07-06.dmg (from 07:49 UTC) and I don't see a warning when I create a VMware template or use that template.

**Comment by noplay** [comment]
I confirm the problem. The issue is we check the VMware setting on server page. But if you use the local server only we skip this page.

**Comment by noplay** [comment]
Should be fix in next build

**Comment by ehlers** [comment]
Just noticed, that the checkbox "Use the local server" in the VMware preference is grayed out on darwin. Is that intentional ? That way even an remote VMware server is not possible.

**Comment by noplay** [comment]
Right

**Comment by noplay** [comment]
Fixed in 0f6b4f2b3244118d31deef43090ecb8536aa1e17
