### ISSUE TITLE
VMware fusion support

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#502]
I open this ticket in order to explain the issues with VMware Fusion.

**Comment by grossmj** [comment]
Details can be found in https://community.gns3.com/community/forum/blog/2015/05/08/vmware-support-in-gns3.

In summary:

```
The vmnet interfaces created by VMware Fusion do not support the technology used by libpcap read/write packets (i.e. there is no BPF support, please see my post on our old forum for details: http://forum.gns3.net/post26024.html#p26024). Other applications like Wireshark cannot attach as well.

This means that the only way to network VMware Fusion VMs is to use a bridge to add vmnet interfaces and install the tuntap driver to have other emulators use TAP interfaces. But there is more! by default the tuntap driver is limited to 16 interfaces, this is just a simple limit in the source code that you can patch and recompile.
```

Supporting VMware Fusion will be quite tricky but not impossible.

**Comment by noplay** [comment]
If the VMware team follow the same schedule as for VMware fusion 7 we should see a technology preview release for VMware fusion 8 in the coming days and a new release in september/october just in time for el captain  release.

The VMware fusion policy on OSX support is to support just the last two OSX release.

We can pray for a BPF support but I don't think it's on their roadmap..

**Comment by noplay** [comment]
The VMware preview as no support for BPF.

**Comment by noplay** [comment]
Clues about how vmware vmnet work:
https://github.com/alouche/vmware-vmnet-3.2-kernel/blob/e1748a52ec4457b6ace0775e82e8728c8351927a/driver.c
https://github.com/alouche/vmware-vmnet-3.2-kernel/blob/master/vnet.h

It seem the source code for fusion is available because we can see references to APPLE.

**Comment by grossmj** [comment]
https://community.gns3.com/thread/14648

**Comment by grossmj** [comment]
Implemented with the help of the VMware Fusion team.

https://community.gns3.com/community/forum/blog/2015/05/08/vmware-support-in-gns3#comment-13591
