### ISSUE TITLE
Remote GNS3 VM

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#506]
I don't know if this is a good idea but we could add the possibility to have the GNS3 VM run on another host. What is only needed is a host/IP address configured by the user. The major advantage over defining a remote server is that an IP address isn't saved in the project file which increase portability.

**Comment by noplay** [comment]
Perhaps we can replace the notion of VM by something more generic like master server (the vm, a cloud server).

**Comment by grossmj** [comment]
I think we have the following options:

- Rename the tab in Preferences from "GNS3 VM" to "Local GNS3 VM" to avoid confusion when an user install the GNS3 VM on a remote ESXi for instance. A remote server entry should be added in that case.

- Have an IP/host entry in the GNS3 VM settings. This may create unnecessary complexity. Only added advantage is that an IP address/host isn't saved in project files which increase portability.

- We should provide an user friendly way to change the IP/host for servers in project files. Again this comes down to have better portability.

**Comment by noplay** [comment]
Agree to all.

Perhaps we can add an ID on server and having a mapping in the client for changing the IP assigned to an id.

**Comment by grossmj** [comment]
Closing this since we don't want to create unnecessary complexity by introducing a remote GNS3 VM concept.

**Comment by huangyihe2016** [comment]
can a client connect a vm on a remote computer

**Comment by noplay** [comment]
Yes like a local installation
