### ISSUE TITLE
bug vpcs

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#508]
Bonjour

Sur Linux, 
j'utilise 
- la version de vpcs du dépot de gns3 (je suppose qu'elle est plus récente que "l'originale")
- la version stable de développement de gns3

Je crée le schéma suivant :
VPCS1 --- (ethernet switch) -- VPCS2
Je démarre le réseau, je configure les VPCS et je fait des pings. Cela fonctionne.

A chaud (sans rien éteindre), je retire le (ethernet switch) que je remplace par un nouveau (ethernet switch)
Les pings entre les 2 VPCS ne fonctionnent plus,

**Comment by noplay** [comment]
Bonjour, 

C'est sur la 1.3.7 ?

Effectivement on devrait pas autoriser à refaire les lien ethernet à chaud vu que VPCS le supporte pas.

**Comment by Raizo62** [comment]
la version stable sur github.....1.3.8dev, il me semble...

Désolé, je n'avais pas remarqué qu'on ne pouvait pas reconnecter les VPCS.....

Par contre, cela ne me semble pas une bonne idée d’empêcher de refaire les liens vpcs (initialement, je voulais remplacer le switch par un autre type de "switch").
Une solution éventuelle: N'est il pas possible que le système ne retire pas réellement les liens sur les vpcs. Cela permettrait de pouvoir les reconnecter ensuite ailleurs ?

**Comment by grossmj** [comment]
Une solution serais d'ajouter un hypervisor mode dans VPCS pour pouvoir ajouter/enlever des liens a chaud... mais on peut aussi utiliser uBridge pour gerer cela + ajouter la capture de paquets comme on a l'intention de le faire pour les VMs Qemu.

**Comment by noplay** [comment]
Moi je vote pour qu'on fasse tout les liens à terme via ubridge et ainsi avoir un programme unique où on peut ajouter des features  comme de la perte de paquet.

**Comment by grossmj** [comment]
uBridge va etre implementer dans 1.4. Je ferme ce ticket car nous en avons deja un plus general: https://github.com/GNS3/gns3-server/issues/267
