### ISSUE TITLE
At the end of the wizard I need to apply settings for Qemu 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#515]
If I didn't click on apply the settings are lost

**Comment by grossmj** [comment]
Yes, I didn't find a way to automatically accept the settings and close the preferences dialog.

**Comment by noplay** [comment]
Often I forgot to push the Apply button it's a bit strange because we already confirm action in the Wizard. Also it's strange that the OK button doesn't apply the settings.

It's probably a Big change. But what did you think about. When I arrive at the end of a device the Wizard save the device settings and emit a signal allowing the preference windows to refresh. After all you already confirm your action during the wizard.

This will allow us to have device wizard independent  of the PreferenceDialog.

**Comment by grossmj** [comment]
Do you want to look at this?
