### ISSUE TITLE
Preferences menu always open the wizard on OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#516]
I can no longer access to the preferences it's always the setup wizard

**Comment by grossmj** [comment]
That must be some OSX magic because I don't have the issue here ;)

**Comment by noplay** [comment]
Qt has something magic. TextHeuristicRole ...

**Comment by noplay** [comment]
![Giphy](http://media0.giphy.com/media/gT8F4peUvNYUo/giphy.gif)
