### ISSUE TITLE
Support for VirtualBox 5.0

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#520]
Validate that VirtualBox 5 works in GNS3.

**Comment by noplay** [comment]
Work on OSx

**Comment by noplay** [comment]
And it's faster :)

**Comment by noplay** [comment]
Support the detachable mode could be nice :D

**Comment by noplay** [comment]
I think it's ok we can close the issue. What did you think about that @grossmj ?

**Comment by grossmj** [comment]
So far I had no issues using VirtualBox 5.

I noticed Windows 10 users must use this version because there is a problem in VBox 4.
