### ISSUE TITLE
Remote servers not saved

### ISSUE THREAD

**Issue by astoffel** [GNS3/gns3-gui#521]
1.4.0 alpha 1

When opening and closing the Windows GUI does not keep the remote server setting.

**Comment by astoffel** [comment]
Deleted gns3_gui.ini file and let 1.4 build it again, saving preferences now .

**Comment by noplay** [comment]
Didn't see the same issue but I lost my remote server during the migration

**Comment by noplay** [comment]
Hmm something erase the server section after the migration

**Comment by noplay** [comment]
I think I fix your issue thanks !
