### ISSUE TITLE
Start of GNS3 VM doesn't work with VirtualBox

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#530]
GNS3: 1.4.0alpha1, OS: Mac OS X V10.9.5

I know it's not recommended to use VirtualBox for the GNS3 VM, but it looks, that no-one ever has tried this. I think, I have found several errors in this function:

1. A NAT rule is created with a random port, but in utils/wait_for_vm_worker.py line 204 this port isn't used, instead the default port (e.g. 8000) is used.
2. when I use vm_server.setPort(port) to overcome this, only _port is set in http_client.py, _http_port remains the old value. Btw. why are there 2 port variables _port and http_port ?
3. http_client.py, line 329 creates an AttributeError: 'list' object has no attribute 'get'
4. vm_server.getSynchronous wait max. 2 seconds, it's unusual that a VM boots that fast
5. Wouldn't it be nicer to remove the temporary NAT rule after use (in utils/wait_for_vm_worker.py) ? As far as I understood this, this NAT port is only used once to get the IP list from the GNS3 VM, afterwards it's not used anymore.

The following patch solves the first 3 issues, but I'm unsure about that _port and _http_port stuff in http_client.py. For the fourth issue (timeout too short) I don't have a really elegant solution, so I leave it to you. The fifth issue is just nice to have.

```
diff --git a/gns3/http_client.py b/gns3/http_client.py
index dea053f..f4ac409 100644
--- a/gns3/http_client.py
+++ b/gns3/http_client.py
@@ -152,6 +152,7 @@ class HTTPClient(QtCore.QObject):

     def setPort(self, port):
         self._port = port
+        self._http_port = port

     def protocol(self):
         """
@@ -326,7 +327,7 @@ class HTTPClient(QtCore.QObject):
                 if content_type == "application/json":
                     content = response.read()
                     json_data = json.loads(content.decode("utf-8"))
-                    local_server = json_data.get("local", False)
+                    # local_server = json_data.get("local", False)
                     return response.status, json_data
             else:
                 return response.status, None
diff --git a/gns3/utils/wait_for_vm_worker.py b/gns3/utils/wait_for_vm_worker.py
index 80269bf..8ff0992 100644
--- a/gns3/utils/wait_for_vm_worker.py
+++ b/gns3/utils/wait_for_vm_worker.py
@@ -199,7 +199,9 @@ class WaitForVMWorker(QtCore.QObject):
                 if not self._is_running:
                     return

+                vm_port = vm_server.port()
                 vm_server.setHost(ip_address)
+                vm_server.setPort(port)
                 # ask the server all a list of all its interfaces along with IP addresses
                 status, json_data = vm_server.getSynchronous("interfaces", timeout=120)
                 if status != 200:
@@ -214,6 +216,7 @@ class WaitForVMWorker(QtCore.QObject):
                     if "name" in interface and interface["name"] == "eth{}".format(hostonly_interface_number - 1):
                         if "ip_address" in interface:
                             vm_server.setHost(interface["ip_address"])
+                            vm_server.setPort(vm_port)
                             log.info("GNS3 VM IP address set to {}".format(interface["ip_address"]))
                             hostonly_ip_address_found = True
                             break
```

**Comment by noplay** [comment]
_port and _http_port are something related to SSH tunnel. In our case it should be the same.

**Comment by ehlers** [comment]
Oh, I understand. But even when they are the same, it's puzzling to mix them. In http_client.py in two debug logs _port is used, everywhere else _http_port is used (including 2 other debug logs).

**Comment by noplay** [comment]
I will fix the debug log

**Comment by noplay** [comment]
Thanks it's fixe. I think we broke it in the last days :(

**Comment by ehlers** [comment]
Well, I tested the last hour. It works, if the GNS3 VM is already active, but it doesn't work if the GNS3 VM is inactive. In that case the debug log says:

```
2015-07-11 00:57:11 DEBUG wait_for_vm_worker.py:196 Adding GNS3VM NAT port forwarding rule with port 51240 to interface 2
2015-07-11 00:57:11 DEBUG gns3_vm.py:84 Executing VBoxManage with command: ['/Applications/VirtualBox.app/Contents/MacOS/VBoxManage', '--nologo', 'controlvm', 'IOU-VM', 'natpf2', 'GNS3VM,tcp,127.0.0.1,51240,,8000']
2015-07-11 00:57:11 DEBUG http_client.py:314 Synchronous get http://127.0.0.1:51240/v1/interfaces with user
2015-07-11 00:57:30 DEBUG http_client.py:337 Error during get on 127.0.0.1:51240: ''
```

I traced with wireshark:
![wireshark_start_gns3vm](https://cloud.githubusercontent.com/assets/896406/8630712/976c17b8-2769-11e5-90d4-95773250a6bd.png)
About 1.5 seconds after the VM starts, the HTTP connection to get the interface list is established. At that time the boot loader is not even done. After about 20 seconds the linux is booted and the interfaces are set up. At that time the HTTP connection gets reset.

If you immediately retry, you again get a connection reset. You have to wait until the gns3server has been started and it listens for requests. On my computer that takes about 2 seconds.

So i modified utils/wait_for_vm_worker.py to check if the first request got closed, then wait 5 seconds (to be on the safe side), then try again. With that modification, I get 10 successful VM starts out of 10.

Here my changes: I used sleep, because it was easy. But I heard that this is not a good way to wait, because the GUI stops responding during that time. Look at my changes as a test, how to make this stuff work.
```
diff --git a/gns3/utils/wait_for_vm_worker.py b/gns3/utils/wait_for_vm_worker.py
index 9cd889e..a2b3218 100644
--- a/gns3/utils/wait_for_vm_worker.py
+++ b/gns3/utils/wait_for_vm_worker.py
@@ -204,6 +204,12 @@ class WaitForVMWorker(QtCore.QObject):
                 vm_server.setHost(ip_address)
                 # ask the server all a list of all its interfaces along with IP addresses
                 status, json_data = vm_server.getSynchronous("interfaces", timeout=120)
+                # Retry, if TCP connection dropped
+                if status == 0:
+                    import time
+                    time.sleep(5)
+                    status, json_data = vm_server.getSynchronous("interfaces")
+
                 if status != 200:
                     msg = "Server {} has replied with status code {} when retrieving the network interfaces".format(vm_server.url(), status)
                     log.error(msg)
```

**Comment by ehlers** [comment]
Next version, this time it re-tries every second up to 10 times.

```
diff --git a/gns3/utils/wait_for_vm_worker.py b/gns3/utils/wait_for_vm_worker.py
index 9cd889e..eee208a 100644
--- a/gns3/utils/wait_for_vm_worker.py
+++ b/gns3/utils/wait_for_vm_worker.py
@@ -22,6 +22,7 @@ Thread to wait for the GNS3 VM.
 import os
 import socket
 import subprocess
+import time

 from ..qt import QtCore
 from ..version import __version__
@@ -204,6 +205,13 @@ class WaitForVMWorker(QtCore.QObject):
                 vm_server.setHost(ip_address)
                 # ask the server all a list of all its interfaces along with IP addresses
                 status, json_data = vm_server.getSynchronous("interfaces", timeout=120)
+                # Retry, if TCP connection drops
+                retry = 10
+                while status == 0 and retry > 0:
+                    retry -= 1
+                    time.sleep(1)
+                    status, json_data = vm_server.getSynchronous("interfaces")
+
                 if status != 200:
                     msg = "Server {} has replied with status code {} when retrieving the network interfaces".format(vm_server.url(), status)
                     log.error(msg)```

**Comment by ehlers** [comment]
It doesn't really belong to this issue, but I personally like to have the option to use a bridged network instead of host-only. This patch allows it, feels free to use it or not.

```
--- gns3/utils/wait_for_vm_worker.py.retry	2015-07-11 09:05:23.000000000 +0200
+++ gns3/utils/wait_for_vm_worker.py	2015-07-11 09:39:17.000000000 +0200
@@ -165,7 +165,9 @@

                 hostonly_interface_number = self._look_for_interface("hostonly")
                 if hostonly_interface_number < 0:
-                    self.error.emit("The GNS3 VM must have a host only interface configured in order to start", True)
+                    hostonly_interface_number = self._look_for_interface("bridged")
+                if hostonly_interface_number < 0:
+                    self.error.emit("The GNS3 VM must have a host-only or bridged interface configured in order to start", True)
                     return

                 vm_state = self._get_vbox_vm_state()
/Users/behlers/GNS3/GNS3/gns3-gui#
```

**Comment by noplay** [comment]
I opened a new issue for the bridged interface

**Comment by noplay** [comment]
Fixed with a retry function

**Comment by ehlers** [comment]
Thanks for the changes and the creation of a new issue for the bridged network.

While that wait for the vm start works quite well, let me suggest two changes:
- The start of the VM can't be aborted. You can cancel the wait for the VM in the GUI, but the GUI becomes unresponsive until the _getInterfaces function is done.
- Currently the exit criteria in the _getInterfaces function is ```status == 200```. If the server replies with another status, e.g. 401 (because the authentication doesn't match) the user has to wait the full 120 retries. I suggest ```status != 0``` as an abort criteria. That way only TCP connection problems are retried. Another way would be to exit this loop on common status codes (200, 401, ...).
