### ISSUE TITLE
Make the migration from IOUVM smoother

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#531]
Today it's painful for a 1.3  user with IOUVM  to switch from 1.3 to 1.4

Many issues:
* You need to backup and restore projects & images (https://github.com/GNS3/gns3-server/issues/259)
* You need to drop the IOU VM remote server in favor of the GNS3 VM in the settings
* You need to patch all your topologies using the IOUVM in order to drop the remote IOU server and use the GNS3 VM instead

You can't upgrade the IOUVM to 1.4 due to the lack of Python 3.4 support. This mean if we want to improve something in the IOUVM to make transition more easier it should be on the 1.3.X branch.

**Comment by noplay** [comment]
The first issue backup & restore is not complicated, I don't see something blocking us expect perhaps the need to stream the zip creation and uncompress.

**Comment by noplay** [comment]
The point 2 & 3 are more complicated because we don't have a way to be sure the remote server in settings or in topology is an IOUVM server.

# Proposal

## Data migration

Manually by the user:
https://github.com/GNS3/gns3-server/issues/259

## Settings 
When we convert settings from 1.3 to 1.4 we can ask user for conversion if:
* IOU is not running on local server
* Only IOU is running on a remote server

If the user say yes we:
* drop the old server
* setup IOU for using the GNS3 VM

## Topologies conversion
When we open a topologies created with a GNS3 version < 1.4. If IOU devices exists we can ask if the user want to user the GNS3 VM instead of the current. It's doesn't mean we move data but we fix the content of the .gns3 to use the new server

**Comment by ehlers** [comment]
Just an idea for the data migration:

In case the migration needs more then a simple command in the IOU server:

Create a tool, lets name it gns3-iouvm-migration, that runs with python 3.3 (and 3.4). The user installs it in the IOU VM with "pip install gns3-iouvm-migration" and then runs it.

That way you don't have to modify the 1.3 version of gns3-server to support the migration.

**Comment by noplay** [comment]
Yeah it's a possibility

**Comment by noplay** [comment]
Another possibility. We provide an independent application.

This application is a simple wizard explaining step by step what the user should do.
* Configure the GNS VM in GNS3
* Quit GNS3
* Change your IOUVM network card to NAT
* pip3 install gns3-server==1.3.8
* reboot the VM
* Download your backup
* Choose the remote server to replace by the GNS3 VM (the application change the gns3_gui file)
* Do you want to update your topologies? An input field allow the user to change where his topologies are located. If user say yes we update the .gns3 to change the remote server to a GNS3 VM

**Comment by ehlers** [comment]
Sounds good.

To the last point: The default path to the topologies is known from the gns3_gui file, it's in LocalServer / projects_path.

**Comment by grossmj** [comment]
Have you tested the migration process from A to Z? ;) Then you can close this.

**Comment by noplay** [comment]
Tested it's work

**Comment by noplay** [comment]
The only thing, is how the user will found they need to launch the tool.
