### ISSUE TITLE
AttributeError: type object 'QColor' has no attribute 'HexArgb' with PyQT4

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#532]
https://app.getsentry.com/gns3/gns3-gui/group/71742238/

```
AttributeError: type object 'QColor' has no attribute 'HexArgb'
  File "gns3/main_window.py", line 432, in _saveProjectActionSlot
    return self.saveProject(self._project.topologyFile())
  File "gns3/main_window.py", line 1263, in saveProject
    topo = topology.dump(random_id=random_id)
  File "gns3/topology.py", line 541, in dump
    self._dump_gui_settings(topology)
  File "gns3/topology.py", line 421, in _dump_gui_settings
    node["label"] = item.label().dump()
  File "gns3/items/note_item.py", line 202, in dump
    note_info["color"] = self.defaultTextColor().name(QtGui.QColor.HexArgb)
```

**Comment by AdrianSimionov** [comment]
+1 from my side. Annoying.

**Comment by grossmj** [comment]
QtGui.QColor.HexArgb has been introduced in Qt 5.2

The alternative would be to re-constitute the color name ourselves (e.g. hex(color.alpha())

**Comment by noplay** [comment]
AdrianSimionov which distribution are you using? We will fix PyQT4 support but if you can install pyqt5 for python 3 it's more futur proof

**Comment by AdrianSimionov** [comment]
I have this issue on Debian Jessie with XFCE4.

**Comment by noplay** [comment]
You can apt-get install python3-pyqt5 it will work better

Le lun. 13 juil. 2015 14:55, Adrian Simionov <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Ok we drop PyQT4 support and explain to user how to upgrade. For most people it should not be an issue when distribution has official package.
