### ISSUE TITLE
Dropping PyQT4 by default ? 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#533]
We receive crash due to PyQT4 incompatibility from people using distribution supporting pyqt5. 

Perhaps we need to be more strict and disallow starting GNS3 with qt4 by default and allowing it only if you set an option in the configuration file. What did you think about it?

**Comment by grossmj** [comment]
We have to be very careful with this. You should do it if this is easy to install PyQt5 on most platforms.

**Comment by noplay** [comment]
Or we can add a blacklist of distribution not supporting pyqt4 (ubuntu,
mint...)

Le lun. 13 juil. 2015 03:06, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Ok it's dropped and if only PyQT4 is available I display an error:
![capture d ecran 2015-07-15 a 12 17 45](https://cloud.githubusercontent.com/assets/345437/8697079/65410d70-2af2-11e5-9dab-c6df5a9fb074.png)

I also see error when using the GNS3 VM. You can never save the VM settings with Qt4.

**Comment by noplay** [comment]
```
2015-07-15 13:36:31 ERROR main_window.py:1289 GNS3 converter is missing: No module named 'configobj'
```
