### ISSUE TITLE
Error when opening topology in 1.4.0alpha1

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#536]
The topology was created in v1.3.7

When opened in 1.4.0alpha1 gives some warnings:
  
    => 'dot1q' is not one of ['access']
    
    Failed validating 'enum' in schema['properties']['topology']['properties']['nodes']['items']['properties'   ['ports']['items']['properties']['type']:
        {'enum': ['access']}
    
    On instance['topology']['nodes'][1]['ports'][0]['type']:
        'dot1q'
    'dot1q' is not one of ['access']
    
    Failed validating 'enum' in schema['properties']['topology']['properties']['nodes']['items']['properties']    ['ports']['items']['properties']['type']:
        {'enum': ['access']}
    
    On instance['topology']['nodes'][1]['ports'][1]['type']:
        'dot1q'
    'dot1q' is not one of ['access']
    
    Failed validating 'enum' in schema['properties']['topology']['properties']['nodes']['items']['properties']    ['ports']['items']['properties']['type']:
        {'enum': ['access']}
    
    On instance['topology']['nodes'][1]['ports'][2]['type']:
        'dot1q'
    
    Validation error when dumping the topology.
    It's probably a false positive but please send the .gns3 to developers@gns3.net.
    Thanks !
  
Topology is the one below.

    {
    "auto_start": false,
    "name": "C4-PBR",
    "project_id": "dbd9a219-54b7-4c0d-94b8-5048868659ed",
    "resources_type": "local",
    "revision": 3,
    "topology": {
        "links": [
            {
                "description": "Link from vIOS-1 port Ethernet0 to SW1 port 2",
                "destination_node_id": 12,
                "destination_port_id": 166,
                "id": 2,
                "source_node_id": 13,
                "source_port_id": 173
            },
            {
                "description": "Link from C4-TS2 Gi 17/5 port nio_udp:10407:10.125.144.118:20407 to SW1 port 1",
                "destination_node_id": 12,
                "destination_port_id": 165,
                "id": 4,
                "source_node_id": 11,
                "source_port_id": 197
            },
            {
                "description": "Link from SW1 port 3 to vIOS-2 port Ethernet0",
                "destination_node_id": 15,
                "destination_port_id": 199,
                "id": 5,
                "source_node_id": 12,
                "source_port_id": 198
            }
        ],
        "nodes": [
            {
                "description": "Cloud",
                "id": 11,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "C4-TS2 Gi 17/5",
                    "x": 29.53125,
                    "y": -25.0
                },
                "ports": [
                    {
                        "id": 161,
                        "name": "nio_udp:10405:10.125.144.118:20405",
                        "stub": true
                    },
                    {
                        "description": "connected to SW1 on port 1",
                        "id": 197,
                        "link_id": 4,
                        "name": "nio_udp:10407:10.125.144.118:20407",
                        "nio": "NIO_UDP",
                        "stub": true
                    }
                ],
                "properties": {
                    "name": "C4-TS2 Gi 17/5",
                    "nios": [
                        "nio_udp:10405:10.125.144.118:20405",
                        "nio_udp:10407:10.125.144.118:20407"
                    ]
                },
                "server_id": 2,
                "type": "Cloud",
                "x": -414.5,
                "y": -224.0
            },
            {
                "description": "Ethernet switch",
                "device_id": "e85411de-981b-4116-9109-4a1a75d28c53",
                "id": 12,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "SW1",
                    "x": 16.9296875,
                    "y": -25.0
                },
                "ports": [
                    {
                        "description": "connected to C4-TS2 Gi 17/5 on port nio_udp:10407:10.125.144.118:20407",
                        "id": 165,
                        "link_id": 4,
                        "name": "1",
                        "nio": "NIO_UDP",
                        "port_number": 1,
                        "type": "dot1q",
                        "vlan": 1
                    },
                    {
                        "description": "connected to vIOS-1 on port Ethernet0",
                        "id": 166,
                        "link_id": 2,
                        "name": "2",
                        "nio": "NIO_UDP",
                        "port_number": 2,
                        "type": "dot1q",
                        "vlan": 1
                    },
                    {
                        "description": "connected to vIOS-2 on port Ethernet0",
                        "id": 198,
                        "link_id": 5,
                        "name": "3",
                        "nio": "NIO_UDP",
                        "port_number": 3,
                        "type": "dot1q",
                        "vlan": 1
                    }
                ],
                "properties": {
                    "name": "SW1"
                },
                "server_id": 2,
                "type": "EthernetSwitch",
                "x": -171.5,
                "y": -203.0
            },
            {
                "default_symbol": ":/symbols/iosv_virl.normal.svg",
                "description": "QEMU VM",
                "hover_symbol": ":/symbols/iosv_virl.selected.svg",
                "id": 13,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "vIOS-1",
                    "x": 7.4296875,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "description": "connected to SW1 on port 2",
                        "id": 173,
                        "link_id": 2,
                        "name": "Ethernet0",
                        "nio": "NIO_UDP",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 174,
                        "name": "Ethernet1",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 175,
                        "name": "Ethernet2",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 176,
                        "name": "Ethernet3",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 4,
                        "id": 177,
                        "name": "Ethernet4",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 5,
                        "id": 178,
                        "name": "Ethernet5",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 6,
                        "id": 179,
                        "name": "Ethernet6",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 7,
                        "id": 180,
                        "name": "Ethernet7",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 8,
                        "id": 181,
                        "name": "Ethernet8",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 9,
                        "id": 182,
                        "name": "Ethernet9",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 10,
                        "id": 183,
                        "name": "Ethernet10",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 11,
                        "id": 184,
                        "name": "Ethernet11",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 12,
                        "id": 185,
                        "name": "Ethernet12",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 13,
                        "id": 186,
                        "name": "Ethernet13",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 14,
                        "id": 187,
                        "name": "Ethernet14",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 15,
                        "id": 188,
                        "name": "Ethernet15",
                        "port_number": 0
                    }
                ],
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 16,
                    "console": 2001,
                    "cpu_throttling": 0,
                    "hda_disk_image": "vIOS-L3.vmdk",
                    "legacy_networking": false,
                    "name": "vIOS-1",
                    "options": "-nographic -enable-kvm",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512
                },
                "server_id": 2,
                "type": "QemuVM",
                "vm_id": "c64edf3f-4f21-4e94-939e-974d46b06052",
                "x": 200.5,
                "y": -311.5
            },
            {
                "default_symbol": ":/symbols/iosv_virl.normal.svg",
                "description": "QEMU VM",
                "hover_symbol": ":/symbols/iosv_virl.selected.svg",
                "id": 15,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "vIOS-2",
                    "x": 7.4296875,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "description": "connected to SW1 on port 3",
                        "id": 199,
                        "link_id": 5,
                        "name": "Ethernet0",
                        "nio": "NIO_UDP",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 200,
                        "name": "Ethernet1",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 201,
                        "name": "Ethernet2",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 202,
                        "name": "Ethernet3",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 4,
                        "id": 203,
                        "name": "Ethernet4",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 5,
                        "id": 204,
                        "name": "Ethernet5",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 6,
                        "id": 205,
                        "name": "Ethernet6",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 7,
                        "id": 206,
                        "name": "Ethernet7",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 8,
                        "id": 207,
                        "name": "Ethernet8",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 9,
                        "id": 208,
                        "name": "Ethernet9",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 10,
                        "id": 209,
                        "name": "Ethernet10",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 11,
                        "id": 210,
                        "name": "Ethernet11",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 12,
                        "id": 211,
                        "name": "Ethernet12",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 13,
                        "id": 212,
                        "name": "Ethernet13",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 14,
                        "id": 213,
                        "name": "Ethernet14",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 15,
                        "id": 214,
                        "name": "Ethernet15",
                        "port_number": 0
                    }
                ],
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 16,
                    "console": 2002,
                    "cpu_throttling": 0,
                    "hda_disk_image": "vIOS-L3.vmdk",
                    "legacy_networking": false,
                    "name": "vIOS-2",
                    "options": "-nographic -enable-kvm",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512
                },
                "server_id": 2,
                "type": "QemuVM",
                "vm_id": "04d57fa5-533b-4241-af2d-39a638964561",
                "x": 206.5,
                "y": -77.5
            },
            {
                "default_symbol": ":/symbols/iosv_virl.normal.svg",
                "description": "QEMU VM",
                "hover_symbol": ":/symbols/iosv_virl.selected.svg",
                "id": 16,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "vIOS-3",
                    "x": 7.4296875,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "id": 215,
                        "name": "Ethernet0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 1,
                        "id": 216,
                        "name": "Ethernet1",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 2,
                        "id": 217,
                        "name": "Ethernet2",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 3,
                        "id": 218,
                        "name": "Ethernet3",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 4,
                        "id": 219,
                        "name": "Ethernet4",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 5,
                        "id": 220,
                        "name": "Ethernet5",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 6,
                        "id": 221,
                        "name": "Ethernet6",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 7,
                        "id": 222,
                        "name": "Ethernet7",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 8,
                        "id": 223,
                        "name": "Ethernet8",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 9,
                        "id": 224,
                        "name": "Ethernet9",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 10,
                        "id": 225,
                        "name": "Ethernet10",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 11,
                        "id": 226,
                        "name": "Ethernet11",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 12,
                        "id": 227,
                        "name": "Ethernet12",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 13,
                        "id": 228,
                        "name": "Ethernet13",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 14,
                        "id": 229,
                        "name": "Ethernet14",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 15,
                        "id": 230,
                        "name": "Ethernet15",
                        "port_number": 0
                    }
                ],
                "properties": {
                    "adapter_type": "e1000",
                    "adapters": 16,
                    "console": 2003,
                    "cpu_throttling": 0,
                    "hda_disk_image": "vIOS-L3.vmdk",
                    "legacy_networking": false,
                    "name": "vIOS-3",
                    "options": "-nographic -enable-kvm",
                    "process_priority": "normal",
                    "qemu_path": "/usr/bin/qemu-system-x86_64",
                    "ram": 512
                },
                "server_id": 2,
                "type": "QemuVM",
                "vm_id": "5c45bc6e-3b10-4fc7-b6ad-d18f6e06c2a3",
                "x": 211.5,
                "y": 211.5
            },
            {
                "description": "Cloud",
                "id": 17,
                "label": {
                    "color": "#000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "Cloud 3",
                    "x": 51.1875,
                    "y": -25.0
                },
                "properties": {
                    "name": "Cloud 3",
                    "nios": []
                },
                "server_id": 2,
                "type": "Cloud",
                "x": -428.5,
                "y": 129.0
            }
        ],
        "notes": [
            {
                "color": "#000000",
                "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                "text": "Gi 0/0 : 10.0.5.2/24",
                "x": 73.0,
                "y": -301.5
            }
        ],
        "servers": [
            {
                "cloud": false,
                "host": "127.0.0.1",
                "id": 2,
                "local": true,
                "port": 8000
            }
        ]
    },
    "type": "topology",
    "version": "1.3.7"
    }

**Comment by noplay** [comment]
Thanks, i have a fix on my laptop when I got a stable connection I will
push it.

Le dim. 12 juil. 2015 20:04, Adrian Simionov <notifications@github.com> a
écrit :

**Comment by noplay** [comment]
Fixed in 23e1baf92f3617257efc62eb8597c5c08e448d9b
