### ISSUE TITLE
Should we have a default size for custom symbols?

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#537]
https://community.gns3.com/thread/9031

**Comment by noplay** [comment]
We can scale them to same height by default.

**Comment by noplay** [comment]
We need that :D To avoid this kind of issue:

![capture d ecran 2015-10-08 a 16 14 54](https://cloud.githubusercontent.com/assets/345437/10368901/c305f894-6dd7-11e5-99f4-7806e29b07a4.png)

**Comment by grossmj** [comment]
Yep definitely :D

**Comment by noplay** [comment]
It's not easy to do in QT. I have enforced it in the registry. The additional benefits is smaller symbols.

**Comment by noplay** [comment]
It's fixe on the registry for the moment . No clean way do it with Qt :(
