### ISSUE TITLE
Symbol for VM template gone after restart of GNS3

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#538]
GNS3: 1.4.0dev2, OS Linux Debian 8 (Jessie) and Mac OS X 10.9.5

When I assign a new symbol to a template, it's usable. When I close GNS3 it's included in gns3_gui.conf.
```
"symbol": "/home/behlers/JunOS.png",
```
Here the custom symbol: ![junos](https://cloud.githubusercontent.com/assets/896406/8640250/0ada1bbc-28f2-11e5-9fec-47a441f58d66.png)

But when I restart GNS3, the custom symbol for the template is gone, it has again a standard template.

**Comment by grossmj** [comment]
This should do it. Let me know if you still have an issue.

Thanks,
