### ISSUE TITLE
Can't change symbol of a device from a standard symbol to a custom symbol and vice versa

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#539]
GNS3: V1.4.0dev2

When I right-click on a device, I have the option to change the symbol.
- If it has a standard symbol, I can change to another stardard symbol
- If it has a standard symbol, I **can't** change it to a custom symbol
- If it has s custom symbol, I **can't** change it to a standard symbol
- If it has a custom symbol, I can change it to another custom symbol

**Comment by grossmj** [comment]
Known issues ;) related to https://github.com/GNS3/gns3-gui/issues/514

**Comment by ehlers** [comment]
Oops, then I close it.
