### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#541]
https://app.getsentry.com/gns3/gns3-gui/group/72050575/

```
AttributeError: 'list' object has no attribute 'get'
  File "./gns3-gui\gns3\utils\wait_for_vm_worker.py", line 204, in run
  File "./gns3-gui\gns3\http_client.py", line 329, in getSynchronous
```

**Comment by ehlers** [comment]
Already fixed in https://github.com/GNS3/gns3-gui/commit/4a1e6eba8c487615f3ecac3f9e9d768aafd1240c, see issue https://github.com/GNS3/gns3-gui/issues/530

**Comment by grossmj** [comment]
Excellent :)
