### ISSUE TITLE
Issue with vmware player

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#557]
Received by email:

 i would suggest you make your gns3 vm server compatible with vmplayer to0.it's not work fine in vmplayer. VIX missing issue ad after standlone vix installation it also not work vix APi should be part of gns3 pachage so eitehr vmware workstation or player is enough.

**Comment by grossmj** [comment]
> it's not work fine in vmplayer

We need more detail than this.

**Comment by grossmj** [comment]
I've tested VMware player on Windows with GNS3. No issues.
