### ISSUE TITLE
Configure vCPU/RAM from setup wizard

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#565]
This should be based of how much is available on the host.

**Comment by grossmj** [comment]
This is add a new dependency: psutil

**Comment by noplay** [comment]
But we already know we need psutil one day it's not an issue :)

**Comment by grossmj** [comment]
@noplay don't forget to add the psutil dependency on OSX and Windows.

**Comment by noplay** [comment]
Added to the build
