### ISSUE TITLE
Crash with pyqt5.5

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#568]
https://community.gns3.com/ideas/1846

**Comment by noplay** [comment]
Perhaps something changed in the geometry saving :( I think we should catch the error and reset geometry.

**Comment by grossmj** [comment]
My fix didn't worked. Still have the issue: https://app.getsentry.com/gns3/gns3-gui/group/73306825/

Maybe QByteArray is expecting bytes and not a string?

**Comment by noplay** [comment]
I tested on my computer and it's fixe

**Comment by cioby23** [comment]
Confirming also that it has been fixed. Thanks.

**Comment by noplay** [comment]
I found and fix more error. It seem they have removed a byte to str implicit conversion :(
