### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#575]
https://app.getsentry.com/gns3/gns3-gui/group/73370249/

```
RuntimeError: maximum recursion depth exceeded in comparison
  File "gns3/progress.py", line 53, in _remove_query
    if len(self._queries) == 0:
```

**Comment by noplay** [comment]
We don't have the full stacktrace. It's on a dev build. No informations on how to replicate it. I close it :(

**Comment by noplay** [comment]
Also we only got one crash report
