### ISSUE TITLE
Close the GUI if user download an upgrade

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#578]
or maybe just add a message?

https://community.gns3.com/message/37416#37416

**Comment by noplay** [comment]
The download is in background and apply at next startup. We can display a
message when download is done and asking the user if he want to close the
app.

**Comment by noplay** [comment]
Oh you mean the upgrade with a .exe. 

It seem possible but not trivial:
http://nsis.sourceforge.net/Check_whether_your_application_is_running

**Comment by grossmj** [comment]
Looks good. Think it is best to do it in the installer.

**Comment by noplay** [comment]
https://github.com/rstudio/rstudio/blob/master/package/win32/cmake/modules/NSIS.template.in#L989

**Comment by noplay** [comment]
We need to update the application title to untiled.gns3 - GNS3 in order to found it

**Comment by noplay** [comment]
![capture d ecran 2016-02-02 a 15 37 51 2](https://cloud.githubusercontent.com/assets/345437/12752717/19f19986-c9c4-11e5-900d-c3977b1fe208.png)
