### ISSUE TITLE
At first VM launch I got this error

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#581]
I think timeout is too short because at first launch we need to setup the VM by downloading gns3 from pypi
 ![capture d ecran 2015-07-29 a 12 24 34](https://cloud.githubusercontent.com/assets/345437/8955426/e400e130-35ec-11e5-9109-1c56f63a8661.png)

**Comment by grossmj** [comment]
Timeout is 120 seconds. The main issue I think is that once we have the IP address of the VM we assume the server is already running.

**Comment by noplay** [comment]
I think we need to retry until success in the timeout windows if it's not an HTTP status code error.
