### ISSUE TITLE
Trouble with listing VirtualBox VM on Windows 10

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#583]
Reported by matt.

Matt can't see the list of VirtualBox VM in the setup wizard. We test in a command prompt and saw that VBoxManage list vms work but is slow.

**Comment by grossmj** [comment]
I tested with him, it is just slow.... ;)

I'll change the progress dialog minimum delay to 0 for the wizard.

**Comment by grossmj** [comment]
Hum, that was already done.
