### ISSUE TITLE
Upload images never finish

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#584]
Seen by matt and a forum user
https://community.gns3.com/thread/14647

**Comment by noplay** [comment]
if I hide the progress dialog it's work. Seem to be something broken since Qt 5.5

**Comment by noplay** [comment]
Perhaps it's related to:
https://bugreports.qt.io/browse/QTBUG-47042

**Comment by noplay** [comment]
Or https://bugreports.qt.io/browse/QTBUG-46859

**Comment by noplay** [comment]
It's fix

For an unknow reason it's stop working with Qt 5.5
the fix is to use QtCore.Qt.QueuedConnection on the slot
in order to avoid blocking the HTTP thread.

**Comment by grossmj** [comment]
:+1:
