### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type IOUDeviceWizard has been deleted

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#596]
A cancelled operation should not call the callback.

https://app.getsentry.com/gns3/gns3-gui/group/74291803/

```
RuntimeError: wrapped C/C++ object of type IOUDeviceWizard has been deleted
  File "./gns3-gui\gns3\http_client.py", line 660, in _processResponse
  File "./gns3-gui\gns3\dialogs\vm_wizard.py", line 241, in _getImagesFromServerCallback
```

**Comment by grossmj** [comment]
@noplay do you want to take a pick at it?

**Comment by noplay** [comment]
How do you solve this kind of issue?

**Comment by grossmj** [comment]
I think when you close a dialog (here the device wizard) we should cancel any request / prevent the callback to be called. I remember doing that in 1.3.x and I think it worked but something must have been broken since...

https://github.com/GNS3/gns3-gui/blob/master/gns3/http_client.py#L366

**Comment by grossmj** [comment]
It doesn't look like that the canceled signal is emited anywhere.

**Comment by noplay** [comment]
I don't understand why pyqt warn us about that and don't just disconnect slot when the object disappear.
