### ISSUE TITLE
Remove "local server" check box for each module in preferences dialog.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#598]
Currently these check boxes are mostly useful to grey out local settings when they are not checked. This shows users that these settings (e.g. path to VBoxManage, vmrun etc.) are only relevant locally.

I think if we remove the check boxes we should either rename the tab(s) to "General local settings" or put all the local setting widgets in a group box with the "Local server" title like in the IOS on UNIX preferences section.

We would have to keep the checkbox for VPCS module.

**Comment by noplay** [comment]
And perhaps keep it for dynamips for the hub and switch

**Comment by grossmj** [comment]
After thinking about it and for consistency I think it best to keep that setting.
