### ISSUE TITLE
Spelling error wihout -> without

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#601]
GNS3 V1.4.0dev5, gns3/dialogs/preferences_dialog.py
![bildschirmfoto 2015-08-06 um 22 03 35](https://cloud.githubusercontent.com/assets/896406/9122164/7279401a-3c87-11e5-9bde-6a8f92afc6c1.png)

**Comment by grossmj** [comment]
Thanks and welcome back :)
