### ISSUE TITLE
Password of remote server gets lost

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#603]
GNS3: 1.4.0dev5, OS: Debian Linux and Mac OS X 10.9.5

The password of a remote server gets lost when the preference window is opened after the server configuration.

Procedure to reproduce:
- open preference and add a new remote server with user and password
- close preference with OK (saves configuration)
- close GNS3 (that's necessary !!!)
- verify, that new server is in gns3_gui.conf and has correct username and password
- start GNS3
- open preferences
- close preferences with OK (without doing any changes)
- now the server has a null password in gns3_gui.conf

**Comment by noplay** [comment]
I confirm the issue

**Comment by noplay** [comment]
Fixed ! Thanks for the report
