### ISSUE TITLE
Accepting insecure https connections creates additional server entry

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#605]
I created a GNS3 server with a self signed ssl certificate. It also uses user/password authentication. Then this server is adding to the remote server list. On the first connection the GUI asks for confirmation for the insecure certificate, which is granted.

That results in an additional remote server entry without user and password, which holds this certificate. The user now sees two remote server entries for the same server, which is confusing (but works).

Excerpt from gns3_gui.conf:

```
        "remote_servers": [
            {
                "accept_insecure_certificate": "cca0a932ced2fb1b1a18c823542cb065",
                "host": "192.168.1.90",
                "password": null,
                "port": 8000,
                "protocol": "https",
                "ram_limit": 0,
                "url": "https://192.168.1.90:8000",
                "user": null
            },
            {
                "accept_insecure_certificate": null,
                "host": "192.168.1.90",
                "password": "abc",
                "port": 8000,
                "protocol": "https",
                "ram_limit": 0,
                "url": "https://test@192.168.1.90:8000",
                "user": "test"
            }
        ],
```

**Comment by noplay** [comment]
I confirm the issue is only when you use insecure certicate and a user name. Nice catch

**Comment by noplay** [comment]
My status debugging this:
![Giphy](http://media0.giphy.com/media/dOZj6qlD8Kwta/giphy.gif)

The issue is we lost the username when Qt call the callback about the invalid SSL certificate. I try to force Qt to transmit the information

**Comment by noplay** [comment]
setUserName on a QUrl seem to bug.

**Comment by noplay** [comment]
I finally found a way to workaround it  by passing the user in the url string of the constructor of QUrl.

**Comment by noplay** [comment]
Fixed thanks for the report.
