### ISSUE TITLE
KeyError: 'vm:Switch'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#612]
https://app.getsentry.com/gns3/gns3-gui/group/75715011/

```
KeyError: 'vm:Switch'
  File "./gns3-gui\gns3\modules\iou\pages\iou_device_preferences_page.py", line 112, in _iouDeviceChangedSlot
```

**Comment by noplay** [comment]
I suspect the following scenario. The user configure IOU on the GNS3 VM and after turn off the VM in the settings.

**Comment by noplay** [comment]
I didn't manage to replicate it :(

**Comment by grossmj** [comment]
May just be someone trying to hack the code?

**Comment by noplay** [comment]
Should not arrive in 1.4
