### ISSUE TITLE
Option to upload VirtualBox or VMware appliances

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#616]
https://community.gns3.com/message/45878#45878

**Comment by noplay** [comment]
Same than #469 if we do that we promote VMware and VirtualBox versus Qemu.

**Comment by grossmj** [comment]
Yep, this can wait that our long term plan is settled.

**Comment by grossmj** [comment]
We won't support this since we want to encourage using Qemu vs VMware/VirtualBox. Moreover, VMware/VirtualBox VM should only be used locally.
