### ISSUE TITLE
Generic firewall symbol

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#631]
I think we need to provide a default firewall symbol with the GUI for people who want to use appliance firewall. Actually we have two symbol about firewall:
* PIX_firewall
* router_firewall

**Comment by grossmj** [comment]
Actually the PIX firewall symbol is the generic symbol that should be used. It should just be renamed firewall.

**Comment by noplay** [comment]
If we rename the symbol can it generate trouble? Or nobody use it actually.

**Comment by grossmj** [comment]
I tried to use an alias but this doesn't worked as expected:

<file alias="symbols/firewall.svg">symbols/PIX_firewall.svg</file>

The safest is to duplicate PIX_firewall.svg and name is firewall.svg I think

**Comment by noplay** [comment]
Ok it's fixed
