### ISSUE TITLE
The Qemu wizard should not ask for HDA in the case of ASA

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#636]

**Comment by grossmj** [comment]
Actually you have to have a disk to store configs etc.

**Comment by noplay** [comment]
The user should provide an empty disk?

**Comment by grossmj** [comment]
Yep, like a FLASH disk... by default we have a 256MB disk automatically created when no hda disk created in 1.3.x

https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/qemu/qemu_vm.py#L897

I removed that in 1.4 so now you have to explicitly create a disk.

**Comment by noplay** [comment]
Ok
