### ISSUE TITLE
Warn when launching a packet capture with a non-ASCII path with Dynamips

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#638]
https://community.gns3.com/message/47506#47506

**Comment by noplay** [comment]
This problem could be work around by using ubridge for capture

**Comment by grossmj** [comment]
Actually I believe the issue is with Cygwin, so we may end up with the same issue using uBridge.

**Comment by grossmj** [comment]
I send an error from the server if the path contain non-ASCII chars: https://github.com/GNS3/gns3-server/commit/e63e3280a1b2d05817e9104784c976ffc086857b

However the best would be to have the CYGWIN DLL support UTF-8. Currently Dynamips is compiled with Cygwin 1.7. Lastest version is 2.2.1.
