### ISSUE TITLE
Call vmnet management scripts from the GUI

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#639]
We have scripts to add/remove vmnet interfaces but these have to be run using root. It would be more user friendly if we could call those scripts from the GUI, either from the tools menu or from the Preferences but for this we need some kind of graphical sudo I think.

**Comment by ehlers** [comment]
What about a script during installation time, that modifies /etc/sudoers to allow the GNS3 user to start the vmnet-cli (and only that) via sudo without password?

**Comment by noplay** [comment]
I don't know a program modifying the sudoers files. I don't know if it's a good practice. 

Probably supporting tools like gksudo is a good idea for calling them .

**Comment by grossmj** [comment]
Would it be complicated to make one ourselves? VMware does it when you want
to edit network preferences. Also, I agree modifying the sudoers is
probably not good practice and won't be multi-platform anyway.

**Comment by noplay** [comment]
If we want to make a graphical sudo I think the program it self should have
specific rights. It's a chicken and egg problem.

**Comment by ehlers** [comment]
One simple way to to call sudo  with the -S option. Then sudo reads it's password from stdin.

```
       -S          The -S (stdin) option causes sudo to read the password from
                   the standard input instead of the terminal device.  The
                   password must be followed by a newline character.
```

You can create your own password dialog, then send the password via stdin to the subprocess with "sudo -S"

**Comment by noplay** [comment]
Right we can do that

**Comment by ehlers** [comment]
Another way is setting the environment variable SUDO_ASKPASS with the path of a (GUI) program, that gets the password and sends it to stdout. For that to work, you should also pass the option -A to sudo.

**Comment by noplay** [comment]
I will work on the sudo code.

**Comment by noplay** [comment]
Do we need it for Windows?

**Comment by grossmj** [comment]
Yes but this can wait for Windows. Need to do some research, most likely we will use the "Run as" command/program.

**Comment by noplay** [comment]
Which command should we run with that?

**Comment by noplay** [comment]
I have a working sudo code for OSX and linux

**Comment by grossmj** [comment]
> Which command should we run with that?

I think we can either add a text menu interface with the Python cmd module to the vmnet script and then call that script from the Tools menu or we can make a custom interface similar to VMware network preferences and call the script with the correct params.

**Comment by grossmj** [comment]
I vote for the second option, this will make it more user friendly.

**Comment by grossmj** [comment]
I'll take care of that part if you want ;)

**Comment by noplay** [comment]
ok
