### ISSUE TITLE
Support remote console for docker

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#644]
Actually for test purpose we have SHELL_CONSOLE_COMMAND but it's work only for a local docker.

**Comment by noplay** [comment]
cc @gcetusic

**Comment by noplay** [comment]
The issue is for having a console we need to start docker like that:
docker exec -it NAME_OF_CONTAINER bash

**Comment by noplay** [comment]
Another way is too attach to the container with docker attach this mean we would have the output of the container or a shell depending of what is start by the container.

**Comment by noplay** [comment]
With have multiple implementation of telnet in the server code:
* TelnetServer for VMware and VirtualBox
* ioucon for IOU

And this stuff don't use asyncio.

Perhaps it's time for a clean stuff.

We can drop ioucon and made wrapper that expose stdin and stdio of a program on a telnet port. This could work for docker and IOU.

**Comment by grossmj** [comment]
This could be done but we have to be careful, this code can easily break. I would start with TelnetServer and leave ioucon for another day ;)

**Comment by noplay** [comment]
Delayed to 1.5 we will see if it's not a risk to ship it with 1.4

**Comment by noplay** [comment]
I have a remote console working for docker using websocket on the docker_cleanup branch.
