### ISSUE TITLE
Packet capture error on link connecting qemu devices

### ISSUE THREAD

**Issue by mrinaldhillon** [GNS3/gns3-gui#654]
Start packet capture on link connecting 2 qemu vms throws error: Packet capture is not supported on this link.
Packet capture works only links connected to gns3 native ethernet switches

**Comment by cioby23** [comment]
This is not an error. Packet capture between Qemu device is not implemented yet. I have posted a request for this on the GNS3 community site. Check this page https://community.gns3.com/ideas/1749

**Comment by noplay** [comment]
We have idea on how to do it. But this require to rewrote the link for qemu.

**Comment by cioby23** [comment]
I just saw on the GNS3 community forum that  someone has forked gns3 git repos and implemented capture between Qemu device. More details here https://community.gns3.com/thread/5518#47835

**Comment by grossmj** [comment]
We have plans to do it using uBridge , we just don't want to use the Qemu
legacy vlan  syntax which is limited to 8 adapters and has other drawbacks.
Also, a benefit of using uBridge is we will handle dynamic link additions
and removals while a node is running.

**Comment by grossmj** [comment]
I close this issue because we already have a general one covering that: https://github.com/GNS3/gns3-server/issues/267
