### ISSUE TITLE
Setuid ubridge on OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#655]
In order to allow interact with vmnet interfaces we need to setuid the ubridge binary.

**Comment by grossmj** [comment]
What about checking that the setuid is set when first dropping a node in
the GUI? If not we use the graphical sudo to change it. Of course this
would work only for a local server.

**Comment by grossmj** [comment]
We could also check on server side that the setuid is set on OSX and Linux capabilities on Linux and throw an error if not.
