### ISSUE TITLE
Server UUID shown instead of name.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#657]
Adding a remote server in the preferences and trying to use it right away (for instance drag and drop a Cloud or switch) shows an UUID.

![remote_server](https://cloud.githubusercontent.com/assets/4752614/9837878/9d4561de-5a0a-11e5-9420-16c037e7c7ea.png)

Restart GNS3 and the name is displayed correctly.

**Comment by noplay** [comment]
I confirm
