### ISSUE TITLE
On OSX ask user to install a recent qemu? 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#658]
Instead of shipping a more recent qemu build which is a complex and hazardous process.

My proposal is too keep the current qemu. But show a warning to the user when he select it:
> This version of qemu is obsolete and provided only for compatibility with old GNS3 versions.
> Please use Qemu in the GNS3 VM (**recommended**) or install a recent version of Qemu via homebrew or macport.

What did you think about that?

**Comment by grossmj** [comment]
The problem is homebrew and macport is for more advanced users I think, I would recommend to use the GNS3 VM for full Qemu support.

**Comment by noplay** [comment]
We can display this message:

> This version of qemu is obsolete and provided only for compatibility with old GNS3 versions.
> Please use Qemu in the GNS3 VM for full Qemu support.

**Comment by grossmj** [comment]
Works for me.
