### ISSUE TITLE
Malformed QEMU UDP link config when "Use the legacy networking mode" is checked

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-gui#663]
I have two Cumulus VX QEMU VMs in a topology. Per the instructions in http://docs.cumulusnetworks.com/display/VX/Using+GNS3+with+QEMU+and+KVM+Virtual+Machines , on the "Network" tab of the QEMU VM template, I set the checkbox to "Use the legacy networking mode" and set the "Type" dropbox to "Legacy paravirtualized Network I/O (virtio)".

 I then SSH'd into each VM (VX does not implement a console) and configured swp1-3, then "ifup"d them. They do show as up and running in the OS:

```
cumulus@vx-1401$ ip link sh
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000 
    link/ether 00:00:ab:f0:1e:00 brd ff:ff:ff:ff:ff:ff
3: swp1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000 
    link/ether 00:00:ab:f0:1e:01 brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000 
    link/ether 00:00:ab:f0:1e:02 brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000 
    link/ether 00:00:ab:f0:1e:03 brd ff:ff:ff:ff:ff:ff
```

So, then I tried to connect them with a link, but I get an error and the QEMU VMs stop. The whole text from the GNS3 console is:

```
QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name Cumulus-VX-port1402 -m 256M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/gns3user/GNS3/projects/e1caa8ec-06a2-44e3-aca0-7af8bb02272b/project-files/qemu/f35cd3ce-fcb9-4fe1-84ec-631edf37b48a/hda_disk.qcow2,if=ide,index=0,media=disk -serial telnet:0.0.0.0:2001,server,nowait -monitor tcp:127.0.0.1:54942,server,nowait -net user,vlan=0,net=192.168.0.0/24,hostfwd=tcp::1402-:22 -net none -net nic,vlan=0,macaddr=00:00:ab:b4:8a:00,model=virtio -net nic,vlan=1,macaddr=00:00:ab:b4:8a:01,model=virtio -net udp,vlan=1,name=gns3-1,sport=10001,dport=10000,daddr=192.168.1.165 -net nic,vlan=2,macaddr=00:00:ab:b4:8a:02,model=virtio -net nic,vlan=3,macaddr=00:00:ab:b4:8a:03,model=virtio -nographic

Execution log:
qemu-system-x86_64: -net udp,vlan=1,name=gns3-1,sport=10001,dport=10000,daddr=192.168.1.165: Invalid parameter 'udp'

QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-x86_64 -name Cumulus-VX-port1401 -m 256M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/gns3user/GNS3/projects/e1caa8ec-06a2-44e3-aca0-7af8bb02272b/project-files/qemu/2bb07a7b-4d6d-4379-97ce-54c138d5f01e/hda_disk.qcow2,if=ide,index=0,media=disk -serial telnet:0.0.0.0:2000,server,nowait -monitor tcp:127.0.0.1:57483,server,nowait -net user,vlan=0,net=192.168.0.0/24,hostfwd=tcp::1401-:22 -net none -net nic,vlan=0,macaddr=00:00:ab:f0:1e:00,model=virtio -net nic,vlan=1,macaddr=00:00:ab:f0:1e:01,model=virtio -net udp,vlan=1,name=gns3-1,sport=10000,dport=10001,daddr=192.168.1.165 -net nic,vlan=2,macaddr=00:00:ab:f0:1e:02,model=virtio -net nic,vlan=3,macaddr=00:00:ab:f0:1e:03,model=virtio -nographic

Execution log:
qemu-system-x86_64: -net udp,vlan=1,name=gns3-1,sport=10000,dport=10001,daddr=192.168.1.165: Invalid parameter 'udp'
```

In further testing, if I make the QEMU VM templates have "new style" network adapters (i.e., "Use the legacy networking mode" is UNchecked, and Type is set to "Paravirtualized Network I/O (virtio-net-pci)" then when I form a link between the instantiated VMs from this template, the link does work (goes green and stays up) and I see that the relevant QEMU config line on the VMs is:
```-netdev socket,id=gns3-1,udp=192.168.1.165:10000,localaddr=0.0.0.0:10001```
instead of the malformed:
```-net udp,vlan=1,name=gns3-1,sport=10000,dport=10001,daddr=192.168.1.165```

So, I believe there is a problem forming the correct UDP link config for the QEMU VMs when the Network config is set to use "Legacy" mode.

**Comment by grossmj** [comment]
What version of Qemu have you used?

**Comment by wdennis** [comment]
QEMU 2.0.0 from std CentOS 7 repo

**Comment by grossmj** [comment]
Looks like recent version of Qemu do not understand the -udp parameter anymore. Need to investigate this more.

Alternatively, you can use virtio-net-pci network adapter type instead and not use the "legacy networking mode"

**Comment by wdennis** [comment]
Yes, but unfortunately not on the VM disk image I'm wanting to use (somehow
kills SSH access to the VM, which is the only way into it...)

**Comment by wdennis** [comment]
Looked into the qemu "-net udp" option to see the history of it, and I see the discussion of the UDP patch on the -dev mailing list in Oct 2011 (patch authored by Benjamin MARSILI):
https://lists.gnu.org/archive/html/qemu-devel/2011-10/msg00666.html

Then searching for that submitter name in the qemu.git tree, I find this patch merge from Jan 2012:
http://git.qemu.org/?p=qemu.git;a=commitdiff;h=0e0e7facc775e9bb020314f48751b3d09f316c8b

So it look like from Jan 2012 on, "regular" QEMU supported UDP tunnel connections (without having to be patched with the GNS3-curated QEMU patch set.) Looks like this was in the QEMU 1.2 release.

I also see some reorg of the "net" tree in Dec 2012 (corresponds to QEMU 1.4) but due the the volume of files in the QEMU tree, # of commits and my weak C skills, I cannot find out where the "-net udp,..." syntax was removed.

**Comment by wdennis** [comment]
Posted a message on the qemu-discuss list as to the "-net, udp,.." not working on QEMU 2.0.0:
http://lists.nongnu.org/archive/html/qemu-discuss/2015-09/msg00077.html

**Comment by wdennis** [comment]
Someone responded to me with the following:
---
A bit of googling suggests that '-net udp' has never been supported
in mainline QEMU -- it seems to be a local patch provided by the GNS3
folks. I suggest asking in whatever support forum they provide.
---
Can one of your confirm/deny this syntax ever made it into mainline QEMU?

**Comment by grossmj** [comment]
@wdennis I've investigated this issue and it is correct that the "-net udp" option never made it to the mainline QEMU (I thought it did) which is the one GNS3 uses when legacy networking is enabled.

The UDP tunnel support was indeed added in QEMU 1.1 and the syntax is ```-net socket[,vlan=n][,name=str][,fd=h][,udp=host:port][,localaddr=host:port]```

Here is what I will do in GNS3 for the legacy networking option: if the Qemu version is 1.1 or above, I will use the ```-net socket``` syntax otherwise ```-net udp``` and pray that Qemu is patched.

**Comment by wdennis** [comment]
Yup, makes sense - maybe consider a user warning that "if QEMU < 1.1, needs GNS3 UDP tunnel support patch applied" or the like... Thanks for looking into this!

**Comment by grossmj** [comment]
I've implemented the corrections: https://github.com/GNS3/gns3-server/commit/970f22a83e005d561d2a60df0b8f3fb2358f9f79

On Wiindows: a version.txt file containing the Qemu version number (< 1.1.0) must be present in the patched Qemu directory for GNS3 to use the -net udp syntax.
