### ISSUE TITLE
Error like RuntimeError: super-class __init__() of type Dynamips was never called

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#668]
It seem if the context receive a QObject we got this error
```
RuntimeError: super-class __init__() of type Dynamips was never called
```

**Comment by grossmj** [comment]
Looks like it works but why do you import copy in executeHTTPQuery()?

**Comment by grossmj** [comment]
Looks like it is fixed. I will test more and re-open if necessary.
