### ISSUE TITLE
Appliance doesn't work on local Server

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#669]
GNS3 version 1.4.0beta2 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2

Importing the appliance works fine, I choose the local server.
![gns3a_install_local_server](https://cloud.githubusercontent.com/assets/896406/9955374/bb22db48-5df0-11e5-95f8-7efebd41bba2.png)

But I can't use it, GNS3 console says:
```
Host requires authentication
Error while creating project: Can't connect to server http://192.168.1.11:8000
```

In gns3_gui.conf the server entry for this appliance is ```"server": "http://192.168.1.11:8000",```. When I edit it to ```"server": "local",``` the appliance works fine.

**Comment by noplay** [comment]
Thanks for the report

Le ven. 18 sept. 2015 10:41, Bernhard Ehlers <notifications@github.com> a
écrit :
