### ISSUE TITLE
Enhancement request: Edit machine config right out of GUI pick list

### ISSUE THREAD

**Issue by wdennis** [GNS3/gns3-gui#670]
In playing around with QEMU machines, and having to make many tweaks to them, I wish there was a way to edit the machine config by either double-clicking the machine icon or right-clicking it and selecting "Edit" directly from the GUI pick list as shown below:
![edit-machine-def](https://cloud.githubusercontent.com/assets/5913397/9958480/597076ca-5dd8-11e5-998a-a3c5640b44f4.png)

This would be a lot easier than having to go to "Edit" on the top menu, select "Preferences..." then navigate to the proper VM type node, select the VM instance, and click the "Edit" button at the bottom.

**Comment by grossmj** [comment]
Yep, good idea :+1:

**Comment by noplay** [comment]
I was thinking the same

Le ven. 18 sept. 2015 16:10, Jeremy Grossmann <notifications@github.com> a
écrit :
