### ISSUE TITLE
Configuration not always saved in client

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#678]
https://community.gns3.com/ideas/1897

**Comment by noplay** [comment]
Step to reproduce:
* go the preferences
* edit a qemu vm
* increase network adapters
* click on OK
* settings are not changed in the gns3_gui.conf but changed in the GUI

**Comment by noplay** [comment]
It was an issue with a references, the changes was not detected and write to the configuration file.

**Comment by grossmj** [comment]
This may be worth to backport it in 1.3.11
