### ISSUE TITLE
Issue with qemu interface naming

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#688]
https://community.gns3.com/thread/22344

**Comment by grossmj** [comment]
Investigating how to handle that case: https://github.com/GNS3/gns3-gui/issues/309

**Comment by grossmj** [comment]
This has been fixed thanks to a PR from @boenrobot 

https://github.com/GNS3/gns3-gui/pull/894

New named variables ({port0}, {port1}, {segment0}, {segment1}) were added.
