### ISSUE TITLE
Send stats to GNS3 team

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#694]
Beware to privacy issue, an user should be able to turn off stats.

**Comment by grossmj** [comment]
> Beware to privacy issue, an user should be able to turn off stats.

Yep, like crash reports.

**Comment by grossmj** [comment]
Resources:

https://www.ics.com/blog/using-google-analytics-monitor-qt-applications
http://www.ics.com/blog/using-google-analytics-monitor-qt-applications-part-2

**Comment by grossmj** [comment]
Replace https://github.com/GNS3/gns3-gui/blob/master/gns3/utils/analytics.py

**Comment by noplay** [comment]
The documentation:
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide

**Comment by noplay** [comment]
For example:

```
v=1                         // Version.
&tid=UA-XXXXX-Y             // Tracking ID / Property ID.
&cid=555                    // Anonymous Client ID.
&aip=1 // Anonymize IP
&t=screenview               // Screenview hit type.
&an=gns3                // App name.
&av=1.3.11                   // App version.
&ua=GNS3 Windows // User agent
&cd=Startup                    // Screen name / content description.
```

**Comment by noplay** [comment]
POST /collect HTTP/1.1
Host: www.google-analytics.com

payload_data

**Comment by noplay** [comment]
I made some progress on this but I have trouble for reporting the OS.

I have created a analyics ID for my tests.

**Comment by noplay** [comment]
PR opened: #715

**Comment by noplay** [comment]
It's backported to 1.4
