### ISSUE TITLE
Crash on Mac OS X El Capitan

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#695]
https://community.gns3.com/ideas/1912

**Comment by grossmj** [comment]
Of course it looks like we are going to need a El Capitan soon....

**Comment by noplay** [comment]
Ok tested yesterday and doesn't replicate.

I try to update the build server in order to build with the last Qt 4. Build the macport upgrade is so slow ....

**Comment by noplay** [comment]
Qt4 is still building ....

**Comment by noplay** [comment]
Upgraded the build 4.8.7 hope it's solve issues.

**Comment by noplay** [comment]
We will see if we got feedback
