### ISSUE TITLE
Custom progress message box message

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#704]
Would be nice to customize the progress message box in some situation.

For instance when calculating the Idle-PC values we could show "Calculating Idle-PC values..." instead of "Waiting for http://192.168.56.100:8000"

https://github.com/GNS3/gns3-gui/blob/unstable/gns3/graphics_view.py#L1218

I think one way to do it would be to pass that text to the Progress context.

**Comment by noplay** [comment]
It's almost possible:
https://github.com/GNS3/gns3-gui/blob/master/gns3/http_client.py#L83

**Comment by noplay** [comment]
It possible in 1.4:
https://github.com/GNS3/gns3-gui/blob/unstable/gns3/http_client.py#L183

You need to pass progressText to the query:
https://github.com/GNS3/gns3-gui/blob/unstable/gns3/http_client.py#L545
