### ISSUE TITLE
Scanning for Appliance images doesn't end

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#713]
GNS3 1.4.0.dev9 on Linux Debian (Jessie) (64-bit) with Python 3.4.2 Qt 5.3.2.

In about one of three cases when I import an appliance, the scanning for the images doesn't end.
![appliance-scanning](https://cloud.githubusercontent.com/assets/896406/10423148/a8115a58-70c3-11e5-8612-8ec0a0f7f6f6.png)
When I stop the scanning and redo the import, it normally works.

When I start GNS3 with --debug, I don't see anything in the log, while on the second successful try, I see the search in the log.
```
2015-10-12 09:22:12 INFO __init__.py:188 Docker module reset
2015-10-12 09:22:12 INFO __init__.py:70 Built-in module reset
2015-10-12 09:22:12 INFO topology.py:397 Topology reset
2015-10-12 09:25:04 DEBUG registry.py:47 Search images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/GNS3/images/QEMU
2015-10-12 09:25:04 DEBUG registry.py:47 Search images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/Downloads
2015-10-12 09:25:04 DEBUG registry.py:60 Found images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/Downloads/NETem-v3.qcow2
2015-10-12 09:25:04 DEBUG registry.py:47 Search images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/GNS3/images/QEMU
2015-10-12 09:25:04 DEBUG registry.py:47 Search images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/Downloads
2015-10-12 09:25:04 DEBUG registry.py:60 Found images NETem-v3.qcow2 (88297839b5f014ac15a434053f51690f) in /home/behlers/Downloads/NETem-v3.qcow2
```
Somehow unrelated: Why is the scanning done twice?

**Comment by noplay** [comment]
How big are your directories images/QEMU and Downloads? Do you have file inside where the process don't have permissions? I suspect a crash depending the order of scanning for files.

I need to check but probably the double scan is not an issue due to the use of cache. But you are right it should not append.

**Comment by ehlers** [comment]
There are some file in it, see attached list, but not that much. But what puzzles me is, that on the unsuccessful tries, there is not even a "Search images" entry in the log. Not a single sign, that GNS3 even tries to find something.
```
behlers@dell:~$ ls -l ~/GNS3/images/QEMU/
insgesamt 2309644
-rw-r--r-- 1 behlers behlers   4194304 Jan 29  2015 Aboot-veos-serial-2.0.8.iso
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 Aboot-veos-serial-2.0.8.iso.md5sum
-rw-r--r-- 1 behlers behlers  96862208 Aug 16 22:25 IOSv-L2.qcow2
-rw-r--r-- 1 behlers behlers        32 Aug 17 09:38 IOSv-L2.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 559349760 Jan 18  2015 iosxrv-k9-demo-5.3.0.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 iosxrv-k9-demo-5.3.0.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 341311488 Jun 15  2014 junos-11.4R11.4.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 junos-11.4R11.4.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 278659072 Sep 21  2014 junos-vsrx-12.1X47-D10.4-domestic.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 junos-vsrx-12.1X47-D10.4-domestic.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 276365312 Mär  4  2015 junos-vsrx-12.1X47-D20.7-domestic.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 junos-vsrx-12.1X47-D20.7-domestic.qcow2.md5sum
-rw-r--r-- 1 behlers behlers  18415616 Sep 17 22:23 ost-drone-0.7-v1.qcow2
-rw-r--r-- 1 behlers behlers        32 Sep 17 22:31 ost-drone-0.7-v1.qcow2.md5sum
-rw-r--r-- 1 behlers behlers  23461888 Okt 12 09:41 test123
-rw-r--r-- 1 behlers behlers        32 Okt 12 09:41 test123.md5sum
-rw-r--r-- 1 behlers behlers  11206656 Jun  6  2013 TinyCore.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 TinyCore.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 633733120 Jan 29  2015 vEOS-lab-4.14.5F.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 vEOS-lab-4.14.5F.qcow2.md5sum
-rw-r--r-- 1 behlers behlers 121634816 Sep 21  2014 vios-adventerprisek9-m.qcow2
-rw-r--r-- 1 behlers behlers        32 Jun 26 11:53 vios-adventerprisek9-m.qcow2.md5sum
behlers@dell:~$ ls -l ~/Downloads/
insgesamt 22916
-rw-r--r-- 1 behlers behlers     1746 Okt 11 14:37 netem.gns3a
-rw-r--r-- 1 behlers behlers 23461888 Okt 12 08:49 NETem-v3.qcow2
behlers@dell:~$ 
```

**Comment by ehlers** [comment]
Update: The test123 file in the GNS3/images/QEMU subdirectory is from a test that leads to the next issue. It wasn't there, when I made the initial tests.

**Comment by ehlers** [comment]
Some progress:
Reverted change https://github.com/GNS3/gns3-gui/commit/5f87be16d7121be2b84c9bd91f767ece45d8cf82, now it works without hangups.

On my iMac, I had this scanning hangup every time (I know I can't import the appliance, I just wanted to test the first part of the appliance import). With reverting that change it works also on my iMac.

**Comment by noplay** [comment]
Thanks a lot !

**Comment by noplay** [comment]
Which version of Qt do you have on OSX? I'm trying to reproduce the hangup

**Comment by noplay** [comment]
And which version of Python? 

Thanks a lot

**Comment by ehlers** [comment]
GNS3 version 1.4.0.dev9 on Darwin (64-bit) with Python 3.5.0 Qt 5.5.0.

I have updated OS X to El Capitan (10.11) and installed Python3 and QT5 with homebrew. Until now everything else is working fine with GNS3 in this environment.

**Comment by noplay** [comment]
Ok almost the same system.

**Comment by ehlers** [comment]
Maybe it depends on the speed of the system. My iMac is rather old with an i5 processor, while the linux system has an i7.
![bildschirmfoto 2015-10-12 um 18 04 34](https://cloud.githubusercontent.com/assets/896406/10432532/f423ca32-710b-11e5-9530-bac1e7f195e9.png)

**Comment by ehlers** [comment]
BTW: I did a fresh install of El Captitan and all applications. So no leftovers of the old system.

**Comment by ehlers** [comment]
As an additional test, I downloaded the nightly build GNS3-unstable.2015-10-12.dmg . To be absolutely sure, I moved /usr/local/bin and /usr/local/lib out of the way:
```
/Users/behlers# mv /usr/local/bin /usr/local/bin.test
/Users/behlers# mv /usr/local/lib /usr/local/lib.test
```
Then tested with this nightly build, same problem, import of an application hangs always.

**Comment by noplay** [comment]
Can you try with the last unstable from git? I tried a fix. I can build you a new nightly if you don't have the tools on your imac.

Probably related to the speed. I have an SSD.

Thanks a lot

**Comment by ehlers** [comment]
You did a git pull to get the latest unstable and verified, that it includes your patch.
Sad enough, it doesn't solve the problem. Still hanging at the scanning for images.

**Comment by noplay** [comment]
I will test with an old macbook

**Comment by noplay** [comment]
Good news I have the issue on my old macbook.

**Comment by noplay** [comment]
Reinstalling a dev environment on this laptop is painful ... Damn Xcode !

**Comment by noplay** [comment]
Weird I finally found a way to replicate it. It doesn't happen when I open the window but if an image is missing and I click on the refresh button I have the problem. But only on the el capitan laptop.

**Comment by noplay** [comment]
I think finally found  the issue: a6ddddea991b930d5e4d80839e8d5873806c9252

Could you try with last unstable ?

**Comment by ehlers** [comment]
That fixed it, both on Linux and iMac/OS X. Tested your fix https://github.com/GNS3/gns3-gui/commit/a6ddddea991b930d5e4d80839e8d5873806c9252 + the revert https://github.com/GNS3/gns3-gui/commit/ba564869a07b949d2ceaef0a0cfba61e410989d4

Good job !!!

**Comment by noplay** [comment]
Thanks for the feedback

**Comment by noplay** [comment]
It's backported for 1.3.12
