### ISSUE TITLE
Replace QtWebkit by QWebengine

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#716]
Qt 5.6 is planned for the 8 december and will remove QtWebkit in favor of QWebengine.

**Comment by noplay** [comment]
This mean the minimum PyQT version will be 5.4. But ubuntu 14.04 has 5.2...

**Comment by noplay** [comment]
And Debian Jessie has QT 5.3

**Comment by grossmj** [comment]
The cleanest solution would be to support both.

**Comment by grossmj** [comment]
Best is to use a QWizard instead. I've created a mock up there: https://github.com/GNS3/gns3-gui/commit/ab071cd989e3924fdd5a09c65c52e340f573afa9

Just open it with QDesigner and run it (CRTL+R) to have an overview. I think this is quite clean.

**Comment by grossmj** [comment]
This can wait after beta 4 but we must have something before our first RC.

**Comment by noplay** [comment]
Replaced by #731
