### ISSUE TITLE
Test, validate and polish Docker implementation

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#717]

**Comment by noplay** [comment]
Related issues: #644

**Comment by noplay** [comment]
We need to rewrite it for using asyncio. This mean also to drop the docker-py library (a good thing I think).

I think the most simple it's to use the same method as other emulator. Just call the binary.

**Comment by noplay** [comment]
Capture is not supported.

**Comment by grossmj** [comment]
Shouldn't be too complicated to do using uBridge. I can take care of it later if you prefer.

**Comment by noplay** [comment]
Remote console is working on docker_cleanup branch. A lot of stuff to do before having something we can merge. Probably for the end of the week.

**Comment by noplay** [comment]
The console require aiohttp 0.19  this mean we can't ship docker with 1.4

**Comment by noplay** [comment]
You can't modify a container :( you need to delete it  and recreate it
