### ISSUE TITLE
Support for suspend to disk / resume

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#725]
https://community.gns3.com/ideas/1876

**Comment by grossmj** [comment]
How to suspend in Qemu:

```
behlers@dell:~$ qemu-img create -f qcow2 test.qcow2 -o backing_file=junos-vsrx-12.1X47-D20.7-domestic.qcow2
Formatting 'test.qcow2', fmt=qcow2 size=1933574144 backing_file='junos-vsrx-12.1X47-D20.7-domestic.qcow2' encryption=off cluster_size=65536 lazy_refcounts=off
behlers@dell:~$ ls -l test.qcow2
-rw-r--r-- 1 behlers behlers    197120 Okt 15 10:04 test.qcow2
behlers@dell:~$ qemu-system-x86_64 -m 1024 -smp 2 -enable-kvm -monitor stdio test.qcow2
QEMU 2.1.2 monitor - type 'help' for more information
*** Wait until the VM is fully booted ***
(qemu) stop
(qemu) savevm test123
(qemu) q
behlers@dell:~$ qemu-img snapshot -l test.qcow2
Snapshot list:
ID        TAG                 VM SIZE                DATE       VM CLOCK
1         test123                739M 2015-10-15 10:07:17   00:01:08.071
behlers@dell:~$ ls -l test.qcow2
-rw-r--r-- 1 behlers behlers 788070400 Okt 15 10:07 test.qcow2
behlers@dell:~$ qemu-system-x86_64 -m 1024 -smp 2 -enable-kvm -monitor stdio test.qcow2 -loadvm test123
*** The VM is almost instantly fully booted ***
QEMU 2.1.2 monitor - type 'help' for more information
(qemu) q
```

**Comment by grossmj** [comment]
We already have a suspend feature for Qemu VMs but this works similarly to Dynamips, which is more like a pause feature.

**Comment by ehlers** [comment]
Sad enough the original text is gone. It was meant to speed up big/slow booting VMs. Instead of shutting down the VM at the end of using a project, it should be possible to suspend it to disk. When the project gets re-opened and the VM gets started it should use the created snapshot. That should (hopefully) result in a very fast startup of that VM.

It was wanted not only for qemu, but also for VirtualBox and VMware.

This is different to the current suspend feature, what is more a suspend to RAM.

**Comment by grossmj** [comment]
Hey I was writing that https://github.com/GNS3/gns3-gui/issues/2058 issue and saw your comment here :)

**Comment by grossmj** [comment]
I've added support for this, see https://github.com/GNS3/gns3-server/commit/3d1ee4da3fe964aa3af1c43688065adbf2d2c379

This is an option that must be enabled in the VM preferences (Advanced settings). It worked well during my tests but I marked this option as experimental just in case for now. Please re-open if you find an issue.
