### ISSUE TITLE
Replace the web based appliance importer by a Wizard

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#731]
Avoid complicated dependencies and make it more integrated.

**Comment by noplay** [comment]
A first mockup:
ab071cd989e3924fdd5a09c65c52e340f573afa9

**Comment by noplay** [comment]
I have trouble with this screen:
![image](https://cloud.githubusercontent.com/assets/345437/10577402/4bcc439a-766b-11e5-86ac-0f7fd6ee0478.png)

This doesn't support appliance with multiple version available.

**Comment by noplay** [comment]
What do you think about:
![image](https://cloud.githubusercontent.com/assets/345437/10577634/23a4a7f2-766d-11e5-9a19-cb49f1e2fc92.png)

**Comment by grossmj** [comment]
At first I was thinking we could pick the version on the first page but now I quite like that you can see all available versions + files at the same time. Then when selecting one version or one of its files in the table and press next we display a QMessage asking "Would you like to install NX-OS 8.0?" Yes/No. If a file is missing for that version then we show an error message. Does this sound good to you?

Also, we will need something to pick the emulator when we support more than just Qemu for a same appliance (most likely on the first page).

**Comment by noplay** [comment]
And a choice of server instead of the final popup.

**Comment by noplay** [comment]
```
Then when selecting one version or one of its files in the table and press next we display a QMessage asking "Would you like to install NX-OS 8.0?" Yes/No. If a file is missing for that version then we show an error message. Does this sound good to you?
```

I Agree

**Comment by noplay** [comment]
I'm on it
