### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

### ISSUE THREAD

**Issue by osamehz** [GNS3/gns3-gui#735]
Traceback (most recent call last):
  File "./gns3-gui\gns3\http_client.py", line 718, in _processResponse
  File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_configuration_page.py", line 261, in _getQemuBinariesFromServerCallback
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

**Comment by noplay** [comment]
Hi,

On which GNS3 version the error appear? 

Thanks for the help

**Comment by osamehz** [comment]
Gns3 
Version 1.4.0 beta4

**Comment by noplay** [comment]
Step to reproduce:
* right click on a qemu node
* open the configuration dialog
* close it before list of qemu binaries is loaded
* you got the error

**Comment by noplay** [comment]
It's always the same issue with PyQT we got callback on a gui element that no longer exists :(

**Comment by noplay** [comment]
Good way to replicate it open the windows and brute force the escape key.

**Comment by noplay** [comment]
#596 is the same type of error

**Comment by noplay** [comment]
Fixed will be ship in RC1. Thanks for the help
