### ISSUE TITLE
Progress dialog remains

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#741]
Sometimes progress dialogs don't close (see screenshot) and cannot be close manually. I've only seen this on Linux.

![progress_dialog_bug](https://cloud.githubusercontent.com/assets/4752614/10824374/c419fef2-7e25-11e5-848c-fdf8c67c74ca.png)

**Comment by noplay** [comment]
WIth this painting issue?

**Comment by grossmj** [comment]
Yep, looks like it is.

**Comment by noplay** [comment]
Which version of Qt and PyQT do you have?

**Comment by grossmj** [comment]
```
=> version
GNS3 version is 1.4.0dev10 
GNS3 Converter version is 1.2.3
Python version is 3.4.3 (64-bit) with utf-8 encoding
Qt version is 5.2.1
PyQt version is 5.2.1
SIP version is 4.15.5
```

**Comment by noplay** [comment]
Perhaps is a related to the old Qt.

**Comment by grossmj** [comment]
This is the default version for Ubuntu 14.04 :(

**Comment by grossmj** [comment]
Looks like I found the solution. Should be tested on Windows and Mac to be sure it doesn't trigger any unexpected issue.

**Comment by ehlers** [comment]
No problems with your change on Mac OS X 10.11.1 (El Capitan) with Python 3.5.0 Qt 5.5.0. Since https://github.com/GNS3/gns3-gui/issues/713 the import works fine for me.
