### ISSUE TITLE
Portable GNS3 on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#745]
So GNS3 can be run from an USB drive for instance.

**Comment by noplay** [comment]
With the GNS3 vm it's harder to make.

**Comment by danieldemers** [comment]
If the VM is remote/ESXi based it be great to add configuration in a portable GNS3 client to define local LAN and public Internet IP Address/Port assignments to allow the portability.

**Comment by RyanBreaker** [comment]
It would be great as well to have a portable edition of just the client/GUI that can be installed without admin permissions, much like other programs that install to the user's AppData directory, and without the extra things not everyone needs like Pcap and Wireshark.
