### ISSUE TITLE
Default name format

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#748]
I think it would be great if we could choose default device name for each IOU device.
It is a bit boring to edit IOU<num> to R<num> or SW<num>, especially if you have 20-40 devices.

**Comment by grossmj** [comment]
Two ways to look at this

- If the IOU image is a L3 image, make the default naming prefix R, if the  the IOU image is a L3 image, make the default naming prefix SW

- Add an extra step in the New IOU device template wizard, asking the user for a default naming prefix. 

And for that matter, add an extra step in the New IOS router template wizard (and maybe the QEMU wizard) as well for consistency
 
And in either case, add an extra Default name prefix: attribute to the device/router template in Edit mode:

![default_name_prefix](https://cloud.githubusercontent.com/assets/4752614/10897730/19e595c2-8181-11e5-98e9-544625a511e5.png)

**Comment by Raizo62** [comment]
Hi,

You can perhaps do the same thing (Default name prefix)  with VM from VirtualBox/VMWare and Cisco Router ?

With VirtualBox, we will have an "original" VM with a long name (defined only in VirtualBox), and clones with a short default name prefix. Then, It will be more difficult to rename the clone with the same name as Original VM

**Comment by grossmj** [comment]
@noplay can this be applied to Docker containers as well?

**Comment by noplay** [comment]
At this time Docker container use the name of the image. For example:
* busybox-1
* apache-2

**Comment by grossmj** [comment]
@noplay I've implemented it for Docker but couldn't really test (even with experimental features activated).

**Comment by Raizo62** [comment]
Hi

Did you not forget to deactivate the option to log into console window when we use an VirtualBox VM ?

**Comment by noplay** [comment]
@Raizo62 I didn't understood, perhaps @grossmj know. 

@grossmj oh for me the code of docker was no longer in the 1.4 branch since it's not working. Seem it's not the case and removed it will probably create . I try to merge it against 1.5 and it's a failed, it's normal they diverged so much :( I removed the code from master and tell to git to ignore this specific change when merging in 1.5. But your patch need to be rewrote against 1.5.

**Comment by grossmj** [comment]
@Raizo62 I didn't get it either :(

@noplay ok, shouldn't we clean the 1.4? I will rewrote against 1.5

**Comment by Raizo62** [comment]
Good new : with the last code, my bug has disappeared...

**Comment by Raizo62** [comment]
In GNS3, VirtualBox is not similar to IOU/IOS/QEMU.

With IOU/IOS/QEMU, the image file can describe the OS, and we can have an simple name in GNS3.

With VirtualBox, le name in the Dock of GNS3 is the name of the VirtualBox.

In the stable realease of LiveRaizo, the name of VirtualBox is "Debian", and in the topologie the name is become "Debian-1". If i rename it from "Debian-1" to "Debian", i think that i can have problem : VirtualBox have 2 VM called "Debian"

With this functionality of GNS3, the name of VirtualBox can be "VMRaizo-Debian-Jessie-vDate", and in the topologie the name is "Debian-1". It is more difficulte to rename "Debian-1" to "VMRaizo-Debian-Jessie-vDate". But it is not super to have "VMRaizo-Debian-Jessie-vDate" as name in the Docker.

As IOU/IOS/QEMU, can we also choose the name in the docker ?

**Comment by Raizo62** [comment]
If it take too works to change interface of VMBox configuration, can wee have an option in the gns_gui.conf ? 

By default, it will be the same value of the name in VirtualBox.
But, we can change it by hand....

**Comment by Raizo62** [comment]
Hi,

Sorry, there are a bug.

I have 2 VMBox : VMRaizo-Jessie and Windows-2003-server
I change "Template name" of each VM into GNS3
- VMRaizo-Jessie : Debian
- Windows-2003-server : Win2003

When i put on the lab 1 device (VMBox), GNS3 asks me to choose the VMs : VMRaizo-Jessie or Windows-2003-server ?
