### ISSUE TITLE
Crash when closing GUI on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#749]
Environment: Windows 7 VM on VirtualBox.

Steps to reproduce: just start and then close GNS3.

![gns3_crash](https://cloud.githubusercontent.com/assets/4752614/10897858/4bc8a128-8182-11e5-8194-73623676279d.png)

**Comment by grossmj** [comment]
What changed since beta 4?

**Comment by noplay** [comment]
Qt version

**Comment by noplay** [comment]
And the patch for progress dialog

**Comment by noplay** [comment]
![capture d ecran 2015-11-03 a 09 37 26](https://cloud.githubusercontent.com/assets/345437/10903884/b33c86b2-820e-11e5-949f-4a42bdbd1329.png)

**Comment by noplay** [comment]
My patch doesn't seem to have fixe the crash :(

**Comment by noplay** [comment]
And on windows 10 I have no information about where it's crash

**Comment by noplay** [comment]
Ok tested with Qt 5.5.0 and it also crash

**Comment by noplay** [comment]
Perhaps the problem is related to that:
http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#object-destruction-on-exit

**Comment by noplay** [comment]
It seem ok now  by stopping calling deleteLater on app ...
