### ISSUE TITLE
Ability to configure proxy settings

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#750]
If a Windows PC is behind a proxy server and if the gns server is hosted on a remote server, there is no way to access the server using the gns client as we cannot configure proxy authentication settings for gns client.

Gns does not use the proxy settings that are configured with internet explorer. This is also the case when it us run as administrator.

So please provide a feature to configure proxy settings and authentication for GNS3

**Comment by noplay** [comment]
Problem is the user can't access also to the consoles and the VNC. If we do that we need a way to tunnel the console port via the HTTP connection. Or embed in the server a web console and a web vnc.

**Comment by noplay** [comment]
I think that now we have instructions about how to setup a VPN we can close this issue.

**Comment by adosztal** [comment]
An additional request: https://gns3.com/community/discussion/how-to-configure-proxy-settings-
Working for a corporate, I can only second this. No matter what product it is, we must use proxies that do all sort of protection. Is it possible to add this feature?

**Comment by jbulow** [comment]
Are there any plans to allow gns3-ui to work behind a http proxy? All downloads initiated from the UI fails due to inability to use the http proxy settings on the system.
