### ISSUE TITLE
Global Default Font Size

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#751]
I would like the ability to set the global default font size inside the GNS3.conf file for text and device labels . I find that in ubuntu linux the fonts are too large to my taste, so I manually change them all to 9pt. It would be nice to simply set the default font size in the GNS3.conf file and be done with it.

**Comment by noplay** [comment]
We have risk of breaking interfaces if we do it.

**Comment by grossmj** [comment]
We already have this in Preferences => Topology View => Default label style.
