### ISSUE TITLE
Project Backup Tool

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#760]
When you upgrade from 1.3 to 1.4 and even from sub versions to sub versions you are always advised to backup your projects. It would be helpful for many users to have 2 click backups and 2 click retrieval.
 
The proposed idea would be adding the following functions:
 
1) Automatic copy/backup of all projects into a separate folder (backups folder - for windows users it would be under the User/Documents/GNS3/Backups Folder)
2) The tool generates a list of all folders and the folders names in a list in the projects folder with a check box or toggle...so you can choose to backup all or untoggle some that you may not want to backup.
3) Same function as #2 but for retrieval of a project in case there was corruption...tool would generate a list of folders in the backups folder...and allow you to toggle or untoggle which ones you want to grab and overwrite over the current project(s) in the projects folder.
4) Allow GNS3 to pull down a copy of the directory for each lab in the VM and store it within the /GNS3/Backups/ProjectNAME/VM-Directory (this one is similar to Stephens One Button Export of Labs  idea). The VM-Directory is not that big...I am however unsure of what technical issues may arise in trying to transfer directories between client and VM.
5) For #4 to be viable...there may need to be a oops check needed so you do NOT overwrite more recent labs that are just fine on the VM.
6) This function is directly a copy from Stephens....the ability to instead of sending the backup to a folder automatically...but instead export the same info to a zip....this would support the desire to have a backup but more importantly....support sharing of labs etc...images or IOU and IOS...is still the responsibility of the user and I do not think should be addressed till Cisco figures out an educational free licensed version of IOU and IOU is a great idea.
 
When you try to retrieve a project that has the GNS3 Lab data (BIG NUMBER for each folder...) it should be able to grab the lab directory and place in the project folder for safe keeping in the backups folder....once it is retrieved the lab directory is uploaded in the /home/gns3/GNS3/projects/ folder of the VM...
 
This tool may directly be associated with another idea Stephen submitted: One Button Export of Labs However this is more of a upgrade/backup tool...no files the user needs to juggle as the GNS3 folder will most often never be deleted and gets carried over with upgrades...and thus the backups folder can become a companion folder.
 
I like Stephens idea but I feel this is a more all encompassing idea as IOU/Virtual is only becoming more stable and common....I am sure loading actually IOS versions which only require local folder data is not going to die but Virtual and VM related routers/switches/nexus/firewalls....etc are becoming more common and will continue to do so.
 
Dan

**Comment by noplay** [comment]
We advice to snapshot the VM and support export now.
