### ISSUE TITLE
Live collaboration on same project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#761]
There should be an easy way how to collaborate with someone on remote GNS3 server, as discussed here Live collaboration on remote gns3server
At the moment you can sort of collaborate by connecting your projects via UDP forwarding.
 
It would be great if you could just work with someone on the same topology, that when you for example add node or connection it would show on the colleagues client live, so he can for example configure the device.
 
I usually test all my project implementations in GNS3 and when the topology is really big you need helping hand of someone to test it quickly

**Comment by noplay** [comment]
It's work
