### ISSUE TITLE
Loss and latency (no appliance)

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#765]
Is there any future plans to include the ability to generate loss or latency on a link between network device?

In my own organisation we deal with redundancy a lot so ip sla's and track etc are part of all of router configurations that have gre tunnel or private line to sites across the global. But it can be very hard to test out the configuration for these command, as how do you generate loss or latency on demand in the real world. And as GNS3 is my first point of call to test out new configuration this would be hugely helpful.

It would be nice to right click on the link and click "add loss" -> 10% or "Add Latency" -> 200ms

**Comment by grossmj** [comment]
Great idea! And extremely useful feature that can be deployed link-by-link instead of using an entire Virtual Machine (ex: WANem, OpenVswitch...)
 
Interesting to know the point of view of the developers, it looks like linux have Linux Traffic Control (tc) (used in mininet), which has a number of packet schedulers to shape traffic to a configured rate...

**Comment by grossmj** [comment]
Mininet uses tc for that purpose.

**Comment by noplay** [comment]
Perhaps we could implement that inside ubridge. Traffic loss is easy. Latency more complicated.

**Comment by grossmj** [comment]
We can implement some basic traffic control in uBridge. For more advanced things we could support Linux Traffic Control (tc). The server would have to run on a Linux with tc installed of course but I think this is fair.

**Comment by noplay** [comment]
Could we use tc with udp tunnel?

Le lun. 1 mai 2017 à 12:10, Jeremy Grossmann <notifications@github.com> a
écrit :

**Comment by grossmj** [comment]
It would work only with interfaces like TAP...

**Comment by grossmj** [comment]
Note to myself: Dynamips doesn't use uBridge at the moment.

**Comment by noplay** [comment]
I will take care of the IHM

**Comment by grossmj** [comment]
New filter to implement: BPF

Than we can close that issue and work on the issues opened in gns3-server for each emulator.

**Comment by grossmj** [comment]
@noplay I think it makes sense to support multiple BPF filters on one link. Question is how to have it in the GUI?

**Comment by noplay** [comment]
A text area with one filter by line?

**Comment by grossmj** [comment]
I think that would work

**Comment by noplay** [comment]
BPF has been merged we can close this issue
