### ISSUE TITLE
Disable/Disconnect Link option

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#766]
It would be nice to be able to disconnect/disable a link between two devices from GNS3 UI without having to delete the link.  This would allow testing scenarios of link-loss effect on routers, without having to delete and then re-add links.  Not only is it more work, but you have to remember which port your 'virtual cable' was connected to, and the device interface labels reset positions for re-added links, meaning even more work to re-layout the diagram after restoring 'deleted' links.  Technically the disabled link would operate just as if it were deleted, but would remain in the UI ready to be reconnected.  I figure from a UI standpoint it would be simple enough to just grey out links or maybe change the link status color (NOTE I'm aware of the technical problems with link status color reflecting device configuration, and that's not what I'm referring to, just link status color reflecting that the connected link is disabled in GNS3.  Alternatively I guess the link line itself could change color or become dotted or something...)

Personally I could have used this because I was running a number of lab simulations of routing protocol and HSRP/GLBP behaviors in complex environments (9-13 routers simulating HA LAN/WAN across multiple sites) and shutting down an interface in the config is not always the best way to simulate a link/communication failure between devices because the device reacts differently to a shutdown interface than one which just stops communicating with the connected device.  And I had a lot of link interconnects to simulate failures on, so the process of deleting them and re-adding them was cumbersome, and as I mentioned the labels then shift around.

**Comment by grossmj** [comment]
I think a grey dotted line would be the go to indicate a inactive link.

**Comment by pdugas** [comment]
+1

**Comment by Vic563** [comment]
Is there an ETA on this feature request?

**Comment by noplay** [comment]
No ETA for the moment

On Thu, Mar 23, 2017 at 5:41 PM Vic563 <notifications@github.com> wrote:

Is there an ETA on this feature request?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/766#issuecomment-288781799>, or mute
the thread

**Comment by pdugas** [comment]
Any ideas how to simulate a disconnect?  I tried using a hub in between but there's no way to turn the hub off.  Wondering if someone had another clever idea.

**Comment by noplay** [comment]
In 2.0 remove the cable you do it when the VM running. But for the moment no way to temporary disable it.

**Comment by grossmj** [comment]
Duplicate of https://github.com/GNS3/gns3-gui/issues/1295
