### ISSUE TITLE
Customize Device list

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#768]
This is a very simple one: having a customizable folder view or tree view of the device list in GNS3

Until now it was ok the way it was but with the increasing number of options (VMware-Vbox-Qemu) and devices supported, it' starting to be a little messy

**Comment by grossmj** [comment]
@noplay any comment?

**Comment by noplay** [comment]
I think an easy improvement is an input filter at the top.

After reading your idea. I think about something. Perhaps the configuration of device could be in a folders and the node view is a kind of file browser.

Example:
``` 
# ls ~/GNS3/appliances
routers
switch
pc

# ls ~/GNS3/appliances/routers
cisco
alcatel

# ls ~/GNS3/appliances/routers/cisco
7200.gns3a
```

The advantage is it's totally flexible and easier to share the config with multiple PC (you can sync the folder). Also it's easier to backup. 

Another advantage it's start moving non Qt stuff outside the GUI config. Making it easier to move to a web interface later.

But it's a major change. Idea to discuss.

**Comment by grossmj** [comment]
Would be part of https://github.com/GNS3/gns3-gui/issues/2202
