### ISSUE TITLE
Reset all interfaces

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#773]
The issue I am having is that each time the XRv VM is reloaded for whatever reason (obviously including loading the topology), the interfaces connected to the XRv platform(s) need to be deleted and recreated before they work.

An idea is to have a button / function to reset / recreate all the connected interfaces in one go (and possibly build this into the start up sequence as an option).

**Comment by grossmj** [comment]
Similar to https://github.com/GNS3/gns3-gui/issues/50

**Comment by noplay** [comment]
It's with vmware?

**Comment by grossmj** [comment]
I believe this is with VirtualBox.

**Comment by grossmj** [comment]
Nobody reported a similar issue.
