### ISSUE TITLE
View interface labels

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#778]
Can this option be saved in the project?  Right now i have to keep toggling it on depending on the project and it would be nice if it saved it in the project settings.

**Comment by grossmj** [comment]
The state of that button could be saved locally in the GUI preferences.

**Comment by noplay** [comment]
Or it's a general settings? Perhaps user want to enable it for all his projects. Not sure what is the best options. It's a small improvements easy to ship.
