### ISSUE TITLE
Enhancement request for VPCS multi-host

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#782]
Is it possible to start the VPCS multi-host instance when a someone hits the "Start" button in a topology that is using the multi-instance VPCS?
 
Similarly, if someone hits the "stop" button, then if multi-host instance of VPCS that was started (either by clicking the "start" button, or by selecting Tools | VPCS Multi-host) should also be stopped. I guess this might be a bit tricky, because you'll have to keep track of process numbers (because you can't assume that ALL instances of VPCS need to be stopped)

**Comment by noplay** [comment]
I propose to move the multi host to the deprecated settings #1044 and to close this.

The multi host is good to use less ressources but it's break totally the control of GNS3 over the VPCS instance and we will have hard time to move it to the server side when we will need to do the move. The only usage we know is in GNS3 Workbench.

**Comment by noplay** [comment]
Support removed in 2.0
