### ISSUE TITLE
Add a grid

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#787]
It will be excellent if grid is implemented in network design area to place items (routers, switches etc) in a symmetry to have more professional look.

**Comment by grossmj** [comment]
A grid that could be turned on and off would be a fine feature, but associated with that you really need features like the alignment options and possibly a "Snap to grid" feature.

**Comment by comet0** [comment]
If you still need this, I made a small patch that enables an 'invisible' grid on the workspace that snaps all 'nodes' to a 75x distance.

It is extremely hacky and could be implemented better by anyone who understands GNS3's codebase better but it works at least.

image: http://i.imgur.com/2moCp4s.png
patch: https://gist.github.com/comet0/ca90a77aa2a1c60f7022b32483e958d5

**Comment by noplay** [comment]
Thanks

I think their should be a way to implement that in the NodeItem directly and only when user move it to avoid trouble if two user are connected with different grid resolution. 

Show a grid seem to be possible and not too much complicate:
http://www.qtcentre.org/threads/5609-Drawing-grids-efficiently-in-QGraphicsScene?p=28905#post28905

We could have a Snap to grid checkable option in the menu like what we do for Docks:
![image](https://cloud.githubusercontent.com/assets/345437/16185871/330b8f4c-36c7-11e6-8714-5cd597d0a35c.png)

**Comment by comet0** [comment]
Pull request up: https://github.com/GNS3/gns3-gui/pull/1322

**Comment by noplay** [comment]
Awesome

**Comment by noplay** [comment]
The 1.5 will have the snap to grid feature.After that we will need a features to show the grid before closing that issue.

**Comment by ehlers** [comment]
The current implementation is a good start, but snaps the top left edge. For different sized elements it looks like this:
![snap_to_grid](https://cloud.githubusercontent.com/assets/896406/16192021/5ac95602-36e7-11e6-9b77-50ac48971d0c.png)

I would prefer, when the center of an element is snapped to this grid, similar as it's done in the alignment code. Then the result could look like this:
![snap_to_grid_center](https://cloud.githubusercontent.com/assets/896406/16191961/163aa5f4-36e7-11e6-958a-d0003d291fc8.png)

**Comment by comet0** [comment]
I should have thought about that before, 
I have a working patch now with all nodes centered around their center
[demo screenshot](http://i.imgur.com/h9owKee.png)
Though due to clouds being larger than the 75px grid size items can overlap on the grid

patch: https://gist.github.com/comet0/6251ab4c29d066390cf04a0350d69a00

**Comment by noplay** [comment]
I think we can get the center like this:
```python
center = self.mapFromItem(self, self.width() / 2.0, self.height() / 2.0)
```

**Comment by noplay** [comment]
Thanks I will add your patch and an option to enable the grid

**Comment by noplay** [comment]
View grid added and item centered
