### ISSUE TITLE
GNS3 Python API

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#790]
It would be great to have a python module to access GNS3 topology control, like:
 
- shut down / bring up interfaces
- reload / stop / start devices
- build connections between device interfaces
- Control link quality, even during topology running (emulate link quality degradation)
mininet-like:

Emulated Links. The data rate of each link is enforced by Linux Traffic Control (tc), which has a number of packet schedulers to shape traffic to a configured rate...
ex: self.addLink(host, switch, bw=10, delay='5ms', loss=10, max_queue_size=1000)

- add devices to the topology

**Comment by noplay** [comment]
It's partially done with the REST Api. But the management of multiple servers make it hard to use for users.

**Comment by noplay** [comment]
This issue was moved to GNS3/gns3-server#353
