### ISSUE TITLE
 Auto-add interfaces to generic switch

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#793]
In GNS3 v0.8.7, the generic Ethernet switch can with 8 interfaces by default, but once you has saved your project, the number of interfaces on the generic Ethernet switch was reduced to the number needed to build the topology.
 
However, this fact was never that obvious, because should you ever need to add an additional  connection to the generic switch in the future, an additional interface would be automatically added at the time you needed it – even beyond the 8 default interfaces if required – a VERY handy feature.
 
But one that I'm sad to say is.. Missing In Action (MIA) in the v1.x versions
 
Could we have it back please?  I don't use the Hub device, but I suspect it would also be useful there too.

**Comment by noplay** [comment]
@grossmj with 2.0 changes is it relevant?

**Comment by grossmj** [comment]
Not really a big issue. I think this can wait for 2.1. We should really focus on the architecture and back-end stuff for 2.0

**Comment by noplay** [comment]
The 2.0 switch has 8 interface by default
