### ISSUE TITLE
Issue connecting a node to a virtual bridge

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#800]
Hello guys,
I'm not sure whether this feature is implemented or not, but it would be nice if the nodes could communicate with Linux virtual bridges:
```
brctl show  
bridge name bridge id STP enabled interfaces  
virbr0 8000.5254009d4405 yes virbr0-nic  
virbr1 8000.525400ffebb0 yes virbr1-nic  
virbr10 8000.525400a8ff01 yes virbr10-nic  
virbr11 8000.525400335153 yes virbr11-nic  
virbr2 8000.5254000d35ae yes virbr2-nic  
virbr3 8000.5254002a7ee2 yes virbr3-nic  
virbr4 8000.52540097ec52 yes virbr4-nic  
virbr5 8000.5254004491cb yes virbr5-nic  
virbr6 8000.5254005f9a92 yes virbr6-nic  
virbr7 8000.525400573542 yes virbr7-nic  
virbr8 8000.525400960209 yes virbr8-nic  
virbr9 8000.525400e89e8c yes virbr9-nic  
```
They can easily be created by virt-manager:
![image](https://cloud.githubusercontent.com/assets/345437/11058851/f4ff337e-8795-11e5-9598-c272a17afe0a.png)

 
If I try to ping a virtual bridge (virbrn), there's no answer.
If I try to link a virtual bridge interface (virbrn-nic) to a switch called node, there's the following error:
Server error from 127.0.0.1:8000: Mgt: unable to create generic ethernet NIO

Details are here: https://community.gns3.com/message/50908?et=watches.email.thread#50908

**Comment by noplay** [comment]
Don't know if it should work actually.

**Comment by jean-christophe-manciot** [comment]
It would allow us to establish communication between GNS3 nodes & VMs which are running on these virtual bridges.

**Comment by grossmj** [comment]
I don't know if the libpcap can be used on Linux bridges. I usually do not use Linux bridges.

**Comment by jean-christophe-manciot** [comment]
Libvirt, virt-manager & Ganeti make extensive use of Linux bridges.
They do not use tap interfaces.

**Comment by jean-christophe-manciot** [comment]
For example, when trying to simulate a DC/cloud with GNS3, we might need to interface the topology with a SDN controller, OpenStack (DevStack), Cisco's APIC-EM and so on...
So far, it is impossible because these VMs need virtual bridges to communicate with the other nodes.

**Comment by grossmj** [comment]
Well don't really know how libvirt works and I don't know what the usage of virbrn-nic which is down by default (maybe that's why you got the "unable to create generic ethernet NIO" error).

However, I could find some interesting info there: http://forum.gns3.net/topic5513.html

For me this isn't a GNS3 issue.

**Comment by jean-christophe-manciot** [comment]
It is an excellent article indeed, and I've been using this workaround for a few months.
However, it's just a trick and we have to remember which tap interface has been connected to which Linux bridge. 
The common GNS3 user won't go that far IMHO.
According to this [link](https://www.redhat.com/archives/libvirt-users/2012-September/msg00038.html), virbrn-nic interfaces cannot be used for traffic (Red Hat is the creator of libvirt/virt-manager, so I assume we can rely on the previous thread).
So the solution is to dynamically [create/delete new ones as needed by the user](http://unix.stackexchange.com/questions/152331/how-can-i-create-a-virtual-ethernet-interface-on-a-machine-without-a-physical-ad) and connect/disconnect them (brctl addif/delif) to the correct new (brctl addbr/delbr) or existing [virtual bridges](http://www.linuxfoundation.org/collaborate/workgroups/networking/bridge#Network_cards), without disturbing the local existing networking environment (a prior probe is necessary of course with brctl show).
I don't know whether all this can be done on Windows platforms but it may be possible on OS X.
