### ISSUE TITLE
Cannot rename a new "untitled" project

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#804]
Moved from:
https://community.gns3.com/ideas/1865

The bug started with version 1.3.2 . everything was fine until today, it just started out of nowhere.  I upgraded to version 1.3.9 and the bug is still there. Could you help me fix this?
I can create "untitled" just fine, but when I try to "save as" and point to a different location other than the Projects folder I get these errors.
I receive these errors when I try to create a new project and rename it in the Projects folder.

![image](https://cloud.githubusercontent.com/assets/345437/11059930/29c93292-879d-11e5-9c72-039de1fd34ca.png)

![image](https://cloud.githubusercontent.com/assets/345437/11059934/34773d38-879d-11e5-99ea-472f31342e42.png)

![image](https://cloud.githubusercontent.com/assets/345437/11059936/385e7b00-879d-11e5-84f2-3d1392942ca6.png)

![image](https://cloud.githubusercontent.com/assets/345437/11059941/3c98245a-879d-11e5-9a51-2a40af906c5e.png)

![image](https://cloud.githubusercontent.com/assets/345437/11059946/439824ee-879d-11e5-94b2-5b2d3e59f05f.png)

**Comment by noplay** [comment]
I don't see how to replicate it.In the first screenshot the user got a \n at the end of the path.

**Comment by grossmj** [comment]
Don't see how to replicate it too. Nobody else complained about it either, let's close it.
