### ISSUE TITLE
Changing text color break formatting

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#805]
Hello,
 
I discovered another bug, same kind as this Change in color of multiple blocks of text results change in rotation or this Editing properties of multiple blocks of text doesn't work well
This time I wanted to change colour of multiple differently formatted (different letter size - check text "10.10.10.0/24") blocks of text. This change results to change in formatting.
 
Before:
![image](https://cloud.githubusercontent.com/assets/345437/11060587/784b1a80-87a1-11e5-9412-914bf38a7916.png)

After:
![image](https://cloud.githubusercontent.com/assets/345437/11060593/82b2ce5a-87a1-11e5-8f42-d9c62dbbcd70.png)

https://community.gns3.com/ideas/1579

Hello GNS3 team,
 
I have encountered similar bug as was reported here: Editing properties of multiple blocks of text doesn't work well
 
I wanted change a color of multiple rotated blocks of text...
![image](https://cloud.githubusercontent.com/assets/345437/11060610/9573f4c4-87a1-11e5-9e1a-bd95aef6c4b7.png)

...and I got this:
![image](https://cloud.githubusercontent.com/assets/345437/11060622/a1bcbe82-87a1-11e5-8e68-e16d98d0cc24.png)

P.S.: please implement this idea Rotation using mouse   
 
Thank you for your hard work!

**Comment by noplay** [comment]
It's work as designed. If you select multiple text the same rotation will be apply.
![capture d ecran 2015-11-10 a 16 38 41](https://cloud.githubusercontent.com/assets/345437/11066707/90379cfe-87c9-11e5-85f1-9aeee5b1de76.png)

But I agree that the user need to be able to Apply the rotation to only some nodes.

**Comment by grossmj** [comment]
Should we have another checkbox like "Apply the text below to all selected items" but for rotation?

**Comment by noplay** [comment]
I agree

**Comment by noplay** [comment]
Editor updated
![capture d ecran 2016-01-26 a 14 10 10](https://cloud.githubusercontent.com/assets/345437/12581419/af8c4b14-c436-11e5-84d5-06d281986ae0.png)
