### ISSUE TITLE
View | Reset Interface labels doesn't work

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#811]
From red nectar:
Maybe this is just another Favourite Feature that is MIA , but when you choose View | Reset interface labels - irrespective of whether you have them showing at the time or not (in v0.8.7 you would be warned that you had to hide the labels before resetting them) - nothing happens.
 
So bug or MIA - can you please put it on the roadmap to be fixed?

**Comment by noplay** [comment]
What should happen when I use this button? The position of the label should be reset to the original position.

**Comment by grossmj** [comment]
Exact.
