### ISSUE TITLE
I have to delete the connection and add it again to regain Network Connectivity

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#814]
https://community.gns3.com/ideas/1684

Hello All,
 
I re-submit this as a bug, as the first one marked as delivered. Below is the history
 
I have the following
GNS3 ver 1.2.1
operating system: win7 64bit
2 Routers running IOS XR
1 IOU (switch) runs L2 image
 
I have the 2 routers connected as following,
```
R1:int Gig 0/0/0/5 is directly connected to R2:int Gig 0/0/0/5
R1:int Gig 0/0/0/5 IP: 10.2.1.1/24
R2:int Gig 0/0/0/5 IP: 10.2.1.2/24
```

Then using IOU1 to connect
```
R1:int Gig 0/0/0/0 to R2: int Gig 0/0/0/0 
R1:int Gig 0/0/0/0 is connected to Eth 0/1 IOU
R2: int Gig 0/0/0/0 is connected to Eth 0/2 IOU
R1: int Gig 0/0/0/0 IP: 10.1.1.1/24
R2: int Gig 0/0/0/0 IP: 10.1.1.2/24
```
 
The above works great until I close GNS3 and open it again and load the same project
 
When I turn everything off, save everything and close GNS3, then open GNS3, I can't ping any IP andI have to delete the connection and add it again to regain Network Connectivity
 
I believe this must be a bug.. Please advise
 
![image](https://cloud.githubusercontent.com/assets/345437/11064997/127c308e-87c1-11e5-85ed-11d248202f64.png)

 
  Jeremy Grossmann Employee Jan 4, 2015 5:02 PM

Hi,
 
Do you mean you can't ping from any device?
 
  H G Jan 4, 2015 5:26 PM (in response to Jeremy Grossmann)

yes. everything stops
 
  Jeremy Grossmann Employee Mar 14, 2015 9:37 PM

Hi,
 
This should work in GNS3 1.3 (to be released soon). You may try with GNS3 1.3.0 beta 2
 
Thanks,
 
  H G Mar 31, 2015 12:52 AM

Hello Jeremy,
 
Thanks for your effort and amazing application.
 
I have installed GNS3 1.3 and this didn't fix the issue. Exactly the same issue. It gives me really hard times when
 
1- save the project, start it again, I have to disconnect links, reconnect again tons of times to gain Network connectivity, sometimes I get it back and sometimes I don't, and I have to reboot the whole PC, and even after rebooting the PC or closing GNS3 several times, reconnect and connect several times I don't gain Network Connectivity back
 
2- When I want to add more than 3 IOS-XR routers in the topology it acts up and never worked for me, always the fourth router doesn't work. I mean by it doesn't work that there is no Network Connectivity after configuring IP's and everything
 
3- Finally sometimes after restoring the connectivity for one router IOS-XR I mean, I don't get all interfaces working. For example if I have 4 interfaces connected. When I disconnect them and reconnect again, for some of them I can ping the other router on the other end and some of them I can't ping..
 
It became very time consuming and very exhausting to IOS-XR works without these issues.
 
Here is a sample topology, after having all IOS-XR routers working. Now I can't ping any IP from XRV2-IOS_XR_5.2.2 no matter what I do.
 
I would say this should be considered as a high priority issue..
 
![image](https://cloud.githubusercontent.com/assets/345437/11064993/09524a5c-87c1-11e5-8c3c-adf3a5cb9504.png)

**Comment by noplay** [comment]
Comment from @grossmj : 
Hi,
 
We suspect a bug with the simple Ethernet switch. Please use hubs, Etherswitch routers or IOU L2 devices instead.

**Comment by noplay** [comment]
Comment from user:
Hello Jeremy,
 
Thanks for your fast response. I tried the following
 
1- connecting to hub, same thing, no ping
2- connect to IOU switch same thing
 
3- connect IOS-XR to IOS-XR directly same thing
 
It became worse, where when you create the topology and without closing GNS3 it doesn't even ping. After so many iterations it might or it might not. Meaning, saving the project, close GNS3, open it again, no effect still ping
 
rebooting the PC, starting GNS3 same thing
 
This makes as a blocking point, since it consumes a lot of time to get it work..

**Comment by noplay** [comment]
Comment from Rene:
Hi Jeremy,
 
I experience the same problem with 1.3.1. I use both simple ethernet switches and IOU L2 devices. This does not make a difference.
When I start a project randomly routers or switches (I use only IOU L2 and L3 images) are "islands". They can't connect to anything even though the connections are there. When I delete the connections and create them again, reload the router or switch they start working again.
Difference with the above user is that I use Ubuntu 14.04 LTS and the linux GNS3 version 1.3.1.
I did not notice this problem in pre 1.3.0 versions.
 
Hope this hels. Thanks. Rene

**Comment by noplay** [comment]
I think we have solve all the link creation issue since this bug has been open. What did you think @grossmj ?

**Comment by grossmj** [comment]
If IOS XR runs in VirtualBox then this may be related to that bug with UDP tunnels on VirtualBox.

**Comment by grossmj** [comment]
Also: https://gns3.com/discussions/gns3-generail-issues-not-usable

**Comment by grossmj** [comment]
There may be 2 different problems, one with VirtualBox and one with uBridge (with VMware VMs). Still trying to isolate the issues.

**Comment by grossmj** [comment]
Old issue, cannot debug without talking to users. I'll close this for now and hope someone reports something.

**Comment by STEPHENSERO** [comment]
I can´t find a definitive solution for this problem, but a found a workaround. You can create a batch to clear interfaces on Windows:

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate1 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate2 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate3 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate4 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate5 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate6 off

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate1 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate2 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate3 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate4 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate5 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 4.3.2" setlinkstate6 on

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate1 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate2 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate3 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate4 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate5 off
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate6 off

"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate1 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate2 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate3 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate4 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate5 on
"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm "IOS XR 5.3.2" setlinkstate6 on

"IOS XR 4.3.2" and "IOS XR 5.3.2" are names of VM on VirtualBox with six interfaces. Initial string on "" is usual path of VBox installation directory.

You save on notepad with .bat extention and execute when yours routers finish start up.

Regards

Stephen
