### ISSUE TITLE
GNS3 "please wait" progress bar window hangs when trying to delete generic layer2 switch

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#815]
Reported by @AJNOURI

I would say roughly 2 times out of 5, the generic layer2 switch simply doesn't forward traffic and cannot connect to tap interface (cloud), cannot isolate specific causing behavior.
![image](https://cloud.githubusercontent.com/assets/345437/11065115/d6173200-87c1-11e5-8ff4-512ac76c27ff.png)

 
So when I try to delete it, the "please wait" progress bar window hangs
 
![image](https://cloud.githubusercontent.com/assets/345437/11065128/e0d75d14-87c1-11e5-84fc-3a82d00a6538.png)

 
I still can close the progress bar and the switch is deleted with the below message:
![image](https://cloud.githubusercontent.com/assets/345437/11065132/e5fd2d6e-87c1-11e5-828a-ee99434ed1b3.png)

Console log:
![image](https://cloud.githubusercontent.com/assets/345437/11065140/eb0e7240-87c1-11e5-88d6-5214195c8d59.png)

 
When exiting such topology, again the "please wait" progress bar window hangs, and this time I have to kill GNS3 process.
 
Sometimes, for the same topology, the issue disappear after rebooting the system.
 
 
### Environment
```
GNS3 1.3.7
Linux gns3-iouvm 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.2 LTS
Release: 14.04
Codename: trusty
```

**Comment by noplay** [comment]
Comment from @AJNOURI

The issue persists with 1.3.9.
It works normally right after a reboot, then as soon as a remove a link from the generic l2 switch or remove the switch itself "please wait" progress bar window hangs until I close it.
 

When exiting GNS3, the "please wait" progress bar window hangs until I close the windows :
![image](https://cloud.githubusercontent.com/assets/345437/11065179/2800db8e-87c2-11e5-9298-ea4c12078c63.png)

 
 
Log when removing a generic l2 switch:
 
```
2015-08-12 21:31:59 INFO link.py:137 deleting link from ASA-2 Ethernet2 to SW1 1
2015-08-12 21:31:59 INFO link.py:137 deleting link from IOU3 Ethernet1/3 to SW1 2
2015-08-12 21:31:59 INFO link.py:137 deleting link from SW1 3 to mngmnt nio_tap:tap0
2015-08-12 21:31:59 INFO device.py:93 SW1 has been deleted
2015-08-12 21:32:00 INFO http_client.py:386 Response error: Error downloading http://127.0.0.1:8000/v1/projects/c19c8f87-4ad6-4f40-80e1-4d6f35b692d6/dynamips/devices/d4e42221-ed62-4ef0-8803-8ab3073f4eb7/ports/3/nio - server replied: Not Found
2015-08-12 21:32:00 ERROR device.py:134 Error while deleting NIO SW1: Device ID d4e42221-ed62-4ef0-8803-8ab3073f4eb7 doesn't exist
```

**Comment by noplay** [comment]
Hey @AJNOURI how did you install dynamips? Which version of dynamips do you have?

**Comment by AJNOURI** [comment]
Hi @noplay,
Then, I had:

> dynamips
Cisco Router Simulation Platform (version 0.2.14-dev-amd64/Linux stable)
    Copyright (c) 2005-2011 Christophe Fillot.
    Build date: Aug  4 2014 15:26:53

Disappered with 1.3.11 and I am not experiencing such issue with 1.4.0rc1
