### ISSUE TITLE
Upload local image

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#818]
There is a bug with image upload when present locally but not on the remote server.

![image_upload_bug](https://cloud.githubusercontent.com/assets/4752614/11109707/9deb0fa6-88b0-11e5-8dbd-763fd64200c4.png)

After clicking yes nothing happens and no IOS image is present on the remote server.

**Comment by grossmj** [comment]
This prevent the possibility to use a .gns3a with the GNS3 VM.

**Comment by grossmj** [comment]
Possibly this is related too: https://community.gns3.com/message/50919#50919

**Comment by noplay** [comment]
The problem describe by users is solve. It was invalid path.

But it seem to have been broke since I fixed the issue :(

**Comment by noplay** [comment]
Ok it was the message box that was broken
