### ISSUE TITLE
Selecting multiple IOS images in dialog and allowing GNS3 to uncompress them leaves only one file existent

### ISSUE THREAD

**Issue by hexafraction** [GNS3/gns3-gui#82]
Begin with a directory with a collection of compressed and uncompressed IOS images, and select them all (possibly inadvertently). When prompted to decompress an image, choose to decompress it. All other selected images are deleted from the directory, while it should either skip or uncompress other images in the directory.

**Comment by noplay** [comment]
Ok we need to find a way to ask the file picker to not allow multiple select

**Comment by noplay** [comment]
Tested and in current version you can select only one file.
