### ISSUE TITLE
Remote packet capture is slow

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#820]
Captured packets appear in Wireshark between 5 to 10 seconds after pinging between 2 IOU routers.

**Comment by noplay** [comment]
Tested with a VPCS and an IOU on MacOS and it's instant.

Perhaps is related to your old Qt version.

**Comment by noplay** [comment]
Same with wireshark 2.0 on OSX

**Comment by grossmj** [comment]
Hum... must be something on my side.
