### ISSUE TITLE
Save-As with GNS VM does not copy device configs to the new project

### ISSUE THREAD

**Issue by FarFromSane** [GNS3/gns3-gui#831]
See thread https://community.gns3.com/message/51346#51346 
Basically ..
File-save-as duplicates the topology but the routers all come up with a null config. 
Workaround is to export all configs to directory before the save and then import to the new.

I also used to have to restart the VM because all the tcp/udp ports used by the project were still in use.
This seems to be fixed now

**Comment by FarFromSane** [comment]
Windows 7 with Virtual Box

**Comment by noplay** [comment]
Which emulator are you using? Dynamips, Qemu? 

We will investiguate the port issue also.

Thanks for the report

**Comment by noplay** [comment]
@grossmj save as doesn't really support remote server :( We just recreate stuff via the api

* dynamips we need to copy the data from a place to another
* qemu we need to copy the data and modify the qcow2
* virtualbox & vmware linked clone are not duplicate
* vpcs it's work because it's only configuration

**Comment by noplay** [comment]
By the way except for dynamips I think the feature is not really working for vbox, vmware and qemu on local computer

**Comment by FarFromSane** [comment]
sorry for the delay
- Using iosu on Virtual Box 
- Workaround is to export all configs to directory,  save-as to new project,  exit gns,   restart gns and open the previously 'saved as' project,  then re-import the configs.

**Comment by grossmj** [comment]
@noplay unfortunately I think we should have the save-as work on remote servers in 1.4, this is a major feature and we will get many complaints if this isn't implemented correctly.

**Comment by noplay** [comment]
We can add a save as endpoint in the server the risk is low. The problem is
to reflect the change to the topology file with the new vm ids.

**Comment by noplay** [comment]
We have added a warning for this release. Implementing the feature is too big and too dangerous to change during the release candidate process.

**Comment by grossmj** [comment]
This will probably be solved by https://github.com/GNS3/gns3-gui/issues/995

**Comment by noplay** [comment]
Yes it's duplicate

**Comment by Karlheinzniebuhr** [comment]
Having the same issue, using built-in GNS3 VM on Windows 10.
