### ISSUE TITLE
Add support for Royal TSX (Mac version of Royal TS).

### ISSUE THREAD

**Issue by latebeat** [GNS3/gns3-gui#832]
Hey guys,

Thank you so much for adding support for Royal TS!! Could you add support for Royal TSX for the mac version of GNS3 too? They have a Royal TS version for mac, called TSX that uses the same URI. 

Thank you

**Comment by noplay** [comment]
Can you test this build:
http://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2015-11-30/GNS3-unstable.2015-11-30.dmg/download

I can't test because the demo licence doesn't allow the usage of the apple script.

**Comment by noplay** [comment]
I think the correct way to start RoyalTSX from GNS3 is to use an apple script. 

I found this list of Apple Scripts:
https://github.com/lemonmojo/RoyalTSX_Public/tree/master/Toolbox/AppleScript

**Comment by latebeat** [comment]
I don't have my mac right now but I will test tonight and let you know.
Royal TSX v1 is deprecated though. The repository for v2 is
https://github.com/lemonmojo/RoyalTSX_V2_Public
I've also CCed the support guys from Royal. Perhaps they can shed some
light as to what the correct way is to launch the application

Thanks again!

**Comment by lemonmojo** [comment]
@noplay @latebeat There are multiple ways to launch an connection from outside of Royal TSX.
AppleScript is one way to do it. Another possible way is to use our URI scheme. For information on this please see the following KB article: http://support.royalapplications.com/knowledgebase/articles/536080
While the AppleScript interface is only available for registered copies, the URI scheme also works in Shareware-Mode.

**Comment by noplay** [comment]
Thanks a lot it's work nice

**Comment by lemonmojo** [comment]
@noplay You're welcome! Note however that everything after rtsx:// should be URL encoded like in the example we provide in the KB article (rtsx://web%3A%2F%2Froyalapplications.com).

**Comment by noplay** [comment]
From command line it seem we must not url encode when using the Apple open
command.

**Comment by lemonmojo** [comment]
@noplay Yeah, this will most likely work in almost all situations but to be on the safe side I recommend encoding nonetheless. You have been warned! ;)

**Comment by noplay** [comment]
Ok to be safe i add the url encoding I prefer to avoid problem with futur
apple OSX release :P

**Comment by latebeat** [comment]
Thank you guys!

**Comment by noplay** [comment]
A build should be available in the coming minutes
