### ISSUE TITLE
Console type vnc doesn't work on local (linux) server

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#839]
GNS3 version 1.4.0rc1 (latest unstable commit) on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

When I create a qemu template with console type vnc (e.g. by adding a gns3 appliance with console type vnc) and then move that template into a project, I can start and use that qemu VM. But after saving and reloading I get the error

``` Server error from http://192.168.1.11:8000: TinyCore-1: TCP port 5900 is outside the range 2001-5000```

When I try to change the port range of the local server in the GUI to 2001 - 7000 I get
![port_range](https://cloud.githubusercontent.com/assets/896406/11504041/ad4d342c-9843-11e5-8109-aae939c9e906.png)

When I manually change the console_end_port_range in gns3_server.conf to 7000 it's got overwritten by the GUI.

**Comment by noplay** [comment]
A related issue:
https://github.com/GNS3/gns3-server/issues/364#issuecomment-161012790

**Comment by keshara** [comment]
I think as a work around make console port range to 2001-4000(on Preference tab) which allows vnc to work with port range 5900-6000.

**Comment by ehlers** [comment]
@keshara: That doesn't help. When I use the console type vnc the port 5900 is chosen, no matter what the console port range is. When I now want to use this device, GNS3 complains, that port 5900 is outside the console port range (2001-5000, or your suggestion 2001-4000). And I can't fix this error by extending the port range, because this collides with the reserved vnc port range.

The only workaround I have found is to manually edit the gns3 file and change the console port to 2900. That of course requires a vnc client, that can use this port.

**Comment by noplay** [comment]
Stupid VNC protocol.... Why hard code a port WHY !

**Comment by ehlers** [comment]
The port 5900 is not hard coded, it's just the default. The problem is qemu, that wants to use port 5900+display and doesn't accept a negative display. But it has the same effect, port 5900 - 6000 should be reserved to vnc.

**Comment by noplay** [comment]
Not just qemu some VNC client take only a display as parameter. And a negative display is not really standard.

**Comment by grossmj** [comment]
Qemu used to accept negative displays until version 2.something... grrr :(

**Comment by grossmj** [comment]
Fixed with PR #852
