### ISSUE TITLE
[VMWare] Unable to create NIO Ethernet for bridge ethernet0.vnet

### ISSUE THREAD

**Issue by AODtorusan** [GNS3/gns3-gui#840]
Using the latest GNS3 1.4.0 RC1, I linked up an C3745 and a vmware machine loaded with IOS XRv 5.3.0. However when attempting the start the VM, I get the following exception;

```
GNS3 management console.
Running GNS3 version 1.4.0rc1 on Windows (64-bit) with Python 3.4.3 Qt 5.5.1.
Copyright (c) 2006-2015 GNS3 Technologies.

=> Server error from http://127.0.0.1:8000: iosxrv-k9-demo-5.3.0: unable to create NIO Ethernet for bridge 'ethernet0.vnet'
```
It doesn't matter if the C3745 is started before starting the XRv image. 

I am using GNS3 1.4.0 RC1 & VMWare workstation 11 in Windows 10 x64.

**Comment by grossmj** [comment]
Hum, looks like a right issue. Make sure you have installed Winpcap and do the following:

Start cmd.exe as an administrator.
Type ```sc config npf start= auto```
Reboot your computer.
Try again.

Thanks,

**Comment by AODtorusan** [comment]
That fixed it.

Come to think of if, I don't remember if I rebooted after installing winpcap. Perhaps the service is only first started after a reboot.

**Comment by noplay** [comment]
Thanks for the feedback

**Comment by tam1984** [comment]
I also came across this issue when linking a winxp image and l2iou switch.

Jeremy's fix resolved my issue - thanks.

Is this a possible bug?

**Comment by lshouse** [comment]
Jeremy,

Do you have a solution to this for Linux?

**Comment by noplay** [comment]
@ishouse I think it's a permissions issue.  Are you running GNS3 under the same user as VMware?

**Comment by grossmj** [comment]
On Linux, make sure the ubridge command has the right capabilities: 

```
$ which ubridge
/usr/local/bin/ubridge
$ getcap /usr/local/bin/ubridge
/usr/local/bin/ubridge = cap_net_admin,cap_net_raw+ep
```

If the right capabilities aren't set then type the following:
```
sudo setcap cap_net_admin,cap_net_raw=ep /usr/local/bin/ubridge
```

**Comment by artyomkaes** [comment]
grossmj, 
thx for advice! 
Executed command **"sc config npf start= auto"** helped to resolve the error message "unable to create NIO Ethernet for bridge 'ethernet0.vnet"

**Comment by grossmj** [comment]
Thanks for the feedback :+1:

**Comment by Balshore** [comment]
Thanks groosmj, I also had the same issue when creating my VM for PA. Thanks!
