### ISSUE TITLE
Tabbed terminal for OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#841]
From: https://community.gns3.com/thread/22921

osascript -e 'tell application "Terminal"' -e 'activate' -e 'tell application "System Events" to tell process "Terminal" to keystroke "t" using command down' -e 'if (the (count of the window) = 0) or (the busy of window 1 = true) then' -e 'tell application "System Events" to keystroke "n" using command down' -e 'end if' -e 'repeat while contents of selected tab of window 1 starts with linefeed' -e 'delay 0.01' -e 'end repeat' -e 'do script "echo -n -e \"\\033]0;%d\\007\" ; telnet %h %p ; exit" in window 1' -e 'end tell'

**Comment by grossmj** [comment]
Does that work?

**Comment by noplay** [comment]
I will test

**Comment by noplay** [comment]
Work with race conditions when you open all console at the same time. I think iTerm as the same issue.

**Comment by noplay** [comment]
Race condition with apple script is fixed by adding a lock.
