### ISSUE TITLE
QEMU Linked VM used in projects writed in v3.11 doesn't work well on v4.05b

### ISSUE THREAD

**Issue by jprietove** [GNS3/gns3-gui#843]
I have updated from v3.11 to v4.05b.
I try to open GNS3 v3.11 projects with several QEMU VM created with option 'linked VM'.
When starting the project on v4.05b, GNS3 starts base VM instead of hda_disk.qcow2
I've found a workaround: open project and save without starting it. Open file with .gns3 extension with a text editor and find & replace << "linked_clone": false >> with << "linked_clone": true >>
This attribute "linked_clone" didn't appear on my GNS3 v.11 projects but it does on v.4.05b

**Comment by noplay** [comment]
Thanks for the report

**Comment by noplay** [comment]
It should be fixed in 1.4.0rc1. Can you confirm?

**Comment by jprietove** [comment]
Perfect! I have installed 1.4.0rc1, opened a file writed in version 1.3.11 and now it works OK.
Thank you very much!
