### ISSUE TITLE
The preferences windows is too big for small resolutions

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#844]
https://community.gns3.com/thread/23307

```
Hi,
 
I'm using GNS3 1.4.0rc1 on my Lappy (mobile Core i7 4600U + 16 Gigs of RAM). Windows 7 + local server.
Problem is: some GUI buttons are out-of-reach.
GUI needs elements re-arrangement.
 
NOTE: This works fine with my old build - GNS3 v0.8.1 VirtualBox Edition   from 2011 !
Screenshots attached.
 
-Technologov
```

![image](https://cloud.githubusercontent.com/assets/345437/11525182/5838bbc6-98d1-11e5-801c-e8a5fe560c59.png)

![image](https://cloud.githubusercontent.com/assets/345437/11525186/5e77e0de-98d1-11e5-8438-e942ca3a9114.png)

**Comment by noplay** [comment]
The resolution is : 1366x768

**Comment by Technologov** [comment]
Do you have a BETA build for Windows ? So I can verify this bug.

**Comment by cioby23** [comment]
Here you can find the latest nightly builds http://sourceforge.net/projects/gns-3/files/Nightly%20Builds/

**Comment by noplay** [comment]
Wow @cioby23 thanks for sharing it :)  I just took my  tea and the question is already answered.

**Comment by noplay** [comment]
You just need to wait a few minutes a build for the 3 december should be available this build will include the fix.
