### ISSUE TITLE
Dynamips on Windows (without Cygwin) ---  Needs Evaluation

### ISSUE THREAD

**Issue by Technologov** [GNS3/gns3-gui#845]
Dynamips-mingw, by Neozeed (no cygwin required!)
 
http://sourceforge.net/projects/dynamips-mingw/

**Comment by noplay** [comment]
Perhaps this could solve some issues. Or create new :P

**Comment by grossmj** [comment]
Looks very interesting...

**Comment by grossmj** [comment]
Maybe that would resolve this UTF-8 path issues? See https://github.com/GNS3/gns3-gui/issues/638

**Comment by grossmj** [comment]
Moved to https://github.com/GNS3/dynamips/issues/69

**Comment by arash88** [comment]
Hi devs,
Any news regarding using this solution instead of current cygwin dependent version for windows?
Thanks guys.
