### ISSUE TITLE
Issues Ping from ASA8.4 on local to IOU on VM

### ISSUE THREAD

**Issue by adecisco** [GNS3/gns3-gui#853]
Dear Team,

I have extensively look at this issues but I think gns3 should look at it and see how it can be resolve in the next rc.

I have observed that setting up ASA 8.4 on VM only hang at:
NET: Registered protocol family 1
Unpacking initramfs...

The only solution that work has to be deployed on the local machine and this load without issues.

But other issues that came up as a result of this is that ASA cannot communicate with IOU. My guess was since they both reside in different ip address address. IOU is inside VM while ASA is deployed on the local machine. Layer two communication was not successful as the mac address of the ASA link connected to IOU SW was not successful.

I believe this is a bug which will require the team to look at and see how they can solve this issues as soon as the next release.

Thanks for the good job.

Regards,

**Comment by noplay** [comment]
Hi,

We need more informations about your environnement.

* With which version of GNS3?
* Which emulator are you using for running ASA?
* Which OS are you using for running your local server?

**Comment by adecisco** [comment]
Hello Julie,

1. With which version of GNS3? ==> 1.4.0rc1
2. Which emulator are you using for running ASA? ===> QEMU
3. Which OS are you using for running your local server? ====> Win 8.1

Thanks

**Comment by noplay** [comment]
And you are running asa on the GNS3 VM or on the Windows?

**Comment by noplay** [comment]
If it's on Windows which version of Qemu is used?

**Comment by adecisco** [comment]
I am running on window not GNS3 VM with QEMU version 

![image](https://cloud.githubusercontent.com/assets/11568562/11557923/ce4d4820-99af-11e5-9995-8b85acfc00db.png)

When I was using GNS3 VM I had this experience

![asa issues](https://cloud.githubusercontent.com/assets/11568562/11557904/ab90b1e6-99af-11e5-9337-da2ab469d477.png)

But after this I decided to run on window rather than GNS3 VM. I load fine but connectivity starting from LAYER 2 connectivity become a new issues.

Regards,

**Comment by noplay** [comment]
We show a warning when using ASA 8 now. We have no way to make the support reliable because issues are in the kernel from CISCO. And since CISCO as an official solution with ASAv we can promote this solution.

We have look on all solution and hours of R&D and not found something working for everyone.
