### ISSUE TITLE
Buttons "OK"and "Cancel" in preferences have no action

### ISSUE THREAD

**Issue by Technologov** [GNS3/gns3-gui#856]
Host: Win 7 + GNS3 1.4.0-nightly-unstable-03.Dec.2015.

I go to Preferences->General (or any tab)->click "OK" or "Cancel" and no reaction whatsover.
GUI dialog window does not close, until I click on "X" at right-top corner to close the window.

**Comment by noplay** [comment]
Duplicate of #855

It should be fixed in today build

**Comment by noplay** [comment]
Thanks for the report
