### ISSUE TITLE
Move the topology with add CTRL + mouse LEFT button

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#859]
It would be great to add the functionality of Move the topology with **add CTRL + mouse LEFT button**
It is more comfortable and more precise than the vert/horz sliding bars

![Move topology](http://hpnouri.free.fr/misc/GNS3-CTRL-MOUSE-LEFT-BUTTON-MOVE1.gif)

**Comment by noplay** [comment]
Wheel click already do that (on mac OS)

**Comment by grossmj** [comment]
I guess we could allow CTRL + mouse LEFT button or something close to this.

**Comment by noplay** [comment]
SHIFT + Left click work for me on Mac.

**Comment by noplay** [comment]
Same on Linux. I propose to close the issue.

**Comment by grossmj** [comment]
Love it when it is already supported ;)
