### ISSUE TITLE
[BUG] Telnet ports (2001+) for devices are not cleared after reopening GNS3

### ISSUE THREAD

**Issue by Sourg** [GNS3/gns3-gui#860]
1.4.0rc1 on OS X El Capitan
If you open the project and you don't use "Stop devices" (even if devices were not started), then you quit GNS3 (like with CMD+Q) and you open GNS3 + one of your existing projects, GNS3 will complain that:

    Server error from http://<server>:8000: R8: TCP port 2008 already in use on host
    Server error from http://<server>:8000: R7: TCP port 2007 already in use on host
    Server error from http://<server>:8000: R6: TCP port 2006 already in use on host
    Server error from http://<server>:8000: R5: TCP port 2005 already in use on host
    Server error from http://<server>:8000: R9: TCP port 2009 already in use on host
    Server error from http://<server>:8000: R10: TCP port 2010 already in use on host
    Server error from http://<server>:8000: R1: TCP port 2001 already in use on host
    Server error from http://<server>:8000: R2: TCP port 2002 already in use on host
    Server error from http://<server>:8000: R3: TCP port 2003 already in use on host
    Server error from http://<server>:8000: R4: TCP port 2004 already in use on host

Possible solution: 
* when the project is opened, server should close all opened ports and then load topology or 
* to have a dialog window where the user should be asked if we want to close opened ports or to automatically reassign ports from currently opened project (if there will be multi-user support in the future)

**Comment by noplay** [comment]
The PR https://github.com/GNS3/gns3-server/pull/370 should solve this kind of issue (your solution 2)

**Comment by grossmj** [comment]
Resolved by https://github.com/GNS3/gns3-server/pull/374
