### ISSUE TITLE
[BUG] OK and Cancel buttons in GNS3 Preferences don't work

### ISSUE THREAD

**Issue by Sourg** [GNS3/gns3-gui#861]
Observed on last unstable release on OS X El Capitan.
Problem: If you change GNS3 preferences and click either on Ok or Cancel - they do nothing (Settings are not applied, window is not closed).
Unfortunately, I don't remember if there was the same issue on 1.4.0rc1, because I don't change Preferences often.

**Comment by noplay** [comment]
I think you test with the version build the 3 december. 

It's fixed in the build of the 4 december
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2015-12-04/

Duplicate #856, #855
