### ISSUE TITLE
Launching 2 instances of the GUI, the 2nd crashes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#865]
If I start the GUI and then launch another instance of the GUI, the second instance tries to connect to the local server but if I click on cancel the GUI crashes.

**Comment by noplay** [comment]
I don't have the crash. But I see this warning when I click on Cancel:
QThread: Destroyed while thread is still running

I think we have introduce a problem.  We have prevent the GUI to connect to a zombie server by killing the server if the server is already running. But when you launch two gui the second will kill the server started by the first gui ....

**Comment by noplay** [comment]
I think I fix the crash

**Comment by grossmj** [comment]
Tested and it works now.
