### ISSUE TITLE
Cloud Device templates for regular use often with custom image.

### ISSUE THREAD

**Issue by nar4all** [GNS3/gns3-gui#867]
Hi Jermy,

Please consider below  Enhancement request.

I use ESxi as GNS server 1.4 RC1 and add the devices through cloud. For example I have devices like ASA, PaloAlto, fortinet and some live devices with USB Ethernet connected. Every time i connect through cloud need to add the interfaces accordingly and also configure custom image.

Can we add the feature which i illustrated as a sample in forum. I know this will be very easy for you to create which will be very useful for people using third party device using ESXI or live, it will really look like we have integrated third party devices inside the GNS3.

which will look like (illustrated as in forum with image) and we can use as we need and also include VNC, telnet,SSH, RDP, http and https with the IP option. So in case that device we like to access, we can http/SSH take it remotely to configure that device.

Thanks in advance
Narendra

**Comment by grossmj** [comment]
Hi,

What is the link in the forum?

**Comment by nar4all** [comment]
Please find the link below.

https://community.gns3.com/thread/23391



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=5.0.2&source=email_footer_2] On Thu, Dec 10, 2015 at 9:04 am, Jeremy Grossmann < notifications@github.com [notifications@github.com] > wrote:
Hi,

What is the link in the forum?

—
Reply to this email directly or view it on GitHub
[https://github.com/GNS3/gns3-gui/issues/867#issuecomment-163476999] .[https://github.com/notifications/beacon/APeT8k_fdJCGgJ5-qvzEs4N1dfYMsgJfks5pOOosgaJpZM4GyKYq.gif]

**Comment by noplay** [comment]
![image](https://cloud.githubusercontent.com/assets/345437/11709547/cecf33da-9f18-11e5-9312-a0d8aba6cbe4.png)

**Comment by noplay** [comment]
![image](https://cloud.githubusercontent.com/assets/345437/11709555/dcc03e30-9f18-11e5-9345-d64ff3986cdf.png)

**Comment by nar4all** [comment]
Is this will be added in next release

**Comment by noplay** [comment]
It will not be in 1.4 which is feature freeze since the first RC (early december). And we have not decided what will be shipped in the 1.5.

**Comment by nar4all** [comment]
Could you please prioritize this enhancement in 14.1 or 14.2, as it is very useful and also i know this is  very easy to add this option in GNS3. 
Requesting you

**Comment by noplay** [comment]
Reflexion in progress about the cloud:
https://github.com/GNS3/gns3-server/issues/402

**Comment by noplay** [comment]
With reflexion it sound a good idea. We need to make like the other node types. It's a good opportunity to rethink how a user create a cloud.

**Comment by nar4all** [comment]
This is again pushed to 2.0 release, Could you please try to enhance it in upcoming version. As it makes life simpler.
Am just asking for a cloud template which can be stored as of now, Advanced stuffs can be adding in later stages. 
As i have about 25+ live devices which are connected to Switch and connected to ESXI server running GNS3 1.4.5
Each device as about 4 ports which will be using, It is very default to add a cloud and search for the interfaces accordingly.

**Comment by noplay** [comment]
We need to rewrite the cloud before adding this. Because actually the cloud is just graphical stuff in the topology and doesn't exists in other area of the application.

Add this feature now require a lot of code and this code will be drop after when the 2.0 will be available, also this require to write migration code for 2.0.

Also actually we have a lot of people complaints that the cloud is too complex for them. We search a way to simplify it breaking usages:
https://github.com/GNS3/gns3-gui/issues/1116

**Comment by nar4all** [comment]
I have just attached a demo with 2 devices which are connected to GNS3 which I use it, But i have about 25+ devices connected similarly.

![gns3demo](https://cloud.githubusercontent.com/assets/16225266/14894721/ac1df482-0d92-11e6-8971-b64599bd6446.jpg)

I have justed added VLAN's on GNS3 Server, as u can see below screenshot, each vlan is connected to one live device interface, 
which all works great,
only think which am facing is using that cloud everytime, I need to use the appropriate VLAN interface so it connects to right live device interface.

thats the reason, I want to configure it and store with the device image and interfaces. So i can use for any topology without even seeing and selecting the interface every time.

![labdemo1](https://cloud.githubusercontent.com/assets/16225266/14894985/095a02d4-0d94-11e6-9044-1a8808754fa7.jpg)

In the below topology the live device is have interface X0, X2, which is a cloud with interface eth1:101, eth1:102
![labdemo2](https://cloud.githubusercontent.com/assets/16225266/14895078/75b022b0-0d94-11e6-9bc4-e2c854146682.jpg)

Eg2: In the below topology with different GNS3 server X2, which is a cloud with interface eth1:200

![labdemo3](https://cloud.githubusercontent.com/assets/16225266/14895109/9903d842-0d94-11e6-96b1-effbd045e6f7.jpg)

I have another GNS3 server with interface: eth1:100, 101, ......,,.. till 200, with about 100+ interface, each interface is connected to live device, choosing the right device with right interface for configuring which is making crazy.
I think with this info you are able to understand how am using the live device in GNS3.

**Comment by grossmj** [comment]
I've implemented it. However, at the moment I am not sure configuring the network interfaces in the template is the best thing to do. Therefore, the only settings that can be changed in the template are the name, default_name_format, symbol and category, this should be enough for most customizations.

**Comment by nar4all** [comment]
Major concern is selecting the interfaces on each cloud, hence please try to add configuring network interfaces in the template
