### ISSUE TITLE
Relative Paths to Images Saved in .gns3 File Causes -3200 Error

### ISSUE THREAD

**Issue by JaredF** [GNS3/gns3-gui#87]
Possibly the same issue as mentioned in http://forum.gns3.net/topic10962.html and http://forum.gns3.net/topic10418.html

The relative path to the image file is saved in the .gns3 file which causes a '-3200' (could not be found on this server) error when the project is reopened with the server located on a remote machine.

If the gns3 file is manually edited and the absolute path entered for the image file, the project opens successfully.

**Comment by networkpadawan** [comment]
can confirm that it still happens on 1.2.3

**Comment by grossmj** [comment]
This should have been fixed in GNS3 1.3 beta 1. Please re-open if not.

Thanks,
