### ISSUE TITLE
IOU: Could not read configuration file startup-config.cfg

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#870]
GNS3 version 1.4.0dev12 on Darwin (64-bit) with Python 3.5.0 Qt 5.5.1.

Created a new project with just one IOU router, here it's configuration:
![bildschirmfoto 2015-12-10 um 08 49 03](https://cloud.githubusercontent.com/assets/896406/11709820/ef19c608-9f1a-11e5-8884-b39811a85f96.png)

Running the IOU router works fine, on exit ("wr" on IOU, then save the topology) the config is saved on the remote server:
```
gns3@gns3-iouvm:~$ ls -l /opt/gns3/projects/558a6cc0-66eb-49bd-b556-8a48d57ef333
/project-files/iou/ba65da04-6be8-4722-b78b-6afed03f5567/
total 137
-rw-rw----    1 gns3     staff         1136 Dec 10 07:43 NETMAP
-rw-rw----    1 gns3     staff         2048 Dec 10 07:43 iou.log
-rw-rw----    1 gns3     staff           45 Dec 10 07:43 iouyap.ini
-rw-rw----    1 gns3     staff          377 Dec 10 07:45 iouyap.log
-rw-rw----    1 gns3     staff       131072 Dec 10 07:44 nvram_00001
-rw-rw----    1 gns3     staff            7 Dec 10 07:45 private-config.cfg
-rw-rw----    1 gns3     staff         1751 Dec 10 07:45 startup-config.cfg
```

When I now exit GNS3, then restart and load the project, I get the error:

Error: IOU1: Could not read configuration file /Users/behlers/GNS3/configs/startup-config.cfg: [Errno 2] No such file or directory: '/Users/behlers/GNS3/configs/startup-config.cfg'

The same happens with IOU projects, that were previous created.

Here my .gns3 file: [test.gns3.txt](https://github.com/GNS3/gns3-gui/files/57750/test.gns3.txt)

**Comment by ehlers** [comment]
Reverted back to https://github.com/GNS3/gns3-gui/commit/b1b861c99d1ba3e4822d655a6b93c0ccc6f8e24c, then all is fine, so https://github.com/GNS3/gns3-gui/commit/4fe55634ae96c883acb971b46ba7f3073fb904ae seems to introduce the issue.

**Comment by noplay** [comment]
/Users/behlers/GNS3/configs/startup-config.cfg exists?

**Comment by noplay** [comment]
Oh no I understand what happen ... It was working previously but by a side effect ....

**Comment by ehlers** [comment]
The startup-config.cfg doesn't exist on my GUI PC (/Users/behlers/GNS3/configs/ is on my GUI machine). It exists on the remote server, but in a totally different directory (/opt/gns3/projects/558a6cc0-66eb-49bd-b556-8a48d57ef333
/project-files/iou/ba65da04-6be8-4722-b78b-6afed03f5567)

**Comment by noplay** [comment]
We initially send a startup config from your computer to the server. The server rename it and send back the new name to the client. The client receive it  and next time will try to send again the file but will not found the file and we raise an error and previously we were ignoring this error... 

I need to think how to fix that.

**Comment by noplay** [comment]
I patched it to keep the old behavior
