### ISSUE TITLE
The router with "NM-16ESW" but without check "This is a EtherSwitch" seems wrong automatically delvery name

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#876]
Lubuntu 15.10 
GNS3 1.4.0 RC2
gns3server autostart
and local client connect with local server via "remote server"

Once add a router templete without check the "This is a EtherSwitch"
At this moment when I if add NM-16ESW to it
Drag this kind of router into topology, the name becomeing "ESW1 ESW2..."
I think this should be "R1 R2..." because "This is a EtherSwitch" did not check.
If the developers think this logic is correct so please forget it.

**Comment by superwolfboy** [comment]
IDS has the similar problem, the hda can not keep the currect setting , it always keep the first shown image, but hdb can be save currect. 
So I change to use "Default" to add the IDS, but only can add one hda in guide, when finished the cuide I try to add hdb in configuration, then this hdb is local , not on remote which what I want.
![Uploading QQ图片20151211224429.png…]()

**Comment by noplay** [comment]
Hi, can you open a separate issue for the first problem? It will be easier to follow.

Thanks for the help

**Comment by superwolfboy** [comment]
OK, I will change .

**Comment by noplay** [comment]
Thanks !

**Comment by grossmj** [comment]
We do not keep the info that an IOS router is an Etherswitch node. Therefore the base name is ESW when slot 1 contains a NM-16ESW network module.

This could be resolved if we let users configure the base name they would like but this is for a future version of GNS3.
