### ISSUE TITLE
rc2 mac crashing on open

### ISSUE THREAD

**Issue by vader75** [GNS3/gns3-gui#878]
I have downloaded rc2 on OSX 10.11.2 and it crashes on opening:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8f0fc002 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff962335c5 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9c55b6e7 abort + 129
3   Python                        	0x0000000107e7c1e3 Py_FatalError + 420
4   GNS3                          	0x0000000107da9983 main + 3171
5   libdyld.dylib                 	0x00007fff9dcb35ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff57e57648  rdx: 0x0000000000000000
  rdi: 0x000000000000160b  rsi: 0x0000000000000006  rbp: 0x00007fff57e57670  rsp: 0x00007fff57e57648
   r8: 0x00000000000000a9   r9: 0x000000000000008c  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff7cd6bbd0  r13: 0x00007fff57e57cc0  r14: 0x00007fff7be15000  r15: 0x00000001083d9a48
  rip: 0x00007fff8f0fc002  rfl: 0x0000000000000206  cr2: 0x00007fff7cd69008

**Comment by vader75** [comment]
More details:

$ /Applications/GNS3.app/Contents/MacOS/gns3 ; exit;
Application frozen with cx_Freeze
The SSL certificate bundle file '/Applications/GNS3.app/Contents/MacOS/cacert.pem' could not be found
GNS3 GUI version 1.4.0rc2
Copyright (c) 2007-2015 GNS3 Technologies Inc.
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Reinstalling the application may fix this problem.
Fatal Python error: Aborted

Current thread 0x00007fff7be15000 (most recent call first):
  File "./gns3-gui/gns3/application.py", line 32 in __init__
  File "gns3-gui/gns3/main.py", line 232 in main
  File "gns3-gui/gns3/main.py", line 277 in <module>
  File "/Users/gns3/Jenkins/workspace/Release MacOSX/OSX/../boot.py", line 46 in <module>
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...12 completed.

**Comment by alsubhi** [comment]
Same here.

**Comment by gkl1368** [comment]
I have the same problem

**Comment by noplay** [comment]
Could you try again after redownloading the binary?

Thanks for the help

**Comment by alsubhi** [comment]
Yep, it's working now

Thank you.

**Comment by noplay** [comment]
Great it was a bug with last cx freeze versions thanks for the feedback

**Comment by vader75** [comment]
Confirmed working! Thanks.
