### ISSUE TITLE
 Cannot save my topology getting an error message

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#885]
Hello,

       When I try to save a simple topology I am getting an error message I have posted the error message below. If use either save or save as I still get the same error message. I am using the GNS3 VM for the ESXi platform. I believe it could be an in issue with the GNS3 client version 1.4.0rc2 because on another machine I have GNS3 client version 1.4.0rc1 and I do not have this issue at all. Thank you

![capture](https://cloud.githubusercontent.com/assets/16152626/11822519/e8acc754-a33c-11e5-88db-c9ad8846e50b.PNG)

**Comment by noplay** [comment]
The problem is with temporary project, we can't save as a temporary project on a remote host. You need to put a project name when you start a project.

**Comment by noplay** [comment]
By the way I don't know if we have way to allow this particular case whiteout touching too much code. 

An alternative could be to ask confirmation from the user when he use a temporary project. Something like:
"Are you sure to skip the creating project step? We will open you a temporary playground. This playground can't be save if you use a remote server or the GNS3 VM."

**Comment by Vic563** [comment]
Why is it that this works in version 1.4.0rc1 but not in version 1.4.0rc2?

**Comment by noplay** [comment]
All cases are not working in RC1 :(

But I agree that temporary project create less problem and we can probably
manage it without too much trouble for the next RC. We just forgot about
them during our tests.

**Comment by Vic563** [comment]
Okay thank you.

**Comment by noplay** [comment]
Ok I found an easy fix for temporary project

**Comment by Vic563** [comment]
Okay great maybe it can be implemented in the next release. Thank you

**Comment by noplay** [comment]
It will be in RC3 ;)
