### ISSUE TITLE
When using ASA wizard the hda disk is not correctly save

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#886]
When you follow the ASA wizard the hda disk is always the first dis instead of the disk choose:
![image](https://cloud.githubusercontent.com/assets/345437/12330293/a6f2b89a-bae4-11e5-9c8e-5849699d34fb.png)

# Original report
Once add ASA842 templete via remote server,the first step is choosing the hda, then choose the initrd and vmlinuz, but when finish I found the setting of hda didn't save, when I run this asa842 , there is no hda mount on it , when I add the hda on asa(change the templete or asa in topology),it would be a local one , not a hda on remote server which I want. so at this moment I start the asa842 and got the error message: "Running server is not a GNS3 local server (not started with --local)"
I think there are two problems. 1,Once add ASA842 templet, the step of choosing the hda should be kept setting. 2,if one device is on remote server , when change setting and cleck "browse" botton(both on templet and topology), it sould list the image on remote server , not local.

IDS has the similar problem, the hda can not keep the correct setting , it always keep the first shown image, but hdb can be save correctly. 
So I change to use "Default" to add the IDS by manually, but only can add one hda on remote server in guide, when finished the guide I try to add hdb in configuration, then this hdb is local, not on remote which what I want.
![6c9cfe1e-a05c-11e5-8b3c-3e2642f494d1](https://cloud.githubusercontent.com/assets/9411604/11843765/47e43374-a446-11e5-99c5-f7560804478d.png)

**Comment by superwolfboy** [comment]
If you have problem or question please do not be hesitated to conntect with me, cause I want to built one vm based on Lununtu which can supply GNS3 server to client in LAN, also can be used as single vm at the same time.
But when start the gns3server by systemd on Lubuntu, the GNS3-GUI running on same Lubuntu cannot use the virtual equipment which added by local, so we need to add the virtual device remotly though the gui woking local machine. at this moment , I cannot add all the virtual device cause this bug.

**Comment by noplay** [comment]
You need to use the server as a remote server on all GUI including the local if you want to share it on network. Using a server as local and remote is not a scenario supported. The major reason is the directory layout is very strict when using a remote server for security reasons.

In your case I see the ASA images are not at the root of the remote images directory. Remote server doesn't support sub directories. When images are uploaded via GNS3 they are all in ~/GNS3/images/QEMU

**Comment by superwolfboy** [comment]
Maybe I should use soft link to solve this first cause it is diffcult to manage when the qemu devices are so many in one folder.

**Comment by superwolfboy** [comment]
tested of 1.4.0
and I put the three files of asa8.4(2) directly in ~/GNS3/images/QEMU as the image:
![image](https://cloud.githubusercontent.com/assets/9411604/12294554/52513838-ba36-11e5-9515-3c22f3c6371e.png)
then I add the asa8.4(2) via the guide, when finish,I got this:
![image](https://cloud.githubusercontent.com/assets/9411604/12294566/7e11dc0c-ba36-11e5-9bcc-ec2348bc0c93.png)
the "?"should be “flash.qcow2”, but it not save currectly.
then I try on windows , and I got the same result:
![image](https://cloud.githubusercontent.com/assets/9411604/12294611/d2e640ec-ba36-11e5-965d-85f79c65cc3d.png)
Which means at this stage:
![image](https://cloud.githubusercontent.com/assets/9411604/12294626/e56298ce-ba36-11e5-897c-808f540c6a9a.png)
whatever I selected, GNS3 always keeps the first file.

**Comment by noplay** [comment]
Yeah you can't have image in an ASA folders :(

**Comment by superwolfboy** [comment]
even directly put the file into ~/GNS3/images/QEMU out of ASA also cannot working , really hope this can be solved. Thank you.

**Comment by superwolfboy** [comment]
![qq 20160114210040](https://cloud.githubusercontent.com/assets/9411604/12324982/ea630a9a-bb01-11e5-90ae-4b6747ed69ce.png)

**Comment by noplay** [comment]
Ok I understand the issue sorry to have been long.
