### ISSUE TITLE
Dialog box re-sizing issues

### ISSUE THREAD

**Issue by adecisco** [GNS3/gns3-gui#889]
Current release RC2 does not have re-sizing of dialog box enable. I believe it must have been missed.

Kindly note..

**Comment by noplay** [comment]
Which dialog box do you want to resize?

Thanks

**Comment by adecisco** [comment]
Preference dialog box. I have 3200x1800 screen display so the dialog box is tiny.

**Comment by noplay** [comment]
Could you post a screenshot of the result?

**Comment by adecisco** [comment]
This is re-sizing.

![image](https://cloud.githubusercontent.com/assets/11568562/11865680/e30c8216-a4a5-11e5-8826-015b2b2d226d.png)

This is not no option for re-sizing enable:
![image](https://cloud.githubusercontent.com/assets/11568562/11865713/1491a2ee-a4a6-11e5-8940-2f963cea0e0f.png)

This is how my preference dialog box looks like without re-sizing.

![image](https://cloud.githubusercontent.com/assets/11568562/11865736/495b3fe4-a4a6-11e5-9dd3-bfbb66ec414e.png)

All effort to re-size the preference dialog box fail.

Rg.

**Comment by noplay** [comment]
Could you try this build I think it could fixe the issue
http://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2015-12-17/GNS3-unstable.2015-12-17-all-in-one.exe/download

Thanks

**Comment by adecisco** [comment]
I have another issues..

![image](https://cloud.githubusercontent.com/assets/11568562/11866318/a40a908a-a4aa-11e5-8fb5-d667f9a065c6.png)

Please what is the way out..

Thanks,

**Comment by adecisco** [comment]
Effort to upgrade GNS VM give below:

![image](https://cloud.githubusercontent.com/assets/11568562/11866375/015079d0-a4ab-11e5-998c-cc064247589a.png)

**Comment by noplay** [comment]
In the vm switch to unstable version. It should remove the warning.
