### ISSUE TITLE
Cannot capture traffic between two QEMU devices GNS 1.4.0rc2

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#896]
I am trying to capture traffic between two QEMU devices. I am running GNS3 as Administrator and I am still getting the error message "Packet capture is not supported on this link". The weird thing is if I deploy the Ethernet Node on the GNS3 VM and then select the Ethernet node link it let's me capture traffic. But I always needs to deploy an Ethernet switch node.

**Comment by cioby23** [comment]
This is not implemented yet. There is a request for this here https://github.com/GNS3/gns3-server/issues/350 and hopefully it will be available in the next big release 1.5

**Comment by Vic563** [comment]
Okay sound great. Hopefully it's in the 1.5 release. Thank you
