### ISSUE TITLE
Virtualbox instances connect with iou cannot working fine. 

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#899]
OS：win10 pro 64bit
GUI:Gns3 1.3.13
VM:IOU VM
Once connect two tinycore linux(running on virtualbox) with IOU_L2,
one of them can not Ping through with svi on IOU_L2 and other IP, it looks like this virtualbox pc can not connect with IOU, the other can working fine.
If I use cisco 1700 instead pc(running on dynamips),there is no problem.

**Comment by noplay** [comment]
Which version of VirtualBox ?

The two tinycore linux are separate instance of virtualbox? Or they are running inside the virtualbox VM?

**Comment by superwolfboy** [comment]
Virtualbox version is 5.0.12 r104815
I install one tinycore on Virtualbox , then I added it into GNS3 with "Use as a linked base VM", so when I use two tinycore, it will link out two instances based on the one I installed.
They are running on same level with IOU VM(1.3.13), not running inside another  virtualbox VM(hope my understanding of your question is right)

**Comment by noplay** [comment]
And if you are not using linked clone does it work?

Thanks for the help

**Comment by superwolfboy** [comment]
When I don't use link, it is the same , one tinycore can not working fine.
![bug2](https://cloud.githubusercontent.com/assets/9411604/12050980/c1578fac-af37-11e5-9cb2-0a5be86f73eb.png)

**Comment by superwolfboy** [comment]
I have tested for 1.4.0 about this issue and the result as below:
1,Use one virtualbox device(tinycore linux) connect with one iou, tinycore ping svi failed.
2,as the screenshot, connect these kind of device via one non-manage switch inside of GNS3, the IOU and IOS based on dynamics can ping each other, but virtualbox device cannot ping other virtrualbox, also cannot ping iou and IOS.
![qq 20160115224055](https://cloud.githubusercontent.com/assets/9411604/12356066/89ab63e8-bbdb-11e5-8814-a7d92c6813f5.jpg)
3,as the screenshot,use one router based on dynamios as switch, all the device can ping each other.
![qq 20160115225100](https://cloud.githubusercontent.com/assets/9411604/12356113/ced8dfd6-bbdb-11e5-912c-416d3fdc5cac.png)
thank you .

**Comment by grossmj** [comment]
Can you make screenshots of network section summary in VirtualBox for your TinyCore VMs?

For instance:

![virtualbox_network_section](https://cloud.githubusercontent.com/assets/4752614/12438515/b2053416-bee4-11e5-8ffe-7034cf1b81aa.png)

Thanks,

**Comment by grossmj** [comment]
Also, something to try is to switch back to English in VirtualBox and try again. This may be the source of the problem.

**Comment by grossmj** [comment]
@superwolfboy any success?

**Comment by grossmj** [comment]
@superwolfboy ping

**Comment by grossmj** [comment]
Doesn't seem to be a problem with switching to another language in VirtualBox, I have tested with Japanese and things worked as expected.

The problem seems only be with the default Dynamips Ethernet switch (we have had many other reports that something is wrong with it).

Just in case I've added a verification that UDP tunnel is correctly set in VirtualBox: https://github.com/GNS3/gns3-server/commit/167a0b8435ad0febc16535c4b7861a43366b1f80

**Comment by grossmj** [comment]
Dynamips Ethernet switch code seems good. I don't see what could go wrong.

https://github.com/GNS3/dynamips/blob/1d02e348a67915df215a3439c5dbb26ff4dc0cd6/common/eth_switch.c#L233

**Comment by superwolfboy** [comment]
sorry for this issues I forgot,cause that time I  found a job and now I lost it again , I will try these days for this.
