### ISSUE TITLE
Leftover gns3_gui.pid can confuse check of main GUI

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#900]
GNS3 version 1.4.0rc2 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.

At exit of the main gui the gns3_gui.pid is not deleted. Once I had the situation that after a reboot some other process got the PID of the old GNS3 GUI process, that was recorded in gns3_gui.pid . Therefore a newly started GNS3 GUI thought that it is not the main GUI and didn't autostart the server.

One way to resolve this is to delete the gns3_gui.pid after the exit of the main GUI. Nevertheless there could be situations, where the GUI is not cleanly terminated and after a reboot the old gns3_gui.pid can still confuse the check for the main GUI.

Another possibility is to check not only the existence of a process running with the pid of gns3_gui.pid, but also checking if this process really is the GNS3 GUI by checking the process name.

**Comment by noplay** [comment]
Yeah i think we need to check the process name

**Comment by noplay** [comment]
Do you see other cases?

**Comment by ehlers** [comment]
Other cases, where the pid in gns3_gui.pid gets used by another process ?

In theory it's possible that the pid values wrap around. So another process might get the same pid as a previous GNS3 GUI process that already has terminated. Then the start of the GNS3 GUI would falsely detect this process as a primary GUI. But I think that's extremely unlikely.

My scenario can happen relative easy. Imagine someone who mainly uses his PC for GNS3 (that's me :-). He boots his PC and then starts GNS3. As on Unix the PIDs start at one upon boot, the PIDs of a freshly booted system are within a small range. So it's not that unlikely that the PID of the previous running GNS3 GUI is used again for some process. It might again be the GNS3 GUI, but it can be also some other program.

**Comment by noplay** [comment]
Right

**Comment by ehlers** [comment]
Just a simple idea: What about storing gns3_gui.pid in /var/run (on sane OSes). Those directories got deleted on boot, that will solve it in my scenario. Don't know if Windows has such a directory.

**Comment by noplay** [comment]
It's work only for linux.

**Comment by noplay** [comment]
Usually programs update the date of last modification of the file and check if the program has change recently.
