### ISSUE TITLE
When two IOU devices are cabled back-to-back applying a capture crashes one of the IOU devices

### ISSUE THREAD

**Issue by Vic563** [GNS3/gns3-gui#905]
Hello,
   When two IOU devices are cabled back-to-back applying a capture crashes one of the IOU devices and I need to restart the IOU device that went down. Can you please look into this issue. Thank you

**Comment by grossmj** [comment]
What version of GNS3 have you used?

**Comment by Vic563** [comment]
I am using GNS3 version 1.4.0rc2

**Comment by grossmj** [comment]
If you are using Linux, make sure that the latest iouyap version is installed

```
$ iouyap -V
iouyap version 0.97.0
```

If not, follow these instructions: https://github.com/GNS3/iouyap#installation-on-linux-debian-based

**Comment by Vic563** [comment]
I just updated the iouyap version on the GNS3 VM from version 0.96.0 to version 0.97.0 and now when I set the capture the IOU nodes do not crash. Thank you.

**Comment by noplay** [comment]
Thanks for feedback
