### ISSUE TITLE
Devices still showing on the 'end device' Dock though deleted from Vbox VM templates

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#907]
Deleted all VirtualBox VM templates from preference, but they still showing on the end-host dock even after restarting GNS3.

![image](https://cloud.githubusercontent.com/assets/1716020/12136493/954fb7b6-b448-11e5-851e-0d038859f7fd.png)

**Comment by noplay** [comment]
With which version of GNS3?

**Comment by AJNOURI** [comment]
Running GNS3 version 1.3.13 on Linux (64-bit) with Python 3.4.3 Qt 4.8.6.

**Comment by noplay** [comment]
Do you have the bug with 1.4.0?

**Comment by grossmj** [comment]
Well, this is normal. You have Qemu VMs.

VPCS, Cloud and Host are always present and cannot be deleted.
