### ISSUE TITLE
GNS3 starting GNS3 VM problem

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#912]
Is it possible/wise to allow the user to modify GNS3 preferences without GNS3 starting the GNS3 VM listed in preferences?  It seems to me if a user modification to an GNS3 ini files occurs resulting in an invalid reference to the GNS3 VM or a modification to GNS3 preferences occurs while a GNS3 VM is defined in preferences, then GNS3 application will try to start/restart the GNS3 VM and a GNS3 application crash occurs if there are invalid values defined in preferences. 
Hope this rambling question makes sense.

**Comment by noplay** [comment]
If I correctly resume. You are annoy by the fact GNS3 start the VM with GNS3 and if a settings for the VM is broke you can't open the settings.

It will be better to start the VM only when dropping the first node requiring the VM.

**Comment by jtorri** [comment]
As usual I did not explain well.  I'll try to do better.  Install GNS3.  Configure it to use GNS3 VM rather than local server.  Configure preferences and load images and close GNS3.  Start GNS3 again and it starts the GNS3 VM "automatically".  Now go to preferences and change a setting associated with the GNS3 VM then click on "Apply" button.  GNS3 will at that moment try to start another instance of the GNS3 VM and when it does GNS3 is now locked and must be forced to shutdown.  So, why not have an option when GNS3 starts to NOT start the GNS3 VM at the same time?

**Comment by jtorri** [comment]
And, as always, thanks!

**Comment by grossmj** [comment]
I would have swear there was an option to not automatically start the GNS3 VM even if it is activated in the preferences. Anyway, makes sense to have this.

**Comment by noplay** [comment]
Perhaps the starting the GNS3 VM dialog box could have a count down. When the count down expire the VM really start and the cancel button disapear.

**Comment by jtorri** [comment]
Thanks for looking into this.

**Comment by grossmj** [comment]
This is a bit more work than anticipated and this will have to wait for version 1.4.2.

I like the countdown idea + we could also add an option to start the GNS3 VM on demand when dropping a node that uses it.

**Comment by grossmj** [comment]
@noplay do you want to have a go at the count down idea?

**Comment by noplay** [comment]
PR in progress ;)

**Comment by grossmj** [comment]
The last PR allow to stop a running vmrun or VBoxManage process. Would be nice to also have a countdown before the process is actually started.

**Comment by ehlers** [comment]
I see the use case for this countdown, but that's mainly necessary during the initial setup phase of GNS3.

In the daily use of GNS3 after all is configured, I slowly got annoyed by this additional delay. Today I finally reverted your change in my local installation.

So maybe there is a way of having this delay only in the setup phase of GNS3?

**Comment by noplay** [comment]
I'm using it when I want to use only dynamips. Perhaps we should made it optionnal in the VM preferences. What do you think Jeremy?
