### ISSUE TITLE
Bug: Remote SSH Server

### ISSUE THREAD

**Issue by kingfetty** [GNS3/gns3-gui#919]
The Setup:

Remote server running in ESXI already booted.  Remote server IP is 192.168.99.9
GNS3 GUI installed on local subnet with IP 192.168.1.4

The failure:

The GNS3 gui connects and authenticates to the remote server fine and instantiates the port forward from Local-127.0.0.1:1000 to remote 127.0.0.1:8000.  When the GNS3 gui attempts to access the remote server it attempts to still access 192.168.99.9 IP address but using the local port.  I would suspect they put in the wrong variable name in the code and used the real IP instead of the local loopback.  

The Proof:

Connection to ssh://gns3@192.168.99.9:22:8000
SSH connection to ssh://gns3@192.168.99.9:22:8000 with key 
starting thread (client mode): 0xcf91f60
Connected (version 2.0, client OpenSSH_6.6.1p1)

Authentication (publickey) successful!
Creating ID: local 127.0.0.1:1000 for remote 127.0.0.1:8000 - Starting server thread
Thread-3: local 127.0.0.1:1000 for remote 127.0.0.1:8000 - Server thread running
GET http://192.168.99.9:1000/v1/version {}
Response error: Connection refused (error: 1)

As you can see the GET HTTP:// is refering to to the remote IP instead of the local loopback.  This needs to be fixed to hardcoded 127.0.0.1 in the case of SSH connection type.

**Comment by noplay** [comment]
Thanks for the report

**Comment by noplay** [comment]
Thanks for the report it will be in next release and in tomorrow nightly build
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/

**Comment by kingfetty** [comment]
Still not fixed in the nightly builds.

**Comment by noplay** [comment]
Did you try with 1.4 nightly ? It's not merged on the 1.5 branch.

**Comment by kingfetty** [comment]
There's no 1.4 branch listed, only 1.3 and 1.5

**Comment by noplay** [comment]
Your are right .

I fix the build nightly for the 1.4

Thanks a lot for the help.
