### ISSUE TITLE
interface labels disappear

### ISSUE THREAD

**Issue by digininja** [GNS3/gns3-gui#92]
I've got the "show interface labels" turned on but after save, close down and restart the option is off and I have to turn it back on again.

**Comment by Raizo62** [comment]
Yes, it'will be nice if we have an default value for "show interface labels" for new project defined into GNS3's configuration.
And each lab will save the value of "show interface labels" used

**Comment by rashoodkhan** [comment]
@grossmj - I can try fixing this issue. I think it has something to with saving the settings and retrieving it back?

**Comment by grossmj** [comment]
Hey Rashid,

Yep, the state of uiShowPortNamesAction.isChecked() in the MainWindow class should be saved in the topology (project) files. This should be implemented in the Topology class.

This shouldn't be complicated I think.

Thanks,

**Comment by ziajka** [comment]
@grossmj Has been fixed with: https://github.com/GNS3/gns3-gui/issues/712

**Comment by grossmj** [comment]
Hum, that's what I thought :)
