### ISSUE TITLE
[1.4.0] Fails to find qemu-system-x86_64 even though it's there

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#921]
Could not find /usr/local/bin/qemu-system-x86_64 in the Qemu binaries list
Could not find /usr/local/bin/qemu-system-x86_64 in the Qemu binaries list
Could not find /usr/local/bin/qemu-system-x86_64 in the Qemu binaries list

Even though:
root@kvm-ubuntu-gns3:/home/ubuntu/Shared-Folders# which qemu-system-x86_64
/usr/bin/qemu-system-x86_64
root@kvm-ubuntu-gns3:/home/ubuntu/Shared-Folders# env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/ubuntu/JDK/jdk1.8.0_65/bin

GNS3 looks into /usr/local/bin instead of using the PATH.

**Comment by noplay** [comment]
It's an old topology or a node  already existing in your GNS3? The path is not hardcoded but it's save.

I think if it's that we can fix it by allowing you to choose the binary instead of just flushing the list.

**Comment by jean-christophe-manciot** [comment]
Yes, there is an entry "qemu_path": "/usr/local/bin/qemu-system-x86_64" in the topology file which has been copied to another host where the qemu binaries are located in /usr/bin.

**Comment by noplay** [comment]
@grossmj what do you think? It's work as designed... But it's annoying when you move from a computer to another.

**Comment by jean-christophe-manciot** [comment]
How about checking the result of the call & looking for alternate locations from the path if the first call is unsuccessful?

**Comment by grossmj** [comment]
Currently we save the absolute Qemu path in the topology file. I guess it would make sense to look for an alternative if that path cannot be found.

Another way could be to only save the binary name and always do a lookup when loading a project however I am afraid of side effects, especially if you have different version of Qemu installed.

**Comment by jean-christophe-manciot** [comment]
Both solutions seem OK; can't you test the qemu --version when there are multiple qemu binaries and keep the most recent one?

**Comment by noplay** [comment]
The issue with that is some people want to use qemu 0.10 for ASA 8...

**Comment by jean-christophe-manciot** [comment]
That's a very small percentage of GNS3 users.... anyway, have you tried the "Precompiled Windows versions (1.4.0), provided by Prashant Satish" with the link on the official qemu wiki: http://wiki.qemu.org/Links. Maybe you could ship it with the Windows all-in-one version. I have no clue what versions are in it, I haven't been using it for years.

**Comment by noplay** [comment]
You are right ASA 8 is a small part and we push them to ASAv we can ignore this use case.

We could replace by just the binary name. So GNS3 will look into the $PATH in order to choose the best qemu.  It's not a big change.

**Comment by grossmj** [comment]
Should we store the version of Qemu along with the path? That way we can try to match it when looking into $PATH and there are multiple Qemu installed.

**Comment by jean-christophe-manciot** [comment]
If you do that, you won't use the latest if there is a newer version installed since the topology file has been saved.

**Comment by grossmj** [comment]
Got point and it creates to much complexity.

**Comment by jean-christophe-manciot** [comment]
Always using the latest version is too much complexity?

**Comment by grossmj** [comment]
Nope, storing the version number and trying to match it with an installed Qemu binary ;)

**Comment by jean-christophe-manciot** [comment]
I have never experienced issues with qemu and I've been using it for quite some time with many different types of VMs.

**Comment by jean-christophe-manciot** [comment]
OK, we posted at the same time, with yours a few ms ahead :)

**Comment by noplay** [comment]
The only problem with qemu is Windows for example 2.5 is broken on Windows 64 bit. But if user installed it, probably he know what is doing.

**Comment by grossmj** [comment]
Ok, to summarize here is what I propose:

* Check that the Qemu path exists.
* Use it if it exists.
* Look for an alternate path if it doesn't.
* If multiple Qemu binaries are found in $PATH, then use Qemu --version to find the most recent version and use this (doesn't work on Windows)

**Comment by jean-christophe-manciot** [comment]
This sounds about right; I'm not sure what you mean by "alternate path", maybe the usual /usr/bin & /usr/local/bin + maybe /bin?
Also, the last bullet should also be applied to third bullet IMHO.

**Comment by noplay** [comment]
Ok I check and we already manage this for recent topologies (1.4.0 and later).

If we provide a platform in the topology the code will fallback and found a corresponding qemu via which.


The fallback code:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/qemu/qemu_vm.py#L82

The setter of platform:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/qemu/qemu_vm.py#L192

The search binary:
https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/qemu/qemu_vm.py#L147

I will improve that

**Comment by noplay** [comment]
https://github.com/GNS3/gns3-server/commit/889ea1497329cbac9ab1cb942ab6c03862177787

**Comment by noplay** [comment]
It's auto choose based on the path. 

I try to to use the --version but it's impact most code than expected since the code is asynchronous and where we set the qemu path is not asynchronous (it's in a constructor)

**Comment by jean-christophe-manciot** [comment]
I don't understand the last part.

**Comment by noplay** [comment]
Ok seen with jeremy add the --version create too much impact for only few users. We just support searching another bin in the path using path priority of the system.
