### ISSUE TITLE
1.4.0 vmware vm can`t stop!

### ISSUE THREAD

**Issue by qianxideyu** [GNS3/gns3-gui#922]
1.4.0 vmware vm can`t stop! on windows platform，when I add the vm of the vmware,it can`t stop.I must end process of vm,it will stop! this bug in 1.4RC3 solved ，bug in GSN3 1.4.0  version appeared again！

**Comment by noplay** [comment]
It's the GNS3 VM or a VM added in the topology?

**Comment by qianxideyu** [comment]
add a  VM in the topology,not GNS3 VM!

**Comment by noplay** [comment]
Do you always have the issue or only sometimes?

**Comment by grossmj** [comment]
@qianxideyu we need more details otherwise we cannot fix this problem. Do you have this problem with any VM, have you tried to tick the ACPI shutdown option?

**Comment by grossmj** [comment]
No news... closing it.
