### ISSUE TITLE
cannot close virtualbox device normally

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#926]
Onec close the virtualbox device, it will failed and the GNS3 console shows like below and cannot be connected anymore by double click:
Server error from http://192.168.202.1:8000: TinyCore6.4-1: VirtualBox has returned an error: VBoxManage.exe: error: The machine 'TinyCore6.4-1' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

**Comment by noplay** [comment]
With which version of VirtualBox?

**Comment by superwolfboy** [comment]
OS:Win10
GNS3 1.4.0 
VirtualBox:5.0.12 r104815
Thank you

**Comment by noplay** [comment]
Do you have this problem each time?

**Comment by grossmj** [comment]
Are you editing anything from VirtualBox GUI at the same time?

**Comment by superwolfboy** [comment]
Do you have this problem each time? Almost 90% maybe my computer is slow?
Are you editing anything from VirtualBox GUI at the same time? didn't

**Comment by superwolfboy** [comment]
I fould the problem 
I should check in the "enable ACPI shutdown"
the virtualbox instance is tinycore....
sorry for this.

**Comment by noplay** [comment]
Thanks for the information
