### ISSUE TITLE
AVG broke GNS3 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#928]
This problem generate too much report we need to found a way to better inform the user:
https://gns3.com/discussions/could-not-connect-to-127-0-0-1-6

**Comment by superwolfboy** [comment]
I have this issue also and I found that when this happen , the taskmanager can see two gns3.exe. I think one of them is what I closed last time but did not close complete, Onec force close them and reopen gns3 it would be working normally.
.

**Comment by noplay** [comment]
I made full test sessions.

With AVG installed GNS3 doesn't work. If you uninstall AVG it's work. Even if you turn off AVG the problem still exists.

**Comment by noplay** [comment]
AVG conflict with CYGWIN:
http://stackoverflow.com/questions/25604510/encounter-fatal-error-ntcreateeventlock-0xc0000077-when-execute-kinit-in

You need to whitelist dynamips.exe

**Comment by grossmj** [comment]
In 1.4 we add entries to the Windows firewall. Just by curiosity, would it be possible to do something similar for AVG?

**Comment by noplay** [comment]
We can whitelist stuff:
http://www.avg.com/fr-fr/whitelist

But the problem is not a false positive but a crash when AVG watch the dynamips process ...

**Comment by noplay** [comment]
It seem to be an old bug in AVG and nobody care to fix it. It will be solved by #929
