### ISSUE TITLE
User with VMware player can't run the GNS3 VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#949]
It seem a common trouble:
https://gns3.com/qa/could-not-execute-vmrun-comman-2

**Comment by noplay** [comment]
It could be nice to capture the ouput  and show it to the user.

Perhaps we need to allow only VMware Workstation 12 Player.

**Comment by noplay** [comment]
https://gns3.com/qa/gns3-1-4-vm-could-not-execute-vm

**Comment by noplay** [comment]
It seem the detection player / workstation is not reliable.

**Comment by grossmj** [comment]
That may be the issue: https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/vmware/__init__.py#L134

That worked before VMware renamed Player to Workstation Player ;)

**Comment by noplay** [comment]
Yes probably

**Comment by grossmj** [comment]
Upgrading the VIX library fixes the problem.
