### ISSUE TITLE
[Feature Request] - Option to have "other providers" for the cloud offering.

### ISSUE THREAD

**Issue by lachlanjholmes** [GNS3/gns3-gui#95]
Hey all,

I'm not sure if this is on the road map but I was thinking about it recently.

It would be cool to have a drop down in the cloud section to select "other provider" and you could input your own label for the it. I was thinking along the lines of using Digital Ocean Droplets or Other VPS providers out there to perform the GNS3-Server work.

I'm still not sure how/when the current cloud settings option will be working for rackspace, but adding the option to add another would be really cool.

:smile:

**Comment by grossmj** [comment]
Something for way down the road ;) We still have to release something that work with our first provider.

**Comment by noplay** [comment]
Now we  have generic instruction that could work on any cloud provider:
https://gns3.com/support/docs/install-on-a-remote-server
