### ISSUE TITLE
Once select qemu 0.11 for ASA 8.4(2) or vios, the gui console will show error message

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#950]
Win10
GNS3 1.4.0 (GUI)
The message shows like below:

![qq 20160122234515](https://cloud.githubusercontent.com/assets/9411604/12515227/495d351e-c162-11e5-8e92-a0a78f4ea0bc.png)

**Comment by grossmj** [comment]
This bug must have been introduced in one of the latest PR.

**Comment by noplay** [comment]
It's fixed in dev. Thanks
