### ISSUE TITLE
[Linux/1.4.0] VNC console type makes the node crash

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#951]
***Configuration***: 
- console type: vnc
- port number: 5900
- command call for TightVNC: java -jar ~/tvnjviewer-2.7.2-bin/tightvnc-jviewer.jar %h:%p

The login window is correctly displayed; after login, the node behaves very strangely, reboots, and crashes.

Launching the node from outside of GNS3 with virt-manager, I have no issue whatsoever with the same node image and same TightVNC command. After login, the window/node have no issue.

The only differences come from the options used with **qemu-system-x86_64**; 
***With GNS3***:
/usr/local/bin/qemu-system-x86_64 -name Ubuntu-Gnome-Server-15.10-1 -m 512M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/actionmystique/Program-Files/Labs/GNS3/71cf359a-f59e-42f8-a5c5-9137d60110c9/project-files/qemu/2830ca8c-9f8e-4513-ab2c-ab67a5a440fe/hda_disk.qcow2,if=virtio,index=0,media=disk **-vnc 127.0.0.1:0 -monitor tcp:127.0.0.1:45031,server,nowait** -net none -device virtio-net-pci,mac=00:00:ab:40:fe:00 -device virtio-net-pci,mac=00:00:ab:40:fe:01 -device virtio-net-pci,mac=00:00:ab:40:fe:02 -nographic 

***With virt-manager***  (some options are N/A in the comparison):
qemu-system-x86_64 -enable-kvm -name KVM-Ubuntu-Gnome-Server-15.10-VNC -S -machine pc-i440fx-2.4,accel=kvm,usb=off,vmport=off -cpu host -m 8192 -realtime mlock=off -smp 2,maxcpus=4,sockets=4,cores=1,threads=1 -uuid a7c60316-5975-49e0-b520-17147e86879a -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-KVM-Ubuntu-Gnome-Server-15.10-VNC/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x8.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x8 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x8.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x8.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x7 -drive file=/media/actionmystique/SAMSUNG-Ext4-1/KVM-Qemu/VMs/KVM-Ubuntu-Gnome-Server-15.10.qcow2,format=qcow2,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x9,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=23,id=hostnet0,vhost=on,vhostfd=24 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:e4:80:a9,bus=pci.0,addr=0x3 -netdev tap,fd=25,id=hostnet1,vhost=on,vhostfd=26 -device virtio-net-pci,netdev=hostnet1,id=net1,mac=52:54:00:d6:29:0f,bus=pci.0,addr=0x4 -netdev tap,fd=27,id=hostnet2,vhost=on,vhostfd=28 -device virtio-net-pci,netdev=hostnet2,id=net2,mac=52:54:00:38:12:1c,bus=pci.0,addr=0x5 **-chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0 -vnc 127.0.0.1:0 -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vgamem_mb=16,bus=pci.0,addr=0x2** -device intel-hda,id=sound0,bus=pci.0,addr=0x6 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0xa -msg timestamp=on 

I have bolded the options which are potentially meaningful in this situation.

**Comment by noplay** [comment]
Hi,

Thanks for the informations.

Do you have the same issue when using the qemu from your distribution?

Did you report the problem to Qemu? For me it's seem more an issue from their side. At least if the options are invalid it should show an error.

**Comment by jean-christophe-manciot** [comment]
It's not a qemu issue;

**Comment by noplay** [comment]
If you run the first command in a terminal what is the output?

**Comment by grossmj** [comment]
I remember a similar strange problem with a Telnet console program a few months ago. Passing the environment variables when executing it ended up solving that issue. Maybe this is the same thing.

**Comment by jean-christophe-manciot** [comment]
If that can help, when typing the command inside a terminal:

root@samsung-ubuntu:/tmp# qemu-system-x86_64 /usr/local/bin/qemu-system-x86_64 -name Ubuntu-Gnome-Server-15.10-1 -m 512M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/actionmystique/Program-Files/Labs/GNS3/f277e3db-3bdc-4c2b-92e0-80ca496839c1/project-files/qemu/471364c6-8470-45e1-ad65-db915bd401da/hda_disk.qcow2,if=virtio,index=0,media=disk -vnc 127.0.0.1:0 -monitor tcp:127.0.0.1:60790,server,nowait -net none -device virtio-net-pci,mac=00:00:ab:01:da:00 -device virtio-net-pci,mac=00:00:ab:01:da:01 -device virtio-net-pci,mac=00:00:ab:01:da:02 -nographic
qemu-system-x86_64: -nographic: **Could not open '/usr/local/bin/qemu-system-x86_64': Text file busy**

Without the option -nographic, I get the same error.
