### ISSUE TITLE
qemu 0.13 with ASA8.4(2) problem.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#953]
Win10 with GNS3 1.4.0
When I use qemu 0.13 to run asa 8.4(2),
1, if this asa was without any connection, it would be running.
2, but if this asa connect with a ehternet switch (inside of GNS3), it would not run and show error message:

GNS3 management console.
Running GNS3 version 1.4.0 on Windows (64-bit) with Python 3.4.3 Qt 5.5.1.
Copyright (c) 2006-2016 GNS3 Technologies.

=> Error: QEMU process has stopped, return code: 1
Start QEMU with 'C:\Program Files\GNS3\qemu-0.13.0\qemu-system-i386w.exe' -name ASA842-Local-1 -m 512M -smp cpus=1 -boot order=c -drive 'file=C:\Users\Administrator\Desktop\2dd72512-1ed8-48ac-a4ff-2e0000705d9a\project-files\qemu\393a2502-f68c-4406-88d8-dee7d6e19076\hda_disk.qcow2,if=ide,index=0,media=disk' -initrd D:/VPC/IOS/QEMU/ASA-842/asa842-initrd.gz -kernel D:/VPC/IOS/QEMU/ASA-842/asa842-vmlinuz -append 'ide_generic.probe_mask=0x01 ide_core.chs=0.0:980,16,32 auto nousb console=ttyS0,9600 bigphysarea=65536 ide1=noprobe no-hlt -net nic' -serial telnet:0.0.0.0:2001,server,nowait -monitor tcp:127.0.0.1:50401,server,nowait -net none -device e1000,mac=00:00:ab:90:76:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=192.168.202.1:10000,localaddr=192.168.202.1:10001 -device e1000,mac=00:00:ab:90:76:01 -device e1000,mac=00:00:ab:90:76:02 -device e1000,mac=00:00:ab:90:76:03 -icount 2 -hdachs 980,16,32 -nographic

Execution log:

Error: QEMU process has stopped, return code: 1

By the way, for asa 8.4(2), qemu 0.13 should be faster than 2.4, so I use it for running asa 8.4(2) on low proformance PC.
use 2.4 have no this problem.

**Comment by noplay** [comment]
More issues with ASA 8 :(. It seem qemu 0.13 crash on most Windows 10.

We will display a warning when dropping a ASA node in the topology, asking people to use ASAv instead because it's supported by Cisco.

Test on different computer give different results :( Even test on same computer give different result depending of the load of the system.

**Comment by noplay** [comment]
We show a warning when using ASA 8 now. We have no way to make the support reliable because issues are in the kernel from CISCO. And since CISCO as an official solution with ASAv we can promote this solution.

**Comment by superwolfboy** [comment]
gotta and thank you
