### ISSUE TITLE
Multiple links between devices and the interface labels shifts

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#954]
See https://gns3.com/qa/bug-multiple-links-between-devic

Tested it with GNS3 version 1.4.0 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.
* create new empty project
* add two 3725 router
* connect both interface of R1 to R2
* rearrange interface labels
* save project<br>![test1](https://cloud.githubusercontent.com/assets/896406/12539280/52980b3e-c2ef-11e5-8dfa-bebcd83345f0.png)
* reopen project<br>![test2](https://cloud.githubusercontent.com/assets/896406/12539283/5dc596ca-c2ef-11e5-8c25-886adbd1e2de.png)

The position of the interface labels of fa0/0 are correct, but the interface labels of fa0/1 are on a different position after a re-open.

**Comment by noplay** [comment]
I confirm it's easy to reproduce.

Thanks !

**Comment by noplay** [comment]
It's when the topology is saved the position of the label is incorrect.

**Comment by noplay** [comment]
The label is a NoteItem

**Comment by noplay** [comment]
Strange discovery if you modify the file by hand the label will keep the position. It's something in the move label code.

**Comment by noplay** [comment]
I finally isolate something. Save the topology.

Reopen it and save it
source_port_label and destination_port_label are inverted

**Comment by noplay** [comment]
I start to have an headache on this bug :(

**Comment by ehlers** [comment]
Maybe you can declare it as a feature :smiley:

**Comment by noplay** [comment]
My two cents that the problem is here:
https://github.com/GNS3/gns3-gui/blob/master/gns3/graphics_view.py#L296

**Comment by noplay** [comment]
I will make a PR :dancer:
