### ISSUE TITLE
Two ASA's refuse to start when a link is added.

### ISSUE THREAD

**Issue by ovidiucs** [GNS3/gns3-gui#96]
Hi, 

When adding two ASA's they boot just fine.But if I add a link from ASA 1 to ASA 2 and save the project, close the program and then reopen the project. they refuse to start, even though GNS3 tells me they're running.

**Comment by grossmj** [comment]
Hi,

Have you checked the "legacy networking option" and are your on Windows?

Thanks,

**Comment by grossmj** [comment]
Assumed this is fixed since Sep 2014.

**Comment by ovidiucs** [comment]
Sorry for the late reply. Yeah it seems they work just fine now. Thanks.
