### ISSUE TITLE
Keep dynamips nvram file?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#962]
For saving disk space we delete nvram file. But it's generate a lot of confusion. Perhaps we should only delete ghost image and keep the NVRAM.

**Comment by noplay** [comment]
What did you think @grossmj ?

**Comment by grossmj** [comment]
The only time NVRAM files should be deleted is if the option "Automatically delete NVRAMs and disk files" is enabled and you close the project/vm https://github.com/GNS3/gns3-server/blob/master/gns3server/modules/dynamips/nodes/router.py#L361

**Comment by grossmj** [comment]
This option is supposed to be disabled by default.

**Comment by noplay** [comment]
At the end what we  decide ?

**Comment by grossmj** [comment]
Well for conversions we assume users want to keep NVRAMs and disk files. The rest we don't do anything, users should use an EtherSwitch node if they want to have VLANs.

**Comment by noplay** [comment]
Ok it's current behavior
