### ISSUE TITLE
SSH still available on the remote server dialog

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#968]
GNS3 version 1.4.1dev2 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.

Even after removing SSH support, it's still in the remote server dialog (Protocol, SSH port, SSH key)
![remote_server_ssh](https://cloud.githubusercontent.com/assets/896406/12617801/8abe4630-c511-11e5-9359-4e6dfc7593fd.png)

**Comment by noplay** [comment]
Good catch it seem to have been reintroduce by: 8f776974824d83b8f20cebaf661c4becc25aade3
