### ISSUE TITLE
Allow user to choose Player instead of workstation

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#970]
It seem on linux the path of vmrun doesn't give clue about if it's player or workstation:
https://gns3.com/qa/gns3-v-1-4-fail

**Comment by noplay** [comment]
What did you think @grossmj ?

**Comment by ehlers** [comment]
I don't get the problem. The VMware preference has already the host type field to set player or workstation. I'm using VMware player without problems on Linux. But I have to admit, that I don't use the GNS3 VM (why should I on Linux), so I don't know if there are some problems with VMware and GNS3 VM.

Here the screenshot of my Linux installation:
![vmware_type](https://cloud.githubusercontent.com/assets/896406/12677158/50834696-c697-11e5-9764-ad93fc3e89a7.png)

**Comment by payomagic** [comment]
@ehlers - to run VM on linux for use of e.g. IOU...

**Comment by ehlers** [comment]
You don't need the VM to run IOU, linux can run them natively when you install iouyap.
The GNS3 VM is just a linux system, so all you can run in this VM can also run in your local linux. You "just" may have to install additional software, that's already included in the VM.

**Comment by ehlers** [comment]
Back to the host type:

Maybe you can try to auto detect the host type on linux. If shutil.which('vmware') finds a program, then it's workstation, if shutil.which('vmplayer') finds something it's a player. But we should keep the possibility to manually override the type.

**Comment by noplay** [comment]
I think the problem is the first install wizard.

By the way the VM is easier for IOU on non debian system due to the weird dependencies.

**Comment by grossmj** [comment]
I've added a small improvement but still don't see how some users can have a problem. We should ask them what they have for ```vmware -v``` or if vmplayer exists. It is possible they have installed both Workstation and Player too.

**Comment by noplay** [comment]
I tested installing the last vmware player and only the vmplayer command exists. Perhaps we should use the command vmplayer if available before trying vmware.

**Comment by grossmj** [comment]
Interesting finding today. Upgrading from Player to Workstation leaves workstation in a folder named "VMware Player".

![player_upgrade](https://cloud.githubusercontent.com/assets/4752614/12802940/b7d9ae42-caa3-11e5-9938-27163af53aa2.png)

**Comment by noplay** [comment]
No comment....

**Comment by noplay** [comment]
I posted on forum asking people to test the Nightly build:
https://gns3.com/discussions/for-people-with-vmrun-issues

**Comment by noplay** [comment]
We still have complaints

**Comment by grossmj** [comment]
I think complaints are more something regarding VMware install problems / bugs with vmrun or the VIX library.

**Comment by grossmj** [comment]
Stricter checks regarding the VIX library version: https://github.com/GNS3/gns3-server/commit/b408f297264ffe418438878fbef62b31f65cb67d
