### ISSUE TITLE
gns3 process doesn't stop

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#971]
Just ran into an issue I believe had been fixed in a prior build. I exited out of gns3, the VM shutdown and GNS3 gui closed. I started gns3 back up, but I got an error from GNS3 saying it was unable to communicate with the VM, to check firewall settings. After checking and pinging the address in question without issue, and having remember a similar symptom in the past, I checked the running process. Despite the fact I had exited twice without any error, there were still two running GNS3 processes. After forcing the running process to close and starting GNS3, the error no longer populated and everything works fine. 

*After further trial, the issue is repeatable. I'm attaching a screenshot. 

![image](https://cloud.githubusercontent.com/assets/6335629/12692629/ceba612c-c6c7-11e5-9443-25a8a5ed8b69.png)

Fresh 1.4 build, W10, MVWare GNS3 VM,  fresh config. 

Windows 10 build 10586.71
VMware Workstation 12.1.0 3272444
GNS3 1.4.0

**Comment by noplay** [comment]
I think it's fixe in 1.4.1 we fixed stuff releated to duplicate process detection

**Comment by noplay** [comment]
Let's check if the problem is back in 1.4.2

**Comment by codeassassin** [comment]
Just FYI, issue is still present in 1.4.1

**Comment by noplay** [comment]
Ok after inspection it seem the gns3.exe it still running in background. The problem is not with the gns3 server but with gns3 gui.
