### ISSUE TITLE
Explain the differences between server in the setup wizard

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#977]
Suggestion from Andrew:
In the setup wizard, the user is presented with the "remote server/GNS3-VM or local server" option, without any explanation what the difference is. Experienced users would be OK, but new users would be a little confused.

**Comment by noplay** [comment]
I propose this change:
![capture d ecran 2016-02-03 a 19 26 41](https://cloud.githubusercontent.com/assets/345437/12792429/16c67f4a-caac-11e5-9feb-f639f8b20e68.png)

**Comment by grossmj** [comment]
Like it, I would just change "the emulator" by "Qemu" or "the VM" or "the Qemu VM" ;)
