### ISSUE TITLE
Put a link for the GNS3 VM in the setup wizard

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#978]
Suggestion from Andrew:
2) It would be nice to have a link on the next screen, to take them to the GNS3-VM download page. Currently, it just says you need the .ova installed, and then just an error saying it's not installed. There's not a link to the GNS3-VM that I could find on the website, either. Or maybe an option during inital installation asking "Would you like to download the GNS3-VM .ova? Please select VMware or Virtualbox version".

**Comment by grossmj** [comment]
Would be nice with have some intelligence behind this, with the link to the GNS3 VM corresponding to the running GNS3 version.
