### ISSUE TITLE
Replace temporary project by default project

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#982]
In order to simplify the code we drop the temporary project and we open the same default project everytime.

**Comment by noplay** [comment]
I see an issue with multi user environnement where people will conflict.

Perhaps the best solution is no project opened at startup by default. After all when you opened an IDE you need to choose a project name. Their is no magical project.

**Comment by noplay** [comment]
What do you think jeremy?

**Comment by grossmj** [comment]
I know last time I tried to remove the temporary project I got complaints ;) We should try to find an elegant solution.
