### ISSUE TITLE
problem with " in lab's name

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#987]
Hi

On linux, i create a lab with project's name : guillemet"45

When i add an ethernet switch, I have this error message : 
Server error from http://127.0.0.1:8000! SW1: Parse error: unexpected quote

**Comment by noplay** [comment]
I will check this

**Comment by noplay** [comment]
It seem to be a dynamips limitation even when escaping the quote I got this error.

**Comment by noplay** [comment]
I dissallow quote in project name
