### ISSUE TITLE
Drawing lines

### ISSUE THREAD

**Issue by jcalano** [GNS3/gns3-gui#997]
I think this falls under the caption, "Nice to Have."  I have been developing Cisco routing and switching laps in GNS3 for which drawing lines would be very helpful.  I am currently using the "draw a rectangle" feature and am collapsing the box so it looks like a line, which works okay but makes it difficult to move around the screen easily.  Below is a screen shot of Lab 2-1 EIGRP Load Balancing  I recently completed that shows a few lines.
![screenshot](https://cloud.githubusercontent.com/assets/9361647/12836154/74b90092-cb73-11e5-82ae-2c312caaa411.png)

Thanks,

Jim

**Comment by noplay** [comment]
Tagged as enhancement not sure when we will add it.

**Comment by grossmj** [comment]
PR merged.

**Comment by jcalano** [comment]
Yay!  it's working.  thank you!
